### ISSUE TITLE
[Flow] - type the pause actions + reducer

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1004]
We currently type the sources and breakpoints reducers. It would be great to give the same treatment to pausing.

Here's an initial [patch](https://gist.github.com/jasonLaster/48a09ff185f13ec7fa0da30298a8603e). Run this command on a new branch to get started:

```
curl https://gist.githubusercontent.com/jasonLaster/48a09ff185f13ec7fa0da30298a8603e/raw/b740cc5ee55a698445ba5b19b5fc8cb0c77b1127/foo.diff | git apply
```

**how do i run flow?** `flow`

**how do i see a module's coverage?**  `flow coverage --color public/js/utils/source-map-worker.js` or `npm run flow-coverage`

**Comment by montogeek** [comment]
Colorized diff https://gist.github.com/jasonLaster/48a09ff185f13ec7fa0da30298a8603e
