### ISSUE TITLE
[Flow] Type the Source Map Worker

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1005]
The [source map worker](https://github.com/devtools-html/debugger.html/blob/master/public/js/utils/source-map-worker.js) handles some of the most complicated logic in the debugger. It would really help to type the module for clarity and refactoring confidence.

Here is the module's [report card](http://jasonlaster.github.io/debugger-flow-report/sourcefiles/public/js/utils/source-map-worker.js.html).

**how do i run flow?** `flow`

**how do i see a module's coverage?** `npm run flow-coverage`

**Comment by sankha93** [comment]
I am working on this.

**Comment by wldcordeiro** [comment]
Thanks @sankha93 feel free to ask any questions here if you get stuck.
