### ISSUE TITLE
Investigate Conditional Breakpoints

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#101]
**User Story**

As a developer who is debugging their code I need a breakpoint that only triggers under certain scenarios such that when a certain expression is true my breakpoint will pause execution.

**Notes**

Chrome Implementation:&nbsp; [https://developer.chrome.com/devtools/docs/javascript-debugging/conditional-breakpoint-region.jpg](https://developer.chrome.com/devtools/docs/javascript-debugging/conditional-breakpoint-region.jpg)

**UX Needs**

- Button or entry point to open a small input dialog
- Input dialog that explains expression needs

- [ ] Initial button to add breakpoint

**Comment by jasonLaster** [comment]
I'll have some time later today to start working on this

**Comment by jasonLaster** [comment]
We are not going to get to this pre-london, so closing for the time being. Lets re-open when we're ready to tackle.

**Comment by jasonLaster** [comment]
Re-opening to track the work on this feature.

**Comment by wldcordeiro** [comment]
Whoa, I literally had a conversation with my coworker yesterday about some of the ideas we had for the debugger and he mentioned exactly this! Nice work on the PR so far @jasonLaster

**Comment by jasonLaster** [comment]
I added some initial conditional breakpoint design mockups [here](https://invis.io/UM8XCLNK5#/196300930_Conditional_Breakpoint_Pane_Exploration)

Notes:
* I tried to model this after the watch expressions work where there's an left prompt for adding input
* I assumed we'd be able to add a line widget which is 1.5 x a line height. This might be impossible and we'll have to adjust.
* I used a mono spaced font for the input, i'm not sure if we do that in other places but it felt better for code
* I did not include a close button, but assumed that escape would close it, although likely only when the input is in focus.


![screen shot 2016-10-12 at 1 02 21 pm](https://cloud.githubusercontent.com/assets/254562/19319683/f852de32-907b-11e6-9986-9c44fcbf046d.png)

**Comment by helenvholmes** [comment]
> - I did not include a close button, to be consistent with the search bar. Escape and enter would close the panel.
I think the search bar probably needs a close, as does this—I know automatically I would want to close it.

> - The gutter next to the panel seems very empty now. It would be interesting to explore adding something there.
My recommendation would be to extend the message into the gutter, and left-pad the guillemet until the editor begins. (That's what I would try, anyway.)

Looks really good! I like the styling decisions you've made 🎉

**Comment by jasonLaster** [comment]
> close button

Yeah, that makes a lot of sense. I think I have creator's bias, of course it works this way.

Here are some new screens. I'm not sure if you're thinking of the guillemet being in the gutter or just outside.

![screen shot 2016-10-12 at 5 50 17 pm](https://cloud.githubusercontent.com/assets/254562/19328919/17079408-90a4-11e6-9de3-f78f4bb1d742.png)
![screen shot 2016-10-12 at 5 50 08 pm](https://cloud.githubusercontent.com/assets/254562/19328920/170c493a-90a4-11e6-907b-4a393e5ccd36.png)

**Comment by helenvholmes** [comment]
I would have originally said guillemet in the editor, but I really like the second option, where it lines up with the line numbers! Let's go with that, it looks great 👌🏽

**Comment by jasonLaster** [comment]
great! Thanks @helenvholmes, do you know where i can find an official guillemet svg? alternatively I could make one, but i'm not sure about the pixel snapping business

**Comment by helenvholmes** [comment]
I'd recommend using the [unicode](http://www.fileformat.info/info/unicode/char/bb/index.htm) for it, actually: »

That way it will look correct next to whatever typeface you're using to the right of it.

**Comment by jasonLaster** [comment]
good call. Thanks

**Comment by nt1m** [comment]
@jasonLaster: it would be nice if the breakpoint icon could turn orange like in the old debugger for conditional breakpoints

**Comment by jasonLaster** [comment]
Closing this as there are now:
* conditional breakpoints are in behind a flag 
* there are some smaller implementation issues for conditional breakpoints #970 #969
