### ISSUE TITLE
Dark Theme - Breakpoint Tweaks

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#1010]
The breakpoint line coloring and remove button need color tweaking

![screenshot_20161025_234148](https://cloud.githubusercontent.com/assets/580982/19714594/b5e2e9b6-9b0c-11e6-866e-aae57dab1765.png)
![screenshot_20161025_234214](https://cloud.githubusercontent.com/assets/580982/19714595/b5f9be20-9b0c-11e6-95b5-2335c8d70d8f.png)

**Comment by helenvholmes** [comment]
Hey @wldcordeiro, I don't understand the remove button part of this issue—is that not the native checkbox element?

**Comment by wldcordeiro** [comment]
I copied this from @jasonLaster's description so I'm not sure either. It might be the `x` for the close button is blending into the background

**Comment by helenvholmes** [comment]
@wldcordeiro ohhhhh, okay, good show i'll make sure to make that change too
