### ISSUE TITLE
Source Tabs - Change the Hidden Dropdown buttun

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1015]
We should update the "hidden sources" dropdown button to be consistent with other tools.

The new button will be a guillemet, which is just unicode: »

#### Current UI

![screen shot 2016-10-26 at 12 29 24 pm](https://cloud.githubusercontent.com/assets/254562/19734911/751c64d2-9b77-11e6-891a-013ec597b248.png)

#### New button designs (guillmet)

![screen shot 2016-10-26 at 12 27 51 pm](https://cloud.githubusercontent.com/assets/254562/19734922/7c1641f4-9b77-11e6-9d66-cb6d6e5e549b.png)

**Comment by helenvholmes** [comment]
You can use the guillemet for this—"»".

**Comment by AbhiGulati** [comment]
I would like to work on this.

**Comment by wldcordeiro** [comment]
Thanks for this @AbhiGulati 👍
