### ISSUE TITLE
(dark theme) Debug page's colors

### ISSUE THREAD

**Issue by helenvholmes** [devtools-html/debugger.html#1027]
The colors on the debug page are making it hard to read the type in the left sidebar.

<img width="1138" alt="screen shot 2016-10-27 at 9 42 58 am" src="https://cloud.githubusercontent.com/assets/1720093/19770173/4e9a65a6-9c2c-11e6-9b51-d69d6b488b28.png">

**Comment by lmosele** [comment]
Hey @helenvholmes, I'd love to take this on to get my feet wet, it'd be my first ever OS contribution. I'm a UX designer too but any existing design specs to keep in mind?

**Comment by helenvholmes** [comment]
Hey @lmosele,

Hi! Thanks for taking the time!

So existing spec, but we do have a set of existing colors in ```packages/devtools-local-toolbox/public/js/lib/themes/variables.css``` under ```:root.theme-dark``` that are the jumping off point for this issue.

Are you all set up with the project? Do you want/need extra guidance to get started?

**Comment by jasonLaster** [comment]
Thanks @lmosele - here's some more info on making theme changes: https://github.com/devtools-html/debugger.html/issues/988

**Comment by jasonLaster** [comment]
Hey @lmosele @helenvholmes just opened a nice PR for the landing page. We'd love to have your help on some of the other [up for grabs](https://github.com/devtools-html/debugger.html/issues?q=is%3Aissue+is%3Aopen+label%3A%22up+for+grabs%22) issues if you have some time.

**Comment by lmosele** [comment]
@jasonLaster @helenvholmes  Thank you so much for the prompt answers! I may drop in the IRC at some point. Do we have a node version we should be running on? Looks like > v6 was throwing errors for me but I dropped down to 4.4 and it worked. 

I'll be checking out the other up for grabs issues since I didn't have the time to set up earlier. Thanks!
