### ISSUE TITLE
[flow] Add types for utilities

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1034]
There are several util files that types would really help. I think if we can type these files, our overall score would go up a lot.
- http://jasonlaster.github.io/debugger-flow-report/sourcefiles/public/js/utils/assert.js.html
- http://jasonlaster.github.io/debugger-flow-report/sourcefiles/public/js/utils/defer.js.html
- http://jasonlaster.github.io/debugger-flow-report/sourcefiles/public/js/utils/log.js.html
- devtools-config/feature.js (not in the list, but i've seen devtools-confg mentioned in several places).

**Comment by AbhiGulati** [comment]
I would like to work on this.

**Comment by AbhiGulati** [comment]
I am still working on this. As far as I can tell, @jacobjzhang's PR doesn't add annotations for defer.js and log.js. I should have a PR ready by tomorrow.

**Comment by jasonLaster** [comment]
Thanks. I'll try and create some more flew issues. Running npm run flow-coverage shows lots of areas for improvement

**Comment by jacobjzhang** [comment]
@AbhiGulati apologies, didn't see you had called this.
