### ISSUE TITLE
Mochitest - Test searching

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1036]
We should have integration tests for the file and source search:

**File Search**
- test a query with one result
- test a query with many results (enter, shift enter)
- test a query with no results

**Source Search**
- test a query with no results
- test a query with many results (arrow keys, enter)
- clicking the new tab button

**Comment by jacobjzhang** [comment]
@jasonLaster I can take this one

**Comment by jasonLaster** [comment]
We didn't add file search tests, but we can do that later
