### ISSUE TITLE
Source Search tweaks

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1038]
@wldcordeiro you mentioned a couple of tweaks that were out of scope for the source search PR.

@helenvholmes you also mentioned a couple of small tweaks to @wldcordeiro's update.

Lets track this work here. Feel free to update this vague description.

[Invision link](https://projects.invisionapp.com/share/AY8OEG3C6#/screens/117937554_Debugger)

**Comment by wldcordeiro** [comment]
Things I noted in the invision doc that weren't added but could be relatively easy additions.

* result count message https://projects.invisionapp.com/share/AY8OEG3C6#/screens/117937554/comments/74310978

Not so easy addition, still awesome to have.

* additional search types, UX surrounding it https://projects.invisionapp.com/share/AY8OEG3C6#/screens/117937554/comments/74311014

**Comment by jasonLaster** [comment]
> additional search types

Hmm, this is super confusing, but I'm only thinking about "source search" which is where you search for sources. This is not really in scope there.

**Comment by wldcordeiro** [comment]
@jasonLaster From the looks of the invision document it'd be modifiers to search that actually then search all the sources for specific things. 

Stuff like

* search function definitions
* find in file
* line number
* filter variables

Definitely not a tweak though, more like full features/enhancements of their own. 😆

**Comment by jasonLaster** [comment]
Closing this as we've addressed the source search tweaks.
