### ISSUE TITLE
File Search - blinking orange cursor

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1041]
When the file search bar opens, the cursor is orange. After you've typed, it's no longer orange. We should fix this so that when it opens it is the normal grey :)

Not really sure what CSS magic we need to use because it will be orange when the search results are empty :)

![](http://g.recordit.co/ensezSkeZl.gif)

**Comment by ryandoherty** [comment]
Got a browser/OS/revision handy? I've tested this with 2b7d50fcf197d680c0f842c658e62043784b19f7 on Firefox 49.0.2 and Chrome 54.0.2840.71 on OSX 10.11.6 and can't reproduce. Thanks!

**Comment by jasonLaster** [comment]
Weird. Thanks!
