### ISSUE TITLE
CONTRIBUTING.md references missing files

### ISSUE THREAD

**Issue by ryandoherty** [devtools-html/debugger.html#1042]
In https://github.com/devtools-html/debugger.html/blob/master/CONTRIBUTING.md#configuration, the link goes to https://github.com/devtools-html/debugger.html/blob/master/config/development.json, which 404's. The contributing docs also reference https://github.com/devtools-html/debugger.html/blob/master/config/README.md, which 404's.

Was the config directory removed for a reason? I can dig through commits to find the latest version and restore it, but wanted to check first.

**Comment by ryandoherty** [comment]
Also, I'd mark this issue with the 'bug' label, but it appears I somehow am unable to. Sorry!

**Comment by wldcordeiro** [comment]
I think the first file you linked to should be this instead.

https://github.com/devtools-html/debugger.html/blob/master/packages/devtools-config/configs/development.json

The second should be this

https://github.com/devtools-html/debugger.html/blob/master/packages/devtools-config/README.md

This was just a result of our shift to a mono-repo not getting updated. If you'd like to submit a PR with the changes that would be most welcome!

**Comment by ryandoherty** [comment]
Awesome, thanks for the help! I can submit a PR soon(ish).

**Comment by jasonLaster** [comment]
Thanks!
