### ISSUE TITLE
Fresh NPM install not working on windows

### ISSUE THREAD

**Issue by galtalmor** [devtools-html/debugger.html#1043]
Hi,
I'm using latest node and npm versions (node 6.9.1 and npm 3.10.9) on windows 10.
Tried to run 'npm install' according to readme, always getting the following:

```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "c:\\...\\node.exe" "C:\\...\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "preinstall"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! debugger.html@0.0.6 preinstall: `./bin/preinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the debugger.html@0.0.6 preinstall script './bin/preinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the debugger.html package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs debugger.html
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls debugger.html
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\...\debugger.html\npm-debug.log
```

Trying to run `./bin/preinstall` file from a linux shell (git bash/mingw) results in the following (with or without administrator privileges):

```
+-- lerna@2.0.0-beta.30 extraneous (git://github.com/jasonlaster/lerna.git#f59454363fde40769b97291d4fb2f1eece4e2e9a)
Lerna v2.0.0-beta.30
Bootstrapping 7 packages
Installing external dependencies
debugger.html╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
Symlinking packages and binaries
Symlink already exists for chrome-remote-debugging-protocol dependency of devtools-local-toolbox, but links to different location. Replacing with updated symlink...
chrome-remote-debugging-protocol╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
devtools-config╢██████████████████░░░░░░░░░░░░░░░░░░░░░░░░╟
devtools-local-toolbox╢█████████████████████░░░░░░░░░░░░░░░░░░░░░╟
Errored while running BootstrapCommand.execute
Error: ENOENT: no such file or directory, stat 'c:\...\debugger.html\packages\chrome-remote-debugging-protocol\build-bootstrap.js'
    at Error (native)
```

Any suggestions?

**Comment by jasonLaster** [comment]
Hmm try yarn install. Also the preinstall script just wraps lerna so feel free to try to do it yourself. Lerna is windows friendly so should be fine. 

Also please share what you learn!

**Comment by galtalmor** [comment]
So `yarn install` didn't work as well, here's the result:
```
$ yarn install
yarn install v0.16.1
$ ./bin/preinstall
'.' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
And when I try to run lerna from the command line using `./node_modules/lerna/bin/lerna.js bootstrap` I get the same error as above:
```
Errored while running BootstrapCommand.execute
Error: ENOENT: no such file or directory, stat 'd:\Gal\Sites\debugger.html\packages\chrome-remote-debugging-protocol\build-bootstrap.js'
    at Error (native)
```

**Comment by wldcordeiro** [comment]
Try `npm install --ignore-scripts` and then `lerna bootstrap` the pre install script doesn't work with Windows.

**Comment by galtalmor** [comment]
`npm install --ignore-scripts` seems to work fine, but `lerna bootstrap` still returns same error message.

**Comment by jasonLaster** [comment]
Hmm. Build-bootstrap in crdp shouldn't matter. Perhaps try removing or adding that. 

Are you free to screen hero next week? Would be happy to pair on this

**Comment by wldcordeiro** [comment]
I think `lerna bootstrap --ignore-scripts` may work? The docs aren't super clear but it sounds like that it should respect the ignore argument.

**Comment by DevilstarII** [comment]
Error: ENOENT: no such file or directory, stat 'c:\...\debugger.html\packages\chrome-remote-debugging-protocol\build-bootstrap.js'

Looks like build-boostrap.js can be found in debugger.html\packages\chrome-remote-debugging-protocol\bin\build-bootstrap.js

Just copied it to the wanted folder and everything worked.

**Comment by wldcordeiro** [comment]
@DevilstarII what command did you try running? I'm not sure moving the file is the best fix, rather updating the code that is looking in the wrong place is likely a better solution.

**Comment by DevilstarII** [comment]
Now i wonder where i can find the console input field in debugger.html

**Comment by wldcordeiro** [comment]
@DevilstarII I'm confused what your question is, the debugger isn't the console and if you're loading it up in a browser tab you still use the devtools console. However you didn't answer the question I asked which is what command did you run to see the output you had? `npm install`? `lerna bootstrap`?

**Comment by DevilstarII** [comment]
@wldcordeiro Yeah, i completely agree it would be better. I just used it as a temporary workaround for testing on windows.

I ran ./bin/preinstall

**Comment by wldcordeiro** [comment]
@DevilstarII try changing this line https://github.com/devtools-html/debugger.html/blob/933c2ec34c537ca17ad3b08fa86d8c6cb5c49021/packages/chrome-remote-debugging-protocol/package.json#L7

to `"chrome-remote-debugging-protocol": "bin/build-bootstrap.js"` and delete the file you copied to see if it works. I think it's just looking in the wrong place because it's locally installed https://docs.npmjs.com/files/package.json#bin

**Comment by DevilstarII** [comment]
Changing the line helped on the fresh cloned debugger.html

It still produces a WARN message when i run `npm install --ignore-scripts` or `./bin/preinstall`
`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32
"})`
but dev-server starts successfully.

**Comment by wldcordeiro** [comment]
@DevilstarII awesome! If you'd like to make your first contribution to the project as a PR with that change it'd be most appreciated. The warning you're seeing is nothing to worry about though. It's just an optional dependency that only works with OS X, I get that in Linux too.

**Comment by DevilstarII** [comment]
@wldcordeiro Sure. Will do it as soon as i get home.

**Comment by galtalmor** [comment]
@wldcordeiro That fixed it for me too.
So the instructions for a fresh install on windows should be updated to 
```
npm install --ignore-scripts
lerna bootstrap
```
On the `npm install` I still get these warnings, but I suppose that doesn't really matter in any way
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```
I'll let @DevilstarII to make the PR.
Thanks everyone.

**Comment by jasonLaster** [comment]
Thanks @galtalmor @DevilstarII!
