### ISSUE TITLE
[Source Search] Show results summary

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1068]
It would be great if the source search showed a summary of files found as you typed. 

Here's a [patch](https://gist.github.com/jasonLaster/ce8f6b404eb28cece4b209753084c6d8) to get started. Feel free to apply to a local branch:

```
curl https://gist.githubusercontent.com/jasonLaster/ce8f6b404eb28cece4b209753084c6d8/raw/9d964ab88913f70778e915c903b0ce2876e2e2c4/foo.diff | git apply
```

Design:
![screen shot 2016-11-01 at 12 27 40 pm](https://cloud.githubusercontent.com/assets/254562/19897515/ad8dc520-a02e-11e6-98b8-50bf715c514f.png)

Current Behavior: 
![](http://g.recordit.co/58Ybo6OAh4.gif)

**Comment by Zacqary** [comment]
What's the difference between "Files named" and "instances of" here?

Also, what should the summary do in cases like these, where there are definitely matches but certainly no files actually named these things:
![screen shot 2016-11-03 at 3 31 03 pm](https://cloud.githubusercontent.com/assets/1445834/19982016/af6b8e6a-a1da-11e6-9942-f6d6147417f5.png)
![screen shot 2016-11-03 at 3 31 49 pm](https://cloud.githubusercontent.com/assets/1445834/19982017/af6d2efa-a1da-11e6-88a2-28ac31a471a5.png)
