### ISSUE TITLE
 ECONNREFUSED 127.0.0.1:6080

### ISSUE THREAD

**Issue by imvetri** [devtools-html/debugger.html#1069]
I could not try debugger.html because of below error on 

**> "npm start"**

>  debugger.html@0.0.6 start /Users/shanmuv/Desktop/Training/debugger.html
> start-dev-server

> 
> Listening for WS on *:9000
> Will proxy to TCP on *:6080 on first WS connection
> Protocol messages can be logged by enabling logging.firefoxProtocol in your local.json config
> Hot Reloading can be enabled by adding "hotReloading": true to your local.json config
> Development Server Listening at http://localhost:8000
> View debugger examples at http://localhost:7999
> [BABEL] Note: The code generator has deoptimised the styling of "/Users/shanmuv/Desktop/Training/debugger.html/packages/devtools-sham-modules/sham/css-property-db.js" as it exceeds the max of "100KB".
> TCP connection failed: Error: connect ECONNREFUSED 127.0.0.1:6080
> WS connection closed, disconnected from TCP

Please consider this as a low priority issue. 

I wanted to give Debugger.html and I followed steps mentioned in the README and above is the error I got.

**Comment by wldcordeiro** [comment]
Odd, looks like you may have something else using that port?

**Comment by imvetri** [comment]
I tried killing all the process using 8000. and there were no process that was using 6080.

Which port should I try killing ?

Also, I am able to see some content at http://localhost:7999/

**Comment by imvetri** [comment]
One more information. I get below message only when I Open http://localhost:8000/ Whilst opening http://localhost:7999/ doesnt throw any error and it gives me some page.

> TCP connection failed: Error: connect ECONNREFUSED 127.0.0.1:6080
WS connection closed, disconnected from TCP

**Comment by wldcordeiro** [comment]
@imvetri try opening the Firefox Developer Toolbar (Shift+F2) and typing `listen 6080`

**Comment by imvetri** [comment]
Okay. I'll try that and update the thread. 

On a curious note, am I not following the steps mentioned in readme?

**Comment by wldcordeiro** [comment]
@imvetri sometimes the steps in the readme don't work for specific cases, I know that for me I often have to enable the port listening because of the Firefox configuration I run.

**Comment by imvetri** [comment]
I think I didn't follow the steps as instructed. After some hard tries following worked for me.

1.  npm install
2. firefox -> about:config -> [make firefox debuggable](https://github.com/devtools-html/debugger.html/blob/master/docs/remotely-debuggable-browsers.md#firefox) -> **restart**
3. npm start
4. firefox ->debug console -> listen 6080
5. hit http://localhost:8000/ 
6. a page with "about:config" and "Firefox Debugger" opens 
7. Click "Firefox Debugger" -> no response in Firefox
8. start from step 5 in Chrome. -> debugger appears :dancing_men: 

@wldcordeiro  I have following questions.

1. I think this is not a bug, Its simply because I didn't follow the steps correctly.(hence closing this)
2. Is the above setup sufficient to start contributions?

**Comment by imvetri** [comment]
Update: I couldn't see any page on click of "Firefox Debugger" in both firefox(v48) and firefox nightly.

**Comment by montogeek** [comment]
I am hitting this issue in OSX Sierra, nothing is running in any of the ports used by the debugger..

Log:
```
> debugger.html@0.0.6 start /Users/montogeek/Infinite/Lov/debugger.html
> start-dev-server

Listening for WS on *:9000
Will proxy to TCP on *:6080 on first WS connection
Protocol messages can be logged by enabling logging.firefoxProtocol in your local.json config
Hot Reloading can be enabled by adding "hotReloading": true to your local.json config
Development Server Listening at http://localhost:8000
View debugger examples at http://localhost:7999
[BABEL] Note: The code generator has deoptimised the styling of "/Users/montogeek/Infinite/Lov/debugger.html/packages/devtools-sham-modules/sham/css-property-db.js" as it exceeds the max of "100KB".
TCP connection failed: Error: connect ECONNREFUSED 127.0.0.1:6080
WS connection closed, disconnected from TCP
TCP connection failed: Error: connect ECONNREFUSED 127.0.0.1:6080
WS connection closed, disconnected from TCP
```

**Comment by jasonLaster** [comment]
don't worry about that. that's the dev-server trying to connect with chrome.

I have a PR that cleans that up so it's more clear.

**Comment by montogeek** [comment]
@jasonLaster Thanks!
I understood the process wrong, @jlongster helped me!

**Comment by brutalcrozt** [comment]
idk but i still got those error on terminal. it gone after i change **\debugger.html\configs\development.json**
```
"firefox": {
    "webSocketConnection" : false,
```
to
```
"firefox": {
    "webSocketConnection" : true,
```

**Comment by jasonLaster** [comment]
closing as this is a question for the launchpad

**Comment by japrogramer** [comment]
hello Im getting this error after trying to change the port from 8000 to 9000

```
▶ ack 8000
application.json
5:    "parserURL": "http://localhost:8000/assets/build/parser-worker.js",
6:    "sourceMapURL": "http://localhost:8000/assets/build/source-map-worker.js",
7:    "prettyPrintURL": "http://localhost:8000/assets/build/pretty-print-worker.js"
56:    "serverPort": 8000,

local.json
16:    "parserURL": "http://localhost:8000/assets/build/parser-worker.js",
17:    "sourceMapURL": "http://localhost:8000/assets/build/source-map-worker.js",
18:    "prettyPrintURL": "http://localhost:8000/assets/build/pretty-print-worker.js",
19:    "searchURL": "http://localhost:8000/assets/build/search-worker.js"

development.json
16:    "parserURL": "http://localhost:8000/assets/build/parser-worker.js",
17:    "sourceMapURL": "http://localhost:8000/assets/build/source-map-worker.js",
19:      "http://localhost:8000/assets/build/pretty-print-worker.js",
20:    "searchURL": "http://localhost:8000/assets/build/search-worker.js"
91:    "serverPort": 8000,
(tools)
archangel@The_Black_Knight:git/debugger.html/configs  master ✗                                                                                                                                                                                                                                                                                                                                                                     2d ⚑
▶ ack 9000
application.json
52:    "proxyHost": "localhost:9000",

local.json
89:    "serverPort": 9000,

```

**Comment by lukaszsobek** [comment]
@japrogramer you will get this eror when there is a tab open in the debugger, but not in the browser. There is a pending fix for that issue.

**Comment by jasonLaster** [comment]
lets discuss this in the devtools-core repo where the launchpad is maintained

**Comment by ShaguftaMethwani** [comment]
Sorry for commenting 2 years late, but I have this issue and apparently the shortcut doesnt exist anymore, shift+f2. Any idea how can i access the debug console?
