### ISSUE TITLE
[Source Search] show selected source

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1070]
When source search is open, selecting a source in the tree or tabs does not show the source.

![](http://g.recordit.co/fqOD4avWCN.gif)

**Comment by wldcordeiro** [comment]
So basically clicking a tab or tree item should close the search?

**Comment by jasonLaster** [comment]
yep

**Comment by wldcordeiro** [comment]
So I'm still struggling with getting the system up and running as I like so I can't make a patch for a contributer, however here are some details to get someone going.

The interesting bits of the tabs and sources tree are

https://github.com/devtools-html/debugger.html/blob/master/public/js/components/SourceTabs.js#L140
https://github.com/devtools-html/debugger.html/blob/master/public/js/components/SourcesTree.js#L78

You would want to call `toggleFileSearch(false)` in both those onClick handlers.

https://github.com/devtools-html/debugger.html/blob/master/public/js/actions/ui.js

So for SourceTabs you might want something like this at line 140
```js
onClick: () => {
  selectSource(source.get("id"));
  toggleFileSearch(false);
},
```

Though you'd need to get `toggleFileSearch` from the props [here](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/SourceTabs.js#L127)

For SourcesTree it would be similar.

```js
  selectItem(item) {
    if (!nodeHasChildren(item)) {
      this.props.selectSource(item.contents.get("id"));
      this.props.toggleFileSearch(false);
    }
},
```

Though here you would need to pass `toggleFileSearch` down from `Sources` [here](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/Sources.js#L32)
