### ISSUE TITLE
[Source Search] handle narrow width

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1071]
The center pane can potentially be narrow (200px or less) and in those cases we should truncate or appropriately wrap the search results.

![screen shot 2016-11-01 at 4 40 16 pm](https://cloud.githubusercontent.com/assets/254562/19906554/9028cd4a-a051-11e6-8533-85517a4c4582.png)

**Comment by imvetri** [comment]
I think this is fixed. I tried to reproduce this by following.

1. open debugger
2. hit cmd+p and search for text

Following is how the search result comes. 

<img width="588" alt="debugger html_search_files" src="https://cloud.githubusercontent.com/assets/6542274/19931488/b6a37ba0-a132-11e6-90b6-dd9ba96c6eae.png">

@jasonLaster , Could you please confirm are we talking about the same screen?

**Comment by jasonLaster** [comment]
@imvetri this looks like a question of word-wrap or word-break with `/` and `-` in the path.

Try debugging `localhost:7999/todomvc` and doing seaching `t`

![](http://g.recordit.co/i3cYCqW2Oo.gif)

Thanks for the help!

**Comment by jagtalon** [comment]
I got this!

**Comment by jasonLaster** [comment]
Thanks!
