### ISSUE TITLE
Debugger disables keyboard interaction in devtools toolbox on about:blank

### ISSUE THREAD

**Issue by gregtatum** [devtools-html/debugger.html#1081]
STR:

* Navigate to a page with no script sources, e.g. about:blank
* Open up devtools in Firefox.
* Click on inspector
* Hit shift tab in the toolbar a few times to focus on the toolbar
* Hit the right keyboard arrow, focus the debugger then hit spacebar.
* Hit tab again
* No elements will gain focus through the keyboard

Expected Results:

* Full keyboard access should be maintained.

This is not an issue when a page has sources.

**Comment by jasonLaster** [comment]
@gregtatum what happens with the page has sources. The no sources use case seems like an edge case.

**Comment by gregtatum** [comment]
@jasonLaster The tabbing functionality works if there are sources. This might be a XUL bug I've encountered before that looks like this:

STR:
* element.focus()
* element.style.visibility = "hidden"
* Keyboard shortcuts break

The fix is something like focusing on another element at a certain point, possibly combined with window.focus(). I can't really remember the precise fix. Ugh.

Either that or a rogue keypress event handler is swallowing keyboard events somehow.

**Comment by jasonLaster** [comment]
@gregtatum I'm marking this as a `low-priority` issue and moving to the enhancements board.

Do you think that this has improved now that the toolbar has been de-xuled?

If not, I'd like to get back to this in a couple months when hopefully we've done a better job of de-xuling in general.

**Comment by gregtatum** [comment]
Aways a possibility, but probably not.
