### ISSUE TITLE
Frame Focus State

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1084]
We recently made frames focusable which added an outline. I think it would be a little cleaner if we were to style it without the blue border and maybe something else. 

@helenvholmes thoughts?

![screen shot 2016-11-02 at 11 27 19 am](https://cloud.githubusercontent.com/assets/254562/19944090/a4e9e0d8-a110-11e6-99ee-b5aef265fd76.png)

**Comment by helenvholmes** [comment]
I talked about this with @jlongster a few days ago—I think we want to do the following:

1. Have a selected, but unfocused state. This will be some version of gray.
2. Have a selected and focused state. This will be our white-on-blue styling. (Sans native focus.)

I'd opened #962 to address this, but I think there's some work that needs to be done restructuring the tree view that I felt ill-equipped to handle on my own to make this happen.

**Comment by jasonLaster** [comment]
Got it. Thanke
