### ISSUE TITLE
[Dark Theme] secondary text

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1085]
The secondary text is an awkward gray that looks off to me. 

Here is how you change a [theme color](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#themes)

Here is the secondary text for frames, we could also find other secondary text in breakpoints...

```patch
diff --git a/src/components/Frames.css b/src/components/Frames.css
index 34c3979..c442b66 100644
--- a/src/components/Frames.css
+++ b/src/components/Frames.css
@@ -27,6 +27,7 @@
   background-color: var(--theme-tab-toolbar-background);
 }

+/* => here */
 .frames .location {
   color: var(--theme-comment);
   font-weight: lighter;
```

![screen shot 2016-11-02 at 3 28 11 pm](https://cloud.githubusercontent.com/assets/254562/19944140/eb205082-a110-11e6-9a64-325bd8e93d7b.png)

**Comment by jasonLaster** [comment]
@wldcordeiro @helenvholmes I deleted the dark theme label as we no longer have that many issues

**Comment by jasonLaster** [comment]
ping @helenvholmes do you have time to tackle this?

**Comment by andreicristianpetcu** [comment]
I'll work on this

**Comment by jasonLaster** [comment]
Grab it. Nah

**Comment by andreicristianpetcu** [comment]
@jasonLaster I read a lot about Enzyme, Jest and testing React+Redux stuff. I think I can write some tests on my next contribution. I still have Mochitest on my reading list.

**Comment by jasonLaster** [comment]
@andreicristianpetcu nice. yeah, mochitest is our  mozilla test framework. The way we use it, its pretty basic. 

We currently have node unit tests and we're working on getting the mochitests to run in a regular pae
