### ISSUE TITLE
"Not Paused" should not be selectable

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1087]
We should make "Not Paused" not selectable. We did this with other elements [here](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/RightSidebar.css#L8-L11)

![](http://g.recordit.co/toqnUIngjG.gif)

**Comment by ajstrand** [comment]
@jasonLaster I have a PR ready for this issue

**Comment by jasonLaster** [comment]
@ajstrand great, just merged the lint work, so hopefully it's unblocked
