### ISSUE TITLE
[File Search] whitespace queries

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1101]
We recently added a really great codemirror improvement for highlighting search queries. While
playing with it I noticed that we highlight empty and whitespace queries. I can see how this is *good* behavior for an editor where selecting and changing whitespace makes sense, but in our case I think it might be a bit disruptive as you're only really searching for a place to add a breakpoint or get some context. 

With that in mind, I think we should likely bail early and not show matches for empty strings or whitespace strings.

@bomsy, @jlongster, @helenvholmes, @clarkbw, @Zacqary thoughts?

#### matches
![](http://g.recordit.co/aAtlDH8rIG.gif)

#### empty
![screen shot 2016-11-04 at 9 22 22 am](https://cloud.githubusercontent.com/assets/254562/20006856/e0b74028-a26f-11e6-9773-912978fef6a8.png)

### whitespace
![screen shot 2016-11-04 at 9 22 15 am](https://cloud.githubusercontent.com/assets/254562/20006857/e0ba2a68-a26f-11e6-96e4-007c9dd1ad07.png)

**Comment by bomsy** [comment]
I think that makes sense, in this context.

Interestingly,
- Atom doesn't match below 3 whitespaces , user has to use the  regexp `\s+`  instead.
- Chrome devtools matches on whitespaces.

Just throwing out there, should we match only if the whitespace length is above a certain number .. (e.g 2 or 3). That way we are sure the user is explicitly searching for spaces?

**Comment by jasonLaster** [comment]
hmm, i’d be okay matching 3 or more… At that point I assume that’s what you
chose to do :)

I’d also be fine not matching at all. Feel free to make a call and we can
discuss more in the PR.

**Comment by Zacqary** [comment]
:+1: on requiring 2 spaces to search. Although I'm not sure why Atom does 3, maybe there's a good rationale for that?
