### ISSUE TITLE
[Source Tabs] Add additional close items

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1104]
We recently added the source tabs context menu, which has two close items "close tab" and "close all". It'd be great to add the additional common close items for "close other tabs" and "close tabs to the right". I attached a screenshot below for where this is done.

Here's a patch to get started [patch](https://gist.github.com/jasonLaster/54c329896793a6b7f34fdfa121d6fcfb)

![screen shot 2016-11-04 at 10 25 22 am](https://cloud.githubusercontent.com/assets/254562/20008968/006ca846-a279-11e6-81b7-7e22096d6da5.png)

**Comment by bomsy** [comment]
fixing this!

**Comment by charltonaustin** [comment]
How's that coming?
