### ISSUE TITLE
[console] source link does not open the correct location

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1105]
Clicking on a console error link does not open in the right spot. We've tested this in other places, so i think it might be an edge case with how we link to and HTML file... perhaps.

STR:
1. open fiddle https://jsfiddle.net/sheppy/f0xwxupk/
2. go to console and select the first line in the error
3. view the selected location in the debugger

Thanks @a2sheppy for pointing it out

![](http://g.recordit.co/G20opZ6GLc.gif)

### correct location is 81 here
![screen shot 2016-11-04 at 11 34 15 am](https://cloud.githubusercontent.com/assets/254562/20011568/7993944c-a282-11e6-9ddc-06280427e572.png)

**Comment by jlongster** [comment]
This works in nightly for me. Are you sure you're testing the latest version?

**Comment by a2sheppy** [comment]
I'm using Nightly from Oct. 29 and this happens for me.

**Comment by jasonLaster** [comment]
it looks like there is a bug in bug 1313197 that broke linking completely :/ but this should not have resulted in the error you saw, because it shouldn't have opened up a source at all. So I don't know. I'll fix this bug (basically, it calls `selectSourceByURL` instead of `selectSourceURL`) and we'll see if we can repro later

**Comment by jasonLaster** [comment]
@jlongster I believe this is done?

**Comment by clarkbw** [comment]
This looks like it is working for me.  At least I can't repro in Nightly right now.

**Comment by jasonLaster** [comment]
I believe this is supported. We can always re-open
