### ISSUE TITLE
[file search] style outline matches

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1111]
We recently landed support for outlining all of the search results. We should do a quick style pass to clean it up, although it is already pretty good.

Here's the designs from [invision](https://projects.invisionapp.com/share/AY8OEG3C6#/screens/117937554_Debugger) for search

The two takeaways for me are:
1. the outline should be light and stay out of the way
2. the selected match should be yellow. Ideally a garrish yellow as @helenvholmes requested. I'm not sure if we have a css variable for that.

One other consideration is what we want to do for the dark mode. What's the equivalent of a garrish color (is it pink?) Feel free to use your best judgement there. And here's a link for changing the [theme](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#themes) to dark.

![screen shot 2016-11-04 at 12 26 49 pm](https://cloud.githubusercontent.com/assets/254562/20013489/b34012f4-a289-11e6-97ca-44d40e787ed4.png)

**Comment by jasonLaster** [comment]
@monicau I think you might enjoy this one :) 
It involves styling the editor, which as you know is pretty cool.

**Comment by IagoLast** [comment]
Maybe I'm missing something but when I try to reproduce this the browser's default search bar is shown instead the debugger one. 

(When I hit `cmd+p`the debugger search bar is shown but the results dialog is different since this searches on every file)


Could it be some incompatible version of something ?

Debugger.html: 0.0.8
OSX: 10.11.5 (15F34)
NODE: 7.1.0
FFOX-DEV: 51.0a2 (2016-11-14) (64-bit)

Also tested on chrome:
CHROME: 54.0.2840.98 (64-bit)

**Comment by andreicristianpetcu** [comment]
Same here. I was thinking that I was doing something wrong and it did not appear :)

**Comment by jasonLaster** [comment]
Hi @IagoLast, @andreicristianpetcu 

Sorry it wasn't clear

You'll need to go through the [getting started](https://github.com/devtools-html/debugger.html/blob/master/CONTRIBUTING.md#getting-started) setup and enable `editorSearch` in the [local config](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#configs).

**Comment by monicau** [comment]
Hey @jasonLaster thanks for flagging me down. I was able to reproduce this issue. I'll take this if no one is working on it at the moment. Let me know :)

**Comment by jasonLaster** [comment]
Sure!

**Comment by monicau** [comment]
Here's the modified light theme.
![debugger-file-search](https://cloud.githubusercontent.com/assets/2848472/20470087/3c9b2070-af73-11e6-83bc-552f4ccad8d0.png)
For the dark-theme, yellow highlighting also looks good but I can't seem to change the colour of the text itself to make it more readable.
![debugger-file-search-dark](https://cloud.githubusercontent.com/assets/2848472/20470134/9969dc56-af73-11e6-880b-36987b13002c.png)
In dark-theme.css I tried setting the color in the same class that affects the highlight but it doesn't seem to work:
```
.cm-s-mozilla .CodeMirror-selected {
background: rgb(255, 255, 0);
color: rgb(0, 0, 0);
}
```
Is it being overwritten by something else?  When I inspect element, the selected text has classes `cm-overlay cm-selecting`, so do the other matches in the document.  Oddly the currently selected match doesn't have  the class `CodeMirror-selected` or any other classes to differentiate itself from the other matches in the file.. so I'm kinda stumped.  Any ideas?

**Comment by jasonLaster** [comment]
hmm - super strange. 

@monicau Mind opening a WIP PR and I'll take a look. Sorry that i missed this earlier

**Comment by IagoLast** [comment]
@monicau same here, seems like only `.cm-selecting` is being applied.

**Comment by jasonLaster** [comment]
I'll take a look Wednesday, if you guys run out of leads. 

I'm afraid I'd, likely just be digging with the inspector as well.

**Comment by monicau** [comment]
Alright I created a WIP pull request!

**Comment by jasonLaster** [comment]
Thanks @monicau!
