### ISSUE TITLE
issue with Local Setup

### ISSUE THREAD

**Issue by viswanathamsantosh** [devtools-html/debugger.html#1115]
[npm-debug.txt](https://github.com/devtools-html/debugger.html/files/573309/npm-debug.txt)

was trying to setup the project locally on Ubuntu 15.10 on VMware running on windows 10 operating system.npm install gives the following error.
![debugger](https://cloud.githubusercontent.com/assets/3799600/20031318/b88df2b8-a332-11e6-84e5-232cf3c34604.png)
It says fsevents is not compatible with my OS. I tried to install fsevents separately using 'npm install fsevents' but still gives me the same error. Is there any way I could set this project on my local?

**Comment by jasonLaster** [comment]
@wldcordeiro @shlomif @DevilstarII have you seen something like this before?

**Comment by shlomif** [comment]
@jasonLaster : I don't think I saw something like this.

**Comment by DevilstarII** [comment]
@jasonLaster @viswanathamsantosh 

Well, it's an optional dependency and non-macOS users face this problem as far as i understand. But according to wldcordeiro's [comment](https://github.com/devtools-html/debugger.html/issues/1043#issuecomment-257377595), this shouldn't be an issue to start dev-server.

**Comment by Garbee** [comment]
It doesn't look to me as if this is an fsevents problem at all. It looks like something else is failing in the build causing a file to not get made. Then as a chmod on them is attempted, that fails due to them not existing.

`development-server.js` in the `devtools-local-toolbox/bin` directory when installed seems to be missing. I think the problem lies in that packages install process and not fsevents.

**Comment by jasonLaster** [comment]
Nice hawk eyes @Garbee!

We've actually seen this bug with the local-toolbox before. Version 0.0.6 added `bin` to the list of files [here](https://github.com/devtools-html/debugger.html/blob/master/packages/devtools-local-toolbox/package.json#L49-L52)

@viswanathamsantosh was this a fresh git clone of the project three days ago? Can you confirm the toolbox version [here](https://github.com/devtools-html/debugger.html/blob/master/package.json#L71)?

I just did a fresh install with your version of node (5.9) and npm 3.10 which should be pretty close to yours and it worked alright.

**Comment by viswanathamsantosh** [comment]
Thank you so much guys! You are wonderful. I updated my local master branch and ran 'npm install'. It just gave me a warning unlike before which was throwing errors. My local is up now. Thank you. :)

**Comment by jasonLaster** [comment]
Thats great!

Happy to hear. Take a look at our up for grabs!

**Comment by jasonLaster** [comment]
What team are you on?

**Comment by viswanathamsantosh** [comment]
![debugger2](https://cloud.githubusercontent.com/assets/3799600/20150573/7782a296-a66b-11e6-87b8-28c4c4d90df7.png)
Oops sorry! got this error on 'npm start Firefox'. Any thoughts?
[npm-debug.txt](https://github.com/devtools-html/debugger.html/files/581595/npm-debug.txt)

**Comment by jasonLaster** [comment]
Ah. No worries. We're still working on npm run Firefox. Use the long form
command in the docs :)

**Comment by viswanathamsantosh** [comment]
I am a volunteer from the Campus Program team under Participation team, planning to create an activity for Students in campuses to participate in contributing to Firefox dev tools(and may be debugger.html?) so thought to explore this myself first. :D

**Comment by jasonLaster** [comment]
Oh wow neat!

I'd be happy to setup a hangout and help brainstorm contributions to both!

But yeah, take a stab at an up for grab so you get the hang of it.
