### ISSUE TITLE
[RTL] Update call stack component

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1119]
@amitzur did some awesome work [here](https://github.com/devtools-html/debugger.html/pull/903) to make the debugger support right to left formatting.

We should continue making improvements to some of the other components. Lets start by focusing on the call stack, which should be relatively straight forward.

**How do i get started:**
* The best way to get started is to change the index.html `<html>` to `<html dir="html">` [RTL](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#rtl)
* checkout amit's [PR](https://github.com/devtools-html/debugger.html/pull/903) for how he made changes

**Here's what it currently looks like now**

![](https://cloud.githubusercontent.com/assets/394320/19226865/ef18b0d0-8eb9-11e6-82b4-8c4da702fe91.png)

**Here's a patch to get started:**

using floats is probably a bad idea, perhaps we use flex...

```diff
diff --git a/src/components/Frames.css b/src/components/Frames.css
index c18faaf..7f59a5f 100644
--- a/src/components/Frames.css
+++ b/src/components/Frames.css
@@ -27,13 +27,13 @@
 }

 .frames .location {
-  float: right;
+  float: left;
   color: var(--theme-comment);
   font-weight: lighter;
 }

 .frames .title {
-  float: left;
+  float: right;
   text-overflow: ellipsis;
   overflow: hidden;
   margin-right: 1em;
```

**Comment by thejones** [comment]
Working with @noeladd we found that the breakpoint text does not format correctly when running RTL mode. 

```{} || var app = app ``` instead of ```var app = app || {}```

<img width="828" alt="screen shot 2016-11-06 at 3 40 15 pm" src="https://cloud.githubusercontent.com/assets/682850/20041498/ea1aa41a-a437-11e6-825a-937cfb9afe05.png">
