### ISSUE TITLE
consolidate getting started documentation

### ISSUE THREAD

**Issue by afeld** [devtools-html/debugger.html#1127]
The instructions for getting started seem to exist a few places:

* https://github.com/devtools-html/debugger.html#getting-started
* https://github.com/devtools-html/debugger.html/blob/master/CONTRIBUTING.md
* https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md
* https://docs.google.com/document/d/1D1RYP4ImTtY2_STOTZ92Ozb-b4c-gr4MvGcR8E4yjdM/edit#

Would be great to have a single point of reference, which will also help to avoid drift between the different sets of instructions.

**Comment by jasonLaster** [comment]
This is smilar #1233

**Comment by jasonLaster** [comment]
@afeld just landed #1334 which should help in this department!
