### ISSUE TITLE
networkRequest.js trying to fetch JSON list error

### ISSUE THREAD

**Issue by jacobjzhang** [devtools-html/debugger.html#1137]
Upon running 'npm start', the debugger console shows this error. I'm sure that I'm not utilizing that port for any other purpose, as the only other window open was http://localhost:7999/todomvc/ in Firefox for the backbone app.

Screenshot attached.
<img width="1389" alt="screen shot 2016-11-06 at 4 29 11 pm" src="https://cloud.githubusercontent.com/assets/6591285/20041906/91456ddc-a43e-11e6-9a7b-031d44596f49.png">

**Comment by jasonLaster** [comment]
Great issue. i'd noticed that as well. this is the debugger trying to connect to chrome. We should do something to suppress this or make it more clear.

**Comment by jasonLaster** [comment]
This patch is likely the fix

```diff
diff --git a/packages/devtools-local-toolbox/src/index.js b/packages/devtools-local-toolbox/src/index.js
index a1dd65c..8e32bdf 100644
--- a/packages/devtools-local-toolbox/src/index.js
+++ b/packages/devtools-local-toolbox/src/index.js
@@ -114,6 +114,9 @@ function bootstrap(React, ReactDOM, App, appActions, appStore) {
     });
     chrome.connectNodeClient().then(tabs => {
       actions.newTabs(tabs);
+    }).catch(e => {
+      console.log("Connect to node:");
+      console.log("https://github.com/devtools-html/debugger.html/blob/master/CONTRIBUTING.md#node");
     });
     return firefox.connectClient().then(tabs => {
       actions.newTabs(tabs);
```

**Comment by jasonLaster** [comment]
@jacobjzhang interested?

**Comment by jasonLaster** [comment]
moved to devtools-core https://github.com/devtools-html/debugger.html/issues/1485
