### ISSUE TITLE
[Source Tabs] Hide batch close items when there's one tab

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1139]
There are a couple of items in the source tab context menu related to closing multiple tabs. We should only show those items when there are multiple tabs open!

**Comment by jasonLaster** [comment]
Also, don't show "close to the right" if you're selecting the right most one :)

**Comment by bomsy** [comment]
I'm getting this fixed!

**Comment by clarkbw** [comment]
This is fixed now, right?

**Comment by bomsy** [comment]
yes it is!
