### ISSUE TITLE
Test closing the debuggee

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1150]
There are two legacy tests for closing the debuggee and associated windows while paused

- [ ] browser_dbg_clean-exit-window.js
- [ ] browser_dbg_clean-exit.js

We would also like to test persisting:

- [x] tabs
- [ ] selected source
- [ ] watch expressions
- [x] breakpoints

**Comment by darkwing** [comment]
These are all persisted.
