### ISSUE TITLE
Improvement on the action to close multiple tabs

### ISSUE THREAD

**Issue by bomsy** [devtools-html/debugger.html#1151]
At the moment we have an action to close a single tab, which is called N times to close N tabs. An improvement would be to create an action which knows how to close multiple times which we call once.

**Comment by bomsy** [comment]
https://github.com/devtools-html/debugger.html/pull/1134#issuecomment-258708053

**Comment by jasonLaster** [comment]
Thanks for filing @bomsy

**Comment by bomsy** [comment]
@jasonLaster I'm updating the reducers so we dispatch a "CLOSE_TABS". Is that direction ok?

**Comment by jasonLaster** [comment]
@bomsy yup, that makes sense!
