### ISSUE TITLE
Change directory structure

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1153]
Currently, the debugger's source lives in `public/js/**` we would like to move these files to a new directory `src`.

Here's a more verbose description of the files that will move:
* `public/js/**/*` => `src`
* `public/build` => `assets/build`
* `public/images` => `assets/images`
* `public/debugger.properties` => `assets/locales/debugger.properties`
* `packages/devtools-local-toolbox/public/js` => `packages/devtools-local-toolbox/src`

What else needs to change:
* check the webpack configs `webpack.config.js` `packages/devtools-local-toolbox/webpack.config.js` `packages/devtools-local-toolbox/webpack.devtools.config.js`
* check eslintrc, eslintignore
* check stylelintrc stylinteignore
* check `public/js/node-unit-test`
* check `packages/devtools-local-toolbox/bin/development-server`
* check everything in`bin`
* check the other packages, especially config...
* do a project grep for `public/js`

This is obviously a large change, but hopefully not too many individual files need to be edited. If you're interested in grabbing it and run into any issues, share early, ask for questions, etc.

**Comment by wldcordeiro** [comment]
I'll grab this. Got my new setup working too 👍

**Comment by jasonLaster** [comment]
Brave! Welcome back :)

**Comment by jasonLaster** [comment]
This was done in #1184
