### ISSUE TITLE
Fix blank filename in source-tab

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#1160]
**Steps to Reproduce:**
1. Start Nightly
2. Go to Mercurial "https://hg.mozilla.org/mozilla-central/"
3. Open Debugger (Ctrl+Shift+S)
4. Select a source file "(index)"
5. Check .filename in the current source tab

**Actual Results:**
.filename is blank
![fix-blank-filename-in-source-tab](https://cloud.githubusercontent.com/assets/13914314/20167286/ec689654-a75d-11e6-9b03-4cb60ba7bcc1.png)

**Expected Results:**
At least, .filename should be set same with selected source. In this case, "(index)"

**Comment by jasonLaster** [comment]
This is a dupe of #1110 

nice find though!
