### ISSUE TITLE
Fix blurred pause icon in 100% DPI

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#1161]
**Steps to Reproduce:**
1. Start Nightly in 100% DPI
2. Open Debugger (Ctrl+Shift+S)
3. Check the pause icon

**Actual Results:**
![fix-blurred-pause-icon](https://cloud.githubusercontent.com/assets/13914314/20167812/654457d6-a761-11e6-98fb-843ba40f86b1.png)

**Expected Results:**
Thin line style icon is not blurred.

**Comment by jasonLaster** [comment]
@helenvholmes mind looking into this?

**Comment by nt1m** [comment]
@jasonLaster @helenvholmes You can use the SVGs from M-C which don't have the issue.

**Comment by magicp-github** [comment]
New Debugger is using inline SVGs. So it's not same situation.

**Comment by clarkbw** [comment]
Just checked again and this is still an issue.

**Comment by nt1m** [comment]
I think it's safe to copy over the SVG code from m-c and inline it here.
The assets in m-c went through my review where I nitpicked about the blurry pause icon, I'm guessing debugger-html has the wrong version ?

Here's a pixel snapped version: 
https://firefoxux.github.io/firefox-svg-icons/viewer/#pause

**Comment by jasonLaster** [comment]
Thanks @nt1m I never knew about firefoxux, which is an awesome name by the way!

I just made this issue up for grabs, because I believe the task is to simply replace the pause svg we have on file with this new one and perhaps adjust the CSS so that it lines up.

Thanks again!
