### ISSUE TITLE
Don't overflow searchinput and no-result-msg

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#1162]
**Steps to Reproduce:**
1. Start Nightly
2. Go to any sites (e.g. https://www.mozilla.org/en-US/contribute/)
3. Open Debugger (Ctrl+Shift+S)
4. Open searchinput (Ctrl+P)
5. Type search words (e.g. "zzzzz" ) until overlap/overflow

**Actual Results:**
searchinput and no-result-msg overlap/overflow, then layout is broken.
![do-not-overflow-and-overlap-searchinput-and-no-result-msg](https://cloud.githubusercontent.com/assets/13914314/20168505/ec0fd502-a765-11e6-87ea-4cc893acf013.png)

**Expected Results:**
- Overflowed search word is hidden before overlapping with close-btn.
- Don't overflow no-result-msg.

**Comment by jasonLaster** [comment]
Thanks for finding this
