### ISSUE TITLE
Re-enable browser_dbg-searching.js mochitest

### ISSUE THREAD

**Issue by jlongster** [devtools-html/debugger.html#1167]
I had to disable this mochitest because it wasn't working on try. See https://treeherder.mozilla.org/#/jobs?repo=try&revision=f81a032de8b732963fa93589cff9b7830b43098e

**Comment by clarkbw** [comment]
Need to investigate how reliably this is failing on try

**Comment by wldcordeiro** [comment]
This file isn't skipped anymore. Closing.

**Comment by jasonLaster** [comment]
haha - i'm playing a dangerous game where i'm skipping it in MC but not on circle. 

Not sure why it is flakey on circle though

**Comment by codehag** [comment]
this file does not appear any more in the source tree -- what is the status?

**Comment by jasonLaster** [comment]
It's now search-files. We should kill the issue bc we have a new search-
issue
