### ISSUE TITLE
npm run firefox doesn't set firefoxOptions on webdriver instance

### ISSUE THREAD

**Issue by kareniel** [devtools-html/debugger.html#1168]
selenium-webdriver was recently updated from 3.0.0 beta-x to 3.0.1 on npm. Upgrading to the latest version breaks the script behind `npm run firefox` so that the firefoxOptions don't get set on the webdriver instance.

I'm investigating.

(if you run into this, you can run `npm install selenium-webdriver@3.0.0-beta-3` to get `npm run firefox` to work)

You can find the 3.0.0-beta-3 -> 3.0.1 tags commit compare at:
https://github.com/SeleniumHQ/selenium/compare/c7b525db30f2b3ad43cdf7749918fb3a434322dc...1969d7507be7f3b55ae9d1c51c66cd39c1372280

**Comment by jasonLaster** [comment]
Thanks. I noticed this as well, but wasnt 100% sure. Thanks for investigating

**Comment by kareniel** [comment]
Turns out the latest version selenium-webdriver has a fix that sets the moz:firefoxOptions capability behind the scenes when it's given configuration options for the FirefoxDriver. ;)

**Comment by jasonLaster** [comment]
Great. So just to confirm, can we update our package.json and lockfile and
be good.

Mind opening a PR?
