### ISSUE TITLE
Right click + Add Breakpoint does not do anything nor does it dismiss the popup context menu

### ISSUE THREAD

**Issue by shlomif** [devtools-html/debugger.html#1172]
Right click + Add Breakpoint does not do anything nor does it dismiss the popup context menu in the firefox 49.0.2 binary from mozilla.org on Mageia Linux x86-64 v6 when running on a KDE Plasma 5 desktop. This is with commit ab94d5b5bf0db831cfb34316383b3aa3f0025138 on the master branch. I'll try to investigate further. "npm run test-all" appears to pass.

**Comment by shlomif** [comment]
ok, I am now getting this:

```
TypeError: popup.childNodes.forEach is not a function: onShown@http://localhost:8000/public/build/bundle.js:90372:4
showMenu/<@http://localhost:8000/public/build/bundle.js:90390:34
```

I noticed that with this patch (sorry for the bad formatting):

```
diff --git a/public/js/utils/menu.js b/public/js/utils/menu.js
index b1beb71..265b5a0 100644
--- a/public/js/utils/menu.js
+++ b/public/js/utils/menu.js
@@ -20,6 +20,7 @@ function createPopup(doc) {
     document.body.appendChild(mask);
   }
 
+    alert('Flutterbat mask.onclick');
   mask.onclick = () => popup.hidePopup();
 
   popup.openPopupAtScreen = function(clientX, clientY) {
@@ -47,8 +48,11 @@ if (!isFirefoxPanel()) {
 }
 
 function onShown(menu, popup) {
+    alert('Applejack BigMac onShown');
+    alert('Rarity popup=<<' + popup + '>> childNodes=<<' + popup.childNodes + '>>');
   popup.childNodes.forEach((menuitem, index) => {
     const item = menu.items[index];
+      alert('Twilly ' + item + ' ' + menuitem + '<<<' + index + '>>>');
     menuitem.onclick = () => {
       item.click();
       popup.hidePopup();

```

The Twilly alert never happens. It's strange that .forEach() is not there.

**Comment by shlomif** [comment]
I've now checked it in chromium-browser, and the symptoms of this bug do not happen there - "Add Breakpoint" does what it should and dismissed the popup and I'm getting two "Twilly" alerts.

**Comment by shlomif** [comment]
Just for the record, .forEach() on an array reference works as expected in the firefox web console:

```
["foo", "bar", "quux"].forEach((x, i) => { console.log(x + "<<" + i + ">>"); })
undefined
foo<<0>>
bar<<1>>
quux<<2>>
```

**Comment by shlomif** [comment]
As discussed on #devtools on irc.mozilla.org, it turns out that Firefox 49.x and below do not support the `.forEach()` method for NodeList - see https://developer.mozilla.org/en-US/docs/Web/API/NodeList . firefox 50 and above and the current chromium-browser should be ok. Now the question is - whether we want to support "older" browsers or not.

**Comment by jasonLaster** [comment]
ahh - that makes sense.

I don't think we want to support Firefox 49. Thanks for reporting though

**Comment by shlomif** [comment]
On Sun, 20 Nov 2016 11:58:06 -0800
Jason Laster <notifications@github.com> wrote:

> ahh - that makes sense.
> 
> I don't think we want to support Firefox 49. Thanks for reporting though
> 

Got you! Fair enough - I'll use later firefoxen.
