### ISSUE TITLE
Don't set string [object object] after opening search box

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#1173]
**Steps to Reproduce:**
1. Start latest Nightly
2. Open Debugger (Ctrl+Shift+S)
3. Click [+] button > Search box is opened
4. Close search box
5. Click [+] button again

**Actual Results:**
String "[object object]" is set at search box.

![do-not-set-string- object object -after-opening-searchinput](https://cloud.githubusercontent.com/assets/13914314/20240834/08a6a9aa-a966-11e6-91bf-f6f50bd53daa.png)

**Expected Results:**
Don't set string "[object object]" at search box automatically.

**Comment by kareniel** [comment]
I'm taking a look at this right now. I should have a fix by the end of the day :)

**Comment by jasonLaster** [comment]
This was done in #1185
