### ISSUE TITLE
[File Search] Cmd+F should open the search bar with the editor selection

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1177]
When the editor has a text selection, `<cmd>+f` should open the editor search bar with the user selection.

Feel free to play with other editors, chrome and our old firefox debugger had this behavior.

Here's a sketch of a possible solution. I did a quick search of the [codemirror](https://codemirror.net/doc/manual.html) docs for getting the user selected text. This could easily be wrong. For instance, our old editor used [getSelection](https://dxr.mozilla.org/mozilla-central/source/devtools/client/sourceeditor/editor.js#952).

```diff
diff --git a/public/js/components/EditorSearchBar.js b/public/js/components/EditorSearchBar.js
index 3fafa36..ec78704 100644
--- a/public/js/components/EditorSearchBar.js
+++ b/public/js/components/EditorSearchBar.js
@@ -85,13 +85,27 @@ const EditorSearchBar = React.createClass({
     this.setState({ enabled: !this.state.enabled });

     if (this.state.enabled) {
-      const node = this.searchInput();
-      if (node) {
-        node.setSelectionRange(0, node.value.length);
-      }
+      const selection = this.editor.codeMirror.singleSelection();
+      this.setSearchValue(selection)
+      this.selectSearchInput();
     }
   },

+  setSearchValue(value: string) {
+    if (value == "") {
+      return;
+    }
+
+    this.searchInput().value = value;
+  },
+
+  selectSearchInput() {
+    const node = this.searchInput();
+    if (node) {
+      node.setSelectionRange(0, node.value.length);
+    }
+  }
+
   searchInput() {
     return findDOMNode(this).querySelector("input");
   },
```

### GIF of this behavior in the old Firefox Debugger

![](http://g.recordit.co/dnbVkZc7GF.gif)

**Comment by clarkbw** [comment]
@jasonLaster approximate difficulty?

**Comment by jasonLaster** [comment]
Medium

I'll sketch it tomorrow
