### ISSUE TITLE
[Storybook] rm storybook

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1192]
We haven't been using storybook for some time and a lot of the work has fallen out of date. This might be controversial, but I recommend that we remove Storybook for the time being and then we can evaluate re-adding storybook in some cases that now make sense.

For instance:
* we have several components that do not use much state (autocomplete, search box)
* we have some components that could use unit tests perhaps (call stack), with the expand row.

Removing storybook:
* would let us remove many if not all of the fixtures
* stop recommending it in the docs
* provide a clean slate to start anew

**Comment by clarkbw** [comment]
I agree, I was going to write up this same issue.

**Comment by wldcordeiro** [comment]
I support this. If we're going to keep it around we should keep it up to date, otherwise it's just extra baggage to confuse people.
