### ISSUE TITLE
Document directory structure for contributors

### ISSUE THREAD

**Issue by Garbee** [devtools-html/debugger.html#1195]
The lerna and sub-package setup can be pretty wonky for people that aren't used to it. A good way to help make things simpler for people in the future (especially as people are looking at tooling issues) is a quick document on the directory structure. Just a quick glance at what should be in what folders with a quick description.

A quick tree (depth 2 and ignoring node_modules) yields:

```
.
├── bin
├── docs
│   ├── images
│   ├── reference
│   └── screenshots
├── packages
│   ├── chrome-remote-debugging-protocol
│   ├── devtools-config
│   ├── devtools-local-toolbox
│   ├── devtools-modules
│   ├── devtools-network-request
│   └── devtools-sham-modules
└── public
    ├── build
    ├── images
    └── js
```

I'd say this would be the upper-level of directories to describe the contents.

**Comment by wldcordeiro** [comment]
The structure is about to change quite a lot based on #1184 but I do support having some documentation of what the structure is like and what lives where.

**Comment by jasonLaster** [comment]
This is a great idea. 

I often find that one of the first things I do in a new project is grok the structure.

Here's the new structure
```
.
├── bin
├── docs
│   ├── images
│   ├── reference
│   └── screenshots
├── packages
│   ├── chrome-remote-debugging-protocol
│   ├── devtools-config
│   ├── devtools-local-toolbox
│   ├── devtools-modules
│   ├── devtools-network-request
│   └── devtools-sham-modules
└── assets
 |  ├── build
 |  ├── images
└── src
    ├── actions
    ├── components
```

Couple points:

* the packages directory will likely move to it's own repo in a month. There's nothing there that is *debugger* specific and as other tools go to github they will be shared. 
* I'll be pushing a toolbox improvement to make it usable for the console inspector soon and that will also change the structure a bit. 
* we should document the debugger's app structure separately. We have @JasonWeathersby's Debugger doc that is very good. The scope of this work in mind is to provide context for the entire project and how it works and not necessarily the react/redux app.

**Comment by jasonLaster** [comment]
I removed the up for grabs label as one of us should write it :)

**Comment by jasonLaster** [comment]
FYI: I'll be moving the packages directory out soon.  

Also, the bin script is going to get smaller soon as scripts move to the local toolbox

Also, we're now adding more README.mds to directories like docs.

With all of that said, I've talked myself into closing this ticket.

@Garbee et al, feel free to re-open with specific proposals though
