### ISSUE TITLE
[Docs] Update Enhancement suggestions

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1227]
Our docs currently suggest that people file an issue with the enhancements label.

Is that still what we prefer now that we have a project? I think it is, but it is a little weird.

The reason I think it is good this way is that we will still have an issue that tracks the discussion, which can't happen in a note. It's a little awkward that the issue is closed, but that might be the best we can do.

* [Enhancement Project](https://github.com/devtools-html/debugger.html/projects/5)
* [Suggesting enhancements](https://github.com/devtools-html/debugger.html/blob/master/CONTRIBUTING.md#suggesting-enhancements-new)

Questions:
- Should we update the docs to mention that we have a project
- Should we update the docs to mention that we will close the issue, but still discuss
- Should we reconsider the RFC repo? I don't think we should yet as we're not ready to ramp up on taking action on these discussions and this is more of a team decision, which can be put off until we've resolved where the M-C Github question.

**Comment by clarkbw** [comment]
That makes sense to me.  👍

**Comment by jasonLaster** [comment]
closing this for now as we're tracking enhancements decently well and I don't mind closing issues now and moving them to enhancements. seems to be fine...

let me know if you have thoughts though.
