### ISSUE TITLE
Cannot identify menuitem for "Add Breakpoint" and "Remove Breakpoint" as using same id "node-menu-breakpoint"

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#1228]
Cannot identify the following menuitems...

 #node-menu-breakpoint as "Add Breakpoint" 
 #node-menu-breakpoint as "Remove Breakpoint"

#node-menu-conditional-breakpoint as "Add Conditional Breakpoint"
#node-menu-conditional-breakpoint as "Edit Breakpoint"

**Expected Results:**
Define different Id or different class.

**Comment by clarkbw** [comment]
Looks like we need to alter the id used here: https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor.js#L225-L261

**Comment by jasonLaster** [comment]
Thanks @magicp-github. 

I'm curious what use case did you run into here?

**Comment by magicp-github** [comment]
Hello @jasonLaster,
Firstly, I confused this debugging of new debugger in foreign language Firefox (e.g. Arabic). I am checking any elements by Id or class, because I cannot read Arabic.
Secondly, I could not add context menu icons correctly. Context menu icons helps me in foreign language.
