### ISSUE TITLE
[File Search] Remove outlines

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1234]
We should remove the search outlines when the search bar is closed.

#### Sketch:

```diff
diff --git a/src/components/EditorSearchBar.js b/src/components/EditorSearchBar.js
index 306c66b..1125958 100644
--- a/src/components/EditorSearchBar.js
+++ b/src/components/EditorSearchBar.js
@@ -86,6 +86,8 @@ const EditorSearchBar = React.createClass({
       const selection = this.props.editor.codeMirror.getSelection();
       this.setSearchValue(selection);
       this.selectSearchInput();
+    } else {
+      this.search("");
     }
   },
```

#### Gif
![](http://g.recordit.co/kLewlSTlZj.gif)

**Comment by arthur801031** [comment]
@jasonLaster  May I work on this? I'm a first time contributor to debugger.html.

**Comment by wldcordeiro** [comment]
@arthur801031 go for it. It's always great to get new contributors.

**Comment by clarkbw** [comment]
Its yours @arthur801031 be sure to reach out when you have any questions! 🎉

**Comment by arthur801031** [comment]
@wldcordeiro  @clarkbw 
I don't know what's the shortcut key for bringing up the file search bar.

I tried "cmd+f", and it gave me a normal search bar:
<img width="1227" alt="screen shot 2016-11-18 at 3 32 30 pm" src="https://cloud.githubusercontent.com/assets/4562118/20422276/5a1778ae-ada4-11e6-8d56-a97949b83a32.png">

I also tried "cmd+p", and it gave me this:
<img width="1223" alt="screen shot 2016-11-18 at 3 35 29 pm" src="https://cloud.githubusercontent.com/assets/4562118/20422333/adc92c90-ada4-11e6-9288-8e9d2cc821da.png">

Thank you!

**Comment by jasonLaster** [comment]
Great question @arthur801031. You need to run the [debugger locally](https://github.com/devtools-html/debugger.html/blob/master/CONTRIBUTING.md) and then you can do cmd+f.

You also need to enable editorSearch [configs](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#configs)

**Comment by jasonLaster** [comment]
@bomsy do you have an idea a good idea for how this might be done?

**Comment by arthur801031** [comment]
@jasonLaster @clarkbw @wldcordeiro  I've added the code to remove outlines. Please check. Thank you very much! :)
