### ISSUE TITLE
Getting setup on windows

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1248]
Hey, @viswanathamsantosh mind sharing some of the issues you were seeing getting setup with windows 10. 

I imagine some of the potential issues could be with:
* node
* npm
* yarn
* lerna (symlinks)

Potentially hyperterm could help

CCing - @clarkbw @auchenberg @Garbee so they can help if there are concrete issues

**Comment by viswanathamsantosh** [comment]
![yarn1](https://cloud.githubusercontent.com/assets/3799600/20441831/1ba828fa-adec-11e6-9408-2d770f1ecee0.JPG)
Running 
Node 5.6
Npm  4.0.1
Yarn 0.16.1
but got this error!

**Comment by Garbee** [comment]
The preinstall script is bash-only right now. So only UNIX systems can handle it. We need to investigate writing that script within node itself so we can make it platform-independent. This goes for all of the non-js bins we have.

**Comment by jasonLaster** [comment]
@viswanathamsantosh try dropping the preinstall

```diff
diff --git a/package.json b/package.json
index 9f2444b..7543507 100644
--- a/package.json
+++ b/package.json
@@ -31,8 +31,7 @@
     "prepush": "npm run lint; node src/test/node-unit-tests.js --dots",
     "storybook": "start-storybook -p 6006",
     "build-storybook": "build-storybook",
-    "flow-coverage": "flow-coverage-report -i 'src/actions/*.js' -i 'src/reducers/*.js' -i 'src/utils/*.js' -t html -t text",
-    "preinstall": "./bin/preinstall"
+    "flow-coverage": "flow-coverage-report -i 'src/actions/*.js' -i 'src/reducers/*.js' -i 'src/utils/*.js' -t html -t text"
   },
   "dependencies": {
     "codemirror": "^5.1.0",
```

and then manually running 

```
  npm i -g jasonlaster/lerna
  lerna bootstrap
  yarn install
```

**Comment by Garbee** [comment]
Setting things up on a new system, the preinstall script is also failing on Linux machines. I had to do a manual `npm i jasonlaster/lerna` before `yarn install` would work.

**Comment by jasonLaster** [comment]
Hmm. What was the error?

**Comment by Garbee** [comment]
Line 8 of `preinstall` was causing the failure. I'll look into trying to make this script a thing of the past by building it into the package install flow in `package.json`. I don't see why it is necessary right off. By removing this we'll also get built-in Windows support to makes things easier there.

**Comment by jasonLaster** [comment]
@Garbee perhaps we do `postinstall: "lerna bootstrap"`

**Comment by Garbee** [comment]
Yup, looking into this now that the flexbox footer PR is updated.

**Comment by Garbee** [comment]
PR #1264 is open for addressing that problem. Moving bootstrap to postinstall is exactly what was needed.

**Comment by jasonLaster** [comment]
Closing this for now as i think it's addressed

@viswanathamsantosh please ping if you see other issues

**Comment by jasonLaster** [comment]
Talked to @viswanathamsantosh offline and he mentioned issues with

```
`"C:\Program Files (x86)\Mozilla Firefox\firefox.exe" -start-debugger-server 6080 -P development`
```

> I didn't get any error but the firefox didn't start either. Any thoughts?

@Garbee

**Comment by Garbee** [comment]
>`"C:\Program Files (x86)\Mozilla Firefox\firefox.exe" -start-debugger-server 6080 -P development`

Perhaps `--start-debugging-server` ?

**Comment by jasonLaster** [comment]
Also @auchenberg, @clarkbw  thoughts?

Our docs recommend
https://github.com/devtools-html/debugger.html/blob/master/CONTRIBUTING.md#open-the-debugger

```
C:\Program Files (x86)\Mozilla Firefox\firefox.exe -start-debugger-server 6080 -P development
```

and our driver [has](https://github.com/devtools-html/debugger.html/blame/master/bin/firefox-driver.js#L22-L28)

**Comment by viswanathamsantosh** [comment]
`--start-debugging-server` worked perfectly for me now! Thank you jason. :D

**Comment by jasonLaster** [comment]
oh great. perhaps we need to update the driver then to use two dashes. Mind making a PR for that so you can run 

```
npm run firefox
```

We can discuss the tradeoffs in the PR

**Comment by clarkbw** [comment]
> Also @clarkbw thoughts?

Strange, I thought we tested the single dash but now that I look at my windows box I can see it definitely needs the double dash.

Thanks for finding this!

**Comment by clarkbw** [comment]
Most of the issues here are fixed up.  And as of #1309  `npm run firefox` works on Windows.  I'm going to close this for now and we can open up a new issue to investigate further issues.   Thanks a lot everyone!

**Comment by Romanbozeman** [comment]
if this does not work on Windows, then a "Prerequisite Disclaimer" should be included. Why did I just spend an hour installing this SH#T
