### ISSUE TITLE
[Scopes] Show optimized out variables

### ISSUE THREAD

**Issue by jlongster** [devtools-html/debugger.html#1250]
Pulled in from https://bugzilla.mozilla.org/show_bug.cgi?id=1318164.

Right now we explicitly filter out optimized out variables in the object inspector. We should show them but have a message that they are optimized out instead. I'll probably work on this soon because I haven't fixed any small things recently, and it shouldn't be too hard.

**Comment by jasonLaster** [comment]
#1330
