### ISSUE TITLE
sourcemapped breakpoints sliding up by one

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1252]
I've been thinking I'm crazy but because this happens no matter where in the code I try to set a breakpoint I feel like this might actually be a systematic error with how we handle lines in the editor and pass that back to set a breakpoint.

I can't make this happen in the `increment` test page.  But if I run the debugger on something and then run the debugger on our debugger I can reproduce this every time.

Here's a gif of it in action, I'm looking in the `actions/sources` module.

![breakpoints sliding up](https://cloud.githubusercontent.com/assets/2134/20445706/07807c8a-ad8b-11e6-9b06-36ed29ecfd1b.gif)

**Comment by jasonLaster** [comment]
Hmm, strange. This could likely be a bug in our webpack setup perhaps...

I'm going to change the issue title until we can generalize it

**Comment by clarkbw** [comment]
Here's another simpler test case: http://wbamberg.github.io/example-websites/source-mapping/index.html

**Comment by jasonLaster** [comment]
Thanks! Let's fix the issue title
