### ISSUE TITLE
Fix :hover background-color of breakpoint class in dark-theme

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#1287]
**Steps to Reproduce:**
1. Start Nightly
2. Go to any sites (e.g. about:home)
3. Open Debugger with the dark-theme
4. Open any sources
5. Add some breakpoints
6. Hover on breakpoint list

**Actual Results:**
:hover background-color is not different from non-hover one.

![fix-hover-background-color-of-breakpoint-class-in-dark-theme](https://cloud.githubusercontent.com/assets/13914314/20533977/d79417a2-b122-11e6-958e-8e08e7c3b77c.png)

**Expected Results:**
:hover background-color needs more contrast color.

**Comment by jasonLaster** [comment]
Thanks @magicp-github

**Comment by shlomif** [comment]
I'll try to tackle it.

**Comment by shlomif** [comment]
this seems to be OK in commit bc99a6ca3b4f9443fda8a27d5f92371cabfd6281 without any changes. See my screencast at http://www.shlomifish.org/Files/files/video/debugger-dot-html--issue-1287.ogv .

**Comment by clarkbw** [comment]
@shlomif which commit? I think that was a copy / pasta

**Comment by shlomif** [comment]
@clarkbw  : 

```
shlomif[debugger.html]:$trunk$ git show
commit bc99a6ca3b4f9443fda8a27d5f92371cabfd6281
Author: Fernando Montoya <montogeek@gmail.com>
Date:   Tue Nov 22 15:33:07 2016 -0500

    Update CONTRIBUTING.md (#1289)

    * Update CONTRIBUTING.md

    * Update CONTRIBUTING.md

diff --git a/CONTRIBUTING.md b/CONTRIBUTING.md
index 0b5f2b8..8c4e0f0 100644
--- a/CONTRIBUTING.md
+++ b/CONTRIBUTING.md
@@ -363,7 +363,7 @@ For a list of all the configuration options see the [packages/devtools-config/RE

 ### Create a local config file

-* Copy the [`packages/devtools-config/configs/development.json`](./packages/devtools-config/configs/development.json) to `packages/devtools-config/configs/local.json`
+* Copy the [`configs/development.json`](./configs/development.json) to `configs/local.json`

 ## Issues and Pull Request labels

shlomif[debugger.html]:$trunk$
```

on the master branch. Running the debugger there with the dark theme yields a different hover background on breakpoints, which seems to indicate this issue was already remedied.

**Comment by jasonLaster** [comment]
Hmm. This might be something that is unique to the Firefox panel. We should
check nightly.

**Comment by magicp-github** [comment]
My guess is that "--theme-search-overlays-semitransparent" variable is not available in dark-theme.

![theme-dark-variables](https://cloud.githubusercontent.com/assets/13914314/20606071/f6a9d1d2-b2b1-11e6-982f-b116e4e3404e.png)
