### ISSUE TITLE
add "Reveal in Sources" item to the tab context menu

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1290]
This is a feature I use and like in Chrome.  I started down the path toward making this happen and then realized this might be harder than it originally looked as I don't see an easy way to pass the tab id back over to the sources tree.

Also, at a higher level I wonder if when you search for a file we should match opening the file with expanding the tree.  I think in a number of cases that interaction could break down, but at least in the initial case it is the behavior I want.

This just adds the menu item.  After that you need to figure out how you're going to pass a function from the tree down to the `SourceTabs`.

```diff
diff --git a/src/components/SourceTabs.js b/src/components/SourceTabs.js
index 20a7e8e..3259a31 100644
--- a/src/components/SourceTabs.js
+++ b/src/components/SourceTabs.js
@@ -114,7 +114,17 @@ const SourceTabs = React.createClass({
       click: () => closeTabs(tabs)
     };
 
+    const revealInSourcesMenuItem = {
+      id: "node-menu-reveal-in-sources",
+      label: L10N.getStr("sourceTabs.revealInSources"),
+      accesskey: "R",
+      disabled: false,
+      click: () => { /* setExpanded(tab) */ }
+    };
+
     showMenu(e, buildMenu([
+      { item: revealInSourcesMenuItem },
+      { item: { type: "separator" }},
       { item: closeTabMenuItem },
       { item: closeOtherTabsMenuItem, hidden: () => tabs.size === 1 },
       { item: closeTabsToRightMenuItem, hidden: () =>
diff --git a/src/strings.json b/src/strings.json
index a77308c..3ea14cb 100644
--- a/src/strings.json
+++ b/src/strings.json
@@ -40,5 +40,6 @@
   "sourceTabs.closeOtherTabs": "Close others",
   "sourceTabs.closeTabsToRight": "Close tabs to the right",
   "sourceTabs.closeAllTabs": "Close all tabs",
+  "sourceTabs.revealInSources": "Reveal in Sources",
   "loadingText": "Loading\u2026"
 }
```

![screen shot 2016-11-22 at 2 10 59 pm](https://cloud.githubusercontent.com/assets/2134/20544190/a6c3d302-b0bd-11e6-9e2c-01ece9e61ad4.png)

Here's what I have in case someone else wanted to pick this up.

**Comment by jasonLaster** [comment]
CC @arthur801031  might be fun

```diff

diff --git a/src/utils/sources-tree.js b/src/utils/sources-tree.js
index 9c85739..9dd63d3 100644
--- a/src/utils/sources-tree.js
+++ b/src/utils/sources-tree.js
@@ -257,6 +257,8 @@ function createTree(sources: any) {
   for (let source of sources.valueSeq()) {
     addToTree(uncollapsedTree, source);
   }
+
+  // => perhaps the solution is in this code...
   const sourceTree = collapseTree(uncollapsedTree);

   return { uncollapsedTree,
```

**Comment by arthur801031** [comment]
@jasonLaster I will take a look at this tomorrow! :)

**Comment by arthur801031** [comment]
Hi @jasonLaster @clarkbw 

I'm not sure where to pass a reference of the sources tree to `SourceTabs.js`. I've looked at `SourcesTree.js`, `sources-tree.js`, `tree.js`, `ManagedTree.js`, and `Sources.js`, and I'm still confused... Please help. Thank you!

**Comment by jasonLaster** [comment]
Hey @arthur801031 that's a genuinely difficult problem :)

I recommend doing this to get `revealSource` working and we can brainstorm a good approach on thursday.

Generally, I'm not sure what the best way for one react component to talk to another is if not through redux. @jlongster any suggestions?


```diff
diff --git a/src/components/SourceTabs.js b/src/components/SourceTabs.js
index 20a7e8e..e627640 100644
--- a/src/components/SourceTabs.js
+++ b/src/components/SourceTabs.js
@@ -114,6 +114,16 @@ const SourceTabs = React.createClass({
       click: () => closeTabs(tabs)
     };

+    const revealSource = {
+      id: "node-menu-close-all-tabs",
+      label: closeAllTabsLabel,
+      accesskey: "A",
+      disabled: false,
+      click: () => {
+        tree.revealSource(tab.url);
+      }
+    };
+
     showMenu(e, buildMenu([
       { item: closeTabMenuItem },
       { item: closeOtherTabsMenuItem, hidden: () => tabs.size === 1 },
diff --git a/src/components/SourcesTree.js b/src/components/SourcesTree.js
index fe5ce95..37978b1 100644
--- a/src/components/SourcesTree.js
+++ b/src/components/SourcesTree.js
@@ -139,6 +139,7 @@ let SourcesTree = React.createClass({
       onFocus: this.focusItem,
       renderItem: this.renderItem
     });
+    window.tree = tree;

     return dom.div({
       className: "sources-list",
diff --git a/src/components/utils/ManagedTree.js b/src/components/utils/ManagedTree.js
index 289dc2b..6cada38 100644
--- a/src/components/utils/ManagedTree.js
+++ b/src/components/utils/ManagedTree.js
@@ -29,6 +29,10 @@ let ManagedTree = React.createClass({
     }
   },

+  revealSource(url) {
+    // ...
+  },
+
   focusItem(item) {
     if (!this.props.disabledFocus && this.state.focusedItem !== item) {
       this.setState({ focusedItem: item });
```

**Comment by jlongster** [comment]
> Generally, I'm not sure what the best way for one react component to talk to another is if not through redux. @jlongster any suggestions?

You're not really supposed to. The closest you should get is passing props down that happen to affect the state.

You should somewhere maintain state that is a list of sources that should be opened in the source tree, and then pass it down into the tree as items that it should make sure are expanded. This is transient state: a later rendering of a different list will not force the other sources to be closed, you're just telling the source tree "make sure these nodes are expanded".

You'll need to add that functionality to the `ManagedTree`. Take an array of items and make it automatically add those to the `expanded` local state.

Now it's a question of where you store this list. It's probably easiest to do it in redux. You could probably add it to the `ui` reducer, and then it's just a matter of creating a new action and making the `SourceTree` subscribe to it.

The tree API doesn't support explicitly expanding a specific item, so we'll have to add it.

**Comment by jasonLaster** [comment]
Thanks, one point here is that having the state in `redux` means that if the source tree is re-rendered it will expand to that source.

We can always clear that value later too.

**Comment by jlongster** [comment]
That's a good point. This is a problem generally with transient state. We'll have to think of a way to solve it. Sometimes there is a better way to structure things but I can't think of a way off the top of my head.

It's OK to use refs sometimes in the parent, but reaching across the entire tree like this is just wrong. It breaks encapsulation of the component. There is a lot out there on transient state with redux so we could look at patterns that others are using.

Another option would be for the source tree to simply not use `ManagedTree`, but use `Tree` instead and store the tree state in redux. That way you're free to manipulate it however you please. `SourceTree` would then use actions and such to expand items.

**Comment by arthur801031** [comment]
Hi @jasonLaster @jlongster 

I just finished adding:
1. Storing a list of items that should be expanded in redux.
2. A functionality in `ManagedTree` that takes an array of items and add those to the `expanded` local state, which would expand those folders.

Problem:
I’m trying to call the function that I mentioned in 2. in `SourcesTree.js render`, but I haven’t been able to make this work. `SourcesTree.js render` is also where I retrieve the file path and determine the list of items that should be expanded. Please let me know if there’s any way that I can call 2. in `render`. Thank you very much!!

**Comment by jasonLaster** [comment]
Hmm, this *does* sound difficult :)

> Storing a list of items that should be expanded in redux.

* I just merged the reveal tree PR. 
* I don't think you need the list of items in redux. It can be state in the sources tree component.
Perhaps set the state in componentDidUpdate


```js
componentDidUpdate(newProps, oldProps) {
   newProps.shownSource != oldProps.shownSource // yay new thing to reveal
   this.setState("list of things", ...) 
}
```

**Comment by arthur801031** [comment]
Hi @jasonLaster

I got it working! But I'm failing a test in`src/utils/tests/sources-tree.js`. I'm trying to debug the code in this test file. Could you help me out with node testing/debugging in Thursday's office hours if I haven't resolved the issue before then?

Thank you!!

**Comment by jasonLaster** [comment]
Hmm, I'm traveling this week so i wont be at office hours. Happy to pull it down locally tomorrow and try though

**Comment by jasonLaster** [comment]
done in #1403
