### ISSUE TITLE
Cleanup duplicate styles in debugger.css

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#1292]
The following styles are duplicated in styles.css .

[devtools/client/debugger/new/styles.css]

:root.theme-light,
:root .theme-light {...

* {...

html,
body {...

#mount {...

.search-container {...

.search-container .autocomplete {...

.welcomebox {...

.objectBox-object {...

.objectBox-string,
.objectBox-text,
.objectLink-textNode,
.objectBox-table {...

.objectBox-null,
.objectBox-undefined,
.objectBox-hint,
.logRowHint {...

.objectLink-event,
.objectLink-eventLog,
.objectLink-regexp,
.objectLink-object,
.objectLink-Date {...

.tree {...

.tree button {...

.tree .node {...

.tree .node.focused {...

html:not([dir="rtl"]) .tree .node > div {...

html[dir="rtl"] .tree .node > div {

.tree .node.focused svg {...

.tree-node button {...

.command-bar > span {...

html:not([dir="rtl"]) .command-bar > span {...

html[dir="rtl"] .command-bar > span {...

**Comment by madebymak** [comment]
Could not find the styles.css file containing: theme-light or objectLink-eventLog using grep in the root dir of the repository.Did a search and the only file called style.css was at /work/debugger/debugger.html/docs/reference/assets/styles.css . Has this issue been solved already?

**Comment by jasonLaster** [comment]
Thanks @madebymak. I think it is now `debugger.css`. in `assets/build`.

You can generate it with `yarn run publish-assets`
