### ISSUE TITLE
TypeError: bpClient is null bundle.js:20705:4 when disabling breakpoint

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#1296]
**Steps to Reproduce:**
1. Start Nightly (or Dev Edition)
2. Go to about:home
3. Open Debugger (Ctrl+Shift+S)
4. Open a source about:home > (index)
5. Add new breakpoint on line 17
6. Click "Disable Breakpoints" button or check-off the breakpoint in breakpoint list

**Expected Results:**
"Disable Breakpoints" does not work. And also the following error is displayed in console.
![bpclient-is-null](https://cloud.githubusercontent.com/assets/13914314/20575083/1b7e12dc-b1fb-11e6-9875-98d2411a4a90.png)

TypeError: bpClient is null	bundle.js:20705:4

**Actural Results:**
"Disable Breakpoints" works well and no error in console.

**Comment by clarkbw** [comment]
Odd that lines other than 17 don't behave this way...

I tracked this down to here: https://github.com/devtools-html/debugger.html/blob/master/packages/devtools-local-toolbox/src/clients/firefox/commands.js#L80-L84

It seems the `remove()` function is failing for some reason.

**Comment by magicp-github** [comment]
Oops. mistyped below;;
> Expected Results:
Actual Results:
> Actual Results:
Expected Results:

**Comment by magicp-github** [comment]
Oops. mistyped below;;

>   Expected Results:  > Actual Results:

>   Actual Results:  > Expected Results:

**Comment by clarkbw** [comment]
I'm not able to reproduce this on Nightly anymore. The disable breakpoint works just fine on line 17 now.  Please reopen this if we're able to reproduce again.
