### ISSUE TITLE
Format chrome variables

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1298]
We are currently making lots of progress on running the Node standalone debugger #1230 
. The major shortcoming is the ability to show closure scopes and variables.

This issue is for tracking the work needed to show a chrome variable

I created this [gist](https://gist.github.com/jasonLaster/e97be202b28f15175918fbb3eb3717a2) to get the ball rolling.

* loads the local variables into memor
* it comments out the firefox variable renderer
* it shows where the chrome data will eventually go (it's not ready yet)

Lets start playing with pulling in chrome's [frontend](https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/components/RemoteObjectPreviewFormatter.js#L43-L107) for formatting variables. And see how far we can get with some nice hacks.

CC @bomsy just created an issue for tracking the work related to formatting variables

**Comment by bomsy** [comment]
Nice one! i'll start hacking at this to see what we can come up with.

**Comment by jasonLaster** [comment]
Thanks for talking this through today @bomsy.

Here's the [branch](https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:chrome-vars) that we worked on.

The key here was:
* we fetched the local variables and associated it with the scope they were from. This will likely need to be parentId or some other field similar to what we do with firefox loaded objects
* we saved the loaded objects to the reducer
* we started fetching them in the component and got scared!

**Comment by bomsy** [comment]
@jasonLaster thanks! it was great, learnt alot.

**Comment by bomsy** [comment]
From my inital investigations, As seen [here](https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/components/RemoteObjectPreviewFormatter.js#L7) Chrome debugger frontend makes use an experimental [`preview`](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Runtime/#type-ObjectPreview) property object which exists on the [`RemoteObject`](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Runtime/#type-RemoteObject), as the main entry point for variables formatting.

The `RemoteObject` we get back from the scopeChain at the moment does not include the desired `preview` object as shown below.

	 "value": {
	   "type": "function",
	   "className": "Function",
	   "description": "function () {\n this.$el.remove();\n this.stopListening();\n returnthis;\n }",
	   "objectId": "{\"injectedScriptId\":2,\"id\":129}"
     },

i looked at the `protocol.json` it seems to be fine. Any ideas? 
@jasonLaster 

i'm still digging, might just figure it out. :)

**Comment by jasonLaster** [comment]
Hey @bomsy here's what i've got so far by the way

https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:chrome-vars?expand=1

**Comment by jasonLaster** [comment]
@bomsy i'm taking you off this as it's old and really hard :)

**Comment by bomsy** [comment]
cool!

**Comment by jasonLaster** [comment]
closing and we can open new focused issues later
