### ISSUE TITLE
Cannot resolve module 'chrome-remote-debugging-protocol'

### ISSUE THREAD

**Issue by arthur801031** [devtools-html/debugger.html#1303]
**Steps to Reproduce:**
I was several commits behind the master branch, so I fetched the latest changes from master:
`git remote add upstream https://github.com/devtools-html/debugger.html.git`
`git fetch upstream`
`git merge upstream/master`

**Expected Results:**
The debugger page should load when run `yarn start`

**Actural Results:**
When I ran `yarn start`, I got the following error message and the debugger page wouldn't open:
`Module not found: Error: Cannot resolve module 'chrome-remote-debugging-protocol' in /Users/i-chun/Documents/debugger.html_1/debugger.html/packages/devtools-local-toolbox/src/clients
 @ ./packages/devtools-local-toolbox/src/clients/chrome.js 3:15-58`

**Comment by bomsy** [comment]
Did you do a `yarn update` to update package dependencies?

**Comment by arthur801031** [comment]
I just realized that chrome-remote-debugging-protocol has been moved removed (#1263), so I downloaded chrome-remote-debugging-protocol from https://github.com/jasonLaster/chrome-remote-debugging-protocol and put that folder inside the packages folder, and it worked!

**Comment by arthur801031** [comment]
@bomsy  

`yarn upgrade` works! Thank you so much! :)

**Comment by jasonLaster** [comment]
Thanks @bomsy. 

Arthur, I meant to tell you because I ran into the same thing on your branch and just nuked the node modules sir and reinstalled. 

Yarn upgrade is the better solution though :)
