### ISSUE TITLE
[Editor] can't select the scrollbar

### ISSUE THREAD

**Issue by nt1m** [devtools-html/debugger.html#1311]
Note: this was originally reported from bugzilla (not from me)
From: https://bugzilla.mozilla.org/show_bug.cgi?id=1319743

Steps to reproduce:

1. Firefox Developer Edition
2. Open Developer Tools (CTRL + SHIFT + I)
3. Debugger tab (CTRL + SHIFT + S)
4. Minify an file and Prettify it's Source in order to have big space to scroll
5. Try to grab the scroll bar with the mouse pointer

Actual results:

Mouse pointer goes through scrollbar when I try to grab it.

http://screencast.com/t/rBZB1lTL

Expected results:

I want to be able to grab it in order to have a great experience.

**Comment by jasonLaster** [comment]
Thanks @nt1m for sharing. I noticed something last month that was similar in the panel, but not locally. Happy to investigate.

**Comment by jasonLaster** [comment]
renamed the issue to split out two duplicate issues. here's the new one #1562

**Comment by jasonLaster** [comment]
@tromey found: 

```
if I use the scroll wheel, then the cursor changes to an arrow, and when that happens I can grab the scrollbar
```

**Comment by clarkbw** [comment]
Possibly some CSS is causing the scrollbar to appear when its not actually visible.  On the Mac you need to start scrolling to see the scrollbar as normal behavior.

**Comment by jnachtigall** [comment]
afaics this should be fixed now by https://bugzilla.mozilla.org/show_bug.cgi?id=1265807

**Comment by jasonLaster** [comment]
Nice eagle eyes
