### ISSUE TITLE
Allow editing variables

### ISSUE THREAD

**Issue by bjorn3** [devtools-html/debugger.html#1313]

**Comment by jasonLaster** [comment]
Thanks for filing the issue @bjorn3.

I just added it to our Enhancements board https://github.com/devtools-html/debugger.html/projects/5

Out of curiosity, 
* when would you use this in the old debugger
* how often did you use this feature in the old debugger?

**Comment by abitrolly** [comment]
Looks like #6144 is a tracking issue.
