### ISSUE TITLE
[Editor] fix matched colors

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1315]
We currently change the color of the text matched when we search. If you look at other editors you'll noticed that they just rely on the search outline and overlay for the affect. And that is less jarring and more semantically correct.

The issue is that when we match the token for the search result we give the element a class name `cm-selecting` instead of what it would naturally have, which could be `cm-property`

This patch fixes the text color, but of course removes the `cm-selecting` class which we need for showing the outline. 

```diff
diff --git a/src/utils/source-search.js b/src/utils/source-search.js
index e2e112b..897846d 100644
--- a/src/utils/source-search.js
+++ b/src/utils/source-search.js
@@ -63,7 +63,6 @@ function searchOverlay(query) {
       let match = query.exec(stream.string);
       if (match && match.index == stream.pos) {
         stream.pos += match[0].length || 1;
-        return "selecting";
       } else if (match) {
         stream.pos = match.index;
       } else {
```

So the challenge is how do we have both classes :)

Also, one bonus question is can we also style the highlighted match color white so that it is more visible in dark theme? Treat this as extra credit as it's more important to first solve the general question and then we can fix this later...

### screenshots

![](http://g.recordit.co/CmRLrEuCw6.gif)
![](http://g.recordit.co/OHT3Se7C8B.gif)

CC @bomsy I believe you would have some context here.
CC @Zacqary I believe this is the kind of bug you might enjoy :)

**Comment by Zacqary** [comment]
Okay first of all, how do I open the Search in File box? ⌘+P lets me search for a filename, not within the current file

**Comment by jasonLaster** [comment]
Ahh good question, we're currently disabling editor search.

So you'll need to go to `configs/local.json` and add `editorSearch` to the list of features. You can compare this with `configs/development.json`. After that you can do Cmd+f :)

**Comment by Zacqary** [comment]
So am I missing something or is the fix actually this easy?
```diff
diff --git a/src/utils/source-search.js b/src/utils/source-search.js
index b12a675..c31bd1d 100644
--- a/src/utils/source-search.js
+++ b/src/utils/source-search.js
@@ -80,7 +80,7 @@ function searchOverlay(query) {
 function startSearch(cm, state, query) {
   cm.removeOverlay(state.overlay);
   state.overlay = searchOverlay(query);
-  cm.addOverlay(state.overlay, { opaque: true });
+  cm.addOverlay(state.overlay, { opaque: false });
 }
 
 /**
```

**Comment by jasonLaster** [comment]
haha - it might be that easy... what does opaque do?

**Comment by Zacqary** [comment]
From the [CodeMirror Docs](https://codemirror.net/doc/manual.html):

>cm.addOverlay(mode: string|object, ?options: object)
    Enable a highlighting overlay. This is a stateless mini-mode that can be used to add extra highlighting.


> opaque: bool
        Defaults to off, but can be given to allow the overlay styling, when not null, to override the styling of the base mode entirely, instead of the two being applied together.

Setting it to `false` retains the `cm-property` class and preserves the underlying text color.

So, yeah, I think that's it.

**Comment by jasonLaster** [comment]
oh sweet, i like it! PR it up

**Comment by Zacqary** [comment]
As for fixing the dark mode style, that's going to be more difficult to track down. 

When I highlight this:
![screen shot 2016-11-27 at 1 26 30 pm](https://cloud.githubusercontent.com/assets/1445834/20650793/21ac1206-b4a5-11e6-9fbd-571eed258e71.png)
it has the classes `cm-property cm-overlay cm-selecting`.

Then I highlight the next thing, and look at it again:
![screen shot 2016-11-27 at 1 27 11 pm](https://cloud.githubusercontent.com/assets/1445834/20650801/435d45a0-b4a5-11e6-9409-424d3c39e723.png)
but it still has the classes `cm-property cm-overlay cm-selecting`.

`cm-overlay` appears to be a class that CodeMirror is using internally, and has no style properties. `cm-selecting` provides the outline. It's unclear where the gray background is coming from, because the style of the `<span>` element containing `render` doesn't change at all when you select or deselect it. And I don't see any pseudo-elements immediately attached to it.

**Comment by jasonLaster** [comment]
👍  guess this wasn't so hard

**Comment by bomsy** [comment]
Interesting note!
Setting `opaque: false` causes the outlines for searched phrase to be split based on tokens. `opaque: true ` brings them together.
See https://github.com/devtools-html/debugger.html/pull/1318#issuecomment-263252063

**Comment by jasonLaster** [comment]
Hmm, will look into this later, but a quick check of Chrome's debugger and it looks like they have a solution with codemirror. Might be worth doing a quick check of what they do https://github.com/ChromeDevTools/devtools-frontend

![screen shot 2016-11-28 at 7 45 18 am](https://cloud.githubusercontent.com/assets/254562/20669743/cef33112-b543-11e6-857d-13de1eb7ce80.png)

**Comment by bomsy** [comment]
i had a quick peek .. This looks like the useful section in Chrome debugger code.
https://github.com/ChromeDevTools/devtools-frontend/blob/d8b14aea25a93cb6bbceb6aaaf45765c107d1fd9/front_end/source_frame/SourcesTextEditor.js#L727

**Comment by bomsy** [comment]
Off the top of my head,  i think we can fix with a smarter token function.

**Comment by jasonLaster** [comment]
fixed here https://github.com/devtools-html/debugger.html/pull/1318
