### ISSUE TITLE
Add Sidebar toggle buttons

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1317]
It'd be great to add sidebar toggle buttons for a couple of reasons:
1. They really help when the debugger is small
2. We're going to land Vertical Mode soon #1314 and toggling source is HUGE there

**Some product requirements:**
1. clicking the toggle button toggles the adjacent sidebar (open/closed)
2. opening the sidebar opens the sidebar to the previous stored width (it's a nice to have)

**Patch**
This patch is a hodgepodge of things. 
* @wldcordeiro worked on a redux motivated PR in august https://github.com/devtools-html/debugger.html/pull/668
* the inspector and other tools use a `togglePane` function that really helps
* This patch pulls in wellington's work to setup the toggle buttons in the top editor bar. It also pulls in the `togglePane` function and sets up the App.js call site with some copy pasta code that will NOT work :)

[patch](https://gist.github.com/jasonLaster/73374c356e150011786ecce2480acfd5)

```
curl https://gist.githubusercontent.com/jasonLaster/73374c356e150011786ecce2480acfd5/raw/69e9a8ad00404babcf1b2418778ff09924dd4e93/foo.diff | gist apply
```

**Note: I found two issues with the toggle buttons currently**
1. the right one overlays the hidden dropdowns button [img](https://cloud.githubusercontent.com/assets/254562/20649804/5c8a4b28-b495-11e6-9112-43f707e5bc2d.png)
2. they grow and shrink as the pane expands collapses [gif](http://g.recordit.co/YWdCxbBVAI.gif)

#### Screenshots
*Source selected*
![screen shot 2016-11-27 at 11 37 01 am](https://cloud.githubusercontent.com/assets/254562/20649826/de27e33e-b495-11e6-84a5-811ac5e603c1.png)

*No source selected*
![screen shot 2016-11-27 at 11 36 55 am](https://cloud.githubusercontent.com/assets/254562/20649827/de3168f0-b495-11e6-8a8d-b4d7ff2c0173.png)

**Comment by wldcordeiro** [comment]
I'll grab this since I had a prior patch. 😄

**Comment by jasonLaster** [comment]
Hey @wldcordeiro have you had a chance to look at this? happy to move it back to up for grabs

**Comment by wldcordeiro** [comment]
@jasonLaster working on this now. 😄 Have had some life stuff but I'll be pushing a PR soon.

**Comment by jasonLaster** [comment]
🎆
