### ISSUE TITLE
[Source Search] Performance is too slow for fast typing

### ISSUE THREAD

**Issue by Zacqary** [devtools-html/debugger.html#1319]
Here's a recording of what happens when I try to search for `render` at my normal typing speed:
![render](https://cloud.githubusercontent.com/assets/1445834/20650903/c812205c-b4a7-11e6-969b-51e36f6d55c2.gif)

It only picks up half the letters that I type because the callbacks triggered by each keypress are blocking the DOM.

The only workaround is to type really, really slowly.

**Comment by jasonLaster** [comment]
@Zacqary hmm, i think we also have a debounce here which is probably the problem

https://github.com/devtools-html/debugger.html/blame/master/src/components/EditorSearchBar.js#L176-L191

This should definitely be fixed!

**Comment by arthur801031** [comment]
@jasonLaster May I take a look at this? Thank you!

**Comment by arthur801031** [comment]
@jasonLaster  I have fixed the issue. Please check. Thank you! :)

**Comment by bomsy** [comment]
@Zacqary @jasonLaster We do the debounce so we don't have to search for every character typed. We did this to match the workflow of the other editors e.g atom. If the search is a heavy operation do we want to do it on every `keypress`?

**Comment by jasonLaster** [comment]
Hmm, @bomsy @arthur801031 is there a way to update the input as you type and *just* debounce the search function? This way we won't lose characters, but we won't be as distracting.

**Comment by Zacqary** [comment]
Don't have the code in front of me right now to check, but is the search box using a `value` instead of a `defaultValue`? If we're denouncing the search function that means the `value` of the field isn't necessarily going to match the search string currently stored in state at all times, so we shouldn't be having React override the `value` on every render.

That would create an issue with x-ing out the search box to clear it, I'm guessing. I'm wary to use `shouldComponentUpdate` because that's caused massive time-destroying bugs in my experience.

What if the search operation could be made into an asynchronous side effect instead? That way we wouldn't have to add any non-determinism by letting React stop tracking the `input` value.

Yes I just kind of argued with myself in these last three paragraphs but maybe that context is helpful.

**Comment by jasonLaster** [comment]
> What if the search operation could be made into an asynchronous side effect instead

👍

**Comment by bjorn3** [comment]
I experience slowness with just scrolling a 175676 byte file.

**Comment by jasonLaster** [comment]
@bjorn3 I believe that's a different issue, but also important.

**Comment by jasonLaster** [comment]
#1327 landed
