### ISSUE TITLE
[Editor Search Bar] Improve selection highlight

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1329]
Our current search selection has two issus:

1. It highlights each token separately [gif](https://cloud.githubusercontent.com/assets/792924/20667007/0479fbc0-b55f-11e6-826f-262315a101f8.gif)
2. the highlighted text needs to be white [screen](https://cloud.githubusercontent.com/assets/2848472/20470134/9969dc56-af73-11e6-880b-36987b13002c.png)

Both of these issues can be solved by improving how we do search tokenizing.

* Here is our current [implementation](https://github.com/devtools-html/debugger.html/blob/master/src/utils/source-search.js#L58-L74)
* Here is how chrome supports it [token highlighter](https://github.com/ChromeDevTools/devtools-frontend/blob/d8b14aea25a93cb6bbceb6aaaf45765c107d1fd9/front_end/source_frame/SourcesTextEditor.js#L727-L876)

As a side note, I think this is an interesting feature that should be its own codemirror npm package.
I'd be happy to help someone setup a `codemirror-token-highlighter` github repo and npm package, which we can then pull in and others can use.

**Comment by jasonLaster** [comment]
CC @Zacqary, @bomsy interested?

**Comment by bomsy** [comment]
i can take this!

**Comment by jasonLaster** [comment]
Hey @bomsy have you had a chance to look at this?

**Comment by bomsy** [comment]
looking at this now!
