### ISSUE TITLE
Update m-c files

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1333]
Here's a running list of M-C Files that should be changed soon. Bundling this so that we can do this at once.

+ [highlight colors](https://github.com/devtools-html/debugger.html/pull/1282)
+ [remove svgs](https://github.com/devtools-html/debugger.html/issues/1306)
+ [update window rep](https://github.com/devtools-html/debugger.html/issues/933) https://github.com/devtools-html/debugger.html/pull/912
+ [background hove color](https://github.com/devtools-html/debugger.html/issues/1287)

**Comment by jasonLaster** [comment]
Landing these changes in MC!

**Comment by clarkbw** [comment]
Nice!
