### ISSUE TITLE
[Docs] Contributing in the Community

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1339]
The new getting started [docs](https://github.com/devtools-html/debugger.html/pull/1334) drive people at the end to make a contribution. 

One of the possible contribution is to give a [talk](https://github.com/devtools-html/debugger.html/pull/1334/files#diff-09ad6502077560aa1d440e471440ab75R97). I think we can expand on that idea and add a *community* section to our [How can I contribute?](https://github.com/devtools-html/debugger.html/blob/master/CONTRIBUTING.md#how-can-i-contribute) doc. 

**give a talk** 
- we can list other slides
- walk through how a possible outline and some goals
- link to a doc where they can add their talk to a list

**organize an OSS workshop** 
- we can link to other planning docs
- walk through helpful strategies for planning 
  * how to budget three hours
  * how to break into issues and find issues

The beauty is that these things are already happening, so it's just a question of OSSing our private efforts

CC, @clarkbw, @viswanathamsantosh, @Garbee, @garrettgsb

**Comment by clarkbw** [comment]
> organize an OSS workshop

I can get this started on this with some help from the Vancouver tech podcast team

**Comment by ogryzek** [comment]
We have a meetup scheduled for [January 23rd](https://www.meetup.com/VancouverTechMeetup/events/235789664/). Will add more details as we decide on the venue & sponsors.

Planning on going through the resources linked above this week. Looks great so far!

**Comment by garrettgsb** [comment]
Right on-- I'll support Drew with organizing the meetup, and when I have some free time, I'll have a look at the Getting Started guide and give some thoughts on how the session could look.

**Comment by viswanathamsantosh** [comment]
I will have a meeting scheduled in January end with my community Reps to discuss more about this! we have been into different camps and initiatives like Rust, WebVR etc. and introducing this as an activity will give us more insights from the community.

**Comment by viswanathamsantosh** [comment]
Going through the documents:
*I really loved the restructuring of documents. they seem to be very clear
*# create a new terminal tab and # close firefox if it's already running : this comment will definitely solve the one mega problem for a newbie in getting started. two of the people i introduced this project got struck up here and this comment will help them now.
*Including images instead of using image links?
refer: line 41 in [getting-setup.md](https://github.com/devtools-html/debugger.html/blob/master/docs/getting-setup.md)
Any reason on why we open images in new tabs? I believe guides generally show the screenshots along with the instructions no?

**Comment by viswanathamsantosh** [comment]
When it comes to a talk, there are two possibilities of talks.
*one: a talk to contributors asking them to join our project and contribute. I believe we have enough resources in giving a talk and helping them to get involved.
*two: a talk to increase the User base. A talk giving them an overview of debugger.html, in what scenario is it useful? who is it for? a guide to debugging a webapp using this debugger? when to prefer devtools and when to prefer debugger.html? 
I m still not aware of how debugger.html should be preferred over devtools to debug my web applications. Having such guide would be really helpful to understand this webapp.

**Comment by jasonLaster** [comment]
> Including images instead of using image links

I didn't want to affect the readability... but i could be off here and maybe i crop them vertically too...

> a talk to contributors asking them to join our project and contribute

Yeah, I like the talk format where the subject is how the debugger works and the call to action is contribute.

> I m still not aware of how debugger.html should be preferred over devtools

:) I think this is a major bug in our documentation! The debugger.html project *is* the devtools debugger. I'll update the docs to make this more clear. I'll also add docs on how you can see your changes immediately in firefox, while it's rare and requires downloading and building firefox we should provide instructions on how to do it.

**Comment by jasonLaster** [comment]
@clarkbw interested in writing this up

@wldcordeiro lets get some talk links here:
@amitzur mind re-sharing your talk
lets also include my 
* you-gotta-love-the-frontend, 
* james' react talk
* @viswanathamsantosh do you have a talk link?

**Comment by viswanathamsantosh** [comment]
I don't have a talk link but a simple presentation< https://slides.com/isantoshv/devtools/fullscreen#/ > i used for my talk last week.
I spent most of the time demo'ing super cool things we can do with devtools instead of a presentation as my goal was to motivate the participants to use Firefox devtools instead of the rest.

**Comment by viswanathamsantosh** [comment]
I found a presentation made by a fellow speaker. it is more of a presentation we can use for a talk. Here goes the link < http://mte90.github.io/Talk-DevTools/ >

**Comment by jasonLaster** [comment]
Ping @clarkbw it'd be great to add your content on workshops and we can add some talk material too

**Comment by jasonLaster** [comment]
Yay! Really glad we added this :)
