### ISSUE TITLE
[Flow] Type the Editor component

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1340]
We recently added flow types to the [frames]() component and it really helped the code clarity. Also, I'm much more confident accepting PRs knowing that flow has my back.

It would be great to have similar flow checks for other components.

Here's a [patch](https://gist.github.com/jasonLaster/95dd7b5d79545d4e016f4c36ae36f931) for the Editor that i starterd.

```bash
curl https://gist.githubusercontent.com/jasonLaster/95dd7b5d79545d4e016f4c36ae36f931/raw/73d648697f0a100126e82824cdd1e121e7e01a63/foo.diff | git apply
```
Steps:
- [ ] add the `// flow` comment to the top of the file 
- [ ] add other types from the above patch 
- [ ] add code mirror types.

**Comment by montogeek** [comment]
Me 👯

**Comment by jasonLaster** [comment]
Hey @montogeek have you had a chance to take a stab at this?

If so, let me know if you're blocked or have any questions. happy to assist

**Comment by montogeek** [comment]
@jasonLaster I am so sorry, this week I am busy. I can start working on it this weekend

**Comment by jasonLaster** [comment]
no worries. not time sensitive :)

**Comment by jasonLaster** [comment]
ping @montogeek still have time to pick this up?

**Comment by jasonLaster** [comment]
@jacobjzhang are you interested in grabbing this

**Comment by jacobjzhang** [comment]
@jasonLaster I can grab this

**Comment by jacobjzhang** [comment]
@jasonLaster The vast majority of the typing for Editor.js is going to be around CodeMirror. What are your thoughts on integrating https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/codemirror types into the project? I'm not sure what the level of effort here would be.

**Comment by jasonLaster** [comment]
That makes sense. Or we can steal those types that are relevant

**Comment by jasonLaster** [comment]
Flow-typed is the main project for community flow types.

I don't see codemirror there so we might need to use anys.

Honestly that's fine, were not shooting for 100% coverage. This is the
first pass so we'd take decent coverage

**Comment by jasonLaster** [comment]
@jacobjzhang mind sharing the branch you were working on

**Comment by jacobjzhang** [comment]
@jasonLaster forgot to commit before switching branches so I lost my changes. Fortunately because of the scoping issues we talked about, didn't get much farther than your initial patch.

**Comment by jasonLaster** [comment]
Closing this as we recently added types to the SearchBar and learned a lot.

We can re-open new component flow issues later
