### ISSUE TITLE
Clicking "Open in Debugger" in inspector's ev popup opens empty debugger

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#1344]
STR:

1. Hover over a "ev" bubble to open event popup in Inspector
2. Click on the "Open in Debugger" link on the left

AR:
Opens bare/empty/uninitialized debugger with nothing open

ER:
Should open with right file open and jumped to the right function

I think this is something to track to reach feature parity with the old debugger. Do not know if this is rather a problem with the Inspector than Debugger tool though.

**Comment by jasonLaster** [comment]
CC @juliandescottes are you working on this?

**Comment by juliandescottes** [comment]
Looks like this is fixed on Nightly. We have been fixing a lot of issues on the event bubble recently, I'll try to find the bugzilla reference.

**Comment by juliandescottes** [comment]
I think this was fixed by [Bug 1315639](https://bugzilla.mozilla.org/show_bug.cgi?id=1315639) according to [comment 4](https://bugzilla.mozilla.org/show_bug.cgi?id=1315639#c4)

Closing.
