### ISSUE TITLE
[Watch Expressions] Improve Preview

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1350]
We currently show the entire object value when you're paused. We'd like to just show a tiny preview, with the ability to expand the value like you can do in the scope pane.

#### Patch

* I first tried just changing the rep mode to tiny and learned it wouldn't expand
* then I found the place in the scope pane where we build the ObjectInspector and left some notes there

```diff
diff --git a/src/components/Expressions.js b/src/components/Expressions.js
index cb979f2..67328ab 100644
--- a/src/components/Expressions.js
+++ b/src/components/Expressions.js
@@ -56,9 +56,9 @@ const Expressions = React.createClass({
       );
     }
     if (value.exception) {
-      return Rep({ object: value.exception });
+      return Rep({ object: value.exception, mode: "tiny" });
     }
-    return Rep({ object: value.result });
+    return Rep({ object: value.result, mode: "tiny" });
   },

   deleteExpression(e, expression) {
diff --git a/src/components/Scopes.js b/src/components/Scopes.js
index 280b647..8f96e70 100644
--- a/src/components/Scopes.js
+++ b/src/components/Scopes.js
@@ -167,6 +167,10 @@ const Scopes = React.createClass({

     let scopeInspector = info(L10N.getStr("scopes.notAvailable"));
     if (scopes) {
+      // => maybe we want to do something like this instead!
+      // either we have one inspector per expression
+      // or we have one inspector for all of the expressions,
+      // that might make it harder to edit an expression though...
       scopeInspector = ObjectInspector({
         roots: scopes,
         getObjectProperties: id => loadedObjects.get(id),
```

#### What we do now
![screen shot 2016-11-29 at 1 48 57 pm](https://cloud.githubusercontent.com/assets/254562/20724028/c08fa70c-b63a-11e6-9a33-41c5e001df50.png)

#### the preview in "tiny" mode
![screen shot 2016-11-29 at 1 48 00 pm](https://cloud.githubusercontent.com/assets/254562/20724027/c08ec8e6-b63a-11e6-9c22-b25e4d033f03.png)

**Comment by andreicristianpetcu** [comment]
Do you think I can pick this one up @jasonLaster ? Since I worked on [Watch Expressions] in the previous task.

**Comment by jasonLaster** [comment]
@andreicristianpetcu sounds great

**Comment by jasonLaster** [comment]
Hey @andreicristianpetcu have you been able to make progress on this?

If so, are you blocked by anything or have questions?

**Comment by andreicristianpetcu** [comment]
Sorry @jasonLaster but I did not have time. I was kind of busy lately. Nothing blocks me except that. I will ping you if I have any trouble.
If it is urgent and you want to give it to somebody else not problem then. I contribute when I can how much I can and I hope I do not slow down the project :)

**Comment by jasonLaster** [comment]
No worries, if it's okay I think I'm going to take this one over. I have some ideas about how i want to do some refactoring beforehand :)

We've got lots of other "bugs" and "up for grabs"

**Comment by andreicristianpetcu** [comment]
@jasonLaster Sure.... Pick it up if you wish. I'll just ping you when I have some time. I have some side projects that I need to finish before I dedicate more time to debugger.html.

**Comment by wldcordeiro** [comment]
I'll take this.

**Comment by jasonLaster** [comment]
@wldcordeiro nah - i want this one :)
