### ISSUE TITLE
[Source Tree] misses a filename

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1352]
https://github.com/devtools-html/debugger.html/issues/1098 listed some inconsistencies between chrome's source tree and firefox's.

One thing I found was that is that if the file name has a space and or is missing an extension, our algorithm thinks its a directory.

**Steps to reproduce:**
* go to localhost:8000
* in another tab go to localhost:8000 and debug the first tab (basically start inception)
* expand the webpack domain and observe the `webpack/bootstrap 5aa234` dir

**patch**

```diff
diff --git a/src/utils/sources-tree.js b/src/utils/sources-tree.js
index 9c85739..2c1adba 100644
--- a/src/utils/sources-tree.js
+++ b/src/utils/sources-tree.js
@@ -142,6 +142,8 @@ function addToTree(tree: any, source: TmpSource) {
   url.path = decodeURIComponent(url.path);

   const parts = url.path.split("/").filter(p => p !== "");
+
+  // this is should be smarter...
   const isDir = (parts.length === 0 ||
                  parts[parts.length - 1].indexOf(".") === -1);
   parts.unshift(url.group);
@@ -183,6 +185,7 @@ function addToTree(tree: any, source: TmpSource) {

   // Overwrite the contents of the final node to store the source
   // there.
+  // => this is likely where the problem is ...
   if (isDir) {
     subtree.contents.unshift(createNode("(index)", source.get("url"), source));
   } else {
```

### Our Debugger
![screen shot 2016-11-29 at 4 29 25 pm](https://cloud.githubusercontent.com/assets/254562/20729676/1086fff6-b651-11e6-8abb-857cef9fb7e6.png)

### Chrome Debugger
![screen shot 2016-11-29 at 4 30 06 pm](https://cloud.githubusercontent.com/assets/254562/20729698/253e3fae-b651-11e6-82ea-b6b335a3c1b7.png)

CC @amitzur  interested?

**Comment by jasonLaster** [comment]
@amitzur is working on this

**Comment by jasonLaster** [comment]
Hey @amitzur have you had a chance to look at this?
Are you blocked by anything that I can help with?

**Comment by amitzur** [comment]
Actually I meant to surface it before. I think the crux of the matter is how isDir is decided.
Unless I got something wrong, when going over the path, if current part is the last part, it should not be a directory unless it's the actual html file of the frame. Is there a way to detect that? Maybe by accessing the location of the associated frame/window?
Assuming anything on file name (e.g. has a ".") is clearly not the way.

**Comment by jasonLaster** [comment]
> Assuming anything on file name (e.g. has a ".") is clearly not the way
great point.

> it should not be a directory unless it's the actual html of the frame

perhaps we can check to see if the source's contentType is html. That way, we'll know if we're looking for this case

**Comment by jasonLaster** [comment]
Hey @amitzur I just looked into this and unfortunately a `source` does not have its contentType, but a `sourceText` does.

For example, if you update the todomvc example to have an inline script with a debugger statement, you'll see `(index)` in the tree. The source however does not have a contentType, but when you select the source and load the source text you see the type.

Based on this, I think the best thing to do is to compare the source URL with the debuggee URL and see if it is the index case or all the other cases where it's just a filename.

**Comment by jasonLaster** [comment]
Spoke with @jlongster and he had a good observation that we could take a more generic approach

```
something can only be directory if multiple files are inside of it
2:19 PM if `http://example.com/foo` is a source, always only show `foo` as a path. but if `/foo` and `/foo/bar.js` is a source, show two sources `foo/(index)` and `foo/bar.js`
2:19 PM you can never really know if something remote is a directory or not
2:20 PM I guarantee chrome just has similar fuzzy heuristics
a server could easily serve up `/foo` as a normal JS file, but also `/foo/bar.js` as a JS file, so both would have normal JS content types
```

**Comment by jasonLaster** [comment]
@amitzur moving this out of in progress. 

Feel free to re-claim if interested.

**Comment by jasonLaster** [comment]
@Garbee is on it

**Comment by jasonLaster** [comment]
Here's a re-write of the issue overview based on what we know now:

### Steps to Reproduce

1. Open localhost:8000
2. Open a new tab and select "localhost:8000: Debugger" (basically start inception)

#### Actual Result
Observe that in the "webpack://" domain we show a directory `webpack/bootstrap 5aa234` and file `(index)`

#### Expected Result
We would like to see a directory `webpack` and file `bootstrap 5aa234`

### How do we do this:

Well, there are plenty of traps here, but the key understanding is that our `sources-tree` utils logic should be smarter:

* Currently we assume a path part is a file if it's at the end and we see a period
* We should be smarter than that and say, we know a path part is a file if it's the last part and there aren't and there aren't any child files.

#### Examples

* bar file: `foo/bar` should become directory `foo` file `bar`
* index, `foo/bar`, `foo/bar/bazz` should become directories `foo/bar`, with files `(index)` and `bazz`. We know we need inex because `bar` in this case has a child file!

```patch
```diff
diff --git a/src/utils/sources-tree.js b/src/utils/sources-tree.js
index 9c85739..2c1adba 100644
--- a/src/utils/sources-tree.js
+++ b/src/utils/sources-tree.js
@@ -142,6 +142,8 @@ function addToTree(tree: any, source: TmpSource) {
   url.path = decodeURIComponent(url.path);

   const parts = url.path.split("/").filter(p => p !== "");
+
+  // this is should be smarter...
   const isDir = (parts.length === 0 ||
                  parts[parts.length - 1].indexOf(".") === -1);
   parts.unshift(url.group);
@@ -183,6 +185,7 @@ function addToTree(tree: any, source: TmpSource) {

   // Overwrite the contents of the final node to store the source
   // there.
+  // => this is likely where the problem is ...
   if (isDir) {
     subtree.contents.unshift(createNode("(index)", source.get("url"), source));
   } else {
```


### Our Debugger
![screen shot 2016-11-29 at 4 29 25 pm](https://cloud.githubusercontent.com/assets/254562/20729676/1086fff6-b651-11e6-8abb-857cef9fb7e6.png)

### Chrome Debugger
![screen shot 2016-11-29 at 4 30 06 pm](https://cloud.githubusercontent.com/assets/254562/20729698/253e3fae-b651-11e6-82ea-b6b335a3c1b7.png)
