### ISSUE TITLE
[Source Tree] use a "." for the root dir

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1353]
#1098 listed some inconsistencies between chrome's source tree and firefox's.

The biggest difference is that chrome can add a "." root directory, if there are other absolute top level directories.

For example, assume there are two paths:
* webpack://utils.js
* webpack:///users/jlaster/file.js

Then we'll create these directories
```
|-- webpack://
|  |-- .
|  |  |-- utils.js
|  |-- users/jlaster
|  |  |-- file.js
```
      

#### Here is chrome's top level directories for the *webpack://* domain
![screen shot 2016-11-29 at 4 33 51 pm](https://cloud.githubusercontent.com/assets/254562/20729920/1acffdea-b652-11e6-9130-debf9f91f636.png)

#### Here is "." expanded
![screen shot 2016-11-29 at 4 33 54 pm](https://cloud.githubusercontent.com/assets/254562/20729919/1ac6ce78-b652-11e6-9834-8b5226028921.png)

#### Here is what we do (a.k.a. nothing)
![screen shot 2016-11-29 at 4 34 00 pm](https://cloud.githubusercontent.com/assets/254562/20729939/353c17b8-b652-11e6-93fa-a200e9bc3fd1.png)

**steps to reproduce**
* go to localhost:8000
* in another tab go to localhost:8000 and debug the first tab (basically start inception) 
* go to localhost:8000 in chrome and debug it w/ chrome's debugger
* compare the two implementations for the "webpack://" domain

**patch**
```diff
diff --git a/src/utils/sources-tree.js b/src/utils/sources-tree.js
index 9c85739..9c7a504 100644
--- a/src/utils/sources-tree.js
+++ b/src/utils/sources-tree.js
@@ -232,6 +233,10 @@ function collapseTree(node: any, depth: number = 0) {
   if (nodeHasChildren(node)) {
     // Node is not a root/domain node, and only contains 1 item.
     if (depth > 1 && node.contents.length === 1) {
+      // we want to do something special for the first directory
+      // where we can check to see if there's an absolute directory
+      // if there is, we'll create a new virtual directory to put the relative contents in
+
       const next = node.contents[0];
       // Do not collapse if the next node is a leaf node.
       if (nodeHasChildren(next)) {
@@ -240,6 +245,8 @@ function collapseTree(node: any, depth: number = 0) {
           depth + 1);
       }
     }
+
+    // i think this is where the domain is
     // Map the contents.
     return createNode(node.name, node.path,
                       node.contents.map(next => collapseTree(next, depth + 1)));

diff --git a/src/utils/tests/sources-tree.js b/src/utils/tests/sources-tree.js
index d233e40..374992a 100644
--- a/src/utils/tests/sources-tree.js
+++ b/src/utils/tests/sources-tree.js
@@ -87,6 +87,8 @@ describe("sources-tree", () => {
     expect(source3Node.name).to.be("a_source3.js");
   });

+  // => we have nice tests, which can help drive this development
+
   it("sorts folders first", () => {
     const sources = [
       Map({
```

**Comment by jasonLaster** [comment]
@amitzur is on it

**Comment by amitzur** [comment]
In an initial look into the structure of source maps, I gathered that the "." is something that webpack places, probably to reflect structure in the consuming dev tools.
i.e. in bundle.js.map of this project the sources entries look like this:
`webpack:///./public/js/main.js`

Having `webpack:///` as the prefix (they could have placed it in the sourceRoot) creates the separate entry (with the cloud icon) and from that point it's just a matter of splitting by "/".

I'll keep updating with more info as I continue to study this.

**Comment by jasonLaster** [comment]
it might help to look at 

```js
appStore.getSate().sources.toJS()
```

*might work*
```js
appStore.getSate().sources.map(source => source.get("url"))
```


to see how we store the URLs

**Comment by jasonLaster** [comment]
Here's a list of [source urls](https://gist.github.com/jasonLaster/3e6d9944c2ea3a82f575352fd82263c6)

and a script to get it
```js
const sources = Object.values(
  appStore.getState()
    .sources.get("sources")
    .map(s => s.get("url"))
    .toJS()
)

const formattedSources = sources
    .filter(so => so && so.includes("webpack"))
    .sort()
    .join("\n")

console.log(formattedSources);
copy(formattedSources)
```

**Comment by jasonLaster** [comment]
and ugh that list is way too massive so i created a simplified case: 

```
webpack:///Users/jlaster/src/mozilla/debugger.html/assets/images/Svg.js

webpack:///Users/jlaster/src/mozilla/debugger.html/packages/devtools-client-adapters/index.js
webpack:///Users/jlaster/src/mozilla/debugger.html/packages/devtools-client-adapters/src/chrome.js

webpack:///Users/jlaster/src/mozilla/debugger.html/packages/devtools-config/src/feature.js
webpack:///Users/jlaster/src/mozilla/debugger.html/packages/devtools-config/src/test-flag.js
webpack:///Users/jlaster/src/mozilla/debugger.html/packages/devtools-modules/client/shared/components/reps/attribute.js

webpack:///Users/jlaster/src/mozilla/debugger.html/src/actions/ui.js
webpack:///Users/jlaster/src/mozilla/debugger.html/src/components/Accordion.css
webpack:///Users/jlaster/src/mozilla/debugger.html/src/components/Accordion.css?19b6

webpack:///Users/jlaster/src/mozilla/debugger.html/src/utils/menu.js
webpack:///Users/jlaster/src/mozilla/debugger.html/~/charenc/charenc.js
webpack:///Users/jlaster/src/mozilla/debugger.html/~/classnames/index.js
webpack:///Users/jlaster/src/mozilla/debugger.html/~/co/index.js
webpack:///Users/jlaster/src/mozilla/debugger.html/~/codemirror/addon/search/searchcursor.js

webpack:///Users/jlaster/src/mozilla/debugger.html/~/url/~/punycode/punycode.js
webpack:///actions/index.js
webpack:///actions/tabs.js
webpack:///components/LandingPage.css
webpack:///~/ansi-html/index.js
webpack:///~/ansi-regex/index.js
webpack:///~/classnames/index.js
webpack:///~/co/index.js
webpack:///~/css-loader/lib/css-base.js

webpack:///~/webpack/buildin/module.js
webpack:/webpack/bootstrap f2641195698c65f0200c
```

**Comment by jasonLaster** [comment]
Hmm, @amitzur perhaps chrome's devtools source map interprets the URLs differently

![screen shot 2016-11-30 at 9 20 52 am](https://cloud.githubusercontent.com/assets/254562/20755836/61200132-b6de-11e6-8488-28b81b598284.png)

**Comment by jlongster** [comment]
I like ours better, what's the issue exactly? The only thing mentioned is that it's different from Chrome, why is that a bad thing?

And yes, this is definitely because of how sourcemap URLs are resolved. This is part of the `source-map` library and definitely can't change because it would be backwards incompatible and that library is basically frozen (unless there are major problems with a feature, but those have mostly been worked out over the years).

**Comment by jlongster** [comment]
Probably worth looking into still, I *think* it's because we give the `source-map` library a sourcemap and it gives us back URLs, and it resolves things to solve a of use cases. Check the input sourcemap and the output original URLs.

**Comment by jasonLaster** [comment]
> Check the input sourcemap and the output original URLs.

Good idea. If there's nothing we can do there, we can close this.

I prefer having a "." directory as it nice to have ".", "~", "webpack" as sibling dirs. 

In reality, the better fix would be to have directories that line closer with what is on disk, which is the direction the chrome team is headed in.

**Comment by jlongster** [comment]
> I prefer having a "." directory as it nice to have ".", "~", "webpack" as sibling dirs.

I guess I don't understand where `.` is coming from: if the URL in the sourcemap is `webpack:///actions/index.js` (which you pasted above) it makes sense that it would map `/actions/index.js` to a top-level `actions` folder with `index.js` inside of it.

> In reality, the better fix would be to have directories that line closer with what is on disk, which is the direction the chrome team is headed in.

Sourcemaps are completely made up, so it's up to whatever is generating the sourcemaps to do that. I don't see how we could do anything else when dealing with sourcemaps. We use whatever the tool generates, so if it's not generating ideal URLs, the tool needs fixing, not us (for the most part, there may be some things we can do of course)

**Comment by amitzur** [comment]
I think there's some confusion here, which I intend to resolve by resorting to the increment example.
I'm going to show 3 ways to create the source maps, and include what chrome and debugger.html do for each.
The bottom line IMO is, whatever the source maps generated should be reflected in the sources pane. Seems like `source-map` does its job, as @jlongster mentioned, but the client should construct a tree in a optimally visual way (e.g. merge folder levels).

### 1) webpack
Right now, bundled with webpack, this is the source map (extracted from [bundle.js.map](https://github.com/devtools-html/debugger.html/blob/master/src/test/examples/increment/bundle.js.map))
```
webpack:///webpack/bootstrap 4f282b30eeca6ec69a5d
webpack:///./increment/example.js
webpack:///./increment/increment.js
webpack:///./increment/math.j
```

So, it's obvious where the "." comes from. And here's how it shows up in chrome and debugger.html (we can see that debugger.html drops the "."):
![screen shot 2016-12-01 at 15 06 30](https://cloud.githubusercontent.com/assets/394320/20795284/02a773c8-b7d9-11e6-804f-8524a2b1cfbb.png)
![screen shot 2016-12-01 at 15 28 09](https://cloud.githubusercontent.com/assets/394320/20795626/cf1e0b1e-b7da-11e6-9034-5c1433757251.png)

### 2) browserify
Now, if I bundle the example sources with browserify using this line:
`browserify example.js --debug | exorcist bundle.js.map > bundle.js`
Then this is the source map:
```
../../../../../../../../usr/local/lib/node_modules/browserify/node_modules/browser-pack/_prelude.js
example.js
increment.js
math.js
```

And I get these results (notice that debugger.html shows better separation between the bundle and the source mapped sources):
![screen shot 2016-12-01 at 15 32 15](https://cloud.githubusercontent.com/assets/394320/20795769/922085ba-b7db-11e6-8fbd-cd37e59df697.png)
![screen shot 2016-12-01 at 15 30 56](https://cloud.githubusercontent.com/assets/394320/20795772/943c38ee-b7db-11e6-82f6-639c35533908.png)

### 3) browserify with sourceRoot URI
And finally there's the ability to also specify the sourceRoot with the browserify way, and if it's with a URI protocol prefix:
`browserify example.js --debug | exorcist bundle.js.map --root=browserify:/// > bundle.js`

Then it's the same source map, except for sourceRoot, and it shows up like this:
![screen shot 2016-12-01 at 16 57 36](https://cloud.githubusercontent.com/assets/394320/20798399/5dacc008-b7e7-11e6-8f52-9dd263dfe483.png)
![screen shot 2016-12-01 at 16 57 57](https://cloud.githubusercontent.com/assets/394320/20798404/5f4c5da6-b7e7-11e6-977b-5e2ce7b70fdd.png)

**Comment by jasonLaster** [comment]
Thanks for the writeup amit. 

This was very helpful. 

Closing the issue as I think we agree that there isn't anything actionable.
