### ISSUE TITLE
[Toolbox] document running targets

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1355]
From @kdzwinel 
> every time I run the project I'm scanning the docs for instructions on how to run targets that I can debug and I can never find them (then I look at package.json and find out about `yarn run firefox`)

**Comment by jasonLaster** [comment]
Takeaways:

1. we should make it really clear how to run targets from the landing page
2. we could add a terminal instruction
3. we could point people to a section of the getting started doc for runnign targets

**Comment by clarkbw** [comment]
Our [README](https://github.com/devtools-html/debugger.html#getting-setup) now has this in the getting setup section.
