### ISSUE TITLE
[Vertical Layout] Source Tree 

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1358]
We recently landed vertical layout, which gives App.js the ability to monitor the page width and flip to a vertical mode when the page is less than 700px.

Currently the source tree is the full height of the debugger. We would like the source tree to be a sibling of the editor as it is in chrome.

### Patch

Here's a [patch](https://gist.github.com/jasonLaster/579f1b93694431d4763de60697882627) to get the ball rolling. I'm really excited about this one!

it's somewhat large so here's a script to get started
```
curl https://gist.githubusercontent.com/jasonLaster/579f1b93694431d4763de60697882627/raw/a169ec97284b9db303a215bd9adb7f91e0d3c860/foo.diff | git apply
```

### Debugger
![](https://cloud.githubusercontent.com/assets/254562/20759880/510af6f4-b6ec-11e6-8bea-e26872761173.gif)

### Chrome
![](https://cloud.githubusercontent.com/assets/254562/20457854/aea16cf4-ae62-11e6-9c5f-d48607e51c60.png)

**Comment by sankha93** [comment]
I would like to take a stab at this over the weekend.

**Comment by jasonLaster** [comment]
Hey @sankha93 have you had a chance to look at this?
Are you blocked by anything that I can help with?

**Comment by wldcordeiro** [comment]
I'll be taking this.
