### ISSUE TITLE
[Vertical Layout] Scope Pane

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1359]
We recently landed vertical layout, which gives App.js the ability to monitor the page width and flip to a vertical mode when the page is less than 700px.

Currently the scope pane is below the Frames section in the accordion. We would like to move it to the right so that it gets more real estate.

### Patch

Here's a [patch](https://gist.github.com/jasonLaster/f60bee14b54ab9661dee11634573ef74) to get the ball rolling. 

```
curl https://gist.githubusercontent.com/jasonLaster/f60bee14b54ab9661dee11634573ef74/raw/8f7745d216febc5278efe07eba0a782cd49466b4/foo.diff | git apply
```

### Debugger
![](https://cloud.githubusercontent.com/assets/254562/20759880/510af6f4-b6ec-11e6-8bea-e26872761173.gif)

### Chrome
![](https://cloud.githubusercontent.com/assets/254562/20457854/aea16cf4-ae62-11e6-9c5f-d48607e51c60.png)

**Comment by petrgazarov** [comment]
Hey, I'm new to the repo, but this seems pretty straight-forward. Mind if I give it a shot?

**Comment by jasonLaster** [comment]
Hey @petrgazarov go for it!

**Comment by petrgazarov** [comment]
Hm, I had a fork that had 80% of progress made on this. 😕 

No blame, but perhaps next time some communication would be helpful, about either switching to a different issue or moving faster on this one.

**Comment by wldcordeiro** [comment]
@petrgazarov Apologies. I had meant to ping the appropriate people when I did this work. If you're looking for issues to work on feel free to ping me or @jasonLaster and we can direct you to some open ones. Again, apologies for the lack of communication.
