### ISSUE TITLE
[Sources Tree] the host domain should be first

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1374]
We should show the debuggee host domain first in the tree.

Notes:
* we will likely need the tab url in the redux store

Patch for debuggee url

```diff
diff --git a/src/reducers/pause.js b/src/reducers/pause.js
index ba19302..362940f 100644
--- a/src/reducers/pause.js
+++ b/src/reducers/pause.js
@@ -20,9 +20,13 @@ type PauseState = {
   loadedObjects: Object,
   shouldPauseOnExceptions: boolean,
   shouldIgnoreCaughtExceptions: boolean,
-  expressions: I.List<Expression>
+  expressions: I.List<Expression>,
+  debuggeeUrl: string
 }

+// pause is not a great place for it now
+// eventually i think a connection reducer makes sense, but... not sure
+
 const State = makeRecord(({
   pause: undefined,
   isWaitingOnBreak: false,
@@ -31,7 +35,8 @@ const State = makeRecord(({
   loadedObjects: I.Map(),
   shouldPauseOnExceptions: false,
   shouldIgnoreCaughtExceptions: false,
-  expressions: I.List()
+  expressions: I.List(),
+  debuggeeUrl: undefined,
 } : PauseState));

 function update(state = State(), action: Action): Record<PauseState> {
@@ -85,6 +90,8 @@ function update(state = State(), action: Action): Record<PauseState> {
       break;

     case constants.NAVIGATE:
+      // we could likely add it here
+      // action.value ...
       return State();
```

CC @darkwing, @Dalimil 

@Dalimil interested in grabbing this and applying your work from before?

**Comment by Dalimil** [comment]
The `action` object doesn't seem to contain the URL - there is no `action.value`...

**Comment by liorpr** [comment]
@jasonLaster can you elaborate on this or maybe add a photo? not sure what to add here.

**Comment by jasonLaster** [comment]
Sure, right now the sources tree has a bunch of domains for every page you go to. For example, if you go to cnn.com, one domain is cnn.com, and then there are 20 other random ones. We'd like to show CNN first, but at the moment don't have a good way of doing that.

We should do this by first saving the debggee's url when we get a navigate event. We can check the event data

Here's a good way of getting the debuggee url when we navigate:

```diff
diff --git a/src/actions/navigation.js b/src/actions/navigation.js
index 71c2149..d27df53 100644
--- a/src/actions/navigation.js
+++ b/src/actions/navigation.js
@@ -14,11 +14,14 @@ const { newSources } = require("./sources");
  * @memberof actions/navigation
  * @static
  */
-function willNavigate() {
+function willNavigate(_, event) {
   clearSourceMaps();
   clearDocuments();

-  return { type: constants.NAVIGATE };
+  return {
+    type: constants.NAVIGATE,
+    url: event.url
+  };
 }
 ```
 
 @Dalimil, @liorpr still interested in this?

**Comment by Dalimil** [comment]
I'm working on this... I obviously won't have the NAVIGATE event fire at the start - so would the user need to refresh the currently debugged page everytime?

**Comment by jasonLaster** [comment]
Hmm. I'll make a deal, if you get it working with navigate I'll get you the
event for the initial load :)

**Comment by Dalimil** [comment]
I'm still dealing with some flow errors and the code might need some cleaning up (especially because all the tree methods are static and I need to keep passing additional parameters every time), but it seems to be working...

![out](https://cloud.githubusercontent.com/assets/4202539/23751491/9066d400-04c9-11e7-92ea-2e3e4f34a9a9.gif)
