### ISSUE TITLE
Ctrl+P followed by Ctrl+F opens native Firefox search

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#1376]
Steps to reproduce:
1. Ctrl+P to open a certain file
2. Ctrl+F to open for a certain string in this file

Actual results:
Native Firefox search bar is opened

Expected results:
The debugger.html search (labelled with the placeholder "Search for:") should open.

If I click in the debugger file tab then the correct search bar is opened. So maybe it is just an issue of setting the focus to the filed opened by Ctrl+P.

Noticed on Firefox Dev Edition 52, reproduced on today's Nightly Firefox version.

**Comment by jnachtigall** [comment]
Ctrl+F works for me when focus is set (Windows 10 and Ubuntu). But AFAIK shortcuts are OS dependent, @bjorn3, which OS do you use?

**Comment by bjorn3** [comment]
@jnachtigall macOS

**Comment by jasonLaster** [comment]
Nice find!

We recently opened a PR for stopping propagation on function shortcuts like F8. https://github.com/devtools-html/debugger.html/pull/1373/files

Here's what I see. Is that what you get?

![](http://g.recordit.co/bAQn58GlPw.gif)

I think the right UX would be to just suppress the handler and do nothing. We don't really have a file to search...

**Comment by jnachtigall** [comment]
> Here's what I see. Is that what you get?

@jasonLaster Yes, the native searchtool opens instead of the debugger's in-file search. Whereas for @bjorn3 it seems like the debugger's in-file search is not available at all on macOS

**Comment by jasonLaster** [comment]
I'm closing this because locally the new editor search bar will always handle cmd+f

![](http://g.recordit.co/74nkcFStkr.gif)

**Comment by jnachtigall** [comment]
> I'm closing this because locally the new editor search bar will always handle cmd+f

@jasonLaster I do not understand this and rereading the whole thread I think there is a misunderstanding about the STR:

What I (user) wants to do is going to a certain string/method within a certain file. Quite common workflow

So I 
1. First Ctl-P to open this particular file => File opens
2. Immediately after this I do Ctrl-F to search whithin this opened file => Opens Firefox native search instead of the Debugger's search. Only after manually focussing within the debugger editor with mouse the Debugger's search is opened.

Or has there been a commit that fixes this behaviour?
