### ISSUE TITLE
Splitter not resizable when Debugger is docked to side of browser window

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#1378]
I cannot resize (drag'n'release with the mouse) these splitters if the debugger is on the right side:

![2016-12-05 13_02_53-yahoo suche websuche suchmaschine - nightly](https://cloud.githubusercontent.com/assets/3307404/20884382/4358edce-baeb-11e6-94f5-8dd2992a5f18.png)

The middle tab area is a bit to small to work with ;) Interestingly only happens if I am on full window, not if I the windows is minimized to just a portion of the monitor screen. So maybe has to do with larger screen sizes (though mine is "only": 1920x1080). Windows 10, today's Nightly and FDE 52.

**Comment by wldcordeiro** [comment]
I believe this is addressed by our recent vertical layout PRs. However I don't think that has been pushed upstream to nightly yet or dev edition.

**Comment by jnachtigall** [comment]
@wldcordeiro Thanks for info. Is there a way to see which version is deployed in Nightly or Dev edition? Something like `<some-global-debugger-object>.VERSION` (`VERSION` being a time snapshot or similar)

Also, since I use Dev edition for work and face with many issues with the new debugger, an uplift outside of the 6 weeks train schedule would be very much appreciated.

**Comment by wldcordeiro** [comment]
@jnachtigall We don't currently export a version number, but that is a great idea. I'll file an issue for it.

**Comment by jasonLaster** [comment]
@jnachtigall is this what you're running into: https://github.com/devtools-html/debugger.html/issues/856?

**Comment by jnachtigall** [comment]
> @jnachtigall is this what you're running into: #856?

I looked at #856 already before opening this bug and it's hard to tell because there's no screenshot and only a few words in the report there. I'd say it's something different. 

But you can simply side-dock the devtools in Nightly and try to use resize the splitters of the debugger - it's not working at all. So should be very easy to reproduce.

**Comment by jasonLaster** [comment]
Yeah, the right sidebar splitter has its issues for sure

![](http://g.recordit.co/22uDFijXxg.gif)

This is something we knew and decided it wasnt a release blocker even though it is frustrating.

We now have vertical mode and will fix the splitter in this case and the zoomed in case soon.

**Comment by jnachtigall** [comment]
Albeit the UX issues you seem to be able to resize at least. In my case (monitor resolution 1920x1080) I cannot resize at all. So the image above in 1378#issue-193480486 is static, that's no dragging of the splitters possible at (not sure if this was clear).

**Comment by jasonLaster** [comment]
Strange. Yea, right docked is not ready for prime time

**Comment by jasonLaster** [comment]
Lol. Touch it with JS

**Comment by clarkbw** [comment]
Being tracked in bugzilla in [bug 1322062](https://bugzilla.mozilla.org/show_bug.cgi?id=1322062)

**Comment by jasonLaster** [comment]
Thanks @amitzur for fixing it in https://github.com/devtools-html/devtools-core/pull/94
