### ISSUE TITLE
webpack's SingleModuleInstancePlugin added in #1351 kills loading performance on Firefox

### ISSUE THREAD

**Issue by nickolay** [devtools-html/debugger.html#1382]
With debugger.html @ 6540a907068f67b5adb7d14c4b9f52662016733f and current Firefox Nightly simply loading the UI (http://localhost:8000/) takes a few seconds on my machine.

Profiling reveals that most time is spent (surprisingly!) in `__webpack_require__`'s "Self Cost". Digging deeper shows that there are multiple JIT failures on this line: https://github.com/smikhalevski/single-module-instance-webpack-plugin/blame/master/index.js#L15 (CantInlineNativeBadForm) from SingleModuleInstancePlugin added in #1351
<img width="1259" alt="screen shot 2016-12-06 at 10 20 29" src="https://cloud.githubusercontent.com/assets/247067/20916761/76b0b16c-bb9e-11e6-970f-98617c420d1a.png">

It looks like for each of 850+ requires in debugger.html the plugin scans through each of the previously loaded modules, checking to see if the source of the module-being-loaded matches the source of the already loaded module, resulting in 700k+(!) calls to `String(function)`, which Firefox's JIT does not optimize.

Surprisingly, this manages to execute quickly in Chrome and might deserve a bug in SpiderMonkey and/or single-module-instance-webpack-plugin.

**Comment by jasonLaster** [comment]
Thanks for sharing @nickolay! And thank you for the perf analysis as well.

SMP seems pretty inefficient on the surface. I apologize, I've tested the perf on chrome, but this regression is unacceptable and we will fix it.

By the way, it might get worse before it gets better :)

https://github.com/devtools-html/debugger.html/pull/1372

I think what we might need to do, is find a way to tree shake at compile time and avoid the problem all together.

**Comment by jasonLaster** [comment]
Just took a look and you're absolutely right. It looks like there is tremendous GC pressure with all of the new strings created.

<img width="1259" alt="screen shot 2016-12-06 at 1 01 19 pm" src="https://cloud.githubusercontent.com/assets/254562/20937263/34fbaa5e-bbb4-11e6-86ea-9973d0d46220.png">

@juliandescottes looks like we should start caching those sanitized module strings!

**Comment by jasonLaster** [comment]
Just added a cache and saw requires went down from 6 seconds to 1 second.

https://github.com/jasonLaster/single-module-instance-webpack-plugin

<img width="1433" alt="screen shot 2016-12-06 at 3 16 43 pm" src="https://cloud.githubusercontent.com/assets/254562/20942307/e0ac37ba-bbc8-11e6-9693-77b747f08bf7.png">

**Comment by jasonLaster** [comment]
Updated SMP
