### ISSUE TITLE
Use Special Style for "(index)"

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#1387]
If you load a site like ESPN, it's hard to find "(index") in the left sidebar.  Since it's the "main" resource being loaded, it would be good to call more attention to it.

A few ideas:
- A light yellow background on the "(index)" row
- Always show the hostname for "(index)" at the top of the left side list

**Comment by jasonLaster** [comment]
> A light yellow background on the "(index)" row

I think that it being on the top will help a lot. I'm in favor of something that distinguishes it, but a yellow background sounds jarring. perhaps italicized, or slightly grayer font, or different color?

> Always show the hostname for "(index)" at the top of the left side list

Yup, #1374

**Comment by darkwing** [comment]
Closing as #1374 should address the issue.

**Comment by jasonLaster** [comment]
@darkwing one other point here is that chrome has some really useful coloring for the icons that help.

<img width="253" alt="screen shot 2016-12-10 at 3 10 14 pm" src="https://cloud.githubusercontent.com/assets/254562/21075862/cabc14fa-beea-11e6-84ce-64845191b1f2.png">
