### ISSUE TITLE
Remove vertical separator (line) between code and line numbers

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#1394]
I still think that the line between the line numbers and the code does not look nice, especially if the first tab is active (because the vertical line hits loosely into the tab title). See
![687474703a2f2f672e7265636f726469742e636f2f427235756c73443174342e676966](https://cloud.githubusercontent.com/assets/3307404/20961533/b7a0a908-bc65-11e6-993d-d12f69c207c3.gif)

Looks better in Sublime:
![e728c3c4-b231-11e6-826d-fafbd55f4c14](https://cloud.githubusercontent.com/assets/3307404/20961561/d7408abc-bc65-11e6-916a-c8f39a31b94f.png)

**Comment by jasonLaster** [comment]
oops, sorry created a dupe here #1400
