### ISSUE TITLE
Export a version number to see what debugger version comes with Firefox

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#1396]
@wldcordeiro I took the liberty to add this ;) 

As of https://github.com/devtools-html/debugger.html/issues/1378#issuecomment-265091011 it would be great if there was a way to see which version is deployed in Nightly or Dev edition. Something like `<some-global-debugger-object>.VERSION` (VERSION being a time snapshot or git hash, though I would prefer a human readable date/time). 

I was thinking about something like lodash does with [_.VERSION](https://lodash.com/docs/4.17.2#VERSION)

**Comment by wldcordeiro** [comment]
@jnachtigall Thanks! Heh, missed it. I think it'd be nice to make `VERSION` equal to a format like `x.y.z-git-hash` this way it shows our planned version numbers that will be published to npm/Firefox and then in development you'll have a hash to check against.

**Comment by jasonLaster** [comment]
Nice idea!

It's kinda funny that we don't have an obvious debugger global object to namespace it in.

Also, yea using the SHA makes sense. 
I don't think we want to semver the debugger yet...

**Comment by jasonLaster** [comment]
Here's a patch for how I would do it:

```diff
diff --git a/packages/devtools-local-toolbox/webpack.config.js b/packages/devtools-local-toolbox/webpack.config.js
@@ -69,7 +69,8 @@ module.exports = (webpackConfig, envConfig) => {
         NODE_ENV: JSON.stringify(NODE_ENV),
         TARGET: JSON.stringify(TARGET)
       },
-      "DebuggerConfig": JSON.stringify(envConfig)
+      "DebuggerConfig": JSON.stringify(envConfig),
+      "VERSION": JSON.stringify("do some git foo w/ a lib or a shell command")
     })
   );
 
diff --git a/src/main.js b/src/main.js
index 44cb9ec..57804ce 100644
--- a/src/main.js
+++ b/src/main.js
@@ -32,6 +32,7 @@ if (!isFirefoxPanel()) {
 }
 
 window.appStore = store;
+window.debuggerVersion = VERSION;
 
 // Expose the bound actions so external things can do things like
 // selecting a source.
```

**Comment by clarkbw** [comment]
If we start tagging releases you can use `git describe --abbrev=0` to get the latest tag description that can point to the version.  I went through some of this in #633

**Comment by joakin** [comment]
Going to have a stab at this.

**Comment by jasonLaster** [comment]
Hey @clarkbw, @joakin, @jnachtigall 

Joaquin, implemented `debuggerVersion` in #1417. 

I'm reconsidering the value of having a debugger version though. The thinking is, if the user reports a bug with the debugger and provides the firefox version number, we could figure out what the debugger sha is.

What do you guys think?

**Comment by jnachtigall** [comment]
I originally came up with the version number idea, because:
I saw a bug in Dev Edition and Nightly which looked pretty obvious to me, but I did not know if it's worthwhile to report. If the version in Firefox (date) would have been much older than the one in HEAD I would not have cared to report as usually the bug has already been reported and fixed by someone else. I think there's some value to users to know that the Nightly version is almost the same as HEAD (I usually only report bugs if I can reproduce with Nightly).

> The thinking is, if the user reports a bug with the debugger and provides the firefox version number, we could figure out what the debugger sha is.

I guess you were able to do this mapping from firefox version => debugger sha. But I would not know how to look this up ;) So if I have a firefox version as of today (52.0a2 (2016-12-09)), how would i know which debugger version is in there?

Besides, the debugger's is also to be used outside of Firefox afaik. 

Just my opinion, up to you :)

PS
Though, I would recommend a namespaced variable like `dbggr.VERSION` or similar instead of a global variable `debuggerVersion` (in case you want to add further global vars or methods later, and also just out of a habit because this is how it's done for most libs)

**Comment by jasonLaster** [comment]
Yeah, you hit the nail on the head: *I would not know how to map from firefox version to sha*.

I believe we will be able to address this with:
1. more frequent releases 
2. tagging each release and adding it [here](https://github.com/devtools-html/debugger.html/releases)

> Besides, the debugger's is also to be used outside of Firefox afaik.

Yeah, that's another good point. I'm inclined to cross that bridge when we get there because we'll be deploying very differently there. Hopefully continuously deploying actually.

**Comment by jasonLaster** [comment]
closing this for now as I don't think it's actionable. We'll be working on updating our release process over the next month and so hopefully things will be smoother.

Lets continue talking here though about the value of having a local version in the debugger app like `window.debuggerVersion = "<sha>"
