### ISSUE TITLE
Overlapping of footer message with the tab details on the middle pane

### ISSUE THREAD

**Issue by viswanathamsantosh** [devtools-html/debugger.html#1399]
![debugger_issue1](https://cloud.githubusercontent.com/assets/3799600/20978395/c38a7af0-bcce-11e6-8e09-a35496e7056e.JPG)

'First time connecting to Firefox?' message is overlapping with the tabs shown on the page.

**Comment by jasonLaster** [comment]
😢 

thanks for filing.
