### ISSUE TITLE
[Editor] polish the editor gutter style

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1400]
@jnachtigall mentioned this in #1305 and #1394  

> You might also want to check the separating line between line number and content. There's no such separating line in VSCode or Sublime and to me it irritates the eye especially when this line hits the tabs header"

> I still think that the line between the line numbers and the code does not look nice, especially if the first tab is active (because the vertical line hits loosely into the tab title)

A couple of points:
* should the gutter have a different background color
* should there be a right border
  * sublime has a really cool effect where they subtly add a drop shadow when you scroll right

##### Ours

![](https://cloud.githubusercontent.com/assets/3307404/20593769/e2639060-b233-11e6-9ff7-ae4bfd460ad6.png)

<img width="761" alt="screen shot 2016-12-07 at 12 44 59 pm" src="https://cloud.githubusercontent.com/assets/254562/20979451/fcad883a-bc7a-11e6-8000-4b927609a8e2.png">

##### Atom
<img width="616" alt="screen shot 2016-12-07 at 12 40 29 pm" src="https://cloud.githubusercontent.com/assets/254562/20979303/6f71aa50-bc7a-11e6-9053-90c4b1deeef8.png">

##### Chrome DevTools
<img width="603" alt="screen shot 2016-12-07 at 12 40 40 pm" src="https://cloud.githubusercontent.com/assets/254562/20979313/75c37802-bc7a-11e6-8777-1561f2faf899.png">

##### Sublime

<img width="1059" alt="screen shot 2016-12-07 at 12 43 10 pm" src="https://cloud.githubusercontent.com/assets/254562/20979391/c3c5df22-bc7a-11e6-9f64-42fe05620d74.png">

![](http://g.recordit.co/5gNKJQSTlY.gif)

**Comment by jasonLaster** [comment]
@amitzur this is another style one that could be nice

**Comment by jasonLaster** [comment]
Next steps:
* remove right border
* add nice background color
* add right padding

**Comment by irfanhudda** [comment]
I'll take a look at this

**Comment by jasonLaster** [comment]
Thanks @irfanhudda
