### ISSUE TITLE
[UX] Allow the user to drag'n'drop tabs to rearrange their order

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#1405]
Currently tabs are visible in the order their files where opened. Would be nice if tabs could be re-ordered manually by drag'n'dropping with the mouse.

**Comment by jasonLaster** [comment]
That's a nice idea. We now have a draggable library that could help. 

The big blocker is identifying the UX we want. If someone could writeup what other editors do that would help.

**Comment by jnachtigall** [comment]
I think the UI is pretty much the same everywhere:

1. Your left-click (and hold) on the tab header
2. While holding you move the mouse somewhere else on the "tab panel" 
3.a) Drop on the tab panel: Whereever you drop (release left mouse), the tab will be put into that place effectively rearranging the order
3.b) Dropping anywhere else or pressing ESC in between: Nothing happens

I've never seen it anything else. In the end just do it like the Firefox Tabs work and it should be fine and a UX users have learnt and are familar with  ;)

**Comment by jasonLaster** [comment]
moved this issue to our enhancements project as i don't see someone being able to jump on this soon. 

If someone would like to work on it, mention it in the issue and we can re-open it.
