### ISSUE TITLE
[Editor] Syntax highlighting is absent for sources without an extension

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1408]
STR:
1. open a tab in firefox
2. debug tab with remote debugger
3. debug debugger (inception)
4. go to webpack://webpack/bootstrap 2342432234

<img width="979" alt="screen shot 2016-12-08 at 9 06 59 pm" src="https://cloud.githubusercontent.com/assets/254562/21035056/557b354c-bd8a-11e6-8bae-beffb37858bc.png">

**Comment by bomsy** [comment]
This has to do with our heuristics for which mode to use.
atm it defaults to "text" .
This looks like the relevant code section 
https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor.js#L242-L256

**Comment by jasonLaster** [comment]
Good point. I suppose we try and get the contentType on the server from the extension:

https://dxr.mozilla.org/mozilla-central/source/devtools/server/actors/utils/TabSources.js#292-343

I wonder what chrome does.
Also what we should do...

@jlongster thoughts?

**Comment by bomsy** [comment]
Just another thought. Can we safely default our mode to `javascript` rather than `text`?
Are there any scenarios for defaulting to `text`?

it seems like that is done here as well.
https://dxr.mozilla.org/mozilla-central/source/devtools/server/actors/utils/TabSources.js#345-349

**Comment by bomsy** [comment]
> Good point. I suppose we try and get the contentType on the server from the extension:
This will be cool to do, i'll also see what chrome does.

**Comment by jasonLaster** [comment]
@bomsy did a little bit more digging:

1. in this case we're getting the source from source map worker, so we're not talking to the server
2. we can't safely assume it is JS because it could be typescript or closurescript
3. chrome devtools handles this well... reverse engineering the on file item click was pretty helpful

**Comment by jasonLaster** [comment]
removed the "in-progress" label as this bug seems like it's not as important as other bugs

**Comment by jasonLaster** [comment]
moving this to the bug triage board as a note because it's low priority and i don't see us getting to it anytime soon.

**Comment by thomcc** [comment]
Came here to open a bug about TypeScript not having any syntax highlighting.

Just want to say that using JavaScript seems like a much better default than text to me -- ClojureScript might not highlight well in some cases, but most things would highlight pretty well. At least assuming you can tell that it's for a script and not e.g. a stylesheet?

**Comment by jasonLaster** [comment]
hmm... if we're using source maps the source *should* have an extension and we can do the right thing.

The main use case is bad source maps!

**Comment by rvanbaalen** [comment]
What's the current state of this? I noticed that the FF devtools don't show syntax highlighting when my filename has a parameter: 

`app.js` -> works
`app.js?v=1.0.0` -> no syntax highlighting
