### ISSUE TITLE
Better handle inline JS (embedded in html): Open at correct position, show in Source Tree

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#1411]
STR:
1. Open http://openlayers.org/en/v3.19.1/examples/vector-labels.html
2. Open (Ctrl+P) the file vector-labels.html

AR:
Opens the file at line 1 of the html. And I'm lost ;) I need to manually scroll and search for the javascript which is somewhere in there

ER:
Open at first line of included js inside a `<script>` tag.

In case there are several inline js scripts a further enhancement would be to list those in the source tree as well like
```
<vector-labels.html>
  |- <script> at line 23
  |- <script> at line 78
  |- <script> at line 821
```

**Comment by jnachtigall** [comment]
To be fair, Chrome Devtools do not handle this use case either :-) 
(But I personally have it quite often when looking at smaller source code examples like above; or very often embedding data structures from a CMS doing so with inline using JS/JSON is very common). At right now it's rather cumbersome to look at these embedded snippets using the debugger...

**Comment by jasonLaster** [comment]
@jlongster and I have discussed this in the past. 

One option is for us to better improve `sourceURL`, which we want to do here https://github.com/devtools-html/debugger.html/issues/958

Another option is to name these sources and have them appear in the tree as you suggest. I forgot what the technical challenges are here, but I'm sure there are several in the debugger server.

@jnachtigall this is a great issue to raise. What I'm going to do at the moment is to close the issue and add it to the enhancements board.

Lets keep discussing the issue though as that will help us when we plan.
