### ISSUE TITLE
New tab is opened at left side: Should open at right side

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#1418]
**STR:**
1. Open a file with Ctrl+P (so to just have at least one tab open already)
1. Open another file with Ctrl+P

**AR:**
New file opens at *leftmost* (left of already open tab)

**ER:**
Should open to the *rightmost* of already open tabs. The newtab `+` icon is also at the right side...

All tab-based applications I can think of do open new tabs to the right of the already opened tabs: Firefox, Chrome, Chrome Devtools, VSCode, Sublime, Eclipse, Intellij, Notepad++. I guess it's not deliberate behavior but a bug that the debugger does not follow this UX scheme ;)

**Comment by shlomif** [comment]
I'm going to try to tackle this issue.

**Comment by jasonLaster** [comment]
Thanks. 

This is a little difficult for a couple reasons. 

1. Adding to the right means knowing if we need to hide a tab

2. Sublime and other editors add a new tab to the right of the selected tab

**Comment by shlomif** [comment]
OK, I was able to reproduce this issue. I'll try to fix it now.

**Comment by shlomif** [comment]
Hi all!

The commit at https://github.com/shlomif/debugger.html/tree/issue1418-tabs-should-open-on-right fixes the symptoms of the problem while adding a new previously-failing-now-succeeding test and passing all existing tests.

Note that for now I have not followed all of @jasonLaster 's guidelines.

**Comment by jasonLaster** [comment]
PR it so that we can comment.

For the record, following my guidelines is optional. Often not the best
strategy :)

**Comment by jnachtigall** [comment]
> Sublime and other editors add a new tab to the right of the selected tab

That's a point. But I think there's a suble difference: Sublime has no newtab `+` button at the very right. I think, if the newtab button is at the very right (like in the Firefox browser or Chrome browser) then it's consequent to also open at the very right.

**Comment by shlomif** [comment]
@jasonLaster : pull-req sent - https://github.com/devtools-html/debugger.html/pull/1425

**Comment by jasonLaster** [comment]
@jnachtigall I think that's a good point.

Perhaps:
* *Cmd+P*  *new tab button* open tabs to the right
* selecting a source in the tree open a tab to the right of the selected tab

CC @helenvholmes, @jlongster, @clarkbw what do you think?

**Comment by clarkbw** [comment]
I'd keep it simple and always open to the right like in the PR, of course making sure it is also visible.  I think that's why the current behavior (to the left) is what it is.

These tab management issues would be good side projects but I would prioritize other things right now.

**Comment by jlongster** [comment]
Cmd+P doesn't bring up a new tab, so I don't know how this impacts that.

Opening always to the right though makes sense.

**Comment by jasonLaster** [comment]
How's it going @shlomif? Let me know if you're blocked, happy to answer any questions

**Comment by shlomif** [comment]
@jasonLaster : sorry, I have not done any more work on this issue beyond my pull-req - I've been busy with non-debugger.html-related stuff. I'd be OK if someone else try to tackles the remaining issues,

**Comment by jasonLaster** [comment]
sounds good, I'll close the PR and we can re-open the issue

**Comment by arthur801031** [comment]
Hi @jasonLaster  

I will take a look at this tomorrow. :)

**Comment by arthur801031** [comment]
Hi @jasonLaster ,

I'm not sure if there is a better way to retrieve a list of hidden tabs in `src/reducers/sources.js`. I'm thinking if using redux to store `hiddenSourceTabs` at https://github.com/devtools-html/debugger.html/blob/master/src/components/SourceTabs.js#L187 is a good idea. If we do this, we would retrieve this list at https://github.com/devtools-html/debugger.html/blob/master/src/reducers/sources.js#L166, and we can determine where in the tabs we should insert.

Thank you! :)

**Comment by arthur801031** [comment]
Hi @jasonLaster 

I'm not sure if I have this correct, but it seems we cannot know which tabs will be hidden in  `src/reducers/sources.js`. So I'm wondering if it's a good idea to use redux to store the new tab at https://github.com/devtools-html/debugger.html/blob/master/src/reducers/sources.js#L166. When we're determining which tabs should be hidden at https://github.com/devtools-html/debugger.html/blob/master/src/components/SourceTabs.js#L41, we try inserting the new tab at different index of the tabs to see where it can be placed.

Thank you! :)

**Comment by jasonLaster** [comment]
Hmm, another challenge is variable width tabs. 

So, if you always put the new tab to the left of the last visible tab there's a chance that the new tab is really wide and won't fit. 

What I'm thinking is measure the width of the tabs element and then figure out where the new tab should go. 

We can always pass the index of the tab location to the reducer. 

One challenge is measuring the width of the tab before it's been shown. You might need to make a fake tab with js just to measure it. 

Also, determining the widths needs to factor in margins between tabs. 

There's potentially a lot of math :/

**Comment by arthur801031** [comment]
Hi @jasonLaster 

How do we make a fake tab in `src/reducers/sources.js`? I tried constructing a list of dom div of tabs
```
function renderTab(source) {
  const filename = getFilename(source.toJS());
  return dom.div(
    {
      className: classnames("source-tab", { active: false }),
      key: source.get("id"),
      title: getRawSourceURL(source.get("url"))
    },
    dom.div({ className: "filename" }, filename));
}

function updateTabList(state, source, tabIndex) {
  const tabs = state.get("tabs");
  const sourceIndex = tabs.indexOf(source);
  const includesSource = !!tabs.find((t) => t.get("id") == source.get("id"));

  if (includesSource) {
    if (tabIndex != undefined) {
      return tabs
        .delete(sourceIndex)
        .insert(tabIndex, source);
    }

    return tabs;
  }

  const listOfDoms = dom.div(
    { className: "source-tabs", ref: "sourceTabs" },
    tabs.map(renderTab)
  );

  // more stuff to write....
  // return tabs.insert(tabs.size, source);
}
```

I'm not sure what to call to determine the width from those dom elements.

**Comment by jasonLaster** [comment]
Hmm. Yea, I wouldn't create a fake tab in the reducer. Perhaps the
component in a div offscreen.

But in reality, this is a relatively low priority bug :/

**Comment by jasonLaster** [comment]
closing this issue as it is probably harder than it's worth.
