### ISSUE TITLE
Broken links for "Tests" at the CONTRIBUTING.md document

### ISSUE THREAD

**Issue by shlomif** [devtools-html/debugger.html#1423]
At https://github.com/devtools-html/debugger.html/blob/master/CONTRIBUTING.md#tests the "Tests"/"unit tests"/etc. links are broken. Preferably, they should point to some useful information, but at the very least they should not be broken and say "To be filled in.".

**Comment by clarkbw** [comment]
Good find!  I believe that was supposed to link here: https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#testing

**Comment by jasonLaster** [comment]
This is fixed here https://github.com/devtools-html/debugger.html/pull/1379
