### ISSUE TITLE
[UX] Missing tooltips for newtab, close tab and delete breakpoint

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#1424]
Currently, there are new tooltips for newtab and close tab. I'd suppose:
- for new tab `+` button: `Open a new tab (Ctrl+P)`
- for close tab: `Close tab`
- for delete a breakpoint (same icon icon like for close tab): `Delete breakpoint` (or maybe `Remove breakpoint`?)

This wording is similar to Firefox browser. 

Tooltips are helpful hints for new users, but also great for advanced users if they show their shortcut (discoverability).

**Comment by jnachtigall** [comment]
> for new tab + button: Open a new tab (Ctrl+P)

Rethinking this: Actually it does not really open a new tab as @jlongster correctly pointed out in [this comment](https://github.com/devtools-html/debugger.html/issues/1418#issuecomment-266570569) . So I guess the tooltip should rather be `Search for files (Ctrl+P)` so it's in line with the other wording around Ctrl+P stuff

**Comment by jasonLaster** [comment]
Here's a patch to get started

```diff
diff --git a/src/components/Breakpoints.js b/src/components/Breakpoints.js
index 9db77d2..b81e598 100644
--- a/src/components/Breakpoints.js
+++ b/src/components/Breakpoints.js
@@ -106,7 +106,8 @@ const Breakpoints = React.createClass({
       ),
       dom.div({ className: "breakpoint-snippet" }, snippet),
       CloseButton({
-        handleClick: (ev) => this.removeBreakpoint(ev, breakpoint)
+        handleClick: (ev) => this.removeBreakpoint(ev, breakpoint),
+        title: "" // <--
       }));
   },

diff --git a/src/components/SourceTabs.js b/src/components/SourceTabs.js
index 1866182..aad0481 100755
--- a/src/components/SourceTabs.js
+++ b/src/components/SourceTabs.js
@@ -255,12 +255,16 @@ const SourceTabs = React.createClass({
       },
       isPrettyCode ? Svg("prettyPrint") : null,
       dom.div({ className: "filename" }, filename),
-      CloseButton({ handleClick: onClickClose }));
+      CloseButton({
+        handleClick: onClickClose,
+        title: "" // <---
+      }));
   },

   renderNewButton() {
     return dom.div({
       className: "new-tab-btn",
+      title: ""// <---
       onClick: () => this.props.toggleFileSearch(true)
     }, Svg("plus"));
   },
```

**Comment by irfanhudda** [comment]
Can I start working on this?
