### ISSUE TITLE
[UX] Show fullpath of file in tooltip when hovering Ctrl-P'ed files

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#1426]
STR:
I have very similar filename's in my project:
![2016-12-12 11_07_34-bundesministerium fur familie senioren frauen und jugend - gleichstellungsatla](https://cloud.githubusercontent.com/assets/3307404/21095478/d31ff068-c05b-11e6-964b-5a94be4aec95.png)

Real world project ;) Very hard to tell which of the two `production.js` files is the one I am looking for. So I hovered over the file.

AR:
Mousehover does not show any tooltip.

ER:
Mousehover should show a tooltip with the full path of the file.

In the end I guess that this is not so uncommon as many build tools (we use grunt) end up creating files like `app.js` or similar.

There's already part of the file path below the filename. But as you see in the shortcut, it is cut off in a way that it does not help me.

PS Sorry for all these not-sooo-important nitpicking bugs. But I guess it's the all these fine details that make a great tool :)

**Comment by jnachtigall** [comment]
Just looked at the old debugger, which shows the full URL path on mouseover (in the source tree). Like this would be good.

**Comment by jasonLaster** [comment]
@jnachtigall great find! 

* we should use CSS to truncate based on the width of the pane. You have lots of space, why are we cutting it off at 50 
* I think we should show a tooltip, it's a little extra noise but could help in this case.
* I actually got the tooltip in chrome devtools source modal. So, I hear your pain :)

```diff
diff --git a/src/components/SourceSearch.js b/src/components/SourceSearch.js
index a5d9fa6..c61a724 100644
--- a/src/components/SourceSearch.js
+++ b/src/components/SourceSearch.js
@@ -19,6 +19,8 @@ const Autocomplete = createFactory(require("./Autocomplete"));
 function searchResults(sources) {
   function getSourcePath(source) {
     const { path, href } = parseURL(source.get("url"));
+
+    // => why are we always trunctating here?
     // for URLs like "about:home" the path is null so we pass the full href
     return endTruncateStr((path || href), 50);
   }
```

![screen shot 2016-12-12 at 10 55 09 am](https://cloud.githubusercontent.com/assets/254562/21105795/8985dd0c-c059-11e6-9eee-fbbbff13c20d.png)
