### ISSUE TITLE
Add button to hightlight (hover) or select (click) DOM nodes

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#1427]
The old debugger had way to hightlight/select DOM nodes. Really missing it:

Old debugger:
![2016-12-12 11_32_10-program manager](https://cloud.githubusercontent.com/assets/3307404/21096255/7834c4f4-c05f-11e6-943a-8d68204f1987.png)

debugger.html:
![2016-12-12 11_23_31-html-element](https://cloud.githubusercontent.com/assets/3307404/21096258/7bd14574-c05f-11e6-8720-54017fac5ef1.png)

**Comment by jnachtigall** [comment]
oh, just discovered https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Highlight_and_inspect_DOM_nodes which describes this feature and has a note that this is not yet available. Maybe the note should add a link to a bug report one can follow (in case there is one, could not find any)

**Comment by jasonLaster** [comment]
@juliandescottes were you looking at this?

**Comment by clarkbw** [comment]
I saw this the other night so here's some reference points.

This is where a `DOMNode` is detected.  Our location might be [somewhere here](https://github.com/devtools-html/debugger.html/blob/master/src/components/ObjectInspector.js#L142-L172)

https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/widgets/VariablesView.jsm#2483

```js
    // DOMNodes get special treatment since they can be linked to the inspector
    if (this._valueGrip.preview && this._valueGrip.preview.kind === "DOMNode") {
      this._linkToInspector();
    }
```

And starting from here on down is where the action is.

https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/widgets/VariablesView.jsm#2741

```js
  _isLinkableToInspector: function () {
    let isDomNode = this._valueGrip && this._valueGrip.preview.kind === "DOMNode";
    let hasBeenLinked = this._linkedToInspector;
    let hasToolbox = !!this.toolbox;

    return isDomNode && !hasBeenLinked && hasToolbox;
  },
```

```js
  _linkToInspector: function () {
    if (!this._isLinkableToInspector()) {
      return;
    }

    // Listen to value mouseover/click events to highlight and jump
    this._valueLabel.addEventListener("mouseover", this.highlightDomNode, false);
    this._valueLabel.addEventListener("mouseout", this.unhighlightDomNode, false);

    // Add a button to open the node in the inspector
    this._openInspectorNode = this.document.createElement("toolbarbutton");
    this._openInspectorNode.className = "plain variables-view-open-inspector";
    this._openInspectorNode.addEventListener("mousedown", this.openNodeInInspector, false);
    this._title.appendChild(this._openInspectorNode);

    this._linkedToInspector = true;
  },
```

```js
  openNodeInInspector: function (event) {
    if (!this.toolbox) {
      return promise.reject(new Error("Toolbox not available"));
    }

    event && event.stopPropagation();

    return Task.spawn(function* () {
      yield this.toolbox.initInspector();

      let nodeFront = this._nodeFront;
      if (!nodeFront) {
        nodeFront = yield this.toolbox.walker.getNodeActorFromObjectActor(this._valueGrip.actor);
      }

      if (nodeFront) {
        yield this.toolbox.selectTool("inspector");

        let inspectorReady = defer();
        this.toolbox.getPanel("inspector").once("inspector-updated", inspectorReady.resolve);
        yield this.toolbox.selection.setNodeFront(nodeFront, "variables-view");
        yield inspectorReady.promise;
      }
    }.bind(this));
  },
```

**Comment by jasonLaster** [comment]
Ahh, @juliandescottes I believe you were looking at the inverse, linking from the inspector to the debugger.

**Comment by jasonLaster** [comment]
moving this to the enhancements board https://github.com/devtools-html/debugger.html/projects/5

Thanks!

**Comment by nchevobbe** [comment]
Reps should have what's needed to _show_ the icon.
For element-node and text-node, it checks if `grip.preview.isConnected` is true, and if some props were passed (`onDOMNodeMouseOver`, `onDOMNodeMouseOut`, `onInspectIconClick`)

So the following show the icon in the debugger …
```diff
diff --git a/src/components/shared/Rep.js b/src/components/shared/Rep.js
index 16a565a1..1675a32e 100644
--- a/src/components/shared/Rep.js
+++ b/src/components/shared/Rep.js
@@ -9,9 +9,15 @@ type RenderRepOptions = {
 };

 import { REPS } from "devtools-reps";
-const { Rep: _Rep, Grip } = REPS;
-const Rep = createFactory(_Rep);
+const { Rep, Grip } = REPS;

 export default function renderRep({ object, mode }: RenderRepOptions) {
-  return Rep({ object, defaultRep: Grip, mode });
+  return Rep({
+    object,
+    defaultRep: Grip,
+    mode,
+    onDOMNodeMouseOver: x => console.log(x),
+    onDOMNodeMouseOut: x => console.log(x),
+    onInspectIconClick: x => console.log(x),
+  });
 }
```
… but does not do the linking by itself.
You then have to call `toolbox.highlighterUtils` functions like [we do in the console.](http://searchfox.org/mozilla-central/rev/dc1f84cb436f47b9d8b2fa2fecbb809c1acd7c89/devtools/client/webconsole/new-console-output/new-console-output-wrapper.js#94-120)

I don't really know the code of the debugger and how to get the reference to the toolbox though.
If anyone has an idea, please chim in so I can implement this.

Another issue to be take care of would be to stop the propagation of the click event on the inspect icon. If not, other click listeners could be triggered (like the ObjectInspector expand/collapse).

**Comment by nchevobbe** [comment]
If someone wants to work on this, I can mentor them :)

**Comment by TheKK** [comment]
Hi, is this still an issue? I'd like to take this one :)

**Comment by jnachtigall** [comment]
Thanks :) It's still an issue. Probably best to follow up on the comment by nicolas above and follow the getting started section https://github.com/devtools-html/debugger.html#table-of-contents

Pinging @jasonLaster fyi and @nchevobbe for possible mentorship
