### ISSUE TITLE
[Scopes panel] Sort global (Window) variables alphabetically

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#1452]
Use case: I wanted to look up some values of a `MyApp.whatever.someVar` variable. This was not possible because the Global vars are not sorted but seem to be listed in some random form:

![2016-12-16 13_49_07-posteingang - jens nachtigall init de - outlook](https://cloud.githubusercontent.com/assets/3307404/21263409/de5fcf96-c396-11e6-9956-abe8f69bad7d.png)

See the really small scrollbar meaning that there are lots of properties in the `Window.` namespace.

This is a bit unfortunate, because if you have code like that references `MyApp.whatever.someVar` directly, then there's currently no (practical) way to find out the value of  `MyApp.whatever.someVar` because there's also no mouseover var popup.

I'd propose that the properties of  `Window.` are sorted alphabetically.

**Comment by clarkbw** [comment]
Figured this out!

The expand takes place here:
https://github.com/devtools-html/debugger.html/blob/master/src/components/ObjectInspector.js#L86-L107

You can add a `sort()` function like I did here:

```js
  makeNodesForProperties(objProps, parentPath) {
    const { ownProperties, prototype } = objProps;

    const nodes = Object.keys(ownProperties).filter(name => {
      // Ignore non-concrete values like getters and setters
      // for now by making sure we have a value.
      return "value" in ownProperties[name];
    }).sort((a, b) => a.localeCompare(b)).map(name => {
      return createNode(name, `${parentPath}/${name}`, ownProperties[name]);
    });

    // Add the prototype if it exists and is not null
    if (prototype && prototype.type !== "null") {
      nodes.push(createNode(
        "__proto__",
        `${parentPath}/__proto__`,
        { value: prototype }
      ));
    }

    return nodes;
  },
```

The question becomes what kind of sort?

`.sort((a, b) => a.localeCompare(b))` ignores case

![screen shot 2016-12-16 at 1 43 21 pm](https://cloud.githubusercontent.com/assets/2134/21279630/00ebb508-c396-11e6-9214-081e09008d66.png)

And `.sort()` sorts by case first

![screen shot 2016-12-16 at 1 47 01 pm](https://cloud.githubusercontent.com/assets/2134/21279661/2a3c6830-c396-11e6-8cd4-ff13e8829122.png)

**Comment by clarkbw** [comment]
We should probably look at what we previously did and what chrome does here.  @jasonLaster any ideas?

**Comment by clarkbw** [comment]
Looks like everyone uses the `sort()` method.

**Comment by jnachtigall** [comment]
A "simple" sort is fine, but I think we could do better :) Normally, a user is looking into the global scope for some custom `MyApp` property and not so much for all these standard methods/properties. So I think it would be better to somehow (visually) groups these differently, e.g.:

```
MyApp
YetAnotherMyApp
-- separator ---------------
AnalyerNode
Animation
Array
<and-so-on>
...
```

or even having a section for common lib properties in between:
```
MyApp
YetAnotherMyApp
-- separator (libs) ---------------
$ (jQuery)
_ (lodash)
Backbone
-- separator (known prototype stuff) ---------------
AnalyerNode
Animation
Array
<and-so-on>
...
```


Maybe this could be added to the future enhancement whiteboard for reevaluation (and maybe also looking into how other IDEs do it for different languages)

**Comment by jasonLaster** [comment]
Yup, I like the idea of calling out non-default window properties too. 

Will open in a new issue
