### ISSUE TITLE
Polish Debugger UI rough edges

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1460]
I talked with @darkwing earlier today and we found some rough edges that can be polished

- [x] variable view highlight row should be the full width [1]
- [ ] clicking "Cmd+P to search" can open the source search input. Generally it is awkward that the search search input is in the center, but the prompt is in the left pane
- [x] the source search placeholder should be "Search Sources..." not "Search..." because it can be confused with searching for code
- [ ] the source search close button is too dark. It should be the same color as the new tab "+" button
- [x] source tab close buttons have more right padding than left padding to acomodate for the close button. [2] chrome is cleaner 
- [x] source tab with the formatted suffix should hide the formatted suffix and show the pretty print icon in the left. [3]
- we found a search bug where source search was "query [Object object]" could be fixed in github
- [ ] the dark mode text selection makes it hard to read the code. We should find another color that is much closer to the background so it doesn't make the source text look bad
- [ ] the secondary text used for a breakpoint line snippet and call frame source filename is too grey.

[1] variable view highlight row
![](http://g.recordit.co/BqrP5mZt49.gif)

[2] chrome tabs are cleaner in that they don't show the tab unless its active. this makes the right padding issue less of a problem

![](http://g.recordit.co/Iad4BWn6bt.gif)

[3] early source tab designs showed a pause indicator on the left. We could use that space for the blue pretty print icon. As a side-note, i think the pause icon is still useful as well.

![screen shot 2016-12-16 at 3 38 34 pm](https://cloud.githubusercontent.com/assets/254562/21277708/c44b0706-c3a5-11e6-8235-49368be5a2d0.png)

**Comment by clarkbw** [comment]
> the source search placeholder should be "Search Sources..." not "Search..." because it can be confused with searching for code

I think this text might read a little long, we're low on space here and this is supposed to be secondary to the larger "search for files" that lives in the editor space.

**Comment by clarkbw** [comment]
Perhaps shorten it to: '⌘+P search files'

**Comment by jasonLaster** [comment]
@clarkbw actually I was referring to the center pane being vague, but i can see the label being vague as well.

![screen shot 2016-12-16 at 6 25 24 pm](https://cloud.githubusercontent.com/assets/254562/21281719/0dad31dc-c3bd-11e6-9a2c-9ed0ff160e9a.png)


How does that look? I'm a minimalist, so I'd be okay with the label being "⌘+P" too with a tooltip, "search files"

**Comment by wldcordeiro** [comment]
I still kind of like surfacing more than just the search command in center pane. Atom does this rather nicely with tips and other shortcuts. I had opened an issue #776  to do this, it's not a hard change though we could come up with a list of tips/tricks to display.

**Comment by jasonLaster** [comment]
Yup, @wldcordeiro i think you're right it just requires coming up with compelling tips. Add them to #776 and we'll re-open :)

**Comment by clarkbw** [comment]
#1477 added the pretty print icon

**Comment by jasonLaster** [comment]
closing as the other issues are broken out.
