### ISSUE TITLE
[Source Search] autocomplete has duplicate result keys

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1467]
So cnet has some duplicate search result keys, URLs are probably different but the way we key the result is not great. very edge case

STR:
- debug to cnet.com
- Cmd+P 
- type t

You will see errors that there were many results with the key `$/cbsdfp5832910442/moatad=1js` this looks like a case of a bad result key, which should come from:

```diff
diff --git a/src/components/Autocomplete.js b/src/components/Autocomplete.js
index c1b2d60..5aba06b 100644
--- a/src/components/Autocomplete.js
+++ b/src/components/Autocomplete.js
@@ -93,7 +93,7 @@ const Autocomplete = React.createClass({
     return dom.li(
       {
         onClick: () => this.props.selectItem(result),
-        key: result.value,
+        key: result.value, // <= not very specific i guess
         title: result.value,
         className: classnames({
           selected: index === this.state.selectedIndex
```

![](http://g.recordit.co/0LiBGexrXL.gif)

**Comment by clarkbw** [comment]
Not sure if this will always be unique, I was thinking host + value but it seems to work based on the CNN case.  Using `id + value` appears to give me a unique id for the Wheel of Fortune test (RSTLNE).  IDs look like: `"server1.conn4.child4/41"` and values look like: `"/esf.js"` so combined they are `"server1.conn4.child4/41/esf.js"`.

```js
  renderSearchItem(result, index) {
    return dom.li(
      {
        onClick: () => this.props.selectItem(result),
        key: `${result.id}${result.value}`,
        title: result.value,
        className: classnames({
          selected: index === this.state.selectedIndex
        })
      },
      dom.div({ className: "title" }, result.title),
      dom.div({ className: "subtitle" }, result.subtitle)
    );
  },
```
