### ISSUE TITLE
[Scopes Pane] call out non-default global properties

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1470]
@jnachtigall mentioned [here](https://github.com/devtools-html/debugger.html/issues/1452#issuecomment-267762029) that it would be nice to separate out non-default global properties.

We have a couple options:
* group them
* or style them differently

Chrome currently formats them differently with a slight color change
I personally prefer grouping them, so that it's a little bit more discoverable. 

![screen shot 2016-12-17 at 8 38 01 am](https://cloud.githubusercontent.com/assets/254562/21287218/4efd4fec-c434-11e6-9b99-f33d09294944.png)

**Comment by clarkbw** [comment]
Yeah, I'd like to see a grouping.

I think as a baseline you could probably easily group the non-default Window props up to the top.  
![scopes-grouped](https://cloud.githubusercontent.com/assets/2134/21290251/294a8498-c468-11e6-9a5d-bd6551cc1fa4.png)

To further the feature you could try separating out known  library props but I think that would be an entirely different project in scope.

**Comment by clarkbw** [comment]
Dug in a little deeper.

Chrome seems to use the `enumerable` property for deciding to fade out the item.  This creates a number of hit or miss properties.  But probably works better than nothing.  Given its not a great system I don't think grouping would work out well here.

You can get some nice separation like this:

<img width="298" alt="screen shot 2016-12-18 at 10 40 30 pm" src="https://cloud.githubusercontent.com/assets/2134/21303435/3c197c12-c573-11e6-9cb8-8d2af08ab4bb.png">

But you can also get lots of not really useful ones like these: (`btoa`?)

<img width="291" alt="screen shot 2016-12-18 at 10 40 51 pm" src="https://cloud.githubusercontent.com/assets/2134/21303439/3f5119ee-c573-11e6-8cd0-201e8c490b4d.png">

Might be worth trying as it is a little helpful, but I think we could do better.

**Comment by clarkbw** [comment]
Here's what it would take to do that (in ObjectInspector)

```js
      dom.span({ className: classnames("object-label",
               { enumerable: !item.contents.enumerable && !nodeHasChildren(item) }) },
               item.name),
```

```css

.object-node .enumerable {
  opacity: 0.5;
}
```

**Comment by clarkbw** [comment]
Putting up a PR for this initial change.  We can talk about doing further work but this moves us in a good direction for now.
