### ISSUE TITLE
Odd/Incorrect Tab Name 

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#1476]
I was using ESPN as my testing site and, when opening `moatad.js` from the source tree, the tab opened as `...atSW=5B9372C1-A35B-46C7-A504-F1E86B86FEE3&zMoatOF=`.  The actual URL is: `http://js.moatads.com/espndfp832188684382/moatad.js#moatClientLevel1=29724777&moatClientLevel2=467209497&moatClientLevel3=221884737&moatClientLevel4=107681394537&moatClientSlicer1=104318097&moatClientSlicer2=104335617&zMoatPS=incontent&zMoatST=&zMoatSW=5B9372C1-A35B-46C7-A504-F1E86B86FEE3&zMoatOF=`  

Since I clicked `moatad.js` in the source tree, I would expect the tab to open as `moatad.js`.

<img width="954" alt="oddtabname" src="https://cloud.githubusercontent.com/assets/46655/21318505/149758a6-c5cf-11e6-9691-1e1c6f9b7186.png">

**Comment by jasonLaster** [comment]
haha that's pretty funny, i was using `cnet` as my testing site, and also found  `moatad.js` and the tab value as well!!!

This is definitely an issue.

I recommend doing 

```js
Object.values(appStore.getState().sources.toJS().sources))
```

and taking a look at what that source URL really is

**Comment by arthur801031** [comment]
@jasonLaster 

I will take a look at this tomorrow :)
