### ISSUE TITLE
[Editor] New Tab button positioning 

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1489]
We recently added the collapse buttons in the editor header, which threw off the new tab button positioning.

There are two issues that i see:

1. left positioning when a tab is there
2. right positioning when it gets narrow

Here's some [code](https://gist.github.com/jasonLaster/54ee561754869579914d2e94a89a6588) to help you get started.

#### UI

![](http://g.recordit.co/rByG5JtyPt.gif)

**Comment by binarybaba** [comment]
Hey jason, newbie here.. new to yarn too but when I run yarn run chrome, it kind of assumes that I'm on a mac and gives an error. FF works fine. Does that mean I'll have to use only ff while debugging? I'm on ubuntu.

Hmm, could not find the path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome.
Try looking for chrome with ls /Applications
chrome exited with code -2
Done in 0.92s.

**Comment by jasonLaster** [comment]
Ahh. Thanks for the question and in fact this seems like an opportunity for
a PR?

The script runs the chrome bin, which is inside of your chrome app. On Macs
that's in /applications but it sounds like for Ubuntu that's somewhere
else. It'd be awesome if the script knew to check on Ubuntu on another
likely location.

**Comment by binarybaba** [comment]
tbh I'm just trying to get my head around oss contributions and I sort of picked this one for my first stab. I'm fine working on ff. I've opened 8000 on chrome. Just set up the dev env and it's too late in the night. I'll try looking at it tomorrow first thing in the morning see if I can fix this and submit a PR. :D

**Comment by jasonLaster** [comment]
Thanks. You found a great issue for a first bug. Thanks for the help
