### ISSUE TITLE
[Copy Source URL] add command to Editor and Source Tree context menus

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1490]
We recently added [copy source url](https://github.com/devtools-html/debugger.html/pull/1409) to the source tabs. We should do the same with right clicking in the editor, source tree and call frame. 

#### patch 

Here's a [patch](https://gist.github.com/jasonLaster/a980280dbfc0c1810e95759a2f0bbbc6) with some code to get you started.

```
curl https://gist.githubusercontent.com/jasonLaster/a980280dbfc0c1810e95759a2f0bbbc6/raw/b0fa9ad66712ac5df36f512cace09fd99706e2bb/foo.diff | git apply
```

[clipboard.js](https://gist.github.com/jasonLaster/904a7f547c1c3f6b03cea2596d982815) utility.

#### Copy Source URL in tabs
![](http://g.recordit.co/hm3PIsNbnu.gif)

**Comment by jacobjzhang** [comment]
@jasonLaster I think this could be interesting. May I?

**Comment by jacobjzhang** [comment]
@jasonLaster Hey dumb question, where do I find how to get the source URL for frames and the source tree? I see getSelectedSource in Editor.js but am assuming getSelectedFrame is more useful-- do we need to write a function to keep the URL structures the same?

**Comment by jasonLaster** [comment]
Good question. We should have the frame location and get the source for
each frame.

This is your second time looking at the call stack

**Comment by jasonLaster** [comment]
@jacobjzhang looks like frames already have a source

https://github.com/devtools-html/debugger.html/blob/master/src/components/Frames.js#L119-L122
