### ISSUE TITLE
[Reveal Source] update copy

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1494]
We currently use the copy "show source" which is a little vague.

Other editors debuggers have other copy:
* atom: "Reveal in Tree View"
* chrome: "Reveal in Navigator"

I like the verb reveal, and would prefer something simple like `Reveal in Tree'. Thoughts?

![](http://g.recordit.co/4KNGgbur1Y.gif)

**Comment by darkwing** [comment]
"Reveal in Tree" sounds excellent to me.

**Comment by jasonLaster** [comment]
@irfanhudda, @krishnagopinath easy one

**Comment by irfanhudda** [comment]
@jasonLaster Is this just renaming context menu item?

**Comment by jasonLaster** [comment]
yup

**Comment by irfanhudda** [comment]
I'll take this then.
