### ISSUE TITLE
[Collapse Buttons] Animate toggling

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1502]
We should animate the expanding and collapsing sidebars when the buttons is clicked.

**Comment by jasonLaster** [comment]
@binarybaba i think this might help if you're interested in picking it up again: 
https://github.com/devtools-html/debugger.html/issues/1503#issuecomment-270721409

**Comment by wldcordeiro** [comment]
@jasonLaster the buttons themselves are animated. It's the `SplitBox` itself that isn't https://github.com/devtools-html/debugger.html/blob/master/src/components/PaneToggleButton.css#L6

**Comment by binarybaba** [comment]
I'm scared of react but I'll definitely try it tomorrow.. Will see if I can wrap my head around it and tomorrow update you guys!

**Comment by jasonLaster** [comment]
We just landed https://github.com/devtools-html/debugger.html/pull/1666

maybe we can borrow the same approach https://github.com/liorpr/debugger.html/blob/3fc1900cec4fccd6234b0459b0d3a6d26f7dfc9e/src/components/SecondaryPanes/CommandBar.js#L66-L77

**Comment by jasonLaster** [comment]
@liorpr are you on this?

**Comment by liorpr** [comment]
@jasonLaster yes!

**Comment by liorpr** [comment]
got kinda stuck, when the pane collapses the split box actually just re-renders without the first pane(let's say I'm collapsing the first one) and the other one is just there, taking as much width as it needs with flex: 1. Tried to render the first pane with width: 0 and transition the width but it's so slow.

@jasonLaster

**Comment by jasonLaster** [comment]
haha - screw it. this sounds too hard lol. I think react fiber will help.

**Comment by jasonLaster** [comment]
As a record, the issue is that splitbox is a no-op when the pane is closed. This makes it really hard to animate. Fiber will help :)
