### ISSUE TITLE
[CommandBar] flash pressed state of command buttons

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1503]
Especially with keyboard shortcuts we need to make it more obvious which button in the `CommandBar` was activated.  Some kind of flash animation on the button?

**Comment by jasonLaster** [comment]
Here's a quick patch that might help someone get started. 

It's kinda cool that we can get this effect actually 😉 

```patch
diff --git a/src/components/CommandBar.css b/src/components/CommandBar.css
index ad4f66f..394b5fb 100644
--- a/src/components/CommandBar.css
+++ b/src/components/CommandBar.css
@@ -7,6 +7,10 @@
   padding: 8px 5px;
 }

+.command-bar > span.pressed {
+ transition: /* https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions */
+}
+
 .command-bar > span {
   cursor: pointer;
   width: 16px;
diff --git a/src/components/CommandBar.js b/src/components/CommandBar.js
index 3153000..58bbf17 100644
--- a/src/components/CommandBar.js
+++ b/src/components/CommandBar.js
@@ -70,6 +70,16 @@ function debugBtn(onClick, type, className, tooltip) {
   );
 }

+function showPressedAnimation(element) {
+      button.classList.addClass("pressed")
+      setTimeout(() => {
+        button.classList.removeClass("pressed")
+      }, 200)
+
+      // better than timeout would be listening for animationend
+      // https://developer.mozilla.org/en-US/docs/Web/Events/animationend
+}
+
 const CommandBar = React.createClass({
   propTypes: {
     sources: PropTypes.object,
@@ -103,11 +113,17 @@ const CommandBar = React.createClass({
   componentDidMount() {
     const shortcuts = this.context.shortcuts;
     const handleEvent = (e, func) => {
+      // the important thing is we can perhaps do something here
+      // the challenge is to get a reference to the command button
+      // add the class and then remove it in some amount of time
+      const button = e.target;
+      showPressedAnimation(button)
       e.preventDefault();
       e.stopPropagation();
       func();
     };

+  // heres the crazy code where we add command event listeners
     COMMANDS.forEach((action) => shortcuts.on(
```

**Comment by liorpr** [comment]
started to implement this, but got kinda stuck. the buttons are re-rendered so fast(due to the change of the app state and thus the component's props after the action is triggered) that you can't even see the animation.
I'd like to hear your thoughts :)
@jasonLaster @clarkbw

**Comment by jbhoosreddy** [comment]
I don't completely understand the problem you're mentioning. But if the problem is caused by component rendering too fast, maybe you could look into shouldComponentUpdate method in react component lifecycle. You can use this to control when the component is re rendered by react. Maybe that helps!

**Comment by clarkbw** [comment]
Yeah, you could look over the [shouldcomponentupdate](https://facebook.github.io/react/docs/react-component.html#shouldcomponentupdate) docs.  Its also possible that CommandBar should be a `React.PureComponent` instead since its not doing anything complicated.  These are all interesting areas of React performance that I'm only just getting into so I don't want to steer you in the wrong direction.  But without looking into it deeply I think that's worth investigating.
