### ISSUE TITLE
Consider Showing "Conditional" breakpoint icon

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#1505]
It might be nice to show an icon or signifier in the top right column for conditional breakpoints, if only to show that they aren't always the same.

<img width="1262" alt="conditional" src="https://cloud.githubusercontent.com/assets/46655/21367762/fb2c4c18-c6c4-11e6-8c52-0eacc2be9720.png">

**Comment by clarkbw** [comment]
Not sure if I found the right long term solution but I think its subtle yet still indicates the difference.

**Comment by jasonLaster** [comment]
Yup. I think it's good enough for now :)
