### ISSUE TITLE
[RTL] Update the breakpoints component

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1506]
It would be great if the the breakpoints component were more RTL friendly

Here are a couple things that I noticed:
* the green border should be on the right
* the left padding should be on the right so that items line up well

Getting started
* here are some [rtl](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#rtl) docs.
* we use postcss bi-direction for some magic CSS RTL clauses

![screen shot 2016-12-20 at 5 23 14 pm](https://cloud.githubusercontent.com/assets/254562/21370312/0ec6b88a-c6d9-11e6-8ae9-b5a05a127feb.png)

CC @liorpr

**Comment by clarkbw** [comment]
I don't think anyone is currently working on this. Setting back to `up for grabs`

**Comment by irfanhudda** [comment]
I would like to work on this

**Comment by jasonLaster** [comment]
Thanks @irfanhudda
