### ISSUE TITLE
[RTL] Improve search bars

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1507]
This issue tracks cleaning up the file search and source search bar components in RTL mode.

Getting started
* here are some [rtl](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#rtl) docs.
* we use postcss bi-direction for some magic CSS RTL clauses

#### Source Search
![](http://g.recordit.co/ZY9SfeMTvL.gif)

#### File Search
![](http://g.recordit.co/osqkiSrJDG.gif)

**Comment by liorpr** [comment]
@jasonLaster hmm should it remain open?

**Comment by jasonLaster** [comment]
Nope!
