### ISSUE TITLE
[Editor] Multiple Highlight Lines

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1510]
It's possible to add breakpoints in different sources, such that clicking on 

Steps to Reproduce:
* 1. go to todomvc
* 2. add breakpoints in app-view and todo-view
* 3. click on the breakpoints in the list alternating between todo-view and app-view breakpoints

#### Patch

```diff
diff --git a/src/test/mochitest/browser_dbg-editor-highlight.js b/src/test/mochitest/browser_dbg-editor-highlight.js
index d7892e6..7a9e2a1 100644
--- a/src/test/mochitest/browser_dbg-editor-highlight.js
+++ b/src/test/mochitest/browser_dbg-editor-highlight.js
@@ -5,10 +5,12 @@
 // matter if the source text doesn't exist yet or even if the source
 // doesn't exist.

+// we do have some tests for highlighting
+
 add_task(function* () {
   const dbg = yield initDebugger("doc-scripts.html");
   const { selectors: { getSourceText }, getState } = dbg;
-  const sourceUrl = EXAMPLE_URL + "long.js";
+  const sourceUrl = `${EXAMPLE_URL }long.js`;

   // The source itself doesn't even exist yet, and using
   // `selectSourceURL` will set a pending request to load this source
diff --git a/src/test/mochitest/browser_dbg-editor-select.js b/src/test/mochitest/browser_dbg-editor-select.js
index 8b954f8..e490c1e 100644
--- a/src/test/mochitest/browser_dbg-editor-select.js
+++ b/src/test/mochitest/browser_dbg-editor-select.js
@@ -4,6 +4,8 @@
 // Tests that the editor highlights the correct location when the
 // debugger pauses

+// and some tests for debug-line too
+
 // checks to see if the first breakpoint is visible
 function isElementVisible(dbg, elementName) {
   const bpLine = findElement(dbg, elementName);
```

We also have some tests

```diff
diff --git a/src/test/mochitest/browser_dbg-editor-highlight.js b/src/test/mochitest/browser_dbg-editor-highlight.js
index d7892e6..7a9e2a1 100644
--- a/src/test/mochitest/browser_dbg-editor-highlight.js
+++ b/src/test/mochitest/browser_dbg-editor-highlight.js
@@ -5,10 +5,12 @@
 // matter if the source text doesn't exist yet or even if the source
 // doesn't exist.

+// we do have some tests for highlighting
+
 add_task(function* () {
   const dbg = yield initDebugger("doc-scripts.html");
   const { selectors: { getSourceText }, getState } = dbg;
-  const sourceUrl = EXAMPLE_URL + "long.js";
+  const sourceUrl = `${EXAMPLE_URL }long.js`;

   // The source itself doesn't even exist yet, and using
   // `selectSourceURL` will set a pending request to load this source
diff --git a/src/test/mochitest/browser_dbg-editor-select.js b/src/test/mochitest/browser_dbg-editor-select.js
index 8b954f8..e490c1e 100644
--- a/src/test/mochitest/browser_dbg-editor-select.js
+++ b/src/test/mochitest/browser_dbg-editor-select.js
@@ -4,6 +4,8 @@
 // Tests that the editor highlights the correct location when the
 // debugger pauses

+// and some tests for debug-line too
+
 // checks to see if the first breakpoint is visible
 function isElementVisible(dbg, elementName) {
   const bpLine = findElement(dbg, elementName);
```

![](http://g.recordit.co/xXYPSm2c6O.gif)

**Comment by jasonLaster** [comment]
@Zacqary interested in this gnarly bug?

**Comment by Zacqary** [comment]
If I'm understanding correctly, the expected behavior is:

- When you click on a breakpoint in the Breakpoints sidebar, only that breakpoint's line should be highlighted
- When you switch tabs to a new source, all of its breakpoints' lines should be highlighted

And the actual behavior is:

- When you click on a breakpoint in the Breakpoints sidebar that's in a different source, it will switch the tab, and then default to the behavior where it highlights all breakpoints instead of only highlighting the one you clicked on?

**Comment by Zacqary** [comment]
Oh actually it looks like in the GIF it's not even highlighting *all* of them when you switch the tab, just one or two.

So what's the expected behavior on tab-switch then? Is it supposed to be highlighting any breakpoints when you switch the tab or not?

**Comment by jasonLaster** [comment]
Hmm. The expected behavior is that clicking a breakpoint navigates you to
where it's defined and highlights the line. Somehow several lines have the
highlight class

**Comment by jasonLaster** [comment]
@Zacqary are you you still interested in this?

@joshunger, @AbhiGulati, @sankha93 would you enjoy taking a look at this super weird bug?

**Comment by Zacqary** [comment]
I'm interested but it's been difficult to find time to contribute lately.
Don't let me hold things up if someone else wants to take it.

**Comment by jasonLaster** [comment]
no worries. happy to play it by ear.

**Comment by joshunger** [comment]
@jasonLaster I might be interested but busy at the moment... hard to find time

**Comment by joshunger** [comment]
Note this bug on the backbone example - http://todomvc.com/examples/backbone/
