### ISSUE TITLE
Working with Source mapped files

### ISSUE THREAD

**Issue by zspitzer** [devtools-html/debugger.html#1513]
There doesn't seem to be a way to jump to a line & column number in a file?

Minified files are often stripped of all new lines, could the source be word wrapped?

Clicking the line number currently sets a breakpoint in the source file, 
in Chrome Dev Tools clicking the line number jumps to the source file which is more useful.

It would be nice to be able to right click or double click on section of a minified mapped file and jump into the source file

When browsing a source mapped file, could the minified file be highlighted in the tree so you can see where the file comes from

**Comment by jasonLaster** [comment]
Hey @zspitzer!

Funny you ask, we just landed this https://github.com/devtools-html/debugger.html/pull/1474

I think this should address it. Clicking the gutter is an interesting idea. What we have is a little awkward now ...

**Comment by zspitzer** [comment]
hang on, what about wrapping?
