### ISSUE TITLE
[Watch Expressions] evaluate expression when not paused

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1525]
Currently the debugger evaluates watch expressions only when paused.

It would be nice if we also evaluated expression when the debugger is not paused. for example:

* `this` => `Window`
* `2 + 2` => `4`

**Comment by jbhoosreddy** [comment]
Hey @jasonLaster, initially watch expressions was evaluated as soon as it was inputted by the user but I changed it at the time to evaluate on pause. It should be an simple fix to revert it back and an easy bug to get myself back into the project. Could I take a stab at it?

**Comment by jasonLaster** [comment]
Grab it!

Watch expressions would be fun to work together on
