### ISSUE TITLE
Make debugger UI take less vertical space

### ISSUE THREAD

**Issue by nt1m** [devtools-html/debugger.html#1536]
Vertical space is very valuable especially when the debugger is inside the toolbox. It'd be nice if the heights were consistent with other tools inside the toolbox as well (I think we use 24px for toolbars).

**Comment by clarkbw** [comment]
> I think we use 24px for toolbars

I'm not sure if this was intentional or not.  Will need to investigate.

**Comment by wldcordeiro** [comment]
I could have sworn there was an effort for the vertical rhythm not too long ago and we followed guidelines @helenvholmes shared with us, but I agree that we should be consistent between tools.

**Comment by nt1m** [comment]
@clarkbw,@wldcordeiro I think the current height (24px) was decided before Helen's arrival (I remember it was discussed with Brian and Darrin). Our toolbars used a lot of vertical space before then, and 24px seemed like a reasonable height.

Either way, if there are new guidelines, all tools should follow them, not just debugger-html

**Comment by gabrielluong** [comment]
I believe we should be trending towards having more space (vertical space and bigger fonts) - since this helps with legibility as our font is already really tiny. I would hate to see the debugger.html adapt to the old standard when it should be the other way around where all the other tools should be adapting to the new standard.

**Comment by clarkbw** [comment]
Yep, I agree. There really isn't enough space with 24px.

**Comment by nt1m** [comment]
@gabrielluong @clarkbw 
For debugger.html, I would agree 24px is not enough vertical space (considering the crowded tabbar), but for the other tools, considering the low amount of content in the toolbars, 30px would be a waste, and the content would fit fine in 24px.

Here's how the toolbox used to look like if you're curious: https://people-mozilla.org/~shorlander/files/devTools-toolbox-i02/devTools-toolbox-i02.html

Our default toolbox height is 250px, and I don't think we should go above 10% for the toolbar height.

**Comment by nt1m** [comment]
@gabrielluong Also, about the font-size, it really depends on the platform you're on: Windows uses 12px, OSX uses 11px, Linux uses something huge.

**Comment by gabrielluong** [comment]
@nt1m @clarkbw @jasonLaster  Honestly, the toolbox you have shown me looks fine to me. I am sure there will be situations where you are correct such as if i had a MBA 11", but what if you had a 27" monitor instead. I know full well of the fight for consistency among our tool, but I can just as well point out as many inconsistencies we already currently have such as the filter bar in the new console and all the other tools or how the style editor does search compare to the old debugger. 

So, we should be moving forward because if we undo this change now, I know very well we will never move back towards this direction and we go back into this endless cycle where our current UX never really improves. This is an inconsistency but it is also an UX direction so let's not be undoing work and decisions that were already clearly thought out.

**Comment by nt1m** [comment]
@gabrielluong The toolbars do take quite some vertical space (percentage-wise). I don't know about people monitors, but I refer to the default toolbox height which is 250px. 

> I know full well of the fight for consistency among our tool, but I can just as well point out as many inconsistencies we already currently have such as the filter bar in the new console and all the other tools or how the style editor does search compare to the old debugger.

Unfortunately, having those inconsistencies build up makes the unpolished devtools we have today.
I understand the inconsistencies will go over time, but there are absolutely no bugs filed, no official specs about those details, which makes me think that "over time" is not close from soon and that we'll end up shipping the current mess.

If I'm filing this issue, it's just to get action/attention on this inconsistency, either in debugger-html, or either within m-c.

It would be much faster to take action on those issues if we could share CSS between m-c and debugger-html. Not sure if there are plans for that, but I thought I'd mention it.

**Comment by clarkbw** [comment]
> Our default toolbox height is 250px, and I don't think we should go above 10% for the toolbar height.

That's an interesting rule, I'm not sure where it is derived from.

I'm worried less about the inconsistency in height of toolbars (which should be fixed with shared CSS as you point out) as the inconsistent experiences of search and other actions which should be shared widgets as well.

**Comment by clarkbw** [comment]
@nt1m I think we should track this, perhaps somewhere else.  But its good that you filed this, I wasn't aware of it before now.

**Comment by jasonLaster** [comment]
>  share CSS between m-c and debugger-html

we do share css https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-launchpad/src/lib/themes

**Comment by jasonLaster** [comment]
closing as this is not actionable.

this is a useful discussion, so lets keep talking

**Comment by nt1m** [comment]
@jasonLaster There are lots of things that differ, we use inline SVGs (something I'd like to avoid) for debugger-html, we don't re-use any classes (devtools-button, devtools-*input, ...) in debugger-html, ...

**Comment by gabrielluong** [comment]
On the contrary, I would argue that there are many compelling reasons to be embracing inline SVGs. One simple example is the frustration we are dealing with SVGs in responsive.html. I do not believe the current CSS architecture in DevTools is serving us well and we do need to change how we should be doing things, but this is a bigger team discussion.

**Comment by nt1m** [comment]
@gabrielluong Using inline SVGs goes against the semantics. Let's say we want a button with an icon, the logical way to go is to use a <button> with a background-image , not to use a <span> and some random svg markup inside it (which is what debugger-html does FYI).

Also, it turns out we can use filter: url(chrome://global/skin/filters.svg#fill) to make the fill property apply (which is something I've been trying to push in m-c), which solves the problem you've pointed out.

**Comment by gabrielluong** [comment]
The modern way you will typically see it is <button><svg></button>.

**Comment by nt1m** [comment]
@gabrielluong Looks like my comment didn't render properly, corrected it now.

Irony aside, I think it's better to use correct semantics, for accessibilty and other reasons

**Comment by gabrielluong** [comment]
@nt1m See my previous comment for the proper semantics. Again, inline svg really is not disadvantaged by anything you have mention - there are proper ARIA tags available for SVGs. I would prefer to comment on inline SVG in a more relevant bug if you still hold strong opinions here, but I would suggest taking a step back to explore practical SVG usage.
