### ISSUE TITLE
[Vertical Layout] Show the correct collapse buttons

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#1537]
In the vertical layout the collapsible "panes" are different from the horizontal. Render the proper ones for the layout.

**Comment by jasonLaster** [comment]
I think we decided to use an `if` in the splitbox render to remove the content

**Comment by jasonLaster** [comment]
Here's a patch for what i started

https://gist.github.com/jasonLaster/849cac961391452b5bd8ba6fafbf8271

**Comment by wldcordeiro** [comment]
I'll grab this. I had done the other work and am familiar with the changes needed. 😄
