### ISSUE TITLE
Polish some UI colors

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1540]
We recently merged a couple of UI elements with *questionable* colors.

- [x] pause reason #1646
  * we went with an html color
  * should have a good dark theme color
- [ ] conditional breakpoint left border
  * color is probably off too dark / orange
  * it should be transparent and darker on hover like pause breakpoints [here] [1](https://github.com/clarkbw/debugger.html/blob/cond-breakpoint-in-list/src/lib/codemirror-mozilla.css#L8-L10)
  * it should have a good dark theme

---

[1] hover affect for paused breakpoints
![](http://g.recordit.co/DpmAXODzrM.gif)

**Comment by jasonLaster** [comment]
@clarkbw we have the pause reason done. Conditional BPs should be pretty straight forward

**Comment by jasonLaster** [comment]
@clarkbw I'm happy closing this and re-evaluating holistically when we tackle pausing [breakpoints]

[breakpoints]: https://docs.google.com/document/d/19l45AbZUeSj-Jf6pgM5_vyg4ghQLE3sNR2i979BA_X8/edit?usp=drive_web

**Comment by clarkbw** [comment]
Nah, I looked into this yesterday and I think a more wholistic approach would be better anyway
