### ISSUE TITLE
search is finding urls in sources panel even when collapsed

### ISSUE THREAD

**Issue by joshunger** [devtools-html/debugger.html#1549]
search is finding urls in sources panel even when collapsed.  Is search supposed to search the sources list?

1. Visit http://google.com
2. http://localhost:8000/ and debug google.com.
3. CMD + F and enter "api"
4. Notice the odd highlight to the left

![image](https://cloud.githubusercontent.com/assets/2301847/21501330/2a1c132a-cc04-11e6-8b7c-22b4cdb32c6d.png)

**Comment by jasonLaster** [comment]
hmm, I think we should suppress search on the window so that this is never available.

This is a little bit difficult because we bind cmd+f in EditorSearchBar which might only be bound once we've shown a source

**Comment by jasonLaster** [comment]
Actually, this is fixed with the new editor search bar
