### ISSUE TITLE
search can't find text below the fold

### ISSUE THREAD

**Issue by joshunger** [devtools-html/debugger.html#1550]
search can't find text below the fold

1. Visit http://todomvc.com/examples/vanillajs/
2. Debug.
3. CMD + P controller.js
4. Search for `currentPage`

EXPECTING: 4 results at the bottom of the file.
ACTUAL: Phrase not found.

5. Scroll down to the bottom of the page.
6. Search for `currentPage`
7. Results are correct

![image](https://cloud.githubusercontent.com/assets/2301847/21501652/ddde1dd4-cc06-11e6-89d4-b7dc2e8da436.png)
![image](https://cloud.githubusercontent.com/assets/2301847/21501657/04e7718c-cc07-11e6-8c61-8d4c2c577de1.png)

**Comment by clarkbw** [comment]
I think this is a "CodeMirror" thing with the built in search. Try turning on 'editorSearch' in your local confit.  See: https://github.com/devtools-html/debugger.html/blob/master/docs/feature-flags.md

Let me know if that helps!

**Comment by joshunger** [comment]
@clarkbw that fixed it!

**Comment by jasonLaster** [comment]
Great. We'll get the new search bar out soon
