### ISSUE TITLE
[Breakpoints] Move toggle button

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1558]
@Dalimil's great work in #1546 got me to re-think how we want to treat toggling breakpoints.

Previously, the button was entirely user-set i.e. I click it to disable all bps, i click it again to re-enable all bps. This was a broken metaphor because you could also enable and disable bps individually. His PR, made it act like a group checkbox which accurately reflects the BPs aggregate state.

Given that, it would be nice to change the iconography to that of a checkbox so that its clearer for the user. Also, it would be nice to move the button to the breakpoints header so it's not confused with other App state. 

Down the road, I see us using the breakpoints header space better, so this is inline with the direction we're going

![breakpoints-checkboxes](https://cloud.githubusercontent.com/assets/254562/21524880/633ba3d0-cce7-11e6-95ee-8e898814708b.jpg)

CC @clarkbw, @Dalimil

**Comment by Dalimil** [comment]
I'm working on this... but the component state is a bit complicated to maintain because 'indeterminate' can only be sent via JavaScript and 'checked=true' seems to override 'indeterminate=true'. It would need to be an uncontrolled input that is initialized after it mounts...
