### ISSUE TITLE
Add flag for Firefox nightly to firefox-driver or similar

### ISSUE THREAD

**Issue by joshunger** [devtools-html/debugger.html#1559]
It would helpful to add a flag to start Firefox nightly to firefox-driver. 

Here is my hack right now -
```js
function firefoxBinary() {
  let binary = new firefox.Binary('/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin');
  binary.addArguments(binaryArgs());
  return binary;
}
```

**Comment by jasonLaster** [comment]
That's a great call.

Here's a quick patch for what it could look like: 

```diff
 const args = minimist(process.argv.slice(2),
 {
-  boolean: ["start", "tests", "websocket"],
+  boolean: ["start", "tests", "websocket", "nightly"],
   string: ["location"],
 });

 const isWindows = /^win/.test(process.platform);
 const shouldStart = args.start;
 const isTests = args.tests;
+const useNightly = args.nightly;
 const useWebSocket = args.websocket;

 if (isWindows) {
@@ -33,7 +34,12 @@ function binaryArgs() {
 }

 function firefoxBinary() {
-  let binary = new firefox.Binary();
+  let binary;
+  if (useNightly) {
+    binary = new firefox.Binary('/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin')
+  } else {
+    binary = new firefox.Binary();
+  }
```

**Comment by joshunger** [comment]
@jasonLaster on second thought, do you loose your history every time you `yarn run firefox`?  I was seeing weird behavior.

**Comment by jasonLaster** [comment]
Yep. That's mostly intentional though w the profile.

We can have an option to pass a profile in I suppose. At some point you
just call the FF bin command yourself :)

**Comment by joshunger** [comment]
Yeah so if I'm just calling FF bin directly maybe this isn't necessary

**Comment by jasonLaster** [comment]
Yeh. This is mostly to help new comers :)

**Comment by clarkbw** [comment]
James and I talked about creating a temp profile on first run that could be reused. I think it's a good idea.

**Comment by joshunger** [comment]
@jasonLaster @clarkbw what about a quick start script instead?  It was a bit confusing to run `yarn run firefox` the first time and not have my profile.

**Comment by jasonLaster** [comment]
Hmm, what do you mean?

**Comment by joshunger** [comment]
This was my first experience -

1. Follow instructions.
2. `yarn run firefox`
3. Hit http://www.github.com
4. 😕 about why I wasn't logged in

What about a script (or scripts) that does the following -

1. finds your profile directory and prefs.js.
2. updates the prefs.js with the necessary preferences ... `devtools.debugger.remote-enabled` etc. of course while Firefox is closed
3. launches nightly

Then -

`>yarn run firefoxnightly`

Would this work? 

This might provide a better experience to the developer.

**Comment by jasonLaster** [comment]
Hmm, I think we want to route Devs to a hosted version of the debugger
examples first.

Debugging logged in pages is more advanced which we can make clear with
shift f2 and the manual step.

Perhaps we can provide a helpful console message to route Devs to the docs

**Comment by jasonLaster** [comment]
closing this as the drivers moved to devtools core.
