### ISSUE TITLE
[Chrome] Show pause reason

### ISSUE THREAD

**Issue by joshunger** [devtools-html/debugger.html#1560]
The pause reason is not shown when pausing in chrome or node.

<img width="505" alt="screen shot 2016-12-28 at 12 12 35 pm" src="https://cloud.githubusercontent.com/assets/254562/21527138/fa0353d0-ccf6-11e6-8139-79c236a4b038.png">

**Comment by jasonLaster** [comment]
Nice find @joshunger. I think this is mostly a question of adding a firefox feature, and not adding it to V8 yet.

We should have saved the *reason* in the pause data, but it is likely that we missed something or the reason is different

https://github.com/juliandescottes/devtools-core/blob/storybook/packages/devtools-client-adapters/src/chrome/events.js#L51-L54

```diff
diff --git a/src/components/WhyPaused.js b/src/components/WhyPaused.js
index 6b4f90d..c528016 100644
--- a/src/components/WhyPaused.js
+++ b/src/components/WhyPaused.js
@@ -19,6 +19,7 @@ const WhyPaused = React.createClass({

   render() {
     const { pauseInfo } = this.props;
+    // => here
     const reason = getPauseReason(pauseInfo);

     return reason ?
diff --git a/src/utils/pause.js b/src/utils/pause.js
index ded7e0b..51cabc5 100644
--- a/src/utils/pause.js
+++ b/src/utils/pause.js
@@ -23,6 +23,8 @@ function updateFrameLocations(frames: FrameType[]): Promise<FrameType[]> {
 // These are the known unhandled reasons:
 // "breakpointConditionThrown", "clientEvaluated"
 // "interrupted", "attached"
+
+// we might need a new mapping for V8
 const reasons = {
   "debuggerStatement": "whyPaused.debuggerStatement",
   "breakpoint": "whyPaused.breakpoint",
```

**Comment by bomsy** [comment]
i'm interested in this!

**Comment by clarkbw** [comment]
Here's where you can see Chrome's implementation: https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/sources/DebuggerPausedMessage.js#L34-L71

And you'll just need to grab the strings they use (aka `DK.DebuggerModel.BreakReason.DOM`) from here: https://github.com/ChromeDevTools/devtools-frontend/blob/4b57ce79c205a38d78d7d9af6e724e7c24683eb7/front_end/sdk/DebuggerModel.js#L869

```js
SDK.DebuggerModel.BreakReason = {
  DOM: 'DOM',
  EventListener: 'EventListener',
  XHR: 'XHR',
  Exception: 'exception',
  PromiseRejection: 'promiseRejection',
  Assert: 'assert',
  DebugCommand: 'debugCommand',
  Other: 'other'
};
```

**Comment by jasonLaster** [comment]
@bomsy any updates?

**Comment by bomsy** [comment]
yeah coming! :)

**Comment by bomsy** [comment]
Closing this ... still interested though why we get back only one reason type from chrome.
