### ISSUE TITLE
Update formatted code to put empty arrays and objects on one line:

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#1561]
This is a super nit, and may be out of our control to some level, but having empty braces and brackets on multiple lines stretches the formatted code too much:

<img width="267" alt="emptybrackets" src="https://cloud.githubusercontent.com/assets/46655/21527478/35886bf8-ccf1-11e6-92b7-7f716dd1318f.png">

If we could put them on one line, that would be awesome.

**Comment by jasonLaster** [comment]
Oh nice - the bug comes from @fitzgen's https://github.com/mozilla/pretty-fast lib. I'll repost
