### ISSUE TITLE
[Editor] highlighting a long line while scrolling is slow

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1562]
original issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1319743

Scrolling with the mouse for highlighting script in the new Debugger frontend is jerky and very not smooth, with increase of CPU use.

James, could you check this regression in the new Debugger, it's really painful for the user to highlight long script with the mouse.

**Comment by clarkbw** [comment]
The bug referenced has been closed.
