### ISSUE TITLE
[Sidebars] Collapsed Issues

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#1564]
I see a few issues with collapsed panes at the moment:

1.  They still have the directional CSS cursor (signaling dragability) when hovering over the border
2.  You can still click the headings to expand and contract the breakpoint headings, as well as double click sources to open on the left side.

I propose:

1.  The cursor be set to default so people don't think they can drag the panes
2.  We should use CSS `pointer-events: none` to ignore events on the collapsed pane, then maybe even add a CSS blur effect to reinforce that the pane is "bricked", so to speak

**Comment by jasonLaster** [comment]
Nice find!

The splitbox is a shared component and now lives in [devtools-core](https://github.com/devtools-html/devtools-core). It's still fairly easy to make the change and see it locally.

here's a patch that will help get started
```diff
client/shared/components/splitter/SplitBox.js
index 91f3804..fbb54cc 100644
--- a/packages/devtools-modules/client/shared/components/splitter/SplitBox.js
+++ b/packages/devtools-modules/client/shared/components/splitter/SplitBox.js
@@ -193,7 +193,7 @@ const SplitBox = React.createClass({

   render() {
     const vert = this.state.vert;
-    const { startPanel, endPanel, endPanelControl, splitterSize } = this.props;
+    const { startPanel, endPanel, endPanelControl, splitterSize, endPanelCollapsed } = this.props;

     let style = Object.assign({}, this.props.style);

@@ -217,6 +217,8 @@ const SplitBox = React.createClass({
         style: style },
         startPanel ?
           dom.div({
+
+            // we should add a 'collapsed' classname
             className: endPanelControl ? "uncontrolled" : "controlled",
             style: leftPanelStyle },
             startPanel
@@ -230,7 +232,13 @@ const SplitBox = React.createClass({
         }),
         endPanel ?
           dom.div({
+            // we should add a 'collapsed' classname
             className: endPanelControl ? "controlled" : "uncontrolled",
+            className: classnames({
+              controlled: endPanelControl,
+              uncontrolled: !endPanelControl,
+              collapsed: endPanelCollapsed
+            })
             style: rightPanelStyle },
             endPanel
           ) : null
```

**Comment by jasonLaster** [comment]
I believe @Garbee is on this

**Comment by jasonLaster** [comment]
@Garbee are you on this? 

I believe we decided to use an `if` statement in the render to just not show the splitbox content.

**Comment by Garbee** [comment]
Leave it as `Up for grabs` since if someone wants to jump in and do this before I get around to finishing it then I'm cool. Doing a major refactor in another project for a good chunk of today. Working on this in my spare time.

Now that I have the linking working right this should be much easier to work on. I'll try to have a working patch this evening after more of this refactor is done.

**Comment by Garbee** [comment]
PR is up: https://github.com/devtools-html/devtools-core/pull/75

**Comment by Garbee** [comment]
That should do it with an updated build @darkwing. Thank you so much for the great report!

**Comment by Garbee** [comment]
Oh, FTR here as well in case anyone comes across this later...

We chose to simply *not render* the side panels when collapsed. This saves us from having to deal with any of this extra class stuff and adding in more CSS rules. It also avoids any potential pitfalls of keyboard navigation going into that area as well by accident if we don't account for that in the scripting. Plus side bonus, it gives us some precious pixel space back. Overall, nothing but wins.

**Comment by wldcordeiro** [comment]
I think we need a dep bump on the launchpad and then the issue will be fixed up. Also there will be a follow-up bit of work to add the bottom panel collapse in vertical mode (I can handle this @Garbee)

**Comment by Garbee** [comment]
> Also there will be a follow-up bit of work to add the bottom panel collapse in vertical mode (I can handle this @Garbee)

If you want, go for it. I actually just realized I can't even get vertical mode to trigger. Which is kinda weird... Looks like something was broken recently regarding that.

**Comment by jasonLaster** [comment]
@Garbee nope - just need to turn it on

https://github.com/devtools-html/debugger.html/blob/f9482d9ad5d3b1fb034261d72be2c03c8dea6d6c/docs/local-development.md#updating-the-config-locally
