### ISSUE TITLE
First time connecting links point to a non-existent id in CONTRIBUTING.md

### ISSUE THREAD

**Issue by joshunger** [devtools-html/debugger.html#1577]
First time connecting links point to a non-existent id in CONTRIBUTING.md.  What are they supposed to point to?
![image](https://cloud.githubusercontent.com/assets/2301847/21578286/b7018b68-cf37-11e6-864a-98501a8ecade.png)

**Comment by clarkbw** [comment]
That issue is being tracked here: https://github.com/devtools-html/devtools-core/issues/47
