### ISSUE TITLE
[SourceTabs] Add additional source tab shortcuts

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1588]
I've been thinking recently that it might be nice to add additional editor shortcuts for tabs:

* `Cmd+w` - close tab
* `Cmd-shift-{` | `Cmd-shift-}` - prev | next selected tab 

The obvious drawback is that these are used by the browser as well, but I think it's okay given the precedent for overriding `cmd-f` (search) and other shortcuts.

**Comment by clarkbw** [comment]
I worry the tab related ones would interfere with workflows.  The find (text) feels less like it could be part of a developer workflow on a web page so I'm not worried about that, or taking over printing `cmd+P`.

**Comment by jasonLaster** [comment]
Good point. Closing for now
