### ISSUE TITLE
Organize Components Directory

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1589]
We now have 20+ components, so it might be nice to organize them into logical directories:

**Some directories that come to mind are:**

* EditorPane
* shared
* SecondaryPanes

**Editor Pane**
* Editor
* EditorBreakpoint
* EditorSearchBar
* SecondaryPanes
...

**Shared**
* PaneToggleButton
* ObjectInspector
* Rep
* Dropdown
* Autocomplete
* CloseButton

**SecondaryPanes**
* EventListeners
* CommandBar
* Expressions

**Directories**

```
Accordion.css             ChromeScopes.js           Editor.js                 Expressions.css           Rep.js                    SourceSearch.js           WhyPaused.js
Accordion.js              CloseButton.css           EditorBreakpoint.js       Expressions.js            Scopes.css                SourceTabs.css            menu.css
App.css                   CloseButton.js            EditorConditionalPanel.js Frames.css                Scopes.js                 SourceTabs.js             reps.css
App.js                    CommandBar.css            EditorHitMarker.js        Frames.js                 SecondaryPanes.css        Sources.css               test-utils.js
Autocomplete.css          CommandBar.js             EditorSearchBar.css       ObjectInspector.css       SecondaryPanes.js         Sources.js                tests
Autocomplete.js           Dropdown.css              EditorSearchBar.js        ObjectInspector.js        SourceFooter.css          SourcesTree.js            utils
Breakpoints.css           Dropdown.js               EventListeners.css        PaneToggleButton.css      SourceFooter.js           SplitBox.css
Breakpoints.js            Editor.css                EventListeners.js         PaneToggleButton.js       SourceSearch.css          WhyPaused.css
```

**Comment by clarkbw** [comment]
I'm thinking of going forward with the `shared` directory for now.  I think that will reduce things further and we can see if we want to move more of the items after.

I don't have a good feeling for the Panes organization right now so I'd like to punt on that.

So here's what it will look like:

* Components
  * Editor
    * Breakpoint
    * ConditionPanel
    * HitMarker
    * SearchBar
  * shared
    * ManagedTree (from utils)
    * Svg (from utils)
    * Accordion
    * Autocomplete
    * CloseButton
    * PaneToggleButton
    * ObjectInspector
    * Rep

**Comment by clarkbw** [comment]
Not sure about having both the `shared` and `utils` directory.  Might move to all `shared`.

Also not sure what to do about the `reps.css` file, if I can move that to `shared/Reps.css` assuming I update the `App.js` usage.

**Comment by jasonLaster** [comment]
Sounds good. Shared is better than utils I think.

**Comment by jasonLaster** [comment]
I think this is on the right track. 

We probably want one more refactor for secondary panes and then we're good.
