### ISSUE TITLE
Watch Expressions: Final expression doesn't remove

### ISSUE THREAD

**Issue by jbhoosreddy** [devtools-html/debugger.html#1594]
STR: 
1. Add multiple expressions
2. Remove all expressions by clicking the "x" button

ER: All expressions should be removed

AR: Last expression does not remove

Should be an easy bug to solve.

**Comment by shlomif** [comment]
Hi! I'd like to try to tackle this bug.

**Comment by jasonLaster** [comment]
sorry @shlomif, I just did this as part of a larger fix.

**Comment by jasonLaster** [comment]
closing as we'll do this in the larger polish UI issue
