### ISSUE TITLE
Import client types

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1598]
@clarkbw and @ppold added beautiful types https://github.com/devtools-html/devtools-core/pull/49 here.

Lets import these types and replace types in `src/types`

I think this patch is what we're trying to do: [patch](https://gist.github.com/jasonLaster/10f5c31be71b9d50ffbe471aca06fa13)

**Comment by arthur801031** [comment]
Hi @jasonLaster

I'll take a stab at this :)

**Comment by jasonLaster** [comment]
Thanks @arthur801031 for grabbing one of the hard ones!
