### ISSUE TITLE
Context menu disabled attribute doesn't work

### ISSUE THREAD

**Issue by jbhoosreddy** [devtools-html/debugger.html#1607]
This might be easier to explain with a gif.
When you set menu item attribute `disabled: true` the expected result should be that the menu item is greyed out and clicking on it does not do any action.
However, setting attribute disabled to true does not make any change. This might be a bug we would want to handle separately.

![](http://g.recordit.co/wqLDjIS6kp.gif)

**Comment by jasonLaster** [comment]
Here's a patch for getting started

```patch
diff --git a/src/utils/menu.js b/src/utils/menu.js
index 8242913..6b1303b 100644
--- a/src/utils/menu.js
+++ b/src/utils/menu.js
@@ -49,6 +49,11 @@ if (!isFirefoxPanel()) {
 function onShown(menu, popup) {
   popup.childNodes.forEach((menuitem, index) => {
     const item = menu.items[index];
+
+    // we'll want to do something here
+    item.disabled; // or something better
+
+    // definitely don't want this onclick
     menuitem.onclick = () => {
       item.click();
       popup.hidePopup();
```
