### ISSUE TITLE
editing watch expressions does not work

### ISSUE THREAD

**Issue by jbhoosreddy** [devtools-html/debugger.html#1609]
When editing a watch expression, after editing and pressing enter, the expression text disappears and the input field stays there.

![](http://g.recordit.co/YTwHz47qc1.gif)

**Comment by jasonLaster** [comment]
Here's a good place to look:

```diff






diff --git a/src/components/Expressions.js b/src/components/Expressions.js
index 976e73b..739edd4 100644
--- a/src/components/Expressions.js
+++ b/src/components/Expressions.js
@@ -48,6 +48,8 @@ const Expressions = React.createClass({
     if (e.key !== "Enter") {
       return;
     }
+
+// => something in here
     const { addExpression } = this.props;
     const expression = {
       input: e.target.value,
```

**Comment by jasonLaster** [comment]
@andreicristianpetcu it's yours

**Comment by andreicristianpetcu** [comment]
I made a commit. It seems to work. I will test more in the following days to see if I missed something. The Expressions seem to have no unit tests. I will try to make a new test similar to the [other ones](https://github.com/devtools-html/debugger.html/tree/45a276cb6864cf826ddb2c94d933ecef3c9f3272/src/components/tests) but I will cover just this functionality.

**Comment by andreicristianpetcu** [comment]
Hmmm. It seems adding a test is a little more complicated. The current component tests [don't seem like they are run at the moment](https://github.com/devtools-html/debugger.html/blob/45a276cb6864cf826ddb2c94d933ecef3c9f3272/src/test/node-unit-tests.js#L61-L64) and they pass if I [run them but don't seem to check anything](https://github.com/devtools-html/debugger.html/blob/45a276cb6864cf826ddb2c94d933ecef3c9f3272/src/components/tests/Breakpoints.js#L18).

I will make a pull request with the current work. I will start making unit tests in the future on a future task and start working on an existing unit test and not add support for it on some file that are never run. I think it probably is a good reason why they are not run at the moment.

What do you think?
