### ISSUE TITLE
[Watch Expressions] UI Wonkiness

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1610]
I'm seeing some edge-cases with the UI around

* the input bar
* scroll bar with large reps
* close button floating over reps

It would be nice to get some thoughts on how we can / should clean this up...

![](http://g.recordit.co/gZKaqV3m4t.gif)

**Comment by jasonLaster** [comment]
@amitzur are you interested in doing some of this cleanup? I trust your eye for UI detail!

**Comment by amitzur** [comment]
Yes, thanks for bringing me back in. Can we discuss in tomorrow's office
hours? I didn't update in a while and suddenly got changes like the
packages folder disappearing and such. I cleaned everything up and got it
to work now

**Comment by jasonLaster** [comment]
Sounds good!

I did some clean up here already, which I think will help a lot, but it definitely needs a little bit more love
