### ISSUE TITLE
[WhyPaused] handle breakpointConditionThrown

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1611]
We don't currently handle the `breakpointConditionThrown` type and I believe it would be easiest to handle this in the [WhyPaused](https://github.com/devtools-html/debugger.html/blob/master/src/components/WhyPaused.js) component. 

Here's how you can reproduce this situation:
* Open [Optimized Away](https://devtools-html.github.io/debugger-examples/examples/optimized-away.html) for debugging
* _**in the debugger**_
* Set a _Conditional Breakpoint_ on **line 24**
* Enter the text `fsck` or any garbage for the condition
* _**in the page**_
* Click the button
* At this point the debugger should be paused, but not for the reason you think

Here's what the old debugger did:

![screen shot 2017-01-03 at 4 45 46 pm](https://cloud.githubusercontent.com/assets/2134/21628407/22ea40e2-d1d4-11e6-9b96-6b9e86bdf799.png)

And here's the relevant data log:

```json
{
  "type": "PAUSED",
  "pauseInfo": {
    "why": {
      "type": "breakpointConditionThrown",
      "message": "fsck is not defined",
      "actors": [
        "server1.conn1.child2/35"
      ]
    }
}
```

Here's the [bug filed in bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1325595)

I'd suggest we do something like this:

![screen shot 2017-01-03 at 5 00 26 pm](https://cloud.githubusercontent.com/assets/2134/21628691/30bfb06a-d1d6-11e6-9c25-2c5952ed2460.png)

And you could get started with something like this:

```diff
diff --git a/src/components/WhyPaused.js b/src/components/WhyPaused.js
index 5d2910e..e97eab5 100644
--- a/src/components/WhyPaused.js
+++ b/src/components/WhyPaused.js
@@ -20,10 +20,14 @@ const WhyPaused = React.createClass({
   render() {
     const { pauseInfo } = this.props;
     const reason = getPauseReason(pauseInfo);
+    const message = pauseInfo ? pauseInfo.getIn(["why"]).get("message") : null;
 
     // => here
     return reason ?
-      dom.div({ className: "pane why-paused" }, L10N.getStr(reason))
+      dom.div({ className: "pane why-paused" }, [
+        dom.div(null, L10N.getStr(reason)),
+        message ? dom.div(null, message) : null
+      ])
       : null;
   }
 });
diff --git a/src/strings.json b/src/strings.json
index 9c915be..4dc5b59 100644
--- a/src/strings.json
+++ b/src/strings.json
@@ -56,5 +56,6 @@
   "whyPaused.breakpoint": "Paused on breakpoint",
   "whyPaused.exception": "Paused on exception",
   "whyPaused.resumeLimit": "Paused while stepping",
-  "whyPaused.pauseOnDOMEvents": "Paused on event listener"
+  "whyPaused.pauseOnDOMEvents": "Paused on event listener",
+  "whyPaused.breakpointConditionThrown": "Error with Conditional Breakpoint"
 }
diff --git a/src/utils/pause.js b/src/utils/pause.js
index ded7e0b..6e975e1 100644
--- a/src/utils/pause.js
+++ b/src/utils/pause.js
@@ -28,7 +28,8 @@ const reasons = {
   "breakpoint": "whyPaused.breakpoint",
   "exception": "whyPaused.exception",
   "resumeLimit": "whyPaused.resumeLimit",
-  "pauseOnDOMEvents": "whyPaused.pauseOnDOMEvents"
+  "pauseOnDOMEvents": "whyPaused.pauseOnDOMEvents",
+  "breakpointConditionThrown": "whyPaused.breakpointConditionThrown",
 };
 
 function getPauseReason(pauseInfo: Pause): string | null {
```

**Comment by krishnagopinath** [comment]
I'd like to take a look at this, if its not yet taken up by anyone, @clarkbw @jasonLaster

**Comment by jasonLaster** [comment]
Go for it!

**Comment by clarkbw** [comment]
👍

**Comment by krishnagopinath** [comment]
@clarkbw, @jasonLaster, I'm not sure as to what is expected as a completion to this, as the patch seems to have done almost everything about it.. 

better UX, styling? or something else? 

One thing I could think of is, if `breakpointConditionThrown`  is triggered, the debugger could offer to show up an edit action on the conditional breakpoint, thereby, pointing (/spoon-feeding) the user to that position they need to take an action on.. 

Thoughts?

**Comment by jasonLaster** [comment]
@krishnagopinath often the patches are pretty close. No worries :)


> debugger could offer to show up an edit action

Or, just open the panel... this doesn't seem to necessary though :) Unfortunately, we're not great at triggering UI things from other components

**Comment by krishnagopinath** [comment]
This is how it looks now. Somehow this doesn't sit well with me. The centering seems weird after an extra line is added to the message.

Doing anything more to this could be feature-creepy, IMO.

![image](https://cloud.githubusercontent.com/assets/4935809/21814559/ac0cab64-d727-11e6-90ed-085b9ef64f79.png)

Thoughts?

**Comment by jasonLaster** [comment]
I agree @krishnagopinath. 

@clarkbw and I had a similar conversation about the line wrapping.

We'll be having a community call call at 3pm EST today https://github.com/devtools-html/debugger.html/#discussion. It would be great if you could stop by.

@Garbee is working on some command bar UI work that could help us here quite a bit.

**Comment by clarkbw** [comment]
Agreed.  I don't think the centering is going to work well with messages like this and we'll need to change the UI or go back to the original left aligned.

Perhaps the messages sit below the top level green area, they could use a regular white background.  Need to think more about it.

**Comment by krishnagopinath** [comment]
We could discuss this on the comm call tomorrow (I'm assuming there's one, the link says so), if time permits and is deemed important. @clarkbw @jasonLaster
