### ISSUE TITLE
Prettify Source bar takes up precious vertical space

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#1614]
There's a whole bar just for the Prettify Source icon taking up lot's of vertical space. Since it just has one button I would propose to remove this bar completely (which would allow to read about 3 LOC more). The Prettify Source button which is a file/tab concerned action could be moved to its "concern": The tab.

![2017-01-04 10_54_58-](https://cloud.githubusercontent.com/assets/3307404/21638743/ff05fb0a-d26c-11e6-9f8d-b9653b2c0b87.png)

**Comment by jnachtigall** [comment]
Ah, after clicking the "Prettify Source" the bar vanishes. I wonder why it's there in the first place since my JS is "pretty" already. 

Anyway: A whole bar for just one action seems wasteful. Also the button is really hard to discover being at right bottom which is almost the farthest away for the user's eye and mouse.

**Comment by clarkbw** [comment]
We've moved the button from the right to the left, that hasn't landed in Firefox yet.

![screen shot 2017-01-04 at 08 47 58](https://cloud.githubusercontent.com/assets/2134/21650650/825a70c0-d25a-11e6-9d62-dfed3c1f49b6.png)

**Comment by clarkbw** [comment]
I'm closing this for now since we've tried a bunch of variations before that didn't work out.  If we have a new location we feel is better we can try that and we should also dig up all the old PRs and issues to review.  Feel free to keep using this issue for discussion even though its closed.

**Comment by jnachtigall** [comment]
@clarkbw Since Prettify is a file/tab concerned action I'd move it to the tab header. Just left of the close button ("close" actually is also a single file/tab concerned action). 

Plus: Ideally, I think that it should also be a toggle instead of a one-off button: This would show the status of the file ("Prettify" being "on" meaning that the file is different than the original) and one could also switch between Prettified and Original. This would seem intuitive to me.

**Comment by jasonLaster** [comment]
@jnachtigall i'm concerned about tab header as it's a fairly in frequent action.

Hmm, perhaps we add it as a context menu item. We could offer it in both the source tree item and source tab.

one argument for the footer is that we'll likely use that space for more things going forward.
* black boxing
* perhaps cursor location
* really cool things yet discovered...
