### ISSUE TITLE
persist scopes state while stepping

### ISSUE THREAD

**Issue by tromey** [devtools-html/debugger.html#1617]
I set a breakpoint and the debugger stopped there.  I opened a scope in the Scopes pane to see the local variables.  Then I did a step over.  The debugger collapsed the scope.  I think it would be nicer if the scope stayed open.  As it is now, if I want to see what is happening, I have to switch back and forth between the step-over button and the scope button; and if the information I want is buried deeper (say, a property a few levels deep in some object), this is a pain.

**Comment by jasonLaster** [comment]
This is similar for maintaining expanded state for watch expression objects

CC @bomsy

**Comment by jasonLaster** [comment]
@bomsy any updates?

**Comment by bomsy** [comment]
Hey ... yeah been thinking about what the best way to store the state of a particular path. Coming up with something

**Comment by jasonLaster** [comment]
sounds good - definitely an interesting problem!

**Comment by jasonLaster** [comment]
@bomsy we *might* get this for free. try investigating a bit...

**Comment by bomsy** [comment]
will do!

**Comment by jasonLaster** [comment]
Hmm I looked into this and found some encouraging results:

#### Situations:
* selecting frames - works
* stepping - doesn't work

#### selecting frames
![](http://g.recordit.co/whuYKpJUI0.gif)

#### stepping
![](http://g.recordit.co/lwU6aBqJyv.gif)

**Comment by jasonLaster** [comment]
@bomsy dropping the in progress label because it's gone stale. feel free to pickup again though

**Comment by bomsy** [comment]
picking this back up! some nice ideas to try out!
