### ISSUE TITLE
pause on uncaught exception not initially showing the exception

### ISSUE THREAD

**Issue by tromey** [devtools-html/debugger.html#1618]
I have a simple program that throws an exception:

```js
function trw() {
   throw new Error( "hi bob" );
}
function calltrw2() {
  trw();
}
```

I enable "pause on uncaught exception" in the debugger.
Then I enter `calltrw2()` in the console.

This stops at the `throw` -- good!

Now I go to the Scopes pane and open the "trw" scope.
I don't see anything about the exception here.  First I have to "step over", then re-open the "trw" scope, in order to see the exception.  This seems strange, it would be better if the exception object were available immediately.

**Comment by clarkbw** [comment]
I think we could handle this pretty similar to #1611 

When paused on an exception you get some information back that could be displayed.  Either highlighted in the scope (as it used to be) but I also think the WhyPaused component could be displaying this information as well.

Here's some of the data coming back from this page: https://devtools-html.github.io/debugger-examples/examples/exceptions.html

```json
{
  "type": "PAUSED",
  "pauseInfo": {
    "why": {
      "type": "exception",
      "exception": "reachable"
    },
    "frame": {
      "id": "server1.conn10.child2/72",
      "displayName": "caughtException",
      "location": {
        "sourceId": "server1.conn10.child2/30",
        "line": 24,
        "column": 10
      },
      "this": {
        "type": "object",
        "actor": "server1.conn10.child2/pausedobj80",
        "class": "Window",
        "extensible": true,
        "frozen": false,
        "sealed": false,
        "ownPropertyLength": 805,
        "preview": {
          "kind": "ObjectWithURL",
          "url": "https://devtools-html.github.io/debugger-examples/examples/exceptions.html"
        }
      }
```

```json
{
  "type": "PAUSED",
  "pauseInfo": {
    "why": {
      "type": "exception",
      "exception": {
        "type": "object",
        "actor": "server1.conn10.child2/pausedobj93",
        "class": "Error",
        "extensible": true,
        "frozen": false,
        "sealed": false,
        "ownPropertyLength": 4,
        "preview": {
          "kind": "Error",
          "name": "Error",
          "message": "error",
          "stack": "caughtError@https://devtools-html.github.io/debugger-examples/examples/exceptions.html:16:17\n@https://devtools-html.github.io/debugger-examples/examples/exceptions.html:31:7\n",
          "fileName": "https://devtools-html.github.io/debugger-examples/examples/exceptions.html",
          "lineNumber": 16,
          "columnNumber": 17
        }
      }
    },
    "frame": {
      "id": "server1.conn10.child2/87",
      "displayName": "caughtError",
      "location": {
        "sourceId": "server1.conn10.child2/30",
        "line": 16,
        "column": 1...
```

**Comment by jasonLaster** [comment]
@clarkbw I'm not sure what you're suggesting :)

**Comment by clarkbw** [comment]
Sorry if that wasn't clear.  

Given an exception I think you could create a message below the reason by passing the preview directly to the ObjectInspector, so something like this `ObjectInspector(pauseInfo.get(["why"]).get("exception").get("preview"))`

Given something like this seen over the protocol:

```json
{
  "type": "PAUSED",
  "pauseInfo": {
    "why": {
      "type": "exception",
      "exception": {
        "type": "object",
        "actor": "server1.conn10.child2/pausedobj93",
        "class": "Error",
        "extensible": true,
        "frozen": false,
        "sealed": false,
        "ownPropertyLength": 4,
        "preview": {
          "kind": "Error",
          "name": "Error",
          "message": "error",
          "stack": "caughtError@https://devtools-html.github.io/debugger-examples/examples/exceptions.html:16:17\n@https://devtools-html.github.io/debugger-examples/examples/exceptions.html:31:7\n",
          "fileName": "https://devtools-html.github.io/debugger-examples/examples/exceptions.html",
          "lineNumber": 16,
          "columnNumber": 17
        }
      }
    }
```

**Comment by jasonLaster** [comment]
Here's a good patch

```patch

diff --git a/src/utils/pause.js b/src/utils/pause.js
index dfc1502..87ddc0a 100644
--- a/src/utils/pause.js
+++ b/src/utils/pause.js
@@ -48,6 +48,18 @@ function getPauseReason(pauseInfo: Pause): string | null {
   }

   let reasonType = pauseInfo.getIn(["why"]).get("type");
+
+  if (reason == "exception") {
+    // do a special message here:
+    const preview = pauseInfo.getIn(["why", "exception", "preview"]);
+    const betterMessage = ObjectInspector(preview);
+
+    return dom.div({},
+      reasons[reasonType],
+      preview
+    );
+  }
+
```

**Comment by arthur801031** [comment]
I'll take a stab at this 🙂

**Comment by arthur801031** [comment]
Hi @clarkbw and @jasonLaster !

I've got two questions:
1. To address the problem of not seeing the exception in `Scopes`, I tried `ObjectInspector `, but `ObjectInspector ` seems to be local to [Expressions.js](https://github.com/devtools-html/debugger.html/blob/master/src/components/SecondaryPanes/Expressions.js) and [Scopes.js ](https://github.com/devtools-html/debugger.html/blob/master/src/components/SecondaryPanes/Scopes.js) because they both create their own `ObjectInspector`. I think we want to add `preview` to `this.state.scopes` in [Scopes.js ](https://github.com/devtools-html/debugger.html/blob/master/src/components/SecondaryPanes/Scopes.js), and I'm not sure how to use `ObjectInspector` in `src/utils/pause.js` to do this.

2. I'm not sure what to display in `WhyPaused` when we have an uncaught exception. Right now we display `Paused on exception`. I think we could do `Paused on uncaught exception` for this type of exception?

Thank you very much! 😄

**Comment by jasonLaster** [comment]
Thanks for investigating @arthur801031.

I think it makes sense to close this issue for the time being:

1) I prefer pausing before an uncaught exception as it gives you an opportunity to explore the local scope

2) while we can do more to highlight the exception that will be thrown, I don't think we'd get a lot of value from a more descriptive message and there are a lot of edge cases.

I'm in favor of re-evaluatating pause reasons in a couple months after we've reached parity.
