### ISSUE TITLE
pause on uncaught exception -vs- continue

### ISSUE THREAD

**Issue by tromey** [devtools-html/debugger.html#1619]
I have a simple program that throws an exception:

```js
function trw() {
   throw new Error( "hi bob" );
}
function calltrw2() {
  trw();
}
```

I enable "pause on uncaught exception" in the debugger.
Then I enter `calltrw2()` in the console.

This stops at the `throw` -- good!

Now I click the "continue" button.  This causes the debugger to stop in `calltrw2`.

I did not expect this.  Instead, I think it would be better for continuing to carry on -- I clicked it because I am no longer interested in this exception.  I think the rule should be that it should only pause a second time for the same exception if it is explicitly re-thrown, say by code like:

```js
try { mumble; } catch(e) { ... ; throw e; }
```

In particular I think it would be best not to stop again if the exception is merely implicitly re-thrown by a `finally`.

**Comment by jasonLaster** [comment]
I'm moving this to [enhancements] with a server label so that we can prioritize this when we plan for Q2.

[enhancements]: https://github.com/devtools-html/debugger.html/projects/5

**Comment by janodvarko** [comment]
I filled variation of this report:
https://bugzilla.mozilla.org/show_bug.cgi?id=1603440

Honza
