### ISSUE TITLE
pause on exceptions icon is too subtle

### ISSUE THREAD

**Issue by tromey** [devtools-html/debugger.html#1620]
I find the differences between the 3 states of the "pause on exceptions" button a bit too subtle.  I can't readily distinguish them and I end up having to wait for the tooltip in order to see the current setting.

**Comment by clarkbw** [comment]
I really don't like this button either, I never know what state its in or what state is next. 👎

**Comment by jasonLaster** [comment]
You're right :/

We'll be looking into an improvement to the UI in #1665 and other issues.
