### ISSUE TITLE
[DarkMode] fix text selection

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1622]
The dark mode text selection makes it hard to read the code.

Here are some notes on how to work with our [themes](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#themes)

#### Here's where the text selection background is likely defined

I feel like we should find another color that is much closer to the background so it doesn't make the source text look bad.

```patch
diff --git a/src/lib/codemirror-mozilla.css b/src/lib/codemirror-mozilla.css
index 303ff40..87e917b 100644
--- a/src/lib/codemirror-mozilla.css
+++ b/src/lib/codemirror-mozilla.css
@@ -18,6 +18,8 @@
   /* --breakpoint-conditional-background: url("chrome://devtools/skin/images/breakpoint.svg#dark-conditional"); */
 }

+/* HERE */
+
 .CodeMirror .errors {
   width: 16px;
```

#### What it looks like now

![](http://g.recordit.co/arB47M21dp.gif)

**Comment by andreicristianpetcu** [comment]
@jasonLaster I use the dark theme. Can I pick this one up?

**Comment by jasonLaster** [comment]
Go for it

**Comment by irfanhudda** [comment]
@jasonLaster Correct me if I'm wrong, but I believe that this require changes to [https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-launchpad/src/lib/themes/dark-theme.css#L210](https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-launchpad/src/lib/themes/dark-theme.css#L210) file.

**Comment by jasonLaster** [comment]
@irfanhudda thanks, that looks like the spot. It's easy to work on devtools-modules and see the change in the debugger. https://github.com/devtools-html/devtools-core#installing-locally

^ @andreicristianpetcu

**Comment by andreicristianpetcu** [comment]
@jasonLaster [ping](https://github.com/devtools-html/devtools-core/pull/63) :)
