### ISSUE TITLE
Highlight ocurences of the highlighted word (a-la Sublime)

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#1633]
This is something I really like in Sublime, it gives you a fast insight of where your variable, for example, is used.

![screenshot at janv 05 17-17-26](https://cloud.githubusercontent.com/assets/578107/21688122/f20c850e-d36b-11e6-944d-5433ed0e5d16.png)

This would be triggered when a word is double-clicked in the editor, at first.
Maybe later we could have a shortcut to highlight the current text selection (not only on double-click)

**Comment by jbhoosreddy** [comment]
@jasonLaster if this is actionable I'd like to take a stab at this.

**Comment by jasonLaster** [comment]
Yea - i think so... follow @bomsy's work with the source-search utils. should be a fun ride :) similar to your selections api, but with Editor dom events on mouse up or something :P
