### ISSUE TITLE
[Editor Search Bar] Case Insensitive Search

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#1636]
It would be nice to have a toggleable search button for case insensitive search much like Sublime Text and other editors.

Screenshot for inspiration
![screenshot_20170105_132202](https://cloud.githubusercontent.com/assets/580982/21696150/f61f8c80-d349-11e6-83e3-760bbedf72b3.png)

**Comment by jasonLaster** [comment]
@wldcordeiro is on this

**Comment by jasonLaster** [comment]
Here's a screenshot:

![](https://cloud.githubusercontent.com/assets/254562/21696191/e4a17e30-d35a-11e6-8675-4bb7ff191ca7.png)
