### ISSUE TITLE
Please keep the old search as you type functionalitty of the old debugger

### ISSUE THREAD

**Issue by andreicristianpetcu** [devtools-html/debugger.html#1645]
Hi, 

I would like to suggest an enhancement for the new debugger. The old debugger in Firefox shows you a preview of the results as you type. Sometimes I don't know exactly what I am looking for and it really helps to see the results as I type. Also it shows only the lines that match my pattern, showing me more relevant info and less irrelevant non-matching lines.

Since a GIF is worth 10000 words here is a small demo:

![firefox_debugger](https://cloud.githubusercontent.com/assets/922368/21740598/2386ed22-d4b6-11e6-86da-c282ab6b5d48.gif)

This feature is not only built into the old debugger but other IDEs and text editors have it. For example IntelliJ community edition:

![intellij](https://cloud.githubusercontent.com/assets/922368/21740600/3fc42b1c-d4b6-11e6-820c-00be194bb8b1.gif)

Spacemacs

![spacemacs](https://cloud.githubusercontent.com/assets/922368/21740602/4897157e-d4b6-11e6-99bb-d658adb4ff60.gif)

And Eclipse STS https://www.youtube.com/watch?v=1lH7Zla5ubQ

And I also have it in my Vim custom configuration.

Please keep this awesome functionality from the old debugger. I guess it's not trivial to implement but it is really cool and Chrome does not have it :D

**Comment by jasonLaster** [comment]
Thanks for the great writeup. We'll work on it here:

https://github.com/devtools-html/debugger.html/issues/1108
