### ISSUE TITLE
The [SecondaryPanes] component doesn't fully collapse when collapse pane is clicked

### ISSUE THREAD

**Issue by krishnagopinath** [devtools-html/debugger.html#1647]
Here's a gif to explain this. Notice that there are two scrollbars when the right pane is collapsed, which makes it look confusing and weird.. 

![left-bar-bug](https://cloud.githubusercontent.com/assets/4935809/21743451/844bb402-d4d0-11e6-8580-ee63ccf28826.gif)

**Comment by jasonLaster** [comment]
Thanks @krishnagopinath we're handling that here https://github.com/devtools-html/debugger.html/issues/1564
