### ISSUE TITLE
If the old debugger front-end is enabled (in about:config), clicking on source-map links to code doesn't bring you to the debugger

### ISSUE THREAD

**Issue by sole** [devtools-html/debugger.html#1651]
Scenario:

- running Nightly, I had manually enabled the old debugger front-end using about:config
- access http://bgrins.github.io/devtools-demos/debugger/sourcemaps/
- click anywhere to log 'hi'
- The source that console.logs 'hi' is generated with a sourcemap
- if I click on the bundle.js:66:4 line, instead of bringing me to the debugger on that line it brings me to the full source (via view-source) and that line

**Comment by jasonLaster** [comment]
thanks for filing this. I'd be curious to see what @clarkbw says, but my instinct is to close this as the old debugger is deprecated and we hope to be at parity by the end of Q1.

**Comment by belen-albeza** [comment]
Confirming it also happens with DevEdition. 

What is also happening to me is that source maps are not listed along the original JS files, but at a different path. 

It might be related to this other bug in bugzilla: https://bugzilla.mozilla.org/buglist.cgi?quicksearch=TypeScript&list_id=13384940

**Comment by belen-albeza** [comment]
This is happening to me with the default config of Firefox Nightly and Dev Edition –unless the "old front-end" is enabled by default.

I'm attaching an example. It might also be related to this bug in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1294036

[sourcemaps-bug.zip](https://github.com/devtools-html/debugger.html/files/694288/sourcemaps-bug.zip)

**Comment by clarkbw** [comment]
Yeah, we tried to avoid regressing the old debugger but we won't be prioritizing fixes for it so we'll have to live with this for a little while.
