### ISSUE TITLE
Adjustable font size in editor pane

### ISSUE THREAD

**Issue by irfanhudda** [devtools-html/debugger.html#1653]
The current font size of editor appears too small on my screen. 
![screenshot-1](https://cloud.githubusercontent.com/assets/1755089/21776677/a2873a3e-d6c1-11e6-93e7-2508fe448f44.png)

It would be best if we had adjustable font size for editor pane. We could have some options in context menu of editor.

Any suggestions?

**Comment by jasonLaster** [comment]
Thanks for filing. 

There are a couple of challenges with lining up the breakpoint gutter and debug line, but it would be nice to have a normal and maybe comfortable size. 15px or so...

**Comment by clarkbw** [comment]
Lets first look into why the font sizes are so different from the rest of the editor.  The other text is a much more readable size.

**Comment by irfanhudda** [comment]
@clarkbw I'm on Debian 8, Chromium(without extensions). Here editor font defaults to `monospace` which could probably be the cause for this.
