### ISSUE TITLE
[PrettyPrint] option not available for some .min files

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1661]
[bug 1320342](https://bugzilla.mozilla.org/show_bug.cgi?id=1320342) provides these steps to reproduce.

* Go to https://www.brain.fm
* Open `jquery.min.js`
* 🤕 No option to pretty print the file is available

**Comment by clarkbw** [comment]
I just tracked this down to here: https://github.com/devtools-html/debugger.html/blob/master/src/utils/editor.js#L8

In the example above the `jquery.min.js` file includes a source map and therefore shows a `jquery.js` (pretty version) in the same directory.  The `shouldShowPrettyPrint` uses the presence of a source map to indicate that pretty print isn't available. 

@jasonLaster it looks like this came from #959 and I'm not sure what we do here.  Direct people to the source mapped version?

I found an interesting case as well where the source map file wasn't found (404) and so there's no way to view a pretty version of that minified file.  Perhaps there's a way of knowing that we successfully found the source mapped version?

**Comment by clarkbw** [comment]
If we get a 404 on a source map file we should clear the `sourceMapURL` field which should allow for pretty printing again.

**Comment by clarkbw** [comment]
Also I wonder if we should use the bottom bar to indicate a "Source Mapped Version" so people can see that there is a source map and click that to jump to it.  I know we have this in a context menu for jumping to lines but I think it would be good to surface the general jump option.

**Comment by clarkbw** [comment]
Did some more digging.  

I believe if you wanted to tackle this you would need to start here:
https://github.com/clarkbw/debugger.html/blob/master/src/utils/source-map-worker.js#L119-L121

```js
  // Fire off the request, set it in the cache, and return it.
  // Suppress any errors and just return null (ignores bogus
  // sourcemaps).
  const req = _resolveAndFetch(generatedSource); // drop the catch .catch(() => null);
  sourceMapRequests.set(generatedSource.id, req);
  return req;
```

Now the fetch error will be passed back to the caller.

Then handle the passed error somewhere like here:
https://github.com/clarkbw/debugger.html/blob/master/src/actions/sources.js#L75-L79
```js
    const urls = await getOriginalURLs(generatedSource);
    if (!urls) {
      // If this source doesn't have a sourcemap dispatch event to remove the sourceMapURL from the source
      dispatch({
        type: constants.SOURCE_MAP_MISSING,
        id: generatedSource.id
      });
      return;
    }
```

**Comment by bomsy** [comment]
Just for clarification, from the comments above and testing i see 2 scenarios
1. When the source map file is found. How do we redirect the user to it? 
Do we want to have a link to its source map (pretty printed) file ?

2. When we get a 404 on a source map file. we fix with the solution above. correct!

**Comment by jasonLaster** [comment]
As a quick follow up. @bomsy had #1937 open and it just needed a unit test in `actions/tests/breakpoints`.

**Comment by jasonLaster** [comment]
@bomsy's PR is a great place to start. The first part will be re-applying the patch. The second part will be writing a new unit test w/ pretty printing.
