### ISSUE TITLE
Highlight line longer after jumping to file from Console

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#1663]
STR:
1. Click on a line in the console
2. Jumps to Debugger

AR:
3. The line is highlighted for maybe one second, then immediately vanishes. Usually in such a situation you do not know 'where' you are, so you need to orientate first and find/search where to look at - until the highlight is gone. I had this "Where is this line?" situatuion a few times now ;)

![capture_2](https://cloud.githubusercontent.com/assets/3307404/21810185/ff580476-d74a-11e6-880a-1181a022fcab.gif)

ER:
Please make the hightlight last for 3-5 seconds.

Tested with Debugger builtin Nightly 53.0a1 (2017-01-10) (64-bit) Windows 10.

**Comment by jasonLaster** [comment]
hmm, that makes sense. so basically a long highlight which we can do with a `selectLocation param`

**Comment by arthur801031** [comment]
I'll take a stab at this :)

**Comment by arthur801031** [comment]
Feel free to claim this. I couldn't get the mochitests setup to work :(

**Comment by clarkbw** [comment]
> Feel free to claim this. I couldn't get the mochitests setup to work :(

hmm, we need to fix that.  Sorry @arthur801031 I hope you didn't waste too much time. 😠

**Comment by arthur801031** [comment]
I've resolved the issue with mochitests setup. I'll try to take another crack at this 😂

**Comment by jasonLaster** [comment]
Very cool

**Comment by clarkbw** [comment]
fixed in #1904
