### ISSUE TITLE
[Windows] F10 also opens Firefox Menu, F11 does Full-Window

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#1664]
#1367 fixed part of it. But on Windows Firefox opens does trigger the Debugger actions but also the native Firefox actions:

* F10 should only progress the debugger, not also open the Firefox menu
* F11 should only step-in, not also go into full-page mode

53.0a1 (2017-01-10) (64-bit) Windows 10.

**Comment by jasonLaster** [comment]
ping @jbhoosreddy

**Comment by jbhoosreddy** [comment]
pong @jasonLaster. Seriously though, I think my windows local repo has
issues. Setting things up again, should be done shortly.

**Comment by clarkbw** [comment]
I'm not able to reproduce this on my windows machine.  I have Firefox 53.0a2 and I'm stepping over and in with the function keys without an issue.

Maybe there's some kind of focus issue here?

**Comment by jnachtigall** [comment]
@clarkbw I am also not able to reproduce with current FDE anymore. So I'm closing, please reopen if this was inappropriate :)
