### ISSUE TITLE
[Chrome] Breakpoint Exception Toggle's fail for Chrome tabs

### ISSUE THREAD

**Issue by Garbee** [devtools-html/debugger.html#1670]
When switching through the various exception break modes (Uncaught-only, all-exceptions, or none) Chrome tabs will fail on any given trigger. FF tabs still work, so this has something to do with the RDP for Chrome.

<details>
<summary>Error from console</summary>

```
{
  "code": -32602,
  "message": "Invalid parameters",
  "data": "state: string value expected"
}
```

Emanating from: `executeSoon @ promise.js:50`

</details>

<details>
<summary>Steps to reproduce</summary>

1. Open debugger and target a Chrome tab.
2. Toggle the exception pausing in the CommandBar.
3. Check console for errors

</details>

**Comment by clarkbw** [comment]
Looks like this wasn't wired up correctly.  I did some tracing down to the chrome commands.  I'm not sure why it errors out yet, but we only pass two options when 3 are available. `"none", "uncaught", "all"`
https://github.com/devtools-html/devtools-core/blob/9ba99c5b6f60209ff20cf64cec415f14ccb6178a/packages/devtools-client-adapters/src/chrome/commands.js#L29

Likely needs a fresh look.

**Comment by bomsy** [comment]
looking into this..

**Comment by bomsy** [comment]
I think this is an issue for devtools-core

**Comment by bomsy** [comment]
https://github.com/devtools-html/devtools-core/issues/201

**Comment by clarkbw** [comment]
We can probably close this then, right?

**Comment by jasonLaster** [comment]
sure
