### ISSUE TITLE
[Editor] Selection iteration misses even items

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1672]
So I don't know why this is, but when you iterate over the selections, it misses one of them!

Steps to reproduce:
1. go to todo-view.js in backbone
2. select this.model
3. press cmd-g 

expect the second item to be selected
actual: the third item is selected

![](http://g.recordit.co/DaRSx8MuPa.gif)

CC @bomsy @jbhoosreddy

**Comment by jbhoosreddy** [comment]
Didn't see it before but I can look into this.

**Comment by wldcordeiro** [comment]
I thought I was insane and broke it when implementing the search modifiers! This is an odd bug. 😆

**Comment by jbhoosreddy** [comment]
@wldcordeiro a little early to tell but, it could well be that I broke it.
That being said, I do like working on weird bugs like these, but it's only worth it if you're able to figure it out. 😂

**Comment by jbhoosreddy** [comment]
@jasonLaster I tried to replicate the bug following the STR provided, including the latest master branch. It doesn't seem to happen on my end. Could you reconfirm? If so, maybe we could pair for a quick session to track it down.

**Comment by jasonLaster** [comment]
Hmm, I still see it. But I think i've got a good lead, it misses every other one so there's probably two increments in there. like it does matches (0, 2, 4)

**Comment by jbhoosreddy** [comment]
okay. as weird as it sounds, I am not seeing this bug on my end (curious as to why it would be like that). I think I'll drop it and work on something else. It might be a little counter intuitive to spend time to break it in the first place.. 😆. someone else can take over more easily, I think.

**Comment by jasonLaster** [comment]
Cool. I'll look tomorrow

**Comment by liorpr** [comment]
It happens because the traverseResults method is called twice(and registered twice). Once in the Editor component, and once in the SearchBar component. I'm on it!

**Comment by wldcordeiro** [comment]
I can incorporate the fixed into my search modifier PR as I had already moved most of the state up into the Editor there.

**Comment by jasonLaster** [comment]
Oh nice. Did you find the problem?

**Comment by wldcordeiro** [comment]
@jasonLaster not really, but with @liorpr's suggestion having mostly been done in my PR I think it'd just make it easier with merge conflicts to have it incorporated.

**Comment by jasonLaster** [comment]
Thanks everyone. Wellington let's get your fix in soon

**Comment by jasonLaster** [comment]
@wldcordeiro fixed this bug in https://github.com/devtools-html/debugger.html/pull/1644

The issue is that both the editor and the search bar listen for cmd-g and try to do find the next element.

We want to fix this by moving the search state and handling to the editor.

A good next step would be to take that refactoring logic out of #1644 and make a new PR with just that.

**Comment by jasonLaster** [comment]
Thanks @wldcordeiro for fixing this annoying sucker

![](http://g.recordit.co/QuyDsrGYhz.gif)
