### ISSUE TITLE
Publish a new version to MC

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1693]
Here are the rough steps:

1. publish a new version to NPM. publishing, copies the files to a dist directory for npm.
2. check for changes in m-c
3. bump NPM version in MC and copy files to the correct locations.

Context:
* the *devtools* directory in MC will have a package.json, with the current versions

**Comment by nt1m** [comment]
It would be cool if this could be done more often, so Nightly users are able to get the changes and report bugs more quickly. This would make debugger-html better in terms of stability since a lot of our Nightly users are great bug filers :)
