### ISSUE TITLE
[Breakpoints] breakpoints should have a blue left border

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1694]
We currently show a left border for active and conditional breakpoints. It might be nice to show a left border for regular and disabled breakpoints.

* breakpoints would have a left blue border
* disabled breakpoints would have a light blue border

@Garbee mentioned this in chat

**Comment by Garbee** [comment]
Ok, if this is something we want to do then I'll handle it with the breakpoint UX update I'm already working on.

**Comment by Garbee** [comment]
Also with this, disabled *conditional* breakpoints should be a lighter yellow.

I'll try to find the existing variables for these and if we don't have "breakpoint-specific" ones then I'll create those for easy re-use anywhere we may need them in the future for breakpoint-related actions.

**Comment by clarkbw** [comment]
Just to note that we also have #1540 about looking into a better color scheme for the conditional breakpoint.

**Comment by jasonLaster** [comment]
This is a really interesting point. I've thought about it for the past week.

Ultimately, I don't think we should move forward with it for a couple reasons.

1. When I played with it, the border is a very strong visual that adds clutter to the UI.
2. Helen always said that we should use color only when it tells a clear story. In this case, I am not sure that it communicates that it is a *regular* breakpoint strongly.
3. We would like to re-think how we show breakpoints after we reach parity. This would give us a chance to re-evaluate the left border for conditional bps and showing the paused on bp.

Thanks for bringing this up again, these discussions help us think through every aspect of the UI.

closing, but feel free to comment of course.

**Comment by Garbee** [comment]
> Helen always said that we should use color only when it tells a clear story.

The best reason not to.
