### ISSUE TITLE
Syntax Highlight all the things

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1701]
The debugger already supports transpiled code with source maps, but we don't syntax highlight appropriately, which makes the files appear broken.

We should strive to support the common use cases:

- [x] typescript
- [x] elm
- [x] coffee script
- [x] jsx
- [x] flow
- [ ] ...

##### Flow

* @thejameskyle mentioned that we could probably use typescripts codemirror mode for flow. We could also identify if it is flow by checking for the `// @flow` pragma at the top of the source text

**Comment by clarkbw** [comment]
#1642 fixed this
