### ISSUE TITLE
UI Polish

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1704]
Three small things 

- [x] we're missing the bottom border for the command bar. not sure when it went away
- [x] when the sidebars (left and right) are closed you see a horizontal scrollbar
- [x] this might be a bit contentious, but I don't think the "Sources" header buys us anything. It seems a bit like wasted space :) 

Command Bar:

![screen shot 2017-01-13 at 11 32 14 pm](https://cloud.githubusercontent.com/assets/254562/21952384/8dc221d4-d9e8-11e6-9857-f879b1aa3244.png)

CC @clarkbw what do you think about "Sources" I could easily be persuaded to keep it :)

**Comment by arthur801031** [comment]
@jasonLaster  I'll take a stab at this :) 

Is `App.js` tab's bottom border the bottom border for the command bar?

**Comment by clarkbw** [comment]
> what do you think about "Sources" I could easily be persuaded to keep it

I'd argue to keep it.  It maintains a nice, consistent bar across the top.  And allows us to always show the key shortcut for search.  I know it gains us some vertical space but I think I would need to be convinced that we are lacking vertical space in that tree view.

I could be persuaded that we could do something better than just say "Sources" as that seems fairly useless.  I imagined an "iframe selector" would go there eventually.

**Comment by jasonLaster** [comment]
Oh yea. I like the Rob bar with the label. I'm just thinking that we don't
need the word sources. The label and context helps.

**Comment by jasonLaster** [comment]
@clarkbw if you think we should keep the Sources header, I can bring it back

**Comment by clarkbw** [comment]
> @clarkbw if you think we should keep the Sources header, I can bring it back

Nope. 😄
