### ISSUE TITLE
[Dark Theme] Sources and editor have scrollbars sometimes on Gnome Shell

### ISSUE THREAD

**Issue by andreicristianpetcu** [devtools-html/debugger.html#1726]
Sometimes the sources section and the editor section have white scrollbars. Please see the screenshot.

![scrollbars](https://cloud.githubusercontent.com/assets/922368/21997844/5deadc2e-dc29-11e6-9c32-2365f84e1c19.png)

I reporduced it on Fedora 25 with Gnome Shell 3.22.2. I don't know if it happens on other operating systems or on other desktop environments.

**Comment by wldcordeiro** [comment]
@andreicristianpetcu If you are on Firefox the scrollbars aren't styleable.

**Comment by andreicristianpetcu** [comment]
Is there an upstream bug for this? If not then I will report one.

**Comment by andreicristianpetcu** [comment]
Yes..... I am in Firefox.

**Comment by andreicristianpetcu** [comment]
Found the bug :( https://bugzilla.mozilla.org/show_bug.cgi?id=77790

**Comment by jasonLaster** [comment]
yeah - so firefox does not support changing the scrollbar unless it's in the firefox devtools panel :/

Chrome does support it though

**Comment by jasonLaster** [comment]
eagle eyes :)

**Comment by andreicristianpetcu** [comment]
Apparently there is a way to customize Firefox scrollbars. https://gromo.github.io/jquery.scrollbar/demo/basic.html

**Comment by jasonLaster** [comment]
Hmm, i din't think that did anything for me in firefox :/
