### ISSUE TITLE
Conditional debugger statement isn't indented

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1728]
When I set a conditional debugger statement in some minified code exactly where the place of the code is the box for the conditional statement starts at column 0 rather than where the statement has been place.

This means when I open the box and type in my condition I can't read what I am typing without scrolling back horizontally.

Tested in nightly 53.0a1 and 52.0a2.

CC @jonathanKingston

**Comment by jasonLaster** [comment]
Thanks @jonathanKingston

I can see how this could be frustrating. 

At the moment we've setup the conditional pane to be one giant input, which makes this somewhat hard to fix.

Perhaps, one concrete fix would be to make the input the width of the editor so that it is always in view. 

Would that work?

**Comment by jonathanKingston** [comment]
So the input would line wrap? That seems perfectly fine to me however line
numbering might be an issue instead perhaps?

**Comment by jasonLaster** [comment]
hmm, i'm not thinking of wrapping

jus that the conditional pane input is fixed to the editor so the first character is visible regardless of horizontal scroll. Tough to describe :)

**Comment by jasonLaster** [comment]
Hmm, i did a bit of investigating and I think this might be difficult to do at this time.

Here's some of my thinking:

My goal would be to position the input box of the conditional breakpoint pane on top of the editor so it is always the width of the editor and positioned next to the gutter. basically position it absolute to the editor laterally and next to its line vertically. This is hard to do with CSS...


Here are some screenshots from the inspector

![Screen Shot 2017-02-04 at 11.44.43 AM.png](https://shipusercontent.com/3a7c7ae050a45ed87d20775fc50964ae/Screen%20Shot%202017-02-04%20at%2011.44.43%20AM.png)

![Screen Shot 2017-02-04 at 11.45.09 AM.png](https://shipusercontent.com/848182d91150f29add9e0b1b537de314/Screen%20Shot%202017-02-04%20at%2011.45.09%20AM.png)

**Comment by jonathanKingston** [comment]
@jasonLaster that would work, sorry I was confusing this with the other bug I had opened on when the expression fires it doesn't scroll to the correct position horizontally also.

**Comment by jasonLaster** [comment]
Ahh. That's also interesting. Thanks.

**Comment by jasonLaster** [comment]
This could be fixed in #2287

**Comment by aklt** [comment]
While looking at #2287 I tried to reproduce this, but did not succeed. It may be that the 
`noHScroll` setting on the editor fixed this!

**Comment by jasonLaster** [comment]
@jonathanKingston we fixed this while working on #2287

![](http://g.recordit.co/OF9w7tfRxq.gif)
