### ISSUE TITLE
 Source code destroyed in the debugger when setTimeOut('XXX()') is executed

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1742]
mozTest.png

User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

Steps to reproduce:

1. Open this page:
```
--- mozTest.htm ---
<!DOCTYPE html>
<html>
<head>
<script type='text/javascript' src='mozTest.js'></script>
</head>
<body>
 Hello world!
 <script type="text/JavaScript"> AAA(); </script> 
</body>
</html>
--- mozTest.js ---
function AAA() { setTimeout('BBB()',1); }
function BBB() {	AAA(); }
--- end
```
2. Press F12 and open mozTest.js in the debugger panel

Actual results:

There is no source code of mozTest.js, instead it displays just: 
```
---
BBB() 
---
```
It displays the text executed inside setTimeout()
The text is destroyed every time when the code executes, so if it is looped I see no way to work with debugger on this code.

Expected results:

I expect to see the actual source code, so I can debug it.

**Comment by clarkbw** [comment]
Able to reproduce this.  Feels like some kind of debug server error.  When you increase the timeout this works as expected, but anything `100` or below means you get lots of `ADD_SOURCE` events which seem to screw things up.

**Comment by clarkbw** [comment]
Created https://github.com/devtools-html/debugger.html/projects/11#card-1576978 to track this

**Comment by wh0** [comment]
why is the card not linked to this issue? now I can't follow it.

**Comment by clarkbw** [comment]
> why is the card not linked to this issue? now I can't follow it.

I'm not sure I understand.  The card linked above does link to this issue.  When work begins on this we'll reopen this issue or open a new one and link to it from here.  So if you want to follow this issue you will see the progress as it happens here.

**Comment by olberger** [comment]
What a very strange way to manage tickets... almost impossible from anyone outside to monitor progress, AFAIU... but maybe I'm overlooking something.
