### ISSUE TITLE
Debugger sources emptied on download

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1744]
#### STR:
1. open https://www.mozilla.org/en-US/firefox/all/
2. activate devtools and debugger tab
3. download firefox of your choosing
4. witness all js sources in debugger gone

This makes it impossible to debug js on pages where download occurs as part of a triggered function for example. I'm not aware of other ways to get sources back than to refresh the page. But this looses all previous context you had for debugging and is kind of useless.

In 51 I get "This page has no sources." in 53 the list is just empty.

#### Problem

Downloading a file creates a NAVIGATE event which then causes the debugger to dump all the sources, expecting that Firefox will navigate to a new page.

Here's the last log after I clicked a download link.

```
[DISPATCH NAVIGATE] Object { type: "NAVIGATE" } {
  "type": "NAVIGATE"
}
```

CC @merike https://bugzilla.mozilla.org/show_bug.cgi?id=1323961

**Comment by clarkbw** [comment]
Also, this bug exists with the old debugger as well as the new.  Just tried it out on release Firefox.

**Comment by clarkbw** [comment]
Closing, there is a note in the backlog here: https://github.com/devtools-html/debugger.html/projects/11#card-1467612
