### ISSUE TITLE
avoid right / left references in L10N string identifiers 

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1751]
[bug 1321255](https://bugzilla.mozilla.org/show_bug.cgi?id=1321255) avoid using right / left references in the string identifiers 

Instead of this
```
# LOCALIZATION NOTE (sourceTabs.closeTabsToRight): Editor source tab context menu item
# for closing the tabs to the right of the selected tab.
sourceTabs.closeTabsToRight=Close tabs to the right
```

Use this:
```xml
<!-- LOCALIZATION NOTE (closeTabsToTheEnd.label): This should indicate the
direction in which tabs are closed, i.e. locales that use RTL mode should say
left instead of right. -->
<!ENTITY  closeTabsToTheEnd.label            "Close Tabs to the Right">
<!ENTITY  closeTabsToTheEnd.accesskey        "i">
```

**Comment by clarkbw** [comment]
We should also update the docs to reflect this requirement so we can avoid it next time.

**Comment by clarkbw** [comment]
Here's what you need to get started:

Take a look at the [localization](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#internationalization) docs.

Change the label here: https://github.com/clarkbw/debugger.html/blob/master/src/components/SourceTabs.js#L116 to use something like `closeTabsToTheEnd` and update all the references to the old `closeTabsToTheRight`.

Then also in [strings.json](http://github.com/clarkbw/debugger.html/blob/bd9f991ccda7952770a1f132a7a8d6a6fb5c76dc/src/strings.json#L52) and [debugger.properties](http://github.com/clarkbw/debugger.html/blob/bd9f991ccda7952770a1f132a7a8d6a6fb5c76dc/assets/locales/debugger.properties#L278)

Finally, open up the [RTL (Right To Left)](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#rtl) docs and update them with a note about using string identifiers like End or Start instead of Right or Left respectively.

**Comment by garrettgsb** [comment]
Stand back guys, I got this.
