### ISSUE TITLE
utils/defer is not covered by flow

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1758]
I just noticed this in the [utils/defer](https://github.com/devtools-html/debugger.html/blob/master/src/utils/defer.js#L1) module that it uses `/* flow */` instead of `/* @flow */` and when I changed it Flow didn't complete successfully.

**Comment by clarkbw** [comment]
Here's how I'd get started, this doesn't run yet but is close.

```js
/* @flow */

type Resolve = (result: any) => void;
type Reject = (result: any) => void;

export type Defer = {
  resolve: Resolve,
  reject: Reject,
  promise: Promise<*>
};

function defer(): Defer {
  let resolve: Resolve;
  let reject: Reject;
  const promise = new Promise(function(
    innerResolve: Resolve,
    innerReject: Reject
  ) {
    resolve = innerResolve;
    reject = innerReject;
  });
  return {
    resolve: resolve,
    reject: reject,
    promise: promise
  };
}

module.exports = defer;
```

**Comment by arthur801031** [comment]
I'll take a stab at this :)

Are `Resolve` and `Reject` = `any` type, like this [any](https://flowtype.org/docs/builtins.html#any)?
