### ISSUE TITLE
Improve Flow docs

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1759]
We need to update the Flow docs so it is more obvious how people can get started, make changes, test their changes, and know that Flow is working correctly.

**Comment by clarkbw** [comment]
Intro gif http://recordit.co/QYAyms9n3C

**Comment by clarkbw** [comment]
Cheat Sheet: http://www.saltycrane.com/blog/2016/06/flow-type-cheat-sheet/

**Comment by clarkbw** [comment]
#1760 has some new docs incuded

**Comment by jasonLaster** [comment]
We can always improve docs, but atleast we have a baseline
