### ISSUE TITLE
[docs] Issue reporters cannot add labels to issues unless they have admin privileges

### ISSUE THREAD

**Issue by sole** [devtools-html/debugger.html#1762]
Right now the [contributing docs](https://github.com/devtools-html/debugger.html/blob/master/CONTRIBUTING.md#reporting-bugs-bug) ask issue reporters to label issues when filing them, but you cannot do that unless you have additional privileges.

(I am a member of the `devtools-html` organisation and even I cannot add labels)

**Comment by clarkbw** [comment]
Good catch!  Can you update the docs to remove that?

We should probably add something about the triage process as well.

**Comment by sole** [comment]
I will! (I can't assign myself to take the bug though :-D)
