### ISSUE TITLE
Add licenses

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1763]
We should add licenses for:
* fuzzaldrin-plus
* lodash
...

**Comment by clarkbw** [comment]
We could check in a generated license disclaimer via `yarn licenses generate-disclaimer` and perhaps have a check in our CI that running that command isn't different than the file already checked in.

**Comment by jbhoosreddy** [comment]
I think it's a really good idea to do this. I noticed this here facebook/react#8803 (#8789) similar. Maybe we could come up with a similar solution. As part of the bundle creation process.

**Comment by jasonLaster** [comment]
at the moment, we're updating the licenses in [M-C](https://bug1331654.bmoattachments.org/attachment.cgi?id=8828842). This process is not too cumbersome.

@clarkbw I like that idea as we could basically build the debugger's `licenses.html` page and check to make sure it's okay

**Comment by jasonLaster** [comment]
added
