### ISSUE TITLE
[keyboard] should be easier to tab to commands

### ISSUE THREAD

**Issue by Garbee** [devtools-html/debugger.html#1772]
Using the keyboard to navigate currently stops at the editor space. There doesn't seem to be a way to tab from the file manager over to the secondary panel to reach breakpoints and the command bar actions.

Ref image:

![seconday-panel-inaccessible](https://cloud.githubusercontent.com/assets/868301/22154302/f5a09924-def8-11e6-8c09-84efce68dc9e.png)

### Recommendation

This is a tricky situation. Users may want to go from the file manager to the editor or over to the secondary panel dependent upon their context. Github and Etsy for example when you initially tab on their page, after the first tab you get a "skip to content" button to bypass their menus. I think we could utilize the same concept in this case. What we'd do is:

1. Add the same type of action to the end of the file manager to skip to the secondary panel. We would need a better name to call it. ;)
2. Upon the initial tab in the debugger, we could place in the same trigger in case the user wants to jump over there right away. This would be useful to bypass a lot of tabbing if a site has a lot of external resources from various domains causing a large list for the main file manager.

In case the secondary panel is collapsed, we should still show these triggers to tab users and if acted upon it should open the panel and place focus within it. If the user doesn't want to tab to the secondary panel and instead skip to the code editor at the end of the file manager, they just tab again to resume normal tab flow.

**Comment by jasonLaster** [comment]
Thanks for finding this @Garbee!

* Could you share screenshots from Etsy + Github
* Could you share some quick mocks of what this would look like?

**Comment by jasonLaster** [comment]
I'm closing this and moving it to the [enhancements] board. 
It's also discoverable on the tracking issue. 

[enhancements]: https://github.com/devtools-html/debugger.html/projects/5
