### ISSUE TITLE
Cleanup console messages for yarn start

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1782]
Here's what we currently print out when you run the debugger from `yarn start`.

```bash
Listening for WS on *:9000
Will proxy to TCP on *:6080 on first WS connection
Protocol messages can be logged by enabling logging.firefoxProtocol in your local.json config
View debugger examples here:
https://github.com/devtools-html/debugger-examples
Development Server Listening at http://localhost:8000
```

```bash
Listening for WS on *:9000
Will proxy to TCP on *:6080 on first WS connection
```

The first 2 lines are not actually useful, if we need them perhaps we could at least combine them into one shorter message.  Those message come from [here](https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-launchpad/bin/firefox-proxy#L9-L10) and so we will need to create a PR against that repo instead of this one to fix that.

```bash
Protocol messages can be logged by enabling logging.firefoxProtocol in your local.json config
```

The 3rd line is intended to help those who might be looking for how to log messages but I don't feel like its actually that helpful anymore; our docs have improved quite a bit.  That one is also found in the [devtools-core repo](https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-launchpad/bin/firefox-proxy#L12-L13) and so a PR will need to be filed there.  I think we could just remove this one.

```bash
View debugger examples here:
https://github.com/devtools-html/debugger-examples
Development Server Listening at http://localhost:8000
```

For the last set of lines I think we could output more useful instructions for next steps and suggest the `yarn run firefox` commands.  Also since both `yarn run firefox` and `yarn run chrome` now take you to the examples pages I don't think we need to include that.

Here's what I'd suggest:  (though it may be spartan)

```bash
yarn run firefox                         ( in another terminal for a debuggable Firefox )
open http://localhost:8000      ( in any browser to see the debugger.html )

Further documentation: open http://bit.ly/debugger-local-dev
```

It might be nice to use the [chaulk](https://www.npmjs.com/package/chalk) module here as well to call out the commands and fade out the instructions.

What do you all think?

CC @jasonLaster

**Comment by jasonLaster** [comment]
Haha - this is great. 

- perhaps add a header like: next steps
- definitely chalk
- can the entire doc be in core's development server?

**Comment by clarkbw** [comment]
If anyone wants to play with console messages and chaulk, here's a nice one.

**Comment by ckwjdals90** [comment]
I'll take this!

**Comment by adymitruk** [comment]
check slack.. It's MINE! ;)

**Comment by ckwjdals90** [comment]
yeah just leave a message here first next time.

**Comment by clarkbw** [comment]
@adymitruk yours!

**Comment by adymitruk** [comment]
ok. I used it to demonstrate the fork-PR cycle and some dev stuff. The PR is [here](https://github.com/devtools-html/devtools-core/pull/120)

**Comment by jasonLaster** [comment]
Thanks @adymitruk
