### ISSUE TITLE
[L10N] Revert key renames

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1783]
We should revert this commit so that the L10N keys are different and get picked up for translation.

https://github.com/devtools-html/debugger.html/commit/97fbfb934b5ef2ba95dd57e0c8914b4789a3c292

**Comment by flodolo** [comment]
That's only part of the reverted strings. Also search tooltips were changed
https://hg.mozilla.org/mozilla-central/diff/2301f25d1595/devtools/client/locales/en-US/debugger.properties#l1.241

**Comment by jasonLaster** [comment]
Thanks @flodolo!

**Comment by jasonLaster** [comment]
@flodolo looks like this was the offending PR: https://github.com/devtools-html/debugger.html/commit/fb228318a76d274e3c83cb52926a2f266f1d9439
