### ISSUE TITLE
Break point snippets are truncated after 30 chars

### ISSUE THREAD

**Issue by assafdd** [devtools-html/debugger.html#1802]
Would be much nicer using CSS text-overflow: ellipsis.
<img width="1436" alt="breakpoint_sinppet_truncated" src="https://cloud.githubusercontent.com/assets/1753718/22219078/0ba5c2ba-e1b2-11e6-823b-21231c8b89aa.png">

**Comment by jasonLaster** [comment]
@assafdd completely agreed. The problem is that I don't understand CSS ellipsis :)

**Comment by assafdd** [comment]
@jasonLaster  PR on the way :)

**Comment by clarkbw** [comment]
@assafdd can you also make sure to add some padding on the right hand side?  Just so the ellipsis doesn't hit the edge.  The same padding that exists on the left hand side should probably be good.  🥂

**Comment by assafdd** [comment]
@clarkbw will do
