### ISSUE TITLE
[source search] The source search close button is too dark

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1807]
The close button on the right is much darker than the tab buttons above it. I beleive the tab buttons like "new tab" are styled with `color-comment`, which is what we should use here.

We should check to see how the close button looks in other places. We might want to only style this button

**Comment by paulocamboim** [comment]
I'll take this one

**Comment by atom888** [comment]
I'll take this one!

**Comment by clarkbw** [comment]
@atom888 all yours!
