### ISSUE TITLE
[Tabs] Vertically align tabs and new tab button

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1808]
@irfanhudda made some really nice improvements in https://github.com/devtools-html/debugger.html/pull/1745 for the toggle button and new tab button.

We should see if we can get the tabs to vertically align with the new tab button now as well. I think this means that we should move the tab text up a bit...

Also, it might be a good opportunity to use flexbox with the tabs a bit more.

<img width="865" alt="screen shot 2017-01-23 at 7 02 30 pm" src="https://cloud.githubusercontent.com/assets/254562/22228350/8e136ef0-e19e-11e6-9b6d-29baa4002e42.png">

**Comment by soheilhm** [comment]
I am working on this

**Comment by princiya** [comment]
I am working on this issue.

**Comment by princiya** [comment]
Not able to figure out, where the highlighted css (bottom right) is generated from. Any inputs please?
![css](https://cloud.githubusercontent.com/assets/8022693/22617910/1ce70aee-ead0-11e6-95a4-97740f929f88.png)
@irfanhudda @jasonLaster @clarkbw @wldcordeiro

**Comment by irfanhudda** [comment]
@princiya That CSS is probably generated from [https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/Tabs.css#L50](https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/Tabs.css#L50)

Also take a look at [https://devtools-html.github.io/debugger.html/docs/local-development.html#rtl](https://devtools-html.github.io/debugger.html/docs/local-development.html#rtl) to better understand why we have things like `padding-inline-start`, `padding-inline-end`.
