### ISSUE TITLE
[Commandbar] ctrl-f5 should do a full refresh page

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1809]
**Steps to reproduce:**

* File, Open, pick local file to debug
* F12
* make change to source
* F5
* changes didn't come through, so ctrl-f5
* changes didn't come through, so hit enter in address bar. this worked. so does clicking refresh button.

**Expected results:**
ctrl-F5 or F5 should have refreshed. stale cache? I think there is a setting somewhere in F12 for this to disable cache, but both debugger cache and browser caches should be in sync.

**Comment by jasonLaster** [comment]
@clarkbw can we look into this soon

**Comment by zspitzer** [comment]
also when the debugger is paused, F5 only refreshes the browser if dev tools is focussed

**Comment by AlexisDeschamps** [comment]
It seems that F5 always refreshes and brings in the latest local changes for me on Nightly and Developer on Windows 10.

**Comment by jasonLaster** [comment]
lets re-open if we can reproduce it

**Comment by Aybee** [comment]
I'm on FF 59.0.3

No chance here to get the new content of HTML in Debugger tab. The Inspector tab shows the new content.
