### ISSUE TITLE
Context menu has a vertical line on Windows

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1810]
[bug 1322180](https://bugzilla.mozilla.org/show_bug.cgi?id=1322180) provides a [screenshot](https://bugzilla.mozilla.org/attachment.cgi?id=8816932) of a windows context menu gone wrong.

**Comment by jasonLaster** [comment]
@garbee, @jbhoosreddy mind trying this on a windows computer?

**Comment by clarkbw** [comment]
I can't see this on my Windows machine 😕

**Comment by jasonLaster** [comment]
i'll close and we can re-open if we get other complaints
