### ISSUE TITLE
Flow coverage uploading to CodeCov

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1811]
In #1639 I added flow coverage reporting from CircleCI to codecove.io.  However Flow Coverage reports don't yet work with @codecov.  We need https://github.com/facebook/flow/pull/3231 to land first so we have the right information and then we'll need Codecov to support that.  This issue is for tracking that work.

**Comment by jasonLaster** [comment]
closing as it's tracked globally and it's blocked in *flow*
