### ISSUE TITLE
git push to personal repo failes

### ISSUE THREAD

**Issue by soheilhm** [devtools-html/debugger.html#1813]
`yarn install` and `yarn start Firefox` works well but when setting the `git origin` to personal repo, `git push` fails as per screenshot below.

![screen shot 2017-01-23 at 7 07 53 pm](https://cloud.githubusercontent.com/assets/17885979/22232619/657633a0-e19f-11e6-87c4-38618a50297c.png)

**Comment by clarkbw** [comment]
Seeing this in #1814

**Comment by jbhoosreddy** [comment]
closing this issue for now.
