### ISSUE TITLE
git push causes error during verify "SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode"

### ISSUE THREAD

**Issue by steffiau** [devtools-html/debugger.html#1814]
Tried pushing my commits, when husky is verifying my code, the below syntax error shows up.

```
yarn run v0.19.1
$ node src/test/node-unit-tests.js --dots
/Users/Owner/projects/debugger.html/src/test/node-unit-tests.js:67
let testFiles;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/Owner/.nvm/versions/node/v4.4.5/bin/node" "/Users/Owner/.nvm/versions/node/v4.4.5/bin/npm" "run" "prepush"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! debugger.html@0.0.8 prepush: `yarn run lint && yarn run test -- --dots`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the debugger.html@0.0.8 prepush script 'yarn run lint && yarn run test -- --dots'.
npm ERR! This is most likely a problem with the debugger.html package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yarn run lint && yarn run test -- --dots
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs debugger.html
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls debugger.html
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Owner/projects/debugger.html/npm-debug.log

husky - pre-push hook failed (add --no-verify to bypass)

error: failed to push some refs to 'git@github.com:steffiau/debugger.html.git'
```

**Comment by jbhoosreddy** [comment]
from what I can tell by looking at your error log, you might need to upgrade your node engine to a newer version. I use v7.3.0 and I don't see any error on my end.

I recommend installing using nvm, if possible.

`husky` is preventing you from pushing your commits to origin because the unit tests are failing. `node src/test/node-unit-tests.js --dots`

you can bypass it by doing something like `git push origin --no-verify`

**Comment by steffiau** [comment]
Thanks @jbhoosreddy 
My node is on v6.9.4. Which should satisfy the requirement "node": ">=6.9.0". Should the above syntax error still appear?

**Comment by jbhoosreddy** [comment]
So without all the information, it might be a little hard to debug but looking at your error log, this line gives me concern.

`npm ERR! argv "/Users/Owner/.nvm/versions/node/v4.4.5/bin/node" "/Users/Owner/.nvm/versions/node/v4.4.5/bin/npm" "run" "prepush"`

could you tell us the output of `node -v` and `npm -v`? Also `nvm ls`? Maybe your default version is not set to v6.9.4?

**Comment by steffiau** [comment]
`node -v v6.9.4`
`npm -v 3.10.10`
`nvm ls` gives `nvm: command not found`.
Maybe my nvm wasn't properly installed?

**Comment by jasonLaster** [comment]
Hmm, @steffiau I tried `v6.9.4` and it worked. Hmm, try making a small test script with `let` or `const`

**Comment by clarkbw** [comment]
> Maybe my nvm wasn't properly installed?

I think this has something to do with it.

You can see in this line of the error:

```bash
npm ERR! argv "/Users/Owner/.nvm/versions/node/v4.4.5/bin/node" "/Users/Owner/.nvm/versions/node/v4.4.5/bin/npm" "run" "prepush"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
```

That the system is referencing nvm with an outdated node and npm, which is what I believe is causing the issue.  For some reason running this command, perhaps husky, is picking up the old version of node.

@steffiau if you're using [homebrew](http://brew.sh/) you might want to check that nvm is installed by running `brew list nvm`.  If that command errors out you can double check that running `command -v nvm` doesn't print `nvm` but instead prints nothing.  At this point you probably want to uninstall `nvm` if you're no longer using it by running `rm -r /Users/Owner/.nvm/` which removes `nvm` from your system.

**Comment by clarkbw** [comment]
Ok, it looks like this is [husky](https://github.com/typicode/husky) doing this.  I found that in the husky source they look for `nvm` and use it if they can find it, you can see that here: https://github.com/typicode/husky/blob/master/src/index.js#L59-L63 So if you have that `.nvm` directory husky seems to prefer it.

**Comment by jasonLaster** [comment]
@clarkbw that's crazy that you found this :)

**Comment by clarkbw** [comment]
I had a hunch!

**Comment by jbhoosreddy** [comment]
@clarkbw crazy hunch!

**Comment by clarkbw** [comment]
Ok, I'm going to close this out because I believe #1828 will fix the issue.
