### ISSUE TITLE
yarn run firefox didn't set the remote debug ports correctly on Windows

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1825]
Several Windows 10 users last night had problems getting Firefox started in a debuggable state.  We should review the command line options required for Windows.  I have the feeling something isn't being passed correctly because as soon as I used the GCLI and typed `listen` the Firefox that ran was working as expected.

**Comment by jasonLaster** [comment]
@clarkbw refiled in core - https://github.com/devtools-html/devtools-core/issues/121
