### ISSUE TITLE
add Slack to the README

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1826]
We have a new Slack channel and we need to tell people about it.  Our [README](https://github.com/devtools-html/debugger.html/blob/master/README.md#discussion) has a discussion section that needs updating.

Lets include a link to sign up: https://devtools-html-slack.herokuapp.com/

It might be nice to also include a badge with the other badges ![](https://devtools-html-slack.herokuapp.com/badge.svg) 

Lets not remove the IRC suggestion as lots of people still use that.  We can just emphasize Slack as the primary method for now.

**Comment by AlannaHarlton** [comment]
Hi Bryan I'm walking through this one with my tutor right now.

**Comment by clarkbw** [comment]
> Hi Bryan I'm walking through this one with my tutor right now.

All yours @AlannaHarlton!

**Comment by clarkbw** [comment]
Thanks @AlannaHarlton!
