### ISSUE TITLE
turn on hot reloading by default for development environment

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1830]
Customizing the `config/local.json` is an advanced category of involvement.  I think we should turn on `hotReloading` by default for development so people don't have to mess with the default config to get a good working environment.

**Comment by jasonLaster** [comment]
Hold onto your hat. @bomsy, @jbhoosreddy and I worked on the Settings page during the call:
https://github.com/devtools-html/devtools-core/issues/37

**Comment by bomsy** [comment]
I think we should get hot-reloading and other config settings into the settings page.
Is that ok?

**Comment by jasonLaster** [comment]
@bomsy that sounds like a good idea. I'm hesitant to do it by default because it's also could have edge cases.
