### ISSUE TITLE
[Editor] Selecting text jumps

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1832]
We have this weird bug where if you select text in a large document half way down the document, the doc can jump around quite a bit. my theory is codemirror is doing something with the tokens that causes the jumping...

@bomsy, @Zacqary, @jbhoosreddy  could be a weird search bug...

![](http://g.recordit.co/DuMIfkKrB1.gif)

**Comment by wldcordeiro** [comment]
This is fixed I believe.
