### ISSUE TITLE
[Editor] fix the pane toggle button direction

### ISSUE THREAD

**Issue by liorpr** [devtools-html/debugger.html#1834]
The pane toggle button(.toggle-button-end) direction is wrong on vertical mode. This happens because the first css rule is more specific than the last one

<img width="488" alt="screen shot 2017-01-25 at 1 20 00 pm" src="https://cloud.githubusercontent.com/assets/6891569/22288748/f5ec872e-e300-11e6-9c84-66a35e9469ac.png">

**Comment by liorpr** [comment]
submitting my fix, imo we can choose between explicitly state !improtant or just use something like

`html:not([dir="rtl"]).toggle-button-end.vertical svg,
html[dir="rtl"] .toggle-button-start svg {
  transform: rotate(-90deg);
}
`

**Comment by wldcordeiro** [comment]
@liorpr I'm for avoiding `!important` at pretty much all costs. I feel like that property is a code smell. But thanks for reporting the issue.
