### ISSUE TITLE
[Editor] polish selection / highlight colors

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1836]
We currently have lots of UI states for the editor selections and highlights. Here's a general list:

* user selects text (focused on the editor)
* user selects text (clicks on some other debugger UI)
* user does a search and we highlight the current match
* user does a search and we highlight all of the other matches

Current Problems:
* when the user clicks away the selection becomes yellow
* the yellow is generally a bit too strong (we can just change the color and add an alpha)

Goal:
* fix unfocused selection color
* clean up the yellow

### Chrome

chrome does this well

![](http://g.recordit.co/Z15FmWCxZ5.gif)

### Our UI

* You can see the blue selection becomes yellow when you click away
* on chrome cmd+g does not change the match to yellow

![](http://g.recordit.co/2i1ulRYsdT.gif)

* on firefox cmd+g does change the match to yellow

![](http://g.recordit.co/7rPSluR0Zc.gif)

**Comment by bomsy** [comment]
i'll take this!

**Comment by jasonLaster** [comment]
closing as this is very vague
