### ISSUE TITLE
[EditorHover] Add a simple getExpressionsInScope function

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1842]
We recently landed the babel parser and it's now time to do a simple MVP function to put it to use.

What I imagine is we write a simple traversal function that finds some valid expressions that are "in scope"

We can do this by:
a) finding the node that corresponds with a scope
b) scanning it's child nodes for the simplest expression, an identifier. 

For example, if we pause in `sum`, we should be able to find the two identifiers `a`, `b` and tell the editor that if the user hovers over one of them we can do an evaluation.

```js
function sum(a+b) {
  debugger;
  return a + b;
}
```

Here are two tools for doing this [ast explorer][explorer] [babel handbook][handbook]

[explorer]: https://astexplorer.net/
[handbook]: https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#toc-get-the-path-of-a-sub-node

**Comment by mattzeunert** [comment]
I'll try and implement this.

**Comment by jasonLaster** [comment]
Just landed #1988, which gives a node path, which references a scope. We can use this to get all of the binding variables in the scope and their reference paths:

I'm actually adding a babel path that [demonstrates](https://github.com/babel/babel/pull/5296/files#diff-56f320a6a89e1ca4a32a0cbb2da293a1R79) this behavior.
