### ISSUE TITLE
Source List doesn't refresh properly

### ISSUE THREAD

**Issue by jbhoosreddy** [devtools-html/debugger.html#1848]
### STR:
0. Set up debugger and debuggee.
1.a. Go to cnn.com.
1.b. Observe sources in the source list.
2.a. Go to foxnews.com
2.b Observe sources in the source list.

### ER:
cnn.com sources should be removed once the debuggee is on foxnews.com.

### AR:
scripts from both wesites persist. and since both websites pull in a lot of scripts, it becomes very noisy.

### Associated Gif example
http://g.recordit.co/JbgDluPQWA.gif

![](http://g.recordit.co/JbgDluPQWA.gif)

**Comment by jasonLaster** [comment]
I think the gif is too long lol

**Comment by arthur801031** [comment]
I will take a stab at this :)
