### ISSUE TITLE
getting-setup.md has broken link

### ISSUE THREAD

**Issue by SezginEge** [devtools-html/debugger.html#1852]
Hi,

I was reading ["getting setup"](https://github.com/devtools-html/debugger.html/blob/master/docs/getting-setup.md#starting-chrome) file. On "Starting Chrome" section, the link given for the script file redirects 404 page. 

Broken link: https://github.com/devtools-html/debugger.html/blob/master/bin/chrome-driver

**Comment by clarkbw** [comment]
@SezginEge nice catch!  That file moved here: https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-launchpad/bin/chrome-driver.js

Want to make the update?

**Comment by SezginEge** [comment]
@clarkbw 👍

**Comment by clarkbw** [comment]
All yours @SezginEge!
