### ISSUE TITLE
mochitest reload() function does not reset sources state

### ISSUE THREAD

**Issue by yurydelendik** [devtools-html/debugger.html#1865]
While working on #1864, I noticed that after reload() `waitForSources` does no wait for new sources to reload (it's using old sources status). Even after #1863, problem is not going away. I had to insert a debugger statement (or `waitForTime(1000)` works too).

Looks like test at browser_dbg-navigation.js (near [`yield reload(dbg, "long.js");`](https://github.com/devtools-html/debugger.html/blob/master/src/test/mochitest/browser_dbg-navigation.js#L44)) does not check anything useful due to this finding.

**Comment by jasonLaster** [comment]
thanks!

**Comment by jasonLaster** [comment]
finished in #2719
