### ISSUE TITLE
[VerticalLayout] toggle button is in the top right

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1867]
We recently made some changes to the toggle buttons and accidentally pulled the right one to the top of the welcome pane in vertical mode:

It should actually be in the bottom right.

@liorpr, @irfanhudda mind looking into this?

![](http://g.recordit.co/Uzwe4t3eoo.gif)

**Comment by irfanhudda** [comment]
I'll take a look at this

**Comment by jasonLaster** [comment]
> changed specificity of selectors

@irfanhudda what do you mean?

CC @gasolin

**Comment by irfanhudda** [comment]
@jasonLaster I filed an issue here gasolin/postcss-bidirection#6
