### ISSUE TITLE
Increase Collaboration

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1872]
We currently have a fantastic [community](https://github.com/devtools-html/debugger.html/graphs/contributors) of close to 100 people who have contributed code to the Debugger. I'd like to see if we can leverage that community to bring in the next hundred contributors.

I have three strategies for doing this, but I'd love to hear other ideas as well:

1. Mentoring
2. Pairing
3. Experts

**Mentoring** We promise to find a mentor to help with a good first bug or beginner exercise. We can match people when they stop in channel. 

**Pairing** We promise to match someone with a pair. If no one is available at the moment, we can help schedule something later.

**Experts** One of the most basic things i've noticed is that many people don't realize it's okay to ask questions. I've seen people spend hours stuck when a simple question would have helped. By providing a list of *experts* or *ninjas* or whatever, we send a positive signal that we really do want to help you and I think more people would feel comfortable asking. Also, for us, who secretly doesn't want to be a ninja!

With both ideas, we can iterate and see if we can find a scalable solution. For instance, I can see us building a list of people interested in mentoring and pairing.

Like many things, this is an experimentation. If we're not reaching our goal or it is too expensive we can always stop.

**Comment by jbhoosreddy** [comment]
I think it is a great idea. 💃
