### ISSUE TITLE
Tab overflow and hide secondary panel actions overlap new tab with small width

### ISSUE THREAD

**Issue by Garbee** [devtools-html/debugger.html#1877]
Two last buttons in the tab area overlap the new tab button when you shrink down the UX enough. Eventually, overlapping the new tab button before it is hidden completely by the secondary panel.

To reproduce simply slide the secondary panel inwards until they start to overlap.

![overlapping actions](https://cloud.githubusercontent.com/assets/868301/22404705/8dc7c4a4-e604-11e6-90b2-5ecb301b1285.png)

**Comment by jasonLaster** [comment]
@Garbee was thinking that flexbox could really help solve these absolutely positioned buttons

**Comment by princiya** [comment]
@jasonLaster is this issue fixed with the new flex header layout?

**Comment by jasonLaster** [comment]
Yes!

**Comment by magicp-github** [comment]
I can reproduce this issue with the latest Nightly build.
