### ISSUE TITLE
[chrome] willNavigate and navigated are not called when the debuggee navigates

### ISSUE THREAD

**Issue by arthur801031** [devtools-html/debugger.html#1883]
### Issue
When the debuggee is in Chrome, `willNavigate()` and `navigated()` in https://github.com/devtools-html/debugger.html/blob/master/src/actions/navigation.js will not execute when a user clicks on the back/forward button.

### Expected Result (The debuggee is in Firefox)
![ufk3lhy0w4](https://cloud.githubusercontent.com/assets/4562118/22429223/d8b5a922-e744-11e6-992e-313d621b0aaa.gif)
(GIF by @jasonLaster)

### Actual Result (The debuggee is in Chrome)
![j8006cjnhe](https://cloud.githubusercontent.com/assets/4562118/22429442/95642288-e745-11e6-99f0-9f77a8e7d7d8.gif)

CC @jasonLaster

**Comment by bomsy** [comment]
Closing this as new issue created for this fix! 
[#168](https://github.com/devtools-html/devtools-core/issues/168)
