### ISSUE TITLE
Convert to es modules

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1884]
### We are switching to es6 modules for several reasons: 
* flow uses es6 modules
* it's more expressive
* we want to use es6 classes 

[cjs-to-es6](https://github.com/nolanlawson/cjs-to-es6) is a great tool for converting a module

### Steps to convert a module
* `cjs-to-es6 src/components/SecondaryPanes/index.js`
* update import sites to use `default`

#### nested destructuring. watch out for `cjs-to-es6` missing this

```js
const { Services: { appinfo }} = require("devtools-modules");
```

```js
import { Services } from "devtools-module";
const { appinfo } = Services;
```

#### mocking modules

The unit tests mock some modules like [`devtools-modules`](https://github.com/devtools-html/debugger.html/blob/master/src/test/node-unit-tests.js#L15). `mock-require` doesn't work with es modules so we should find a work around.

#### react-dom

For some reason `import dom from "react-dom"` does not work, so just leave that one as is.

Ask all questions in our **slack** room. This can potentialy be tricky with edge cases.

### Progress converting the codebase

- [x] actions
  - [x] breakpoints.js
  - [x] coverage.js
  - [x] event-listeners.js
  - [x] expressions.js
  - [x] index.js
  - [x] navigation.js
  - [x] pause.js
  - [x] sources.js
- [ ] components
  - [x] App.js
  - [ ] Editor
    - [x] Breakpoint.js
    - [ ] ConditionalPanel.js
    - [x] Footer.js
    - [ ] HitMarker.js
    - [ ] SearchBar.js
    - [x] Tabs.js
    - [ ] index.js
    - [x] Preview.js
  - [ ] SecondaryPanes
    - [x] Breakpoints.js
    - [x] ChromeScopes.js
    - [x] CommandBar.js
    - [x] EventListeners.js
    - [x] Expressions.js
    - [x] Frames.js
    - [x] Scopes.js
    - [x] WhyPaused.js
    - [ ] index.js
  - [x] SourceSearch.js
  - [x] Sources.js
  - [x] SourcesTree.js
  - [x] WelcomeBox.js
  - [ ] shared
    - [x] Accordion.js
    - [ ] Autocomplete.js
    - [x] Button
    - [x] Close.js
    - [x] PaneToggle.js
    - [x] Dropdown.js
    - [x] ManagedTree.js
    - [x] ObjectInspector.js
    - [x] Rep.js
    - [x] Svg.js
    - [x] menu.js
- [ ] constants.js
- [x] feature.js
- [ ] global-types.js
- [ ] main.js
- [ ] panel.js
- [x] reducers
  - [x] async-requests.js
  - [x] breakpoints.js
  - [x] coverage.js
  - [x] event-listeners.js
  - [x] expressions.js
  - [x] index.js
  - [x] pause.js
  - [x] sources.js
- utils
	- editor
		- [x] build-query.js
		- [x] expression.js
		- [ ] index.js
		- [x] source-documents.js
		- [x] source-search.js
	- redux
		- middleware
			- [x] history.js
			- [x] log.js
			- [x] promise.js
			- [x] thunk.js
			- [x] wait-service.js
	- pretty-print
		- [x] worker.js
		- [x] index.js
    - [x] DevToolsUtils.js
	- [x] assert.js
	- [x] client.js
	- [x] create-store.js
	- [x] defer.js
	- [x] dehydrate-state.js
	- [x] editor.js
	- [x] fromJS.js
	- [x] log.js
	- [x] makeRecord.js
	- [x] path.js
	- [x] pause.js
	- [x] prefs.js
	- [x] test-head.js
    - [x] utils.js

**Comment by Garbee** [comment]
FYI `CommandBar` is currently *not* updated to ES6 module syntax. Currently it is checked off, which seems incorrect.

**Comment by OrRosenblatt** [comment]
Hi, I"m starting to work on this.

**Comment by jasonLaster** [comment]
Great. Share the modules you're refactoring

**Comment by OrRosenblatt** [comment]
I finished refactor constants.js and the files in actions folder.

**Comment by sashakru** [comment]
Will start with `reducers`

**Comment by barakd** [comment]
started working on utils #goodnessSquad

**Comment by sashakru** [comment]
After switching to es modules I encountered with:

```
src/reducers/breakpoints.js:54
 54: function update(state = State(), action: Action) {
                     ^^^^^ parameter `state`. Missing annotation
``` 

I'm not familiar with `Flow` and not pretty sure what I need to define, any suggestions?

**Comment by clarkbw** [comment]
Hi @sashakru give this a try:

```js

function update(state: BreakpointsState = State(), action: Action) {
  switch (action.type) {
    case "ADD_BREAKPOINT": {
```

And if that doesn't work you can just go ahead with this instead:

```js

function update(state: any = State(), action: Action) {
  switch (action.type) {
    case "ADD_BREAKPOINT": {
```

**Comment by jasonLaster** [comment]
We're currently **137/280** basically 50% in the components directory

**Comment by clarkbw** [comment]
I'm going to try working on the Dropdown.js file.

**Comment by clarkbw** [comment]
Looks like Dropdown.js was already done, picking `menu.js` instead.

**Comment by wldcordeiro** [comment]
I'm tackling the actions.  😄

**Comment by jeffpape** [comment]
i would like to take utils/pause.js
thank you.

**Comment by Erica42** [comment]
I'd like to work on event-listeners.js

**Comment by Erica42** [comment]
I'd like to work on expressions.js

**Comment by wldcordeiro** [comment]
@Erica42 if it's in `actions/` I've got the whole dir. I'm opening the PR shortly. 😄

**Comment by Erica42** [comment]
@wldcordeiro it's in reducers. :)

**Comment by virzen** [comment]
Hi, I would like to take care of `reducers/sources`.

**Comment by jasonLaster** [comment]
@virzen that'd be great. Thanks

**Comment by virzen** [comment]
There it goes! ☝️ 😄

**Comment by virzen** [comment]
Since it was really a breeze, I would also take care of the other reducers, that is:
- async requests,
- breakpoints,
- coverage,
- index,
- pause.

**Comment by jasonLaster** [comment]
@virzen go for it!

**Comment by jasonLaster** [comment]
@virzen @peterschussheim - we're now at 68% for the project, which is a huge jump

and 86% for components which is also a big jump from 50% recently!

**Comment by peterschussheim** [comment]
Starting work on the remaining components.

**Comment by jasonLaster** [comment]
We're down to just the random test files and one offs

![screen shot 2017-05-16 at 9 20 39 am](https://cloud.githubusercontent.com/assets/254562/26107970/1495f862-3a19-11e7-8abe-620671b26dbc.png)
