### ISSUE TITLE
Convert to es6 classes

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1890]
Here's a [gist](https://gist.github.com/jasonLaster/d95a10362fe1e6b687aabba2df26b72e) with some notes.

I'm not sure if we want to switch to the decorator, but the explicit map functions are nice

## Components

- [x] App
- [x] Sources
- [x] SourcesTree
- [x] SourceSearch
- [x] WelcomeBox
- [x] Editor
  - [x] Breakpoint
  - [x] Footer
  - [x] HitMarker
  - [x] Editor *
  - [x] SearchBar*
  - [x] Tabs
  - [x] Preview
- [x] SecondaryPanes
  - [x] Breakpoints
  - [x] ChromeScopes
  - [x] CommandBar
  - [x] EventListeners
  - [x] Expressions
  - [x] Frames
  - [x] SecondaryPanes
  - [x] Scopes
  - [x] WhyPaused
- [x] shared
  - [x] Button
    - [x] PaneToggle
  - [x] Accordion
  - [x] AutoComplete
  - [x] Dropdown
  - [x] ManagedTree
  - [x] ObjectInspector
  - [x] Popover
  - [x] ResultList
  - [x] SearchInput

**Note: Asterisks next to the component are probably harder tasks than the others.**

**Comment by tomrav** [comment]
Starting to take a look at this.
<3 #goodnessSquad

**Comment by wldcordeiro** [comment]
Added a list to track the components that have been converted.

**Comment by ryanjduffy** [comment]
Opened a PR for converting the SecondaryPanes

**Comment by jasonLaster** [comment]
We're currently **16/32** components refactored!

**Comment by peterschussheim** [comment]
Starting to work on  Breakpoint, Footer, HitMarker.

**Comment by jasonLaster** [comment]
Great!

**Comment by deneuv34** [comment]
may I join to work on AutoComplete?

**Comment by jasonLaster** [comment]
Sure!

**Comment by peterschussheim** [comment]
Starting work on SearchBar

**Comment by ryanjduffy** [comment]
^^^ PR for Editor

**Comment by ryanjduffy** [comment]
^^^ PR for remaining shared components

**Comment by jasonLaster** [comment]
Thanks @AnshulMalik @ryanjduffy @wldcordeiro and everyone else!
