### ISSUE TITLE
[Flow] add types to components

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1894]
We'd like to support flow types in our components. This issue will track our progress and will be a good place to raise issues as they arise.

Here are some [flow] docs. The best thing to do is to open one PR per module converted to flow.

- [ ] components
  - [x] App.js
  - [ ] Editor
    - [x] Breakpoint.js
    - [x] ConditionalPanel.js
    - [x] Footer.js
    - [x] HitMarker.js
    - [x] SearchBar.js
    - [x] Tabs.js
    - [ ] index.js
  - [x] SecondaryPanes
    - [x] Breakpoints.js
    - [x] ChromeScopes.js
    - [x] CommandBar.js
    - [x] EventListeners.js
    - [x] Expressions.js
    - [x] Frames.js
    - [x] Scopes.js
    - [x] WhyPaused.js
    - [x] index.js
  - [x] SourceSearch.js
  - [x] Sources.js
  - [x] SourcesTree.js
  - [ ] WelcomeBox.js
  - [x] shared
    - [x] Accordion.js
    - [x] Autocomplete.js
    - [x] Button
    - [x] Close.js
    - [x] PaneToggle.js
    - [x] Dropdown.js
    - [x] ManagedTree.js
    - [x] ObjectInspector.js
    - [x] Rep.js
    - [x] Svg.js
    - [x] menu.js

[flow]: https://github.com/devtools-html/debugger.html/blob/master/docs/flow.md

**Comment by arthur801031** [comment]
I'll take `SecondaryPanes/Breakpoints.js`.

**Comment by arthur801031** [comment]
I'll take the following:
- SecondaryPanes/Scopes.js

**Comment by arthur801031** [comment]
I'll take the following:
- `shared/Autocomplete.js`
- `shared/Button.js`
- `shared/Close.js`
- `shared/PaneToggle.js`
- `shared/Dropdown.js`

**Comment by arthur801031** [comment]
I'll take the following:
- `shared/ObjectInspector.js`
- `shared/Rep.js`
- `shared/Svg.js`
- `shared/Menu.js`
- `Editor/index.js`
