### ISSUE TITLE
Remove CSS transition in Breakpoint for performance issue when disabling/enabling many breakpoints

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#1912]
**Steps to Reproduce**
1. Start Nightly
2. Navigate to "https://www.mozilla.org/en-US/contribute/"
3. Open debugger (Ctrl+Shift+S)
4. Select source www.mozilla.org > media/js > common-bundle.****.js
5. Add some breakpoints (e.g. 5 breakpoints on line 4, 7, 10, 13, 16)
6. Switching Disable breakpoints and Enable breakpoints...

**Actual Results**
Switching disable/enable breakpoints is too slow.

**Expected Results**
Switching disable/enable breakpoints is quickly. No longer need any CSS transitions.

![debugger-breakpoints](https://cloud.githubusercontent.com/assets/13914314/22576365/5e833d2e-e9fe-11e6-8be4-8902b4e250de.png)

**Comment by clarkbw** [comment]
> No longer need any CSS transitions.

Which transition did you remove?

**Comment by clarkbw** [comment]
I'm seeing this run slowly but its not clear to me yet that the transition is to blame.

**Comment by jasonLaster** [comment]
Hmm, i'm not seeing the slowness after the new bundle.

Happy to re-open if you still see it.

![](http://g.recordit.co/SB48fwi1ph.gif)
