### ISSUE TITLE
[Docs] Customize theme

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1921]
We are currently using `Cayman` as the GH Page Theme, which has great defaults but lacks a distinct look and feel.

It would be awesome to fork Cayman and add our own branding. A good place to start would be on the homepage and on a docs page.

### Homepage

- [ ] Better Header block
- [ ] Better value summary
- [ ] Secondary content 

### Docs

- [ ] A better navbar
- [ ] A better table of contents

Here are some screenshots to give you a rough idea of what I have in mind. Ofcourse, we should iterate on it :)

#### Homepage

![homepage](https://cloud.githubusercontent.com/assets/254562/22604485/cf879d6a-ea19-11e6-8f18-86e7fdcf5ac1.jpg)

#### Docs Page

![docs page](https://cloud.githubusercontent.com/assets/254562/22604486/cf8808f4-ea19-11e6-9a40-2c24ac1ed259.jpg)

#### Brownie Points

🍪 This is a really important issue that we would love to have, but simply don't have the time to do. If you're interested reach out to @jasonLaster.

**Comment by mateusortiz** [comment]
I want trying helping on this issue 😃

**Comment by clarkbw** [comment]
Hi @mateusortiz let me know how I can help here.  I was just reviewing this today.

**Comment by codehag** [comment]
I am closing this and adding it to our feature backlog
