### ISSUE TITLE
[docs] links to local development

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1922]
It looks like the links to local development from contributing are currently broken.

https://devtools-html.github.io/debugger.html/CONTRIBUTING.html#local-development-computer

https://devtools-html.github.io/debugger.html/docs/local-development.html#internationalization

**Comment by irfanhudda** [comment]
The version of `jekyll-relative-links` used by `pages-gem` does not support links with fragments e.g. `[test](somefile.md#fragment)`. This should start working when `pages-gem` updates `jekyll-relative-links` version in its dependencies.

**Comment by irfanhudda** [comment]
@jasonLaster This can be closed now. Links on [https://devtools-html.github.io/debugger.html/CONTRIBUTING.html#local-development-computer](https://devtools-html.github.io/debugger.html/CONTRIBUTING.html#local-development-computer) page are now working.
