### ISSUE TITLE
[Windows]  source-map unit tests fail

### ISSUE THREAD

**Issue by Garbee** [devtools-html/debugger.html#1925]
`@princiya` brought this to my attention in Slack... She was getting timeout errors on the tests for sourcemaps in the *CLI* on Windows but not in the web mocha runner. So I tested both on my Linux system, all clear in CLI but Mocha on the web view fails on `should add a breakpoint with the same error.

It looks like any given test could end up flaky based on the timeout depending on what the hardware, OS, and other factors of the machine are. I'm not sure if we should increase the timeout, since we do want to verify things are completed in a timely manner. This should at least be documented somehow, and a fix so the flakyness doesn't occur investigated to see if there is a viable solution.

**Comment by jasonLaster** [comment]
Lets try and isolate the problem a bit. My guess is that it is likely tests that use a worker like the `sourcemap` test.

Perhaps we should try running the unit tests 100 times and see if we can find any patterns?

**Comment by jasonLaster** [comment]
We moved the test to the source map library. Now it's fine.
