### ISSUE TITLE
Fix text wrap in dropdown li

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#1941]
**Steps to Reproduce**
1. Go to "https://www.mozilla.org/en-US/contribute/"
2. Select some sources until dropdown is visible
3. Open dropdown

**Actual Results**
File name is wrapped.

**Expected Results**
File name is not wrapped.

![fix-text-wrap-in-dropdown-li](https://cloud.githubusercontent.com/assets/13914314/22631300/4d80ae20-ec4d-11e6-8501-f9413fd6ad4a.png)

**Comment by jasonLaster** [comment]
We chose to use an elipsis, which indicates the value was truncated. We can re-evaluate this later when we look at other dropdowns and search results.
