### ISSUE TITLE
Fix label position in menuitem

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#1942]
**Steps to Reproduce**
1. Go to any sites (e.g. "about:home")
2. Select any sources
3. Right click on tab
4. Check context menu items

**Actual Results**
Label position begin on the far left.

**Expected Results**
Label position begin after menu-iconic-left. 

![fix-label-position-in-menuitem](https://cloud.githubusercontent.com/assets/13914314/22631516/32634c24-ec52-11e6-9e11-7cc6b7da0145.png)

**Comment by clarkbw** [comment]
This must be on windows. This is similar to another windows issue about a line through the items. I think we have an issue with the shim that's handling the context menu for windows.

**Comment by jasonLaster** [comment]
@clarkbw is this something for any context menu in windows? if so we should refile in bugzilla?

**Comment by nt1m** [comment]
@jasonLaster Only for the new debugger.

**Comment by nt1m** [comment]
Two possible fixes here:
- Import chrome://global/skin/menu.css when isFirefoxPanel is true (the CSS file is only imported automatically for XUL documents)
- Append the menu in the parent doc (toolbox) which should have the CSS file, when isFirefoxPanel is true

**Comment by jasonLaster** [comment]
I looked into a bit and while the padding is off, it does not affect any of the other default styling. I'm going to move it off this current sprint as I don't think it should block our launch criteria.

Hopefully, I'll get my windows development environment setup soon though and can do this as I do think we should get the default styling.

**Comment by nt1m** [comment]
I looked a bit at this, and it seems like what I said in my previous comment might be wrong. When inspecting the menupopup, I see that all menuitems have .menu-text as their child, but the debugger menu doesn't seem to have .menu-text.


Debugger menu:
```
<menuitem>Foo</menuitem>
```
Other menus:
```
<menuitem>
  <xul:box class="menu-text">Foo</xul:box>
</menuitem>
```

**Comment by jasonLaster** [comment]
Fixed! Thanks for your patience @magicp-github :)
