### ISSUE TITLE
[lint] Add markdown linting

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1944]
Babel uses [remark] for markdown linting, which is a huge win. It can check for spacing, links, and other consistency issues with our MD files. My favorite piece is that [validate-links][rmv] will check our links to see if they work.

[branch]

[branch]: https://github.com/devtools-html/debugger.html/compare/remark
[remark]: https://github.com/wooorm/remark-lint
[rmv]: https://github.com/wooorm/remark-validate-links

**Comment by clarkbw** [comment]
👍

**Comment by clarkbw** [comment]
FYI, I've added remark to the [RFCs](https://github.com/devtools-html/rfcs/) repository here: https://github.com/devtools-html/rfcs/pull/10 and I think its going to work out well.

**Comment by irfanhudda** [comment]
We can add more rules to `.remarkrc`. My suggestion is using this 
```json
{
  "presets": ["lint-recommended"],
  "plugins": {
    "lint": {
      "list-item-indent": false,
      "no-unused-definitions": false,
      "no-shortcut-reference-link": false,
      "no-shortcut-reference-image": false
    },
    "validate-links": {
      "repository": ""
    }
  }
}
```

Running `yarn run lint-md` after this gives 13 warning.
