### ISSUE TITLE
[Editor] Pause Line color

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1948]
We currently show pause lines as green, which is slightly un-intuitive as green is associated with going.

It might me nice to try yellow or blue, which are also informational colors

![](https://cloud.githubusercontent.com/assets/2134/22579643/a184f3ce-e986-11e6-82e2-b896077aec4a.png)

**Comment by jasonLaster** [comment]
Here are two quick screens that I made for showing the pause line:

I'm personally in favor of light blue although we use blue as it's consistent with chrome and we use blue in other places in a similar fashion. 

### yellow
![screen shot 2017-02-08 at 3 25 38 pm](https://cloud.githubusercontent.com/assets/254562/22755842/e7b419e8-ee12-11e6-8c64-7192de50eff8.png)

### blue
![screen shot 2017-02-08 at 3 24 26 pm](https://cloud.githubusercontent.com/assets/254562/22755843/e7c31fec-ee12-11e6-9822-74c5fa9be16c.png)

Lets not make a decision right away. curious to see what people think

**Comment by darkwing** [comment]
I love both, but the to me, the yellow is a better signal of "pause"; i.e. a yellow light, caution sign, etc.

**Comment by darkwing** [comment]
Tweeted out from the Chrome Twitter account today:  

![c4labclvyaehglm](https://cloud.githubusercontent.com/assets/46655/22942002/4cd1ff72-f2ad-11e6-9908-877b6bcb92b1.png)

I really like yellow.

**Comment by clarkbw** [comment]
Lets go with the yellow.  I'd really like to get the WhyPaused component to be a bit lighter in the way Chrome has it because it is a bit too distracting right now.

**Comment by jasonLaster** [comment]
Yep - I definitely agree about the why paused background

Sounds good

**Comment by jasonLaster** [comment]
I think I'm in favor of using a blue line for the pause line and then dropping the background color from why paused and lighting up a pause icon in there.
