### ISSUE TITLE
Right-clicking when the context-menu is displayed should hide the context-menu

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#1952]
STR : 
1. Right click where there should be a debugger context-menu (e.g. a file tab )
2. Right click again

Expected result: The application context menu should be hidden
Actual result: The native context menu is displayed, in addition with the application one (see ⬇ )

![peek 07-02-2017 13-58](https://cloud.githubusercontent.com/assets/578107/22692126/d0818f06-ed3d-11e6-964c-5d289948707f.gif)

**Comment by wldcordeiro** [comment]
I noticed this as well. I'm going to see if I can fix this up @nchevobbe.

To follow expectations for users the right click will close the currently open context menu (and prevent the default to avoid what you see in your gif)

**Comment by jasonLaster** [comment]
@binarybaba is looking at this

**Comment by binarybaba** [comment]
I screwed up with my git. Had to reset hard and stuff. sorry

**Comment by nchevobbe** [comment]
> I screwed up with my git. Had to reset hard and stuff. sorry

Even with reflog ? http://effectif.com/git/recovering-lost-git-commits

**Comment by binarybaba** [comment]
Okay I didn't know reflog. Thank you!
