### ISSUE TITLE
[Editor] highlighting line on reload

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1964]
We currently highlight the previously selected location when we start the debugger. I find that to be somewhat distracting as it's no longer that helpful.

It would be nice to open the previously selected source, but not flash the line.

As a bit of back story, this happens because we store the previously selected location as a `pendinglocation` in prefs. We can use this to open the source, without highlighting the line on reload.

#### Patch

```diff
diff --git a/src/components/Editor/index.js b/src/components/Editor/index.js
index d41d57a..c070c04 100644
--- a/src/components/Editor/index.js
+++ b/src/components/Editor/index.js
@@ -457,6 +457,10 @@ const Editor = React.createClass({
     const line = this.pendingJumpLine;
     this.editor.alignLine(line);

+    // this is where we add the `highlight-line`
+    // I think the closest approximation of what we want to do is to not highlight a line if we don't have a
+    // previously selected location. This would basically mean, don't highlight the first location.
+
```

#### GIF

![](http://g.recordit.co/KXOZjVeSlt.gif)

**Comment by clarkbw** [comment]
I agree this is distracting.  I never understood what it was for until just now when I read this.  I don't think my selected location is actually that useful assuming you open me to the same file and same location I don't think you need to highlight the exact line.

**Comment by jbhoosreddy** [comment]
Something like this is probably what we need to do.

```diff
diff --git a/src/components/Editor/index.js b/src/components/Editor/index.js
index 212560f..21d3af1 100644
--- a/src/components/Editor/index.js
+++ b/src/components/Editor/index.js
@@ -485,8 +485,9 @@ const Editor = React.createClass({
     // We only want to do the flashing animation if it's not a debug
     // line, which has it's own styling.
     if (
-      !this.props.selectedFrame ||
-      this.props.selectedFrame.location.line !== line
+      this.lastJumpLine &&
+      (!this.props.selectedFrame ||
+      this.props.selectedFrame.location.line !== line)
     ) {
       this.editor.codeMirror.addLineClass(line - 1, "line", "highlight-line");
     }
```
