### ISSUE TITLE
watch expressions variables don't expand

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1970]
When trying to expand a variable in the watch expressions list it seems to expand inline and then from there I'm not sure.  I was expecting it to work exactly like the scopes list.

http://recordit.co/EWErz5MCQF

![screen shot 2017-02-08 at 4 05 48 pm](https://cloud.githubusercontent.com/assets/2134/22763253/7dacd6d8-ee18-11e6-96e8-00f46ad31d0f.png)

**Comment by arthur801031** [comment]
I'll take a stab at this :)
