### ISSUE TITLE
[panel] new-breakpoint is gone when switching devtools-tab

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#1982]
**Steps to reproduce**
1. Go to any sites (e.g. about:home)
2. Select any sources (e.g. chrome://browser/content/contentSearchUI.js)
3. Add new breakpoint (e.g. on line 9)
4. Switch devtools tab to "Style Editor"
5. Go back to "Debugger" tab
6. Confirm breakpoint mark on line number

**Actual Results**
.new-breakpoint is gone when switching devtools-tab. After that, it will be appeared if click source tab.

**Expected Results**
.new-breakpoint is not gone, even if switching devtools-tab.

![breakpoint-is-gone-when-switching-devtools-tab](https://cloud.githubusercontent.com/assets/13914314/22809570/bd25c040-ef76-11e6-823a-18d0ef5cd0df.gif)

**Comment by jasonLaster** [comment]
Thanks for filing @magicp-github

**Comment by jasonLaster** [comment]
I believe this is due to a larger issue, which is that we don't persist breakpoints across debugging sessions.

I'll look into doing this in a separate issue and we can see if it fixes it.

**Comment by jasonLaster** [comment]
This is now fixed thanks to @arthur801031's work persisting breakpoints!

![](http://g.recordit.co/ovUxD7WXG9.gif)
