### ISSUE TITLE
togglePanes collapse/expands opposite pane in the Dev Edition in RTL locales

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#1986]
**Steps to reproduce**
1. Start Dev Edition in Arabic
2. Open Debugger
3. Click togglePanes

**Actual Results**
togglePanes collapse/expands opposite pane.

**Expected Results**
togglePanes collapse/expands pane on the same side, even if in RTL locales.

![togglepanes-collapse-expands-oposite-pane-in-dev-edition-in-rtl-locales](https://cloud.githubusercontent.com/assets/13914314/22821925/8d56f204-efc0-11e6-86f0-8ad22af195c2.gif)

**Comment by magicp-github** [comment]
This bug reproduce in Dev. Edition. It works fine in Nightly.

**Comment by jasonLaster** [comment]
Closing this as it works fine locally:

@wldcordeiro, @Garbee do you remember when we fixed this?

![](http://g.recordit.co/0z15SUQtOc.gif)

**Comment by wldcordeiro** [comment]
@jasonLaster I think it was fixed with the vertical layout work and some follow-up LTR/RTL work.
