### ISSUE TITLE
object inspector doesn't distinguish ordinary entries from "special" ones

### ISSUE THREAD

**Issue by tromey** [devtools-html/debugger.html#2012]
The debugger will sometimes insert special entries into a scope in the object inspector, like "<exception>" or "<return>".  In the old debugger these were visually different from ordinary entries; but in the new debugger the two appear exactly the same.

**Comment by jasonLaster** [comment]
@tromey mind providing an STR and perhaps a screenshot of what it looks like nwo

**Comment by tromey** [comment]
I couldn't get github to linkify this test URL, but here you go: data:text/html;base64,PHNjcmlwdD4KICBmdW5jdGlvbiBmKCkgewogICAgICBsZXQgeCA9IHsiPHJldHVybj4iOiA1fTsKICAgICAgcmV0dXJuIHg7CiAgfQo8L3NjcmlwdD4KPGJvZHkgb25jbGljaz0iZigpIj5DbGljayBtZTwvYm9keT4K

Open this page, then open the debugger.  Set a breakpoint on the return from `f`.  Then click the text.  When the debugger stops at the breakpoint, step over until the function is returning a value.  Expand the "<return>" object.  I get this:

![image](https://cloud.githubusercontent.com/assets/1557670/23221984/bbb6a42e-f8e3-11e6-8dd9-88cc37688edb.png)

There's no visual distinction between the two "<return>"s, but I think there should be.

**Comment by jasonLaster** [comment]
Here's the html for the record:

```html
<script>
  function f() {
      let x = {"<return>": 5};
      return x;
  }
</script>
<body onclick="f()">Click me</body>
```

haha - this is such an edge case :)

**Comment by tromey** [comment]
One further problem here is that for a Proxy it's impossible to tell that the properties are synthesized, because they are synthesized on the server and there's no indication of this.  I'll file a bug about this in bugzilla.

**Comment by tromey** [comment]
I spoke too soon, maybe we can check object.class==="Proxy".

**Comment by tromey** [comment]
In addition to Proxy and <return> there are also some synthetic properties in Promise.

**Comment by jasonLaster** [comment]
closing this for now as it's a low priority. We can always re-open if it is an issue
