### ISSUE TITLE
Hidden tabs not shown when clicked from the tree-node

### ISSUE THREAD

**Issue by princiya** [devtools-html/debugger.html#2015]
### Bug

![hidden-tab-not-shown](https://cloud.githubusercontent.com/assets/8022693/22908534/5a676b6c-f24f-11e6-82f6-d80363fcc749.gif)

STR:

Suppose a tab is hidden, if you try to access the same file from the left side-bar (tree-node), the tab doesn't up.

**Comment by wldcordeiro** [comment]
I wonder what the expected behavior is here. In Atom and Sublime does opening something from the file tree while having enough files open to trigger an overflow menu put them in the overflow or as left/right-most tab?

**Comment by clarkbw** [comment]
I think the chrome devtools tab behaviour could be pretty good here. They swap out the last tab with the selected tab. Try it for yourself by side docking chrome devtools and squishing the tabs, then choose a hidden tab.

**Comment by wldcordeiro** [comment]
@clarkbw last tab here being the right most visible tab? Or the current active one?

**Comment by jasonLaster** [comment]
yeah, i'd be happy with either first or last tab. Also, noticing that atom doesn't even bother with the dropdown, which is kind of nice

**Comment by clarkbw** [comment]
I think it's the end tab in RTL parlance 🙂

**Comment by jasonLaster** [comment]
Here's an approach I think would work

```diff
diff --git a/src/components/Editor/Tabs.js b/src/components/Editor/Tabs.js
index 7b139e5..baaa6ae 100644
--- a/src/components/Editor/Tabs.js
+++ b/src/components/Editor/Tabs.js
@@ -253,10 +253,20 @@ class SourceTabs extends Component {
       return;
     }

-    const sourceTabs = this.props.sourceTabs;
+    const { sourceTabs, selectedSource } = this.props;
     const sourceTabEls = this.refs.sourceTabs.children;
     const hiddenSourceTabs = getHiddenTabs(sourceTabs, sourceTabEls);

+    // if the selectedSource is in the hidden tabs list
+    // then figure out how to show it in the list of tabs
+    // naively, find the last shown tab and place it before that tab
+    // the challenge is if the selected source is wider than that tab.
+    // in that case we need to try placing it befor the next available tab
+
+    // when we find the location to place the tab
+    // we should fire a new action (updateSourceTabs), which will set the
+    // new tabs list in the redux store
+
     this.setState({ hiddenSourceTabs });
   }
```

**Comment by jasonLaster** [comment]
@princiya is working on this
