### ISSUE TITLE
[DOCS] remove permalink from the readme

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2024]
We currently show the jekyll info in the readme. We should see if there is a way to hide this if it's possible. 

<img width="1266" alt="screen shot 2017-02-14 at 2 57 45 pm" src="https://cloud.githubusercontent.com/assets/254562/22946717/33ff7dc6-f2c6-11e6-842d-3fa2b1ffad0f.png">

**Comment by ThomasCrevoisier** [comment]
@jasonLaster I'm not sure if we can hide those data without adding some file processing.
Don't know Jekyll a lot, but could we include other markdown files ? 

We could have something like :
```
README.md
site.md
```

And in `site.md` we would have : 
```
---
title: ...
permalink: ...
---

// Include the content of README.md
```

**Comment by irfanhudda** [comment]
The reason we have front matter here is to specify the title.

We can remove front matter if move badges below the title.

**Comment by jasonLaster** [comment]
Oh neat. Let's move the badges down :)

**Comment by irfanhudda** [comment]
@jasonLaster I'll create a pull request then.
