### ISSUE TITLE
Splitter measures mouse position when devtools is docked to the right

### ISSUE THREAD

**Issue by joewalker** [devtools-html/debugger.html#2027]
STR:

* Open the new debugger
* Dock devtools to the right of the page
* Re-position either splitter

Expected: It moves normally

Actual: You need to move the mouse cursor a long way to the left of the screen to make the splitter move. Presumably the math is done based on the browser window left edge rather than the devtools window left edge. When docked to the bottom, they're the same.

**Comment by wldcordeiro** [comment]
Thanks for the report @joewalker! I'm not sure if this bug is still present or not in the latest code. What version of Firefox are you on? @jasonLaster if I'm not mistaken the splitbox is in devtools-core and m-c so maybe copying this issue to devtools-core if we verify it's still a problem.

**Comment by joewalker** [comment]
I'm currently running Nightly - 54.0a1 (2017-02-16).

**Comment by jasonLaster** [comment]
Thanks @joewalker. I see this as well. We'll look into it soon

**Comment by julienw** [comment]
> Presumably the math is done based on the browser window left edge rather than the devtools window left edge. 

Indeed :)

https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-modules/client/shared/components/splitter/SplitBox.js#L103-L106

I'm trying to fix this.

**Comment by clarkbw** [comment]
setting this to in progress for @julienw
