### ISSUE TITLE
Show upload size in Network Panel

### ISSUE THREAD

**Issue by zspitzer** [devtools-html/debugger.html#2029]
Steps to reproduce the problem: 
1. open the devtools network panel 
2. upload a file using html file upload

What is the expected behavior? 
The size of the upload to be visible for the individual network request

**Comment by clarkbw** [comment]
Thanks. This issue needs to be filed with the network panel. We only track the debugger in this GitHub repo.

**Comment by zspitzer** [comment]
Where is the network panel, bugzilla or somewhere else on github?

**Comment by juliandescottes** [comment]
@zspitzer you can log bugs for the netmonitor on bugzilla : https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Developer%20Tools%3A%20Netmonitor

**Comment by zspitzer** [comment]
found an existing bug https://bugzilla.mozilla.org/show_bug.cgi?id=1160254
