### ISSUE TITLE
Refresh watch expressions

### ISSUE THREAD

**Issue by hedvaze** [devtools-html/debugger.html#2032]
Display reference error instead of value
<img width="406" alt="screen shot 2017-02-15 at 21 48 19" src="https://cloud.githubusercontent.com/assets/18256531/22992494/86536a08-f3c8-11e6-81f9-0fbbc359cf27.png">

Open at #goodnessSquad event

**Comment by clarkbw** [comment]
Once #2118 lands we can look into this further.

**Comment by bomsy** [comment]
I've been looking into this, can't seem to replicate.

**Comment by bomsy** [comment]
Actually it looks #2118 fixes this as well.
