### ISSUE TITLE
Breakpoints pane close button is not correctly aligned

### ISSUE THREAD

**Issue by irfanhudda** [devtools-html/debugger.html#2056]
### Screenshot
![breakpoint](https://cloud.githubusercontent.com/assets/1755089/23176584/a4a265fc-f889-11e6-9917-d4e3e66a9cd1.gif)

Close button should be aligned to the right side but is currently on left side.

**Comment by jasonLaster** [comment]
@wldcordeiro this is probably similar https://github.com/devtools-html/debugger.html/pull/2043

**Comment by irfanhudda** [comment]
Fixed now
