### ISSUE TITLE
[FunctionSearch] move to SearchBar component

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2066]
The UI is currently rendered in [`Editor/index.js`](https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/index.js#L537)

We should move this to the `Editor/SearchBar` so that it'll be easier to build the search bar bottom bar that toggles function search.

We could also create a new `FunctionSearch` that is used in the SearchBar

https://gist.github.com/jasonLaster/5c56ade66ef6bd81052881d0cd8df04d

**Comment by CodeMacabre** [comment]
@wldcordeiro I'm interested in taking this one on, although I may need a bit of help along the way.

**Comment by wldcordeiro** [comment]
@CodeMacabre I can work with you on this one. 😄 There's some prep work I'll be doing in https://github.com/devtools-html/debugger.html/issues/2078 first to give it a new home.

**Comment by CodeMacabre** [comment]
@wldcordeiro Sounds good. I'm happy to help with #2078 too / instead to help this get underway.

**Comment by wldcordeiro** [comment]
This has been moved, but there's still work to do to make the UI/UX nicer. Starting that now in another PR.
