### ISSUE TITLE
[SourceTabs] Sources Dropdown hidden in RTL

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2075]
We show a tabs dropdown when there are too many source tabs to show. When the debugger is in RTL mode, the dropdown button is on the left and the dropdown is cropped by the left sidebar when it's opened.

We should have the dropdown open to the right of the button in RTL, which would keep it from being cropped.

#### patch

```diff


diff --git a/src/components/shared/Dropdown.css b/src/components/shared/Dropdown.css
index 5e0e481..ab314fb 100644
--- a/src/components/shared/Dropdown.css
+++ b/src/components/shared/Dropdown.css
@@ -4,6 +4,8 @@
   box-shadow: 0 4px 4px 0 var(--theme-search-overlays-semitransparent);
   max-height: 300px;
   position: absolute;
+
+  /* this probably needs to change*/
   offset-inline-end: 8px;
   top: 35px;
   width: 150px;
```

#### Screenshot

![screen shot 2017-02-24 at 6 58 18 pm](https://cloud.githubusercontent.com/assets/254562/23325434/430fba24-fac3-11e6-99aa-f12a45d6ac7c.png)

**Comment by irfanhudda** [comment]
This was working with `postcss-bidirection` `2.0.3`.

**Comment by zystvan** [comment]
I'll take this issue. @wldcordeiro
