### ISSUE TITLE
[EditorSearch] Add search bottom bar

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2078]
This tracks the work needed to add a search bottom bar:

- [x] search modifiers on the bottom right
- [x] function search toggle button bottom left

Notes:
* helen's design called for the search button being a toggle for the bar, but i'm not sure if that is clear enough
* when this is added, we'll want to disable modifiers when doing a function search, but that's also out of scope

### Screenshot
![](https://cloud.githubusercontent.com/assets/254562/22855693/3bc6fe24-f052-11e6-862d-922fa8183bb4.jpg)

**Comment by wldcordeiro** [comment]
The button was added. There is additional work being done to move the function search UI itself into the search bar now and additional refactoring to simplify our two distinct search types project and document.
