### ISSUE TITLE
[Editor] alignLine misreads the start location

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2081]
I've noticed that while searching the editor can occassionally be a bit jumpy. The reason for this is that the editor thinks that the new search result is not visible and centers the result in the middle of the editor.

This is a bug in how we calculate the start and last visible line of the document: [here](https://github.com/devtools-html/debugger.html/blob/master/src/utils/editor/source-editor.js#L96-L97)

Here are some screenshots of searching where the match is visible, but codemirror thinks it's not:

One other thought, this is likely CSS and could work on firefox, but fail on chrome

#### search

![screen shot 2017-02-22 at 4 50 55 pm](https://cloud.githubusercontent.com/assets/254562/23234264/847c3578-f91f-11e6-8078-f19037503099.png)

#### alignLine

![screen shot 2017-02-22 at 4 51 04 pm](https://cloud.githubusercontent.com/assets/254562/23234269/8989311a-f91f-11e6-98b7-7c471ecdf564.png)

**Comment by rrandom** [comment]
Hi, @jasonLaster , I found that set `"viewportMargin": Infinity`  when create the editor instance will fix this.  But it's not recommend by Codemirror https://codemirror.net/doc/manual.html#option_viewportMargin

**Comment by jasonLaster** [comment]
Hmm nice find. Let's see if that fixes it. The problem is in chrome but not
Firefox

**Comment by jasonLaster** [comment]
I think this is fixed by https://github.com/devtools-html/devtools-core/pull/515
