### ISSUE TITLE
[Sources] selection highlight should be full width

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2082]
The sources highlight is no longer 100% width of the source sidebar pane

#### patch

```diff
diff --git a/src/components/shared/ManagedTree.css b/src/components/shared/ManagedTree.css
index bea3344..2907f11 100644
--- a/src/components/shared/ManagedTree.css
+++ b/src/components/shared/ManagedTree.css
@@ -19,6 +19,7 @@
   cursor: pointer;
 }

+/* here */
 .tree .node.focused {
   color: white;
   background-color: var(--theme-selection-background);
```

#### Screenshot

![Screen Shot 2017-02-22 at 5.02.08 PM.png](https://shipusercontent.com/8621c2281bb283614599105d96b57e86/Screen%20Shot%202017-02-22%20at%205.02.08%20PM.png)

**Comment by rrandom** [comment]
I will take this.

**Comment by jasonLaster** [comment]
Thanks!

**Comment by jasonLaster** [comment]
Hey @irfanhudda what's your timeline here?

**Comment by irfanhudda** [comment]
@jasonLaster I can file a PR for this by today.

@rrandom Do you mind if I take this?

**Comment by rrandom** [comment]
@irfanhudda Ok, take it

**Comment by jasonLaster** [comment]
sorry @rrandom. I got confused :)

**Comment by rrandom** [comment]
@jasonLaster  Never mind :)

**Comment by irfanhudda** [comment]
@rrandom Thanks.
