### ISSUE TITLE
[Call Stack] The frame location is greyed out on hover

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2083]
We recently changed how we handle hover and focus states in the call stack. One of the unintended consequences is that the frame source location color is now white on grey which looks bad. We should remove that style, so that it doesn't change on focus or hover.

Look [here](https://github.com/devtools-html/debugger.html/blob/master/src/components/SecondaryPanes/Frames.css#L49-L54) for the fix.

![](http://g.recordit.co/UQbwQr4RVO.gif)

**Comment by jcreighton** [comment]
I think this would be great for my first contribution. Please assign me 😄

**Comment by clarkbw** [comment]
@jcreighton its all yours!

**Comment by clarkbw** [comment]
(github doesn't allow us to assign anyone not in the org to an issue, but its labeled `in progress` so it is yours)

**Comment by jcreighton** [comment]
@clarkbw 👍  Thank you!

**Comment by jasonLaster** [comment]
Hey @jcreighton when do you think you'll be able to work on it?

**Comment by jcreighton** [comment]
@jasonLaster Worked on it last night, just opened a PR
