### ISSUE TITLE
Persist Call Stack accordion opened/closed state

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#2093]
With Nightly 54.0a1 (2017-02-22) (64-bit).

STR:
1. Have a few breakpoints
2. F8 through them to look at the Scope variables
3. Close "Call Stack" accordion

![call_stack_not_persisted](https://cloud.githubusercontent.com/assets/3307404/23256502/04d5b1fe-f9c0-11e6-94e8-84fb2c359dad.gif)

ER:
Keep Call Stack closed

AR:
Wheneven a breakpoint is hit again, then the Call Stack automatically reopens. And I have to close it again.

I saw that there are many closed issues about persisting the open/closed state, so maybe it's a regression.

**Comment by clarkbw** [comment]
I think this was fixed in #1545 but hasn't landed in nightly yet?

**Comment by jasonLaster** [comment]
likely

**Comment by clarkbw** [comment]
Landing in Nightly is happening here: https://bugzilla.mozilla.org/show_bug.cgi?id=1338567
