### ISSUE TITLE
[EditorSearch] cmd+f without a selection should refocus the search bar

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2103]

**Comment by aklt** [comment]
I;ll have a go at this in a few hours

**Comment by jasonLaster** [comment]
@aklt curious to see what you think when you have a chance. It'd be neat if this *just* works now

**Comment by aklt** [comment]
Hi Jason, I was expecting the previous search text to reappear in the search bar if I reopen it after having closed it previously as I think we talked about on slack.  That does not happen, but the search bar is refocused :)

**Comment by jasonLaster** [comment]
Ahh. We should fix that :)

**Comment by aklt** [comment]
Should I make an issue on it?

**Comment by jasonLaster** [comment]
@aklt lets fix it in this issue

**Comment by aklt** [comment]
This should be fixed now.
