### ISSUE TITLE
[EditorSearch] escape should always close the search bar

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2104]

**Comment by nchevobbe** [comment]
I will have a look at this

**Comment by nchevobbe** [comment]
Hey @jasonLaster , do you have a STR describing how hitting escape would *not* close the search bar ? It seems to work well for me in any case :/

**Comment by jasonLaster** [comment]
yep - you have to click away from the search bar

**Comment by nchevobbe** [comment]
So the only problem I see is when I make the search input lose its focus by clicking in the editor. If I click on anywhere but the editor, the search bar loses focus, but pressing escape works as expected.
Back to the editor issue. The problem is that we have a `keydown` listener on it 
```js
    this.editor.codeMirror.getWrapperElement()
      .addEventListener("keydown", e => onKeyDown(this.editor.codeMirror, e));
```
The `onKeyDown` function comes from `src/utils/editor/index.js`, and looks like : 
```js
function onKeyDown(codeMirror, e) {
[...]
  if (key === "Escape" && target == textArea) {
    e.stopPropagation();
    e.preventDefault();
    codeWrapper.focus();
  } [...]
}
``

The key part here is the `e.stopPropagation();` which prevent the regular handling of the Esc key to be called.
Removing the `stopPropagation` call fixes this issue, but I'm afraid it could have side effects.

This event handler was added in https://github.com/devtools-html/debugger.html/commit/71360324aed48f8978ef00520596b7f40c46fb72 , in order to be able to navigate out of the editor. I think some of the logic from this handler could be moved to `editor/index.js` , where we have a listener for the esc keydown too.

**Comment by jasonLaster** [comment]
hmm, i've been worried about the *many* uses of escape for some time.

Perhaps we have one top level escape handler that can do:

1. refocus on codewrapper
2. close search bars...

**Comment by jasonLaster** [comment]
This is fairly complicated and the UX is not clear, so closing it for the time being.
