### ISSUE TITLE
[FunctionSearch] support scrolling the list of results

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2106]
If you open function search and search a file that has lots of results, you'll notice it doesn't scroll. 

The problem is in Autocmplete, but i think we can re-write it to be better

### getting started

1. enable functionSearch
2. open a source and press cmd+shift+o

**Comment by jasonLaster** [comment]
We currently scroll the list in a [manual] fashion. We'd like to use [scrollIntView]

[scrollIntoView]: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView
[manual]: https://github.com/devtools-html/debugger.html/blob/master/src/components/shared/Autocomplete.js#L51-L66

**Comment by arthur801031** [comment]
I'll take a stab at this.

**Comment by jasonLaster** [comment]
@arthur801031 taking your name off it because you've got two other issues
