### ISSUE TITLE
Yarn start shows a warning about mocha

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2117]
`yarn start` shows this warning which we should suppress because it can be confusing

thanks @codemacabre for reporting

![image](https://cloud.githubusercontent.com/assets/254562/23282775/d1e2e542-f9f0-11e6-9559-ba8fc7fdb7d6.png)

**Comment by clarkbw** [comment]
We get a lot of reports about this, lets try to figure out a solution to at least mute this warning, if not fix it.

**Comment by juliandescottes** [comment]
Should be able to handle that using the `module.noParse` webpack config (https://webpack.github.io/docs/configuration.html#module-noparse)
