### ISSUE TITLE
veritcally align watch expressions placeholder

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#2123]
Coming from #2107

![screen shot 2017-02-23 at 9 01 07 am](https://cloud.githubusercontent.com/assets/2134/23269814/a5ac69c0-f9a6-11e6-9b5a-9f33c892e935.png)

@zystvan is taking this one on!

**Comment by wldcordeiro** [comment]
Self-assigning so I know to track it for mentoring.

**Comment by wldcordeiro** [comment]
Thanks @zystvan for the work! Looks great and makes our secondary panes more consistent.
