### ISSUE TITLE
[FunctionSearch] move function declarations out of editor state and to the util

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#2124]
Breaking this out of #2007

**Comment by jasonLaster** [comment]
@wldcordeiro marking this as yours as it's close to your work. it's mostly just blocked...

**Comment by jasonLaster** [comment]
If it's a shortcut, it's OK to call the string `.key`, but the localization comment should make it clear it's a shortcut.

If it's an accesskey, it should be called `correspondinglabel.accesskey`

::: devtools/client/locales/en-US/debugger.properties
@@ +19,5 @@
> +copySourceUrl=Copy Source Url
> +
> +# LOCALIZATION NOTE (copySourceUrl.key): Access key to copy the source URL of a file from
> +# the context menu.
> +copySourceUrl.key=X

**Comment by wldcordeiro** [comment]
I think @jasonLaster landed this in his recent PR.
