### ISSUE TITLE
[EditorSearch] move search state to UI reducer

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#2126]
Breaking this out of  #1930

**Comment by wldcordeiro** [comment]
I'll be working on this, I'm doing a lot with search so to summarize the "waves"

1. [x] Add search bottom bar to house search modifiers and function search
2. [ ] Move function search into search bar
3. [ ] Refactor autocomplete and search bar to reuse components and clean up UI/UX
4. [ ] Move state of editor search including modifiers and function searching into redux.

**Comment by jasonLaster** [comment]
@wldcordeiro lets get more context here so that potentially others could work on it as well
