### ISSUE TITLE
[panel] source search occassionally fails

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2132]
I noticed while testing today that source search occasionally fails in the panel.

### GIF

![](http://g.recordit.co/jDZnnA5oDE.gif)

**Comment by darkwing** [comment]
Could you describe the issue?  I somehow still don't see or understand the issue.

**Comment by jasonLaster** [comment]
hmm, i can't reproduce. it was pretty sad when it failed earlier.

This is probably stale as @wldcordeiro did some work on the result list recently
