### ISSUE TITLE
[tabs] icons are too small

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2141]
@juliandescottes  mentioned in bugzilla that the tab icons look a bit small. I'm not sure if I see it, but i'm very accustomed to them at this point :)

![](https://bug1338567.bmoattachments.org/attachment.cgi?id=8840675)

**Comment by juliandescottes** [comment]
The icons that bother me here are the expand/collapse and plus icons.

The size is maybe not the issue, but they are not aligned with the icons in the sidebar on the right, feels inconsistent. 

I also think we are missing some padding/margin for the expand/collapse icons. They is no breathing space between them and the borders of  the tab panel.

**Comment by jasonLaster** [comment]
> The icons that bother me here are the expand/collapse and plus icons.

This is a hard problem. @princiya and @Garbee worked on vertically aligning the text and buttons. i suppose we can line up command bar buttons too.

> I also think we are missing some padding/margin for the expand/collapse icons. They is no breathing space between them and the borders of the tab panel.

agreed

**Comment by juliandescottes** [comment]
The "dropdown-button" icon also looks a bit too small and not aligned with the others.

<img width="248" alt="image" src="https://cloud.githubusercontent.com/assets/1141550/23451154/09a40e08-fe5f-11e6-9218-dac2df426e27.png">

**Comment by wldcordeiro** [comment]
Agreed. I also think the collapse buttons could have a little bit more breathing room from the border.

**Comment by DanUgelow** [comment]
Going to work on this

**Comment by jasonLaster** [comment]
@DanUgelow how's it going?

**Comment by DanUgelow** [comment]
@jasonLaster still learning my way around everything. It's a bit slow but hoping I can do something in the next day or two
