### ISSUE TITLE
[panel] pause on exceptions button is blue on load

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2148]
![screen shot 2017-02-25 at 6 40 19 pm](https://cloud.githubusercontent.com/assets/254562/23335752/e7a0bb80-fb89-11e6-99b6-0a3b802b1468.png)

**Comment by najamkhn** [comment]
Seems like it persists its last state. There seems to be three states that it cycles around i.e,
* `pause-exceptions enabled`
* `pause-exceptions uncaught enabled`
* `pause-exceptions all enabled`

I tried it with all of them and it seems to just persist the values above. Shouldn't it be the case?

**Comment by jasonLaster** [comment]
sorry, that wasn't clear. This is an issue that only happens when the debugger is in the firefox panel.

I'm working on a fix now, but forgot to mark it in-progress
