### ISSUE TITLE
[panel] dark theme colors 

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#2149]
Follow up to #2131 

![image](https://cloud.githubusercontent.com/assets/1141550/23338323/1237155a-fc08-11e6-998b-fff56c74fb0f.png)

We still have two issues visible in this screenshot, 
- [ ] the source tree icons are almost invisible
- [ ] the source tab close icon is black (for the second source tab, not the selected one)

**Comment by juliandescottes** [comment]
Closing as dupe for #2163

**Comment by jasonLaster** [comment]
oops sorry, i missed this

**Comment by juliandescottes** [comment]
np, your has better screenshots :)
