### ISSUE TITLE
cleanup icons in dark theme

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2163]
- icons in the source tree (almost the same color as the background color)
- close icon in a source tab (black)
- sidebar toggle button is grey, but could be the color of the "new tab" button

#### toggle
![screen shot 2017-02-26 at 4 39 29 pm](https://cloud.githubusercontent.com/assets/254562/23343974/3c9b641a-fc42-11e6-80b2-79e31ed40fd6.png)

#### hovered on inactive tabs
![screen shot 2017-02-26 at 4 39 17 pm](https://cloud.githubusercontent.com/assets/254562/23343975/3cba41c8-fc42-11e6-9da7-f33bfc6a0815.png)

#### icons
![screen shot 2017-02-26 at 4 39 07 pm](https://cloud.githubusercontent.com/assets/254562/23343976/3cbeeb06-fc42-11e6-8662-5d0e22a6e320.png)

**Comment by jcreighton** [comment]
@jasonLaster I see the close button in your screenshot but I'm not seeing those. The close buttons are hidden due to `visibility: hidden;`. Was that on purpose?

**Comment by jasonLaster** [comment]
Yep. Only visible on hover :)

**Comment by jcreighton** [comment]
I'm not seeing it at all -- even on hover:
![close_buttons](https://cloud.githubusercontent.com/assets/5232812/23347143/061d1092-fc6e-11e6-8398-2e860e0e027e.gif)

**Comment by jasonLaster** [comment]
Then that's a bug :)

**Comment by jcreighton** [comment]
@jasonLaster Argh, figured it out. I had to install packages. The CSS wasn't being compiled correctly otherwise. Thanks for being so responsive!
