### ISSUE TITLE
Ctrl/Cmd+F doesn't toggle the searchbar off

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#2173]
Pressing this keyboard shortcut should toggle the searchbar off as well.

**Comment by jasonLaster** [comment]
We actually don't want it to. We want it to set the input value. Try it in atom or sublime :)

**Comment by ThomasCrevoisier** [comment]
@jasonLaster @wldcordeiro If the selection is empty, should we keep the actual value in the search bar ? The actual behavior is that the search bar is empty after pressing Cmd+F again.
