### ISSUE TITLE
object-inspector.js:isDefault mixes host and target properties

### ISSUE THREAD

**Issue by tromey** [devtools-html/debugger.html#2177]
Right now object-inspector.js:isDefault is defined as:

```
if (typeof window == "object") {
  WINDOW_PROPERTIES = Object.getOwnPropertyNames(window);
}
...
function isDefault(item) {
  return WINDOW_PROPERTIES.includes(item.name);
}
```

However, this is testing properties of the debugger host, whereas it ought to check properties of the debuggee.

**Comment by jasonLaster** [comment]
Thanks for filing the issue so we can track this. 

At the moment, I believe this is a low priority because "default" is a UI detail that does not impact the user significantly. Also, I am not sure of a situation where the panel would have a window property that content does not have or vice versa.

**Comment by jasonLaster** [comment]
I'm closing now because I don't see us getting to it in the next month. 

I've added the issue to the [enhancements](https://github.com/devtools-html/debugger.html/projects/5) board, so that it is tracked and can be prioritized in the context of all possible work.
