### ISSUE TITLE
[Stepping] scopes/call-stack flashing while stepping

### ISSUE THREAD

**Issue by tromey** [devtools-html/debugger.html#2180]
When stepping, the scopes and call-stack panes flash.  I think this is fairly distracting.  In the attached screen capture you can see the green "paused" panel disappear, and the "call stack" and "scopes" panes close; then they re-populate when the step finishes.

I think it would be less distracting if the panes remained in place while stepping.  Perhaps the green pane could change colors and text, provided it remained the same size; or maybe these panes could dim and become unclickable while stepping.  The concrete problem I experience with the current approach is that I lose context with the flashing.

I realize that sometimes it makes sense for these things to change.  But even the changes could be a bit gentler -- for instance changes in the call stack could be animated, etc.  If it's necessary to collapse the panes, this could maybe be done after a short delay, in the hope that the step operation would finish before the collapse.

![debug-flash](https://cloud.githubusercontent.com/assets/1557670/23369771/b5aa6f80-fccf-11e6-8455-4f31b2b1a4b2.gif)

**Comment by tromey** [comment]
Darn it, that did not upload correctly.  Will try again.

**Comment by tromey** [comment]
![debug-flash](https://cloud.githubusercontent.com/assets/1557670/23369771/b5aa6f80-fccf-11e6-8455-4f31b2b1a4b2.gif)

**Comment by jasonLaster** [comment]
@tromey flashing is a tough problem we’ve punted on. but I bet we can do something like… not clear the state for half a second and wait to see if we pause again... The tough thing is that darn `resume` event

**Comment by tromey** [comment]
I looked at this a bit today.  Changing the pause reducer and WhyPaused helps; but the Scope pane still flashes, so more work would be required there.

The bigger point here is that this change should depend on the resumption reason: maybe it's ok to keep the panes as-is for a step in/out/over, but a plain resume should probably collapse everything.

Flashing changes in the scope pane (say, when a variable's value changes) should probably be done in a separate bug.

**Comment by clarkbw** [comment]
I wonder if you could do this in CSS?  If you animated (over a second or so) the disappearance of a node you could keep them hanging around while react replaces them.  We just need to ensure that the new thing that replaces the old thing stops the old animation from continuing.

**Comment by jasonLaster** [comment]
This should be easier now because we keep track of the fact that we're currently stepping and that we have an action that fires when we finish stepping. With that said, this not currently a priority, so I'll move it to the enhancements board.

If someone is interested in picking it up, I can share some context.
