### ISSUE TITLE
When viewing a request's query string, multiple parameters with the same name are ignored except for the last occurance

### ISSUE THREAD

**Issue by emceeaich** [devtools-html/debugger.html#2193]
Steps to reproduce:

* Go to https://emceeaich.github.io/triage-report/
* Hit F12 or right-click to inspect element 
* Go to Network tab to inspect one of the XHR tagged requests
* Note that the request includes `&product=Core&product=Firefox&product=Firefox for Android&product=Firefox for iOS&product=Toolkit` in the query string
* Click on `Params` tab
* Observe there's only one `component` parameter, `Toolkit`, listed in that tab

![screen shot 2017-02-27 at 5 37 02 pm](https://cloud.githubusercontent.com/assets/10146300/23387750/665aa8d4-fd13-11e6-8e02-3eaf93111f57.png)

Expected result

* a `component` parameter for each occurrence in the query string

Version: Nightly 54.0a1 (2017-02-23) (64-bit) MacOS

**Comment by wldcordeiro** [comment]
Huh, thanks for the report. But this is the debugger project, I believe you would want to report on [bugzilla](https://bugzilla.mozilla.org/).

**Comment by emceeaich** [comment]
Sorry for the confusion, will refile in the right place. Do we have a spot on the mozilla wiki where we point out where to file which bug where?

**Comment by emceeaich** [comment]
Closing, filed bug against Firefox: Developer Tools: Netmonitor as https://bugzilla.mozilla.org/show_bug.cgi?id=1343122
