### ISSUE TITLE
[EditorPreview] Preview Member Expressions

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2219]
It'd be nice to be able to hover on `b` of `obj.a.b` and preview the expression `obj.a.b`.

once we have the expression, we need to be able to be able to call `client.evaluate(expression, frameId)` and show the response in the popup.

https://astexplorer.net/#/gist/a3801b36d67b0d11b18898649e23eb04/e352a873fdf5b1736daf77dca9e56d70d564efa4

**Comment by bomsy** [comment]
i'll poke at this

**Comment by jasonLaster** [comment]
Here's a checklist for progress:
- [ ] parse member expressions #2297
- [ ] evaluate expressions
- [ ] parse member expressions in `getSymbols` so it's fast
