### ISSUE TITLE
[EditorPreview] Preview variables from outer scopes

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2220]
It would be nice to be able to hover on variables that come from outer scopes and show them in the preview.

We can do this by getting the scope chain out of pauseData and getting all of the binding variables.

**Comment by jasonLaster** [comment]
here's a [branch](https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:vars-in-scope?expand=1) I started to help get started. 

There's an interesting question where we call `variablesInScope`, perhaps it's a selector in the pause reducer...

**Comment by julienw** [comment]
Clearing because I'll be in PTO. Feel free to merge or reuse my patch :)
