### ISSUE TITLE
React DevTools causes sources to be empty on debugger-examples

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#2231]
When the page has no sources, the current source tree is empty:

<img width="1002" alt="image" src="https://cloud.githubusercontent.com/assets/1141550/23451730/8321854c-fe61-11e6-8a8d-5ee6a73b116d.png">

It would be nice if we could have a message stating that there are no sources. When I saw this UI, I thought there was a bug in the debugger which prevented from listing sources!

The old firefox debugger used to show a message in this case:
<img width="371" alt="image" src="https://cloud.githubusercontent.com/assets/1141550/23451798/c942ec46-fe61-11e6-8a3f-c57dd6ddff9d.png">

**Comment by wldcordeiro** [comment]
Hmm how are there now sources at all? Like shouldn't we have at minimum the index file? Even if it has no scripts in it. I swear that's the behavior Chrome and the old debugger have.

**Comment by juliandescottes** [comment]
I agree it's weird, I didn't look into more details. The test url is https://devtools-html.github.io/debugger-examples/

**Comment by juliandescottes** [comment]
So it looks like a regression. 

I don't have the issue when using the current Nightly, but I do when trying out the new bundle currently attached to https://bugzilla.mozilla.org/show_bug.cgi?id=1338567

I also have the issue when testing the project from Github. So probably introduced in the last month or so.

**Comment by jasonLaster** [comment]
Agreed. 

One style point, it would be nice to update the other "Not Paused" styles to be the softer color like this one

[no-sources.pdf](https://shipusercontent.com/60b45d6af7069341d7bfe464c49a9e97/no-sources.pdf)

**Comment by juliandescottes** [comment]
I investigated a bit more and this is actually a very weird bug.

> I don't have the issue when using the current Nightly, but I do when trying out the new bundle currently attached to https://bugzilla.mozilla.org/show_bug.cgi?id=1338567

But it's not a regression of the new bundle, the difference comes from the addons I have installed in Nightly.

![debugger_react_devtools_bug](https://cloud.githubusercontent.com/assets/1141550/23459223/b1c70ab6-fe7f-11e6-8a95-40d3f87efd77.gif)

It looks like having installed the "React devtools" addon on the debuggee allows the debugger to see the index of the page!?

**Comment by jasonLaster** [comment]
hmm, this must be a server bug then if the debugger is not getting the newSource events.

**Comment by jasonLaster** [comment]
I'm closing now because I don't see us getting to it in the next month. 

I've added the issue to the [enhancements](https://github.com/devtools-html/debugger.html/projects/5) board, so that it is tracked and can be prioritized in the context of all possible work.
