### ISSUE TITLE
Fix missing CSS variables not found in variables.css

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#2232]
The following CSS variables are not defined anywhere:
- `--theme-faded-tab-color`
- `--theme-toolbar-background-alt`

They are used in some CSS files but are missing from both the variables.css defined in devtools-core and in the one found in mozilla-central.
 
They were initially introduced in https://github.com/devtools-html/debugger.html/commit/9c498c2c83e7562909132883e12578a9b45fc295

We can either reintroduce the variables or remove their usage.

**Comment by juliandescottes** [comment]
Actually --theme-toolbar-background-alt is present in devtools-core version of variables.css, but missing in mozilla-central.

**Comment by jasonLaster** [comment]
Lets replace this `--theme-faded-tab-color` variable with something available. and sync `--theme-toolbar-background-alt` when we do the next bundle

**Comment by jasonLaster** [comment]
The fix was merged in m-c

**Comment by jasonLaster** [comment]
@juliandescottes hmm where is this at :)

it looks like it might be doneish?

**Comment by clarkbw** [comment]
done now?

**Comment by jasonLaster** [comment]
we can re-open if we need to sync a variable
