### ISSUE TITLE
isBucket is confused by objects with matching names

### ISSUE THREAD

**Issue by tromey** [devtools-html/debugger.html#2239]
You can confuse the bucketing code by writing a test case like:

```js
function f() {
  return {bucket53: "WAT"};
}
```

I think the `isBucket` approach of matching based on names is flawed; instead if something is a bucket, this ought to be a special property somewhere in the model.

**Comment by jasonLaster** [comment]
I'd like to see if we can keep the simple data structure for now, which off the top of my head probably means keeping this edge case. Perhaps we can improve it slightly by renaming the key "<bucket53>"... this would reduce the likeliness significantly. but in a world of sha1 collisions, who knows...

**Comment by tromey** [comment]
I found this by inspection, not with real code.  So keeping the "bucket" name is probably fine, as names go.  The problem is that any choice of name will result in some object being uninspectable, because this code is conflating host and target properties.

**Comment by jasonLaster** [comment]
yeah - i feel like we're writing embedded CSS all over again :P 

`my-really-long-prefix-selector`

**Comment by jasonLaster** [comment]
I think the solution should be to update the path to be `<bucket-##>` which is pretty unique

**Comment by tromey** [comment]
So, IMO there is no point to changing the name.  The current name is unusual enough.  If you do change it, though, we'll just need a new bug for the new name, because the underlying problem will remain.

**Comment by jasonLaster** [comment]
Closing this as it's not a high priority at the moment. We can revisit when the Object Inspector is in reps and it is shipped by default.
