### ISSUE TITLE
[FunctionSearch] Result List Max height

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2240]
It'd be nice to have a max height on the result list so only 6~7 items showed. This would always give us vertical space for showing the source.

![Screen Shot 2017-03-01 at 10.31.36 AM.png](https://shipusercontent.com/d524291fbc378175e7ede9fe693fd637/Screen%20Shot%202017-03-01%20at%2010.31.36%20AM.png)

**Comment by wldcordeiro** [comment]
I could have sworn I set a max height for this. 🤔 

https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/SearchBar.css#L111

**Comment by AlanCezarAraujo** [comment]
I'm starting to work on it.
