### ISSUE TITLE
[docs] Add a roadmap doc

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2241]
It's helpful for the community to be able to learn what our roadmap is:

1. what we're working on
2. what we plan to work on over the next 3 - 6 months, year...

This helps in a couple ways:

1. they can weigh in on it
2. they can put feature requests in context
3. they can see if we plan on working on that thing they want... (watch expressions)

**Comment by clarkbw** [comment]
Created a doc, will start working on it soon.
https://docs.google.com/document/d/1g-KOVLdEm_7aMtFckVJ4nvlyP_KmCQaHSLKm_Ofp9Vo/edit#
