### ISSUE TITLE
[Sources] Right arrow should not go to the next source

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2256]
currently right arrow expands directories and goes to the next source in the source tree.

We would like to limit it so that it only expands directories.

#### Background

The change is likely in **devtools-core** [`tree.js`](https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-sham-modules/client/shared/components/tree.js#L522). The best way to test the changes is to actually make the change in the debugger node_modules directory. Once you feel good about the change, you can open a PR in devtools-core

#### possible diff

```diff
diff --git a/packages/devtools-sham-modules/client/shared/components/tree.js b/packages/devtools-sham-modules/client/shared/components/tree.js
index b3d6faa..64fff6d 100644
--- a/packages/devtools-sham-modules/client/shared/components/tree.js
+++ b/packages/devtools-sham-modules/client/shared/components/tree.js
@@ -519,8 +519,6 @@ const Tree = module.exports = createClass({
       case "ArrowRight":
         if (!this.props.isExpanded(this.props.focused)) {
           this._onExpand(this.props.focused);
-        } else {
-          this._focusNextNode();
         }
         return;
     }
```

**Comment by ryanjduffy** [comment]
Proposed diff was right on. See linked PR ^^^
