### ISSUE TITLE
[FunctionSearch] Not updating selected item on click

### ISSUE THREAD

**Issue by AlanCezarAraujo** [devtools-html/debugger.html#2267]
Whan I click on an item from the result list, it navigates to the item in the source panel, but it doesn't update the selected item in the result list.

**Comment by AlanCezarAraujo** [comment]
I'm already wornking to fix it.

**Comment by wldcordeiro** [comment]
Can you describe what you mean by not updating in the result list?

**Comment by wldcordeiro** [comment]
@AlanCezarAraujo I see what you mean now.

Here's a patch that should do what we expect.

```patch
diff --git a/src/components/Editor/SearchBar.js b/src/components/Editor/SearchBar.js
index d1a5add..c85f379 100644
--- a/src/components/Editor/SearchBar.js
+++ b/src/components/Editor/SearchBar.js
@@ -322,11 +322,14 @@ const SearchBar = React.createClass({
   },
 
   // Handlers
-  selectResultItem(item: SymbolDeclaration) {
+  selectResultItem(item: SymbolDeclaration, index: number, e: SyntheticEvent) {
     const { selectSource, selectedSource } = this.props;
     if (selectedSource) {
+      this.setState({ selectedResultIndex: index });
       selectSource(
         selectedSource.get("id"), { line: item.location.start.line });
+      this.closeSearch(e);
     }
   },
 
diff --git a/src/components/shared/ResultList.js b/src/components/shared/ResultList.js
index e4a25c7..bd61838 100644
--- a/src/components/shared/ResultList.js
+++ b/src/components/shared/ResultList.js
@@ -24,7 +24,7 @@ const ResultList = React.createClass({
   renderListItem(item: ResultListItem, index: number) {
     return dom.li(
       {
-        onClick: () => this.props.selectItem(item),
+        onClick: e => this.props.selectItem(item, index, e),
         key: `${item.id}${item.value}${index}`,
         ref: index,
         title: item.value,
```

**Comment by AlanCezarAraujo** [comment]
@wldcordeiro thanks for your help!  
I went on a different approach but you gave me a more elegant solution.  
I'll open a PR as soon as I fix some Flow issues.

**Comment by wldcordeiro** [comment]
@AlanCezarAraujo you may want to leave `selectResultItem` itself alone as it's used by the keyDown handler as well and just modify this [line](https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/SearchBar.js#L486) like so

```js
selectItem(e, item, index) {
  if (this.props.selectedSource) {
    this.setState({ selectedResultIndex: index });
    this.props.selectSource(
      this.props.selectedSource.get("id"),
      { line: item.location.start.line }
    );
    this.closeSearch(e);
  }
},
```

**Comment by jasonLaster** [comment]
ping @AlanCezarAraujo - how's it going?

**Comment by AlanCezarAraujo** [comment]
@jasonLaster @wldcordeiro  I'm having some weird issues, probably with Webpack.
As soon as I get through this problem I'll open a Pull Request.

You can look at what I've done in [this commit](https://github.com/AlanCezarAraujo/debugger.html/commit/4410e41dfd2eab55d05ba062662507389878ed46).
Let me know what you think about the refactoring.

**Comment by jasonLaster** [comment]
Thanks for the update @AlanCezarAraujo.

What were you seeing?

**Comment by AlanCezarAraujo** [comment]
Hi @jasonLaster!

Sorry for the late response. I've had a busy week at work.  
But here we go: 

On `onKeyDown` event, there were some chained `if/else` conditions.  
I created the object `keyDownHandlers` which is used by the event handler simplifying the condition chain to this:

```js
keyDownHandlers[e.key] && keyDownHandlers[e.key]
      .call(this, e, searchResults, resultCount);
```

I'd appreciate any thought on this.

**Comment by jasonLaster** [comment]
This looks a bit magical for my taste, but PR it as a refactor PR and we can discuss there

**Comment by AlanCezarAraujo** [comment]
Hi @jasonLaster! I took @wldcordeiro suggestion to fix it.  
Sorry for my late work.
