### ISSUE TITLE
Add -no-remote startup parameter to Firefox development instance

### ISSUE THREAD

**Issue by Fensterbank** [devtools-html/debugger.html#2269]
I used the proposed startup parameters at [remotely-debuggable-browsers.md](https://github.com/devtools-html/debugger.html/blob/master/docs/remotely-debuggable-browsers.md#firefox-all-versions) for Firefox on Windows to start a debuggable Firefox process in an own development profile.

` -start-debugger-server 6080 -P development`

Unfortunately I faced the problem that after I started my development instance, I was unable to use or start my default Firefox.
I suggest to append the parameter `-no-remote` to the development instance to prevent interfering with an already running (or later started) Firefox default instance.

I think most people using Firefox in the development profile will also have their normal Firefox to surf the web which is not possible without `-no-remote`.

**Comment by jasonLaster** [comment]
@MoLow @svenvNL @Garbee @clarkbw @irfanhudda thoughts on if this could help us with windows

**Comment by clarkbw** [comment]
I think there are issues if you run `-no-remote` with a first Firefox instance and then run you DevEdition afterward (defaults to remote on). But in general I don't think there's a real problem with this.  I haven't tested it on Windows yet though.

**Comment by jasonLaster** [comment]
Thanks @Fensterbank, I don't think we want to use `no-remote` at this time. Our `yarn firefox` command will create a new profile on the fly.

We recently upgraded our windows firefox driver, so maybe it will work for you.
