### ISSUE TITLE
[Sources] Seems like it is Case-Sensitive, also doesn't mix similar paths

### ISSUE THREAD

**Issue by dehghani-mehdi** [devtools-html/debugger.html#2274]
Hi,

I'm using FFv52 [beta], I enabled new debugger via `about:config`. as I mentioned in title of the issue, seems like `Sources` is `Case-Sensitive`, also doesn't mix similar paths, for ex. imagine this 2 links:

`/A/B/C/js-file.js` & `/A/B/another-js-file.js`, in `Sources` I got 2 separate entries, I think second one should be sub-item of first one. also same situation for `/a/b/C/js-file.js` & `/A/B/another-js-file.js`.

Thank you!

**Comment by wldcordeiro** [comment]
Could you post a screenshot?

**Comment by dehghani-mehdi** [comment]
![ddd](https://cloud.githubusercontent.com/assets/9152330/23584876/bcea403c-0183-11e7-918c-33744b5e9f29.png)

**Comment by wldcordeiro** [comment]
I'm not quite sure I see the problem here. I would expect those two be two *separate* directories.

**Comment by dehghani-mehdi** [comment]
@wldcordeiro as we have just 1 folder here, `DesktopModules`, I believe 2 entries for 1 folder is not correct. imagine following paths in some `web page`:

- `DesktopModules/file1.js`
- `Desktopmodules/file2.js`
- `desktopmodules/file3.js`
- `desktopModules/file4.js`
- `DESKTOPModules/file5.js`
- ...

Is that correct to having N entries in `Sources` panel for same folder?

**Comment by wldcordeiro** [comment]
`DesktopModules`, `desktopmodules` and `desktopModules` would be three distinct directories. This is standard in OSes.  I think I understand what the issue is though, for files/folders hosted on the server the directories are case-insensitive like URL paths. However when we bring in sourcemapped files/folders we would want case-sensitivity like in an OS.

**Comment by jasonLaster** [comment]
makes sense... I'm still not sure that I have enough information to go off. I wonder if there's an easy way to reproduce this issue?

**Comment by dehghani-mehdi** [comment]
@jasonLaster Can you simulate with creating simple HTML page with some JS links, that meets above condition or you need a testcase?

**Comment by jbhoosreddy** [comment]
I think I understand the issue. @dehghani-mehdi if you do have a sample test case you can make public that'd be helpful too. I'll look into this and compare with how chrome also handles this.

**Comment by jasonLaster** [comment]
This is a good way to test the behavior. With that said, I think i prefer the case sensitive approach.


```diff
diff --git a/src/utils/tests/sources-tree.js b/src/utils/tests/sources-tree.js
index 568cb34..76cb1f3 100644
--- a/src/utils/tests/sources-tree.js
+++ b/src/utils/tests/sources-tree.js
@@ -10,6 +10,12 @@ describe("sources-tree", () => {
     url: "http://example.com/a/b/c.js",
     actor: "actor1"
   });
+
+  const aBcSource2 = Map({
+    url: "http://example.com/a/B/c2.js",
+    actor: "actor1"
+  });
+
   const abcdeSource = Map({
     url: "http://example.com/a/b/c/d/e.js",
     actor: "actor2"
@@ -223,6 +229,33 @@ describe("sources-tree", () => {
     expect(abcNode.path).to.be("/example.com/a/b/c.js");
   });

+  it("can collapse a single source", () => {
+    const fullTree = createNode("root", "", []);
+    addToTree(fullTree, abcSource, aBcSource2);
+    expect(fullTree.contents.length).to.be(1);
+    const tree = collapseTree(fullTree);
+
+    const host = tree.contents[0];
+    expect(host.name).to.be("example.com");
+    expect(host.contents.length).to.be(1);
+
+    const abFolder = host.contents[0];
+    expect(abFolder.name).to.be("a/b");
+    expect(abFolder.contents.length).to.be(1);
+
+    const abcNode = abFolder.contents[0];
+    expect(abcNode.name).to.be("c.js");
+    expect(abcNode.path).to.be("/example.com/a/b/c.js");
+
+    const abFolder = host.contents[1];
+    expect(abFolder.name).to.be("a/b");
+    expect(abFolder.contents.length).to.be(1);
+
+    const abcNode = abFolder.contents[1];
+    expect(abcNode.name).to.be("c2.js");
+    expect(abcNode.path).to.be("/example.com/a/b/c.js");
+  });
+
```

**Comment by jasonLaster** [comment]
I think this is the correct behavior because the server could treat `/a/b/c` differently from `a/B/C`

**Comment by dehghani-mehdi** [comment]
I think it's not correct to show multiple entries for same path. _so Chrome guys have new thing to laugh on me, I'm not sure, but I think Chrome merge this king of paths, I'll check tomorrow_

@jbhoosreddy seems like there is no need to testcase anymore.
