### ISSUE TITLE
update assets/panel/prefs

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2277]
the prefs file currently reflects an old version of `devtools/preferences/devtools.js` because we haven't updated the docker image. 

We should update the image and then update `prefs.js` to just be debugger prefs

**Comment by jryans** [comment]
Is this a task I can perform? Do I need special access to publish the new Docker image?

**Comment by jryans** [comment]
Looks like @jasonLaster completed this task in #2361.
