### ISSUE TITLE
[Parser] move to a worker

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2282]
It would be nice to move the parsing to a worker for two reasons

1. we never block the main thread
2. we can do it immediately on source text load 

Look to how we do the source-map worker and util with `workerTask` for an example of how to setup the APIs

Here's a [patch](https://gist.github.com/8981376b1406660bfe52d45546d3f9fb) and [branch](https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:parser-worker?expand=1)

**Comment by wldcordeiro** [comment]
I'll grab this, I've got some ideas for the parsing that I wanted to play with and learning more about workers is on my list of things to do.
