### ISSUE TITLE
[perf] start speed walking

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2283]
:runner: 

We should investigate ways to speed up debugger stepping. The two bottlenecks that I see are:

1. codemirror and searching
2. immutable hydration

Immutable is expensive because we hydrate all of the pause data on each pause event. 

#### Here's a screenshot of a performance profile:

![screenshot-3]

Here is an experimental [branch] with immutable hydration stripped away.

#### Here are some screenshots with hydration removed

![screenshot-1]
![screenshot-2]

#### Next Steps

We can do one of two things, either remove immutable hydration for pause data (something James and I discussed) or defer some hydration for later. Namely, hydrate frames and scope data, but defer loading the object properties to a later tick.

[branch]:https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:stepping-perf

[screenshot-1]:https://shipusercontent.com/9063418a44ae97b9f1e683913d217be3/Screen%20Shot%202017-03-04%20at%206.48.10%20PM.png
[screenshot-2]:https://shipusercontent.com/268cbd460f86dc1d22c30a0dcb3f0e1a/Screen%20Shot%202017-03-04%20at%206.47.56%20PM.png

[screenshot-3]:https://shipusercontent.com/0f3ea33486b416480441dc02caad715e/Screen%20Shot%202017-03-04%20at%207.00.30%20PM.png

**Comment by wldcordeiro** [comment]
> We can do one of two things, either remove immutable hydration for pause data (something James and I discussed) or defer some hydration for later. Namely, hydrate frames and scope data, but defer loading the object properties to a later tick.

@jasonLaster Is it possible we could also stand to reduce our use of `.toJS()`? That may be more expensive than accessing the immutable data types' APIs. Deferring is also nice though, maybe combining the strategy of deferring and using the immutable APIS would  be a good solution?

Could you share what you're doing in the screenshots? I'd like to test it as well and see how it fairs on my laptop as its pretty old and could be a good low-spec example. 😆

**Comment by jasonLaster** [comment]
I looked at the perf for stepping earlier with @gregtatum and found three things

1. json parsing is slow in the launchpad (can't fix that)
2. immutable hydration in the pause reducer
3. getAndProcessFrames is slow because of toJS

<img width="1089" alt="onpacket" src="https://cloud.githubusercontent.com/assets/254562/25759373/3f827de2-31a0-11e7-8b19-1a1dea224eca.png">
![immutable hydration](https://cloud.githubusercontent.com/assets/254562/25759374/3f82cac2-31a0-11e7-955d-78adfae4c12b.png)
![getandprocessframes](https://cloud.githubusercontent.com/assets/254562/25759375/3f83f898-31a0-11e7-9915-5e358e9ae576.png)
