### ISSUE TITLE
Conditional breakpoint panel close button is hidden in files with long lines

### ISSUE THREAD

**Issue by irfanhudda** [devtools-html/debugger.html#2287]
Close button of conditional breakpoint panel is hidden when viewing files with long lines.

### Steps to reproduce:
1. Open a file in debugger with long line (horizontal scrollbar in codemirror should appear)
2. Right click on gutter and select `Add Conditional Breakpoint`
3. Close button is not visible. (Can be seen if we scroll horizontally)

### Screenshot
![scr](https://cloud.githubusercontent.com/assets/1755089/23589737/c96b22c0-01f8-11e7-9580-af6e0530891d.gif)

This line might need some change [https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/ConditionalPanel.css#L20](https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/ConditionalPanel.css#L20)

**Comment by aklt** [comment]
I tried to find a solution for this while working on #1945, but understood from @ryanjduffy that he did not run into this working on the same fix.  I am curious what the correct fix is for this.

**Comment by jasonLaster** [comment]
So, the problem as i understand it is that the CB panel is the width of the line and we want it to be the width of the editor wrapper... I'm open to creative solutions :P

**Comment by aklt** [comment]
AFAICT there is not nice CSS solution, so something creative seems to be needed, probably a hack.  Are any of you aware of an elegant solution?

**Comment by aklt** [comment]
As far as I can tell there is no nice pure CSS way of solving this, but please
let me know if I am wrong.  It is possible to hook into events firing when the
ConditionalPane is opened or closed and at that point programatically place the
close button better.

The situation in the screenshot looks a bit more difficult to me.  When dragging
the `SplitBox.onMove` is called from `Draggable` and I thought there might be a
good way here somewhere to get the size of the right pane and place the close
button somewhere.  However I don't think it is possible without refactoring the
`devtools-modules`, something I do not feel comfortable doing.

Maybe there is another way?

**Comment by jasonLaster** [comment]
lets try something like this:

```diff

diff --git a/src/components/Editor/index.js b/src/components/Editor/index.js
index e5a8cbe..6e71c33 100644
--- a/src/components/Editor/index.js
+++ b/src/components/Editor/index.js
@@ -362,9 +362,14 @@ const Editor = React.createClass({
     });

     this.cbPanel = this.editor.codeMirror.addLineWidget(line, panel, {
-      coverGutter: true
+      coverGutter: true,
+      noHScroll: true
     });
     this.cbPanel.node.querySelector("input").focus();
+
+    // set the width of the editor here...
+    const editorWidth = this.cbPanel.node.closest(".editor-pane").getBoundingClientRect().width;
+    this.cbPanel.node...;
   },

```

@amitzur might be interesting to you... 
Ultimately, i'd like to clean this up with some better *react* ways, but for now this is likely fine.

**Comment by amitzur** [comment]
I'll take a look and discuss in today's community call

**Comment by aklt** [comment]
Would love to join you, but I cannot make it today.  curious what you find!

**Comment by aklt** [comment]
With the patch above by @jasonLaster applied the close button will align correctly with the right pane when the conditional panel is opened. The noHScroll option was the reason for this. The situation in the image above is not fixed by this, though.

I spoke with @amitzur and found out it was concluded that the real fix, possibly involving changes to SplitBox so that resize events are emitted, will land at a later point in time.  So I think the best solution for now is to apply the noHScroll part of Jasons patch.

Also, I took the liberty to add a little space between the close button and the right panel.

**Comment by jasonLaster** [comment]
@amitzur @aklt here's a way to always provided the dimensions to children. React cautions against [context](https://facebook.github.io/react/docs/context.html), but this might be a useful case for it.

```diff
index 74c7f48..9708f86 100644
--- a/packages/devtools-modules/client/shared/components/splitter/SplitBox.js
+++ b/packages/devtools-modules/client/shared/components/splitter/SplitBox.js
@@ -66,6 +66,13 @@ const SplitBox = React.createClass({
     };
   },

+  getChildContext() {
+    const { width, height, vert } = this.state;
+    return {
+      width, height, vert
+    };
+  },
+
   componentWillReceiveProps(nextProps) {
     if (this.props.vert !== nextProps.vert) {
       this.setState({ vert: nextProps.vert });
@@ -232,4 +239,10 @@ const SplitBox = React.createClass({
   }
 });

+SplitBox.childContextTypes = {
+  vert: PropTypes.bool,
+  width: PropTypes.number,
+  height: PropTypes.number
+};
+
```

**Comment by jasonLaster** [comment]
Ohh... my solution is probably impractical because we just need to tell codemirror that there was a change.
