### ISSUE TITLE
How to avoid installing invalid prefs via `copy-assets`

### ISSUE THREAD

**Issue by jryans** [devtools-html/debugger.html#2302]
The `copy-assets` script for running mochitests currently copies a full DevTools pref set from this repo to m-c. However, this is not the repo of record for non-debugger prefs, and so `copy-assets` could inadvertently alter some non-debugger prefs to unexpected / older values.

Should this repo instead maintain a debugger-only prefs file to avoid confusion? Is there any reason a full DevTools prefs file is needed here?

@jasonLaster, I thought I remembered you splitting out debugger prefs somewhere, but I am not seeing in this repo at the moment...

**Comment by jryans** [comment]
Ah, they are broken out into separate files in m-c, but not over here. Maybe there's unfinished work here?

**Comment by jryans** [comment]
Seems like this repo should maintain only the `devtools/client/preferences/devtools.js` m-c file, and can feel free to replace it, etc. when landing updates.

The current `assets/panel/prefs.js` file here could be removed.

**Comment by jryans** [comment]
Looks related to #2277.

**Comment by jasonLaster** [comment]
yep - this is related to #2277. I just need to update the MC image we use so that it has `prefs/debugger.js` and then i'm good
