### ISSUE TITLE
Syntax highlighting for TypeScript

### ISSUE THREAD

**Issue by jryans** [devtools-html/debugger.html#2306]
Saw a request on IRC for TypeScript syntax highlighting. (I think they were using the old debugger, but this seemed like a better place to file.)

**Comment by wldcordeiro** [comment]
I believe this has landed. One of our debugging examples is a Typescript project and I saw highlighting there.

**Comment by clarkbw** [comment]
Yep, this example: https://devtools-html.github.io/debugger-examples/examples/typescript/greeter/ should highlight Nightly and DevEdition.
