### ISSUE TITLE
[Editor] Syntax highlighting for clojurescript

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2307]
We have support for other modes like coffeescript, jsx, flow, elm (i think). 

Steps:
1. add the context-type
2. add the codemirror mode

**Comment by tromey** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1211397

**Comment by jasonLaster** [comment]
Here's a chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=312271
