### ISSUE TITLE
[Symbol Search] UI Polish

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#2309]
There are some unresolved questions about the interface for symbol searching.

1. Should we have icons that identify the symbol type (class/function/variable)
2. The current layout could be problematic with using horizontal space. Should we use some kind of dropdown?

Opening this as discussion so we can figure out how to make it actionable.

**Comment by jasonLaster** [comment]
I'll throw in that we want to include "go to line" soon. 

Likely we detect if you add a colon first and update the magnifying glass icon. 

If we see that variable search is on we could also show an@. We could also see a preceding @. 

Re: dropdown. My quick response is that we don't need it off we folks class search onto variable search. 

Re: icons. I could see punting on this until we start our work on improving inline preview. Two reasons, we want to be confirm with the variable previews and we would benefit from having a designer :)

**Comment by wldcordeiro** [comment]
I like the idea of wildcards mapping to search-types with buttons for discoverability purposes.

Sublime uses `@` for functions and I like it a lot.

**Comment by jasonLaster** [comment]
Hey @wldcordeiro this issue has become kinda vague.

- "go to line" is a fun feature, but probably a separate issue
- I would guess we should remove "class" search for now and perhaps find a home for it later
- icons for types of symbols is a good idea, but I think we should wait for a designer
- wildcards is a good idea. we should file an issue for that.

**Comment by wldcordeiro** [comment]
> "go to line" is a fun feature, but probably a separate issue

Agreed, I think that would be an issue of its own.

> I would guess we should remove "class" search for now and perhaps find a home for it later

Yeah not really super useful, could just merge into variables as it's a form of declaration. 

> icons for types of symbols is a good idea, but I think we should wait for a designer

Probably for the best.

> wildcards is a good idea. we should file an issue for that.

Agreed

**Comment by jasonLaster** [comment]
Filed #2446 

We can tackle "go to line" afterwards
