### ISSUE TITLE
[Editor] Conditional Breakpoint close button is hidden when the editor resizes

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2317]
The conditional breakpoint pane does not resize when the editor resizes, which causes the close button to either be hidden or for the pane to look small :)

The solution is to tell codemirror to re-calculate the pane width.

That is easy to do with `setSize`. You can see codemirror already does this in `onResize` when the window resizes.

```diff
diff --git a/src/components/Editor/index.js b/src/components/Editor/index.js
index 438b999..1257a99 100644
--- a/src/components/Editor/index.js
+++ b/src/components/Editor/index.js
@@ -267,6 +267,11 @@ const Editor = React.createClass({
     this.previewSelectedToken(e, ctx, modifiers);
   },

+  // not sure how to know when to fire this :)
+  resizeEditor() {
+    this.editor.codeMirror.setSize();
+  },
+
```

Additional discussion in #2287

![](https://cloud.githubusercontent.com/assets/1755089/23589737/c96b22c0-01f8-11e7-9580-af6e0530891d.gif)

**Comment by magsout** [comment]
@jasonLaster 
>The solution is to tell codemirror to re-calculate the pane width.

Why did you add a method to calculate the width ? Why not add a width: 100%?


Maybe I missed something 

![screen recording 2017-03-13 at 02 13 pm](https://cloud.githubusercontent.com/assets/1997108/23855783/6ac11e32-07f7-11e7-9ddf-96f92b4fa0ea.gif)

**Comment by jasonLaster** [comment]
@magsout it's an interesting problem. CodeMirror calculates the panel width here because the panel by default is the width of the line. 

Jump in and you'll see what I mean.

**Comment by magsout** [comment]
@jasonLaster not sure to understand.

WHat I understand is:

The parent is `<div class="new-breakpoint"></div>` so the width of `<div class="CodeMirror-linewidget"></div>` depends of it ?

**Comment by jasonLaster** [comment]
Hmm, not sure. Let me know what you find

**Comment by irfanhudda** [comment]
Updated GIF for this issue
![breakpoint](https://cloud.githubusercontent.com/assets/1755089/23908130/26342fc2-08f9-11e7-9df2-76734f921ef0.gif)

**Comment by magsout** [comment]
I invested a little more.  When the component is mount `CodeMirror-linewidget` width is calculated and `CodeMirror-sizer` too.

I started on this idea:

I propose to remove the function wich calculates the width of `CodeMirror-linewidget`. 

So `CodeMirror-linewidget` depends to the width of `CodeMirror-sizer`.

We just need to add a function to resize `CodeMirror-sizer` when the editor resizes

@jasonLaster what do you think ?

**Comment by jasonLaster** [comment]
Hmm, not sure if I follow. 

@aklt @amitzur @ryanjduffy what do you think?

**Comment by ryanjduffy** [comment]
It can't depend upon the width of `CodeMirror-sizer` because that node reflects the width of the content and not that of the viewport. The result would be a regression of #2287 in which the close button would be hidden for long lines again.

**Comment by ryanjduffy** [comment]
Wrote up a *very* rough approach that adds an `onResize` callback to `Splitbox` from `devtools-modules` which, when called in the app, updates the ui state in redux with a fake "size" to trigger an update of the editor and thereby a `setSize()` on the CodeMirror.

Not sure if/when I'll be able to polish it up so sharing here in case someone else wants to take the torch.

```
diff --git a/src/actions/ui.js b/src/actions/ui.js
index 0045ecf..9c496e4 100644
--- a/src/actions/ui.js
+++ b/src/actions/ui.js
@@ -37,9 +37,17 @@ function togglePaneCollapse(position: string, paneCollapsed: boolean) {
   };
 }
 
+function editorResized () {
+  return {
+    type: "EDITOR_RESIZED",
+    size: window.performance.now()
+  };
+}
+
 module.exports = {
   toggleFileSearch,
   closeFileSearch,
+  editorResized,
   showSource,
   togglePaneCollapse
 };
diff --git a/src/components/App.js b/src/components/App.js
index 5ece10a..0b31bbf 100644
--- a/src/components/App.js
+++ b/src/components/App.js
@@ -100,6 +100,7 @@ class App extends Component {
         splitterSize: 1,
         startPanel: Sources({ sources, horizontal }),
         startPanelCollapsed,
+        onResize: this.props.editorResized,
         endPanel: SplitBox({
           style: { overflowX },
           initialSize: "300px",
@@ -107,6 +108,7 @@ class App extends Component {
           maxSize: "80%",
           splitterSize: 1,
           endPanelControl: true,
+          onResize: this.props.editorResized,
           startPanel: this.renderEditorPane(),
           endPanel: SecondaryPanes({ horizontal }),
           endPanelCollapsed,
diff --git a/src/components/Editor/index.js b/src/components/Editor/index.js
index bb34f58..3c9d0d3 100644
--- a/src/components/Editor/index.js
+++ b/src/components/Editor/index.js
@@ -23,7 +23,8 @@ const {
   getSourceText, getBreakpointsForSource,
   getSelectedLocation, getSelectedFrame,
   getSelectedSource, getHitCountForSource,
-  getCoverageEnabled, getLoadedObjects
+  getCoverageEnabled, getLoadedObjects,
+  getEditorSize
 } = require("../../selectors");
 const { makeLocationId } = require("../../reducers/breakpoints");
 const actions = require("../../actions");
@@ -223,6 +224,12 @@ const Editor = React.createClass({
     }
   },
 
+  componentWillUpdate(nextProps) {
+    if (this.props.editorSize !== nextProps.editorSize) {
+      this.editor.codeMirror.setSize();
+    }
+  },
+
   componentWillUnmount() {
     this.editor.destroy();
     this.editor = null;
@@ -668,6 +675,7 @@ module.exports = connect(state => {
   const selectedSource = getSelectedSource(state);
 
   return {
+    editorSize: getEditorSize(state),
     selectedLocation,
     selectedSource,
     sourceText: getSourceText(state, sourceId),
diff --git a/src/reducers/ui.js b/src/reducers/ui.js
index 1ac1554..00c21e3 100644
--- a/src/reducers/ui.js
+++ b/src/reducers/ui.js
@@ -17,13 +17,15 @@ export type UIState = {
   shownSource: string,
   startPanelCollapsed: boolean,
   endPanelCollapsed: boolean,
+  editorSize: number
 };
 
 const State = makeRecord(({
   searchOn: false,
   shownSource: "",
   startPanelCollapsed: prefs.startPanelCollapsed,
-  endPanelCollapsed: prefs.endPanelCollapsed
+  endPanelCollapsed: prefs.endPanelCollapsed,
+  editorSize: 0
 } : UIState));
 
 function update(state = State(), action: Action): Record<UIState> {
@@ -46,6 +48,10 @@ function update(state = State(), action: Action): Record<UIState> {
       return state.set("endPanelCollapsed", action.paneCollapsed);
     }
 
+    case "EDITOR_RESIZED": {
+      return state.set("editorSize", action.size);
+    }
+
     default: {
       return state;
     }
@@ -73,9 +79,14 @@ function getPaneCollapse(
   return state.ui.get("endPanelCollapsed");
 }
 
+function getEditorSize(state: OuterState): number {
+  return state.ui.get("editorSize");
+}
+
 module.exports = {
   State,
   update,
+  getEditorSize,
   getFileSearchState,
   getShownSource,
   getPaneCollapse
diff --git a/src/selectors.js b/src/selectors.js
index 0b34505..225dc15 100644
--- a/src/selectors.js
+++ b/src/selectors.js
@@ -45,6 +45,7 @@ module.exports = {
 
   getEventListeners: eventListeners.getEventListeners,
 
+  getEditorSize: ui.getEditorSize,
   getFileSearchState: ui.getFileSearchState,
   getShownSource: ui.getShownSource,
   getPaneCollapse: ui.getPaneCollapse,
```

Also added the following to `onStopMove` in `Splitbox`

```
    if (this.props.onResize) {
      const { vert, height, width } = this.state;
      this.props.onResize({
        size: vert ? height : width
      });
    }
```

**Comment by jasonLaster** [comment]
ping @magsout. How's it going?

**Comment by magsout** [comment]
Sorry for the delay. I am trying to understand your architecture and how the Editor  and CodeMiror work. 

Thanks for sharing your idea @ryanjduffy I'll try to see if I am able to polish it.

**Comment by jasonLaster** [comment]
How's it going @magsout? Happy to help in slack

**Comment by jasonLaster** [comment]
Hey @magsout I'm making this issue available again. Feel free to reclaim it if you have time.
