### ISSUE TITLE
migrate to jest

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2319]
We'd like to migrate to jest, which is a more modern unit testing library with better support for mocking and snapshot testing

Steps:

- [x] get tests running #2315
- [x] Update CI integration
- [x] Update npm scripts
- [x] Remove Mocha code
- [x] update docs
- [x] Code coverage

#### coverage

`--coverage` creates a nice report. We also have lots of coverage output for codecov to ingest.

**Comment by montogeek** [comment]
I will continue with the todo list today
