### ISSUE TITLE
[Footer] remove extra footer padding

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2324]
The editor footer appears to have 5 or so pixels of padding above the border.

You can see it in dark mode and when the footer overlays text

<img src='https://shipusercontent.com/0e56540d6f73cba997c97d403ac5a0b8/Screen%20Shot%202017-03-10%20at%207.36.17%20AM.png' title='Screen Shot 2017-03-10 at 7.36.17 AM.png' width=630>

**Comment by magsout** [comment]
@jasonLaster 

I would like to work on this.

The height of `editor-mount` https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/Editor.css#L71 depends on the height of https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/Footer.css#L14

Would it be revelant to add a variable or just change the value?

**Comment by jasonLaster** [comment]
Yea, a variable scoped to the editor would be a good idea.
