### ISSUE TITLE
Add some indications for offline development with examples

### ISSUE THREAD

**Issue by ThomasCrevoisier** [devtools-html/debugger.html#2335]
Quick anecdote : I was in the train, wanted to work on the debugger and totally forgot that `yarn run chrome` opens on the online examples ^^'

What do you think about adding a quick note on `docs/getting-setup.md` mentioning https://github.com/devtools-html/debugger-examples ?

**Comment by clarkbw** [comment]
Great idea!  I've definitely hit this before as well.
