### ISSUE TITLE
Show message for pages with no Javascript to debug

### ISSUE THREAD

**Issue by ruturajv** [devtools-html/debugger.html#2371]
The default page that is opened with `yarn run firefox` opens up a page that is not having any Javascript: https://devtools-html.github.io/debugger-examples/

On opening the debugger window of that tab, it just shows an empty pane / structure. A new user like me might get stuck thinking its not working; It'll be great if a message like "No JavaScript to debug" is present.

![screenshot from 2017-03-14 21-17-24](https://cloud.githubusercontent.com/assets/227817/23909155/faf9ccec-08fb-11e7-873d-d01a73240b7b.png)

**Comment by jasonLaster** [comment]
This is similar to #2231
