### ISSUE TITLE
Remove vendor prefixes

### ISSUE THREAD

**Issue by irfanhudda** [devtools-html/debugger.html#2372]
Now that we have `autoprefixer` #1838 there is no need for vendor prefixes in css files. We should probably remove them

One example is here [https://github.com/devtools-html/debugger.html/blob/master/src/components/SecondaryPanes/Expressions.css#L12](https://github.com/devtools-html/debugger.html/blob/master/src/components/SecondaryPanes/Expressions.css#L12)

**Comment by DanUgelow** [comment]
I can work on cleaning up the css

**Comment by irfanhudda** [comment]
Hey @DanUgelow it looks like #2386 PR was raised for fixing this issue.
