### ISSUE TITLE
[ConditionalBreakpoint] Should focus on the pane

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2393]
When the editor search bar is open, it steals the focus from the conditional breakpoint pane:

STR:

1. select a source
2. cmd+f to open the search bar
3. right click on a gutter line and select "add conditional breakpoint"

Expect: the conditional breakpoint pane to be in focus
Actual: the search bar is in focus

**Comment by irfanhudda** [comment]
I think this might already be fixed. I cannot reproduce this locally.

**Comment by ruturajv** [comment]
conversely, I wonder shouldn't we close the Search bar? Since he has moved away from the search (assuming that he is done with his search).  Wouldn't it be ideal that he continues to his original task of Finding "by starting fresh" with "Ctrl+F" ?

**Comment by ruturajv** [comment]
@irfanhudda - I can reproduce the issue on Linux64 (ubuntu)

**Comment by jasonLaster** [comment]
@ruturajv i'm not sure about that :) not saying you're wrong, just i don't have a good example of where an editor debugger does this now. Also, I haven't played with it enough to say.

**Comment by irfanhudda** [comment]
@ruturajv @jasonLaster I've tried reproducing and found that conditional breakpoint panel is in focus.
![steps](https://cloud.githubusercontent.com/assets/1755089/24203740/8e602760-0f3c-11e7-8880-b9b9b9a542e2.gif)

Am I missing something?

**Comment by ruturajv** [comment]
@irfanhudda  - Aaargh!! I thought post conditional breakpoint creation, The Search pane should be in focus. yes conditional breakpoint text box ***is*** in focus

Does this make the issue - resolved?

**Comment by ruturajv** [comment]
@irfanhudda - also what is the tool to create these gifs? if ur using linux..

**Comment by irfanhudda** [comment]
@ruturajv [https://github.com/phw/peek](https://github.com/phw/peek) might be a good option for creating gifs

**Comment by jasonLaster** [comment]
Yep - i'm seeing that too. 

By the way, there are two cases here. 
1. Opening the pane via the context menu and 
2. Opening the pane via the cmd+b
