### ISSUE TITLE
[Scopes] expanded properties are not updated while stepping

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2394]
STR:

1. pause and expand an object
2. step
3. check the expanded object 

Expected: it has updated
Actual: it has not updated

@bomsy I think this is related to the actor cache

**Comment by bomsy** [comment]
@jlast true! i'll have a peek.

**Comment by arthur801031** [comment]
Just talked to @jasonLaster . I'll take a stab at this 🙂

**Comment by bomsy** [comment]
Nice!
