### ISSUE TITLE
Cannot open "Search for sources" again

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#2396]
**Steps to reproduce:**
1. Start Nightly (or Dev. Edition)
2. Go to any sites (e.g. about:home)
3. Open Debugger
4. Open "Search for sources" (e.g. click [+] or Ctrl+P)
5. Close "Search for sources"
6. Open "Search for sources" again

**Actual Results:**
No response. Cannot open "Search for sources" again.

**Expected Results:**
"Search for sources" works after the second times.

**Comment by irfanhudda** [comment]
I can confirm that we see this error in `master` branch.

When we try to open `SourceSearch` after closing it, we see some error in console.

Interestingly, we don't see the error if don't close `SourceSearch` but instead just switch tab and reopen `SourceSearch` again.

**Comment by irfanhudda** [comment]
I'll look into this

**Comment by wldcordeiro** [comment]
@irfanhudda double check this, with my redux stuff landing it may have been fixed in the process?
