### ISSUE TITLE
[EditorPreview] is masked by the conditional breakpoint panel

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2397]
The conditional breakpoint panel is very rudely masking the preview popup. We can make the popup much more capable with a higher `z-index`

Here's a patch, which i haven't tested. I'm not sure what the right zindex should be.

```diff
diff --git a/src/components/Editor/Preview.css b/src/components/Editor/Preview.css
index a84cadd..7b62e5a 100644
--- a/src/components/Editor/Preview.css
+++ b/src/components/Editor/Preview.css
@@ -9,6 +9,7 @@
   max-height: 130px;
   overflow: auto;
   max-width: 400px;
+  z-index: 5;
 }
 ```

![](http://g.recordit.co/6IRqovVENz.gif)

**Comment by bomsy** [comment]
Noticed this as well

![image](https://cloud.githubusercontent.com/assets/792924/24038750/ace78d4a-0afa-11e7-9210-aab9ffc83c0a.png)


I think they are related, and can be fixed along side.
