### ISSUE TITLE
[EditorPreview] Don’t preview variables outside of the frame

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2398]
Currently, we will preview variables regardless of whether they are in the selected frame. The problem with this is that you often get values that you would not expect.

For instance, if you pause in a function with "this" and then jump to another module with "this" hovering will give you the value from the selected frame.

We can fix this, by first checking the context (source id, line, location) of the token we're hovering on and seeing if it is within the selected frame.

The primary challenge here is to get the code range for the frame. The pause data has the start of the frame and outer scope, but it doesn't have the end. This is where babel comes in because we can get the scope start and end locations from the AST :)

![](http://g.recordit.co/snLzI3LGSp.gif)

**Comment by ryanjduffy** [comment]
Looking into this one

**Comment by ryanjduffy** [comment]
What do you think of bailing on `previewSelectedToken()` if the selected frame isn't for the selected source? That's a relatively easy first step, at least.

```
    if (!selectedFrame || !sourceText || !isEnabled("editorPreview") ||
        selectedFrame.location.sourceId !== selectedSource.get("id")) {
      return;
    }
```

**Comment by ryanjduffy** [comment]
Also noticed that `this` inspection isn't working because `selectedFrame` isn't passed to `previewExpression`. @jasonLaster Are you seeing the same?

**Comment by jasonLaster** [comment]
Hmm - i think that i fair, but shouldn't we always be looking at the selected source?
