### ISSUE TITLE
[EditorPreview] Simple `this` values are displayed as full-fledge values when the script is inline

### ISSUE THREAD

**Issue by julienw** [devtools-html/debugger.html#2402]
Debugging with this code:

```html
<!doctype html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta name='viewport' content='initial-scale=1'>
  </head>
  <body>
    <button type='button'>Click me!</button>
    <script type="text/javascript" charset="utf-8">
      var a = 'a';
      var b = 'b';

(function() {
  const c = 'cc';
  let a = 'aa';

  function func(c, d) {
    var e = 'eee';
    {
      const f = 'fff' + this;
      const len = this.length;
      const string = this;
      const g = string.length;

      debugger;
    }
  }

  document.querySelector('button').onclick = () => func.call('this', 'ccc', 'ddd');
})();
    </script>
  </body>
</html>
```
yields me a weird `this` value: instead of the string `"this"` I get a full-fledged String object:

![capture d ecran de 2017-03-17 16-07-17](https://cloud.githubusercontent.com/assets/454175/24049319/ed6baa32-0b2b-11e7-8f70-31b62b5bb031.png)

This works properly if the same script is in a separate file instead of inline.

**Comment by julienw** [comment]
This is what I get as a preview:
![preview-this](https://cloud.githubusercontent.com/assets/454175/24049505/90e44c32-0b2c-11e7-967e-72fc0c5a9219.png)

**Comment by jasonLaster** [comment]
@jcreighton is on it

**Comment by jcreighton** [comment]
Would the issue here be `func.call('this', 'ccc', 'ddd');` which sends in `'this'` instead of the this object? Or am I missing something?

**Comment by jasonLaster** [comment]
Yea. That could be it! I didn't see that

**Comment by jcreighton** [comment]
@jasonLaster Once I send in the `this` object instead, it shows the correct object in the preview. 
<img width="376" alt="screen shot 2017-04-08 at 4 30 09 pm" src="https://cloud.githubusercontent.com/assets/5232812/24832221/bb97dd2e-1c78-11e7-89e0-8d70bb1480f1.png">

**Comment by jasonLaster** [comment]
Thanks, the bucketing for window makes me so sad right now. We should do something better :)
