### ISSUE TITLE
[SearchBar] Search bar when scrolling with keyboard need to be fixed

### ISSUE THREAD

**Issue by irfanhudda** [devtools-html/debugger.html#2424]
Trying the steps from #2370 for Sensor Web example

On scrolling using keyboard `SearchBar` covers tabs. Also bottom bar is not visible

STR:
1. Open a big file (`main.js` from Sensor Web example [http://aws-sensorweb-static-site.s3-website-us-west-2.amazonaws.com/](http://aws-sensorweb-static-site.s3-website-us-west-2.amazonaws.com/))
2. Open search bar (`Ctrl+f`)
3. Focus on editor.
4. Try to scroll down using keyboard arrow key

![bug](https://cloud.githubusercontent.com/assets/1755089/24204405/5bd61352-0f3e-11e7-9850-9629c91f247d.gif)

Interestingly, scrolling with mouse seems to work well. Also I was not able to reproduce this issue in other examples

**Comment by samjwalker** [comment]
Found separate bugs on windows 10:

1) The search bar masking the tabs as you pointed out.
2) When the search bar is opened it is pushing everything down the screen putting the bottom scroll bar off the screen and the bottom scroll arrow off also.

Not sure if this is a bug but I'm not getting the "search for" bar underneath the main search bar.

Should we raise separate bugs for these?

**Comment by jasonLaster** [comment]
Hmm, is the second one https://github.com/devtools-html/debugger.html/issues/2291? If not, then file a new issue :)

**Comment by jasonLaster** [comment]
One thought that might not help is there is a CSS sticky property we might be able to use. We used it for the command bar effectively :)

**Comment by samjwalker** [comment]
Looking at it today, both of the bugs are reproducable in nightly but not our local debugger.html

However there is a funny gap at the bottom of the screen and we'll raise an issue for that.

Also still no sign of the other bar underneath the main search bar and will look into that.

In summary I can not reproduce any of the main issues.

**Comment by jasonLaster** [comment]
Hmm, that's interesting @samjwalker. I just tried @irfanhudda STR in both chrome and firefox with debugger.html and was able to reproduce. try clicking in the document and then holding down the arrow key.

**Comment by irfanhudda** [comment]
Also, note that I could reproduce this on Sensor Web example [http://aws-sensorweb-static-site.s3-website-us-west-2.amazonaws.com/](http://aws-sensorweb-static-site.s3-website-us-west-2.amazonaws.com/). Other examples were working well so it might be because the file is very large.

**Comment by samjwalker** [comment]
Must be to do with the file size. I am reprodicing with `http://aws-sensorweb-static-site.s3-website-us-west-2.amazonaws.com/`.

**Comment by samjwalker** [comment]
Ok so it looks like we can't prettify Big files and so the `.editor-mount` has been set to 100% for these big files. by doing that it hasn't taken the search bar into concideration and when that is opened it pushes everything down resulting in everything being pushed off screen.

**Comment by jasonLaster** [comment]
hmm - i'm not sure what you mean by big files? We don't prettify some things like files that have been source mapped or are already pretty.

**Comment by jasonLaster** [comment]
@samjwalker @irfanhudda @jbhoosreddy lets try and reproduce this now

**Comment by jasonLaster** [comment]
works great!
