### ISSUE TITLE
Blank space at the end of editor component.

### ISSUE THREAD

**Issue by samjwalker** [devtools-html/debugger.html#2429]
**When the search bar is opened there is as gap present (as highlited in the picture) and the 2nd search bar is not appearing.**

**STR:**

1) Open a file in the debugger

2) Open the search bar `ctrl+f`

**Expected result:**
Both of the search bars are open and no gaps anywhere.

**Actual result:**
Only the main search bar is opened and there is a gap above the `.source-footer`

This gap is part of the `.editor-wrapper1` and so must be to do with some incorrect calculations (when the editor is opened the size of the `.editor-mount` is 100% - 72px but should be 100% - 45px  and when done the gap is appering in the right place.

Also the second search bar will only open when `searchModifiers` and `symbolSearch` are true and only `searchModifiers` is true.
![gap present where scroll bar should be](https://cloud.githubusercontent.com/assets/15427172/24250133/be45c868-0fcd-11e7-8240-9c1eba6f804e.PNG)

**Comment by jasonLaster** [comment]
Nice find!
