### ISSUE TITLE
[DarkTheme] Highlight line is too bright

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2447]
The highlight line feels a bit like :camera: flash. We should soften it in dark mode so that it is not so harsh :)

Here are some notes on [colors](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#colors)

```diff
diff --git a/src/components/Editor/index.js b/src/components/Editor/index.js
index cab77ab..54b09f3 100644
--- a/src/components/Editor/index.js
+++ b/src/components/Editor/index.js
@@ -478,6 +478,7 @@ const Editor = React.createClass({
     // happening ever again (in case CodeMirror re-applies the
     // class, etc).
     if (this.lastJumpLine) {
+      // => this is where the class is toggled so the flash is probably coming from this class
       clearLineClass(this.editor.codeMirror, "highlight-line");
     }
```

![](http://g.recordit.co/TLwV44mepb.gif)

**Comment by jacobjzhang** [comment]
@jasonLaster is that just normal ctrl+F in the Editor? Anything configurations need to be turned on to search for functions/variables?

**Comment by jasonLaster** [comment]
It's function and variable search. Check the settings panel in the
launchpad.

You likely need symbolSearch on and functionSearch
