### ISSUE TITLE
[SoucesTree] Show the host domain first when the debugger opens

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2448]
@Dalimil recently helped us show the host domain first in the source list when the debuggee navigates #1374. We should be able to also show the host domain first when the debugger opens by setting the debuggee url when the debugger opens

**Comment by jasonLaster** [comment]
I took a stab at this this weekend and got the `debuggeeUrl` when the debugger connected. 

https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:navigate-on-connect?expand=1

unfortunately, this breaks the source tree :P

@Dalimil would you like to take a look?

**Comment by Dalimil** [comment]
The `SourcesTree.componentWillReceiveProps(nextProps)` function in `SourcesTree.js` seems to expect to be given additional sources via `nextProps.sources` every time it is called, but when `sources.size === 0` it recreates the tree - I'm not quite sure why, but the debuggeeUrl is part of the props and when it changes, this function is called with 0 sources, so it basically removes everything. 

I'm also getting different results when I call `actions.navigate(tabTarget._form.url);` in `firefox.js` immediately vs. when called after a scheduled setTimeout...

**Comment by jasonLaster** [comment]
oh fascinating. so we need to be a bit stricter about when we build the tree. 

like slow down...
