### ISSUE TITLE
double husky dependency

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#2460]
I'm seeing this warning when running `yarn install`.

```bash
warning debugger.html@0.1.0: "dependencies" has dependency "husky" with range "^0.13.1" that collides with a dependency in "devDependencies" of the same name with version "^0.13.2"
```

Looks like it is listed twice, not sure which one we want to keep.

`dependencies`
https://github.com/devtools-html/debugger.html/blob/master/package.json#L64

`devDependencies`
https://github.com/devtools-html/debugger.html/blob/master/package.json#L99

**Comment by wldcordeiro** [comment]
I think `devDependencies` would be the one we want since husky is used in development for a pre-push hook
