### ISSUE TITLE
[FunctionSearch] NaN results 

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2467]
@jacobjzhang has a `NaN` in his recent GIF. I'm not quite sure how he got it.

STR:
1. go to `todo-view.js` 
2. select function search
3. search for `close`

?

![](http://g.recordit.co/KEEn6tvCCX.gif)

**Comment by jacobjzhang** [comment]
Looks like after toggling function search off, there is no count or index passed as props.
<img width="1393" alt="screen shot 2017-03-27 at 5 57 36 pm copy" src="https://cloud.githubusercontent.com/assets/6591285/24379915/300d4ba0-1317-11e7-8f37-23627ef9d20a.png">

**Comment by bomsy** [comment]
looks like this is fixed!
