### ISSUE TITLE
Please add high sensitivity horizontal mouse wheel scrolling to the Debugger tab/view

### ISSUE THREAD

**Issue by tommai78101** [devtools-html/debugger.html#2476]
At the moment, we can only scroll horizontally by moving the mouse cursor to the bottom horizontal scrollbar and drag it to left or right. Unfortunately, in some cases where the horizontal scrollbar is very wide, or when the JavaScript code is not being code-wrapped due to auto-beautification, a slight mouse movement will cause the whole code to jump off-screen.

Here's one example:

![](http://i.imgur.com/W5P7TpR.gif)

![](http://i.imgur.com/yETZwpF.gif)

I want to be able to scroll horizontally either with the arrows keys on the keyboard, or with the mouse wheel. Not only that, but allow sensitive scrolling (shifting left/right by +5/-5 pixels, or similar) when scrolling horizontally on some codes where we have to debug JavaScript codes that are pretty long.

Thanks.

**Comment by jasonLaster** [comment]
Thanks for filing @tommai78101.

We're somewhat limited by what codemirror offers us here. They're generally pretty good, but I know that there are cases where it is dissappointing.

I think the user has three options:

1. scroll with the trackpad
2. prettify 
3. copy to their favorite editor and search their... 

This is ultimately a pretty difficult UX problem that we're not equipped to handle well at the moment as we're still tackling some pretty fundamental pieces like Preview and Search.

![](http://g.recordit.co/TfMiRUdVb4.gif)

**Comment by tommai78101** [comment]
Okay, thanks for the update. Perhaps if it's okay to add a label stating it is "deferred"?

**Comment by gwarser** [comment]
Enable scrollbar arrows!
