### ISSUE TITLE
Get project built when using files from Firefox repo

### ISSUE THREAD

**Issue by jlongster** [devtools-html/debugger.html#249]
We should start working on being in harmony with Firefox. As a first step, let's just make it so that we can point `ff-devtools-libs` to Firefox and webpack will successfully build the project. This does **not** mean it will run, but at least all the modules are found and bundled in.

I didn't know where to start with this so I made a google doc: https://docs.google.com/document/d/1qLi2mp8aS-Pcn7w48rib7xmd_XzyRFoQTHr6sWMoTs8/edit

From my research, I think these are the steps that will get us there:

- [x] Integrate ff-devtools-libs into debugger.html. This will make it much easier to quickly tweak it and keep in sync. Nobody else is using it anyway. Over time most of the code will be deleted as we pull more and more from gecko-dev.
- [x] Fix easy require paths, such as promise, task, etc
- [ ] De-privilege client/main.js in m-c so we can use a raw copy

- ~~Write our own WebSocket transport.~~ (Not going to do this yet, will do it in a different issue) This will be a heavily refactored version of the current one, with all unnecessary code removed. Currently there is a bunch of vestigial code in there from old Firefox usage. It will not be dependent on anything from gecko-dev and could eventually be a standalone module. We only need the low-level transport. We can pass this transport into the main/client.js from gecko-dev and it should work.
- ~~Focus on devtools.html to fix critical modules~~. This includes DevToolsUtils, SDK, main/client.js etc. Once these are fixed we should be able to at least build debugger.html

**Comment by jlongster** [comment]
Merged in ff-devtools-libs in https://github.com/jlongster/debugger.html/commit/37896b89f2d960f1cb52b1e11fd00e9952f08732

**Comment by jlongster** [comment]
We already have several changes that allow us to run files directly from m-c. These files live in public/js/lib/devtools. There are still some important files in devtools-sham, which are the hacked up versions. client/main.js is an important one.

We've discovered that we don't really need that many files from m-c. The protocol client is the only thing we really need. We can easily use other utility libraries instead of DevToolsUtils, and I think that's ok.

Given the above, the only thing really left here is to work on client/main.js in m-c and make sure we can copy it over with no changes.

**Comment by jlongster** [comment]
Jason and I decided that this won't get done until next sprint, since there's only a few days left.

**Comment by clarkbw** [comment]
I feel like most of this is already done

**Comment by jlongster** [comment]
Yes, I meant to update this yesterday. I think we can close it for now. Compatibility with m-c will be a long-standing effort and we'll keep working on it in new bugs.
