### ISSUE TITLE
[WatchExpressions] with Pause on exceptions on, causes to pause 

### ISSUE THREAD

**Issue by bomsy** [devtools-html/debugger.html#2496]
STR:
* Open the debugger
* Make sure the pause on all exceptions is on
* Add an expression that won't exist in the current scope e.g `i`

Actual:
* It automatically puts the expression into a editor page and pauses on that line
* Does not add the expression

Expected:
* Should not pause on exception
* Should add expression to the watch list

![image](https://cloud.githubusercontent.com/assets/792924/24483259/b6228aa6-14ee-11e7-9c9a-7de9fcabbc14.png)

**Comment by jasonLaster** [comment]
Hmm, lets see. I like chrome's pause notice when you do a console eval w/ pause on exceptions on.

![Screen Shot 2017-04-18 at 1.02.44 PM.png](https://shipusercontent.com/1ed8167ef5c7765273659f5253c48bfa/Screen%20Shot%202017-04-18%20at%201.02.44%20PM.png)

**Comment by jasonLaster** [comment]
We might be able to fix this by realizing that we're currently doing a watch expression evaluation and automatically resuming
