### ISSUE TITLE
Error occurred while processing 'resume: TypeError: can't access dead object

### ISSUE THREAD

**Issue by tommai78101** [devtools-html/debugger.html#2498]
**Full stack trace message:**

```
error occurred while processing 'resume: TypeError: can't access dead object
Stack: createNonSourceMappedActor@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/utils/TabSources.js:298:1
getFrameLocation@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/utils/TabSources.js:578:7
_handleResumeLimit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/script.js:903:31
onResume@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/script.js:1007:28
onPacket@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/main.js:1769:15
_onJSONObjectReady/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/transport/transport.js:483:11
exports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14
exports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14
enter@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/script.js:350:5
_pushThreadPause@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/script.js:533:5
_pauseAndRespond@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/script.js:741:7
hit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/breakpoint.js:175:12
@moz-extension://efb7b1b2-2991-4a92-9d3b-02d90f272635/popup.js:3:3
EventListener.handleEvent*@moz-extension://efb7b1b2-2991-4a92-9d3b-02d90f272635/popup.js:1:1
Line: 298, column: 1
```

**Caused by:**

`event.target.classlist.contains()`

**Steps to reproduce:**

1. Open the following attachment and place it somewhere where you're able to load the extension into the browser.
2. Debug the extension. The DevTool window should pop-up.
3. Do the following:

![](http://i.imgur.com/Eac24SI.gif)

**Remarks:**

I suspected the code `event.target.classlist.contains()` is not handling cases where a missing class name in the entire `practice.html` and `popup.html` occurs. It only occurs when that code is executed. After executing the code and getting tons of errors in the Console tab/view/panel, the whole DevTools window becomes unresponsive, and you need to close the window, then click on the `Debug` button to reactivate the window.

I hoped I'm reporting it in the right place.

**Comment by jasonLaster** [comment]
@tommai78101 would you mind refiling this issue in bugzilla as it relates to either the old UI or the server

**Comment by tommai78101** [comment]
Nevermind, I think I found where to file it. It's in the "Firefox", because the description said so.

**Comment by julienw** [comment]
@tommai78101 can you paste the bug link please ? :)

**Comment by tommai78101** [comment]
@julienw Sorry, just had lunch.

https://bugzilla.mozilla.org/show_bug.cgi?id=1352089

**Comment by julienw** [comment]
No pressure :) thanks !
