### ISSUE TITLE
Finish up migration to CircleCI 2.0

### ISSUE THREAD

**Issue by jryans** [devtools-html/debugger.html#2499]
@clarkbw got started down the path of migrating to CircleCI 2.0 (#2063), and we should try to finish that out.

This would really simplify the way we make use of Docker for mochitests.

In #2495, I was trying to pull a Docker image by hash, but that's not supported by the old Docker version in CircleCI 1.0, so just another reason to push forward with this migration effort.

**Comment by jasonLaster** [comment]
I worked with Peter and @Garbee on this today 

1. we created a new image for the mozilla + node dependencies 
2. we ran yarn in the image and `yarn lint-css`
3. we pulled down m-c code and ran `./mach build`


```bash
```
