### ISSUE TITLE
Sourcemaps do not work for Typescript

### ISSUE THREAD

**Issue by jgonis** [devtools-html/debugger.html#2500]
Pretty much what the title says.  I have made this project public in order to offer a test case, https://gitlab.com/jgonis/nature-of-code, but when I compile my typescript files and go to, say, the Random Walker page and bring up the debugger it displays the generated Javascript file, not the typescript files that were compiled to create it.  I tested Edge and Chrome to make sure that they work correctly with the sourcemaps generated and they both do.

**Comment by wldcordeiro** [comment]
Huh weird, this project works for me and uses Typescript as well. 

http://aws-sensorweb-static-site.s3-website-us-west-2.amazonaws.com/

**Comment by jasonLaster** [comment]
Thanks @jgonis. I'm moving this bug so that it can be tracked closer to the source map package.
