### ISSUE TITLE
Stepping buttons' background is transparent

### ISSUE THREAD

**Issue by fitzgen** [devtools-html/debugger.html#2513]
Stepping buttons' background is transparent, makes it hard to see them.

<img width="622" alt="screen shot 2017-03-31 at 2 18 58 pm" src="https://cloud.githubusercontent.com/assets/74571/24569851/13fd0276-161d-11e7-95bf-3cd0cff35a57.png">

**Comment by jasonLaster** [comment]
Hmm, this should be fixed on nightly

![](http://g.recordit.co/rFeEWExk34.gif)

**Comment by fitzgen** [comment]
Any chance it could be uplifted to dev edition?
