### ISSUE TITLE
[FunctionSearch] clear query after selecting an item

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2526]
Currently we don't clear the query when you select a function from the function list.

### Patch

```diff
diff --git a/src/components/Editor/SearchBar.js b/src/components/Editor/SearchBar.js
index 7a4c581..1cd458c 100644
--- a/src/components/Editor/SearchBar.js
+++ b/src/components/Editor/SearchBar.js
@@ -410,6 +410,9 @@ const SearchBar = React.createClass({
         line: item.location.start.line,
       });

+      // clear the search ?!?!
+      this.clearSearch();
+
       this.closeSearch(e);
     }
   },

```

### GIF

![](http://g.recordit.co/Z2vjtqmAi7.gif)

**Comment by roieu** [comment]
@jasonLaster looking at this one as candidate for Capriza Hackaton

**Comment by zivkaziv** [comment]
Hi, is this issue still open?

**Comment by jasonLaster** [comment]
Yep, Go for it!

**Comment by zivkaziv** [comment]
Hey @jasonLaster, I was trying to use this.clearSearch(); to clear this field, but I think this method doesn't working (at least in chrome where I use to debug it). Do you know if I'm missing something here?

**Comment by jasonLaster** [comment]
@zivkaziv hmm, sorry - i'm not sure... 

ask in slack. Also, share some screenshots/gifs

**Comment by ofiron01** [comment]
@jasonLaster @zivkaziv sorry noticed your discussion only after submitting my PR

**Comment by Z95** [comment]
NP.. I had some problem to solve it.. so it's good that you did it:)

**Comment by zivkaziv** [comment]
NP, I had some problem to solve it.. so it good that you did it:)
