### ISSUE TITLE
[FunctionSearch] What’s the best behavior on blur?

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2528]
Currently the search bar behaves more like a permanent UI component like source tree than a modal.

There are a couple behaviors that I'd like to discuss:

1. do we want to close the search bar when you click somewhere else?
2. if we don't close it, do we still want the arrow keys (up/down) to iterate through the list

### GIF
![](http://g.recordit.co/eCJFFdQAsZ.gif)

**Comment by ruturajv** [comment]
I'd prefer clicking outside should close the search bar, even the escape key event should do that (sticks to typical flow and keybindings)

**Comment by wldcordeiro** [comment]
I don't know about clicking out closing the bar, but I do like the idea of escape closing it.

**Comment by jasonLaster** [comment]
Hmm, I got some design help earlier in the week and I think it would be nice to move the function and symbol search to a modal (command palette) similar to Atom and VS Code. 

https://code.visualstudio.com/docs/editor/editingevolved#_go-to-symbol

There are a couple of reasons for this:

1. The modal is task oriented, find and select an item
2. it doesn't push the editor down
3. it's a convention with other editors
4. we can start adding other commands to the command palette 

I'm going to close this issue as I don't think we should act on this now. What do you think @wldcordeiro @ruturajv?
