### ISSUE TITLE
 [console] Clicking a filename in the console doesn't jump to the right line

### ISSUE THREAD

**Issue by julienw** [devtools-html/debugger.html#2532]
See bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1353049

**Comment by irfanhudda** [comment]
@julienw I was about to create PR for this :slightly_smiling_face:

**Comment by julienw** [comment]
Looks like that it works if the devtools is docked at the bottom of the window, but not at the right.

**Comment by julienw** [comment]
@irfanhudda Not the same bug :) I'm talking about clicking from the Web Console here :)

**Comment by irfanhudda** [comment]
@julienw Oh. Thanks for clarifying.

**Comment by codehag** [comment]
This may have been fixed, we have had 3 people try and no one is able to reproduce
