### ISSUE TITLE
Missing  'marionetteProtocol' field / Unsupported Marionette protocol

### ISSUE THREAD

**Issue by LeslieMurphy** [devtools-html/debugger.html#2534]
I got this error when I tried to launch FF
WebDriverError: Missing 'marionetteProtocol' field in handshake

I was at FF 39.  I upgraded to 43.0.1 - debugger still not working.

Tried again at 43.0.1 
[error.txt](https://github.com/devtools-html/debugger.html/files/891056/error.txt)
and got:

WebDriverError: Unsupported Marionette protocol version 2, required 3

Please improve error handling - e.g. echo back to the page on http://localhost:8000/ this error, and link to the download for the correct version.

**Comment by jasonLaster** [comment]
Thanks @LeslieMurphy, We have talked about finding a way to set a minumum version of Firefox. In our case, I believe that is 48. Would you mind re-trying with 48+?

I'm closing this early, but would be happy to re-open if you still see this issue.

**Comment by LeslieMurphy** [comment]
Thanks.  That fixed up the first issue.  Now FF launches OK.  But I don't
see anything "interesting" in the web page after FF launches.  Maybe I am
doing something wrong?

I think I installed using NPM.  I am noticing install instructions for Yarn
now; did not see them earlier today.  Maybe I messed up my install?

[image: Inline image 1]

[image: Inline image 2]

**Comment by jasonLaster** [comment]
Hmm. Did you click the launch Firefox button and refresh?

The refresh part is a frustrating temporary bug :/

**Comment by LeslieMurphy** [comment]
I am probably doing something wrong.   Clicking the button launches a FF
instance - but nothing show up in the debugger window.  I do see this in
the console log, is it a clue?  I can confirm that TCP port 6080 is not
open

even if I hand launch FF the 6080 port does not open.  Is it maybe because
I have a 32 bit version of FF?  I can uninstall and reinstall the 64 if
that is needed.  I do have the 3 pref's set OK for the remote debugging.

firefox.exe --start-debugger-server 6080


TCP connection failed: Error: connect ECONNREFUSED 127.0.0.1:6080
WS connection closed, disconnected from TCP
TCP connection failed: Error: connect ECONNREFUSED 127.0.0.1:6080
WS connection closed, disconnected from TCP
running false
TCP connection failed: Error: connect ECONNREFUSED 127.0.0.1:6080
WS connection closed, disconnected from TCP

**Comment by jasonLaster** [comment]
Hi @LeslieMurphy, could you join our [slack](https://devtools-html-slack.herokuapp.com) so we can look into this?

**Comment by LeslieMurphy** [comment]
Yes, done.

**Comment by jasonLaster** [comment]
This was addressed in https://github.com/devtools-html/devtools-core/pull/325
