### ISSUE TITLE
Cannot read property 'Debugger' of undefined

### ISSUE THREAD

**Issue by kyleholzinger** [devtools-html/debugger.html#2543]
Whenever I start up the server and open one of the browsers, as soon as I try to navigate to one of the tabs in the debugger I get `Cannot read property 'Debugger' of undefined`. Any idea how to fix this? Totally possible I didn't start it up correctly or something

**Comment by kyleholzinger** [comment]
Looking at the server logs, I also see this:
<img width="1341" alt="screen shot 2017-04-04 at 4 41 19 pm" src="https://cloud.githubusercontent.com/assets/2652762/24677678/976b7710-1955-11e7-83ed-98b1afd127b6.png">

**Comment by wldcordeiro** [comment]
@kyleholzinger Regarding the screenshot I believe you need to listen for remote connections, open the Devtools CLI (<kbd>shift</kbd>+<kbd>F2</kbd>) and type `listen 6080`

**Comment by kyleholzinger** [comment]
Hahaha dammit you're rignt. Thanks @wldcordeiro . Maybe that should be in the docs? I didn't see a mention of it in the install guide

**Comment by wldcordeiro** [comment]
@kyleholzinger it looks like it is in our docs just not a super visible location. 🤔 https://github.com/devtools-html/debugger.html/blob/master/docs/remotely-debuggable-browsers.md#firefox
