### ISSUE TITLE
[Scopes] add properties while stepping

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2547]
@bomsy While testing this yesterday, noticed that if a property does not exist it does not get added.

![](https://cloud.githubusercontent.com/assets/792924/24701198/74da3064-19f1-11e7-8008-ba876968d437.gif)

**Comment by bomsy** [comment]
Steps to approach this
- [ ] Write a basic jest for the scope component
- [ ] Remove all dependence on  the actor id, from the server
- [ ] Move expanded cache out of managed tree into redux
