### ISSUE TITLE
'Reveal in tree' should also work for tabs with pretty printed source

### ISSUE THREAD

**Issue by Archaeopteryx** [devtools-html/debugger.html#2553]
Firefox 55.0a1 20170406030206 on Windows 8.1, also with latest 54.0a2

'Reveal in tree' doesn't work for tabs with pretty printed source.

Steps to reproduce:
1. Open http://gridbyexample.com/examples/example5/
2. Open the debugger.
3. Open the file platform.twitter.com/js/... (there is only one file).
4. Pretty print the source (either from the tab's context menu or the button at the bottom).
5. Collapse all opened folders on the left.
6. Use the tab context menu on the opened tab and use 'Reveal in tree'.

Actual result:
Nothing happens.

Expected result:
File selected in tree like it happens for the raw source tab.

**Comment by arthur801031** [comment]
I'll take a stab at this :)
