### ISSUE TITLE
Keyboard shortcut 'o' used twice: For file search and for function search

### ISSUE THREAD

**Issue by Archaeopteryx** [devtools-html/debugger.html#2554]
Firefox 55.0a1 20170406030206 on Windows 8.1, also with latest 54.0a2

The Keyboard shortcut 'o' is used twice: For file search and for function search.

functionSearch.search.key=O
sources.searchAlt.key=O

Pressing Ctrl + O always toggles the file search here.

**Comment by clarkbw** [comment]
Function search on Windows should be `ctrl+shift+O`  does that work?

**Comment by clarkbw** [comment]
I think function search is using the `symbolSearch.search.key` I'm not sure where `functionSearch.search.key` is used.

**Comment by Archaeopteryx** [comment]
`ctrl+shift+o` works in 55.0a1 where it overrides the same shortcut for opening the toolbox options (the latter ones get opened in 54.0a2). Please add the key modifiers to the localization comments in the future.

**Comment by jasonLaster** [comment]
Thanks
