### ISSUE TITLE
[OutlineView] style the list of functions

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2562]
* style the list of functions. 
  * It might be nice to show function parens too. This bug is for that separately #2735 
* jump to the source location with [`selectSource`](https://github.com/devtools-html/debugger.html/blob/master/src/actions/sources.js#L156-L158). 

This is a rough sketch of how to use previewFunction
```diff
diff --git a/src/components/Outline.js b/src/components/Outline.js
index 6b9299d..7b15730 100644
--- a/src/components/Outline.js
+++ b/src/components/Outline.js
@@ -8,6 +8,8 @@ import { getSelectedSource, getSourceText } from "../selectors";
 import { isEnabled } from "devtools-config";
 import { getSymbols } from "../utils/parser";
 import "./Outline.css";
+import previewFunction from "../shared/previewFunction";
+

 import type { Record } from "../utils/makeRecord";
 import type { SourceText } from "debugger-html";
@@ -37,7 +39,7 @@ class Outline extends Component {
   }

   renderFunction(func) {
-    return dom.li({ key: func.id }, func.value);
+    return dom.li({ key: func.id }, previewFunction(func));
   }
```

<img src='https://shipusercontent.com/beabce573cddd7574cc4555b1b13ce26/Screen%20Shot%202017-04-07%20at%201.55.14%20PM.png' title='Screen Shot 2017-04-07 at 1.55.14 PM.png' width=786>

**Comment by gabrielluong** [comment]
Gonna continue working on the outline view

**Comment by jasonLaster** [comment]
Closing this as we can handle the params in their own bug :)
