### ISSUE TITLE
[EditorPreview] Watch Expressions + Input

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2578]
We've gotten feedback that it would be great if you could save expressions quickly to "Watch Expressions". This feature adds a bottom bar to previews that let you quickly refine and save an expression.

The input initially shows the preview expression, but you can edit it to be anything.

### **Notes:**

* we can use the input styling from [conditional breakpoints]( https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/ConditionalPanel.js#L44-L50)
* save to watch expressions logic can be borrowed from the [editor context menu](https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/EditorMenu.js#L59-L64)

### Screenshot
<img width="816" alt="screen shot 2017-04-07 at 11 27 55 am" src="https://cloud.githubusercontent.com/assets/254562/24807198/55b56efc-1b85-11e7-8926-7cc58faf4cb3.png">

### Patch

```diff
diff --git a/src/components/Editor/Preview.js b/src/components/Editor/Preview.js
index 630b1b4..288d1f3 100644
--- a/src/components/Editor/Preview.js
+++ b/src/components/Editor/Preview.js
@@ -92,6 +92,8 @@ class Preview extends Component {
     });
   }

+  renderBottomBar() {}
+
   renderPreview(expression, value) {
     const root = {
       name: expression,
@@ -104,7 +106,10 @@ class Preview extends Component {
     }

     if (value.type === "object") {
-      return this.renderObjectPreview(expression, root);
+      return [
+        this.renderObjectPreview(expression, root),
+        this.renderBottomBar()
+      ];
     }

```

**Comment by ruturajv** [comment]
Just so that I'm clear... Its like adding a `watch` but instead of a variable, we're watching an `expression`...  ie `isCrazy || isGeek` ? @jasonLaster

**Comment by jasonLaster** [comment]
haha, that's correct

**Comment by jasonLaster** [comment]
We landed the first part of the preview bottom bar:

- [ ] Lets improve the watch button with (style, localization, tooltips)
- [ ] Fix the case with member expressions :)

**Comment by jasonLaster** [comment]
moving this to the enhancements board as it's a nice to have and fairly complicated.

https://github.com/devtools-html/debugger.html/projects/5
