### ISSUE TITLE
[FunctionSearch] Switch to a  modal

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2587]
Many of our peers (vscode, atom, chrome) use a modal for searching. The modal is useful for function, variable (symbol), and command search (command palette), it is also used for searching for files.

I think we should adopt this convention as well.

Steps:

1. create a modal (Command Palette) that is fixed to the top of the debugger
2. Use our autocomplete and results list UI in the modal
3. have our search for function and variables button launch the modal

<img src='https://shipusercontent.com/cbe5d33b9fce29f73f191ac5108f80a7/command%20palette.jpg' title='command palette.jpg' width=1422>

**Comment by jasonLaster** [comment]
@wldcordeiro is working on it

**Comment by wldcordeiro** [comment]
Bumping. I've got a local branch with a lot of work done. I've just been busy starting a new job. Should PR soon. 😄

**Comment by jasonLaster** [comment]
closing, i think this is in a great spot!
