### ISSUE TITLE
[Editor] Highlight functions

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2590]
One nice thing that VS Code does when you're searching for a function is highlight the function and signature and body. They do it with an off putting yellow, but i think the principle is good.

Lets try and add a similar function to our editor with codemirror.

### Notes

* **getting function locations** We've already done the hard work by parsing the file and getting functions with `getSymbols`. Symbols returns a list of functions. Here's one functions data, which has the start and end location for the entire function.

```json
{
  "id": "initialize:32",
  "title": "initialize",
  "subtitle": ":32",
  "value": "initialize",
  "location": {
    "start": {
      "line": 32,
      "column": 14
    },
    "end": {
      "line": 36,
      "column": 3
    }
  }
}
```

* **highlighting lines** there are two ways i can think of when it comes to highlighting the function. The first is to use the highlighter from search, which operates on the token level. The second way is to add a class to each line of the function, with a special class for the first and last line probably. This approach is similar to how we highlight the current debug line. I think this approach is the cleanest.

it'd look something like this:

```js
highlightFunction(function) {
   this.highlightedFunction = function;
   const {location: {start, end}} = function;
   const [firstLine, ...lines, lastLine] = // get array of lines
   firstLine.addClass()
   lines.forEach()
   lastLine.addClass
}
```

sadly, we'd also have to do the same thing when it comes to unhighlighting the function as well. We'll need to do some cleanup when the selected source changes and the highlight is removed.

### GIF

<img width="1079" alt="screen shot 2017-04-07 at 7 58 40 pm" src="https://cloud.githubusercontent.com/assets/254562/24823489/c181eb3c-1bcc-11e7-8851-c67a96991c02.png">

**Comment by jcreighton** [comment]
Grabbing this one!

**Comment by jasonLaster** [comment]
@jcreighton  alright - but you have to pick the highlight color! :P

**Comment by clarkbw** [comment]
I think this was done in #2717
