### ISSUE TITLE
[scopes] bucket properties alphabetically

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2603]
We currently bucket properties when there are more than 100 properties. This is good for finding what you're looking for, but not great when looking for keys in a large object.

It would be nice if instead of showing a numeric index, we did an alphabetic range:

#### New

<img width="248" alt="screen shot 2017-04-09 at 12 43 26 pm" src="https://cloud.githubusercontent.com/assets/254562/24839086/6a9676c4-1d22-11e7-8348-53698d5ffc69.png">

#### Old

<img width="296" alt="screen shot 2017-04-09 at 12 45 43 pm" src="https://cloud.githubusercontent.com/assets/254562/24839087/7747ad7a-1d22-11e7-8df6-bac2ac47188b.png">

#### Patch

```diff
diff --git a/src/utils/object-inspector.js b/src/utils/object-inspector.js
index 478973a..b757d74 100644
--- a/src/utils/object-inspector.js
+++ b/src/utils/object-inspector.js
@@ -95,6 +95,7 @@ function makeNodesForProperties(
   if (numProperties > bucketSize) {
     const numBuckets = Math.ceil(numProperties / bucketSize);
     let buckets = [];
+    // here's the bucketing logic
     for (let i = 1; i <= numBuckets; i++) {
       const bucketKey = `bucket${i}`;
       const minKey = (i - 1) * bucketSize;
diff --git a/src/utils/tests/object-inspector.js b/src/utils/tests/object-inspector.js
index 982d4bd..028d60d 100644
--- a/src/utils/tests/object-inspector.js
+++ b/src/utils/tests/object-inspector.js
@@ -98,6 +98,7 @@ describe("object-inspector", () => {
       expect(paths).to.eql(["root/bar", "root/__proto__"]);
     });

+    // we should also have a test for alphabetic bucketing
     it("bucketing", () => {
       let objProps = { ownProperties: {} };
       for (let i = 0; i < 331; i++) {
```

**Comment by jasonLaster** [comment]
Hmm, after thinking about it a bit more I can see a couple of problems with this approach:

1. keys are often **not** ordered alphabetically. 
2. keys can be numerical
3. keys can be prefixed with an underscore...

I'm now leaning towards not bucketing object properties and only bucketing arrays

**Comment by clarkbw** [comment]
I think that makes sense.  I still like the idea of bucketing the window object into two: custom and default properties.  However that's an optimization that can be done down the line.

**Comment by jasonLaster** [comment]
@bomsy is working on that optimization now :)
