### ISSUE TITLE
[SourceTree] fails to render the root directory 

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#2614]
STR:

1. go to https://davidwalsh.name/

---

URLs:

```js
urls = Object.values(appStore.getState().sources.sources.toJS()).map(s => s.url)
```

---

There's a test below that isolates the behavior. The problem comes from the root directory appearing below another source below the root.

**Comment by darkwing** [comment]
Been super busy but had a moment to look at and was introduced here:

https://github.com/devtools-html/debugger.html/commit/2c22306d9d9c4680bd48375fa80c5e7f531cbc1e

Will continue looking into it

**Comment by darkwing** [comment]
Also important to note it happens in both Chrome and Firefox, so it's not isolated to the Chrome or Firefox files.

**Comment by jasonLaster** [comment]
Here is the start of a test

```js
const {
  initDebugger,
  reload,
  selectSource,
  waitForDispatch
} = require("../utils");

function countTabs(dbg) {
  return dbg.selectors.getSourceTabs(dbg.getState()).size
}

module.exports = async function(ctx) {
  const { ok, is, info, requestLongerTimeout } = ctx;

  const dbg = await initDebugger("doc-scripts.html");


  selectSource(dbg, "simple1");
  selectSource(dbg, "simple2");

  expect(countTabs(dbg)).to.equal(2);

  await reload(dbg);
  expect(countTabs(dbg)).to.equal(2);
};

```

**Comment by jasonLaster** [comment]
Here's a test. Notice the index comes second:
https://gist.github.com/jasonLaster/99fb7bd80f5537358a934f0ece63f0dc

Here's the failure:

```
    { name: 'root',
      path: '',
      contents:
       [ { name: 'davidwalsh.name',
           path: '/davidwalsh.name',
           contents: [Object] },
         { name: 'davidwalsh.name',
           path: '/davidwalsh.name',
           contents: [Object] } ] }
```

Notice two directories `'/davidwalsh.name'` `'/davidwalsh.name'`. This does not happen if the index comes second.

**Comment by jasonLaster** [comment]
This might not be an issue any more: I'm no longer seeing console errors: This is what the tree looks like for me

<img src='https://shipusercontent.com/2b725507b68095ff19d2d5326e493347/Screen%20Shot%202017-06-14%20at%207.57.02%20AM.png' title='Screen Shot 2017-06-14 at 7.57.02 AM.png' width=902>


---

Revision: chrome's tree has a demos directory that's missing in ours


<img src='https://shipusercontent.com/6e64918f51debe498e48eaddaf0e419f/Screen%20Shot%202017-06-14%20at%207.58.31%20AM.png' title='Screen Shot 2017-06-14 at 7.58.31 AM.png' width=198>

**Comment by codehag** [comment]
@darkwing -- can you let me know which files are missing? Are you expecting to see files other than JS?

@jasonLaster the files that are not showing up are not js files, do we want to show those?
