### ISSUE TITLE
Last Closed Tab Opens Upon Load

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#2615]
-  I had two files opened within the top tab bar.  
-  I closed both of them (all file tabs closed, 
-  I refreshed the page
-  The last file I closed was opened in the tab bar by default.

**Comment by jasonLaster** [comment]
haha - that's a fun bug. 

This happens because the `sources.selected_source` location probably doesn't get cleared

**Comment by bomsy** [comment]
STR

Add 2 tabs
Remove the currently selected one
Refresh
AR:

It shows 2 tabs

ER:

Should be 1 tab
