### ISSUE TITLE
[Chrome] Chrome debugger fails to initialize

### ISSUE THREAD

**Issue by mquander** [devtools-html/debugger.html#2616]
When trying to start the debugger on a Chrome tab, the destructuring assignment in [chrome.js](https://github.com/devtools-html/debugger.html/blob/2c22306d9d9c4680bd48375fa80c5e7f531cbc1e/src/client/chrome.js#L7) fails every time, so it won't start. This seems to have been caused by https://github.com/devtools-html/debugger.html/pull/2478 and the associated refactoring to move things into devtools-launchpad.

![image](https://cloud.githubusercontent.com/assets/428637/24887270/621c4012-1e0f-11e7-8ea8-cf6a47d0022b.png)

**Comment by jasonLaster** [comment]
Great Fix!

We would love to improve our chrome variable support.
