### ISSUE TITLE
[Testing] Add a jest test for a react component

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2618]
One of the best things about Jest is the ecosystem around testing react components. We have some components that would really benefit from unit testing like `functionPreview`.

This issue is for getting a unit test for **any** component in so that we have the pattern for testing other components in the future.

**Comment by AnshulMalik** [comment]
Tried something for testing react components, this method uses enzyme to make testing react components less painful

```
import { createFactory } from "react";
import { shallow } from "enzyme";
import Close from "../../components/shared/Button/Close";

const CloseButton = createFactory(Close);

describe("CloseButton", () => {
  it("should call handleClick function", () => {
    const onClick = jest.genMockFunction();
    const wrapper = shallow(new CloseButton({ handleClick: onClick }));

    wrapper.find(".close-btn").simulate("click");

    expect(onClick).toBeCalled();
  });
});
```

**Comment by jasonLaster** [comment]
I tried to use this test and got an error

```
Time:        1.089s
Ran all test suites matching "src/components".
  console.error ../node_modules/enzyme/build/react-compat.js:131
    react-addons-test-utils is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation
```

This is exactly the kind of test I would like to see in the codebase

perhaps we render and simulate with reacts renderer's https://facebook.github.io/react/docs/test-utils.html

The other style test that we should have is where we render the component to JSON and save it as a fixture.

We should PR this style and also the fixture style!

**Comment by AnshulMalik** [comment]
React also recommenda the use of Enzyme. It   requires `react-addon-test-utils` package to be installed manually.

Also enzyme requires react-dom v15
4.2, we have 15.3.2. And upgrading it breaks the existing test cases. So need to find some workaround.

@jasonLaster Enzyme also has functionality to test against snapshot. So we test and save it's state and next time use it to check if something has changed.

**Comment by jasonLaster** [comment]
Great write up. I know this is possible as these testing solutions predate 15.4

**Comment by stefb965** [comment]
1
