### ISSUE TITLE
Add "Sources" label above source tree

### ISSUE THREAD

**Issue by helenvholmes** [devtools-html/debugger.html#262]
Specifically, this one: 
<img width="328" alt="screen shot 2016-06-16 at 11 41 32 am" src="https://cloud.githubusercontent.com/assets/1720093/16114086/53e8e42a-33b7-11e6-85a6-d8631e60d0fc.png">

James and I have gone back and forth a _bunch_ on this area. I liked having space above that area for [purely visual reasons](http://cl.ly/0a1n2h2N402P), but without a clear direction for functionality perhaps we should remove it.

For prosperity, we've chatted mostly about using that area for a "Filter Sources" area, although that will probably overlap with some pretty common keyboard shortcuts that people will probably get more mileage on.

@jlongster + @jasonLaster: If the two of you truly feel a filter (or, whatever else we can come up with), perhaps we should remove it—elsewise, let's use this space to chat what might become of it.

**Comment by jasonLaster** [comment]
I'm in favor of removing it.

**Comment by helenvholmes** [comment]
@jlongster, any opinions? If you're in favor as well let's switch this to removing the area until further notice.

**Comment by jlongster** [comment]
Yeah we can remove it! I did that once and it looked a little weird, but maybe that's just because I'm used to it.

**Comment by helenvholmes** [comment]
I think we're all used to it, but it's empty space that we're not using at the moment.

Let's remove it until further notice 😪

**Comment by amitzur** [comment]
I just opened the debugger for the first time, and when I saw this space I immediately tried to focus on it for filtering files :)
So filter is oh so natural there, however that might have happened because I was looking for this functionality, and couldn't find it elsewhere. Plus, the space exists so it made sense for me to look for functionality there. If it didn't exist, maybe I wouldn't look for it there.

**Comment by ilancohen** [comment]
Can I just fix this (or other beginner bugs) and do a pull request? Is there somewhere where I can see who's working on each issue?
(Sorry for the beginner questions.)

**Comment by jasonLaster** [comment]
Hi @ilsncohen. Go for it!

**Comment by helenvholmes** [comment]
@ilancohen, I'll assign you to the bug.

**Comment by helenvholmes** [comment]
Just renamed this bug for the third time. Some explanation if you don't want to read everything already in the bug:

The area above the source tree was originally a filter, which seemed redundant. We weren't sure if we wanted it or not.

<img width="631" alt="screen shot 2016-06-30 at 11 10 37 am" src="https://cloud.githubusercontent.com/assets/1720093/16493401/553f0384-3eb3-11e6-87c5-37d9a4840d60.png">

We removed it in #262, although now the space seems like it's floating. (See comment 0, ["purely visual reasons"](http://cl.ly/0a1n2h2N402P).

<img width="395" alt="screen shot 2016-06-30 at 11 12 51 am" src="https://cloud.githubusercontent.com/assets/1720093/16493480/9cb0ae16-3eb3-11e6-9bcc-e4e7aaf5b68d.png">

Working suggestion for this is that we bring the Sources header area back and put "Sources" in it. Just a label, with the idea that the space will eventually become tabs, or a filter input, or something else.

**Comment by ilancohen** [comment]
@helenvholmes - I'll put that header (back) in.

**Comment by helenvholmes** [comment]
@ilancohen Thank you very much! Sorry for the long backstory—really appreciate you doing the work.

**Comment by ilancohen** [comment]
@helenvholmes no, I'm happy to get the backstory! I just got into this project through Jason, and it's bnice to understand where things are coming from/going to.

**Comment by clarkbw** [comment]
@ilancohen looking at #135 and 62213c95c7320c4ea33f09faada5874e75c8228c where the original filter was added I think you can copy out this CSS:

```CSS
.sources-header {
   height: 30px;
   border-bottom: 1px solid var(--theme-gray);
  color: var(--theme-splitter-color);
  padding-left: 10px;
  line-height: 30px;
  font-size: 0.9em;
}
```

And add in the extra dom element needed before the SourceTree here: https://github.com/jlongster/debugger.html/blob/master/public/js/components/Sources.js#L25

Just update the tests and you'll be done.

**Comment by clarkbw** [comment]
This seems to have stalled out, I'm going to pick this up for now.
