### ISSUE TITLE
[CodeFolding] style closed markers

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2626]
1. use the devtools orange theme
2. update the devtools collapse icon to be similar to atoms...
  note cmd+option+i in atom opens atom's devtools! you can steal their collapse badgey thing 

### screenshot

<img width="633" alt="screen shot 2017-04-11 at 3 39 00 pm" src="https://cloud.githubusercontent.com/assets/254562/24927463/21cb33e2-1ecd-11e7-8067-9d9c7bb305bd.png">

### notes

Here's the location of the fold marker CSS: https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-source-editor/src/source-editor.css#L180-L224

**Comment by jasonLaster** [comment]
@samjwalker is working on this

**Comment by samjwalker** [comment]
This is how atom does it.

![capture2](https://cloud.githubusercontent.com/assets/15427172/24953626/ea76fbcc-1f73-11e7-8cf9-1f90cd85cf44.PNG)

Please could you explain what you mean by the yellow theme since I can't find an option for it.

**Comment by wldcordeiro** [comment]
@samjwalker I think @jasonLaster meant using one of our theme variables that is orange. I'd guess either `--theme-graphs-orange` or `--theme-highlight-lightorange`

**Comment by jasonLaster** [comment]
yep, definitely a variable if we have a good one for it. Otherwise, we can try and find something else that works

**Comment by jasonLaster** [comment]
This has gone stale, so i'll move it to enhancements

https://github.com/devtools-html/debugger.html/projects/5
