### ISSUE TITLE
How can we improve information hierarchy in the right sidebar?

### ISSUE THREAD

**Issue by helenvholmes** [devtools-html/debugger.html#263]
Sorry for the huge gif, but I think it illustrates pretty well what I think the guiding principles for the right sidebar in the debugger:

![2016-06-16 14_02_13](https://cloud.githubusercontent.com/assets/1720093/16117642/01b2f434-33cb-11e6-8334-084a36a74faa.gif)

I'll work on this and attach some designs to discuss.

**Comment by jlongster** [comment]
Sounds good!

**Comment by clarkbw** [comment]
@helenvholmes can you break this down into a single component you want to approach first?  like the scopes list? or breakpoints?

Or is this more of a general design approach?  (just trying to make this more actionable)

**Comment by helenvholmes** [comment]
I'm going to close out this issue—we tackled some of what this bug was looking to improve in #876, and additional improvements probably merit their own, more specific issues.
