### ISSUE TITLE
[Tabs] tabs are no longer persisted on refresh

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2638]
STR:
1. go to http://devtools-html.github.io/debugger-examples/examples/todomvc/
2. select two sources
3. refresh the debugger

AR: you see the selected source
ER: you see both tabs

here is a test that demonstrates the regression:

One way to work on this is to go to `localhost:8000/integration` and fix the tabs test:

```patch

diff --git a/src/test/integration/runner.js b/src/test/integration/runner.js
index 46f07f0..e2fff6a 100644
--- a/src/test/integration/runner.js
+++ b/src/test/integration/runner.js
@@ -153,7 +153,7 @@ describe("Tests", () => {
     await sourceMapsBogus(ctx);
   });

-  it("tabs", async function() {
+  it.only("tabs", async function() {
     await tabs(ctx);
   });
 });
diff --git a/src/test/integration/tests/tabs.js b/src/test/integration/tests/tabs.js
index cd35d34..b1a28db 100644
--- a/src/test/integration/tests/tabs.js
+++ b/src/test/integration/tests/tabs.js
@@ -21,6 +21,5 @@ module.exports = async function(ctx) {
   await reload(dbg, "simple2");
   await waitForDispatch(dbg, "LOAD_SOURCE_TEXT");

-  // NOTE: when we fix persisted tabs we should have two
-  expect(countTabs(dbg)).to.equal(1);
+  expect(countTabs(dbg)).to.equal(2);
 };
 ```

**Comment by AnshulMalik** [comment]
I can't reproduce this issue, works fine here.

**Comment by bomsy** [comment]
I see the issue, it seems like it persist sometimes and does not the others

**Comment by jasonLaster** [comment]
oh strange. I wonder what cases it's persisted in...

**Comment by bomsy** [comment]
So far what i see is that removing the currently selected tab does not persist..

**Comment by bomsy** [comment]
##### STR
* Add 2 tabs
* Remove the currently selected one
* Refresh


##### AR: 
 It shows 2 tabs
##### ER: 
Should be 1 tab

**Comment by jasonLaster** [comment]
haha - sounds like a related but different bug!

**Comment by bomsy** [comment]
Hahaaa
