### ISSUE TITLE
Style call stack logos

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2659]
We're now showing library logos in the call stack for (backbone, jquery, react). It would be nice to style them a bit so that it is polished:

- [ ]  line them up with the text
- [ ] color them white when the frame is selected

this is likely a fill property on the svg

#### How to get started

1. backbone, jquery: debug todomvc in the examples app and add a breakpoint in todo-view.js
2. react, debug the sample react app in examples

#### screenshot

<img width="300" alt="backbone call stack" src="https://cloud.githubusercontent.com/assets/254562/25046210/442e7560-20fe-11e7-8b27-753b460725b8.png">

**Comment by PunitGr** [comment]
I'd love to help!

**Comment by jasonLaster** [comment]
@PunitGr great! Stop by and ask any questions in slack

**Comment by PunitGr** [comment]
Hi @jasonLaster, does this work?

![screen shot 2017-04-20 at 12 16 47 pm](https://cloud.githubusercontent.com/assets/9111111/25217117/49c3fdd2-25c3-11e7-9257-2388ce6e8a72.png)

**Comment by AnshulMalik** [comment]
Hey @PunitGr , this looks awesome. Create a PR :)
