### ISSUE TITLE
Is it possible to use this inside a page as a component?

### ISSUE THREAD

**Issue by serapath** [devtools-html/debugger.html#2663]
I saw there is https://www.npmjs.com/package/debugger.html as an npm module.

Is or will there be some way for doing something like:

```js
var debuggerHTML = require('debugger.html')
debuggerHTML(function (el, api) {
  document.body.appendChild(el)
  // maybe interact with the debugger.html instance through it's api
})
```

I don't know about the API that would make most sense, but I already see terminal/console components and editor components and file tree components which can be included in a web app. It would be kind of cool to also have the option to add debugger and all kinds of other devtools as components to be able to use them in web apps :-)

**Comment by jasonLaster** [comment]
We've got some demos of the debugger running in Emacs and could do the same with Atom.

We haven't done much on this front, but have designed the APIs so you could either drop it in and connect to node or a browser with our Redux backend or use our utils or UI.

Stop by our slack and we can discuss!
