### ISSUE TITLE
[Editor] Right clicking on the gutter should not add a breakpoint

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2668]
right clicking on the gutter should open the context menu with the menuitem to "Add a breakpoint".

It looks like we're currently adding the breakpoint pre-maturely :)

The issue is likely [here]

[here]: https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/index.js#L403-L423

**Comment by sarahlim** [comment]
I just cloned and I'm having trouble replicating this:

![gif of left clicking to add a breakpoint, right clicking to open context menu w/o adding breakpoint](https://media.giphy.com/media/3o7bu2sehHjuq2l8nm/giphy.gif)

Left clicking produces a breakpoint as expected. Right clicking opens the context menu, no breakpoint appears in the UI, and Redux devtools don't log an `ADD_BREAKPOINT` action.

I'm new, so I might be doing something wrong!

**Comment by jasonLaster** [comment]
Haha. That's awesome. I'll try and find the edge case :)

**Comment by jasonLaster** [comment]
Also, how'd you get redux Dev tools?

**Comment by sarahlim** [comment]
Main repo [here](https://github.com/gaearon/redux-devtools), browser extensions [here](https://github.com/zalmoxisus/redux-devtools-extension)!

**Comment by jasonLaster** [comment]
Thanks @sarahlim I'm using the redux devtools and love it now!

I investigated the bug and it looks like it only happens on chrome :)

![](http://g.recordit.co/tpHV5JQ0ad.gif)

**Comment by sarahlim** [comment]
> it only happens on chrome

Bizarre, my GIF was recorded in Chrome (definitely), 57.0.2987.133 (I think).

I'll check again when I'm not supposed to be studying for midterms!

**Comment by jasonLaster** [comment]
Haha. I'll also investigate some more.

**Comment by jasonLaster** [comment]
Hey @sarahlim just checking in. Do you have any time to investigate?

**Comment by jasonLaster** [comment]
Ping @sarahlim do you have time to look into this? If not no worries

**Comment by sarahlim** [comment]
Hi @jasonLaster -- so sorry for the radio silence. I'm a bit swamped right now, but if this is still happening after school is out for the year, happy to give it another go then!

**Comment by jasonLaster** [comment]
That's alright. It's not a priority. Talk to you soon :)

**Comment by sarahlim** [comment]
It's working for me on Chrome 58.0.3029 as well, both regular and incognito mode. What version is causing the error for you?
