### ISSUE TITLE
Object inspector doesn't get expanded with Watch Expression on very large object

### ISSUE THREAD

**Issue by bgrins** [devtools-html/debugger.html#2671]
STR:

* Open https://s3.amazonaws.com/mozilla-games/ZenGarden/EpicZenGarden.html
* Click the pause button to pause on next tick
* Once paused, add a new watch expression: `Module`
* Attempt to expand the object

Expected:
* The object is expanded and properties show up below 

Actual:
* Nothing shows up below.  The tab also seems to hang even after resuming execution.

I'm sure this'll need some profiling.  Note this is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1348761 with the same object causing the Variables View to hang.

**Comment by jasonLaster** [comment]
Thanks for filing this. I can profile this in a bit, one of the advantages of the new Object Inspector is that we'll bucket large arrays and objects. 

My guess is that this is server related.

**Comment by bgrins** [comment]
I think this will get fixed by a server-side patch in https://bugzilla.mozilla.org/show_bug.cgi?id=1348761

**Comment by jasonLaster** [comment]
nice find: https://reviewboard.mozilla.org/r/132128/diff/1#index_header
