### ISSUE TITLE
Toggle pane button is positioned incorrectly in RTL layout

### ISSUE THREAD

**Issue by irfanhudda** [devtools-html/debugger.html#2676]
### Screenshot
![rtl-bug](https://cloud.githubusercontent.com/assets/1755089/25139844/1044f004-247c-11e7-99b0-d503d094dd9d.png)

There are two problems with above RTL layout
+ [x] Toggle pane button for secondary pane (`.toggle-button-end`) should be aligned to the left. (may require a change to [`PaneToggle.css`](https://github.com/devtools-html/debugger.html/blob/master/src/components/shared/Button/PaneToggle.css#L20)) #2770
+ [ ] Splitter appears to stop before command-bar (Some problem with borders?)

**Comment by jasonLaster** [comment]
Nice find!

**Comment by sharathnarayanph** [comment]
Hey guys! I am new to the project. I have been playing around with the code for few days now and I would like to jump in. Is it okay if I start working on this issue?

**Comment by jasonLaster** [comment]
Go for it!

**Comment by jasonLaster** [comment]
Join us in slack if you have questions

**Comment by sharathnarayanph** [comment]
Thanks Jason!
