### ISSUE TITLE
remove feature flag for Watch Expressions 

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#2678]
We've shipped Watch Expressions so its time to remove the feature flag for it.

Here's a [search](https://github.com/devtools-html/debugger.html/search?utf8=%E2%9C%93&q=watchExpressions&type=) of all the usage of the key `watchExpressions`.  

We need to remove all references to that key and make sure watch expressions are now on by default.

**Comment by andreicristianpetcu** [comment]
Can I work on this one also? @clarkbw

**Comment by AnshulMalik** [comment]
Go ahead @andreicristianpetcu

**Comment by andreicristianpetcu** [comment]
[done](https://github.com/devtools-html/debugger.html/pull/2762) @AnshulMalik
