### ISSUE TITLE
remove feature flag for search modifiers

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#2685]
We've shipped Search Modifiers so its time to remove the feature flag for it.

Here's a [search](https://github.com/devtools-html/debugger.html/search?utf8=%E2%9C%93&q=searchModifiers&type=) of all the usage of the key `searchModifiers`.  

We need to remove all references to that key and make sure search modifiers are now on by default.

**Comment by andreicristianpetcu** [comment]
Can I work on this? @clarkbw

**Comment by jasonLaster** [comment]
Go for it @andreicristianpetcu

**Comment by jasonLaster** [comment]
You can see other recent PRs

**Comment by andreicristianpetcu** [comment]
[Good tip](https://github.com/devtools-html/debugger.html/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20remove%20feature%20flag%20)! Thank you @jasonLaster
