### ISSUE TITLE
remove feature flag for symbol search

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#2686]
We've shipped Symbol Search so its time to remove the feature flag for it.

Here's a [search](https://github.com/devtools-html/debugger.html/search?utf8=%E2%9C%93&q=symbolSearch&type=) of all the usage of the key `symbolSearch`.  

We need to remove all references to that key and make sure the feature is now on by default.

**Comment by fujifish** [comment]
Working on this
