### ISSUE TITLE
remove feature flag for editor preview

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#2687]
We've shipped Editor Hover / Preview so its time to remove the feature flag for it.

Here's a [search](https://github.com/devtools-html/debugger.html/search?utf8=%E2%9C%93&q=editorPreview&type=) of all the usage of the key `editorPreview`.  

We need to remove all references to that key and make sure the feature is now on by default.

**Comment by fujifish** [comment]
Will be working on this
