### ISSUE TITLE
remove feature flag for show source

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#2688]
We've shipped the Show Source feature so its time to remove the feature flag for it.

Here's a [search](https://github.com/devtools-html/debugger.html/search?utf8=%E2%9C%93&q=showSource&type=) of all the usage of the key `showSource`.  

We need to remove all references to that key and make sure the feature is now on by default.

**Comment by adamki** [comment]
Hi all. New to the repo and would love to take a shot at completing this. 

Looks like we need to remove all the use cases for `showSource` and ensure that we enable default use with something like this:

```
"showSource" : {
   "label": "Show Source",
   "enabled": true
}
``` 
It looks like this change will need to be added to various `config` files. Are there any guides that I can reference regarding `config`? Having a bit of trouble discerning which config files will need the snippet above.

**Comment by clarkbw** [comment]
Hmm, it looks like #1765 partially removed the `showSource` flag but there is just one piece left over.  Looks like a lot smaller change now.  Feel free to grab one of the other as well!

**Comment by clarkbw** [comment]
@adamki do you still want this one or want to take something like #2678 watch expressions instead?

**Comment by adamki** [comment]
Im still on it. 

I've removed all the found instances of `showSource`. Mostly, i am still a bit unclear about the process of setting the showSource feature to default/if this still needs to be done. Am I correct in thinking that if the `showSource` feature has been shipped, that it no longer needs to be explicitly enabled? 

Sorry for the redundant question. Still learning how the feature configs work.

Also, once I finish this, i would be happy to do the same with the other feature flags here: [#2689](https://github.com/devtools-html/debugger.html/issues/2689)

**Comment by clarkbw** [comment]
I think what you mentioned in https://github.com/devtools-html/debugger.html/issues/2688#issuecomment-297192438 is the only remaining reference to `showSource`

Take a look at this PR for watch expressions: #2762 and you'll see more of how the `isEnabled` flags are used to toggle features.

And it seems like most of the others from #2689 might be taken already 😿 We can find something else.

**Comment by adamki** [comment]
There is a pending PR on [this](https://github.com/devtools-html/debugger.html/pull/2766). But there is a small git conflict. I tried rebasing and ran into some issue(likely my bad as im new to rebasing) and will look into it further once I have a bit more time. I just wanted to let others know if they have the desire to take a look at this issue.
