### ISSUE TITLE
[Sources] Show react file icons in the tree

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2690]
It would be super cool if we could show relevant file icons in the sources tree. One example of this would be the React logo next to React components.

#### Plan

I think we could add the logo if two things are true:

1. the file is inside a components directory
2. we detect that `react` is loaded

Basically if it's a component of a react app. 

Down the road we can be more thorough and check the source text as well for some indicators like the file has react imported and is using `createClass` or `Component`.

#### Patch

Here is a simple patch that shows how we could swap out all JS files for React, but in practice we'll want to be a bit smarter.

```diff
diff --git a/src/components/SourcesTree.js b/src/components/SourcesTree.js
index 12ab597..d30c339 100644
--- a/src/components/SourcesTree.js
+++ b/src/components/SourcesTree.js
@@ -157,6 +157,9 @@ class SourcesTree extends Component {
     }

     if (!nodeHasChildren(item)) {
+      if (item.contents.get("url").match(/js/)) {
+        return Svg("react");
+      }
       return Svg("file");
     }

diff --git a/src/components/shared/Svg.css b/src/components/shared/Svg.css
index 2627c91..e72c3b6 100644
--- a/src/components/shared/Svg.css
+++ b/src/components/shared/Svg.css
@@ -32,6 +32,14 @@
   width: 15px;
 }

+.react svg {
+  width: 12px;
+}
+
+.react path {
+  fill: var(--theme-highlight-blue);
+}
+
```

#### Screenshot (prototype)

![react sources.png](https://shipusercontent.com/64e415fbedb318657896999c7205f51c/react%20sources.png)

**Comment by andreicristianpetcu** [comment]
Can I pick this up?

**Comment by jasonLaster** [comment]
@andreicristianpetcu it's yours!

**Comment by noamkatzir** [comment]
I will take it

**Comment by andreicristianpetcu** [comment]
I did not have time to work on this task and I'm glad @noamkatzir had but please in the future pick tasks that have the [available](https://github.com/devtools-html/debugger.html/issues?q=is%3Aopen+is%3Aissue+label%3Aavailable) lable and not the in progress label.

**Comment by jasonLaster** [comment]
Sorry @andreicristianpetcu I was at a meetup last night and missed the label.

**Comment by andreicristianpetcu** [comment]
No problem :) @jasonLaster

**Comment by jasonLaster** [comment]
adding this to the enhancements board:

https://github.com/devtools-html/debugger.html/projects/5
