### ISSUE TITLE
[preview] don’t show undefined values

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2691]
<img src='https://shipusercontent.com/aa54fe52842946ec3480e9777577f712/Screen%20Shot%202017-04-19%20at%204.21.06%20PM.png' title='Screen Shot 2017-04-19 at 4.21.06 PM.png' width=537>

**Comment by jasonLaster** [comment]
@peterschussheim  is working on it

**Comment by peterschussheim** [comment]
@jasonLaster Recorded a demo of the patch I am working on, resolving unit and snapshot failures now and will open PR shortly.

![Image of test](http://g.recordit.co/Ad5kC1bOEI.gif)

**Comment by jasonLaster** [comment]
nice, looks great!
