### ISSUE TITLE
[preview] show boolean values in the tooltip

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2692]
They are simple enough to show in the tooltip like what we do with functions

**Comment by peterschussheim** [comment]
Can I take this one?

**Comment by peterschussheim** [comment]
Made a simple example that returns true and false booleans to demonstrate the **current behavior**:

![testing-bools](http://g.recordit.co/JZYvJOmRKp.gif)

As shown in the capture:
- currently show preview when an expression evaluates to `true`

**Comment by jasonLaster** [comment]
Nice. Perhaps add it to the debugger examples repo?

**Comment by peterschussheim** [comment]
Sure!

**Comment by peterschussheim** [comment]
@jasonLaster, not sure if this is relevant but noticed `getExpressionValue` is returning `undefined` to callee in Editor/index.js line 770 when given a `false` value:


![google chrome017](https://cloud.githubusercontent.com/assets/3654683/26001731/621d47e6-36fb-11e7-96b0-119a54fb2b68.jpg)

I'm wondering if this function would return something other than undefined, showing a false value would be easier.  Any thoughts?

**Comment by jasonLaster** [comment]
haha - love the thought bubble.

Yeah, why is it undefined. It would be really nice to have `false`

**Comment by peterschussheim** [comment]
@jasonLaster Made some progress, however, as shown in the screenshot below, a `TypeError` is thrown when hovering over a `Function`:
![google chrome021](https://cloud.githubusercontent.com/assets/3654683/26081382/87e043bc-3998-11e7-86d1-fd39888dc96d.jpg)

## Current changes:
```javascript
diff --git a/src/components/Editor/index.js b/src/components/Editor/index.js
index df440c06..b35a45e1 100644
--- a/src/components/Editor/index.js
+++ b/src/components/Editor/index.js
@@ -770,7 +770,7 @@ class Editor extends PureComponent {
       getExpression: this.props.getExpression
     });

-    if (!value || value.type == "undefined") {
+    if (value.type == "undefined") {
       return;
     }

diff --git a/src/utils/editor/expression.js b/src/utils/editor/expression.js
index 039ffe24..3e02a44b 100644
--- a/src/utils/editor/expression.js
+++ b/src/utils/editor/expression.js
@@ -84,7 +84,7 @@ export function getExpressionValue(
   { getExpression }: Object
 ) {
   const variableValue = get(selectedExpression, "contents.value");
-  if (variableValue) {
+  if (typeof variableValue === "boolean" || variableValue) {
     return variableValue;
   }
```

## Screenshot:
![screen](http://g.recordit.co/9SSC0pSTDc.gif)

**Comment by jasonLaster** [comment]
Hmm, mind opening a PR so we can look?
