### ISSUE TITLE
[blackbox] it’s not hiding react-with-addons frames

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2710]
STR:
1. go to https://codepen.io/gaearon/pen/VbvBWg?editors=0010
2. navigate to react-with-addons.js in the debugger
3. blackbox the source
4. navigate to index.html
5. add a breakpoint on line 250
6. click in a tic tac toe box

AR: see all the frames
ER: see only index.html frames

**Comment by clarkbw** [comment]
I'm not seeing anything other than the index.html frames anymore.  

Here's a screenshot from today's Nightly:

<img width="1184" alt="screen shot 2017-06-05 at 4 49 07 pm" src="https://cloud.githubusercontent.com/assets/2134/26808023/fd5cdeb2-4a0e-11e7-9709-220f12b63123.png">
