### ISSUE TITLE
[Tabs] We show closed tabs when we reload

### ISSUE THREAD

**Issue by bomsy** [devtools-html/debugger.html#2715]
After the debugger is refreshed, 
* Close the active tab

AR:  The source text for the next selected tab does not get loaded
ER: The source text for the next selected tab should get loaded.

![no-sourcetext](https://cloud.githubusercontent.com/assets/792924/25308787/77952b76-27b4-11e7-8b7a-eb851cc1dcc9.gif)

**Comment by jasonLaster** [comment]
@bomsy ooh, this might be fixed by your tabs work :)

**Comment by jasonLaster** [comment]
Hmm - this looks like it's still an issue. Kinda interesting though

**Comment by bomsy** [comment]
Oh ... yeah . It's a separate issue. Was not fixed by my tabs PR.
I was going to look at it next, but forgot.
I can look at it.

**Comment by jasonLaster** [comment]
This should fix this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1366754

**Comment by bomsy** [comment]
These should all be fixed!
