### ISSUE TITLE
Think of a better way to ship the debugger to Firefox

### ISSUE THREAD

**Issue by captainbrosset** [devtools-html/debugger.html#2726]
This issue is for us to think about how we want to ship new versions of the debugger to DevTools inside Firefox.

To my knowledge, right now the process to do so is mostly manual and error-prone.
It requires bundling the sources from this repo and dropping the bundle into the [mozilla-central mercurial repository](https://hg.mozilla.org/mozilla-central/) ([here](https://hg.mozilla.org/mozilla-central/file/tip/devtools/client/debugger/new)).

As it happens, we are working on [moving all of DevTools to GitHub](https://docs.google.com/document/d/1tod1YH8uuzZykKawNvrLyyxuxxYNUfYsvTuHFa2Jf9s/edit#) soon (target date is June 26th for now, but this might change, follow [the meeting notes](https://docs.google.com/document/d/1mTX9wskT7nr-x5Kp0bqS-Cs5RHQEmX9PCCkr3e9FoWU/edit#) for more info).

This means, among other things, that having a build step for DevTools will become much easier. Inside mozilla-central, the build step we have is to build Firefox, not for, for instance, downloading dependencies from NPM.

So, once DevTools is in a GitHub repository, we should think of ways to ship the debugger to it in a more automated, simpler, faster way.

**Comment by jasonLaster** [comment]
I'm closing this as it is not actionable for the next couple months.

Lets continue the discussion here as we plan:

https://docs.google.com/document/d/15L0tujw_MYwptjWoaVlItQ_kFrKVv7eAidfpc1jmlac/edit?usp=sharing
