### ISSUE TITLE
[tests] Jest unit tests fail in node 7.7

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2728]
The `jest` unit tests fail when run in node 7.7 with the error that the global `L10N` is not available.

#### Reproduce

* install node 7.7
* git clone https://github.com/devtools-html/debugger.html.git
* yarn 
* yarn test

I like using [nvm] so that i can install a version `nvm install 7.7` and then test

#### Issue

We setup `global.L10N` [here]. It's possible this has to do with how Jest uses VM contexts.

<img src='https://shipusercontent.com/d31802c998fd9bd217bedcdba224a2f2/Screen%20Shot%202017-04-25%20at%2011.29.04%20AM.png' title='Screen Shot 2017-04-25 at 11.29.04 AM.png' width=1105>

[nvm]: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=nvm+node
[here]: https://github.com/devtools-html/debugger.html/blob/master/src/test/tests-setup.js

**Comment by irfanhudda** [comment]
I was able to run the test after commenting https://github.com/devtools-html/debugger.html/blob/master/src/utils/tests/scopes.js#L200 and https://github.com/devtools-html/debugger.html/blob/master/src/utils/tests/scopes.js#L204 lines

**Comment by MylesBorins** [comment]
so I'm seeing this fail in node v6.10.2 and v7.6.0... going to assume that @irfanhudda figured this out and the bug was not in Node itself. LMK if I am wrong

**Comment by jasonLaster** [comment]
hmm, i didn't see it in 7.0

**Comment by jasonLaster** [comment]
This could be the bug: https://github.com/nodejs/node/pull/11266

**Comment by fhinkel** [comment]
We changed the behavior in https://github.com/nodejs/node/pull/11266/. Now, more properties are (correctly) deleted. Which test is failing? Is there maybe an incorrect assumption that `L10N` is present when it really should have been deleted? 

Background: Jest is using the vm-module, and we change the behavior of the delete operator in the vm-module. Sorry that that's interfering with your tests :crying_cat_face:
