### ISSUE TITLE
High CPU usage (constantly querying getSymbols)

### ISSUE THREAD

**Issue by yurydelendik** [devtools-html/debugger.html#2731]
STR:
1. Open FF at https://devtools-html.github.io/debugger-examples/examples/wasm/fib/fib.index.html (and start listening at 6080)
2. Start development server `yarn start`
3. Open other instance of Firefox or Chrome Canary at localhost:8000 and connect to fib.index.html
4. Open Activity/Performance Monitor

Actual result:
Notice above 100% CPU usage by process

Expected result:
Normal CPU usage

P.S. on Mac OSX

<img width="1065" alt="screen shot 2017-04-24 at 8 15 14 pm" src="https://cloud.githubusercontent.com/assets/1523410/25394798/a583bb5a-29a4-11e7-9920-f88726ac2702.png">

**Comment by jasonLaster** [comment]
I see the same thing here: https://devtools-html.github.io/debugger-examples/examples/evals.html
