### ISSUE TITLE
[SourceTree] show the webpack icon in the webpack domain directory

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2745]
It would be so cool if we could show the webpack icon in the source tree for webpack domains!

<img src='https://shipusercontent.com/26e16662181d4e58b8bcdb14fa447028/Screen%20Shot%202017-04-26%20at%2010.03.46%20AM.png' title='Screen Shot 2017-04-26 at 10.03.46 AM.png' width=514>

**Comment by oriharel** [comment]
I'm working on it!

**Comment by jasonLaster** [comment]
https://github.com/webpack/media/blob/master/logo/icon.svg

**Comment by clarkbw** [comment]
Got the go ahead from the kind folks at webpack for using the icon!

**Comment by amitzur** [comment]
There's a consistency issue with colored SVG's. I'm just not sure we intended for this visual effect along the source tree in terms of the color.
<img width="253" alt="screen shot 2017-05-10 at 9 31 23" src="https://cloud.githubusercontent.com/assets/394320/25885891/b3ea1566-3563-11e7-9d31-7030de36405d.png">

This is also evident in the react logo, which specifies a fill color in itself. But less conspicuous.

One possible solution is to remove the fills from the SVG, but not sure if license permits, plus doesn't always work visually (it doesn't for the webpack logo - it just turns to a full hexagon)

**Comment by jasonLaster** [comment]
Thanks @amitzur, we were just talking about that as well.

I think Atom does a great job of simplifying the icon so that it fits with other icons. I will merge this work as we have done the "hard" thing here and we can create a new issue for using a better SVG and perhaps styling some of the other icons as well. For instance, I think "JS" would be really easy and would help a lot.

<img width="348" alt="screen shot 2017-05-10 at 11 18 14 am" src="https://cloud.githubusercontent.com/assets/254562/25894102/808ae3da-3572-11e7-8adb-f0f7881879f2.png">

**Comment by amitzur** [comment]
nice work by Atom
