### ISSUE TITLE
[CallStack] add a copy frames item in the context menu

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2746]
It would be really great if we could let you copy the call stack by right clicking on the call stack.

an output we could add to the clipboard would be like 

```
onclick  todo-view.js#24
render  todo-view.js#31
listenTo  backbone.js#24
```

We can use the same format that chrome has :)

**Comment by zivkaziv** [comment]
I'm on it.. I'll create pool request for it soon..

**Comment by clarkbw** [comment]
This looks 😎

**Comment by zivkaziv** [comment]
I have a question, can I just edit the file "debugger.properties"?
I want to add there copyStackTrace value and copyStackTrace access key (like copySourceUrl

**Comment by jasonLaster** [comment]
Go for it. That's the point!

Ask in our slack and you'll more reliably get answers
