### ISSUE TITLE
Left panel scrolls as you move up/down the file tree

### ISSUE THREAD

**Issue by amitzur** [devtools-html/debugger.html#276]
I guess this is intentional, but IMO it's really annoying to have the panel scroll when you work with the keyboard arrows to navigate the file panel.

**Comment by jasonLaster** [comment]
What do you recommend? Not sure if I follow.

**Comment by jlongster** [comment]
I think I know what he means. I've seen the scrolling behavior get a little wonky before, but I'm not sure if that's what he saw. Can you tell us which browser you are using and more info? In Firefox, the tree does try to implement scrolling behavior.

**Comment by amitzur** [comment]
I'm referring to the scroll starting when the selected file is still around the middle, rather than it being the last. See this video to better understand: https://youtu.be/kgodmlaNgtc

I would expect it to just reach the last file and if I press down arrow, then it scrolls with me. Very standard, I think

**Comment by jasonLaster** [comment]
Haha yea that is strange. 

We're using another tree library, so this fix might have to land in gecko. I don't want to discourage you, but just give you a heads up. Either way, it'd be nice to see where the behavior is coming from.

**Comment by jlongster** [comment]
We've already made local modifications to the tree. Before landing, we'll need to reconcile them with mozilla-central. I plan on diffing the files and figuring them out. I'd avoid making big changes to tree.js, but small tweaks are OK.

**Comment by clarkbw** [comment]
Interesting, I think the more standard behaviour is actually a less desirable UX.  I agree 100% that I don't like how the scrolling looks jumpy on every navigate, it would be better if it made a larger scroll once for every couple moves.  However I think the "standard scroll", where you reach the end of the viewport and then it scrolls the next item, is worse UX because it prevents you from being able to see how much further you might want to travel.  I don't think there's a good argument for hiding the next item until you navigate to it other than that's what computers have been traditionally doing.

**Comment by amitzur** [comment]
That's a compelling argument and an interesting discussion. My thoughts - 
1) I wouldn't downsize the importance of what users are accustomed to when estimating UX.
2) I don't think inventing the wheel is the right thing to do in this case.
3) In our case I don't think navigating the tree should even be the mainstream way to browse between sources. That should be done with a file opener like in issue #158 . Running through sources in the tree is more a "get to know thy tree of sources" kind of interaction.

**Comment by jasonLaster** [comment]
Is this still an issue?

**Comment by clarkbw** [comment]
I'm going to close this out for now, certainly good questions raised and something we can look into further later.  However keeping this issue open and stale isn't providing much value.  Lets reopen / reference this later as we look into possible solutions.
