### ISSUE TITLE
[PrettyPrint] option unavailable

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#2782]
via [bug 1361271](https://bugzilla.mozilla.org/show_bug.cgi?id=1361271)

Firefox Nightly 55.0a1 (2017-04-27) (64-bit)

1. Go [here]
2. Open the Debugger.
3. find (cmd+P embed) https://queso-cdn.prod.reuters.tv/assets/embedded.bundle.js
4. The script appears

but then

* no options to unminify it. 
* no way to set a sensible breaking point.

[here]: https://queso-cdn.prod.reuters.tv/index.html?autoplay=true&muted=true&countdown=true&preroll=true&proll=iuuq%3A%2F%2Fqvcbet.h.epvcmfdmjdl.ofu%2Fhbnqbe%2Fbet%3Fta%3D3y3%26jv%3D%2F4735792%2Fwjefp.vt.sfvufst%2Fxpsme%2Fbsujdmf%26djv_tat%3D300y250%2C1500y692%26dvtu_qbsbnt%3DwjefpDiboofm%253E13421%252D13976%252D13978%252D14073%252D1003%252D118169%2526wjefpJe%253E371551279%2526uzqf%253Ebsujdmf_qsfspmm%2526begsjfoemz%253Eusvf%26jnqm%3Dt%26hegq_sfr%3D1%26fow%3Dwq%26pvuqvu%3Dynm_wbtu3%26vowjfxfe_qptjujpo_tubsu%3D1%26dpssfmbups%3D8499280988809153%26vsm%3Diuuq%3A%2F%2Fvt.sfvufst.dpn%26eftdsjqujpo_vsm%3Diuuq%253B%252G%252Gxxx.sfvufst.dpn%252Gbsujdmf%252Gvt-hfsnboz-vtb-usvnq-jwbolb-jeVTLCO17S0A8&poster=http%3A%2F%2Fs1.reutersmedia.net%2Fresources%2Fr%2F%3Fd%3D20170425%26i%3D128192763%26w%3D780%26r%3D128192763-10_0%26t%3D2&mid=128192763&title=VERBATIM%3A%20Ivanka%20Trump%20hears%20groans%20at%20women%27s%20summit&suppress_ads=false&suppress_rtv=false&source=http%3A%2F%2Fwww.reuters.com%2Farticle%2Fus-germany-usa-trump-ivanka-idUSKBN17R0Z8&chartbeat_uid=52639&chartbeat_domain=preview.reuters.com&region=US&draggable=false&hide_title=false&correlator=8499280988809153

**Comment by miketaylr** [comment]
This bug makes it hard to do my job. :(

I need to set breakpoints to find out why new Pandora is busted in Nightly, but it's not possible with https://www.pandora.com/web-client/37.2b288d7f92d80323cb24.js in the new debugger. 😭

**Comment by miketaylr** [comment]
Uh, I just restarted the browser and got the pretty printer button for this file... but it didn't do anything. Closing and re-opening the debugger made it actually work.

**Comment by jasonLaster** [comment]
@miketaylr Thanks for the GIF, that will help hunting it down. It sounds like it works in the old debugger, but fails in the new one

**Comment by digitarald** [comment]
Right clicking the tab and choosing pretty print still works.

**Comment by digitarald** [comment]
Another case, checking sources on a google.com search. Both sources are served with `text/javascript`:

1. https://www.google.com/xjs/_/js/k=xjs.s.en_US._6_2EfjINk4.O/m=aa,abd,aspn,async,dvl,foot,fpe,ipv6,lu,m,sf,tl,vs,d3l,tnv,mrn,attl,adinfo,dpc,apmf,me,atn/am=wCJGjhccAPk_IRQStxAWyAImDiA/exm=sx,c,sb,cdos,cr,elog,hsm,jsa,r,qsm,d,csi/rt=j/d=1/ed=1/t=zcms/rs=ACT90oFAvRO4FrdrO03G04l7APidtFKo3w
2. https://www.google.com/xjs/_/js/k=xjs.s.en_US._6_2EfjINk4.O/m=sx,c,sb,cdos,cr,elog,hsm,jsa,r,qsm,d,csi/am=wCJGjhccAPk_IRQStxAWyAImDiA/rt=j/d=1/t=zcms/rs=ACT90oFAvRO4FrdrO03G04l7APidtFKo3w

**Comment by bomsy** [comment]
I'm investigating this ..

**Comment by bomsy** [comment]
So we have a couple of issues with our heuristics for determining what should be pretty printed.
Specifically the utilty `shouldPrettyPrint`.
1) For @clarkbw  case, it was ignored because it had a source map file (which it should not).
2) For @digitarald case, it is ignored because we determine javascript files by the file extensions in url and these files have no extensions

**Comment by bomsy** [comment]
I just wanted note cases we need to handle

- minified js files without sourcemaps
- minified js files with sourcemaps which have 404'd
- minified js files without `.js` or any javascript file extension
