### ISSUE TITLE
[Tabs] tab height is flush with the header

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2790]
We recently broke the tab height so that it became flush with the top of the debugger.

I believe #2751 might be to blame, but i'm not sure

You can easily test this in the debugger or in storybook `yarn storybook`

<img src='https://shipusercontent.com/3a81cf7af7290a4d7940cf2fa88d3af7/Screen%20Shot%202017-05-02%20at%206.37.29%20PM.png' title='Screen Shot 2017-05-02 at 6.37.29 PM.png' width=650>

**Comment by diessica** [comment]
I'm working on it.

**Comment by diessica** [comment]
@jasonLaster May I ask why is this issue already closed?

**Comment by jasonLaster** [comment]
Oh. I thought we were done :)

I forgot about the dropdown. Let's move that to a new issue to track it
better.

**Comment by diessica** [comment]
Oh, sorry! I was supposed to comment on #2791, which is closed even though it's still undone! 😕  Nevermind!

(Yeah, let's move the dropdown problem to a separate issue.)
