### ISSUE TITLE
[Tabs] height of icons relative to text

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2791]
We should polish the tab icon positioning again

* both selected and unselected tabs
* in RTL mode as well

- In RTL there's no padding
- pretty print icon is too far away
- blackbox might be a pixel too high

We should check in firefox and chrome

The easiest way to test is in storybook `yarn storybook`

<img src='https://shipusercontent.com/f0cb1dc7b634461be6947a5b9ce81f70/Screen%20Shot%202017-05-02%20at%206.40.07%20PM.png' title='Screen Shot 2017-05-02 at 6.40.07 PM.png' width=535>
<img src='https://shipusercontent.com/fc10307d49edcaa7fc7fc0f4fb61b28c/Screen%20Shot%202017-05-02%20at%206.40.03%20PM.png' title='Screen Shot 2017-05-02 at 6.40.03 PM.png' width=604>

**Comment by diessica** [comment]
Gonna take this one!

**Comment by diessica** [comment]
Still not done with this one! Would you mind leaving it open?
