### ISSUE TITLE
[VerticalMode] The secondary pane toggle button is misplaced

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2792]
When the debugger is in vertical mode (narrow), the toggle button should be in the bottom right (like chrome) but instead it is floating in the bottom left.

We also need to double check in RTL mode as well, which can be changed in the settings pane of the launchpad.

<img src='https://shipusercontent.com/f0a2da2f8283d1911e7297f300a7dbc6/Screen%20Shot%202017-05-02%20at%206.42.16%20PM.png' title='Screen Shot 2017-05-02 at 6.42.16 PM.png' width=544>

**Comment by diessica** [comment]
Gonna take this one!
