### ISSUE TITLE
[CodeFolding] gap on a paused line

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2796]
When code folding is on there i a gap in the gutter for paused lines.

We can likely fix this by adding the same background color for code fold space when we're paused.

You can turn on code folding in the launchpad settings pane.

![](http://g.recordit.co/XrxPxwUgba.gif)

**Comment by karthikJagadeesh** [comment]
Can I have this one for my first PR?

**Comment by jasonLaster** [comment]
@DanUgelow is also working on this, but it is a challenging problem so it would be nice to see what you find too.

**Comment by rohanprasad** [comment]
@jasonLaster Any update regarding this ? Can I pick this if no one else is working ?

**Comment by jasonLaster** [comment]
Thanks @rohanprasad, but we're punting on code folding at the moment. We can pick it up later.
https://github.com/devtools-html/debugger.html/projects/5
