### ISSUE TITLE
Displaying table-based variables as a table, not as a list of [Array, Array...]

### ISSUE THREAD

**Issue by sole** [devtools-html/debugger.html#2797]
I'm debugging a thing where important variables are m x n tables, and so inspecting their values with the hover pop up is not super convenient.

It would be super cool if the formatting was more 'table like', so you can inspect the contents of the variable in tabular way, not in a list/array. I wonder if this is something that reps could take care of?

(This is [an old feature request](https://bugzilla.mozilla.org/show_bug.cgi?id=1094194) from the old debugger. I edited it instead of just copying and pasting).

**Comment by jasonLaster** [comment]
moved to reps: https://github.com/devtools-html/reps/issues/149
