### ISSUE TITLE
Enable React Perf Addons

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2801]
As part of the reselect work we added `react-addons-perf`. When it is on it tries to get a lib that is not available. It would be great if we could get it working so we could take accurate measurements.

Perhaps the issue is that we're using react `15.3.x`

```diff
diff --git a/src/main.js b/src/main.js
index ade5ac3..63144b3 100644
--- a/src/main.js
+++ b/src/main.js
@@ -2,11 +2,11 @@

 const React = require("react");
 const ReactDOM = require("react-dom");
-//
-// if (process.env.NODE_ENV !== "production") {
-//   const Perf = require("react-addons-perf");
-//   window.Perf = Perf;
-// }
+
+if (process.env.NODE_ENV !== "production") {
+  const Perf = require("react-addons-perf");
+  window.Perf = Perf;
+}
```

**Comment by asolove** [comment]
Alternately, upgrade the whole codebase to React 15.4.x so we can use the new user timing integration, which would be even better.

**Comment by jasonLaster** [comment]
@codehag lets land prioritize this so we can detect these regressions sooner!

**Comment by jasonLaster** [comment]
it's in!
