### ISSUE TITLE
[flow] switch from PropTypes to Props

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2804]
We would like to switch from using PropTypes to flow props because it gives us a lot more coverage. I switched the [Tabs] component and learned a lot in the process. 

We've done most of them, and just have a few to go!

### todolist

- [x] Frames/index.js
- [ ] CommandBar.js
- [ ] TextSearch.js
- [x] ProjectSearch/index.js
- [ ] Editor/index.js
- [ ] App.js

[Tabs]:https://github.com/devtools-html/debugger.html/pull/2799/files#diff-bab1d2a309d9243dde45e9093e4ec799R91

**Comment by clarkbw** [comment]
Cool!  Lemme try one!  I'll take Footer

**Comment by AnshulMalik** [comment]
I'll try one too.

**Comment by Andarist** [comment]
wondering how does it work, is `props` stripped down later? or converted to `PropTypes` by a transform?

**Comment by jasonLaster** [comment]
@Andarist it's stripped away. It's basically acknowledging that we're going to use flow and static type our code. Want to jump in and claim a file?

**Comment by Andarist** [comment]
Yeah, already cloned and looking at `EventListeners` and reading dev guides ;)

Would be cool if they could be transformed to `PropTypes` if u distribute this as module (whatever if umd, cjs or smth else). You might have switched to `flow`, consumers of this as library might not.

**Comment by Andarist** [comment]
@jasonLaster 
can try `SearchBar` next

**Comment by jasonLaster** [comment]
Go for it

**Comment by sharathnarayanph** [comment]
I'd to like to take up "Expressions"

**Comment by Andarist** [comment]
Im also working on `HitMarker`

**Comment by peterschussheim** [comment]
@jasonLaster Starting work on `shared/Popover`

**Comment by jasonLaster** [comment]
Thanks!

**Comment by anbarasiu** [comment]
Is this an updated list? I think I'll start with shared/Accordion and shared/Autocomplete.

**Comment by jasonLaster** [comment]
probably not, we try to keep it up to date :)

**Comment by ohana54** [comment]
I'll take `Popover`

**Comment by satiewaltz** [comment]
I'll take object inspector!

**Comment by jasonLaster** [comment]
@satiewaltz its yours

**Comment by satiewaltz** [comment]
@jasonLaster  
Just thought I about this: I've been checking out the conversion to flow types issue in this project. Some components listed in that issue use the `Context` API for the `shortcuts component. I've done some research into it - and it seems like a runtime type library is required to convert from `contextTypes` to flow types: https://github.com/codemix/flow-runtime. I think its something that should be noted in the issue when people make PRs that use that component.

**Comment by jasonLaster** [comment]
Thanks @satiewaltz, I'd be open to using `flow-runtime` as well. Thanks for the update. Also, it's okay not to type context :) we use it very sparingly.

**Comment by amelzer** [comment]
I'll do Breakpoints in Secondary Panes

**Comment by amelzer** [comment]
Secondary Panes / Breakpoints looks done and seems only be missing the checkmark in this ticket.
Secondary Panes / Why Paused looks also done
Shared / Button / Close looks also done

I'll take Secondary Panes / CommandBar

**Comment by satiewaltz** [comment]
@amelzer  Note: `CommandBar`'s `contextTypes` can only be switched out if a runtime type library is used like `flow-runtime` as noted earlier from when I was looking at it. Fortunately, only several components have `contextTypes` defined in them: it's all places that inherits context from the shortcuts component. 

Maybe that component can be marked done unless there's an alternative way to convert it?

**Comment by amelzer** [comment]
@satiewaltz Yes, I got that, that's why it is in this done-ish list :)

**Comment by jasonLaster** [comment]
@joshunger i'm taking your head off it. Feel free to jump on it again if your schedule clears up.

**Comment by joshunger** [comment]
@jasonlaster sounds good my schedule should clear up in a week and a half

**Comment by joshunger** [comment]
👏
