### ISSUE TITLE
Hover for sub-properties displays a string

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#2814]
Here's how to reproduce this.

* Open: https://devtools-html.github.io/debugger-examples/examples/todomvc/
* Set a breakpoint on line `70` of `todo-view.js`
* Toggle a TODO item as completed in the todomvc
* Hover over `this`
* Then hover over `this.model`

I expect to be inspecting the `model` property of `this` instead of viewing a string.

Here are some screenshots:

<img width="1327" alt="screen shot 2017-05-04 at 1 24 01 pm" src="https://cloud.githubusercontent.com/assets/2134/25723520/2d3137f6-30cd-11e7-815c-81ee5004ef0c.png">

<img width="545" alt="screen shot 2017-05-04 at 1 22 45 pm" src="https://cloud.githubusercontent.com/assets/2134/25723528/37a3e314-30cd-11e7-82dc-ff47d81fb88e.png">

<img width="535" alt="screen shot 2017-05-04 at 1 22 52 pm" src="https://cloud.githubusercontent.com/assets/2134/25723529/3a2b30d8-30cd-11e7-8845-13b63aeebf1a.png">

**Comment by asolove** [comment]
This was probably caused by my recent changes to add selectors for the Editor component's data. Looking at it now.

**Comment by clarkbw** [comment]
Awesome!  Such a fast and small fix 👍
