### ISSUE TITLE
[breakpoints] Nightly won't delete breakpoints

### ISSUE THREAD

**Issue by ekr** [devtools-html/debugger.html#2817]
I have some breakpoints set on a script. I can X them out and they appear to go away but when I reload the page, they are back and checked.

**Comment by jasonLaster** [comment]
re-opening as i'm seeing deleted breakpoints, re-activate when the debugger is reloaded in the launchpad and re-opened in the panel.

**Comment by ekr** [comment]
Yah, i am still seeing this.

**Comment by jasonLaster** [comment]
Btw, we haven't updated nightly yet. So its just testable on GitHub

**Comment by ekr** [comment]
Ah. OK.

**Comment by codehag** [comment]
done!
