### ISSUE TITLE
[Breakpoints] Needs polishing in alignments

### ISSUE THREAD

**Issue by diessica** [devtools-html/debugger.html#2841]
1. The "remove breakpoint" button (`X`) isn't aligned vertically. 
2. The "remove breakpoint" button (`X`) isn't aligned with the checkbox above it.
3. When breakpoints are added, the "Breakpoint" title bar gets a height larger than the others – see "Call Stack", for example. *(I'm almost sure this happens because of the checkbox on the right side.)*

## Screenshot
![screencast 2017-05-07 at 11 38 40 am](https://cloud.githubusercontent.com/assets/5303585/25782099/ede7a2b6-3319-11e7-8fd5-dbfb7e666f6d.gif)

In vertical mode, the problem described in the 3rd item gets even more evident:
![image](https://cloud.githubusercontent.com/assets/5303585/25782118/5f750d2e-331a-11e7-9930-a16ee1d3edd7.png)
> Notice the height difference between the title bars.

**Comment by jasonLaster** [comment]
Great writeup! I meant to file an issue for the vertical mode header issue last week :)

I agree with all three issue.

**Comment by galtalmor** [comment]
Please ignore the previous commits, only the last one is relevant.
