### ISSUE TITLE
Unable CSS variables "--theme-toolbar-background-hover"

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#2844]
**Steps to Reproduce**
1. Start latest Nightly
2. Open Browser Console (Ctrl+Shift+J) -> Enable CSS warnings
3. Open Debugger (Ctrl+Shift+S)
4. Hover mouse on command-bar buttons

**Actual Results**
Logs the following warnings because no CSS variables "--theme-toolbar-background-hover" in variables.css

Property contained reference to invalid variable.  Error in parsing value for ‘background-attachment’.  Falling back to ‘initial’. debugger.css:2865:58117
Property contained reference to invalid variable.  Error in parsing value for ‘background-clip’.  Falling back to ‘initial’. debugger.css:2865:58117
...

**Expected Results**
No warnings

**Comment by jasonLaster** [comment]
Thanks @magicp-github
