### ISSUE TITLE
[Tabs] Dropdown that opens "more tabs" is misaligned

### ISSUE THREAD

**Issue by diessica** [devtools-html/debugger.html#2858]
### LTR mode
Some ideas on how it could be polished would be appreciated. But only aligning it to the arrow would do it.

![image](https://cloud.githubusercontent.com/assets/5303585/25900593/551dd962-356a-11e7-8757-396a73b3fa98.png)

### RTL mode ⚠️ 
It's barely visible while in this mode.

![image](https://cloud.githubusercontent.com/assets/5303585/25900602/5d617994-356a-11e7-8775-15cbe140bba4.png)

**Comment by diessica** [comment]
Working on this along with #2791.

**Comment by jasonLaster** [comment]
Sounds good
