### ISSUE TITLE
[Sources] style webpack icon

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2859]
We recently added webpack icons in the source tree in #2745. It would be great to style it a bit better:

1. adjust it's position and size
2. start using Atom's webpack logo which is simpler

How to get atom's icon? Open atom find the webpack icon in the tree (see debugger.html) and open the inspector `<cmd>+<option>+i`. 

We'd like to style the other icons soon as well so it's okay if this one still looks a little out of place :)

**Comment by peterschussheim** [comment]
@jasonLaster Can I take this one?

**Comment by jasonLaster** [comment]
Hey @peterschussheim sure, but unfortunately it looks like Ori's work might not have landed...

**Comment by peterschussheim** [comment]
@jasonLaster Yes, that was going to be my next question :) 

Would his work apply to the Frames icons as well?  

Perhaps I could experiment with a story? Otherwise, I will wait until his work is merged.

**Comment by jasonLaster** [comment]
hmm, i'm not sure if @oriharel's work landed: https://github.com/oriharel/debugger.html/commit/7b192f71232bdedbe36bd18cd537389de97f3ada
