### ISSUE TITLE
[CallStack] Anonymous functions not labelled in call stack

### ISSUE THREAD

**Issue by Sequoia** [devtools-html/debugger.html#2878]
# Expected

Anonymous function is labelled `(anonymous function)` in call stack.

# Actual

No label at all (see `index.js: 16` below).

![debug-stack-libs](https://cloud.githubusercontent.com/assets/317498/26003480/c5c33ad0-3700-11e7-96c4-5d5c76b34598.gif)

**Comment by jasonLaster** [comment]
@Sequoia mind sharing the anonymous frame data? I'm not exactly sure what you mean. 

Also, it would be great if you could add some of these dummy apps to our [debugger-examples](https://devtools-html.github.io/debugger-examples/) repo so we can reproduce it easily.

It would be nice to reduce this to a test case.

**Comment by Sequoia** [comment]
1. Create an anonymous function, run & break in that function
   ```js
   setTimeout(function(){
     debugger;
   }, 50);
   ```
![screen shot 2017-05-12 at 12 50 22 pm](https://cloud.githubusercontent.com/assets/317498/26008207/cab3adc0-3711-11e7-8a20-683069a466d0.png)
2. Name the function and do it again
   ```js
   setTimeout(function nameyMcNameface(){
     debugger;
   }, 50);
   ```
![screen shot 2017-05-12 at 12 51 15 pm](https://cloud.githubusercontent.com/assets/317498/26008247/f23bbb26-3711-11e7-87bb-b46d6726ec85.png)

Note how you see "nameyMcNameface" in the second screenshot's stack frame (highlighted), *nothing* in the first (also highlighted).

## Expected
![screen shot 2017-05-12 at 12 57 05 pm](https://cloud.githubusercontent.com/assets/317498/26008379/890e6256-3712-11e7-9543-765def7624b0.png)

**Comment by Sequoia** [comment]
Re: demos: will do when I have time. Is there a guide for adding Node demos?

**Comment by jasonLaster** [comment]
we just have lots of example dirs and a readme lol.

thanks for the test cases!

**Comment by jasonLaster** [comment]
added to the tracking issue #3947
