### ISSUE TITLE
[PrettyPrint] pretty print should map the selected location

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#2883]
Here's a pattern I'm experiencing sometimes.

I click on an error in the console, specifically on the file and location.
This takes me to the debugger with the file open at the correct, however this file is the *ugly* version so I can't easily understand the location.
I click on the Pretty Print option to cleanup the file.  
However I'm not taken to the correct location after pretty print, I now have to search around the file for something I saw in the error.

So if when I clicked 'Pretty Print' the debugger bounced me to the correct location that would be really useful.

**Comment by jasonLaster** [comment]
We landed some fixes for mapping the breakpoints.

We might still have to land a fix for mapping the selected location.

**Comment by codehag** [comment]
this is done
