### ISSUE TITLE
[SourceTree] blob: (and wasm:) schemas are not properly grouped in sources

### ISSUE THREAD

**Issue by yurydelendik** [devtools-html/debugger.html#2884]
The blob schema may have origin, which follows `blob:`. It will be nice to group blobs by origin similar to how web pages are grouped.

STR: open debugger at http://webassembly.org/demo/Tanks/

<img width="797" alt="screen shot 2017-05-12 at 2 55 39 pm" src="https://cloud.githubusercontent.com/assets/1523410/26014756/9bc97230-3723-11e7-9de1-7f884d649058.png">

Similar functionality is wanted for `wasm:`

**Comment by jasonLaster** [comment]
I'm a bit confused. Can you show the ideal source tree in ascii? 

I can follow up with pseudo code for the issue afterwards

**Comment by yurydelendik** [comment]
I was thinking about something like:

```
+ webassembly.org
|-- demo/Tanks
+ blob:webassembly.org
|-- xxx-xxx-xxx
+ wasm:webassembly.org
|-- demo/Tanks
```

wasm: is tricky with tanks with Tanks demo since wasm is generated by blob script, so it can be

```
+ wasm:blob:webassembly.org
|-- + demo/Tanks
|-- |-- xxxxx-xxxx
```

or

```
+ wasm:
|-- + blob:webassembly.org/demo/Tanks
|-- |--  xxxxx-xxxx
```

`wasm:` is differ between browsers (no standard). Firefox's can be `wasm:xxxxx-xxx` or `wasm:http://example.org/path/script.js:xxxx-xxx`, Chrome's `wasm://xxxx-xxxx` (?)

**Comment by jasonLaster** [comment]
We recently did special styling for webpack:

perhaps we can do something similar here where we pull out the origin prefixes and show a logo... 

<img src='https://shipusercontent.com/8061e5337519e24b7cb39524418e9407/webpack.png' title='webpack.png' width=253>

**Comment by jasonLaster** [comment]
It would be cool if could inline the files regardless of wasm blob scheme and show the wasm and blob schemes in the icon on the left. Here is a small test that we can make green.

Step one - get the folder structure working
Step two - show the icons in the tree

```diff
diff --git a/src/utils/sources-tree/tests/addToTree.spec.js b/src/utils/sources-tree/tests/addToTree.spec.js
index 74df6a5..1be684c 100644
--- a/src/utils/sources-tree/tests/addToTree.spec.js
+++ b/src/utils/sources-tree/tests/addToTree.spec.js
@@ -66,6 +66,33 @@ describe("sources-tree", () => {
       expect(source1Node.name).toBe("source1.js");
     });

+    it("supports wasm and blobs", () => {
+      const sourcesList = [
+        "http://webassembly.org/demo/Tanks/Build/UnityLoader.js",
+        "http://webassembly.org/demo/Tanks/TemplateData/UnityProgress.js",
+        "blob:http://webassembly.org/5a1e6d45-c42c-c947-b420-7cc7ee7a94f5",
+        "http://webassembly.org/demo/Tanks/",
+        "wasm:http://webassembly.org/demo/Tanks/Build/UnityLoader.js:da39a3ee5e6b4b0d",
+        "wasm:blob:http://webassembly.org/5a1e6d45-c42c-c947-b420-7cc7ee7a94f5:1d94844895c5ea0e"
+      ];
+      const sources = sourcesList.map((url, index) => ({
+        url,
+        id: index
+      }));
+
+      /*
+      - http://webassembly.org
+        - demo/Tanks
+          - 5a1e6d45-c42c-c947-b420-7cc7ee7a94f5
+          - (index)
+          - Build
+            - UnityLoader.js:da39a3ee5e6b4b0d
+        -TemplateData
+          - UnityProgress.js
+          - 5a1e6d45-c42c-c947-b420-7cc7ee7a94f5:1d94844895c5ea0e
+      */
+    });
+
```

**Comment by jasonLaster** [comment]
closing as we'll soon have sourcemaps with proper URLs
