### ISSUE TITLE
[Breakpoints] + [SourceMaps] breakpoints are out of sync with the server on reload

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2904]
When a user adds a breakpoint to an original file, makes some changes to the file, and reloads the breakpoint is in the wrong location.

As a bit of background, I found this bug because I was working on Editor/Preview and found that i would add a breakpoint in `renderPreview` and when I refreshed the debugger would pause in a different place than the breakpoint! uhoh :/

The reason that the breakpoint is in a different spot in the UI than where the debugger pauses is because breakpoint locations are stored in the UI as Pending Breakpoints with original locations a.k.a `Editor/Preview.js#23` and on the server as generated locations a.k.a `bundle.js#2343`. So, when the user reloads the client shows the breakpoint on line 23, but the debugger pauses on line 2343, which turns out to be a new line on `Editor/Preview.js`.

**Comment by codehag** [comment]
On it

**Comment by codehag** [comment]
:sob: its done yey!
