### ISSUE TITLE
Think through how a breakpoint is shown in the breakpoint list

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#291]
@amitzur started an interesting discussion in #289 on what we show in breakpoings. 
Also, @clarkbw has thought about different breakpoint states in #287.

Lets discuss how we want to show a breakpoint in the breakpoint list:

Some things to consider

Content:
- File name
- Line number
- File line
- Condition

State:
- active
- disabled
- current paused on that line

**Comment by clarkbw** [comment]
Also probably worth thinking about any actions that are available from the breakpoint list.  Should the entire line toggle the breakpoint on / off?  Or should some part of the element navigate the editor to the breakpoint?  Or maybe some hybrid of those options?

**Comment by clarkbw** [comment]
Was just talking with people about this last night, wondering if we could try grouping by file.

Currently we preserve the order of adding breakpoints, which has value.  However we could maintain that order but within file groupings.

<img width="301" alt="screen shot 2016-08-11 at 12 00 47 pm" src="https://cloud.githubusercontent.com/assets/2134/17601086/44eed24c-5fbb-11e6-878b-64b16c8476d3.png">

**Comment by wldcordeiro** [comment]
Totally support @clarkbw's file grouping suggestion. It would be a very nice addition. Handling file grouping gets interesting with repeat files. Do we just expand their name to include the next level of the dir? If there's a `foo.js` in `bar/` and `bur/`  do we list them as `../bar/foo.js` and `../bur/foo.js`?

**Comment by jasonLaster** [comment]
Hmm, I like grouping but would prefer that we punt until after we launch and can discuss the different cases.

**Comment by jasonLaster** [comment]
closing this for now as we recently cleaned up the breakpoint styles and this is a bit stale.

There are some good ideas here like file grouping that we can revisit later
