### ISSUE TITLE
Add a license header

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2925]
We should add an MPL2 license header to our files so that we are abiding by the best practices. Hopefully we can update the policy soon and take them out.

```js
\* This Source Code Form is subject to the terms of the Mozilla Public
  * License, v. 2.0. If a copy of the MPL was not distributed with this
  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
 ```

**Comment by brutalcrozt** [comment]
second /claim doesn't work?

**Comment by Garbee** [comment]
And if we want this linted as well for any future updates there is a [header plugin](https://github.com/Stuk/eslint-plugin-header) for eslint to do this task.
