### ISSUE TITLE
[Preview] Popup is in the top left

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2948]
It looks like when the popup target is not available the preview popup is shown in the top left. this is hard to reproduce.

We should default to not showing the popup when there's no target.

<img src='https://shipusercontent.com/2072b74bd7c4d7788c9a7d8c48db289c/Screen%20Shot%202017-05-17%20at%205.45.22%20PM.png' title='Screen Shot 2017-05-17 at 5.45.22 PM.png' width=707>

**Comment by bomsy** [comment]
Any STR?

**Comment by jasonLaster** [comment]
@bomsy I think it is because the selected token aka target element is undefined.

I'd just add that fix for now

**Comment by bomsy** [comment]
This should be fixed by #3057
