### ISSUE TITLE
Search shows 'no results' after switching to another tool and switching back to debugger

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#2963]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1366220

STRs if running in firefox:
1. debug any file
2. CTRL/CMD+F
3. type something for which you find matches in the file
![image](https://cloud.githubusercontent.com/assets/1141550/26250270/c81932f4-3ca9-11e7-9bc6-3276ca57ff45.png)
4. switch to another tool
5. switch back to debugger

- ER: the search should still show the same status
- AR: the search shows "no results" 
![image](https://cloud.githubusercontent.com/assets/1141550/26250306/e5d3d966-3ca9-11e7-937f-25182e089cbe.png)

STRs if running in content:
Instead of steps 4&5, resize the window to be small enough to switch to vertical layout, this triggers the same issue.

**Comment by jasonLaster** [comment]
hmm - i'm not seeing it at the moment:

![](http://g.recordit.co/QNiIQ1dcVq.gif)
