### ISSUE TITLE
[Editor] Highlight lines in scope

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2964]
We're currently working on getting the lines in scope when we're paused in #2954. We're doing this so that we can make the lines that are not in scope inert so that we don't accidentally show preview popups. The other benefit is that we can help show the user that we're paused and some of the code is now "live".

Here's a screenshot of what the before and after could be like. The contrast is bumped up for affect, it likely wont be this intense.

<img src='https://shipusercontent.com/1e4c27de23181018d6a9ddbe85759a0c/pause-hgh2.jpg' title='pause-hgh2.jpg' width=3178>

**Comment by ryanjduffy** [comment]
Added a parser function in #3041 to start enabling this feature.

**Comment by jasonLaster** [comment]
There are a couple of follow up issues, but we can mark this as done

**Comment by ryanjduffy** [comment]
@jasonLaster Nice work landing the UI side!
