### ISSUE TITLE
[SecondaryPane] Labels aren't aligned vertically

### ISSUE THREAD

**Issue by AnshulMalik** [devtools-html/debugger.html#2979]
Current:
The labels aren't exactly in middle
![bef](https://cloud.githubusercontent.com/assets/7821757/26305148/bd6e45d8-3f0b-11e7-89b5-a5622f4fbe4c.png)

Expected:
![af](https://cloud.githubusercontent.com/assets/7821757/26305151/c30b5274-3f0b-11e7-9776-c878afa49da1.png)

Here is a diff that can help

```diff
diff --git a/src/components/shared/Accordion.css b/src/components/shared/Accordion.css
index e26ba65..43e4c90 100644
--- a/src/components/shared/Accordion.css
+++ b/src/components/shared/Accordion.css
@@ -11,6 +11,7 @@
   padding: 5px;
   transition: all 0.25s ease;
   width: 100%;
+  align-items: center;
 
   -webkit-user-select: none;
   -moz-user-select: none;
```

**Comment by gururajbn** [comment]
@jasonLaster can i give it a try as a first PR?

**Comment by jasonLaster** [comment]
Go for it!
