### ISSUE TITLE
[Framework Frames] Add libraries

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2980]
We want to add as many libraries for to our new Framework Frames feature. Come add your library.

It's very easy to add your library. Here's the ExtJS [PR](https://github.com/devtools-html/debugger.html/pull/2886), which is a good prototype.

#### Added

- [x] Backbone
- [x] jQuery
- [x] React 
- [x] ExtJS
- [x] Pug
- [x] Express
- [x] Angular
- [x] Ember
- [x] Redux
- [x] Lodash
- [x] Underscore
- [x] Immutable
- [x] RxJS
- [x] Preact 
- [x] Next.js
- [x] Vue
- [x] Marko
- [x] Node internals

#### Screenshots

![call stack.gif](https://shipusercontent.com/a665c85bf97dbc626d1174ccede90a1b/call%20stack.gif)

--- 

![](https://cloud.githubusercontent.com/assets/26968615/26312396/b28dac70-3f07-11e7-9fb1-0bb6632fe3fd.png)

---

<img src='https://shipusercontent.com/0c9db3af12bd9dd678d0825abe740fc6/Screen%20Shot%202017-05-22%20at%2010.21.33%20AM.png' title='Screen Shot 2017-05-22 at 10.21.33 AM.png' width=300>

**Comment by zaggy** [comment]
Hi, can I grab this as my first PR? I'd like to add at least a couple of them for starters. Maybe RxJs and Angular first.

**Comment by bomsy** [comment]
Hey @zaggy go ahead!!

**Comment by wldcordeiro** [comment]
@jasonLaster is there a chance we could introduce some kind of common annotation or interface that libs could utilize to give us this information? Feel like we'll always be playing catch-up with keeping our list of supported libs complete. Might be worth punting on as we develop the idea.

**Comment by jasonLaster** [comment]
Yes. I think we'll want to do that in the future :)

**Comment by andreicristianpetcu** [comment]
Lodash seems to be free. Can I pick it up, @jasonLaster ?

**Comment by jasonLaster** [comment]
Yes. I'm excited about that one

**Comment by andreicristianpetcu** [comment]
Damn! I mixed Underscore and Lodash . I always mix them up :) I added both :P 

![lo_dark](https://user-images.githubusercontent.com/922368/26931110-f2474b4c-4c4e-11e7-8edc-3d3a48a5ac30.png)
![lo_light](https://user-images.githubusercontent.com/922368/26931111-f256bfe6-4c4e-11e7-8f04-44b2d804daa2.png)
![underscore_dark](https://user-images.githubusercontent.com/922368/26931112-f25781d8-4c4e-11e7-930e-2a221e805883.png)
![underscore_light](https://user-images.githubusercontent.com/922368/26931113-f25c68ce-4c4e-11e7-910f-55442bde41c1.png)

As you can notice, the dark Lodash logo [has the --theme-highlight-blue color](https://github.com/devtools-html/debugger.html/blob/615311c0d65361c54135cb15b9ffa43c0cb1b370/src/components/SecondaryPanes/Frames/Frames.css#L106) while the rest do not. What should I do?

1) Make the [rect](https://raw.githubusercontent.com/andreicristianpetcu/debugger.html/framework_frames_underscore/assets/images/underscore.svg) in dark mode use the same color with a CSS selector?
2) Remove the rule for dark mode?
3) Add a similar rule for light theme?

Something else?

**Comment by jasonLaster** [comment]
Hmm, sure you can tweak the logo a bit with css but otherwise it's okay. We can always circle back on styling.

Thanks!

**Comment by andreicristianpetcu** [comment]
I prefer the natural colors of the logos. They look better with their real colors. I made the pull request.

**Comment by andreicristianpetcu** [comment]
I started [working on adding Ember](https://github.com/andreicristianpetcu/debugger.html/commit/4bdb5f7f9f71fcaa15dddbe8ae1d553e728f9237). I did not test it since I do not have an ember app up and running yet. Please do not add ember support since I am already working on it 😄 

Also I notice a lot of duplication. Maybe we can refactor it into some key/value object instead of having a lot of [if isSomething return "Something"](https://github.com/devtools-html/debugger.html/blob/96b53264876f3ce80b0b2e72f6dba0cba112b1c8/src/utils/frame.js#L16-L101)?

**Comment by andreicristianpetcu** [comment]
I tested and made [a pull request for Ember](https://github.com/devtools-html/debugger.html/pull/3154) @jasonLaster

**Comment by codehag** [comment]
@andreicristianpetcu I think refactoring might be a good idea, though i think we have a pretty clear way of writing it now, with only the if statements. A key value solution would still need something like that. What do you have in mind?

**Comment by andreicristianpetcu** [comment]
@codehag Well.... I would start by writing [unit tests](https://github.com/devtools-html/debugger.html/blob/bd8592c0688f74e2008bdc8795b364d99772c866/src/utils/tests/frame.js) for all the existing svg mappings and then, I would create an [Flow Array of a new type that contains a regex literal field](https://github.com/devtools-html/debugger.html/blob/bd8592c0688f74e2008bdc8795b364d99772c866/src/utils/frame.js#L16-L56) and [a library name](https://github.com/devtools-html/debugger.html/blob/bd8592c0688f74e2008bdc8795b364d99772c866/src/utils/frame.js#L62-L100). Then [I would iterate over the array check the regex and if it matches then return the name of the library](https://github.com/devtools-html/debugger.html/blob/bd8592c0688f74e2008bdc8795b364d99772c866/src/utils/frame.js#L59).

**Comment by ksaldana1** [comment]
I was unable to find an appropriate SVG to use for Immutable. Seems to be the last library we need to close this issue.

The only SVG I could find displayed the [entire name](http://instantlogosearch.com/?q=immutable). I think the [IM logo](https://altar.io/wp-content/themes/altar.io/dist/images/techs/immutable.png) would be more appropriate. If someone could point me to a source I think we could get this issue finished up and perhaps consider some of the refactoring suggestions that @andreicristianpetcu mentioned.

**Comment by yaelballa** [comment]
@ksaldana1 I've created an svg file from IM logo and also added it in PR #3588

**Comment by jasonLaster** [comment]
Would someone like to compile an image of all the frameworks and contributors?

@yaelballa, @ksaldana1, @andreicristianpetcu?

**Comment by yaelballa** [comment]
not sure I understood - do you mean a print screen of the debugger with all the icons?

**Comment by jasonLaster** [comment]
thinking of a quick photoshopped JPG compiling the different screenshots others have shared. 

Something nice though that includes the people who helped out and the name of the frameworks

**Comment by ohana54** [comment]
Added Preact: #4296

**Comment by jainsneha23** [comment]
Working on adding Marko. Will raise a PR soon

**Comment by brutalcrozt** [comment]
Next.js done, 1 left to go?

**Comment by nyrosmith** [comment]
Closing as it seems we have all frameworks we initially wanted.

**Comment by jasonLaster** [comment]
:confetti_ball:

**Comment by amitzur** [comment]
Can we add to this list:
- [ ] MobX 

There's the icon here:
https://cdn.worldvectorlogo.com/logos/mobx.svg

**Comment by nyrosmith** [comment]
@amitzur Mind creating a New issue? Otherwise this will stay open until no more frameworks get created :-)

**Comment by amitzur** [comment]
Sure :) Wasn't sure what was the right way to go
