### ISSUE TITLE
[Preview] Highlight expression yellow

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2984]
We currently have a very soft grey match highlight. We should make it pop with either a yellow background like chrome or some other strategy like underlying the token.

#### Screenshot

<img src='https://shipusercontent.com/f431b6f4299400ff4693738140c4cba6/Screen%20Shot%202017-05-22%20at%2012.44.23%20PM.png' title='Screen Shot 2017-05-22 at 12.44.23 PM.png' width=472>

#### Chrome

<img src='https://shipusercontent.com/45a30d67eadd4c94366bd37681f0910a/Screen%20Shot%202017-05-22%20at%2012.45.26%20PM.png' title='Screen Shot 2017-05-22 at 12.45.26 PM.png' width=489>

**Comment by ofiron01** [comment]
@jasonLaster, can I take this as my first PR?

**Comment by jasonLaster** [comment]
Sure!
