### ISSUE TITLE
[UX] Move Scopes panel to top

### ISSUE THREAD

**Issue by gerdneuman** [devtools-html/debugger.html#2998]
The order of panels currently is (from top to bottom): 
```
Watch Expressions
Break Points
Call Stack 
Scopes
```

FWIW, I personally mainly interact with the "Scopes". I almost never use the Call Stack, and never the Watch Expressions.

FWIW again, I use the VSCode Debugger quite heavily and found its order in its "Debug Side Bar" a bit better:
(Image taken from https://code.visualstudio.com/Docs/editor/debugging)

![image](https://cloud.githubusercontent.com/assets/12525563/26376953/aee8ead2-400e-11e7-8281-574367fb5fed.png)

I do not know how other people use the panels, but for my use case the "Scopes" are most important. I think it should be on top. (BTW: I also think that "Variables" like in VSCode would be a much better name than "Scopes")

This would seem more natural to me:
```
Variables
Watch Expressions
Break Points
Call Stack 
```

**Comment by jasonLaster** [comment]
Sorry for missing this @gerdneuman. Meant to get back and it fell off my queue.

We steal a lot of good ideas from VS Code, so this idea is not crazy. I'd like to revisit call stacks and Scopes/Variables, this summer. The current design makes sense conceptually to me as the call stack is hierarchically on top (frame -> scope -> variable). 

We've simplified the call stack dramatically by grouping framework frames which will make the UI more useful i believe. The next step for me is to think through how we show you the variables you likely care about.

This is two things:

1. clean up the variables when you are source mapped. we show the bundled variables _webpackContext2, babelDefault3... and not the original variables `toggleBtn`, `isActive`... 
2. highlight the expressions in scope. In practice variables are less useful than expressions `person` is not as good as `person.data.firstName`. We analyze the code in scope for these expressions when we preview a var. We are planning on doing a sweep of the code and showing inline previews similar to how google docs shows comments. I think that this will force us to think about the sidebar UX :)
