### ISSUE TITLE
Use inline documentation (JSDoc-style), if available

### ISSUE THREAD

**Issue by donaldpipowitch** [devtools-html/debugger.html#3000]
Converting a [Twitter conversation](https://twitter.com/jasonlaster11/status/861999806096519170) to a GitHub isse.

Given a file like:

```html
<!DOCTYPE html>
<html>
<body>
  <script>
    /**
     * Add numbers.
     * @param {number} a - First number.
     * @param {number} b - Second number.
     */
    function add(a, b) {
      debugger;
      return a + b;
    }
    add(1, 2);
  </script>
</body>
</html>
```

It would be nice, if `debugger.html` could actually use inline documentation (JSDoc-style) where it is useful - in a similar way like IntelliSense and similar IDE features.

**In "Scopes" view**

![image](https://cloud.githubusercontent.com/assets/1152805/26401663/3d0cdcec-4087-11e7-9791-81278a5144e4.png)

Hovering over `add` should show `Add numbers.`, `a` should show `First number.` and `b` should show `Second number.`.

**Inside the console**

![image](https://cloud.githubusercontent.com/assets/1152805/26401705/71572f70-4087-11e7-9252-8fa5e02a69af.png)

While typing `add` `Add numbers.` could be shown behind the popup. 
While writing the params the documentation for `a` and `b` could be shown.

**Comment by jasonLaster** [comment]
Yes, that's a great idea. I'm adding it to our enhancements board so that we can evaluate when we plan.

I'de like to consider running VS Code's intellisense server...
