### ISSUE TITLE
[Chrome] it shows numbers as [Object object]

### ISSUE THREAD

**Issue by hex13** [devtools-html/debugger.html#3002]
![image](https://cloud.githubusercontent.com/assets/3883359/26414880/cdf7683e-40b0-11e7-9307-4be2336deae4.png)

I use Chrome: Version 58.0.3029.110 (64-bit)
OS X El capitain (10.11.6)
NodeJS (6.9.5)

I've just installed debugger according to the docs on:
https://github.com/devtools-html/debugger.html#quick-setup
not sure if it's relevant, but `yarn start` didn't work

```
yarn start v0.15.1
$ "node bin/dev-server" 
sh: node bin/dev-server: No such file or directory
error Command failed with exit code 127.
```

and I manually run `node bin/dev-server.js`

ran my test script by command `node --inspect --debug abc.js `

and went to `http://localhost:8000/` choose `Node`, then selected `abc` script.

test script I created:

```javascript
"use strict";
let a = 0;
setInterval(() => {
const b = 12;
    a++;
    console.log(a);
}, 4000);
```

**Comment by jasonLaster** [comment]
Thanks for filing @hex13

**Comment by jasonLaster** [comment]
added it to a tracking issue #3947
