### ISSUE TITLE
[Breakpoints] The order of the breakpoints added changes after reloading the page

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3005]
[Steps to reproduce]:
1. Go to https://devtools-html.github.io/debugger-examples/examples/todomvc/
2. Open Debugger.
3. Navigate to todo-view.js
4. Click on the gutter, any line with written code and add many breakpoints/conditional breakpoints (e.g todo-view.js).
5. Navigate to any js file (e.g app-view.js).
6. Click on the gutter, any line with written code and add many breakpoints.
7. Refresh the page.

[Expected result]:
The order of the breakpoints should remain the same as when they were added.

[Actual result]:
The order of the breakpoints added changes after reloading the page.

[Note]:
Sometimes the order changes without refreshing the page.

### Before
![](https://bug1366745.bmoattachments.org/attachment.cgi?id=8870012)

### After
![](https://bug1366745.bmoattachments.org/attachment.cgi?id=8870011)

**Comment by codehag** [comment]
would it make sense to add a timestamp field to each breakpoint?

**Comment by jasonLaster** [comment]
duplicate of #3280
