### ISSUE TITLE
[Inspector] clicking on the label for an event does not open the debugger

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#3029]
Steps to reproduce.

1. Start Firefox Nightly 55.0a1 (2017-05-29) (64-bit) (macos)
2. Start a responsive design window 360 x 640 (Firefox Android user agent)
3. Go to http://www.ouest-france.fr/sport/basket/basket-les-demoiselles-de-ruaudin-en-n2-la-saison-prochaine-4991001
4. Scroll down/up a bit so the yellow button: [Je m'abonne] appears on the top right.
5. Click inspect element on it.
6. Click on ev label, the pop up appears with a mousedown event.  
    ![capture d ecran 2017-05-30 a 09 33 09](https://cloud.githubusercontent.com/assets/505230/26564390/166fcbce-451b-11e7-8168-5f57e87b2763.png)
7. Click on the label to go to the debugger.

Expected:
Go to the debugger at the right place in the code.

Actual:
Nothing is happening. Like the click has been ignored.

**Comment by jasonLaster** [comment]
Thanks for filing @karlcow

**Comment by juliandescottes** [comment]
Following the STRS, when I click on the "breakpoint" icon to the left of "mousedown", the debugger tab opens. The file is minified, so not sure this is the right place, but at least the debugger opens for me.

**Comment by jasonLaster** [comment]
I pretty printed the file and it took me here:

<img src='https://shipusercontent.com/cbb9d82a270619b3cb974930d26ba741/Screen%20Shot%202017-05-30%20at%209.48.56%20AM.png' title='Screen Shot 2017-05-30 at 9.48.56 AM.png' width=512>

**Comment by juliandescottes** [comment]
@karlcow can you tell us specifically which device you select in RDM? I used a nexus device here, not sure it makes a big difference? (uastring was "Mozilla/5.0 (Linux; Android 4.4.4; en-us; Nexus 4 Build/JOP40D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2307.2 Mobile Safari/537.36" )

**Comment by karlcow** [comment]
@juliandescottes made my own. 
`Mozilla/5.0 (Android 5.1.1; Mobile; rv:54.0) Gecko/54.0 Firefox/54.0`

**Comment by juliandescottes** [comment]
Just tried with this UA string, debugger still opens for me. Just to make sure since you mentioned "label" in the STRs, you are clicking on the breakpoint icon, right?

**Comment by karlcow** [comment]
Let me try with a non Firefox UA. Also in terms of modified preferences for devtools debugger.

![capture d ecran 2017-05-31 a 06 20 36](https://cloud.githubusercontent.com/assets/505230/26605521/5e11624a-45c9-11e7-90cc-7f30df40356a.png)
![capture d ecran 2017-05-31 a 06 28 19](https://cloud.githubusercontent.com/assets/505230/26605798/5f9634c8-45ca-11e7-99ca-4a5131120a0b.png)


0. Restarting, clean profile (no cookies, storage, etc.), Nightly 55.0a1 (2017-05-30) (64-bit) macos
1. Chose apple iPhone 6s in RDM
2. Same steps to reproduce. Nothing is happening. 

Tried with other events, same thing. I can see them locally in the inspector, look at their code, but when I click on the label, the debugger is not opening.

Ah discovered an interesting fact about:config?filter=devtools.debugger  After manually resetting a couple of devtools preferences from the screen above, it worked.

Once reset
![capture d ecran 2017-05-31 a 06 32 56](https://cloud.githubusercontent.com/assets/505230/26605995/1dcf18ba-45cb-11e7-8c94-6879d1f892a3.png)

**Comment by jasonLaster** [comment]
This is a similar bug, that should move to the inspector component where it can be appropriately triaged. At a minimum it should be in bugzilla because the debugger UI cannot fix it.
