### ISSUE TITLE
[WatchExpressions] should use proper textboxes

### ISSUE THREAD

**Issue by gijsk** [devtools-html/debugger.html#3034]
Somehow the watch expression edit field doesn't seem to work properly. Some of the issues:

1. no matter where I click to edit a watch, the cursor always starts at index 0
2. selection with shift or mouse drag doesn't seem to work
3. once editing, clicking doesn't move the cursor
4. fn-backspace (for delete) on my mbp keyboard doesn't seem to do the right thing - it removes the last character and moves the cursor to the end, instead of deleting the character right after the cursor

There's probably more. This smells like a bad reimplementation of a textbox. It should just use a textbox and hide the borders.

**Comment by jasonLaster** [comment]
Thanks for filing: part of the issue is the cursor starting at index 0. That part comes from this change that bz made: https://bugzilla.mozilla.org/show_bug.cgi?id=1357206

I'm curious about the other parts though as I didn't realize they were affected as well.

**Comment by jasonLaster** [comment]
Thanks for filing the other regressions. I see them too on nightly, but not in chrome which leads me to believe it is related to bz's change

**Comment by bwinton** [comment]
Similarly if I have `window.fullScreen` and put the cursor before the `.` and repeatedly hit delete on my Windows box instead of the expected `window` I end up with `window.ulcen`.  It looks like it's moving forward a character before the delete each time…  :)
