### ISSUE TITLE
[Breakpoints] Remove column breakpoints in the gutter

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3042]
We now show column breakpoints in the gutter when a breakpoints slides to a column. We should also support removing the breakpoint.

This is a bit trickier because we need to find the correct breakpoint and try and fire the remove breakpoint action with its location.

Here's a start: you'll see that when `columnBreakpoints` is off we ignore the column information

```diff
diff --git a/src/utils/editor/index.js b/src/utils/editor/index.js
index db370e7..e96756d 100644
--- a/src/utils/editor/index.js
+++ b/src/utils/editor/index.js
@@ -44,7 +44,11 @@ function isTextForSource(sourceText) {

 function breakpointAtLocation(breakpoints, { line, column = undefined }) {
   return breakpoints.find(bp => {
-    return bp.location.line === line + 1 && bp.location.column === column;
+    const sameColumn = isEnabled("columnBreakpoints")
+      ? bp.location.column === column
+      : true;
+    const sameLine = bp.location.line === line + 1;
+    return sameLine && sameColumn;
   });
```

The second part i'm less sure about: here we get the column location from the bp because when you click on the gutter we assume the column is undefined

```diff
diff --git a/src/components/Editor/index.js b/src/components/Editor/index.js
index d02ff48..984ddf9 100644
--- a/src/components/Editor/index.js
+++ b/src/components/Editor/index.js
@@ -556,7 +556,7 @@ class Editor extends PureComponent {
       removeBreakpoint({
         sourceId: sourceId,
         line: line + 1,
-        column: column
+        column: column || bp.getIn("location.column")
       });
     } else {
```

**Comment by anbarasiu** [comment]
Can we assume if _column_ is undefined, it could be set to true, because when the click initiates from the gutter, it always seems so?

> const sameColumn = isEnabled("columnBreakpoints") && column
>       ? bp.location.column === column
>       : true;

**Comment by jasonLaster** [comment]
Actually no, because in an evil case you can add a bp on a line with a
comment and it slides to another line and column. I'll get you an example
to test with :)
