### ISSUE TITLE
ERROR on npm install

### ISSUE THREAD

**Issue by imvetri** [devtools-html/debugger.html#3045]
OS: Windows 7
Node: 6.10.1
Npm : 3.10.1
Debug log : 
[npm-debug.log.txt](https://github.com/devtools-html/debugger.html/files/1039146/npm-debug.log.txt)

Please let me know if this is some issue with npm/ node
**Update**: This is not an issue with npm / node. I tried installing dependencies for express and it working good.

**Comment by jasonLaster** [comment]
Try using node 7. also npm version 4.1.2

**Comment by imvetri** [comment]
Tried with suggested versions. Still encountering issues. Below is the npm debug log

[npm-debug.log.node7.npm4.txt](https://github.com/devtools-html/debugger.html/files/1048186/npm-debug.log.node7.npm4.txt)

**Comment by jasonLaster** [comment]
Hmm, interesting. Thanks for sharing

**Comment by imvetri** [comment]
I referred to https://github.com/devtools-html/debugger.html/issues/1043
and I tried with npm install --ignore-script. This seemed to be working. But it  failed again when i tried npm start.

[npm-debug.log.npmstart.txt](https://github.com/devtools-html/debugger.html/files/1048233/npm-debug.log.npmstart.txt)

**Comment by jasonLaster** [comment]
thanks
