### ISSUE TITLE
[Preview] Show undefineds in a tooltip

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3058]
We currently hide undefineds, we should switch to showing undefined values in the tooltip.

**Comment by arthur801031** [comment]
I'll take a stab at this. :)

**Comment by jasonLaster** [comment]
More like this... 

<img width="682" alt="screen shot 2017-06-22 at 7 25 28 am" src="https://user-images.githubusercontent.com/254562/27431872-03befd34-571c-11e7-84b5-86fe746df116.png">


Lets also do the same thing for null.

**Comment by codehag** [comment]
Done!
