### ISSUE TITLE
[ObjectInspector] Keys should be vertically aligned

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3063]
One of the nice things that the old debugger did was vertically align the variable keys. We currently align the triangle and raw values which creates makes it seem like objects are one level deaper

### STR:
1. go to http://localhost:7999/promises.html
2. expand variable `rejectError`

### New Debugger
<img src='https://shipusercontent.com/7330f6a2e86d36fcef0a8c1cab97db36/Screen%20Shot%202017-06-02%20at%2011.01.42%20AM.png' title='Screen Shot 2017-06-02 at 11.01.42 AM.png' width=279>

### Old Debugger
<img src='https://shipusercontent.com/2939837c48745c8950abfdf3e8e1948d/Screen%20Shot%202017-06-02%20at%2011.01.36%20AM.png' title='Screen Shot 2017-06-02 at 11.01.36 AM.png' width=277>

#### Notes

```diff
diff --git a/src/components/shared/ManagedTree.js b/src/components/shared/ManagedTree.js
index c7b7dd8..7ebd1b3 100644
--- a/src/components/shared/ManagedTree.js
+++ b/src/components/shared/ManagedTree.js
@@ -115,6 +115,7 @@ class ManagedTree extends Component {
   render() {
     const { expanded, focusedItem } = this.state;

+    // we might need to change something here
     const props = Object.assign({}, this.props, {
       isExpanded: item => expanded.has(this.props.getKey(item)),
       focused: focusedItem,
diff --git a/src/components/shared/ObjectInspector.js b/src/components/shared/ObjectInspector.js
index 3679112..59e4c96 100644
--- a/src/components/shared/ObjectInspector.js
+++ b/src/components/shared/ObjectInspector.js
@@ -138,6 +138,9 @@ class ObjectInspector extends Component {
           focused,
           "default-property": isDefault(item)
         }),
+        // maybe we want to look here
+        // or consider using a before element?
+
         style: { marginLeft: depth * 15 },
         onClick: e => {
           e.stopPropagation()
```

**Comment by peterschussheim** [comment]
@jasonLaster mind if I take this one?

**Comment by jasonLaster** [comment]
Go for it

**Comment by peterschussheim** [comment]
[New issue](https://github.com/devtools-html/debugger.html/issues/3088) created to add support for aligning keys for users of `RTL` setting.
