### ISSUE TITLE
Search function in debugger is case sensitive by default

### ISSUE THREAD

**Issue by vladikoff** [devtools-html/debugger.html#3068]
The default behaviour seems to unlike other text editors.  

![image](https://cloud.githubusercontent.com/assets/128755/26746136/012a49c6-47bc-11e7-9c78-27ffd83e4eee.png)

(This is from a series of bugs reported by Firefox teams, I'm making sure we file all of those. Please close if dup)

**Comment by jasonLaster** [comment]
Hmm. We can switch that. We also recently backed it by prefs so whatever you choose will be saved going forward

**Comment by jasonLaster** [comment]
I did a bit of research and case insensitive is the more common default.

**Comment by ohana54** [comment]
I'm on it
