### ISSUE TITLE
Debugger source view is lost when switching between Console

### ISSUE THREAD

**Issue by vladikoff** [devtools-html/debugger.html#3069]
Original report: 

> When you switch from “Debugger” panel to “Console” panel in the browser toolbox, and then back to “Debugger” panel it doesn’t take you to where you were originally scrolled - it scrolls you above it to some other place
![rep](https://cloud.githubusercontent.com/assets/128755/26746267/7c718478-47bc-11e7-9d52-186425780c4a.gif)

(This is from a series of bugs reported by Firefox teams, I'm making sure we file all of those. Please close if dup)

**Comment by vladikoff** [comment]
Related https://github.com/devtools-html/debugger.html/issues/3033 ?

**Comment by jasonLaster** [comment]
It's more closely related to the recent search bug with switching toolbox tabs.

**Comment by jasonLaster** [comment]
I believe this was fixed in nightly by https://github.com/devtools-html/debugger.html/pull/3147

![](http://g.recordit.co/p1ZDleUT8a.gif)
