### ISSUE TITLE
Is it possible to allow browser toolbox prompt connection by default in Nightly / Dev Edition?

### ISSUE THREAD

**Issue by vladikoff** [devtools-html/debugger.html#3070]
> I work using fresh profiles a LOT, I wish the browser toolbox prompt connection dialog had a "Always Accept" option, it's really a pain in the ass. We could even go further (a man can dream) and activate the toolbox and disable the prompt-connection dialog by default on Nightly only. +1

(This is from a series of bugs reported by Firefox teams, I'm making sure we file all of those. Please close if dup)

**Comment by jasonLaster** [comment]
Hey @vladikoff I'm thinking about this now. If you have a new profile, how would "Always Accept" work? It can't be a pref :P 

having "prompt-connection" off by default in nightly makes sense to me.

**Comment by jasonLaster** [comment]
Nevermind, the checkbox **would** flip the pref

**Comment by vladikoff** [comment]
@jasonLaster I think enabling this pref in Nightly / DevEd by default might be enough: `'devtools.debugger.prompt-connection': false,` Ref: https://github.com/vladikoff/fxa-dev-launcher/blob/master/profile.js#L73


Might need a minor security review.



cc @eoger ideas?

**Comment by eoger** [comment]
Yup, false by default on Nightly would be awesome

**Comment by jasonLaster** [comment]
`false` seems like a good approach. 

Here's an older bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1013379

**Comment by clarkbw** [comment]
I've also filed [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1375280) to disable the prompt pref in Nightly only.

**Comment by bgrins** [comment]
@vladikoff @eoger to be clear, are you talking about a local build or a Nightly downloaded from https://www.mozilla.org/en-US/firefox/channel/desktop/?

**Comment by eoger** [comment]
Local build, but it could also apply to the "release" version of Nightly.

**Comment by jasonLaster** [comment]
This is now done :)
