### ISSUE TITLE
Content of files seems to disappear sometimes in the debugger when a breakpoint is hit (in browser toolbox)

### ISSUE THREAD

**Issue by vladikoff** [devtools-html/debugger.html#3073]
Workaround: "My current workaround for this is to close and re-open devtools. Which sucks because you have to re-set the breakpoint then." 

(This is from a series of bugs reported by Firefox teams, I'm making sure we file all of those. Please close if dup)

**Comment by jasonLaster** [comment]
I believe @miketaylr is the one who saw this issue. There isn't a good way to reproduce this yet.

**Comment by codehag** [comment]
Hi, I was investigating a group of bugs related to this. Do you have a test case that I can try to make sure that the fix for those is the same as here?

**Comment by jasonLaster** [comment]
Taking this out of the milestone as we're blocked on an STR

**Comment by jasonLaster** [comment]
This has been fixed by the editor stability work we did last week
