### ISSUE TITLE
window.crypto errors are harder to debug than in Google Chrome

### ISSUE THREAD

**Issue by vladikoff** [devtools-html/debugger.html#3075]
Example with this code: 

```
return window.crypto.subtle.decrypt(
      {
        name: "AES-GCM",
        iv: 3, //The initialization vector you used to encrypt
        tagLength: 128
      },
      APP_DERIVE_KEY_DATA, // from generateKey or importKey above
      ENCRYPTED_ARRAY_BUFFER //ArrayBuffer of the data
    )
```

The `iv` value should be a `Uint8Array`. 

## Firefox output

> DOMException [SyntaxError: "An invalid or illegal string was specified"
code: 12
nsresult: 0x8053000c

![image](https://cloud.githubusercontent.com/assets/128755/26747289/c028c680-47c2-11e7-84af-05eabd041467.png)

## Google Chrome output

![image](https://cloud.githubusercontent.com/assets/128755/26747294/cae83376-47c2-11e7-9439-5578260f3e2f.png)

## Expected 

Firefox should say that `iv` should be a BufferSource. There are other cases where Firefox just says `DOMException` with no explanation and the only way to find the problem is to fire up Chrome and get a better error report.

**Comment by jasonLaster** [comment]
Refiled in the console component: https://bugzilla.mozilla.org/show_bug.cgi?id=1375297
