### ISSUE TITLE
[Scopes] keys gets the global value

### ISSUE THREAD

**Issue by vladikoff** [devtools-html/debugger.html#3076]
```
window.crypto.subtle.generateKey(
  {
    name: "ECDH",
    namedCurve: "P-256", //can be "P-256", "P-384", or "P-521"
  },
  true, //whether the key is extractable (i.e. can be used in exportKey)
  ["deriveKey", "deriveBits"] //can be any combination of "deriveKey" and "deriveBits"
)
  .then(function(keys){
    debugger
    console.log('app key', keys);
    APP_PUBLIC_KEY = keys.publicKey;
    APP_PRIVATE_KEY = keys.privateKey;
  })
```

When the `debugger` stops, `keys` is some global function:

![image](https://cloud.githubusercontent.com/assets/128755/26747448/d73231a8-47c3-11e7-97be-9491dbfc440e.png)

If renamed to something else then it works properly: 

![image](https://cloud.githubusercontent.com/assets/128755/26747461/eabed118-47c3-11e7-8c1b-de26f7fb7012.png)

(This happens to other variable names, not just `keys`)

**Comment by jimblandy** [comment]
We definitely have the means to get this right. I'm pretty sure we must be just using the Debugger API incorrectly in the server.

**Comment by jasonLaster** [comment]
I tested a similar case with some shadow variables including `location` which shadows a window property and everything was okay. I'll look into CryptoKey as an edge case too.

```js
function shadowing() {
  let foo = 'foo'
  let bar = 'bar'
  function inner(foo, location) {
    bar = 'bazz'
    debugger
  }

  inner('fim', 'cool');
}
```

![](http://g.recordit.co/LsREvoyTee.gif)

<img width="783" alt="screen shot 2017-06-08 at 7 35 11 pm" src="https://user-images.githubusercontent.com/254562/26955029-dff25d14-4c81-11e7-8530-9a52bb644167.png">

**Comment by jasonLaster** [comment]
Hmm, I tried running the crypto example [here] and found the correct behavior the scopes view, but the wrong behavior on preview which tells me that the console is not behaving correctly.

### Scopes with and without shadowing

<img width="711" alt="screen shot 2017-06-08 at 7 45 53 pm" src="https://user-images.githubusercontent.com/254562/26955241-9d438310-4c83-11e7-834f-ba63e1c8fe8a.png">
<img width="734" alt="screen shot 2017-06-08 at 7 45 20 pm" src="https://user-images.githubusercontent.com/254562/26955242-9d439026-4c83-11e7-8e6d-b5b79008e43f.png">

### Preview

<img width="712" alt="screen shot 2017-06-08 at 7 46 05 pm" src="https://user-images.githubusercontent.com/254562/26955255-abde28bc-4c83-11e7-83a8-d894dc37bba9.png">

<img width="755" alt="screen shot 2017-06-08 at 7 45 59 pm" src="https://user-images.githubusercontent.com/254562/26955256-abe2f00e-4c83-11e7-95f4-ad9eeb041ccc.png">


[here]:https://devtools-html.github.io/debugger-examples/examples/objects.html

**Comment by jasonLaster** [comment]
I dug a bit deeper into it this morning and found a couple interesting things:

**1.** it looks like this is limited to *keys* which is not being handled well on the server. I tried `assign` and `length` and it was okay.

```js
function shadowing() {
  function keysFunc(keys) {
    keys;
    debugger
  }

  function mkeysFunc(mkeys) {
    mkeys;
    debugger
  }

  function locFunc(location) {
    location;
    debugger
  }

  function lengthFunc(length) {
    length;
    debugger
  }

  function assignFunc(assign) {
    assign;
    debugger
  }

  keysFunc('cool');
  lengthFunc('cool');
  mkeysFunc('cool');
  locFunc('cool');
  assignFunc('cool');
}
```

**2.* The server is not formatting the right object

logging inside the `actors/object.js` grip function shows that it is trying to format the window.keys function instead of the local object. We should look into how the object is retrieved to find the bug. 

Fortunately this bug is narrower in scope than it otherwise could have been.

**Comment by jasonLaster** [comment]
I'm going to take this issue out of the milestone as I don't think it should be a blocker for launching:

1. it is only an issue for shadowing with the keys var
2. it is server side

**Comment by vladikoff** [comment]
Thanks for checking this. I will see if I can find other shadow vars like
that

**Comment by jasonLaster** [comment]
opened in bugzilla because it's a server bug
https://bugzilla.mozilla.org/show_bug.cgi?id=1390582
