### ISSUE TITLE
Consolidate Source and SourceText

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3078]
We currently have two store fields Source and SourceText. I think it would be nice to consolidate them. 

This would mean `Source` would have this type:

```js
 Source = {
    id: SourceId,
    url?: string,
    sourceMapURL?: string,
    isBlackBoxed: boolean,
    isPrettyPrinted: boolean,
    text?: string,
    contentType?: string,
    loading?: boolean
  };
```

The benefits of consolidation is that it would be easier to get a source's text. The two fields are different because of the way the protocol works, but that is largely an implementation detail.

Here is a [gist] for the refactor. I'm curious what others think.

[gist]:https://gist.github.com/jasonLaster/203d87ae579f08e808c0490d8ab480bd

**Comment by clarkbw** [comment]
Looks like this was done in #3081 already

**Comment by jasonLaster** [comment]
not done yet :)

**Comment by jasonLaster** [comment]
This is done!
