### ISSUE TITLE
"Copy Link Address" menuitem id is "node-menu-close-tabs-to-right"

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#3083]
"Copy Link Address" menuitem id is "node-menu-close-tabs-to-right"
![node-menu-close-tabs-to-right](https://cloud.githubusercontent.com/assets/13914314/26759718/6789521c-4941-11e7-8dcb-845c10ec7b42.png)

**Comment by jasonLaster** [comment]
Thanks! Nice find

**Comment by jasonLaster** [comment]
This is an easy first bug if you want to grep for the incorrect id and replace it.

**Comment by codehag** [comment]
Done! Thanks @borisstgermain
