### ISSUE TITLE
[ObjectInspector] [RTL] Keys should vertically align when inspecting objects, RTL

### ISSUE THREAD

**Issue by peterschussheim** [devtools-html/debugger.html#3088]
We recently merged a small [patch](https://github.com/devtools-html/debugger.html/pull/3079) that vertically aligned variable keys in `ObjectInspector`, however, it is only effective for **users of `LTR` (left to right) setting**.

@jasonLaster Suggested creating a simple style utility.  This would allow us to say, for example, `marginStart` or `marginEnd`, taking advantage of `logical-css properties`.  The function should be able to detect which setting (LTR or RTL) is in use and apply the appropriate CSS rule.

### Steps To Reproduce:
- enable `RTL` setting in launchpad
- go to http://localhost:7999/promises.html
- expand variable rejectError

### Screenshots:
|Current|Desired|
|----------|------|
|![current](https://cloud.githubusercontent.com/assets/3654683/26785995/f2c6bfea-49d2-11e7-92ce-a4e1f8879501.jpg)|![desired](https://cloud.githubusercontent.com/assets/3654683/26785999/f743b6ea-49d2-11e7-87f2-2cad8acb2b31.jpg)|

### Notes:
- [useful docs on our RTL support](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#rtl)
- [margin-inline-start](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-start)
- [margin-inline-end](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-end)
- [Building RTL-Aware Web Apps & Websites: Part 1](https://hacks.mozilla.org/2015/09/building-rtl-aware-web-apps-and-websites-part-1/)
#### Related Issues:
- [ObjectInspector] Keys should be vertically aligned: #3063

**Comment by jasonLaster** [comment]
Thanks @peterschussheim i think the desired screen could use a bit of work :)
