### ISSUE TITLE
Refactor ManagedTree

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3092]
Managed tree takes a number of arguements that are callbacks. Many of these callbacks are not using information from the parent component, and should probably be defined on the ManagedTree component instead. Here are some examples:
```
getRoots: () => results,
getChildren: file => {
  return file.matches || [];
},
getParent: item => null,
getKey: item => item.filepath || `${item.value}/${item.line}`,
renderItem: (item, depth, focused, _, expanded) =>
  item.filepath ? this.renderFile(item, expanded) : this.renderLine(item)
```

These are duplicated each time that the component is declared. It is used in the following components:
- `ObjectInspector`
- `SourceTree`
- `ChromeScopes`
- `ProjectSearch/TextSearch`

Task:
- [ ] check which other callbacks are being declared in the same way repeatedly in these files
- [ ] create methods on the ManagedTree component
- [ ] remove extra callbacks from the parent components

**Comment by amitzur** [comment]
I also noticed it's not clear whether the class "node" should be added to items

**Comment by jasonLaster** [comment]
dropping the `available` tag because I don't know what we want yet.

**Comment by jasonLaster** [comment]
moving to the enhancements board: 
https://github.com/devtools-html/debugger.html/projects/5
