### ISSUE TITLE
New gecko driver is required on start

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3093]
I tried running master this morning and had the following error:

<img width="576" alt="screen shot 2017-06-05 at 5 14 58 pm" src="https://cloud.githubusercontent.com/assets/26968615/26790126/e953a852-4a12-11e7-9e5c-c34b1c19271c.png">

It also no longer opens the debugger with the example project page. It seems like something changed over the weekend. Can anyone confirm that this is happening?

**Comment by jasonLaster** [comment]
mind opening in devtools-core as this is a launchpad bug

**Comment by codehag** [comment]
yep!
