### ISSUE TITLE
[EditorSearch] The debugger width is too wide

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3094]
Looks like the editor search bar in vertical mode is causing the debugger width to be too wide which creates an awkward horizontal scrollbar.

#### GIF

![](http://g.recordit.co/IuWcOcWPyn.gif)

Here are some good places to start digging:

```diff
diff --git a/src/components/Editor/Editor.css b/src/components/Editor/Editor.css
index 19c7e9c..054e1f5 100644
--- a/src/components/Editor/Editor.css
+++ b/src/components/Editor/Editor.css
@@ -34,6 +34,7 @@
   position: absolute;
   height: calc(100% - 31px);
   width: 100%;
+  /* maybe here */
   top: 30px;
   left: 0px;
   --editor-footer-height: 27px;
diff --git a/src/components/Editor/SearchBar.css b/src/components/Editor/SearchBar.css
index f2f60f5..dab43ab 100644
--- a/src/components/Editor/SearchBar.css
+++ b/src/components/Editor/SearchBar.css
@@ -21,6 +21,7 @@
   display: flex;
   flex-shrink: 0;
   justify-content: space-between;
+  /* likely here */
   width: calc(100% - 1px);
   height: var(--editor-second-searchbar-height);
   background-color: var(--theme-toolbar-background);
```

**Comment by sarahlim** [comment]
Sorry, I'm having trouble reproducing, could you give more details? My first attempt in Chrome was fine, looks like there's no horizontal spillover beyond the native bounce effect:

![jun-19-2017 19-05-35](https://user-images.githubusercontent.com/57372/27313342-48d367d0-5522-11e7-9de0-ffc5abedb361.gif)

**Comment by codehag** [comment]
I am also unable to reproduce this one
