### ISSUE TITLE
[Editor] Extract additional components

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3103]
The editor has become bloated which makes it difficult to reason about and improve performance. 

- [ ] out of scope locations
- [ ] debug line
- [ ] Preview (we could do more in the component)

---

What would these refactors look like? The best examples are `Editor/Breakpoint` or `Editor/HighlightLines`. 

In the case of **out of scope locations** we would have `Editor/OutOfScopeLocation` and a `renderOutOfScopeLocations` function which would map over the locations and create an array of `OutOfScopeLocation` components. The benefit of this approach is we take advantage of reacts render engine. #3056

For debug line, we would move `clearDebugLine` and `setDebugLine` into `Editor/debugLine` and handle mounting and unmounting the line in a similar fashion to what we do with highlight lines.

**Comment by peterschussheim** [comment]
@jasonLaster Can I start on `debugLine`?

**Comment by jasonLaster** [comment]
This is now a duplicte of #3264
