### ISSUE TITLE
[Pause] Stepping over await calls.

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3106]
The debugger should step over await statements. When I have something in my debugger 

like this: If I'm on line 2. and I press step over, I don't care this call is asynchronous, I want to be on line 3. 

```js
1.    async foo() {
2.      await bar();
3.      return true;
4.   }
```

**Comment by jimblandy** [comment]
Generators and async/await were not standard yet when Debugger was designed, so there are plenty of improvements we could make here. Some of it might be SpiderMonkey work, but stepping across an `await` seems more like setting an internal breakpoint on the instruction after the `await` and waiting for it to be hit. There's code in the `step` implementation now to handle returns and throws; it would need to be taught that `await` is something different.

I'm also not sure we have a good way to set that breakpoint accurately. That might require Debugger work.

**Comment by jasonLaster** [comment]
github.com/devtools-html/debugger.html/issues/3106

**Comment by jasonLaster** [comment]
Here are some ASTs, i think we can prototype a solution on the client and if we like it add something on the server:

SIMPLE: [ast]( https://astexplorer.net/#/gist/373291544b7824bb815aec303b1af9e4/a60cfdb455937247b3fe93efd45ac2c1c6dbfa9b)

it would be nice to also handle babel's code: [babel](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code=async%20function%20foo()%20%7B%0A%20%20await%20slow()%0A%20%20const%20bar%20%3D%203%3B%0A%7D)

**Comment by jasonLaster** [comment]
Just landed @jbhoosreddy's amazing PR for async stepping. There are now a couple of small follow ups:

1. land a test for step over (might need to tweak the implementation)
2. add support for step in and step out
3. add unit tests for the new parser functions

**Comment by codehag** [comment]
Closing and opening a new issue for tracking the remaining two improvements needed: improve step in / step out & and unit tests
