### ISSUE TITLE
[Scopes] Horizontal scrolling

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3107]
We should be able to scroll horizontally when the scopes get really deep

A good way to test this is to pause, narrow the debugger, and expand function, prototype, constructor a bunch

<img src='https://shipusercontent.com/b7acb6e3325c5cf30ab47e5019ec1466/Screen%20Shot%202017-06-06%20at%202.51.21%20PM.png' title='Screen Shot 2017-06-06 at 2.51.21 PM.png' width=646>

**Comment by ofiron01** [comment]
After some investigation,
@jasonLaster can you recall why the root element returned in render() of SecondaryPanes has
as inline style of overflowX: "hidden" ?

`render() {
    return dom.div(
      {
        className: "secondary-panes",
        style: { overflowX: "hidden" }
      },
      CommandBar(),
      WhyPaused(),
      this.props.horizontal
        ? this.renderHorizontalLayout()
        : this.renderVerticalLayout()
    );
  }`

**Comment by jasonLaster** [comment]
Hmm, we want the scroll bar for a sidebar pane: this might be it

https://github.com/devtools-html/debugger.html/blob/master/src/components/SecondaryPanes/Scopes.css#L25-L28
