### ISSUE TITLE
[FrameworkGrouping] call stack misses frames frames when framework grouping is disabled

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3110]
STR:

1. pause with framework grouping on
2. disable framework grouping by right clicking the call stack

ER: you see all the frames
AR: you see most of the frames :)

**Comment by codehag** [comment]
Do we have a concrete STR? I am having trouble seeing the issue

**Comment by codehag** [comment]
This is what i am seeing:

Loading without Framework Grouping enabled:
<img width="301" alt="screen shot 2017-07-10 at 12 57 29 pm" src="https://user-images.githubusercontent.com/26968615/28015292-89651d2c-656f-11e7-9f5d-dcaf3520b6a2.png">

Loading with Framework Grouping enabled:
<img width="302" alt="screen shot 2017-07-10 at 12 57 38 pm" src="https://user-images.githubusercontent.com/26968615/28015298-8d84f9d6-656f-11e7-9893-9d53b9c4b2b2.png">

disabling Framwork Grouping:
<img width="302" alt="screen shot 2017-07-10 at 12 57 47 pm" src="https://user-images.githubusercontent.com/26968615/28015313-99cc831c-656f-11e7-8c76-5e27fc3583e9.png">

**Comment by jasonLaster** [comment]
[STR]
1. open todomvc
2. open debugger.html -> todomvc
3. open debugger.html -> debugger.html
4. add a breakpoint in Editor/index.html#renderFooter
