### ISSUE TITLE
[Scopes] Match Arguments to the argument names

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#3116]
Hello!

I often find I'm in this scenario where I'm looking in the Scopes at the arguments but I need to translate (in my head) the Array of arguments into the named ones used within the function.  It would be nice if the debugger did that for me.

Here you can see the function is `function (message, sender, sendResponse)` so I would hope the arguments object would look like:
```
arguments
  * message
  * sender
  * sendResponse
```

Here's a screenshot:

<img width="901" alt="screen shot 2017-06-06 at 3 02 18 pm" src="https://user-images.githubusercontent.com/2134/26854011-35503822-4ac9-11e7-9288-131236a614cd.png">

**Comment by jasonLaster** [comment]
Good idea - it's actually nice to see it treated as array like here when we really want it to be object like.

I especially like how the third param is `2()`. It gets this behavior because we shortened our object formatting for functions to just `key()`, but ignored the Array case :)

**Comment by jasonLaster** [comment]
@nchevobbe this is probably something that we will want to do in the Arguments Reps. I don't know if you have the data that you need though.

The debugger could help you there because we have the local function AST Node...

**Comment by nchevobbe** [comment]
So, I checked and it looks like we don't have much value for it.
if I evaluate 
```js
(function(a, b,c){return arguments;})(1,2,3)
```

I get the following grip : 

```json
{
  "type": "object",
  "actor": "server2.conn3.child19/obj30",
  "class": "Arguments",
  "extensible": true,
  "frozen": false,
  "sealed": false,
  "ownPropertyLength": 5,
  "preview": {
    "kind": "Object",
    "ownProperties": {
      "0": {
        "configurable": true,
        "enumerable": true,
        "writable": true,
        "value": 1
      },
      "1": {
        "configurable": true,
        "enumerable": true,
        "writable": true,
        "value": 2
      },
      "2": {
        "configurable": true,
        "enumerable": true,
        "writable": true,
        "value": 3
      }
    },
    "ownSymbols": [],
    "ownPropertiesLength": 5,
    "ownSymbolsLength": 1,
    "safeGetterValues": {}
  }
}
```


so yes, we'd need more than just the grip.
We may have a `propertiesNameMap` prop, which could look something like : 
```js
  propertiesNameMap: {
    "0": "a",
    "1": "b",
    "2": "c",
  }
```
that we could use to render node label in the ObjectInspector.

**Comment by jasonLaster** [comment]
yeah a `propertiesNameMap` would work. Lets see if we can get that data on the server. I'm going to refile this in devtools-core #reps
