### ISSUE TITLE
[Preview] bound functions

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3144]
There are two issues with bound functions:

1. they should use their real name like "apply"
2. they should not be clickable: now they error

Go to `previewFunction.js` and `Editor/Preview`

STR: go to examples, objects, crypto

<img src='https://shipusercontent.com/389e0bd19e02965c521ffc186e88f2ca/Screen%20Shot%202017-06-08%20at%207.47.11%20PM.png' title='Screen Shot 2017-06-08 at 7.47.11 PM.png' width=694>
<img src='https://shipusercontent.com/debf2e8aa0a318d30eff86e1f00f2785/Screen%20Shot%202017-06-08%20at%207.46.05%20PM.png' title='Screen Shot 2017-06-08 at 7.46.05 PM.png' width=712>

**Comment by bomsy** [comment]
@jasonLaster 

![image](https://user-images.githubusercontent.com/792924/28078362-7ff3abf8-665c-11e7-87ba-a79eef1336f4.png)

Looks like this is fixed. correct?

**Comment by jasonLaster** [comment]
`keys` is different than `myKeys`

**Comment by codehag** [comment]
where do i find crypto? i was not able to find it among the examples

**Comment by jasonLaster** [comment]
Try previewing apply in a function apply or bind

**Comment by bomsy** [comment]
Can't seem to find an STR that replicates this. @jasonLaster do you have one we can use?

**Comment by jasonLaster** [comment]
looks pretty good

![Screen Shot 2017-10-20 at 3.51.12 PM.png](https://shipusercontent.com/4c733d741c378abc7567e66d1129539d/Screen%20Shot%202017-10-20%20at%203.51.12%20PM.png)
