### ISSUE TITLE
[README] Update the screenshot

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3151]
The screenshot is pretty old

We should highlight
* tabs
* the blue pause line
* framework frames
* and perhaps the conditional breakpoint pane

Steps to take a great screenshot on the mac: `<cmd>+shift+4` then `spacebar`, then click

https://cloud.githubusercontent.com/assets/2134/22579643/a184f3ce-e986-11e6-82e2-b896077aec4a.png

**Comment by nyrosmith** [comment]
@jasonLaster I think this can be closed
