### ISSUE TITLE
[FunctionSearch] function search misses exported functions

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3158]
I just noticed that our function search is missing exported functions. It's likely also missing async functions as well. This should be a fun babel PR to work on and figure out what's going on under the hood. Here's an [AST](https://astexplorer.net/#/gist/740a3150f5b2e8b7d2c9aeee90c5e5ea/545bb2bf64e1e92235b46855d488c4458823e933) to help w/ the digging.

![](http://g.recordit.co/imDCjGqlmI.gif)

Here's a patch with a test and some comments

```diff
diff --git a/src/utils/parser/tests/fixtures/func.js b/src/utils/parser/tests/fixtures/func.js
index 5f57c06..11b21e8 100644
--- a/src/utils/parser/tests/fixtures/func.js
+++ b/src/utils/parser/tests/fixtures/func.js
@@ -2,6 +2,18 @@ function square(n) {
   return n * n;
 }

+export function exFoo() {
+  return 'yay'
+}
+
+async function slowFoo() {
+  return 'meh'
+}
+
+export async function exSlowFoo() {
+  return 'yay in a bit'
+}
+
 child = function() {};

 (function() {
diff --git a/src/utils/parser/utils/helpers.js b/src/utils/parser/utils/helpers.js
index 4eaec40..f3df39c 100644
--- a/src/utils/parser/utils/helpers.js
+++ b/src/utils/parser/utils/helpers.js
@@ -10,6 +10,7 @@ export function isLexicalScope(path: NodePath) {
 }

 export function isFunction(path: NodePath) {
+  // hmm, we're missing something here
   return (
     t.isFunction(path) ||
     t.isArrowFunctionExpression(path) ||
```

**Comment by frigus02** [comment]
I just tried to reproduce the behavior and noticed that the search UI looks very different already. Ctrl+Shift+O opens a modal. And this seems to include all functions (including async and exported ones).

![debugger-search-modal-async-functions](https://user-images.githubusercontent.com/3579251/28837423-f5c4919e-76ec-11e7-8e25-c2750307c394.png)

Maybe I'm looking at the wrong branch, though.

**Comment by jasonLaster** [comment]
oh wow - thanks. maybe this is fixed then. 

The modal *is* new.

**Comment by jasonLaster** [comment]
lets see if the tests demonstrate this behavior

**Comment by frigus02** [comment]
Nice. I'm trying to get a pull request ready.

**Comment by jasonLaster** [comment]
Thanks @figus02, are you interested in working on getting support for async functions?
