### ISSUE TITLE
Immutable is not listed as one of the project dependencies

### ISSUE THREAD

**Issue by zaggy** [devtools-html/debugger.html#3162]
I just noticed that in several places in code we use Immutable module, but it is not set as a dependency in package.json I found it in 14 files in total

Steps to reproduce: just open the package.json and note that module `immutable` is not listed in dependencies. Then open for example `src/utils/makeRecord.js` and notice that it tries to import everything from `immutable` module.

**Comment by wldcordeiro** [comment]
I think this may have been missed a bit ago when immutable was removed. @jasonLaster that sould right to you?

**Comment by zaggy** [comment]
It is still used. At least from what I can see.

**Comment by jasonLaster** [comment]
oh weird - it should be there :) we probably pull it in from the launchpad so it works, but it should be explicit

**Comment by nyrosmith** [comment]
@jasonLaster  immutable is now in package.json so I think this can be closed
