### ISSUE TITLE
Cannot set debugger breakpoint on generatedSource

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3167]
Steps to reproduce:
- open a debuggee with a generated source
- add a breakpoint to the generated source
- the breakpoint will be moved to the original source

Expected:
- breakpoint will remain in the generated source

**Comment by jasonLaster** [comment]
Here's a non-pretty answer.
https://gist.github.com/cda7b293c3024b3a1f57d41969ef9ffe

It takes advantage of the fact that we *do* save the generated location here...

**Comment by jasonLaster** [comment]
We landed the first version. There are some next steps:

- [ ] Refactor components
- [ ] Support toggling between original/generated sources #3288
- [ ] Simplify breakpoint clients
