### ISSUE TITLE
[Documentation] Running the debugger as part of a firefox build

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3169]
I looked around and wasn't able to find any docs on how we run the debugger as part of the firefox panel. This might be that I wasn't looking in the right place. I think it would be a useful bit of documentation, so if we don't have it already I would be happy to write it. If it does exist, would it make sense to put it in a clearer location?

**Comment by jasonLaster** [comment]
Yes! good idea. We have some mochitest docs, which covers some of this but we should take a stab at this!

**Comment by wldcordeiro** [comment]
Looks like with the PR above this is done.
