### ISSUE TITLE
Land JS bundle in Firefox

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#317]
Prototype the initial workflow

Goal is to encounter some of the inevitable issues before we are the default debugger and learn what need to get done right before the switch.

No need to implement a feature flag preference just yet, we can require manually rewiring the old debugger off to see the new one in action.

**Comment by jlongster** [comment]
Work being done in https://bugzilla.mozilla.org/show_bug.cgi?id=1288511

**Comment by jasonLaster** [comment]
@jlongster is this pass done?

**Comment by jlongster** [comment]
Yep!
