### ISSUE TITLE
[flow] Improve covariant style

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3172]
We currently follow an awkward style for covariants 

```js

  constructor() {
    super();

    const self: any = this;
    self.closeConditionalPanel = this.closeConditionalPanel.bind(this);
    self.onEscape = this.onEscape.bind(this);
    self.onGutterClick = this.onGutterClick.bind(this);
    self.onGutterContextMenu = this.onGutterContextMenu.bind(this);
    self.onScroll = this.onScroll.bind(this);
    self.onSearchAgain = this.onSearchAgain.bind(t
```

@thejameskyle shared some wisdom on how we can improve the style

---

Class methods are covariant in Flow by default, which in effect means they are "read-only" and cannot be assigned to.

```js
class Error extends React.Component {
  constructor(props) {
    super(props);
    this.onClick = this.onClick.bind(this); // Error
    //   ^ property `onClick`. Covariant property `onClick` incompatible with contravariant use in
    //     assignment of property `onClick`
  }
  
  onClick(event: ButtonClickEvent) {
    // ...
  }
  
  render() {
    return <button onClick={this.onClick}>Click Me</button>;
  }
}
```

In order to make this work, you need to use an additional class field, which are invariant (read & write) by default, like this:

```js
class WorksWithClassPropertyType extends React.Component {
  constructor(props) {
    super(props);
    this.onClick = this.onClick.bind(this); // Works!
  }
  
  onClick: (ButtonClickEvent) => void;
  onClick(event) {
    // ...
  }
}
```

Alternatively you can use the class properties proposal to get around all of this:

```js
class WorksWithClassPropertyArrowFunction extends React.Component {
  onClick = (event: ButtonClickEvent) => {
    // ...
  };
}
```

[[See in Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IojgJ7qGgBCArjhywAdgGFoyUgGsAogDdCIvAF5QAWVj8AzoQVK8AMlABvRKFCl+WBsoAqxLAHNCOAFygAEnfUAZAUKistCEqAYANIgAvqyIpNDE2tqgsjbYoIQAHjhKACbJRGQ4AHRi1JgiBqbmlqLaOFj85NgAFOhU6NoAlNUWFtr83FhtHd2sfaA4ABbI2sWiElLSoGrTs-PikjLFAEbIIrkta2M1UTU1C1vSLYSKyh4BwptL+so9ZhMgoMU-p+cWtlyhGG7xqANc1hEoAAPDtBE9QJclioTMcNosZFEAHwY5bqQjQ4BwwIiLHjUBnM5xBJJUAAdWw0m0dOQ0wkiW0AAUOsDOHYuDwsjkDgVGCUyhhRFUPrURPVGs1hu1YJ1QRMBkMRiqThM0UiZCtJjM5vrpLt9odjl1yWcLBdnjIPC1HqbXjgeiosaB5LBkLlyaabnd3b0+l8fsU-lT4hz6YzmaypuyktyVbyOABBNLwABi-BE5GQogy2TyoqKpXKUuUodNhqDBge8NdwY9XplFnDvwsMWiiCAA)]

**Comment by codehag** [comment]
is there a reason why we don't use `return <button onClick={() => this.onClick}>Click Me</button>;` ?

**Comment by jasonLaster** [comment]
Do you mean, why don't we use JSX? I'd be happy to :)

We were holding off the past couple months to finish up the import/commonjs refactor and keep the codebase stable for launching. Perhaps we start allowing a small amount of JSX nowish and allow bigger refactors post launch, like july?

**Comment by codehag** [comment]
Ah sorry i wasn't clear enough. I meant why don't we use this shorthand: `e =>  this.onClick(e)`

**Comment by codehag** [comment]
also, regarding JSX -- I am honestly quite happy with how we are doing it now. It reminds me of hiccup syntax. The only issue is that it might be deprecated...

**Comment by thejameskyle** [comment]
@codehag Performance is impacted by creating functions within every `render()` vs creating them once per component.

**Comment by zaggy** [comment]
I was planning to cover thay as part if fixing flow `any` code style issues this weekend

**Comment by maniator** [comment]
I can continue on with the proposal in my PR if everyone agrees, it should be easy to knock-out a lot of the `: any` from the code with this change.

**Comment by jasonLaster** [comment]
closing as we have an approach now
