### ISSUE TITLE
debugger perf issue when stepping through youtube.com

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#3179]
This is about a general performance issue when running the debugger in the panel.  I tried this on the latest nightly and it still grinds Firefox to a halt.

Here's the steps to reproduce:

- `cmd+P` --> desktop_polymer
- pretty print
- search for function `acquireApi`
- set breakpoint on `acquireApi`
- click on a video
- step over x 5 or so time the more you step the slower it gets to respond

I captured this profile of the performance problem in action: https://perfht.ml/2rvcCWl

**Comment by clarkbw** [comment]
Here's another run with a larger sample size https://perfht.ml/2rvNZsS

**Comment by jasonLaster** [comment]
I think a big part of it is codemirror highlighting the out of scope lines. I'll try turning that off and measure the perf.

**Comment by jasonLaster** [comment]
I think this is the youtube page:  youtube.com/new, but i can't find desktop_polymer

**Comment by clarkbw** [comment]
> I think this is the youtube page: youtube.com/new, but i can't find desktop_polymer

Yes, that's the URL.  Its possible it has changed...

**Comment by jasonLaster** [comment]
removing from the milestone as i can no longer find desktop_polymer. 

For the record, the big offender here initially was styling out of scope lines which has been fixed

**Comment by clarkbw** [comment]
Tried out the STRs here again and I can't get Firefox to beach ball anymore. Some steps are still a bit slow but doesn't freeze up.
