### ISSUE TITLE
Possible character encoding issues with Chrome RDP

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#318]
Chrome seems to be returning the decoded string for the URL.  This may be creating the next problem where Chrome cannot create the web socket connection because the URL is `undefined`.  Firefox loads the debugger page just fine.

```
api.js:1020 Uncaught (in promise) DOMException: Failed to construct 'WebSocket': The URL 'undefined' is invalid.(…)
WebInspector.WebSocketConnection @ api.js:1020
WebInspector.WebSocketConnection.Create @ api.js:1033
resolve @ index.js:32
connect @ index.js:30
connectTab @ chrome.js:52
(anonymous function) @ index.js:37callNext @ task.js:30
Promise.resolve.then.value @ task.js:36
```

Here's a test website: http://xn--80ahjdhy.xn--p1ai/

Screenshot of the difference at the tabs page:
![screen shot 2016-07-12 at 1 21 45 pm](https://cloud.githubusercontent.com/assets/2134/16782273/9b83bb94-4833-11e6-89ac-654552a3616c.png)

**Comment by jasonLaster** [comment]
Nice find @clarkbw

**Comment by clarkbw** [comment]
I'm not seeing this error anymore, the  websocket connection works, so I think we can close this even though the display is still incorrect.

Here's what I found about the issue.

Chrome is returning an [IDN](https://en.wikipedia.org/wiki/Internationalized_domain_name) in [Punycode](https://en.wikipedia.org/wiki/Punycode) though I'm not sure why because they display it correctly in their URL bar.  [IDN in Google Chrome](https://www.chromium.org/developers/design-documents/idn-in-google-chrome) explains the Chrome thinking around punycode but not for what we are seeing.

To fix this I believe what we would need to use a library like https://github.com/bestiejs/punycode.js to decode the URL for display.  (this module was previously included in node.js, now being [removed for an internal solution](https://github.com/nodejs/node/pull/7941))

```js
const punycode = require('punycode');
punycode.decode("http://xn--80ahjdhy.xn--p1ai/") // -> http://дизайн.рф/
```

Because the WebSocket connection is being made and the debugger works I don't think we need to fix this right away.

I believe the official solution is the `URL.domainToUnicode` method.  However it seems fairly unclear what the status of that API is going forward, it is not implemented in Firefox or Chrome.  Servo has implemented the WHATWG method of `URL.domainToUnicode` https://github.com/servo/servo/issues/11629 and https://github.com/servo/servo/pull/11632 yet the WHATWG actually removed the API here: https://github.com/whatwg/url/issues/63 in favor of this different API: https://github.com/whatwg/url/issues/64
