### ISSUE TITLE
Vendor lodash dep in m-c

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3189]
It would be nice to vendor lodash in mc. The benefit is that we could use it directly in the debugger without worrying about the bundle size ballooning.

We currently do something like `import get from 'lodash/get'` with this change we could do `import {get} from 'lodash'`

**Comment by gregtatum** [comment]
I wanted this so many times working in m-c.

**Comment by jasonLaster** [comment]
This will be done when the new release lands
