### ISSUE TITLE
Use prettier for "Pretty print source"?

### ISSUE THREAD

**Issue by gerdneuman** [devtools-html/debugger.html#3214]
Often I find the results of `Pretty Print Source` disappointing, especially for larger files. Here's the end of a 1.5MB js (indentation is broken):

![2017-06-23 15_07_44-](https://user-images.githubusercontent.com/12525563/27483466-cda398e4-5825-11e7-9419-c0d7de79c837.png)

(done with Firefox 56.0a1 (2017-06-22))

compared to Chrome:
![2017-06-23 15_09_08-chrome](https://user-images.githubusercontent.com/12525563/27483502-fc17d9c4-5825-11e7-9ca1-ad8dfcd42b5f.png)

I do not know how the `Pretty Print Source` is done at the moment, but wouldn't it be a solution if prettier would be used instead. Here's the result for the same minified JS pumped into https://prettier.github.io/prettier/:
![2017-06-23 15_12_45-prettier](https://user-images.githubusercontent.com/12525563/27483618-78616784-5826-11e7-8f37-3f263efb539a.png)

Much better.

**Comment by jasonLaster** [comment]
Thanks for filing the issue. We've discussed it as well and would like to switch to prettier. 

The one wrinkle is that I'm not sure if prettier gives a mapping back to the ugly version, which is important for breakpoints and stepping.

**Comment by jasonLaster** [comment]
It might be difficult...

https://twitter.com/left_pad/status/878311413051146240

**Comment by jasonLaster** [comment]
closing, as we will not do this in the short term w/o source maps...
