### ISSUE TITLE
[FileSearch] Searching a string in a file preempts the scroll behavior from when stepping in a program

### ISSUE THREAD

**Issue by julienw** [devtools-html/debugger.html#3216]
Normally, when stepping in a program, I expect that the current line is scrolled to while I step.

But it looks like that when we have a search string that matches in the same file, the view is scrolled to the match instead of the stepped line.

STR:
1. open https://everlong.org/mozilla/testcase-debugger/
2. Open the debugger
3. open the file `script.js`
4. type CTRL-F, search for the string `Lorem`. It should match something.
5. open the file `(index)`
6. put a breakpoint line 13 (line `behavior()`)
7. click the button. The debugger should break at line 13.
8. press the button "step in" to step in the function `behavior`.

Expected:
* The current line should be visible.

Actual:
* it's not, instead the search is hilighted.

**Comment by jasonLaster** [comment]
This fixes the bug, but I think we should revisit and see if we can better organize the options findNext, keepSelection...

https://github.com/jasonLaster/debugger.html/tree/fix-search-pause

**Comment by jasonLaster** [comment]
@anshul is working on this

**Comment by jasonLaster** [comment]
Here is a GIF of the bug:

![](http://g.recordit.co/xclfU6sQ13.gif) and a [commit](https://github.com/jasonLaster/debugger.html/commit/fcce2c09ab924b3aa53e76f8e6a01b7c9cad0e0f) of a potential fix.

**Comment by jasonLaster** [comment]
@anshul still interested in this?

**Comment by AlexisDeschamps** [comment]
I was actually able to replicate the bug about a week ago, but now I don't seem to be able to. Could recent updates have fixed the bug?

Here's what I get now:
![ezgif-4-ed56a099f0](https://user-images.githubusercontent.com/12681350/36863696-78eb8638-1d58-11e8-8018-5814bb7f920f.gif)

**Comment by jasonLaster** [comment]
ooh... 

Try doing a git bisect. Or basically git checkout a commit from a week or two ago and run `yarn; yarn start`

**Comment by jasonLaster** [comment]
yep, i couldn't reproduce either. @julienw mind trying again?

**Comment by julienw** [comment]
yes I believe this is fixed
