### ISSUE TITLE
[Editor] HTML should be syntax highlighted

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3222]
I think we had this working earlier. My guess is that this is related to the sourceText -> source conversion.

<img src='https://shipusercontent.com/da4c998fc7a229a91bb0b28530a74901/Screen%20Shot%202017-06-23%20at%209.41.16%20PM.png' title='Screen Shot 2017-06-23 at 9.41.16 PM.png' width=878>

**Comment by jbhoosreddy** [comment]
@jasonLaster thank god I read this. I had so many confusions. I still see parts of code in actions/ast, etc. rely on source text. I'm guessing we want to change remaining sourcesText -> sources?

**Comment by jasonLaster** [comment]
Yeah. Where are the source text references?
