### ISSUE TITLE
[SymbolModal] Add button to file search to open symbol search

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#3233]
Previously file search had `variables` and `functions` buttons to toggle the symbol search type. With the symbol searching being moved to a modal we just want a button that opens the symbol search modal.

<img width="866" alt="screen shot 2017-08-02 at 5 43 37 pm" src="https://user-images.githubusercontent.com/254562/28896387-4389b2de-77aa-11e7-9285-fe57357d16f0.png">

**Comment by jasonLaster** [comment]
I'd like to focus on what atom and sublime do with CLI like UIs

`@` `*` `#` etc

**Comment by aklt** [comment]
I'm working on this! :-)

**Comment by aklt** [comment]
What do you think about this UI:

![ffdebug-find](https://user-images.githubusercontent.com/142361/29124041-ff569d66-7d17-11e7-9510-44f4549d2da2.gif)

**Comment by jasonLaster** [comment]
Nice. That toggle makes more sense to me in the project search context. Perhaps we just have a "Search for functions" link?

**Comment by aklt** [comment]
That was a quick answer!  :-)
