### ISSUE TITLE
[SymbolModal] Animate the symbol search enter/leave

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#3234]
Use `react-transition-group` to animate the modal's enter and leaving. I think a slide in/out animation should look good.

**Comment by jasonLaster** [comment]
I'm not too familiar with animating in CSS or JS, so i'll defer to others.

I think the initial idea was to animate the modal in from the top.

By the way, the modal we're talking about is opened with cmd+shift+o. It is used to search for functions now, but in the future will be files and variables as well.

**Comment by wldcordeiro** [comment]
I'll jump on this. Easing back in and I've used this recently. 😄
