### ISSUE TITLE
[Preview] Parse more function symbol types

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#3239]
Currently our symbol parsing doesn't understand some function types that might be used in the wild. It doesn't cover cases where we have `MethodDefinition`s in a class or an arrow function `ClassProperty`. I have a branch ~[here](https://github.com/wldcordeiro/debugger.html/tree/parse-more-symbols)~ that gets us nearly there with parsing these symbol types.

Or if you aren't a fan of checking out a branch here is a [patch](https://gist.github.com/wldcordeiro/1acf6b11f947291fdb47a94cffa23096)

**Comment by firhatsungkar** [comment]
@wldcordeiro Is this issue still available ? Can I work on this issue?

**Comment by jasonLaster** [comment]
It's yours @firhatsungkar

**Comment by jasonLaster** [comment]
@firhatsungkar any luck?

**Comment by jasonLaster** [comment]
@firhatsungkar making it available again. Feel free to re-claim

**Comment by wldcordeiro** [comment]
I'm going to claim this. I want this for selfish reasons 😈

**Comment by jasonLaster** [comment]
ping @wldcordeiro

**Comment by wldcordeiro** [comment]
Been off this for a while with quick open modal stuff. I'll grab this now
