### ISSUE TITLE
Move test files from test folders to `filename.spec.js`

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3243]
We would like our unit tests to be inline with the files they're testing. We can do this by having the test files names `<filename>.spec.js`

**Comment by jasonLaster** [comment]
Here is a list of our tests

> A good bash script or node script should be able to do this transform in one step :)

- [ ] src/actions/tests/ast.js
- [ ] src/actions/tests/breakpoints.js
- [ ] src/actions/tests/expressions.js
- [ ] src/actions/tests/navigation.js
- [ ] src/actions/tests/pending-breakpoints.js
- [ ] src/actions/tests/sources.js
- [ ] src/actions/tests/ui.js
- [ ] src/client/firefox/tests/commands.js
- [ ] src/client/firefox/tests/onconnect.js
- [ ] src/components/Editor/tests/Editor.js
- [ ] src/components/Editor/tests/SearchBar.js
- [ ] src/components/SecondaryPanes/Frames/tests/Frame.js
- [ ] src/components/SecondaryPanes/Frames/tests/FrameMenu.js
- [ ] src/components/SecondaryPanes/Frames/tests/Frames.js
- [ ] src/components/SecondaryPanes/Frames/tests/Group.js
- [ ] src/components/tests/Outline.js
- [ ] src/components/tests/SymbolModal.js
- [ ] src/components/tests/WhyPaused.js
- [ ] src/components/tests/closeButton.js
- [ ] src/components/tests/previewFunction.js
- [ ] src/components/tests/resultList.js
- [ ] src/reducers/tests/breakpoints.js
- [ ] src/reducers/tests/sources.js
- [ ] src/reducers/tests/ui.js
- [ ] src/test/integration/tests/asm.js
- [ ] src/test/integration/tests/breaking-from-console.js
- [ ] src/test/integration/tests/breaking.js
- [ ] src/test/integration/tests/breakpoints-cond.js
- [ ] src/test/integration/tests/breakpoints.js
- [ ] src/test/integration/tests/call-stack.js
- [ ] src/test/integration/tests/debugger-buttons.js
- [ ] src/test/integration/tests/editor-gutter.js
- [ ] src/test/integration/tests/editor-highlight.js
- [ ] src/test/integration/tests/editor-preview.js
- [ ] src/test/integration/tests/editor-select.js
- [ ] src/test/integration/tests/expressions.js
- [ ] src/test/integration/tests/iframes.js
- [ ] src/test/integration/tests/index.js
- [ ] src/test/integration/tests/keyboard-navigation.js
- [ ] src/test/integration/tests/keyboard-shortcuts.js
- [ ] src/test/integration/tests/navigation.js
- [ ] src/test/integration/tests/pause-exceptions.js
- [ ] src/test/integration/tests/pretty-print-paused.js
- [ ] src/test/integration/tests/pretty-print.js
- [ ] src/test/integration/tests/returnvalues.js
- [ ] src/test/integration/tests/scopes-mutations.js
- [ ] src/test/integration/tests/scopes.js
- [ ] src/test/integration/tests/searching.js
- [ ] src/test/integration/tests/sourcemaps-bogus.js
- [ ] src/test/integration/tests/sourcemaps-reloading.js
- [ ] src/test/integration/tests/sourcemaps.js
- [ ] src/test/integration/tests/sourcemaps2.js
- [ ] src/test/integration/tests/sources.js
- [ ] src/test/integration/tests/tabs.js
- [ ] src/utils/parser/tests/closest.js
- [ ] src/utils/parser/tests/getOutOfScopeLocations.js
- [ ] src/utils/parser/tests/getSymbols.js
- [ ] src/utils/parser/tests/scopes.js
- [ ] src/utils/search/tests/build-query.js
- [ ] src/utils/search/tests/get-matches.js
- [ ] src/utils/search/tests/project-search.js
- [ ] src/utils/tests/frame.js
- [ ] src/utils/tests/fromJS.js
- [ ] src/utils/tests/object-inspector.js
- [ ] src/utils/tests/scopes.js
- [ ] src/utils/tests/source-search.js
- [ ] src/utils/tests/source.js
- [ ] src/utils/tests/sources-tree.js

**Comment by Ronsho** [comment]
On it.

**Comment by jasonLaster** [comment]
After talking with @Ronsho, it's not clear that we want to do this.

The reason for that is that snapshots and helpers still belong in a tests directory.

Also, jest and immutable use the `__tests__` folder pattern

**Comment by wldcordeiro** [comment]
@jasonLaster If we use the `.spec.js` style and retain the test dirs we get the best of both worlds and can remove the special pattern match for the test folders and rely on it finding the specs.

**Comment by jasonLaster** [comment]
yea, that's a good point.

@Ronsho still interested?

**Comment by Ronsho** [comment]
So we are for moving only the spec files out of the tests dir?

**Comment by jasonLaster** [comment]
Keeping them in the test dir, but with the suffix

**Comment by Ronsho** [comment]
Will take it!
