### ISSUE TITLE
Allow to remove or disable event listeners of DOM nodes

### ISSUE THREAD

**Issue by Defman21** [devtools-html/debugger.html#3247]
You can only see the list of listeners of a specific DOM node. I'd want to see a way to disable or remove an event listener (or all of them) without JS + DOM manipulation (copying the node, replacing the original one with the new one w/out listeners).

![screenshot_20170629_222520](https://user-images.githubusercontent.com/7100645/27706320-d8a509aa-5d19-11e7-9d07-f4aa22e80414.png)

**Comment by Defman21** [comment]
Looks like I've reported on the wrong repo though I didn't find one for the Inspector.  I'd be happy to move this issue to the right repo if needed.

**Comment by nt1m** [comment]
@Defman21 https://bugzilla.mozilla.org under Firefox > Developer Tools - Inspector

**Comment by Defman21** [comment]
Thanks.

**Comment by Defman21** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1226637
