### ISSUE TITLE
debugger shows a non existing event

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#3251]
With Firefox Nightly 56.0a1 (2017-06-29) (64-bit)
This is a spin-off of https://bugzilla.mozilla.org/show_bug.cgi?id=1376050

1.  Create an account on orbitz.com
2. Go to: https://www.orbitz.com/user/account
3. Click "other travelers"
4. Inspect the birth date field.

See how it has an associated event with it. 
Click the event and notice that it is empty.

<img width="412" alt="capture d ecran 2017-06-29 a 17 19 12" src="https://user-images.githubusercontent.com/505230/27715972-bf3d3d4a-5cef-11e7-9c08-2dc070f85baf.png">

Chrome and Safari do not display an event at all.

**Comment by bomsy** [comment]
This should be an inspector issue not a debugger issue.

**Comment by karlcow** [comment]
huh. indeed. Put that on the fatigue of the work week.
Sorry. Opened there 
https://bugzilla.mozilla.org/show_bug.cgi?id=1378017

**Comment by karlcow** [comment]
I was replying to an erased comment(?) saying
> This should be an inspector issue not a debugger issue.

**Comment by bomsy** [comment]
Sorry, my bad mistakenly erased it!
