### ISSUE TITLE
Can't debug Firefox WebExtention

### ISSUE THREAD

**Issue by YuriyPobezhymov** [devtools-html/debugger.html#3252]
Hello.
I use the project that was bootstrapped with Create React App.
I can debug my standalone app through you cool debugger, but I don't understand why, but I can't debug it as extension.
I try to do sidebar, so I place such code in manifest:
`  "sidebar_action": {
    "default_title": "My sidebar",
    "default_panel": "index.html"
  }`

The 'index.html' is the file that is built by 'node scripts/build.js' command.

**Comment by jasonLaster** [comment]
I'm closing this as I believe you can debug extension with the about:debugging in the new debugger now that it is released in dev edition
