### ISSUE TITLE
This page has no sources could be improved

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#3253]
This isn't something that happens often but I think we can do a little better than what we have here at least in terms of spacing / padding etc.

<img width="281" alt="screen shot 2017-06-30 at 8 29 18 am" src="https://user-images.githubusercontent.com/2134/27742803-d6856cc8-5d6e-11e7-9f74-9af30543a684.png">

**Comment by jasonLaster** [comment]
The initial design had the message vertically aligned in the middle. I believe this was a regression that happened with the outline tabs.

**Comment by belen-albeza** [comment]
I'm happy to take a look at this. It'd be my first PR for the project, so I might take a bit until I setup the whole thing locally.

**Comment by jasonLaster** [comment]
Thanks @belen-albeza. It's yours!

**Comment by clarkbw** [comment]
Great work @belen-albeza!
