### ISSUE TITLE
[CallStack] Replace Ember image with Tomster

### ISSUE THREAD

**Issue by locks** [devtools-html/debugger.html#3258]
As mentioned in https://github.com/devtools-html/debugger.html/pull/3154#issuecomment-307718763, the current Ember logo isn't very legible due to its width.

The task is to replace the current logo with a Tomster in the hopes that it improves legibility.
There is a Tomster we might be able to use at https://github.com/emberjs/ember-inspector/blob/master/public/assets/images/tomster.png, but it's PNG not SVG.
I'm trying to get an SVG.

**Comment by jasonLaster** [comment]
Thanks @locks

**Comment by jasonLaster** [comment]
https://worldvectorlogo.com/downloaded/ember-tomster

This site has a tomster that we can use.

Here are [docs] on using svgs. In this case we can replace the existing ember svg with this one.

[docs]:https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#svgs

**Comment by amelzer** [comment]
I'll take care of that later today :)

**Comment by amelzer** [comment]
Hey, I tried to find some ember projects to try this with but I mostly could'n get them to run. Any recommendations on where to find a simple project?

**Comment by locks** [comment]
Hey @amelzer, here's a list of a couple of Ember applications you can test on:

- https://emberjs.com/api
- https://emberjs.com/builds
- http://emberobserver.com/
- https://ember-twiddle.com/

**Comment by amelzer** [comment]
Hey @locks , thank you for your fast reply. I am just trying to get that old logo to show, maybe I am not on the right track :)
