### ISSUE TITLE
Discrepancy between UA string in emulator vs real device 

### ISSUE THREAD

**Issue by marcoscaceres** [devtools-html/debugger.html#3261]
On [twitter](https://twitter.com/igrigorik/status/882278990022672385), @igrigorik pointed out that, when emulating a device, there appears to be a discrepancy between the UA string sent by the device VS the UA string sent by developer tools. 

The [twit](https://twitter.com/igrigorik/status/882278990022672385) contains a couple of screenshots that illustrate the mismatch in the values being sent. 

I tried searching for where the UA strings are added, but couldn't find it. Should be easy to fix tho.

**Comment by marcoscaceres** [comment]
Dup of https://bugzilla.mozilla.org/show_bug.cgi?id=1317721

**Comment by jasonLaster** [comment]
Thanks for reporting. Closing as this is doesn't seem to be  debugger related

**Comment by marcoscaceres** [comment]
@jasonLaster, I'm still a bit confused as to where to file these bugs? Just keep using bugzilla for general devtools stuff?

**Comment by jbhoosreddy** [comment]
Things might seem a bit confusing as teams are moving from Bugzilla to GitHub and all of this is still in discussion/transition. For now, [debugger.html](https://github.com/devtools-html/debugger.html) and [perf.html](https://github.com/devtools-html/perf.html) can be found on GitHub. Issues/Bugs for the RDM project and other tools (like the Inspector) should still be filed on Bugzilla as that's where the code development/maintenance is done. @marcoscaceres
