### ISSUE TITLE
[Preview] start using symbols in preview

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3263]
Now that we have all the symbols for a file we can do a synchronous version of preview that does not need to traverse the AST when you mouse over a token.

Here are some new examples of tokens we can support:

* mousing over an object/array property
* properties inside of a call expression assignment `var App.TodoView = extend({ render() {} })`
* object properties inside of member expressions

Here's a branch: https://github.com/jasonLaster/debugger.html/tree/symbol-preview

**Comment by codehag** [comment]
I'm having a bit of difficulty getting started on this, as the branch is a bit behind master and it's hard to tell what is going on/what changed. Do you have an example of current vs desired behavior?
