### ISSUE TITLE
[Scopes] Save variable expand state while stepping

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3269]
We used to support keeping variable expand states while stepping. We dropped support earlier when we realized we were keeping stale data. We should look into re-adding support though.

**Comment by bgrins** [comment]
Same thing with Watch Expressions.  @jasonLaster would you like me to file a new issue for that or do you expect they would be handled here?

**Comment by bgrins** [comment]
STR:

Load data:text/html,<script>var obj = { a: { b: 'c' } }; document.onclick = function() { debugger; for (var i = 0; i < 3; i++) ; } </script>
Open debugger
Click anywhere to pause
Expand "Scopes" -> Window -> obj
Step

Expected:
obj remains expanded

Actual:
Window gets collapsed

**Comment by bgrins** [comment]
![stepping-watch](https://user-images.githubusercontent.com/95570/28469422-07980ef6-6deb-11e7-954f-963835e3dd1f.gif)

Gif of the behavior with watch expressions

**Comment by jasonLaster** [comment]
This might be a nice bug to re-explore.

I think step one is to talk to the console folks and see what we did in the old debugger. variable-view.jsm

**Comment by Standard8** [comment]
Does this issue cover the scopes as well? One of my biggest issues at the moment is when you're trying to watch a variable that is in one of the upper scopes, and you have to keep expanding it. IMHO that's a bug, rather than an enhancement.

**Comment by jasonLaster** [comment]
haha - yeah i can see that too. I'm moving this to the backlog so we'll get to it in the next sprint or two.

**Comment by janodvarko** [comment]
This issue is still nicely reproducible.

There are two places that need to be fixed:
* Watch Expressions
* Scopes
(additional bug might be reported)

Note that switching to another (callstack) frame and back also resets the expanded state.
It's not clear how long the state should be stored. E.g. resuming JS and breaking at the same state the next day should also work?

Honza
