### ISSUE TITLE
[ProjectSearch] results should stream in

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3270]
It would be nice if the project text worker could receive a "streaming" task and send results back appx every 100ms.

This [gist](https://gist.github.com/88b9b10d874a5da6242e798bb5e346e0) [branch](https://github.com/jasonLaster/devtools-core/tree/streaming-worker) starts that work. It's modeled after a similar worker I had in another project: [lazyWorker](https://github.com/marionettejs/marionette.inspector/blob/master/extension/js/agent/utils/lazyWorker.js)

The basic concept is this:

1. call a method to create a set of tasks
2. start a worker and do tasks for a set time interval (100ms)
3. after that time is up, report the results
4. if there are more tasks start again...

NOTE: this work will be done in [devtools-core](https://github.com/devtools-html/devtools-core) because we're updating the worker utils.

**Comment by jbhoosreddy** [comment]
I'm curious to learn this. I'll take this.

**Comment by jasonLaster** [comment]
Great. The test is close. Probably two puzzles away from completion

**Comment by jasonLaster** [comment]
Also, the lazy worker is one of my favorite strategies.

**Comment by jasonLaster** [comment]
We're landing the streaming worker

**Comment by codehag** [comment]
@jbhoosreddy are you currently on this?

**Comment by jasonLaster** [comment]
the util is in on core. I'm not working on using it yet.
