### ISSUE TITLE
[Tabs] Decouple tabs functionality from sources

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3279]
We currently show the current selected source tab as active.

We should show a new tab when you're doing a project text search. And it should be a bit active.

This is a bit challenging because tabs are currently associated with sources and URLs

**Comment by bomsy** [comment]
A couple of thoughts about it
* Use the HOC pattern for tabs (i.e split to `Tabs.js` and `Tab.js`)
* Use more generic naming  i.e `SourceTabs` to `Tabs`
* Separate tab actions from source actions file
* Have separate reducers for the tabs
* Remove dependencies on source urls

**Comment by codehag** [comment]
Is this currently in progress?

**Comment by bomsy** [comment]
no i've not started it yet. was going to pick it up next..

**Comment by codehag** [comment]
Wanted to add @ametzler's observations here as well:

"the Tab thing seems to affect more that the storybook. If I click the the '+' symbol and search the project, it does not open a new tab but loads the file in the current one"

**Comment by jasonLaster** [comment]
https://github.com/devtools-html/debugger.html/pull/4199

**Comment by jasonLaster** [comment]
The PR has all but the source tests passing in Jest. The next step is to finish up the jest tests and then focus on the mochitests.
