### ISSUE TITLE
[Breakpoints] (and more generally the paused line) is one too far down in XUL files.

### ISSUE THREAD

**Issue by bwinton** [devtools-html/debugger.html#3282]
Uh, what it says there.  If I click on a line, the breakpoint shows up on the line below, and when I'm stepping through the code, the line that gets executed is the one before the highlighted line.

**Comment by jasonLaster** [comment]
@bwinton do you have a good STR? I don't have a great XUL file that I like to debug :)

**Comment by bwinton** [comment]
In today's nightly, open the Browser Toolbox.
Ctrl-P search for tabbrowser.xml and open it.
Ctrl-F search for `name="_adjustFocusAfterTabSwitch"`, scroll down and click on line 1349 to set a breakpoint.  (Notice it slides down to 1350, a blank line.)
Opening a new tab isn't working for me now, but when it does, it should hit that breakpoint, and you can see the odd stepping behaviour…

**Comment by codehag** [comment]
This might be an issue in the server; It returns the following error:  
noCodeAtLineColumn: “Could not find any entry points to set a breakpoint on, even though I was told a script existed on the line I started the search with.”

Also, this works with the old debugger

**Comment by jasonLaster** [comment]
a similar bug
https://bugzilla.mozilla.org/show_bug.cgi?id=1363534

**Comment by darkwing** [comment]
Since XUL is going away, and this didn't work in the previous debugger, can we close this?

**Comment by jasonLaster** [comment]
I think so, we can track it in firefox...
