### ISSUE TITLE
[Preview] the highlight expression is too bright in the dark theme

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3283]
The preview highlight is too bright. This is an easy CSS fix, which just requires looking at our CSS variables or adding a custom color. Here are some [color](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#colors) docs.

```diff
diff --git a/src/components/Editor/Preview.css b/src/components/Editor/Preview.css
index 87fe815..68018bd 100644
--- a/src/components/Editor/Preview.css
+++ b/src/components/Editor/Preview.css
@@ -28,6 +28,10 @@
   cursor: pointer;
 }
 
+/*
+  We should either find a different variable
+  Or add a custom color here...
+ */
 .selection, .debug-expression.selection {
   background-color: var(--theme-highlight-yellow);
```

![](http://g.recordit.co/YQ6BCy6fGh.gif)

**Comment by GeoDoo** [comment]
Hello, Jason! I am new in OSS and contributing in general so bear with me!

It would be my pleasure to help on this one, because it seems easy enough!

**Comment by jasonLaster** [comment]
Hi @GeoDoo! Thanks. Feel free to stop by our slack room w/ any questions getting started or what not

**Comment by jasonLaster** [comment]
![Pasted image at 2017_07_11 04_34 PM.png](https://shipusercontent.com/97458c2628c6c1e0d8a179476b7c9c21/Pasted%20image%20at%202017_07_11%2004_34%20PM.png)


I looked into using a dark yellow as a highlight color but I think the olive tone clashes too much with the day glo green. I think blue would inaccurately associate itself with the breakpoint icon. How about using a darker purple (#743884) background with brighter text (#E7EBEE) as seen below?

**Comment by codehag** [comment]
looks good!
