### ISSUE TITLE
[Breakpoints] Slid Breakpoints can be in the wrong position after reloading

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3290]
[STR]
1. go to http://localhost:8000/integration/examples/doc-scripts.html
2. select simple1.js
3. add a bp on line 2
4. keep reloading

You'll see the BP jump between line 2, and 4.

The problem is that we rely on the breakpoint client location, which does not update based on the sliding. We can either update it to do that, or stop using the breakpoint client entirely. The benefit is that we can simplify the system so the redux store is the one source of truth.

```diff
commit 648e1f70ecfb70478b78d848a579f50a5d2e3a56
Author: Jason Laster <jason.laster.11@gmail.com>
Date:   Sun Jul 9 14:15:14 2017 -0400

    klj

diff --git a/src/client/firefox/commands.js b/src/client/firefox/commands.js
index 32f59ef..9597c85 100644
--- a/src/client/firefox/commands.js
+++ b/src/client/firefox/commands.js
@@ -23,7 +23,11 @@ import type {

 import { makeLocationId } from "../../utils/breakpoint";

-import { createSource, createBreakpointLocation } from "./create";
+import {
+  createSource,
+  createBreakpointLocation,
+  getActualLocation
+} from "./create";

 let bpClients: BPClients;
 let threadClient: ThreadClient;
@@ -111,10 +115,18 @@ function setBreakpoint(
       noSliding
     })
     .then(([{ actualLocation }, bpClient]) => {
-      actualLocation = createBreakpointLocation(location, actualLocation);
-      const id = makeLocationId(actualLocation);
+      const bpactualLocation = createBreakpointLocation(
+        location,
+        actualLocation
+      );
+
+      const id = makeLocationId(bpactualLocation);
       bpClients[id] = bpClient;
-      return { id, actualLocation };
+
+      const bpLocation = getActualLocation(bpClient.location, actualLocation);
+      bpClient.location = bpLocation;
+
+      return { id, actualLocation: bpactualLocation };
     });
 }

diff --git a/src/client/firefox/create.js b/src/client/firefox/create.js
index ee40654..5f88cdb 100644
--- a/src/client/firefox/create.js
+++ b/src/client/firefox/create.js
@@ -73,3 +73,14 @@ export function createBreakpointLocation(
     column: actualLocation.column
   };
 }
+
+export function getActualLocation(location: Location, actualLocation?: Object) {
+  if (!actualLocation) {
+    return location;
+  }
+
+  return {
+    line: actualLocation.line,
+    column: actualLocation.column
+  };
+ }
```

**Comment by jbhoosreddy** [comment]
Oh my god integration test samples were hosted on locahost:8000? I wish I knew that.

**Comment by jasonLaster** [comment]
Lol we should show that on the launchpad

**Comment by codehag** [comment]
We have the following cases:
- Debugger is reloaded (client breakpoints are discarded)
- Debuggee is reloaded (client breakpoints are used to break immediately if a breakpoint is detected.)

If we clear the client breakpoints, this would simplify our code (which would be great), the drawback being that we will need to pause everything on the debuggee until we know that we do not need to break on an early breakpoint, this might be disruptive to the user. What do you folks think?

**Comment by jasonLaster** [comment]
this should be fixed post refactor.

I'll leave open so we can confirm next week on nightly
