### ISSUE TITLE
Debugger does not send the user to the console in the case of an error

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3292]
While debugging, I noticed that if there was an exception in the code while i was working in the debugger, I would not have any indication that an exception had been thrown. Instead, the debugger would show me which line it had paused on. It might make sense to have the user directed to the console if an error is thrown, or have some visual indication that there has been an exception.

**Comment by jasonLaster** [comment]
I like how chrome handles this by underlying the exception expression in the debugger. What do others think?

**Comment by jasonLaster** [comment]
closing to focus on #3112
