### ISSUE TITLE
[ColumnBP] Remove breakpoints on click and alt + click

### ISSUE THREAD

**Issue by bomsy** [devtools-html/debugger.html#3296]
At the moment we add breakpoints on click, it would be nice to remove a existing breakpoint when it is clicked and also on alt + click

**Comment by jasonLaster** [comment]
@bomsy where is this at?

**Comment by bomsy** [comment]
It seems like there is some regression here, Clicking to add the breakpoint no longer works... will investigate

**Comment by codehag** [comment]
this is working for me, @bomsy perhaps this is done?

**Comment by bomsy** [comment]
heya, @yulia i checked again ...
This is what i see

#### Fixed
* We can add / remove column breakpoints on alt + click

#### Not Fixed
* We can't at the moment remove an existing column breakpoint when we click on it
* I'm still also having the issue where the breakpoint point is offsets are wrong

![](http://g.recordit.co/nKxU3cJJx3.gif)

Please confirm this

**Comment by bomsy** [comment]
Will get a fix out today.
