### ISSUE TITLE
Refactor Reducers and Selectors

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3301]
This depends on #3300 

Our reducers are doing a lot of logic and data formatting. With an api and thunks in place, we can move logic from the reducers that is currently data formatting logic into the api. This will allow our reducers to be pure. We can also remove all calls in reducers to other actions/ store (ie prefs) and make reducers independant. This will also be an opportunity to move prefs into its own "store"

We will need to:
- move selectors into their own files
- move all formatting logic out of reducers
- decouple reducers
- decouple prefs

**Comment by jasonLaster** [comment]
Closing as we're working on some of this now.
