### ISSUE TITLE
Selection Line Height Uneven

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#3304]
<img width="297" alt="lineheight" src="https://user-images.githubusercontent.com/46655/28077886-aa05fc72-6628-11e7-9fd4-2eeed664d5fe.png">

This is super minor but there appears to be more pixels on top of highlighted text and very few (if any) on the bottom of highlighted text.

**Comment by jasonLaster** [comment]
This probably explains why you can scroll off the bottom and we don't update. I've been wondering how this could happen.

**Comment by jasonLaster** [comment]
fixed
