### ISSUE TITLE
[Breakpoint] Adding Breakpoints in (index) Throws Errors

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#3308]
We can add breakpoints anywhere in `(index)`; adding a breakpoint on a line with no JS (i.e. a line with only a META tag) throws the following error:

```
worker-utils.js?002c:61 Uncaught TypeError: Cannot read property 'apply' of undefined
    at workerHandler (worker-utils.js?002c:61)
```

Of course adding a breakpoint in HTML is a useless thing to do but worth pointing out the error.

**Comment by darkwing** [comment]
Hmm, actually it throws the same error when in a SCRIPT tag within (index):

<img width="540" alt="err" src="https://user-images.githubusercontent.com/46655/28078769-8abfc296-662b-11e7-8b7f-50d6efb48d65.png">

**Comment by darkwing** [comment]
I should point out I'm seeing this in Chrome, BTW.

**Comment by jasonLaster** [comment]
thanks - we should at a minimum add a mochitest so that we can lock down this behavior.

**Comment by jasonLaster** [comment]
@darkwing - do you have an STR for this case?

**Comment by darkwing** [comment]
Closing this as I can no longer reproduce the issue.

**Comment by jasonLaster** [comment]
Great. I think we actually fixed this with @ryanjduffy parse-script-tags

**Comment by ryanjduffy** [comment]
🎉 for bonus fixes!
