### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#331]
Our project should include the license file, even though most files have (or should have) license headers embedded; a license file makes it clearer.

Here is the URL we are supposed to use, which is mostly markdown format already.
https://www.mozilla.org/media/MPL/2.0/index.txt

When adding a license file to any project it is recommended that we document the permission of previous contributors to ensure that they understand and agree to the license.

So if you've contributed to this repository (all users included in the list below) and agree to give permission for us to continue using the [MPL 2](https://www.mozilla.org/en-US/MPL/2.0/FAQ/), __please add the following comment to this issue__:

> I give my permission to license under the MPL 2 any contributions I have made to the debugger.html code base.

## Contributors
- [x] @marfarma 
- [x] @jay3686 
- [x] @ToucheSir 
- [x] @matt-oconnell 
- [x] @amitzur 
- [x] @ilancohen

**Comment by matt-oconnell** [comment]
I give my permission to license under the MPL 2 any contributions I have made to the debugger.html code base.

**Comment by jasonLaster** [comment]
@amitzur mind approving this?

**Comment by amitzur** [comment]
I give my permission to license under the MPL 2 any contributions I have made to the debugger.html code base.

**Comment by ilancohen** [comment]
I give my permission to license under the MPL 2 any contributions I have made to the debugger.html code base.

**Comment by clarkbw** [comment]
Checking in with @jay3686, @ToucheSir, and @marfarma

**Comment by ToucheSir** [comment]
I give my permission to license under the MPL 2 any contributions I have made to the debugger.html code base.

**Comment by clarkbw** [comment]
Last two to go, @jay3686 and @marfarma

**Comment by jay3686** [comment]
I give my permission to license under the MPL 2 any contributions I have made to the debugger.html code base.

**Comment by marfarma** [comment]
I give my permission to license under the MPL 2 any contributions I have made to the debugger.html code base.

**Comment by clarkbw** [comment]
Thank you everyone!  This is awesome.
