### ISSUE TITLE
New debugger frontend breaks serviceworker debugging

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3313]
copy of https://bugzilla.mozilla.org/show_bug.cgi?id=1380085

STEPS TO REPRODUCE:

1)  Start current nightly with clean profile.
2)  Load about:debugging.
3)  Click the "Workers" text in the sidebar on the left.
4)  Click the "Opt out of multiple content processes" button in the yellow
    warning about service worker debugging not being e10s-multi compatible.
5)  Click "OK" in the resulting confirmation prompt.  This will restart your
    browser.
6)  After restart, open a new tab in addition to about:debugging.
7)  Load https://perfht.ml/2uavsT8 in that new tab.
8)  Go back to the about:debugging tab.
9)  Click the "Debug" button for the running "https://perf-html.io/sw.js" service
    worker.
10) Observe the resulting debugger window that comes up.

EXPECTED RESULTS: Has service worker source, lets you debug it.

ACTUAL RESULTS: "This page has no sources".

ADDITIONAL INFORMATION: Toggling the "devtools.debugger.new-debugger-frontend" preference to "false" makes things work: clicking the Debug button shows the service worker source.  Toggling it back to "true" makes things not work again.

**Comment by jasonLaster** [comment]
https://pastebin.mozilla.org/9026873

**Comment by jasonLaster** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1380867
