### ISSUE TITLE
Crypto errors are not descriptive 

### ISSUE THREAD

**Issue by vladikoff** [devtools-html/debugger.html#3315]
Not sure if this is the right place to file this:

### Firefox

![](http://v14d.com/i/59659ccd719ac.jpg)

### Chrome

![](http://v14d.com/i/59659cedc0fe1.jpg)

#### Expected 

Firefox should say ` key is not extractable`

**Comment by jasonLaster** [comment]
@vladikoff I'm going to close this as this project is focused on the debugger UI. This is likely a console issue.
