### ISSUE TITLE
[WhyPaused] exception details in dark theme

### ISSUE THREAD

**Issue by zaggy** [devtools-html/debugger.html#3316]
Color of the WhyPaused exception details in latest Nightly is very hard to read in dark theme. 
![image](https://user-images.githubusercontent.com/69977/28101352-b9f0eeb2-6713-11e7-9ac8-80d813d2874a.png)

Need to revise the color in favor of something more contrast to the background color. Maybe something like that:
![untitled](https://user-images.githubusercontent.com/69977/28101516-b750dde2-6714-11e7-9ad3-ac1a71aa797a.png)

**Comment by zaggy** [comment]
I can play with the colors sometime next week.

**Comment by jasonLaster** [comment]
thanks @zaggy. I like the direction you're going in.

**Comment by jasonLaster** [comment]
Here's a sketch for where the CSS should go

```diff
diff --git a/src/components/SecondaryPanes/Frames/WhyPaused.css b/src/components/SecondaryPanes/Frames/WhyPaused.css
index 2e8ba0e..ca6bc41 100644
--- a/src/components/SecondaryPanes/Frames/WhyPaused.css
+++ b/src/components/SecondaryPanes/Frames/WhyPaused.css
@@ -24,3 +24,7 @@
   color: var(--theme-graphs-full-red);
   font-weight: bold;
 }
+
+.theme-dark .secondary-panes .why-paused .message.warning {
+  /* something better in here*/
+}
```

Feel free to test this by setting the Pause on Exceptions button to pause on all exceptions and then adding something crazy :) like `throw new Error("fo")`

**Comment by digitarald** [comment]
For legibility we might also want to remove the italic style on the error text (leave it on `Paused on …`.
