### ISSUE TITLE
[scopes] Anonymous Functions  are weird in some cases

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#3317]
Steps to reproduce:

1. Go to `data:text/html,test<script>let x = [function(){}, function(){}]; debugger</script>`
2. Open the devtools and reload the page
3. The page should now be paused

If you look at the Scopes panel, you can see that the `x` items, which are 2 functions, are displayed a bit weirdly : 

![screen shot 2017-07-12 at 09 28 31](https://user-images.githubusercontent.com/578107/28106595-b852bfec-66e4-11e7-822f-3e028e90d795.png)

```
▼ x: [2]
    ▶︎ 0()
    ▶︎ 1()
```

This is due to the `previewFunction` which use the property name to render function like `${propertyName}()`. In the case of an array, this is odd since it shows the index followed by parens, which can be confusing.

In this situation, it would be nice to fallback to the regular output like : 
```
▼ x: [2]
    ▶︎ 0: function()
    ▶︎ 1: function()
```

I guess we could have similar issues with Set and WeakSet.

Since the ObjectInspector is now in devtools-core, and that we plan to have a similar way of rendering functions, this could be fixed there.

**Comment by jasonLaster** [comment]
Agreed

**Comment by jasonLaster** [comment]
closing as this is handled in devtools-core
