### ISSUE TITLE
Maps & Sets content are not displayed in the Scopes panel

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#3319]
Steps to reproduce: 
1. Go to https://codepen.io/nchevobbe/full/JJwMpP/
2. Open the debugger
3. Reload the page

The debugger should now be paused.
`xmap` and `xset` are resp. a map and a set with at least one item.

But, if you inspect it in the Scopes panel, you can't see their content (we only show the `size` and `__proto__` properties) : 

![screen shot 2017-07-12 at 09 50 29](https://user-images.githubusercontent.com/578107/28107554-8d622a94-66e8-11e7-9b1c-e85351ab913c.png)

We could show them like we do in the variable view in the old console frontend : 

```
▼ Map
    ▼ <entries>
        "a" : "b"
```
and 
```
▼ Set
    ▼ <entries>
        0 : "a"
        1 : "b"
```

The same issue applies to WeakSet and WeakMap

**Comment by jasonLaster** [comment]
I believe we can move this to devtools-core as it is an `OI` issue

**Comment by jasonLaster** [comment]
closing as it's filed in devtools-core
