### ISSUE TITLE
There is no bucketting for NodeList objects

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#3320]
Steps to reproduce:
1. Go to [mozilla.org](http://www.mozilla.org)
2. Open the console
3. Evaluate the following expression : 
```js
{
  let nodelist = document.querySelectorAll("*"); 
  let arr = Array.from(nodelist); 
  debugger;
}
```

The debugger should now be paused.
In the Scopes panel, if you expand `arr`, you can see that it is bucketed (group of 100 items).
If you expand `nodelist`, there is no bucketing and we show +1000 NodeList items.

I think maybe we could expose a `supportBucketing` function, or something similar in Reps so we can use it in the ObjectInspector.

**Comment by jasonLaster** [comment]
I think we should move this to `devtools-core` as it is an OI concern

**Comment by nchevobbe** [comment]
I agree. Could you file an issue to use the PI from devtools-core in the
debugger and assign it to me ? I will look at that next week

Le 12 juil. 2017 5:26 PM, "Jason Laster" <notifications@github.com> a
écrit :

**Comment by jasonLaster** [comment]
closing as the bug is in core
