### ISSUE TITLE
RFC: Remove Pending Breakpoints

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3321]
Here is the thinking behind this: PendingBreakpoints are a duplication of state. We end up always having to update both prefs and pendingBreakpoints which have to always be in sync; though there is no real benefit from this other, and it makes maintaining the code more difficult.

Here is my understanding of PendingBreakpoints (please fill in if I missed something):
- we use them to persist breakpoints between sessions

This means that we do not need to have the pending breakpoints added optimistically, and it means that we do not need a representation of them, because they are never used for display. they are effectively outside information, that does not need to be re-represented in the redux store.

I would propose relying only on the prefs store for this, it would simplify our data flow and would require fewer updates.

Let me know what you think!

**Comment by jasonLaster** [comment]
:thumbsup:

**Comment by jasonLaster** [comment]
After thinking about it a bit more, I think we first want to simplify how we store prefs. There are two problems that I see with prefs:

1. it's possible the current value of prefs is different from the current value of the store
2. the code is making the reducers ugly! Here's a patch where we remove the pref updating logic from the reducers. In my mind, this should be our first goal 💃 

```diff
diff --git a/src/reducers/breakpoints.js b/src/reducers/breakpoints.js
index 8769f0a..7df4fd1 100644
--- a/src/reducers/breakpoints.js
+++ b/src/reducers/breakpoints.js
@@ -53,10 +53,6 @@ function update(
       const newState = addBreakpoint(state, action);
       // TODO: remove this when we have a prefs reducer
       const stateWithShim = addPendingBreakpoint(newState, action);
-      setPendingBreakpoints(stateWithShim);
-
-      // const stateWithShim = addPrefBreakpoint(newState, action);
-
       return stateWithShim;
     }

diff --git a/src/reducers/ui.js b/src/reducers/ui.js
index ef56e94..6c9876d 100644
--- a/src/reducers/ui.js
+++ b/src/reducers/ui.js
@@ -98,18 +98,6 @@ function update(
     case "TOGGLE_FILE_SEARCH_MODIFIER": {
       const actionVal = !state.getIn(["fileSearchModifiers", action.modifier]);

-      if (action.modifier == "caseSensitive") {
-        prefs.fileSearchCaseSensitive = actionVal;
-      }
-
-      if (action.modifier == "wholeWord") {
-        prefs.fileSearchWholeWord = actionVal;
-      }
-
-      if (action.modifier == "regexMatch") {
-        prefs.fileSearchRegexMatch = actionVal;
-      }
-
       return state.setIn(["fileSearchModifiers", action.modifier], actionVal);
     }

@@ -123,11 +111,9 @@ function update(

     case "TOGGLE_PANE": {
       if (action.position == "start") {
-        prefs.startPanelCollapsed = action.paneCollapsed;
         return state.set("startPanelCollapsed", action.paneCollapsed);
       }

-      prefs.endPanelCollapsed = action.paneCollapsed;
       return state.set("endPanelCollapsed", action.paneCollapsed);
     }
```

Isn't it nice, it's great! It's the best! So how do we update the prefs? I think there are two ways that come to mind. 

1. introduce a prefs reducer
2. add a store subscriber


Here is what the subscriber would look like:

```diff
diff --git a/src/utils/bootstrap.js b/src/utils/bootstrap.js
index 9231c5c..31bcfac 100644
--- a/src/utils/bootstrap.js
+++ b/src/utils/bootstrap.js
@@ -31,6 +31,8 @@ export function bootstrapStore(client, services) {
     store.dispatch
   );

+  store.subscribe(() => updatePrefs(store.getState()));

   return { store, actions, selectors };
 }

diff --git a/src/utils/prefs.js b/src/utils/prefs.js
index 7ecc5c5..ea59137 100644
--- a/src/utils/prefs.js
+++ b/src/utils/prefs.js
@@ -51,4 +51,14 @@ if (prefs.debuggerPrefsSchemaVersion !== prefsSchemaVersion) {

+export function updatePrefs(state) {
+  prefs.each(prefName => {
+    const selector = selectors[`get${capitalize(prefName)}`];
+    const prefValue = selector(state);
+    if (prefs[prefName] !== prefValue) {
+      prefs[prefName] = prefValue;
+    }
+  });
+}
+
```

Both methods would work, but i think there are some advantages to using a subscriber. 

1. the subscriber does not care about the actions that should change the state. It also is not interested in how the state was changed. It JUST cares that the state changed. Think of this like a component, the component UI does not care when or why the data changed, it just reflects the current state of the data in UI form.

**Comment by jasonLaster** [comment]
@clarkbw suggests trying a middleware solution

https://github.com/clarkbw/Gecko-Profiler-Addon/commit/d86dcf0c4158c14a04337c7b9c5de11a9a613eee

**Comment by codehag** [comment]
I think both ideas have some good stuff in there. I think one issue with the subscriber is that it relies on duplicating state, rather than our use case, which is that we have data that is at the moment only represented in prefs. Subscribers work best if we have a state that needs to be persisted, but we don't have that. A good example of a place where this would fail is pendingBreakpoints. Also, The example that you gave is a good one: `fileSearchCaseSensitive` for instance has no representation in the application aside from in prefs, and would not be updated unless it is somehow represented in state. 

I think that's pointing us to the real issue we are having actually. We do not have a reducer clearly showing what is happening in the persisted state (prefs). This means that we do not have a single store. And that is what we are missing. I mistakenly thought that we should get rid of PendingBreakpoints, but no -- what we need is a place where the persisted state is represented. Otherwise we are breaking from the idea of having a single store. (this is where my misconception came from)

While I think that @clarkbw has an interesting proposal, I do not think it is the best case for us, as it introduces unnecessary complexity where we already have other tools that can accomplish the same thing. Also, it will not resolve the issue that we are using state that isnt in our central reducer.

What I would propose, @jasonLaster is that we combine parts of both our ideas, both 1 & 2. 

I would even say that we don't need the subscriber. i find using the subscribe method ... somewhat error prone. If you misname a function or change the name of a function, or if you change something in the return value, this will blow up. Further, if you need to do some form of data sanitation, or something specific for prefs, this does not give you space to do that. It is too generalized. It feels like a low level api that is too powerful. Plus, it has a few intricacies such as not running with every dispatch. 

Instead, We use a "PersistedState" reducer, which represents the missing application state. But rather than what I initially suggested of directly updating prefs, we are instead using this state to represent the persisted state.
We only act on changes to the `PersistedState` reducer, rather than the overall state. It would look something like this:

```javascript
// @flow

/**
 * Persisted State reducer
 * @module reducers/persisted-state
 */
import * as I from "immutable";

import { prefs } from "../utils/prefs";
import {
  makePendingLocationId,
  createPendingBreakpoint
} from "../utils/breakpoint";
import makeRecord from "../utils/makeRecord";

export function initialState() {
  return makeRecord(restorePersistedData)();
}

function update(state = initialState(), action) {
  switch (action.type) {
    case "ADD_BREAKPOINT": { // we can still have fine grained control of our state
      const newState = addPendingBreakpoint(state, action); // we are being declaritive here
      prefs.pendingBreakpoint = newState.get('pendingBreakpoints'); // and we are being declarative here
      return newState;
    }
    // ... and others
    default: {
      return state;
    }
  }
}

function addPendingBreakpoint(state, action) {
  if (action.status === "done") {
    const { value: { breakpoint, previousLocation } } = action;
    const pendingBreakpoint = createPendingBreakpoint(breakpoint);
    const id = pendingBreakpoint.id;

    if (previousLocation) {
      const previousLocationId = makePendingLocationId(previousLocation);
      return state
        .deleteIn(["pendingBreakpoints", previousLocationId])
        .setIn(["pendingBreakpoints", id], pendingBreakpoint);
    }

    return state.setIn(["pendingBreakpoints", id], pendingBreakpoint);
  }

  return state;
}

function restorePersistedData() {
  return I.Map(prefs);
}

export default update;
```
This way we are not making unnecessary low level calls for every update. We only touch prefs when we really need to. Alternatively, we can continue to use your subscriber, but have it only respond to changes in prefs... though this still feels wrong and like we will shoot ourselves in the foot.

I also considered using sagas for this purpose, as they are a middleware responding to actions, much like what @clarkbw suggested. But it doesn't get around the fact that we are then splitting up where our data is stored, which is the root of the problem here. Instead I would say the simplest solution for now will be to create a Prefs / persistedState reducer, and do the prefs assigment there / use a subscriber on the persistedState reducer.

**Comment by jasonLaster** [comment]
closing this as pending BPs are now in their own reducer
