### ISSUE TITLE
[Project Search] Cleanup the css and styles for dark theme

### ISSUE THREAD

**Issue by bomsy** [devtools-html/debugger.html#3326]
We just landed initial work for the Project text search UI [here](https://github.com/devtools-html/debugger.html/pull/3276)

We should do a bit of cleanup of the styles and add styling for dark theme

**Comment by jasonLaster** [comment]
@bomsy is this done?

**Comment by bomsy** [comment]
Yeah it is .. for what i had in mind at the time. Unless you have some more u need to do
