### ISSUE TITLE
file search loses source contents

### ISSUE THREAD

**Issue by jlongster** [devtools-html/debugger.html#334]
If I have a source open, press cmd+P to bring up the search bar, and press cmd+P again to hide it, all the source contents are gone.

**Comment by clarkbw** [comment]
> press cmd+P again to hide it

ah ha! I couldn't figure out how to hide it!

**Comment by jasonLaster** [comment]
haha - there are clearly some UX things here. We should open some small tickets for file search UX.

**Comment by jasonLaster** [comment]
@jbhoosreddy interested in grabbing this?

**Comment by jasonLaster** [comment]
This looks like a fix
https://gist.github.com/jasonLaster/2c9f9d5048c144ea5031d09efd9b9bb1
