### ISSUE TITLE
[Breakpoints] conditional breakpoint panel width is too wide

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3343]
We used to have the panel styled so that the close button was always aligned on the right.

<img src='https://shipusercontent.com/84ba0867c837538091b48a5337542b68/Screen%20Shot%202017-07-14%20at%209.59.40%20AM.png' title='Screen Shot 2017-07-14 at 9.59.40 AM.png' width=716>

At some point the panel became too wide.

<img src='https://shipusercontent.com/f00a7869c968a6f2d7836b61541b83af/Screen%20Shot%202017-07-14%20at%209.59.46%20AM.png' title='Screen Shot 2017-07-14 at 9.59.46 AM.png' width=668>

**Comment by irfanhudda** [comment]
Is this already fixed?

![screen](https://user-images.githubusercontent.com/1755089/28743918-97835906-7473-11e7-8f6c-86cc2be60d05.png)

**Comment by jasonLaster** [comment]
I don't think so...

**Comment by jasonLaster** [comment]
This looks fixed
