### ISSUE TITLE
[Breakpoints] XML files have weird breakpoint behavior

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3346]
When adding a breakpoint to an xml file, switching to the console, and returning the the debugger, if you try to remove that existing breakpoint, it will instead add a new one at the top of the file:

![weirdxmlbreakpoints](https://user-images.githubusercontent.com/26968615/28218051-a18fdb1c-68b7-11e7-810a-545d4288c66d.gif)

**Comment by KES777** [comment]
[for reference](https://bugzilla.mozilla.org/show_bug.cgi?id=1391989)
