### ISSUE TITLE
[L10N] Remove unused strings sourcesPane.showSourcesTooltip/showOutlineTooltip

### ISSUE THREAD

**Issue by Archaeopteryx** [devtools-html/debugger.html#3355]
The strings
```
sourcesPane.showSourcesTooltip
sourcesPane.showOutlineTooltip
```
added in #2975 https://github.com/devtools-html/debugger.html/commit/28db40a5bd0a20bd7b7a5a6c37b08dd0b9cbcee6#diff-20813869930fe033851f84e870d6693fR51
aren't used anymore since #3087 got merged: https://github.com/devtools-html/debugger.html/commit/92b200fd17e78caee03688322147534e66e3080d?diff=split#diff-20813869930fe033851f84e870d6693fL55

**Comment by jasonLaster** [comment]
Thanks

**Comment by Ronsho** [comment]
PR created -> https://github.com/devtools-html/debugger.html/pull/3526

**Comment by codehag** [comment]
Thanks!
