### ISSUE TITLE
[Editor] alignLine is off in the panel

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3357]
I've noticed at times that sometimes the debugger gets confused about lines that are actually visible: 

1. you click on a breakpoint that is hidden and you aren't shown it
2. you pause and the highlight line is not shown

I believe this happens because codemirror believes the line is visible and doesn't do anything. See the function `alignLine`.

Another theory is that we do something to keep the editor from jumping on the component side...

**Comment by codehag** [comment]
Do we have an STR with these two cases?

**Comment by jasonLaster** [comment]
I need to bump source editor
