### ISSUE TITLE
File Search - arrow key navigation

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#337]
Arrow Keys should navigate file search (up/down/enter)

![screen shot 2016-07-14 at 3 03 58 pm](https://cloud.githubusercontent.com/assets/254562/16852005/1811cfce-49d4-11e6-8f2e-ea917f28bc10.png)

**Comment by clarkbw** [comment]
> Arrow Keys should navigate

Might be nice to display this somewhere so people know / learn.  🔽 arrow down 🔼 arrow up ↩️ and enter to select

**Comment by jasonLaster** [comment]
yeah, although this might be something people would just expect... not sure how far accessibility has come in setting expectations :)

**Comment by amitzur** [comment]
Want to spark a small design discussion here:

1. Autocomplete needs to know what it's showing. I guess that should go as part of its local state. Should that be an array of the origin indices from props.items ? Or a list of the actual shown item objects? Also, not sure if this needs to be an immutable data structure (what's the benefit?). Maybe a Seq like props.items

2. component state also holds selectedIndex which is initially -1

3. keyUp handler on the input

**Comment by amitzur** [comment]
btw I mean to take this, not just discuss :)

**Comment by jasonLaster** [comment]
Thanks @amitzur. It's yours. 

> component state also holds selectedIndex which is initially -1
agreed

> keyUp handler on the input

> Autocomplete needs to know what it's showing
I'm not sure, at this time, I'm okay re-calculating the search results on enter. 

```js
results = this.getSearchResults()
result = results[selectedIndex]
this.props.selectItem(result)
```

The trade off with re-computing search results is speed, but at the moment we're just doing a string.includes call on the sources, which should not be expensive.

I wouldn't worry about immutable objects here if you do want to store results state :)

**Comment by amitzur** [comment]
makes sense. BTW, the keyUp on the input will take care of ArrowUp and ArrowDown, but the Escape I feel should go where the cmd+p shortcut goes, which is an event listener on the window defined in App.js

**Comment by jasonLaster** [comment]
agreed

**Comment by jasonLaster** [comment]
Thanks @amitzur!
