### ISSUE TITLE
RFC: Introducing Sagas

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3372]
We are going in a really excellent direction with our refactorings. One topic that came up during our work week was sagas. I did a little bit of drawing regarding how this would look from an architectural perspective:

<img width="1409" alt="screen shot 2017-07-19 at 1 50 24 pm" src="https://user-images.githubusercontent.com/26968615/28365748-0a4f4a4a-6c8a-11e7-846e-3ff461498248.png">

A comparison of the two approaches:

### Thunks:

Thunks are a promise based way of wrapping our dispatch action to handle asynchronous data. This is well suited when we have a simple asynchronous query. Simple here being defined as one responder, and at most one data change.

Pros: 
- easy to get started, you wrap the action in a dispatch with promise middleware. 
- Promises are easy to comprehend as they have been around for a while

Cons: 
- thunks are called. They do not have control over when they are called or how. This can result in bubbling
- there is a single potential error handler, the catch block, which is called sequentially. no fine grained control on errors / roll back /roll forwards
- they are not composeable
- make actions and reducers difficult to test

### Sagas:

Sagas rely on generators and sit between dispatched actions and the reducers they influence. They respond to actions and take care of multi-step data processing / server communicaton. This is best suited for distributed / long life transactions.

Pros: 
- fine grained error handling / roll backs / roll forwards
- sagas call, and are not called. They have more control over how they are executed, this reduces bubbling. 
- they return simple objects, sagas, reducers, and actions can be tested independantly

cons:
- rely on the generator pattern, which not many are familiar with
- require a large refactoring

### Reading Material:
- [Problems with Thunks and Sagas](http://blog.isquaredsoftware.com/2017/01/idiomatic-redux-thoughts-on-thunks-sagas-abstraction-and-reusability/)
- [Redux side effects reading list](https://github.com/markerikson/react-redux-links/blob/master/redux-side-effects.md)
- [Pros and cons of Redux Saga generators](https://stackoverflow.com/questions/34930735/pros-cons-of-using-redux-saga-with-es6-generators-vs-redux-thunk-with-es7-async)
- [similar discussion](http://en.arguman.org/we-should-switch-from-redux-thunk-to-redux-saga)

I still have a bit of thinking to do about this but am interested what others have on their minds!

**Comment by kwonoj** [comment]
Just throwing out question, feel freely ignore / discard 🙏  - has `epics` been considered as a candidate as well? (https://github.com/redux-observable/redux-observable/blob/master/docs/basics/Epics.md#epics)

**Comment by markerikson** [comment]
Hey, I recognize those first two links! :)  Nice diagrams too, btw.

Not sure I have specific feedback to offer, beyond agreeing that sagas (and the equivalents from `redux-observable` / `redux-logic` ) are definitely great tools for setting up complex async workflows and decoupling parts of an app architecture.  

You might also want to glance through some of the articles in the ["Redux Architecture"](https://github.com/markerikson/react-redux-links/blob/master/redux-architecture.md) section of my list, especially the "Variations" section - there's a few articles there that discuss interesting uses of sagas.

**Comment by jasonLaster** [comment]
Closing this issue as we're currently working on refactoring our redux thunk actions and will continue evaluating sagas as we go.

Thanks for all the input!
