### ISSUE TITLE
[Frames] Simplify Redux call stacks

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3375]
Here is a call stack from: perf.html running locally: [link](http://localhost:4242/public/3ae552768a35425c99fb71ddeab54ed50cfaa221/timeline/?invertCallstack&range=116.2780_132.3306&react_perf&thread=4) with a breakpoint in `profile-view.js:97` I think there are a couple of things we could do to simplify it:

1) group frames 2 - 9: **action dispatch**
2) group frames 11 - 13: **action dispatch**
3) group frames 14 - 21: **resolve promise**

In terms of algorithms:

1. group frames that match redux or thread-middleware.
2. group frames that match regenerator-runtime, core-js, or babel
3. label frame groups **action dispatch** if you see *combineReducers* or *createStore*
4. label frame groups **resolve promise** if you see `es6.promise` in the group

Curious to see what others with more knowledge think.

#### Call Stack

```
1 - webpack:///src/content/reducers/profile-view.js
2 - webpack:///~/redux/es/combineReducers.js
3 - webpack:///~/redux/es/combineReducers.js
4 - webpack:///~/redux/es/combineReducers.js
5 - webpack:///~/redux/es/createStore.js
6 - webpack:///~/redux-logger/lib/index.js
7 - webpack:///src/common/thread-middleware.js
8 - webpack:///~/redux-thunk/lib/index.js
9 - webpack:///~/redux/es/applyMiddleware.js
10 - webpack:///src/content/actions/receive-profile.js
11 - webpack:///~/redux-thunk/lib/index.js
12 - webpack:///~/redux/es/applyMiddleware.js
13 - webpack:///src/content/actions/receive-profile.js
14 - webpack:///~/regenerator-runtime/runtime.js
15 - webpack:///~/regenerator-runtime/runtime.js
16 - webpack:///~/regenerator-runtime/runtime.js
17 - webpack:///~/babel-runtime/helpers/asyncToGenerator.js
18 - webpack:///~/babel-runtime/helpers/asyncToGenerator.js
19 - webpack:///~/core-js/library/modules/es6.promise.js
20 - webpack:///~/core-js/library/modules/es6.promise.js
21 - webpack:///~/core-js/library/modules/_microtask.js
```

#### Screenshot

<img src='https://shipusercontent.com/b735055350bbe673a8c536974b035ca9/Screen%20Shot%202017-07-19%20at%202.38.28%20PM.png' title='Screen Shot 2017-07-19 at 2.38.28 PM.png' width=801>

### Steps to get started

1. go to https://github.com/devtools-html/perf.html/
2. git clone, npm install, npm start
3. add a breakpoint in `reducers/profile-view.js`

**Comment by gregtatum** [comment]
I'm not sure where _callee7$ is specifically coming from, somewhere in the thunk. It would be nice to have a clear stack showing `receiveProfileFromAddon` with the Redux pseudo stacks in there. The general principle would be nice to only show me what I really care about.

**Comment by jasonLaster** [comment]
hmm - i know what you're saying. I bet we can do something with function names and babel... Like go up and get the name...

**Comment by jasonLaster** [comment]
Here are two use cases

go to localhost:8000 and add breakpoints at `reducers/ast.js#83` (set_symbols) and `actions/ast.js#47` (setSymbols).!

| Reducer | Action |
|--|--|
| ![red] | ![act] |
[act]:https://shipusercontent.com/6f1907e5efe2e216fe64f68622a6dfdd/Screen%20Shot%202018-03-27%20at%2010.05.20%20AM.png
[red]:https://shipusercontent.com/1a887ecd5d626dc6620c2f44660818f7/Screen%20Shot%202018-03-27%20at%2010.06.46%20AM.png

**Comment by calebstdenis** [comment]
So I'm noticing a pattern here in our call stack groups. Seems like we should be basing the group name on the bottom frame rather than the top one.
![download](https://user-images.githubusercontent.com/7321311/38152666-cc906980-3436-11e8-92d9-a2adbda1f58a.png)

**Comment by jasonLaster** [comment]
hmm, can you share an example stack?

**Comment by calebstdenis** [comment]
For sure! [Here's the Jest test case](https://github.com/calebstdenis/debugger.html/commit/16471fb330b5452783b91afe5d046866e7e02e3d) for your [example](https://github.com/devtools-html/debugger.html/issues/3375#issuecomment-376541150).

Lemme rephrase what I've been saying: It would be super easy to make the above test pass. The hard thing is doing it in a way that would make it scale to projects other than our own. Actually... that got me thinking: maybe we just have the wrong test case.

**Comment by jasonLaster** [comment]
Moving this to the sandbox
