### ISSUE TITLE
[Preview] Mousing over the bottom of the token causes a flicker

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3377]
STR:
1. pause
2. move the mouse below a token and then onto the bottom of the token

expected: see the preview
actual: weird flickers

![](http://g.recordit.co/rKlJGarPIE.gif)

**Comment by codehag** [comment]
I am not able to get a convincing reproduction of this.. but is this due to the cursor position?

**Comment by codehag** [comment]
I initially took the "flicker" to be the behavior where it goes from showing the `this` object but then opening to the full object, but i am guessing that this behavior is expected?

**Comment by jasonLaster** [comment]
so... i can't reproduce this either. Lets leave it open for a bit and see

**Comment by jasonLaster** [comment]
I cant reproduce this
