### ISSUE TITLE
File Search - UI tweaks

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#338]
Here are a couple file search tweaks that come to mind. @helenvholmes, @clarkbw, @jlongster any others i'm missing?

- [x] the magnifying glass should be aligned on firefox (it is in chrome) (fixed)
- [x] the magnifying glass should only be blue when focused
- [x] the input bar should have placeholder copy for searching
- [x] file search should be open by default (with copy below mentioning cmd+p opens files) 
- [ ] there should be a button for exiting file search when there is already a selected source
- [x] Lets also replace the CSS values with variables

**Comment by jlongster** [comment]
Don't have many thoughts on this, but the magnifying glass is aligned for me in Firefox...

**Comment by jasonLaster** [comment]
oh strange

**Comment by clarkbw** [comment]
> but the magnifying glass is aligned for me in Firefox...

Same here.  Otherwise looks like a good list.

**Comment by jasonLaster** [comment]
Lets also replace the CSS values with (variables
)[https://github.com/jlongster/debugger.html/blob/master/public/js/lib/variables.css#L38]

**Comment by jasonLaster** [comment]
@amitzur, interested in working on this list? 

I think they should all be fairly actionable except for the item "file search" button one. @helenvholmes, do you have an idea of where you think we should surface a file search button if it's not open?
