### ISSUE TITLE
[Breakpoints] Breakpoints disappear on layout change

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3386]
https://bug1382432.bmoattachments.org/attachment.cgi?id=8888211

**Comment by jasonLaster** [comment]
I'm seeing an error w/ `clearDebugLine` not having the editor:

```js
	  clearDebugLine(selectedFrame) {
	    if (selectedFrame) {
	      var line = selectedFrame.location.line;
	      if (this.debugExpression) {
	        this.debugExpression.clear();
	      }
	
	      this.state.editor.codeMirror.removeLineClass(line - 1, "line", "new-debug-line");
	    }
	  }
```

**Comment by jasonLaster** [comment]
this should be fixed by the `editor.state` fix

**Comment by codehag** [comment]
Should now be fixed

**Comment by codehag** [comment]
This hasn't been fixed yet, but I will reopen the branch with the slightly hacky fix; we can work on a more robust solution in a bit

**Comment by jasonLaster** [comment]
should be fixed
