### ISSUE TITLE
[Scopes] should be able to copy values

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3388]
We should support copying variable names and values from the scopes pane. Lets look at what the old debugger and chrome UI does and draw some inspiration.

For example if the local scope has a variable `foo` with the value `"Hello World"`, the user should be able to right click on `foo` and add it to the clipboard.

**Comment by codehag** [comment]
when i copy the stack trace i get this
```
arithmetic (math.min.js#18)
(global) (SOURCEsource2886#1)
```

in chrome, the copy stack trace looks like this:

```
arithmetic (math.min.js:formatted:18)
(anonymous) (VM71:1)
```

I find these to be equivalent; shall we close this?

**Comment by jasonLaster** [comment]
Copying reps values will be done in devtools core
