### ISSUE TITLE
[Scopes]  does not show function's return value

### ISSUE THREAD

**Issue by tromey** [devtools-html/debugger.html#3390]
The old debugger would show the function's return value on stepping out, like this:

![screenshot from 2017-07-20 10-21-00](https://user-images.githubusercontent.com/1557670/28428020-3e0579f8-6d35-11e7-9d46-ba84f7e969c1.png)

I don't see this in the new debugger.

I just made a simple function and then repeatedly clicked the step over button.  Eventually it stops at the end of the function and shows the return value.

**Comment by jasonLaster** [comment]
You can test it out w/ this test page locally: http://localhost:8000/integration/examples/doc-return-values.html

**Comment by tromey** [comment]
I can reproduce it with the booleans example without having to clone the repository: https://devtools-html.github.io/debugger-examples/examples/booleans/

**Comment by tromey** [comment]
To reproduce, open that page, put a breakpoint in the `makeBooleans` function, then click the button.  Then click "step over" repeatedly.  It will double stop at the "}" (which is what I was looking at when I found this); the second stop ought to show the return value.

**Comment by bomsy** [comment]
i tried to reproduce this,  i get this

![](http://g.recordit.co/o8UNOp6Mq5.gif)

Looks like it works now. Or am i misunderstanding something?

**Comment by tromey** [comment]
That looks correct to me.

**Comment by bomsy** [comment]
Cool thanks! this looks like its fixed, will do a bit more testing and close this

**Comment by codehag** [comment]
I think I found what is happening. the last bracket requires that you step over twice, it doesnt show the return value on the first step.

I think we don't want to have two steps at the end of the function. any ideas on how to avoid that?

**Comment by yurydelendik** [comment]
> I think we don't want to have two steps at the end of the function. any ideas on how to avoid that?

So Debugger API shows return value at [Debugger.Frame::onPop](https://developer.mozilla.org/en-US/docs/Tools/Debugger-API/Debugger.Frame) -- you cannot ignore this one. It comes after last step, which can be somehow ignored, but it is hard. A frame has location (offset) property, but it does not give you much.

**Comment by tromey** [comment]
> I think we don't want to have two steps at the end of the function. any ideas on how to avoid that?

This is what I was looking into when I found that I couldn't see the <return> at all.

I'm not sure whether I'll implement it or not, but the basic idea is to add a new debugger API so the server can tell whether it's stopped at a return opcode, and, if so, keep going until the frame pop.

**Comment by jasonLaster** [comment]
@tromey That would be nice.

**Comment by yurydelendik** [comment]
> to add a new debugger API 

@tromey I don't think you needs a new api -- all you need to disable breaking point in SpiderMonkey just before frame pops. (I know how to do it for wasm part -- I was modeling it after the JS behavior)

**Comment by jasonLaster** [comment]
@tromey @yurydelendik lets move this to a more specific bugzilla ticket.

**Comment by tromey** [comment]
> lets move this to a more specific bugzilla ticket

https://bugzilla.mozilla.org/show_bug.cgi?id=970469

**Comment by tromey** [comment]
FWIW I tried this with a new artifact build based on today's inbound tip, and I can still reproduce the problem.

**Comment by bomsy** [comment]
i tested it on the `next` branch seems to be fixed there

**Comment by jasonLaster** [comment]
#3813 has another example of this.

**Comment by jasonLaster** [comment]
@julienw talks about it here too #4064

--

When stepping in some code, the "step out" button allows to wait at the end of the current function, so that we can inspect the final state of the function's variables before actually stepping out. This is useful.

However we can't inspect the return value itself. This would be a very useful addition.

Note: this was possible in the old debugger so we should have the data already: 
![capture d ecran de 2017-09-18 15-50-59](https://user-images.githubusercontent.com/454175/30545261-652c1400-9c89-11e7-9172-161e49336b38.png)

**Comment by jasonLaster** [comment]
Here's a quick summary of how to pick up this work:

1. re-add the mochitest which exercised this behavior: #4188. You should be able to re-run the test [docs][d] and see the test fail

2. reproduce the bug locally by going to the test [example][e] and pausing in `returnSomething`. See the screenshots from the launchpad and nightly below

3. observe the pause data in the pause [reducer][p] and how it is used in the scopes [util][s]. 

#### Launchpad

<img src='https://shipusercontent.com/f3c5c9ac3a0c6b89b3a0c5de0e732e17/Screen%20Shot%202017-10-18%20at%202.38.15%20PM.png' title='Screen Shot 2017-10-18 at 2.38.15 PM.png' width=1548>

#### Nightly

<img src='https://shipusercontent.com/126b701f7b48ca096d7a9b55521f9f0e/Screen%20Shot%202017-10-18%20at%202.37.53%20PM.png' title='Screen Shot 2017-10-18 at 2.37.53 PM.png' width=1548>

#### Console 

`why.frameFinished.return` exists :smile: 

<img src='https://shipusercontent.com/215594cc2bb3b006c442736dbba028d2/Screen%20Shot%202017-10-18%20at%202.41.41%20PM.png' title='Screen Shot 2017-10-18 at 2.41.41 PM.png' width=1435>


[e]:http://localhost:8000/integration/examples/doc-return-values.html
[d]:https://github.com/devtools-html/debugger.html/blob/master/docs/mochitests.md
[s]: https://github.com/devtools-html/debugger.html/blob/master/src/utils/scopes.js#L73-L88
[p]:https://github.com/devtools-html/debugger.html/blob/master/src/reducers/pause.js#L44-L45

**Comment by jimblandy** [comment]
I've got the `browser_dbg-returnvalues.js` mochitest working again. Going to start looking at the failure.

**Comment by jimblandy** [comment]
This is kind of interesting.

- `getScopes` (utils/scopes.js) is trying to build the list of scopes to display in the panel. It would like to recognize the scope of the currently executing frame, to display it specially&mdash;in particular, to call `getSpecialVariables`, which shows the return value if present. Unfortunately, this call never happens: `pauseInfo.frame.scope` is `undefined`, so it has no idea which scope is the currently executing frame's. Intriguingly, `pauseInfo.frame.scope` *is* set; its value is just `undefined`.
- I looked at the pause packets we're getting from the server; one is shown below. Note that the `frame` property has type `"call"`, which [the protocol documentation][proto] says means it should have an `environment` property. It does not.
- As a sanity check, I made sure the client is indeed expecting an environment property there. Indeed:
  - [paused (client/firefox/events.js)][paused] receives each pause packet, and passes it to...
  - [createPause (client/firefox/create.js)][createPause], which passes the frame to...
  - [createFrame (client/firefox/create.js)][createFrame], which [checks `frame.environment`][check].
 
[proto]: http://searchfox.org/mozilla-central/source/devtools/docs/backend/protocol.md#function-call-frames
[paused]: https://github.com/devtools-html/debugger.html/blob/master/src/client/firefox/events.js#L38-L54
[createPause]: https://github.com/devtools-html/debugger.html/blob/master/src/client/firefox/create.js#L51-L62
[check]: https://github.com/devtools-html/debugger.html/blob/master/src/client/firefox/create.js#L32

## The pause packet

Here's the pause packet we got:

    {
      "from": "server1.conn47.child1/context27",
      "type": "paused",
      "actor": "server1.conn47.child1/pause5655",
      "frame": {
        "actor": "server1.conn47.child1/frame5656",
        "type": "call",
        "callee": {
          "type": "object",
          "actor": "server1.conn47.child1/pausedobj5657",
          "class": "Function",
          "extensible": true,
          "frozen": false,
          "sealed": false,
          "name": "return_something",
          "displayName": "return_something",
          "parameterNames": [
            "x"
          ],
          "location": {
            "url": "http://localhost:8000/integration/examples/doc-return-values.html",
            "line": 8
          }
        },
        "this": {
          "type": "object",
          "actor": "server1.conn47.child1/pausedobj5658",
          "class": "Window",
          "extensible": true,
          "frozen": false,
          "sealed": false,
          "ownPropertyLength": 767,
          "preview": {
            "kind": "ObjectWithURL",
            "url": "http://localhost:8000/integration/examples/doc-return-values.html"
          }
        },
        "arguments": [
          2
        ],
        "where": {
          "source": {
            "actor": "server1.conn47.child1/source29",
            "generatedUrl": null,
            "url": "http://localhost:8000/integration/examples/doc-return-values.html",
            "isBlackBoxed": false,
            "isPrettyPrinted": false,
            "isSourceMapped": false,
            "sourceMapURL": null,
            "introductionUrl": null,
            "introductionType": null
          },
          "line": 9,
          "column": 6
        }
      },
      "poppedFrames": [
        "server1.conn47.child1/frame34"
      ],
      "why": {
        "type": "debuggerStatement"
      }
    }
