### ISSUE TITLE
[Editor] improve perf with startOperation/endOperation

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3400]
We could improve our editor performance by minimizing the number of operations that codeMirror does.

The best way to do this is with a new API we added to CM, which will be released in the next version. We can call `startOperation` in will receive props, and `endOperation` in did update.

https://github.com/devtools-html/debugger.html/pull/3367

**Comment by jasonLaster** [comment]
@codehag this might be easier now that the refactor is done

**Comment by wldcordeiro** [comment]
This is still open and we use `operation` already in some locations. Reading the docs we should be able to do most things with it and avoid `startOperation`/`endOperation`.

https://codemirror.net/doc/manual.html#api_misc

Should we revisit this? @jasonLaster I'm down to investigate and implement if it stands to help. 😄

**Comment by jasonLaster** [comment]
i think we can close this for now as we got the operations down quite a bit. Also not sure if this would work :)

**Comment by jasonLaster** [comment]
I'm closing this as I no longer think this will help us. w/ the codemirror editor updates
