### ISSUE TITLE
[Symbols] The function start line number is wrong

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3402]
The symbol modal is getting the wrong line number from `getSymbol`. You can see this by looking at the results list and comparing the values in `Editor/index.js`

<img src='https://shipusercontent.com/11845a6dd3ecdcc9fb36cbda285da821/Screen%20Shot%202017-07-21%20at%2010.31.50%20AM.png' title='Screen Shot 2017-07-21 at 10.31.50 AM.png' width=736>

**Comment by jasonLaster** [comment]
@ryanjduffy is working on it

**Comment by ryanjduffy** [comment]
Just pulled down the latest and I'm not seeing this behavior. Here's a screencap of the same search:

![image](https://user-images.githubusercontent.com/788456/28594577-1485f60a-7156-11e7-8401-174878ea47cd.png)

**Comment by jasonLaster** [comment]
closing this as we can't reproduce it. We can re-open if it *comes* back
