### ISSUE TITLE
[SymbolModal] should clear the query after a selection

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3404]
I often find myself using the function search to find a function, re-opening it and being surprised there is still a query:

![](http://g.recordit.co/hAI9eLzovd.gif)

```diff

diff --git a/src/components/SymbolModal.js b/src/components/SymbolModal.js
index 4b68c9d..8fb8f0a 100644
--- a/src/components/SymbolModal.js
+++ b/src/components/SymbolModal.js
@@ -156,6 +156,7 @@ class SymbolModal extends Component {
       line: item.location.start.line
     });

+    // clear the query...
     this.closeModal();
   }
```

**Comment by pgadige** [comment]
I'd like to work on this issue. Could you please assign it to me? As I understand, when the search function/box is reopened it should be cleared off the previous query, or in other words, it should be empty. Am I on the right track?
