### ISSUE TITLE
[pause] [watchexpressions] stepping gets confused

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3406]
filing from bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1331263

OK, that doesn't seem to be enough to reliably reproduce this. Better steps:

0. nightly Jan. 15, clean profile, enable browser toolbox, open add-on manager, switch to 'appearance', enable dark compact theme
1. restart with the same profile, dismiss default browser prompt if it shows up.
2. open addons manager again (I used restore prev. session, probably doesn't matter)
3. open browser toolbox via cmd-opt-shift-i (or Windows/Linux equiv.). accept connection prompt.
4. switch to debugger, set breakpoint in AddonManager.jsm on the first line of getPrefferedIconURL (2360).
5. in the browser, switch away and back to the appearance tab
6. the breakpoint will hit. Add these 3 watches:

aAddon.id
aAddon.icons
aAddon.iconURL

7. hit continue a few times

ER:
don't get stuck

AR:
at some point the debugger believes it's paused (continue button highlights, OS X icon overlay shows pause status, if you switch to another devtools tab the debugger tab highlights) but also that it's not (no current line highlight, continue/step buttons all do nothing when clicked, locals are not displayed and watches view displays nothing for any of the watches). The main browser does not respond to input. The only way to restore normalcy is quitting the browser devtools process.

Full console output in the browser toolbox:

DebuggeeWouldRun: debuggee `resource://gre/modules/commonjs/toolkit/loader.js:748' would run  builtin-modules.js:152:11
DebuggeeWouldRun: debuggee `resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:736' would run  script.js:350:5
DebuggeeWouldRun: debuggee `resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:736' would run script.js:350:5
DebuggeeWouldRun: debuggee `self-hosted:3162' would run  object.js:1031:20

**Comment by clarkbw** [comment]
I just ran through this and I couldn't create the same issue.  Here are my steps.

1. nightly, clean profile
```bash
export TMP_PROFILE=`mktemp -d`
/Applications/FirefoxNightly.app/Contents/MacOS/firefox --profile $TMP_PROFILE
```
1.  open devtools / settings turn on browser chrome / remote debugging in bottom right
1.  go to `about:addons` / appearance and enable dark compact theme
1. restart browser
```bash
/Applications/FirefoxNightly.app/Contents/MacOS/firefox --profile $TMP_PROFILE --jsdebugger
```
1.  open `about:addons` again (I used restore prev. session, probably doesn't matter)
1.  switch to debugger
1. open `AddonManager.jsm` via cmd+P 
1. set breakpoint on the first line of `getPrefferedIconURL` (2335) 
  1. Note that function search for `getPrefferedIconURL` didn't work
1. switch extensions tab (within about:addons) and back to the appearance tab
1.     the breakpoint will hit. Add these 3 watches:

aAddon.id
aAddon.icons
aAddon.iconURL

1.  hit continue a few times

AR: Seems to work as expected for me.

UER: Watch expression values remain after continue.

<img width="1134" alt="screen shot 2017-07-21 at 2 28 23 pm" src="https://user-images.githubusercontent.com/2134/28483196-de69f914-6e20-11e7-93e3-540dc50059e2.png">

**Comment by jasonLaster** [comment]
@clarkbw can we close this?

**Comment by clarkbw** [comment]
Yes, this issue is fixed.  Is there an issue on file for watch expression values remaining after no longer being paused?
