### ISSUE TITLE
When inspector is zoomed in the "Dropdown" for options is misplaced

### ISSUE THREAD

**Issue by vladikoff** [devtools-html/debugger.html#3423]
![](https://user-images.githubusercontent.com/128755/28526086-6ede6cca-7054-11e7-91c3-a00527814608.png)

See screenshot above ^
The additional menus show up in strange locations

**Comment by jasonLaster** [comment]
@vladikoff can you refile this in bugzilla under the inspector component?

**Comment by vladikoff** [comment]
@jasonLaster ooo thanks!!
