### ISSUE TITLE
[WatchExpressions] the remove button is often hidden by the scroll bar

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#3428]
I scrolled up the side bar to see my watch expressions and realized I needed to remove some of the old ones.  However when I tried to do that the scroll bar hangs around for a bit and makes it nearly impossible to catch the remove button.  Eventually the scroll bar fades away and you're able to remove click the button.  Just wondering if there is a solution to this or perhaps an alternate layout that could prevent it.

Is it possible to move the buttons while the scroll bar is visible?  Do we know when that has happened? Like onAfterScroll() -> bump buttons over for scroll bar timeout...

![watch-expressions-hidden-remove](https://user-images.githubusercontent.com/2134/28530778-b7a1c296-7049-11e7-9c27-1a443e9504ba.png)

**Comment by jasonLaster** [comment]
Looks like we should apply the same margins to the watch expression close button and reload button as we do for breakpoints.

<img width="298" alt="screen shot 2017-07-24 at 11 43 45 am" src="https://user-images.githubusercontent.com/254562/28531653-78bbc89e-7065-11e7-8cae-8bec174778b7.png">

**Comment by codehag** [comment]
Im taking this one on because i want to think a bit about our css system and this might be a good spot to try something

**Comment by jasonLaster** [comment]
:thumbsup:

**Comment by clarkbw** [comment]
Also just realized the other step to reproduce this is to try deleting a number of watch expressions at once.  

1. Create several watch expressions for anything
1. Pause on a breakpoint where the sidebar overflows
2. Click the remove button on the first watch expression
3. The other watch expressions should slide up and the next remove button should be under your mouse however the scroll bar often interferes with the button
