### ISSUE TITLE
[Workers] [Breakpoints]  in service workers don't work reliably

### ISSUE THREAD

**Issue by bzbarsky** [devtools-html/debugger.html#3432]
STEPS TO REPRODUCE:

1)  Start current nightly with clean profile.
2)  Load about:debugging.
3)  Click the "Workers" text in the sidebar on the left.
4)  Click the "Opt out of multiple content processes" button in the yellow warning about service worker debugging not being e10s-multi compatible.
5)  Click "OK" in the resulting confirmation prompt.  This will restart your browser.
6)  After restart, open a new tab in addition to about:debugging.
7)  Load https://gauntface.github.io/simple-push-demo/ in that new tab.
8)  Go back to the about:debugging tab.
9)  Click the "Debug" button for the running "https://gauntface.github.io/simple-push-demo/service-worker.js" service worker.
10) Add a breakpoint in the "push" event listener.
11) Go to the https://gauntface.github.io/simple-push-demo/ page, click the "Enable Push Notifications" thing, grant permission, send a push.

This sometimes stops at the breakpoint and sometimes doesn't, according to @wanderview

**Comment by wanderview** [comment]
I guess I should clarify I was returning to an existing profile so I wasn't constantly restarting with the opt-out pref flip.

In the past this sort of thing has happened when we run the SW in one process, but the debugger in a different process.

**Comment by wanderview** [comment]
Sure enough, I have multiple web content processes.  Looking at about memory:

```
Web Content (pid 3644)
Explicit Allocations

60.16 MB (100.0%) -- explicit
├──16.07 MB (26.71%) ++ js-non-window
├──12.74 MB (21.18%) ── heap-unclassified
├──10.84 MB (18.02%) -- heap-overhead
│  ├───9.24 MB (15.35%) ── bin-unused
│  ├───0.92 MB (01.53%) ── bookkeeping
│  └───0.68 MB (01.14%) ── page-cache
├───7.76 MB (12.90%) -- window-objects
│   ├──5.29 MB (08.79%) ++ top(about:newtab, id=6442450968)
│   └──2.47 MB (04.11%) ++ top(https://gauntface.github.io/simple-push-demo/, id=6442450965)
├───4.40 MB (07.32%) ++ workers/workers(gauntface.github.io)/worker(https://gauntface.github.io/simple-push-demo/service-worker.js, 0x17a2eb45800)
├───2.40 MB (03.98%) ++ (14 tiny)
├───2.03 MB (03.38%) -- script-preloader
│   ├──2.01 MB (03.35%) ── non-heap/memmapped-cache
│   └──0.02 MB (00.03%) ++ heap
├───1.20 MB (01.99%) ── telemetry
├───1.12 MB (01.86%) ── profiler/profiler-state
├───0.85 MB (01.42%) ── xpti-working-set
└───0.74 MB (01.24%) -- images
    ├──0.71 MB (01.17%) ++ content
    └──0.04 MB (00.07%) ++ chrome
```

And:

```
Web Content (pid 11792)
Explicit Allocations

37.63 MB (100.0%) -- explicit
├──15.35 MB (40.79%) ++ js-non-window
├───6.08 MB (16.16%) -- workers/workers(gauntface.github.io)
│   ├──4.42 MB (11.75%) ++ worker(https://gauntface.github.io/simple-push-demo/service-worker.js, 0x19f92273800)
│   └──1.66 MB (04.41%) ++ worker(https://gauntface.github.io/simple-push-demo/service-worker.js, 0x19f8d468000)
├───4.00 MB (10.62%) ++ heap-overhead
├───3.76 MB (010.00%) ── heap-unclassified
├───2.02 MB (05.38%) ++ script-preloader
├───1.22 MB (03.24%) ++ (13 tiny)
├───1.20 MB (03.18%) ── telemetry
├───1.16 MB (03.07%) ── profiler/profiler-state
├───1.00 MB (02.66%) -- window-objects
│   ├──0.55 MB (01.46%) ++ top(moz-extension://194f521a-5d1a-4740-8f32-2a0a0128ba45/_generated_background_page.html, id=4294967297)
│   └──0.45 MB (01.20%) ++ top(moz-extension://2b28a3b6-1011-4eb9-b60d-4a5df80f0ec5/_generated_background_page.html, id=4294967300)
├───0.85 MB (02.26%) ── xpti-working-set
├───0.52 MB (01.38%) ── preferences
└───0.47 MB (01.25%) ++ layout
```

It appears to be getting confused by the webextension process.

**Comment by clarkbw** [comment]
I think @wanderview filed [bug 1280737](https://bugzilla.mozilla.org/show_bug.cgi?id=1280737) a while back, is this the same issue as that?

**Comment by wanderview** [comment]
We shouldn't be running service workers in the extension process.  I filed this to try to look at it from the service worker side:

https://bugzilla.mozilla.org/show_bug.cgi?id=1383905

Is devtools running in the extension process now or something?

**Comment by wanderview** [comment]
> I think @wanderview filed bug 1280737 a while back, is this the same issue as that?

I don't know.  I think its probably different since the extension process didn't exist back then.

**Comment by clarkbw** [comment]
> Is devtools running in the extension process now or something?

I feel like I'm grasping at straws but it reminded me of this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1373219) @rpl was working on (for extension debugging) and sounds similar.

**Comment by jasonLaster** [comment]
hmm, there is probably something racey, but I was not able to reproduce it when i tried
http://g.recordit.co/jjsQ2Cpr9e.gif

**Comment by wanderview** [comment]
I believe we had a situation previously where you could end up running the service worker in multiple processes at once, even though we had tried to disable that without our "multi-e10s opt out".  That particular problem has been fixed.  My guess is that this issue was a manifestation of that bug.

**Comment by jasonLaster** [comment]
Got it. I'll tentatively close the bug. Lets re-open it if something comes up.
