### ISSUE TITLE
[SourceSearch] Searching for long not-found text has really bizarre behavior

### ISSUE THREAD

**Issue by bzbarsky** [devtools-html/debugger.html#3450]
STEPS TO REPRODUCE:

1) Load https://bugzilla.mozilla.org/show_bug.cgi?id=1382311#c4 and select all the text in that comment.
2) Load https://en.wikipedia.org/wiki/Barack_Obama in Firefox
3) Open devtools, select debugger tab.
4) Start a search (Cmd+P on Mac).
5) Paste (Cmd+V).

EXPECTED RESULTS: text not found, communicated in some sane way.

ACTUAL RESULTS: text not found and suddenly there is huge red text everywhere.  I can't even cancel the search, because all that UI is covered by red text.

**Comment by jasonLaster** [comment]
<img src='https://shipusercontent.com/970db37c50f3154965c7f10532e55b53/Screen%20Shot%202017-07-25%20at%208.09.46%20PM.png' title='Screen Shot 2017-07-25 at 8.09.46 PM.png' width=571>

**Comment by bzbarsky** [comment]
What I see is this:
![image](https://user-images.githubusercontent.com/1457979/28601492-866bfa14-7186-11e7-850d-11309d8bff1a.png)

**Comment by codehag** [comment]
closing in favor of #3469
