### ISSUE TITLE
[PrettyPrint] Unable to prettify (prettyprint, pretty-print) source of some scripts

### ISSUE THREAD

**Issue by bzbarsky** [devtools-html/debugger.html#3451]
STEPS TO REPRODUCE:

1) Load https://en.wikipedia.org/wiki/Barack_Obama in Firefox
2) Open debugger.
3) Search for "addEmbeddedCss"
4) Click on one of the hits (in load.php)
5) Attempt to pretty-print the script.

EXPECTED RESULTS: Can do it.

ACTUAL RESULTS: The "prettyprint this" UI is absent.

ADDITIONAL INFORMATION: The old debugger UI lets me prettyprint this script.

**Comment by codehag** [comment]
In this case we have a file that has an extention `.php`, but the underlying script is javascript. We are doing a check for `Content-Type` in the pretty print worker, but it seems to not be working as expected. A good place to look is in `src/utils/source.js` in the `isJavascript` function to see what is going on.

**Comment by bzbarsky** [comment]
In general, browsers will run scripts even if they're served with random MIME types.  So checking Content-Type is not the right way to go about detecting whether something is a script from the browser's point of view...

**Comment by jasonLaster** [comment]
hmm, i wonder if we want to have a blacklist then... like HTML?

**Comment by digitarald** [comment]
For reference, the file type is `text/javascript; charset=utf-8`. Would that be not whitelisted? #2782 has a similar symptom but the content-type is `application/javascript`.
