### ISSUE TITLE
[Breakpoints] [SourceMap] Two identical breakpoints shown when the same source is used in two bundles

### ISSUE THREAD

**Issue by yurydelendik** [devtools-html/debugger.html#3459]
STR:

1. Open and start debugging https://devtools-html.github.io/debugger-examples/examples/dualuse/dualuse.html
2. In the debugger, at webpack://log.js set breakpoint at `console.log` expression
3. Reload the dualuse.html to break on the breakpoint

Actual result:

Notice two breakpoints appeared at the sidebar list:
<img width="976" alt="screen shot 2017-07-26 at 9 43 24 am" src="https://user-images.githubusercontent.com/1523410/28627293-f611ffac-71e6-11e7-9a5e-12104987dff8.png">

(as workaround one of them can be removed)

Expected result:
Only one breakpoint shown

P.S. This also makes "Jump to generated source" function somewhat unpredictable, especially during debugging

**Comment by yurydelendik** [comment]
After playing with different tabs states before step 3 (reload dualuse.html), it shows different UI issues (log.js tab is closed, or active/not active): debugger line is not seleceted but maybe flashes, or tab is not selected.

**Comment by jasonLaster** [comment]
This is very similar to two different cases:

1. pretty printing a generated source
2. pretty printing an original source

**Comment by jasonLaster** [comment]
This is kinda how I see it

<img src='https://shipusercontent.com/fe51b57fb6c4c07c76125a42ff3a4227/Screen%20Shot%202017-07-26%20at%2012.28.53%20PM.png' title='Screen Shot 2017-07-26 at 12.28.53 PM.png' width=374>

**Comment by jasonLaster** [comment]
I'm moving the issue to the icebox. We will re-prioritize the issues in the icebox at the beginning of the next release in 6 weeks.
