### ISSUE TITLE
[SourceSearch] Improve not-found UI

### ISSUE THREAD

**Issue by violasong** [devtools-html/debugger.html#3469]
Fixes #3450

Currently, no results looks like this:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/55994/28643402-949cb45a-720a-11e7-9afd-11e838e796ed.png">

I'm proposing we:

- [x] remove the error-red color since there's not necessarily anything wrong here
- [x] remove the sad smileys because the mood should be neutral
- [x] change message to the less redundant "No results found"
- [x] Vertically-center "No results found" text a little better

Mockup:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/55994/28643444-bad764bc-720a-11e7-8ac3-a7138f58b38b.png">

**Comment by codehag** [comment]
:+1: great suggestions

**Comment by bzbarsky** [comment]
Please make sure the new setup handles the issue raised in https://github.com/devtools-html/debugger.html/issues/3450 (the error text bleeding all over the UI) sanely.

**Comment by codehag** [comment]
Yes, of course :) we have decided that it doesn't make sense to give so much information, and we are opting for a simplified text which is "no results found" rather than including the attempted search query.

**Comment by wldcordeiro** [comment]
@bzbarsky that issue will be closed because this change will invalidate the issue.
