### ISSUE TITLE
[SourceMap] Breakpoint is not hit

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3479]
[STR]
1. yarn storybook in debugger.html
2. add a breakpoint in [SearchInput.js#44](https://github.com/devtools-html/debugger.html/blob/master/src/components/stories/SearchInput.js)
3. click on a search input story

#### New Debugger
![](http://g.recordit.co/MPLXBMS96c.gif)

#### Old Debugger
![](http://g.recordit.co/481wEU2pBC.gif)

**Comment by TitanNano** [comment]
I believe this issue only appears for me when
```TypeScript
this.something()
    .then(() => {});
```
is generated to 
```JavaScript
this.something().then(() => {});
```

**Comment by jasonLaster** [comment]
Thanks - i would like to figure out why the original -> generated mapping is one line off

that's a great find!
