### ISSUE TITLE
[Editor] Highlight executable lines

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3482]
Firebug and Chrome fade lines that are not executable. There are some advantages of this UI:

* it differentiates between code and comments or whitespace
* it makes it clear which lines you can add breakpoints on

parity: https://bugzilla.mozilla.org/show_bug.cgi?id=1138243

<img src='https://shipusercontent.com/14eb9789858be39edcc831aa8dc3b5c5/Screen%20Shot%202017-07-27%20at%204.58.31%20PM.png' title='Screen Shot 2017-07-27 at 4.58.31 PM.png' width=515>

**Comment by darkwing** [comment]
I'm noticing that if there's an empty line (last line in my test doc), if I click the line number to create a breakpoint, the new breakpoint shows up in the Breakpoints list *very briefly*, then goes away.

**Comment by jasonLaster** [comment]
Here's a quick sketch of what the implementation could look like. 

We basically walk through the tokens and peek at them :)

```diff
diff --git a/src/utils/parser/getEmptyLines.js b/src/utils/parser/getEmptyLines.js
new file mode 100644
index 0000000..412f60f
--- /dev/null
+++ b/src/utils/parser/getEmptyLines.js
@@ -0,0 +1,16 @@
+import uniq from "lodash/uniq";
+import { getAst } from "./utils/ast";
+const whiteList = ["CommentLine"];
+
+export default function getEmptyLines(source: Source) {
+  const ast = getAst(source);
+  if (!ast || !ast.comments) {
+    return [];
+  }
+
+  const lines = ast.tokens
+    .filter(token => whiteList.includes(token.type))
+    .map(token => token.loc.start.line);
+
+  return uniq(lines);
+}
diff --git a/src/utils/parser/tests/getEmptyLines.js b/src/utils/parser/tests/getEmptyLines.js
new file mode 100644
index 0000000..0dee09a
--- /dev/null
+++ b/src/utils/parser/tests/getEmptyLines.js
@@ -0,0 +1,7 @@
+import { getSource } from "./helpers";
+
+describe("getEmptyLines", () => {
+  it("allSymbols", () => {
+    expect(getEmptyLines(getSource("allSymbols"))).toMatchSnapshot();
+  });
+});
```

**Comment by bomsy** [comment]
@jasonLaster this is completely done?
