### ISSUE TITLE
[Storybook] Preview has location error

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3487]
We are having a bit of trouble with our storybook code. When trying to work with preview we get this rather intense error:

<img width="1282" alt="screen shot 2017-07-28 at 11 53 43 am" src="https://user-images.githubusercontent.com/26968615/28712468-8dd5ef10-738b-11e7-8f0a-217de4ea65b4.png">

It looks like we have an issue with `markText` on line 52 in `Preview.js`.

To run story book, type `yarn storybook` in your console
then you can point your browser to `localhost:9001`

This is a good first bug
Let me know if you need help on this!

**Comment by darkwing** [comment]
I can't seem to reproduce this; working well for me.

**Comment by Anzumana** [comment]
will take this one. maybe i can reproduce it.
what operating system and commit / branch did you use @darkwing

**Comment by jasonLaster** [comment]
It shouldn't matter. Happy to close if you couldn't reproduce:

1. `yarn storybook`
2. go to *simple object*

**Comment by Anzumana** [comment]
also works for me.  @codehag can you reproduce the issue consistently?

**Comment by codehag** [comment]
hm. yes. i wonder what is going on...
yarn version is 0.24.5, just tried the most recent master :/

**Comment by Anzumana** [comment]
not exactly sure how get a different yarn version i installed mine with brew.
@jasonLaster used npm i think to install yarn so should be easier for him to switch versions.
Or is there an easy way for me to do so in order to replicate ?

**Comment by codehag** [comment]
npm is also what i use. when you install it via npm it is tied to your node version so keep that in mind as well. So to get the yarn version -- `npm install yarn@0.24.5` -- you might also want to uninstall yarn from brew. 

Though if I am the only one with this issue maybe it isn't a problem. ..

**Comment by Anzumana** [comment]
not sure what version of yarn @darkwing  is on. i was on 0.27.5 and wasn't able to reproduce.

**Comment by Anzumana** [comment]
would be good to figure out why this could be the case as things like that should be avoided if at all possible. just in case people clone the repo and test things like the story book and then leave it without saying hello or opening an issue

**Comment by nyrosmith** [comment]
I also have this issue but I have no idea what could cause this behavior & why not everyone runs into this.
Trying to investigate further...

**Comment by wldcordeiro** [comment]
I figured out the fix while doing the JSX transform on Preview and its story. Will open PR shortly sorry @Anzumana for grabbing it out from under you.

**Comment by jasonLaster** [comment]
@wldcordeiro what was the issue?

**Comment by Anzumana** [comment]
@codehag does this fix the issue for you ?

**Comment by wldcordeiro** [comment]
@jasonLaster The `Preview` used to have a prop called `location` that changed to `range`.

**Comment by codehag** [comment]
this is fixed

**Comment by Anzumana** [comment]
sweet
