### ISSUE TITLE
Improve project for contributors

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#349]
This is my tracking issue related to a number of changes I believe we need to make to improve the project for new contributors.  Many thanks to @kentcdodds for his [first timers only](https://medium.com/@kentcdodds/first-timers-only-78281ea47455#.mdhjl55ik) post which heavily inspired a lot of this.

## README

We need to cleanup the readme doc so that its a high level overview of the project and move many of the details into other more complete documentation areas.  The readme is the first thing people see when they find this project, it should give people a good sense of the project overall, where as the details of specific things like starting Chrome can be in other docs.

- [x] explain what the project is and who it is intended for
- [x] quick start instructions like `npm install, npm start`
- [x] document who is working on the project and how you can get involved
- [x] improve the screenshots and details describing the debugger
- [x] link to contributing doc and describe how to get started
- [x] remove the Travis CI badge
- [x] Create a section for "contacting us" that better describes where to find us (IRC devtools-html)
* might be nice to have another channel as well like gitter 

## CONTRIBUTING

Use the [docs/](https://github.com/jlongster/debugger.html/tree/master/docs) directory for detailed descriptions of each section.  Keep the overall document about getting people quickly started on the various areas of the project (storybook, karma, cypress) and pointing them to further docs for each section.

- [x] Possibly add a [Make a Pull Request](http://makeapullrequest.com/) badge to help first time contributors get going
- [x] Link to other "Getting Started" docs like the github doc:  https://guides.github.com/activities/contributing-to-open-source/ 
- [x] create and / or improve the high level sections for each key area of development

## Improve Issue Organization

To help people who are getting started with the project for the first time or open source in general for the first time I'd like to change up the issue organization.

- [x] move from "Beginner Bug" to the "up-for-grabs" tag
- [x] along with above register our project with the [up for grabs](http://up-for-grabs.net/) site
- [x] document in the contributing doc what "up-for-grabs" means
- [ ] document how anything assigned indicates an intent to implement
- [ ] Possibly request adding our project to the [awesome for beginners](https://github.com/MunGell/awesome-for-beginners#javascript) list
- [x] create and use a difficulty rating system with tags: difficulty:(insane|hard|medium|easy)
    * insane: refactor of a large part of the project, requires new tests, new frameworks
    * hard: requires new tests, new code, good understanding of project; expect lots of review
    * medium: adapting existing code, adapting existing tests, expect quick review
    * easy: small changes, update tests, update docs, expect very little review
- [ ] document in contributing how anything "up for grabs" should have a difficulty rating

## Encourage first time contributors

We have a number of issues that could be great for first time contributors to work on; not every issue needs to be tagged this way but I think it would be good to have a system for setting aside some work that could be the very first contribution for someone out there.

- [x] create a "first-timers-only" tag which indicates we're looking for someone who has never contributed to open source before
- [x] document the "first-timers-only" tag in the docs and contributors doc, describe how a mentor should be assigned to the issue 

## Ensure a comfortable and friendly environment

Everyone working on this project is amazing and we want to protect and declare that for others who are new to the project.

- [ ] join the [Contribution Covenant](http://contributor-covenant.org/), a couple mozilla projects are already on there
- [x] add the CC code of conduct document to our repository
- [x] document where the CC lives in our contributing doc
- [x] Include a link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) which, in addition to the CC, provides another layer specifically for Mozilla employees and contributors

## update the [docs/](https://github.com/jlongster/debugger.html/tree/master/docs) directory

- [ ] Review current documentation, file issues for updating docs out of date
- [ ] File issues for any missing documentation
- [ ] Create screencasts for each of the docs

**Comment by kentcdodds** [comment]
I can't begin to state how awesome this is. Thanks for doing this! ❤️

**Comment by jlongster** [comment]
This is awesome! A lot of good stuff that we can do. To bring another viewpoint though, I have two things:

It sounds like you want the readme to be a contributor's doc basically. I'm not sure I agree with that. A readme should be a succinct description about how to get the project running for a variety of people, including advanced people. It is a very basic part of the workflow to start Chrome on a debugging port, and dedicating 1 paragraph's worth of space for these commands is extremely useful IMHO. I don't want to turn away advanced people either. There are projects where I look around and constantly think "just freaking tell me how to run stuff!". I love readme's that are more of a cheat sheet to get thinks working quickly.

We should make another doc which is the "getting started" or "contributing" doc (you already started one), and the first section of the readme should explain that and link to it.

The other point is that we should balance our investment in docs. There are still things that are changing drastically, and it's too early to have things like screencasts for some things (like testing, lots of things are changing). We have a **really** tight deadline. Let's not get too distracted with documenting things that will be out-of-date by the time we finish documenting them.

Eventually we will want to move any documention to https://github.com/mozilla/devtools-docs, because we will be sharing the same things across multiple tools.

Generally I love these ideas though, especially managing issues better.

**Comment by clarkbw** [comment]
> It sounds like you want the readme to be a contributor's doc basically. I'm not sure I agree with that.

No, that's not the intent for the readme; I agree with what you're saying.  And we already have a contributing doc to use for getting people started with longer docs.  I want the readme to have the get up and running docs and actually the Chrome section was a bad example to use because that probably does belong in the readme.  

I'll file a separate PR for the readme so we can work through this but the goal here most certainly isn't to hide things from advanced users, we are building a debugger so many of our contributors will be those types.  Its mostly trying to look at the readme from an information hierarchy POV.  The greatest number of people will just look at the readme to understand the project, that area is poorly undeserved right now.  Next is people who just want to run the project to play with it against Chrome, Firefox, and Node; we need quick run docs for that and links to further docs in other places.  Next is the much smaller set of people who are looking to contribute and I think its actually pretty hard to get "quick run" docs for these people; maybe I'm wrong there.  But there are a lot of instructions involved no matter what you're trying to do to help.

I hear what you're saying about docs and I agree that our priority focus needs to be on shipping.  Certainly much of the docs we write now will be outdated soon enough but we're never finished so waiting until that moment to write docs usually ends up with no docs.  It is a balance.  Docs for things like flow would be premature right now, however I need the cypress docs just because I'm always forgetting how to get it all up and running and cypress is still up in the air.

**Comment by jlongster** [comment]
Yes, definitely agree that it's a balance :) I think I was mainly thinking about things like screencasts, which are time-consuming to create and very hard to update (you basically need to make a new one each time). But having docs is definitely good, even for things that might change next week.

The readme could be a ton better about explaining what this is, yeah. As long as it's super clear how to do the most basic things (open chrome, debug current firefox, turn on hot reloading, etc) that many people getting started will run into, I'm ok with that. That may even be a separate document, but if it's clearly linked to and explained at the top of the readme that's probably fine.

**Comment by jasonLaster** [comment]
Thanks @clarkbw for bringing this up

I'm in favor of keeping the readme a "high level overview of the project". 

Information like running the debugger, debugging a target (firefox, node, chrome), ... testing is best described in specific documents. I started this with integration tests and I'd like to add unit testing as well. IMO, the readme should be a cheat-code on the most needed information for getting started and link to topical docs. 

> advanced / beginner contributors 

I think it's also important to think about internal and external contributors. The internal contributors might have the project context and quickly jump to the topical document they need. The external contributors will benefit first by learning about the product and team, and then other information.

**Comment by jasonLaster** [comment]
> another channel like gitter

I think that could be a great idea. gitter does a good job of notifying you when somebody pings in channel. With something like that, it could help first comers / lurkers stay involved. Gitter was instrumental for Backbone Marionette, we were the first org to adopt gitter (gitter is built on Marionette so we had an in) and our community grew to 3k+ quickly and has been a huge win for the community.

**Comment by clarkbw** [comment]
README and CONTRIBUTING update coming in #352

**Comment by amitzur** [comment]
> I need the cypress docs just because I'm always forgetting how to get it all up and running and cypress is still up in the air.

I agree, and what was a major hurdle for me to get into this project is cypress installation.

**Comment by jasonLaster** [comment]
Thanks @amitzur we have these docs, but they're new and probably hard to find
https://github.com/jlongster/debugger.html/blob/master/docs/integration-tests.md

not sure if the install steps are clear enough either

**Comment by jasonLaster** [comment]
@clarkbw this issue has been open for some time, 
+ do you have time to complete some of the low hanging fruit? 
+ discuss any of the open questions
+ file some smaller more actionable issues

I personally like the idea of 
* linking to the *make a pull request* egghead series
* agreeing to the Contribution Covenant and including it in the project
* reviewing the docs for key concepts, testing, getting started...
* documenting people in the project and adding screenshots

Personally, i'm not sure if we're ready to be added to the list of good projects for beginners yet. Hopefully we will by october when flow, our testing strategy, and docs are improved.

**Comment by clarkbw** [comment]
> and adding screenshots

added this in #538

**Comment by clarkbw** [comment]
Contributor Covenant is handled in #565

**Comment by clarkbw** [comment]
Make a Pull Request in #564

**Comment by clarkbw** [comment]
Here's what I have left to do:

- [ ] document in contributing how anything "up for grabs" should have a difficulty rating
- [ ] document how anything assigned indicates an intent to implement

As far as the other items I think we're going to wait.

I'm not yet comfortable joining the contributor convent, we're too young.  If there was a wait to snooze a github issue for 6 months from now that is what I would do for this.

Related [docs](./docs/) directory changes can wait still.  DevRel will be helping us with some of that so it's probably too soon to start on our own.

**Comment by jbhoosreddy** [comment]
This is the first time I learned about the contributor covenant. It was an
insightful read. Definitely something to watch out for!

**Comment by jasonLaster** [comment]
@clarkbw you're making great progress here!

One thing I thought of while reading the PR PR was how a lot of new contributors would be anxious about getting started. Even though our doc explains the steps, it might still *seem* like a lot. One fix would be a quick five minute video that goes through all of the steps of clone, install, start a browser, start the server. I know making videos can be a lot of work, but i think this one would be especially useful.

**Comment by clarkbw** [comment]
Great idea! I'll give it a try this week.
