### ISSUE TITLE
[DebugLine] expressions are not marked when selecting sources

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3500]
STR:
1. pause
2. select a source where there's another frame

ER: see the debug expression
AR: you see the debug line, but not expression

NOTE: selecting frames in the call stack properly show expressions.

![](http://g.recordit.co/ZmvPyJc1k7.gif)

**Comment by jasonLaster** [comment]
There's a similar issue with breakpoints:

![](http://g.recordit.co/WtAiNEpRhC.gif)

**Comment by codehag** [comment]
I took a look, and here is what is happening:

debug expressions is a single instance, each time we switch files the debug expression is pointing to a line on a single source. however when you select it via the callstack, it sets a new line.

I think we might want to rethink using the debug line to show where in the callstack a given call was made. If we use it, then it would be confusing -- as we are not currently paused at that location. Maybe we need a different visual cue for this?

**Comment by jasonLaster** [comment]
Just spoke offline, and we only want to show one frame's debug line.
