### ISSUE TITLE
Convert Components to JSX

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#3506]
We've been looking into converting our components to JSX for a while this is a tracking issue.

#### Automation

This [jscodeshift][jsc] could help out :)
[jsc]:https://github.com/HipsterBrown/espresso/blob/master/src/transforms/jsx.js

# Components

- [x] App
- [x] SymbolModal
- [x] WelcomeBox
- [x] Breakpoints
- [x] CallSites
- [x] ConditionalPanel
- [x] Footer
- [x] Editor (index)
- [x] Preview (index)
- [x] SearchBar
- [x] Tabs (index)
- [x] PrimaryPanes (index)
- [x] Outline
- [x] SourcesTree
- [x] ProjectSearch (index)
- [x] SourceSearch
- [x] TextSearch
- [x] Frames (index)
- [x] Frame
- [x] Group
- [x] WhyPaused
- [x] SecondaryPanes (index)
- [x] ChromeScopes
- [x] CommandBar
- [x] EventListeners
- [x] Expressions
- [x] Scopes
- [x] Close
- [x] PaneToggle
- [x] Accordion
- [x] AutoComplete
- [x] BracketArrow
- [x] Dropdown
- [x] ManagedTree
- [x] Modal
- [x] ~ObjectInspector~
- [x] Popover
- [x] ResultList
- [x] SearchInput
- [x] Svg
  - [x] Update usage to be JSX compatible. [See comment here.](https://github.com/devtools-html/debugger.html/pull/3573#discussion_r131511803)

**Comment by nyrosmith** [comment]
Can I try to help you converting the components?

**Comment by jasonLaster** [comment]
@nyrosmith sure! want to grab Modal or Popover?

**Comment by nyrosmith** [comment]
Maybe starting with something trivial and then converting one after another. I think there are enough compononents to work on.
Do you prefer 1 branch per component or one branch for all changes?

**Comment by jasonLaster** [comment]
one branch per component. It's easier to review + land

**Comment by nyrosmith** [comment]
OK. I'll start tomorrow and really hope to deliver results quickly.

**Comment by jasonLaster** [comment]
Lets also fix this bug: https://github.com/devtools-html/debugger.html/issues/3547

which we just created :)

**Comment by Anzumana** [comment]
would also like to try asked @wldcordeiro which one he thinks i should start with

**Comment by jasonLaster** [comment]
@Anzumana just jump in try one. no worries

**Comment by amelzer** [comment]
@wldcordeiro I'll do the Tabs.js now

**Comment by jasonLaster** [comment]
:thumbsup:

**Comment by ksaldana1** [comment]
@wldcordeiro Looks like the `Breakpoints` component is listed twice.

**Comment by zacck** [comment]
@nyrosmith @jasonLaster  I'll take a component or two if there is more to convert ...

**Comment by jasonLaster** [comment]
@zacck how about Outline or Expressions?

**Comment by nyrosmith** [comment]
@jasonLaster I'd like to try ManagedTree because understanding how it works may help me solve #3652

**Comment by zacck** [comment]
I'm starting with Outline, Looks like I will have to throw in previewFunction too

**Comment by wldcordeiro** [comment]
I'm grabbing `Preview` and `Tabs`

**Comment by zacck** [comment]
I'm grabbing `previewFunction`.

**Comment by nyrosmith** [comment]
I started with Accordion. Can someone point me to how I can test it?

**Comment by jasonLaster** [comment]
the sidebar uses it

**Comment by rohanprasad** [comment]
Hey guys, can you suggest any component that I can pick up ?

**Comment by jasonLaster** [comment]
@rohanprasad perhaps Outline?

**Comment by zacck** [comment]
But I thought I did Outline already?

**Comment by jasonLaster** [comment]
:) true. Perhaps Frame

**Comment by rohanprasad** [comment]
@jasonLaster Sure, I have already started with #3714 , will pick this after that.

**Comment by wldcordeiro** [comment]
Down to just `ChromeScopes` and some storybook files! 😄

**Comment by wldcordeiro** [comment]
I'm covering the last bits in a PR. 🎆

**Comment by zacck** [comment]
@wldcordeiro  I was working on `previewFunction` but @jasonLaster  said not to  bother since we are going to do away with it.

**Comment by wldcordeiro** [comment]
@zacck oh well what's done is done. 😆 This way we have no code using older ReactDOM helpers and when we do get rid of it it's a swap.

**Comment by wldcordeiro** [comment]
It's a wrap! We now are using JSX everywhere, thank you everyone for your help getting the project onto the JSX train. We hope that this enables more contributors to join in and reduces friction for them along with our move to future React versions! 🎉 🎉
