### ISSUE TITLE
Kill the Web Test Runner

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3514]
The web test runner, has currently been deprecated for the past two months while we have worked to stabilize the debugger in preparation of 56.

Over this time, I've realized that we do not have enough mochitests and have continued adding additional tests.

We have two options as I see it, we can invest the time to stabilize WTR or we can kill it (with the option of reviving at any point). 

#### Stabilize

1. unify the two tests
2. run WTR on CI
3. add the necessary APIs like type, arrows etc 

#### Kill it

1. rm the directory
2. update the docs
3. improve the mochitest runner so that it is more contributor friendly

---

I'm in favor of killing it and investing in the mochitest experience. Mochitests are the source of truth and we should continue to prioritize them until we are happy with that experience.

We can always come back to the WTR at a later date. We've learned a lot from it and if anything, we know it's possible. We also know it will be much easier when headless firefox is a reality.

**Comment by codehag** [comment]
:+1: I support the killing it option as well

**Comment by bomsy** [comment]
👍🏾
