### ISSUE TITLE
[Dark] Improve background color styling

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3523]
We seem to have two background colors that are used almost everywhere (light and dark grey-blue)

- [x] sidebars bleed into the editor (same background)
- [x] source search especially bleeds into editors
- [ ] symbol popup has the same background
- [x] right sidebar has a zebra thing

there is also a question of focus, selected, and hover background states too 

---

<img src='https://shipusercontent.com/24bc314fb698da371c6c971aa7773df7/Screen%20Shot%202017-08-01%20at%204.35.55%20PM.png' title='Screen Shot 2017-08-01 at 4.35.55 PM.png' width=1280>

<img src='https://shipusercontent.com/cde4f92fd17132523522f46f9690cf23/Screen%20Shot%202017-08-01%20at%204.35.48%20PM.png' title='Screen Shot 2017-08-01 at 4.35.48 PM.png' width=1362>

**Comment by zspitzer** [comment]
Can the background colours be made much darker? 

the current low contrast theme hurts my eyes compared to Chrome's dark theme

**Comment by violasong** [comment]
Thanks @zspitzer, will keep that in mind.

**Comment by diessica** [comment]
Let's get this closed! I'll work on the last item.

**Comment by jasonLaster** [comment]
Thanks @diessica i think this is actually done :) 

take a look at firefox nightly. The launchpad colors are off at the moment due to the variables not being synced

**Comment by violasong** [comment]
Oh yeah :), I think this is done except possibly "symbol popup has the same background" - I forget what that was referring to.

**Comment by jasonLaster** [comment]
cmd+shift+o for function search.

![Screen Shot 2017-09-27 at 8.08.10 PM.png](https://shipusercontent.com/b4d2c9a854131e7652a0c0e9882424d5/Screen%20Shot%202017-09-27%20at%208.08.10%20PM.png)


I'd like to circle back when we look at editor UX

**Comment by diessica** [comment]
@jasonLaster I don't get it. Still need help on this?

**Comment by jasonLaster** [comment]
nope, we're good here.
