### ISSUE TITLE
[Pretty Print] breakpoints are not persisted

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3532]
We are not persisting breakpoints that are added to a pretty printed source.

STR:

* open the debugger and point to math.min
* pretty print the source
* add a breakpoint
* reload

expected: breakpoint is on the minified source
actual: no breakpoint

**Comment by clarkbw** [comment]
See also [bug 1172931](https://bugzilla.mozilla.org/show_bug.cgi?id=1172931)

**Comment by jasonLaster** [comment]
We might get this for free when we add persisted pretty tabs

**Comment by jasonLaster** [comment]
closing because once we do #4009 it will work.

**Comment by jasonLaster** [comment]
STR are at 
+ https://github.com/webcompat/web-bugs/issues/12325#issuecomment-336168501. 
+ the second is in my previous comment -- happy to file a new bug for that if you prefer.

Here's a screencast of clicking through the call stack when the breakpoint does stick (on a simpler page: https://miketaylr.com/code/input-type-attr.html) not doing anything useful:

http://recordit.co/q7CrccRfcH

**Comment by janodvarko** [comment]
I have another test case:

STR:
1) Load http://softwareishard.com/tests/debugger/issue3532/
2) Open index.js file and pretty print it
3) Create BP on line 2
4) Click the `Click Me!` button on the page
5) BP doesn't hit => BUG

Interesting is that the test case does work online (given the URL above), but doesn't work when running locally on my web server with this URL:
http://10.0.3.111:8080/www/source-maps/prettyprint/

Honza

**Comment by jasonLaster** [comment]
strange, it works for me too. It also works with reloading as well...

**Comment by darkwing** [comment]
Catches for me.  Closing.
