### ISSUE TITLE
[Investigate] Random actions cause a suspended AudioContext to resume

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3541]
It looks like when the debugger fires its resume command, the audioCtx is also resumed. There is a good explanation in the ticket about what is going on. We should investigate to see if we can provide more information / help somehow.

Copy-pasta 🍝 :

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

Steps to reproduce:

Go to https://webaudiodemos.appspot.com/wubwubwub/ (not my site but an easy way to reproduce)
Open dev console and run audioCtx.suspend()
Add a breakpoint in any js file (also caused by opening the dev tools, or downloading a file)

Actual results:

Audio playback resumed

Expected results:

Audio Playback should have stayed paused

More information: https://bugzilla.mozilla.org/show_bug.cgi?id=1375562

**Comment by jasonLaster** [comment]
This is a server bug, so I'm closing this and we can track it on bugzilla
