### ISSUE TITLE
[mochitest] browser_dbg-pretty-print is failing

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3542]
looks like the pretty print test is failing. Probably related to the pretty print work that just landed

```
3539 INFO TEST-UNEXPECTED-FAIL | devtools/client/debugger/new/test/mochitest/browser_dbg-pretty-print.js | Uncaught exception - at chrome://mochitests/content/browser/devtools/client/debugger/new/test/mochitest/head.js:382 - Error: Unable to find source: math.min.js:formatted

Stack trace:
```

https://circleci.com/gh/devtools-html/debugger.html/5873?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by jasonLaster** [comment]
The error is coming from line 13: 
`  const ppSrc = findSource(dbg, "math.min.js:formatted");` I bet it's a timing issue with the new async code...




```js
  clickElement(dbg, "prettyPrintButton");
  yield waitForDispatch(dbg, "SELECT_SOURCE");

  const ppSrc = findSource(dbg, "math.min.js:formatted");
  ok(ppSrc, "Pretty-printed source exists");
```

**Comment by codehag** [comment]
has this been resolved?

**Comment by jasonLaster** [comment]
yep
