### ISSUE TITLE
[SourceSearch] Fix “No Results” positioning

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3547]
looks like this [PR] broke the positioning. It's our first JSX causality :)

[PR]:https://github.com/devtools-html/debugger.html/issues/3507

<img src='https://shipusercontent.com/226d226c2c878771e41209a5f15d44f5/Screen%20Shot%202017-08-03%20at%203.12.52%20PM.png' title='Screen Shot 2017-08-03 at 3.12.52 PM.png' width=1139>

**Comment by wldcordeiro** [comment]
I'm not sure if the JSX conversion did it or not. I'm double checking it but nothing is immediately standing out.
