### ISSUE TITLE
[PrettyPrint] Odd Parsing Issue with `let` 

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#3552]
There's a weird parsing issue I discovered.  Consider the following within source:

```
let d;
```

When I click the pretty print button, the source gets changed to:

```
letd;
```

The space is removed, thus `letd` becomes  a keyword.

Can be seen at: https://davidwalsh.name/demo/EmptyLineTest.php -> EmptyLineTest.js

**Comment by codehag** [comment]
woah interesting! thanks for reporting it!

**Comment by jasonLaster** [comment]
lets try this again, we just bumped pretty print

**Comment by nyrosmith** [comment]
I just checked against current master. The issue still exists.

**Comment by jasonLaster** [comment]
Thanks.

Would be fun to debug pretty-fast

**Comment by jasonLaster** [comment]
This bug requires getting https://github.com/mozilla/pretty-fast setup and working on adding a [test](https://github.com/mozilla/pretty-fast/blob/master/test.js#L92) and a fix in a PR.
