### ISSUE TITLE
Chrome issues with breakpoints

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3562]
We added some new methods to firefox -- but we missed this with chrome. We should add `getBreakpointByLocation`, and possibly a few other methods

**Comment by codehag** [comment]
Some more details:
test adding and removing breakpoints with chrome as a debuggee. For sure we will need to add `getBreakpointByLocation`, but we may need others. You will find the relevant files in `src/client/`

**Comment by jasonLaster** [comment]
this could be difficult because 
a) debugging the client/command layer is low level.
b) there could be other bugs here too

**Comment by jasonLaster** [comment]
added to a new tracking issue: #3947
