### ISSUE TITLE
[SourcesTree] webcomponents not displaying well in tree view

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#3568]
Try going here: https://www.webcomponents.org/collection/PolymerElements/paper-input-elements
And opening the debugger.
There is a `data://` tree that holds all the JS files and things look very strange.  See screenshot.

<img width="1112" alt="screen shot 2017-07-28 at 8 59 57 am" src="https://user-images.githubusercontent.com/2134/28980344-647774aa-7902-11e7-9b3e-c61e4e439f0f.png">

**Comment by clarkbw** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1385320

**Comment by nyrosmith** [comment]
I just rechecked and it seems it is fixed.

![polymer](https://user-images.githubusercontent.com/2511026/34639298-969e89f0-f2dd-11e7-8182-6b6ca46dc8bb.gif)

Closing for now but feel free to reopen if you still have issues

**Comment by jasonLaster** [comment]
Yep, seems better
