### ISSUE TITLE
[Breakpoints] Allow to set breakpoints for different statements within a single line

### ISSUE THREAD

**Issue by SebastianZ** [devtools-html/debugger.html#3574]
It should be possible to set a breakpoint for a specific statement within a single line, making it easier to debug one function call in a stack of calls.

The Chrome DevTools already have that feature looking like this:

![inline breakpoints](https://user-images.githubusercontent.com/958943/28989811-266a0120-7978-11e7-9146-44845666f9ca.png)

Sebastian

**Comment by bomsy** [comment]
Thanks for filing. We are working on column breakpoints atm.

**Comment by jasonLaster** [comment]
closing as we're currently working on this in other issues
