### ISSUE TITLE
[Blackbox] Blackboxed sources can't be distinguished in source tree

### ISSUE THREAD

**Issue by SebastianZ** [devtools-html/debugger.html#3576]
Blackboxed sources are displayed the same as non-blackboxed sources. They should be shown differently, so it's easier to distinguish them.

Sebastian

**Comment by jasonLaster** [comment]
I'm not sure the correct treatment should be. Perhaps we replace the file icon with the eye? What does chrome do?

**Comment by SebastianZ** [comment]
As far as I can see, the Chrome DevTools don't make a difference, either.

Though the old debugger UI displayed the name of the script faintly:

![Faint blackboxed script](https://user-images.githubusercontent.com/958943/29088727-5705415a-7c7a-11e7-924d-7f8366a04f7a.png)

But a file icon with the eye sounds good, too. Maybe a combination of both?

Sebastian

**Comment by tohmjudson** [comment]
/claim
I'm on it!
