### ISSUE TITLE
Code Quality Reporting

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3581]
It would be nice to get automated code quality reporting on CI:

1. help us see what should be improved
2. help point out quality regressions

https://codebeat.co/
https://codeclimate.com

i wonder what others are using and what the tradeoffs are.

**Comment by AnshulMalik** [comment]
I have only seen people using https://www.codacy.com/

**Comment by jasonLaster** [comment]
i like it

**Comment by jasonLaster** [comment]
Closing this issue and moving to the [enhancements](github.com/devtools-html/debugger.html/projects/5) board. 

* We will hopefully be able to prioritize it in the near future. 
* The issue is closed temporarily, but feel free to continue discussing the issue
