### ISSUE TITLE
[Preview] Click and drag in editor still shows the value preview

### ISSUE THREAD

**Issue by gregtatum** [devtools-html/debugger.html#3589]
Steps to reproduce:
 * Double click on a word to highlight it.
 * Drag around to highlight a selection.
 * Repeat

Expected result:
 * I should get an easy to highlight line of text, where I can easily control the selection.

Actual result:
 * The preview pop up is still active, causing either my selection to drop (when double clicking), or for the preview to get in the way of the text that I'm selecting.

Example image of attempting a selection:
<img width="748" alt="image" src="https://user-images.githubusercontent.com/1588648/29040952-a48fac26-7b76-11e7-98d9-d76d57fb6f49.png">

**Comment by jasonLaster** [comment]
diff --git a/src/components/Editor/Preview.css b/src/components/Editor/Preview.css
index 5450120..f98e2ea 100644
--- a/src/components/Editor/Preview.css
+++ b/src/components/Editor/Preview.css
@@ -33,6 +33,8 @@
   cursor: pointer;
 }

+/* can we do something like this: :not(::selection) */
+
 .selection,
 .debug-expression.selection {
   background-color: var(--theme-highlight-yellow);
(END)

**Comment by codehag** [comment]
fixed by #3749
