### ISSUE TITLE
[prefs] drop default schema value

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3595]
The debugger schema [pref][p] should not have a default value because it doesn't mean anything. This [logic][g] should just work if it's not set.

https://bugzilla.mozilla.org/show_bug.cgi?id=1388128

[g]:https://github.com/devtools-html/debugger.html/blob/master/src/utils/prefs.js#L47-L53
[p]:https://github.com/devtools-html/debugger.html/blob/master/assets/panel/prefs.js#L27

**Comment by lukaszsobek** [comment]
Maybe move the value from one place to another? :)

**Comment by jasonLaster** [comment]
going to close as it's stale and not a priority.
