### ISSUE TITLE
Investigate a key shortcut library like mousetrap

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#360]
We're running into issues with keyboard shortcuts that could be fixed with a mature library like [mousetrap](https://github.com/ccampbell/mousetrap).

[file search does not work](https://github.com/jlongster/debugger.html/issues/354#issuecomment-233634994)

**Comment by bgrins** [comment]
Not sure what issues you are running into exactly, but maybe the key-shortcuts module will work: https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/key-shortcuts.js#28. Looks like it has a fairly similar API.
