### ISSUE TITLE
Left side bar js / resources list - scroll into view not happening 

### ISSUE THREAD

**Issue by ruturajv** [devtools-html/debugger.html#3631]
**STR**:
1. open www.bbc.com
1. click the any items in left
1. use down-arrow on keyboard to select list-item below
1. keep pressing down-arrow, soon, the selection will go below the visible pane

**Expected**: the selected item should be brought into view.

![debugger-sidebar-scroll-into-view](https://user-images.githubusercontent.com/227817/29201803-451cfe7c-7e7f-11e7-9875-dcd72b1ff626.gif)

**Comment by jasonLaster** [comment]
We've fixed this and it's broken so many times :/

The current solution relies on a set height. I think we need some logic to validate that it is correct for all the shown nodes...


https://github.com/devtools-html/debugger.html/blob/master/src/components/PrimaryPanes/SourcesTree.js#L263-L264

**Comment by jasonLaster** [comment]
closing as we're upgrading the tree component which changes this logic
