### ISSUE TITLE
[source] improve loaded state

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3648]
It would be nice to cleanup the source loaded state question. There are three states: "unloaded", "loading", "loaded"

One approach is to use a util to make "loaded" clearer. Another is to change the loading field to `loadedState` and have the three values

* here is a [gist](https://gist.github.com/jasonLaster/9ceb5d8c38c98d3350ef5b75adc7f18d) for option one
* here is a [gist](https://gist.github.com/jasonLaster/df279b487e8728b3ee93e0e3b28b5810) for option two

@bomsy persuaded me option two is better :)

**Comment by sharathnarayanph** [comment]
May I work on this?

**Comment by jasonLaster** [comment]
sure!
