### ISSUE TITLE
[ProjectSearch] steal Atom’s look and feel

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3651]
Our project search focus states and general background colors could use some work. Lets borrow ideas from Atom while trying to use our CSS variables. 

It's okay to introduce a new color if we need to as well. One way to do it well is to use HSL and change the lightness by a bit.

### Atom

![](http://g.recordit.co/qTEtjscM9x.gif)

### Current Version

![](http://g.recordit.co/3LAmYEfGOf.gif)

### Notes

* the best way to find a css variable is to find another color in the UI and inspect it :)

**Comment by bomsy** [comment]
Noticed this. It would cool to handle while fixing look and feel
![image](https://user-images.githubusercontent.com/792924/29318847-a83b033a-81c9-11e7-9a41-220cf5fdfa8d.png)

**Comment by zacck** [comment]
@bomsy  trying to tackle this one ands I can't seem to replicate the issue you are facing has that been handled?

**Comment by bomsy** [comment]
one thing that would be fun would be to highlight the line number when the file path is focused - JLast

**Comment by bomsy** [comment]
@zacck i've added @jasonLaster comments here for ease

**Comment by zacck** [comment]
@bomsy  Thank you 😄 
@jasonLaster for the  number highlight I propose we change the  focused line-number to white, I have also added indentation to the  numbers. Please see the attached image
![screen shot 2017-08-30 at 8 57 52 pm](https://user-images.githubusercontent.com/897731/29890029-79a3b068-8dc6-11e7-897e-dae8e5eeaf13.png)

Going to attempt switching the file path and file icon filling to a contrasting color too

**Comment by jasonLaster** [comment]
Here's the text selection

1. lighten gutter lines
2. ligthen lines
3. outline around matches...

lots of good stuff :P

![](http://g.recordit.co/koMBTlEeva.gif)

**Comment by zacck** [comment]
@jasonLaster  do you think I can 'compose' the code-mirror-gutter-background?  In order to make it lighter? I am not in favor of changing the value because what happens in light mode then?

**Comment by jasonLaster** [comment]
compose?

**Comment by zacck** [comment]
To lighten the gutter in dark mode, I would need to darken it in light mode? Or am I over complicating this?

**Comment by jasonLaster** [comment]
I don't think we have a gutter in project search. I'm confused
