### ISSUE TITLE
Stop using pointer cursor for buttons

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3669]
Pointer cursor isn't used in other DevTools Tabs. Cursor style should be consistent with other DevTools tabs.

link: https://bugzilla.mozilla.org/show_bug.cgi?id=1390062

**Comment by MayankSrivastav** [comment]
Hi, I would like to take it up.
I guess we are talking about the file-name tabs in the editor panel? The pointer there should be an arrow pointer?
File to be modified seems like Tabs.css in Editor component?

**Comment by jasonLaster** [comment]
@MayankSrivastav great. It's yours.

Yeah, a lot of these should be removed I guess

<img src='https://shipusercontent.com/ba90c69035288dd19cba29ba424d168b/Screen%20Shot%202017-08-16%20at%2011.40.44%20AM.png' title='Screen Shot 2017-08-16 at 11.40.44 AM.png' width=1091>

**Comment by MayankSrivastav** [comment]
Ok. so, cursor: pointer needs to be removed from every css file. pointer should not be used at all.

**Comment by jasonLaster** [comment]
that's what i think
