### ISSUE TITLE
[Windows] launchpad fails to start firefox with debugger-server

### ISSUE THREAD

**Issue by MayankSrivastav** [devtools-html/debugger.html#3671]
After starting the debugger and launching the Firefox with the TodoMVC app, the debugger doesn't show any node to debug.
The debugger window is blank.  So, we can't select the application to debug. Attached is a screenshot for reference on Windows.
![windows issue](https://user-images.githubusercontent.com/13278659/29326203-3c546de8-8208-11e7-90c3-7e182d62977f.png)

**Comment by jasonLaster** [comment]
closing because it's here:

https://github.com/devtools-html/devtools-core/issues/170
