### ISSUE TITLE
ContextMenus should show keyboard shortcuts

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3673]
The old debugger used to show keyboard shortcuts. It would be nice to have this behavior as well as it's a good education

### New Debugger
<img width="242" alt="screen shot 2017-07-06 at 10 26 13 pm" src="https://user-images.githubusercontent.com/2481105/27940717-62f6d72a-629a-11e7-9a20-ceae1f0fbba5.png">

### Old Debugger
<img width="374" alt="screen shot 2017-07-06 at 10 19 47 pm" src="https://user-images.githubusercontent.com/2481105/27940639-cf8f0714-6299-11e7-8120-ce981a2f93e6.png">

**Comment by bgrins** [comment]
If the `acceltext` attribute is set on the `<menuitem>` then it will print it out with native styling. For instance, `acceltext="⌘P"`. However, in order for this to happen automatically the menuitem has to  [have a `key` attribute pointing to a xul key](https://dxr.mozilla.org/mozilla-central/rev/b95b1638db48fc3d450b95b98da6bcd2f9326d2f/layout/xul/nsMenuFrame.cpp#1032).

The `acceltext` could potentially be generated explicitly via ShortcutUtils.jsm from a `<key>` element, and the old debugger does do that [for things like tooltips](https://dxr.mozilla.org/mozilla-central/rev/b95b1638db48fc3d450b95b98da6bcd2f9326d2f/devtools/client/debugger/views/toolbar-view.js#55.  If we want to avoid using `<key>` elements altogether then we could modify that module a bit to accept metadata.

How do we do keyboard shortcut handling in the debugger, again?

**Comment by jasonLaster** [comment]
We use key-shortcuts via a shortcuts context: https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/index.js#L207

**Comment by bgrins** [comment]
OK, and how is the menu that ultimately calls `onToggleBreakpoint` constructed?

**Comment by bgrins** [comment]
I think I'd modify [KeyShortcuts.stringify](https://github.com/devtools-html/devtools-core/blob/2c01041a1812a3dafee3367ac3e72fd8518fecd3/packages/devtools-modules/src/key-shortcuts.js#L152) function to more closely match [ShortcutUtils.prettifyShortcut](https://dxr.mozilla.org/mozilla-central/source/toolkit/modules/ShortcutUtils.jsm), and then manually set the `acceltext` to that value whenever the `menuitem` is created

**Comment by jasonLaster** [comment]
@lukaszsobek I'm un-assigning you as it's been two weeks and this is a panel bug. Feel free to re-clame

**Comment by jbhoosreddy** [comment]
This potentially is not that important in comparison to other things, but I've been wanting this forever. I'm sure I made other issues for this also. But I seem to remember there was something blocking it.. Anyways, claiming it.

**Comment by jbhoosreddy** [comment]
I should have a PR for the Panel by tomorrow
