### ISSUE TITLE
[Breakpoints] Leftover breakpoint breaks the debugger

### ISSUE THREAD

**Issue by eoger** [devtools-html/debugger.html#3682]
I set a breakpoint in a previous session in the browser toolbox debugger.
When I open the debugger (even after restarting the browser multiple times), clicks on the Firefox UI are not registered and CSS `:hover` rules are not applied.
Trying to remove that breakpoint triggers an error.

Screencast:
https://gfycat.com/gifs/detail/JubilantDeepAyeaye

Entire screenshot of the errors in the screencast:
<img width="1003" alt="screen shot 2017-08-16 at 10 45 00 am" src="https://user-images.githubusercontent.com/6424575/29369234-fed3a0b6-826f-11e7-8918-8a167bd06a5d.png">

cc @vladikoff

**Comment by jasonLaster** [comment]
@eoger mind sharing the STR?

**Comment by vladikoff** [comment]
@eoger Was this in Nightly?

**Comment by eoger** [comment]
Yes this was Nightly

**Comment by eoger** [comment]
@jasonLaster wasn't able to reproduce exactly. But:
- Open Firefox
- Open browser toolbox, set a breakpoint in browser-sync, line 260.
- Cmd+Q, reopen browser, reopen debugger

From then the breakpoint has disappeared, but I can't set it up again:
https://gfycat.com/gifs/detail/LavishEnviousAdder
<img width="949" alt="screen shot 2017-08-16 at 11 57 20 am" src="https://user-images.githubusercontent.com/6424575/29372914-83c5fce2-827a-11e7-92c5-2ccb37fb9aa1.png">

**Comment by vladikoff** [comment]
Ok I was able to reproduce this locally, the breakpoint won't stick to the line number:

![action-s](https://user-images.githubusercontent.com/128755/29379775-80cb4850-8291-11e7-93f7-a05a0724849d.gif)

**Comment by vladikoff** [comment]
### STR

* Fresh Nightly Profile (57.0a1 (2017-08-16) (64-bit))
* Open toolbox
* Set a breakpoint at browser-sync.js by going to Debugger, looking for file called `browser-sync.js`:

![image](https://user-images.githubusercontent.com/128755/29379875-d26baa60-8291-11e7-8781-263b872b1e7b.png)

* CMD+Q DevTools, CMD+Q Firefox
* Restart the created profile
* Open Toolbox, browser-sync.js is open
* Scroll to line, no breakpoint set:

![image](https://user-images.githubusercontent.com/128755/29379927-0226a32c-8292-11e7-8b6f-2d9c22ad9791.png)

* Try to set a breakpoint on that line: 
![260](https://user-images.githubusercontent.com/128755/29379950-14ba3b66-8292-11e7-8041-e41755560041.gif)

Errors in console:

![image](https://user-images.githubusercontent.com/128755/29379958-2234fe8e-8292-11e7-9b35-5fb41fa8cca0.png)

**Comment by jasonLaster** [comment]
I believe this bug is coming the fact that we "move" breakpoints to keep them in the same original location when the user reloads.

Scenario: 
1. the app is using sourcemaps to bundle three files (a,b,c). 
2. The user adds a breakpoint to file b, line 10
3. the user changes file a
4. the user reloads the page
5. the debugger sees that the file b, line 10 breakpoint points to the wrong generated location
6. the debugger "moves" the breakpoint to the new location, which means 
  6.a it updates the original locations in the UI
  6.b it creates a new breakpoint on the server
  6.c it forgets to remove the old breakpoint on the server
  
This diff is a sketch of what i think the solution should look like. When we see the new and old generated location is different, we remember to clean up after ourselves and remove the breakpoint.

```diff

diff --git a/src/actions/breakpoints/syncBreakpoint.js b/src/actions/breakpoints/syncBreakpoint.js
index ee220b4..4237afb 100644
--- a/src/actions/breakpoints/syncBreakpoint.js
+++ b/src/actions/breakpoints/syncBreakpoint.js
@@ -64,6 +64,10 @@ export async function syncClientBreakpoint(
       newGeneratedLocation
     );

+    if (locationMoved(generatedLocation, newGeneratedLocation)) {
+      await client.removeBreakpoint(generatedLocation);
+    }
+
     const breakpoint = {
       ...pendingBreakpoint,
       id: makeLocationId(newLocation),
diff --git a/src/client/firefox/commands.js b/src/client/firefox/commands.js
index 40f2232..e405e9d 100644
--- a/src/client/firefox/commands.js
+++ b/src/client/firefox/commands.js
@@ -125,9 +125,9 @@ function setBreakpoint(
     });
 }

-function removeBreakpoint(breakpoint: Breakpoint) {
+function removeBreakpoint(generatedLocation) {
   try {
-    const id = makeLocationId(breakpoint.generatedLocation);
+    const id = makeLocationId(generatedLocation);
     const bpClient = bpClients[id];
     if (!bpClient) {
       console.warn("No breakpoint to delete on server");
```

**Comment by jasonLaster** [comment]
This is fixed here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1394495
