### ISSUE TITLE
[flow] update to v 56

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3683]
It would be great to get help upgrading flow from 52 to 53.

Flow 53 is blocked on some new flow rules: https://circleci.com/gh/devtools-html/debugger.html/6192?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by arthur801031** [comment]
I'll take a stab at this :)

**Comment by jasonLaster** [comment]
Oh thanks @arthur801031!

**Comment by jasonLaster** [comment]
This PR is a good start, but it's possible things have changed in 54 and 55.

[flow-upgrade][fu] could help 

[fu]: https://github.com/facebook/flow/tree/master/packages/flow-upgrade

**Comment by ahuth** [comment]
I've started on this as well. Will take a shot and see how it goes. Got about half of the flow errors resolved.

**Comment by jasonLaster** [comment]
@ahuth that's great!

**Comment by jasonLaster** [comment]
Open a WIP PR so we can provide feedback

**Comment by jasonLaster** [comment]
what version of flow are you using?

**Comment by ahuth** [comment]
> Open a WIP PR so we can provide feedback

Will do 👍 

> what version of flow are you using?

I'm in the middle of upgrading to 0.53.0 as a first shot, which seems to be where the significant React changes were made. Planning on going to the latest version, though (0.57.3) by the end of the effort.

**Comment by jasonLaster** [comment]
sounds good. We'd obviously be happy to go to 53 before we try 54, ...

**Comment by ahuth** [comment]
An interesting thing is that flow-upgrade doesn't seem to be able to actually change anything:

```
Running 3 codemods...

Processing 139 files...
Spawning 3 workers...
Sending 47 files to free worker...
Sending 47 files to free worker...
Sending 45 files to free worker...
All done.
Results:
0 errors
62 unmodified
0 skipped
0 ok
Time elapsed: 42.583seconds
✨  Done in 137.17s.
```

Doing the upgrade by hand is partially done, but was hoping that the codemods could make it a bit easier.

**Comment by jasonLaster** [comment]
heh - yeah... weird

**Comment by ahuth** [comment]
/claim

Opened a WIP PR

**Comment by ahuth** [comment]
@jasonLaster, should I close this, since we've upgraded to Flow 53? I still want to upgrade this to 57, but that will take some more work on a couple of the dependencies.

**Comment by jasonLaster** [comment]
Good call
