### ISSUE TITLE
[Breakpoints] then() is ignored

### ISSUE THREAD

**Issue by TitanNano** [devtools-html/debugger.html#3689]
![screen shot 2017-08-16 at 16 34 34](https://user-images.githubusercontent.com/4500858/29384172-6e0855e0-82d3-11e7-953e-9e55f8d7817c.png)

This is transpiled typescript + sourcemap. The breakpoint is simply ignored in both Dev and Nighty but halts in Chrome, so I'm certain the code is executed.

**Comment by codehag** [comment]
this might be related to #3479

**Comment by jasonLaster** [comment]
@TitanNano can you try this now in Nightly

**Comment by TitanNano** [comment]
@jasonLaster I tested this and for my case it appeaser to work now.

**Comment by jasonLaster** [comment]
Hey! That's great news. I think we fixed it in the server
