### ISSUE TITLE
Help people submit debugger examples

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3699]
blocks and rawgit are good resources for submitting debugger examples that can easily be debugged.

We should have docs for the best process and point to them in our ISSUE_TEMPLATE.md

**Comment by jasonLaster** [comment]
Im finding glitch to be really good for simple examples

**Comment by digitarald** [comment]
gist + bl.ocks.org works great for me and can track changes as well.

Example for a console issue: https://bl.ocks.org/digitarald/462312bed5e78242ce3fbfbb9bd23f7c

**Comment by jasonLaster** [comment]
nice, i think i liked glitch because of live edit as well. I'm often tweaking to get the smallest case

**Comment by jasonLaster** [comment]
closing as we can discuss in the ISSUE_TEMPLATE
