### ISSUE TITLE
Polish Dark and Firebug themes

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#370]
We now support three themes (dark, firebug, light). As a result we need to convert all of our styling to css variables so that the themes always look good.

For example, the [autocomplete](https://github.com/jlongster/debugger.html/blob/master/public/js/components/Autocomplete.css#L14) stylesheet uses raw values like `#dde1e4`, which should be `var(--theme-gray)`. All values can be found in [variables.css](https://github.com/jlongster/debugger.html/blob/master/public/js/lib/variables.css#L86).

Extra credit if we update our stylelint to check for colors and enforce variables... after briefly looking i couldn't find a rule

#### Firebug
![screen shot 2016-07-20 at 1 15 54 pm](https://cloud.githubusercontent.com/assets/254562/16995740/fadeceb4-4e7b-11e6-8010-c01b9e0d8a96.png)

### Dark theme
![screen shot 2016-07-20 at 1 15 36 pm](https://cloud.githubusercontent.com/assets/254562/16995739/fadcc8a8-4e7b-11e6-8492-7f1ce48eecc8.png)

**Comment by jasonLaster** [comment]
Pulling it out of the sprint as we're not going to be able to get to it in time.

**Comment by clarkbw** [comment]
related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1295321

**Comment by wldcordeiro** [comment]
If someone can mentor me on what is where, I'm down to do this. 👍

**Comment by jasonLaster** [comment]
Hey @wldcordeiro would be happy to help!

**Comment by wldcordeiro** [comment]
@jasonLaster adjust the font sizes? Are the current values not using the theme vars? This is for the right and left sidebar?

**Comment by jlongster** [comment]
This bug should probably be moved to next sprint. Right now we're just making sure that the basic dark/firebug themes even work. They were totally broken before but I just spent a few hours getting them basically working. How does moving this out (as a polish bug) sound?

**Comment by jasonLaster** [comment]
sounds good to me

**Comment by jasonLaster** [comment]
Closing this issue and re-opening a new more relevant issue #988.
