### ISSUE TITLE
[workers] show a list of workers

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3701]
It would be great to show a list of workers in the new UI. The old debugger UI had it

https://bugzilla.mozilla.org/show_bug.cgi?id=1304682

**Comment by nyrosmith** [comment]
@jasonLaster I'll try this but atm I have no idea where to Start.
Can you point me to where I can read the available workers.

**Comment by jasonLaster** [comment]
Sure. I'll have to dig for it as well

**Comment by jasonLaster** [comment]
How about you start with dummy data and the UI? We want something similar
to chrome where it's an accordion Pane on the right.

**Comment by nyrosmith** [comment]
You mean the right section with breakpoints, expressions,...?

**Comment by jasonLaster** [comment]
Yep.

**Comment by jasonLaster** [comment]
Here's a quick branch for getting started.

I haven't tested it yet so it will need some massaging to iron out the mistakes, but it should be a good template for getting a secondary sidebar pane. It also adds a storybook story so you can quickly sketch out the UI without real data

https://github.com/jasonLaster/debugger.html/tree/worker
