### ISSUE TITLE
Variable preview sometimes not shown

### ISSUE THREAD

**Issue by SebastianZ** [devtools-html/debugger.html#3705]
The variable preview doesn't work in some cases.

Test case:
1. Go to https://css-tricks.com/almanac/properties/s/shape-outside/
2. Set a breakpoint in the (index) script at line 248 (`if(autocomplete.autocomplete...`)
3. Scroll the page
  => Script execution will stop at that line.
4. Hover the first `autocomplete`.

=> No preview popup is shown.

Sebastian

**Comment by SebastianZ** [comment]
Here's some simpler example code:

```html
<script>
function test(y) {
  let x = 2;
  return y(x);
}

let a = test(function foo(bar) {
  return bar * 4;
});
console.log(a);
</script>
```

Breaking at `return bar * 4;` won't show a preview for `bar`.

Sebastian

**Comment by codehag** [comment]
Thanks for the report!

**Comment by jasonLaster** [comment]
Added an example [here](https://tide-clock.glitch.me/)

I noticed previewing the param works, so this is an issue w/ how we find the expression to evaluate

```diff
diff --git a/src/actions/ast.js b/src/actions/ast.js
index 4784f9b..7b3da4f 100644
--- a/src/actions/ast.js
+++ b/src/actions/ast.js
@@ -113,11 +113,13 @@ export function setSelection(
         const source = getSelectedSource(getState());
         const _symbols = await parser.getSymbols(source.toJS());

+        // this is the best part, lets see if the token can be found
         const found = findBestMatch(_symbols, tokenPos, token);
         if (!found) {
           return;
         }

+        // if it is found lets see what the value of expression is
         const { expression, location } = found;

         if (!expression) {
diff --git a/src/utils/editor/expression.js b/src/utils/editor/expression.js
index 2b0e8a5..7bff998 100644
--- a/src/utils/editor/expression.js
+++ b/src/utils/editor/expression.js
@@ -20,6 +20,9 @@ export function updateSelection(
   editor: any,
   { linesInScope, selection, setSelection, clearSelection }: any
 ) {
+  // lets see what's passed in...
+  console.log(target.innerText);
+
   const location = getTokenLocation(editor.codeMirror, target);
   const tokenText = target.innerText ? target.innerText.trim() : "";
   const cursorPos = target.getBoundingClientRect();
@@ -48,5 +51,7 @@ export function updateSelection(
     return;
     ```

**Comment by sagorika1996** [comment]
Getting this when applying break at `return bar * 4;` 
<br>
![image 3](https://user-images.githubusercontent.com/20087782/29634634-179f76e4-8868-11e7-9e8e-e17bea9e062e.png)

**Comment by SebastianZ** [comment]
With the simple example I also can't reproduce it anymore using Nightly 57.0a1 (2017-08-23), though the more complex one still shows the error.

Sebastian

**Comment by jasonLaster** [comment]
Thanks @SebastianZ, I looked at this w/ gareth and we think the problem is in our HTML parsing [`parse-script-tags`][pst].

Here is a [test](https://gist.github.com/jasonLaster/ed43541e4f59fd6366f15bde2061b054) that we can use to find the crazy edge cases w/ <script> tags. This test has a script w/ json as well as external JS as well.


[pst]:https://github.com/ryanjduffy/parse-script-tags

**Comment by jasonLaster** [comment]
Actually, upon closer examination, it looks like parse-script-tags worked:

```

**Comment by jasonLaster** [comment]
Hmm... this is looking fixed to me. I think we might have fixed this w/ the CLRF work here https://github.com/ryanjduffy/parse-script-tags/pull/4
