### ISSUE TITLE
[SourceMap] Show hint when mapped sources can't be loaded

### ISSUE THREAD

**Issue by SebastianZ** [devtools-html/debugger.html#3707]
This was initially filed as [bug 1228496](https://bugzilla.mozilla.org/show_bug.cgi?id=1228496), which has a test case attached.

If a mapped source is not available on the server, i.e. the "sources" property in the source map refers to a file that doesn't exist, then the Debugger currently shows "Loading…" forever.

It would be much better if the user got a message displayed that the related source could not be loaded. I imagine something like 'Original source could not be loaded.' at the to of the source view.

Sebastian

**Comment by tromey** [comment]
I think this is fixed in M-C.  The toolbox provides a wrapper for the source map service that expands the error message somewhat.  I think there's a test for a missing source in M-C as well.

**Comment by codehag** [comment]
I will investigate this in the panel and see if it is fixed
