### ISSUE TITLE
Add hint about Ctrl+Shift+F to initial page

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#3708]
Use case is having some code in an application one is not extremely familiar with (app is big, or originally written by someone else, or totally external). When opening the debugger, I am presented with "Ctrl+P" to open a JS file, but I do not have any idea where the code is in. 

It would be great if one could search not only in one specific file, but across multiple files for certain strings.

I could add more very specific use cases where I was looking for this feature if it would add value to the discussion.

FWIW, I am using the FF Nightly DevTool version of Debugger.html

**Comment by nyrosmith** [comment]
I think what you are looking for is CTRL+SHIFT+F

**Comment by jnachtigall** [comment]
@nyrosmith Hmm, this does just nothing for me (Windows 10 with todays Firefox Nightly). Also, when opening the Debugger, there's no reference to CTRL+Shift+F, is there some hints/docs about this feature somewhere?

**Comment by nyrosmith** [comment]
Sorry I don't know if it is in Nightly but when running html-debugger on my machine the feature definitly exists but mus be enabled in "settings".

**Comment by nyrosmith** [comment]
You can try it just by cloning this repo, yarn install, yarn run start

**Comment by jnachtigall** [comment]
OK, I trust you that it's in here. So closing and will come eventually :) Would be cool if FF Nightly could just fetch the Debugger current HEAD each day. I don't like the Nightly is out-of-sync here.

**Comment by jnachtigall** [comment]
@nyrosmith Just tried now, this works great, but I suggest a text hint on the first page to be added like already done for Ctrl+P:
![2017-08-18 14_55_30-debugger - nightly](https://user-images.githubusercontent.com/3307404/29459895-ff24a2ba-8425-11e7-8960-e0bf99e08eab.png)

**Comment by jasonLaster** [comment]
Good idea
