### ISSUE TITLE
Blackboxing Source

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#371]
Blackboxing Source indicates that a library or resource is to be ignored by the developer tools.  This is done because developers want to focus on the code they write, not the libraries that they have included.  Often libraries can emit warnings or exceptions which get in the way of a developers workflow in the console and when stepping through a breakpoint paused execution.

Black boxed code should
* be skipped in the step in/over/out commands
* ignore exceptions such that they aren't caught by "break on exceptions"
* ignore warnings in the console
* not allow for breakpoints or pausing on breakpoints in the black boxed code

Here is what is required:

- [ ] automatically recognize scripts that are to be black boxed
- [ ] identify or categorize in the file tree, sources that are black boxed.
- [ ] provide a toggle that allows developers to toggle the black boxed state of the source code
- [ ] identify in the editor when source code is black boxed and what that means

In the future we could also:
- [ ] provide access to the framework black box patterns to allow for customization
- [ ] indicated hidden call stack frames from black boxed code

See Chrome docs: https://developer.chrome.com/devtools/docs/blackboxing

**Comment by jasonLaster** [comment]
I'm closing this issue as we're not planning on working on it in the next couple of sprints. We can re-open it or reference it when we do as the overview is helpful.
