### ISSUE TITLE
[Breakpoints] Another, unwanted, breakpoint is created while holding ctrl + B

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3715]
[Steps to reproduce]:
1.Launch Firefox.
2.Access the https://devtools-html.github.io/debugger-examples/examples/todomvc/ webpage.
3.Open the debugger.
4.Hold the CTRL + B combination on any line of code.

[Expected result]:
An breakpoint is constantly created and removed.

[Actual result]:
Another breakpoint is created on a different line.

![Breakpoint issue.gif](https://shipusercontent.com/9ed2855adb439ff6e8201e5056de2ed4/Breakpoint%20issue.gif)

**Comment by MayankSrivastav** [comment]
Hi, Trying to work on this one. I have reproduced the issue. Seems like some problem with keybindings? Not sure though.
Can you please guide me a little?
Thanks

**Comment by jasonLaster** [comment]
@MayankSrivastav I think this might actually be a debugger server bug. 

The keybinding is in `Editor/index.js` or Editor/Breakpoints

**Comment by jasonLaster** [comment]
re-opening it because i can still repro
