### ISSUE TITLE
Line Numbers Janky upon Horizontal Scroll

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#3717]
In a source tab with a long line of text, quick scrolling is a bit janky:

![numbergutterjank](https://user-images.githubusercontent.com/46655/29474348-f752cff8-8420-11e7-822e-978096905196.gif)

Hopefully they're a way the lines gutter can be fixed (not animated to position) which should prevent this problem

**Comment by codehag** [comment]
Thanks for bringing this up, we should make that stick!

**Comment by lukaszsobek** [comment]
Is that still an Issue?

![horizontal scroll](https://user-images.githubusercontent.com/23530054/33519848-c91854cc-d7af-11e7-8c4a-bd2f93349356.gif)

**Comment by danedavid** [comment]
not leading to any React re-renders, if that matters...
![image](https://user-images.githubusercontent.com/19928280/33798691-34022e14-dd43-11e7-9128-fed27b9f709d.png)

**Comment by darkwing** [comment]
I still see this in current master:

![scrollnumbers](https://user-images.githubusercontent.com/46655/34020835-1134358c-e0fc-11e7-843a-e2075ab56262.gif)

I don't see the issue on this old CM demo (https://codemirror.net/demo/fullscreen.html), so there has to be a way to prevent this problem.

**Comment by darkwing** [comment]
Oddly enough, this only happens in Firefox; in Chrome the line numbers are sticky as they should be.

**Comment by darkwing** [comment]
Sooo...I've just noticed this only happens when opening the debugger in browser at localhost:8000 -- this problem doesn't occur when placed within Firefox DevTools.

Going to close this...but sorta weird that it happens when loaded outside of the bottom devtools bar.

**Comment by jasonLaster** [comment]
Nice.
