### ISSUE TITLE
[Photon] Remove border-bottom from the last child of accordions

### ISSUE THREAD

**Issue by gabrielluong** [devtools-html/debugger.html#3720]
We're looking to be more consistent with how accordions look across all the tools. We will be removing the border-bottom for the last child of an accordion. 

<img width="946" alt="screen shot 2017-08-18 at 1 42 36 pm" src="https://user-images.githubusercontent.com/1190888/29477082-aa3e8036-841b-11e7-9db9-76c85f1b93a5.png">

The CSS should be this:
.accordion div:last-child ._content {
    border-bottom: none;
}

**Comment by codehag** [comment]
Thanks!
