### ISSUE TITLE
Move workers to their own directory

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3725]
It would be great if we could move the workers to their own top level directory. This means moving these directories in `src/utils` to a new `src/workers` directory.

* parser
* pretty-print
* search

#### Benefits

* we can add a README with some advice and tips for working with workers. 
* we can add some worker utils / tests
* we can simplify the utils directory

**Comment by jselmani** [comment]
I'm a student at Seneca College learning open source, and I was hoping to work on this bug for my course as a good start.  If no one else is currently working on it, I'd like to give it a try.  Look forward to hearing back!

PS. In case you're wondering, I'm one of Dave Humphrey's students 👍

**Comment by jasonLaster** [comment]
Hey @jselmani it's yours!

**Comment by jasonLaster** [comment]
stop by our slack w/ questions, but the name of the game here is to move the directories and get `yarn test` passing. Our integration tests too i suppose, but we can check CI for that.

**Comment by jselmani** [comment]
I will certainly join the slack channel and move forward from there.  Thanks for getting back to me so quickly @jasonLaster.

**Comment by jselmani** [comment]
@jasonLaster can we please close this now that it's finished?

**Comment by jasonLaster** [comment]
yep!
