### ISSUE TITLE
[PrettyPrint] Debugger hang after doing pretty print and trying to find on https://www.joinhoney.com/

### ISSUE THREAD

**Issue by mkaply** [devtools-html/debugger.html#3728]
I was trying to debug a problem on https://www.joinhoney.com/ on Nightly.

Right click->Inspect, then Debugger, then selected cdn.honey.com->js->main.2.23.1.js and clicked the pretty print icon.

From there the browser started getting unresponsive. I saw an unresponsive dialog popup, but things seemed to start working. Went to the search form and typed in Firefox and only one character went in and I got the slow script dialog again.

Warning: Unresponsive script
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.
Script: chrome://devtools/content/sour…odemirror/codemirror.bundle.js:1799

From then on, the browser was completely unresponsive, had to kill the script.

This is on today's nightly.

**Comment by jasonLaster** [comment]
Thanks for the report!

**Comment by jasonLaster** [comment]
I just looked into it and I think the problem that we can solve is that it is not clear that we are pretty printing. I think the best thing to do is to optimistically create the pretty printed source w/ the loading field set to true.

This way, we can immediately show the pretty printed source and when the text comes in we can show it.

**Comment by jasonLaster** [comment]
This seems slightly better now, but still not great.

The big difference between the old debugger and new with respect to pretty printing was done in a worker in the debugger server, where as the new ui does it in a worker in the ui context. I dont know if that should matter.

There are some UX issues that i would like to sort out before we look into this further though:

I currently see the browser spin for 10 seconds while it creates the pretty file, then it shows the pretty file but there are some ux issues around navigating between the ugly and pretty versions.

**Comment by jasonLaster** [comment]
I think i misread the issue

cmd+f works as well as i think you can expect. @codehag did some great work in september to optimize it. At the time we stole plenty of good ideas from the old debugger

![](http://g.recordit.co/BY8DKKshYH.gif)

**Comment by jasonLaster** [comment]
I'm closing, but feel free to re-open if you still see the issue
