### ISSUE TITLE
File location is not always revealed in the Tree menu

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3729]
[Steps to reproduce]:
1. Launch Firefox.
2. Access the https://devtools-html.github.io/debugger-examples/examples/todomvc/ webpage.
3. Open the debugger.
4. Open the todos.js file.
5. Close the Tree view.
6. Click the "Reaveal in Tree" option for the todos.js file.
7. Close the Tree view again.
8. Click the "Reveal in Tree" option for the todos.js file.

[Expected result]:
The file's location is revealed each time in the tree menu.

[Actual result]:
It seems that the file location can be revealed only once in the tree menu.

![Screen Shot 2017-08-21 at 9.40.06 AM.png](https://shipusercontent.com/8834d7f13f7de346b589b7c02a7ca508/Screen%20Shot%202017-08-21%20at%209.40.06%20AM.png)

**Comment by darkwing** [comment]
`SHOW_SOURCE` fires each time but `SourceTree`'s `componentWillReceiveProps` doesn't fire on the second attempt, so I'm thinking no state change prevents the signal from getting to `SourceTree`

**Comment by jasonLaster** [comment]
oh - that's really smart. we might need to clear shownSource

https://github.com/devtools-html/debugger.html/blob/master/src/reducers/ui.js#L41

**Comment by jasonLaster** [comment]
```diff
diff --git a/src/actions/ui.js b/src/actions/ui.js
index f6dbd01..41d2ea0 100644
--- a/src/actions/ui.js
+++ b/src/actions/ui.js
@@ -70,6 +70,12 @@ export function showSource(sourceId: string) {
   };
 }
 
+export function clearShownSource() {
+  return {
+    type: "CLEAR_SHOWN_SOURCE"
+  };
+}
+
 export function togglePaneCollapse(position: string, paneCollapsed: boolean) {
   return {
     type: "TOGGLE_PANE",
diff --git a/src/components/PrimaryPanes/SourcesTree.js b/src/components/PrimaryPanes/SourcesTree.js
index 90257a6..cce700c 100644
--- a/src/components/PrimaryPanes/SourcesTree.js
+++ b/src/components/PrimaryPanes/SourcesTree.js
@@ -204,6 +204,7 @@ class SourcesTree extends Component {
   }
 
   renderItem(item, depth, focused, _, expanded, { setExpanded }) {
+    const { clearShownSource } = this.props;
     const arrow = Svg("arrow", {
       className: classnames({
         expanded: expanded,
@@ -212,6 +213,7 @@ class SourcesTree extends Component {
       onClick: e => {
         e.stopPropagation();
         setExpanded(item, !expanded);
+        clearShownSource();
       }
     });
 
diff --git a/src/reducers/ui.js b/src/reducers/ui.js
index 34a79e3..cdafd9c 100644
--- a/src/reducers/ui.js
+++ b/src/reducers/ui.js
@@ -121,6 +121,10 @@ function update(
       return state.set("shownSource", action.sourceUrl);
     }
 
+    case "CLEAR_SHOWN_SOURCE": {
+      return state.set("shownSource");
+    }
+
     case "TOGGLE_PANE": {
       if (action.position == "start") {
         prefs.startPanelCollapsed = action.paneCollapsed;
         ```
