### ISSUE TITLE
Add hover effect to "add new tab" button

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3732]
We have removed the hover pointer from all of our elements, however we should have some indication of what is clickable.

@MayankSrivastav had suggestion of adding the same hover color as we have for our other buttons (ie stepping) and I think this is a great idea

![pasted image at 2017_08_21 10_28 pm](https://user-images.githubusercontent.com/26968615/29530894-3c52ccb6-86a6-11e7-86ec-4509ba6c37be.png)

**Comment by rohanprasad** [comment]
@codehag Working on it. Can you think of other places I could do the same ?

**Comment by codehag** [comment]
Done!
