### ISSUE TITLE
[styling] alignment of text hints for searchs

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3734]
This was brought up by @jnachtigall in #3718
"
I think for readability it would be better if the text was left-aligned centered. That is like:
```
          Ctrl+P to search for sources
          Ctrl+Shift+F to find in files
```
instead of
```
           Ctrl+P to search for sources
             Ctrl+Shift+F to ...
```
"

I would also suggest making `Ctrl+P` and `Ctrl+Shift+F` bold

This is a good starting issue

**Comment by hughugsy** [comment]
Hey, can I work on this? :)

**Comment by codehag** [comment]
@hughugsy its all yours! Let me know if you run into any trouble :)
