### ISSUE TITLE
[Windows] Issues with running jest

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3735]
I was investigating why jest tests are failing on windows with @nyrosmith, Here is what we found:

1) mochi tests are being run when the jest script is run. 
2) several jest snapshots fail, though because of the huge output, we are unable to see which ones are failing. so far we have on log (but it isnt helpful). I have attached it.

Suggested plan: we should run this on another environment; I propose using the windows VM. If someone has a windows machine, it would be great if they could try to reproduce this. If we determine that this is a new problem we can investigate further on our own. Otherwise we should take another look as to what is going on.

**Comment by nyrosmith** [comment]
Now `yarn test` works on my windows PC so I close this
