### ISSUE TITLE
Codemirror hang when trying to open script in debugger

### ISSUE THREAD

**Issue by miketaylr** [devtools-html/debugger.html#3738]
(Found trying to investigate https://github.com/webcompat/web-bugs/issues/9102)

STR:

In Nightly/OSX:

1) go to https://www.zertifikate.commerzbank.de/webforms/mobile/index.html?home/{"site":{"country":1,"language":1,"isoCode":"de-DE"}}
2) open debugger and try to click on app.js from the sources panel

`Script: chrome://devtools/content/sour…odemirror/codemirror.bundle.js:1799`

<img width="820" alt="screen shot 2017-08-21 at 3 55 10 pm" src="https://user-images.githubusercontent.com/67283/29537925-2f45af92-8689-11e7-91f3-dfa4382779f6.png">

Stop Script and Continue do nothing... :(

**Comment by codehag** [comment]
thanks for the bug report!

**Comment by jasonLaster** [comment]
This is now fixed. thanks for being patient @miketaylr 

![](http://g.recordit.co/34ed952qrP.gif)
