### ISSUE TITLE
[Vertical] there’s a gap between the top and bottom section 

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3758]
The left sidebar tabs are floating a bit. And the Editor footer is off by 1px.

```diff

diff --git a/src/components/Editor/Footer.css b/src/components/Editor/Footer.css
index af46c65..3454896 100644
--- a/src/components/Editor/Footer.css
+++ b/src/components/Editor/Footer.css
@@ -3,6 +3,8 @@
   border-top: 1px solid var(--theme-splitter-color);
   position: absolute;
   display: flex;
+
+  /* this should work right? :) */
   bottom: 0;
   left: 0;
   right: 1px;
diff --git a/src/components/PrimaryPanes/Sources.css b/src/components/PrimaryPanes/Sources.css
index 99f9455..c969b4e 100644
--- a/src/components/PrimaryPanes/Sources.css
+++ b/src/components/PrimaryPanes/Sources.css
@@ -95,6 +95,7 @@
   width: 100%;
 }

+/* not sure why there's a gap here...  */
 .source-footer .tab {
   flex: 1;
   justify-content: center;
```

<img src='https://shipusercontent.com/bdf7e8b34dcff22ed71383f063ae17f8/Screen%20Shot%202017-08-23%20at%2010.41.31%20AM.png' title='Screen Shot 2017-08-23 at 10.41.31 AM.png' width=756>

**Comment by pradeepgangwar** [comment]
I am new person here looking to have a start by contributing to some easy bugs and understanding the code base. So, I would be happy to solve this bug.
And help me by explaining more about this bug.

**Comment by jasonLaster** [comment]
@pradeepgangwar great.

**Comment by pradeepgangwar** [comment]
Can you help me by explaining a bit more about the bug?

**Comment by jasonLaster** [comment]
do you see the gap in the sources view tab. the dark tab should touch the command bar, but it is elevated by 4 or so pixels

**Comment by pradeepgangwar** [comment]
@jasonLaster I saw this problem is on smaller screen. When the right side bar comes below.

So, to solve this bug I should edit a file related to this on my local machine and then send a PR. Are there any tests to run before sending a PR?

**Comment by jasonLaster** [comment]
feel free to open the tabs PR first. you can just open the PR. :)

**Comment by jasonLaster** [comment]
we have a `yarn test-all` script that is run before you push :)

**Comment by pradeepgangwar** [comment]
@jasonLaster Raised a PR for tabs. Please review.
