### ISSUE TITLE
Handle failed network connection to debug [chrome]

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#377]
With connections to Firefox there is some timeout logic that gracefully handles the case where the connection fails to find debuggable tabs.   In that case we then display the following message.  I'll be updating this message in a future PR.

![screen shot 2016-07-20 at 3 34 32 pm](https://cloud.githubusercontent.com/assets/2134/17005545/bfa4b0f2-4e8f-11e6-9636-898fd47ab619.png)

However when you turn on debug for Chrome the connection fails and errors out leaving a blank page.  We need to fix this so our default page can contain some additional instructions for both Firefox and Chrome.

Here are the relevant places where the network connection is handled for each client.  It would probably be best to have a shared solution but I might just implement something that works for now.

## Firefox

https://github.com/jlongster/debugger.html/blob/8f84c9b7341bd0bfe734368066d1bc9b86a5eb46/public/js/clients/firefox.js#L61-L67

## Chrome

https://github.com/jlongster/debugger.html/blob/d6715edc31cb3bf2e5d9078124aebc9edae4b256/public/js/clients/chrome.js#L49

**Comment by jasonLaster** [comment]
yup - this is probably in `networkRequest` and in the [development-server](https://github.com/jlongster/debugger.html/blob/master/bin/development-server.js#L25-L37) `httpGet` function.

**Comment by clarkbw** [comment]
@jasonLaster I believe this issue has gone stale with recent work and the new landing page. amirite?

**Comment by jasonLaster** [comment]
Should be done actually

**Comment by clarkbw** [comment]
Closing
