### ISSUE TITLE
Use Babel to stop adding displayName for react classes

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3771]
It would be neat if we could stop adding displayName to our react components.

https://github.com/Krizzu/babel-plugin-transform-react-class-displayname

**Comment by nyrosmith** [comment]
I'll take this one @jasonLaster

**Comment by codehag** [comment]
Correct me if i'm wrong, but I was under the impression that babel does this automatically? and that we were using displayName because we were not using webpack? https://github.com/babel/babel/issues/1331

**Comment by nyrosmith** [comment]
Really unsure about this rn. Will investigate...

**Comment by codehag** [comment]
The library is also a bit young / underused -- there might be an alternative solution that is better tested. I agree that it would be nice to stop adding displayName unless we need a custom displayName.

**Comment by jasonLaster** [comment]
Oh, maybe it does... either way, lets stop using displayName :)

**Comment by codehag** [comment]
I can confirm that JSX does this automatically: https://facebook.github.io/react/docs/react-component.html#displayname

perhaps we can attach this to the jsx issue, and use this issue to track the components that have already been converted?

**Comment by codehag** [comment]
on second thought, lets make this a tracking issue for this task on its own. It is a good starting issue
