### ISSUE TITLE
[Console] source links don't link to prettified source

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#3777]
See http://recordit.co/zm6FMcPu9w

### STR

1. Open console on bbc.com/news
2. Click source for formatted log (was `init.js:1:11836` for me)
3. Prettify `init.js` in Debugger
4. Back in Console, click link `init.js:1:11836` again

#### Expected

Debugger opens with the right position in prettified source

#### Actual

Debugger opens the old un-prettified source

**Comment by digitarald** [comment]
Links to event handlers from the Inspector are also affected by this.

**Comment by tromey** [comment]
The bug here is that other users of the source mapping service aren't notified when a source is prettified.  I plan to handle this in https://github.com/devtools-html/devtools-core/issues/352 - it's just been pushed down the queue a bit.

**Comment by jasonLaster** [comment]
@tromey interesting. I'm not sure if we're calling `applySourceMap` for pretty printed sources. 

Context: the new debugger has different tabs for pretty and raw sources. I believe the old debugger treated a pretty printed source as the same source. We made this decision because we thought it was nice in some cases to see both versions.

**Comment by digitarald** [comment]
@tromey can you confirm that the source map service has all you need and that we should we file the bug in bugzilla to have inspector & console updated?

**Comment by tromey** [comment]
I think the needed work should be done in the toolbox, so I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1397714

I don't think there's anything to do in the debugger, so I think this particular bug can be closed now.

**Comment by jasonLaster** [comment]
I'm re-opening it so that we can make sure it gets done:

here's a similar bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1433820

 http://bayanbox.ir/view/1345913938885179254/prettify.webm

**Comment by digitarald** [comment]
WorksForMe now, Console link correctly updates to `:formatted:`
