### ISSUE TITLE
Add debuggable target instructions to the default page

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#378]
Currently when you have no debuggable targets available (Chrome or Firefox) we display this message to help you get setup with Node.

![screen shot 2016-07-20 at 3 34 32 pm](https://cloud.githubusercontent.com/assets/2134/17005660/4a2882f8-4e90-11e6-956a-8cae422b82d7.png)

In #352 we're changing the README and the way the process works for getting started such that it will be necessary to have instructions on this default page.  Users will be encouraged to `npm start` and `open http://localhost:8000/`and from there might be given further "quick start" instructions to getting Firefox or Chrome up and running.  Beyond the quick start instructions we will need to link to the correct locations for the CONTRIBUTING doc and the documentation describing how to start Chrome and Firefox with remote debugging turned on.

**Comment by jasonLaster** [comment]
@jbhoosreddy - this could be a good one too

**Comment by clarkbw** [comment]
This wasn't exactly the right thing to do but this is what I aimed for:

* Always show Firefox + Chrome sections
 * Include quick instructions for starting each
  * Include links to further instructions in the docs
* Update the node section to be similar

Here's the quick mockup I made by commenting out lots of code:

![screen shot 2016-07-22 at 12 47 45 pm](https://cloud.githubusercontent.com/assets/2134/17069282/b337524e-500a-11e6-89b5-e8d802e55a17.png)

**Comment by jlongster** [comment]
Personally I think those commands could be overwhelming here (if the user did something wrong that's unrelated, that's not a great first thing to show). I'd rather keep the form of a statement like "You may be looking too..." and "connect to firefox" is a link that display the command to run Firefox or something (and could also link to the docs).

**Comment by clarkbw** [comment]
> "You may be looking too..." and "connect to firefox"

Agreed, I didn't like the commands approach, you can see it becomes messy and then we have multiple places where these commands live.

**Comment by jbhoosreddy** [comment]
One thing we could do is have a GitHub style "Copy to clipboard" button which copies the appropriate command to clipboard and can be executed by the users directly.

**Comment by clarkbw** [comment]
> GitHub style "Copy to clipboard" button

I like it!  Could keep it short and offer both OS options while still linking to the docs for more information.

**Comment by clarkbw** [comment]
Fixed in #471
