### ISSUE TITLE
[Project Search] File path does not appear in nightly

### ISSUE THREAD

**Issue by bomsy** [devtools-html/debugger.html#3782]
The file paths for the results do not show up in nightly

![image](https://user-images.githubusercontent.com/792924/29727932-d012e466-89cd-11e7-9a77-fe03e8943dda.png)

**Comment by codehag** [comment]
thanks for reporting it bomsy!

**Comment by jasonLaster** [comment]
I was able to reproduce when debugging the debugger.
Maybe this is a problem w/ original files:

<img src='https://shipusercontent.com/6320cf5ed8e5fbdf08b5779450d55091/Screen%20Shot%202017-08-31%20at%2011.35.28%20AM.png' title='Screen Shot 2017-08-31 at 11.35.28 AM.png' width=597>

**Comment by jasonLaster** [comment]
this is s 

```
diff --git a/src/utils/sources-tree/tests/utils.spec.js b/src/utils/sources-tree/tests/utils.spec.js
index a401f5d..67a7a5b 100644
--- a/src/utils/sources-tree/tests/utils.spec.js
+++ b/src/utils/sources-tree/tests/utils.spec.js
@@ -75,6 +75,12 @@ describe("sources tree", () => {
         relPath
       );
     });
+
+    it("supports other schemes", () => {
+      expect(getRelativePath("webpack:///Users/jlaster/src/mozilla/debugger.html/node_modules/devtools-reps/src/reps/date-time.js")).toBe(
+        // not sure what we want in here
+      );
+    })
   });
```

**Comment by bomsy** [comment]
i'm thinking we should fall back to showing the full path, when we find an unknown scheme
