### ISSUE TITLE
[ProjectSearch] Improve Text Search -> Source Transition

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#3787]
I'd like to make a few suggestions re: text search

1.  When clicking on a line result in the search results, it would be nice if the line or keyword instance would be highlighted when the source is opened.

2.  Stealing from Atom (and probably lots of other text editors), it would be sweet if the search results opened in their own source tab and then persisted as a background tab when clicking on results.  "Oh crap, that's not what I wanted, let me see the results list again and try another item".

**Comment by bomsy** [comment]
@darkwing totally agree. I think we have a flash highlight on the line atm, but It seems to be a really quick one and the user may not really see it. it would be really useful to have a more lasting highlight on the line and/or the keyword.

2. We have this in the works! Atm tabs are tightly coupled to sources making it difficult to create tabs that are not source related tabs. I'm working on a PR to decouple tabs from sources, enabling us to be open results as it's own tab.

**Comment by jasonLaster** [comment]
closing bc this covers the selection #3829. Tabs is separate

**Comment by nyrosmith** [comment]
@jasonLaster  I think you forgot to push the "close" button :-)

**Comment by jasonLaster** [comment]
Do you mean the separate tab? That *should* be tracked in another issue.
