### ISSUE TITLE
[CallStack] show react components

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3792]
Create React App has begun showing Error Stacks with component information. The benefit of this UI is that it shows users the component tree so they can see where something went wrong.

It would be great if we could show the component names in the call stack. In the screenshot below I include the react render frames, but those might not be useful

@sebmarkbage has a spec for custom stack frames [here](https://gist.github.com/sebmarkbage/bdefa100f19345229d526d0fdd22830f).

---

### Component Call Stack

![Screen Shot 2017-08-27 at 10.34.23 AM.png](https://shipusercontent.com/2044bfcfa7435966b4e83d447d7209c8/Screen%20Shot%202017-08-27%20at%2010.34.23%20AM.png)

### Create React App 

![Screen Shot 2017-08-27 at 10.00.42 AM.png](https://shipusercontent.com/3987fa490eba7c76175f8f5b5093dbee/Screen%20Shot%202017-08-27%20at%2010.00.42%20AM.png)

![](https://video.twimg.com/tweet_video/DIH2113UAAQ3SDA.mp4)

**Comment by jasonLaster** [comment]
cc @gaearon @bvaughn

**Comment by gaearon** [comment]
To be clear we haven't enabled this in React yet but I'm working on it.

**Comment by jasonLaster** [comment]
moving this to the icebox. we can re-evaluate in the next release cycle

**Comment by jasonLaster** [comment]
Here's an initial re-write of the components pane, with the goals of

- separating out components from extra
- adding children
- making it behave like a tree (WIP - we should use the Tree component)

https://github.com/jasonLaster/debugger.html/tree/components

**Comment by jasonLaster** [comment]
here is a branch for the component tree - https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:component-tree?expand=1

**Comment by jasonLaster** [comment]
Moving to the icebox
