### ISSUE TITLE
Recurring issues with properties file updates

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#3795]
The PR #3713 landed with a wrong localization note in the properties file. 

`# LOCALIZATION NOTE (copy)`

`copy` should match the name of the localization string. 

` # LOCALIZATION NOTE (copySource)`

Issues with the properties file are a recurring friction point we have when dropping a new bundle of the debugger in mozilla-central. Sorry to nag you about that, but catching this kind of things when trying to update the bundle is a bit too late, not to mention frustrating :)

The debugger properties file is used by the localization teams, and therefore need to follow their rules.

You can find some resources about localization guidelines here: https://developer.mozilla.org/en/docs/Mozilla/Localization but honestly it's hard to remember all the rules when you are not doing this regularly, so maybe ping @flodolo (or me but I might miss a lot of stuff) when a PR touches the properties file.

cc @codehag @jasonLaster : any idea on how to enforce a better review policy for the debugger properties file?

**Comment by flodolo** [comment]
Some projects are using the CODEOWNER file to ping me automatically
https://github.com/mozilla/testpilot/blob/master/CODEOWNERS

Downsides:
* Right now, it's just me
* It might get a bit confusing, since I'm reviewing string changes, not looking at code, and the PR might look reviewed 
* I'm afraid you need to add me as contributor to the repo (but I'm not completely sure about this).

**Comment by flodolo** [comment]
This might be a better doc to look at
https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices#Choose_good_key_IDs

Also note something that debugger is not doing: it would be great to have keys called "FOO.label and FOO.accesskey", vs "FOO and FOO.accesskey".

**Comment by juliandescottes** [comment]
Quickly discussed about this with @jasonLaster and we'll add @flodolo to CODEOWNERS for the properties file.

**Comment by jasonLaster** [comment]
@flodolo I just added you as a collaborator. I think you'll have to accept before you're included

**Comment by flodolo** [comment]
> @flodolo I just added you as a collaborator. I think you'll have to accept before you're included

Done, thanks.
