### ISSUE TITLE
[workers] get worker list

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3814]
Relevant links:
* http://searchfox.org/mozilla-central/source/devtools/server/actors/child-process.js#119
* http://searchfox.org/mozilla-central/search?q=workerListChanged&path=
* see about:debugging examples for the toolbox link

Connect the event (useful when the list of workers changes)
```diff
diff --git a/src/client/firefox/events.js b/src/client/firefox/events.js
index ff8748b..05f9bb1 100644
--- a/src/client/firefox/events.js
+++ b/src/client/firefox/events.js
@@ -65,10 +65,15 @@ function newSource(_: "newSource", { source }: SourcePacket) {
   }
 }

+function workerListChanged() {
+  debugger;
+}
+
 const clientEvents = {
   paused,
   resumed,
-  newSource
+  newSource,
+  workerListChanged
 };

 export { setupEvents, clientEvents };
 ```
 
 Here is a diff for adding a debuggee reducer, and getting the workers:
 https://gist.github.com/jasonLaster/2b60af0711d1e768314df12d8a24726a

**Comment by nyrosmith** [comment]
Working on it!
