### ISSUE TITLE
[Console] Error links 404

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3816]
I believe the webpack links here 404, lets try and get a small test case:

![Screen Shot 2017-08-29 at 4.42.40 PM.png](https://shipusercontent.com/388e7e64a223517f50fd818cd7988306/Screen%20Shot%202017-08-29%20at%204.42.40%20PM.png)

**Comment by palnes** [comment]
A repository for reproducing can be found at https://github.com/palnes/debugger3816 :) Hope that helps!

**Comment by jasonLaster** [comment]
Thanks @palnes! That is a huge help

**Comment by jasonLaster** [comment]
@tromey would you be interested in taking a look. It might be related to the source map service not seeing the source.

**Comment by tromey** [comment]
I see:
![image](https://user-images.githubusercontent.com/1557670/30650218-93cb3d70-9ddf-11e7-8b0b-edf55a522e9f.png)
First step is maybe to figure out why the error message is so bad.

**Comment by tromey** [comment]
`new URL` is throwing and giving the bad message, but only because we're giving it an empty string.

**Comment by tromey** [comment]
Ok, found that, and the links in the stack trace seem to work.  But, the original error location is weird:

![image](https://user-images.githubusercontent.com/1557670/30654367-e0b1a998-9dea-11e7-931e-4d2929c42b55.png)

What is up with that.

**Comment by tromey** [comment]
That's `main.js line 4081 > eval:46:13` for those of us who didn't memorize the ascii table in hex.

**Comment by tromey** [comment]
I think I'm going to leave this one with just the source-map fix, the weird mangling of the location is something else.

**Comment by jasonLaster** [comment]
@tromey what's the status here?

**Comment by tromey** [comment]
The devtools-source-map fix was https://github.com/devtools-html/devtools-core/pull/700

I'm not ready to do a new release of that package, though, because I have a number of changes I want to bundle together.

**Comment by jasonLaster** [comment]
This looks fixed

![](http://g.recordit.co/3xkUiSeuSS.gif)
