### ISSUE TITLE
[Preview] ignore `=` token

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3824]
STR:

1. pause in todo-view.js line 81
2. mouse over the `=` on the line

Expected: nothing should happen
Actual: see the whole expression highlighted

The fix is probably to blacklist `=`, but it would be nice to poke around and see what else we should exclude.
```diff
diff --git a/src/utils/editor/expression.js b/src/utils/editor/expression.js
index 5532848..1defda4 100644
--- a/src/utils/editor/expression.js
+++ b/src/utils/editor/expression.js
@@ -36,7 +36,7 @@ export function updatePreview(
     }
   }

-  const invalidToken = tokenText === "" || tokenText.match(/[(){},.;\s]/);
+  const invalidToken = tokenText === "" || tokenText.match(/[(){},.;=\s]/);
   const invalidTarget =
     (target.parentElement &&
       !target.parentElement.closest(".CodeMirror-line")) ||
```

So, what's the harm of highlighting the whole expression? Well, glad you asked:

1. it might do the entire assignment which is mutating state. Yuck
2. it's distracting (it's going to return undefined) and throw a popup in your face

So, where's the other logic. Preview is hard yo:

1. look in Editor/Preview/index for the hover event
2. look in Actions/ast for setPreview

This code is awesome. It's really neat to see how it works :dancer:

![Screen Shot 2017-08-30 at 3.45.53 PM.png](https://shipusercontent.com/ef4eea610ce89462b356c554e0718cd1/Screen%20Shot%202017-08-30%20at%203.45.53%20PM.png)

**Comment by Fischer-L** [comment]
@jasonLaster 
Also found the similar tokens as "<", ">", "+", "-", "*", "/" produce the same issue. 
![3824](https://user-images.githubusercontent.com/5627487/30240709-20d75d74-95a8-11e7-914f-fa4412be33ad.gif)

Tried to filter out these tokens as well as below.
![3824_solution](https://user-images.githubusercontent.com/5627487/30240711-292c1b5e-95a8-11e7-8d42-958ec55beda7.gif)

Probably we should filter out  "<", ">", "+", "-", "*", "/" too. How do you think? If ok, i am going to submit the patch, thanks.

**Comment by jasonLaster** [comment]
Yes! Go for it. We have an issue for = but they're all valid.

**Comment by jasonLaster** [comment]
The issue for = has some notes

**Comment by Fischer-L** [comment]
@jasonLaster 
I wasn't able to push to my github nor to pass `yarn run test-all` command.
Just keep encountering the below error (even on the pure master branch) and do `yarn install` didn't help either. Did I miss something in my environment? Thank you.
```
yarn run v0.27.5
$ yarn test; yarn lint; yarn flow
TypeError: projects.map is not a function
    at Object.<anonymous> (/Users/fischer/Projects/debugger.html/node_modules/jest-cli/build/cli/runCLI.js:112:28)
    at Generator.next (<anonymous>)
    at step (/Users/fischer/Projects/debugger.html/node_modules/jest-cli/build/cli/runCLI.js:1:260)
    at /Users/fischer/Projects/debugger.html/node_modules/jest-cli/build/cli/runCLI.js:1:490
    at Object.<anonymous> (/Users/fischer/Projects/debugger.html/node_modules/jest-cli/build/cli/runCLI.js:1:171)
    at Object.module.exports [as runCLI] (/Users/fischer/Projects/debugger.html/node_modules/jest-cli/build/cli/runCLI.js:139:50)
    at Object.run (/Users/fischer/Projects/debugger.html/node_modules/devtools-launchpad/node_modules/jest-cli/build/cli/index.js:42:17)
    at Object.<anonymous> (/Users/fischer/Projects/debugger.html/node_modules/devtools-launchpad/node_modules/jest-cli/bin/jest.js:16:25)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
error Command failed with exit code 1.
```

**Comment by nyrosmith** [comment]
@Fischer-L push with --no-verify flag
That's a known issue

**Comment by jasonLaster** [comment]
Upgrade to yarn 0.28.4

**Comment by jasonLaster** [comment]
@hugsy is on it

**Comment by Fischer-L** [comment]
@nyrosmith 
> push with --no-verify flag
Thanks for the info

@jasonLaster 
> Upgrade to yarn 0.28.4
Thanks, upgrading yarn and not seeing the error of "TypeError: projects.map is not a function" with `yarn test`.
However, another issue about eslint came: `yarn lint` would bring error of 
```
ESLint: 4.6.1.
ESLint couldn't find the plugin "eslint-plugin-mozilla".
``` 
Then I installed "eslint-plugin-mozilla@latest" but it would bring this error:
```
$ run-p lint-css lint-js lint-md
/bin/sh: run-p: command not found
error Command failed with exit code 127.
```
Since the `yarn test` was passed at least and the patch is not big, will submit the patch first.
