### ISSUE TITLE
Style Welcome Box Shortcuts

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3830]
It would be nice if we could do three things here

* align the shortcuts
* drop the +
* add function search cmd+shift+o

### Ours
![Screen Shot 2017-08-30 at 6.31.22 PM.png](https://shipusercontent.com/b713781a2bff06f33f753fefa41d0271/Screen%20Shot%202017-08-30%20at%206.31.22%20PM.png)

### Chromes
![Screen Shot 2017-08-30 at 6.30.58 PM.png](https://shipusercontent.com/52fb3aebab6010dff4eb03231e6b443f/Screen%20Shot%202017-08-30%20at%206.30.58%20PM.png)

Here's a sketch of what the solution would look like

```diff
diff --git a/src/components/WelcomeBox.js b/src/components/WelcomeBox.js
index 9f840ba..65e8eed 100644
--- a/src/components/WelcomeBox.js
+++ b/src/components/WelcomeBox.js
@@ -38,6 +38,17 @@ class WelcomeBox extends Component {
     );
   }

+  renderShortcut() {
+    return (
+      <div>
+        <b>
+          {keyCombinationOne}
+        </b>
+        {searchSourcesLabel}
+      </div>
+    )
+  }
+
   render() {
     const keyCombinationOne = formatKeyShortcut(
       L10N.getStr("sources.search.key2")
@@ -52,6 +63,7 @@ class WelcomeBox extends Component {

     const searchProjectLabelComp = (
       <div>
+        {/*  we'll need to style this some more */}
         <b>
           {keyCombinationTwo}
         </b>
@@ -59,20 +71,12 @@ class WelcomeBox extends Component {
       </div>
     );

-    const searchSourcesLabelComp = (
-      <div>
-        <b>
-          {keyCombinationOne}
-        </b>
-        {searchSourcesLabel}
-      </div>
-    );
-
+    // perhaps we want to extract this to a new render function
     return (
       <div className="welcomebox">
         <div className="alignlabel">
           {searchSourcesLabelComp}
-          {isEnabled("searchNav") ? searchProjectLabelComp : null}
+          {isEnabled("searchNav") ? this.renderShortcut("project") : null}
           {this.renderToggleButton()}
         </div>
```

**Comment by pradeepgangwar** [comment]
@jasonLaster I looked into the issue and tried to understand the code behind it. I was able to modify the looks of text but I am not able to rempve "+" sign from shift. 

For changing the looks I modified **WelcomeBox.css** and **WelcomeBox.js**

![screenshot-2017-8-31 debugger](https://user-images.githubusercontent.com/21259802/29925356-b7798180-8e7d-11e7-9c89-173620a752ae.png)

Can you help me in removing + sign from Shift ? I did the following changes in **utils/text.js*.

![change](https://user-images.githubusercontent.com/21259802/29925649-970484a8-8e7e-11e7-968c-d53a8176043f.png)

**Comment by jasonLaster** [comment]
Sure. Can you open the PR and we can work there?

**Comment by pradeepgangwar** [comment]
@jasonLaster  Created PR #3835 . Please look at it.

**Comment by jnachtigall** [comment]
Well, to be honest (rethinking it) it should be the other way around imho: First what you can do (action), then how to do it (shortcut). That is, like VSCode is doing it:
![2017-09-05 14_33_34-visual studio code](https://user-images.githubusercontent.com/3307404/30061409-81082a20-9247-11e7-92d9-4861b77c8c67.png)

Well, most menus are also like this, e.g. Copy___Ctrl_+_C and so on. Not a big thing, maybe nitpicking, maybe even bikeshedding...

Secondly, I think it would be a could idea if the text was clickable and would cause the action to happen. When I switch to the debugger tab using the mouse (in Firefox DevTools) it would be faster to just click on one of the actions. Either way people might do this. And it would be consistent with the top left "Ctrl+P to search" which is also clickable already.

**Comment by jasonLaster** [comment]
Hmm, I'n neutral on the `+`. Making them clickable is a great idea

**Comment by nyrosmith** [comment]
@jasonLaster I think this can be closed because the PR is merged and you created a new issue for clickable actions
