### ISSUE TITLE
[Preview] the debug line should not flash

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3831]
We have a cute bug where we flash the debug line when we hover on an expression we're evaluating.

![](http://g.recordit.co/FIkTetDWsG.gif)

#### Code Sketch

To fix this we'll want to note what the current command is. Perhaps we call it "preview". We'll then want to pass the command to debug line and tell it not to update in that case.

```diff
diff --git a/src/components/Editor/DebugLine.js b/src/components/Editor/DebugLine.js
index 3cb2c83..12c91f5 100644
--- a/src/components/Editor/DebugLine.js
+++ b/src/components/Editor/DebugLine.js
@@ -43,6 +43,12 @@ export default class DebugLine extends Component {
     this.clearDebugLine(this.props.selectedFrame, this.props.editor);
   }

+  shouldComponentUpdate(nextProps) {
+    if (nextProps.command == "preview") {
+      return false;
+    }
+  }
+
   setDebugLine(
     selectedFrame: Object,
     selectedLocation: Object,
diff --git a/src/components/Editor/index.js b/src/components/Editor/index.js
index 1bcffa3..afe445d 100644
--- a/src/components/Editor/index.js
+++ b/src/components/Editor/index.js
@@ -634,7 +634,7 @@ class Editor extends PureComponent {

   renderDebugLine() {
     const { editor } = this.state;
-    const { selectedLocation, selectedFrame } = this.props;
+    const { selectedLocation, selectedFrame,command } = this.props;
     if (
       !editor ||
       !selectedLocation ||
@@ -650,6 +650,7 @@ class Editor extends PureComponent {
         editor={editor}
         selectedFrame={selectedFrame}
         selectedLocation={selectedLocation}
+        command={command}
       />
     );
   }
@@ -744,7 +745,8 @@ export default connect(
       coverageOn: getCoverageEnabled(state),
       query: getFileSearchQueryState(state),
       searchModifiers: getFileSearchModifierState(state),
-      linesInScope: getInScopeLines(state)
+      linesInScope: getInScopeLines(state),
+      command: getCommand(state),
     };
   },
   dispatch => bindActionCreators(actions, dispatch)
diff --git a/src/reducers/pause.js b/src/reducers/pause.js
index 9615ead..049f1ed 100644
--- a/src/reducers/pause.js
+++ b/src/reducers/pause.js
@@ -143,6 +143,13 @@ function update(state: PauseState = State(), action: Action): PauseState {
     case "COMMAND":
       return { ...state, command: action.value.type };

+    case "SET_PREVIEW": {
+      if (action.status == "start") {
+        return { ...state, command: "preview" };
+      } else {
+        return { ...state, command: "" };
+      }
+    }
     case "CLEAR_COMMAND":
       return { ...state, command: "" };
```

**Comment by Fischer-L** [comment]
@jasonLaster Thanks for a clear code sketch. Are you fixing this issue? I am happy to help out here if you don't  mind : )
After browsing the code base I guess I kind of know what we want to do here. 
  - Basically when the pause reducer sees an async "SET_PREVIEW" action[1] is starting, it should mark command state as "preview".
  - Then the Editor component should pass this command state to the DebugLine component's as a prop while rendering
  - The DebugLine now will know no need to update when seeing a "preview" command

BTW could you provide the STR? I tried to pause on some script but didn't see the flash while previewing. I tested on FF56.0b6 and the latest debugger on a localhost:8000 page

[1] https://github.com/devtools-html/debugger.html/blob/a3e5bff53d1c67d02eb3c4f91391f2996169dcf8/src/actions/types.js#L52

Thank you

**Comment by jasonLaster** [comment]
@Fischer-L it's yours. I like writing the code sketches so that anyone can pick it up :)

Also, I think you've got a great understanding of the problem.

In terms of the STR, try getting the project setup: see "getting setup", and debugging the todomvc example, w/ a breakpoint on line 34 of todo-view.js. 

I paused on line 34, and did some mousing over of variables. Happy to chat more on slack

**Comment by Fischer-L** [comment]
![debugger_local_try](https://user-images.githubusercontent.com/5627487/30067820-7cb984b8-928e-11e7-9379-a12a1173f595.gif)

@jasonLaster Thanks for the reply. Please see the gif. Tried the todo mvc example. I paused on L33 (L34 as well), but still didn't see the flashing debugger line. My debugger project code base should be new, just pulled 2 days ago. I would like to solve this issue so the 1st thing I guess is to reproduce it otherwise it would be like we are submitting a patch without care. I will go to my friend to see if could reproduce the issue.

**Comment by jasonLaster** [comment]
Hi @Fischer-L I thought i was losing my mind, i couldn't repro it either.

It turns out you need to pause in initialize and then select another frame:

1. click View in the call stack
2. select the top frame of the group
3. mouse over delegateevents

Note, i'm no longer sue if my fix will work. Try logging the render calls in DebugLine to see what's triggering the update first :)

![](http://g.recordit.co/khAf85gZyK.gif)

**Comment by Fischer-L** [comment]
![no_flash_debug_line_in_sub_frame](https://user-images.githubusercontent.com/5627487/30238991-291114ee-9585-11e7-906a-c23a3b4299c5.gif)
@jasonLaster Hi still could not see the flash debugger line in the current stack frame or sub stack frames. Just rebased on Master and my tip is at 09438b25f682a875b4d41170f9161efedd113730 now.

**Comment by jasonLaster** [comment]
haha - okay. That's pretty strange. Thanks for investigating...
