### ISSUE TITLE
Evaluate Sequential await Usage

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#3834]
I noticed debugger.html uses lots of `await`(yay!), sometimes back to back, a la:

```js
await dispatch(addSearchQuery(query));
await dispatch(loadAllSources());
``` 

Google's Async functions doc (https://developers.google.com/web/fundamentals/getting-started/primers/async-functions) makes a really good point about optimizing and parallelism with `await` usage:

```js
async function parallel() {
  const wait1 = wait(500); // Start a 500ms timer asynchronously…
  const wait2 = wait(500); // …meaning this timer happens in parallel.
  await wait1; // Wait 500ms for the first timer…
  await wait2; // …by which time this timer has already finished.
  return "done!";
}
```

We should evaluate where we're using awaits and see what we can do to ensure we're not being too sequential.

**Comment by jasonLaster** [comment]
That's a nice idea.

One thing to keep in mind is that sometimes the second action is dependent on the first. This is often the case w/ loading text and getting source symbols, which empty lines uses

**Comment by darkwing** [comment]
Yep, thus the evaluation.  Most cases probably do rely on each other.

**Comment by jasonLaster** [comment]
closing this issue, but feel free to propose some changes. I like squeezing some perf out of the debugger.
