### ISSUE TITLE
Source Tabs and Gutter Column Don't Line Up

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#3846]
Hard to see in the light theme but pronounced in the dark theme:

<img width="127" alt="lineuplight" src="https://user-images.githubusercontent.com/46655/29952015-2d9f42f6-8e8c-11e7-9f10-a225e10ce68a.png">

<img width="264" alt="lineupdark" src="https://user-images.githubusercontent.com/46655/29952018-3047cc6c-8e8c-11e7-8818-4e3743148632.png">

**Comment by jasonLaster** [comment]
This fix can be made in here: https://github.com/rohanprasad/debugger.html/blob/search-store-mapping/src/components/Editor/Tabs.css#L1

**Comment by Ronsho** [comment]
will take it!

**Comment by diessica** [comment]
Is anyone on it? I'd like to take this.

**Comment by bomsy** [comment]
@Ronsho are you still on this?

**Comment by jasonLaster** [comment]
@diessica it's yours

**Comment by pradeepgangwar** [comment]
@jasonLaster Can i try resolving this issue, if @diessica is busy with something else.

**Comment by jasonLaster** [comment]
@pradeepgangwar go for it

**Comment by jasonLaster** [comment]
here are some nottes

https://github.com/devtools-html/debugger.html/blob/master/src/utils/editor/source-documents.js#L41

it could literally do document.querySelector(‘tab-foo’).style.marginLeft = whatever the gutter is…


we could also update this:

https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-source-editor/src/utils.js#L47-L50

**Comment by pradeepgangwar** [comment]
@jasonLaster If I understand bug correctly, then it is talking of difference between line column and tab. 
But I ran the debugger today and found that it was not like that. I think either this bug has been resolved or i have misunderstood it.

![screenshot-2017-10-6 debugger](https://user-images.githubusercontent.com/21259802/31294049-17c1f2b2-aaf7-11e7-9d7d-ed956b5f57c0.png)

**Comment by jasonLaster** [comment]
try looking at files w/ more than 100 lines of code

**Comment by pradeepgangwar** [comment]
Yes, I got it there is some issue with it.
