### ISSUE TITLE
[Expressions] Duplication Error

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#3862]
Steps to reproduce:

1.  Create a Watch Expression called "Yes"
2.  Create a Watch Expression called "No"
3.  Create a Watch Expression called "Yes"

Errors kick off, more when you refresh the page.  Sample:

TypeError: this.state.editor is null[Learn More]  debugger.js:108071:5
TypeError: editor is null

**Comment by jasonLaster** [comment]
oh nice. We have several expression issues which might be related.

**Comment by nyrosmith** [comment]
@darkwing  can you still reproduce it?
I just tried and this behavior doesn't occur on my machine (current master)
![expressions](https://user-images.githubusercontent.com/2511026/30036447-afa3dfb2-91b3-11e7-985c-f5ab5352d8c1.gif)

**Comment by jasonLaster** [comment]
fixed by #4116
