### ISSUE TITLE
Stop using React

### ISSUE THREAD

**Issue by Riamse** [devtools-html/debugger.html#3864]
React is licensed under a [strong patent retaliation](https://medium.com/@raulk/if-youre-a-startup-you-should-not-use-react-reflecting-on-the-bsd-patents-license-b049d4a67dd2) license. Devtools uses React. Software licensed as such is such a threat to freedom that it would be counterproductive to promote its use in this way. We should migrate away from React as fast as humanly possible.

**Comment by juliandescottes** [comment]
The discussion around Mozilla & DevTools using React is happening on the mozilla governance mailing list: https://groups.google.com/forum/#!topic/mozilla.governance/-82KAvA9rKM

We should keep all the discussion in a single thread so I advise to close this issue and continue in the mailing list. Thanks.

**Comment by jasonLaster** [comment]
closing as the discussion is happening else where
