### ISSUE TITLE
Audit button cursors

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3872]
@darkwing found that our "search sources" and "find in files" buttons used the text cursor instead of the default in #3858.

I checked and several other of our clickable buttons fall back on cursor text.

- [ ] tabs
- [ ] accordion headers

There are probably others as well. Lets go through the UI and make sure that we've converted these hover cursors to the default cursor.

**Comment by pradeepgangwar** [comment]
I think in this issue we are talking about the cursor style that i observed when I hover over to **Sources** and  **Outline** Tab. Cursor changed to - (like it is in the) text edit mode. 

And i think we don't want it. Am i right?
