### ISSUE TITLE
Syntax highlighting is crazy for some JSX construct

### ISSUE THREAD

**Issue by julienw** [devtools-html/debugger.html#3878]
Here is the code that makes the syntax highlighting crazy:

```javascript
  render() {
    this._scheduleDraw();
    return (
      <div className={this.props.className}>
        <canvas
          className={classNames(
            `${this.props.className}Canvas`,
            'threadStackGraphCanvas'
          )}
          ref={ref => (this._canvas = ref)}
          onMouseUp={this._onMouseUp}
        />
      </div>
    );
  }
```

See how it renders:
![capture d ecran de 2017-09-04 17-59-00](https://user-images.githubusercontent.com/454175/30033296-c49c05e8-919a-11e7-85ed-fe135275e147.png)

**Comment by jasonLaster** [comment]
It would be nice to see what is available w/ codemirror, maybe others have found a good solution?

**Comment by wldcordeiro** [comment]
Maybe CodeMirror's latest version has fixed it? I don't see a note in the changelog about the JSX mode specifically. Also maybe worth reporting to [them](https://github.com/codemirror/CodeMirror) if it does seem broken.

**Comment by julienw** [comment]
It was easy to actually try:
![screenshot-2017-10-30 codemirror](https://user-images.githubusercontent.com/454175/32163532-e2344aaa-bd5c-11e7-9958-dbd07fa49617.png)

Yep, it looks like Code Mirror's newer versions actually fix this.

**Comment by julienw** [comment]
Though some of the colors are still weird: see the angle bracket in the ref's arrow function, or `onMouseUp` not having the right color, or the closing `div` tag.

But it's not as broken as it was.

**Comment by julienw** [comment]
I added this example in this issue: https://github.com/codemirror/CodeMirror/issues/3745#issuecomment-340389826

**Comment by julienw** [comment]
Ah, they answered that we should be in JSX mode, and this actually works in JSX mode (while JS mode still shows the same issue as initially shown). I don't know if there's any drawbacks using this mode for all JS code, I asked there.

**Comment by jasonLaster** [comment]
Thanks @julienw we can be pretty smart about the mode if we parse the source text and see a JSX node

**Comment by jasonLaster** [comment]
when was the JSX mode introduced? should we try to do this w/ 28? or jump and do it?

**Comment by nyrosmith** [comment]
@jasonLaster jsx mode was introduced in [v5.11.0.](https://github.com/codemirror/CodeMirror/releases/tag/5.11.0) in Jan 2016

@julienw Are you already onto it? Otherwise I'd claim it and look if we always can always use jsx mode for javascript

**Comment by julienw** [comment]
@nyrosmith I'm not, I was just trying to make things clear :)

**Comment by julienw** [comment]
They say there shouldn't be any drawback to always use JSX, but maybe there are other implications, like performance.

**Comment by nyrosmith** [comment]
@julienw can you provide an URL I can test the changes?

**Comment by julienw** [comment]
I don't have one easily usable online.

But here is a not-so-simple STR:
1. clone https://github.com/devtools-html/perf.html/
2. run `yarn install && yarn start`
3. with Firefox, go to http://localhost:4242/public/1ecd7a421948995171a4bb483b7bcc8e1868cc57/calltree/
4. Open the Debugger and open the file webpack > src > components > shared > TreeView.js

You'll see most of the file is blue because of the pattern ```className={`treeViewHeaderColumn treeViewFixedColumn ${col.propName}`}``` line 34.

**Comment by nyrosmith** [comment]
That's fine for me. Let's see if I can improve the highlighting
