### ISSUE TITLE
ErrorMessage: services is not defined

### ISSUE THREAD

**Issue by nyrosmith** [devtools-html/debugger.html#3883]
Sometimes when navigating between pages there comes an error message: `Uncaught ReferenceError: services is not defined`
![reference_error](https://user-images.githubusercontent.com/2511026/30036272-e0324b84-91b1-11e7-9f89-0c1f633a790f.gif)

**Comment by jasonLaster** [comment]
This happens when the `eventListeners` feature is on. Closing this issue as it should just be off now.
