### ISSUE TITLE
Debuggee fast navigation breaks debugger

### ISSUE THREAD

**Issue by nyrosmith** [devtools-html/debugger.html#3884]
Please ignore the `services is not defined` error. I created another issue for that.
![fast_navigation](https://user-images.githubusercontent.com/2511026/30036351-cf5d1f86-91b2-11e7-97e1-d6cde9006354.gif)

**Comment by jasonLaster** [comment]
@nyrosmith can you try testing this in Firefox Nightly. Basically not the launchpad, but in the panel.

**Comment by nyrosmith** [comment]
@jasonLaster do you mean just installing nightly? How do I get master into that?

**Comment by jasonLaster** [comment]
closing as we haven't reproduced
