### ISSUE TITLE
Watch Expression Text Bleeds Over Remove Icon

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#3901]
The "x" icon to remove a watch expression is difficult to see when the expression extends past its given space, as the close icon overlaps the text:

<img width="310" alt="watchexpressionclose" src="https://user-images.githubusercontent.com/46655/30089652-d566e5b2-9273-11e7-93d5-5390b91d89d1.png">

We could employ this technique:

https://davidwalsh.name/css-ellipsis

Or we could pad the close icon and allow scroll of the text

**Comment by jasonLaster** [comment]
Nice find. I'm worried that we need at least 60% of the space for showing an expression value. 

I think a CSS elipsis with a maximum width of 40% probably is the way to go. I'm not a huge fan of this UI in general and I hope to see it deprecated in the winter :)

**Comment by iamstratos** [comment]
I will commit this tomorrow!

**Comment by jasonLaster** [comment]
@iamstratos sure, its yours

**Comment by iamstratos** [comment]
Do you use inline css or any other way to style your elements?

**Comment by jasonLaster** [comment]
@iamstratos we try and use CSS files
