### ISSUE TITLE
Provide Selected Hover Color

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#3903]
When hovering over selected items, their background color matches an unselected background color.  As a nice detail, it would be cool if we could make the selected hover color closer match the selected color than the normal back.  In the case of this gif, a slightly lighter blue:

![selectedhover](https://user-images.githubusercontent.com/46655/30091238-36ea504e-927e-11e7-808b-9f1b025f2b26.gif)

**Comment by jasonLaster** [comment]
Daniel looked into it and saw this was fixed
