### ISSUE TITLE
Audit Text Case

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#3904]
Debugger.html jumps between text case patterns.  For example:

"Close tab"
"Reveal in Tree"
"Blackbox Source"

It would be worth the time to audit text case and become consistent.  Firefox context menus use an uppercase pattern, FWIW:

"Save Page As..."
"Select All"
"Inspect Element"

**Comment by jasonLaster** [comment]
we should capitalize the first word: e.g. "Close tab"
