### ISSUE TITLE
[EmptyLines] don't update when the debuggee reloads

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3911]
#### STR

1. start debugger inception
  1. open the launchpad 
  2. open a new firefox
  3. open todomvc
  4. open launchpad in ff and point it to debugger
2. in the original browser or a new tab open the launchpad and point to the first debugger.html
3. go to actions/addBreakpoint

observe that line 50 is disabled

Steps to fix:

I recommend adding a new fixture in the parser tests and trying to reproduce and fix there.

![Screen Shot 2017-09-06 at 3.46.56 PM.png](https://shipusercontent.com/92d79544a747e956ce351d822e6fcf29/Screen%20Shot%202017-09-06%20at%203.46.56%20PM.png)

**Comment by darkwing** [comment]
Everything looks correct up until 44; 45 should be disabled, as should 49, 53, 55, etc.  Huh.

**Comment by darkwing** [comment]
Oddly enough, at first try, it looks like it's working properly here:

<img width="952" alt="wfmlines" src="https://user-images.githubusercontent.com/46655/30134150-bd870280-931b-11e7-9f6d-af0bccca8dab.png">

**Comment by jasonLaster** [comment]
Yep. I was able to reproduce this by adding a comment in `Editor/index.js` and reloading, then removing and reloading.

It looks like we don't do a good job of clearing the lines when they change.

```diff
diff --git a/src/components/Editor/index.js b/src/components/Editor/index.js
index 0ce82d1..b3a96f4 100644
--- a/src/components/Editor/index.js
+++ b/src/components/Editor/index.js
@@ -13,6 +13,14 @@ import { debugGlobal } from "devtools-launchpad";
 import { isLoaded } from "../../utils/source";

 import { isEmptyLineInSource } from "../../reducers/ast";
+/*
+
+
+
+
+
+*/
+

 import {
   getActiveSearch,
```

**Comment by jasonLaster** [comment]
This was fixed by our Editor refactor!
