### ISSUE TITLE
[ProjectSearch] Search in file doesn't have 'No Results' state

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#3924]
The screen for search is empty as blank state and stays empty when nothing is found. It is is hard to tell if the search is just not doing anything.

*Source search* shows `No Results`. *Search in file* shows an empty space.

Source search | File search
------------ | -------------
<img width="540" alt="image" src="https://user-images.githubusercontent.com/8599/30223711-e243932a-9480-11e7-8e5e-a61cc27fc336.png"> | <img width="527" alt="image" src="https://user-images.githubusercontent.com/8599/30223720-ea0df064-9480-11e7-92be-7afcdd374f90.png">

### Small code sketch

```diff
diff --git a/src/components/ProjectSearch/TextSearch.js b/src/components/ProjectSearch/TextSearch.js
index 2c42080..3500d2e 100644
--- a/src/components/ProjectSearch/TextSearch.js
+++ b/src/components/ProjectSearch/TextSearch.js
@@ -143,8 +143,17 @@ export default class TextSearch extends Component {
     );
   }

+  renderNoResults() {
+    return <div></div>
+  }
+
   renderResults() {
     const results = this.getResults();
+
+    if (results.length == 0) {
+      return this.renderNoResults();
+    }
+
     results = results.filter(result => result.matches.length > 0);
     function getFilePath(item, index) {
       return item.filepath
```

**Comment by jasonLaster** [comment]
@abhinav is looking into it
