### ISSUE TITLE
[Editor] Add a menu item to execute selected text in the console

### ISSUE THREAD

**Issue by captainbrosset** [devtools-html/debugger.html#3942]
Filing from some feedback received today on IRC #devtools:

"Selecting text in debugger to evaluate in console.  Couldn't figure out how to do that, but seems like a super easy convenience function.
Just an extra right click entry that copies it over and runs it."

**Comment by jasonLaster** [comment]
Yes, that's a great win. Chrome also uses the selection to show a preview. They started doing this 8 months or so ago.

**Comment by lukaszsobek** [comment]
Seems we need something along the lines of:
- add new text entry to the localization file "Evaluate in console"
- add this entry to a new menu item
- the menu item only appears when we right-click a selection of text
- the new menu item calls a function
- the function console logs the output

**Comment by jasonLaster** [comment]
I think we can add a `consoleEvaluate` action in `actions/panel` 

```js
export function consoleEvaluate(input) {
    return ({ client }: ThunkArgs) => {
      // check to see if there is a syntax error ... 
      
      // then evaluate
      client.evaluate(`console.log(input)`)
    }
}
```

**Comment by lukaszsobek** [comment]
@jasonLaster @captainbrosset 
So when we run evaluateInConsole we seem to have 3 scenarios:

- we are evaluating a variable, in which case we want to return:
a) which variable was evaluated
b) what the variable contained or undefined

- we are evaluating a function content, in which case we want to return:
a) which function was evaluated
b) what the contents of the functions are

- we are evaluating a function execution, in which case we want to return:
a) which function was being executed
b) what the contents of the functions are
c) what the return value of the function is

Does that sound about right?

**Comment by lukaszsobek** [comment]
Merged. Closing.
