### ISSUE TITLE
F3 opens the Firefox search before selecting the next text match

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#3943]
The feature introduced for [2641](https://github.com/devtools-html/debugger.html/issues/2641) in (PRs #2673 and #2642) has apparently regressed.

In the latest Nightly, if I do a text search with the debugger, pressing F3 will first make the Firefox search appear. After that will start selecting the next occurrence of the query in the debugger.

**Comment by AlexisDeschamps** [comment]
I was not able to reproduce on Windows 10 on Nightly. It seems that whenever `Enter`/`Shift-Enter` worked, `F3`/`Shift-F3` also worked.

**Comment by jasonLaster** [comment]
@juliandescottes can you try this again?

**Comment by juliandescottes** [comment]
Looks fixed in recent Nightlies, feel free to close.
