### ISSUE TITLE
[Preview] Missing tooltip for falsy values

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#3944]
Try to run the following code:
```javascript
(function () {
  let falsyString = "";
  let falsyBool = false;
  let falsyNumber = 0;

  let truthyString = " ";
  let truthyBool = true;
  let truthyNumber = 1;

  debugger;
})();
```

When paused on debugger, try to hover on each of the variables available in scope. The tooltip is not displayed for any of the falsy variables.

![falsy_tooltip](https://user-images.githubusercontent.com/1141550/30216051-0f84d34a-94b2-11e7-9c7b-f6c326d0913a.gif)

**Comment by jasonLaster** [comment]
Here is a [site] where you can try it out

[site]: https://fabulous-umbrella.glitch.me/

**Comment by nyrosmith** [comment]
I tried to fix this and I nailed it to https://github.com/devtools-html/debugger.html/blob/09438b25f682a875b4d41170f9161efedd113730/src/actions/ast.js#L150

But then I really got stuck... Maybe this is helpful for someone more experienced on the codebase

**Comment by jasonLaster** [comment]
what did you see there? Was there a problem w/ the `result` being falsey?

try 

```js
        if (result === undefined) {
          return;
        }
```

**Comment by nyrosmith** [comment]
Oh stupid me. So obvious...

**Comment by juliandescottes** [comment]
The issue is back.

**Comment by jasonLaster** [comment]
there's a new issue for it

**Comment by jasonLaster** [comment]
https://github.com/devtools-html/debugger.html/issues/5279
