### ISSUE TITLE
Editor - Code Search

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#396]
![screen shot 2016-07-22 at 8 59 38 am](https://cloud.githubusercontent.com/assets/254562/17057791/7ed8df60-4fea-11e6-8c84-04d337f27447.png)

Editor Search:
- [ ] show a search pane
- [ ] show search results
- [ ] go to next / previous

Implementations:
+ [current debugger](https://dxr.mozilla.org/mozilla-central/source/devtools/client/sourceeditor/debugger.js#11-91)
+ [code mirror](https://codemirror.net/demo/search.html)

We should compare implementations and see if the reasons for building our own search experience still hold up. If not, I'd prefer to use search.js and stay with the community. 

I believe @helenvholmes has some designs for editor search. One piece that I remember is that search is on the top below tabs and not at the footer.

**Comment by helenvholmes** [comment]
<img width="1150" alt="screen shot 2016-07-25 at 5 10 31 pm" src="https://cloud.githubusercontent.com/assets/1720093/17138709/8c7ebb26-530f-11e6-94b9-0849a5cc04dc.png">

![search and filter](https://cloud.githubusercontent.com/assets/1720093/17138738/ab5f5f50-530f-11e6-800f-64a26d6d1c49.png)

(Relevant designs)

Chrome used to do something similar to what I had designed for "search across files", although I can't seem to remember the key command for it now.

I'm fine with changing to search.js's implementation for search in-file—seems like that's what Sublime is using, who UX I was looking at for search-in-file for results as well.

**Comment by jasonLaster** [comment]
@jlongster now that we've integrated codemirror. Does it make sense to close this for now and keep what we have? I assume after we launch we can revisit it?

**Comment by jlongster** [comment]
I'd like to at least look at the native codemirror behavior and see if it's just a matter of making sure we hook up the code search addon. If it's any more complex, yeah, we can close this and open more specific issues and focus on searching later.

**Comment by jasonLaster** [comment]
Closing this issue as it's gone stale. Opened https://github.com/devtools-html/debugger.html/issues/716 to tackle code search in the panel.
