### ISSUE TITLE
Weird Tree Highlighting / Overflow

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#3972]
When scrolling horizontally in tree, the highlight background color looks weird:

<img width="252" alt="weirdhighlight" src="https://user-images.githubusercontent.com/46655/30292444-cbe86aa6-96fb-11e7-8370-933358d9ed1f.png">

*Probably* a Firefox quirk more than anything.  We should investigate the cause and then file a Firefox bug if it appears to be a browser issue.

**Comment by darkwing** [comment]
This has something to do with it:

```
.managed-tree .tree {
    white-space: nowrap;
}
```

Removing that CSS solves the problem, though the text wraps.  We should focus the fix around this.

**Comment by amitzur** [comment]
I think the only solution here is to wrap the text node with a span and give that span the same styling. It's the only element that reaches the right edge.

I made a simplified case here:
The problem:
https://jsfiddle.net/wLsc4unm/1/
The solution:
https://jsfiddle.net/usLszhuL/3/

**Comment by zacck** [comment]
@jasonLaster  I can try get this one working

**Comment by jasonLaster** [comment]
sure!
