### ISSUE TITLE
Simplify scope display names

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3974]
We currently simplify function display names when we're showing call stacks.

We should do the same thing here: `exports.syncClientBreakpoint</_ref<` => `_ref`. And... if we dropped babel's async to generator, it would be `syncClientBreakpoint`.

#### Screenshot

![Screen Shot 2017-09-11 at 6.49.57 PM.png](https://shipusercontent.com/aceb27ede412bfb9894c113ccbe0089c/Screen%20Shot%202017-09-11%20at%206.49.57%20PM.png)

#### Sketch

```diff

diff --git a/src/utils/scopes.js b/src/utils/scopes.js
index 107b3a2..64e52ea 100644
--- a/src/utils/scopes.js
+++ b/src/utils/scopes.js
@@ -96,7 +96,9 @@ export function getScopes(
       const bindings = scope.bindings;
       let title;
       if (type === "function") {
-        title = scope.function.displayName || "(anonymous)";
+        title = scope.function.displayName
+          ? simplifyDisplayName(scope.function.displayName)
+          : "(anonymous)"; // while we're at it we should L10N this as well.
       } else {
         title = L10N.getStr("scopes.block");
       }
```

**Comment by NettaB** [comment]
hi. how do we reproduce this issue? what situation causes the function name to look like this?

**Comment by jasonLaster** [comment]
good question, let me find a good place to pause

**Comment by jasonLaster** [comment]
Go to: https://znm3qxj923.codesandbox.io/
and add a bp: in components/Footer.js on line 39.

You should see a scope with `_class<` which could be simplifed to `_class`. I got my screenshot by debugging the debugger, but that is a bit tougher :)

**Comment by jasonLaster** [comment]
![Screen Shot 2017-09-13 at 2.06.25 PM.png](https://shipusercontent.com/f52b2de8ef188601fa74aa757abecd07/Screen%20Shot%202017-09-13%20at%202.06.25%20PM.png)

**Comment by amitzur** [comment]
hmm.. how come I'm seeing the transpiled ES5 version of Footer.js?
<img width="972" alt="screen shot 2017-09-13 at 11 00 12 pm" src="https://user-images.githubusercontent.com/394320/30398009-709ebbea-98d7-11e7-9046-bc909e35b818.png">

**Comment by jasonLaster** [comment]
you're looking at `static/js` i think this is a bad example...

**Comment by jasonLaster** [comment]
@amitzur I tried to come up with a better example: [here](https://salty-dawn.glitch.me/). Unfortunately, this didn't show the scopes...

```js

function stuff() {

  const obj = {
    foo: function() {
      [1,2,3].forEach(function(item) {
        (function yay() {
          console.log("yo")
        })()
      })
    }
  }
  
  obj.foo();
  
}
```

![Screen Shot 2017-09-13 at 4.09.02 PM.png](https://shipusercontent.com/7a0bd02b9f08bed1aaf76f858d3cdf45/Screen%20Shot%202017-09-13%20at%204.09.02%20PM.png)

**Comment by amitzur** [comment]
Yeah, this is similar to what @NettaB and Noga came up with. Does this have to do with source maps? I thought the "<" character is added when the function is wrapped in a closure

**Comment by jasonLaster** [comment]
yeah, it comes from this paper: 
https://github.com/devtools-html/debugger.html/blob/master/src/utils/frame.js#L203
http://johnjbarton.github.io/nonymous/index.html

**Comment by jasonLaster** [comment]
Good call! Updated the example:
https://salty-dawn.glitch.me/

![Screen Shot 2017-09-13 at 4.19.36 PM.png](https://shipusercontent.com/33d3ab912fa5db9ee352b0097a5c8de1/Screen%20Shot%202017-09-13%20at%204.19.36%20PM.png)
