### ISSUE TITLE
Add Group Breakpoint Removal

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#3976]
It would be nice if we could remove breakpoints with one click.  I propose we add a "x" icon in the heading for that block which would remove every breakpoint.  

<img width="300" alt="breakpointscheckboxes" src="https://user-images.githubusercontent.com/46655/30304406-f94c6f9c-9732-11e7-93f1-d41923a970d5.png">

**Comment by wldcordeiro** [comment]
I'd support this more if the breakpoint list was organized like so, but I still think it'd be nice to have.

```
file-name
  - bp line 300
  - bp line 392
file-name2
  - bp line 123
  - bp line 1029
``

**Comment by jasonLaster** [comment]
We have a context menu item. I'm also thinking of having an ellipsis for other actions as well when we look at a couple breakpoint ux issues

- moving PoE 
- moving pause on next statement
- grouping by file

**Comment by jasonLaster** [comment]
closing as we'll discuss this in a  tracking issue
