### ISSUE TITLE
Remove the usage of --theme-content-color3 that overrides the --theme-comment color

### ISSUE THREAD

**Issue by gabrielluong** [devtools-html/debugger.html#3978]
The debugger uses the --theme-content-color3 in the dark theme to override the previous --theme-comment color. This is no longer needed and should be removed.

**Comment by wldcordeiro** [comment]
So replace `--theme-content-color3` with `--theme-comment`?

**Comment by gabrielluong** [comment]
Yes

**Comment by gabrielluong** [comment]
Actually, I think there are some parts that were originally gonna use --theme-comment already, but was overridden with --theme-content-color3.

**Comment by diessica** [comment]
It looks like an quick refactor. Still need help on this?

**Comment by jasonLaster** [comment]
@diessica that'd be great

**Comment by jasonLaster** [comment]
:wave: @diessica, just checking in to see how it's going and if you have any questions.

Also, if you're currently busy, feel free to `/unclaim` the issue. You can always `/claim` another one later. And, this is OSS, we're guilt free!

Also, always happy to chat on [slack] or in a 'hangout!

[slack]: https://devtools-html-slack.herokuapp.com/
