### ISSUE TITLE
readme screenshot

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#398]
thinking of using this for the readme screenshot

![debugger](https://cloud.githubusercontent.com/assets/2134/17063739/9d4b0fba-4fed-11e6-9651-9ea4bc32b6c7.png)

thoughts? @jlongster  @jasonLaster 

I want something that shows off
* sources tree view
* editor
* editor tabs
* breakpoint list
* scopes
* call stack (however this call stack was actually too big to include and pushed everything down)
* paused state

**Comment by jasonLaster** [comment]
Looks good. It might be interesting to show it without the browser chrome too at some point. The advantage of the chrome is that you see it's a local dev environment, but I wonder if that's central to the marketing. People who want to embed it might prefer just seeing the debugger.

**Comment by clarkbw** [comment]
> show it without the browser chrome

I was thinking that as well.  That either it might be nice to show it in other browsers or just remove the browser chrome all together.

**Comment by clarkbw** [comment]
Here's the full height, no chrome version

![debugger](https://cloud.githubusercontent.com/assets/2134/17065593/8906ffb4-4ff7-11e6-89c1-aaa13f8e8664.png)

**Comment by jasonLaster** [comment]
I think I like the initial aspect ratio. And could go either way on the chrome

**Comment by jlongster** [comment]
I like the first screenshot a lot better as well. And I like the chrome, it makes for a prettier screenshot.
