### ISSUE TITLE
[ProjectSearch] exclude node_modules and content scripts

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3987]
We should exclude searches to node_modules and content scripts by default and give a UI for searching them

**Comment by jasonLaster** [comment]
How does this look as a simple UI? We could re-use the ellispis svg, and dropdown class?

Either way, we should do 2 PRs, first exclude the 3rd party code and then add the UI for re-enabling it.

![Screen Shot 2017-09-12 at 3.40.59 PM.png](https://shipusercontent.com/0de4dc1c37bb8665d23dd8c013a70df4/Screen%20Shot%202017-09-12%20at%203.40.59%20PM.png)
![Screen Shot 2017-09-12 at 3.40.46 PM.png](https://shipusercontent.com/119fdc4990a9d01a118f08279bb862fb/Screen%20Shot%202017-09-12%20at%203.40.46%20PM.png)

**Comment by jasonLaster** [comment]
@abhinav is on it

**Comment by abhinav** [comment]
@jasonLaster You're pinging the wrong user on these tickets.

**Comment by bomsy** [comment]
- [ ] Exclude 3rd Party code from project text search
- [ ]  Add UI for enabling/ disabling 3rd party code

**Comment by digitarald** [comment]
UI considerations:

- Atom's UI spells out the active modifiers to help understand the icons: <img width="409" alt="image" src="https://user-images.githubusercontent.com/8599/30345008-66f3571a-97b8-11e7-97f6-a810d200256d.png">

- As icons are we break the icons out into text when the space allows, like Firefox's UI: <img width="489" alt="image" src="https://user-images.githubusercontent.com/8599/30345189-0ac44570-97b9-11e7-8d4d-8ef589c87a11.png">

- Replace the 3-dots-menu with a `Scope` dropdown next to the options, allowing selection from `All|Sources|Content Scripts` (or whatever the 1st PR includes).

Thoughts @jasonLaster ?

**Comment by abhinav-koppula** [comment]
@jasonLaster - @abhinav-koppula is the correct username

**Comment by jasonLaster** [comment]
closing as we'll get to this when we do project search
