### ISSUE TITLE
Align vertical spacing of search UIs

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#3990]
<img width="300" alt="image" src="https://user-images.githubusercontent.com/8599/30352007-cd6c428a-97d2-11e7-8be9-a7d4ac18da6f.png">

vs

<img width="275" alt="image" src="https://user-images.githubusercontent.com/8599/30352027-e2c30ea2-97d2-11e7-97d8-5b1c67f031cc.png">

Second one doesn't fit into the vertical rhythm (27px vs 40px).

**Comment by jasonLaster** [comment]
closing because we can address it in #3178
