### ISSUE TITLE
Hang when going from Console to Debugger

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#3991]
https://perfht.ml/2joU0UH

- Codemirror's `updateHeightsInViewport` is expensive due to mostly reflows: https://perfht.ml/2jnqRsU
- There are 2 cycles of `updateHeightsInViewport` for loading one file, which might be overhead. One is caused by `setOption` and the other by `resetLineNumberFormat`: https://perfht.ml/2joUJ8n

**Comment by digitarald** [comment]
Maybe related to #3400

**Comment by jasonLaster** [comment]
Looks like this is coming from `resetLineNumberFormat`, which was added for wasm


![Screen Shot 2017-09-19 at 10.57.47 AM.png](https://shipusercontent.com/1de2605b4fcebc313490ba415942d51a/Screen%20Shot%202017-09-19%20at%2010.57.47%20AM.png)

**Comment by jasonLaster** [comment]
@digitarald do you have an STR here?

**Comment by digitarald** [comment]
Tried different cases of clicking from Console logs to the JS source and could not reproduce a noticeable super long hangs anymore (just long delays on loading the sources).

**Comment by jasonLaster** [comment]
I found one :) 

when the debugger is open locally

**Comment by digitarald** [comment]
The root cause of this issue seems fixed.

Amazon: https://perfht.ml/2V1Rx1c - snappy.
Github: https://perfht.ml/2V0YTlq - we seem to be waiting for downloading the source maps and the worker before drawing any UI, which is an odd choice. I will file that as separate issue though.
