### ISSUE TITLE
[PrettyPrint] interferes with source maps

### ISSUE THREAD

**Issue by tromey** [devtools-html/debugger.html#3995]
* Visit https://tromey.github.io/source-map-examples/minified/index.html
* Open the debugger
* Open bundle.js
* Pretty-print the bundle
* Now open s1.js

I get an error:

```
Error while fetching an original source: Error: "webpack:///s2.js" is not in the SourceMap.
Source URL: webpack:///s2.js
```

I believe what is happening is that the debugger-generated source map overwrites the user-supplied one.  But, the debugger doesn't update its source list to follow.

See also https://bugzilla.mozilla.org/show_bug.cgi?id=952127

**Comment by jasonLaster** [comment]
I'm moving this to the icebox, we will re-evaluate at the beginning of the next release planning process.
