### ISSUE TITLE
[PrettyPrint] can't pretty print before the source is loaded

### ISSUE THREAD

**Issue by tromey** [devtools-html/debugger.html#3996]
If I reopen the debugger, I may see a tab from a source that I had opened previously.  The tab isn't selected and no source is shown.

I can right click on the tab and select pretty-printing -- but nothing happens.

If I left click on the tab, the source is loaded; and then if I pretty-print, it works.

This was a bit confusing to me the first couple of times.  I think pretty-printing should implicitly load the source.

**Comment by jasonLaster** [comment]
Nice find
