### ISSUE TITLE
[WelcomeBox] should be responsive

### ISSUE THREAD

**Issue by tromey** [devtools-html/debugger.html#3999]
I opened the browser toolbox.  My window was apparently a bit narrow so the instructions telling me how to search came out garbled:

![image](https://user-images.githubusercontent.com/1557670/30390614-e9d41db6-9873-11e7-826d-81ca7e55c918.png)

Widening the window a bit fixes this.  But really it shouldn't happen.

**Comment by jasonLaster** [comment]
We should stagger the search shortcuts on a narrow UI:

```
Ctrl P
to search for sources

...

```

**Comment by iamstratos** [comment]
I could work on this issue. Is that okay?

**Comment by jasonLaster** [comment]
@iamstratos go for it.
