### ISSUE TITLE
Conditional breakpoint on hot code path slow down Firefox to a crawl

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#4017]
STRs [WARNING: this might force you to kill your browser instance!]
- go to about:home (or any webpage)
- in the console, execute 
``` javascript
(function () {
  debugger;
  let i = 0;
  window.setInterval(() => {
    i++;
    if (i === 100) {
      i = 0;
    }
  }, 10);
})();
```
- debugger should open and be paused on the debugger statement
- add a conditional breakpoint on line i++, condition "false"
- resume

As expected, the conditional breakpoint should never hit. CPU activity increases significantly. And after a few seconds, Firefox slows down to a crawl, and I need to kill it. 

Interestingly, this does not happen:
- with the old debugger frontend (the CPU activity doesn't even really increase)
- on some specific about: pages, such as about:sessionrestore. Looking at [AboutRedirector.cpp](http://searchfox.org/mozilla-central/source/browser/components/about/AboutRedirector.cpp#74), this is one of the "about" pages which runs in the main process, so that probably has something to do with this bug.

**Comment by digitarald** [comment]
Recorded a profile: https://perfht.ml/2AmcWdJ

Looks like React is constantly updating state in the main process after receiving messages; and the content pocess has some hangs due to `_setBreakpoint`.

**Comment by jimblandy** [comment]
We don't expect the client to be involved in conditional breakpoints at all, so there's something very odd going on here.

**Comment by jasonLaster** [comment]
@jimblandy did you see this comment above:

> on some specific about: pages, such as about:sessionrestore. Looking at AboutRedirector.cpp, this is one of the "about" pages which runs in the main process, so that probably has something to do with this bug.

it might be just for some `about` pages

**Comment by darkwing** [comment]
I followed these steps, waited a few minutes, and no massive CPU spike.
