### ISSUE TITLE
[ProjectSearch] left arrow presses should collapse the group

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4018]
Our Project Search mirrors atom's UI and our sources tree in many ways. One nice feature they have is that left arrow will always collapse the group of matches or files.

The benefit of this is that the keyboard becomes much more useful, if you're half way through a big list, you can always left arrow to collapse the group and move on.

![](http://g.recordit.co/VWMz4POmJB.gif)

**Comment by jasonLaster** [comment]
@abhinav-koppula is on it.

**Comment by nchevobbe** [comment]
If this uses the Tree component, https://github.com/devtools-html/devtools-core/commit/739e193ec48df0ca5d876deb14cd894775ae2f4d#diff-ea6020634144f5e2ba8dae590d5bb115 added that (not published on npm yet though)

**Comment by jasonLaster** [comment]
closing as we'll get it for free when we upgrade the tree
