### ISSUE TITLE
[Editor] Copy menu entry is never enabled when running in Firefox

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#4019]
When right clicking in the editor, the menu proposes various options
<img width="272" alt="image" src="https://user-images.githubusercontent.com/1141550/30447468-8755e9ca-998c-11e7-81fa-82a10df5edc6.png">

The "Copy" menu item is disabled. I suppose that in Launchpad, it becomes enabled when some text is selected. However in Firefox when there is any selection, the menu is replaced with: 
<img width="153" alt="image" src="https://user-images.githubusercontent.com/1141550/30447520-a80436fe-998c-11e7-8e6b-e642909bb80f.png">

I never managed to have "Copy" enabled, if I'm correct maybe it should be hidden when running in Firefox?

**Comment by jasonLaster** [comment]
We should never see the second context menu. This is a regression (I believe we introduced when we upgraded codemirror).

**Comment by jasonLaster** [comment]
This was a regression caused by a global toolbox contextmenu that used a capture. It'll be fixed soon
