### ISSUE TITLE
[Preview] Tooltip shows undefined for variable used as object key

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#4020]
STRs:

run in the console

```js
(function (key) {
  debugger;
  let obj = {};
  obj[key] = 0;
  return obj;
})("a");
```
hover on "key" in obj[key]

Expected result: should show `"a"`
Actual result: shows `undefined`

**Comment by juliandescottes** [comment]
![](https://screenletstore.appspot.com/img/d05e00d4-9983-11e7-b141-ddd9e672c8a3.png)

**Comment by bomsy** [comment]
The issue relates to the computed and uncomputed MemberExpressions. we are looking at `obj[key]` (computed) as `obj.key` (uncomputed)

**Comment by juliandescottes** [comment]
Thanks for fixing this @bomsy ! Just happened to test this in the last debugger bundle update and this works fine now :)
