### ISSUE TITLE
[Editor] flash function when it is copied

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4022]
@jenncreighton added an awesome `highlightLineRange` function a couple months ago for selecting lines.

We should use it to highlight the function when it is copied too. We might also want to add a couple of updates to it too:

1. update the first and last line so we dont flash the entire line but after the first character of the first line and before the last character of the last line
2. add a new redux action like `flashLighlightLine` that knows how to add a highlight and then clear it after a second.

Here is where [highlightLineRange][here] is used now. We should add it here too:

```diff
--- a/src/components/Editor/EditorMenu.js
+++ b/src/components/Editor/EditorMenu.js
@@ -101,7 +101,10 @@ function getMenuItems(
     label: copyFunctionLabel,
     accesskey: copyFunctionKey,
     disabled: !functionText,
-    click: () => copyToTheClipboard(functionText)
+    click: () => {
+      copyToTheClipboard(functionText);
+      // do something here...
+    }
   };
   ```

[here]: https://github.com/yurydelendik/debugger.html/blob/getScopes2/src/components/SymbolModal.js#L186-L191

**Comment by borian** [comment]
Hey, 
first contributer here.
I've had a go at this issue.

The mentioned `highlightLineRange` seems to do something different.
`selectSource` seems to be used to do the highlight effect.
![peek 2017-09-20 22-05](https://user-images.githubusercontent.com/1525694/30665218-8e10edc8-9e50-11e7-97da-1f1180f7eec7.gif)

The [`selectSource`](https://github.com/devtools-html/debugger.html/blob/f048741f3c194ff93aa67d573278ea8a38433ac5/src/actions/sources.js#L191) function can only highlight one line.


When you use the **copy Function** action, I would expect it to highlight the line with the function definition or the whole function. For both, *EditorMenu.js* does not have enough context.   
The [`findFunctionText`](https://github.com/devtools-html/debugger.html/blob/37365ddd8d7bebadda096dd814a3a63eaaa8449c/src/utils/function.js#L19) has the necessary context but does not expose it.  

So maybe `findFunctionText` could be extended to return an object with the function text and all available context (firstLine, lastLine).

But I wanted some feedback before I go further.

**Comment by jasonLaster** [comment]
Hey, great research.

> I would expect it to highlight the line with the function definition or the whole function. 

Lets highlight the whole function

> maybe findFunctionText could be extended to return an object

How about we create a new method `getFunctionLocation` that returns the start and end location. `findFunctionText` can use it too :)

Sorry for missing this comment yesterday, feel free to ping us in slack. We're much more responsive there!

**Comment by jasonLaster** [comment]
ping @borian :)

**Comment by jasonLaster** [comment]
:wave: @borian, just checking in to see how it's going and if you have any questions.

Also, if you're currently busy, feel free to `/unclaim` the issue. You can always `/claim` another one later. And, this is OSS, we're guilt free!

Also, always happy to chat on [slack] or in a 'hangout!

[slack]: https://devtools-html-slack.herokuapp.com/
