### ISSUE TITLE
[SourcesTree] eval sources don't show up in Sources pane

### ISSUE THREAD

**Issue by tromey** [devtools-html/debugger.html#4029]
Open `about:blank`, open the console and evaluate `eval("function qqz() { debugger; }")`.  Next, evaluate `qqz()`.

This will open the debugger and pause at the `debugger` statement.  However, there are no sources shown in the sources pane.  I also couldn't find a way to search for `qqz`.

**Comment by jasonLaster** [comment]
@tromey this was by design, we felt that inline scripts and evals should be shown when you pause and given a tab, but not shown in the tree. The one caveat is if there is a sourceUrl stanza.

I'd be open to suggestions though. We have all the data client-side so it's just a question of UX.

**Comment by tromey** [comment]
Ok, I didn't realize that.  Thanks.

However, I evalled this in the console:
```
function foo() {
  debugger;
}
//# sourceURL=http://example.com/derp.js
```

(It's an example from one of the source-map bugs - the "derp" may be commentary but it isn't coming from me :-)
... and I still don't see any sources.

**Comment by jasonLaster** [comment]
hmm, we have this mochitest:

https://github.com/devtools-html/debugger.html/blob/master/src/test/mochitest/browser_dbg-sources.js#L68-L75

mind checking to see if there's a regression?

**Comment by tromey** [comment]
That test works fine.  But if I start from `about:blank` and type stuff in at the console, I don't see the sources.

**Comment by tromey** [comment]
Ok, this is weird: if I type in the above to the console -> no source is shown.  However if I wrap the above in `eval`, then it works.

**Comment by tromey** [comment]
Going to close this here in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=833747
I'm tending to think this is a bug somewhere other than the debugger.
