### ISSUE TITLE
Watch Expressions

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#403]
Implement Watch Expressions in the right sidebar:

Tasks:

- [x] add / remove watch expressions 
- [x] edit an expression
- [x] show an expression value on pause or on edit

Thoughts:

* expressions stored in redux (maybe pause store, that's when they're evaluated)
* input is a formatted input (we don't need syntax highlighting now)
* value is a Rep (look at variable view for how to use them)
* evaluations are evaluated with the same client console eval api
* don't worry too much about the UI, we can style it later

**Chrome:**
![screen shot 2016-07-22 at 1 16 16 pm](https://cloud.githubusercontent.com/assets/254562/17065172/5f216114-500e-11e6-8b2f-3b85df3e5524.png)

**Firefox**
![screen shot 2016-07-22 at 1 16 05 pm](https://cloud.githubusercontent.com/assets/254562/17065173/5f2fb520-500e-11e6-944d-d83abd73d63c.png)

**Comment by jbhoosreddy** [comment]
I'll work on this one now.

**Comment by jasonLaster** [comment]
@jbhoosreddy we can mark this as done when we have a rough implementation where you can add expressions that are evaluated on pause.

+ Object Inspector
+ Edit 
+ Delete

can all come later. This is a big feature and aught to be broken up into smaller pieces

**Comment by jbhoosreddy** [comment]
@jasonLaster thanks. It works to that extent, so I'm going to make a PR tonight. I was actually looking into the httpGet issue now.

**Comment by jasonLaster** [comment]
@jbhoosreddy did a great job in https://github.com/jlongster/debugger.html/pull/434. The first pass has the ability to add and edit watch expresions.

We'll do a second pass soon:
+ look at comments in #434 
+ add remove expressions
+ format with the Object Inspector

**Comment by jasonLaster** [comment]
@jbhoosreddy You've done a great job here. I'm going to close this master ticket and we can always open smaller ones to tweak the UX. I know you have some ideas here.
