### ISSUE TITLE
[Outline] move the tabs to the top

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4031]
The new photon designs call for moving the sources/outline tabs to the top to be consistent.

We hopefully can borrow the html/css from the editor tabs, while re-using the JS...

### Light

![Screen Shot 2017-09-15 at 9.46.30 AM.png](https://shipusercontent.com/b66e7de0d4ab94f00f5d8da906f79963/Screen%20Shot%202017-09-15%20at%209.46.30%20AM.png)

### Dark

![Screen Shot 2017-09-15 at 9.46.37 AM.png](https://shipusercontent.com/ecda22ce18d2d5e0b0b9a869b57002ea/Screen%20Shot%202017-09-15%20at%209.46.37%20AM.png)

**Comment by nyrosmith** [comment]
I am on it.
