### ISSUE TITLE
[Expressions] are retained across domains

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4040]
STR

- Add some watch expressions on cnn.com
- Browse to google.com in another tab
- Open debugger

ER: No watch expressions
AR: Watch expressions from session on cnn.com

Expressions should be stored per domain by default to avoid surprises.

**Comment by jasonLaster** [comment]
I think this is a nice feature, but not necessarily something users expect to have. Chrome and i'm pretty sure the old debugger didn't store expressions by domain.

**Comment by jasonLaster** [comment]
I added this issue to the enhancements board because we won't be able to work on it this quarter. We can re-evaluate when we look at Q1

https://github.com/devtools-html/debugger.html/projects/5
