### ISSUE TITLE
Can’t debug a popup

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4041]
STR:
- Set a breakpoint in a source file related to a popup window
- Open the popup window (without setting the noautohide toggle button from the developer toolbox, and so the popup window is going to auto hide when it will lost the focus)
- The breakpoint is fired and the debugger is paused on the breakpoint
- Click on the debugger to interact with the debugger UI, the popup window loses its focus and it is closed automatically
- The debugger is stuck in the "paused on a breakpoint" mode and I wasn't able to unpause it anymore
- The browser is also stuck and the UI do not react to the events (probably because it is still paused in the debugger)
- closing the toolbox window is the only way to unstuck the browser UI (and if you open the toolbox window again everything seems to be back to normal)

patch: https://bug1349956.bmoattachments.org/attachment.cgi?id=8853142
bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1349956&list_id=

**Comment by nyrosmith** [comment]
Duplicate of #3539 ?

**Comment by jasonLaster** [comment]
yep
