### ISSUE TITLE
Update to devtools-reps 0.13.0

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#4051]
This new version of Reps has some nice performances wins since it lazy loads properties, and thus shouldn't hang when expanding large arrays for example. It also fetches automatically properties, entries and symbols so the debugger will get everything for free (almost)

The code of the ObjectInspector was changed significantly in order to achieve that, so consumers need to change the props passed to it.

As an example, [see how this was done in the console](https://hg.mozilla.org/mozilla-central/diff/0f7830472380/devtools/client/webconsole/new-console-output/components/grip-message-body.js#l1.73).

The main thing is that the ObjectInspector now expects a `createObjectClient` function, which will create an ObjectClient for a given grip, so you don't have to pass specific callbacks to fetch and get object properties, entries and symbols.
It also accept a `releaseActor` function that will release actors used to fetch properties (the root actors lifecycle still need to be handled by the debugger though).

---

I am not sure I'll have enough time to work on this issue for the debugger, given that I don't know the codebase. But I'll happily help and review if someone is willing to do it :)

**Comment by jasonLaster** [comment]
we should really prioritize this so that we can collaborate more easily

**Comment by wldcordeiro** [comment]
We ended up doing an update to 0.19 so I think we can close this.
