### ISSUE TITLE
Debugger script search not working when content type = 'image/svg+xml'.

### ISSUE THREAD

**Issue by paradisaeidae** [devtools-html/debugger.html#4059]
Have an svg file served up with script tag <script id="scriptID" type="text/javascript">
Javascript is part of tag.

Attempt to use search function of debugger.
No search appears to happen.
No results visible.

Expected: Find the search string. Javascript or svg descriptor, tag or content.

**Comment by jasonLaster** [comment]
Thanks for the report @paradisaeidae. Are you referring to `cmd+f`, `cmd+p`, or `cmd+shift+f`, or `cmd+shift+o`?

**Comment by paradisaeidae** [comment]
My apologies.
Operator ignorance.
The tooltip had not appeared for me until recently.
I see the search can be quite functional!

Thankyou!
