### ISSUE TITLE
Make it possible to inspect a function's return value [old-debugger-parity]

### ISSUE THREAD

**Issue by julienw** [devtools-html/debugger.html#4064]
When stepping in some code, the "step out" button allows to wait at the end of the current function, so that we can inspect the final state of the function's variables before actually stepping out. This is useful.

However we can't inspect the return value itself. This would be a very useful addition.

Note: this was possible in the old debugger so we should have the data already: 
![capture d ecran de 2017-09-18 15-50-59](https://user-images.githubusercontent.com/454175/30545261-652c1400-9c89-11e7-9172-161e49336b38.png)

**Comment by tromey** [comment]
I think this is a dup of #3390

**Comment by julienw** [comment]
Likely yes, but we need to make it clear this is missing from previous frontend, and so is a regression and needs to be fixed quicker.

**Comment by jasonLaster** [comment]
thanks @julienw. I'll close this and add the other issue to our milestone.

If you have other STRs, please share.
