### ISSUE TITLE
[SourcesTree] Display anonymous eval-ed code in the source tree

### ISSUE THREAD

**Issue by julienw** [devtools-html/debugger.html#4065]
Currently we don't display anonymous eval-ed code in the source tree. We display it only when it's named through sourcemap annotations (either full sourcemaps or just `sourceURL`) [as explained on MDN](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Debug_eval_sources).

It would be useful to display also anonymous code, for the following reasons:
* Make it obvious that it's executed
* Make it easy to see what's executed. Looking at eval-ed code as a string is painful.

Obviously setting a breakpoint there would be useless, so maybe we shouldn't allow it. Finding a way to break at eval-ed code would be nice but isn't the purpose of this bug. (note we already can use `debugger` in the eval-ed code).

**Comment by julienw** [comment]
testcase:
```html
<!doctype html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta name='viewport' content='initial-scale=1'>
  </head>
  <body>
    <button type="button">eval something!</button>
    <script>
const script = `console.log('hello world')`;
document.querySelector('button').addEventListener('click', () => eval(script));
    </script>
  </body>
</html>
```

Note this doesn't work in Chrome either.

**Comment by jasonLaster** [comment]
moving to the enhancements board as we won't be getting to it this quarter
