### ISSUE TITLE
Source Tab block is off 1px

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4074]
There appears to be a 1px line between the source tabs and the editor:

<img width="1020" alt="tablines" src="https://user-images.githubusercontent.com/46655/30554506-5fff376a-9c6a-11e7-9d6d-899369678007.png">

Hopefully it's just a height issues that needs adjustment

**Comment by darkwing** [comment]
Looks like there's a pixel off at the bottom of the tool as well:

<img width="487" alt="borderbottom" src="https://user-images.githubusercontent.com/46655/30555289-d07767ae-9c6c-11e7-9cdf-eeee6793033c.png">

**Comment by cjb5790** [comment]
I'll take a look at this.

**Comment by jasonLaster** [comment]
@cjb5790 can we find another issue for you, it was just completed. Sorry for not updating the issue to `in-progress`

**Comment by cjb5790** [comment]
@jasonLaster no problem! I'll take a look at the other open issues.
