### ISSUE TITLE
Prevent Unnecessary Left Pane Re-renders

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4085]
There are a few functionality in the left Source / Outline pane that trigger renders but it would be nicer if they wouldn't.

1.  *Swapping between Source and Outline tabs* - The tree re-renders when switching back to Sources and it's fairly noticeable, especially when you see the scrollbar at the bottom.

2.  When I open a few tree items in the source list, then use the "collapse pane" button, then click it again to show the left pane, the tree resets to nothing open.

If we could just show/hide items instead of complete re-renders, it may lighten the app and prevent weird side effects.

**Comment by AnshulMalik** [comment]
Hey @darkwing I don't think the tree actually re-renders.

And also the second point, The opened items stays open on "collapse pane" for me.

Can you please recheck?
