### ISSUE TITLE
[Preview] "watch" error: "TypeError: cyclic object value"

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4098]
STR:

1.  Open the Todo app, create a breakpoint at router.js, line 16
2.  Refresh the source page, let the breakpoint hit
3.  Hover over the object name `app` on line 20
4.  Watch the info popup display
5.  Click the "Watch" keyword in the footer

Error appears:  "TypeError: cyclic object value"

**Comment by jasonLaster** [comment]
is this the same thing? https://github.com/devtools-html/devtools-core/issues/681

**Comment by nchevobbe** [comment]
Not sure if it is related to https://github.com/devtools-html/devtools-core/issues/681 (it was related to the grip structure).
I can have a look to the issue, see if it's Reps related

**Comment by jasonLaster** [comment]
yeah, i think this is reps
