### ISSUE TITLE
[Stepping] Improve Stepping UX

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4109]
We've discussed several ideas for stepping in the past:

1. only show stepping buttons and paused panels when we're paused & when we're stepping.
2. move pausing buttons (Pause on Exception and Next Statement) to the breakpoints panel

There are a couple of advantages:

1. the active state is less noisy
2. the pause state is more obvious
3. we have more space for additional pausing actions. Think event listeners, dom mutations, xhr, watch points ...
4. we can finally solve the FLASHING pane problem when stepping

### Horizontal Mode

![](http://g.recordit.co/DkhpaTpRNo.gif)

### Vertical Mode

![](http://g.recordit.co/sixI8Wnl1c.gif)

### Pause Actions

When the user selects "pause on next statement" or "pause on exception", we can show it in the breakpoint pane. 

<img width="696" alt="screen shot 2017-09-21 at 12 06 01 am" src="https://user-images.githubusercontent.com/254562/30678516-b9fbdb2c-9e60-11e7-8aa8-083842c29ff7.png">

### actions in the breakpoints panel

* the dropdown is one possibility. VS code shows these actions in the [panel][pa]. 
[pa]: https://cloud.githubusercontent.com/assets/323878/15724622/b4d94908-27fc-11e6-981e-2bf39907493e.png

<img width="762" alt="screen shot 2017-09-21 at 12 05 54 am" src="https://user-images.githubusercontent.com/254562/30678517-b9fc3d88-9e60-11e7-80bd-b4f526c2a0f5.png">

Here's the [branch][b] where i'm working on it. Pull it down and play with it. 

[b]:https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:active-view?expand=1

**Comment by digitarald** [comment]
Just to throw this in as hypothesis that we could test with some user research or an experiment: The stepping controls to the side of the code might throw some people off, as they navigate execution flow navigate the source but the controls are in the sidepanel.

VSCode's solution that overlays the stepping controls seems like a good alternative and also avoids the empty button space that needs to be kept available for the buttons.

**Comment by jasonLaster** [comment]
we've discussed moving the stepping buttons before

**Comment by jasonLaster** [comment]
For me, it's an incremental thing:

1. move pause buttons, which are rare
2. hide step buttons so they're only visible when paused
3. improve the paused UI holistically

**Comment by jasonLaster** [comment]
Here's a revised dropdown that is a bit simpler. We'll still want to think through select states:

1. do we highlight the button if a state is selected
2. do we show an item in the breakpoint list once it's selected


![Screen Shot 2017-10-06 at 6.09.10 PM.png](https://shipusercontent.com/5a9c9063450f1ad321a7d6c18fb3c796/Screen%20Shot%202017-10-06%20at%206.09.10%20PM.png)

**Comment by jasonLaster** [comment]
So here's the challenge: the user clicks step over or resume and we want to leave the buttons visible until we are re-paused or 200ms has gone by.

1. re-paused is easy, when the paused action fires we are paused and know to show the buttons
2. the COMMAND action `start` fires when the resume button is clicked and we store the `resume` value in the command field. We can show the button as long as there is a pending command.
3. the command action `done` fires when the resume action completes, and clears the command state... at this point, we no longer know if we're truly resumed or if we'll re-pause in a bit...

<img src='https://shipusercontent.com/0f589cbcebd1f15e42aa5fd972903ef4/Screen%20Shot%202017-11-22%20at%205.23.40%20PM.png' title='Screen Shot 2017-11-22 at 5.23.40 PM.png' width=679>


Proposal, introduce a new field 'pending' which we clear 200ms later. I'm sure pending is a bad name

```diff
diff --git a/src/actions/pause/commands.js b/src/actions/pause/commands.js
index 82ea99c..049ca3b 100644
--- a/src/actions/pause/commands.js
+++ b/src/actions/pause/commands.js
@@ -23,11 +23,13 @@ type CommandType = "stepOver" | "stepIn" | "stepOut" | "resume";
  */
 export function command(type: CommandType) {
   return async ({ dispatch, client }: ThunkArgs) => {
-    return dispatch({
+    await dispatch({
       type: "COMMAND",
       command: type,
       [PROMISE]: client[type]()
     });
+
+    await setTimeout(() => dispatch({ type: "PENDING" }), 200);
   };
 }
 
diff --git a/src/components/SecondaryPanes/CommandBar.js b/src/components/SecondaryPanes/CommandBar.js
index a01672b..a5252d4 100644
--- a/src/components/SecondaryPanes/CommandBar.js
+++ b/src/components/SecondaryPanes/CommandBar.js
@@ -151,7 +151,7 @@ class CommandBar extends Component<Props> {
     const className = isPaused ? "active" : "disabled";
     const isDisabled = !this.props.pause;
 
-    if (!isPaused && features.removeCommandBarOptions) {
+    if (!showStepButtons && features.removeCommandBarOptions) {
       return;
     }
 
@@ -288,7 +288,8 @@ export default connect(
       pause: getPause(state),
       isWaitingOnBreak: getIsWaitingOnBreak(state),
       shouldPauseOnExceptions: getShouldPauseOnExceptions(state),
-      shouldIgnoreCaughtExceptions: getShouldIgnoreCaughtExceptions(state)
+      shouldIgnoreCaughtExceptions: getShouldIgnoreCaughtExceptions(state),
+      showStepButtons: shouldShowStepButtons()
     };
   },
   dispatch => bindActionCreators(actions, dispatch)
diff --git a/src/reducers/pause.js b/src/reducers/pause.js
index 018ed1d..747a7fa 100644
--- a/src/reducers/pause.js
+++ b/src/reducers/pause.js
@@ -157,7 +157,10 @@ function update(state: PauseState = State(), action: Action): PauseState {
     case "COMMAND":
       return action.status === "start"
         ? { ...state, ...emptyPauseState, command: action.command }
-        : { ...state, command: "" };
+        : { ...state, command: "", pending: true };
+
+    case "PENDING":
+      return { ...state, pending: false };
 
     case "RESUME":
       // We clear why on resume because we need it to decide if
@@ -288,4 +291,8 @@ export function getChromeScopes(state: OuterState) {
   return frame ? frame.scopeChain : undefined;
 }
 
+export function shouldShowStepButtons(state: OuterState) {
+  return state.pending || state.command || state.pause;
+}
+
 export default update;
diff --git a/src/utils/tests/ast.spec.js b/src/utils/tests/ast.spec.js
index 560d777..299cb0e 100644
--- a/src/utils/tests/ast.spec.js
+++ b/src/utils/tests/ast.spec.js
@@ -1,42 +1,5 @@
-import { findBestMatchExpression } from "../ast";
-
-import getSymbols from "../../workers/parser/getSymbols";
-import { getSource } from "../../workers/parser/tests/helpers";
-
 describe("find the best expression for the token", () => {
-  it("should find the identifier", () => {
-    const source = getSource("computed-props");
-    const symbols = getSymbols(source);
-
-    const expression = findBestMatchExpression(
-      symbols,
-      { line: 1, column: 13 },
-      "key"
-    );
-    expect(expression).toMatchSnapshot();
-  });
-
-  it("should find the expression for the property", () => {
-    const source = getSource("computed-props");
-    const symbols = getSymbols(source);
-
-    const expression = findBestMatchExpression(
-      symbols,
-      { line: 6, column: 16 },
-      "b"
-    );
-    expect(expression).toMatchSnapshot();
-  });
-
-  it("should find the identifier for computed member expressions", () => {
-    const source = getSource("computed-props");
-    const symbols = getSymbols(source);
-
-    const expression = findBestMatchExpression(
-      symbols,
-      { line: 5, column: 6 },
-      "key"
-    );
-    expect(expression).toMatchSnapshot();
+  it("", () => {
+    expect(2).toEqual(2);
   });
 });
```

**Comment by jasonLaster** [comment]
Just created a google doc to come up w/ next steps for the stepping UX work.
@digitarald, @violasong, @codehag, would love your thoughts

**Comment by violasong** [comment]
Added some questions and a rough mockup to the bottom of the [doc](https://docs.google.com/document/d/1Rf9IVlx8RbVQ7OVzN980KHsUBG0uVt6zcWofKt1TYUs/edit)

**Comment by SebastianZ** [comment]
I'm slightly against hiding the step buttons while the script execution is not paused. With that you add some flashing problem when paused vs. unpaused, which may lead to a "Where are the buttons gone?!" UX.

I would just make the enabled vs. disabled state of the buttons more obvious.

Sebastian

**Comment by jasonLaster** [comment]
Thanks @SebastianZ. Our hope is that the buttons would remain while the debugger steps, but I can see how that is difficult. Nothing is finalized here


Here is our product doc for the POE button. [doc]
Here is a screenshot of what we have now behind a flga

![Screen Shot 2018-02-14 at 3.10.45 PM.png](https://shipusercontent.com/141ce1f5dad8362203c8baa90c41827a/Screen%20Shot%202018-02-14%20at%203.10.45%20PM.png)


[doc]: https://docs.google.com/document/d/1Rf9IVlx8RbVQ7OVzN980KHsUBG0uVt6zcWofKt1TYUs/edit

**Comment by violasong** [comment]
I'm planning to look into this (as well as the other things mentioned in this [Debugger UX doc](https://docs.google.com/document/d/1lrnEcvXaAFNTY-O4DGxdabMcUeGebkUtpuc5XTSOIj0/edit) starting next week - @jasonLaster, let me know if any one thing should be prioritized above anything else, especially if there's a release 60 deadline involved.

**Comment by jasonLaster** [comment]
Great! Happy to plan early next week

**Comment by jasonLaster** [comment]
I'm closing this as we'll tackle a bunch of it as part of the breakpoint ux
