### ISSUE TITLE
[ConditionalPanel] Use CodeMirror

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4117]
It would be really nice to have a snazzy editor in the conditional panel. We could re-use something like this for watch expressions too.

Here's the [branch](https://github.com/jasonLaster/debugger.html/tree/conditional-editor)

![](http://g.recordit.co/u720kh3aDz.gif)

**Comment by jasonLaster** [comment]
@jacobjzhang is working on it

**Comment by jasonLaster** [comment]
This commit shows how we can support keyboard shortcuts like enter/escape

https://github.com/devtools-html/debugger.html/commit/2485f7cd0fae45ad92bab342905fe3d81e6e105c

**Comment by jacobjzhang** [comment]
I started working on this again after a rough rebase. Going to land something by end of week.

**Comment by jasonLaster** [comment]
@jacobjzhang i'm taking your head off this. Feel free to re-claim it.

**Comment by jasonLaster** [comment]
I'm moving the issue to the icebox. We will re-prioritize the issues in the icebox at the beginning of the next release in 6 weeks.
