### ISSUE TITLE
Toolbox Favicon

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#412]
It'd be fun if we had a toolbox favicon. To be clear, this is not a user thing, but just a nice polish touch for developers who are working in local dev mode.

----

### 11/29 update

We had a favicon, which was broken when we moved the index.html to the toolbox. Lets fix it!

**Comment by jasonLaster** [comment]
@helenvholmes want to have fun with this?

**Comment by jasonLaster** [comment]
Also nice, but not important in the issue queue

**Comment by helenvholmes** [comment]
My recommendation would be the panel icon: https://cl.ly/0R3W3g1d2A0a

**Comment by Dalimil** [comment]
Is it OK to convert it to an .ico file first? Because SVG favicons seem to be only supported in Firefox at the moment ( http://caniuse.com/#feat=link-icon-svg )

**Comment by jasonLaster** [comment]
Yeah. Definitely

**Comment by Dalimil** [comment]
Did someone break the favicon path after swapping /index.html and /packages/devtools-local-toolbox/index.html ?

**Comment by jasonLaster** [comment]
yep - thanks for filing @Dalimil. Want to PR a fix?

**Comment by Dalimil** [comment]
I thought I would just be able to change line 92 (`app.use(express.static("assets/build"));`) of `/packages/devtools-local-toolbox/bin/development-server.js` but I'm unable to reach the favicon.png filepath for some reason.

**Comment by jasonLaster** [comment]
@Dalimil good thought.

my bet is that it would be easier if we move the favicon to a directory in the toolbox... 

not too much context here though, so your guess is as good as mine

**Comment by andreicristianpetcu** [comment]
@jasonLaster Can I get the next "easy" task? I see tasks are getting assigned imediatly after creation :)

**Comment by wldcordeiro** [comment]
As far as I can tell this work was already done.

**Comment by jasonLaster** [comment]
perhaps - @Dalimil mind PRing that fix?

**Comment by Dalimil** [comment]
@wldcordeiro It was but then the project structure changed and the favicon path stopped being valid and it disappeared again...
