### ISSUE TITLE
[SourceTree] Set root directory

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4121]
One of my biggest pet-pieves while debugging is that the source tree shows thousands of files, but in reality, I only care about one directory. 

It would be really cool if the user could right click on a directory, and select "Set Root Directory". 

Notes:

* We would highlight the root node in the UI
* Right click would have a contextmenu option to "reset the directory"
* We could persist the setting to prefs so it stays

Here is a [patch](https://gist.github.com/b8bed25cac5148cd116d7b6e813c69be) to start with.

### Before

<img src='https://shipusercontent.com/aaff08a521a45cac8a1819dd97274ac1/Screen%20Shot%202017-09-21%20at%208.43.48%20PM.png' title='Screen Shot 2017-09-21 at 8.43.48 PM.png' width=805>

### After

<img src='https://shipusercontent.com/461f988994f5fb2fc3e6bca114329d2b/Screen%20Shot%202017-09-21%20at%208.42.17%20PM.png' title='Screen Shot 2017-09-21 at 8.42.17 PM.png' width=761>

**Comment by jasonLaster** [comment]
aight, now we solve the tree: this test can be run with `jest --watch src/utils/sources-tree/tests/addToTree.spec.js`

```diff
diff --git a/src/utils/sources-tree/tests/addToTree.spec.js b/src/utils/sources-tree/tests/addToTree.spec.js
index 851410d..38aabf3 100644
--- a/src/utils/sources-tree/tests/addToTree.spec.js
+++ b/src/utils/sources-tree/tests/addToTree.spec.js
@@ -225,5 +225,46 @@ describe("sources-tree", () => {
       sources.forEach(source => addToTree(tree, source, domain));
       expect(formatTree(tree)).toMatchSnapshot();
     });
+
+    it("uses projectRoot to filter the list", () => {
+      const testData = [
+        {
+          url: "components/TodoTextInput.js"
+        },
+        {
+          url: "components/Header.js"
+        },
+        {
+          url: "reducers/index.js"
+        },
+        {
+          url: "components/TodoItem.js"
+        },
+        {
+          url: "resource://gre/modules/ExtensionContent.jsm"
+        },
+        {
+          url:
+            "https://voz37vlg5.codesandbox.io/static/js/components/TodoItem.js"
+        },
+        {
+          url: "index.js"
+        }
+      ];
+
+      const domain = "http://localhost:4242";
+      const sources = createSourcesList(testData);
+      const root = "components";
+      const tree = createNode("root", "", []);
+      sources.forEach(source => addToTree(tree, source, domain, root));
+
+      /*
+          - components
+            - TodoTextInput.js
+            - Header.js
+      */
+      console.log(formatTree(tree))
+      expect(formatTree(tree)).toMatchSnapshot();
+    });
   });
 });
```

**Comment by AnshulMalik** [comment]
Made some progress 

![t](https://user-images.githubusercontent.com/7821757/34213427-34749cf8-e5c5-11e7-921c-5a63a5784872.gif)

**Comment by jasonLaster** [comment]
Oh nice!
