### ISSUE TITLE
[Accessibility] Show a shortcuts modal

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4122]
It would be great from an accessibility perspective if we documented our shortcuts and mouse tricks:

* alt-click to continue to a location
* cmd*b to toggle a bp

Notes:

* we could have a button in the bottom right to launch the modal
* we could use this modal pattern for other things in the future
* we could share this modal w/ other tools so that other tools can have shortcut modals too :)

### Single Modal

<img src='https://shipusercontent.com/cde06027ecd2aba3422cd820a023f572/Screen%20Shot%202017-09-21%20at%209.27.27%20PM.png' title='Screen Shot 2017-09-21 at 9.27.27 PM.png' width=617>

### Modal w/ a sidebar

<img src='https://shipusercontent.com/b43011a5732568790f9700204935cf9f/Screen%20Shot%202017-09-21%20at%209.27.17%20PM.png' title='Screen Shot 2017-09-21 at 9.27.17 PM.png' width=571>

**Comment by violasong** [comment]
This looks great! I think I prefer the UI with the single modal - while the sidebar makes it look nicer, I suspect shortcut-hunting is easier when it's all laid out. 

I also recommend using the main body color and larger/darker icons - I only changed the first row but hopefully this is clear enough :).

<img width="852" alt="image" src="https://user-images.githubusercontent.com/55994/30822975-9ab5ff7c-a1df-11e7-80ee-7c486667a416.png">

**Comment by jasonLaster** [comment]
:fire:
