### ISSUE TITLE
Duplicate Scope Item

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4140]
Should the same object be displayed twice?  
<img width="1137" alt="duplicatescope" src="https://user-images.githubusercontent.com/46655/30774197-5ad73f0c-a044-11e7-8b27-eab9d76ed30e.png">

**Comment by jasonLaster** [comment]
no, that's pretty scary...

**Comment by jasonLaster** [comment]
closing as it will be solved in reps
