### ISSUE TITLE
[Outline] Include icons from DevIcons

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4141]
It would be sweet to use a consistent set of icons as Atom. This is a two step process:

1. setup a font-loader in webpack for base64 encoding fonts
2. pull in octicons

Here are some links

* https://github.com/atom/atom/blob/master/static/variables/octicon-utf-codes.less
* https://github.com/atom/atom/blob/master/static/octicons-2.1.2.woff
* http://fizzed.com/oss/font-mfizz
* https://vorillaz.github.io/devicons/#/dafont
* https://atom.io/packages/file-icons
* https://github.com/nicksrandall/base64-font-loader

**Comment by jasonLaster** [comment]
and here are the SVGs: https://github.com/vorillaz/devicons/tree/master/!SVG

**Comment by jasonLaster** [comment]
here are octicon icons: https://github.com/primer/octicons

**Comment by jasonLaster** [comment]
![Screen Shot 2017-10-10 at 10.12.12 AM.png](https://shipusercontent.com/8a4017ab19a653453c8dac52ff2fe486/Screen%20Shot%202017-10-10%20at%2010.12.12%20AM.png)

and here's where the octicons font lives: `/Applications/Atom.app/Contents/Resources/app/static`

i still think if we figureout which svg is used, we can use that...

**Comment by jasonLaster** [comment]
The goal here is to re-use atom's function and class icons:

<img src='https://shipusercontent.com/5538bde5840778578eafe03d5f71ad92/Screen%20Shot%202017-10-11%20at%201.51.34%20PM.png' title='Screen Shot 2017-10-11 at 1.51.34 PM.png' width=910>

**Comment by sarahlim** [comment]
Do you know what Atom plugins are in the screenshot above? I was hoping to inspect the webview, since I haven't had any luck finding those exact icons from [Octicons](https://octicons.github.com/) or [devicons](https://vorillaz.github.io/devicons/#/dafont). (Unless we don't actually need to get the same ones? But I'm having trouble finding plain lambda icons, too 😛)

**Comment by lukaszsobek** [comment]
Can this be closed, as the lambda issue is resolved or are we going for a full icon rework?
