### ISSUE TITLE
Add Telemetry probes

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4158]
We should add some baseline telemetry probes

* source selected (react component, minified, original file)
* add a bp on a react component, minified, original file

Links:
* [shared/telemetry](http://searchfox.org/mozilla-central/source/devtools/client/shared/telemetry.js)
* [toolbox](http://searchfox.org/mozilla-central/source/devtools/client/framework/toolbox.js#675)
* [docs](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/collection/histograms.html)
* [docs2](https://docs.telemetry.mozilla.org/concepts/data_pipeline.html)

**Comment by yurydelendik** [comment]
Can we also add one for source type enum used (e.g. wasm, ts, etc.)? (FWIW I care about only about wasm :)

**Comment by digitarald** [comment]
Related: Since we are slow on this one we can probably do directly to using event telemetry https://bugzilla.mozilla.org/show_bug.cgi?id=1415976

**Comment by codehag** [comment]
@digitarald @jasonLaster 

I'm working through the questions on the telemetry review document. What are we looking to do with the current telemetry probe that is being added? it seems to be related to source text load -- but this isnt part of the two tasks mentioned in this ticket:

 -  source selected (react component, minified, original file)
 -  add a bp on a react component, minified, original file

Are we timing how long source texts load for the average user? Could this better be achieved with our talos tests? should we rework this probe to be for the source selected?

We have a base pr, which is pretty good -- lets land it and break the two probes into their own prs and add the scalars as necessary

**Comment by ochameau** [comment]
> Could this better be achieved with our talos tests?
A common pattern is to have a telemetry probe and its equivalent on DAMP.
Telemetry allows to see what really happens on user computers, while DAMP helps tracking possible regressions. I see telemetry as a way to confirm that we don't ultimately regress thing silently with something being wrong in DAMP. It also help understanding what are the real world performance of an action in real usecases/computers.

**Comment by digitarald** [comment]
> I see telemetry as a way to confirm that we don't ultimately regress thing silently with something being wrong in DAMP.

Another way to put it is making it an iterative cycle; if we see Telemetry regress without any signal from DAMP; we know that our tests are not reflecting a major part of real life use cases.

> source selected (react component, minified, original file)

Risk with the current patch is that we get a multi-modal result and can't tell things apart. We know that load times heavily depend on the kind of source, so should probably include it from the start.

**Comment by digitarald** [comment]
> Risk with the current patch is that we get a multi-modal result and can't tell things apart. We know that load times heavily depend on the kind of source, so should probably include it from the start.

After letting that simmer for a moment we can have load times by type as a follow up probe. We have an idea but not a solid spec on how to bucket different types of file attributes at this time.
