### ISSUE TITLE
responsive design for sidebar layout

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#417]
We want the debugger to work well when there is limited horizontal space, like is the case for when the toolbox is mounted to the side instead of bottom. 

I did a quick hack to examine this.  The way our base structure is created with the splitters seems to make a responsive design difficult.  The approach I was thinking of was giving the splitter references only to the box we wanted it to affect and requiring the other boxes to use the flex layout.  This would allow us to use a flex row view which could wrap components like the sidebar around when space is tight.  While the splitter could still enforce a size requirement for the box.

Patch: https://gist.github.com/clarkbw/d6cb86ac6c071f781433a030cf115b61

![localhost-8000--firefox-tab tab1](https://cloud.githubusercontent.com/assets/2134/17112388/b8f5c088-525a-11e6-8d64-5743a8f72320.png)

**Comment by jlongster** [comment]
Honza is already working on the next version of the split box that will handle this. The split box should ideally handle this for us, otherwise it's not the most friendly API. I'd ask Honza how far along he is. If anything, we can do something like this but I'd prefer to evolve split box.

**Comment by clarkbw** [comment]
> If anything, we can do something like this but I'd prefer to evolve split box.

I think updating the split box to be better is the best route.  I'll touch base with @janodvarko on his progress so far.

Other next steps are working with @helenvholmes on a design for the debugger in this view.

**Comment by janodvarko** [comment]
@clarkbw, @jlongster : here is what I have so far, see live demo: http://janodvarko.cz/devtools/splitter.html/

It's built on top of the split-box from debugger.html + flex-box support. I don't have horizontal splitters yet, but vertical alignment works well I think.

Are there any other specific requirements?

Honza

**Comment by jasonLaster** [comment]
thanks @janodvarko. The vertical splitter looks great, I believe we want the same requirements for the horizontal splitter.

**Comment by clarkbw** [comment]
bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1260552

**Comment by clarkbw** [comment]
Wanted to include a screenshot of the Chrome layout for reference.

![screen shot 2016-07-25 at 10 39 49 am](https://cloud.githubusercontent.com/assets/2134/17988140/2a3f9e26-6ad9-11e6-96de-b2d8f4174e03.png)

**Comment by jasonLaster** [comment]
This is now actionable now that we have Honza's new splitter. 

@helenvholmes I'm re-assigning you so that we can have designs to go off of. I think Chrome's design is a safe default as we want things to be familiar to chrome devs. With that said, we should do the work to have an opinion on the portrait layout. We might want to talk about this in Toronto as we'll be in one place as well.

**Comment by jasonLaster** [comment]
This might be nice to budget for 53

**Comment by jasonLaster** [comment]
closing this issue and making a more actionable issue
