### ISSUE TITLE
GIT fetch is borked 

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4177]
Fetching from origin will currently throw an error

```
g clone https://github.com/devtools-html/debugger.html.git
git fetch origin
```

### Error

```
➜  Sep-26 g clone https://github.com/devtools-html/debugger.html.git
Cloning into 'debugger.html'...
remote: Counting objects: 24706, done.
remote: Compressing objects: 100% (28/28), done.
remote: fatal: unable to read 0ebec13c473c5ca7eda959606c71005c8c9521ec
remote: aborting due to possible repository corruption on the remote side.
fatal: early EOF
fatal: index-pack failed
```

* I can create new repo based on local master at [foobar](https://github.com/jasonLaster/foobar) and it works
* the github desktop app works w/ origin
* we can merge PRs and they're added to master
* i tried pushing another branch onto origin/master but it was still broken

**Comment by codehag** [comment]
I tried reproducing this and haven't been able to. is this still an issue?

**Comment by bomsy** [comment]
Yeah ... looks like its fixed!

**Comment by nyrosmith** [comment]
I had this problem in the morning. Need to check when I'm back on my PC

**Comment by nyrosmith** [comment]
Just checked. Now it works for me again

**Comment by clarkbw** [comment]
Glad its working again, not yet sure what happened.

**Comment by jasonLaster** [comment]
haha - yeah, i'd like to see if there was something that happened on the GH side
