### ISSUE TITLE
All Lines are treated as empty lines when paused

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#4182]
Steps to reproduce:
<img width="1051" alt="screen shot 2017-09-27 at 5 21 52 pm" src="https://user-images.githubusercontent.com/26968615/30922164-9c5deefa-a3a8-11e7-872c-c31dfb368b80.png">

1. Launch Firefox.
2. Access the https://devtools-html.github.io/debugger-examples/examples/todomvc/ webpage.
3. Open the debugger.
4. Open the todo-view.js file.
5. Add a breakpoint at line 34.
6. Add an todo item in the UI.

Expected:
The lines within scope to be enabled

actual:
all lines are treated as disabled

**Comment by bomsy** [comment]
@nyrosmith @codehag is this fixed?

**Comment by nyrosmith** [comment]
@bomsy yes. I tried it myself and @codehag also confirmed it on slack

**Comment by bomsy** [comment]
Cool .. nice! thanks!
