### ISSUE TITLE
Search on large code base hangs for 500ms when skipping to the next word

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4189]
Recorded when debugging https://pudding.cool/2017/03/hamilton/index.html and searching for `.arc`

Perf shows codemirror being the issue, just like #3988 : https://perfht.ml/2wWWuLc

![image](https://user-images.githubusercontent.com/8599/30930956-255f6408-a378-11e7-9439-39e98cbd45d5.png)

**Comment by jasonLaster** [comment]
@anshul is looking at it

**Comment by digitarald** [comment]
Another profile for just opening a file, causing 1s hang: https://perfht.ml/2wWIEsr

**Comment by jasonLaster** [comment]
Here is another example: [profile](https://perfht.ml/2yw0hjS)

STR:
- Go to netflix.com
- Open devtools debugger
- Find script codex.nflxext.com -> 2.0.0/truthbundle -> akira -> common/bootstrap.js
- Ctrl+F to search source code
- Type 's' 't'

Expected: Able to find strings in source
Actual: After first letter, the browser hangs until a slow script dialog pops up.

I see a lot of time in JS, but we should make sure we aren't doing something silly in debugger too.

BONUS: When the slow-script dialog appears, pressing the debug button will break your browser by leaving you in a nested modal state. Everything reflows correctly, but can't interact with the UI at all.

**Comment by jasonLaster** [comment]
closing as it's fast on netflix and i can't repro on https://pudding.cool/2017/03/hamilton/index.html 

STR:
- Go to netflix.com
- Open devtools debugger
- Find script codex.nflxext.com -> 2.0.0/truthbundle -> akira -> common/bootstrap.js
- Ctrl+F to search source code
- Type 's' 't'


![](http://g.recordit.co/32wOxagAzE.gif)
