### ISSUE TITLE
Sources root missing padding

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4190]
Somewhere along the line we lost that padding that should be to the left of the root element in the sources tab:

<img width="252" alt="wheredapadgo" src="https://user-images.githubusercontent.com/46655/30931370-1d66bfa0-a38a-11e7-97bb-b1fea6a07fde.png">

**Comment by bomsy** [comment]
@diessica excellentl!

**Comment by aagandhi1** [comment]
I'm a student at Seneca college learning open source, and I was hoping to work on this bug for my course.  If no one else is currently working on it, I'd like to give it a try.

**Comment by jasonLaster** [comment]
@aagandhi1 go for it. 

/claim

**Comment by aagandhi1** [comment]
Thanks
