### ISSUE TITLE
Issues from debugging session on Hamilton Data Vis

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4192]
Debugging https://pudding.cool/2017/03/hamilton/index.html hits a few issues. Goal is to find existing issues or file new ones with all the listed problems.

- [x] Super slow Debugger switching
- [x] Empty tab
- [x] No source map (or pretty print)

![Recording](http://g.recordit.co/uaLAUvm6JN.gif)

### Super slow Debugger switching

Debugger takes a looong time open … counting "One, two, three, four, five, six, seven, nine" …
    - Profile with `,Worker` does show the work happening in `parser-worker`: https://perfht.ml/2wXAhgb

When the debugger is opened directly is does *not* have the lag:

*(Recording opens `Debugger` from toolbar menu)*
![No lag](http://g.recordit.co/QKUXfdsC4i.gif)

### Empty tab

Last active is opened as tab but doesn't load, even after selecting the file in the source tree

### No source map (or pretty print)

Debugger doesn't apply source map `main.bf14fa95.js.map` to `https://pudding.cool/2017/03/hamilton/static/js/main.bf14fa95.js`

**Comment by jasonLaster** [comment]
![](http://g.recordit.co/08TtTXAGKt.gif)
![](http://g.recordit.co/GYD9wGVoAi.gif)
![](http://g.recordit.co/zDwGDBwnXO.gif)
![](http://g.recordit.co/2u2VV0LAEd.gif)
![](http://g.recordit.co/2u2VV0LAEd.gif)

**Comment by jasonLaster** [comment]
- I think switching is significantly faster. 
- Empty tabs is fixed
