### ISSUE TITLE
Pretty Print - Pretty printing a generated source

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#420]
Case:
+ a bundle file "a.js" has been source mapped, creating original files "b.js", "c.js"
+ user pretty prints "a.js" creating "d.js"

Use Case
* the user wants to see the bundle file prettified so that he can see what crazy babel transpiling is going on and debug that directly.

Problem:
+ do we support breakpoints in "d.js" (pretty bundle) and "b.js" and "c.js"? This might be difficult because two source maps point back to the same generated source. To be fair, this might just work, but we should test it.

**Comment by clarkbw** [comment]
Initial work could be to disable for now
