### ISSUE TITLE
Show full URL in source tab title

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4203]
Reported by bjv via https://discourse.mozilla.org/t/full-file-paths-on-hover-in-debugger/19664

**STR:** Open a file and hover the tab.

**ER:** Show the full URL

**AR:** Tab title currently repeats the tab title, including `…`.

<img width="455" alt="image" src="https://user-images.githubusercontent.com/8599/30992209-92329f74-a45d-11e7-83a4-60bd24a3d8dd.png">

(Marking as bug as the current title is rather useless)

**Comment by jasonLaster** [comment]
here's where the bug is

```diff
➜  debugger.html gls
diff --git a/src/components/Editor/Tabs.js b/src/components/Editor/Tabs.js
index b4df273..7748bd4 100644
--- a/src/components/Editor/Tabs.js
+++ b/src/components/Editor/Tabs.js
@@ -369,7 +369,7 @@ class SourceTabs extends PureComponent {
         key={source}
         onClick={() => setActiveSearch(source)}
         onContextMenu={e => this.onTabContextMenu(e, source)}
-        title={tabName(source)}
+        title={tabName(source)} // this is what needs to be changed
       >
         <div className="filename">{tabName(source)}</div>
         <CloseButton
```

**Comment by nyrosmith** [comment]
I am on it!

**Comment by ohana54** [comment]
I'm on it

**Comment by jasonLaster** [comment]
Thanks @ohana54
