### ISSUE TITLE
[Breakpoints] Page source isn't available in breakpoint triggered in refresh with a file URI

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4209]
STR:

1. go to this [site](https://bug1381571.bmoattachments.org/attachment.cgi?id=8887150)
2. Open Devtools > Debugger
3. Place a breakpoint on the alert()
4. Refresh the page

Observed Result:

The breakpoint is hit, but the source cannot be viewed or found in the sources list. I can't view what breakpoint has been hit, I can only hit continue until the page is loaded.

Expected Result:

The breakpoint is hit, and the source can be viewed allowing you to look at where the breakpoint is and perform debugging.

**Comment by eqrion** [comment]
Also from [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1381571#c2), this seems to only happen when using a `file:///` URI.

So to reproduce it, you have to view the page locally through `file:///`.

**Comment by lukaszsobek** [comment]
Is this still a thing? Seems to be behaving as expected now:
![klo9rpqulp](https://user-images.githubusercontent.com/23530054/31982910-1d69c060-b95b-11e7-98c1-9f0e16ce291b.gif)

**Comment by jasonLaster** [comment]
@lukaszsobek are you using the `file:///` prefix?

**Comment by lukaszsobek** [comment]
@jasonLaster Sorry, my bad - still broken on file protocol.

**Comment by codehag** [comment]
we should definitely address this, but I am not sure this should be a p1 -- it hasn't been touched since october last year, and the case isn't very common. The other p1s have a more significant impact on daily usage.

**Comment by jasonLaster** [comment]
I just tried to reproduce this and it seemed to work *fingers crossed*

STR:
1. download the root-breakpoint html file
2. open it at the file:// address for me it was file:///Users/jlaster/Desktop/root-breakpoint.html
3. add a breakpoint at alert
4. refresh

![](http://g.recordit.co/fWafGO9Ixe.gif)
