### ISSUE TITLE
Pretty Print  UX

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#421]
Found a couple of tweaks that will need to be made after the PR lands:

- [ ] formatted source should not be in the tree
- [ ] pretty print button should be "selected" in pretty source
- [ ] selecting the pretty print button should take you to the other source ugly -> pretty, pretty -> ugly

**Comment by jasonLaster** [comment]
@jbhoosreddy i think this might be a fun one for you. There's some interesting bits in here that need to be sorted out before pretty printing can land.

**Comment by jasonLaster** [comment]
Also, i noticed recently that selecting "pretty print" a second time causes an error, so there's a  bug in there too.

**Comment by jasonLaster** [comment]
@jbhoosreddy happy to take a stab at this today or tomorrow

**Comment by jbhoosreddy** [comment]
@jasonLaster. Please go for it. It'll take me some time before I'm able to
contribute again. I'll keep monitoring the changes. Thanks.
