### ISSUE TITLE
goto line functionality

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#4210]
a user has requested goto line functionality similar to the old debugger

something like adding `:100` in the search field to go to line 100

this should be easy to implement using the selectLocation functionality using the current source. 

### GIST

```diff
diff --git a/src/components/App.js b/src/components/App.js
index 1dd5132..ed7e64e 100644
--- a/src/components/App.js
+++ b/src/components/App.js
@@ -100,6 +100,13 @@ class App extends Component {
       L10N.getStr("symbolSearch.search.key2"),
       this.toggleSymbolModal
     );
+
+    // cmd g should toggle go to line
+    shortcuts.on(
+      L10N.getStr("symbolSearch.search.key2"),
+      this.toggleSymbolModal
+    );
+
     shortcuts.on("Escape", this.onEscape);
   }
 
@@ -143,6 +150,30 @@ class App extends Component {
     setActiveSearch("symbol");
   }
 
+  toggleGoToLineModal(_, e: SyntheticEvent) {
+    const {
+      selectedSource,
+      activeSearch,
+      closeActiveSearch,
+      setActiveSearch
+    } = this.props;
+
+    e.preventDefault();
+    e.stopPropagation();
+
+    // this is beautiful. we don't wan to topen if there is no source :)
+    // yay
+    if (!selectedSource) {
+      return;
+    }
+
+    if (activeSearch == "symbol") {
+      return closeActiveSearch();
+    }
+
+    setActiveSearch("line");
+  }
+
   onLayoutChange() {
     if (isVisible()) {
       this.setState({ horizontal: verticalLayoutBreakpoint.matches });
diff --git a/src/components/SymbolModal.js b/src/components/SymbolModal.js
index e515a1b..9db62fa 100644
--- a/src/components/SymbolModal.js
+++ b/src/components/SymbolModal.js
@@ -1,5 +1,10 @@
 // @flow
 
+// copy this file and re-name it to go to line
+
+// the key detail is that enter should call the action `selectSource` with the current
+// selected source and the line
+
 import PropTypes from "prop-types";
 import React, { Component } from "react";
 import { connect } from "react-redux";
```

**Comment by jasonLaster** [comment]
Agreed, lets find a good UI for this. Chrome uses `ctrl+g` which is the standard shortcut. They also use their modal, which is a good pattern here. I think they had an alert box until recently :)

<img src='https://shipusercontent.com/b39405c0a8f5e50717844c634f1f0fe6/Screen%20Shot%202017-09-29%20at%209.32.22%20AM.png' title='Screen Shot 2017-09-29 at 9.32.22 AM.png' width=978>

**Comment by nicofrand** [comment]
I'd like that (`:` triggering line mode, etc.) ! IMO `#` should trigger the function mode though, like before.

**Comment by codehag** [comment]
Yes, i was thinking this would be nice too

**Comment by svitlana-galianova** [comment]
Hi everyone! I am looking for my first bug and I am interested to contribute and explore React. I am wondering if this is a good idea to start on this one or would you recommend me some other bug to start with?

**Comment by jasonLaster** [comment]
@svitlana-galianova we're doing a meetup tonight, i think some people might start it then

**Comment by jfo** [comment]
/claim

at @jasonLaster 's suggestion I'm taking a look at this one, got a bit of a diff going, I'll update soon! Will likely have questions :)

**Comment by wldcordeiro** [comment]
This was landed. So I'm going to close it.

**Comment by nicofrand** [comment]
Sorry to comment on a closed ticket but I cannot find how to use this feature, with Firefox 58.0b4 (I was told this landed in Firefox 58) ?

**Comment by jasonLaster** [comment]
yep, `cmd+:`
