### ISSUE TITLE
Batch expressions wrapper

### ISSUE THREAD

**Issue by bomsy** [devtools-html/debugger.html#4212]
we can create a batch expressions wrapper like this:

```js
import { zipObject, zip } from "lodash";

export function wrapBatchExpressions(expressions) {
  const inputs = expressions.map(e => e.input);
  const wrappedExpressions = inputs.map(wrapExpression);
  return zipObject(inputs, wrappedExpressions);
}

  it("creates batch object", () => {
    console.log(wrapBatchExpressions([{ input: "foo" }, { input: 'foo"\\' }]));
  });
```

**Comment by codehag** [comment]
Looks interesting! what is the use case here? I might have missed some of the discussion :)

**Comment by jasonLaster** [comment]
if we can run the expressions in one batch, it will speed up the time it takes to evaluate. I'm not sure if this is a priority

**Comment by jasonLaster** [comment]
I'm going to close this as it's a nice to have, but not important at the moment. 

It'll be in #enhancements
