### ISSUE TITLE
[Editor] Update the look of matching brackets highlight for Photon

### ISSUE THREAD

**Issue by violasong** [devtools-html/debugger.html#4217]
To match Photon, it would be great to replace the old green outline of matching brackets to this blue background/underline styling instead:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/55994/31037084-1151a338-a524-11e7-933b-7b4db2649635.png">

This is a CM change and changes should be done in light-theme.css and dark-theme.css.

**Comment by belld19233** [comment]
/claim
testing

**Comment by tbrisker** [comment]
Looks like this change needs to be done in devtools-mc-assets, right?

**Comment by jasonLaster** [comment]
@tbrisker yep

**Comment by darkwing** [comment]
R+'d in Bugzilla (https://bugzilla.mozilla.org/show_bug.cgi?id=1446354), so this is done.
