### ISSUE TITLE
Watch expressions are easily hijackable

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#4220]
1. Load http://example.com/
2. Open the web console
3. Enter `eval = () => 0`
4. Open the debugger
5. Add a new watch expression: `1`

Result: `0`
Expected: `1`

**Comment by bomsy** [comment]
Oohhh ...Thanks for the report!

**Comment by jasonLaster** [comment]
Nice find @Loirooriol, this is a bug with the debugger server. You can see the same issue w/ the old debugger as well.

**Comment by Loirooriol** [comment]
Oh, I thought the culprit was #4107 because it wraps the expression in an `eval`.

**Comment by jasonLaster** [comment]
yep, good point... we do the same [thing][t] w/ the old debugger client as well.

[t]:http://searchfox.org/mozilla-central/source/devtools/client/debugger/debugger-controller.js#1184-1193

**Comment by jasonLaster** [comment]
so... this fixes it:


```diff
diff --git a/src/utils/expressions.js b/src/utils/expressions.js
index ec27dac..05e40e1 100644
--- a/src/utils/expressions.js
+++ b/src/utils/expressions.js
@@ -14,13 +14,13 @@ export function sanitizeInput(input: string) {
  * NOTE: we add line after the expression to protect against comments.
 */
 export function wrapExpression(input: string) {
-  return `eval(\`
+  return `
     try {
       ${sanitizeInput(input)}
     } catch (e) {
       e
     }
-  \`)`.trim();
+  `.trim();
 }
```
