### ISSUE TITLE
Watch expressions are vulnerable to injection

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#4223]
After #4107, creating a `null.foo` watch expression no longer pauses the debugger when in "Pause on uncaught exceptions" mode.

However, try `` ` + null.foo + ` ``. It pauses.

Or enter `}catch(e){}; 123; try{` and the result will be `123` instead of a syntax error.

**Comment by jasonLaster** [comment]
Hey @Loirooriol! Thanks for filing these watch expressions bugs.

Can you join our [slack](https://devtools-html-slack.herokuapp.com) so we can discuss
