### ISSUE TITLE
Disable All breakpoints

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#423]
We should support disabling all of the breakpoints. The button is already in there, it's the crossed out badge:

![screen shot 2016-07-26 at 3 07 51 pm](https://cloud.githubusercontent.com/assets/254562/17151712/978b9998-5342-11e6-829a-66a5b6fdc0ed.png)

I'm not sure how to do this yet:
+ In chrome there is a method `setBreakpointsActive`
+ In firefox, we might disable all of the breakpoints
+ There should be a pause reducer state like "breakpointsDisabled"

**Comment by clarkbw** [comment]
Just to throw my opinion in here, I feel that moving the button into the breakpoint container could make it more contextual than where it exists now.  I believe the reason it is up with the other buttons is for ease of access when you're stepping and want to disable break points to run to the end.

Here's where I'd place it instead:
<img width="307" alt="screen shot 2016-08-11 at 1 47 57 pm" src="https://cloud.githubusercontent.com/assets/2134/17604404/873838f0-5fca-11e6-949e-8ff419f164e8.png">

But I defer to @helenvholmes

**Comment by jasonLaster** [comment]
I think this is a nice tweak. 
If we agree on the design, I'd support doing it next sprint.

**Comment by helenvholmes** [comment]
I like @clarkbw's suggestion, looks good to me.
