### ISSUE TITLE
[PERF] optimize debug lines in the editor

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4236]
It looks like we're spending a lot of time in `setDebugLine` and `clearDebugLine`.

![](https://slack-imgs.com/?c=1&url=http%3A%2F%2Fg.recordit.co%2FbTIQXMmX6T.gif)

The way I'd debug this is to open [sensorWeb][s] w/ the launchpad and add `console.log` and `console.time` calls in those two functions and see where we're spending the time.

[s]:http://aws-sensorweb-static-site.s3-website-us-west-2.amazonaws.com/

**Comment by hughugsy** [comment]
Hey, can I work on this?

**Comment by jasonLaster** [comment]
@hughugsy sure.

This *fixes* it, but we should still try and keep the marked text. Perhaps the problem was the setState which would do an endless loop...

```diff
diff --git a/src/components/Editor/DebugLine.js b/src/components/Editor/DebugLine.js
index f92c616..7eab45f 100644
--- a/src/components/Editor/DebugLine.js
+++ b/src/components/Editor/DebugLine.js
@@ -17,6 +17,8 @@ export default class DebugLine extends Component {
     }
   };

+  debugExpression: Object;
+
   constructor() {
     super();
     this.state = { debugExpression: { clear: () => {} } };
@@ -57,19 +59,19 @@ export default class DebugLine extends Component {
     }

     doc.addLineClass(line, "line", "new-debug-line");
-    const debugExpression = markText(editor, "debug-expression", {
-      start: { line, column },
-      end: { line, column: null }
-    });
-    this.setState({ debugExpression });
+    // const debugExpression = markText(editor, "debug-expression", {
+    //   start: { line, column },
+    //   end: { line, column: null }
+    // });
+    // this.debugExpression = debugExpression;
   }

   clearDebugLine(selectedFrame: Object, editor: Object) {
     const { line, sourceId } = selectedFrame.location;
-    const { debugExpression } = this.state;
-    if (debugExpression) {
-      debugExpression.clear();
-    }
+    // const { debugExpression } = this;
+    // if (debugExpression) {
+    //   debugExpression.clear();
+    // }

     const editorLine = line - 1;
     const doc = getDocument(sourceId);
```

**Comment by sw-yx** [comment]
Hi, we tried debugging this today at ReactNYC:

We initially thought the issue was about clicking and unclicking the debug gutter line, but Jason clarified in person that the problem is actually the time it takes to arrive in the editor context relevant to a breakpoint. We were not able to replicate the long delay in a reasonable-sized react app but clarifying the issue here for future people tackling this
