### ISSUE TITLE
Fix greenkeeper

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#4238]
Our greenkeeper isn't working as well as expected and we should fix it

**Comment by jasonLaster** [comment]
We're getting this error:

![Screen Shot 2017-10-02 at 12.49.52 PM.png](https://shipusercontent.com/ce647a904c6e41c8293797f78b487846/Screen%20Shot%202017-10-02%20at%2012.49.52%20PM.png)

It comes from [here][h]. I just created a new GH_TOKEN to see if that'll help

[h]:https://github.com/greenkeeperio/greenkeeper-lockfile/blob/master/upload.js#L53

**Comment by jasonLaster** [comment]
I think this was fixed here https://github.com/devtools-html/debugger.html/pull/4222/files
