### ISSUE TITLE
Warn when showing original files that have been source mapped

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4241]
Follow up from #4192, I did not notice the *Webpack* domain. If users open a file that has was source-mapped into separate files; the debugger could give a hint to the user; with a link to the folder or the files that got extracted.

**Comment by jasonLaster** [comment]
We now show the generated source label to indicate where a file has been mapped from. We also have the webpack logo in the source tree.


<img src='https://shipusercontent.com/0c18620949a56a346f93534250f92561/Screen%20Shot%202018-01-15%20at%205.44.44%20PM.png' title='Screen Shot 2018-01-15 at 5.44.44 PM.png' width=732>
