### ISSUE TITLE
[PrettyPrint] breaks on JS inlined inside an HTML doc

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#4282]
Copied from https://bugzilla.mozilla.org/show_bug.cgi?id=1384675

[TypeError: lastToken is undefined pretty-print-worker.js:535:1]

The STR is roughly:
- Load gmail in Firefox nightly.
- Bring up the devtools, network tab.
- Find/wait for a POST to "/mail/u/0", select it.
- Select the Stack trace sub-tab on the right.
- The top line is maybe still named "Rq...".  Click on it.
- End up on the Debugger tab in a massive bunch of minified JS.  The tab header is some gibberish like "rs=ASDFQWERYTUIOP" and unless you scroll up, you won't notice you're in an inline HTML document.
- Right click on the tab and choose "pretty print source".
- Observe a failure to pretty print and no feedback other than the "lastToken is undefined" in the browser console.

It does seem pretty obvious that pretty printing the entirety of the original source doc including the HTML is not going to work out, at least not unless the pretty printer understands HTML too.  I guess at the time I was expecting that I would end up in the source as understood by the JS engine, not the raw document.  Maybe this bug should be morphed or duped to one like that?  The network panel's "stack trace" functionality is incredibly useful, and it would be even more incredibly useful if devtools could do that.

(Chrome parity-wise, they don't seem to have the "stack trace" functionality, but I can turn on logging XHRs.  In that case they only seem to log the top frame, and when I click on it I similarly end up in their "Sources" tab with the entire minified line highlighted, with the whole document displayed.  There is no offer to pretty print the file like is offered for a JS content type tab.)

**Comment by nchevobbe** [comment]
Here is another STR (not sure if it is exactly the same issue):

1. Go to [this page](data:text/html,<script>for(let i=0; i<10;i++) {console.log(i);}</script>Hello) 
2. Open the debugger
3. Open the only file in the source tree `script>Hello`
4. Notice there is no pretty print button, and the file shows the `<script>` tags as well as the "Hello" (user should expect to only have the script content)
5. Right-click on the tab, and select "Pretty print"

Expected Result: The file is pretty printed
Actual Result: Nothing happens and the following error appears in the browser console: 
```
uncaught exception: SyntaxError: Unterminated regular expression (1:50)
```

**Comment by nchevobbe** [comment]
See also https://discourse.mozilla.org/t/pretty-print-javascript-in-script-tags-in-a-webpage-ff-56-0-2/21087

**Comment by karlcow** [comment]
Just to raise the importance of this. 
When doing diagnosis of websites and specifically things like webapp which have a tendency to inject everything in one page (Cue google here), it becomes very hard to navigate the minified JS soup.

1. Go to https://google.com/
2. Search a term
3. Open debugger tool
4. Go to the `search` resource aka the HTML page.
5. Try to set a breakpoint 👺 or just read the code 🤡

**Comment by karlcow** [comment]
ping @digitarald ^^^ ;)

**Comment by jasonLaster** [comment]
Thanks @karlcow

**Comment by jasonLaster** [comment]
I'm going to move this to the icebox because we hope to improve how the server supports inline scripts in the next quarter. When that is done, we will be able to do this kind of work much easier. 

We have a similar issue for showing original inline scripts as well.
