### ISSUE TITLE
Optimize initial pause 

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4297]
We're currently optimizing stepping speed in #4284, but the initial pause is a special case that should also be investigated.

My theory is that we will do additional work on the first pause like parsing large scripts.

STR:
1. go to [perf-html][p] locally
2. add a breakpoint in TabBar.js#34
3. click "Timeline" or one of the other tabs

Observe that it takes awhile to pause

[p]:http://localhost:4242/public/fa1302b5668d67f1434932edd5fa60932d9895ac/markers/?hiddenThreads=&markerSearch=&range=2.1344_3.2600&react_perf&thread=5&threadOrder=0-2-3-4-5-1
[p2]:https://github.com/devtools-html/perf.html

NOTE: [perf-html][p2] is a great project that is easy to git clone, npm install, npm start :)

**Comment by jasonLaster** [comment]
i'm going to look into this and see if i can simplify

how / when we map scopes and get symbols

**Comment by yurydelendik** [comment]
Reduced test case for parsing https://yurydelendik.github.io/old-man-sandbox/babel-parse/index.html

**Comment by jasonLaster** [comment]
Here's the source: https://github.com/yurydelendik/old-man-sandbox/blob/master/babel-parse/package.json
