### ISSUE TITLE
[Scopes] Only show the local scope by default in the scopes pane

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4300]
We used to only expand the local scope when we paused. We now expand all the scopes. The problem is that means we slow down the stepping speed quite a bit to do a lot of renders. We also, show way more data than we need to the user!

```diff
diff --git a/src/components/SecondaryPanes/Scopes.js b/src/components/SecondaryPanes/Scopes.js
index b24ba5b..6d2f886 100644
--- a/src/components/SecondaryPanes/Scopes.js
+++ b/src/components/SecondaryPanes/Scopes.js
@@ -65,7 +65,8 @@ class Scopes extends PureComponent {
         <div className="pane scopes-list">
           <ObjectInspector
             roots={scopes}
-            autoExpandDepth={1}
+            autoExpandDepth={0}
+            {/* something else should be here too */}
             getObjectProperties={id => loadedObjects[id]}
             loadObjectProperties={loadObjectProperties}
             disableWrap={true}
(END)
```

![Screen Shot 2017-10-03 at 2.38.18 PM.png](https://shipusercontent.com/36ca2b17ccb601603aa1150a6ed636e3/Screen%20Shot%202017-10-03%20at%202.38.18%20PM.png)

**Comment by Loirooriol** [comment]
The render would probably be much faster if at each step you didn't remove all the scopes first and then redraw them all. So annoying.

**Comment by nyrosmith** [comment]
@jasonLaster is this done? The PR is merged...
