### ISSUE TITLE
[Scopes] Block variable differs from error/console variable

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4320]
STR:
- Break on exception on during the load of https://gregglind.github.io/x-shield-inflight-dashboard/
- See the exception `TypeError: e.approval_request is null`

ER: Scope shows `e`, Console holds `e` for debugging

AR: `r` in Scopes, `e` in Console

![image](https://user-images.githubusercontent.com/8599/31305253-303a98a6-aaea-11e7-8a54-2de351dc9295.png)

**Comment by jasonLaster** [comment]
I can't reproduce. Does it work for you?

**Comment by jasonLaster** [comment]
@digitarald could you try and reproduce?
