### ISSUE TITLE
Source tree item vs. tab context menu: "Copy source URI" vs. "Copy link address"

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4325]
The context menu items use different language for getting the full URI for a source:

* Right-clicking a source in the tree shows "Copy source URI"
* Right-clicking a tab in the tab listing shows "Copy link address"

For now, we should just make the two context menu items use the same label. 

In the future, we should share context menu items between the tab context menu and source context menu.

**Comment by lukaszsobek** [comment]
I'd take this one for a light start.

**Comment by jasonLaster** [comment]
@lukaszsobek next time you can `/claim` it :)

**Comment by jasonLaster** [comment]
I prefer `Copy source URI` because link is not clear...

**Comment by lukaszsobek** [comment]
What about the access key? If I move both over to `Copy source URI` the old `Copy link address` entry can be removed completely.

**Comment by jasonLaster** [comment]
sure!
