### ISSUE TITLE
[Breakpoints] show line text

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4326]
This is just a quick idea but ....

If you look at the breakpoint listing, it doesn't say much.  It shows you the file name and the line but, unless you're currently at that breakpoint, you don't really know what code is there.  

What if we did something like this:

<img width="298" alt="breakpointdetail" src="https://user-images.githubusercontent.com/46655/31317022-f2873e72-abfe-11e7-8a64-2dd025a48f9b.png">

What we'd need to feel for here is if this would cause too much bloat and scrolling to the breakpoint list.  I, however, would find this super useful.

**Comment by jasonLaster** [comment]
Thanks for filing @darkwing, i see this as part of the larger Breakpoints pane UX work we can do this quarter. I definitely agree we should show users the line the breakpoint is on.

In the past we've talked about grouping breakpoints by file as well. This might be a good time to bring this conversation back.


<img src='https://shipusercontent.com/dbf673127a6bb6ba8b58fb578a1f533f/Screen%20Shot%202017-10-08%20at%2011.03.04%20AM.png' title='Screen Shot 2017-10-08 at 11.03.04 AM.png' width=521>

**Comment by jasonLaster** [comment]
here is a gist to help get the ball rolling:

```diff
diff --git a/src/actions/breakpoints/addBreakpoint.js b/src/actions/breakpoints/addBreakpoint.js
index 2dfbb5c..5e19e30 100644
--- a/src/actions/breakpoints/addBreakpoint.js
+++ b/src/actions/breakpoints/addBreakpoint.js
@@ -7,6 +7,7 @@ import {
 } from "../../utils/breakpoint";
 import { getSource } from "../../selectors";
 import { getGeneratedLocation } from "../../utils/source-maps";
+import { getSourceLine } from "../../utils/source";
 
 export default async function addBreakpoint(
   getState,
@@ -26,6 +27,8 @@ export default async function addBreakpoint(
     sourceMaps
   );
 
+  const lineText = getSourceLine(source, location);
+
   assertLocation(location);
   assertLocation(generatedLocation);
 
@@ -57,7 +60,8 @@ export default async function addBreakpoint(
     location: newLocation,
     astLocation,
     hitCount,
-    generatedLocation: newGeneratedLocation
+    generatedLocation: newGeneratedLocation,
+    text: lineText
   };
 
   assertBreakpoint(newBreakpoint);
diff --git a/src/actions/breakpoints/syncBreakpoint.js b/src/actions/breakpoints/syncBreakpoint.js
index b00fc77..d1475ed 100644
--- a/src/actions/breakpoints/syncBreakpoint.js
+++ b/src/actions/breakpoints/syncBreakpoint.js
@@ -33,6 +33,9 @@ function createSyncData(
   const overrides = { ...pendingBreakpoint, generatedLocation };
   const breakpoint = createBreakpoint(location, overrides);
 
+  // we'll have to pass source in here
+  const lineText = getSourceLine(source, scopedLocation);
+
   assertBreakpoint(breakpoint);
   return { breakpoint, previousLocation };
 }
diff --git a/src/utils/source.js b/src/utils/source.js
index 97ee400..689b431 100644
--- a/src/utils/source.js
+++ b/src/utils/source.js
@@ -246,6 +246,10 @@ function isLoaded(source: Source) {
   return source.loadedState === "loaded";
 }
 
+function getSourceLine(source, location) {
+  return source.text.split("\n")[location.line - 1];
+}
+
 export {
   isJavaScript,
   isPretty,
```

**Comment by darkwing** [comment]
@jasonLaster YES!  This would be amazing!  👍

**Comment by jasonLaster** [comment]
Thanks @jordanch, just clarifying. This issue is just for showing the line. Please ask us questions in slack if something comes up!

**Comment by jordanch** [comment]
Yes, indeed. Thanks @jasonLaster

**Comment by jasonLaster** [comment]
Hey @jordanch just following up to see how it's going. Also, we invited you to our community team a couple weeks ago :) you should see the invite in your inbox

**Comment by jordanch** [comment]
Hi @jasonLaster - it's going, albeit slowly! 

Thank you! I received and accepted, woot!

**Comment by jasonLaster** [comment]
Great!

Out of curiosity, what have you learned so far about breakpoints? It's a complicated part of the project :)

**Comment by nyrosmith** [comment]
@jordanch are you still on it? It's no problem if you don't resume working on it

**Comment by jordanch** [comment]
@nyrosmith 

yeah, this is on my radar, im tackling it while learning redux in my Udacity course. 

I apologize ahead of time for picking a difficult issue that has taken me some time to PR although I thought it a decent practical challenge! 

I'm hoping to have something up in the next couple weeks.

**Comment by jasonLaster** [comment]
Hey @jordanch how's it going? can we help anywhere?

**Comment by jordanch** [comment]
Howsit @jasonLaster 

Swamped @ work. This is still on my radar! Thing's will be slowing down here in a couple weeks and then I'll have more capacity. Cool?

**Comment by jasonLaster** [comment]
closing this as we'll have a new issue for the awesome new breakpoints pane
