### ISSUE TITLE
Breakpoints should not toggle when clicking on the label

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#4334]
![debugger_breakpoint_label_toggle](https://user-images.githubusercontent.com/1141550/31382599-8694fc0c-adb8-11e7-8e58-defe3c4c929b.gif)

STRs:
- add a few breakpoints in a source
- click on the label of a breakpoint
ER: Editor should move to the breakpoint location, and breakpoint state should not toggle.
AR: Editor moves but the breakpoint state changes

Breakpoint state should only change when clicking on the checkbox. It's usually a good practice to link the label and the checkbox, but in this particular case, both result in separate actions so we shouldn't do that.

**Comment by bomsy** [comment]
Heya! @juliandescottes Where are you seeing this?

Looks like it has been fixed in master, but might not be released yet... cos i see it in nightly

![](http://g.recordit.co/6ILxntDhkA.gif)

**Comment by nyrosmith** [comment]
@juliandescottes @bomsy I think that was fixed with https://github.com/devtools-html/debugger.html/pull/4269

**Comment by bomsy** [comment]
oh cool ...nice! thanks.
Will close this!
