### ISSUE TITLE
Show Imagesize in preview popover

### ISSUE THREAD

**Issue by staabm** [devtools-html/debugger.html#4336]
the inspector shows a preview of a image and its resolution on mouse over.
would be great this popover would also indicate the filesize of the image (as file size matters, you know ;-))

In case you give me a hint into the correct direction I will try to fix it on my own.

FF58 Nightly screen (10/10/2017)

![grafik](https://user-images.githubusercontent.com/120441/31391385-a6a20b7a-add6-11e7-85be-286531cbe1c9.png)

**Comment by jasonLaster** [comment]
Hi @staabm, that's a great suggestion. I think you want to file this issue in bugzilla w/ this inspector though:

https://bugzilla.mozilla.org/enter_bug.cgi

**Comment by staabm** [comment]
oh my, I added a bug there a few months ago.

https://bugzilla.mozilla.org/show_bug.cgi?id=1369054

couldnt even remember it mysefl ;)
