### ISSUE TITLE
Debugger can't show sourcemapped sources for preact todomvc

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4342]
STR: Open Debugger and see Sources for `src/app/` on https://preact-todomvc.surge.sh/

AR: 
```
Error while fetching an original source: Error: "https://preact-todomvc.surge.sh/src/app/item.js" is not in the SourceMap.
Source URL: https://preact-todomvc.surge.sh/src/app/item.js
```

ER: Works in Chrome

**Comment by jasonLaster** [comment]
![](http://g.recordit.co/HqFgwQ3phz.gif)

**Comment by digitarald** [comment]
WFM now. When I had the issue, Console showed that it could not find the files referenced in the source maps.
