### ISSUE TITLE
[L10N] Hard-coded accesskeys

### ISSUE THREAD

**Issue by StoyanDimitrov** [devtools-html/debugger.html#4345]
This is the list of the hard-coded accesskeys I see in the Firefox UI.

[EditorMenu.js#L82](https://github.com/devtools-html/debugger.html/blob/cfe847a2b5dc14ebc1bae54c154e5a9320fc274d/src/components/Editor/EditorMenu.js#L82)

[EditorMenu.js#L89](https://github.com/devtools-html/debugger.html/blob/cfe847a2b5dc14ebc1bae54c154e5a9320fc274d/src/components/Editor/EditorMenu.js#L89)

[GutterMenu.js#L68](https://github.com/devtools-html/debugger.html/blob/cfe847a2b5dc14ebc1bae54c154e5a9320fc274d/src/components/Editor/GutterMenu.js#L68)

[GutterMenu.js#L82](https://github.com/devtools-html/debugger.html/blob/cfe847a2b5dc14ebc1bae54c154e5a9320fc274d/src/components/Editor/GutterMenu.js#L82)

[GutterMenu.js#L106](https://github.com/devtools-html/debugger.html/blob/cfe847a2b5dc14ebc1bae54c154e5a9320fc274d/src/components/Editor/GutterMenu.js#L106)

I think they should be migrated to l10zable ones to help with translation consistency.

**Comment by lukaszsobek** [comment]
Just went through the whole src folder, the ones you mentioned seem to be the only ones still hard-coded.
