### ISSUE TITLE
Update Labels

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4353]
Github is promoting two new labels: "Help Wanted" and "Good First Bug". Given the SEO value and recognizability, i think we should adopt them.

I propose we drop the `difficulty` labels in favor of "Good First Bug". Easy bugs are GFB, and the others medium/difficult should be killed. They just scare ppl.

`Available` bugs are our `Help Wanted` I think we can do a 1.1 swap here. If they're available, we'd love the help

**Comment by digitarald** [comment]
We should definitely hook into GH's services whenever possible. I wonder if they will provide aliases at some point, but as labels are freely editable we are not loosing information and the risk of changing is low.

As a follow up or on this, should we generally convert the label scheme to `Camel Case Text` (like `Code Health` ;) )?

**Comment by amitzur** [comment]
Feels like this can be automated with GitHub's API.
Also, notice it's "good first issue", not bug.

I agree that no newcomer is interested in the difference between difficulty medium and hard. If it also doesn't interest the veterans I'd remove it.

> As a follow up or on this, should we generally convert the label scheme to Camel Case Text (like Code Health ;) )?

well, according to https://help.github.com/articles/about-labels/ they use only lowercase in labels.

**Comment by digitarald** [comment]
> well, according to https://help.github.com/articles/about-labels/ they use only lowercase in labels.

Good catch (I also prefer find them more readable).

I am torn on how to manage well specified issues for the more advanced community vs marking things available for "beginners". We don't have too many bugs that are `available` and `medium/hard`; and the ones that are are not really well specified. `/claim` seems to solve these cases, to track assigning & progress. So maybe `good first bug` is all we need to replace `available`.
