### ISSUE TITLE
[Sources] Source Tree contents does not change

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4374]
The Source Tree uses `item.contents = source` to store the source record. Unfortunately, the record is immmuatble and therefore does not update when the source updates, for instance is pretty printed or blackboxed.

We should update this because the API is currently misleading

**Comment by lukaszsobek** [comment]
Is it a matter of changing `const` lo `let` on line 241 of SourcesTree.js?

**Comment by codehag** [comment]
since the record is immutable, the state saved on like 241 becomes stale, so changing it to let or const will not make a difference. The contents are set in addToTree, I suspect that what we need is a getter function rather than storing the state when the file is initially loaded. what do you think @jasonLaster? 

maybe something like this:

```javascript
// line 122 in addToTree.js
if (childNode) {
  const existingNode = node.contents[childIndex];
  existingNode.contents = { 
    getSource: () => getSource(source.id), // in case we need the full source (probably not often)
    getSourceProperty: (prop) => getSource(source.id).get(prop) // short hand so we dont have to write everything out
  };
}

// all future instances such as in SourcesTree.js will need to updated like so
const source = item.contents.getSourceProperty("url");
```

**Comment by jasonLaster** [comment]
@codehag that could work. I was thinking we could also just keep the source path and url in contents and get the source at render time... the advantage of this approach is then our tree becomes agnostic to what is stored in it... it doesn't have to be a source just an object w/ path and ID. 

but i'm good w/ anything here
