### ISSUE TITLE
debugger.css has different line feed code

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#4376]
**Steps to Reproduce:**
Open debugger.css using any editors (e.g. EmEditor)
_location: resource://devtools/client/debugger/new/debugger.css
omni.ja: chrome/devtools/modules/devtools/client/debugger/new/debugger.css_

**Actual Results:**
debugger.css has a different line feed code. (line: 2976 to 2987 using CR+LF)
![debugger_css](https://user-images.githubusercontent.com/13914314/31581710-62040994-b1ac-11e7-8263-f758ba6a02f2.png)

Firefox has no issues by this. But editor show line feed warning.

**Comment by nyrosmith** [comment]
This should be fixed via https://github.com/devtools-html/debugger.html/pull/4475
