### ISSUE TITLE
Breakpoints / jump to error in beautified source

### ISSUE THREAD

**Issue by jogibear9988** [devtools-html/debugger.html#4377]
It would be great if you can support setting (and hitting) breakpoints in source when it is beautified. Chrome for example supports this. 

Also when I click an error you jump to the minimized file. Maybe it is possible to make a additional jump to the line in the beautified file.

**Comment by jasonLaster** [comment]
I'm not sure what you mean:

We support adding breakpoints and pausing in pretty files

![](http://g.recordit.co/Xi5KKhJkJR.gif)
