### ISSUE TITLE
Investigate slow editor variable tooltip

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4387]
Recording of me trying to focus on the variable in the 2nd of the 3 lines:

https://www.dropbox.com/s/43ceuu5y5gxzsz5/2017-10-06%2016.47.35.mov?dl=0

I assume there is a slight hang when the tooltip is generated which doesn't take into account the latest position or when the mouse exists the hovered variable.

**Comment by digitarald** [comment]
A profile of the hanging (reproduced on this issue page, resulting in a [crash](https://crash-stats.mozilla.com/report/index/06ab93ff-033f-45b6-8535-0bf170171016) 😈, not the debuggers fault  ), showing massive GC issues and time spend in `findBestMatch`

Brainstorming a bit on a better heuristic:

- Show yellow highlight ASAP (could a light version even use CSS?)
- Debounce the tooltip by 100ms (to be tested)

**Comment by digitarald** [comment]
@jasonLaster 

- Could you give the profile a glance to look for other root causes that could make this issue actionable?
- What do you think about the idea of changing the heuristics? You mentioned concerns about delaying the tooltip?
- Might there are learnings from past optimizations to address the 3 issues identified?

**Comment by jasonLaster** [comment]
Good Idea. I was thinking about investigating the perf bugs (including opening the debugger) tomorrow

**Comment by jasonLaster** [comment]
This worked well for me when pausing in gmail

![](http://g.recordit.co/pCqDfGU35S.gif)

Feel free to re-open if you can reproduce a slow down.

**Comment by jasonLaster** [comment]
here's a recording https://perfht.ml/2FjuFWL
