### ISSUE TITLE
Pause Button Enabled by Default when No Breakpoints Set

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4392]
The pause button defaults to enabled upon debugger load despite no breakpoints set or 

<img width="249" alt="pausedefaultenabled" src="https://user-images.githubusercontent.com/46655/31641495-a36cac7a-b2aa-11e7-8752-00555d83746f.png">

I'm thinking this button should start out disabled.

**Comment by jasonLaster** [comment]
We're moving this button and watch expressions to a dropdown where it will be clearer
