### ISSUE TITLE
[Editor] Navigating to a new source should scroll the editor to the top

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4393]
STR:

1.  Open a source in the editor and scroll down.
2.  Open another source

In my instance, I scrolled to line 70, and when I opened another source, the editor scroll was at line 70.

When opening a new source, we should scroll the editor to the top.

**Comment by jasonLaster** [comment]
I'm guessing this is a recent regression that was triggered by our Editor lifecyle PR:

I thought this [test][t] exercised that.

[t]: https://github.com/devtools-html/debugger.html/blob/master/src/test/mochitest/browser_dbg-editor-highlight.js#L6

**Comment by lukaszsobek** [comment]
This seems to happen because the Editor uses the same editor tab to display the new content without resetting the line and column.

**Comment by jasonLaster** [comment]
Hmm, weird it should create a new document for the new source

**Comment by lukaszsobek** [comment]
It is a bug where the scroll state of the current window is preserved when opening a new one. I have the part with navigating a new window to the top done, but would love to handle the 4573 issue at the same time. However in order for that to happen we'd need #4832 to be taken care of.

**Comment by jasonLaster** [comment]
Yep. Although, this is a different patch so it could easily be two PRs.

**Comment by jasonLaster** [comment]
We like small PRs :)

**Comment by lukaszsobek** [comment]
Closing. Issue resolved apart from edge cases, which are already mentioned in another issue.
