### ISSUE TITLE
Conditional Breakpoint Weirdness

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4402]
STR:

1.  Right-click line 11, click "Add/Edit Conditional Breakpoint", but don't add any text

2.  Right-click line 17, click "Add/Edit Conditional Breakpoint", but don't add any text

3.  Click into the conditional breakpoint for line 11, type something, hit ENTER key.

The conditional breakpoint gets added for line 17, not line 11.

![conditionalbreakpointweirdness](https://user-images.githubusercontent.com/46655/31668297-715d3872-b317-11e7-8f9c-2e1d55511852.gif)

**Comment by darkwing** [comment]
Another detail:  when clicking the "x" on the remaining conditional bar, nothing seems to happen.

**Comment by nyrosmith** [comment]
@jasonLaster @darkwing I think we should just disallow multiple ConditionalPanels to be open at a time.
Would that be ok for you?

**Comment by nyrosmith** [comment]
The easiest fix would be close the ConditionalPanel on blur

**Comment by nyrosmith** [comment]
https://github.com/devtools-html/debugger.html/pull/4465 needs to land before this can be started
