### ISSUE TITLE
[console] "View source in Debugger links" from console open new view-source tab

### ISSUE THREAD

**Issue by miketaylr** [devtools-html/debugger.html#4411]
STR (I'm sure there are simpler ways, but this is what I'm working on right now...and I'm lazy)

1. Open RDM, select a Firefox for Android user agent, navigate to https://www.dxdelivery.com/contact/, and make sure touch is enabled
2. Paste the following into the console

```js
(function dbgEvtListeners() {
    ['click', 'touchstart', 'touchend', 'touchmove', 'mousedown', 'mouseup'].forEach(function(evt){
        window.addEventListener(evt, function(e){
            console.log(e, e.type, ' being sent to ' + e.target.outerHTML);
        }, true);
    });
    var origDispatchEvent = HTMLElement.prototype.dispatchEvent
    HTMLElement.prototype.dispatchEvent = function(evt) {
        console.trace('dispatchEvent! ', evt.type);
        return origDispatchEvent.call(this, evt);
    }

    console.log('evt debugging ready');
})()
```

3. click the how can we help you select
4. in the dispatch event! that was logged, attempt to click the `FastClick.prototype.onTouchEnd` link

<img width="671" alt="screen shot 2018-04-03 at 10 57 33 am" src="https://user-images.githubusercontent.com/67283/38260669-dd1fa05a-372d-11e8-96d5-3a9674cb7343.png">

Expected Results: the debugger opens up, with that file selected
Actual Results: A new tab opens up, `view-source:https://www.dxdelivery.com/bundles/js?v=iiRP9N8-72PtpkEQ7n5jKMWszbCFv30E6LC0LGGChME1%20line%201%20%3E%20eval`

<img width="1792" alt="screen shot 2018-04-03 at 10 57 40 am" src="https://user-images.githubusercontent.com/67283/38260698-f087f962-372d-11e8-921b-4a19b939dfe5.png">

(note: I think this behavior was mentioned in https://github.com/devtools-html/debugger.html/issues/3411, but I didn't see any open bugs about this specifically)

**Comment by jasonLaster** [comment]
hmm, @miketaylr I'm not seeing the error:

<img src='https://shipusercontent.com/324cf000b01cbc6d958def68fbdc1f4f/Screen%20Shot%202017-10-17%20at%207.06.00%20PM.png' title='Screen Shot 2017-10-17 at 7.06.00 PM.png' width=1429>

**Comment by jasonLaster** [comment]
sidenote, that's a delicious burger

<img src='https://shipusercontent.com/01a75c4cef5cdf39289a182f22000239/Screen%20Shot%202017-10-17%20at%207.07.47%20PM.png' title='Screen Shot 2017-10-17 at 7.07.47 PM.png' width=328>

**Comment by miketaylr** [comment]
> sidenote, that's a delicious burger

lol



> hmm, @miketaylr I'm not seeing the error:

Oops. One detail I left out, @jasonLaster:

You need a Firefox for Android UA string to get the bug to reproduce, because otherwise you won't hit the `dispatchEvent` code path that gets a `console.error`. So you have to add a custom device using "Mozilla/5.0 (Android 8.0; Mobile; rv:58.0) Gecko/20100101 Firefox/58.0" (or whatever).

(As an aside... I still think it's weird we don't send a Gecko UA in RDM by default, but whatever).

**Comment by miketaylr** [comment]
(and just verified this still reproduces in the latest nightly)

**Comment by codehag** [comment]
@miketaylr hi, I tried reproducing this and i am not seeing this. here is a screenshot of the log that i am seeing:

<img width="1303" alt="screen shot 2018-04-03 at 10 42 14" src="https://user-images.githubusercontent.com/26968615/38238942-b9dac2de-372b-11e8-9078-878e19822bc7.png">

It has been a while since this was reported, should we update the str to try to reproduce?

**Comment by miketaylr** [comment]
hi @codehag, yeah, the original STR don't work anymore. I guess maybe we removed `console.error` support or something? But it does still reproduce if you use `console.trace`, I update the original STR in https://github.com/devtools-html/debugger.html/issues/4411#issue-266207050. Thanks!

**Comment by joshunger** [comment]
I still see the error too.

**Comment by darkwing** [comment]
The view-source issue was fixed, I think this is good to go.
