### ISSUE TITLE
[PrettyPrint] pretty print button not available for scripts without file extensions (maybe?)

### ISSUE THREAD

**Issue by miketaylr** [devtools-html/debugger.html#4412]
STR:

1. navigate to https://www.dxdelivery.com/contact/
2. open debugger, and open https://www.dxdelivery.com/bundles/js in the sources

Expected: there should be a pretty print button so I can debug the script
Actual: no dice 😿 

The resource is pretty clearly JS (hence showing up in the debugger):

```
curl -I https://www.dxdelivery.com/bundles/js
HTTP/1.1 200 OK
Cache-Control: public
Content-Length: 106880
Content-Type: text/javascript; charset=utf-8
Expires: Wed, 17 Oct 2018 17:15:47 GMT
Last-Modified: Tue, 17 Oct 2017 17:15:47 GMT
Vary: User-Agent
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000; includeSubDomains
Content-Security-Policy: default-src https: data: 'unsafe-inline' 'unsafe-eval'
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-UA-Compatible: IE=Edge
node: svr13
Date: Tue, 17 Oct 2017 17:15:47 GMT
Set-Cookie: MySession-Cookie=!f2o/e1gVcTFc1EUGjNvgeuu+KbtciW7rg/F3xOVsjcENQTiZ5zpkej9T2mgQrVeozskzE1m744vcDt2dcz7EpYW7mdj4FQ/2Zdp/P17p8Mdrx+uQzCR6m4sGgLV2lDG6pyq4rbzCZSvSUYxfL9/s6obgv74wb0yUJT3vA4DoBX86xHwcBvs3aQJznzXnBmFQR9nB; expires=Wed, 18-Oct-2017 05:15:48 GMT; path=/
```

**Comment by bomsy** [comment]
Heya, @miketaylr It seems to work in nightly.
This is what i see, please confirm

![](http://g.recordit.co/XIXW21BhL5.gif)

**Comment by miketaylr** [comment]
Oh... that's silly. I should have tested in Nightly, I was in DevEdition. Thanks @bomsy!

**Comment by karlcow** [comment]
@miketaylr in case it happens again, ctrl+click on the tab of the script and you will get a magical menu :)
