### ISSUE TITLE
Right-Clicking a Conditional Breakpoint Container Shouldn't Show Context Menu

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4417]
<img width="488" alt="rightclickconditional" src="https://user-images.githubusercontent.com/46655/31698232-02ca1ec8-b382-11e7-878e-9764d364fa7e.png">

We should just let this fall through to the default context menu

**Comment by lukaszsobek** [comment]
hmmm, can't reproduce this on windows with the newest upstream:

![screenshot_1](https://user-images.githubusercontent.com/23530054/31876737-10287000-b7d4-11e7-8fc7-5cd02b710f45.png)

**Comment by jainsneha23** [comment]
Yes. Seems to be fixed in master. I can see this html:

`<div class="CodeMirror-linewidget" cm-ignore-events="true"><div class="conditional-breakpoint-panel">`

cm-ignore-events will ignore right click inside the conditional breakpoint panel

We can close this issue.

**Comment by jasonLaster** [comment]
@darkwing was this in the panel?
