### ISSUE TITLE
Context Menu Allowed to Render Offscreen

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4419]
If you right-click close enough to the bottom or right of the editor, its render can bleed offscreen:

<img width="601" alt="contextoffscreen" src="https://user-images.githubusercontent.com/46655/31698841-272eb190-b385-11e7-8bf8-49a557a531fb.png">

**Comment by wldcordeiro** [comment]
😆 I've run into this before. Nice find! I wonder if it also breaks out of the right edge of the window (or left in RTL mode)?

**Comment by jasonLaster** [comment]
this is only for the launchpad.
