### ISSUE TITLE
Editor footer background short in dark theme

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#4421]
I noticed that in the dark theme the footer background seems to end short on the bottom and right edges.
<img width="1609" alt="screen shot 2017-10-17 at 8 52 29 pm" src="https://user-images.githubusercontent.com/580982/31698920-2e1a4d0a-b37d-11e7-9fce-488124098518.png">

**Comment by pradeepgangwar** [comment]
@wldcordeiro I changed the CSS rule `position: absolute` to `position: sticky` for the footer. That fixed the problem for bottom and right space but created space on upper side. Please have a look.

![screenshot-2017-10-18 debugger](https://user-images.githubusercontent.com/21259802/31706576-07801870-b407-11e7-8f61-4d46bf5d0f2d.png)
