### ISSUE TITLE
Accesskeys for breakpoints menu items in main should not be hardcoded but localizable

### ISSUE THREAD

**Issue by Archaeopteryx** [devtools-html/debugger.html#4429]
Tested with Firefox 57.0b8 and checked the mozilla-central source where the issue also applies.

The main pane's left column with the line numbers has a context menu whose access keys are hardcoded:

toggle breakpoint: "B"
add a conditional breapoint: "C"
disabled breakpoint: "D"

These should be localizable (if the letters are not part of the words used like in German, they get shown after the command and that looks really weird).

**Comment by jasonLaster** [comment]
@Archaeopteryx i think this is coming from here, which looks localized: 
https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/GutterMenu.js#L35-L65

@nyrosmith @darkwing what do you think?

**Comment by Archaeopteryx** [comment]
Yes, thank you, fixed by #4378
