### ISSUE TITLE
Polish the function and source modal

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#4431]
It would be nice to polish both the function and source modal

- [ ] focused result item is off
- [ ] the drop shadow is too bright for dark theme

---

#### Source Modal

<img src='https://shipusercontent.com/51152219f24a16838270bc96d6931ade/Screen%20Shot%202017-10-18%20at%204.29.59%20PM.png' title='Screen Shot 2017-10-18 at 4.29.59 PM.png' width=1185>

#### drop shadow is too bright for dark theme

See screenshot below.

![image](https://user-images.githubusercontent.com/1141550/31740165-c008aef4-b450-11e7-8577-5c2ae67eced8.png)

The modal is using a boxshadow with a color set to --popup-shadow-color. 
For dark theme this is #5c667b :  
![image](https://user-images.githubusercontent.com/1141550/31740307-3cb23b1e-b451-11e7-8e5a-beaa6a03ef0f.png)

It might be a bit too bright for our current dark theme colors?

cc @violasong

**Comment by violasong** [comment]
Ah yes! The shadow should probably be black. We should also try these shadow specs from the design system: http://design.firefox.com/photon/patterns/shadows.html It's meant for light mode so the color/opacity is probably too subtle for dark mode. However I'd love to see the "Shadow 20" or "30" elevation here.

**Comment by wldcordeiro** [comment]
I'm going to close this issue but move the action items to the quick open follow-up issue.
