### ISSUE TITLE
Key shortcuts modal is hard to read in dark theme

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#4432]
See screenshot below:

![image](https://user-images.githubusercontent.com/1141550/31740374-73aba600-b451-11e7-83cc-1c687881b1ee.png)

The color of the keys is hard to read. The color used is var(--theme-body-color) from the `.shortcuts-list li` selector.  However since the keys have a light background, this text is hard to read (the color was set to be used on dark backgrounds).

Either use a darker color, or change the key background in dark theme.

**Comment by pradeepgangwar** [comment]
@juliandescottes Sir, let me know which combination would be better. I will try modifying it.

**Comment by juliandescottes** [comment]
@pradeepgangwar I think we should keep the keys white-ish. So let's use another color for dark theme. 

Can probably do something similar as what the accordion does:

https://github.com/devtools-html/debugger.html/blob/04918304796bd5912ba6958c4b48519f16cef1c7/src/components/shared/Accordion.css#L1-L7

**Comment by pradeepgangwar** [comment]
@juliandescottes I think I can't help here. Since I am running on a Linux machine and this is how my shortcuts modal looks like. 😇 

![screenshot-2017-10-20 debugger](https://user-images.githubusercontent.com/21259802/31832626-55c87ad8-b5e5-11e7-8606-930ee2214659.png)

**Comment by juliandescottes** [comment]
No worries @pradeepgangwar thanks for having a look :)

**Comment by ddinis-alves** [comment]
I'd like to try fixing this.

**Comment by juliandescottes** [comment]
@ddinis-alves thanks! I think you can use the [claim command](https://github.com/devtools-html/debugger.html#next-steps) to get assigned to the bug :)

**Comment by jasonLaster** [comment]
ping @ddinis-alves how's it going?
