### ISSUE TITLE
[Editor] is blank when devtools opens

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4437]
I'm seeing a blank editor when i open devtools w/ a selected tab.

STR:

1. go to [todomvc][t]
2. select todo-view.js
3. close devtools
4. re-open devtools

ER: see the source
AR: editor is blank

It would be nice to get a mochitest here

![](https://bugzilla.mozilla.org/show_bug.cgi?id=1409101)

[t]:https://bugzilla.mozilla.org/show_bug.cgi?id=1409101

**Comment by jainsneha23** [comment]
@jasonLaster Can you check if the bug still exists in master?

**Comment by jasonLaster** [comment]
hey @jainsneha23 this is a panel bug which is tough to debug. I recommend grabbing something else :)

**Comment by lukaszsobek** [comment]
So basically we want to preserve the state complete with focus and pretty printed tabs? How are we keeping the tabs across reloads now?

**Comment by lukaszsobek** [comment]
Issue opened here: https://github.com/devtools-html/devtools-core/issues/839

**Comment by lukaszsobek** [comment]
Issue should be fixed now @jasonLaster ?
