### ISSUE TITLE
Clicking from Console error to Debugger hangs 1+sec

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4440]
(Tested on a high end Windows laptop)

Opened Console on https://discourse.mozilla.org/t/things-i-miss-about-firebug/17233 and clicked on the ember notice. After I did this once, the source was open in Debugger. Even with the source open, the second click in Console did hang for 1+sec.

Maybe the Debugger does some unnecessary rendering?

https://perfht.ml/2xSKHTv

The 2 hangs in that segment are `selectSource` and `mapToPropsProxy`.

**Comment by michaelgv** [comment]
@digitarald I don't experience the same thing from my end. Were you running on latest?

**Comment by jasonLaster** [comment]
STR:
1. go to https://discourse.mozilla.org/t/things-i-miss-about-firebug/17233 
2. go to console and click on the error link

ER: go to line 17,771
AR: go to line 1

![screen shot 2017-11-09 at 7 36 42 pm](https://user-images.githubusercontent.com/254562/32636980-5d792afc-c585-11e7-81d3-162e1900835b.png)

it's not slow

**Comment by jasonLaster** [comment]
This will be faster with lazy-scripts, but we can still do better

**Comment by jasonLaster** [comment]
it's pretty fast now
