### ISSUE TITLE
[PrettyPrint] Add test to ensure original source and pretty printed outline tab functions match

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4443]
The sample URI I used was:

https://davidwalsh.name/wp-includes/js/wp-embed.min.js?ver=4.8.2

The outline tab for the original source shows:

```
c()
receiveEmbedMessage(c)
```

The pretty-printed outline tab shows:

```
"No functions"
```

Unless I'm missing something obvious, there's no real structure change between the two, so the Outline tab function listing shouldn't change.

**Comment by codehag** [comment]
this still needs a test
