### ISSUE TITLE
[Preview] Mis-judge the in-scope inner location as out-of-scope from its parent scope

### ISSUE THREAD

**Issue by Fischer-L** [devtools-html/debugger.html#4459]
STR:
1. visit http://todomvc.com/examples/react/#/active
2. add a bp in TodoModel.js#46
3. click toggle all in todomvc
4. step over to proceed to Line 50
5. hover `this` on Line 46

ER: see the preview of `this` on Line 46

AR: no preview of `this` on Line 46. See the gif below
![0pusqajliw](https://user-images.githubusercontent.com/5627487/31851735-3d6c88bc-b69e-11e7-98b6-07269e2a9d44.gif)

Root cause:
This issue was found during working on #4369 .
In the step 4, while getting out-of-scope locations[1], we have the bp position [2] and the location of `app.TodoModel.prototype.toggleAll` [3] and the location of the function arg for `this.todos.map` [4] (See [5] for the `toggleAll` method).

The location [4] now is considered out-of-scope by `containsPosition` because it doesn't contains the [2] position. This is correct from the view point of location-position relationship. As a result the Line 46 was totally ruled as out-of-scope.

The fix probably should be improve `getOutOfScopeLocations` function in handling this tricky scope thing such as concat comment locations, handling overlapping-inner location before calling `containsPosition` to do its job. (`containsPosition` did the right job and should keep focusing on location-position relationship)

[1] https://github.com/devtools-html/debugger.html/blob/c5177581a8af4b797f9aa56f82214216de0176c6/src/workers/parser/getOutOfScopeLocations.js#L86

[2] Object { sourceId: "server1.conn173.child2/source34", line: 50 }

[3]
```
{ // the location of `app.TodoModel.prototype.toggleAll` 
  end: Object { line: 51, column: 2 }
  start: Object { line: 41, column: 37 }
}
```
[4] 
```
{ // the location of the function arg for `this.todos.map`. Now will be filtered as out-of-scope
  end: Object { line: 48, column: 3 }
  start: Object { line: 46, column: 30 }
}
```

[5]
```js
 app.TodoModel.prototype.toggleAll = function (checked) {
	// Note: it's usually better to use immutable data structures since they're
	// easier to reason about and React works very well with them. That's why
	// we use map() and filter() everywhere instead of mutating the array or
	// todo items themselves.
	this.todos = this.todos.map(function (todo) { // Line 46
		return Utils.extend({}, todo, {completed: checked});
	});
       
        this.inform(); // Line 50
};
```

[6] https://github.com/devtools-html/debugger.html/blob/c5177581a8af4b797f9aa56f82214216de0176c6/src/workers/parser/utils/contains.js#L6

**Comment by Fischer-L** [comment]
working on this

**Comment by jasonLaster** [comment]
Nice write up. @ryanjduffy found this in v1 and we punted :)

It was harder then because we were using line out-of-scope classes. Thanks!

**Comment by Fischer-L** [comment]
> It was harder then because we were using line out-of-scope classes. Thanks!

Yes, this is tricky. We need some clean plus efficient approaches...

**Comment by jasonLaster** [comment]
How's it going?

**Comment by Fischer-L** [comment]
@jasonLaster 

Would like to know the previous discussion and have a discussion with you before proceeding, thanks. Below is my thoughts.

Checked out Chrome, looks like Chrome goes *call-stack* approach, which means as long as variables are visible from the bp's call stack (maybe closure variables, this etc), we still can preview on variables even inside far away functions, see Chrome Preview[3]. We not necessarily want to do that since probably the nearest enclosing function is the main focus and codes inside some far away functions don't matter during debugging.

#### Possible approach:
Here our topic is how to approach those functions inside the nearest bp-enclosing function. Consider the code example snippet below:
```js
// With the below partial example script, there will be a locations array as
// [
//   ... ...
//   { end: 8,  start: 6  }, // Location 1 before `processNums`
//   { end: 25, start: 12 }, // Location 2 within `processNums`
//   { end: 18, start: 16 }, // Location 3 within `processNums`
//   { end: 22, start: 20 }, // Location 4 within `processNums`
//   { end: 36, start: 29 }, // Location 5  after `processNums`
//   ... ...
// ]
// 
// If set a bp at Line 24, during debugging we might expect able to 
// preview on Location 2 ~ 4.

// Some other functions befoer `processNums`......

obj.prototype.processNums = function (nums) {    // Line 12

  let factor = 2;

  let offestNums = nums.map(n => {               // Line 16
    return n + this.offset;
  });                                            // Line 18

  let sum = offestNums.reduce(accum, n => {      // Line 20
    return (accum + n) * factor;
  }, 0);                                         // Line 22

  return this.doSth(sum);                        // Line 24 (bp)
}                                                // Line 25

// Some other functions after `processNums`......
```

The function locations array returned at [1] are ordered by the Start-Line-Ordering Logic[2].
So one possible approach is 
1. before filtering locations, let's find the nearest bp-enclosing function location, which is to loop locations to find the last location enclosing the bp. Assume we found it at index i. 
2. Then from index i, loop locations again, remove locations enclosed by locations[i] and stop looping once find the 1st location not enclosed by locations[i].
   After the step 1~ 2, the locations array in the above example will be like
    ```js
    // [
    //   ... ...
    //   { end: 8,  start: 6  }, // Location 1 before `processNums`
    //   { end: 25, start: 12 }, // Location 2 within `processNums`
    //   { end: 36, start: 29 }, // Location 5  after `processNums`
    //   ... ...
    // ]
    ```
3. Continue the rest of works. We will not mis-judge Location 3 & 4 as out-of-scope

#### Time complexity:
Assume the locations' length is n.

The step 1 costs n loops. The step 2 costs (n - i) loops. So the total loops are (2n - i).

With some optimization we could do i loops in the step 1. So the total loops could reduced to n.

Theoretically, the time complexity is linear.

#### Special common case:
Consider the code as below:
```js
(function () {                     // Line 1
  "user strict";

  // Some codes...

  let a = 1, b = 2;

  obj.doSth = function (n) {
    return Math.max(
      // The `this` here will not
      // be resolved to `obj`
      n + a + b, this._MAX);
  }

  // Some codes...

  let result = obj.doSth(100);    // Line 299 (bp)
})();                             // Line 300 (end of script)
```
In the above case, the whole script is in-scope. We basically fall into Chrome Preview mode.

At the bp Line 299, able to preview all variables(closure etc) visible on the call stack.

However, `this` inside `obj.doSth` will be resolved to that `this` for the bp Line 299, not `obj` or `undefined`.

This could be a special and common case.




[1] https://github.com/devtools-html/debugger.html/blob/c5177581a8af4b797f9aa56f82214216de0176c6/src/workers/parser/getOutOfScopeLocations.js#L84



[2] Start-Line-Ordering Logic: 
    locA is before locB if locA start line is before locB. If start lines are the same, locA is before locB if locA end line is after locB.



[3] Chrome Preview
![4459 _chrome_preview_scope](https://user-images.githubusercontent.com/5627487/32272650-01733662-becd-11e7-832c-53b3a06702d9.gif)

**Comment by Fischer-L** [comment]
@jasonLaster 

#### Special common case update:

The `this` resolution case may be considered as another thread or topic because it has to do with how we'd like to resolve `this`.

Consider this code example:
```js
  var global_variable = "I'm global";
  function exchange() {
    let currency = {
      _allowed: true,

      country: "GBP",

      exchange: function(usd) {

        let helper = {
          rate: 1.33,

          cal: function(usd) {
            if (currency._allowed) {
               // When previewing at the bp A,
               // in our devtool, `this` will be resolved to the global `window`.
               // in Chrome devtool, `this` will resolved to the `currency` object
               return this.rate * usd;
            }
            return -1;
          }
        };

        let gbp = helper.cal(usd); // Set a bp A here
        gbp && console.log(`Exchanged ${usd} to ${this.country} ${gbp}`);
      }
    };
    currency.exchange(100);
  }
```

When previewing at the bp A,

- in our devtool, `this` will be resolved to the global `window`, see [1] FF_THIS_RESOLUTION
- in Chrome devtool, `this` will resolved to the `currency` object, see [2] Chrome_THIS_RESOLUTION

Not sure if this is about the call stack resolution order, should look into that part for detail.

However, probably we could put this call stack resolution case to another thread.

[1] FF_THIS_RESOLUTION
![4459_ff_this_resolution](https://user-images.githubusercontent.com/5627487/32319695-72e0f1d8-bf89-11e7-9541-1d469409b8d2.gif)

[2] Chrome_THIS_RESOLUTION
![4459_chrome_this_resolution](https://user-images.githubusercontent.com/5627487/32319751-90e2c26a-bf89-11e7-8abc-2a77e8aa9e0f.gif)

**Comment by jasonLaster** [comment]
Thanks for the analysis @Fischer-L, 

```js
obj.prototype.processNums = function (nums) {    // Line 1
  let factor = 2;                                // Line 2

  let offestNums = nums.map(n => {               // Line 4
    return n + this.offset;                      // Line 5
  });                                            // Line 6

  return offsetNums;                             // Line 8 (bp)
}                                                // Line 9
```

If we pause on line 9, I would expect `offestNums` to be in scope, but `n` and `this.offset` to be out of scope. 

> `this` will resolved to the `currency` object

Lets look at this case later :)

**Comment by ryanjduffy** [comment]
Checking back (since I just noticed I was tagged last week) if there's anything I can do to help out on this issue. Not sure what is still outstanding at this point.

**Comment by Fischer-L** [comment]
Looks like the `this` resolution indeed is about another topic, see #4324

**Comment by jasonLaster** [comment]
I think we can close this. Is that correct @Fischer-L @ryanjduffy?

**Comment by Fischer-L** [comment]
> I think we can close this. Is that correct

@jasonLaster Yes, this is ok to close, thank you

**Comment by wldcordeiro** [comment]
Closing based on the comments above.
