### ISSUE TITLE
Improve config

### ISSUE THREAD

**Issue by jlongster** [devtools-html/debugger.html#446]
Jason and I talked and we're going to introduce a new `TARGET` env variable which specifies the desired environment. The main thing this will be used for is specifying that we are building for the Firefox panel, which changes a lot of stuff. So building it would be `TARGET=firefox-panel webpack`. I'm also going to look into using `nconf` or another system like that for the backend, and move our simple system to the client only. This gives us more control over a lot of the backend config (like ports and such) which is helpful for things like CI.

I'd like the concrete tasks to be done, but ~~I'm not exactly sure yet~~. I'll do some more research and update this issue/file a PR once I know more. Not going to spend much time on this; I'm going to try to land the bundle on Monday but some of this work is necessary for that.

This issue covers the following:

* [x] Use the `TARGET` env variable to detect if we're compiling for Firefox or not
* [ ] Research using nconf on the backend to manage configs and dump out a config object for the client
* [ ] Migrate our simple system all to the client, which reads values off of the given config structure

**Comment by jlongster** [comment]
So introducing `TARGET` was pretty easy: #447. I think this solves the config issues for the firefox panel, so I probably won't refactor the config system any more until later this week (if we want to look at nconf). I really want to get the bundle landed on Monday.

**Comment by jasonLaster** [comment]
@jlongster do you think we'll have time to look into this in this sprint or the next sprint? 

I think this might be something we want to punt on for now. 

I'm much happier now that we have a ci.json config as well.

**Comment by wldcordeiro** [comment]
@jlongster Is the env var `TARGET` wise? Seems like one other things might use as well Maybe something like `FXDEV_TARGET` just to not collide?

**Comment by jasonLaster** [comment]
We talked in #879 about revisiting the config system now that we're including Prefs. I propose we start the conversation here, but if the work is very different we close this ticket and open a new one.

**Comment by jasonLaster** [comment]
https://github.com/devtools-html/debugger.html/pull/879#discussion_r82065993

> Sure, that's fine. Honestly I think it might be good if we eventually just use the Prefs API itself. It basically works with json files, as far as I know, we can load in whatever json files locally we want. This way in the Firefox panel feature flags are real prefs, and you can toggle them on and off, which is how we've previously been able to with in the panel.

**Comment by clarkbw** [comment]
Closing this for now, we can reopen this later.
