### ISSUE TITLE
Right-click in editor window shows 2 context menus

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#4469]
* open editor window
* right click inside the text
2 context menus appear (debugger + default)
* press esc to hide one
* press esc to hide the other

![31880096-d33ad848-b7df-11e7-95e0-4673e8debf74](https://user-images.githubusercontent.com/23530054/31881679-8e5e9d40-b7e4-11e7-8aa5-c3c0e612b56a.gif)

Expected:
Only the debugger context menu shows

**Comment by jainsneha23** [comment]
@bomsy Please close the issue.
