### ISSUE TITLE
[Preview] fails to show a value

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4472]
Preview fails to show the value for `focusedHost`. The value is available in the scopes pane

![](https://bug1406048.bmoattachments.org/attachment.cgi?id=8920573)

CC https://bugzilla.mozilla.org/show_bug.cgi?id=1406048

**Comment by jasonLaster** [comment]
The next step is to create a small test case:

https://dbg.glitch.me/

should be easy to do that w/ the host.split function...

**Comment by bomsy** [comment]
https://glitch.com/edit/#!/join/bc65113f-8017-4677-85cf-e7c22a5c6da5

Interestingly, it looks like the issue is `this` is still pointing to the global scope rather than the invoking object

**Comment by jasonLaster** [comment]
oh we have an issue for that #4324

**Comment by jasonLaster** [comment]
lets close this as it's a dupe
