### ISSUE TITLE
Launchpad:  addComponentAsRefTo Error

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4479]
Every time I update to this repo's master to get the new patches, then do a `yarn install`, I see the following in the launchpad (http://localhost:8000):

```
Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).  invariant.js:42
```

I can `rm -rf node_modules && yarn nom` but this issue isn't going away so I presume there's a real problem somewhere.

**Comment by codehag** [comment]
this should be moved to the launchpad repo

**Comment by wldcordeiro** [comment]
Closing for issue in devtools-core
