### ISSUE TITLE
Cleanup test warnings

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4485]
When we converted to React 15.6 we started seeing some createClass test warnings:

>       Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

It would be great to clean those up.

![Screen Shot 2017-10-25 at 1.48.47 PM.png](https://shipusercontent.com/137006b8a591682345b14113ff44d041/Screen%20Shot%202017-10-25%20at%201.48.47%20PM.png)

**Comment by joel-bentley** [comment]
It looks like these warnings are from a known issue in React v15.6 when using `import * as React from 'react';`
https://github.com/facebook/react/issues/10583

The Facebook team decided not to fix since these warnings go away when switch to React v16.0

**Comment by joel-bentley** [comment]
So, the above is the case in only one instance `src/components/shared/Modal.js`

The rest of the errors are from `React.createClass` and `React.PropTypes` being used in the 
```
devtools-launchpad
devtools-splitter
devtools-components
```
packages, which are part of https://github.com/devtools-html/devtools-core. I could make a PR over there.

**Comment by jasonLaster** [comment]
@joel-bentley thanks that would be great
