### ISSUE TITLE
[Search] escape does not clear current highlight

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4490]
We just landed a new QuickOpen modal, which had a small regression w/ closing via the escape key [here](https://github.com/Garbee/debugger.html/blob/hotfix/test/src/components/QuickOpenModal.js#L209-L224)

STR:

1. go to a file w/ js functions
2. open modal cmd+shift+o
3. arrow key down to highlight a function
4. hit esc

ER should see the highlight go away

![Screen Shot 2017-10-25 at 3.47.00 PM.png](https://shipusercontent.com/b0d637bf7014559c2913aa004402b0fd/Screen%20Shot%202017-10-25%20at%203.47.00%20PM.png)

**Comment by wldcordeiro** [comment]
```patch
diff --git a/src/components/QuickOpenModal.js b/src/components/QuickOpenModal.js
index 91f58278..35379581 100644
--- a/src/components/QuickOpenModal.js
+++ b/src/components/QuickOpenModal.js
@@ -79,7 +79,6 @@ export class QuickOpenModal extends Component<Props, State> {
 
   closeModal = () => {
     this.props.closeQuickOpen();
-    this.props.clearHighlightLineRange();
   };
 
   searchSources = (query: string) => {
diff --git a/src/reducers/ui.js b/src/reducers/ui.js
index de0e51d6..06989e16 100644
--- a/src/reducers/ui.js
+++ b/src/reducers/ui.js
@@ -96,6 +96,7 @@ function update(
 
       return state.set("highlightedLineRange", lineRange);
 
+    case "CLOSE_QUICK_OPEN":
     case "CLEAR_HIGHLIGHT_LINES":
       return state.set("highlightedLineRange", {});
```

**Comment by wldcordeiro** [comment]
@lukaszsobek here's is a patch that should work.

**Comment by lukaszsobek** [comment]
@wldcordeiro Thank you!
