### ISSUE TITLE
Unfinished Conditional Breakpoints Linger Between Files

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4495]
1.  Open a source, right-click line 10, choose "Add conditional breakpoint", don't enter anything

2.  Open another source; the empty conditional breakpoint will display

This isn't something we want -- conditional breakpoint elements should be tied to a source.

**Comment by darkwing** [comment]
Another oddity:  flip back and forth between the two sources and empty conditional breakpoint elements multiply:

<img width="856" alt="conditionals" src="https://user-images.githubusercontent.com/46655/32032382-7a509e18-b9cc-11e7-978f-87ed5368ba64.png">

**Comment by nyrosmith** [comment]
Should be fixed with https://github.com/devtools-html/debugger.html/pull/4483
