### ISSUE TITLE
 Source Search Keyboard Focus Goes Offscreen

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4504]
With FIrefox DevTools panel up, when I use the Down key to scroll through the options of source search, if the list is long and the screen is short, I can scroll down but going past the the screen height of options doesn't keep those lsat items in view;  the items hidden by short screen height aren't shown.

We should ensure those hidden context menu items are shown when focused upon.

**Comment by jasonLaster** [comment]
@darkwing can you share a screen shot?

**Comment by lukaszsobek** [comment]
Screenshot from #4842 
![scroll_outofbounds](https://user-images.githubusercontent.com/23530054/33795181-daeb22e2-dcdc-11e7-98c2-4dcd9a5984c2.gif)

**Comment by lukaszsobek** [comment]
@darkwing @jasonLaster Do we want the size of the result list to stay the same as it is now (i.e. 80vh)?   There is also a min-height requirement of 340px in a media-query for the 80vh to kick in - not quite sure about the reason for that.

**Comment by jasonLaster** [comment]
I believe @codehag has some thoughts here.

@violasong what do you think?

**Comment by codehag** [comment]
I don't have much to add here, I am not sure what the decision behind 80vh was

**Comment by lukaszsobek** [comment]
Fix merged, closing issue.
