### ISSUE TITLE
File Search Shows Massive Document Icon

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4505]
I did Command+Shift+F and completed a search of ".name" on https://davidwalsh.name
and saw this:

<img width="853" alt="search1" src="https://user-images.githubusercontent.com/46655/32085567-87fed024-ba95-11e7-990e-70a70ace8323.png">
<img width="859" alt="search2" src="https://user-images.githubusercontent.com/46655/32085568-8a12eae4-ba95-11e7-9792-f95f94c9a943.png">

CSS error likely.

**Comment by jselmani** [comment]
@darkwing I'd like to work on this if that's alright with you.
