### ISSUE TITLE
Display network Response as plain text along with JSON

### ISSUE THREAD

**Issue by hanxue** [devtools-html/debugger.html#4509]
When there is a network response that returns JSON data, Devtool helpfully formats it in JSON

![image](https://user-images.githubusercontent.com/760008/32094927-04d9af76-bb34-11e7-820a-5cf4da2ae2a7.png)

But there is no easy way to copy the raw output. It is possible to right-click on the network request and copy the Response

![image](https://user-images.githubusercontent.com/760008/32095593-422d3bca-bb36-11e7-8be6-920d4c29fc2b.png)

That was not intuitive and took me some googling to find out. 

## Feature Request

Is it possible to add an extra `raw` or `plain text` tab, so the content can be easily copied?

Chrome's Devtool has a `Preview` tab which will apply formatting to JSON or HTML response, but there is also a `Response` tab that returns the raw output. 

![image](https://user-images.githubusercontent.com/760008/32095653-70c53186-bb36-11e7-9007-46f280353ce5.png)

**Comment by jasonLaster** [comment]
Hi, thanks for filing, but i believe this is a network panel proposal

http://bugzilla.mozilla.org/
