### ISSUE TITLE
String expressions.placeholder is reused in different contexts

### ISSUE THREAD

**Issue by flodolo** [devtools-html/debugger.html#4513]
Spotted in
https://bugzilla.mozilla.org/show_bug.cgi?id=1408562#c42

The original string was a [placeholder](https://github.com/devtools-html/debugger.html/blob/6660e0ddd273fb09e8b8a725a299a6f601279482/src/components/SecondaryPanes/Expressions.js#L182). It was then [reused](https://github.com/devtools-html/debugger.html/blob/4114a97f1584097c64d85b3d02e51946f4533caf/src/components/Editor/EditorMenu.js#L91) as a menu label with an accesskey.

That's not OK. Just because English has the same text in both contexts, it's not necessarily true for other languages, and will lead to poor translations in one of the two contexts.

The first symptom that you're doing something wrong is using a string called "placeholder" for a menu.

**Comment by wldcordeiro** [comment]
The links point to the same file and line?

**Comment by flodolo** [comment]
Ugh, sorry about that, clipboard failure. Updated the [first link](https://github.com/devtools-html/debugger.html/blob/6660e0ddd273fb09e8b8a725a299a6f601279482/src/components/SecondaryPanes/Expressions.js#L182).
