### ISSUE TITLE
[Editor/QuickOpen] When you use symbol or go to line functionality the gutter disappears

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#4515]
STR

1. Open quick open modal (<kbd>cmd</kbd>+P)
2. Search symbols in file `@`
3. Pick a result and hit enter
4. The gutter disappears

Note that clicking in the gutter area makes it reappear. The steps above also have the same result if you do a go to line query `:32` rather than `@`

**Comment by lukaszsobek** [comment]
@wldcordeiro - Is this still the case?

Tested on:
Opera Version: 49.0.2725.39
Ubuntu Kylin 17.10 (x86_64; ubuntu:GNOME)

Video:
![disappearing-gutter](https://user-images.githubusercontent.com/23530054/33599941-0d2d2652-d9a8-11e7-859c-2f82c3608f0f.gif)

**Comment by wldcordeiro** [comment]
Double checked and this is no longer happening. Thanks @lukaszsobek
