### ISSUE TITLE
Breakpoint is set, but not visible

### ISSUE THREAD

**Issue by yurydelendik** [devtools-html/debugger.html#4519]
STR (in Nightly):

1. Open devtools on the Debugger tab
2. Load https://mdn.github.io/webassembly-examples/js-api-examples/memory.html in the current tab.
3. Set a breakpoint before the ‘i32.load’ operation.
4. Reload the page.
5. Observe paused location.

Actual result:
On step 3, the breakpoint disappears; and on step 5, still not visible (even if it was paused)

Expected:
The breakpoint is visible and listed in the breakpoints panel

**Comment by yurydelendik** [comment]
I still can observe this issue in the nightly

**Comment by wldcordeiro** [comment]
Not sure the status here. I see two merged PRs @yurydelendik could you update?

**Comment by yurydelendik** [comment]
We can close it as fixed by #4817 -- there was issues that prevented to verify it.
