### ISSUE TITLE
[Project Search] Closing Find window does not remove results from memory

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#4526]
STR + AR:
- go to [this page](https://developmentarc.gitbooks.io/react-indepth/content/life_cycle/update/postrender_with_componentdidupdate.html)
- select gitbook.js
- press ctrl/cmd+shift+f in editor window
- type in "input" and press enter
- wait for results to appear
- close find window by pressing x
- press ctrl/cmd+shift+f again
- wait ...
- find window appears after a long delay with results from previous search 

ER:
- find window opens with an empty state

**Comment by wldcordeiro** [comment]
@lukaszsobek Thanks for the report! Just FYI it's nice to include the UI component in question in the issue title. I wasn't sure if this was for file search (cmd+f) or project search (cmd+shift+f) so I've updated the title.

**Comment by lukaszsobek** [comment]
@wldcordeiro Thank you! Will mention it next time.

**Comment by princiya** [comment]
@wldcordeiro again, trying to understand the whole structure for the `search`. I am able to reproduce this bug and I want to take up this issue. Please assign it to me :)

I want to make sure, when the `close` button is clicked, the `state` is set right. In my attempt to debug, can you please help me figure out where is [this](https://github.com/devtools-html/debugger.html/blob/master/src/components/App.js#L14) function being declared? I don't see it in `selectors`.

**Comment by princiya** [comment]
Oops, I see the issue is being claimed. Never mind, but please help me understand the source for that function :)

**Comment by wldcordeiro** [comment]
@princiya I think you can most easily see this by using the project search, closing the tab/view and then investigating the store via something like the redux-devtools to see that the contents aren't cleared.

**Comment by lukaszsobek** [comment]
@princiya it's yours for taking!
