### ISSUE TITLE
[Parser] Parse destructured variable names

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#4530]
Somewhat of a follow up to #3239 

<img width="1920" alt="screen shot 2017-10-29 at 11 45 17 pm" src="https://user-images.githubusercontent.com/580982/32156510-89222b5c-bd03-11e7-80d7-9cfef678042f.png">

If you notice there are two empty named results in the symbol list that map to expressions like

```js
const { a, b } = this.props
```

We should parse these kinds of expressions and add entries for each of the variables.

**Comment by jasonLaster** [comment]
Lets add a code sample and test for this. it'll be a great AST issue to share on twitter

**Comment by AnshulMalik** [comment]
Am I going the right way ?

![a](https://user-images.githubusercontent.com/7821757/33164334-47385d7a-d058-11e7-8d7e-1316a4d6bca5.gif)

```diff --git a/src/workers/parser/getSymbols.js b/src/workers/parser/getSymbols.js
index 89ac6505..a7daa86a 100644
--- a/src/workers/parser/getSymbols.js
+++ b/src/workers/parser/getSymbols.js
@@ -71,10 +71,19 @@ function getVariableNames(path: NodePath): SymbolDeclaration[] {
     }));
   }

-  return path.node.declarations.map(dec => ({
-    name: dec.id.name,
-    location: dec.loc
-  }));
+  return path.node.declarations.map(dec => {
+    if (dec.id.type == "ObjectPattern") {
+      return {
+        name: dec.init.name,
+        location: dec.init.loc
+      };
+    }
+    return {
+      name: dec.id.name,
+      location: dec.loc
+    };
+  });
+
 }
```

**Comment by jasonLaster** [comment]
Yep, looking good @AnshulMalik. Tests will help a lot here.

**Comment by nyrosmith** [comment]
Closing as it seems it already landed
