### ISSUE TITLE
Update the mapDispatchToProps calls for our components

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#4532]
Currently most of our `connect()` calls look like this.

```js
function mapStateToProps(state) {
  const selectedSource = getSelectedSource(state);
  let symbols = null;
  if (selectedSource != null) {
    symbols = getSymbols(state, selectedSource.toJS());
  }
  return {
    enabled: getQuickOpenEnabled(state),
    sources: formatSources(getSources(state)),
    selectedSource,
    symbols: formatSymbols(symbols),
    query: getQuickOpenQuery(state),
    searchType: getQuickOpenType(state)
  };
}

export default connect(mapStateToProps, dispatch =>
  bindActionCreators(actions, dispatch)
)(QuickOpenModal);
```

It'd be a lot nicer if we updated the second argument from `dispatch => bindActionCreators(actions, dispatch)` to something like this.

```js
function mapStateToProps(state) {
  const selectedSource = getSelectedSource(state);
  let symbols = null;
  if (selectedSource != null) {
    symbols = getSymbols(state, selectedSource.toJS());
  }
  return {
    enabled: getQuickOpenEnabled(state),
    sources: formatSources(getSources(state)),
    selectedSource,
    symbols: formatSymbols(symbols),
    query: getQuickOpenQuery(state),
    searchType: getQuickOpenType(state)
  };
}

const actionCreators = {
  selectSource,
  setQuickOpenQuery,
  highlightLineRange,
  closeQuickOpen,
}

export default connect(mapStateToProps, actionCreators)(QuickOpenModal);
```

This way our components will only have the action creators available to them that they need (making things like the React devtools easier to use) and because Redux automatically binds an function map we won't need to bring `bindActionCreators` into each file.

One problem here though is that since we have this ESLint rule (`"no-shadow": 2`) enabled we'll run into errors from shadowing the function names, we could disable this rule though.

**Comment by Fischer-L** [comment]
Just update the issue status: the merged PR #4640 is the start. Next there will be more PRs coming. And in each PR, probably better to touch one component and derived components at once. So lower risk and easier to review.

**Comment by Fischer-L** [comment]
/unclaim
As the team's discussion [1], the current approach is fine.
[1] https://github.com/devtools-html/debugger.html/pull/4859#issuecomment-353219834

**Comment by darkwing** [comment]
I believe this is complete.
