### ISSUE TITLE
"Remove breakpoint" in CodeMirror doesn't work on commented out line

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#4534]
**Steps to reproduce:**
1. Navigate to "about:debugging"
2. Load temporary add-on in local. (e.g. apply-css https://github.com/mdn/webextensions-examples/tree/master/apply-css)
3. Click Debug button.
4. Add breakpoint in background.js (e.g. line 14)
5. Edit "background.js" in local, and comment out line 14.
6. Click Reload button on about:debugging page.
7. Remove breakpoint in CodeMirror.

![remove-breakpoint-on-commented-out-line](https://user-images.githubusercontent.com/13914314/32162578-d320a91a-bd9c-11e7-8f5b-9114aa6e9eb7.png)

**Actual Results:**
"Remove breakpoint" doesn't work in CodeMirror
(But, it works on breakpoints pane)

**Expected Results:**
"Remove breakpoint" works even if on commented line.

**Comment by jasonLaster** [comment]
thanks @sharathnarayanph, would be great to make it easy to remove regardless of comment :)

**Comment by wldcordeiro** [comment]
Looks like the fix landed, closing.
