### ISSUE TITLE
Improve parsing speed

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4542]
Reduced [test case][t] for parsing [source][s] 

It is likely that babel 7 will help us, if not we can see if we can land some perf fixes to babel.

[t]: https://yurydelendik.github.io/old-man-sandbox/babel-parse/index.html
[s]: https://github.com/yurydelendik/old-man-sandbox/blob/master/babel-parse/package.json

**Comment by jasonLaster** [comment]
CC @wldcordeiro

**Comment by AnshulMalik** [comment]
Tried to test babel 7 out, though I didn't get positive results, 
https://github.com/AnshulMalik/debugger.html/tree/babylon-7

**Comment by jasonLaster** [comment]
Here are the steps to reproduce

```
yarn
jest src/utils/tests/ast.spec.js
```

**Comment by jasonLaster** [comment]
closing as it's not clear perf will get better if we bump to 7.
