### ISSUE TITLE
[WelcomeBox] is too low-contrast

### ISSUE THREAD

**Issue by bzbarsky** [devtools-html/debugger.html#4544]
This is the "Cmd-P to search for sources" and the like text.

The background here is rgb(249, 249, 250), looks like.  The text color is rgb(204, 209, 213).

Running through the basic calculations at https://www.w3.org/TR/AERT/#color-contrast (and note that these colors are all gray, so really color brightness is all that matters), we have a brightness of 249 for the background and a brightness of 207 for the foreground, for a brightness difference of 42.  The minimum recommendation for brightness difference is 125.

(That said, if you compute the color difference in this case, per the formulas on the linked page, that's 112, which is also way lower than the recommended minimum of 500).

**Comment by jasonLaster** [comment]
Here are some screenshots:

<img src='https://shipusercontent.com/0976c23fb036567aea6ab8a55e3231ac/Screen%20Shot%202018-01-25%20at%201.35.03%20PM.png' title='Screen Shot 2018-01-25 at 1.35.03 PM.png' width=508>

<img src='https://shipusercontent.com/fb3781086aa3a0acfbd26ba9955cc729/Screen%20Shot%202018-01-25%20at%201.34.59%20PM.png' title='Screen Shot 2018-01-25 at 1.34.59 PM.png' width=351>

**Comment by violasong** [comment]
Should match the colors of the other panels like so:

- File search keyboard shortcuts, other important elements like Modifiers buttons, source tree icons: var(--theme-body-color)
- Input placeholder color: Gabe says if .search-field input::placeholder is changed to black like the other panels, it will apply the right translucency to match.

**Comment by ericawright** [comment]
@violasong 
<img width="853" alt="screen shot 2018-01-30 at 2 43 50 pm" src="https://user-images.githubusercontent.com/10803178/35587602-486811be-05cc-11e8-81a7-ada6d11a4427.png">
<img width="621" alt="screen shot 2018-01-30 at 2 44 00 pm" src="https://user-images.githubusercontent.com/10803178/35587600-4692a3ae-05cc-11e8-9321-cb26c58bb05a.png">

this is the current result - is the "modifiers" section a bit too dark? and did you want the search icon and "x" to also be darker? What about the x in the file tab?

@jasonLaster Also, is there a way I can see it in in dark theme, or do I have to run it with a firefox build for that?

**Comment by jasonLaster** [comment]
@ericawright you can go back to the launchpad and then settings

**Comment by jasonLaster** [comment]
also seems a bit dark here

**Comment by violasong** [comment]
Ah I love the placeholder, but the other parts do look dark. I think --theme-body-color results in Gray 60 (rgb(74, 74, 79)) in some places in the Inspector, but maybe it's set differently in the Debugger?

**Comment by jasonLaster** [comment]
oh yeah - it's also possible that we need to update the variables.css to reflect the correct value of theme-body-color or gray 60...

**Comment by jasonLaster** [comment]
my guess is that this would look good if we exported to firefox :/

**Comment by violasong** [comment]
And yes, great question regarding the x buttons! There's a Gray-40 var(--theme-body-color-alt) that would look good for these, I think!

**Comment by violasong** [comment]
In the sidebars, the pale disclosure arrow icons, plus button icon, and "add watch expression" text should probably be theme-body-color-alt as well.

**Comment by ericawright** [comment]
@jasonLaster, I don't think it's a variable thing, just changed the same variables in FF and it's the same result.
![screen shot 2018-01-31 at 10 33 48 am](https://user-images.githubusercontent.com/10803178/35631606-4be66c40-0672-11e8-8d96-47c2ac56b8ae.png)

(though the x on the file tab looks darker - I had nothing to do with that)

**Comment by jasonLaster** [comment]
good to know!
