### ISSUE TITLE
Watch expressions should use their own packet for evaluation

### ISSUE THREAD

**Issue by jimblandy** [devtools-html/debugger.html#4555]
It would simplify the debugger client for the pause actor to accept a request tailored for evaluating watch expressions. This packet would take an array of source expressions, and return an array of completion values. The packet would disable pause-on-exception behavior, and handle breakpoint hits by terminating evaluation of the expression, and reporting the hit, perhaps as an additional sort of completion value.

At present, watch expressions use the same mechanism as the console, which wants pauses for exceptions and breakpoints to show up in the debugger UI. Giving watch expressions a request of their own would make it easier to accommodate both uses.

cc @jasonLaster

**Comment by bomsy** [comment]
@jimblandy is this a mentorable issue? Would love to try to do the work with your guidance if possible.

**Comment by jasonLaster** [comment]
I think I can help as well. It'd be fun to document the feature too so others see how we can add a new endpoint.

**Comment by bomsy** [comment]
Ok cool! Will love to do all that.

**Comment by jasonLaster** [comment]
I'm moving the issue to the icebox. We will re-prioritize the issues in the icebox at the beginning of the next release in 6 weeks.
