### ISSUE TITLE
[QuickOpen] `?` should show options

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4560]
VS Code and Chrome do a great job of showing possible commands with `?`

We should do the same thing. 

<img src='https://shipusercontent.com/ceb5b7d6c605f16aacf7a6a78c2fe651/Screen%20Shot%202017-11-02%20at%2012.21.21%20PM.png' title='Screen Shot 2017-11-02 at 12.21.21 PM.png' width=731>

---

<img src='https://shipusercontent.com/52a47f22149ce874bf258ca900af6364/Screen%20Shot%202017-11-02%20at%2012.22.12%20PM.png' title='Screen Shot 2017-11-02 at 12.22.12 PM.png' width=642>

**Comment by pradeepgangwar** [comment]
@jasonLaster I have not done something big change to this code repository. So although i may be knowing little about fixing it. But I would like to try it and learn something. Please guide me a little to start. And i will try it if i can fix it.

**Comment by jasonLaster** [comment]
Great, @wldcordeiro will mentor this issue, but I would start by working on QuickOpen showing a list of buttons 

- jump to go to line,
- jump to sources

these actions are all in redux :)

**Comment by pradeepgangwar** [comment]
@jasonLaster If i am right, main task is to open a drop down suggestion list when user types **?**

**Comment by wldcordeiro** [comment]
@pradeepgangwar I'll update this with a patch later today for you to base off but the overview goes like this
1. User opens quick open modal (cmd+p)
2. User enters `?`
3. A list shows up that show our options
  * `@ for functions`
  * `# for variables`
  * `: for go to line`
  * `term: search for term and go to line`
4. User arrows down to option and hits enter
5. Quick open updates its query to use the option chosen.

This list might not be what we actually want listed but there's the basis.

**Comment by nyrosmith** [comment]
The PR got merged so I'll close this
