### ISSUE TITLE
Provide Additional Source Details in Footer

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4572]
<img width="979" alt="emptyspace" src="https://user-images.githubusercontent.com/46655/32358227-51e67758-c012-11e7-9c04-2d7b02f0f73f.png">

There's an amazing opportunity, IMO, to provide a bit more detail about each source in the editor area footer.  What info...I'm not quite sure yet.  File size, compression (gzipped or not), maybe a link to the network tab, etc.  

I'm thinking we should figure out how to use that space most wisely.

**Comment by jasonLaster** [comment]
Yep, agreed


- we're adding a link back to the generated file if it is original soon
- we're moving the cmd+f search bar down there

there's still space tho

**Comment by jasonLaster** [comment]
closing as we show a link back to the generated file if it is original soon.

We might also move search down there. Anyways, we can always re-open the discussion later.
