### ISSUE TITLE
[Breakpoints] Extract Context menu

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4597]
We recently extracted the Editor Gutter Menu into its own component and it became much easier to understand.

The Breakpoints gutter menu is 200+ lines and would be great to simplify [here](https://gist.github.com/29e9a9ad7a0b07e8c7764740139d9896)

**Comment by wldcordeiro** [comment]
@Fischer-L still grabbing this?

**Comment by Fischer-L** [comment]
@wldcordeiro 
> @Fischer-L still grabbing this?

Working on this. Sorry for the slow progress because of my busy day jobs and the vacations at the end of the year.

**Comment by jasonLaster** [comment]
No Worries! We like to check in because it can be difficult to lose track :)

**Comment by lukaszsobek** [comment]
After this is merged we might want a followup issue with cleanup in terms of alphabetical ordering of items and enforcing naming conventions for easier parsability.

**Comment by lukaszsobek** [comment]
Merged. Closing.
