### ISSUE TITLE
Portrait mode does not enable automatically when restarting Debugger

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#4599]
**Steps to reproduce**
1. Start latest Nightly
2. Open Debugger (Ctrl+Shift+S)
3. Set "Dock to side of browser window"
4. Resize width of Developer Tools until Portrait mode
5. Close Developer Tools
6. Open Debugger again (Ctrl+Shift+S)

**Actual Results**
Portrait mode does not enable automatically when restarting Debugger.

**Expected Results**
Enable

**Comment by wldcordeiro** [comment]
I tried this just now and it retained the layout when reopened, @magicp-github could you check again?

**Comment by jasonLaster** [comment]
this was fixed :)
