### ISSUE TITLE
[Outline] Change param color to magenta

### ISSUE THREAD

**Issue by violasong** [devtools-html/debugger.html#4604]
We're trying to keep red for errors only, so it would be great if we could change the red params in Outline to syntax magenta (var(--theme-highlight-red)).

<img width="257" alt="image" src="https://user-images.githubusercontent.com/55994/32465179-73045864-c2f7-11e7-8884-c767c3b0fa8c.png">

(Ideally it would match the syntax highlighting, but in the code it looks like this is just colored as blue and blue.)

**Comment by jasonLaster** [comment]
Nice idea!

**Comment by bogas04** [comment]
Is this fixed ? 

Nightly 59 (Nov 15)

![screen shot 2017-11-16 at 5 35 03 pm](https://user-images.githubusercontent.com/6177621/32890373-7ef7865a-caf4-11e7-8b3e-df25c31191d5.png)

**Comment by codehag** [comment]
doesn't look like it, parameters are still red
