### ISSUE TITLE
Hide scrollbar of Dropdown when no overflow

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#4609]
**Steps to reproduce:**
1. Launch Nightly on Windows
2. Open multiple tabs until displaying Dropdown button
3. Open Dropdown

**Actual Results:**
Scrollbar always visible.
![dropdown](https://user-images.githubusercontent.com/13914314/32471544-37030aa4-c3a1-11e7-899c-2b17bcafab95.png)

**Expected Results:**
Hide scrollbar when no overflow.

**Regression:**
[Tabs] files do not overflow #3625

**Comment by lukaszsobek** [comment]
Change merged, closing issue.
