### ISSUE TITLE
Can set breakpoints on non-JS lines

### ISSUE THREAD

**Issue by hallvors** [devtools-html/debugger.html#461]
1. Go to http://localhost:8000/increment example in debuggee browser
2. In debugger, open *increment / (index)* and set breakpoint on the line with the HTML *title* tag

Bug: the debugger should know what lines it makes sense to set breakpoints on :)

**Comment by jlongster** [comment]
It's impossible to deterministically know which lines you can and can't set breakpoints on. Scripts (functions) may have already been GCed so it doesn't look like there's anything there, but you definitely should be able to set a breakpoint there and refresh the page and hit it in the next session.

This is a really tricky problem and it's best to just let the breakpoint be set even if it's never hit. What would the other behavior be anyway? Move the breakpoint? Don't let the user add it? It's simpler UX as well to just set the breakpoint.

**Comment by hallvors** [comment]
hm.. if there was an inline event handler in the HTML, would setting a breakpoint actually work? 8-)

You are saying the source code rendering view has absolutely no idea what code is JS, what is HTML and what is CSS? It's unexpected behaviour but if you say it's by design just close this as invalid.

**Comment by jasonLaster** [comment]
@jlongster feel free to open this if there is something actionable here.

**Comment by jlongster** [comment]
> hm.. if there was an inline event handler in the HTML, would setting a breakpoint actually work? 8-)

I think it actually might, yes. They shouldn't be much different than inline scripts, but there may be bugs with introducing them through attributes.

Yea, the source code rendering has no idea what code is what in mixed mode. It might be possible to us (the client) to support mixed mode and be smart about it but that's a very big feature and I'm not sure if it's worth the pay-off, given that most people don't actually debug HTML files (just JS).

It's a good idea but not something we can really do right now.

**Comment by hallvors** [comment]
> <@UCF1A1TAL> when testing Propr locally, I usually get some error messages when closing the Node server process. Database-related, I'm not sure why (the connection handling is just done by Sequelize stuff I think).
```
TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/Users/hrms/repos/somme/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/Users/hrms/repos/somme/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
```
Is this something to worry about?
<sub>[View in Slack](https://wja.slack.com/archives/C0NKEM6QP/p1544783128412900)</sub>
