### ISSUE TITLE
Investigate slow pausing performance

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4610]
STR (a stress test):
- Go to inbox.google.com
- Paused in the Debugger
- Nearly 10sec hang, first time it caused a slow script dialog depending on which script you hit

https://perfht.ml/2zCZ52O

- `onPrototypeAndProperties resource://devtools/server/actors/object.js` takes 1 second in the content process
- `getChildren resource://devtools/client/debugger/new/debugger.js` takes 400ms on main
- *React component updates* `batchUpdates & co` takes 4.2s on main, which looks similar to [bug 1414387](https://bugzilla.mozilla.org/show_bug.cgi?id=1414387), where all time is spent in React JS.

**Comment by jasonLaster** [comment]
This worked well for me when pausing in gmail

![](http://g.recordit.co/pCqDfGU35S.gif)

Feel free to re-open if you can reproduce the jank. 

here's a recording https://perfht.ml/2FjuFWL
