### ISSUE TITLE
toggle-button-end is not displayed when displaying welcomebox in portrait mode

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#4612]
**Steps to reproduce:**
1. Launch latest Nightly
2. Open Debugger with portrait mode (Dock to side of browser window)
3. Close all tabs

**Actual Results:**
toggle-button-end is not visible.
![toggle-button-end](https://user-images.githubusercontent.com/13914314/32481425-99609a1a-c3d6-11e7-8ac0-540427ac7d9f.png)

**Expected Results:**
toggle-button-end is visible in the bottom-end of welcomebox.

**Comment by wldcordeiro** [comment]
Closing as the related PR was merged.
