### ISSUE TITLE
[PrettyPrint] pretty file stays in focus

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4615]
STRs: 
- pretty print script.js
- close the pretty print tab
- add a breakpoint in the first line of startAnimationTimer
- step over repeatedly

The pretty print tab comes back, despite being closed in step 2. The focus switches back and forth between the two tabs.

The script I use to get this behavior is 
```
(function () {
  let timer;
  let map = {};
  var startAnimationTimer = function(id) {
    var item = map[id];

    if (timer) {
      window.clearTimeout(timer);
    }

    timer = window.setTimeout(function() {
      startAnimationTimer(id++);
    }, 50);
  };

  startAnimationTimer(0);
})();
```

served in an empty html file.

(needs to be a bit complex in order to trigger the switch back and forth between the pretty printed and non pretty printed version)

![debugger_pretty_print](https://user-images.githubusercontent.com/1141550/32519718-ef09491c-c40d-11e7-9209-b70f9493a74d.gif)

**Comment by lukaszsobek** [comment]
Duplicate. Closing in favor of #4714
