### ISSUE TITLE
[Outline] selecting a function does not highlight the line

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4616]
Selecting a function in the outline list does not highlight the line. I think this is because we changed `selectSource` and didn't update this spot.

See this [pr](https://github.com/devtools-html/debugger.html/issues/4598).

It would be nice to add a mochitest for outline view when we fix this.

```diff
diff --git a/src/components/PrimaryPanes/Outline.js b/src/components/PrimaryPanes/Outline.js
index 3db4f9f..d59f1b5 100644
--- a/src/components/PrimaryPanes/Outline.js
+++ b/src/components/PrimaryPanes/Outline.js
@@ -33,7 +33,7 @@ export class Outline extends Component<Props> {
     }
     const selectedSourceId = selectedSource.get("id");
     const startLine = location.start.line;
-    selectSource(selectedSourceId, { line: startLine });
+    selectSource(selectedSourceId, { location: { line: startLine } });
   }
 
   renderPlaceholder() {
```

![Screen Shot 2017-11-07 at 5.16.45 PM.png](https://shipusercontent.com/daa5f0962c0175c3fb202e5a365e5df5/Screen%20Shot%202017-11-07%20at%205.16.45%20PM.png)

**Comment by juliandescottes** [comment]
This is still not fixed when testing the release from https://bugzilla.mozilla.org/show_bug.cgi?id=1423158 which contains the following changelog https://github.com/devtools-html/debugger.html/compare/efa4ca367dadb1bb54525f9fe305dd38c0ec6323...d2ed2927c7070e7443f297f98f1bf145a583f3c7

Is there a test covering this feature?

**Comment by juliandescottes** [comment]
Sorry my bad, tested the wrong changeset, this is fixed with the last bundle, ignore my previous comment :)
