### ISSUE TITLE
[WatchExpressions] are intermittent

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4617]
the watch variables seem to be subject to race conditions. Variables that should be defined show up as unavailable

1. go to [timers](https://dbg-timers.glitch.me/)
2. add a bp on client/12
3. add `id` expression
4. pause and resume...

![](https://bug1415300.bmoattachments.org/attachment.cgi?id=8926094)

**Comment by jasonLaster** [comment]
@juliandescottes this does not repro yet...

**Comment by juliandescottes** [comment]
@jasonLaster try with https://www.piskelapp.com/ break on piskel-animated-preview, line 39

**Comment by juliandescottes** [comment]
You can use this isolated example: https://daisy-speedboat.glitch.me/

**Comment by juliandescottes** [comment]
I no longer reproduce with v11.0. Any idea what could have fixed this @jasonLaster ? Feel free to close.

**Comment by jasonLaster** [comment]
haha - nope... was going to look at it soon though

**Comment by jasonLaster** [comment]
we're no loner seeing this

**Comment by jasonLaster** [comment]
I noticed while stepping that Scopes became unavailable when expressions were being evaluated... 

It was fixed when i removed the expressions.

**Comment by juliandescottes** [comment]
What does this have to do with the initial report?

**Comment by jasonLaster** [comment]
i think it's related... but yeah, it could be different.

**Comment by jasonLaster** [comment]
fair. closing
