### ISSUE TITLE
[PrettyPrint] uncaught exception: SyntaxError: Unexpected character '`' (709:32)

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#4619]
**Steps to reproduce:**
1. Launch Nightly
2. Navigate to "about:home" (about:newtab)
3. Open Debugger (Ctrl+Shift+S)
4. Open "resource://activity-stream/data/content/activity-stream.bundle.js"
5. Click Pretty Print button
6. Check Browser console log

**Actual Results:**
Pretty Print does not work.
console log: uncaught exception: SyntaxError: Unexpected character '`' (709:32)  (unknown)

**Expected Results:**
Works with no error.

**Comment by assafdd** [comment]
I dug a little in this issues. 
might be related to the acron.js version the debugger is using(currently very old one  ~2.6.4 used in pretty-fast package).
I was able to reproduce the exception with the following code snippet from the ticket (https://github.com/ternjs/acorn/issues/575) :
```
const acorn = require("acorn")
const code = `
    \`\${ foo({class: 1}) }\`
`

console.log(acorn.version)
console.log(code)
console.log(acorn.parse(code, {ecmaVersion: 8}))
```

**Comment by jasonLaster** [comment]
thanks for the repro. We can easily bump acorn in pretty-fast :)

**Comment by assafdd** [comment]
Just tested it locally and it solve the problem

**Comment by assafdd** [comment]
I'll send a PR on pretty-fast repo

**Comment by assafdd** [comment]
@jasonLaster once this PR https://github.com/mozilla/pretty-fast/pull/20 is approved we can bump  pretty-fast here too.

**Comment by assafdd** [comment]
@jasonLaster I accidentally pushed this on the same branch  of https://github.com/devtools-html/debugger.html/pull/4700/ ...
So I revert it. and will push it on a seperate branch soon

**Comment by jasonLaster** [comment]
k
