### ISSUE TITLE
Firefox spitting out the following.

### ISSUE THREAD

**Issue by FireWolf74** [devtools-html/debugger.html#4652]
When I try to run certain Flash games this is what spits out at me.

###!!! [Parent][MessageChannel] Error: (msgtype=0xA4000A,name=PPlu
###############Promise resolved after context unloaded! [Parent][MessageChannel::Call] Error: Channel error: cannot send/recv! [Parent][MessageChannel::Call] Error: ( msgtype=0xA20001,name=PPluginInstance::Msg___delete__ ) Channel error: cannot send/recv! [Parent][MessageChannel::Call] Error: Channel error: cannot send/recv! [Parent][MessageChannel::Call] Error: ( msgtype=0xA20001,name=PPluginInstance::Msg___delete__ ) Channel error: cannot send/recv! [Parent][MessageChannel] Error: ( msgtype=0xA4000A,name=PPlu
Too many ('s.

Thanks for filing an issue! 

If you're reporting a bug, please share a clear description of the problem and the steps needed to reproduce the problem.  It's also helpful to include a gif, screenshot, and minimal test case.

* you can find us in slack: https://devtools-html-slack.herokuapp.com/
* our tips on formatting issues: https://github.com/devtools-html/debugger.html/blob/master/docs/issues.md
* our glitch.com template for filing small test cases: https://fabulous-umbrella.glitch.me/

Thanks again,
Debugger Team!

-----------------------------------------------

**Comment by jasonLaster** [comment]
Hi @FireWolf74, Debugger.html is a project for the debugger frontend. This bug is a devtools bug and should be filed in bugzilla.mozilla.org under the Firefox DevTools Product.
