### ISSUE TITLE
[Console] Following link to large file from Console doesn't react for a while

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4654]
STR:

- Fresh Nightly profile
- Open https://discourse.mozilla.org/t/things-i-miss-about-firebug/17233
- Open Console
- Click the file for the Ember tooling notice 
- Keep clicking

<img width="678" alt="image" src="https://user-images.githubusercontent.com/8599/32637509-05e33b54-c56f-11e7-99de-2dbcf89705d1.png">

AR:

- Nothing happens for me, for about 10sec, then Debugger opens with the file (not correct line)

ER:

- Open Debugger and show the file with the right line

**Comment by digitarald** [comment]
Same on Github, takes 3sec to click:

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/8599/32637735-64a1c916-c570-11e7-95f6-81f2be4a22ae.png">

**Comment by juliandescottes** [comment]
For the record, the workaround I used on https://github.com/devtools-html/debugger.html/issues/4705 also makes the performance of this scenario much better.

**Comment by jasonLaster** [comment]
I just looked into this and the slow down comes from our current strategy of blocking opening the debugger on fetching all of the sources. 

- We fetch all the sources because the debugger can open after the page is open
- We block because when a user clicks a link in the console, we check to see if the debugger has the source before deciding to show the source in `view-source` or the debugger.

#### We can speed up the debugger opening by not blocking:

```diff
diff --git a/src/client/firefox.js b/src/client/firefox.js
index 0715faf..fb0a6d1 100644
--- a/src/client/firefox.js
+++ b/src/client/firefox.js
@@ -45,9 +45,9 @@ export async function onConnect(connection: any, actions: Object): Object {
   // the debugger (if it's paused already, or if loading the page from
   // bfcache) so explicity fire `newSource` events for all returned
   // sources.
-  const sources = await clientCommands.fetchSources();
+  clientCommands.fetchSources().then(sources => actions.newSources(sources));
+
   await actions.connect(tabTarget.url);
-  await actions.newSources(sources);

   // If the threadClient is already paused, make sure to show a
   // paused state.
```

#### navigating to viewSource

We can check the source map url service to see if the source has been seen before opening the debugger

#### Note

One thing to watch out for if we stop blocking the debugger opening is that we scroll when the source loads.

**Comment by jasonLaster** [comment]
Here is a sketch of what the changes could look like in the panel:

```diff
diff --git a/devtools/client/framework/source-map-url-service.js b/devtools/client/framework/source-map-url-service.js
index fe4ff87..f2940f7 100644
--- a/devtools/client/framework/source-map-url-service.js
+++ b/devtools/client/framework/source-map-url-service.js
@@ -347,4 +347,6 @@ SourceMapURLService.prototype._onPrefChanged = function () {
   }
 };
 
+SourceMapURLService.prototype.hasSource = // YAY
+ 
 exports.SourceMapURLService = SourceMapURLService;
diff --git a/devtools/client/shared/view-source.js b/devtools/client/shared/view-source.js
index 94a6dff..3ec74b6 100644
--- a/devtools/client/shared/view-source.js
+++ b/devtools/client/shared/view-source.js
@@ -59,8 +59,7 @@ exports.viewSourceInDebugger = Task.async(function* (toolbox, sourceURL, sourceL
 
   // New debugger frontend
   if (Services.prefs.getBoolPref("devtools.debugger.new-debugger-frontend")) {
-    const source = dbg.getSource(sourceURL);
-    if (source) {
+    if (toolbox.sourceMapService.hasSource(sourceURL)) {
       yield toolbox.selectTool("jsdebugger");
       dbg.selectSource(sourceURL, sourceLine);
return true;
```

**Comment by codehag** [comment]
p1 of this fix: https://reviewboard.mozilla.org/r/222292/

**Comment by digitarald** [comment]
Works snappy for me now.
