### ISSUE TITLE
Debugger not loading

### ISSUE THREAD

**Issue by eoger** [devtools-html/debugger.html#4666]
This is in the browser toolbox. Restarting Firefox doesn't help.
The last command I typed in the console was: `fetch("https://localhost:12345").catch(e => { debugger })`.

<img width="986" alt="screen shot 2017-11-10 at 1 47 37 pm" src="https://user-images.githubusercontent.com/6424575/32673587-bf46b13a-c61d-11e7-9d43-47eda1ab8365.png">

**Comment by eoger** [comment]
I think it might be caused by breakpoints I put in a file in another patch then changed my branch.

**Comment by jasonLaster** [comment]
hmm, strange. could you file the bug in the bugzilla debugger. as this is a `server` bug. We'll be sure to look into it though.
