### ISSUE TITLE
Hang when entering pausing

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4679]
STR:

- Open Bugzilla bug
- Hit Pause in Debugger
- Scroll down

ER:
- Debugger jumps into paused state quickly

AR:
- 5s hang

https://perfht.ml/2zB4qqC

This profile is a hang after clicking one too many times on pretty print and reverting the printing with the 2nd click: https://perfht.ml/2zDpL2H , same pattern.

Most hang time spent in `showSourceText`: 50% `replaceDocument`, 30% `setMode`, 13% `updateLineNumberFormat`.

**Comment by jasonLaster** [comment]
This is now pretty snappy for me. Let me know how it works for you.


![](http://g.recordit.co/TwxiT1GrYL.gif)
