### ISSUE TITLE
Avoid spamming IPC messages on busy pages

### ISSUE THREAD

**Issue by legnaleurc** [devtools-html/debugger.html#4680]
I found a page which has a script looks like:
```javascript
setInterval(function a () => {
    eval('debugger;');
    a();
}, 4000);
```
When I trying to open the debugger, it causes parent process using 100% CPU.
https://perfht.ml/2hnZ5bG

However Chrome plays well on this page.

**Comment by codehag** [comment]
Thanks for the bug report!

**Comment by darkwing** [comment]
I couldn't reproduce.
