### ISSUE TITLE
Search across all files is not present

### ISSUE THREAD

**Issue by S2-** [devtools-html/debugger.html#4681]
**problem**
ctrl+shift+f does not search across all files

**expected result**
ctrl+shift+f should search across all files, and not just the open one.

**Comment by jasonLaster** [comment]
Hi @S2- I am not sure that this is a common interaction. We are trying to follow similar interactions to editors.

**Comment by S2-** [comment]
Hi @jasonLaster that's ok. What I am missing is the "search a string in all loaded js files". How I do that is not really important, but it would be nice if I can *somehow* do it.

**Comment by jasonLaster** [comment]
Yep - cmd+shift+f does that and it should be documented in the welcome page and shortcuts modal. With that said, if you need docs... it is not clear enough. I'll see what we can do :)
