### ISSUE TITLE
[Search][UX] "Results Not Found" before the results

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#4685]
Using Firefox Nightly 59.0a1 (2017-11-13) (64-bit)

1. Go to https://trends.google.com/trends/
2. Open developer tools. 
3. Go to the debugger
4. Search in all files (command + shift + F on macOS) with a string.

Example: backdrop

![capture d ecran 2017-11-14 a 10 15 53](https://user-images.githubusercontent.com/505230/32757890-14017d4a-c925-11e7-85b5-a21ef7749b9d.png)

After a **couple of seconds** (long enough to have the feeling to be waiting but on the cliff of anxiety that they will never come. Cue dramatic music effects).

![capture d ecran 2017-11-14 a 10 17 12](https://user-images.githubusercontent.com/505230/32757905-26002fc8-c925-11e7-844c-5abf939da763.png)

Expected: 
Have something in the UX that the search is going on. 

Actual:
The  Not results found is misleading and encourages to abandon the search.

**Comment by codehag** [comment]
This could be achieved using redux-thunk, and have a "loading" message while we are waiting

**Comment by varenya** [comment]
@jasonLaster I have a fix for this but I am not sure how to style the "loading.." part. are there already any components for this?

**Comment by codehag** [comment]
@varenya we don't have anything yet, what about just using a text for now? we can iterate on it later :)

**Comment by lukaszsobek** [comment]
Fix merged, closing issue.
