### ISSUE TITLE
Weird position for the "X" close button

### ISSUE THREAD

**Issue by julienw** [devtools-html/debugger.html#4688]
See picture:
![capture d ecran de 2017-11-14 17-14-58](https://user-images.githubusercontent.com/454175/32790684-6054514c-c95f-11e7-8b65-a47ce964a502.png)

**Comment by julienw** [comment]
This is in latest nightly 20171114100042

**Comment by juliandescottes** [comment]
On OSX, I don't see an issue with source tabs, but there is one with watch expressions. The close icon is correctly sized, but too low

![image](https://user-images.githubusercontent.com/1141550/32790773-9ab0d50e-c95f-11e7-93cb-1d8351a547ba.png)
