### ISSUE TITLE
Source Maps - load source map files in the toolbox

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#469]
we'll need a way to fetch source maps from the toolbox. We currently use the dev-server in the local development mode.

**Comment by jlongster** [comment]
We're pushing sourcemaps out to the next sprint.

**Comment by jlongster** [comment]
This works now from #807 

<img width="781" alt="screen shot 2016-09-27 at 1 53 42 pm" src="https://cloud.githubusercontent.com/assets/17031/18885504/f217e5bc-84b9-11e6-9522-63b9925f7c65.png">
