### ISSUE TITLE
Performance regression when loading sources

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#4692]
Performance regression spotted with the [11-7 bundle release](https://bugzilla.mozilla.org/show_bug.cgi?id=1415300).

See screenshot of DAMP perf charts, reload regressed of 10%:
![image](https://user-images.githubusercontent.com/1141550/32801215-b2270326-c97c-11e7-8ebb-5909530ce301.png)

The test case from https://bugzilla.mozilla.org/show_bug.cgi?id=1366693 really highlights the issue. The test page is simply sequentially loading scripts as fast as possible and measuring the time it takes to load all scripts. 

On my machine: 
- without devtools opened: < 1s
- with debugger opened (version 10-25): 3s ([profile](https://perfht.ml/2zCcNCz))
- with debugger opened (version 11-7): 10s ([profile](https://perfht.ml/2zY3rld))

The test case is a zip at https://bugzilla.mozilla.org/attachment.cgi?id=8869957

Precise STRs:
- serve the content of the zip e.g. on http://127.0.0.1:8080
- open http://127.0.0.1:8080
- (the page should display "Loaded in X seconds", X hopefully below 1)
- open the debugger (be careful about opening only the debugger and not any other tools as they can impact the perf)
- reload the page
- page will now take several seconds to load

**Comment by juliandescottes** [comment]
The performance regression comes from 7ad903845df119c0c0a79e37e116e3ea34c5854d (which improves JSX syntax highlighting).

On the second profile you can see a lot of time is spent in codemirror (even though no source is actually opened in the UI). Looks like we rerender the Editor component more than we used to?

**Comment by nyrosmith** [comment]
I can't verify by numbers but I think this should no longer be an issue because of #4653 and #4677

**Comment by juliandescottes** [comment]
@nyrosmith just tested with the latest revision of master and the issue is still there, sorry :/
