### ISSUE TITLE
Search bar inside Debugger panel of developer tools has broken carat placement

### ISSUE THREAD

**Issue by simonsarris** [devtools-html/debugger.html#4693]
I'm on 59.0a1 (2017-11-14) (32-bit) Windows 10

Summary: Pressing the `home` key moves the carat to the start of the search box, and then pressing any key afterwards types that letter, then also moves the carat to the end of the search box.

The same thing happens without using the `home` key, if you click anywhere with the mouse to move the carat and type one letter, the carat moves out of position, to the end of the line.

------------

Example: Open developer tools, open the Debugger panel and click a file. Now press CTRL+F to start searching.

Type `"yam"` because you're looking for yams. But there are so many yams amongst your code and really you're looking for *garnet yams* so you press the "home" key to move the carat to the start of the search box. This works.

You start to type out `"garnet "` to prepend your search term. You type the `"g"`

`"gyam"` is what's in the field. At this point, the cursor magically moves back to the end of the field. This is a bug.

So if you type:

`"yams[home key]garnet "`

You will see

`"gyamsarnet "`

When you are supposed to see:

`"garnet yams"`

**Comment by simonsarris** [comment]
I'm not familiar with the codebase buy eyeballing it, this may be the culprit:

https://github.com/devtools-html/debugger.html/blob/e12186b556563e67ee8c1dd37094a1c1be5042bb/src/components/shared/SearchInput.js#L62-L70

**Comment by jasonLaster** [comment]
Thanks @simonsarris

**Comment by wldcordeiro** [comment]
The code above was there to ensure that the cursor was placed after one of the shortcut characters, it could be made more robust to only do so for that case and not all text.

**Comment by Loirooriol** [comment]
How come this hasn't been fixed already? The UX is so horribly broken. What are these shortcut characters that needed the offending code? I don't understand.

**Comment by jasonLaster** [comment]
Sorry @Loirooriol, we'll look into it soon.

**Comment by avantgrogg** [comment]
Hey, sorry for the delay on this. Looking into the code that was added, @wldcordeiro is the goal to make sure the cursor ends up after the icon if an icon exists? Some further questions around uat:

If a user opens a search with an icon, types a part of a word then uses the mouse to place the cursor behind the icon, what is the expected behavior?

If a user opens a search with an icon, types a part of a word then presses the home button, should the cursor be placed in front of the icon as opposed to the beginning of the input?

**Comment by wldcordeiro** [comment]
It was part of an old implementation and it wasn't properly done but it's not needed and was dropped already.

**Comment by jasonLaster** [comment]
@wldcordeiro is this fixed?

**Comment by avantgrogg** [comment]
Testing out the criteria that @simonsarris noted, typing `"yams[home key]garnet "` results in the correct behavior, with the text in the input ending up being `"garnet yams"`

**Comment by Loirooriol** [comment]
I still get `gyamsarnet` on latest Nightly.

**Comment by jasonLaster** [comment]
sorry, it's fixed in Github. Will be on nightly after they cut a new version of beta

**Comment by Loirooriol** [comment]
I guess it's https://github.com/devtools-html/debugger.html/commit/282c688f9a0150aab6b810a8d57a874a5c005e0a#diff-5f2aad7d5f0db62d1bdb6c5f0b64e714
