### ISSUE TITLE
Debugger still shows removed scripts in sources panels

### ISSUE THREAD

**Issue by nicofrand** [devtools-html/debugger.html#4708]
Ex: http://jsbin.com/lujehesixe/1/edit?html,js,console
The "code.jquery.com" source should not appear anymore (I removed the script dynamically).

**STR**:

* Load a JS script in your HTML 
* Open the debugger panel
* Remove the JS script dynamically

**What happens**

The script still appears in the sources panel.

**What I expect**

The script should not appear in the sources panel.

**Comment by bomsy** [comment]
Chrome still shows it as well

![image](https://user-images.githubusercontent.com/792924/33230454-87127a28-d1db-11e7-8e11-abba2a1a970f.png)

**Comment by jasonLaster** [comment]
How do you remove the script dynamically?

**Comment by bomsy** [comment]
he has a `document.getElementById("test").remove();` in the jsbin file.

**Comment by jasonLaster** [comment]
oh interesting. not sure if the server gives us a source removed event

**Comment by nicofrand** [comment]
Chrome Version 61.0.3163.100 (Official build) (64 bits) does not show them, I don't have access to a newer version for now.

**Comment by jasonLaster** [comment]
closing and moving to the enhancements board https://github.com/devtools-html/debugger.html/projects/5
