### ISSUE TITLE
Horizontal scrollbar is too high when searching all files

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#4712]
Horizontal scrollbar is too high when searching all files:

![image](https://user-images.githubusercontent.com/1141550/32911448-8137e190-cb0c-11e7-8b71-8b5edb77ce7e.png)

(see blank space below the scrollbar in the center panel)

**Comment by juliandescottes** [comment]
Thanks for claiming the bug @CharlesStocky 
Sorry about the super short summary, I opened the bug while investigating something else and forgot to add more details. 

I should add that I saw the issue when testing the debugger integrated in Firefox Nightly, and haven't tried with the launchpad setup. Ping me if you have any problem reproducing the issue!

**Comment by CharlesStocky** [comment]
The problem showed up in stable as well. Should the editor pane (when searching files) be flush to the bottom of the browser? @juliandescottes

**Comment by jasonLaster** [comment]
I think this was fixed, is that correct @CharlesStocky
