### ISSUE TITLE
[Pause] Locations should be symmetric  for original and generated files

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4715]
One of the coolest features we've worked on IMO, is debugger symmettry. Basically, we expect users to mostly care about debugging the original code, but we'll try to help users when they want to see the generated code.

One of the biggest use cases for trying to see the generated code is when you want to inspect variables in the generated code.

We currently map breakpoint locations, so you can see where the breakpoint is. We do not map the debug line and call stack locations, but we totally could and should

here's a [patch](https://gist.github.com/a25952d5dc9caac5cd6178d106be529d)

<img src='https://shipusercontent.com/0cdcafbbe2cd423f38cc58bb6299ccef/symmettry.jpg' title='symmettry.jpg' width=1773>

**Comment by yurydelendik** [comment]
It is worth to notice that "symmetric" might not be a right word here. Single generated location might be mapped to multiple original locations (see e.g. [allGeneratedPositionsFor](https://github.com/mozilla/source-map#sourcemapconsumerprototypeallgeneratedpositionsfororiginalposition) ), but probably to simplicity of this issue the first generated location (or one returned by `generatedPositionFor`) must be selected for symmetry.
