### ISSUE TITLE
Can't reload the page when paused on exception

### ISSUE THREAD

**Issue by sole** [devtools-html/debugger.html#4725]
I have enabled pause on exception.

My code created an exception and so the debugger is paused showing me the error (sorta, see #4724).

I edited and saved my code in my external editor and now I'd like to reload the page to see if I actually fixed it. Except... I can't. 

I keep pressing ⌘R to no avail. I'm forever trapped on the debugger, captive to the exception my code triggered before. The only escape route is to close the tab and reopen it again.

**Comment by jasonLaster** [comment]
Ooh, that's not great. Could you share some screenshots or an STR?

**Comment by sole** [comment]
Sorry for the slow response. I spoke to @codehag and I'll try to build a test case. I have a hunch that the reason I can't do anything is because I'm debugging a massive chunk of code (40K webpack mole with built in source maps) and something might be consuming the UI thread, making the tab unresponsive.

**Comment by jasonLaster** [comment]
hey @sole. I'm thinking about closing this as the perf on nightly has gotten 10X better. Feel free to re-open if you see anything.
