### ISSUE TITLE
[eslint] fix badge component warning

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4727]
run `yarn lint-js` and you'll get this warning

<img src='https://shipusercontent.com/5fe8b95b47ef1a391765cd64e7cc5c64/Screen%20Shot%202017-11-17%20at%205.41.36%20PM.png' title='Screen Shot 2017-11-17 at 5.41.36 PM.png' width=786>

**Comment by borian** [comment]
https://github.com/borian/debugger.html/commit/fe80ddbffcbde4b517c2e2528a5ab0116584d756
I've added flow types in accordance with the docs.
https://flow.org/en/docs/react/children/

This fixes the lint-warning and all tests pass.
But the react package does not define a Node type, so editors with type-checking will still complain.

![badge-proptypes](https://user-images.githubusercontent.com/1525694/32993756-ca8212e2-cd5c-11e7-8745-a820f94059e6.png)

**Comment by jasonLaster** [comment]
Ahh, hmm... that's a good point. I think @bomsy's type was wrong :)

How about we try 

```js
import type {Node} from "react"
...
children: Node[]
```

**Comment by bomsy** [comment]
@borian @jasonLaster  ooppsiee! my bad! :) i've learnt something new today as regards react children.

> ```js
> import type {Node} from "react"
> ...
> children: Node[]
> ```

@jasonLaster  Will the children for the badge ever be more than one value?

**Comment by jasonLaster** [comment]
nope

**Comment by lukaszsobek** [comment]
Closing as fixed
![yarn-js](https://user-images.githubusercontent.com/23530054/33981670-102bd652-e0ae-11e7-9840-bd3005c77df7.png)
