### ISSUE TITLE
Ignore caught exceptions

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#474]
Currently we have a settings menu for this action and we don't want to continue using the settings menu for hiding this option.

Chrome uses the Pause on Exceptions button to trigger a secondary menu for this action.  I believe we should be looking into something similar to this system.  I'd rather have a combo button interaction but that's up for design.

Here are the levels of pause:
* First action turns on "Pause on Exceptions"
* Second action turns on "Pause on caught Exceptions"

Then we need some way to turn it all off again.

**Comment by jasonLaster** [comment]
Hey @clarkbw, @helenvholmes mind weighing in with some designs / sketches of how you see this working:

The engineering side should be easy: [protocol method](https://github.com/devtools-html/debugger.html/blob/master/public/js/lib/devtools-sham/shared/client/main.js#L1863-L1867) [client command](https://github.com/devtools-html/debugger.html/blob/master/public/js/clients/firefox/commands.js#L97-L100)

**Comment by clarkbw** [comment]
Here's what Chrome does.  Not recommending this, just for reference.
![pause on caught exceptions](https://cloud.githubusercontent.com/assets/2134/17504160/2add01ba-5dab-11e6-8d63-1ac52707138a.gif)

**Comment by helenvholmes** [comment]
Anyone mind giving me the low-down on the difference between exceptions and caught exceptions? (I think James did at some point... yikes, sorry!)

If we wanted to do some sort of combo button, not understanding what the two do, we could have it cycle through three states on click:

![screen shot 2016-08-09 at 9 53 41 am](https://cloud.githubusercontent.com/assets/1720093/17518764/2e25c76e-5e17-11e6-93e6-4a3643db2b99.png)

(That second icon is entirely made-up just to help illustrate the point.)

**Comment by jlongster** [comment]
@helenvholmes There are two types of breaking on exceptions: 

1. Pause on any exception whatsoever, even if it's wrapped in a try/catch block and is handled
2. Only pause on exceptions that aren't caught, and bubble up to the top and are thrown

Does that make sense?

**Comment by jasonLaster** [comment]
Damnit, @jlongster beat me to it. Here's what I had, might help:


Here are two programs: the first catches an exception, the second does not:

```js
try {
  doSomethingHard();
} catch (e) {
  console.log('oops, that hard thing failed');
}
```

```js
doSomethingHard();
```

The benefit of pausing on uncaught exceptions is that they are unexpected uhohs. The benefit of pausing on caught exceptions is sometimes, that's just where you want to stop and it's useful. I think it's most useful to pause on uncaught exceptions.

**Comment by helenvholmes** [comment]
From the above, it sounds like the most useful option someone would want to click is:

> 2. Only pause on exceptions that aren't caught, and bubble up to the top and are thrown

Do we want to surface "pause on uncaught exceptions" _and_ "pause on caught exceptions", with toggling both meaning "pause on all exceptions"? Do we all agree that "pause on uncaught exceptions" should be the first choice we surface, as it's more useful to see your unhandled errors than your handled errors?

**Comment by jlongster** [comment]
> Do we want to surface "pause on uncaught exceptions" and "pause on caught exceptions", with toggling both meaning "pause on all exceptions"?

There actually isn't a "pause on caught exception only" option. It's more an option to the "pause on exception" behavior: do you ignore caught exceptions or not. Uncaught exceptions will always be paused on.

I think having 1 icon with 3 states is worth trying, and clicking it toggles through the states. Not sure if that's too hard to explain to the user though.

**Comment by helenvholmes** [comment]
![screen shot 2016-08-09 at 1 44 47 pm](https://cloud.githubusercontent.com/assets/1720093/17526961/75cfd3b4-5e37-11e6-9f4b-e574d7f1d348.png)

I'm continuing with a potentially nonsense icon, but something like this, perhaps?

**Comment by helenvholmes** [comment]
![screen shot 2016-08-09 at 2 37 14 pm](https://cloud.githubusercontent.com/assets/1720093/17528807/c7397352-5e3e-11e6-8f36-a94e1227e942.png)

I'm starting to wonder where this Chrome-stop-sign-analogy came from. I guess because errors stop you? But then why the pause sign? 

We could potentially do warnings/errors... hm:

![screen shot 2016-08-09 at 2 42 52 pm](https://cloud.githubusercontent.com/assets/1720093/17528973/91d88756-5e3f-11e6-80d5-4827f94e4605.png)

**Comment by jlongster** [comment]
I think it's because you "pause" or "stop" on the error... I guess? I'm not sure if warning works well because I don't really see it as a warning... but I don't know what the right icon is. If this is too confusing maybe there is a different way. Feel free to experiment with an icon with just 2 states and then some other way to turn on "pause on caught exceptions as well)".

**Comment by jasonLaster** [comment]
Maybe a color change is enough, "uncaught" red, "caught" blue...
