### ISSUE TITLE
Developer tools in private browsing uses accounts from non-private window

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#4743]
Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1414315

### Steps to reproduce:

Log in on Wikipedia as user A. Open a new private window and log in as user B. (A or B could be anonymous, in which case the username is null) Activate the developer console in the private Wikipedia window and search for "wgUserName"

### Actual results:

The line containing the username says: `"wgUserName": "A",`

That is, the session from the non-private window is used 

### Expected results:

The line containing the username should say: `"wgUserName": "B",`

I am not sure if this can be a security issue or not, marking it as such just in case.

**Comment by jasonLaster** [comment]
@jimblandy can you add some context here?

**Comment by jasonLaster** [comment]
closing this bug as it is likely not a UI issue.
We will track it in bugzilla
