### ISSUE TITLE
Get sources with Debugger.Source, not HTTP GET request

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#4744]
This was an issue on firebug, it is not clear if this is still the case.

basically: when making a post request, the debugger makes two requests, a post and then a get
what is expected: that we just make the post request

we need to find a test case for this and see if this is still happening

bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1005542

**Comment by SebastianZ** [comment]
As mentioned in the Bugzilla report, the issue is not reproducible anymore in Firefox 57.0. The related test case is here:

https://getfirebug.com/tests/manual/issues/7401/issue7401.php

So, this issue can be closed. Unfortunately, I don't have the rights to do that myself.

Sebastian

**Comment by codehag** [comment]
Thanks Sebastian!
