### ISSUE TITLE
Create settings menu for automatic actions

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#475]
The two settings relate to the functions we have for manually working with sources.

* Auto Prettify Minified Sources
* Auto Black Box Minified Sources

Personally I feel like these options should either be located in the source tree or the editor area where the effect takes place.  The settings menu we use is generally located an so these options are likely unused.

Here is the original settings menu:
![screen shot 2016-07-19 at 11 48 22 am](https://cloud.githubusercontent.com/assets/2134/17382098/10959de2-5984-11e6-89a6-e598c523cf38.png)

**Comment by clarkbw** [comment]
- [ ] Open new issue for removing settings menu

**Comment by jasonLaster** [comment]
Looks like the settings menu is already removed.

**Comment by mikhoul** [comment]
@jasonLaster   Could you tell me which solution I have if I want to have "_**Auto Prettify Minified Sources**_" in Firefox 56 and higher ?    I don't see this option that I had in the older FF version.

Regards :octocat:

**Comment by jasonLaster** [comment]
Hi, we don't currently offer auto pretty-print. I just created #4171 to track the feature.
