### ISSUE TITLE
[Breakpoints] Re-Add Event Listeners

### ISSUE THREAD

**Issue by bzbarsky** [devtools-html/debugger.html#4750]
The old Firefox debugger UI used to have an "Events" view which showed what event listeners were attached in the page and allowed breakpointing on them.  There seems to be nothing like that in the new debugger UI.

I could have sworn this was a known issue, but I see no existing open issues on it...

**Comment by jasonLaster** [comment]
I could have too... Strange. It's a goal to bring it back this quarter and we have a simple UI behind a feature flag. I'll convert it to a pref soon and scope out the remaining work.

Thanks for asking, it's good to hear people are missing it

**Comment by bzbarsky** [comment]
To be clear, I am missing it enough that I have the new UI turned off.  ;)

It would be nice if we could have this work for all event targets, not just nodes and windows.  That might need a hook in Gecko to return a list of the other event targets associated with a given window, but that should be pretty easy to implement, since Gecko has that information internally already.

**Comment by sole** [comment]
There's an interesting test case with anonymous event listeners over [this bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1326816)

**Comment by jasonLaster** [comment]
We are doing some planning work here

https://docs.google.com/document/d/1DXzoa7cUZJ_z41_QK1I1nPtyexkgGxup7C_at1SCcQs/edit#

**Comment by jasonLaster** [comment]
moving to the icebox as we will not do this in the 62 release

**Comment by bzbarsky** [comment]
@jasonLaster So does "closed" here mean "wontfix" or something else?  Closing things just because you're not going to get to them yet (but plan to later) is ... odd.

**Comment by digitarald** [comment]
@bzbarsky as an update on this, we are planning to pick this work up for 65 (64 being a short-staffed cycle that focuses on breakpoint and stepping quality).

**Comment by Anton-Shakalo-epam** [comment]
it is 72 already released but still no events tab

**Comment by nchevobbe** [comment]
@Anton-Shakalo-epam  you may have missed https://developer.mozilla.org/en-US/docs/Tools/Debugger/Set_event_listener_breakpoints

**Comment by nchevobbe** [comment]
@janodvarko looks like we can close this issue right?

**Comment by Anton-Shakalo-epam** [comment]
@nchevobbe well, there is still no way to remove event listener from node in inspector. Maybe you can close this one but what is needed to remove exact event listener from node and this is seems to be missing

**Comment by nchevobbe** [comment]
this repo was about the debugger, not the inspector. Please file a bug on bugzilla describing what it should do https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Inspector

**Comment by janodvarko** [comment]
Closed already

Honza
