### ISSUE TITLE
Have a way to get at event listeners from the watch/variable views

### ISSUE THREAD

**Issue by bzbarsky** [devtools-html/debugger.html#4751]
If a value in the watch/variable view is an EventTarget, it would be nice to be able to expose the event listeners on it.

**Comment by codehag** [comment]
Hi bzbarksy, thanks for the report. Can you be a bit more specific about what you are expecting to happen?

**Comment by bzbarsky** [comment]
@codehag You know how in the devtools inspector, if you have a node with event listeners it has a little "ev" marker and if you click that you can look at the event listener?

This issue is about having similar functionality for values being inspected in the debugger.

**Comment by jasonLaster** [comment]
Thanks, i moved this request to https://github.com/devtools-html/devtools-core/issues/910 where we handle formatting console/debugger variables.
