### ISSUE TITLE
Debugging inline Content Scripts inserted by Webexts

### ISSUE THREAD

**Issue by mastacheata** [devtools-html/debugger.html#4754]
I've stumbled across this problem while trying to debug a User Script in Greasemonkey.
Greasemonkey inserts userscripts as inline code (i.e. not a file inside the extension) via browser.tabs.executeScript
Debugging the UserScript / Content Script of Greasemonkey inside a webpage would usually involve opening the website and then checking the Debugger panel inside the Dev Tools to find the content script inserted by the extension.
That fails because there is no file with the userscript code in the debugger panel.

If you put a debugger statement into the userscript code, it will properly stop at the debugger statement, have all the right variables loaded in the scope and even has the correct function names in the callstack.
The only problem is it has no file in the "editor" panel, but instead shows the resource://gre/modules/ExtensionContent.jsm file. (That's where the executeScript API is actually happening)

Debugging the extension itself doesn't work either. As soon as the executeScript command is done, it's out of the Extension scope and back in the browser scope.
At least for the case where there's a debugger statement in the content script code, it should be possible to have a dummy file for displaying it's code.

I'm not sure if the Debugger Frontend can get the code that's inserted if there's no breakpoint or exception inside the inline Content Script.

Here's a minimalistic demo extension:
https://github.com/mastacheata/debug-content-scripts-demo-extension
(You'll have to debug the extension for it to stop after creating the tab and then open the debugger for the new tab to see the code injection and have it stop in the injected code)

I had also opened a bug for that in bugzilla on friday, before noticing that the GitHub is way more frequented for the debugger.
https://bugzilla.mozilla.org/show_bug.cgi?id=1418547

**Comment by jasonLaster** [comment]
Thanks for filing a detailed report!

**Comment by jasonLaster** [comment]
Closing as this is in bugzilla and the bug is in the server
