### ISSUE TITLE
[Tabs] Remove stray dark line underneath Debugger tab strip

### ISSUE THREAD

**Issue by violasong** [devtools-html/debugger.html#4756]
Easiest fix is to simply remove the background-color from .editor-pane.

Ideally, could instead figure out why there's this 1px-tall extra bottom spacing in the first place.

Here it is highlighted in red:
![image](https://user-images.githubusercontent.com/55994/33043790-760f79d0-cdfb-11e7-8147-e5d03cbfccb5.png)

Bonus nitpick:
![image](https://user-images.githubusercontent.com/55994/33043836-988a30ea-cdfb-11e7-82c7-97c15e2c58dd.png)
After removing background-color from .editor-pane I see this tiny gray line right at the top of the line number gutter that's making that little area look weird. Would be cool if we could get rid of that too.

**Comment by pradeepgangwar** [comment]
@codehag This issue looks fixed. Please close this to avoid confusion. 😃

**Comment by violasong** [comment]
It looks like this is happening again in Nightly:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/55994/37616237-826f8fd4-2b6c-11e8-8120-3b770e5f199e.png">

**Comment by jasonLaster** [comment]
I'm seeing it in nightly as well

**Comment by Malachi-Holden** [comment]
I am not able to replicate this issue.
I am using Ubuntu 16.04, with Firefox nightly Version 61.0a1 (2018-04-03) (64-bit)
![screenshot from 2018-04-03 14-22-47](https://user-images.githubusercontent.com/35282360/38267959-ec756054-374a-11e8-8521-6eff49c76f71.png)

**Comment by darkwing** [comment]
This should be gone now, I've not seen in ages
