### ISSUE TITLE
Add tooltip to icons

### ISSUE THREAD

**Issue by jbhoosreddy** [devtools-html/debugger.html#476]
Adding tooltips to the icons should help people out who are not familiar with what the buttons do.

<img width="136" alt="screen shot 2016-08-03 at 3 11 39 pm" src="https://cloud.githubusercontent.com/assets/2481105/17383555/656e751c-598b-11e6-834f-f85bcb4c7b44.png">

**Comment by jasonLaster** [comment]
Great find
