### ISSUE TITLE
Pretty-Printed Tab wont Close

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4763]
I'm trying to close a pretty print tab and...it keeps coming back:

![wontclose](https://user-images.githubusercontent.com/46655/33099935-45ba0272-ced8-11e7-85b7-0dbb46285511.gif)

If I close the original tab first, *then* close the pretty print tab, it finally stays closed.  When I open the original tab again, however, the pretty print tab also shows up.

**Comment by darkwing** [comment]
Sorry, this might be a dupe of #4714

**Comment by jasonLaster** [comment]
yep
