### ISSUE TITLE
Color change for Dark Debugger selected text readability (Photon polish uplift)

### ISSUE THREAD

**Issue by violasong** [devtools-html/debugger.html#4765]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/55994/33105658-278609a8-cee3-11e7-9eba-74a95967e0f5.png">

Currently in dark mode Debugger, selected text is difficult to read because of the light blue highlight color. Let's use this color instead: #353B48. (It's the same color as the Inspector's line-hover color.)

I'm hoping to get this into 58, so it would be ideal if this patch could be submitted for uplift consideration before December 4th.

**Comment by leibale** [comment]
/unclaim

I looked into the code and it looks like that [devtools-mc-assets](https://hg.mozilla.org/integration/mozilla-inbound/archive/tip.zip/devtools) package is downloading [this zip file](https://hg.mozilla.org/integration/mozilla-inbound/archive/tip.zip/devtools) and settings the themes colors by that zip. I don't have access to change this zip, but I think that @jasonLaster can help you with this one.

(I can override this particular variable, but it feels ugly to me..)

**Comment by codehag** [comment]
@leibale Hey! thanks for taking a look
@violasong do we want this to change for all tools, or just the debugger?

**Comment by violasong** [comment]
@codehag Thanks for asking about this - I realized this needs to be changed for Style Editor too (so maybe all codemirror tools?). Inspector/Console don't need this change.

**Comment by gabrielluong** [comment]
This issue probably belongs to m-c and not debugger.html since the changes here need to persist across the entire toolbox for every CodeMirror instance.

**Comment by AnshulMalik** [comment]
Created an issue in bugzilla, and a patch 
https://bugzilla.mozilla.org/show_bug.cgi?id=1422244
