### ISSUE TITLE
Duplicate conditional-breakpoint-panel when send "Ctrl + B"

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#4767]
**Steps to reproduce:**
1. Open any scripts
2. Focus (set cursor) on any lines
3. Add conditional breakpoint on the same line
4. Send "Ctrl + B"

**Actual Results:**
conditional-breakpoint-panel will be duplicated.

![duplicate-conditional-breakpoint-panel](https://user-images.githubusercontent.com/13914314/33115954-3e8e173a-cfa6-11e7-9d45-bb3142f651ae.png)

**Expected Results:**
No any actions?

**Comment by nyrosmith** [comment]
@magicp-github Did you see this behavior in launchpad or Firefox panel? In launchpad I am unable to reproduce it

**Comment by magicp-github** [comment]
I can reproduce in the latest Nightly build (20171123100420).

**Comment by nyrosmith** [comment]
@magicp-github can you reproduce it in launchpad too? I tried several times but it seems to me it's already fixed here

**Comment by magicp-github** [comment]
Yes, I can reproduce it in launchpad too.

**Comment by nyrosmith** [comment]
Hmm maybe I am doing something wrong. Habe you already joined our slack? Maybe we can do a quick hangout so this can get tackled fast

**Comment by magicp-github** [comment]
I don't use slack. Step 2-3 is important. Focused line and conditional breakpoint should be on the same line. "Ctrl+B" will make a breakpoint on the focused line, then conditional breakpoint panel will be duplicated.

**Comment by nyrosmith** [comment]
Thx for clarification!
