### ISSUE TITLE
[Outline] functions should not wrap

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4776]
We should use CSS to keep the functions from wrapping. perhaps `overflow-x: hidden`

### good
<img src='https://shipusercontent.com/5e1e5debff1134773db3cb30d62b6422/Screen%20Shot%202017-11-22%20at%2011.25.35%20PM.png' title='Screen Shot 2017-11-22 at 11.25.35 PM.png' width=309>

### not great
<img src='https://shipusercontent.com/e6868e0807c8bf5602df0915c18c2409/Screen%20Shot%202017-11-22%20at%2011.25.24%20PM.png' title='Screen Shot 2017-11-22 at 11.25.24 PM.png' width=224>

**Comment by codehag** [comment]
i understand that this might be an easy patch to do, but i would rather take this out right now. we have a lot of other work and this increases the maintenance burden. Outline view is also behind a feature flag right now. Lets try to make performance bugs available rather than features.
