### ISSUE TITLE
batch update breakpoints

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#4782]
we currently add breakpoints one at a time. this slows down start up time as it requires for every file, every breakpoint to be checked. We should batch add the breakpoints, and take care of syncing later once everything is finished.

for this issue, we need a reducer that allows us to add a set of breakpoints. this would be added to reducers/breakpoints.js, with type `ADD_BREAKPOINTS`

might look something like this

```javascript
case "ADD_BREAKPOINTS":
  const newState = state.merge("breakpoints", action.breakpoints)
  return newState;
```

**Comment by jasonLaster** [comment]
@codehag can you add some more information here.

1. are we discussing updating `checkPendingBreakpoints`
2. are we concerned about touching the store too often?
3. are we worried about too many Editor/Breakpoints renders?
4. are we worried about too many SecondaryPanes/Breakpoints renders?
