### ISSUE TITLE
Defer loadSourceText

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#4783]
we should not load the source text before showing the UI, because this is slow and frustrating for users. at the moment, loading a source, selecting a source, and checking breakpoints is all done at once. instead we should try this schedule

- load all sources
- load all sourcemaps
- load all breakpoints
- check selected source (only once)
- load selected source (only once)
- sync breakpoints (which will load the source text for a few more files, but the debugger will already be usable)

**Comment by jasonLaster** [comment]
I believe we're doing this now :)

If not, we can re-open
