### ISSUE TITLE
add loading indicator for large files being loaded

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#4784]
At the moment, it is sometimes unclear if the debugger is working or not when it it loading a large file

we should add a loading screen to improve the loading experience!

This can be a simple loading indicator, like the string "loading.." for now

we have three states for sources, "unloaded", "loading" and "loaded". this might be a good place to start

**Comment by jasonLaster** [comment]
@codehag we currently show a loading message in the editor: https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/index.js#L480-L493

is that what you're referring too?
