### ISSUE TITLE
[breakpoints] Clicking on "Step over" button doesn't take me to next line when using production build of React

### ISSUE THREAD

**Issue by vijaykm2** [devtools-html/debugger.html#4785]
Clicking on "Step over" button doesn't take me to next line when using production build of Reactjs.

Here are steps to reproduce this issue.

1. Create a new sample Reactjs project using create-react-app.
2. Edit the App.js file so that it looks like the attached screenshot.
3. Create the production build of this project using command "yarn build".
4. Install serve.js using command "npm install -g serve".
5. Serve this app using "serve -s build".
6. Open this app on "http://localhost:5000".
7. After page loads, open debugger.
8.  In the App.js file, add a breakpoint  first console.log and reload the page.
9. When the debugger pauses at breakpoint, click on stepover button. 

Actual behavior:
Stepover button doesn't take me to next line. It takes me to some other line.

Expected behavior:

Stepover button should take me to next line.

**Comment by vijaykm2** [comment]
<img width="1680" alt="screen shot 2017-11-23 at 2 01 34 pm" src="https://user-images.githubusercontent.com/6619551/33187921-19e359d0-d05b-11e7-9947-35c7a98186cb.png">

**Comment by nyrosmith** [comment]
Repo for testing
 https://github.com/vijaykm2/Reactjs-bug-4785

**Comment by vijaykm2** [comment]
Another issue i found: If i keep a breakpoint on return statement, debugger doesn't stop at the return statement.

**Comment by jasonLaster** [comment]
@vijaykm2 I believe we fixed this in github recently. I'll let you know next week when it lands in Firefox Nightly.

The debugger server supports stepping to new locations, unfortunately with source maps the server goes to a new location that maps to the same original location. We added a new check in the client to guarantee that we move original locations as well.

**Comment by jasonLaster** [comment]
@vijaykm2 can you see if this is fixed on nightly?

**Comment by jasonLaster** [comment]
Looks fixed!

![](http://g.recordit.co/iMhjI4QB4Q.gif)

**Comment by jasonLaster** [comment]
Generated Stepping looks good too

![](http://g.recordit.co/8zrSQbcKVk.gif)
