### ISSUE TITLE
Storybook is broken

### ISSUE THREAD

**Issue by unconfident** [devtools-html/debugger.html#4788]
As of now there are two problems with it:

- It doesn't build due to attempts of resolving a missing file from a missing dependency
- react-redux's `connect` throws errors in runtime about Redux Store missing from the context. 

And it just seems to be abandoned in general.

The first problem was introduced in #4332 after launchpad has been updated and dependency which this package directly never depended upon disappeared from the dependency tree. Now it throws bunch of 

```
Module not found: Error: Can't resolve 'devtools-modules/src/themes/dark-theme.css`
```

errors during the build step. The css file also is not present in the latest version of `devtools-modules`. Replacing `import "devtools-modules/src/themes/dark-theme.css";` with `
import "devtools-mc-assets/assets/devtools/client/themes/dark-theme.css";` everywhere under the the `src/components/stories` fixes it but I'm not confident in those two being the same file. Maybe instead these imports simply needs to be removed. I can't tell - it's the first time I'm looking at this code base

I don't know if storybook is useful at all, but seeing that it was broken for over a month without anyone noticing leads me to thinking that maybe nobody needs it and it can be simply removed from the codebase altogether

**Comment by jasonLaster** [comment]
Thanks for the fantastic writeup. It's true that we're not using storybook at the moment, but that can be explained by two factors: 1) prioritizing performance post-launch, 2) not having CI to prevent regressions

- I'd like to see it fixed
- I'd like to setup percy again. We re-extended our license recently

**Comment by jasonLaster** [comment]
Hey @Anzumana how's it going? Do you think you have time to look into this?

I took the "in progress" label off the issue, because it'd be great to get other's eyes on it as well...

I hope to use storybook in a week to show the different babel transformed scopes we're working on improving like async functions, forOf, and modules. It'd be awesome to have storybook working so we can use it for this!

**Comment by Anzumana** [comment]
yeah time is an issue still :/

**Comment by jasonLaster** [comment]
I'm closing this issue as we fixed the primary blocker. But I think we have some other issues with storybook which we should probably address as well...
