### ISSUE TITLE
[Breakpoints] Does not stop at breakpoint when sourcemap by rollup + babel

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#4799]
**STR:**
1. Go to https://jnachtigall.github.io/bp/bp.html
2. Open `app.js` and set breakpoint to line 2
3. Reload

**AR:**
Debugger does not stop at the breakpoint

**ER:**
Should stop (works like this in Chrome).

![image](https://user-images.githubusercontent.com/3307404/33261860-8f747db2-d364-11e7-932d-057ab93134e8.png)

The included js file is actually `app-production.js` which has a `//# sourceMappingURL=app-production.js.map` in it pointing to this `app.js`. FWIW, the sourcemap and `app-production.js` is created using [rollup](https://github.com/rollup/rollup) and [its babel plugin](https://github.com/rollup/rollup-plugin-babel).

I am using Firefox Nightly 59.0a1 (2017-11-26) (64-bit) on Windows 10.

**Comment by jasonLaster** [comment]
Great writeup

**Comment by jnachtigall** [comment]
I forgot to say (don't know if this is important) that when I remove the `jquery document ready` wrapper, then the breakpoint is hit successfully. I noticed this while trying to create a minimal test case. That is, having 
```
console.log('My viewport is: ');
```
in the original `app.js` instead of
```
$(function() {
  console.log('My viewport is: ');
});
```
then breakpoint would be hit. That is, when the script line is immediately called when script is loaded and not when `document.ready`. Maybe this helps narrowing down the bug.

**Comment by jasonLaster** [comment]
Nice. I wonder what the map is doing. Do you have a repo where we can play with it and rebuild?

**Comment by jnachtigall** [comment]
I added the build tools at https://github.com/jnachtigall/jnachtigall.github.io/ so you can play with it

1. Clone and change to `bp` folder
2. `npm install`
3. `npm run build` or `npm start` (which also builds), see `bp/package.json`.
4. Set breakpoints in https://github.com/jnachtigall/jnachtigall.github.io/blob/master/bp/src/app.js

FWIW, I noticed that in the console the working breakpoint (outside of jQuery's `document.ready`) shows the correct sourcemapped file, whereas the not-working breakpoint points to the production file:
![image](https://user-images.githubusercontent.com/3307404/33376897-c4c43884-d50f-11e7-89e5-f068e164ecb0.png)

**Comment by jasonLaster** [comment]
Thanks for the clear STR!

I just investigated and learned some interesting things:


Here is the breakpoint we try to add
```json
{
    "id": "http://localhost:8080/app-production.js:3:13",
    "disabled": false,
    "hidden": false,
    "loading": false,
    "condition": null,
    "location": {
      "sourceId": "server1.conn9.child1/source29/originalSource-9cf7e6cd063b0710192a3fffb4c483de",
      "sourceUrl": "http://localhost:8080/Users/jlaster/src/_daily/Feb-14/jnachtigall.github.io/bp/src/app.js",
      "line": 3,
      "column": 2
    },
    "astLocation": {
      "offset": {
        "sourceId": "server1.conn9.child1/source29/originalSource-9cf7e6cd063b0710192a3fffb4c483de",
        "sourceUrl": "http://localhost:8080/Users/jlaster/src/_daily/Feb-14/jnachtigall.github.io/bp/src/app.js",
        "line": 3,
        "column": 2
      }
    },
    "generatedLocation": {
      "line": 3,
      "sourceId": "server1.conn9.child1/source29",
      "column": 13,
      "sourceUrl": "http://localhost:8080/app-production.js"
    }
  }
}```

notice that the generated column in 13 and the original column is 2. The reason for this is

1. the debugger maps (3,undefined) to (3,13) to calculate the generated location
2. the debugger sets the bp to (3,13) 
3. the debugger maps (3,13) to the original location of (3,2) 
4. the debugger saves those two locations

**Comment by jasonLaster** [comment]
last point here, the server currently chooses not to use any entrypoints because the only one is at col 2, and the client is requesting column 13...

**Comment by jnachtigall** [comment]
@jasonLaster fwiw, the screenshot links above do not render.

**Comment by jasonLaster** [comment]
![Screen Shot 2018-02-14 at 4.25.48 PM.png](https://shipusercontent.com/620f72c119ad0ac75f7ed5494b26eb1b/Screen%20Shot%202018-02-14%20at%204.25.48%20PM.png)
![Screen Shot 2018-02-14 at 4.25.39 PM.png](https://shipusercontent.com/20bfb478a0a3418f33752ff7e6f4660c/Screen%20Shot%202018-02-14%20at%204.25.39%20PM.png)
![Screen Shot 2018-02-14 at 4.25.29 PM.png](https://shipusercontent.com/5d7bfeaaedd4a187e18cf35dcc74d7d7/Screen%20Shot%202018-02-14%20at%204.25.29%20PM.png)

**Comment by jasonLaster** [comment]
this will be done here: https://bugzilla.mozilla.org/show_bug.cgi?id=1440093

it's getting close :)

**Comment by jasonLaster** [comment]
Landed!
