### ISSUE TITLE
Explain the gotoline shortcut

### ISSUE THREAD

**Issue by nicofrand** [devtools-html/debugger.html#4804]
As there is an explanation to say "Use CTRL+p" or "Use CTRL+Shift+F" to search files/functions, there should be an explanation to say "Use CTRL+:" (or "CTRL+;" on azerty layouts) to go to a specific line.

"CTRL+:" or "CTRL+;" are really not easy to find out, and the keys are not easy to reach… I wish I could tell the debugger to use "CTRL+G" instead like on Chrome or some IDEs, but an explanation would be great to begin with I think.

**Comment by gnadelwartz** [comment]
if `CTRL+g` is not used it can be a second (compatibility) shortcut for goto line

**Comment by codehag** [comment]
CTRL+g is being used, but perhaps not for the most necessary action. It is currently used to search again.

We need to add an explanation in any case; it can be added in the shortcuts overlay.

<img width="1234" alt="screen shot 2017-11-28 at 12 35 07" src="https://user-images.githubusercontent.com/26968615/33317908-0312a62a-d439-11e7-85a0-5a1344ffc40b.png">


```diff
diff --git a/src/components/ShortcutsModal.js b/src/components/ShortcutsModal.js
index a842b5f0..f5179e4c 100644
--- a/src/components/ShortcutsModal.js
+++ b/src/components/ShortcutsModal.js
@@ -86,6 +86,7 @@ export class ShortcutsModal extends Component<Props> {
           L10N.getStr("shortcuts.functionSearch"),
           formatKeyShortcut(L10N.getStr("functionSearch.key"))
         )}
+        // add the CTRL+: shortcut here
       </ul>
     );
   }
```

**Comment by tahmidefaz** [comment]
\claim
@davisv007, @roberthosking, @sanginovs and I will be taking a look at it.

**Comment by tahmidefaz** [comment]
/claim
@davisv007, @RobertHosking, @sanginovs and I will be taking a look at it.

**Comment by tahmidefaz** [comment]
/unclaim
We got some feedback on a different PR request that we did. Unclaiming it because if anyone wants to work on it can go ahead. Sorry for the inconvenience.

**Comment by JacobTM** [comment]
/claim I will be working on this issue along with @michaelm396 & @coledu

**Comment by jasonLaster** [comment]
the ctrl+g shortcut comes from editors like atom

Try 

1. cmd+f
2. search
3. close search bar
4. cmd+g - will jump to the next result

http://recordit.co/NVvJZNVJEe

not sure what to do here. we should have a google doc with all of our shortcuts and rationale... hard to keep track of :)

**Comment by nicofrand** [comment]
In my Atom (without modfiying it): 
![screenshot_20171201_081025](https://user-images.githubusercontent.com/3419050/33471776-2b8f5d0e-d66f-11e7-8a0d-f6f475c73dc4.png)

**Comment by JacobTM** [comment]
/unclaim we were working on this bug for a class and since the semester is almost over now, we are going our separate ways

**Comment by ggl** [comment]
How about pressing Ctrl/Cmd+F again jump to the next result instead of clearing the search field if search is already open and Ctrl/Cmd+G for go to line #?

Atom and Sublime Text keybindings are not really consistent across platfroms. MacOS uses Cmd+F/Cmd+G for find/find next and Ctrl+G for go to line, while Linux is using Ctrl+F/Ctrl+G for find/go to line and F3 for find next.

https://github.com/nwinkler/atom-keyboard-shortcuts
