### ISSUE TITLE
Add PrettyPrint Icon to Tabs Dropdown

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4807]
It would be nice to repeat the Pretty Print icon in the tabs dropdown:

<img width="730" alt="dropdownicon" src="https://user-images.githubusercontent.com/46655/33291215-b2365868-d38a-11e7-8926-6cd184731fe3.png">

Without the `{}`, it's impossible to know which tab you're clicking on if both are open

**Comment by lukaszsobek** [comment]
Feature implemented.
