### ISSUE TITLE
[WatchExpressions] occasionally evaluated in the wrong scope

### ISSUE THREAD

**Issue by jimblandy** [devtools-html/debugger.html#4809]
- Visit [timers](https://dbg-timers.glitch.me/).
- Set a breakpoint at client.js line 12.
- Add `id` as a watch expression.
- Press the "stuff" button.
- Resume various times.

I occasionally see the watch expression `id` being evaluated apparently in the global scope:

![image](https://user-images.githubusercontent.com/751272/33293467-bbb10162-d381-11e7-92c0-e08d9af77ab0.png)

Note that the screenshot shows that we are evaluating the expression while the call to `startAnimationTimer` is on the stack, yet the scope in which we seem to be evaluating is the global scope.

I might just be confused about what's going on here, but at the very least, I don't think we should ever pause in errors in watch expressions.

**Comment by codehag** [comment]
thanks. i will try to confirm that this is happening. are you pausing on exceptions by any chance?

**Comment by jimblandy** [comment]
The screen shot says "paused on exception", so I assume so?

**Comment by codehag** [comment]
😅 good point. i was looking for the pause exception button

**Comment by AlexisDeschamps** [comment]
I think I am unable to replicate on Windows 10 with Firefox Nightly in the launchpad or inside a panel. I tried with `Ignore exceptions`, `Pause on uncaught exceptions`, and `Pause on all exceptions`. I think I am just not hitting an exception at all though and the bug could only occur then.

**Comment by jasonLaster** [comment]
I'm no longer seeing this.
