### ISSUE TITLE
Blackbox Icon Isn't Removed When Tab Closed

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4810]
I closed a blackboxed tab but the icon didn't go away from the Outline tab

<img width="635" alt="blackboxlegacy" src="https://user-images.githubusercontent.com/46655/33298846-4f8e8f5e-d3ae-11e7-8a1e-a909cce0efb1.png">

**Comment by darkwing** [comment]
Also worth noting that opening that item again starts the tab in blackboxed mode, which I'm not sure we want.

**Comment by codehag** [comment]
thanks for the bug report! If anyone wants to pick this up, please ping me and I will walk you through where the issue is likely.

**Comment by codehag** [comment]
@darkwing -- after looking at the behavior, i am wondering if we want the blackboxed status to go away if the tab is closed. I think you can black box a source and it shouldn't be unblack boxed until you explicitly say so?

it feels like you shouldnt need to open the file to black box it as well.. what do you think?

**Comment by jasonLaster** [comment]
yeah, i think the icon is just as important as ever. From a UI perspective though it is probably too bright, maybe it should be the same grey :)

also, there should be a context menu item to unblack box it, not sure if that's the case.

**Comment by tohmjudson** [comment]
I'd happily revisit this. For the icon being bright, I went with that since it matched what was going on in the tab and in the footer icon color change, but I see what you mean... it really stands out and might be better that same grey.

 I do agree that the icon should stay if even if the tab is closed

**Comment by jasonLaster** [comment]
i think we should keep the icon there as long as the source is blackboxed
