### ISSUE TITLE
Move network throttle tool to network panel

### ISSUE THREAD

**Issue by domoritz** [devtools-html/debugger.html#4816]
https://blog.nightly.mozilla.org/2016/11/07/simulate-slow-connections-with-the-network-throttling-tool/ introduces the network throttle tool. In the comments, many people said that the tool is hard to find because it is hidden in the responsive mode. Chrome has the throttle feature on the network panel. I suggest to move or duplicate the feature so that it is accessible from the network panel. 

Sorry if this is the wrong place to file this issue. Should it be filed here or at https://bugzilla.mozilla.org/?

**Comment by bomsy** [comment]
heya @domoritz yeah this should be file in bugzilla.

**Comment by domoritz** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1421948
