### ISSUE TITLE
[Breakpoint] Show condition for conditional breakpoints in list

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4824]
The only indicator right now is a small orange bar.

It would be nice to see the condition, cut off by ellipsis to fit; maybe with click to edit for quick access to revising it.

**Comment by codehag** [comment]
@digitarald,

maybe something like this? 

<img width="299" alt="screen shot 2017-11-29 at 10 57 24" src="https://user-images.githubusercontent.com/26968615/33369229-25b7dd7e-d4f4-11e7-9fdd-d0a1ca26b1ec.png">

**Comment by cristidrg** [comment]
Is this issue available?

**Comment by jasonLaster** [comment]
I'd like to look at overhauling the breakpoint UI soon to include grouping breakpoints by file and include a text snippet.

**Comment by jasonLaster** [comment]
I'm closing this bug as we'll solve it in the larger breakpoint ux sprint
