### ISSUE TITLE
Credentials and cookies issues

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#4825]
we are experiencing some issues with sources fetched with credentials. 

+ https://twitter.com/ryancoshea/status/930818874290864128
+ https://github.com/devtools-html/debugger.html/issues/4812
+ https://bugzilla.mozilla.org/show_bug.cgi?id=1404245

there is also a bug where private mode uses cookies from a logged in session, but i cannot find the bug right now. This issue can be used as a location to collect more bug reports regarding this.

**Comment by jasonLaster** [comment]
I'm moving this to the icebox. We can re-evaluate at the start of the next release
