### ISSUE TITLE
Switching from prettified to unformatted code hangs 8s

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4831]
https://perfht.ml/2j56cXR

STR:

- Open application.js on Slack
- Prettyprint. Get coffee, this can take a while
- Switch back to unformatted

ER:
- Fast source switching

AR:
- 8s hang

**Comment by jasonLaster** [comment]
here's a link: https://devtools-html.slack.com

**Comment by jasonLaster** [comment]
Looks like we spend a bunch of time in codemirror. This is good news, it's easy to fix!

<img src='https://shipusercontent.com/257d75c8d29d9c1e736bc8fd00f3cefc/Screen%20Shot%202017-12-01%20at%209.40.31%20AM.png' title='Screen Shot 2017-12-01 at 9.40.31 AM.png' width=1003>
<img src='https://shipusercontent.com/7ff70ca4217d0e1feefa29930433cd8c/Screen%20Shot%202017-12-01%20at%209.40.08%20AM.png' title='Screen Shot 2017-12-01 at 9.40.08 AM.png' width=1020>

**Comment by AnshulMalik** [comment]
Switching works smoothly on chrome, firefox seems to be lagging.

**Comment by jasonLaster** [comment]
@AnshulMalik do you mean that is fine when the debugger is run in the launchpad in chrome?

**Comment by AnshulMalik** [comment]
Yep, but seems like it doesn't work always, it was working fine with `debugger.js` from devtools front. But when tested with `https://www.joinhoney.com/`, chrome is also stuck for a long time.

**Comment by jasonLaster** [comment]
hmm - could you try w/ firefox nightly and the old debugger UI. It's available by disabling the new one is the devtools settings.

**Comment by AnshulMalik** [comment]
Old debugger takes behaves the same way, slow!

**Comment by jasonLaster** [comment]
haha - must just be really big. Thanks @AnshulMalik
