### ISSUE TITLE
[PrettyPrint] Pretty document loaded first time has wrong properties

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#4832]
STR:
- open debugger on minimized file `https://apis.google.com/js/api.js`
- press `ctrl+shift+i`
- open `src/components/Editor/index.js`
- place breakpoint  ~line 237 inside `componentDidUpdate` after the line `const { selectedLocation, selectedSource } = this.props;`
- prettify js
- look at Scope > Local > selectedSource > loadedState
- look at Scope > Local > selectedSource > isPrettyPrinted

ER:
first load:
- selectedSource.get("loadedState") == "loading"
- selectedSource.get("isPrettyPrinted") == "true"
All loads after:
- selectedSource.get("loadedState") == "loaded"
- selectedSource.get("isPrettyPrinted") == "true"

AR:
first load:
- selectedSource.get("loadedState") == "loaded"
- selectedSource.get("isPrettyPrinted") == "false"
All loads after:
- selectedSource.get("loadedState") == "loaded"
- selectedSource.get("isPrettyPrinted") == "true"

Image:
![pretty_print_bug_overlay](https://user-images.githubusercontent.com/23530054/33458001-cadcf4a2-d624-11e7-9020-5cd12efc522a.png)

**Comment by jasonLaster** [comment]
Nice find. Can you share a test case and the steps to follow...

**Comment by lukaszsobek** [comment]
updated desc to make it clearer.
