### ISSUE TITLE
Massive hang after clicking pretty print a few times

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4833]
STR:

- Click pretty print a few times application.js on Slack

AR:
- Even after the pretty printed script shows up, the whole UI beachballs

Profile with 20s main process hang: https://perfht.ml/2BnIjS2

**Comment by lukaszsobek** [comment]
Just to make sure, what does to beachball mean?

**Comment by codehag** [comment]
beachball occurs on macs, and it is an indicator that the system is waiting for something

**Comment by digitarald** [comment]
Also called Eternal Flame: https://xkcd.com/961/

**Comment by AnshulMalik** [comment]
This can be closed ?
