### ISSUE TITLE
[Performance] Replace subsequent .toJS() calls with reference to stored value

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#4837]
.toJS() seems to be an expensive function. Wherever possible it would be nice to call it once, store the value and use the value instead of calling the function over and over again. 

At the moment of writing there are 94 instances of .toJS() in the code. This issue would require looking at the functions where .toJS() is called and, if it is called two or more times within the same function to assign the result of .toJS() to a variable and reference that instead of executing the function several times.

Todo List
- [ ] Actions
- [ ] Components
  - [ ]  Source Tree #5738

**Comment by cristidrg** [comment]
I can work on this

**Comment by bomsy** [comment]
@cristidrg go for it! You can claim it if you like

**Comment by codehag** [comment]
this might need to be broken up, since this is a pretty large change, and will require a lot of things to be changed. @cristidrg let us know if you need help keeping it managable!

**Comment by cristidrg** [comment]
Sure, I'll share my insights after I'll work on it for a bit.

**Comment by jasonLaster** [comment]
This will be 10X easier now that sources uses a record.

We should be able replace ALL of the toJS calls now because `source.text` works as well as `source.get("text")`

**Comment by jasonLaster** [comment]
So... I ran into a problem where i accidentally tried to set a value in a source record. Now that the objects _look_ like objects we have to be careful :)

**Comment by jasonLaster** [comment]
I think we've basically finished this. @lukaszsobek thoughts?

**Comment by lukaszsobek** [comment]
@jasonLaster I'd agree, and we got rid of a lot of items.
Just doing a final sanity test for the remaining items to see if there is anything more to squeeze out of it.

**Comment by jasonLaster** [comment]
sounds good

**Comment by lukaszsobek** [comment]
We're down to about 40 or so. The remaining toJS are either of no relevance to the performance of the working application or needed. Closing this.
