### ISSUE TITLE
Hot reloading broken

### ISSUE THREAD

**Issue by Anzumana** [devtools-html/debugger.html#4841]
In our readme we state that the react hot reloader is currently broken 
https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#hot-reloading-fire

It seems that we have not yet integrated the hot reloader into our debugger therefore we still need to integrate it
https://github.com/gaearon/react-hot-loader

**Comment by jasonLaster** [comment]
lets solve this in the launchpad
