### ISSUE TITLE
[Pretty Print] unable to pretty print minfied JS file on stickerapp.com

### ISSUE THREAD

**Issue by miketaylr** [devtools-html/debugger.html#4846]
Using the latest Nightly on OSX.

STR:

1. open `https://stickerapp.com/editor/edit/new/single/path/0/97/51/25/glossy_coated/?file=%7B%22width%22%3A388%2C%22height%22%3A369%2C%22thumb_url%22%3A%22%2Ftemp%2F12%2F01%2F1512148395_5a218dab91d95_thumb.png%22%7D`

(who knows how long that URL will be valid, if it's not anymore, just go to https://stickerapp.com/custom-stickers/ and click "upload file" to get to the right place).

2. In the debugger, navigate to `https://d6ce0no7ktiq.cloudfront.net/build/2.7.38/editor.js`
3. Press pretty print

Expected: it works
Actual: nothing. No errors in the browser console either. :(

**Comment by lukaszsobek** [comment]
Works for me on auto pretty print.

![peek 2017-12-02 22-30](https://user-images.githubusercontent.com/23530054/33519886-83b5d4f8-d7b0-11e7-8f43-3c071e7535f2.gif)

**Comment by miketaylr** [comment]
@lukaszsobek how do I enabled that?

**Comment by lukaszsobek** [comment]
go to `assets/panel/prefs.js`
line 16
change `auto-pretty-print` from `false` to `true`

**Comment by bomsy** [comment]
@miketaylr In nightly, i think there's `devtools.debugger.auto-pretty-print` in `about:config` also

**Comment by miketaylr** [comment]
Thanks... I use DevEdition (and don't run with my own modded builds of DevTools). Hopefully that pref will ride the trains soon.

**Comment by jasonLaster** [comment]
@bomsy @mikeataylr can we close this?

**Comment by miketaylr** [comment]
> @bomsy @mikeataylr can we close this?

I... don't know. A vanilla Nightly debugger can't pretty print that file. That feels like a bug? Are there plans to expose auto pretty print in devtools settings somewhere?

**Comment by jasonLaster** [comment]
I see. Let's leave it open.

We're adding the auto-pretty-print option in the devtools settings pane.

**Comment by miketaylr** [comment]
So... I just re-tested, and I can't reproduce anymore in 58 DevEdition. What I *think* is happening is that it's just very slow. There's no visual feedback when clicking the `{ }` button, so I think I was mentally bailing before it finished. Now I can see an extra prettified editor.js tab if I wait 3 to 4 seconds.

(is there a feature request bug open to automatically focus the prettified tab when it's available?)

So let's close.

**Comment by jasonLaster** [comment]
I believe so. We're working on some of the loading state stuff too:

1) disable/hide the button
2) create the tab early and show a loading state
