### ISSUE TITLE
[Performance] Webpack devtool modes slow down page load

### ISSUE THREAD

**Issue by ChrisGitter** [devtools-html/debugger.html#4849]
I tried to use the debugger with a big React/Redux project using Webpack for bundling. At first load the debugger opens slowly. The site load itself is not effected at first. But when I set a breakpoint somewhere and then reload, the site load takes up to a minute or so. It also freezes the inspector tabs and the CPU is under some load.

I recently tried to switch from chrome to Firefox and I use the same settings as I do in Chrome, where debugger and breakpoints work without any delay or preformance issues.

My webpack config uses the 'cheap-module-eval-source-map' setting.

To reproduce I can take any React projects that use webpack, for example: https://github.com/andrewngu/sound-redux
I cloned it, changed the devtool setting in webpack to use source maps and it showed the same issues.

I have tried this with ArchLinux and Ubuntu, both on latest versions and both using the latest Firefox developer edition.

**Comment by jasonLaster** [comment]
Thanks @ChrisGitter! We'll take a look :)

**Comment by tbaud0n** [comment]
I'm not using webpack but my webapp takes more than 12 seconds to load if the devtools are open and only 2-3 seconds if devtools panels are closed.
It's a local development and the page loads 280 files (mainly js + css files). 
@jasonLaster do you think it's linked to this issue or do I need to feel a new issue?

**Comment by jasonLaster** [comment]
Hey @tbaud0n - thanks for filing :) we're working on this now and have 3 fixes for it

1. throttle updating the redux store for each source
2. schedule how we load source maps so we don't load them immediately
3. schedule async work like syncing breakpoints so they're not immediately done

2 & 3 are now on Firefox Nightly. 1 is a huge win and we're just fixing up a memory leak with it. Could you try Firefox nightly and let us know what you think?

Also, what's your site? We can test it w/ 1 locally :)

And, of course ping you when it lands

**Comment by tbaud0n** [comment]
I've tried using nightly and there is a little improvement (9 sec instead of 12 sec) but the problem is still present as it should take only 3 seconds to load the page.

On discourse.mozilla.org, there's a [discussion](https://discourse.mozilla.org/t/devtools-slow-and-occasionally-unresponsive-on-some-sites/19936/35) about this issue. Julian Descottes helped me to find that the problem happens when the network panel has been opened.

Here is the perf without opening the network panel : https://perfht.ml/2CYFNmU
The perf with the network panel open : https://perfht.ml/2oFPlAh

I don't know how to analyze it so let me know if you there is something I did wrong.

The app that I'm building is not accessible to the public for the moment.

**Comment by jasonLaster** [comment]
Thanks @tbaud0n

**Comment by jasonLaster** [comment]
@ChrisGitter i just saw an issue with `eval-source-map` so i'm not surprised cheap is slow too.

I'll investigate soon

**Comment by jasonLaster** [comment]
#3736 documents webpack's `eval-source-map` mode. We should test both

**Comment by jasonLaster** [comment]
Here's one idea where we use an HoC to throttle the SouceTree. I kinda think this [proposal](https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:speedup-sources?expand=1) will fail because the tree will also re-render when connect is fired.

**Comment by jasonLaster** [comment]
Hey @tbaud0n, @bwhitty I've got a PR that helps quite a lot with webpack eval-source-map and cheap-source-map. I hope to land this on nightly next week after 60 is released.

**Comment by jasonLaster** [comment]
Out of curiosity, do you see the same issues with Firefox Dev Edition?
