### ISSUE TITLE
[DropDown] Hidden tabs dropdown covered by panes

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#4854]
The visibility of the dropdown for hidden tabs depends on the width of the editor window.

In certain situations the dropdown gets covered by the panes which makes it impossible to know which item to select.

ER: Expanded dropdown never gets covered by panes trying to overlap it.

Video:
![dropdown](https://user-images.githubusercontent.com/23530054/33571199-98e1093a-d92f-11e7-873d-b947f1538533.gif)

**Comment by bomsy** [comment]
I think this issue can go together with https://github.com/devtools-html/debugger.html/issues/4855
is they are closely related.
