### ISSUE TITLE
[DropDown] Hidden tabs dropdown renders out of bounds

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#4855]
The visibility of the dropdown for hidden tabs depends on the width of the editor window.

When the editor window gets small enough opening the hidden tabs dropdown causes it to render incorrectly and out of bounds. 

And In certain situations the dropdown gets covered by the panes which makes it impossible to know which item to select.

ER: The dropdown checks how much space there is available and places itself correctly

ER: Expanded dropdown never gets covered by panes trying to overlap it.

Video:
![dropdown](https://user-images.githubusercontent.com/23530054/33571199-98e1093a-d92f-11e7-873d-b947f1538533.gif)

**Comment by bomsy** [comment]
Maybe we should probably have some sort of a minimum width how small that can go

**Comment by lukaszsobek** [comment]
@bomsy That might be one solution. I'm thinking of making sure that even when you are using a 1024x768 resolution the debugger is still usable. That would make it a min-width of about 300px, but what happens if the user needs the expressions pane more and wants to resize that. I guess we could argue that they can close the sources pane then.
