### ISSUE TITLE
[Launchpad] Connection spam via network-request.js

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#4856]
STR:
- open launchpad
- wait

ER: 
- nothing happens

AR:
- console gets spammed with denied connection requests

Video:
![launchpad-spam](https://user-images.githubusercontent.com/23530054/33571924-c43ec728-d931-11e7-85f2-a07802763d02.gif)

**Comment by bomsy** [comment]
This is an issue for devtools core. https://github.com/devtools-html/devtools-core/issues/831
