### ISSUE TITLE
Links from sourcemapped Network Stack Trace don't jump to correct source line

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4857]
STR:
- Open Network on [perf-html](https://perf-html.io/public/bf377b229ec75f94bf3596e45d7bff52a9203f74/calltree/?hiddenThreads=&thread=3&threadOrder=0-2-3-4-5-1&v=2), filtered on XHR
- Click first link in sourcemapped Stack Trace panel 

AR:
- Debugger opens with right file but not correct line

ER:
- Right file and line opens

We should confirm that #4747 fixes this; but I don't know how to test that with launchpad as it is not in Nightly atm.

**Comment by jasonLaster** [comment]
@digitarald can you re-confirm this. it might work now

**Comment by digitarald** [comment]
Trying to reproduce. Seems to work now.

As follow up I see an issue that loading `withSize.js` took more than 30sec. The profiles shows a heavy pattern of worker messages: https://perfht.ml/2p31yM2

**Comment by jasonLaster** [comment]
<img src='https://shipusercontent.com/531d6300563a3311aaed4c01d1e611b6/Screen%20Shot%202018-03-08%20at%206.00.19%20PM.png' title='Screen Shot 2018-03-08 at 6.00.19 PM.png' width=1440>

Thanks @digitarald, I saw this culprit below the worker calls... I saw this yesterday when looking at #4849 with the webpack evals.

This reminds me of the change we made last month where we stopped throttling the source tree.
