### ISSUE TITLE
[CallStack] responsive ui

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4865]
STR:
- Break in a JS file on Github or anything with longer file names (names like hashes)

AR:
- The name can't be fully seen

Filename doesn't use all the space:
<img width="733" alt="image" src="https://user-images.githubusercontent.com/8599/33674866-a8a99468-da65-11e7-8002-cb1c9b5bd966.png">

Filename doesn't shrink and pushes out function name:
<img width="316" alt="image" src="https://user-images.githubusercontent.com/8599/33674875-b050862c-da65-11e7-9629-8176281f7417.png">

Possible fixes:
- [ ] Responsive layout
- [ ] Title attribute on filename and function name

**Comment by CharlesStocky** [comment]
Would showing the filename on mouse-over suffice @digitarald ?

**Comment by jasonLaster** [comment]
@CharlesStocky i think a tooltip would help. Also, is there a way to truncate w/ CSS?

**Comment by lukaszsobek** [comment]
@jasonLaster @CharlesStocky `text-overflow: ellipsis`

**Comment by CharlesStocky** [comment]
Im thinking a utility function that currently exists (/src/utils/utils.js endTruncateStr) isn't needed and may hamper future development. The same functionality can exist with css and it's dynamic.

**Comment by jasonLaster** [comment]
Hey @CharlesStocky how's it going?

**Comment by CharlesStocky** [comment]
@jasonLaster I'm pretty much done with the fix. I completely removed endTruncateStr. Here's what it's looking like: 

<img width="512" alt="image" src="https://user-images.githubusercontent.com/24966772/35421405-a9419ec8-0208-11e8-9dff-4276a60f77a6.png">

Source tabs and the buttons to the right of them no longer overlap on narrowing of the editor pane: 

<img width="512" alt="image" src="https://user-images.githubusercontent.com/24966772/35421455-e8484252-0208-11e8-8927-cc78a7fb986b.png">

Let me know if you'd like to see anything else!

**Comment by jasonLaster** [comment]
looks good!

**Comment by jasonLaster** [comment]
Hey @CharlesStocky @darkwing how's this going?

**Comment by jasonLaster** [comment]
i'm moving this to the icebox. We can re-evaluate at the start of the next release.
