### ISSUE TITLE
"Pause on all exceptions" toggle switch is hard to discover and hard to figure out which state it is

### ISSUE THREAD

**Issue by arai-a** [devtools-html/debugger.html#4872]
Steps to reproduce:
  1. Run Nightly 59.0a1 (2017-12-07) (64-bit) with clean profile on macOS
  2. Open debugger

Actual result:
  1. it's hard to find "Pause on all exceptions" feature for the following reasons:
    a. previously it was provided via menu with text, now it's button without text
    b. I'm not sure if it's common tho, the icon (octagon with 2 lines) doesn't describe the feature well
    c. even once I found the icon, clicking it doesn't change the visual (actually it does, but it's really minor difference in the brightness), and it looked like the button isn't what I was looking for (actually I thought the button is not yet available at that state)
  2. similar to 1.c, it's hard to see which state (Pause on all exceptions/Ignore exceptions/Pause on uncaught exceptions) it is, the difference is only in the brightness (or color?). especially "Ignore exceptions" and "Pause on uncaught exceptions" look almost same for me

Expected result:
  1. the feature is provided with more discoverable way
  2. there's more obvious visual difference for each state

**Comment by jasonLaster** [comment]
Sorry for the slow reply, we're working on moving the pause on exceptions buttons

![Pasted Image 1.tiff](https://shipusercontent.com/672a1709e20b1aa5e67cfa346962dae7/Pasted%20Image%201.tiff)
