### ISSUE TITLE
Update to React 16.2.0

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#4879]
This is needed so the whole devtools toolbox can also switch to React 16 as well.
Here's what we should do: 

- [x] Update React packages to 16.2.0 (use separate packages for proptypes and react-dom-factories). Maybe @MikeRatcliffe could help us here.
- [x] Update all the dependencies that would not work in their current version with React 16 (see also https://github.com/devtools-html/debugger.html/issues/4848)
- [x] Because devtools-reps will be updated, the `<ObjectInspector>`instances should use the new API (pass a `createObjectClient`prop instead of using `loadedProperties` and `loadProperties`). @jasonLaster commited to this
- [ ] Because of the update of devtools-reps, switching from horizontal to vertical layout (or the other way around) will collapse any expanded nodes by the user. To overcome this, we'll switch to a css grid layout and media-queries to switch from one layout to another (See https://github.com/devtools-html/debugger.html/issues/4839). React 16 allow us to return Fragments from components so we can put the main parts as direct children of the `.debugger` node. @codehag commited to this.
- [ ] Because of previous point, we won't be able to use the `<Splitter>` component (which works by wrapping 2 children, which we don't want). A new `<GridAreaResizer>` component will be created to be able to resize a grid track. @nchevobbe commited to this.

**Comment by jasonLaster** [comment]
@nchevobbe surprised me earlier when he informed me of the large `set_operation` performance time. It looks like it's about 200ms:

My take away is that we can probably optimize this quite a bit. We probably should as well as this is likely our perf when opening the debugger for the first time.

<img src='https://shipusercontent.com/ea8d10fcb6bd461bd6cbc9c346bee55f/Screen%20Shot%202017-12-07%20at%204.44.42%20PM.png' title='Screen Shot 2017-12-07 at 4.44.42 PM.png' width=1074>
<img src='https://shipusercontent.com/af959227c1a608a2050839305ef65485/Screen%20Shot%202017-12-07%20at%204.44.31%20PM.png' title='Screen Shot 2017-12-07 at 4.44.31 PM.png' width=887>

---

<img src='https://shipusercontent.com/38cd705a2cb141f1962a5b9a0d73da2a/Screen%20Shot%202017-12-07%20at%204.46.11%20PM.png' title='Screen Shot 2017-12-07 at 4.46.11 PM.png' width=730>
<img src='https://shipusercontent.com/42fa1caf051f5c2ead30f2629b6318bd/Screen%20Shot%202017-12-07%20at%204.46.27%20PM.png' title='Screen Shot 2017-12-07 at 4.46.27 PM.png' width=1225>

**Comment by MikeRatcliffe** [comment]
> Update React packages to 16.2.0 (use separate packages for proptypes and react-dom-factories). Maybe @MikeRatcliffe could help us here.

I have already done all the work we need to do in devtools-core, debugger.html etc. you should be able to just bump to 16.2.0 in package.json.

**Comment by nchevobbe** [comment]
The update is now completed

**Comment by nchevobbe** [comment]
I though I was on devtools-core, sorry about that

**Comment by codehag** [comment]
no problem!
