### ISSUE TITLE
[Perf] Switching callstack entries causes hangs on large minified files

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4897]
STR:
- Pause on uncaught exception on https://alpha.giveth.io/ and hit it
- Switch callstack entries

https://perfht.ml/2iI66VD
- 8s hang
- 3x 900ms forced flexbox reflows, caused by `offsetTop` and `updateHeightsInViewport`: https://perfht.ml/2iH9FeE
- 2.4s in `getCallSites`

**Comment by jasonLaster** [comment]
I'm seeing a pattern here

<img src='https://shipusercontent.com/44969de386304cc22dfd1d26b99db26e/Screen%20Shot%202017-12-09%20at%2012.20.45%20PM.png' title='Screen Shot 2017-12-09 at 12.20.45 PM.png' width=1440>

**Comment by jasonLaster** [comment]
I'd like to see if we're calling `updateHeightsInViewport` because we're updating the line number formatter:

if that's the case, commenting this out will help a lot.

```diff
diff --git a/src/utils/editor/source-documents.js b/src/utils/editor/source-documents.js
index 0e7e53f..1e57428 100644
--- a/src/utils/editor/source-documents.js
+++ b/src/utils/editor/source-documents.js
@@ -32,7 +32,7 @@ function clearDocuments() {
 
 function resetLineNumberFormat(editor: Object) {
   const cm = editor.codeMirror;
-  cm.setOption("lineNumberFormatter", number => number);
+  // cm.setOption("lineNumberFormatter", number => number);
   resizeBreakpointGutter(cm);
   resizeToggleButton(cm);
 }
@@ -41,9 +41,10 @@ function updateLineNumberFormat(editor: Object, sourceId: string) {
   if (!isWasm(sourceId)) {
     return resetLineNumberFormat(editor);
   }
+
   const cm = editor.codeMirror;
-  const lineNumberFormatter = getWasmLineNumberFormatter(sourceId);
-  cm.setOption("lineNumberFormatter", lineNumberFormatter);
+  // const lineNumberFormatter = getWasmLineNumberFormatter(sourceId);
+  // cm.setOption("lineNumberFormatter", lineNumberFormatter);
   resizeBreakpointGutter(cm);
   resizeToggleButton(cm);
 }
```

If the problem is that we're updating the line number formatter too much, then the fix is pretty easy :) It turns out that we only need to set it if we're about to view a wasm source or navigating from a wasm source to a non-wasm source. 

If we do something in Editor.componentDidUpdate to check if we're in that case, and only then call `updateLineNumberFormatter`

**Comment by jasonLaster** [comment]
hmm, so it looks like every time we toggle a document, `updateHeightsInViewport` sets a line from 15px to 13px. This is pretty weird, i wonder what we're doing to keep changing it...

**Comment by jasonLaster** [comment]
@digitarald do you remember how to throw an exception.

**Comment by digitarald** [comment]
Confirmed fixed. Refresh throws an exception for me.

Here a profile, showing short 200ms (aka totally acceptable) for navigating callstack entries: https://perfht.ml/2HgvImu
