### ISSUE TITLE
[PrettyPrint] Indentation Stops Late in File

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4904]
Looking at `underscore.js` in the TodoMVC demo, clicking the pretty print button opens the prettified tab and things look good...until late in the file, the indentation appears to stop working:

<img width="664" alt="indentationproblem" src="https://user-images.githubusercontent.com/46655/33895107-57c6413a-df25-11e7-9572-d52cf5f61ed6.png">

**Comment by mozbugzi2** [comment]
If there is a `switch` statement earlier in the same function, it's probably Bugzilla 1261971 which should be fixed by https://github.com/mozilla/pretty-fast/pull/23

**Comment by jasonLaster** [comment]
Thanks @mozbugzi2

**Comment by jasonLaster** [comment]
lets close this as there's now an issue in pretty-fast :)
