### ISSUE TITLE
[Footer] the right sidebar height is off

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4907]
The right sidebar footer height is one pixel too much :)

<img src='https://shipusercontent.com/ad425b90977faa4d4836171bd7202248/Screen%20Shot%202017-12-13%20at%2011.08.52%20AM.png' title='Screen Shot 2017-12-13 at 11.08.52 AM.png' width=477>

**Comment by lukaszsobek** [comment]
It might actually be 2 pixels we need to shave off a certain flex property in one of the classes that defines the bottom bar.

**Comment by bomsy** [comment]
is this
