### ISSUE TITLE
[Tests] Trying to access .log of console when it is not initiated yet

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#4927]
The console is trying to log an error, but it seems that because console is still being started and an empty object at the time we are trying to access its property we get an error.

![console_log](https://user-images.githubusercontent.com/23530054/34036891-f465e712-e186-11e7-9579-f3ca0e3cafb7.png)

**Comment by bomsy** [comment]
@lukaszsobek @jasonLaster can this be closed or is there more to be done?

**Comment by lukaszsobek** [comment]
I'll close this as it seems to be fixed - rebased a pr that had the error and after the patch it immediately went green.
