### ISSUE TITLE
TypeError: Inspector is undefined

### ISSUE THREAD

**Issue by mattwellss** [devtools-html/debugger.html#4929]
## Version
FirefoxDeveloperEdition v58.0b11
Mac OS 10.12

## Description
When inspecting a website with an unreasonable number of scripts, the debugger will stop on a `debugger;` statement. However, it seems unable to find the code to display it on the "Debugger" tab. Stepping through code _appears_ to work, and closing the inspector with the × in the corner. Once the inspector has been closed in this way, it's impossible to bring back, instead triggering the following error:
```
TypeError: inspector is undefined[Learn More]  devtools.js:628:9
```

clicking on the link shows the following line(s):
```js
  async inspectNode(tab, nodeSelectors, startTime) {
    let target = TargetFactory.forTab(tab);

    let toolbox = await gDevTools.showToolbox(target, "inspector", null, null, startTime);
    let inspector = toolbox.getCurrentPanel();

    // new-node-front tells us when the node has been selected, whether the
    // browser is remote or not.
    let onNewNode = inspector.selection.once("new-node-front");
```

I've tried to find the offending line of code in this repository, but my searches failed and now I'm concerned this is the wrong repo 😨. Many apologies if so!

Thanks so much for this tool. It's general greatness and continuing incremental improvement are an inspiration to me for my own work.

**Comment by lukaszsobek** [comment]
@mattwellss - Do you happen to have a link to the website you were debugging? It would greatly help in reproducing what happened.

**Comment by mattwellss** [comment]
@lukaszsobek It was a local site. Any publicly accessible versions wouldn't have debugger statements.

What I provided in terms of how to produce this is not sufficient and I'm sorry I even bothered creating an issue before I had those steps.
I'll work on generating a more worthwhile "steps to reproduce" guide in the coming days.

**Comment by jasonLaster** [comment]
Hi @mattwellss can you please refile in http://bugzilla.mozilla.org/
