### ISSUE TITLE
is there a documentation covers  types and params for actors in websocket protocol

### ISSUE THREAD

**Issue by developernew123** [devtools-html/debugger.html#4976]
I want a documentation that covers types and params for actors in debugging protocol when using websocket connection , I want to be able to navigate to pages , set http headers , use cookies and execute javascript remotely.
the only good documentation I fount is here : 
[https://developer.mozilla.org/en-US/docs/Tools/Web_Console/remoting](url)
but it only covered WebConsoleActor

**Comment by jasonLaster** [comment]
this might help: https://github.com/devtools-html/debugger.html/tree/master/src/client

**Comment by developernew123** [comment]
this didn't help , there is no any thing there about firefox debugging protocol

**Comment by jasonLaster** [comment]
Here are the docs that we have in the debugger client

https://github.com/devtools-html/debugger.html/blob/master/docs/client.md#L32

happy to add to it if you have questions
