### ISSUE TITLE
[ContextMenu] Renders out of bounds if opened too close to window edge

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#4977]
STR:
- open source in debugger
- right-click on a code line near the bottom edge

ER: Context menu fully renders inside debugger window

AR: Part of context menu renders out of bounds (concerns bottom and right edge)

Vid:
![context-menu-disappears](https://user-images.githubusercontent.com/23530054/34322686-c67cc92a-e82e-11e7-8d66-161e7930a309.gif)

**Comment by jasonLaster** [comment]
this is only true in the launchpad
