### ISSUE TITLE
Add Google Canary to Launchpad

### ISSUE THREAD

**Issue by joshunger** [devtools-html/debugger.html#4995]
Would it be possible to add Google Canary to Launchpad?  Taking a guess but I think most developers would expect this.
![image](https://user-images.githubusercontent.com/2301847/34436319-eb6e551a-ec51-11e7-8f08-14d50cb37404.png)

**Comment by joshunger** [comment]
The problem is I get used to Canary features 😢

**Comment by jasonLaster** [comment]
We can first look for canary, but i guess in this case its about debugging canary, which is not really a priority because it's likely the same debug protocol
