### ISSUE TITLE
[Perf] Command + o feels much slower compared to Google Chrome

### ISSUE THREAD

**Issue by joshunger** [devtools-html/debugger.html#4996]
Command + o feels much slower compared to Google Chrome.  What is the best performance tool to provide the difference?  I thought there was a performance tool that took screen captures and detected differences in the UI but I can't find it in a Google search.

**Comment by jasonLaster** [comment]
you can use chrome's performance tool and get screenshots from there.

Thanks, would always love to speed up these modals.

**Comment by jasonLaster** [comment]
We fixed this today.

**Comment by joshunger** [comment]
Thank you 🎉
