### ISSUE TITLE
Shortcut to set conditional breakpoint also open Bookmarks Manager/Library

### ISSUE THREAD

**Issue by Archaeopteryx** [devtools-html/debugger.html#5005]
Reproduce with latest Nightly and Beta on Windows 8.1

Pressing the shortcut to create a conditional breakpoint:
>toggleCondPanel.key=CmdOrCtrl+Shift+B
creates the prompt for the condition and open the bookmarks manager because that uses the same shortcut.

**Comment by jasonLaster** [comment]
fixed!
