### ISSUE TITLE
Accesskey for 'Add Conditional Breakpoint' also used for 'Edit Breakpoint'

### ISSUE THREAD

**Issue by Archaeopteryx** [devtools-html/debugger.html#5006]
Reproduce in latest Firefox Beta and Nightly

"Add conditional breakpoint" has the accesskey "c". After one used that command, "Edit breakpoint" will be shown with a "(C)" at the end because the accesskey has neither been updated nor removed nor is it part of the new string.

**Comment by jasonLaster** [comment]
I think this is okay because the two should be mutually exclusive

1. first you add a condition
2. then you edit it
