### ISSUE TITLE
gotoline shortcut CmdOrCtrl+Shift+; not supported by some keyboards/languages

### ISSUE THREAD

**Issue by Archaeopteryx** [devtools-html/debugger.html#5007]
The shortcut CmdOrCtrl+Shift+; for the gotoline feature can't be triggered for some non-English keyboards (e.g. German) because those generate the ; with Shift + key (e.g. German Shift + . = ;)

**Comment by jasonLaster** [comment]
this should be fixed. Let me know if it's not.
