### ISSUE TITLE
(discussion) Action logs

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#501]
(discussion) We currently have the ability to console.log actions. It would also be nice to be able save the actions to a file during CI.

There are two options that I see:
+ add the actions to a global registry `window.actionLog` and export it during the `saveFixture` command
+ post the actions to a dev-server endpoint as that writes them to a log file

This came up yesterday when I was digging into our tests' intermittents. When I added the logs, it became easier to understand what happened on each test.

**Comment by jlongster** [comment]
In my opinion the CI should allow this. It's not uncommon to use this workflow on try: enable more verbose logging and download the log file and see what's going on. Why not just download the log file from CI?

**Comment by jasonLaster** [comment]
At the moment, we're not saving console logs to a log file, you're right that we should probably just generalize it to that.

**Comment by jlongster** [comment]
Cool, then we don't have to write code! :) We could still drive logging from prefs if you wanted, and in fact that's related to your client logging PR. I'd be fine with a pref, but I'd prefer that pref to just flip the Firefox pref to log protocol data. With these prefs we could control the amount of logging when pushing to CI.

**Comment by jasonLaster** [comment]
Finished in #530
