### ISSUE TITLE
[Tabs] Improve truncation of long filenames, smaller max tab size 

### ISSUE THREAD

**Issue by violasong** [devtools-html/debugger.html#5019]
STR: 
- Open Debugger when viewing a github issues page like this one 
- Navigate to `assets-cdn.github.com > assets > frameworks-alsxsljd...`
- The tab is too wide and the info in it is hashy gibberish
- Bonus problem: click Pretty Print
The source map message mentions the filename with the same poor truncation rules, and when the Debugger is narrow it breaks in this odd way:
<img width="462" alt="image" src="https://user-images.githubusercontent.com/55994/34536772-16a511ba-f07b-11e7-9d16-3508b0d54610.png">

Suggestions:
- Max truncation level should be at most half what it is now, perhaps 20 chars or so. This will keep the max tab size smaller, even when there's only one tab.
- Do the truncation at the end instead of beginning. So with this file it would end up looking like `frameworks-fbf9e3a...`
- When the window is very narrow, more truncation would happen so that you can always see the full tab UI. (The tab would look like `[ framew...  x ]` - I think we could do this with text-overflow: ellipsis;
- Hm, for the "source mapped from" message, would it make sense to remove that message, and instead keep the pretty print icon to the left but in a highlighted state?
- Hovering over anything truncated should show a tooltip with full text

(Sprouted from discussions in #4928)

**Comment by CharlesStocky** [comment]
This is about to be PR'ed (https://github.com/devtools-html/debugger.html/pull/5415)
