### ISSUE TITLE
reset connection when the debugger refreshes

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#502]
I believe one of the reasons we were seeing intermittents with chrome this week was that the test would reload the debugger and not properly reset the connection. 

The situation I would see was:
- reload debugger
- select a source
- add a breakpoint
- do an action in the debuggee to trigger a pause
- debugger wouldn't pause

The problem was fixed by not reloading the debugger: https://github.com/devtools-html/debugger.html/commit/b3ce17ca6cc928a79c0ec6bb9bbb860fd70141c1, but the more long term solution is to probably do what we're doing in firefox and drop the connection before the debugger reloads:

``` js
window.addEventListener("beforeunload", () => {
    getTabTarget() && getTabTarget().destroy();
});
```

**Comment by clarkbw** [comment]
I keep wondering if this is going to be as simple as something like this:

```diff
diff --git a/packages/devtools-local-toolbox/src/clients/chrome.js b/packages/devtools-local-toolbox/src/clients/chrome.js
index a58b424..dc4b022 100644
--- a/packages/devtools-local-toolbox/src/clients/chrome.js
+++ b/packages/devtools-local-toolbox/src/clients/chrome.js
@@ -53,6 +53,10 @@ function connectClient() {
 function connectTab(tab) {
   return connect(tab.webSocketDebuggerUrl).then(conn => {
     connection = conn;
+    window.addEventListener("beforeunload", () => {
+      conn.onclose = function disable() {};
+      conn.close();
+    });
   });
 }
```

**Comment by jasonLaster** [comment]
@clarkbw yeah! that looks like it... if there's a close function. or likely conn.Runtime.close()

So many of these issues are quick once you get in there!

**Comment by jasonLaster** [comment]
@clarkbw it's neat that merging https://github.com/devtools-html/devtools-core/pull/54 closed this issue. Github's NLP has gotten good!
