### ISSUE TITLE
[Editor] Scrollbars corner overlap after switch Toolbox tab

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#5022]
**Steps to reproduce:**
1. Launch Nightly
2. Go to about:home
3. Open Debugger
4. Select any sources (e.g. about:home or contentSearchUI.js)
5. Scroll vertical scrollbar (It's no problem)
6. Switch to other toolbox tab and switch back
7. Scroll vertical scrollbar again

![steps-to-reproduce_20180104_153601](https://user-images.githubusercontent.com/13914314/34552796-0d830f0a-f167-11e7-8b2f-38de7ef541ad.gif)

**Actual results:**
In step 7, scrollbars corner will be overlapped.

**Expected results:**
No overlap.

**Comment by AlexWang-16** [comment]
Hi @magicp-github  , I'm interested in tackling this issue, but I was not able to replicate this on the Mac. I've used Nightly v61.0a1. Is there another way that I can perhaps replicate this issue?

![issue](https://user-images.githubusercontent.com/13398997/37504288-bd232872-28b3-11e8-9a5a-10b8c0cdb118.gif)

**Comment by jasonLaster** [comment]
@AlexWang-16 this might be windows only

**Comment by darkwing** [comment]
Could not reproduce this on Windows.
