### ISSUE TITLE
[CallStack] Broken Stacktrace is back

### ISSUE THREAD

**Issue by TitanNano** [devtools-html/debugger.html#5023]
![screen shot 2018-01-04 at 09 52 27](https://user-images.githubusercontent.com/4500858/34556375-4f574396-f136-11e7-941e-0446a95d88a5.png)
This happened after I stepped into an Angular internal method. 
```
TypeError: Argument 1 of Node.removeChild is not an object.[Weitere Informationen] react-dom.js:1379:3
```

**Comment by TitanNano** [comment]
```
Unknown SVG: rxjs  debugger.js:33573:5
Error: Minified React error #105; 
visit http://facebook.github.io/react/docs/error-decoder.html?invariant=105&args[]=Svg 
for the full message or use the non-minified dev environment for full errors and additional helpful warnings.  react-dom.js:16637:15
```

This seems to be one of the causes for this issue.

**Comment by TitanNano** [comment]
Steps to Reproduce:
1. go to https://jovandemo.modulentwicklung.de:8001/admin
2. login with User: anyone@mozilla.org PW: 123456789
3. go to Orders > Orders
4. Open Debugger and search for file: Shared/Directives/DataTable/DataTableController.ts
5. Set a breakpoint in line 197
6. Move cursor in side the view-port to trigger angular

Result: No call stack is shown, no scopes are shown either.

Additional:

1. Right click and select jump to generated source

Result: a new tab appears with the generated source, on the left the broken call stack appears too.

**Comment by bomsy** [comment]
Thanks @TitanNano !  will look into this!
