### ISSUE TITLE
[SourceMaps]  "TypeError: sourceMaps is null" in browser console

### ISSUE THREAD

**Issue by fitzgen** [devtools-html/debugger.html#5028]
Haven't been able to make a reduced test case or STR, and when I switch profiles the issue goes away.

But here's a backtrace:

```
TypeError: sourceMaps is null
Stack trace:
loadSourceMap/<@resource://devtools/shared/base-loader.js -> resource://devtools/client/debugger/new/debugger.js:19026:11
async*thunk/</</<@resource://devtools/shared/base-loader.js -> resource://devtools/client/debugger/new/debugger.js:45455:45
dispatch@resource://devtools/shared/base-loader.js -> resource://devtools/client/debugger/new/debugger.js:9787:18
newSources/</<@resource://devtools/shared/base-loader.js -> resource://devtools/client/debugger/new/debugger.js:19005:54
newSources/<@resource://devtools/shared/base-loader.js -> resource://devtools/client/debugger/new/debugger.js:19005:24
async*thunk/</</<@resource://devtools/shared/base-loader.js -> resource://devtools/client/debugger/new/debugger.js:45455:45
bindActionCreator/<@resource://devtools/shared/base-loader.js -> resource://devtools/client/debugger/new/debugger.js:9700:12
onConnect@resource://devtools/shared/base-loader.js -> resource://devtools/client/debugger/new/debugger.js:30185:9
async*onConnect@resource://devtools/shared/base-loader.js -> resource://devtools/client/debugger/new/debugger.js:30086:31
async*bootstrap@resource://devtools/shared/base-loader.js -> resource://devtools/client/debugger/new/debugger.js:27049:15
open@resource://devtools/shared/base-loader.js -> resource://devtools/client/debugger/new/panel.js:29:15
async*onLoad@resource://devtools/shared/base-loader.js -> resource://devtools/client/framework/toolbox.js:1675:19
  Promise-backend.js:925
TypeError: sourceMaps is null[Learn More]  debugger.js:19026:11
```

**Comment by jasonLaster** [comment]
another user reported this as well today...

**Comment by tromey** [comment]
> Haven't been able to make a reduced test case or STR

See https://bugzilla.mozilla.org/show_bug.cgi?id=1410590

**Comment by jasonLaster** [comment]
CC https://bugzilla.mozilla.org/show_bug.cgi?id=1410590

---

I don't see the "sourceMaps is null" in the editor, but I do see it in the browser console.
For me the editor just says "Loading..." and never changes.

The browser console says:

TypeError: sourceMaps is null[Learn More]  debugger.js:25005:1

I actually see several reports with different line numbers.


These STR worked for me:
* Turn the source map pref off
* Open https://tromey.github.io/source-map-examples/simple/index.html
* Open devtools
* Switch to debugger

**Comment by jasonLaster** [comment]
I'm closing this here because this is a toolbox issue and not a debugger UI issue. We should prioritize [1410590](https://bugzilla.mozilla.org/show_bug.cgi?id=1410590)

**Comment by jasonLaster** [comment]
Actually, never mind this looks like it is a debugger issue because we fail when the pref is off
