### ISSUE TITLE
[SourceTree] A file is missing from the tree

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5029]
It looks like the file `increment.js` is missing from the tree:

STR:
1. go to [inc](http://firefox-dev.tools/debugger-examples/examples/increment/)
2. view the source tree :)

I think the problem is that increment.js is an original file, but i'm not sure why that should matter...

<img src='https://shipusercontent.com/f870b3a65a70a5afeaf64ab3b427f158/Screen%20Shot%202018-01-04%20at%206.14.45%20PM.png' title='Screen Shot 2018-01-04 at 6.14.45 PM.png' width=654>

**Comment by lukaszsobek** [comment]
Found it :)
![increment](https://user-images.githubusercontent.com/23530054/34659961-cca7b3de-f43e-11e7-8067-b825e75344ce.png)

**Comment by jasonLaster** [comment]
hmm, yeah.. I'm seeing this in other cases too. It looks like we sometimes miss a file :/

**Comment by wldcordeiro** [comment]
Yep I see it happen with todomvc as well where the root `app.js` will not be present.

**Comment by lukaszsobek** [comment]
Is there a consistent str?

**Comment by codehag** [comment]
I've been trying to reproduce this but no luck -- any suggestions on how to get this to happen @jasonLaster @wldcordeiro

**Comment by codehag** [comment]
I've traced the issue to the server.

here is an str with running this as a panel:

1. have a different test page open (google, or something, doesnt matter. cleaning your browser content toolbox helps)
2. navigate to http://firefox-dev.tools/debugger-examples/examples/todomvc/

Expected Results: "app.js should be visible under the /js folder"
Actual results: it is not visible

Further investigation:
- app.js is not added as a source actor on this initial load, it is added on reload

I added a console log into SourceActor -> initialize on line 157. Here are the logs for the initial load from the source actor:
```
console.log: source
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/jquery/jquery.js
console.log: source
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/underscore/underscore.js
console.log: source
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/backbone/backbone.js
console.log: source
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/backbone.localStorage/backbone.localStorage.js
console.log: source
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/underscore/underscore.js line 1261 > Function
console.log: source
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/views/app-view.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/underscore/underscore.js line 1261 > Function
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/routers/router.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/models/todo.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/collections/todos.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/views/todo-view.js
```

here is the log for the reload:

```
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/todomvc-common/base.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/todomvc-common/base.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/jquery/jquery.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/jquery/jquery.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/underscore/underscore.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/underscore/underscore.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/backbone/backbone.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/backbone/backbone.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/backbone.localStorage/backbone.localStorage.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/backbone.localStorage/backbone.localStorage.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/models/todo.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/models/todo.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/collections/todos.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/collections/todos.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/views/todo-view.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/views/todo-view.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/underscore/underscore.js line 1261 > Function
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/underscore/underscore.js line 1261 > Function
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/views/app-view.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/views/app-view.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/underscore/underscore.js line 1261 > Function
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/bower_components/underscore/underscore.js line 1261 > Function
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/routers/router.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/routers/router.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/app.js
console.log: source added
console.log: #### http://firefox-dev.tools/debugger-examples/examples/todomvc/js/app.js
```

On reload we seem to be adding each file twice. we also have all of the files this time. Any ideas? @jimblandy maybe you have some insight?

**Comment by codehag** [comment]
Some more information as I dig into this, just took a look at script.js --

* having two events on reload is due to the "reusableActor" for the sourcesStore in script.js 
  i am guessing this is intended, so not worried about that!

* we are not firing newSource events for all of the expected sources

second point is worriesome. I'm not sure how we discover files, I will keep looking into this for another hour and then I will wait for input

**Comment by jasonLaster** [comment]
Just confirmed the other test case that i saw this w/ [`increment`](http://firefox-dev.tools/debugger-examples/examples/increment/)

STR:
1. load [`increment`](http://firefox-dev.tools/debugger-examples/examples/increment/)
2. select `increment.js` 
3. refresh debugger

ER: you see incremenet.js in the tree
AR: you don't

### Nothing selected
<img src='https://shipusercontent.com/bd544105c0c8e9c9e5f2f97f2b01921a/Screen%20Shot%202018-01-11%20at%204.47.59%20PM.png' title='Screen Shot 2018-01-11 at 4.47.59 PM.png' width=555>

### increment.js
<img src='https://shipusercontent.com/7460eee2fc2d62f510eeb9254428a629/Screen%20Shot%202018-01-11%20at%204.47.50%20PM.png' title='Screen Shot 2018-01-11 at 4.47.50 PM.png' width=674>

### func.js
<img src='https://shipusercontent.com/211aad9c92d224ef764d6e86cd1858a3/Screen%20Shot%202018-01-11%20at%204.47.42%20PM.png' title='Screen Shot 2018-01-11 at 4.47.42 PM.png' width=634>

### increment.js
<img src='https://shipusercontent.com/8e9ba96c8bcc7ad216d84dc5d6c4c498/Screen%20Shot%202018-01-11%20at%204.47.12%20PM.png' title='Screen Shot 2018-01-11 at 4.47.12 PM.png' width=762>

**Comment by jasonLaster** [comment]
It looks like there were 2 issues: 

1. sources were GCd (when i added window.dontKillMe = () => {}) to app.js it stuck around)
2. sources that were loading were not added. 

Closing as 2 was fixed and 1 is a server issue...
