### ISSUE TITLE
Depenency CI is red

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5030]
Dependency CI is currently failing, which is a big deal because we need to make sure we're not pulling in packages that are not licensed.

https://dependencyci.com/github/devtools-html/debugger.html

<img src='https://shipusercontent.com/bc1faf7b58ce10d8a2c6237340ca294f/Screen%20Shot%202018-01-04%20at%2012.23.52%20PM.png' title='Screen Shot 2018-01-04 at 12.23.52 PM.png' width=778>

**Comment by wldcordeiro** [comment]
Looks like this should be fixed? But the last run still is looking for the deprecated/etc.

**Comment by jasonLaster** [comment]
Hmm, i'll continue hacking on this tomorrow

**Comment by lukaszsobek** [comment]
Is dependency-ci gone for good and replaced with deploy/netlify, or just temporarily disabled?
