### ISSUE TITLE
[QuickOpen] focused search result and hovered item looked the same

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#5034]
Here's a screenshot I got when doing a search with Cmd + P 

![screen shot 2018-01-05 at 14 39 25](https://user-images.githubusercontent.com/578107/34611758-0afa63d0-f227-11e7-9a46-f633bdf78aa8.png)

The first result is the "active" one.
The second is in hover state because of the placement of my mouse.

It confused me for a second, making me wonder what was going to happen if I pressed Enter.
I think it would be nice to have different styles for those cases

For the record, here's what vscode do: 

<img width="616" alt="screen shot 2018-01-05 at 14 43 53" src="https://user-images.githubusercontent.com/578107/34611759-0c4c6ae4-f227-11e7-9839-b29cc29b38a5.png">

**Comment by ppatel221** [comment]
Hey im a student in an open source development class. I am looking to contribute to an open source project. Is it okay if i take over?

**Comment by nyrosmith** [comment]
@ppatel221 of course!
Also visit our slack. We are much more responsive there and always happy to answer all your questions!

**Comment by violasong** [comment]
I think it would be great to follow the Inspector pattern of blue background/white text for active row, and pale blue background for hovered row. However, that may look too intense for these big row areas with subtle borders. I wonder if it would make sense to move the path to the same line as the filename to condense the rows. Some truncation would be needed, similar to #5019.

**Comment by jasonLaster** [comment]
@ppatel221 how's it going?

**Comment by jasonLaster** [comment]
Here's another good example

<img src='https://shipusercontent.com/ddd2065be616809a0f3f7b61f2cae25a/36224948-b3206830-118e-11e8-8dfc-42bd3bd3a2a6.png' title='36224948-b3206830-118e-11e8-8dfc-42bd3bd3a2a6.png' width=1438>

**Comment by jasonLaster** [comment]
ping @ppatel221 do you think you have time to work on this?

**Comment by nihal31** [comment]
Hey I see that this is not in progress. If @ppatel221 is not working on this anymore, can I claim this? It would be first contribution!

**Comment by nchevobbe** [comment]
@nihal31 It's been 3 weeks @ppatel221 was pinged, let's assume they're not working on it anymore.
So yeah, claim it :) (and I really want this to happen, I am confused every time I use the QuickModal :D)

**Comment by nihal31** [comment]
Keeping the color scheme similar to what we get when we do a function search, the result looks something like this
![screenshot from 2018-03-08 00-54-14](https://user-images.githubusercontent.com/4532171/37113454-6d7a4fe2-226b-11e8-9929-c9023a6a6274.png)
@jasonLaster @nchevobbe What do you think of @violasong 's comment above?

**Comment by jasonLaster** [comment]
looks great!

**Comment by jasonLaster** [comment]
Thanks @nihal31. 

I'm happy moving forward with what you have and addressing the QuickOpen item height in a separate issue.

One easy step would be to use CSS to keep the path to one line, which would help quite a bit. I'm hesitant to have the path on the same line as that could become pretty tight.

**Comment by jasonLaster** [comment]
Just created #5630

**Comment by nchevobbe** [comment]
@nihal31 awesome

**Comment by nihal31** [comment]
This work is open in PR #5654 and ready for some comments :)
