### ISSUE TITLE
[SourcesSearch] Give me a way to manually add a sourcemap for a file

### ISSUE THREAD

**Issue by ajvincent** [devtools-html/debugger.html#5040]
From the debugger channel in DevTools Slack:
> so I'm deep in debugging a bit of jQuery minimized code, and the website that loaded it loaded a version without a sourceMappingURL comment.  Fortunately, the doc'n for this version of jQuery specifies where the source mapping is.  Is there any way I can tell the debugger "use this source map"?

System Details:  Fedora 27 Linux, Firefox 57.0.1

**Comment by jasonLaster** [comment]
```diff
diff --git a/src/actions/sources/newSources.js b/src/actions/sources/newSources.js
index f39d0a7..c84e015 100644
--- a/src/actions/sources/newSources.js
+++ b/src/actions/sources/newSources.js
@@ -41,12 +41,24 @@ function createOriginalSource(
   };
 }
 
+const sourceMapWhiteList = {
+  "https://code.jquery.com/jquery-3.2.1.min.js":
+    "https://code.jquery.com/jquery-3.2.1.min.map"
+};
+
 /**
  * @memberof actions/sources
  * @static
  */
 function loadSourceMap(generatedSource) {
   return async function({ dispatch, getState, sourceMaps }: ThunkArgs) {
+    if (
+      !generatedSource.sourceMapURL &&
+      sourceMapWhiteList[generatedSource.url]
+    ) {
+      generatedSource.sourceMapURL = sourceMapWhiteList[generatedSource.url];
+    }
+
     const urls = await sourceMaps.getOriginalURLs(generatedSource);
 
     if (!urls) {
```

**Comment by ajvincent** [comment]
When I tried using this at work, the result was such a performance hit as to make the devtools virtually unusable.  We ended up using a "channel redirector" inside the target app to force it to load the unminified code.  The result was a night & day difference:  with the redirector, the debugger responded very quickly.

**Comment by jasonLaster** [comment]
good to know. what version of firefox were you using? Nightly has gotten much faster

**Comment by ajvincent** [comment]
FF57.  I don't know what minor version.

**Comment by jasonLaster** [comment]
@ajvincent sorry. 57 was really slow for sourcemaps. we've gone from 15 seconds in many cases to <2 seconds in 59...
