### ISSUE TITLE
[CodeHealth] Refactor redux selectors exports

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5042]
It would be cool if we could simplify the selectors & redux exports.

Here is a [branch](https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:export-selectors?expand=1) where I started. It should be pretty close, but it requires a very good knowledge of es6's module system :)

**Comment by lukaszsobek** [comment]
The features seem to be all moved and the changes merged. Is there something more to do here?

**Comment by jasonLaster** [comment]
nope it's done!
