### ISSUE TITLE
[Docs] Switch from Jekyll to Gatsby

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5047]
Our [landing page][lpage] & [docs] are currently built with jekyll and hosted with github pages. It would be nice to switch to [Gatsby] and Netlify.

Features of the current setup:

+ configs are in debugger.html
+ deploys happen when a PR is merged
+ everything is markdown

Advantages of the new setup:

+ Layouts and themes are easier (landing page, docs)
+ Docs are searchable
+ Netlify offers analytics (how often are blog posts read, how often are docs read, how much traffic do we get from sources)

Here is a [tutorial](https://www.gatsbyjs.org/blog/2017-12-06-gatsby-plus-contentful-plus-netlify/) on how one project got setup w/ gatsby + netify + contentful and algolia. I dont think we need contentful yet but it's cool :)

NOTE: this is a big project, but would be a lot of fun. I'd be happy to mentor if you're interested and i think we can land the new gatsby site incrementally. So it doesn't all have to be done by one person and in one chunk. Also, just getting started and sharing what you learn is helpful too!

Also, one other route is to use [Docusaurus](https://github.com/facebook/Docusaurus) which might be more out of the box. Or one of the gatsby starter projects like [gatsby-starter-docs](https://github.com/ericwindmill/gatsby-starter-docs).

Lastly this issue #1921 shows some mockups i did of what a debugger.html landing page and docs page could look like :) disregard the ugly blue, just wanted to start the conversation!

[lpage]:http://firefox-dev.tools/debugger.html/
[docs]:http://firefox-dev.tools/debugger.html/docs/
[Gatsby]:https://www.gatsbyjs.org/

**Comment by jasonLaster** [comment]
@nyrosmith i'm taking your head off it as it's been 2 months. feel free to re-claim it

**Comment by jasonLaster** [comment]
how's it going @zeoneo?

**Comment by zeoneo** [comment]
I understood earlier Jekyll set up and Gatsby js. I will start actual work now and post updates on my progress here.

**Comment by s-pace** [comment]
:wave:
@jasonLaster @zeoneo 
Do you need any help? Super quick to reach something working: http://debugger-docsearch.surge.sh/

Happy to help. I can PR the integration of the search bar. Just point me out on which repo/branch to do so.

Have a nice week

**Comment by jasonLaster** [comment]
@s-pace please do

**Comment by s-pace** [comment]
@jasonLaster Where is the source rendering : http://firefox-dev.tools/debugger.html/ ?

**Comment by jasonLaster** [comment]
it's coming from the github pages template which builds docs/readme

**Comment by jasonLaster** [comment]
I'm hacking on a better homepage, which will replace http://firefox-dev.tools/debugger.html/ . For now i think the docs are fine

**Comment by s-pace** [comment]
👋 @jasonLaster 

I can recommend you to use [vuepress](https://vuepress.vuejs.org/) or [docusaurus](https://docusaurus.io/). It does the job.

You can also fill the form from [our home page](https://community.algolia.com/docsearch/) if you want me to grant you access to the full algolia analytics we do provide.

Cheers
