### ISSUE TITLE
[Labels] Changes `available` to `help wanted` and `difficulty: easy` to `good first bug`

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#5053]
As discussed in issue #4353 and debugger.html slack we want to make it easier for new contributors to find issues they want to work on.  One of the ways to do that is to use the `good first bug` and `help wanted` labels, which are promoted by github.

Since we already have a similar structure with the `available` and `difficulty: easy` labels it seems that one of the easiest ways to align the two realities is to rename our `available` label to `help wanted`, and `difficulty: easy` to `good first bug`.

Since `good first bug` and `help wanted` are officially promoted by github the rewording of labels will expose our issues to a wider audience and allow them to be found by people who are specifically looking to start contributing to open source. On top of that there are also several github issue search engines for beginners that specifically list issues with the mentioned above labels.

I relabeled the issues for now, so we can see how it looks and feels like.

**Comment by bomsy** [comment]
I think this is a good idea , especially for the exposure to wider audience ...

**Comment by codehag** [comment]
I think this is an excellent idea

**Comment by jasonLaster** [comment]
Thanks @lukaszsobek!

"Good first issue" makes sense given it's what github looks for :_
