### ISSUE TITLE
[SourceTree] Fix sources-panel styling for RTL locales

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#5059]
Steps to reproduce:
1. Launch Nightly in RTL locales
2. Open Debugger

Actual results:
- Tab border position is wrong
- Twisty direction is wrong
![debugger-in-rtl](https://user-images.githubusercontent.com/13914314/34704851-6de68ce2-f53f-11e7-8b01-016b2c3e986a.png)

Expected results:
Set correct direction for RTL locales

**Comment by lukaszsobek** [comment]
Merged. Closing.
