### ISSUE TITLE
[Scopes] Consolidate function scopes

### ISSUE THREAD

**Issue by yurydelendik** [devtools-html/debugger.html#5061]
STR:
1. Navigate to  [es6](https://yurydelendik.github.io/old-man-sandbox/sorted-es6/test.es6.html) example
2. Set breakpoint at line 94 of bundle.js
3. Inspect environments/scopes

```js
function comparer(a, b) {
  const ma = /.(\d+)\W*$/.exec(a);
  const mb = /.(\d+)\W*$/.exec(b);
  if (ma == null || mb == null || ma[1] == mb[1]) {
  	return a < b ? -1 : a > b ? 1 : 0;
  } else {
    const na = +ma[1], nb = +mb[1];
    return na < nb ? -1 : na > nb ? 1 : 0; // set breakpoint here
  }
}
```

The function at the specified location contains 3 environments: 

1. function
2. function body
3. if-else.

<img width="983" alt="screen shot 2018-01-08 at 7 16 11 pm" src="https://user-images.githubusercontent.com/1523410/34700489-0b22cbca-f4a9-11e7-9bac-7940f7e5aaba.png">

Chrome has only 2 environments: function, if-else.

<img width="1002" alt="screen shot 2018-01-08 at 7 15 50 pm" src="https://user-images.githubusercontent.com/1523410/34724749-a661664e-f514-11e7-97b2-5ae5ec9301fe.png">

Does it make sense to consolidate the function & function body scopes into a single scope? 

Scope content will change during stepping through since new environments may appear/disappear. In other words, it's expected to see scopes less granular on the debugger side, and grouped within function boundary.

/cc @jimblandy

**Comment by jimblandy** [comment]
I don't think the way we call out each distinct scope today is especially helpful, so I think a less noisy display would be great.

But we'll need to display things clearly when bindings in inner scopes shadow bindings for variables of the same name in outer scopes. In the current UI, the separated scopes give the developer a hint, at least.

**Comment by jasonLaster** [comment]
Here is another example that shows the difference between default assignments params and params...

https://es6-default-assignments.glitch.me/

### without default params

<img src='https://shipusercontent.com/4b67f6b6742456afc8b0dfd57fc4dc5e/Screen%20Shot%202018-01-16%20at%204.10.11%20PM.png' title='Screen Shot 2018-01-16 at 4.10.11 PM.png' width=737>

### with default params

<img src='https://shipusercontent.com/2935dda415a8b55fda78149305afa024/Screen%20Shot%202018-01-15%20at%205.51.19%20PM.png' title='Screen Shot 2018-01-15 at 5.51.19 PM.png' width=575>

**Comment by yurydelendik** [comment]
Patch for "ma, mb" issue at https://bugzilla.mozilla.org/show_bug.cgi?id=1431461

**Comment by jasonLaster** [comment]
@yurydelendik I think there are 2 cases listed above:

1. const/let
2. default params

are there other cases where we have too many block scopes?

**Comment by yurydelendik** [comment]
* (`for` might have `let`)
* `catch` creates a scopes
* all breaks with `with()`

**Comment by jasonLaster** [comment]
I'm moving this issue to bugzilla so we can track it closer to spidermonkey - https://bugzilla.mozilla.org/show_bug.cgi?id=1448166
