### ISSUE TITLE
[SourceTree]  up-arrow or down-arrow is off by a bit

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5064]
STR:
1. navigate to [todomvc](http://devtools-html.github.io/debugger-examples/examples/todomvc/)
2. select a source
3. press up-arrow or down-arrow

!! Make sure there are more sources than fit on the screen, so the list can scroll.

ER: The highlighted result remains visible when the list scrolls.
AR: The highlighted result disappears and the list does not scroll correctly.

![](http://g.recordit.co/bS2lZsPP9z.gif)

**Comment by lukaszsobek** [comment]
It's a bit hard to see with low frame-rate gifs, so I'll ask to be sure: ER is each line being highlighted in sequence and AR is lines being skipped?

**Comment by jasonLaster** [comment]
not skipped, it currently goes off screen. It's easier if you see it :)

**Comment by lukaszsobek** [comment]
@jasonLaster added ER and AR.

**Comment by mmcote** [comment]
Larger issue was documented under devtools-core, at [https://github.com/devtools-html/devtools-core/issues/908]().

**Comment by lukaszsobek** [comment]
Fixed. Closing.
