### ISSUE TITLE
[QuickOpen] All the results are shown

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5085]
I believe we're showing all of the functions when the modal opens. For sources with thousands of functions that can be slow.

**Comment by bomsy** [comment]
Should we show top x results?

**Comment by jasonLaster** [comment]
yeah - i think so... or see what fuzz aldrin can do w/ buffering

or use react virtualized...

**Comment by jasonLaster** [comment]
this will be fixed soon :)
