### ISSUE TITLE
[QuickOpen] go to line shows matching files

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5086]
It looks like queries that begin with `:` will show files that match the remaining query.

<img src='https://shipusercontent.com/ab6a0630252ae38db3f1b0c21357a668/Screen%20Shot%202018-01-11%20at%2011.29.45%20AM.png' title='Screen Shot 2018-01-11 at 11.29.45 AM.png' width=640>

**Comment by wldcordeiro** [comment]
So if we have the goto line prefix we should error if the following stuff doesn't match the `line:column` format (column is optional)
