### ISSUE TITLE
[CodeHealth] Replace bind.this with fat arrow functions

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#5091]
We currently have ~70 instances of `this.nameOfAFunctionHere.bind(this)` in the code.

Where possible it would be great to replace the function declarations via `function nameOfAFunctionHere() { ...` with fat arrow functions `nameOfAFunctionHere = () => { ...` so we don't have to bind the context manually in the constructor.

**Comment by atiqueansari1987** [comment]
Anyone working on this?

**Comment by jasonLaster** [comment]
@atiqueansari1987 go for it

**Comment by atiqueansari1987** [comment]
Cool. I will try and submit a PR this weekend.

/claim

**Comment by jasonLaster** [comment]
Hey @atiqueansari1987 how's it going?

**Comment by atiqueansari1987** [comment]
Hi @jasonLaster last weekend I didn't get time to work on this. I will try and submit a PR this week.

**Comment by atiqueansari1987** [comment]
Also I don't have permission to Fork the repo. Can you please help me with this?

**Comment by darkwing** [comment]
Hello @neilholcomb !  How are things going with this?  Anything I can do to help?

**Comment by jasonLaster** [comment]
Hey @neilholcomb, I'm taking your head off this. Feel free to re-claim it.

**Comment by jasonLaster** [comment]
Hey @gurumukhi how's it going?

**Comment by gurumukhi** [comment]
Hey @jasonLaster , I couldn't work on this for some personal reasons. Unclaiming it if others wanna pick this up, I will take this/other bugs once I get some time next.

**Comment by jasonLaster** [comment]
no worries. thanks for the update

**Comment by lukaszsobek** [comment]
Merged. Closing.
