### ISSUE TITLE
[ProjectSearch] sad face while typing

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5108]
It looks like the recent consolidation #5016 is causing the sad face to appear before the user does a search:

STR:
1. cmd+shift+f
2. start typing 

see: sad face

<img src='https://shipusercontent.com/c3bee147c1b711b002ddb28cccc5aae7/Screen%20Shot%202018-01-15%20at%205.51.19%20PM.png' title='Screen Shot 2018-01-15 at 5.51.19 PM.png' width=575>

**Comment by jbhoosreddy** [comment]
done in #5124
