### ISSUE TITLE
[ProjectSearch] shows minified results

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#5109]
STR:

- Open https://arewesmoothyet.com/?mode=track&trackedStat=Devtools%20Hangs
- CMD-SHIFT-F for "trackedStats"
- Click on the first result
- Prettify file; needs some time
- Go back to search with CMD-SHIFT-F
- Focus search field and search again

ER: Show results from prettified file

AR: Repeated results from both un-formatted and formatted file.

<img width="687" alt="image" src="https://user-images.githubusercontent.com/8599/34973764-3b10c72a-fa3e-11e7-890f-3f07f97a7015.png">

<img width="515" alt="image" src="https://user-images.githubusercontent.com/8599/34973845-be0cd9d4-fa3e-11e7-9093-ebfdcc41539f.png">

Clicking on one file header actually toggle both, first and duped, result listings.

**Comment by jbhoosreddy** [comment]
fixed in #5158
