### ISSUE TITLE
[SourceTree] index file is missing for vue

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5112]
STR:

1. navigate to [todomvc - vue](http://todomvc.com/examples/vue/)
2. expand todomvc source tree node
3. expand examples/vue

ER: see (index)
AR: it's not there

<img src='https://shipusercontent.com/366476b6d387efd0f083a86725d8ebda/Screen%20Shot%202018-01-16%20at%209.32.41%20AM.png' title='Screen Shot 2018-01-16 at 9.32.41 AM.png' width=248>

**Comment by hughugsy** [comment]
Hello 👋 
One of the sources has `null` url property. Could this be index file?
![sourceurl](https://user-images.githubusercontent.com/16086407/35736780-514a6212-083a-11e8-9e90-83d56cfb1947.png)
