### ISSUE TITLE
[Tabs] should have the same width

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#5113]
Lots of times I have a bunch of consecutive debugger tabs that I want to close. But I can't use "Close all tabs" nor "Close other tabs" because I want to keep some.

With Firefox tabs it's easy, I just click the close button several times because when a tab is closed the next one takes its position.

But with the debugger I can't do this because all tabs have different widths, so the close button appears at different positions and I must move the mouse.

**Comment by wldcordeiro** [comment]
We could maybe put a pref on this. If you check out editors like Atom and VS Code they usually have options for whether tabs should be equal size or not.

**Comment by jasonLaster** [comment]
Closing this issue and moving to the [enhancements](http://github.com/devtools-html/debugger.html/projects/5) board. 

* We will hopefully be able to prioritize it in the near future. 
* The issue is closed temporarily, but feel free to continue discussing the issue
