### ISSUE TITLE
[Expressions] Removed watched expressions reappear

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#5114]
Follow-up from #3598

1. Go to http://www.example.org/
2. Open the debugger
3. Set the debugger to "Pause on all exceptions"
4. Add a new watched expression: `foo.bar`
5. The debugger pauses: `ReferenceError: foo is not defined`
6. Remove the watched expression
7. Click ▷ (Resume)

Expected: the watched expression stays removed.
Result: the watched expression reappears.
From: https://bugzilla.mozilla.org/show_bug.cgi?id=1388099

**Comment by wldcordeiro** [comment]
I don't know if this issue needed to be opened. Were you testing in Firefox? It might be that the fix just hasn't landed there yet.

**Comment by Loirooriol** [comment]
The "Pause on all exceptions" case was never fixed. I already complained but since #3598 is not reopened, I decided to file a new issue.

**Comment by Loirooriol** [comment]
@jasonLaster But #3598 is still closed...

**Comment by lukaszsobek** [comment]
Closing in favor of #3598
