### ISSUE TITLE
[Stepping] step-in goes to an unexpected line

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#5115]
From: https://bugzilla.mozilla.org/show_bug.cgi?id=1380672

1. Load data:application/json,[]
2. Open the new debugger frontend
3. Search json-viewer.js and open it
4. Add a breakpoint in this line 10:
    ```
    const { render } = require("devtools/client/shared/vendor/react-dom");
    ```
5. Reload the page, the script pauses in there
6. Step in.

Result: the debugger highlights line 95:
```
  function copyString(string) {
```

Just why? If you step it again goes to the next function declaration:
```
  function dispatchEvent(type, value) {
```

And finally another step in goes back to line 10 and behaves as expected.

**Comment by jasonLaster** [comment]
Thanks for filing. Here's a GIF

![](http://g.recordit.co/hxo7IbaYnI.gif)

**Comment by jasonLaster** [comment]
Looking into this a bit more:

- the breakpoint is hit twice. the first time must be an outer location like define. The second is the correct one
- the old debugger works fine. This is a client issue w/ where we add the breakpoint

**Comment by jasonLaster** [comment]
I looked into it a bit more and found that the old UI has the same bug. I believe the issue could be in the engine.

I added some logs to `actors/script.js#_makeOnStep` and learned that the server registers an onStep hook with a start location of line 10 column 0.

Then the step hook is called for 7 offsets on line 10: 5, 6, 10, 14, 1, 22, 26, 27... 

The next onStep call is on line 95! Why don't we go to line 11? :)

Here are some logs:

```
>> _makeOnStep {"startLocation":{"source":{"actor":"server1.conn0.child1/source29","generatedUrl":null,"url":"resource://devtools-client-jsonview/json-viewer.js","isBlackBoxed":false,"isPrettyPrinted":false,"isSourceMapped":false,"sourceMapURL":null,"introductionUrl":null,"introductionType":"scriptElement"},"line":10,"column":0}}
>> _onStep not an entry point {"offset":5,"location":{"lineNumber":10,"columnNumber":0,"isEntryPoint":false}}
>> _onStep not an entry point {"offset":6,"location":{"lineNumber":10,"columnNumber":0,"isEntryPoint":false}}
>> _onStep not an entry point {"offset":10,"location":{"lineNumber":10,"columnNumber":0,"isEntryPoint":false}}
>> _onStep not an entry point {"offset":14,"location":{"lineNumber":10,"columnNumber":0,"isEntryPoint":false}}
>> _onStep not an entry point {"offset":18,"location":{"lineNumber":10,"columnNumber":0,"isEntryPoint":false}}
>> _onStep not an entry point {"offset":22,"location":{"lineNumber":10,"columnNumber":0,"isEntryPoint":false}}
>> _onStep not an entry point {"offset":26,"location":{"lineNumber":10,"columnNumber":0,"isEntryPoint":false}}
>> _onStep at an entrypoint: {"offset":27,"location":{"lineNumber":95,"columnNumber":0,"isEntryPoint":true}}
```

**Comment by jasonLaster** [comment]
The root problem is that spider monkey has bad line number information when functions have let/const and function declarations.

https://bugzilla.mozilla.org/show_bug.cgi?id=1431202

**Comment by jasonLaster** [comment]
I'm going to close this bug because it is going to be fixed in spidermonkey
