### ISSUE TITLE
[Flow] Run flow-typed to get coverage of some third party libraries

### ISSUE THREAD

**Issue by gregtatum** [devtools-html/debugger.html#5122]
There is no coverage for most of the types, as they get coerced to `any` types when they run through  third party libraries. This is particularly bad for reselect, which powers all of the selectors. 

Flow-typed has definition files for the following libraries:

  • enzyme_v3.x.x.js
  • reselect_v3.x.x.js
  • prop-types_v15.x.x.js
  • react-redux_v5.x.x.js
  • lodash_v4.x.x.js

The tool is available here:
https://github.com/flowtype/flow-typed

Also be warned that it generates lots of "stubs" for libraries that aren't supported, they can be a bit of noise if committed.

**Comment by gregtatum** [comment]
The tool is available here:
https://github.com/flowtype/flow-typed

Also be warned that it generates lots of "stubs" for libraries that aren't supported, they can be a bit of noise if committed.

**Comment by wldcordeiro** [comment]
I think it's best to manually add each dependencies types rather than add all + generate stubs.

**Comment by jasonLaster** [comment]
@wldcordeiro why?

**Comment by jasonLaster** [comment]
@gregtatum does perf.html flow type react-redux?

**Comment by gregtatum** [comment]
I built some manual definitions since the ones from `flow-typed` weren't accurate enough and were not causing errors in the props. They are pretty verbose and explicit in order to be correct. I know that people have been working on the official types, but I haven't seen what they've done. I'd be happy to have a bigger discussion around this if you're interested. We still have a couple of small correctness issues with our definition (involving ThunkActions) where we need to fix things.

Some example typing: https://github.com/devtools-html/perf.html/blob/529cb9a1286d7f3b38bf740855dcb5c09a70159e/src/components/marker-table/Settings.js#L63-L70

**Comment by jasonLaster** [comment]
we're now typing all of the 3rd party libs we use

**Comment by gregtatum** [comment]
😮 whoa, nice job!
