### ISSUE TITLE
[Flow] Immutable.js has no type coverage

### ISSUE THREAD

**Issue by gregtatum** [devtools-html/debugger.html#5123]
There are no library definitions in `flow-typed` for Immutable.js, but the latest version of Immutable is adding flow types to the project itself. They are actively being worked on in the release candidate for version 4.0.0, so if the debugger upgraded it would be able to gain the type definition files for free.

**Comment by jasonLaster** [comment]
We should probably upgrade immutable at the same time as the rest of devtools.

**Comment by wldcordeiro** [comment]
@gregtatum there are types that come with the current 3.x version of Immutable but they have an error in them that the devs chose to punt on fixing and instead fixed in 4.x
