### ISSUE TITLE
[Pause] Can't unpause debugger

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#5125]
1. Go to https://example.com
2. Open the debugger
3. Click the pause button
4. Change your mind and attempt to unpause

Result: there is no direct way other than running some script and clicking resume.
Expected: clicking the pause button again should unpause

**Comment by jasonLaster** [comment]
I'm moving the issue to the icebox. We will re-prioritize the issues in the icebox at the beginning of the next release in 6 weeks.
