### ISSUE TITLE
Link to expected JS comment format in CONTRIBUTING

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#513]
We should give people a heads up about the expected comment formatting as seen in https://github.com/devtools-html/debugger.html/pull/491#discussion-diff-73884118

**Comment by jlongster** [comment]
We can just link here: https://wiki.mozilla.org/DevTools/CodingStandards

Although I don't think that is explicitly called out in there, we can add it.

**Comment by clarkbw** [comment]
- [ ] Add comment formatting to Wiki Page
- [ ] Link to JS code formatting in the [CONTRIBUTING](./CONTRIBUTING.md) doc

**Comment by clarkbw** [comment]
Updated the [Comments](https://wiki.mozilla.org/DevTools/CodingStandards#Comments) section of the Coding Standards wiki page.
