### ISSUE TITLE
[Preview] 'Split console' overlays the debugger variable tooltip

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#5134]
*STR:*
1. Set a breakpoint and also enable `Toggle split console [esc])`
2. Hover a variable at bottom

*AR:*
The variable tooltip is cropped:
![image](https://user-images.githubusercontent.com/3307404/35091459-06ff6616-fc3d-11e7-94cd-e4cc982ce692.png)

*ER:*
Don't crop. Either have the tooltip above the `Split console`. Or: Take the opened console into consideration while calculation into which direction the tooltop should open (So in this case not to the bottom but to the top).

**Comment by lukaszsobek** [comment]
Thinking about it there seem to be two situations worth considering: 
1.) the debugger is too low to hold the tooltip.
2.) the debugger is too narrow to hold the tooltip.

What would you say should happen in such situations?

**Comment by jasonLaster** [comment]
@juliandescottes do you think we could use a XUL wrapper here?

**Comment by jnachtigall** [comment]
> What would you say should happen in such situations?

From a user perspective I would expect the tooltip to overlay just like normal, that is, with part of it overlaying over the normal html content (and not be confined to the debugger window). Don't know if this is technically possible though, because afaik the debugger is in its own `iframe` or so. (But at least this might be possible with regards to the `Console` split area)

**Comment by juliandescottes** [comment]
XUL is on the way out, we shouldn't invest in this direction. We should design tooltips to fit in the devtools frame.

Regardless of XUL, the DevTools tooltip is creating tooltip containers in the topmost devtools frame, so even without XUL we have no overlapping issues between devtools panels (eg splitconsole, devtools toolbar etc). It also takes care of calculating best position for the tooltip. 

I would be concerned with having the debugger relying on a different tooltip implementation on github vs mc. Given the current workflow I think I'd prefer the debugger to keep a custom implementation, even if it's more limited.

Calculate the available space in the debugger frame and anchor the tooltip accordingly.

**Comment by ochameau** [comment]
@bgrins is there any plan to replace xul:popup/xul:panel with something else? If not a plan, has it been discussed? I find it quite frustrating to limit devtools UX because of XUL being deprecated.

**Comment by tripurari001** [comment]
I would like to work on this 

My approach would be to calculate the best position to open the tool-tip ( top or bottom ) based on the position of element ( hovered one )

**Comment by darkwing** [comment]
Great @tripurari001 !  Let us know if we can help along the way :)

**Comment by jasonLaster** [comment]
Hey, @tripurari001, I'm un-assigning you as it's been a month. Feel free to re-claim it if you have time

**Comment by jbhoosreddy** [comment]
Been trying to reproduce this issue.
1. update to master. 2. ./bin/download-firefox-artifact. 3. yarn copy-assets-watch
![](http://g.recordit.co/peyHGWBP3r.gif)
The split console is not over the popup.

**Comment by jasonLaster** [comment]
yep! that is true

**Comment by jasonLaster** [comment]
Hmm, it looks like we try to avoid it, but expanding a node causes it

![](http://g.recordit.co/3CkGfxYyFi.gif)
