### ISSUE TITLE
[Sources] the selection width is clipped

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5149]
I think that upgrading to reps and the new tree component caused the sources tree node to be clipped.

this seems like a good fix

```diff
diff --git a/src/components/PrimaryPanes/Sources.css b/src/components/PrimaryPanes/Sources.css
index 0e49ca0..c32840c 100644
--- a/src/components/PrimaryPanes/Sources.css
+++ b/src/components/PrimaryPanes/Sources.css
@@ -33,6 +33,7 @@

 .sources-list .managed-tree .tree .node {
   padding: 0px 0px 0px 3px;
+  width: 100%;
 }
 ```

![](http://g.recordit.co/HMfj8CuYRn.gif)

**Comment by calebt97** [comment]
Hey my name is Caleb (noob for short). I'd love to help you!

**Comment by lukaszsobek** [comment]
@calebt97 Hey Caleb, we'd love your help. I think this issue is pretty much covered though, so maybe take a look at some of our other good first issues here: https://github.com/devtools-html/debugger.html/labels/good%20first%20issue and pick one you like.

**Comment by lukaszsobek** [comment]
Fixed, closing.
