### ISSUE TITLE
[CallStack] Simplify Babel call stacks

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5150]
It's really common for babel to create a bunch of call stack frames when you're paused in an async function.

Here is an example

| displayName | url |
|--|--|
| _callee2$ | webpack:///entry.js |
| tryCatch | webpack:///Users/jlaster/src/mozilla/debugger-examples/node_modules/regenerator-runtime/runtime.js |
| invoke | webpack:///Users/jlaster/src/mozilla/debugger-examples/node_modules/regenerator-runtime/runtime.js |
| defineIteratorMethods/</prototype[method] | webpack:///Users/jlaster/src/mozilla/debugger-examples/node_modules/regenerator-runtime/runtime.js |
| step | undefined |
| step/< | undefined |
| run | webpack:///Users/jlaster/src/mozilla/debugger-examples/node_modules/core-js/modules/es6.promise.js |
| notify/< | webpack:///Users/jlaster/src/mozilla/debugger-examples/node_modules/core-js/modules/es6.promise.js |
| flush | webpack:///Users/jlaster/src/mozilla/debugger-examples/node_modules/core-js/modules/_microtask.js |

It would be awesome if we could simplify it to 

| displayName | url |
|--|--|
| _callee2$ | webpack:///entry.js |
| Async | Babel |

STR:

1. go to http://firefox-dev.tools/debugger-examples/examples/babel/
2. add a breakpoint in entry.js#31

**Comment by calebstdenis** [comment]
@jasonLaster Should we take into account the possibility of `regenerator-runtime` (the top frames) appearing in a non-Babel context? I'm leaning towards "yes" but if the answer is "no" then the implementation for this should be pretty trivial.

**Comment by jasonLaster** [comment]
haha - yeah :) lets go for it!
