### ISSUE TITLE
[Scopes] are missing padding

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5151]
It looks like the scopes pane lost its padding after we refactored the reps and tree component

<img src='https://shipusercontent.com/2b16536c141786dc575d7b26d9660ead/Screen%20Shot%202018-01-19%20at%204.03.34%20PM.png' title='Screen Shot 2018-01-19 at 4.03.34 PM.png' width=324>

**Comment by lukaszsobek** [comment]
Fixed, closing.
