### ISSUE TITLE
Add lint rule for MPL file header

### ISSUE THREAD

**Issue by calebstdenis** [devtools-html/debugger.html#5155]
```javascript
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at <http://mozilla.org/MPL/2.0/>. */
```
^ Every file needs this header. In order to avoid issues like #4869, it would be nice if we had:
- [ ] A lint rule enforcing its presence, using [eslint-plugin-header](https://www.npmjs.com/package/eslint-plugin-header)
- [ ] Setup VS Code (and Atom?) to auto-add this header to new files.

If someone other than me ends up claiming this, don't hesitate to reach out to me on Slack

**Comment by lukaszsobek** [comment]
Like this idea a lot, especially the lint rule, or a similar approach - even automatically adding the header if it is not there yet. It would save time with future implementations and stop us from hunting around trying to re-add the headers.

**Comment by jasonLaster** [comment]
Yo - do you have time to do this?

**Comment by calebstdenis** [comment]
@jasonLaster I can spare an hour or two this week. :)

**Comment by calebstdenis** [comment]
I'm unclaiming this for now to prioritize another issue. If anyone picks it up before me, please don't hesitate to reach out on Slack.

**Comment by calebstdenis** [comment]
Because of the flow directive it seems like this issue is dependent on Stuk/eslint-plugin-header#9

**Comment by jasonLaster** [comment]
@calebstdenis lets fork and land the fix
