### ISSUE TITLE
[QuickOpen] Go To line should only show a sad face when the query is bad

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5157]
STR:
1. cmd+:
2. type 12

AR: sad face
ER: should not be sad

If the user types `:sdlkjdsf` it should show a sad face because that query would be cray

![](http://g.recordit.co/dc6mZUbe1q.gif)

**Comment by jbhoosreddy** [comment]
#5108

**Comment by jbhoosreddy** [comment]
#5086 fixes this.

**Comment by jasonLaster** [comment]
Hey @jbhoosreddy @atwalg2 @wldcordeiro I still see the issue.

Also the prefix is selected lol.. Damn this is a tough feature :)

<img src='https://shipusercontent.com/b3d944a0a33d42670172f260cae8e07b/Screen%20Shot%202018-02-02%20at%205.50.40%20PM.png' title='Screen Shot 2018-02-02 at 5.50.40 PM.png' width=769>

<img src='https://shipusercontent.com/96c8af125e402f6c006b1d3a3aeea13a/Screen%20Shot%202018-02-02%20at%205.51.07%20PM.png' title='Screen Shot 2018-02-02 at 5.51.07 PM.png' width=796>

**Comment by lukaszsobek** [comment]
@jasonLaster the prefix is selected because we select everything there is in the input field on reopening. It will not be selected on the first open.

**Comment by jasonLaster** [comment]
hmm, i feel like if you do `cmd+;`,`<esc>`,`cmd+;` it shouldnt be selected... can we make that work?

**Comment by lukaszsobek** [comment]
@jasonLaster - will give it a go.

**Comment by lukaszsobek** [comment]
Merged. Closing.
