### ISSUE TITLE
Fix Keyboard Shortcuts with the firefox panel

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#517]
We noticed while loading the bundle that the keyboard shortcuts library uses Services, which includes Prefs, which uses localstorage, which breaks.

We should fix this soon so that we can bundle the debugger of of HEAD

**Comment by jasonLaster** [comment]
jryans is working on a patch that will support localstorage in the panel. If this lands then keyboard-shortcuts will be supported. Don't ask why localstorage is related to keyboard shortcuts 😛

**Comment by clarkbw** [comment]
> jryans is working on a patch that will support localstorage in the panel

Can you drop a link to that work?  🚧

**Comment by jasonLaster** [comment]
not sure if it's being tracked.
