### ISSUE TITLE
Remove to-fast-properties optimization

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5179]
It looks like we're including a v8 optimization that throws warning in spider monkey. We should try and remove it from the babel / webpack build step.

https://github.com/sindresorhus/to-fast-properties

**Comment by darkwing** [comment]
It doesn't appear that we're using this anymore @jasonLaster ; I am, however, seeing it in yarn.lock from example directories.  Does that matter or was this simply for our project?
