### ISSUE TITLE
[QuickOpen] Remove result count

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5189]
@gabrielluong pointed out to me the other day that most editors do not include the result count in their quick open modal. 

I think it is a cleaner to leave out the result count. The other benefit is then we can find fewer matches (100 instead 1000) which will be even faster.

This what it would look like

| files | functions |
| --- | --- |
| <img  src='https://shipusercontent.com/59d0710d1bc14933e23e751982705e05/Screen%20Shot%202018-01-24%20at%205.49.50%20PM.png' title='Screen Shot 2018-01-24 at 5.49.50 PM.png' width=432> | <img src='https://shipusercontent.com/96b06becf30beb416c1cc013c0ca92a5/Screen%20Shot%202018-01-24%20at%205.49.55%20PM.png' title='Screen Shot 2018-01-24 at 5.49.55 PM.png' width=431> |

**Comment by jasonLaster** [comment]
Hey @CharlesStocky how's it going?

**Comment by CharlesStocky** [comment]
I'm starting to work on it now @jasonLaster. Just to make sure I understand the issue, should the result count not show up when searching in files/ sources?

**Comment by jasonLaster** [comment]
yep

**Comment by CharlesStocky** [comment]
@jasonLaster How's this? 

<img width="765" alt="screen shot 2018-02-09 at 3 58 34 pm" src="https://user-images.githubusercontent.com/24966772/36052177-32a754fa-0db2-11e8-86a3-b1cab708f0bd.png">

**Comment by jasonLaster** [comment]
i like it.

**Comment by CharlesStocky** [comment]
Is there anywhere else the result count shouldn't show up? If not I'll submit a PR :)

**Comment by AnshulMalik** [comment]
I think that was the only place. @CharlesStocky

**Comment by CharlesStocky** [comment]
Unweaving Jest tests at the moment, I'll submit the PR soon.

**Comment by CharlesStocky** [comment]
I made a PR that was merged for this issue. https://github.com/devtools-html/debugger.html/pull/5387

**Comment by jasonLaster** [comment]
Hmm, I think this addressed the issue, but now i see the result count is missing from project search `cmd+shift+f`. I forgot if we want it in file search `cmd+f`

**Comment by jasonLaster** [comment]
Just filed #5528
