### ISSUE TITLE
resource:// urls in source tree

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#519]
Not sure how we want to handle these for now.  We could hide them or maybe leaving them in the list but perhaps it could be at least sorted to the bottom.  The add-on code running in the page is a valid use case for some set of people bu feels less important than the page itself.

![screen shot 2016-08-08 at 1 35 37 pm](https://cloud.githubusercontent.com/assets/2134/17495334/92f9ff34-5d6d-11e6-96cb-bef23b80c030.png)

**Comment by jlongster** [comment]
Addon debugging is a very important use case (almost mentioned this in my email) and I think they'll always show up as resource:// URLs, so we need to be careful of hardcoding any rules for them specifically. What does our old debugger to for these scripts?

**Comment by jlongster** [comment]
Also, did you do anything to see those webpack URLs? Sourcemapping should be turned off so you shouldn't be seeing those...

**Comment by jasonLaster** [comment]
@jlongster I believe source mapping is on by default on the server at the moment. My patch on friday that disables it probably didn't land yet.

**Comment by clarkbw** [comment]
Ok, lets keep them as is for now.
