### ISSUE TITLE
Investigate CodeMirror module

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#520]
We need to figure out how we'll be supporting codemirror and other features in the new debugger. The big question is, how do we share editor functionality with other tools so that users have a consistent experience.

**Options**:
1. we modify `sourceditor.js` so that we can re-use it directly in `Editor.js`
2. we develop a new modular editor that other tools can use going forward. [comment](https://github.com/devtools-html/debugger.html/issues/134#issuecomment-238379361)

With something like this, it is probably best to prototype a couple options and see what direction feels right.

**Comment by jasonLaster** [comment]
Is this done?

**Comment by jlongster** [comment]
Not quite; this bug needs to be resolved on m-c first: https://bugzilla.mozilla.org/show_bug.cgi?id=1295213

**Comment by jlongster** [comment]
This is done.
