### ISSUE TITLE
[Expression] syntax errors are cleared on save

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#5204]
Create a watch expression with a syntax error, e.g. `[1,2,3`

Result: the expression is cleared and "Invalid expression..." is displayed.

Expected: the expression is not cleared so that you can fix the syntax error without having to rewrite it all.

**Comment by jasonLaster** [comment]
@Loirooriol this was added to the debugger in github. It should be in nightly tomorrow or monday.

**Comment by Loirooriol** [comment]
Still bad after [bug 1432842](https://bugzilla.mozilla.org/show_bug.cgi?id=1432842) (v10).

**Comment by jasonLaster** [comment]
CC @bomsy @wldcordeiro what do you think?

**Comment by bomsy** [comment]
I think it's a good idea that we do not clear the invalid expression. 
It can be frustrating to retype really long expressions because of tiny mistakes.
Maybe making the border (and also maybe the text) red should be quite obvious to the user.

**Comment by bomsy** [comment]
Maybe we shoould fix this as well here

![](http://g.recordit.co/RVaVrdnNUD.gif)

The field should not remain red (in the invalid expression state) after the invalid expression has been field.

**Comment by jasonLaster** [comment]
```diff
diff --git a/src/actions/expressions.js b/src/actions/expressions.js
index bf237e9..62fde2e 100644
--- a/src/actions/expressions.js
+++ b/src/actions/expressions.js
@@ -48,6 +48,7 @@ export function addExpression(input: string) {
 }
 
 export function clearExpressionError() {
+  // maybe this will help
   return { type: "CLEAR_EXPRESSION_ERROR" };
 }
 
diff --git a/src/components/SecondaryPanes/Expressions.js b/src/components/SecondaryPanes/Expressions.js
index fb22daf..dbd22d0 100644
--- a/src/components/SecondaryPanes/Expressions.js
+++ b/src/components/SecondaryPanes/Expressions.js
@@ -57,6 +57,7 @@ class Expressions extends Component<Props, State> {
   }
 
   clear = () => {
+    // some useful code
     this.setState(() => {
       this.props.clearExpressionError();
       return { editing: false, editIndex: -1, inputValue: "" };
@@ -207,6 +208,8 @@ class Expressions extends Component<Props, State> {
   renderExpressionEditInput(expression: Expression) {
     const { expressionError } = this.props;
     const { inputValue, editing } = this.state;
+
+    /// is this doing the right thing?
     const error = editing === true && expressionError === true;
     return (
       <span className="expression-input-container" key={expression.input}>
```

**Comment by marcogallo566** [comment]
Thank you, this will help a lot!
