### ISSUE TITLE
Debugger freezes window

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#5205]
1. Disable e10s
2. Load https://api.github.com/
3. Open debugger
4. Click pause button
5. Click some row in the JSON Viewer so that a script runs

Result: the window freezes. If you focus some other window (not necessarily a Firefox one) and then you focus the former back, then it works again.

Windows 10 1709, Nightly 60.

**Comment by jasonLaster** [comment]
This works now

![](http://g.recordit.co/O0wmPDfU8j.gif)

Re-open if you can still reproduce

**Comment by Loirooriol** [comment]
Reproducible in latest Nighly d6957f004e9cc3d7408ac3a8f2b49ff97556e27f. I can't reopen.

![screencast](https://user-images.githubusercontent.com/7477678/37312165-46f2c56a-264a-11e8-8887-36783b3e3fa6.gif)

**Comment by AnshulMalik** [comment]
I can't reproduce this on latest pull from m-c, so this will be fixed soon in nightly :)

**Comment by Loirooriol** [comment]
@AnshulMalik Still reproducible in Nightly 8f1b2f872f0ea358a0412eb8b8687f08d47f6621, and right now this is the latest commit in mozilla-central.

**Comment by AnshulMalik** [comment]
This is strange, it works fine for me

**Comment by jasonLaster** [comment]
@AlexisDeschamps @darkwing can you try and repro on windows?

**Comment by Loirooriol** [comment]
Did you make sure that e10s (`browser.tabs.remote.autostart`) was disabled?

**Comment by jasonLaster** [comment]
oh interesting. I dont think we're testing non-e10s anymore?

**Comment by jasonLaster** [comment]
I'm closing for now as we we're not prioritizing non-e10s perf issues.

I'll re-open if that changes.
