### ISSUE TITLE
Previous searched text should be selected

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#5214]
1. Got to http://example.com/
2. Open debugger
3. Press Ctr+Shift+F, the search bar appears
4. Enter `a` and press enter
5. Select some result, the file opens and search bar closes
6. Press Ctr+Shift+F again, now to search `b`

Expected: when the search bar appears, `a` is selected to that writing something rewrites the old value
Result: the cursor is at the end, so the new text to be searched is appended.

**Comment by lukaszsobek** [comment]
I think there was a discussion on this topic, so it might be this way by design.

**Comment by Loirooriol** [comment]
The current behavior is so annoying and I don't know any other program that does this.

All of Firefox, Chrome, Chrome's debugger, Edge, Edge's debugger, Notepad, Notepad++, Word, etc. select the previous searched text so that you can replace it with the new one. Firefox's debugger is the only weird one.

**Comment by jasonLaster** [comment]
This does seem like a bug

**Comment by lukaszsobek** [comment]
Merged. Closing.
