### ISSUE TITLE
[Expressions] Cursor moves to the end when writing watch expression

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#5220]
Like #4693, but with watch expressions.

1. Click *Add watch expression*
2. Write `123`, press enter
3. Double click the watch expression
4. Press home key
5. Write `abc`

Result: the field shows `a123bc`
Expected: `abc123`

**Comment by lukaszsobek** [comment]
lol, this one is good. Here is a visual on the bug:
![abc123](https://user-images.githubusercontent.com/23530054/35481127-ad850c4c-041d-11e8-802d-75cfc5bfb6e2.gif)

**Comment by Loirooriol** [comment]
I still don't understand why somebody thought using `setSelectionRange` to move the cursor to the end would be useful. I would just get rid of that.

https://github.com/devtools-html/debugger.html/blob/8fe140cce02dd4a7181b436b7ac46875dbc1251d/src/components/SecondaryPanes/Expressions.js#L87

It's also in SearchInput.js, maybe it's what causes #5214.

https://github.com/devtools-html/debugger.html/blob/8fe140cce02dd4a7181b436b7ac46875dbc1251d/src/components/shared/SearchInput.js#L60

**Comment by jasonLaster** [comment]
yeah - i forgot why ...

CC @wldcordeiro

**Comment by lukaszsobek** [comment]
Merged. Closing.
