### ISSUE TITLE
[Breakpoints] Clean up extracted context menu

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#5223]
We recently merged https://github.com/devtools-html/debugger.html/pull/5049 which extracts the context menu for breakpoints into its own file. As a followup it would be nice to give 2 files:

src/components/SecondaryPanes/Breakpoints.js
src/components/SecondaryPanes/BreakpointsContextMenu.js

a cosmetic treatment consisting of:

- dividing import statements into dependencies and code imports by moving the corresponding statements together.
- sorting each of the groups alphabetically so that if we import both `a` and `b` the import statements should be ordered alphabetically.

Also make sure that the name of each
- label variable actually ends with the word label e.g. `deleteSelfLabel` instead of `deleteSelf`
- key variable actually ends with the word key e.g. `enableSelfKey` instead of `enableSelf`
- item variable actually ends with the word item e.g. `enableOthersItem` instead of `enableOthers` 

=== Why
Coding takes time, much of which is spent on reading the code of others. In order to waste as little time as possible we need to make sure the code we produce is as easy to understand as possible. One of the easiest way to achieve this is simply by sorting things alphabetically and giving variables meaningful names.

**Comment by nharrisanalyst** [comment]
I would like to help can i be assigned?

**Comment by jasonLaster** [comment]
@nharrisanalyst it's yours!

**Comment by jasonLaster** [comment]
you can claim it! https://github.com/devtools-html/debugger.html/#next-steps
