### ISSUE TITLE
[Webpack] Set up to automatically import react and react-dom

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#5234]
In order to stop typing `import React from "react"` and `import ReactDOM from "react-dom"` manually every time we could make Webpack do the job for us. This would look as follows:

```
module.exports = {
...
  plugins: [
    new webpack.ProvidePlugin({
      'React': 'react',
      'ReactDOM': 'react-dom',
      'myfancystuff': 'firefox-is-awesome',
     ...
    })
  ],
...
```

This would:
1.) save us from having to type out import statements
2.) make assure us the needed items are always going to be imported,
3.) the dependencies would only get imported when we need them,
4.) help us stop hunting selected missing dependency imports,
5.) lower the number of lines in the code.

Questions:
a.) Would this have a negative impact on the performance of the debugger in terms of load time?
b.) As this adds a layer of abstraction, how would we communicate this feature to our contributors?
c.) Which other modules could we handle this way to automate in a meaningful way?

**Comment by MikeRatcliffe** [comment]
I have only recently started to work on the debugger.html codebase but it 'feels' like we shouldn't do this... some issues off the top of my head:

1. Some components don't use ReactDOM so we would have some unnecessary imports.
2. Some files may not even need to import React so again we could have unnecessary imports.
3. We often choose not to load the whole of ReactDOM by using e.g. `import div from react-dom`
4. I like to see everything a file is doing and moving these things to a background process will make the files more difficult to comprehend for new contributors.

**Comment by lukaszsobek** [comment]
@MikeRatcliffe 
ad 1,2 - the imports are conditional on an as needed basis, so if the file uses e.g. React it is going to be imported, if it doesn't - there is no import.
ad 3 - would be interesting to see if and how such a case can be handled, because we have a few instances of it in the import statements.
ad 4 - It feels like this is very much a question of preference, but I agree that it would add a thing to keep in mind when working with the repo.

**Comment by nyrosmith** [comment]
I already tried this in another project and we reverted it.
Rule of thumb: Make things explicit. Such a change causes more confusion than helping in anything

**Comment by bomsy** [comment]
I agree with the points made  that importing  stuff should be explicit.
And that it'll make things a lot more confusing.

**Comment by lukaszsobek** [comment]
Not desirable. Closing.
