### ISSUE TITLE
[Source Tree] highlight selected tab

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#524]
When you have multiple source tabs open in the editor I assumed switching between them would update the source tree view on the left.  I'm not sure some opposite approach of a tightly coupled source view that jumps around is the answer, but likely the selected state should change so it isn't confusing when I want to go back to a file that appears to already be selected.

See screenshot where one tab is selected but the source view shows the other file to be the selected file.
![screen shot 2016-08-08 at 4 04 49 pm](https://cloud.githubusercontent.com/assets/2134/17499478/744b82b4-5d82-11e6-9fdd-7fb161293b0c.png)

**Comment by jasonLaster** [comment]
Thanks for filling this, Jane's and I talked about this in June. 

I think you're right that is a question of updating the selected item. I'd like to double check Chrome's and sublimes UX. I don't think any of them open the tree.

**Comment by wldcordeiro** [comment]
Atom and I think Sublime just put a highlight over the lowest expanded part of the tree from what I can tell.

**Comment by wldcordeiro** [comment]
Updating from research, Sublime only highlights the file not the tree so collapsing the containing folder won't apply the highlight to the folder. Both however will highlight the selected tab rather than last clicked.

## Sublime

![screenshot_20160919_214229](https://cloud.githubusercontent.com/assets/580982/18656850/0baaf590-7eb2-11e6-94f3-54abedc53477.png)


## Atom

![screenshot_20160919_214212](https://cloud.githubusercontent.com/assets/580982/18656853/10b60642-7eb2-11e6-8079-d5ed29ef5dc0.png)

**Comment by jasonLaster** [comment]
Go for it.

**Comment by wldcordeiro** [comment]
Bumping with status update, had been distracted with some other issues that had come up. Been working on this today and should have a PR in today or tomorrow.

**Comment by wldcordeiro** [comment]
A slightly more complicated change than I had anticipated as there are several levels of components interacting here. I'm relabeling to signal this and in the event I burn out on the issue I'll remove my assignment and others will know. 😄

**Comment by wldcordeiro** [comment]
Jumping back on this, more free time available to focus on the task.

**Comment by jasonLaster** [comment]
Hey @wldcordeiro, just saw you claimed this awhile back. Still interested in taking a stab?

**Comment by wldcordeiro** [comment]
@jasonLaster sorry, had lapsed on this. Working on it now. Should get a PR in soon.

**Comment by jasonLaster** [comment]
No worries man. Ping me if you have questions. It's a tricky one

**Comment by jasonLaster** [comment]
Hey @wldcordeiro do you have a branch you can share?

By the way, i think we could use something like this this: https://github.com/devtools-html/debugger.html/pull/1403/files#diff-050facbbe0316544048b8fe886ad454dR337

**Comment by wldcordeiro** [comment]
@jasonLaster I don't. 😞 I had a local one on my old laptop but no longer.

**Comment by clarkbw** [comment]
> but no longer

no worries 😄

**Comment by jasonLaster** [comment]
@wldcordeiro cleaned up this issue.

@arthur801031 finished working on "reveal source" which should give you some nice APIs for focusing on the selected source. https://github.com/devtools-html/debugger.html/pull/1403

Are you interested in taking a stab at this with the new APIs?

**Comment by arthur801031** [comment]
I will take a stab at this :)
