### ISSUE TITLE
[Preview] Show empty values

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5241]
We recently regressed when it comes to showing tooltips for empty/falsey values

STR:
1. navigate to https://index-empties.glitch.me/
2. click "stuff"
3. hover on falsyString, falsyBool, falsyNumber, undefinedThing, nullThing

```js
function stuff() {
  let falsyString = "";
  let falsyBool = false;
  let falsyNumber = 0;
  let undefinedThing = undefined;
  let nullThing = null;

  let truthyString = " ";
  let truthyBool = true;
  let truthyNumber = 1;

  debugger;
}
```

**Comment by Fischer-L** [comment]
I can reproduce this bug but one thing confuses me, which is, while hovering on `falsyNumber` I could observed[1] the preview prop like
```
Object { expression: "falsyNumber", result: 0, location: {…}, tokenPos: {…}, cursorPos: DOMRect, extra: {}, updating: false }
```
But no preview showed for `falsyNumber`.

The same prop for `undefinedThing` also observed
```
Object { expression: "undefinedThing", result: {…}, location: {…}, tokenPos: {…}, cursorPos: DOMRect, extra: {}, updating: false }
```
and a preview showed for `undefinedThing`

[1][https://github.com/devtools-html/debugger.html/blob/6d4220ecc43e4613f5db8feda6b2c25676f46259/src/components/Editor/Preview/index.js#L137](https://github.com/devtools-html/debugger.html/blob/6d4220ecc43e4613f5db8feda6b2c25676f46259/src/components/Editor/Preview/index.js#L137)

**Comment by Fischer-L** [comment]
@jasonLaster Would you see PR #5279? thanks
