### ISSUE TITLE
Breakpoints - adding lots of breakpoints causes errors

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#525]
If you open a source and start thrashing on the gutter (adding/removing) lots of breakpoints, you'll quickly see three errors:

+ ` {from: "server1.conn147.child1/34", error: "wrongState", message: "Cannot set breakpoint while debuggee is running."}`
+ `error: "wrongState", message: "Stack frames are only available while the debuggee is paused.", from: "server1.conn147.child1/26"}`
+ `TypeError: Cannot read property 'type' of undefined` in firefox/events.js.16

![screen shot 2016-08-09 at 10 51 19 am](https://cloud.githubusercontent.com/assets/254562/17520812/122f7282-5e1f-11e6-86ad-33387db9c42a.png)

**Comment by clarkbw** [comment]
@jasonLaster should we drop this for the next sprint?

**Comment by jasonLaster** [comment]
Not sure yet, looking into a related bug for disable all breakpoints.

Im looking into an easy fix, where we disable the breakpoint in the gutter
if it's loading and disable all breakpoints if a breakpoint is loading.
