### ISSUE TITLE
[Sources] The indentation of the files is off

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5250]
It looks like the tree indentation is a bit off, which could come from a variety of places:

1. https://github.com/devtools-html/debugger.html/issues/5239
2. https://github.com/devtools-html/debugger.html/issues/5216

<img src='https://shipusercontent.com/245a1d94ac4f19099bf30f024f224518/Screen%20Shot%202018-01-30%20at%205.17.36%20PM.png' title='Screen Shot 2018-01-30 at 5.17.36 PM.png' width=697>

**Comment by MikeRatcliffe** [comment]
Here is a screenshot from an MDN tutorial for comparison:

![Before](https://user-images.githubusercontent.com/116941/35628962-4c5788da-0695-11e8-83b0-56794003efa3.png)

**Comment by MikeRatcliffe** [comment]
I am debugging this using http://todomvc.com/examples/dojo/ because it has a reasonably deep tree.

**Comment by MikeRatcliffe** [comment]
I have created a pull request at https://github.com/devtools-html/devtools-core/pull/919 so that this can be fixed upstream.

**Comment by MikeRatcliffe** [comment]
In the future we may consider switching to the arrows provided by core but for consistency in the debugger let's make the CSS change. The debugger arrows are a different size than core and I think they fit the debugger better.

**Comment by lukaszsobek** [comment]
Merged. Closing.
