### ISSUE TITLE
[Breakpoint] Adds XHR breakpoints

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#5255]
It is sometimes necessary to discover which functions called a specific XHR request.

1. Have a UI for adding breakpoints.
2. Propose to add breakpoints on XHR requests (all of them or including a specific string)
3. When the code reaches the XHR request, jump to the code at the right place (probably formatted version of the code).

**Comment by SebastianZ** [comment]
For reference, the idea of breaking on XHRs was initially requested in Bugzilla as [bug 821610](https://bugzilla.mozilla.org/show_bug.cgi?id=821610).

For what it's worth, Firebug had this feature and it had UIs within its *Net* and *Console* panels to set them and a [*Breakpoints* side panel](https://web.archive.org/web/20170502101655/http://getfirebug.com/wiki/index.php/Breakpoints_Side_Panel) within its debugger to list and remove them.

Sebastian

**Comment by jasonLaster** [comment]
I'm moving the issue to the icebox. We will re-prioritize the issues in the icebox at the beginning of the next release in 6 weeks.

**Comment by jasonLaster** [comment]
Here are some notes:

@jlast What the Network panel needs is server side hook (and actor?) that can be used to create a new breakpoint using URL (and later other props like e.g. a keyword saying that the XHR breakpoint should break the execution only when the response body contains the keyword, etc.) Consequently we can play with the Net panel UI/UX... (edited)

From API perspective, it could be as simple as: `createXhrBreakpoint(url);`  - Breaks the current JS execution when the current XHR URL contains given `url` value. Later, it could be nice if support for conditional breakpoint is added. e.g. `count == 2` - breaks only if URL parameter `count` is presented and equal to `2` or, checking the post/response  body for specific keyword

Here is detailed description of how it works in Firebug http://www.softwareishard.com/blog/firebug/firebug-15-xhr-breakpoints/

**Comment by jasonLaster** [comment]
CC @janodvarko @jimblandy i think you'll enjoy @AnshulMalik thread actor work...

**Comment by AnshulMalik** [comment]
Can we get this one out of icebox?

**Comment by AnshulMalik** [comment]
Ohh I think we have covered the points from this bug, I have created another bug for enhancement. Sorry for the trouble.
