### ISSUE TITLE
[QuickOpen] Pretty printed tabs are not listed

### ISSUE THREAD

**Issue by AnshulMalik** [devtools-html/debugger.html#5256]
STR:
- Pretty print a source
- Close minified source
- Press `Cmd + P`
- Pretty Printed source doesn't appear in the list

Is this intentional behavior?

![watch](https://user-images.githubusercontent.com/7821757/35604822-57f9ddd0-066a-11e8-9941-8c2b72384f0e.gif)

**Comment by jasonLaster** [comment]
We only want to show one version... but i guess it's not clear which one to show...

We have a couple PP UX issues that we should sort out :)
