### ISSUE TITLE
Outline panel only show one class

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#5257]
On Nightly 60.0a1 (2018-01-30) 

Steps to reproduce:
1. Go to https://debugger-html-multiple-classes-outline.glitch.me/
2. Open the debugger
3. Select the `script.js` file
4. Open the Outline panel

Expected results:

2 classes `A` & `B` are displayed, each one with their functions

Actual results:

Only the `A` class is displayed, with its functions, but also the ones from the `B` class

<img width="559" alt="image" src="https://user-images.githubusercontent.com/578107/35609722-bafbb7e8-065e-11e8-9c72-b9349fe6605a.png">

**Comment by darkwing** [comment]
This will be fixed as part of

**Comment by darkwing** [comment]
Fixed in #5290
