### ISSUE TITLE
Classes in the outline panel could be collapsible

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#5260]
If you have multiple classes in a file, it would be nice to hide all the methods from a given class you are not interested in.

**Comment by jasonLaster** [comment]
I'm not sure if this is needed. I think Firefox is a bad example. There shouldn't be many files in the wild with lots of classes. 

If we add filtering in the future that will help here as well.

**Comment by darkwing** [comment]
I agree with @jasonLaster here.  I think it would be a cool addition, and would only enact it if there were {x} number of classes or functions.

**Comment by jasonLaster** [comment]
I'm moving the issue to the icebox. We will re-prioritize the issues in the icebox at the beginning of the next release in 6 weeks.
