### ISSUE TITLE
[QuickOpen] Cmd+P while Help panel is displayed should hide the help panel

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#5261]
**Steps to reproduce:**
1. Open the Help Panel (Click the `?`)
2. When opened, do <kbd>Cmd</kbd> + <kbd>P</kbd>

**Expected results:**

I can search for files

**Actual results:**

The help panel is in front of the search file modal

![jan-31-2018 09-27-28](https://user-images.githubusercontent.com/578107/35612420-02e7210a-0669-11e8-808e-7f2145e30ce7.gif)

---

I think this can be a common behavior since you look at the help to get the shortcut and want to use it right away.

**Comment by wldcordeiro** [comment]
Ah yeah there should only be one winning modal. 😆
