### ISSUE TITLE
[Outline] Should show a loading message

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#5267]
At the moment, if the Outline panel does not have symbols, either because the file do not have functions, or because they are being fetched, we show the "No functions" text.

See: 
![jan-31-2018 11-40-03](https://user-images.githubusercontent.com/578107/35618514-8259f3d8-067b-11e8-9027-4fc6642f245e.gif)

This can take some time for bundle files and make the user think the outline view is broken.

Instead, when we are fetching symbols, we should display a "loading functions" or something similar, until we are done.

**Comment by AnshulMalik** [comment]
Hey @sravan-s, would you like to hack on this?

**Comment by Rohanhacker** [comment]
Can I work on this ?

**Comment by jasonLaster** [comment]
how's it going @Rohanhacker

**Comment by Rohanhacker** [comment]
Sorry couldn't make a pr got a little busy I will make a PR tonight. I am a bit confused though. Should I put the loading state for symbols in ast -> symbols as loadedstate in a way similar to how its being done for sources or should I put it somewhere else.

**Comment by jasonLaster** [comment]
Good question @Rohanhacker we currently use `symbols && symbols.identifiers.length > 0` to indicate that we're loading. Feel free to do the same.

The better thing to do is to have a proper symbols loading flag and to stop using the `emptySymbols` object. If that makes sense feel free to do this change first and then outline view.

the two places we do symbols loading now are QuickOpen and actions/preview.

**Comment by Rohanhacker** [comment]
@jasonLaster Thanks for the reply. I think It would make more sense to refactor it first and then finish this outline issue. I'll fix #5267 first and then get back to this .
