### ISSUE TITLE
[QuickOpen] Cmd + P show an input with "0 results"

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#5277]
Steps to reproduce:
1. Open the debugger
2. Do Cmd + P

Expected results:

I see the input bar with a text that invites me to search for sources

Actual results:

I see an input bar with a "0 results" label, although I did not search for anything yet: 

![image](https://user-images.githubusercontent.com/578107/35666716-5a604d90-072b-11e8-8db2-f0a90d10a8c0.png)

When the input is open, we shouldn't show the number of result if we did not search for anything yet.

**Comment by jasonLaster** [comment]
Hey @nchevobbe what site are you debugging?

**Comment by wldcordeiro** [comment]
I was under the impression we were axing the result count?

**Comment by jasonLaster** [comment]
- true lets close this.
- do we want to show quickopen if there are 0 sources?
