### ISSUE TITLE
[Breakpoints] breakpoint missed at jsx error

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5280]
STR: 
1. go to https://github.com/nchevobbe/devtools-bug-finder/tree/refactor
2. clone it, then npm install
3. just open index.html
4. open the debugger
5. select the "web console" component
6. see the error in the console about this being undefined
7. click on the source to get to the jsx file
8. put a breakpoint at said line
9. select another component
10. should trigger the breakpoint, but it does not, at least on my machine

<img src='https://shipusercontent.com/c224bc9de563809c3d35f64a9d449553/Screen%20Shot%202018-02-01%20at%209.28.59%20AM.png' title='Screen Shot 2018-02-01 at 9.28.59 AM.png' width=1410>

**Comment by nchevobbe** [comment]
So, here's what the original code looks like : 
```js
class ComponentsSidebar extends React.Component {
  // constructor(props) {
  //   super(props);
  //   this.onComponentChange = this.onComponentChange.bind(this);
  // }

  onFilterChange(e) {
    const {searchBug} = this.props;
    searchBug({
      [e.target.name]: e.target.value
    });
  }

  onComponentChange(e) {
    var searchBug = this.props.searchBug;
    searchBug({
      component: e.target.value
    });
  }
```

I am trying to add a breakpoint to the `var searchBug …` line.
Here's the breakpoints in the state: 

```json
{
  "breakpoints": {
    "server1.conn2.child1/source45/originalSource-5531acef69df6020219915b56bf9edde:18:4": {
      "id": "file:///Users/nchevobbe/Projects/devtools-bug-finder/public/bundle.js:21205:4",
      "disabled": false,
      "hidden": false,
      "loading": false,
      "condition": null,
      "location": {
        "sourceId": "server1.conn2.child1/source45/originalSource-5531acef69df6020219915b56bf9edde",
        "sourceUrl": "webpack:///app/components/ComponentsSidebar.jsx",
        "line": 18,
        "column": 4
      },
      "astLocation": {
        "name": "onComponentChange",
        "offset": {
          "line": 1
        }
      },
      "generatedLocation": {
        "line": 21205,
        "sourceId": "server1.conn2.child1/source45",
        "column": 4,
        "sourceUrl": "file:///Users/nchevobbe/Projects/devtools-bug-finder/public/bundle.js"
      }
    }
  },
  "breakpointsDisabled": false
}
```

Here's the function in the bundle: 
<img width="559" alt="image" src="https://user-images.githubusercontent.com/578107/35695862-07edace6-0786-11e8-9de5-00bf9513bc61.png">


---

Now if I remove the indentation in the line, it does work !
```js
  onComponentChange(e) {
var searchBug = this.props.searchBug;
    searchBug({
      component: e.target.value
    });
  }
```

Here's the state at this point:
```json
{
  "breakpoints": {
    "server1.conn2.child1/source45/originalSource-5531acef69df6020219915b56bf9edde:18:4": {
      "id": "server1.conn2.child1/breakpoint197",
      "condition": null,
      "disabled": false,
      "hidden": false,
      "loading": false,
      "text": "",
      "astLocation": {
        "name": "onComponentChange",
        "offset": {
          "line": 1
        }
      },
      "generatedLocation": {
        "line": 21205,
        "sourceId": "server1.conn2.child1/source45",
        "column": 4,
        "sourceUrl": "file:///Users/nchevobbe/Projects/devtools-bug-finder/public/bundle.js"
      },
      "location": {
        "line": 18,
        "column": 4,
        "sourceUrl": "webpack:///app/components/ComponentsSidebar.jsx",
        "sourceId": "server1.conn2.child1/source45/originalSource-5531acef69df6020219915b56bf9edde"
      }
    }
  },
  "breakpointsDisabled": false
}
```

**Comment by jasonLaster** [comment]
Hmm, @nchevobbe did you fix the bug :)


<img src='https://shipusercontent.com/5147932079727221267ed0452ee56cca/Screen%20Shot%202018-02-05%20at%206.30.37%20PM.png' title='Screen Shot 2018-02-05 at 6.30.37 PM.png' width=1422>
<img src='https://shipusercontent.com/21ac5fe9f964d4ff2ad1a08255cc8e8d/Screen%20Shot%202018-02-05%20at%206.30.31%20PM.png' title='Screen Shot 2018-02-05 at 6.30.31 PM.png' width=1422>

also is `open index.html` enough?

**Comment by nchevobbe** [comment]
Let me check again

**Comment by nchevobbe** [comment]
So, I did not fixed the bug, and to see it you have to click on a component on the left sidebar (like webconsole).

**Comment by jasonLaster** [comment]
landed
https://bugzilla.mozilla.org/show_bug.cgi?id=1436151
