### ISSUE TITLE
[QuickOpen] modal scrolls when displayed

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#5284]
Steps to reproduce:
1. In a page with a good number of files, open the debugger in the firefox devtools, docked at the bottom (not sure this is important but I could not reproduce with the launchpad)
2. Open the Source modal (Cmd + P)

Expected results:
I see the modal, scrolled at the top

Actual results:

The modal is displayed, but already scrolled

![feb-01-2018 16-21-52](https://user-images.githubusercontent.com/578107/35686363-6ac598b6-076c-11e8-9c0f-5b1879e55ea0.gif)

**Comment by kootoopas** [comment]
Seems that `resultEl.clientHeight` is out of wack. I compared getting its value wo/ and w/ `setTimeout`, and I got different values:

excerpt of `utils/result-list.js`:
```javascript
function scrollList(resultList, index) {
  // ...
  console.log(resultEl.clientHeight)
  setTimeout(() => console.log(resultEl.clientHeight), 200);
  // ...
}
```

results to
```javascript
1076 // X crazy height
53   // ✔️ right height via timeout
```

So as a result of this, if I delay the scrolling invocation (both for firefox and chrome), it behaves properly:

```javascript
function scrollList(resultList, index) {
  // ...
  setTimeout(() => {
    if (isFirefox()) {
      resultEl.scrollIntoView({ block: "center", behavior: "smooth" });
    } else {
      chromeScrollList(resultEl, index);
    }
  }, 200)
}
```

I think that it's the initial animation of [ResultList] that causes this. Looking into it more rn.
