### ISSUE TITLE
[SourceTree] Reveal in Tree does not work after we set a directory as root

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5287]
STR:
1. go to todomvc
2. add a directory as the root
3. cmd+p select another source
4. contextmenu select "reveal in tree"

ER: works
AR: doesn't :)

**Comment by AnshulMalik** [comment]
Hey @sravan-s, this might help, we changed the getDirectories function when we landed project roots.

Seems like I forgot to update every location where it was called from. The one I found causing problem here

```diff
diff --git a/src/components/PrimaryPanes/SourcesTree.js b/src/components/PrimaryPanes/SourcesTree.js
index 7243f1b0..e0a8667c 100644
--- a/src/components/PrimaryPanes/SourcesTree.js
+++ b/src/components/PrimaryPanes/SourcesTree.js
@@ -150,7 +150,8 @@ class SourcesTree extends Component<Props, State> {
     ) {
       const highlightItems = getDirectories(
         nextProps.selectedSource.get("url"),
-        sourceTree
+        sourceTree,
+        projectRoot
       );

       return this.setState({ highlightItems });
```

**Comment by AnshulMalik** [comment]
It'd be awesome if we update the tests for `getDirectories` function too :)

**Comment by sravan-s** [comment]
Thanks for the heads up ;)

**Comment by AnshulMalik** [comment]
And one more observation, you'll need to remove project root from `fullUrl` in `getDirectories`, [here](https://github.com/devtools-html/debugger.html/blob/master/src/utils/sources-tree/getDirectories.js#L37)

**Comment by sravan-s** [comment]
@jasonLaster @AnshulMalik  Quick discussion before implementing the thing - don't you guys think its a better idea to hide results from other directories if a specific folder is set as root?

**Comment by jasonLaster** [comment]
I would lean towards removing the root so that it is shown?

**Comment by sravan-s** [comment]
So... what would be the other significances of adding a directory root? (I'm kinda new here, is there anything I am missing?)

**Comment by jasonLaster** [comment]
it's still a new feature, so we've got to figure out the UX. I assume revealing a file out of the root is an edge case
