### ISSUE TITLE
[SourceTree] clicking on a directory does not toggle it

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5298]
Looks like clicking a directory in the source tree no longer toggles it. The reason for this is the tree always tells the item that the directory is expanded! It's lying :)

Here's the tree code in [question](https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-components/src/tree.js#L81-L100)

<img src='https://shipusercontent.com/5895c48a70cd62c8125d9b1aa1d344e3/Screen%20Shot%202018-02-02%20at%202.47.35%20PM.png' title='Screen Shot 2018-02-02 at 2.47.35 PM.png' width=697>

<img src='https://shipusercontent.com/7698d42edb8252570a4edc9e6b07785b/Screen%20Shot%202018-02-02%20at%202.46.34%20PM.png' title='Screen Shot 2018-02-02 at 2.46.34 PM.png' width=567>

**Comment by lukaszsobek** [comment]
Merged. Closing.
