### ISSUE TITLE
TARFU Intrusive Javascript Debugger Breaks Inspection

### ISSUE THREAD

**Issue by ClintonGallagher** [devtools-html/debugger.html#5300]
Firefox Developer Edition v59 (and earlier)    

- When Inspecting elements in a page refreshing the page (using browser or context menu) can cause Developer Tools to switch to the Javascript debugger tab and start debugging any Javascript loaded by the page. Returning to the Inspector tab pauses the Debugger but some features like mouse selection will not work.

- When Inspecting and clicking on an element in the page Developer Tools switches to the Javascript debugger tab and starts debugging any Javascript that may be loaded in the page.

The Debugger seems to have a mind of its own. Is there a logical workflow to avoid this anomaly when Inspecting elements in the page or what?

**Comment by jasonLaster** [comment]
Hey @ClintonGallagher could you give us some steps to reproduce this bug?

**Comment by ClintonGallagher** [comment]
Gave it a shot this morning and can consistently repeat the following:
// Repeatable
1. Load Page

2. Inspect an element on the page

3. Refresh the page (browser or context menu)

4. Tools switch to Debugger tab and load moz-extension:// onloadwff.js (perhaps my mistake for stating the Debugger attempts to debug script that was loaded by the page as it seems it is loading its own script into the Debugger tab.)

5. Reselecting Inspect tab moves to Inspect tab and displays message "Debugger is paused. Some features like mouse selection will not work."

6. Inspection is now disabled.

Comment:
When inspecting and confirming needed edits it is IMO a common habit to return to the IDE and modify a style for example and then refresh the page to observe results intending to continue where one left off while Inspecting. This workflow is broken. Perhaps it is needed but has been annoying for some time and perhaps is best avoided by using the Style Editor tab first but refreshing the page is a habit.

Furthermore, Firefox knows I came here and commented about it so it will not allow me to repeat other anomalies this afternoon that have been causing the Debugger to load while Inspecting. Typical.

**Comment by jasonLaster** [comment]
I'm moving the issue to the icebox. We will re-prioritize the issues in the icebox at the beginning of the next release in 6 weeks.
