### ISSUE TITLE
[Editor] Last few columns of editor are cut off.

### ISSUE THREAD

**Issue by mmcote** [devtools-html/debugger.html#5302]
If the code being debugged has lines long enough enable the horizontal scroll, and you attempt to scroll horizontally to the end of the editor, you see that the last few columns are missing. To be specific the last 30 px of the editor are missing.

Reproduce: 
- Debug a file that has lines long enough to enable the horizontal scroll.
- Try scrolling to the rightmost column of the editor. 
- Observe that your longest line of code will be missing a few columns.

![02beforehorizontalcutoff](https://user-images.githubusercontent.com/14250545/35754155-a7d244b2-081f-11e8-94b6-ec26bca39e0e.gif)

**Comment by mmcote** [comment]
Hey @lukaszsobek, do you mind if I take this bug on, as I was actually working on this prior and found the source of the problem, I was just waiting for the issue to be claimable. Sorry for the trouble :)

**Comment by lukaszsobek** [comment]
@mmcote Sure thing, go ahead! /unclaim

**Comment by mmcote** [comment]
Thank you @lukaszsobek
