### ISSUE TITLE
[Debugger] Middle mouse wheel clicking on the opened tabs should close them

### ISSUE THREAD

**Issue by tommai78101** [devtools-html/debugger.html#5323]
This is a feature suggestion.

When viewing JavaScript source codes in the Debugger, usually, you would mouse over the X (close button) on the right side of the opened tabs to close them. A tiny feature enhancement would be to make it also allow users to middle-mouse-wheel click on the tabs to close them.

![](https://i.imgur.com/9rVlFCG.png)

**Fig 1: Middle mouse wheel clicking on the cherries would close the opened tabs.**

In Chrome DevTools, you can close opened tabs with middle mouse wheel clicks.

Any thoughts / opinions on this?

**Comment by lukaszsobek** [comment]
I've seen middle wheel or double click in various applications - assuming everyone has a middle wheel on their mouse these days.
