### ISSUE TITLE
"No result found" label breaks on letter while there's plenty of space

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#5324]
Steps to reproduce:
1. Go to data:text/html,<script>var hello;</script>
2. Open the debugger
3. Search in files ( Cmd + Shift + F ) for "boo"

Expected results:

The "No result found" label is displayed, and word wraps to a new line when needed

Actual results:

![image](https://user-images.githubusercontent.com/578107/35863811-208a80e4-0b50-11e8-8aab-23ae244cca1a.png)

The words break on letters while there's plenty of space to break on word. At worst, I expect hyphens at the right spot.

**Comment by ericawright** [comment]
fixed with #5359
