### ISSUE TITLE
Cmd+P keyboard shortcut for Windows

### ISSUE THREAD

**Issue by jbhoosreddy** [devtools-html/debugger.html#533]
Currently, the keyboard shortcut to toggle file search is (Cmd+P) which works perfectly on OSX. But I suspect, it will not work Windows as it does not have the Cmd key.
We need to add additional listener for the corresponding Windows key shortcut (Ctrl+P) to toggle file search.
We should also modify the welcome screen copy to reflect that change for Windows users.
<img width="288" alt="screen shot 2016-08-10 at 11 41 40 pm" src="https://cloud.githubusercontent.com/assets/2481105/17580332/b97b612a-5f52-11e6-8df4-591e3c57f4fe.png">
thoughts @jasonLaster?

**Comment by jlongster** [comment]
I thought this was solved by the key shortcuts library?

**Comment by jasonLaster** [comment]
I think it is. I agree we should update the copy to say ctrl on Windows
though.

**Comment by wldcordeiro** [comment]
Not windows but on Linux (Kubuntu 16.04) the shortcut isn't working so the copy needs updating and maybe the shortcut itself. I'm down to look into this. 👍

**Comment by wldcordeiro** [comment]
So this line uses `Cmd+P`
https://github.com/devtools-html/debugger.html/blob/master/public/js/components/App.js#L56

however in the `key-shortcuts.js`
https://github.com/devtools-html/debugger.html/blob/master/public/js/lib/devtools-sham/client/shared/key-shortcuts.js#L114 there's a `CommandOrControl`/`CmdOrCtrl` that should be used (also should we even have the if block for `Cmd` alone?) So the solution to getting the shortcut working is easy. However, the message, is there a simple way for me to get the platform? Then I can just make the message show what is needed.

**Comment by jasonLaster** [comment]
I think the best you can do now is to check to see if it's a mac:

> Is there a simple way for me to get the platform?

```js
const { Services } = require("Services");
const isOSX = Services.appinfo.OS === "Darwin";
```

Thanks for the help! Let me know if you have any questions, if you want to say hello stop by our [irc](https://github.com/devtools-html/debugger.html#discussion) room to say hello.

**Comment by jbhoosreddy** [comment]
@jasonLaster I was just typing the same thing. 👍

**Comment by wldcordeiro** [comment]
#586 brought this in.

**Comment by jasonLaster** [comment]
Thanks @wldcordeiro!
