### ISSUE TITLE
[Scopes] Listing hover background is off

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5331]
There is a weird left margin in the scopes listing that we should fix.

<img width="329" alt="scopes-pad" src="https://user-images.githubusercontent.com/46655/35881374-38141374-0b46-11e8-8d05-0f848992ee60.png">

**Comment by jasonLaster** [comment]
Hows it going @pradeepgangwar?

**Comment by subCode321** [comment]
i wanna contribute

**Comment by pradeepgangwar** [comment]
@subCode321 This issue is fixed now.
