### ISSUE TITLE
[Outline] Alphabetize function list (?)

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5333]
This pane seems like it would be much easier to use if the functions were alphabetized.  

With functions listed in order of use, it's really hard to find anything.

<img width="252" alt="outlinelisting" src="https://user-images.githubusercontent.com/46655/35891779-8d001c28-0b6b-11e8-8747-54309ed95cd4.png">

**Comment by jasonLaster** [comment]
yeah - i think that's right...

i've toyed with a filter input at the top too, but i think this is the right next step

**Comment by brabadu** [comment]
Many developers use eslint config, which forces some particular order of functions. e.g. by lifecycle in React components. So alphabetizing this list may confuse some devs

**Comment by lukaszsobek** [comment]
In a huge list of functions it seems to take much less time for the user to find what they are looking for in alphabetical order. Even if we grouped functions by class (which might be in order of appearance) reading the functions inside that class sorted alphabetically would probably take less time than the alternative.

**Comment by codehag** [comment]
How about we allow users to sort the list, rather than enforcing a particular order?

this can be done with a checkbox for now that looks like this

[] alphabetize

and then we sort them. if its unchecked they appear in the order that they are found in the code

**Comment by nyrosmith** [comment]
I wouldn't try to be smarter than the author of the code. I'd show the content of the source in the same order in the outline. Everything else would be confusing especially if I inspect my own source (I know the order more or less)
I am currently sketching such an solution so we can discuss on that

**Comment by AnshulMalik** [comment]
I am with @nyrosmith , It would be more sensible if the names show up in same order as defined in the code

**Comment by jasonLaster** [comment]
I think i've been persuaded to let the list stay in the original order...

re: a checkbox, I would prefer to have a settings pane where it can be set rather than a UI element that is always visible.

**Comment by nyrosmith** [comment]
/claim
I am already working on a new Outline which keeps order
