### ISSUE TITLE
[Docs] Add algolia search

### ISSUE THREAD

**Issue by s-pace** [devtools-html/debugger.html#5338]
👋 team,

First all a tons of thank you for such tool. We were at FOSDEM 2018 and we were delighted to see the nice presentation.

I use your user guide and I couldn't help providing you [a great search experience for your incredible documentation](https://community.algolia.com/docsearch/).
![Enhance search experience](https://cl.ly/3A0U002e1k28/download/Screen%20Recording%202018-02-07%20at%2004.58%20PM.gif)

You can attach it to any input of your choice. I let you integrate it as you want. Ping me if you need a hand:

Congratulations, your search is now ready!
I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:
- Copy the following CSS/JS snippets and add them to your page
```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />
<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: 'a6b8766ba29d14a94923259734c3b342',
  indexName: 'firefox_debugger_html',
  inputSelector: '### REPLACE ME ####',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```
- Add a search input if you don't have any yet, and update the inputSelector value in the code snippet to a CSS selector that targets your input field.
- Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/documentation/)
- You can also check your configuration in the github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/firefox_debugger_html.json). Feel free to open pull requests!

Feel free to get back to us if you have any issues or questions regarding the integration.
We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it.

Have a nice day :)

**Comment by jasonLaster** [comment]
Wow @s-pace! This is amazing

We've got to set this up :)
Perhaps this is the push we need to have a better docs page!

**Comment by s-pace** [comment]
Thank you, would love to help!

**Comment by jasonLaster** [comment]
Oh wow. Yeah - the rough goal is to move to netlify so we can have more control over the docs.

We have this issue to make an MVP docs site with Gatsby or Docusaurus. Because at the moment we just have markdown i'd be happy with the simplest thing that we can then use.
https://github.com/devtools-html/debugger.html/issues/5047

**Comment by s-pace** [comment]
👋 @jasonLaster,

If you want to try it in the meanwhile, I have bootstrap you a showcase in 2 sec:

http://debugger-docsearch.surge.sh/

We could even integrate it. We do provide analytic on top of it :) 🦊

**Comment by jasonLaster** [comment]
@s-pace this is blocked on me not knowing how to add it to our existing github-pages docs...

Do other do this now with a template integration or something else?

**Comment by s-pace** [comment]
No, they only integrate the snippets on their html pages I guess.

If you can't find a wait, ping me and I will have a look with the team / ask others that have done it easily.

**Comment by jasonLaster** [comment]
we use the standard template, so not sure how to do this. We should be a pretty common case. 

I'd be happy to suck in a different template that has algolia built in :)

**Comment by s-pace** [comment]
Do you have access to some HTML?

If so, yo will only need to add the required includes.

Keep me posted @jasonLaster

**Comment by jasonLaster** [comment]
@s-pace We don't. We're just using the standard github pages template<img src='https://shipusercontent.com/72e486e251db2352ea3c19436644aa39/Screen%20Shot%202018-03-25%20at%207.25.02%20PM.png' title='Screen Shot 2018-03-25 at 7.25.02 PM.png' width=774>
