### ISSUE TITLE
improve the design of the initial pause state of the debugger

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#534]
Coming out of the discussion in #261 I believe this is the higher priority story to tell.

When the debugger pauses initially we need to grab the users attention to explain the story of what, where, and why.  
- What happened?
  - The page paused.
- Where
  - In the Editor, the line
- Why
  - ?

**Comment by jasonLaster** [comment]
@jlongster I know you made some progress on this issue a couple of weeks ago. Where does this stand now?

**Comment by jlongster** [comment]
I don't think I worked on anything related to this. We've talked about having an overlay on the page when the debugger is paused which we should do. Makes it clear that it's paused. For the debugger UI itself I think it's fine the way it is.

**Comment by clarkbw** [comment]
Closing this out for now, we'll open this up again as a user story later.
