### ISSUE TITLE
Don't show 'Set Directory Root' context menu item for `(index)`

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5340]
Clicking on that context menu item for `(index)` changes the source pane to show `No Sources`

**Comment by AnshulMalik** [comment]
I don't see `Set root directory` in context menu instead, I only see `Copy Source URI`. 

Can you please add STR?

**Comment by darkwing** [comment]
@AnshulMalik I fixed it last week.  We can close :)
