### ISSUE TITLE
[SourceTree] Add `Copy Source to Clipboard` functionality to context menu

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5341]
May also be good for the tab context menu as well.

**Comment by codehag** [comment]
Can you describe this a bit more?

**Comment by darkwing** [comment]
I started this PR but it's not a priority so it would be a good contributor opportunity;

https://github.com/devtools-html/debugger.html/pull/5349

**Comment by jasonLaster** [comment]
@zeoneo how's it going?

**Comment by zeoneo** [comment]
@jasonLaster I started working now. Will get back to you in case of difficulties
