### ISSUE TITLE
[Outline] Add "Copy Function" context menu item to functions

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5352]
@jasonLaster added a "Copy function" context menu item to the editor source pane.  It would be cool if we added a context menu for Outline pane functions to do the same thing.

**Comment by codehag** [comment]
would this copy the function in the outline in their entirety? that would be interesting!

**Comment by jasonLaster** [comment]
Nice idea!

**Comment by AnshulMalik** [comment]
I am unclaiming this as this can be a good issue for new contributor, feel free to claim it :)

Here is my branch, it might help
https://github.com/AnshulMalik/debugger.html/commit/bfe6583fefd3ab98f0983a88d58c8b93d90f908b

**Comment by AnshulMalik** [comment]
unclaim

**Comment by escaton** [comment]
@darkwing could you close this issue please?
