### ISSUE TITLE
Inactive "+" in Breakpoints Pane should be greyed out

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5355]
If the "+" isn't active, it should be the same grey color as the watch expressions refresh icon.

<img width="303" alt="inactivebreakpoint" src="https://user-images.githubusercontent.com/46655/35956329-91f907d6-0c5a-11e8-84ed-e2392c665eda.png">

**Comment by jasonLaster** [comment]
@darkwing can you add more context as to why the "+" is blue. I know we color it if there is an active pause on exception selected. Are there other reasons?

By the way, we *do* want to re-think this new UI. It's currently disabled in firefox now

**Comment by jasonLaster** [comment]
take a look :)

**Comment by tripurari001** [comment]
@jasonLaster  @darkwing 
it may not be a bug because because it's in highlighted color only when `pause on all exception` or `pause on uncaught exception` is selected otherwise it is grey

**Comment by jasonLaster** [comment]
> I can't toggle (unselect) pause on next exception once it's selected

yep - that's logged in another issue

**Comment by darkwing** [comment]
I may have misunderstood what state I was in when I filed this issue, so it may not be relevant.  Let's focus on the toggle issue for now

**Comment by tripurari001** [comment]
so I should unclaim here right ??
:)

**Comment by darkwing** [comment]
Closing this as invalid.
