### ISSUE TITLE
[Search] 2 search bars, one does not work, the other is not focused

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#5366]
![screenshot](https://user-images.githubusercontent.com/7477678/35996288-67bfd4b0-0d16-11e8-9567-1904a8c1cd9b.png)

When I press Ctrl+F to search something, a 2nd search bar appears below the real one. And this extra bar does not seem to work properly. The one that works is not focused by Ctrl+F, I must click it manually.

So search is so broken.

**Comment by jasonLaster** [comment]
hm, can you check the browser console?

also do you have any plugins. this is the source editor search showing up.

@gabrielluong did we touch the source editor recently?

**Comment by Loirooriol** [comment]
Regressed by https://bugzilla.mozilla.org/show_bug.cgi?id=1432842

It seems the first time I use Ctrl+F the proper search bar opens, but other uses open the other search bar.

No errors in the browser console, reproducible in clean profile.

![screencast](https://user-images.githubusercontent.com/7477678/35998178-28037524-0d1c-11e8-9f8e-a1754deaaa55.gif)

**Comment by jasonLaster** [comment]
nice find. also i love the keyboard!

**Comment by darkwing** [comment]
I could not reproduce this on my Windows 10 machine.

**Comment by jasonLaster** [comment]
@Loirooriol is this an issue for you on nightly now?

**Comment by Loirooriol** [comment]
Yes, on latest nightly ea3da643422c58d65335f1778dd6c89c09911585

**Comment by jasonLaster** [comment]
@darkwing was testing in the launchpad. We'll now verify in the panel.

**Comment by darkwing** [comment]
I finally got edge debugger working in a Firefox build and can confirm that this is happening. :(

**Comment by darkwing** [comment]
A few additional notes:

* On edge build for Windows:  One Ctrl+F shows the "Search in file" bar but doesn't focus on the input, another Ctrl+F does nothing, then another Ctrl+F shows the second search box, this time focusing on it.

* On LaunchPad for Windows:  Everything works as intended: only the "Search File" box displays and the focus is set properly every time.

* On edge build for Mac:  Everything works as intended: only the "Search File" box displays and the focus is set properly every time.

*

**Comment by jasonLaster** [comment]
Nice writeup!

Here is a useful link to start looking for inconcistencies
https://github.com/devtools-html/debugger.html/blob/master/src/utils/editor/create-editor.js#L15-L32

you can either make changes here and run `node ./bin/copy-assets` w/ the right flags

or just debug here

https://searchfox.org/mozilla-central/source/devtools/client/debugger/new/debugger.js#49123
