### ISSUE TITLE
Set as Root Directory & Reveal In Tree Conflict

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5401]
If you open a few sources, then set a very specific root, then use the Reveal In Tree context menu to find a broad source, you're searching for a source that theoretically isn't in range.

When a user chooses "Reveal In Tree" on a source that isn't in a modified Reveal in Tree root, I believe we should revert the tree root to the overall overall root and highlight the intended source.

**Comment by jasonLaster** [comment]
this is being done in #5287
