### ISSUE TITLE
[Editor] Preview tooltip can get stuck in visible state when mouse leaves code window too fast

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#5406]
STR:

- Pause on a larger code base
- Quickly hover a variable and move mouse out of code panel before tooltip appears (made easy by it being slow on large code cases, see #3984)

AR: Tooltip stays open until mouse re-enters code panel

ER: Tooltip never appears or closes when mouse leaves

Maybe the fix is improving performance; but we'll see Telemetry if we hit a level that would mitigate the issue described here.

**Comment by jasonLaster** [comment]
How is it going @haoRchen?

**Comment by haoRchen** [comment]
@jasonLaster progressing. I have found the mouseover() call within the editor canvas
![10 - possible mask](https://user-images.githubusercontent.com/19397242/37311862-5325c092-261f-11e8-88cd-f5a0b292c3ee.png)
as well as the mouseleave() within the popover
![11 - onmouseleave popover](https://user-images.githubusercontent.com/19397242/37311875-5feb88ca-261f-11e8-8ec0-f13e88736ebe.png)
Manually testing mouseover() is a bit troublesome as it rarely registers the debug variable for creating the popover, the event gets triggered when I move my cursor onto the editor; which will process another element as the target of the mouseover(). eg. the scroll bar UI as shown below
![12 - debugging mouseover](https://user-images.githubusercontent.com/19397242/37312565-e172fc14-2621-11e8-935c-def996d533fe.png)

Will be looking into mouseleave() shortly.

Any advice?

**Comment by jasonLaster** [comment]
Hmm, sometimes when this is the case, I cheat and add a new condition that is only true when i type a letter like "f" :) you can do this with a new keyDown event.

I'll defer to @darkwing, or @wldcordeiro who are great w/ the UI

**Comment by jasonLaster** [comment]
how's this going @haoRchen?

**Comment by haoRchen** [comment]
@jasonLaster  I'm having trouble getting past the editor mask. 
Using your suggested method, pressing "A" on top of the variable grabs nothing as the target:
![17 - target for onkeydown](https://user-images.githubusercontent.com/19397242/37543507-3e17466e-2938-11e8-8b5e-26c941f87754.png)
I am going to see if this issue was introduced in an earlier release via git bisect.

**Comment by jasonLaster** [comment]
Thanks @haoRchen nice work so far. I pinged the core team to see if someone could help mentor

**Comment by haoRchen** [comment]
I did a git bisect and discovered that this behavior began with release v10.0 a635124 on January 25th, 2017. Compared to v9.0 0de8d3f on January 12th, the preview tool-tip was able to self-adjust to appear above and below the debug line. Will look further into this.

**Comment by jasonLaster** [comment]
@haoRchen any luck here? I'm going to open this bug up for others so we can get some additional eyes on it.

**Comment by dimitardanailov** [comment]
Greetings, 

> Pause on a larger code base

Which is the best project for this requirement ?

cc: @haoRchen @digitarald

**Comment by jasonLaster** [comment]
closing as a dupe of #6193
