### ISSUE TITLE
[Infrastructure] Windows Error: "missing = in const declaration"

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5408]
I tried getting the debugger running on a Windows PC today.  After installing yarn, cloning the repo, and do a `yarn start / yarn run firefox`, I go to localhost:8000 and see the following error:

```
SyntaxError:  missing = in const declaration
```

The source at said point is:

```
function firstString(...args) {
    for (const arg of args) {
        if (typeof arg === "string") {
            return arg;
        }
    }
}
```

I think we're missing a dependency in package.json that we've all taken for granted

**Comment by AlexisDeschamps** [comment]
I tried a clean clone and setup with node v9.3.0 on latest Windows 10 and I did not get any errors. Of course, I may already have some other dependency as you suggested. Maybe the browser you visited localhost:8000 did not have some of the latest ECMAScript features?

**Comment by darkwing** [comment]
Turns out my Firefox didn't update to current, it went from 48 -> 56 -> 57 -> 58, so I didn't have the most up to date stuff.  This isn't an issue, just an old browser.
