### ISSUE TITLE
Hide "file modal" when pressing Cmd + Shift + F

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#5416]
Steps to reproduce:
1. Open this page
2. Hit <kbd>Cmd</kbd>+<kbd>P</kbd> (this should show the file modal)
3. Hit <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> (this start the search in project)

Expected results:
The file modal is dismissed and I can type what i'm searching for

Actual results:
The search UI appears underneath the file modal, which is still visible: 

<img width="829" alt="screen shot 2018-02-14 at 08 03 17" src="https://user-images.githubusercontent.com/578107/36191509-dfcc0d70-115d-11e8-9c8b-ed57cd0de0df.png">

---

We should hide the modal when showing the search UI.

**Comment by lukaszsobek** [comment]
Merged. Closing.
