### ISSUE TITLE
Can't distinguish active state on project explorer dropdown

### ISSUE THREAD

**Issue by gregtatum** [devtools-html/debugger.html#5420]
## Steps to reproduce:
 * Open debugger on a project
 * Hit Cmd+P
 * Type in a search
 * Move mouse over second term

## Actual behavior:

It's impossible to distinguish between the active state of the first term, and the hover state of the second. So I don't know which item is selected.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/1588648/36224775-3071bec0-118e-11e8-8dec-c28790c6e6a8.png">

In addition, the color is so light I had trouble visually even seeing that something was highlighted.

## Expected behavior

The photon design system uses a bright blue to show active state in the drop down in the URL bar.

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/1588648/36224948-b3206830-118e-11e8-8dfc-42bd3bd3a2a6.png">

**Comment by jasonLaster** [comment]
Thanks @gregtatum. @nchevobbe filed the same thing recently here #5034
