### ISSUE TITLE
[QuickOpen] selected source is not visible 

### ISSUE THREAD

**Issue by gregtatum** [devtools-html/debugger.html#5421]
## Steps to reproduce:

* Open a few files in the debugger.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/1588648/36225200-86a6eb8e-118f-11e8-98b4-caef3f18e6ce.png">

* Hit Cmd + P and type in a search term for a file not in the list.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/1588648/36225235-a059c2c2-118f-11e8-8159-935018f47d27.png">

* Use enter to load the the file.

## Expected behavior

The file is loaded and brought to the front of the tabs

## Actual behavior.

The file is loaded, but it is in the background still.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/1588648/36225288-ceaf85b2-118f-11e8-974a-970c3b1f3bc2.png">

**Comment by jasonLaster** [comment]
weird is this perf.html?

could you give a clearer STR? 
also love the watch expressions

**Comment by gregtatum** [comment]
It's not reproducing now. This was using perf.html. I was having some occasional runtime errors where things would totally break during my long debug sessions, so perhaps something funky happened to the state of the application.

**Comment by jasonLaster** [comment]
oh strange. alright. closing, lets re-open if we have a case that repros consistently
