### ISSUE TITLE
Pause on caught exceptions impossible to distinguish

### ISSUE THREAD

**Issue by gregtatum** [devtools-html/debugger.html#5422]
## Steps to reproduce:

* Click on the pause exceptions button multiple times

## Expected behavior:

* I understand what state the debugger is in regards to breaking on thrown exceptions, breaking on caught thrown excpection, and not breaking.

## Actual behavior:

I don't have any visual feedback as to what state the debugger is in. I can't distinguish the colors on the icon, and I believe there are 3 potential states for the button, but I don't understand what they are.

<img width="156" alt="image" src="https://user-images.githubusercontent.com/1588648/36225414-359aa414-1190-11e8-94a9-4daa67946086.png">

**Comment by jasonLaster** [comment]
I agree. Our current design is highlighted in this bug #4109. I think we're going in the direction of textual labels that make it clearer what the states are. It's just a question of where they live.
