### ISSUE TITLE
Stepping buttons disappear when shrinking debugger window

### ISSUE THREAD

**Issue by gregtatum** [devtools-html/debugger.html#5423]
# Steps to reproduce:

* Open up the debugger in devtools on the right.
* Ensure that devtools is small enough so that the stepping buttons are on the bottom of the debugger
* Shrink the vertical size of the debugger.

![STR](https://media.giphy.com/media/3oxQNzW2rZD6ndNCkE/giphy.gif)

# Actual behavior

* The stepping buttons disappear once the window is small enough, making it impossible to step when a debugger statement is hit.
* Try to click on either the devtools' horizontal splitter (between the debugger and console) or the debugger's internal splitter. It's almost impossible to click and get it right.

# Expected behavior

The stepping buttons should always be visible. and provide a clear separation of the two splitters.

**Comment by jasonLaster** [comment]
here are some docs for debugging the [panel](https://github.com/devtools-html/debugger.html/blob/master/docs/debugging-firefox.md)

it'd be fun to simulate this effect in the launchpad too. but less important

**Comment by darkwing** [comment]
Reproducing this bug is difficult.  I'm seeing desired functionality:

![toolsoverlap](https://user-images.githubusercontent.com/46655/36994944-532eecc8-2078-11e8-9129-52dd173ac2f8.gif)

Will keep looking though

**Comment by jasonLaster** [comment]
Yeah, that's really strange.

**Comment by gregtatum** [comment]
Just chiming to say that it works on my end now too 🎉
