### ISSUE TITLE
[Scopes] Scope nodes are a bit too similar to "regular" variable nodes

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#5426]
The Scopes groups variables under "Block" nodes. Sometimes they are named, which is great.
But it's hard to distinguish those "blocks" node from the "variable" nodes. See: 

<img width="455" alt="image" src="https://user-images.githubusercontent.com/578107/36247277-ba1e04d0-1233-11e8-8d7b-279a1b81dc30.png">

They are of the same color as variable names, and I feel like we could find something different for these top-level nodes.
We could start with having a different color, or maybe a background color, or an icon, … to they stand out from the other nodes.
This way you can quickly distinguish them when you have multiple block and variables expanded.

What do you think ? poke @violasong , @ericawright

**Comment by jasonLaster** [comment]
Yep, I agree!

**Comment by violasong** [comment]
I don't understand this enough to suggest a very specific solution, but in general, using the photon purple as a secondary color to differentiate from the blue seems like a good idea!

**Comment by nchevobbe** [comment]
Here's how it could look:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/578107/36368637-7d33eeea-1558-11e8-980e-e891422dadc4.png">

I added an icon because with only the color change, it felt a bit dull.
The icon shouldn't be on the `Window` object, but for now, we don't have a classname to target these "Block" nodes (I think we should have one).

Thoughts @codehag @jasonLaster @violasong ?

**Comment by codehag** [comment]
i like it! i think the icon really adds something

**Comment by nchevobbe** [comment]
If someone wants to work on this, here's a starting point: 

```diff
diff --git a/src/components/SecondaryPanes/Scopes.css b/src/components/SecondaryPanes/Scopes.css
index bcae688a..d20aa0ce 100644
--- a/src/components/SecondaryPanes/Scopes.css
+++ b/src/components/SecondaryPanes/Scopes.css
@@ -18,6 +18,14 @@ html[dir="rtl"] .object-node {
   color: var(--theme-highlight-blue);
 }
 
+.tree-node[aria-level="0"] .object-label {
+  color: var(--theme-highlight-red);
+}
+
+.tree-node[aria-level="0"] > .node:not(.lessen) .object-label:before {
+  content: "☲ ";
+}
+
 .objectBox-object,
 .objectBox-string,
 .objectBox-text,
```

Note the `> .node:not(.lessen)` to prevent targetting the global window. Not sure if this is the way to go. I'd rather have a property on the scope so we can add a className in the ObjectInspector code.
But for now, that could be enough ?

**Comment by jasonLaster** [comment]
Looks nice!

I wonder if some vertical margins or larger font would help scopes as well.

**Comment by nchevobbe** [comment]
I tried a bit but it looks weird in regards with the other nodes.

![image](https://user-images.githubusercontent.com/578107/36381048-ad12056c-1584-11e8-9383-8a2552420c7d.png)


![image](https://user-images.githubusercontent.com/578107/36381112-d9a386e6-1584-11e8-9b34-b7b5673954da.png)


Here's in bold 

![image](https://user-images.githubusercontent.com/578107/36380998-89566e88-1584-11e8-8d83-db0d383214f7.png)

**Comment by jasonLaster** [comment]
true, bold is nice. Ship it!

**Comment by nchevobbe** [comment]
:) We need to make a change in the objectInspector to allow it to receive a given className for a node so we can target "Blocks" and not the Window (looking for `:not(.lessen)` does not work since the classname is removed when expanding the window node).

**Comment by violasong** [comment]
Love the icon! If I'm understanding this correctly, I would suggest the gray90 color plus bold weight, to make it look more like a heading, of higher hierarchy than the blue - the magenta provides a nice contrast but is more like a highlight color.

**Comment by jasonLaster** [comment]
@violasong that makes sense. Ideally we'll do more with the information as well to make it clearer. We're fixing some bugs so that we have fewer scopes and i'd like to do more work to simplify the scopes & names of the scopes we show

**Comment by nchevobbe** [comment]
Here's a version with a WIP PR on the Reps side, with colors indicated by @violasong 

<img width="285" alt="image" src="https://user-images.githubusercontent.com/578107/36990149-01b1e2ca-20a4-11e8-8abb-0c4fd5a606e2.png">

**Comment by jasonLaster** [comment]
@nchevobbe could you share the same version with some scopes expanded. 

My initial thought is that might be too dark because it's darker than the accordion pane header.

**Comment by nchevobbe** [comment]
Yes, I agree: 

<img width="489" alt="image" src="https://user-images.githubusercontent.com/578107/37020178-379747f0-211b-11e8-8a94-20b749eed1d5.png">

Here's with non-bold blocks: 

<img width="437" alt="image" src="https://user-images.githubusercontent.com/578107/37020217-583f1564-211b-11e8-9c05-2450dd63a6c9.png">

Here's with the same color as the accordion headers: 

<img width="391" alt="image" src="https://user-images.githubusercontent.com/578107/37020306-9d4f449e-211b-11e8-8437-dde97b73e7c2.png">

and in bold: 

<img width="398" alt="image" src="https://user-images.githubusercontent.com/578107/37020330-b25600b2-211b-11e8-908b-086b6db419e7.png">

**Comment by nchevobbe** [comment]
Here's what's needed on the debugger side: 
```diff
diff --git a/src/utils/pause/scopes/getScope.js b/src/utils/pause/scopes/getScope.js
index e14d6aaa..4fc5625d 100644
--- a/src/utils/pause/scopes/getScope.js
+++ b/src/utils/pause/scopes/getScope.js
@@ -3,6 +3,7 @@
  * file, You can obtain one at <http://mozilla.org/MPL/2.0/>. */
 
 // @flow
+import { ObjectInspectorUtils } from "devtools-reps";
 import { getBindingVariables } from "./getVariables";
 import { getFramePopVariables, getThisVariable } from "./utils";
 import { simplifyDisplayName } from "../../frame";
@@ -81,7 +82,8 @@ export function getScope(
       return {
         name: title,
         path: key,
-        contents: vars
+        contents: vars,
+        type: ObjectInspectorUtils.node.NODE_TYPES.BLOCK
       };
     }
   } else if (type === "object" && scope.object) {

```

**Comment by jasonLaster** [comment]
Great. Thanks

**Comment by violasong** [comment]
Ah yes, I agree the bold is too loud. Thanks for the extra screenshots! I think we can stick with that standard pane color that's same as the accordion headers, and maybe just make the icon larger — e.g. same size as the source tree icons. I'd love to borrow more styling from the source tree in general - e.g. the slightly smaller text and slightly more line spacing will make this look a lot nicer.

**Comment by nchevobbe** [comment]
PR up https://github.com/devtools-html/devtools-core/pull/983 :)

![image](https://user-images.githubusercontent.com/578107/37088773-be52ed42-21fe-11e8-9883-433d3e5d13da.png)

**Comment by jasonLaster** [comment]
This was fixed in the latest Reps version

**Comment by nchevobbe** [comment]
This still need some work on the debugger side. I'll put a PR up when I release the new reps version (this week)
