### ISSUE TITLE
[QuickOpen] "Go to line" as documented by the help panel seems broken

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#5427]
Steps to reproduce:
1. Go to http://firefox-dev.tools/debugger-examples/examples/todomvc/
2. Open the debugger
3. Open the `todo-view.js` file
4. Trigger the "Go to line" with <kbd>Cmd</kbd>+<kbd>;</kbd>

Expected results:

I can go to line 120 by typing `120` and then <kbd>Enter</kbd>

Actual results:

I'm welcomed with a sad red face: 
<img width="283" alt="image" src="https://user-images.githubusercontent.com/578107/36247663-2601b40c-1235-11e8-86f1-119648abd8cd.png">

Which is weird to start with.
Then if I type `120`, sad red face is still not happy 

<img width="131" alt="image" src="https://user-images.githubusercontent.com/578107/36247692-4092cb30-1235-11e8-964d-e3804bd22288.png">

I figured out that I should leave the colon, I still have the sad face, but at least <kbd>Enter</kbd> navigates me to the correct line

<img width="114" alt="image" src="https://user-images.githubusercontent.com/578107/36247731-6b035736-1235-11e8-9325-919f0ab25566.png">

---

The whole process should be smoother:
- if the user triggered the "go to line" shortcut, the colon shouldn't be editable (or at least, it should not be automatically selected)
- I should be prompted to enter a line number so I don't feel like something is broken
- I shouldn't see a sad red face, unless I type a line number not existing in the file
- I should only be able to type digits

**Comment by lukaszsobek** [comment]
Can't reproduce the error:
![goto](https://user-images.githubusercontent.com/23530054/36250693-dac1cf7c-123e-11e8-883d-e2f526a7e6ea.gif)

**Comment by nchevobbe** [comment]
For the record, it was on Nightly, so things might have been fixed in the meantime.
I still think we should have a better hint for the user to indicate they can type a line number. Even if `:` is used in many IDEs, I don't think it sufficient.

**Comment by lukaszsobek** [comment]
@nchevobbe - Making the hint more visible sounds like a great idea, any chance you could open a new separate issue for that so it doesn't get lost among all the things mentioned in this issue?

**Comment by nchevobbe** [comment]
@lukaszsobek sure https://github.com/devtools-html/debugger.html/issues/5443

**Comment by lukaszsobek** [comment]
Remaining item extracted into separate issue. Closing.
