### ISSUE TITLE
A "copy" button in the Preview popup would be helpful

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#5429]
This would be great to have a "copy" button in the preview popup that would basically do what `copy(obj)` does in the console.
This way you could have a json stringified version of the variable you are inspecting (or if it is a primitive, the primitive itself)

**Comment by jasonLaster** [comment]
@kootoopas i'm not sure what the correct ux is for this yet.

**Comment by jasonLaster** [comment]
Lets wait until we can rope in ux and discuss preview because this is also related to save to watch expressions.

**Comment by kootoopas** [comment]
@jasonLaster Gotcha. I was completely unaware of watch expressions. I haven't found a use case for them yet, since it seems that you can only watch globally accessible ones (?). :/

**Comment by jasonLaster** [comment]
I'm moving this to the icebox, we will re-evaluate at the beginning of the next release planning process.
