### ISSUE TITLE
Testing - add a simple mochitest

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#543]
+ Enables the `new-debugger-frontend` pref
+ go to an example page
+ adds a breakpoint
+ pauses

**Comment by jlongster** [comment]
How is this different from #537?

I also filed https://bugzilla.mozilla.org/show_bug.cgi?id=1294686 because things related to m-c should be in bugzilla to integrate with everything else. This issue if fine too, but will probably require some m-c patches as well.

**Comment by jasonLaster** [comment]
haha - it's not. oops
