### ISSUE TITLE
[QuickOpen] "Go to line" should have a better hint

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#5443]
At the moment, when you hit <kbd>Cmd</kbd>+<kbd>;</kbd> , you are prompted with an input containing a colon, without much more information.

We could have a better hint for the user (a placeholder, a label, …)

**Comment by wldcordeiro** [comment]
This is a little harder just because if we put a `:` in the input the placeholder is cleared, but it should be doable and would be a nice UX enhancement.

**Comment by marvinkome** [comment]
Since it also uses the SearchInput component. I was thinking we add "Go to line" in the place where "Loading ..." or close button will be
