### ISSUE TITLE
Does debugger.html requires Node 6.9 or 7?

### ISSUE THREAD

**Issue by ochameau** [devtools-html/debugger.html#5445]
The documentation tells us to use at least version 7 of Node
  https://github.com/devtools-html/debugger.html/blob/master/docs/getting-setup.md
While package.json ask for 6.9:
  https://github.com/devtools-html/debugger.html/blob/master/package.json#L15
(BTW, does npm checks that and warn if node version is incorrect?)

I'm currently trying to clarify npm worflows in m-c for console/netmonitor and would like to align to whatever version is required for debugger.html.

**Comment by jasonLaster** [comment]
i think the debugger requires 7x and the docs should be changed
