### ISSUE TITLE
[mochitest] Add a test for pause on next

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5446]
We should add a mochitest for pause on next.

It can be similar to this test: 
https://github.com/devtools-html/debugger.html/blob/release-17/src/test/mochitest/browser_dbg-breaking.js#L1

Basically go to a page, click the pause button, then eval a function, assert we're paused

**Comment by AlexWang-16** [comment]
I've claimed this issue, but I also see that @lukaszsobek has claimed this issue previously. The issue currently indicates it is not in progress, hence my claim. I want to confirm that I haven't jumped on top of someone else already working on this issue. Is it still good for the taking?

**Comment by jasonLaster** [comment]
@AlexWang-16 it's all yours

**Comment by AlexWang-16** [comment]
Thanks for the tips. I've tried to replicate pausing the debugger by hand and I can't seem to get it into the state where I can click the pause button. What's the best way to do this?

![no-pause-button](https://user-images.githubusercontent.com/13398997/38844757-e71b28f0-41c2-11e8-8423-74c28b4d7145.gif)

**Comment by jasonLaster** [comment]
oh interesting... this must be true for you remove-command-bar-options

check with dbg.features
