### ISSUE TITLE
[SourceTree] directory root can cause the tree to show no sources

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5447]
When a directory root does not match, the user sees a message "No Sources..." which can be very confusing. Confession, i was stumped for 4 days when i saw this!

Here are a couple thoughts:

1. The user can add a root for one domain and then debug another page and nothing will match. Do we want to key roots by domain?
2. If nothing matches, should we clear the root so that we show everything? Should we show a better error message and let the user clear it?

<img src='https://shipusercontent.com/0edac5885beeaa987d4590887a8ef3d1/Screen%20Shot%202018-02-16%20at%209.45.43%20AM.png' title='Screen Shot 2018-02-16 at 9.45.43 AM.png' width=1425>

**Comment by darkwing** [comment]
I think we should maybe do both?  Show a message that there are no matches and then show the entire tree.

**Comment by lukaszsobek** [comment]
Maybe remember which root was set for a given url and show the full tree for other urls. However, this would require us to store the settings and could lead to bloat when ancient url items start to haunt our local storage.

**Comment by jasonLaster** [comment]
Hmm, @darkwing how would that work?

**Comment by jasonLaster** [comment]
@darkwing i think we should consider this blocked by #5448

**Comment by darkwing** [comment]
Agreed; I think we can/should add a bottom bar to the sources pane, as we have for outline alphabetization.  We can have a "Clear directory root" button there.
