### ISSUE TITLE
[Pause] history should not have arrows

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#5456]
When we pause to debug we show a history of steps with the ability to cycle through them by pressing left and right arrows. 

It would be nice if the buttons were not active when there is just one step:

![should_not_have_arrows](https://user-images.githubusercontent.com/23530054/36339442-3737f6ea-13c6-11e8-899b-bc9d538d32c2.gif)

**Comment by codehag** [comment]
thanks for the bug report! this is an experimental ui so we are quite open to changes

**Comment by lukaszsobek** [comment]
@codehag Maybe just making the arrows non-responsive when there is just one result would be better than completely removing them. Changed the intro issue text.

**Comment by haoRchen** [comment]
Hi, I'd love to tackle this if no one is working on it.

**Comment by haoRchen** [comment]
\claim

**Comment by haoRchen** [comment]
hi @subCode321, I'm still tinkering with this issue
