### ISSUE TITLE
Can't Inspect Object with Numerical Keys

### ISSUE THREAD

**Issue by siefkenj** [devtools-html/debugger.html#5463]
In the Firefox (57) console, objects with only numerical keys will not expand.  For example,

```
x = {12345: 'val'}
```

will show up with an expander arrow, but upon expanding it, only `__proto__` will show.

**Comment by nyrosmith** [comment]
@siefkenj Do you refer to the Console or the debugger? This repo is just handling the debugger.
None the less I just checked both (console & debugger) with 58.0.2 and it works for me. Please update Firefox.
Closing for now but feel free to reopen If you still have issues after updating.

**Comment by nchevobbe** [comment]
Hello @siefkenj , this is probably some variant of https://bugzilla.mozilla.org/show_bug.cgi?id=1371936 .
Bug for the console should be filed in bugzilla. You can sign-in with your Github account and use this URL to submit bugs https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Developer%20Tools%3A%20Console
