### ISSUE TITLE
Investigate using fragment where possible

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#5464]
This would reduce the amount of DOM nodes we use and might have a positive impact on performances

**Comment by nchevobbe** [comment]
oh, I filed on the wrong repo, but I think this is valid.
So, before React 16, each component needed to return a single root ReactElement.
In some case, there is no sense doing so, from an HTML standpoint, so it adds unecessary DOM nodes, which can impact React DOM diffing perf (the more node, the more you need to check).

Starting React 16, a component can return an array of ReactElement, or a Fragment (See https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html). A fragment is a way to have a "root" which will not be rendered in the DOM.

**Comment by jasonLaster** [comment]
Thanks for opening @nchevobbe.

I'd be happy to open more specific/actionable react fragment bugs if we see a slow down that would benefit from react fragments
