### ISSUE TITLE
Toggle Breakpoints - preserve breakpoint "disabled" state

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#547]
One feature that chrome has that is nice is that they preserve the breakpoint disabled state when toggling all breakpoints. 

The usecase here is that while you're debugging you've enabled/disabled some breakpoints for a workflow, then you toggle disable breakpoints so you can get to the right spot, then you enable it again.

![screen shot 2016-08-16 at 11 01 39 am](https://cloud.githubusercontent.com/assets/254562/17703682/9a9e8500-63a0-11e6-97c6-9ed846c6c57e.png)

Here's a sketch of how the work could be done
https://gist.github.com/jasonLaster/12d18102361653f2a8842e357b8bdcbc

It outlines the different files that need to be touched and has some pseudo-code.

Feel free to reach out with questions if you're interested

**Comment by ThomasCrvsr** [comment]
@jasonLaster Do you mind if I try to do the implementation ? :)

**Comment by jasonLaster** [comment]
@thomasCrvsr sure. Note it's marked hard so might have some traps. But should be good, will touch both chrome and Firefox

**Comment by ThomasCrvsr** [comment]
@jasonLaster I'm working on the implementation of `toggleAllBreakpoints()` for Firefox.
We should get the App state in order to toggle each breakpoint individually : https://gist.github.com/jasonLaster/12d18102361653f2a8842e357b8bdcbc#file-foo-diff-L107

A proposal would be to pass the app state to `toggleAllBreakpoints()` as a second param, which will be passed to `setBreakpoint()` or `removeBreakpoint()` depending if we disable/enable breakpoints.

Have you got a better idea ? :)

**Comment by jasonLaster** [comment]
@ThomasCrvsr i'm not sure exactly what you're asking here?

One thing you might have missed in the description is that we do not update the breakpoints *disable* state when we toggle all of the breakpoints. The reason for that is that it's nice to "turn off" all the breakpoints and then when you turn them on again, you still have some disabled some enabled based on your workflow.

> App state in order to toggle each breakpoint individually

In general we don't pass app state into the client methods as they should have a small API, just get the data that they need to perform some function.

![](http://g.recordit.co/zUiLDRewN5.gif)

**Comment by ThomasCrvsr** [comment]
@jasonLaster Sorry, I wasn't clear ^^' I was referring to `public/js/clients/firefox/commands.js` in your gist. You call `getState()` in the function `setBreakpoint()` in the line I shared in my previous comment.

**Comment by jasonLaster** [comment]
ohhhhh, that's not great :). let me look

**Comment by ThomasCrevoisier** [comment]
@jasonLaster I face to another problem. If we set a breakpoint, remove it and set it again we don't have the same actor.
It become problematic when implementing the "toggleAll" feature for Firefox as we should update the state app to have consistency for actors.
What we could do is making the `toggleAllBreakpoints()` function to return every breakpoints and use it in the appropriate reducer to update every breakpoint. What to you think about it ?

**Comment by ThomasCrevoisier** [comment]
The long term solution would be the server side implementation like Chrome (the server-side is not present in this codebase right ?), but I could try the first implementation for the moment :)

**Comment by jasonLaster** [comment]
Sounds good @ThomasCrevoisier.
