### ISSUE TITLE
Doc spell check fails on prepush

### ISSUE THREAD

**Issue by AnshulMalik** [devtools-html/debugger.html#5479]
Looks like we missed some spellings in 2-20-2018 update,

<img width="870" alt="screen shot 2018-02-20 at 9 30 04 pm" src="https://user-images.githubusercontent.com/7821757/36434783-e3f67ae8-1685-11e8-96bb-6bdf64fbc2e7.png">

To fix this, either add the missing words in [dictionary](https://github.com/devtools-html/debugger.html/blob/master/assets/dictionary.txt) or rephrase the sentence.

**Comment by tripurari001** [comment]
I am also facing same issue

**Comment by AnshulMalik** [comment]
For now, if docs is causing the push to fail,  you can use `no-verify` to skip the tests, but you should run `yarn test` to make sure other tests are good :)
