### ISSUE TITLE
Search Input is not focused when pressing shortcut a 2nd time

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#5487]
(tested on macos only)

STRs:
- go to http://firefox-dev.tools/debugger-examples/examples/todomvc/
- open debugger, open any source
- press CMD+F to focus search input
- type anything
- click in the editor
- press CMD+F again

Expected result: Field is focused and I can start searching again
Actual result: Field is cleared but not focused, I need to click on the field to start searching again.

**Comment by darkwing** [comment]
My PR (https://github.com/devtools-html/debugger.html/pull/5399) should fix this @juliandescottes ! :)

**Comment by juliandescottes** [comment]
great, thanks @darkwing , feel free to close this.

**Comment by lukaszsobek** [comment]
Closing as per consensus.
