### ISSUE TITLE
Template literals break pretty print

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#5495]
Store this script in a file:

```js
`${1}${2}${3}`;
function func() {
  for (let bar of foo) {
    for (let baz of bar) {
      baz();
    }
  }
}
```

Run it in a HTML page. Open the debugger, locate the script, and click "Pretty print source".

Result: horrible invalid syntax

![screenshot](https://user-images.githubusercontent.com/7477678/36505206-0d6b19d8-1753-11e8-84b3-05d8a6c25f66.png)

**Comment by jasonLaster** [comment]
Thanks @Loirooriol please file this in https://github.com/mozilla/pretty-fast/issues

**Comment by darkwing** [comment]
Closed for pretty-fast PR
