### ISSUE TITLE
Watch Expressions Hover Looks Odd

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5500]
The watch expression hover on the input seems odd:

<img width="300" alt="watchexpressionshover" src="https://user-images.githubusercontent.com/46655/36516366-329c9804-1743-11e8-9a0d-341e22fcbcaf.png">

Hovering over the element should show the light blue across the entire item, not just the input, and clicking the item (not just the input) should set the focus on the input element.

**Comment by nyrosmith** [comment]
Closing as https://github.com/devtools-html/debugger.html/pull/5591 got merged
