### ISSUE TITLE
[General] Update setState to function pattern

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#5512]
In our codebase we have about 60 instances of `setState`. Unfortunately all of them try to update the state by passing in an object like this:
```
toggleShortcutsModal() {
 this.setState({
      shortcutsModalEnabled: !this.state.shortcutsModalEnabled
    });
}
```
As you might know telling React to update state like we do above gives us no certainty as to when these changes will actually be implemented as setState does not update immediately. Or as Boromir would say: 
![screenshot-20180223134344-536x315](https://user-images.githubusercontent.com/23530054/36594705-a21dbe1c-189f-11e8-9e5d-817bcf48c69e.png)

In order to follow a more defining pattern of updating state where we actually know that after executing the setState call the state WILL be updated we would need to convert each and every one of these calls to a functional format like:
```
toggleShortcutsModal() {
 this.setState((prevState) => ({
      shortcutsModalEnabled: !prevState.shortcutsModalEnabled
    }));
};
```

**Comment by jasonLaster** [comment]
Thanks for filing and starting the conversation. Do you have examples where our code would be cleaner with this pattern?

**Comment by munyari** [comment]
So the issue here is that the non-functional form of `setState` batches calls, whereas calls to the functional form are executed in series. This is a problem when the state update depends on the previous state. From [the docs](https://reactjs.org/docs/react-component.html#setstate):

> This form of setState() is also asynchronous, and multiple calls during the same cycle may be batched together. For example, if you attempt to increment an item quantity more than once in the same cycle, that will result in the equivalent of:
> ```javascript
> Object.assign(
>   previousState,
>   {quantity: state.quantity + 1},
>   {quantity: state.quantity + 1},
>   ...
> )
> ```
> 
> Subsequent calls will override values from previous calls in the same cycle, so the quantity will only be incremented once. If the next state depends on the previous state, we recommend using the updater function form, instead:
> 
> ```javascript
> this.setState((prevState) => {
>   return {quantity: prevState.quantity + 1};
> });
> ```

I'd be glad to submit a patch as my first contribution to this project :)

**Comment by nyrosmith** [comment]
@munyari go for it! Also join our slack if you have questions
