### ISSUE TITLE
[Sources] Debugger does not distinguish scripts with different GET parameters

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#5515]
Create a page with

```html
<script src="script.php?param=1"></script>
<script src="script.php?param=2"></script>
```

where that script is

```php
<?php
if ($_GET["param"] == "1") {
  echo "var a = 1; debugger;\n";
} else {
  echo "var a = 2;\n";
}
?>
```

Due to `debugger`, the debugger will show a script.php tab with the first script. Resume the script, right-click the tab and choose "Reveal in tree". This will open a tab with the second script!

In Sources, script.php is listed only once, and refers to the second one.

**Comment by AnshulMalik** [comment]
Never seen people embedding php output as script

**Comment by Loirooriol** [comment]
Well, not sure if it uses PHP, but Microsoft uses scripts that depend on the GET parameter. Due to this bug I can't debug why my greasemonkey script is not working.

**Comment by jasonLaster** [comment]
What do we need to fix here:

- reveal tree should take you to the correct file
- the source tree should show both sources and if there's a conflict w/ the filename probably show the params?

**Comment by Loirooriol** [comment]
Yes. And I think I added a breakpoint to a script but after reloading the debugger paused in the other one, because I couldn't find the code I was interested to. But maybe that's a different bug, I will know better once I'm able to open the desired script in a tab.

**Comment by jasonLaster** [comment]
does `cmd+p` help?

**Comment by Loirooriol** [comment]
Thanks, Ctrl+P can distinguish GET parameters. It seems the other issue is not related to this, it's just that the debugger pauses on unexisting breakpoints, does not pause on existing ones, and step-in does something weird that is closer to step-out.

**Comment by jasonLaster** [comment]
haha - i need some help parsing this: 

> it's just that the debugger pauses on unexisting breakpoints, does not pause on existing ones, and step-in does something weird that is closer to step-out.
