### ISSUE TITLE
Consider adding error boundaries to debugger

### ISSUE THREAD

**Issue by gregtatum** [devtools-html/debugger.html#5533]
I've been having the debugger going completely blank with some kind of error fairly frequently. Error boundaries would help mitigate some of the mystery of what is going on, and perhaps not leave your application in an invalid state. This is new in React 16.

https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html

**Comment by jasonLaster** [comment]
Yep. This will be really helpful

**Comment by lukaszsobek** [comment]
What boundaries do we want to set? Seems like every rendered component should have its own, but that would be a lot of change whereas just having it on top level components seems a bit little. Also do errors bubble i.e. if we have one boundary inside another do both trigger or just one.

**Comment by jasonLaster** [comment]
I'm going to close this as it's not actionable now. Lets keep this idea in our back pocket and use it when we think it's appropriate
