### ISSUE TITLE
Runtime errors being caught by event-emitter

### ISSUE THREAD

**Issue by MaxBittker** [devtools-html/debugger.html#5543]
The context of this issue is that I'm trying to integrate error reporting into this repo so that we can have visibility into uncaught exceptions in debugger.html that should be fixed.

The issue I had was that errors thrown from inside the render function of components (and very likely other lifecycle methods*) were **not** hitting the global error handler, but were instead being console.log'd by this line: 

https://github.com/devtools-html/devtools-core/blob/d3b868dc496d3ece9a4db1be8589e06b81d8e5bf/packages/devtools-modules/src/utils/event-emitter.js#L122

My question is: what is this event-emitter module used for, why might an error from the application end up here, and what would be a good solution to make sure all uncaught errors hit this global error handler (or what would be a an error reporting functionality to hook into this emitter?

*errors thrown from asynchronous contexts such as `setImmediate(()=>foo.i_throw())` don't have this issue and hit the global error handler just fine

**Comment by jasonLaster** [comment]
@nchevobbe @codehag do you know what's going on here?

**Comment by jasonLaster** [comment]
I'm closing this as there's ongoing work on the event emitter. We can re-evaluate when we have basic sentry support and the event emitter work has landed.

**Comment by MaxBittker** [comment]
thanks jason 👍
