### ISSUE TITLE
Debugger breaks run-to-completion when Worker onmessage callbacks fire

### ISSUE THREAD

**Issue by jimblandy** [devtools-html/debugger.html#5545]
This is a proxy for [bugzilla 1426467][bug]. This is just a summary; see Bugzilla for current information.

When there is a worker that is sending messages down, "step in" can accidentally land in the worker.onmessage callback
         
STR: (https://dbg-setinterval.glitch.me/)

1. click click me
2. step over
3. step IN

AR: land in funca
ER: land in onmessage

[bug]: https://bugzilla.mozilla.org/show_bug.cgi?id=1426467

**Comment by jimblandy** [comment]
Analysis:

Here's what's going on in this bug:

- In the midst of some JavaScript invocation, the worker's parent window hits a
  breakpoint. The devtools server calls nsIDOMWindowUtils::SuspendTimeouts, and
  starts a nested event loop.

- The worker sends the parent a message, enqueuing a runnable on the main thread.

- The main thread's event loop processes the runnable. Since the parent window
  has timeouts suspended, MessageEventRunnable::WorkerRun stashes the runnable
  in WorkerPrivateParent::mQueuedRunnables: https://goo.gl/eFgA1u

- The developer continues from the breakpoint. The devtools server calls
  nsIDOMWindowUtils::ResumeTimeouts, which runs the runnables saved in
  mQueuedRunnables.

- The worker message runnable calls the parent window's onmessage handler.

This is incorrect. Running the onmessage handler in the midst of the original
JavaScript invocation (which was only paused at a breakpoint) violates the
run-to-completion rule.

**Comment by AnshulMalik** [comment]
Looks like this is fixed now.
