### ISSUE TITLE
[Editor] "Reveal in Tree" Editor Context Menu Item Switches from PrettyPrinted Tab to Original Tab

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5564]
Using this context menu item should have no effect on the selected tab.

![wtfswitch](https://user-images.githubusercontent.com/46655/36822384-615346d2-1cbd-11e8-9884-8ce0460aa1af.gif)

**Comment by jasonLaster** [comment]
@darkwing could you add an STR for how to reproduce?

**Comment by darkwing** [comment]
* Right-click a pretty-printed tab's contents to see its context menu
* Click on the "Reveal in Tree" item

You'll then see the tab change to its original source counterpart.

**Comment by jasonLaster** [comment]
This issue might be blocked by the ongoing pretty print refactoring.

**Comment by darkwing** [comment]
Following the logic, it appears this is triggered in `src/actions/ui.js`'s `showSource` method:

```diff
diff --git a/src/actions/ui.js b/src/actions/ui.js
index 496f47cdb..096b076bd 100644
--- a/src/actions/ui.js
+++ b/src/actions/ui.js
@@ -84,6 +84,8 @@ export function showSource(sourceId: string) {

     dispatch({
       type: "SHOW_SOURCE",
+      // "getRawSourceURL" is required to ensure the SourcesTree finds the correct source
+      // Removing "getRawSourceURL" loses the ability to find the item in tree
       sourceUrl: getRawSourceURL(source.get("url"))
     });
   };
```

It appears that this `showSource` function is only ever used for Reveal in Tree, so we may be able to isolate a change here.  The `getRawSourceURL` need is a bit of a conundrum right now.

**Comment by darkwing** [comment]
Looking at this more:

```diff
diff --git a/src/actions/ui.js b/src/actions/ui.js
index a6b2b6070..896be3e70 100644
--- a/src/actions/ui.js
+++ b/src/actions/ui.js
@@ -87,7 +87,7 @@ export function showSource(sourceId: string) {

     dispatch({
       type: "SHOW_SOURCE",
-      sourceUrl: getRawSourceURL(source.url)
+      sourceUrl: source.url
     });
   };
 }
diff --git a/src/components/PrimaryPanes/SourcesTree.js b/src/components/PrimaryPanes/SourcesTree.js
index bffb962de..f4b7aabca 100644
--- a/src/components/PrimaryPanes/SourcesTree.js
+++ b/src/components/PrimaryPanes/SourcesTree.js
@@ -115,7 +115,10 @@ class SourcesTree extends Component<Props, State> {
     }

     if (nextProps.shownSource && nextProps.shownSource != shownSource) {
-      const listItems = getDirectories(nextProps.shownSource, sourceTree);
+      const listItems = getDirectories(
+        getRawSourceURL(nextProps.shownSource),
+        sourceTree
+      );

       if (listItems && listItems[0]) {
         this.selectItem(listItems[0]);
```

Using `getRawSourceURL` in `ui.js` seems wrong because it could effect the tab selection; *not* using `getRawSourceURL` for the `SourcesTree.js` block will always lead to a problem, because `:formatted` URLs will never display in the tree.

With the code above, the tab still switches from pretty-printed to original source tab, but this is a decent start!
