### ISSUE TITLE
Remove unused css variables

### ISSUE THREAD

**Issue by nt1m** [devtools-html/debugger.html#5566]
We have some css properties that are defined, but never used

Properties
- `--theme-search-overlays-semitransparent` 
- `--theme-search-overlays-semitransparent` 
- `--theme-codemirror-gutter-background`

Bugzilla bugs
- https://bugzilla.mozilla.org/show_bug.cgi?id=1441929
- https://bugzilla.mozilla.org/show_bug.cgi?id=1441879
- https://bugzilla.mozilla.org/show_bug.cgi?id=1441878

**Comment by lauragift21** [comment]
I'll like to work on this.

**Comment by sunnywalker** [comment]
it looks like `--theme-codemirror-gutter-background` is being used in `src/utils/editor/source-editor.css` lines 170 and 188

**Comment by jasonLaster** [comment]
Thanks!

By the way, `breakpoint-hover-background` was fixed here https://hg.mozilla.org/integration/autoland/rev/f6264884db15

**Comment by lauragift21** [comment]
Thanks for pointing that out. I have a problem with locating this file src/utils/editor/source-editor.css

**Comment by msujaws** [comment]
Bug 1441882 added a test that catches these types of errors. When fixing this, the entry for this bug will need to be removed from the whitelist in browser_parsable_css.js.

**Comment by juliandescottes** [comment]
Reopening per https://github.com/devtools-html/debugger.html/issues/5668

`--theme-search-overlays-semitransparent` still needs to be removed

**Comment by irrationalRock** [comment]
Hi, I made a PR to remove one of the <code>--theme-search-overlays-semitransparent</code> but there is another in a node modules called devtools-mc-assets. In that repo a file called sync.js downloads a zip and in that zip exists <code>--theme-search-overlays-semitransparent</code>.
