### ISSUE TITLE
Keyshortcuts no longer work when breaking and focusing the page

### ISSUE THREAD

**Issue by ochameau** [devtools-html/debugger.html#5568]
STR:
* open data:text/html,<script>onclick=() => {debugger;}</script>
* click on the page while the debugger is opened
* click on the page to ensure it has the focus
* try hitting any keyshortcut: F5, Ctrl+Maj+I (toggle toolbox), ... many key shortcuts no longer work. Some other still do, like Ctrl+TAB to switch to the next tab.

**Comment by jasonLaster** [comment]
@darkwing  @AlexisDeschamps @calebstdenis could you see if this works for you on windows?

**Comment by calebstdenis** [comment]
@jasonLaster I can reproduce the bug as described on Nightly on Windows.

**Comment by jasonLaster** [comment]
@ochameau I'm not sure if this is a debugger bug or a toolbox bug. Do you know where f5 and cmd+option+i are bound?
