### ISSUE TITLE
[Windows] Ctrl+P `.highlight` markers font looks blurry on Windows

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#5584]
I noticed this since a 3, 4 weeks. The highlighted, bold parts of the Search matches of `Ctrl+P` look blurry on Windows. No idea why, maybe some odd fonts settings. I also captured the browser.xul output, but cannot see anything obvious in the CSS:

![image](https://user-images.githubusercontent.com/3307404/36890421-0f680514-1dfe-11e8-9597-1042e7d2a4e6.png)

See how bold, kinda ugly the bold `api` match looks. The letter spacing is kind of too narrow.

I looked at this also on Linux and there it looks fine.

PS Looking at the source I see that the match is hightlighted using `<strong class="hightlight">`. While this is not totally incorrect afaik, I think it should rather be `<mark>` to make it semantically 100% correct and better accessibly. By the way there's also https://github.com/bvaughn/react-highlight-words (which also uses `mark` not `strong` here).

**Comment by lukaszsobek** [comment]
@jasonLaster I read up on the code and fuzzy-aldrin-plus uses strong internally. Technically it should accept options as its third parameter in which we are then able to set the way it highlights, but this options object seems to be completely ignored. Referring the issue: https://github.com/jeancroy/fuzz-aldrin-plus/issues/37

**Comment by jasonLaster** [comment]
Thanks, lets see what they say

**Comment by jeancroy** [comment]
Does the usage of mark vs strong make a difference in anti-aliasing ?

**Comment by lukaszsobek** [comment]
Merged. Closing.

**Comment by jnachtigall** [comment]
@lukaszsobek It still (or again) looks blurry on Nightly:

![image](https://user-images.githubusercontent.com/3307404/40174899-be6b96b6-59d6-11e8-8db8-9bdd4adb48e8.png)

For instance, check the 4th entry `PathUtils.js` letters. So using `<mark>` instead of `<strong>` did not seem to have fixed the issue. I am on Windows 10.

Can you reopen?

PS Looks like the 
```css
.result-item .title .highlight {

    font-weight: bold;
}
```
causes this. I am not a fonts expert, but maybe the used font on Windows is not great for bold.
