### ISSUE TITLE
Fix React 16.2 warning for PureComponent

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5589]
We recently upgraded to React 16.2 and we're now appropriately inundated with helpful warnings in both the console and the jest unit tests. It'd be great to get some help cleaning these up

```
Warning: EditorMenu has a method called shouldComponentUpdate(). shouldComponentUpdate should not be used when extending React.PureComponent. Please extend React.Component if shouldComponentUpdate is used.
```

**Comment by nyrosmith** [comment]
/claim

I'll also look at the context related warnings too.
