### ISSUE TITLE
[Stepping] Can't step over upper in call stack

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#5596]
Run this code in the console:

```js
function f() {
  var foo = 123;
  ++foo;
  return foo;
}
function g() {
  debugger;
  var bar = f();
  ++bar;
}
g();
```

1. The debugger pauses at `debugger;` in function `g`.
2. Step in. The debugger pauses at `var bar = f();` in function `g`.
3. Step in. The debugger pauses at `var foo = 123;` in function `f`.
4. In call stack, click function `g`. The debugger goes back to `var bar = f();` in function `g`.
5. Step over.

Result: The debugger pauses at `++foo;` in function `f`.
Expected: The debugger pauses at `++bar;` in function `g`.

**Comment by jasonLaster** [comment]
@Loirooriol so just to be clear, you would expect a different behavior stepping behavior based on the selected frame in the call stack?

**Comment by Loirooriol** [comment]
Yes, I think it would be more useful. Not sure if it's what debuggers usually do, though.

**Comment by jasonLaster** [comment]
Yeah, its certainly something I've thought about as well. It seems like something we could do in the *happy* case. 

One challenge would be if we hit a debugger statement or breakpoint while heading to the selected path, but that might be okay...

**Comment by jasonLaster** [comment]
I'm moving this to the icebox. We will prioritize it in our next release scheduling meeting.
