### ISSUE TITLE
[SourceMaps] update to source-map to 0.7.2

### ISSUE THREAD

**Issue by andreicristianpetcu** [devtools-html/debugger.html#5598]
Hi,

Source-map got new and shiny performance fixes in 0.7.2. It would be really cool if the debugger would benefit from the following fixes:

https://hacks.mozilla.org/2018/01/oxidizing-source-maps-with-rust-and-webassembly/
http://fitzgeraldnick.com/2018/02/26/speed-without-wizardry.html

**Comment by andreicristianpetcu** [comment]
Relevant issue in upstream https://github.com/babel/babel/issues/7486

**Comment by jasonLaster** [comment]
Thanks! Good call

**Comment by andreicristianpetcu** [comment]
Here is the list of dependencies that have an old source-maps as a dependency

babel-generator@^6.18.0, babel-generator@^6.26.0:
"@babel/generator@7.0.0-beta.40":
babel-cli@^6.7.5:
babel-core@^6.0.0, babel-core@^6.25.0, babel-core@^6.26.0:
babel-generator@^6.18.0, babel-generator@^6.26.0:
babel-register@^6.18.0, babel-register@^6.26.0:
clean-css@4.1.x:
csso@~2.3.1:
devtools-map-bindings@^0.3.3:
devtools-source-map@^0.14.8:
handlebars@^4.0.3:
istanbul-lib-source-maps@^1.1.0, istanbul-lib-source-maps@^1.2.2:
jest-cli@^20.0.4:
jstransform@^11.0.3:
postcss@^5.0.10, postcss@^5.0.11, postcss@^5.0.12, postcss@^5.0.13, postcss@^5.0.14, postcss@^5.0.16, postcss@^5.0.2, postcss@^5.0.4, postcss@^5.0.5, postcss@^5.0.6, postcss@^5.0.8, postcss@^5.2.16:
postcss@^6.0.0, postcss@^6.0.1, postcss@^6.0.13:
postcss@^6.0.0, postcss@^6.0.1, postcss@^6.0.13:
pretty-fast@^0.2.3:
recast@^0.11.17, recast@~0.11.12:
snapdragon@^0.8.1:
source-map-support@^0.4.15:
uglify-es@^3.3.4:
uglify-js@3.3.x:
uglify-js@^2.6, uglify-js@^2.8.27, uglify-js@^2.8.29:
uglifyjs-webpack-plugin@^0.4.6:
uglifyjs-webpack-plugin@^1.1.6:
webpack-sources@^1.0.1, webpack-sources@^1.1.0:
webpack@^2.2.1:
webpack@^3.10.0, webpack@^3.3.0:

---optional dependencies
escodegen@^1.6.1, escodegen@^1.9.0:

**Comment by andreicristianpetcu** [comment]
Here is a list of dependencies that depend on source-map

babel-generator
babel-cli
babel-core
babel-register

clean-css
csso
devtools-map-bindings
devtools-source-map
handlebars
istanbul-lib-source-maps
jest-cli
jstransform
postcss
pretty-fast
recast
snapdragon
source-map-support
uglify-es
uglify-js
uglifyjs-webpack-plugin
webpack-sources
webpack

convert-source-map through inline-source-map

---optional dependencies
escodegen

**Comment by andreicristianpetcu** [comment]
Any idea which one would be more important?
