### ISSUE TITLE
[Storybook] Remove storybook for the time being

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5614]
[Storybook] is an interactive ui development environment for react components. It makes it easier to document a components many states and develop quickly.

We've had storybook for the history of the project, but have not taken advantage of it to it's full potential.

- for awhile we built features in storybook first (call stacks)
- for awhile we had perceptual diffing (percy)

At the moment it is under-used and honestly needs work before it will be used effectively:

- stories need to be fixed
- storybook should be upgraded for react 16
- percy or another tool should be used to keep it green
- it should tie in better with jest

Given this and given it is not a priority for the next three months, i think we should take it out of the project temporarily. I'd fully support bringing it back in the future, perhaps with a new version of storybook and incrementally re-adding stories...

[Storybook]: https://storybook.js.org/

**Comment by jasonLaster** [comment]
@nyrosmith lets wait and get more feedback

**Comment by nyrosmith** [comment]
OK
/unclaim

**Comment by darkwing** [comment]
As we do more UI work, I think Storybook could be really useful.  That said, if a contributor comes along and knows how to fix it, that would be great, otherwise I think our core team has much more important work to focus on.

**Comment by nyrosmith** [comment]
+1 for removing storybook for now.
The stories are outdated and broken so no one benefits having them atm...

**Comment by lukaszsobek** [comment]
I didn't even know there was one, but from what is discussed here 1.) we seem to be doing pretty well without it , 2.) making it work and maintaining it requires overhead we are currently not eager to deal with, 3.)  the costs appear to outweigh the benefits.
+1 for removing storybook here too
