### ISSUE TITLE
[QuickOpen] Loading message never disappears

### ISSUE THREAD

**Issue by AnshulMalik** [devtools-html/debugger.html#5623]
<img width="1025" alt="screen shot 2018-03-07 at 4 55 32 pm" src="https://user-images.githubusercontent.com/7821757/37089910-5fa0dd02-2228-11e8-9f80-e1ae9a98dd5c.png">

When you open Quick Open dialog(Cmd+P), you can see `Loading...` text displayed even after the results are available.

Expected:
`Loading...` should disappear when results are available.

**Comment by atwalg2** [comment]
Hello @atiqueansari1987 
Since I caused this bug. I came up with this solution. 
I'm going to make a pull request for it tonight.

In src/components/QuickOpenModal.js
```    const { enabled, query, symbols, selectedSource } = this.props;
```
...
```        {selectedSource != null &&
          this.isSymbolSearch() &&
          (!symbols ||
            (symbols.functions.length == 0 && (
              <div className="loading-indicator">
                {L10N.getStr("loadingText")}
              </div>
            )))}
```
