### ISSUE TITLE
Storybook doesn't work with fresh install

### ISSUE THREAD

**Issue by jmeas** [devtools-html/debugger.html#563]
**Type:** Bug, perhaps?

**Affected component:** Storybook

**Steps to reproduce:**

1. Clone a fresh copy of the debugger
2. Run `npm install`
3. Run `npm start` (just for kicks. You can also leave this step out if you want)
4. Run `npm run storybook`
5. Load up the URL for storybook in the browser: `http://localhost:9001/`
6. Observe that the storybook loads, but that there are no components

<details>
  <summary>There's an error in the console: (click to expand)</summary>
```
ERROR in ./.storybook/config.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../public/build/styles.css in /Users/jmeas/webdev/debugger.html/.storybook
 @ ./.storybook/config.js 7:0-37
```
</details>

Based on this, and the contents of my `public/build` folder, it looks like the CSS isn't being built.

<details>
  <summary>The contents of my `public/build` folder are: (click to expand)</summary>
```
- bundle.js
- bundle.js.map
- pretty-print-worker.js
- pretty-print-worker.js.map
- source-map-worker.js
- source-map-worker.js.map
```
</details>

I tried this twice, with the following versions of Node/npm:

1. Node v6.4.0, npm v3.10.3
2. Node v4.46, npm v.2.15.5

---

Based on a quick glance at the build tools, it looks like Webpack is supposed to build the CSS (I think?), so I explicitly tried running `npm run prepublish` to get webpack to run, but it still didn't output a CSS file.

Also, I looked through [the CONTRIBUTING guide](https://github.com/devtools-html/debugger.html/blob/master/CONTRIBUTING.md) to see if there was any mention of an explicit process to build the CSS, but nothing stood out to me.

If this is a problem with the setup instructions, or if it's a bug in the build process, I'd be happy to make a PR to help get it fixed for future developers. But atm I can't pinpoint the issue.

I might just be doing something silly, though. Any clues? :)

**Comment by jasonLaster** [comment]
@jmeas try doing a webpack build.

**Comment by jmeas** [comment]
Is that done by running the command `webpack`, @jasonLaster ? If so, I tried that by running `npm run prepublish` (which [is aliased to webpack](https://github.com/devtools-html/debugger.html/blob/53501477b9dab79c5ae9dca2ffdf75f257604117/package.json#L28))

**Comment by jasonLaster** [comment]
Oh, yeah that's probably the same thing

**Comment by jmeas** [comment]
If you've got time tonight/this weekend we could ScreenHero?

**Comment by jasonLaster** [comment]
Hmm, in away from my computer so it's tough for me to pinpoint it. I think you're on the right track.

**Comment by jasonLaster** [comment]
Ah @jmeas just looked quickly, I believe our webpack config needs to be updated. It only builds styles.css when it's not in development. Should be an easy fix to allow that all the time so there's always a styles.css

**Comment by jlongster** [comment]
Don't have any context at all, but we don't want to build a styles.css in development, as it breaks hot reloading. It's it's storybook specific... yeah that's fine.

**Comment by jmeas** [comment]
> It only builds styles.css when it's not in development. Should be an easy fix to allow that all the time so there's always a styles.css

Makes sense. I (temporarily) got around this by running:

`NODE_ENV=production npm run prepublish`

The CSS looks a little bare, but I'm not sure if that's because it's not being run in the context of the greater app. For instance, there's no syntax highlighting, and I can't see breakpoints in that associated story. Does that sound right?

Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/2322305/17827548/76d5177a-6633-11e6-848a-21e652e040df.png)

**Comment by jasonLaster** [comment]
Oh nice. By the way, the issue came from the stores being loaded in the storybook config file. 

That does look right :/

We recently changed our theme management and it now retired on a root div with the theme-light class. 

I'm out, so just guessing...

**Comment by jmeas** [comment]
> We recently changed our theme management and it now retired on a root div with the theme-light class.

Ah okay, that makes sense. Thanks for the help with figuring this out!

**Comment by jasonLaster** [comment]
Fixed https://github.com/devtools-html/debugger.html/commit/9a01c43deeeade0ffe0ee2c363f13556520d9692
