### ISSUE TITLE
Search Box of find-in-all-files acts weird

### ISSUE THREAD

**Issue by ruturajv** [devtools-html/debugger.html#5634]
When searching across files in debugger, the searchbox acts weirdly, the caret always goes past the last character

STR:
1. open debugger
1. `Ctrl + Shift + F` (I use linux) [Search inside all files]
1. Type anything for searching
1. Move caret inside the search text, by using left arrow (The caret goes back to last character)
1. Even selection of the entire word leads to loss of selection (caret goes past last char)

Last 2 points shown in the gif below

![debugger-search-in-files](https://user-images.githubusercontent.com/227817/37133821-85d74496-22bb-11e8-97ac-6a7a169cf498.gif)

- This is observed in Firefox release and Firefox Beta
- I couldn't replicate in the debugger.html's latest master, but I'm not sure how the keybindings work after its integrated inside Firefox

**Comment by AnshulMalik** [comment]
I think this is resolved now.

**Comment by jasonLaster** [comment]
Thanks for filing!

Yep, @ruturajv try this in nightly.
