### ISSUE TITLE
[Shortcuts] Use non-breakable space for shortcuts in shortcuts popup (FR locale)

### ISSUE THREAD

**Issue by nicofrand** [devtools-html/debugger.html#5637]
In the shortcut popup the shortcuts texts like "CTRL + P" should use non-breakable spaces to avoid this kind of layout (french locale):

![firefox-shortcuts](https://user-images.githubusercontent.com/3419050/37147404-13836260-22c7-11e8-94da-cd3790d2dbc7.png)

**Comment by Haroenv** [comment]
should probably be `white-space: pre` instead, no?

**Comment by nicofrand** [comment]
Yup, would work too !

**Comment by PatMB30** [comment]
Hi!

I'd like to know if this issue is claimed or not?

**Comment by jasonLaster** [comment]
@PatMB30 feel free to claim it

**Comment by buttersnipps** [comment]
Hi, Is there a way to change the language of the debugger . It's always shows english even though I try it on firefox with french pack active.

**Comment by jasonLaster** [comment]
In firefox, you can change languages, with a language pack
https://addons.mozilla.org/en-US/firefox/language-tools/

Locally, in the launchpad, we dont have a good way of doing that yet
