### ISSUE TITLE
Move (or copy) the content of the shortcut modal into debugger content

### ISSUE THREAD

**Issue by nicofrand** [devtools-html/debugger.html#5638]
When we open the debugger without any file, there are two shortcuts explained:

![firefox-shortcuts-discover](https://user-images.githubusercontent.com/3419050/37147484-627eb5ea-22c7-11e8-83c7-7184cfcb2a6c.png)

It would be really great if all shortcuts that appear in the shortcuts modal were moved here, or at least copied. I had to ask on IRC to know how to open the shortcul modal (the button is really small and IMO not at the right place : it refers more to breakpoints than anything).

Reminder of the shortcut modal:

![firefox-shortcuts](https://user-images.githubusercontent.com/3419050/37147521-7bc2f12e-22c7-11e8-8574-5502a7c78e76.png)

**Comment by jasonLaster** [comment]
Hmm, i think that could be too much content, but it would be nice to have a link to open the shortcuts modal?

Like `See more shortcuts`

**Comment by nicofrand** [comment]
Why too much content ? It really looks like we have the space ? 
And that's useful content.

But if the community disagress, I guess a button/link to access the modal would be a first step.

**Comment by jasonLaster** [comment]
@darkwing @violasong how do you feel about a link to open the shortcuts modal from the welcome pane?

It's redundant w/ the ? logo, but could be nice

**Comment by violasong** [comment]
I like the idea of a `More shortcuts` link below the two lines. Keeping it simple helps communicate the empty-state. The redundancy with the `?` button seems fine since it's so unobtrusive down there. Eventually I'd love to link `?` to a more fleshed out help modal based on quick open (https://mozilla.invisionapp.com/d/main/#/console/12557775/283871189/preview), but the shortcuts modal seems fine for now.

**Comment by Rohanhacker** [comment]
@jasonLaster I am a bit confused here. Can you post screenshot from the invision ?? How should i proceed with this issue ?

**Comment by jasonLaster** [comment]
Hey @violasong could you share a screenshot. I can't login either :)

**Comment by violasong** [comment]
Ah, sorry, I used the wrong link! It was pretty tangential, but this is what I originally was talking about - combined help/shortcuts/quick open: https://mozilla.invisionapp.com/share/2XEEY0RYA#/screens/283871189_tab_Overflow
The latest version of the combined modal idea just has shortcuts as a menu item https://mozilla.invisionapp.com/share/DPGL221WHNZ#/screens

Neither of the above are very relevant to this particular issue which is just adding the link "More shortcuts" to the welcome screen. Maybe something as simple as this with all the text descriptions capitalized -

<img width="621" alt="image" src="https://user-images.githubusercontent.com/55994/38648855-42e98042-3da8-11e8-9d87-38c9272d99e0.png">

Side note: it seems like the current shortcuts message is positioned a little too far to the right
