### ISSUE TITLE
[Editor] does not update on attach

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5639]
I'm seeing some funny business when i open the devtools panel. 

1. the editor does not show the text
2. switching tabs does not update the editor
3. breakpoints are missing

I think React 16 is to blame, but i'll need to dig deeper :)

**Comment by lukaszsobek** [comment]
Noticed that too, especially on reloading the debugger with already open tabs - you would need to manually trigger an update by clicking the position in the sidebar.
