### ISSUE TITLE
[QuickOpenModal] scroll resets to top

### ISSUE THREAD

**Issue by kootoopas** [devtools-html/debugger.html#5660]
yeap

![quickopenmodal-scroll-resets-to-zero](https://user-images.githubusercontent.com/601001/37314212-9bfc8954-265b-11e8-99c5-77161b49bf0a.gif)

**Comment by kootoopas** [comment]
/claim since I've tinkered with this recently :)

**Comment by kootoopas** [comment]
Hmm, weird. I can reproduce it in the nightly's devtools, but not in the standalone debugger.

**Comment by jasonLaster** [comment]
hmm, strange. Nightly is 10 days behind GH so check again in when it's up to date

**Comment by kootoopas** [comment]
Ooh okay I thought it was pulling from master on a daily... sorry if this turns out to be a false flag!

**Comment by jasonLaster** [comment]
This is working for me in nightly. Let me know if it works for you.
