### ISSUE TITLE
In lower image, 'SOURCE LIST PANE' should be named 'TOOLBAR' and 'WATCH EXPRESSIONS', resp.

### ISSUE THREAD

**Issue by rogererens** [devtools-html/debugger.html#5661]
On this page
https://mozilladevelopers.github.io/playground/debugger/
in the bottom image the upper two sections have wrong content in the text boxes.

![image](https://user-images.githubusercontent.com/907897/37336800-c64c4594-26b2-11e8-8c07-01b54d1a0b96.png)

**Comment by AnshulMalik** [comment]
Hey, @rogererens Thanks for filing.

There already exists a bug for this https://github.com/MozillaDevelopers/playground/issues/28
