### ISSUE TITLE
[SourceTree] Show original files when the files have the same URL

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5663]
STR:
1. go to https://q7mmol9xy9.codesandbox.io/
2. go to src/Hello.js

Code Sandbox ships each file down with its own base64 sourcemap and no sourceUrl. The result is that the original file has the same url as its generated file equivalent. This means that the source tree at the moment only shows the generated file. cmd+p shows both but doesn't differentiate them.

We have two options:

1. show both and differentiate them e.g ([sm] suffix)
2. show the original file and let the user jump back to the generated file

### Chrome
<img src='https://shipusercontent.com/2aa202c580b77384c3fe7b544c91999d/Screen%20Shot%202018-03-13%20at%2011.21.16%20AM.png' title='Screen Shot 2018-03-13 at 11.21.16 AM.png' width=788>

### Firefox 
![Screen Shot 2018-03-13 at 11.21.08 AM.png](https://shipusercontent.com/dd26dc6cb3278fbcf85540208c4c9e80/Screen%20Shot%202018-03-13%20at%2011.21.08%20AM.png)

**Comment by joshunger** [comment]
@buttersnipps are you working on this issue?

**Comment by joshunger** [comment]
@buttersnipps I'm going to take a look in at this issue later this week can you let me know if you're working on it? If I don't hear from you I'll start working on it.  If you want to ✋ it off let me know.

**Comment by joshunger** [comment]
Mouse over -
![image](https://user-images.githubusercontent.com/2301847/37977856-e3014f32-31a1-11e8-94b1-d14dad76f018.png)

**Comment by joshunger** [comment]
![image](https://user-images.githubusercontent.com/2301847/38197571-21226e42-3646-11e8-84e8-94907bf76055.png)

**Comment by jasonLaster** [comment]
After exploring changing the url to be clearer we decided that it would cause more confusion about how the url came from the source map.

**Comment by joshunger** [comment]
@jasonLaster the React tree components use path as the `key` which becomes a problem because these two files have the same path, but different `id`s. How would you like me to fix?

- https://github.com/devtools-html/debugger.html/blob/master/src/components/PrimaryPanes/SourcesTree.js#L290
- https://github.com/devtools-html/debugger.html/blob/master/src/components/shared/ManagedTree.js#L153

**Comment by jasonLaster** [comment]
i think we do something like this for blackboxing where we add something to the path adding `-original` to the end should work.

**Comment by joshunger** [comment]
```
./node_modules/.bin/start-firefox --start --location https://q7mmol9xy9.codesandbox.io/
```

**Comment by jasonLaster** [comment]
This might be another case:

I just saw something similar on https://angular-quickstart.glitch.me/ . does the `ngfactory` file fall into the same issue, @jasonLaster ?

![screenflow](https://user-images.githubusercontent.com/8599/40452945-692d6424-5e98-11e8-9227-968839080ab1.gif)

**Comment by joshunger** [comment]
per @darkwing 

> Hello @joshunger ; as we talked about this morning, we have a bit of maintenance work we need to do with the SourcesTree before we attack this. You can feel free to experiment with it but it may be best to hold off for the moment."

/unclaim

**Comment by jbhoosreddy** [comment]
As of today, on master, it is actually showing both sources in the source tree. but with no differentiation between them " [sm]". I'll add a PR to modify the string. That should make it apparent when user clicks on it.

**Comment by jasonLaster** [comment]
Progress

- [ ] duplicate keys should not have a conflict
- [ ] AppModule is a duplicate key
- [ ] selecting an item should highlight the correct item
- [ ] show [sw] at the end

**Comment by digitarald** [comment]
Quickly hacking something in Inspector, this might be another more subtle formatting for the `sm` label

<img width="152" alt="image" src="https://user-images.githubusercontent.com/8599/43419162-121356a2-93f5-11e8-9aba-a8ac98679eb4.png">

There might even be enough space to make it an actual word (vs [sm](https://www.internetslang.com/SM-meaning-definition.asp)):

<img width="162" alt="image" src="https://user-images.githubusercontent.com/8599/43419230-3a1ca270-93f5-11e8-8399-0600f9b27134.png">

**Comment by jasonLaster** [comment]
yeah, i think we can do something with color too... like a stylized `JS` or an icon on the right.  With that said, I see this issue as mostly the business logic side, once we have this we can improve the look and feel.

**Comment by joshunger** [comment]
👍 I interviewed two developers when I was looking at this and both didn't understand what "sm" meant. 2 cents.

**Comment by digitarald** [comment]
Continuing the interface discussion in https://github.com/devtools-html/debugger.html/issues/6824. Please share your thoughts there.
