### ISSUE TITLE
[Stepping] Fast stepping is freezing the debugger UI and the devtools.

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#5677]
With Firefox Nightly 61.0a1 (2018-03-14) (64-bit) (but this has been going on for a while.)

1. Go to any site with scripting.
2. Set a breakpoint
3. Starts stepping, be in or out or over (this is working)
4. Accelerate the stepping because you want to reach another section. (multiple fast click on the stepping button)

Actual:
The UI freezes, the script area becomes blank and you often need to really close the devtools to come back to a normal state.

Expected:
Just carry on record the number of steps events and go through them.

**Comment by jasonLaster** [comment]
how quickly are you stepping? we have a bug where we crash if you step quickly

**Comment by karlcow** [comment]
@jasonLaster Fast :) For example in a foreach loop when I want to move forward quickly, so my click/taps are faster than the UI refresh. That must be the bug you are talking about.

**Comment by jasonLaster** [comment]
yeah, it's a terrible bug :bug:

**Comment by jasonLaster** [comment]
We fixed two cases where stepping quickly caused issues. I found another one today that seems like a good culprit:

![Screen Shot 2018-03-15 at 4.49.16 PM.png](https://shipusercontent.com/656043807b1d9574a4429567720412ff/Screen%20Shot%202018-03-15%20at%204.49.16%20PM.png)

**Comment by jasonLaster** [comment]
Actually, this bug was fixed by this patch, which will land in mc soon:
https://github.com/devtools-html/debugger.html/issues/5490

**Comment by jasonLaster** [comment]
closing for now. we can re-open if we see some more cases
