### ISSUE TITLE
[QuickOpen] Style selected matches 

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5679]
We currently do a bad job of styling the black fuzzy matches when a row is selected.

![](http://g.recordit.co/aAckOZyZlf.gif)

**Comment by humphd** [comment]
@jasonLaster my students are picking bugs to work on right now, and @AlexWang-16 is wondering about this one.  Would you suggest this as a good-first-bug for him, or do you have another suggestion that might be better?  Thanks for any advice.

**Comment by jasonLaster** [comment]
Yep, this would be great

@darkwing @violasong do you have an idea of what this should look like?

**Comment by jasonLaster** [comment]
@humphd you should join our slack so we can discuss other issues + projects https://devtools-html-slack.herokuapp.com/

**Comment by violasong** [comment]
I think fuzzy matches can be white bold when selected - it's be a subtle look but same as what we do in the Firefox URL bar.

**Comment by AlexWang-16** [comment]
Thanks for the confirmation @jasonLaster. I'm be happy to take a stab at this bug. I've also joined slack for Firefox Nightly. I did not see a channel for devtools-html. Should I join devtools-core instead?

**Comment by jasonLaster** [comment]
hmm - there should be a #general and #debugger room

**Comment by jasonLaster** [comment]
Hey @AlexWang-16 how's it going?

**Comment by AlexWang-16** [comment]
@jasonLaster I think I got it. Going to commit then do a PR. It should be ready within 10 - 15 minutes.
