### ISSUE TITLE
Console breaks when evaluating code in the new debugger

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#568]
The console currently crashes when evaluating code with the new debugger on.

The reason for this is that it relies on the old Debugger to determine which frame to evaluate code on.

**Comment by jasonLaster** [comment]
I added a patch here: https://bugzilla.mozilla.org/show_bug.cgi?id=1295753

try is down so waiting to run the tests

**Comment by jbhoosreddy** [comment]
Is there a place where I can check if I try gets back up? @jasonLaster

**Comment by jasonLaster** [comment]
i don't know, that's a good question

**Comment by jbhoosreddy** [comment]
I talked to my friend in platform-ops and it seems we can view the status
here.

https://api.pub.build.mozilla.org/treestatus/

**Comment by clarkbw** [comment]
Trees are open again!

**Comment by jasonLaster** [comment]
I mentioned in standup that there are two issues with the console. That's actually not the case, the second issue, which was with the right sidebar object inspector was there before.

This issue has two PRs, one github facing, the other m-c..
