### ISSUE TITLE
[Flow] upgrade to 68

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5687]
68 just came out and looks pretty great

https://circleci.com/gh/devtools-html/debugger.html/11247?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

We would get stricter action types and native types, both of which are helpful

**Comment by darkwing** [comment]
@nyrosmith has an amazing start on this here:

https://github.com/devtools-html/debugger.html/pull/5893

Working off of that gets us most of the way there!
