### ISSUE TITLE
Add husky to the project

### ISSUE THREAD

**Issue by jbhoosreddy** [devtools-html/debugger.html#569]
Husky is useful for improving the quality of code pushed by contributors. It reduces a lot of noise. And prevent a lot of silly mistakes (which I also tend to make...). Seeing the recent work done here, with the perspective of contributors, I would recommend adding husky to the project also.

https://github.com/typicode/husky

**Comment by jlongster** [comment]
My only concern is that it forces you to go through the whole test suite even when pushing out documentation updates, etc. Given that we really should go through the CI 100% of the time anyway (because we have to be sure that it works in the CI environment, even if it works locally), I'd like to develop a culture where you always open a PR and wait for the CI, and run it locally if you just want to be faster. But I'm not against it if others want this.

**Comment by jbhoosreddy** [comment]
In that case, husky might not be the best solution for this use case.

**Comment by jasonLaster** [comment]
I'm also inclined to rely on CI. My issue here is that CI is an async process and I would not want to slow down the contributor workflow to catch a case that could be handled by CI

**Comment by jasonLaster** [comment]
Thanks for the suggestion. I'm interested in the project because git hooks are useful, but often poorly understood

**Comment by jlongster** [comment]
It is a neat idea, maybe could at least run the linter on push? That would catch stupid stuff but should be very quick.

**Comment by jbhoosreddy** [comment]
A hook for linting was what I had in mind. Quick to resolve and easy to fix. We get quicker feedback also instead of waiting for CI results. I'll try it out and see how it could fit in this context.

**Comment by jlongster** [comment]
You can run `npm run lint` if you don't want to wait on CI :) But I get your point.

**Comment by jbhoosreddy** [comment]
@jlongster: \me 😁

**Comment by jasonLaster** [comment]
closing for now, we might want to come back to this later.

**Comment by clarkbw** [comment]
Jumping into this late, but I can see the appeal of running `npm run lint` before a commit.  It is pretty quick and could save some time.  Lets come back to this later.

**Comment by eoger** [comment]
We did this on fxa-auth-server and fxa-content-server and we couldn't be happier.
It's also pretty simple to [set up](https://github.com/mozilla/fxa-auth-server/pull/1270/files).
Personally it saved me from a lot of shameful force-pushs and it could help newer contributors to make better PRs.

**Comment by clarkbw** [comment]
Ok, I want to come back to this.  @jbhoosreddy was right and each time I see a lint failure in the CI I'm filled with sadness. 😭 😢 

Lets give this a try, just the lint step.  Who wants to take this on?

```
"prepush": "npm run lint"
```

**Comment by jbhoosreddy** [comment]
I made a tiny PR which adds it, in case we actually want to use it.
