### ISSUE TITLE
[Preview] Support hovering on computed properties

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5691]
@bomsy recently added support for hovering on member expressions of a computed property, so for example if there was this code:

```
const director = collection.genres["sci-fi"].movies[0].director
```

The user could hover on `movies` and `director` and see the values. It would be amazing if the user could hover on `"sci-fi"` and `0` and also see values. These are common cases where it would be great to see the sci-fi genre or the first movie.

**Comment by darkwing** [comment]
@bomsy Are you working on this as well?  I thought you mentioned something like this during our early week standups

**Comment by atwalg2** [comment]
https://wax-twig.glitch.me/

**Comment by bomsy** [comment]
@darkwing True! @atwalg2  Yeah..this has been fixed already. via https://github.com/devtools-html/debugger.html/pull/5818
