### ISSUE TITLE
[QuickOpen] up arrow should not move the cursor to the front

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5698]
When quick open is open and the user is iterating over the results with the arrow keys, up arrow moves the cursor to the front of the input and down arrow moves it to the bottom. the up/down arrow keys should not affect the cursor.

![](http://g.recordit.co/aAckOZyZlf.gif)

**Comment by haoRchen** [comment]
I'm unable to reproduce the up arrow key moving cursor forward. Both up and down causes the cursor to disappear. 

![1 - reproducing issue](https://user-images.githubusercontent.com/19397242/37561127-0f29cc9c-2a1d-11e8-9002-5436083e826b.gif)

**Comment by jasonLaster** [comment]
@haoRchen i'm refering to the input text cursor... if you type `abc` up arrow moves the cursor to c, down brings it to a.

**Comment by haoRchen** [comment]
got it!
