### ISSUE TITLE
Testing - pretty printing

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#570]
It would be nice to have unit tests that exercise pretty printing creating a source as well as loading the source text.

**Comment by wldcordeiro** [comment]
@jasonLaster could you elaborate? I'm interested in helping out with debugger.html but this is a bit vague. 😛

**Comment by jasonLaster** [comment]
haha - sorry, I'd like to write a test somewhat like this one 
https://github.com/devtools-html/debugger.html/blob/master/public/js/actions/tests/sources.js#L166-L184

for pretty printing. The nice thing is everything is client side, so we can test pretty printing without relying on the debugger connection.

**Comment by jlongster** [comment]
There's another issue open so closing this (see #645)
