### ISSUE TITLE
[Preview] Previewing destructured variables

### ISSUE THREAD

**Issue by bomsy** [devtools-html/debugger.html#5706]
hovering on `variables` should show the value

```js
const { variables, functions } = symbols;
```

Here are some notes from the code to help:

```diff
diff --git a/src/utils/ast.js b/src/utils/ast.js
index a77346f..5663c82 100644
--- a/src/utils/ast.js
+++ b/src/utils/ast.js
@@ -13,7 +13,9 @@ export function findBestMatchExpression(
   symbols: SymbolDeclarations,
   tokenPos: Position
 ) {
-  const { memberExpressions, identifiers } = symbols;
+  const { memberExpressions, identifiers, objectProperties } = symbols;
+
+  // not sure if we need objectProperties but it could do the trick...
   const { line, column } = tokenPos;
   return identifiers.concat(memberExpressions).reduce((found, expression) => {
     const overlaps =
diff --git a/src/workers/parser/getSymbols.js b/src/workers/parser/getSymbols.js
index c00da50..adf7038 100644
--- a/src/workers/parser/getSymbols.js
+++ b/src/workers/parser/getSymbols.js
@@ -160,6 +160,9 @@ function extractSymbol(path: SimplePath, symbols) {
 
   if (t.isObjectProperty(path)) {
     const { start, end, identifierName } = path.node.key.loc;
+
+    // this is a good place to log...
+    // if this gets added, then maybe we want to explore using it in getExpression
     symbols.objectProperties.push({
       name: identifierName,
       location: { start, end },
diff --git a/src/workers/parser/tests/fixtures/allSymbols.js b/src/workers/parser/tests/fixtures/allSymbols.js
index bebda9f..6c6db88 100644
--- a/src/workers/parser/tests/fixtures/allSymbols.js
+++ b/src/workers/parser/tests/fixtures/allSymbols.js
@@ -31,3 +31,4 @@ class Ultra {
 }
 
 this.props.history.push(`/dacs/${this.props.dac.id}`);
+const { foo }  = { foo: 3 }
```

**Comment by bomsy** [comment]
@marcogallo566 How is this going?

**Comment by jasonLaster** [comment]
@marcogallo566 here's an AST [visualization](https://astexplorer.net/#/gist/fa0f56b4bc5e8a0e017db5da3c9e5444/e66d15b9b236cc167ffba0d557ed51ef07a8a139)

<img src='https://shipusercontent.com/f565e92437aac415abd75d4a81ad4274/Screen%20Shot%202018-04-01%20at%201.27.10%20PM.png' title='Screen Shot 2018-04-01 at 1.27.10 PM.png' width=633>
<img src='https://shipusercontent.com/af646f5adfcda5d1d31c73e4ef837585/Screen%20Shot%202018-04-01%20at%201.26.56%20PM.png' title='Screen Shot 2018-04-01 at 1.26.56 PM.png' width=627>

**Comment by jasonLaster** [comment]
I looked in the `getSymbols.spec.js` test results and found some nice things

we have a fixture `destructuring.js` and find some interesting things:

`getSymbols.spec.js.snap`

<img src='https://shipusercontent.com/d971741b2b49e62e768c4ea74acf15b1/Screen%20Shot%202018-04-01%20at%201.32.02%20PM.png' title='Screen Shot 2018-04-01 at 1.32.02 PM.png' width=1368>
<img src='https://shipusercontent.com/6f165eb8146f89b9bf3b712fb57b13ca/Screen%20Shot%202018-04-01%20at%201.29.41%20PM.png' title='Screen Shot 2018-04-01 at 1.29.41 PM.png' width=1398>

**Comment by marcogallo566** [comment]
First of all, thank you both.
@jasonLaster I'm checking `identifiers` and I found the same thing: logging in the console I found that `name` and `expression` are `undefined`, fix this will be helpful, now I'm working to this. Besides the first option is a good way, I hadn't considered it.
