### ISSUE TITLE
[Inspector] Native colors conversion

### ISSUE THREAD

**Issue by tommai78101** [devtools-html/debugger.html#5717]
This is what Chrome has, a native support for color conversion on the fly.

![](https://i.imgur.com/PyHempw.gif)

And this is what we have for Firefox.

![](https://i.imgur.com/PbWaf3O.gif)

I would like to request for the color picker to support native color conversion, and allow the users to enter in specific color values when the color picker is opened.

I find such features for converting colors across HSV, RGBA, and Hex useful when determining what colors to make out of, and it would be to see it on Firefox.

**Comment by jasonLaster** [comment]
Thanks. This should be filed in bugzilla's inspector component.

**Comment by tommai78101** [comment]
Thanks. Will do.
