### ISSUE TITLE
[SourceTree] ProjectDirectoryRoot: Multiple "/" Set

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5720]
STR:

0.  Ensure you have no directory root set:  `dbg.prefs.projectDirectoryRoot = "";`
1.  Go to https://davidwalsh.name
2.  Right-click 'davidwalsh.name', click 'Set Directory Root'
3.  Right-click 'wp-includes/js', click 'Set Directory Root'
4.  Go to https://yahoo.com
5.  Right-click 'www.yahoo.com`, click 'Set Directory Root'
6.  Right-click any other domain, click 'Set Directory Root'
7.  Check `dbg.prefs.projectDirectoryRoot` each time -- the directory root never changes -- instead a `/` is simply appended to the root

**Comment by fvsch** [comment]
Should this bug titled "[SourceTree] …" (not plural), so that it can be grouped with the others?

**Comment by jasonLaster** [comment]
@fvsch good call

**Comment by darkwing** [comment]
We can close this since the PR merged earlier today for clearing sources will no longer allow setting a new root on a different domain without clearing first.
