### ISSUE TITLE
[Sources] Item Path:  Loses parent path after a while

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5731]
STR:

1.  Go to https://davidwalsh.name
2.  Continue to set root directory on the first child directory recursively (via right-click, "Set Project Root")
3.  Eventually the project root loses its complete parent path: 

<img width="1415" alt="path-wtf" src="https://user-images.githubusercontent.com/46655/37667454-0c67eaa6-2c30-11e8-8301-d70bba6b6820.png">

**Comment by darkwing** [comment]
A bit more information:

<img width="1415" alt="better" src="https://user-images.githubusercontent.com/46655/37667615-68a261b6-2c30-11e8-8cd0-0c6b7ad01e92.png">

**Comment by jasonLaster** [comment]
closing as i think this is fixed now
