### ISSUE TITLE
Breakpoints don't work in node inspect

### ISSUE THREAD

**Issue by vxcamiloxv** [devtools-html/debugger.html#5739]
In Firefox for Node don't show the debugger buttons and when ran `node--inspect-brk  bin/pump` nothing happens, the debugger didn't show anything (only the code) and with `--inspect` the code ran but when I put some breakpoints didn't work.

Firefox v59
Node v8.10
Debugger v0.6.0
Gnu/Linux (Parabola/Arch)

**Screenshots**

![screenshot-2018-03-21_10-01-41](https://user-images.githubusercontent.com/14242544/37717946-9535e288-2cef-11e8-9b38-19fabdcf0b96.png)
![screenshot-2018-03-21_10-05-06](https://user-images.githubusercontent.com/14242544/37717947-9552d03c-2cef-11e8-9a6c-840f2281a781.png)

**Comment by jasonLaster** [comment]
hi, thanks for looking into this. We're not trying to support node at the moment.
