### ISSUE TITLE
[SourceTree] Missing path segment for resource:// and extension:// URLs

### ISSUE THREAD

**Issue by fvsch** [devtools-html/debugger.html#5759]
In Firefox Nightly 2018-03-22:

<img width="242" alt="screenshot" src="https://user-images.githubusercontent.com/243601/37796352-61cdeac0-2e17-11e8-8219-3e347a37243a.png">

Sources on the `resource://` and `extension://` protocols are missing the first path segment after the protocol (or is that considered a domain maybe?).

Example with two source URLs:

```
moz-extension://39d86772-227a-3143-96fc-2e1cee5d25ae/content.js
resource://gre/modules/ExtensionContent.jsm
```

Displayed:

```
moz-extension://
    content.js

resource://
    modules
        ExtensionContent.jsm
```

Expected:

```
moz-extension://39d86772-227a-3143-96fc-2e1cee5d25ae
    content.js

resource://gre
    modules
        ExtensionContent.jsm
```

or maybe:

```
moz-extension://
    39d86772-227a-3143-96fc-2e1cee5d25ae
        content.js

resource://
    gre/modules
        ExtensionContent.jsm
```

PS: please disregard the dark boxes in the screen shot, they're probably due to WebRender.

**Comment by jasonLaster** [comment]
Thanks for filing @fvsch. Sorry for the delay. Could you share a good STR?

**Comment by jasonLaster** [comment]
Thanks @fvsch
