### ISSUE TITLE
[QuickOpen] File search should use the directory root

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5760]
The new debugger project root is amazing! It really simplifies the source tree when work working with large projects. We should try and use the directory root to simplify Quick Open:

1. we should only show files that match the root
2. we should truncate the file paths so you only see the part of the relevant part of the path

### Quick Open

![Screen Shot 2018-03-22 at 6.30.24 PM.png](https://shipusercontent.com/00ae4c856f25082093e9e25d0daeb3ac/Screen%20Shot%202018-03-22%20at%206.30.24%20PM.png)

### Directory Roots

![Screen Shot 2018-03-22 at 5.59.29 PM.png](https://shipusercontent.com/9b76e3b378ca00fc27bc69daa1778ee5/Screen%20Shot%202018-03-22%20at%205.59.29%20PM.png)

**Comment by darkwing** [comment]
Whoa, great idea!
