### ISSUE TITLE
[SecondaryPane] should not allow text selections

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5762]
STR
1. add a breakpoint
2. select the breakpoint and drag your mouse down 

:/

![Screen Shot 2018-03-22 at 6.42.00 PM.png](https://shipusercontent.com/2172bb810a3451ff458968c43ac70ffd/Screen%20Shot%202018-03-22%20at%206.42.00%20PM.png)

**Comment by darkwing** [comment]
The fix for this will likely be:

```css
-moz-user-select: none;
  user-select: none;
```

for the `.secondary-panes` selector

**Comment by ph3n0m666** [comment]
most modern browsers:

.secondary-panes {
  user-select: none;
}

every possible browser (or as I call it - overkill :) 
.secondary-panes {
  -webkit-touch-callout: none;
    -webkit-user-select: none;
     -khtml-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
}

**Comment by buttersnipps** [comment]
\claim

**Comment by buttersnipps** [comment]
Added the suggested changed to stop users from selecting text on the secondary pane
https://github.com/devtools-html/debugger.html/pull/5775
