### ISSUE TITLE
Implement Photon ResultList Design

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5770]
@violasong has provided the following mockups for our result list design:

![photo-dropdown-design](https://user-images.githubusercontent.com/46655/37837918-84fd156c-2e84-11e8-9326-4dd52c181bf2.png)

Once @marcogallo566's PR https://github.com/devtools-html/debugger.html/pull/5729 has been merged, the last remaining piece is adding the tab/"JS" image, which can be found here:

https://design.firefox.com/icons/viewer/

**Comment by MicahRamirez** [comment]
Just making sure I understand the behavior for showing "JS" versus "Tab" image: 
We show the tab image in a ResultList item if there exists a tab with path equal to the ResultList item path?

I wasn't able to find the "JS" image within the provided link. Tab was there, but JS wasn't.
