### ISSUE TITLE
Source Search Show Empty Item

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5785]
STR:
- Go to https://davidwalsh.name
- Hit Command+P
- Scroll down
- You'll see an empty item in the result list

When hovering over said Item, the title is "/", so I believe we need that to say "(index)" instead.

<img width="700" alt="indexitem" src="https://user-images.githubusercontent.com/46655/37926565-4555c104-30fd-11e8-8903-5fee50d6cb67.png">

**Comment by jasonLaster** [comment]
Nice find
