### ISSUE TITLE
Scopes pane doesnt update

### ISSUE THREAD

**Issue by JasonWeathersby** [devtools-html/debugger.html#579]
When selecting different frames the scopes pane does not update with the proper variables. I was able to fix this by changing the pause reducer action type SECLECT_FRAME

```
    case constants.SELECT_FRAME:
      let intermState = state.setIn(["pause", "frame", "scope"], fromJS(action.frame.scope));
      return intermState.set("selectedFrame", action.frame);
```

Not sure this is the best way to handle this though.

**Comment by clarkbw** [comment]
This is awesome!  

![2016-08-24 21_47_20](https://cloud.githubusercontent.com/assets/2134/17957170/5ab8151e-6a44-11e6-8b44-053ec7a03f09.gif)

I think you could just do this (1 line change):

```js
    case constants.SELECT_FRAME:
      state = state.setIn(["pause", "frame", "scope"],
                          fromJS(action.frame.scope));
      return state.set("selectedFrameId", action.frame.id);
```

But we need @jasonLaster or @jlongster to take a look

**Comment by JasonWeathersby** [comment]
Thanks Jason. l originally got it to work by passing in the selected frame to the scopes component but that required a bit more code and adding more data to the scopes component did not make sense to me.
