### ISSUE TITLE
Reference to the original script is lost

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#5791]
This happens when investigating https://webcompat.com/issues/6830

## Steps to reproduce

1. With Firefox Android (WebIDE) or Firefox Desktop/Responsive Design mode with Firefox android UA
2. Go to https://secure.fnac.com/MyAccount/Wishlist/Home
3. Login with Google (for example)
4. tap create my first list "Créer ma première liste"
5. A rectangle happen with "Nommer ma liste"
6. Inspect this rectangle and search for the `input` element
7. Click on event list associated with the `input` (image 1)
8. Click on focus
9. Click on the arrow to access the script (image 2)

Actual:
We get a window with one line `jsli.Transformation` and the tab has the title `headermobile.js`

Expected:
Reach the real `headermobile.js` script.

See Chrome devtools. (Image 3). The line `jsli.Transformation` is in the VM2237 tab.

### image 1
<img width="966" alt="capture d ecran 2018-03-27 a 10 18 21" src="https://user-images.githubusercontent.com/505230/37941757-c2b83c00-31aa-11e8-83bb-9bffb88cda33.png">

### image 2
<img width="750" alt="capture d ecran 2018-03-27 a 10 19 06" src="https://user-images.githubusercontent.com/505230/37941769-d012bbfa-31aa-11e8-8cc7-8e6619ef8e65.png">

### image 3
<img width="1497" alt="capture d ecran 2018-03-27 a 10 36 08" src="https://user-images.githubusercontent.com/505230/37941779-d87a6f7c-31aa-11e8-9712-81d1fef891d3.png">

**Comment by jasonLaster** [comment]
This is likely a distinction without a difference, but could you file this bug in the Inspector component in devtools. The logic for finding the appropriate location is there.
