### ISSUE TITLE
[Sources] Consider Higher Level Sources Filtering

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5797]
The Project Directory Root feature was added long after the project was started.  This feature introduced filtering of sources for the tree, but we also want to filter sources for quick open searches.  

Instead of filtering sources in multiple places, I believe we should filter sources at the highest level.  In this case, when no root is set (""), all sources are retrieved and available everywhere; if a root is set, filtered sources are retrieved and available everywhere. I'm not suggesting we create a `getFilteredRootSources` function; I'm suggesting we make the main source retrieving functionality, `getSources`, return filtered root sources.

I'd ask: how often do we want to retrieve all sources *not* under a given root?  I'm guessing not as often.  By making `getSources` act as the "source of truth" for sources we care about now, we can save ourselves the need to filter sources in multiple spots.  We'd need to add a `getAllSources` function to retrieve every source in the case we'd need them.

**Comment by AnshulMalik** [comment]
I agree. This will help at a lot of places.

**Comment by jasonLaster** [comment]
Thanks @darkwing, I think it is great to step back and look at how we support directory roots throughout the UI.

As a general rule of thumb, I think it is helpful to extract shared UI logic out of the components and into Redux, either as a reducer store field or reducer selector.

I like the idea of adding a selector `getFilteredRootSources`, which would be similar to how `getVisibleBreakpoints` works. Notice how it first filters and then formats the breakpoints:

```js
export function getVisibleBreakpoints(state: OuterState) {
  const selectedSource = getSelectedSource(state);
  if (!selectedSource) {
    return null;
  }

  return getBreakpoints(state)
    .filter(bp => isVisible(bp, selectedSource))
    .map(bp => formatBreakpoint(bp, selectedSource));
}
```

The advantage of this approach is 

1. we simplify components
2. we dry up the code
3. we (could) memoize the values with re-select
4. it is opt-in in that components that care can connect to the new selector. Consumers that do not care are not affected.

**Comment by darkwing** [comment]
@jasonLaster created the filtered source selector, so we can close this.
