### ISSUE TITLE
[Scopes] stepIn shows <Scopes unavailable>

### ISSUE THREAD

**Issue by julienw** [devtools-html/debugger.html#5816]
STR:
1. open https://spotty-walker.glitch.me/
2. Open the index file in the debugger
3. Add breakpoints at the first lines of both functions (lines 10 and 14)
4. Reload the page
=> We breaks in `test1`, everything looks OK.

5. After stepping in, we get "scope unavailable" when it breaks at the second breakpoint:

![Capture](https://user-images.githubusercontent.com/454175/38080240-316e131c-3341-11e8-9feb-1f91033156b6.png)

What's extremely weird is that it happens 100% in one of my installs (nightly, english, few addons), and 0% on another install (different profile, also nightly, but french locale, and slighly more addons).

Here is the full code for the example:
```html
<!doctype html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta name='viewport' content='initial-scale=1'>
  </head>
  <body>
    <script>
function test1(foo = "bar", native = true) {
  const hello = "world";
  console.log(foo, native, hello);
}
function test2(foo, native) {
  const hello = "world";
  console.log(foo, native, hello);
}

test1();
test2();
    </script>
  </body>
</html>
```

**Comment by julienw** [comment]
Ah, looking at it closer, I realize the first break happens in [React Addon](https://addons.mozilla.org/en-US/firefox/addon/react-devtools/). Still the display and the call stack are strange.

**Comment by julienw** [comment]
OK, disabling the React Addon, I don't have the first issue, but I still get "scope unavailable" after stepping in, in the same profile.

**Comment by jasonLaster** [comment]
Thanks, it's good that we don't need the addon to repro.

**Comment by darkwing** [comment]
No longer happens.
