### ISSUE TITLE
create introduction screencast

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#582]
via https://github.com/devtools-html/debugger.html/issues/349#issuecomment-241413316

> [...] a lot of new contributors would be anxious about getting started. Even though our doc explains the steps, it might still seem like a lot. One fix would be a quick five minute video that goes through all of the steps of clone, install, start a browser, start the server. [...]

**Comment by jasonLaster** [comment]
ping @clarkbw are you interested in taking a stab at this soon?

**Comment by clarkbw** [comment]
Yeah, I've been meaning to get back to this.  Thanks for the reminder!

**Comment by jasonLaster** [comment]
I'll take this!

**Comment by clarkbw** [comment]
I believe this was done in #1379
