### ISSUE TITLE
Move some devtools-core packages to debugger.html

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#5820]
cc @jasonLaster @nchevobbe 

Per the discussion on https://github.com/devtools-html/rfcs/issues/40 we should get started on moving the packages used by the debugger to this repository.

The action items we decided during our meeting were:
- move packages for reps, components and tree from devtools-core to debugger.html
- do not rename the debugger.html repo
- stop publishing packages from debugger.html to npm
- keep package.json files to have clear dependencies
- all dependencies within debugger.html will be file path dependencies
- move all issues about reps, components and tree to debugger.html
- history of commits will not be preserved when moving the code, but the move commit will point to the original repository
- do not change the release process to mozilla-central
- issue management will be separated between debugger-related issues and ex-devtools-core issues. @nchevobbe will not necessarily mirror what the debugger team does (e.g. closing issues not being worked on)
- new labels will be introduced for all packages

**Comment by nchevobbe** [comment]
Done in https://github.com/devtools-html/debugger.html/pull/6068 (wip) , https://github.com/devtools-html/debugger.html/pull/6079 and https://github.com/devtools-html/debugger.html/pull/5824

**Comment by nchevobbe** [comment]
All PR are merged now, we can close this :)
