### ISSUE TITLE
[Breakpoints] [PrettyPrint] Pretty breakpoints are missing on reload

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#5827]
Steps to reproduce

1. With Firefox Nightly 61.0a1 (2018-03-29) (64-bit)
2. Responsive Design Mode/Firefox Android UA/ touch enable
3. Go to http://peggo.tv/
4. Open debugger 
5. Find http://d3ud741uvs727m.cloudfront.net/?vudud=713949
6. prettify the script (you need to go through the tab, the `{}` is not available. Another bug)
7. find `n.prototype.Sb = function (a) {… etc …}`. 
8. set a breakpoint inside
9. Reload the page

Expected:
The script breaks where we told it to break and we can step in.

Actual:
The full context seems to have been reloaded. The breakpoint is lost. The debugger is stopped. But no code to view.

PS: issue discovered by attempting analysis on https://webcompat.com/issues/16226

**Comment by jasonLaster** [comment]
Thanks. I was seeing the same thing yesterday when I was looking at another pretty print issue!
