### ISSUE TITLE
[Preview] No preview for empty strings and false booleans

### ISSUE THREAD

**Issue by kootoopas** [devtools-html/debugger.html#5829]
### EDIT: This is already fixed, although I stumbled upon the issue on nightly, which uses a slightly outdated debugger.html. I just wish that there was a way to use the github master's version of the debugger on nightly so that when someone bumps on an issue while developing sth else they know that it's valid.

Oh well, here's the issue anyway. `¯\_(ツ)_/¯`

### STR

* copy these into the file scope you want to debug:
```javascript
    const heey = false;
    let heey1 = false;
    let heey2 = true;
    const heey3 = heey;
    const undef = undefined;
    const emptyString = "";
    const nullDef = null;
    const stringDef = "something";
```
* add a breakpoint to that scope
* make the code run to pause it
* on pause, hover over the variables to trigger their preview popup

### ER
All variables should trigger the `Preview` popup.

### AR
All variables do, except for variables that hold empty strings or false booleans:
![screen shot 2018-03-30 at 13 53 50](https://user-images.githubusercontent.com/601001/38136312-4996514e-3426-11e8-8dda-321b71ba02e6.png)
![screen shot 2018-03-30 at 13 53 59](https://user-images.githubusercontent.com/601001/38136313-49bae55e-3426-11e8-9095-63851389fe4d.png)
![screen shot 2018-03-30 at 13 59 23](https://user-images.githubusercontent.com/601001/38136314-49e77a06-3426-11e8-81ea-c72fd0123736.png)
![screen shot 2018-03-30 at 13 59 29](https://user-images.githubusercontent.com/601001/38136316-4a0bd82e-3426-11e8-8eb7-bcbb47068fb6.png)
![screen shot 2018-03-30 at 13 59 40](https://user-images.githubusercontent.com/601001/38136317-4a3855f2-3426-11e8-9ea2-abb181866f11.png)
![screen shot 2018-03-30 at 14 00 25](https://user-images.githubusercontent.com/601001/38136318-4a5ad0be-3426-11e8-9150-a14125f295f3.png)

### Source of the problem
The falsy check of the `value` prop in `renderPreview` of `src/components/Editor/Preview/Popup.js` is responsible for this:
```javascript
  renderPreview() {
    const { value } = this.props;
    if (!value) {
      return null;
    }
```

**Comment by jasonLaster** [comment]
Thanks. I think you persuaded me to write a mochitest for these cases today!

I've been thinking about it.

**Comment by jasonLaster** [comment]
i'm seeing this issue in the panel :)

**Comment by kootoopas** [comment]
@jasonLaster  Oh really? Weird, because once I pulled from the latest master and run the debugger all was well. :)

**Comment by kootoopas** [comment]
There's specific commentary about the cases I'm describing in `renderPreview()`:
```javascript
  renderPreview() {
    // We don't have to check and
    // return on `false`, `""`, `0`, `undefined` etc,
    // these falsy simple typed value because we want to
    // do `renderSimplePreview` on these values below.
```

**Comment by juliandescottes** [comment]
This is the 3rd time this issue regresses (#3944 , #5241 and this issue), thanks for finally adding a test  :)

**Comment by bomsy** [comment]
I think this can be closed!
