### ISSUE TITLE
Persist tabs across debuggee refreshes

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#583]
We should persist tabs across debuggee and debugger close/opens. This means that you always keep your debugger's editor tabs open.

Here's a preliminary [patch](https://gist.github.com/22ec423591d7d8c9ced683385f4f05fe) that i think is pretty close.

You can get setup by doing:

```
curl https://gist.githubusercontent.com/jasonLaster/22ec423591d7d8c9ced683385f4f05fe/raw/faac253bdfc0ff47ed98de8d69fb48083cf57103/foo.diff |  git apply
```

This is a somewhat advanced issue because it touches our reducers and how sources load. Should be fun if you're up for it!

**Comment by jasonLaster** [comment]
ping @jbhoosreddy are you still interested in taking a stab at this?

@jlongster I forgot if we've settled on a good approach for this

**Comment by jlongster** [comment]
Can't remember exactly either. The difficulty is a tab is currently tied to a sourceId, but we don't have the new source's sourceId's when the NAVIGATION action is resetting the state. Need to give tabs the ability to just be tied to a URL as well, and if it has just a URL it resolves it first when clicked.

**Comment by jlongster** [comment]
There are UX issues too: what happens if that source doesn't exist anymore, etc

**Comment by jasonLaster** [comment]
This issue is ready to be `up for grabs`.

@bomsy, @kareniel, @jagtalon are you interested?

**Comment by jagtalon** [comment]
@jasonLaster would like to tackle it!

**Comment by kareniel** [comment]
@jagtalon dang, you fast :smile:

**Comment by jagtalon** [comment]
@kareniel haha I just happened to open my email at that time

**Comment by jasonLaster** [comment]
🔫  🔫

**Comment by jasonLaster** [comment]
@jagtalon how's it going? Let me know if you have any questions, this is a *tricky* one.

**Comment by jagtalon** [comment]
Hey, Jason! Sorry for the delay I got bogged down this week by stuff.
Will work on it this week!

Thank you!


On Tue, Nov 15, 2016, at 01:53 PM, Jason Laster wrote:
> @jagtalon[1] how's it going? Let me know if you have any questions,
> this is a *tricky* one.
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
>


Links:

  1. https://github.com/jagtalon
  2. https://github.com/devtools-html/debugger.html/issues/583#issuecomment-260731696

**Comment by jasonLaster** [comment]
no worries, take your time :)

**Comment by jasonLaster** [comment]
Hey @jagtalon I took another stab at the solution this morning. It's actually pretty similar to the first approach, but probably more up to date as the code has changed a bit

https://gist.github.com/dc054cf627109a9d1921dfe0bec2961a

as a reference, you can take a look at how we persist breakpoints and the selected source as well.

**Comment by jagtalon** [comment]
Thank you! Working on it this weekend! Really sorry for the delay on
this.




On Sat, Nov 19, 2016, at 08:23 AM, Jason Laster wrote:

> Hey @jagtalon[1] I took another stab at the solution this morning.
> It's actually pretty similar to the first approach, but probably more
> up to date as the code has changed a bit
> https://gist.github.com/dc054cf627109a9d1921dfe0bec2961a



> as a reference, you can take a look at how we persist breakpoints and
> the selected source as well.
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
> 


Links:

  1. https://github.com/jagtalon
  2. https://github.com/devtools-html/debugger.html/issues/583#issuecomment-261713600

**Comment by jagtalon** [comment]
@jasonLaster ok I might not be able to get to this this week. :( All you, @bomsy @kareniel!

**Comment by jasonLaster** [comment]
no worries, i'll drop the in progress label

**Comment by arthur801031** [comment]
@jasonLaster 

I will take a stab at this :)
