### ISSUE TITLE
[Preview] TypeError: undefined has no properties

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5834]
## Steps to Repeat

1.  Create a breakpoint
2.  Refresh the source page
3.  Hover your mouse somewhere inside of the editor
4.  See: "TypeError: undefined has no properties" ; preview.js: line 182:33

**Comment by jasonLaster** [comment]
@darkwing can you share an example URL and source where you set the breakpoint and paused?

**Comment by darkwing** [comment]
It's possible this bug was fixed by an unrelated update to Preview; I'll keep an eye out and re-open once I see it again and have STR.
