### ISSUE TITLE
File Search - close ui

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#584]
It would be nice to have a button in the top right for exiting file search

![screen shot 2016-08-25 at 4 32 18 pm](https://cloud.githubusercontent.com/assets/254562/17984891/4d06b13a-6ae1-11e6-8679-9a4ebbf58cc2.png)

Here's a sketch of what the change could look like:
```diff
diff --git a/public/js/components/App.js b/public/js/components/App.js
index 306f664..764a100 100644
--- a/public/js/components/App.js
+++ b/public/js/components/App.js
@@ -46,6 +46,7 @@ const App = React.createClass({
   displayName: "App",
 
   getInitialState() {
+    // here's the flag for search!
     return {
       searchOn: false
     };
@@ -67,6 +68,10 @@ const App = React.createClass({
     this.setState({ searchOn: !this.state.searchOn });
   },
 
+  closeFileSearch() {
+    this.setStae("searchOn", false);
+  },
+
   onKeyDown(e) {
     if (e.key === "Escape") {
       this.setState({ searchOn: false });
@@ -75,13 +80,19 @@ const App = React.createClass({
   },
 
   renderSourcesSearch() {
-    return Autocomplete({
-      selectItem: result => {
-        this.props.selectSource(result.id);
-        this.setState({ searchOn: false });
-      },
-      items: searchResults(this.props.sources)
-    });
+    return
+    dom.div({},
+       dom.div({className: "close-button"},
+        // insert an SVG or the right html code for an X whatevs
+       ),
+       Autocomplete({
+        selectItem: result => {
+          this.props.selectSource(result.id);
+          this.setState({ searchOn: false });
+        },
+        items: searchResults(this.props.sources)
+      })
+    }
   },
 
   renderEditor() {
```

**Comment by wldcordeiro** [comment]
I could do this. @jasonLaster 

> It would be nice to have a button in the top right for exiting file search

Like an `x` in the far right of the search bar?

Regarding that patch? Is that just a concept/idea for how you could do it?

**Comment by jasonLaster** [comment]
Concept. Wrote it quickly

I was thinking top right of the pane.

X in the input in my mind would clear the search... Could be persuaded
though

**Comment by wldcordeiro** [comment]
Could the div wrapping the two be given padding around the input and place the x just outside the input?

**Comment by wldcordeiro** [comment]
Working on styling the button now. Is there preference on units and layout? I started using flexbox, but want to make sure I'm writing things that fit in.

**Comment by jasonLaster** [comment]
@wldcordeiro flexbox is perfect. We use that in several places

**Comment by wldcordeiro** [comment]
Should be closeable.
