### ISSUE TITLE
[feature] Show the iteration values in each/foreach loops.

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#5840]
When iterating by stepping into the code  in a loop like this one below or `$.each`

```js
const items = ['item1', 'item2', 'item3'];
items.forEach(function(item){
  //some code
});
```

make visible in the UI the current value of the `item`, probably near the code itself.

**Comment by karlcow** [comment]
Bonus: Show the previous and the next value when possible.

**Comment by jasonLaster** [comment]
This is a cool feature! We would love to work on UI improvements like this in the summer/fall.

I'm going to move this to the icebox and we'll pick it up later.
