### ISSUE TITLE
[Sources] Selection issue with active state and scrolling

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#5844]
Nightly 61.0a1 (2018-04-01) (64-bit), OSX.

STR:
- Opened https://q7mmol9xy9.codesandbox.io/
- Select `external "system"` and `external "file"` entries

AR: Selection is something not maintained and scrolling issue.

![screenflow](https://user-images.githubusercontent.com/8599/38205136-501ecfba-365a-11e8-80b7-c43e7c503010.gif)

I think I saw missing `:active` (as in current file opened) in the sources panel before, this might be related.

**Comment by darkwing** [comment]
My site has the same highlight issue with the following URL's item:

https://ad.doubleclick.net/ddm/adj/N366601.452584BUYSELLADS.COM/B9719141.131867274;dc_ver=41.108;sz=180x150;u_sd=2;dc_adk=2036841227;ord=sjv93r;dc_rfl=1,https%3A%2F%2Fdavidwalsh.name%2F$0;xdt=1;crlt=UNf*RH5!on;sttr=40;prcl=s?

**Comment by darkwing** [comment]
This might be related:  https://github.com/devtools-html/debugger.html/issues/5918

One thing in common with all of the highlight issues I've had, as well as the example you've cited, is that the source URLs don't have a file extension.
