### ISSUE TITLE
[bug] ev flag disappears when moving cursor away

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#5857]
Using Firefox Nightly 61.0a1 (2018-04-04) (64-bit) on macos

1. Go to https://play.google.com/store/apps/details?id=org.mozilla.firefox
2. "Inspect Element" one of the 3 vertical dots in the Reviews section
3. The inspector opens probably on `<span class="DPvwYc NE4Eeb" aria-hidden="true"></span>`
4. Go back to the browser window and hover the 3 dots.

Actual: 
The event flag appears on a nesting `div` above. Move out to the browser window back to the Inspector. The event flag disappears

Expected:
Leave the flag in place so I can have a chance to click it to explore the scripting. 😛

**Comment by jasonLaster** [comment]
Is this an inspector bug? If so, it should be filed in bugzilla

**Comment by karlcow** [comment]
@jasonLaster Yeah I was hesitant. I'm not sure if it's debugger or Inspector. But it's happening in the inspector. Let me do that.

**Comment by karlcow** [comment]
Duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1451594
