### ISSUE TITLE
Dark theme makes it hard to see what is highlighted in response (Network tab)

### ISSUE THREAD

**Issue by Tazmain** [devtools-html/debugger.html#5858]
In the network tab the dark theme makes it really difficult to see exactly what has been highlighted. 

![image](https://user-images.githubusercontent.com/9366533/38361327-47bcbe66-38cd-11e8-82a2-e6cac776d10a.png)

So when selecting the value in the headers or response (json) the dark theme makes it impossible to see what exactly has been highlighted. 

When the line is not highlighted it is easier to see what exactly has been highlighted.

**Comment by jasonLaster** [comment]
Hi @Tazmain, I think this is a network monitor bug. Could you file it in: http://bugzilla.mozilla.org/
