### ISSUE TITLE
[Preview] Popup gets clipped

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5862]
The preview popup recently started getting clipped. I think it is related to the new Reps version, but should be easy to disect...

<img src='https://shipusercontent.com/c827394232f15afcbc0778cb4127b804/Screen%20Shot%202018-04-05%20at%208.55.00%20AM.png' title='Screen Shot 2018-04-05 at 8.55.00 AM.png' width=502>

**Comment by marcobeltempo** [comment]
I would like to take on this issue. 
@jasonLaster I used `yarn link` to connect devtools-core, I'm just unsure how to run it.

**Comment by jasonLaster** [comment]
Hey @marcobeltempo feel free to. I'm not sure if yarn link will work, my recomendation is to change the files in the node modules directory and then apply that patch in devtools core

**Comment by nchevobbe** [comment]
@jasonLaster is this still an issue ? I tried to reproduce with latest master with no luck.
What's the STR ?
