### ISSUE TITLE
[ProjectSearch] Focus state colors are a bit off

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5863]
I'm a big fan of our project search keyboard navigation, but along the way we allowed our focus state colors to get have an off blue

I think our indentation is a bit off too...

Should be pretty easy to fix these things with some CSS

![](http://g.recordit.co/KeVrOhQWWh.gif)

**Comment by dimitardanailov** [comment]
@jasonLaster 

Could you share with me steps: How this issue / feature can be reproduced ?

**Comment by jasonLaster** [comment]
1. cmd+shift+f
2. type something and enter
3. tab over to the item
