### ISSUE TITLE
Suggestion: Add Editorconfig file

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#588]
Something that would be a nice developer convenience would be a simple [EditorConfig](http://editorconfig.org/) file. With how many different standards there are to spacing and stuff, it's nice to be able to leave your editor defaults as is and let the project dictate.

I could PR one but I figured I'd make an issue first.

**Comment by jasonLaster** [comment]
Go for it. Would be nice to see, I think it's often helpful. Also can't hurt

**Comment by clarkbw** [comment]
This was done a while back
