### ISSUE TITLE
UX modifications to watch expressions

### ISSUE THREAD

**Issue by jbhoosreddy** [devtools-html/debugger.html#590]
The preliminary work in watch expressions was done in #403. This issue ticket is to work on fine-tuning watch expressions, and then maybe enabling it by default.

@helenvholmes do you have any suggestions on the UX. If not, I'll go ahead and work on implementing the current Firefox UX.

**Comment by jasonLaster** [comment]
removing it from the milestone as i don't think it should be considered critical for us hitting our sprint.

**Comment by clarkbw** [comment]
Here are my thoughts on the Watch Expressions interface. 

### base feature

We need an obvious way to add a variable name to the watch expressions list, this should include some kind of auto-complete to help people out with variables we know about.  This feature is for people who know what watch expressions are, how to use them, and use them frequently when solving code issues (likely not that many people).

### integrated with the editor

Taking this further I think we want to integrate with the editor.  Allow users to hover or click on a variable in the editor and add that variable to the watch list.  This adding procedure may require a popup of some kind but I think we'll want something like that to inspect variable values anyway.  I see this as a way of introducing this feature to more people.

### integrated with console logging

One other way of taking this further is to consider the watch expressions to be our method for console logging variables.  So every time the variable I'm watching changes we log that into the console.    This is how people actually debug their applications and one possible way we could integrate console logging to the debugger.

### integrated with breakpoints (conditional)

And to take the watching a step further I think it would be interesting to allow people to say `pause when $x > 10` such that the debugger pauses execution when the variable reaches a value or expression that it shouldn't.

### log / graph values over time

Last item here that I've been asked for by people who work on animations is that the watch expressions logs and can graph the output over time.  This would allow developers who are seeing lots of different values to visually see when a set of values in all the values are going out of bounds.

**Comment by jasonLaster** [comment]
I'm going to close this now as I think the first step is feature parity, and then we can focus on long term feature improvements.

**Comment by jyavenard** [comment]
It's kind of an essential feature missing... At this stage, with no easy way to check a variable content, the current JS debugger found in Nightly is rather unusable...

**Comment by jasonLaster** [comment]
Hi @jyavenard! I'm not sure what you mean by "check a variable content". I would think the console and scopes help with this. With that said, we're working on getting to parity with watch expressions over here https://github.com/devtools-html/debugger.html/issues/916

**Comment by jyavenard** [comment]
In a debug build (though it's not much better with opt build), "scopes" will take over 1 minute to open on my 8 cores mac pro. During the time scopes populate, the entire browser is unresponsive (as all happens on the main thread)
Using the console is also less than ideal everytime you want to check the value of a variable.
Hovering the mouse over the variable doesn't work (like it does in chrome), so using the watch variable had always been the fallback solution. And this is currently gone AFAICT.

**Comment by jasonLaster** [comment]
Hmm, that's a really good point. I hadn't considered the `debug build` issue. 

We have "hover" and "watch expressions" on the roadmap, but it sounds like in your case it might be helpful to disable the new debugger in the pref `devtools.debugger.new-frontend`
