### ISSUE TITLE
[Breakpoints] Create Enable/Disable Pausing Button

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5903]
Parent issue:  #5773

Implement the button in the top/right portion of the secondary pane:

<img width="294" alt="enabledisablepausing" src="https://user-images.githubusercontent.com/46655/38567187-324f6ac4-3cab-11e8-93a0-7dbe653dd586.png">

**Comment by jasonLaster** [comment]
[disablebreakpoints.svg](https://shipusercontent.com/d2d6909f645a02e13f244e4e51e63f77/disablebreakpoints.svg)

**Comment by darkwing** [comment]
Rough sketch of server work required:
https://gist.github.com/jasonLaster/7b900c3709df6ee64c52b1894488641c
