### ISSUE TITLE
[Styling] Watch Expressions refresh Breakpoints add buttons not focused

### ISSUE THREAD

**Issue by paesh1997** [devtools-html/debugger.html#5910]
After ctrl+shirt+f and tabbing through the headers, Watch Expressions refresh and Breakpoints add button can not be activated when it is focused. Instead, they are able to be activated immediately after tabbing again.

Refresh button and Add Breakpoints button should be focused when it is the active element. 

My team (@chan750) (@denigrise) and I are in @emmet0r 's Open Source Software Engineering class, and we discovered this issue while working on part of issue #4080 
![styling](https://user-images.githubusercontent.com/36204746/38573123-1e8c87ac-3cc3-11e8-8957-b58ff04668f8.gif)

**Comment by jasonLaster** [comment]
how's it going @paesh1997?

**Comment by darkwing** [comment]
The "+" button is now focusable
