### ISSUE TITLE
SourcesTree: (index) click weirdness

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5918]
The first time I click on "(index)" in the SourcesTree, the following item is focused:

```js
// console.log'ing from inside `focusItem()`
Object { name: "(index)", path: "https://davidwalsh.name/", contents: {…} }
Object { name: "(index)", path: "https://davidwalsh.name/", contents: {…} }
Object { name: "root", path: "", contents: […] }
```

If I click it again, I get:

```js
Object { name: "(index)", path: "https://davidwalsh.name/", contents: {…} }
Object { name: "(index)", path: "https://davidwalsh.name/", contents: {…} }
```

The `Object { name: "root", path: "", contents: […] }` item appears to be what throws the highlight off.  We need to figure out where that's coming from to fix this bug.

**Comment by darkwing** [comment]
The problematic `Object { name: "root", path: "", contents: […] }` item is coming from `ManagedTree`:

```js
highlightItem(highlightItems: Array<Item>) {
  // ....

  //... the last line:
  this.focusItem(highlightItems[index]);
}
```

**Comment by janodvarko** [comment]
@darkwing How can I reproduce this issue? STR?

Honza
