### ISSUE TITLE
[Breakpoints] Context Menu Items Not Working Reliably

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5926]
STR:

1.  Go to https://davidwalsh.name
2.  Open tab for https://d2zah9y47r7bi2.cloudfront.net/releases/current/tracker.js
3.  Add a breakpoint to lines 4, 10, and 20
4.  Right-click the breakpoint for line 10 in the Breakpoints list
5.  Click "Remove all others"
6.  All breakpoints are removed

Expected:  The breakpoints from line 4 and 20 are removed, 10 remains

**Comment by AnshulMalik** [comment]
Works fine for me, in launchpad.

**Comment by AnshulMalik** [comment]
Can reproduce it when the script is prettified.

**Comment by jasonLaster** [comment]
hey @pranoy10 any luck?

**Comment by darkwing** [comment]
I fixed this a while back.  yay!
