### ISSUE TITLE
TypeScript Icons Not Displaying In SourceTree

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5927]
I was looking at the Angular example in devtools-examples (http://localhost:7999/angular/sample/dist/) and the .ts files show no icon:

<img width="248" alt="notypescripticon" src="https://user-images.githubusercontent.com/46655/38593054-1335ad38-3d05-11e8-8857-b74d4da8892d.png">

**Comment by jasonLaster** [comment]
this would be good to have a unit test for

**Comment by darkwing** [comment]
Page I'm on is in the description; devtools-components: http://localhost:7999/angular/sample/dist/

**Comment by darkwing** [comment]
There's something weird going on here that I haven't figured out yet;  hovering over the URL in the DOM inspector shows that the file couldn't be loaded, but the network panel shows the file is OK but no size:

<img width="1336" alt="tswtf" src="https://user-images.githubusercontent.com/46655/38647075-1b41911c-3db0-11e8-96f7-0273dd74b77d.png">

**Comment by jasonLaster** [comment]
is that the same as this app: http://firefox-dev.tools/debugger-examples/examples/angular/sample/

**Comment by darkwing** [comment]
So I figured out what's going on; the `typescript.svg` file got corrupted because the `xmlns` and other attributes were are in the `<path>` element somehow.  I changed the contents to:

```xml
<svg viewBox="0 0 128 128" xmlns="http://www.w3.org/2000/svg" class="cls-2" id="original-2">
<path d="M 1.5 63.91 v 62.5 h 125 V 1.41 H 1.5 Z m 100.73 -5 a 15.56 15.56 0 0 1 7.82 4.5 a 20.58 20.58 0 0 1 3 4 c 0 0.16 -5.4 3.81 -8.69 5.85 c -0.12 0.08 -0.6 -0.44 -1.13 -1.23 a 7.09 7.09 0 0 0 -5.87 -3.53 c -3.79 -0.26 -6.23 1.73 -6.21 5 a 4.58 4.58 0 0 0 0.54 2.34 c 0.83 1.73 2.38 2.76 7.24 4.86 c 8.95 3.85 12.78 6.39 15.16 10 c 2.66 4 3.25 10.46 1.45 15.24 c -2 5.2 -6.9 8.73 -13.83 9.9 a 38.32 38.32 0 0 1 -9.52 -0.1 a 23 23 0 0 1 -12.72 -6.63 c -1.15 -1.27 -3.39 -4.58 -3.25 -4.82 a 9.34 9.34 0 0 1 1.15 -0.73 L 82 101 l 3.59 -2.08 l 0.75 1.11 a 16.78 16.78 0 0 0 4.74 4.54 c 4 2.1 9.46 1.81 12.16 -0.62 a 5.43 5.43 0 0 0 0.69 -6.92 c -1 -1.39 -3 -2.56 -8.59 -5 c -6.45 -2.78 -9.23 -4.5 -11.77 -7.24 a 16.48 16.48 0 0 1 -3.43 -6.25 a 25 25 0 0 1 -0.22 -8 c 1.33 -6.23 6 -10.58 12.82 -11.87 A 31.66 31.66 0 0 1 102.23 58.93 Z M 72.89 64.15 l 0 5.12 H 56.66 V 115.5 H 45.15 V 69.26 H 28.88 v -5 A 49.19 49.19 0 0 1 29 59.09 C 29.08 59 39 59 51 59 L 72.83 59 Z" data-name="original" />
</svg>
```

And now an icon properly displays.
