### ISSUE TITLE
[EmptyLines] Last Line Sometimes Not Marked Empty

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5928]
1.  Go to https://davidwalsh.name
2.  Open resource https://pagead2.googlesyndication.com/pagead/js/lidar.js
3.  Line 33, which is empty, is not marked as an empty line
4.  Click line 33, watch the breakpoint momentarily display but then disappear

<img width="917" alt="emptyline" src="https://user-images.githubusercontent.com/46655/38593389-acd72448-3d06-11e8-961b-74b52e74d48b.png">

**Comment by jasonLaster** [comment]
the bug is in parser/pausePoints.js

**Comment by nyrosmith** [comment]
Any progress on this @yalooong?
Just visit out slack if you have questions vor need help

**Comment by yalooong** [comment]
/unclaim I have to unclaim the issue now due to my work. I had spent a lot of time on this before, but unfortunately did not find a way to fix it. I will continue work on it when I have time.

**Comment by jasonLaster** [comment]
@yalooong thanks. take a look here - https://github.com/devtools-html/debugger.html/blob/master/src/workers/parser/pausePoints.js#L153-L158

**Comment by darkwing** [comment]
Since we no longer fade out empty lines, I'm going to close this.
