### ISSUE TITLE
Scopes - show <this> for all of the call stack frames

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#593]
We're currently only showing the <this> property for the first frame in the call stack, but we should show it for all frames.

![](http://g.recordit.co/JgTF9qT3he.gif)

The issue is likely [here](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/Scopes.js#L102-L105) where we check to see if we're showing the *innermost* scope, when in reality we want to show `<this>` in the local scope of every frame. The fix is likely a cleanup of `getScopes` that treats the first scope (local scope) differently than the other n-1 scopes.

This is a good bug for contributors who likely the geeky problems :)

**Comment by ThomasCrvsr** [comment]
@jasonLaster Mind if I investigate ? I'm looking to make a first contribution but don't really know where to start ^^

**Comment by jasonLaster** [comment]
Sure. I mention the file above that's the issue. 

Let me know if you have any issues running the project locally

**Comment by ThomasCrvsr** [comment]
@jasonLaster Are scopes only available for Firefox target ?
I finally make the remote-debugging work on Firefox, so I can concentrate on the behavior :)

However, I tried to reproduce what you've done : I can't even see `<this>` for `App.TodoView`.

<img width="1138" alt="screen shot 2016-08-28 at 13 01 21" src="https://cloud.githubusercontent.com/assets/4603973/18033300/d7e6a2c4-6d20-11e6-9059-393581c25938.png">

Are the relevant infos in `frame.environment.bindings` ?

**Comment by jasonLaster** [comment]
Ohh my guess is that you need to pull.  #592 fixed this so that it is available. 

@thomascrvsr if that doesn't help let me know. I'd be happy to do a quick screenhero session and reproduce it with you. 

This is a property of frame.

**Comment by ThomasCrvsr** [comment]
Okay thanks, I'll take a look at this tonight or tomorrow morning and keep
you informed !

Le dim. 28 août 2016 16:33, Jason Laster <notifications@github.com> a
écrit :

**Comment by ThomasCrvsr** [comment]
@jasonLaster : I made a draft of the fix. Basically, in `getScopes()`, when we encounter the scope with the same actor of the scope of the selected frame I add `this` variable to `vars`.

Is this the right direction to take ?
