### ISSUE TITLE
[QuickOpen] CSS icon is not showing up

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5935]
looks like we're missing an icon for CSS files... maybe this is also an issue for the source tree

![Screen Shot 2018-04-11 at 12.50.22 PM.png](https://shipusercontent.com/129771f70236b2f7a98050eed310379b/Screen%20Shot%202018-04-11%20at%2012.50.22%20PM.png)

**Comment by darkwing** [comment]
I'm not seeing a specific image for CSS files; we should set the default for images in the SourcesTree to be the file icon.
