### ISSUE TITLE
[QuickOpen] Function search matches are poorly formatted

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5936]
Looks like the photon work might have messed up the layout of function search :/

![Screen Shot 2018-04-11 at 12.51.48 PM.png](https://shipusercontent.com/3688dc29a3baaf4247553df99ddfecff/Screen%20Shot%202018-04-11%20at%2012.51.48%20PM.png)

**Comment by Sekhmet** [comment]
I checked old commit to see how it used to look like. Is it supposed to look like this?
![image](https://user-images.githubusercontent.com/1968722/38631966-8ed2d568-3dbb-11e8-98f9-3f11ee80a1f9.png)
