### ISSUE TITLE
[Testing] add license headers to all of the mochitests

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5958]
We have a couple mochitests that are missing license headers.

We should audit the list in `src/test/mochitest`.

**Comment by Sekhmet** [comment]
Some lines there use Public Domain license header. Should it be replaced with MPL or left as-is?
https://github.com/devtools-html/debugger.html/blob/e788538248139c00b69f268e39b264d98c5bc58f/src/test/mochitest/browser_dbg-async-stepping.js#L1-L5

**Comment by jasonLaster** [comment]
@Sekhmet not sure I'd compare it to these tests and then go with the most common case
