### ISSUE TITLE
[QuickOpen] Polish add 1st expression

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#5962]
Haha, thanks for this feedback, this video is making me question my whole push for a minimal empty accordion state everywhere in DevTools. (I'm also intending it for Grid/Flex https://mozilla.invisionapp.com/share/TUE5VV8MV#/screens/279164270_empty_Grid-Flex). The idea is automatically minimal UI where you don't have to manually minimize everything you never use, but it may be tricky to get it right. Since Watch Expressions is assumed to be a top 5% power nerd feature, it seemed worth making it smaller in the screen.

So, I think there are a couple things we can do to improve this: When there are 0 watch expressions, hide the refresh button, but make the plus button look dark so that it's the clear next step. Also, maybe the expander arrow should actually look/be disabled? I like @jdescottes' idea that clicking + expands the new field no matter what. (edited)

If we do the idea of just having it show the "new watch expr" input when the accordion is expanded, that sort of brings us half way back to the original functionality :smile: - and I'm definitely not opposed to that if it seems like the most natural way for this to work. Especially if the W.E. accordion is at least closed by default/on first launch. I'm guessing a closed-on-launch W.E. will remain closed for most users, so they'll still reap the minimized benefits until they someday idly click it (edited)

**Comment by darkwing** [comment]
I think all of this was addressed with Victoria's UX help
