### ISSUE TITLE
[Sources] Displayed files should have the same icons

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#5963]
Here's a screenshot where I'm paused in tree.js (a react component): 
<img width="1809" alt="image" src="https://user-images.githubusercontent.com/578107/38725208-e37d58a8-3f06-11e8-93df-973470861ae1.png">

There's 3 places where the filename is displayed: 
- source panel (JS icon)
- tab header (React icon)
- breakpoint panel (no icon)

It would be nice if we would be consistent and show the same icon in those different places

**Comment by jasonLaster** [comment]
I think this can now be easily fixed now that we have a SourceIcon component.
