### ISSUE TITLE
[Breakpoints] Show Special Icon in Group File Name

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#5970]
We have this awesome feature where we show a React icon if the file is a React file; maybe we should try showing the same icon in next to the file name in the breakpoints pane:

<img width="1182" alt="react" src="https://user-images.githubusercontent.com/46655/38753663-ba58f73e-3f24-11e8-9877-19a07b766f0a.png">

**Comment by jasonLaster** [comment]
Yeah! Even the file icon might add a nice visual call out.

**Comment by jasonLaster** [comment]
<img src='https://shipusercontent.com/264049eeacdeb8e0eff623f0097c5407/Screen%20Shot%202018-04-13%20at%205.06.29%20PM.png' title='Screen Shot 2018-04-13 at 5.06.29 PM.png' width=300>

**Comment by darkwing** [comment]
Closing as dupe https://github.com/devtools-html/debugger.html/issues/6000
