### ISSUE TITLE
Dragging the horizontal splitter offscreen ignores the mouseup event

### ISSUE THREAD

**Issue by gregtatum** [devtools-html/debugger.html#5974]
Steps to reproduce:

 * Have the debugger and console open in DevTools with the split screen like so: <img width="722" alt="image" src="https://user-images.githubusercontent.com/1588648/38763515-2c7a861e-3f63-11e8-9452-ab1d742bde42.png">
 * Drag the splitter for the toolbar with the breakpoints. <img width="720" alt="image" src="https://user-images.githubusercontent.com/1588648/38763522-42d1ac1c-3f63-11e8-91e3-c3b5a879343b.png">
 * Drag, and continue moving the mouse clearly into the webconsole screen.
 * Release the splitter in the webconsole screen.
 * Move the mouse back into the debugger screen

Expected results:
 * The splitter should no longer move.

Actual results:
 * The splitter continues to move, even though I am no longer depressing on the mouse.
 * I must click on the mouse to release it.

**Comment by AlexMolodyh** [comment]
@gregtatum - Any idea where the event handlers are located for this splitter? I've looked through a few file but can't seem to locate it. Or would you say this click event is handled by the DOM?

**Comment by AlexMolodyh** [comment]
Sweet! Thanks @jasonLaster!

**Comment by AlexMolodyh** [comment]
@jasonLaster - Any Ideas on how to reproduce this in the debugger? I can reproduce it in the browser and it only seems to happen with the console pane being open, other screens don't affect it.

**Comment by AlexMolodyh** [comment]
@jasonLaster - Any Ideas on how to reproduce this in the debugger? I can reproduce it in the browser and it only seems to happen with the console pane being open, other screens don't affect it.

**Comment by AlexMolodyh** [comment]
@jasonLaster Are node modules not to be modified?

**Comment by jasonLaster** [comment]
You can update the splitter which is in another package

**Comment by darkwing** [comment]
@jasonLaster Did you fix this?

**Comment by jasonLaster** [comment]
yep
