### ISSUE TITLE
Contents in Debugger should show human-readable Unicode domain names and Unicode filenames instead of showing Punycode domain names and URI-encoded filenames

### ISSUE THREAD

**Issue by Zhang-Junzhi** [devtools-html/debugger.html#5977]
CC [1450292][bz]

The debugger should show non-ascii url hostnames, paths, and filenames. e.g. Source Tree, Tabs, ...

STR:
1. go to https://dbg-unicode.glitch.me/
2. click on 測.js

This issue was fixed for other panes in [1448553][bz2], which provides a common module to get Unicode hostnames, Unicode URL components and Unicode URLs(see unicode-url.js, unicode-url-stub.js), so they can be reused in this bug.

### Screenshots

![Image](https://bugzilla.mozilla.org/attachment.cgi?id=8968050)

<img src='https://shipusercontent.com/7c43203656b9211ce0f920dbf806a851/Screen%20Shot%202018-04-15%20at%209.53.02%20AM.png' title='Screen Shot 2018-04-15 at 9.53.02 AM.png' width=388>

[bz]: https://bugzilla.mozilla.org/show_bug.cgi?id=1450292
[bz2]: https://bugzilla.mozilla.org/show_bug.cgi?id=1448553

**Comment by jasonLaster** [comment]
Thanks for filing. I'd like to find a good solution that re-uses your work in [unicode-url.js][url]. Perhaps we land a shim module [here](https://github.com/devtools-html/devtools-core/tree/master/packages/devtools-modules) so that the debugger has a shim locally and uses the real thing in the panel?


[url]: https://searchfox.org/mozilla-central/source/devtools/client/shared/unicode-url.js

**Comment by Zhang-Junzhi** [comment]
For now the "slim" versions for the other tools are actually stubs(E.g. [unicode-url-stub.js](https://searchfox.org/mozilla-central/source/devtools/client/shared/webpack/shims/unicode-url-stub.js))

I am not sure whether you meant an actual slim, or a stub? In other words, I would like to hear your opinion as to whether to implement an actual slim module first, or to introduce a stub to fix the debugger in the panel first? If the former, then we can hold this bug for now, and I will let you know by leaving a message here when the slim module is done.

**Comment by jasonLaster** [comment]
I think the fix involves adding the shim in devtools-modules, and then using webpack-config to point to the correct module in the panel..

**Comment by Zhang-Junzhi** [comment]
Okay, now I see what you meant the former.

I will leave a comment in this issue when the shim is implemented.

**Comment by jasonLaster** [comment]
@Zhang-Junzhi how's it going? I think this is ready to be done in the debugger

**Comment by Zhang-Junzhi** [comment]
I am sorry to disappoint, Jason. I haven't yet started looking into the Debuuger code for now. I wished I could work on this, but I don't have much time these days.

So if anyone is interested in fixing this, please feel free to take it and fix it based on my commited unicode-url shim.

**Comment by Zhang-Junzhi** [comment]
@jasonLaster I am going to work on this in a couple of days if it isn't that urgent. If anyone is going to fix it sooner, please comment here and let me know in case that both of us are working on the same issue.

**Comment by jasonLaster** [comment]
thanks
