### ISSUE TITLE
Stepping into an ES module: SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"'

### ISSUE THREAD

**Issue by mnoorenberghe** [devtools-html/debugger.html#5986]
Test case: 
STR:
1. navigate to [page](https://cdn.rawgit.com/jakearchibald/a298d5af601982c338186cd355e624a8/raw/aaa2cbee9a5810d14b01ae965e52ecb9b2965a44/)
2. Set a breakpoint on the `addTextToBody('Modules are pretty cool.');` line of the test case
3. Refresh the test case
4. When the breakpoint is hit, click "Step in"

Expected result:
Steps into the method

Actual result:
Steps onto the `export function addTextToBody(text)` line. Browser Console contains an error:

> SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (1:0) parser-worker.js:1063:5
> 	parse resource://devtools/client/debugger/new/parser-worker.js:1063:5
> 	getAst resource://devtools/client/debugger/new/parser-worker.js:1094:11
> 	traverseAst resource://devtools/client/debugger/new/parser-worker.js:1111:15
> 	extractSymbols resource://devtools/client/debugger/new/parser-worker.js:1749:16
> 	getSymbols resource://devtools/client/debugger/new/parser-worker.js:1929:19
> 	workerHandler/< resource://devtools/client/debugger/new/parser-worker.js:916:24

I'm not sure what the consequence of the error is but variable tooltips don't seem to work.

**Comment by jasonLaster** [comment]
Thanks for filing, will fix soon!

**Comment by jasonLaster** [comment]
Okay, i opened a PR for the parser error, but i think thee are other things that are preventing the sources from being delivered to the client reliably

![](http://g.recordit.co/N10GCJiDDL.gif)

**Comment by mnoorenberghe** [comment]
Maybe related to https://bugzilla.mozilla.org/show_bug.cgi?id=1443247 or https://bugzilla.mozilla.org/show_bug.cgi?id=1312180

**Comment by jasonLaster** [comment]
interesting. these are good bug reports. I'll investigate during the 62 cycle

**Comment by digitarald** [comment]
Testing 62.0a1 (2018-05-24) (64-bit) on the [test page](https://cdn.rawgit.com/jakearchibald/a298d5af601982c338186cd355e624a8/raw/aaa2cbee9a5810d14b01ae965e52ecb9b2965a44/)
 I see modules disappearing on reload

![screenflow](https://user-images.githubusercontent.com/8599/40517600-0195d1ce-5f6b-11e8-950c-6a7dcdd421ea.gif)

**Comment by darkwing** [comment]
I've seeing this "disappearing" file effect before.  As for the original issue, I cannot duplicate it; no errors when stepping in.

**Comment by jasonLaster** [comment]
closing as this is handled in the JS engine here: https://bugzilla.mozilla.org/show_bug.cgi?id=1469599
