### ISSUE TITLE
[Breakpoints] Show Source Icons with Group/File Name

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#6000]
Parent issue:  #5999

We show icons in the Source Tree and sometimes Tabs for a given resource.  Example tabs include React, Angular, Pretty Print, Blackboxed, etc.

It would be nice if we carried those over to the breakpoints UI:

<img width="307" alt="breakpointicon" src="https://user-images.githubusercontent.com/46655/38900067-ba2121ea-425f-11e8-8035-a428f4d92bc5.png">

@jasonLaster has some code in #5985 that can be borrowed.

**Comment by jasonLaster** [comment]
How's it going @abitravers1989? Anything i can do to help?
