### ISSUE TITLE
[Tabs] clarify tabs with the same filename

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6004]
Our tabs currently only show the filename. It would be nice to show the directory when there are are two tabs with the same name

<img src='https://shipusercontent.com/91f32fb43ba01c7360f128d7ae3e1b58/Screen%20Shot%202018-04-17%20at%203.37.24%20PM.png' title='Screen Shot 2018-04-17 at 3.37.24 PM.png' width=510>

![](http://g.recordit.co/V7i5MQ2iz3.gif)

**Comment by darkwing** [comment]
Great idea, and we should make this a utility function because the same could happen for breakpoint grouping

**Comment by jasonLaster** [comment]
@adancarrasco sorry this is a dupe of #6005.
