### ISSUE TITLE
[Breakpoints] Files with the same filename

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6005]
Our breakpoints are grouped by filename, unfortunately when there are two files with the same name the breakpoints are not grouped separately.

I think we should do something similar to editors and show the directory he file is in as well when there are duplicates.

<img src='https://shipusercontent.com/ba5284458b877df85ffc6627253c8682/Screen%20Shot%202018-04-17%20at%203.41.58%20PM.png' title='Screen Shot 2018-04-17 at 3.41.58 PM.png' width=362>

![](http://g.recordit.co/V7i5MQ2iz3.gif)

**Comment by buttersnipps** [comment]
Hey,
Just to be clear we want the breakpoint panel to show the directory like the editor does if files are the same name?

**Comment by darkwing** [comment]
@buttersnipps Eventually but for now simply showing the same file name label, with maybe a `title` attribute with the full path, would be great.

**Comment by jainsneha23** [comment]
@darkwing We already have title attribute with the fullpath in the filename. Can you please tell the expected output here.

<img width="632" alt="screen shot 2018-05-03 at 5 01 07 pm" src="https://user-images.githubusercontent.com/8366397/39574157-b72363fe-4ef3-11e8-8c17-43528f91689d.png">
<img width="623" alt="screen shot 2018-05-03 at 5 02 35 pm" src="https://user-images.githubusercontent.com/8366397/39574176-d327fc2c-4ef3-11e8-90bf-3ab4df9ecb7d.png">

**Comment by jasonLaster** [comment]
Hey @jainsneha23!


Oh nice point, i think this basically works. I think it would be nice to include the directory name next to the filename if they are the same. e.g:

- index.js (education)
- index.js (job)

the directory name can have a secondary grey color...

**Comment by jainsneha23** [comment]
@jasonLaster Hey there can be situations with parent folder name same as well. So, we will have to check until we get different parent folder. And we can specify the same as picture below.

<img width="698" alt="screen shot 2018-05-03 at 9 24 53 pm" src="https://user-images.githubusercontent.com/8366397/39588048-9210537c-4f18-11e8-8043-81cde42144ac.png">

**Comment by jasonLaster** [comment]
yeah, that kind of thing. good point. we should go up until its unique

**Comment by jainsneha23** [comment]
@jasonLaster And then the same should apply on the editor as well??

**Comment by jainsneha23** [comment]
@kootoopas i am working on it. 
https://github.com/jainsneha23/debugger.html/tree/issue-6005
working solution. needs optimisation though.

**Comment by jasonLaster** [comment]
hmm, i'm not sure. @jainsneha23 what were you saying?
