### ISSUE TITLE
[Tabs] Update the show more button 

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6012]
It would be nice to use the new chevron for the show more button in the tabbar

Here is how you can get it w/ CSS

```diff
diff --git a/src/components/SecondaryPanes/CommandBar.css b/src/components/SecondaryPanes/CommandBar.css
index c99c97d..32eca25 100644
--- a/src/components/SecondaryPanes/CommandBar.css
+++ b/src/components/SecondaryPanes/CommandBar.css
@@ -48,7 +48,7 @@ img.shortcuts {
 }

 .command-bar img.stepOut {
-  mask: url(/images/stepOut.svg) no-repeat;
+  mask: url(/mc/command-chevron.svg) no-repeat;
 }
```

### Tabbar
<img src='https://shipusercontent.com/4a8efb5e6fc3444e8d2536d1fef402aa/Screen%20Shot%202018-04-18%20at%2010.16.25%20AM.png' title='Screen Shot 2018-04-18 at 10.16.25 AM.png' width=384>

### Show More dropdown
<img src='https://shipusercontent.com/8553368a44822016c484efaba03f7c0d/Screen%20Shot%202018-04-17%20at%2010.02.03%20PM.png' title='Screen Shot 2018-04-17 at 10.02.03 PM.png' width=277>

**Comment by bomsy** [comment]
@jasonLaster we are a bit confused by this ticket

**Comment by jasonLaster** [comment]
@bomsy what's up?

I might have been vague w/ the css patch... you'll need to change it somewhere else :)
