### ISSUE TITLE
[Tabs] Refresh the show more dropdown

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6013]
The show more dropdown can use a bit of love. The simplest changes would be to 

- [ ] adjust the alignment of the icon
- [ ] reduce the line height of the items
- [ ] add a bit of rounded borders to the panel

### Show More dropdown
<img src='https://shipusercontent.com/8553368a44822016c484efaba03f7c0d/Screen%20Shot%202018-04-17%20at%2010.02.03%20PM.png' title='Screen Shot 2018-04-17 at 10.02.03 PM.png' width=277>

**Comment by buttersnipps** [comment]
if its ok . can I work on this ?

**Comment by buttersnipps** [comment]
Please review #6039
