### ISSUE TITLE
Intermitten re-render when switching back to debugger UI tab.

### ISSUE THREAD

**Issue by yzen** [devtools-html/debugger.html#6015]
Sorry if this is a duplicate. When I have a debugger running locally in Firefox and try to debug another tab: intermittently when I switch between tabs and go back to the debugger one, all of the UI re-renders and results in a noticeable flicker.

**Comment by jasonLaster** [comment]
hmm, i don't follow. what do you mean by running locally?

**Comment by yzen** [comment]
Sorry, all I meant was that when run the latest master on my machine.

**Comment by jasonLaster** [comment]
master in the launchpad or m-c and ./mach run?

**Comment by yzen** [comment]
Just the launchpad

**Comment by jasonLaster** [comment]
i see. what do you mean by a re-render? like a render method is called? sorry for being slow

**Comment by yzen** [comment]
I can verify that, but I see a flash of the entire debugger UI which I assumed was because of re-render, I'll double check now.

**Comment by jasonLaster** [comment]
@yzen would you mind re-testing this?

**Comment by jasonLaster** [comment]
closing this. Feel free to re-open if you can reproduce it.
