### ISSUE TITLE
[Sources] reveal in tree doesn’t work with directory roots

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6027]
STR:

1. go to todomvc
2. select `js` as the root in the tree
3. navigate to todo-view.js
4. select reveal in tree

Expected Result: it expands the tree to show the file
Actual Result: it doesnt do anything

**Comment by darkwing** [comment]
Note:

It appears that everything is going through the correct routine but `getDirectories` is returning `Object { name: "root", path: "", contents: […] }`

**Comment by darkwing** [comment]
So this gets us closer:

https://gist.github.com/darkwing/a2feb06e193014c778a5ed87265ab070

The *only* side effect I can find is that trying to set a root under a root under a root doesn't show the sources they should, mostly like because of changing line 127 from `-1` to `-2`
