### ISSUE TITLE
[Editor] When clicking on link from Console to show where an error occurred, code fails to scroll to cursor

### ISSUE THREAD

**Issue by tommai78101** [devtools-html/debugger.html#6036]
Here's a GIF of what I meant by "clicking on link from Console, and not scrolling editor pane to show where the cursor is at".

![gif](https://user-images.githubusercontent.com/6444116/39066046-be278894-44a1-11e8-803f-1e9a2f85c27c.gif)

The cursor will be off the screen beyond what the user can see in the Code view (viewport). The problem is, the code view doesn't scroll horizontally to the cursor. It will always start off on the leftmost side of the code view, and does nothing.

Here's what it's showing in Chrome:

![gif](https://user-images.githubusercontent.com/6444116/39066209-4b149dc8-44a2-11e8-9b8d-f16ff48ad4d1.gif)

What happens is, the cursor jumps to the error in the code, and the code view scroll to the cursor.

The lack of the "scrolling to cursor" behavior is what's missing in the debugger.

Requesting to see if this can be implemented. Thanks.

**Comment by jasonLaster** [comment]
@tommai78101 do you have steps to reproduce?

**Comment by tommai78101** [comment]
@jasonLaster I can confirm it's no longer an issue after updating to version 61 for Dev Edition.

It may have been fixed some time between April 20th and May 11.

![gif](https://user-images.githubusercontent.com/6444116/40545718-d0d70f72-5ffa-11e8-80a9-ba030ca1704f.gif)

**Comment by jasonLaster** [comment]
thanks

**Comment by tommai78101** [comment]
@jasonLaster Actually, on second thought, it's 90% confirm. The last 10% is because for minified sources, I can't really tell if it's truly jumping to the right spots in the code.
