### ISSUE TITLE
Breakpoints - include source name in the description

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#604]
It would be nice to include the breakpoint source name in the description so that it is clear where the breakpoint is set. This design is similar to how we show source locations in the call stack. It is also similar to how chrome shows it.

This would need to be styled so that the typography is right before we ship it. The patch below is a first pass though so anyone should feel free to pick it up and run with it.

#### Before
![screen shot 2016-08-28 at 1 57 23 pm](https://cloud.githubusercontent.com/assets/254562/18035618/180bb794-6d27-11e6-8fde-17468a1f22d7.png)

#### After
![screen shot 2016-08-28 at 1 55 19 pm](https://cloud.githubusercontent.com/assets/254562/18035603/da9bf5ae-6d26-11e6-976a-128b8172b404.png)

```diff
diff --git a/public/js/components/Breakpoints.js b/public/js/components/Breakpoints.js
index 72c571a..d6bb329 100644
--- a/public/js/components/Breakpoints.js
+++ b/public/js/components/Breakpoints.js
@@ -9,6 +9,8 @@ const { getSource, getPause, getBreakpoints } = require("../selectors");
 const { makeLocationId } = require("../reducers/breakpoints");
 const { truncateStr } = require("../utils/utils");
 const { DOM: dom, PropTypes } = React;
+const { endTruncateStr } = require("../utils/utils");
+const { basename } = require("../utils/path");
 
 require("./Breakpoints.css");
 
@@ -26,6 +28,15 @@ function isCurrentlyPausedAtBreakpoint(state, breakpoint) {
   return bpId === pausedId;
 }
 
+function renderSourceLocation(source, line) {
+  const url = basename(source.get("url"));
+  // const line = url !== "" ? `: ${line}` : "";
+  return url !== "" ?
+    dom.div({ className: "location" },
+      `${endTruncateStr(url, 30)}${line}`
+    ) : null;
+}
+
 const Breakpoints = React.createClass({
   propTypes: {
     breakpoints: ImPropTypes.map.isRequired,
@@ -84,7 +95,8 @@ const Breakpoints = React.createClass({
         }),
       dom.div(
         { className: "breakpoint-label", title: breakpoint.text },
-        `${line} ${snippet}`
+        dom.div({}, renderSourceLocation(breakpoint.location.source, line)),
+        `${snippet}`
       ),
       isPausedIcon
     );
```

**Comment by clarkbw** [comment]
Worth looking at #291 as well for some previous design discussion

**Comment by wldcordeiro** [comment]
I'll grab this.

**Comment by jasonLaster** [comment]
@helenvholmes mind doing a quick visual pass on this. It can be pretty similar to chrome
