### ISSUE TITLE
[Component] the content should be padded

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6049]
Our new component pane should get the same padding as the other panes

STR: 
1. go to https://firefox-debugger-example-react-js.glitch.me/
2. set a breakpoint in App.jsx/onSortClick
3. click the button

Notice the left arrows need some padding in the "HelloWorld" pane

<img src='https://shipusercontent.com/f5b6725feb94f1cf80da209125a54d6d/Screen%20Shot%202018-04-21%20at%209.12.52%20AM.png' title='Screen Shot 2018-04-21 at 9.12.52 AM.png' width=378>

**Comment by CamStan** [comment]
There's a group of four (@wmeulink, @No-one-alone, @Launia and myself) of us here at a university who are going to try to work on this bug together in order to get familiar with this process. So there may be comments, questions, or pull requests coming from any one of us. :grinning:

**Comment by CamStan** [comment]
@jasonLaster, we seem to be having an issue replicating the bug. After navigating to [https://firefox-debugger-example-react-js.glitch.me/](url), the app.jsx file (ours is lower case) does not have an onSortClick function.

![image](https://user-images.githubusercontent.com/12384825/39606163-bf80d6c2-4ee8-11e8-9be6-6520c423d885.png)

So using the inspector I clicked on the button and had it take me to the onSortClick funciton on line 911 in main.js which is where I put a breakpoint. However, after clicking the button, no "HelloWorld" pane shows up.

![image](https://user-images.githubusercontent.com/12384825/39606241-44957d54-4ee9-11e8-8be8-e5078056dd1c.png)

We are all new to this, so any help would be appreciated.

**Comment by CamStan** [comment]
Just realized a pull request was made for this 11 days ago, but the bug is still labeled as open. Was this already fixed?

**Comment by jasonLaster** [comment]
yes, sorry
