### ISSUE TITLE
Right Sidebar - the header should be fixed

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#605]
The right sidebar header currently scrolls out of view. It should be fixed on the top so that the commands are always available.

We can probably do more to improve the scrolling behavior of the accordion, like making the accordion item headers sticky, so the top most item header is always visible, but that is probably out of scope for now. 

![screen shot 2016-08-28 at 2 01 23 pm](https://cloud.githubusercontent.com/assets/254562/18035647/b9a36084-6d27-11e6-95fd-494c1a935041.png)

![screen shot 2016-08-28 at 2 01 11 pm](https://cloud.githubusercontent.com/assets/254562/18035646/b9a2ce3a-6d27-11e6-877b-efa043c92980.png)

**Comment by wldcordeiro** [comment]
I'll take a look at this.
