### ISSUE TITLE
[Preview] Popup gets clipped on top

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6051]
When you're hovering over a big object that won't fit below, we try to show it above the variable. Unfortunately, showing it above is often not a good option either.

In these cases, it would be great if we could show the popup to the right of the variable and try and use all of the available space needed...

<img src='https://shipusercontent.com/5869fd0f83eded871fce7a50c3a32ddf/Screen%20Shot%202018-04-21%20at%209.23.27%20AM.png' title='Screen Shot 2018-04-21 at 9.23.27 AM.png' width=587>

**Comment by shirlyb3** [comment]
/claim
I think I found the location where it can be changed:
https://github.com/devtools-html/debugger.html/blob/master/src/components/shared/Popover.js#L76

**Comment by jasonLaster** [comment]
How is it going @shirlyb3? Anything i can help with?

**Comment by shirlyb3** [comment]
@jasonLaster going well, almost done - there's only one case the preview is not located in the way I wanted it to, so I'm checking now what I missed.

I might need help with the tests, I have 2 popover tests failing - 
it expects the preview to be located over the token, but now according to the `editorRect` and `targetRect` passed to the popover component in the test, the position calculation in my implementation places it on the right side of the token.
This is the one failing -  https://github.com/devtools-html/debugger.html/blob/master/src/components/shared/tests/Popover.spec.js#L73
But I'm not 100% sure the test is wrong (and also I don't want to be one of those programmers saying "tests are wrong my code is awesome"), so I feel like I need some approval. Also, I never created or updated a .snap file, so I'm not sure what's the procedure - can I just change the expected component props?
