### ISSUE TITLE
Firefox uses a lot of CPU when inspecting an element with a really huge css selector

### ISSUE THREAD

**Issue by lilydjwg** [devtools-html/debugger.html#6056]
Firefox version 61.0a1 date 20180416
Arch Linux

* Install Adblock Plus and have the "blocking social media buttons" (rough back-translation) feature on.
* Go to a page with such a button blocked (I found this with https://www.zhihu.com/people/ling-long-xie-seng/activities; there is a blue "关注" button being blocked by it on the right). Inspect this button to check css styles
* Wait for a lot time with one CPU core 100% used before Firefox responds again
* You'll see a really huge css selector finally. I don't know how huge it is because Firefox froze again when I tried to copy it, but from the scrollbar I can tell it's really really huge.

Maybe you can find the css rule causing this issue and reproduce it with a simpler page?

BTW: I've reported to Adblock Plus since that button shouldn't be blocked. If they fix it the page I linked won't reproduce the issue any more.

**Comment by jasonLaster** [comment]
Thanks @lilydjwg could you please file this in bugzilla under the devtools > inspector component.
