### ISSUE TITLE
Breakpoints - remove breakpoint button

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#606]
Let's add a remove button appear to the right of a breakpoint on hover. Having this button will make it easier for users to remove breakpoints without having to click the gutter marker.

![delete-breakpoint](https://cloud.githubusercontent.com/assets/1720093/18672205/2b0c7856-7f15-11e6-93ab-6a534ec45e55.png)

This [patch](https://gist.github.com/jasonLaster/71a2683becf26bc52247385c20a022e4) outlines what the changeset will look like. Feel free to ask any questions, especially around getting setup. 

EDIT: from @helenvholmes, added a screenshot with the proposed change mocked up

**Comment by wldcordeiro** [comment]
Seems similar to the search close button issue so I'll take this one on. 👍

**Comment by jasonLaster** [comment]
@helenvholmes, @clarkbw, @jlongster do you think this UI makes sense? Chrome has the remove breakpoint action in a contextmenu.

@jlongster we simplified the markup for the breakpoint, which makes it tougher to implement right-side actions. Does this still make sense considering that?

**Comment by helenvholmes** [comment]
This would remove it completely from the list, separate from toggling its checkbox, correct?

The interaction makes sense to me. [Here's the link](https://dxr.mozilla.org/mozilla-central/source/devtools/client/themes/images/close.svg) to the 'x' icon I imagine we'd be using.

**Comment by jasonLaster** [comment]
@helenvholmes yup. sometimes you just want it gone. Which to be fair, you can do when you click the gutter, but it would be nice to be able to delete it from the list.

**Comment by jlongster** [comment]
I think it makes sense, and I think it's a good reason to avoid the breakpoint icon because it would be weird to have two icons there but only one of them actually clickable. Now that we don't have the breakpoint icon, we could put an X there.

To clean up the UI a little, maybe it would only appear on hover? That's a pretty common interaction so that it's not so cluttered but you can still do it quickly.

**Comment by jasonLaster** [comment]
> weird to have two icons there but only one of them actually clickable

good point. 

> maybe it would only appear on hover

That's what I was thinking as well.

**Comment by wldcordeiro** [comment]
+1+ that @jlongster the hover icon seems to make sense.
