### ISSUE TITLE
[Pretty Print] broken for our-thinking

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#6061]
This is reproducible in more than one site since last week(?).

For example

0. With Firefox Nightly 61.0a1 (2018-04-22) (64-bit) on macOs 10.13.4 (17E199)
1. Open RDM with Firefox Android UA
2. Go to https://www.akamai.com/us/en/about/our-thinking/state-of-the-internet-report/
3. Open the debugger and find https://www.akamai.com/scripts/app.built.1521050552.js
4. Select the two brackets at the bottom. **Nothing is happening**
5. Go to the tab label itself, Ctrl+click and choose "Pretty print source". **Nothing is happening**

**Comment by jasonLaster** [comment]
I'm sorry for the delay. I'll look into it today. Is it possible that "source maps" is disabled for you?

**Comment by jasonLaster** [comment]
Hmm, seems to work for me:

![](http://g.recordit.co/Ca5yB1lfJw.gif)

**Comment by karlcow** [comment]
Given the date. It's probably because I had "Enable Source Maps" off. aka issue #6328
Thanks @jasonLaster
