### ISSUE TITLE
[Breakpoints] (Nit) Expressions Should Only Have a Blue Border When Focused

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#6063]
We updated the Watch Expressions block last week to show the input when there are no expressions, but forgot to ensure the blue border only displays when the input is *focused*.

<img width="309" alt="badborder" src="https://user-images.githubusercontent.com/46655/39133177-344e0b0e-46d9-11e8-9072-9a15fba395c5.png">

**Comment by violasong** [comment]
@darkwing one more nit for this - the dark mode border color should be Blue-50 (to match the Console focus rings)
