### ISSUE TITLE
[Breakpoints] (Nit) Tighten Breakpoints Spacing

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#6065]
The spacing between breakpoints at the moment is a bit much.  @violasong will provide a more specific target for spacing :)

<img width="304" alt="breakpointsspacing" src="https://user-images.githubusercontent.com/46655/39133508-fee94630-46d9-11e8-808f-50e2f2529201.png">

**Comment by violasong** [comment]
Here are some nits/suggestions :). I'm providing the CSS just so you can see what I think it should be visually but any visual equivalent of these is good too. Forgot to take a screenshot of the result, oops.

.breakpoints-exceptions
padding-bottom: .5em;
padding-top: .5em;

.breakpoints-list .breakpoint-heading
padding-top: .75em

.breakpoints-list .breakpoint-label
font-size: 11px

.breakpoints-list .breakpoint-heading, .breakpoints-list .breakpoint, .breakpoints-exceptions
padding: 0.25em 1em .25em 0.5em;

.pane.breakpoints-list
padding-bottom: .35em;

.breakpoints-exceptions-caught
    margin-top: -.25em;

Potential bug I noticed - when hovering over a breakpoint code snippet, I'm unable to scroll the panel (using 2-finger scroll on MacOS)

I'm looking at the code snippet and realizing that for short lines of code, it includes the next line. I feel like this might be easier to parse if we just do at most the one line? Not sure about this though. An extra space between line would help.
