### ISSUE TITLE
Scopes - fail to expand `addOptions` property

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#607]
#### Steps to reproduce

* open todomvc
* go to backbone.js and add a breakpoint in get on line 291
* create a todo
* expand scope `anonymous` and property `addOptions`

You'll see this error `no such actor` in the console.

![screen shot 2016-08-28 at 2 05 25 pm](https://cloud.githubusercontent.com/assets/254562/18035745/8489961e-6d29-11e6-8c25-dac40a953c6d.png)

![screen shot 2016-08-28 at 2 05 15 pm](https://cloud.githubusercontent.com/assets/254562/18035749/b17d57e6-6d29-11e6-8984-a2ad1273e481.png)

**Comment by jasonLaster** [comment]
hmm, i'm not reproducing this anymore

**Comment by jasonLaster** [comment]
strange, i'm seeing it again. I wonder if it's something like `optimizedOut` where it's not available on the server sometimes...

**Comment by wldcordeiro** [comment]
@jasonLaster I was trying to recreate and hadn't been able to. Expanding `addOptions` worked for me with no error in console (not sure if you were using the devtools console or browser toolbox but neither had an error.)

**Comment by clarkbw** [comment]
@jasonLaster investigate scope of issue and then drop from P1 and Milestone accordingly.

**Comment by jasonLaster** [comment]
can't repro
