### ISSUE TITLE
[Breakpoints] (Nit) Generated Text for React Displaying Improperly

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#6076]
I spotted this when adding a breakpoint to a React component method:

<img width="1277" alt="weirdreacttext" src="https://user-images.githubusercontent.com/46655/39150803-12417084-4709-11e8-8ff5-8da7e015c729.png">

The text should be `onSortClick {`

**Comment by bomsy** [comment]
\claim

**Comment by bomsy** [comment]
@darkwing  Looks like this might have been fixed!

![](http://g.recordit.co/mHBEmxnnau.gif)

**Comment by bomsy** [comment]
If not
