### ISSUE TITLE
[Breakpoints] Breakpoint text showing wrong text when breakpoint is pushed to a following line.

### ISSUE THREAD

**Issue by mmcote** [devtools-html/debugger.html#6078]
1. Open https://ahfarmer.github.io/emoji-search/.
2. Set breakpoint on line 33 `}`, it will be pushed to line 35 `export default App`.
3. Note the breakpoint line number in the breakpoint pane is correct at 35, but the text is from line 33 not line 35, `export default App`.

4. The correct text can be seen by refreshing the debugger. 

![breakpointbug](https://user-images.githubusercontent.com/14250545/39167905-d0e5a0ec-474e-11e8-8445-854f170223e0.gif)

**Comment by darkwing** [comment]
This may be the same root issue as https://github.com/devtools-html/debugger.html/issues/6076
