### ISSUE TITLE
Breakpoints - select breakpoint doesn't navigate in paused source

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#608]
#### Steps to reproduce
* add a couple breakpoints in a source
* pause on one of the breakpoints
* select another breakpoint in the list in that source
* you won't be navigated to that source

This is probably due to the highlight line being there for the pause location

**Comment by jlongster** [comment]
Will be fixed by #713

**Comment by jlongster** [comment]
I'm pretty sure this is a dupe of #675
