### ISSUE TITLE
Breakpoints - selecting a breakpoint should flash the line

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#609]
When you select a breakpoint in the breakpoint list that is near to the current editor location nothing happens because the breakpoint location is already in view. This makes it seem like a bug. What we should do is show a flash indicator on that line that draws the user to the breakpoint line she just selected.

This is a good issue for a community member as it is UI related. The most important context you'll need is around the [Editor](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/Editor.js). The Editor is a react component that wraps codemirror. We'll likely want to use a [css animation](http://stackoverflow.com/questions/10072993/css3-transitions-want-to-add-a-colour-and-fade-it-away) for the fade. And probably add and remove a class when it is done so we don't litter the editor with lots of classes for lines we have highlighted in the past.

One more thought, we'll likely add the flash indicator the same way we add the debug line (green line) [here](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/Editor.js#L100-L107)

**Comment by wldcordeiro** [comment]
I'll grab this issue.

**Comment by jasonLaster** [comment]
@wldcordeiro mind if @jacobjzhang grabs this?

**Comment by wldcordeiro** [comment]
Sure? I had put it aside while working on the sidebar collapsing but now that I got that done/we're reworking that I have time for this. But if @jacobjzhang wants it they can take it.

**Comment by jasonLaster** [comment]
Actually, @jacobjzhang @wldcordeiro I tagged the wrong issue. I intended to tag #606.

@jlongster actually fixed this earlier last week.
