### ISSUE TITLE
[Frames] Call Stack and Scopes spacing and truncation thoughts

### ISSUE THREAD

**Issue by violasong** [devtools-html/debugger.html#6091]
Call Stack rows are looking a bit too tall - they should match the breakpoints spacing specified in #6065 

The Scopes rows look a bit too short - if they could match the source tree, that would be great.

Also, call stack line numbers should ideally line up and look the same as the breakpoint line numbers, and have better truncation on file names.

**Comment by jasonLaster** [comment]
cc @darkwing, @violasong did we fix this?

**Comment by violasong** [comment]
I don't think this has happened yet, but it fits nicely into Honza's new Callstacks improvement project: https://docs.google.com/document/d/17XzcgIqHk1qjEXLi-Sk7VHaMTr_76tCO6iV7txg_d_E/ :)

**Comment by jasonLaster** [comment]
@violasong can we close this and focus on #6631?

**Comment by violasong** [comment]
Sounds good!
