### ISSUE TITLE
Breakpoint - styling

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#610]
the breakpoint marker is not centered:

![screen shot 2016-08-28 at 10 17 32 pm](https://cloud.githubusercontent.com/assets/254562/18039037/03416872-6d6d-11e6-8f3f-9f3ddbe2a23c.png)

**Comment by jlongster** [comment]
This is not an issue with Firefox. Jason, it'd be great if you used Firefox for the next couple weeks while we try to polish it for Firefox. Closing as we really need to focus on Firefox right now. If I'm wrong and it somehow is Firefox you can re-open.

<img width="266" alt="screen shot 2016-08-29 at 8 51 57 am" src="https://cloud.githubusercontent.com/assets/17031/18052025/04ee8fa2-6dc6-11e6-91c8-4de6547cc0dd.png">

**Comment by wldcordeiro** [comment]
@jlongster is this when you embed the debugger or when you run a tab? I'm on Firefox (gecko-dev) and have the breakpoint styling look a little off.
![screenshot_20160829_083632](https://cloud.githubusercontent.com/assets/580982/18055089/da57037a-6dc3-11e6-9add-89b95d8cd28b.png)

**Comment by jasonLaster** [comment]
> focus on Firefox

That makes sense.

I'll re-open and label it as chrome so we can come back to the chrome issues when we have time. It will be nice to do a quick pass at that point.

**Comment by ThomasCrvsr** [comment]
I can take a look at this if you want :)

**Comment by ThomasCrvsr** [comment]
A temporary fix might be to increase the `height` of the breakpoint svg [here](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/Editor.css#L28)
