### ISSUE TITLE
ElementNode attribute are not cropped

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#6121]
_From @nchevobbe on December 7, 2017 9:4_

**Steps to reproduce:**
1. Evaluate:
```js
var div = document.createElement("div");
div.setAttribute("data-test","a".repeat(5000));
div;
```

**Expected results:**
The `data-test attribute` is cropped 

**Actual results:**
It is not cropped (and does not wrap)

_Copied from original issue: devtools-html/devtools-core#835_

**Comment by nchevobbe** [comment]
_From @kootoopas on December 15, 2017 8:45_

Call me weird but I find the expected cropped display hindering accessibility, since there's no way of seeing cropped attributes. Shouldn't they wrap ideally?

Chrome offers the same single line non-crop functionality btw:
<img width="560" alt="screen shot 2017-12-15 at 10 41 40 am" src="https://user-images.githubusercontent.com/601001/34033902-e90986d2-e184-11e7-9eb3-736c7b82514a.png">

**Comment by nchevobbe** [comment]
I'd say we could crop and have a title attribute to show the whole string. Or we could make the ellipsis clickable for people who want to see the whole rule.

**Comment by nipuna777** [comment]
> _From @kootoopas on December 15, 2017 8:45_
> 
> Call me weird but I find the expected cropped display hindering accessibility, since there's no way of seeing cropped attributes. Shouldn't they wrap ideally?
> 
> Chrome offers the same single line non-crop functionality btw:
> <img alt="screen shot 2017-12-15 at 10 41 40 am" width="560" src="https://user-images.githubusercontent.com/601001/34033902-e90986d2-e184-11e7-9eb3-736c7b82514a.png">

In Chrome, we can scroll and view the entire attribute. In firefox console, that doesn't seem to be possible.

By 'cropped' do you mean that the attribute should be cut off at a set limit? Or should we add elipsis at the end of screen?

Is this a good first issue to be picked up? If so, I'd like to take a crack at it.

**Comment by nchevobbe** [comment]
> By 'cropped' do you mean that the attribute should be cut off at a set limit? Or should we add elipsis at the end of screen?

Yeah, there should be an ellipsis at some point, and the attribute value should be put in the `title` of the span so the user can get access to the whole value if they want to.

@nipuna777 You can pick it up for sure

**Comment by nchevobbe** [comment]
Sure!
So here's the place where the attributes are created: https://github.com/devtools-html/debugger.html/blob/09be11c85725bbd0d2deeacf22a824c0b27d5e32/packages/devtools-reps/src/reps/element-node.js#L145-L147
We already call the `StringRep`, but without any `cropLimit`  (https://github.com/devtools-html/debugger.html/blob/09be11c85725bbd0d2deeacf22a824c0b27d5e32/packages/devtools-reps/src/reps/string.js#L54)

Passing a `cropLimit` prop (`50` seems enough to me), should be okay.
In `StringRep`, if the string is cropped we might want to add a `title` attribute with the full length though, so one can still quickly scan it.

**Comment by nipuna777** [comment]
/unclaim

Unclaming this now because I've not made much progress and @darkwing is interested in taking it on. 
Sorry if I held this task up.

**Comment by nchevobbe** [comment]
The patch looks good to me, and it does work well.
Regarding the `title, it is added to the DOM, but I can't have a tooltip to be displayed, that's weird.
