### ISSUE TITLE
(Nit) [Expressions] Misc tweaks to empty state/add behavior

### ISSUE THREAD

**Issue by violasong** [devtools-html/debugger.html#6166]
- [x] Plus button should match stepping buttons in color

- [x] When no Watch Expressions, should hide Refresh button

- [x] Dotted-outline focus ring that appears when clicking + seems unnecessary

- [x] Clicking + should always open the accordion and change focus to the input field

- [x] Watch expressions rows should be taller, to match the new breakpoint styling

**Comment by phoenixking25** [comment]
row should be taller mean have to increase height of the rows in css? @darkwing

**Comment by darkwing** [comment]
In a previous conversation @violasong mentioned that `1em` may be the height we want -- give it a shot :)

**Comment by violasong** [comment]
It should visually match the height of the breakpoint rows, so borrowing some styles from there might help :)

**Comment by phoenixking25** [comment]
![screenshot from 2018-05-05 19-10-51](https://user-images.githubusercontent.com/22527880/39664057-0e501ec6-509b-11e8-98b3-f31381a51d3f.png)
![screenshot from 2018-05-05 19-11-11](https://user-images.githubusercontent.com/22527880/39664058-0ead57ee-509b-11e8-9ec4-3ee07b5283af.png)

**Comment by phoenixking25** [comment]
added `min-height: 3em` to `.expression-container`  Is it looking alright with this or add some padding too? @violasong
