### ISSUE TITLE
[Search] tweak input bars

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6179]
We recently landed some improvements for the Quick Open Modal [here](https://github.com/devtools-html/debugger.html/issues/5988). These changes caused some issues for project search and file search, which we should clean up:

- close button
- general layout inbalances

### Project Search
<img src='https://shipusercontent.com/6a94f594df59e956c8157155aa82acde/Screen%20Shot%202018-04-30%20at%209.04.21%20AM.png' title='Screen Shot 2018-04-30 at 9.04.21 AM.png' width=967>

### File Search
<img src='https://shipusercontent.com/3f0b5f68e13e58f1214a3a699486e887/Screen%20Shot%202018-04-30%20at%209.04.08%20AM.png' title='Screen Shot 2018-04-30 at 9.04.08 AM.png' width=918>

**Comment by darkwing** [comment]
The issue is the `.search-field .close-btn`'s `margin-top`; we may need to axe it completely.  We may also need to add the "big"  classname to the `QuickOpenModal`

**Comment by AlexMolodyh** [comment]
Does this happen for every browser version or just specific ones? 

I was trying to reproduce this in the latest version of Firefox and couldn't get it to reproduce.

**Comment by jasonLaster** [comment]
@AlexMolodyh this is only in github locally. We havent landed this bug in firefox yet

**Comment by AlexMolodyh** [comment]
@jasonLaster - I guess I'm a little confused about how to recreate this issue then. Is this not a firefox debugger issue?

**Comment by jasonLaster** [comment]
it is :)

checkout the getting setup instructions http://github.com/devtools-html/debugger.html/

**Comment by AlexMolodyh** [comment]
@jasonLaster - Yes, that would be great. When would you have time?

**Comment by jasonLaster** [comment]
<img src='https://shipusercontent.com/3c5afa34b0c412e83aa36f6629351422/Screen%20Shot%202018-05-03%20at%201.59.58%20PM.png' title='Screen Shot 2018-05-03 at 1.59.58 PM.png' width=1552>

**Comment by AlexMolodyh** [comment]
Thanks @jasonLaster!

**Comment by AlexMolodyh** [comment]
I can't seem to reproduce the issue on my hp laptop. Would this be a mac specific issue? Here's a screenshot of it.
![screenshot from 2018-05-03 14-36-26](https://user-images.githubusercontent.com/32307614/39596204-a7a064b8-4edf-11e8-827d-25aebb1fb850.png)

**Comment by AlexMolodyh** [comment]
@jasonLaster - Is there anything else that we need to do to close this issue? @darkwing approved the pull request and merged it into master.

**Comment by nyrosmith** [comment]
Closing as the associatrd PR got merged.
Thanks @AlexMolodyh & friends!
