### ISSUE TITLE
Breakpoint title is vertically misaligned

### ISSUE THREAD

**Issue by captainbrosset** [devtools-html/debugger.html#6181]
If you look closely, you'll see that the title (i.e. the piece of code) and the cross icon (to delete the breakpoint) are both a little bit too high within the breakpoint element.
The checkpoint, however, seems properly aligned.

<img width="243" alt="breakpoint" src="https://user-images.githubusercontent.com/1152698/39431424-f6fe2406-4c90-11e8-82c9-6b36ff71b30e.PNG">

I guess the intent was to have everything vertically centered?

**Comment by jasonLaster** [comment]
I think @darkwing is on this
