### ISSUE TITLE
[Pause] mochi browser_dbg-pause-exceptions.js and jest pause.spec randomly fail

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#6190]
Running pause tests sometimes causes them randomly to fail. I noticed it several times when running jest and also in mochitest. 
An Example is https://github.com/devtools-html/debugger.html/pull/6188 where the pause test fails even though the item worked on has nothing to do with it.

**Comment by lukaszsobek** [comment]
Seems to have been resolved. Closing.

**Comment by jasonLaster** [comment]
yep!
