### ISSUE TITLE
Error: relatedTarget.classList is undefined in Popup.js

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#6201]
<img width="847" alt="classlist" src="https://user-images.githubusercontent.com/46655/39547633-c3e06cbc-4e1d-11e8-99e1-2cbe4de7c9bc.png">

I haven't been able to reproduce this yet but just something we should be aware of; at the very least check that classList exists.

**Comment by jasonLaster** [comment]
uhoh
