### ISSUE TITLE
[Expressions] Invalid chrome URI error

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#6213]
1. Open browser console
2. Open debugger
3. Add some watch expression
4. Browser console shows

> Invalid chrome URI: /
> [Show/hide message details.] [Exception... "Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIInterfaceRequestor.getInterface]"  nsresult: "0x80004002 (NS_NOINTERFACE)"  location: "JS frame :: resource://gre/modules/LoginManagerContent.jsm :: messageManagerFromWindow :: line 157"  data: no]
> messageManagerFromWindow resource://gre/modules/LoginManagerContent.jsm:157:10
> _onFormSubmit resource://gre/modules/LoginManagerContent.jsm:938:26
> notify resource://gre/modules/LoginManagerContent.jsm:62:7

**Comment by jasonLaster** [comment]
@Loirooriol is that related to expressions? do you see that if you add something in the console?

**Comment by Loirooriol** [comment]
@jasonLaster Not in the console, I only get this when I add a watch expression.

**Comment by darkwing** [comment]
Tested this and don't see the issue.
