### ISSUE TITLE
Files list persists when navigating from one site to the other

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#6219]
0. with Firefox Nightly 61.0a1 (2018-05-03) (64-bit)
1. Open the devtools on the debugger
2. Enter mozilla.org in the address bar.
3. The files are loaded and shown in the debugger <img width="966" alt="capture d ecran 2018-05-04 a 15 11 35" src="https://user-images.githubusercontent.com/505230/39614797-88d827b8-4fad-11e8-8321-453e6c7dbf14.png">
3. Now enter wikipedia.org in the address bar.
4. the files from wikipedia are added to the view BUT **the ones from mozilla.org persist too**. <img width="966" alt="capture d ecran 2018-05-04 a 15 15 28" src="https://user-images.githubusercontent.com/505230/39614871-0201f8ee-4fae-11e8-8cd4-a389828b0630.png">

Expected:
Just the new context should appear, not the previous one.

This is unrelated to mozilla/wikipedia. This is happening consistently for the last couple of days everywhere.

**Comment by jasonLaster** [comment]
Thanks @karlcow

**Comment by bomsy** [comment]
Looks like this is fixed in 62.0a1(2018-05-12)(64-bit).

Closing for now.
