### ISSUE TITLE
Add search keycommand info above Sources

### ISSUE THREAD

**Issue by helenvholmes** [devtools-html/debugger.html#622]
I think that the area above Sources might just continue to evolve, but for the moment I believe it would be a good spot to educate users about "Cmd + P to search". 

Mac: 
<img width="831" alt="screen shot 2016-08-30 at 11 08 55 am" src="https://cloud.githubusercontent.com/assets/1720093/18094744/80a512a6-6ea2-11e6-9350-2467b84d8151.png">

Windows/Linux:
<img width="960" alt="screen shot 2016-08-30 at 11 12 54 am" src="https://cloud.githubusercontent.com/assets/1720093/18094811/b6b925c6-6ea2-11e6-8964-97b0d3ec5b66.png">

**Comment by wldcordeiro** [comment]
Just adding the label there? I'll grab that real quick.

**Comment by clarkbw** [comment]
👏  I think you just need to follow the example for the search input.

The [renderWelcomeBox()](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/App.js#L106-L112) function has it.

**Comment by clarkbw** [comment]
@wldcordeiro are you picking this up?

I was just thinking it might be nice to make the label or perhaps the header area in general clickable so someone could bring up the search field by clicking.  However we'll need to wait on #623 to see the outcome of where the buttons land.

**Comment by helenvholmes** [comment]
> I was just thinking it might be nice to make the label or perhaps the header area in general clickable so someone could bring up the search field by clicking. However we'll need to wait on #623 to see the outcome of where the buttons land.

Following current patterns, they'd be here-ish: https://cl.ly/0E0s1F1O2A3r
