### ISSUE TITLE
[QuickOpen] Treat files with same resolved paths as one

### ISSUE THREAD

**Issue by kootoopas** [devtools-html/debugger.html#6250]
The file is the same but I guess somewhere in the codebase it's referenced with a preceding `./` so the debugger treats it as a different file entry (see `./` diff in start of filepaths):
![screen shot 2018-05-08 at 12 47 56](https://user-images.githubusercontent.com/601001/39750664-7427c7c4-52be-11e8-9eb0-07536ee00409.png)

**Comment by kootoopas** [comment]
Nevermind, file contents differ. One is typescript source and the other post-webpack processed. It's still weird that their paths are the same though!

**Comment by jasonLaster** [comment]
yes, we'll address this in a diffeent issue about differentiating original and generated sources
