### ISSUE TITLE
Startpage's `Ctrl+P` and `Ctrl+Shift+F` should be <button/>s

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#6251]
From the mouse cursor and visually it is not clear that the 'buttons' are clickable. Looks like these are divs/spans with event listeners. Would be better if these where real `<button>`'s, also for semantics/accessibility. Like it is for the Performance or Memory tab:

![debugger-buttons](https://user-images.githubusercontent.com/3307404/39756222-02b74e60-52c9-11e8-9f5c-ea1d32e9889e.gif)

Probably it would be easy to fix by:
1. Changing the corresponding source code html from `div/span` to `<button>`
2. Apply the same CSS to it like it is for the buttons on Memory / Performance tab
3. Optionally: Probably nicer to write the shortcuts with `+` as it is in other shortcuts, at least in Windows/Linux (not sure about Mac). That is, `Ctrl+P` and `Ctrl+Shift+F` instead of `Ctrl P` and `Ctrl Shift F`. All other Firefox shortcuts like `Ctrl+C` or `Ctrl+F` are written with `+` (just click on the top-right hamburger menu to check)

**Comment by jnachtigall** [comment]
@phoenixking25 almost perfect, thank you! :) (though I'm not a maintainer, so wait for them for a proper code review).

What I'm seeing that still could be improved:
1. Both bothes should have the same width so they align more nicely. (The find files button is a bit wider at the moment). Not sure how this would be best done. Setting a `min-width` on both probably does not work this the strings also get translated and depending on the language the length might vary/change.
2. Well, still I think it should be That is, `Ctrl+P` and `Ctrl+Shift+F` instead of `Ctrl P` and `Ctrl Shift F` for consistency. At least on Windows and Linux there's always a `+` for shortcuts, in Firefox and in all other languages.

**Comment by phoenixking25** [comment]
![min-width](https://user-images.githubusercontent.com/22527880/39783886-2c21b496-5334-11e8-81d9-86055785d933.gif)
@jnachtigall Thanks for the help :) Setting `min-width: 250px` did the thing. And the `+` sign will work on that :)

**Comment by jnachtigall** [comment]
> Setting min-width: 250px did the thing.

Cool, but as said this will work for english (and probably 90% of other languages) but might not work for some languages/translations (in other languages, like German which has looong words, the 250px will not be enough, and then it will break) . Though I am not sure how to fix this with CSS, maybe having a container wrapper around the buttons and let the buttons always be 100% of the container size so that the buttons are always equal size.

Anyway, you might want to create a first PR so reviewers can check on the code :)

**Comment by jnachtigall** [comment]
@phoenixking25 As said, looks mostly good to me. Thank you! Mind adding the PR?

**Comment by gerdneuman** [comment]
@jasonLaster Not sure why this was closed? The current buttons are irritating. For instance I just wanted to click on the middle pane so that it has focus, but instead I've hit the `Ctrl+P` button because this seems to stretch 100% horizontally:
![image](https://user-images.githubusercontent.com/12525563/43200090-7edcf098-9014-11e8-88f6-b73b5cad9dd9.png)

I think, these buttons should really be like they are the `Performance` or `Memory` tab.

Can you reopen? Looks like phoenixking25  had some nice WiP but never really finished.

**Comment by gerdneuman** [comment]
ok, https://github.com/devtools-html/debugger.html/pull/6285#issuecomment-389566904 is an explanation, but where's the bug/redesign to follow?
