### ISSUE TITLE
[releases] release v40 - Investigate step-in performance regression 

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#6254]
[Release 40](https://github.com/devtools-html/debugger.html/compare/release-39...release-40) regressed the performance of the "step-in" performance test of 20%.

The code for the performance test is at: https://searchfox.org/mozilla-central/source/testing/talos/talos/tests/devtools/addon/content/tests/debugger/custom.js#71

The list of commits from the release is at https://github.com/devtools-html/debugger.html/compare/release-39...release-40

**Comment by juliandescottes** [comment]
Looking at the list of commits, maybe related to:
- Use pausePoints to determine valid pause locations, f3cf6a8593aee4d6f49bf3089fdae7a1ded6f60d
- Bump source-map to 16, 5c3c451b11419fde2f66e939d5d0cc8f291b8c1b

At first glance, other commits seem less likely to impact the step-in performance

**Comment by jasonLaster** [comment]
the graph went back to normal.
