### ISSUE TITLE
Search failure doesn't update when hitting Enter to search

### ISSUE THREAD

**Issue by hcs64** [devtools-html/debugger.html#6255]
Steps to reproduce:
1. Open files in tabs in the debugger
2. Ctrl+F search for something that is in one file but not the current tab (frowny appears and search term turns red)
3. Switch to the tab with the file that contains the search term
4. Click in the search box and hit Enter to re-run the search

Even though the search term is found, the frowny and red text remain.

**Comment by jasonLaster** [comment]
Thanks for the report!

**Comment by lukaszsobek** [comment]
Merged. Closing.
