### ISSUE TITLE
Add support for await in console

### ISSUE THREAD

**Issue by brianpeiris** [devtools-html/debugger.html#6256]
I'd like to be able to run async code in the console. I'd expect it to be considered a "top level" context. 

For example, I want to run:
`await new Promise(resolve => setTimeout(resolve, 1000))`

But this currently results in an error:
`SyntaxError: await is only valid in async functions and async generators`

**Comment by jasonLaster** [comment]
Good idea @brianpeiris. I think this bug should be in bugzilla.

**Comment by brianpeiris** [comment]
Oh, sorry, some how totally overlooked that this project was _just_ the debugger. Thanks.
