### ISSUE TITLE
[ObjectInspector] Expanding longString nodeValue of attribute crashes the console

### ISSUE THREAD

**Issue by kootoopas** [devtools-html/debugger.html#6257]
#### STR

browser: nightly 62.0a1 (2018-05-07) (64-bit)
os: macOS 10.13.3
1. Open nightly.
2. cmd + alt + i
3. Paste these into console:
```
document.body.setAttribute('s', 'r '.repeat(5000))
document.body.attributes.s
```
4. Click on the `s` attribute to expand it, click on its `nodeValue` to expand the longString.

#### ER

`key: value` pair should have expanded value.

#### AR

The whole console tab crashes and requires closing and opening the Developer Tools to function again.

I speculate that this happens because the longString is expanded as a prop, because when the OI solely renders the value (`document.body.attributes.s.nodeValue`) the longString expands normally. It should be noted that LongString props of short object are expanded however: `a={a:'r '.repeat(5000)}`.

**Comment by darkwing** [comment]
Could not reproduce.
