### ISSUE TITLE
Cursors should be pointer styled on blank state screen links

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6269]
<img width="291" alt="image" src="https://user-images.githubusercontent.com/8599/39903550-8c8bd1fe-5488-11e8-82e8-7a7e6614d99c.png">

Both text lines are clickable and should show a pointer (but currently show a text cursor).

**Comment by AnshulMalik** [comment]
Closing in favour of https://github.com/devtools-html/debugger.html/issues/6251
