### ISSUE TITLE
Fix devtools.debugger.pending-breakpoints overflow issue

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6279]
Data in `devtools.debugger.pending-breakpoints` is invalid JSON: https://gist.github.com/digitarald/a0ccbe43a1ddf4a484a7d30ea3536746

Browser Console throws this several times:

`Warning: attempting to write 7034 bytes to preference devtools.debugger.pending-breakpoints. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.`

P1, because this might affect more frequent debugger users.

**Comment by jasonLaster** [comment]
Here is a formatted gist.
http://jsoneditoronline.org/?id=7fa7d6b45f0d498bb609086641743abd

it's just 17 breakpoints, which is not that much

**Comment by Loirooriol** [comment]
Also see #5219

**Comment by bomsy** [comment]
OLD 

```js 
 "https://ton.twimg.com/tweetdeck-web/web/dist/bundle.f8cdc25670.js:formatted:5:": {
    condition: null,
    disabled: false,
    location: {
      sourceUrl:
        "https://ton.twimg.com/tweetdeck-web/web/dist/bundle.f8cdc25670.js:formatted",
      line: 5,
      column: 0
    },
    astLocation: {
      offset: {
        sourceId:
          "server1.conn9.child1/source36/originalSource-002da27b62870739bb2396d425b57db5",
        sourceUrl:
          "https://ton.twimg.com/tweetdeck-web/web/dist/bundle.f8cdc25670.js:formatted",
        line: 5,
        column: 0
      }
    },
    generatedLocation: {
      sourceUrl:
        "https://ton.twimg.com/tweetdeck-web/web/dist/bundle.f8cdc25670.js",
      line: 1,
      column: 47
    }
  }
```

NEW

```js 
 "https://ton.twimg.com/tweetdeck-web/web/dist/bundle.f8cdc25670.js:formatted:5:": {
    condition: null,
    disabled: false,
    astLocation: {
      offset: "server1.conn9.child1/source36/originalSource-002da27b62870739bb2396d425b57db5"
    },
    generatedLocation: "https://ton.twimg.com/tweetdeck-web/web/dist/bundle.f8cdc25670.js:1:47"
  }
```

Thinking about this, i feel the sample OLD json above can be reduced to NEW json above. Some key changes
- The property key `https://ton.twimg.com/tweetdeck-web/web/dist/bundle.f8cdc25670.js:formatted:5:` already contains the sourceUrl, line and column
- location info is the same as the key above, so does not need to be repeated
- The generated Location mashes the line and column into the sourceUrl i.e 
```js
    generatedLocation: {
      sourceUrl:
        "https://ton.twimg.com/tweetdeck-web/web/dist/bundle.f8cdc25670.js",
      line: 1,
      column: 47
    }
```
becomes

```js
generatedLocation: "https://ton.twimg.com/tweetdeck-web/web/dist/bundle.f8cdc25670.js:1:47"
```

**Comment by Loirooriol** [comment]
This would be an improvement, but URLs can be very long and one may add multiple breakpoints in the same file, or in different files in the same folder. So I still think that compressing the JSON would be good.

**Comment by bomsy** [comment]
@Loirooriol Oh yes i totally agree. This suggestion was just to make the json as compact as possible, removing redundant data. Compression is definitely needed as well.

**Comment by digitarald** [comment]
Maybe I am missing something; but why does this needs to be stored in a pref and can't be stored in IndexedDB (like many other parts of Firefox do with UI state)?

**Comment by jasonLaster** [comment]
good question @digitarald
