### ISSUE TITLE
[Breakpoints] Highlighting the current breakpoint doesn't work in debugger examples

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6281]
STR: Debug http://firefox-debugger-example-react-js.glitch.me/ and set a breakpoint in Devtools.js

This pausing on the first breakpoint:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/8599/39938292-4d28a38c-5507-11e8-9c6a-131c95a83daa.png">

Same for second breakpoint:
<img width="850" alt="image" src="https://user-images.githubusercontent.com/8599/39938418-c312bf60-5507-11e8-8169-09ea5c0e5d94.png">

AR: Breakpoint not highlighted
ER: Highlighted breakpoint

P1 as this adds the missing affordance of users knowing when they are paused.

**Comment by darkwing** [comment]
@digitarald Am I understanding it right that you'd like some type of signifier in the right sidebar's Breakpoints list as to which breakpoint is currently hit?

**Comment by jasonLaster** [comment]
@darkwing we should have that, i think we're just too precise with our isCurrentlyPaused at check. See the mappedBreakpoints PR...

**Comment by darkwing** [comment]
I fixed this in @jasonLaster 's breakpoints refactor.  https://github.com/devtools-html/debugger.html/pull/6398
