### ISSUE TITLE
Callstack doesn't navigate to correct function

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6282]
STR:
- Break in a UnorderedList component in http://firefox-debugger-example-react-js.glitch.me/
- Step into `map`
- See Callstack and render entries

AR: Jumps within the `map` function
ER: Jumps to Component `render` function.

![screenflow](https://user-images.githubusercontent.com/8599/39938721-b5d7146c-5508-11e8-93e0-7fbc33c972bf.gif)

**Comment by digitarald** [comment]
Or maybe it does jump to the right last known position within render. The 2 render entries still need to be explained then.

**Comment by jasonLaster** [comment]
So, I believe this is correct, but does need some explaining. 

render - the inner render of *item* inside the map
render - the outer render for the function
finishClassComponent - tough to tell with the gif, but looks like where render was called...

**Comment by jasonLaster** [comment]
I'm going to move this to the icebox because I think it would be good to reconsider how we show display names in the call stack, but probably after we've finished the performance and quality work.
