### ISSUE TITLE
Clicking a component tooltip navigates incorrectly

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6283]
STR: Pause in https://firefox-debugger-example-react-js.glitch.me/ and hover a component

![screenflow](https://user-images.githubusercontent.com/8599/39938975-9644e74a-5509-11e8-9bfd-31dc3da0e66b.gif)

AR: Navigates to generated main.js file without a line
ER: Not sure, the component is defined in the same file

Same happens when clicking the `React.Component` tooltip.

**Comment by lukaszsobek** [comment]
That looks like a fun one :)

**Comment by lukaszsobek** [comment]
Duplicate of #6028 . Closing.
