### ISSUE TITLE
React component is shown as `render`

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6284]
STR:
- Open https://firefox-debugger-example-react-js.glitch.me/
- Add breakpoint in `render` function in `webpack:///app/components/DevTools.jsx`
- Click `Cycle`

<img width="847" alt="image" src="https://user-images.githubusercontent.com/8599/39939093-ffb74a60-5509-11e8-81ba-1727e4fdffd7.png">

AR: `render` component shown in the sidebar and in the tooltip
ER: See `DemoClicker` component

**Comment by jasonLaster** [comment]
i think this might be fixed in nightly soon
