### ISSUE TITLE
[Editor] "Jump to" in Developer tools doesn't scroll to cursor position

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6290]
Steps to reproduce:

1) Open Developer Tools
2) Open www.google.com
3) Goto Debugger tab
4) open api.google.com → js → api.js
5) Press Ctrl-J and enter "10:400"

I have a minified file with 400,000 columns, it's hard

Open any minified js file, press Ctrl-J and enter "1:400"

Actual results:

Cursor disappeared, I suspect it moved to desired position, but I have no way to scroll to this position.

Also, there's no indication of line/column cursor position anywhere on the screen 

Expected results:

Cursor jumps to position 10:400, remains visible.

**Comment by jasonLaster** [comment]
@Hindelburg interesting mind trying 61 or 62 via dev edition and nightly?

**Comment by Hindelburg** [comment]
I ran the test again in Firefox Developer Edition 61 using the dark theme and it still correctly jumped to the cursor position.

**Comment by Hindelburg** [comment]
I also tested it in nightly and it jumped to the cursor position again.
