### ISSUE TITLE
[Editor] does not show the whole file

### ISSUE THREAD

**Issue by nicofrand** [devtools-html/debugger.html#6295]
Hi,

the debugger only shows a part of the file downloaded. The file appears in full in the network tab but not in the debugger: the line 1 in the debugger is actually the line 201 in the file.

Below are animated screenshots (I have since reduced a bit the STR and connect to `/yunohost/sso` directly and not the hextris app, but the `ynhpanel.js` file is the same).

![bug-devtools](https://user-images.githubusercontent.com/3419050/39956157-8bf23982-55db-11e8-8b94-01f410297364.gif)

In the network tab:
![screenshot_20180509_174236](https://user-images.githubusercontent.com/3419050/39956198-19c1b60c-55dc-11e8-9463-f3fd787f5cf9.png)

In the debugger:
![screenshot_20180509_174216](https://user-images.githubusercontent.com/3419050/39956201-24587cf4-55dc-11e8-930c-d81cc8413b67.png)

I did not find any simple STR.
Here is what I did though:

0. I use Firefox 61.0b3
0. I installed YunoHost in a vagrant VM : https://github.com/YunoHost/ynh-dev with a local domain name of `yolo.test` and created a dumb user.
0. In went to `http://yolo.test/yunohost/` and logged in with the dum user.
0. I opened the devtools and took a look at the *ynhpanel.js*
0. The file is not displayed in full in the editor (I did not prettify the output)

I know, the STR are painful. I tried saving the page on my computer but could not reproduce the issue.
BTW, it works with Google Chrome.

**Comment by nicofrand** [comment]
Hi again,

I can actually not make it work again with a new profile. I tried downloading the nightly, creating a new profile and using it, but I still meet the issue. I can't even use another browser as it is to debug something on Firefox…

**Comment by jasonLaster** [comment]
Thanks for sharing. @janodvarko can you reproduce this?

**Comment by darkwing** [comment]
@janodvarko Can you reproduce this?
