### ISSUE TITLE
[breakpoints] can't add a breakpoint (parsing)

### ISSUE THREAD

**Issue by julienw** [devtools-html/debugger.html#6306]
This file has several problems with the current debugger's parsing capabilities:
1. An error in this function declaration:
```javascript
function _sortByField<T: Object>(fieldName: string, geckoTable: T): T {
```
2. Because of this, it then chokes on a string template:
```javascript
    const name = `Extension ${quotedName} (ID: ${extensions.id[index]})`;
```
Then below this line evrything is considered as comments and I can't add a breakpoint on any line below this. This is bad :(

Here is the full source for the file with an issue. Notice this is correct in github ;) [gist](https://gist.github.com/jasonLaster/4615ce881d54dabea9a5fca93cf379bd)

**Comment by jasonLaster** [comment]
@julienw is it easy to add an STR for how to reproduce in perf.html?

**Comment by julienw** [comment]
> @julienw is it easy to add an STR for how to reproduce in perf.html?

Oh yes, it's surprisingly easier than I thought.
1. go to https://perf-html.io
2. open the debugger
3. open the file `webpack > src/profile-logic/process-profile`
4. scroll down the file

The first error is around line 102:
![capture d ecran de 2018-05-15 12-29-19](https://user-images.githubusercontent.com/454175/40051600-9ef3fcfc-583b-11e8-9789-51d6bd21dabd.png)

The second error is around line 358:
![capture d ecran de 2018-05-15 12-30-04](https://user-images.githubusercontent.com/454175/40051624-b7e6c99c-583b-11e8-91cd-93798a469bc6.png)

> Also, i moved the source to a gist, so it is easier to curl and doesn't pollute the issue

Good move !

**Comment by AnshulMalik** [comment]
So, what I found was, the symbols were parsed correctly, on line 102, we get a function named `_sortByField` with two parameters named `fieldName` and `geckoTable`.
I think just highlighting is off. Which because of typescript mode. Here is a diff that should fix it.

```diff
diff --git a/src/utils/source.js b/src/utils/source.js
index f9332b5d..aba30d90 100644
--- a/src/utils/source.js
+++ b/src/utils/source.js
@@ -258,7 +258,7 @@ export function getMode(
       return { name: "text/typescript-jsx" };
     }

-    return { name: "text/typescript" };
+    return { name: "text/javascript" };
   }
```

**Comment by julienw** [comment]
Hey @AnshulMalik, have you looked at the second error too? This is quite more important as this prevents me from adding breakpoints.

**Comment by julienw** [comment]
Breakpoints seem to work again in latest Nightly. Source Highlighting is still off but that's a much smaller annoyance.
