### ISSUE TITLE
[Pause] Test fails when run a second time

### ISSUE THREAD

**Issue by lukaszsobek** [devtools-html/debugger.html#6319]
STR:
- Run `yarn test:js`,
- see a passing test,
- run `yarn test:js` again,
- see a failing test

The pause.spec test passes the first time, but fails every run after that:

Screen:
![screenshot-20180516085149-579x642](https://user-images.githubusercontent.com/23530054/40101299-4f705336-58e7-11e8-850a-da23f6b631c0.png)

**Comment by AnshulMalik** [comment]
Tests seems to pass for me.
