### ISSUE TITLE
[Editor] Dark theme makes selection not visible on breakpoint

### ISSUE THREAD

**Issue by andreicristianpetcu** [devtools-html/debugger.html#6329]
Set the dark theme.
Put a breakpoint somewhere.
Try to select part of the text where the breakpoint stopped.
I cannot see what text was selected.

For example I cannot see any selection done on line 8 that is part of 

```javascript
collection = state[itemName].collection;
```

![screenshot from 2018-05-17 12-07-32](https://user-images.githubusercontent.com/922368/40167931-f7e70e4a-59ca-11e8-94c5-f35d7fa720c7.png)

Full video https://vimeo.com/270327231

**Comment by LeoThalman** [comment]
I managed to fix the highlighting issue by altering the debug-expression-background for .dark theme .editor-wrapper class in the ~/src/components/Editor/Editor.css file. Is that change alright or should I try and find a fix that doesn't involve changing the color?

**Comment by jasonLaster** [comment]
can share some screenshots of how it looks?

It might help to see how it looks in the panel too
https://github.com/devtools-html/debugger.html/blob/master/docs/running-as-firefox-panel.md

**Comment by LeoThalman** [comment]
![dark-theme_new-debug-color](https://user-images.githubusercontent.com/32425569/40676615-17608db4-6330-11e8-885f-93d39cb260f6.png)
Here's what it looks like from debugger, the background color I used was the same one for the light theme, I lowered the alpha to make it easier to read. I'm downloading the code to run the panel right now, I'll add that when I can.

**Comment by LeoThalman** [comment]
![dark-theme_new-debug-color-firefox-panel](https://user-images.githubusercontent.com/32425569/40678015-2fac9f76-6334-11e8-8d71-bebe8e725831.png)
Here's what it looks like in the Firefox panel. I'll look into the hiding when there is a selection now.

**Comment by LeoThalman** [comment]
I've tried looking into hiding it when there is a selection but I can't seem to find where the selection is happening. I went through the Preview/index.js, I saw where the on mouse over was hiding css but I couldn't find where the selection was. Is there somewhere else I can look into or should I try another approach?

**Comment by basav22** [comment]
hi @darkwing, I want to give it a try. 
/claim

**Comment by darkwing** [comment]
Hey @basav22 -- I think this is fixed!  Sorry we didn't close it sooner.  I'd love to have you try another bug though! :)

**Comment by basav22** [comment]
hi @darkwing, the PR which is merged has changes to show user selection with different colour. But doesn't hide the debugger selection. You mean, this thing is fixed in some different PR ??

**Comment by jasonLaster** [comment]
@basav22 feel free to open a new issue for hiding debugger selection :) I think issues with multiple parts can be confusing.

**Comment by basav22** [comment]
thanks @jasonLaster . I will open new issue.

**Comment by andreicristianpetcu** [comment]
@LeoThalman thank you for fixing this issue!
