### ISSUE TITLE
document (and automate) release process

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#633]
I started hacking on some tools for this and there are a number of tools already out there but its probably best if I describe what I think we want since it is unlikely I'll be the one creating the releases in the future.

Overall I want people to be able to identify the debugger bundle in Firefox with the release in GitHub such that they can determine if a bug or feature has already been fixed or implemented respectively.
- We need a way to mark releases on GitHub that land in Firefox. 
  - I think we should use the [GitHub releases](https://github.com/devtools-html/debugger.html/releases) feature
  - GitHub releases use tags to create milestones and is probably best to use the [Semantic Versioning](http://semver.org/) schema which npm gives us for free.
- We need to have a consistent format for our bugzilla bugs which are landing new releases such that people can find all the information about the release they might need to understand what  is contained in the bundle.
  - Bugs will track what Firefox release they land in so we should be able to query for all bundles landed in a release (or at least the latest).  To track all bundle lands we might need a special whiteboard value or something similar.
- We should be writing up quick release notes that at least indicate major features

Here's what the release steps could be:
- run full tests (with something like `rm -r node_modules && npm install && npm test`)
- create tag (with something like `npm version minor`)
  - with a `"preversion": "rm -r node_modules && npm install && npm test"` script we can remove step one
- run `bin/make-firefox-bundle`
  - possibly use the tag + hash instead of the log message (`git describe`)
- publish `git push --follow-tags`
- generate bugzilla bug default template (possibly printed out at the end of `bin/make-firefox-bundle`) 

Here's an example bugzilla bug template:

<pre>
debugger.html
https://github.com/devtools-html/debugger.html

Release v1.0.0 (previously v0.0.1)

Release Notes:
https://github.com/devtools-html/debugger.html/releases/tag/v1.0.0 
Compared to previous release:
https://github.com/devtools-html/debugger.html/compare/v1.0.0...v0.0.1 
Compared to master:
https://github.com/devtools-html/debugger.html/compare/v1.0.0...master 

All Releases:
https://github.com/devtools-html/debugger.html/releases 
</pre>

With a bugzilla whiteboard value of something like `[debugger-html-release]` we could more easily query for all of the releases on bugzilla.

**useful commands**

latest tag: 

``` bash
git describe --abbrev=0
```

previous tag: 

``` bash
git describe --abbrev=0 `git describe --abbrev=0`^
```

**Comment by jasonLaster** [comment]
I'll do a lot of this soon in order to avoid overriding changes in m-c. 

Thanks for all of the details. Great issue!

**Comment by jasonLaster** [comment]
closing as we'll do this work in the toolbox and on m-c.
