### ISSUE TITLE
[breakpoints] Re-add the greyed out (not clickable) line numbers

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#6330]
I want to set a break point in this function and I find it really hard to pick the right line number:

![image](https://user-images.githubusercontent.com/3307404/40174480-88d6ac4e-59d5-11e8-8864-bc927af6f911.png)

For instance, I can click on line 16 but not on lines 17-20 (this is not obvious to react-to-babel-to-js beginners). Would it be possible to get back the grey-out line numbers. At the moment I find myself hovering line numbers all the time before being able to click just to find the right spot to set a breakpoint. Usually, I just want to set a bp at some place.

I'd prefer to have it back like it was before (don't have an older version, but like it was also in Chrome):
![image](https://user-images.githubusercontent.com/3307404/40174718-305449c2-59d6-11e8-8c2c-05625ceb2ee4.png)

I mean like lines 27-30 are greyed out.

**Comment by darkwing** [comment]
I agree; the following will do the trick:

1.  Create a new file, `src/components/Editor/EmptyLines.css`, with the following contents:

```js
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at <http://mozilla.org/MPL/2.0/>. */

.empty-line .CodeMirror-linenumber {
  opacity: 0.5;
}
```

2.  Import it into `EmptyLines.js`:

```js
import "./EmptyLines.css";
```

**Comment by jasonLaster** [comment]
CC @digitarald @violasong 

Another option we discussed was to show the distinction on hover.

**Comment by jasonLaster** [comment]
hey @rishispeets thanks for offering, but i dont know if we have an idea of what we want yet

**Comment by rishispeets** [comment]
Ah, gotcha! Misinterpreted your previous comment :-). I'll unclaim it.

**Comment by jnachtigall** [comment]
> Another option we discussed was to show the distinction on hover. 

Well, the problem is that the distinction between _line numbers where I can set a bp_ **vs.** _lines where I can't_ is only visible once I have reached (hover) this line number. It should be at the start of mouse movement, so I move it to the right line number. 

So I always end up hovering (searching by hover) line number to be able to set. Mentally it's like: 
1. I wanna set a bp in a function
2. Go to beginning and click line number that's not empty => Click (I usually click without actively looking on the hover) => Not working => Notice Grey (hover) => Damn it, not working => Repeat until line numbers works

I'd like to call this `search by hover` ;)

**Comment by jasonLaster** [comment]
yeah. i agree that hunting for a spot is silly :)
