### ISSUE TITLE
Glitch takes 5 seconds to load

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6332]
STR:

1. navigate to https://dbg-class-prop-this.glitch.me/
2. open devtools with the debugger

profile: https://perfht.ml/2L9WgJh

### breakdown

1. loading
2. loading
3. creating sources / creating tree
4. showing a source / creating codemirror
5. creating sources / updating tree
6. creating a breakpoint & codemirror for the bp

![g1.png](https://shipusercontent.com/56bd260cd9bbd7d4c9c13256624f95be/g1.png)
![g2.png](https://shipusercontent.com/fab2d60e35eb6be06e5604a59bb059ec/g2.png)
![g3.png](https://shipusercontent.com/e25ff58a43fa4b79090b3b359c5e720a/g3.png)
![g4.png](https://shipusercontent.com/3f18a9065ddea104bc1863f6468d6343/g4.png)
![g5.png](https://shipusercontent.com/b0f79b45ffd93a85789a89b13067e47a/g5.png)
![g6.png](https://shipusercontent.com/0ddb4c3d94247ae22b73429c6e24e186/g6.png)

**Comment by digitarald** [comment]
Confirmed fix, blazing fast loading: https://perfht.ml/2L9Rz0N
