### ISSUE TITLE
[Expressions] expanding a node does not expand the pane

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6333]
STR

1. pause and add an expression, which is an object
2. expand some keys

![](http://g.recordit.co/yASYx3RhpJ.gif)

**Comment by wldcordeiro** [comment]
Oof this looks nasty but the fix should be pretty small. Good contributor bug 🐛

**Comment by nyrosmith** [comment]
Hi @AlexMolodyh!
It looks like @darkwing has already submitted a Pull Request to fix this

**Comment by AlexMolodyh** [comment]
@nyrosmith - my bad, I didn't see that.
