### ISSUE TITLE
All the mochitests!

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#634]
This is a tracking issue for all the different sections of mochitests which cover the current debugger and need to be converted to cover this debugger.
- [ ] bfcache #635
- [x] Edge cases... #639
- [x] Pretty printing #645
- [x] Sourcemaps  #647
- [x] Source listing #648
- [x] Navigating #643
- [x] Split console #649
- [x] Breaking #636 
- [x] Auto-select preferred source #646
- [x] Editor #640
- [x] Keyboard shortcuts #642
- [x] Call frames #650
- [x] Breakpoint sliding #637 
- [x] Browser toolbox #638
- [x] iframes #641
- [x] Pause on exceptions  #644

![19ttgo](https://cloud.githubusercontent.com/assets/2134/18145565/a29bd12c-6f80-11e6-9a14-cc463dc1031a.jpg)

**Comment by jlongster** [comment]
Thanks for filing this! How come some have separate issues and others not?

Once we have a flow going (probably tomorrow, landing some stuff on m-c right now) let's ping some of the contributors and see if they'll help too.

**Comment by clarkbw** [comment]
> How come some have separate issues and others not?

I think I was just mid-workflow.

This issue would be a good place to add docs, feel free to edit the top comment.

**Comment by jlongster** [comment]
I've landed the ability to run mochitests, and documented the general workflow here: https://github.com/devtools-html/debugger.html/blob/master/docs/mochitests.md

I'm working on some of the breakpoint tests right now. If someone else, maybe @jasonLaster, wants to start playing with this, it's ready. Just read the docs. We still need to flesh out the story for various things, like how to click the gutter in codemirror, but we can start writing tests. I'm writing a test that tests the CodeMirror breakpoint gutter but running into a few issues with simulating clicking, but hopefully after we figure a few things out it'll be quick to write tests.

**Comment by jasonLaster** [comment]
Take a look at how cypress clicks the gutter. There's a helper for
scrolling to the line.

**Comment by jlongster** [comment]
My issue is something else; I think it's easiest if we use small test sources for the gutter tests that don't even need scrolling. The UI doesn't seem to be completely updated after `EventUtils.synthesizeMouseAtCenter` returns; I'm not sure if it's CodeMirror's fault or not, it could be doing something asynchronous.

**Comment by jbhoosreddy** [comment]
> The UI doesn't seem to be completely updated after `EventUtils.synthesizeMouseAtCenter` returns
I may be wrong but I ran into the same problem writing another test. Brian suggested I use `node.click` instead and it worked.

**Comment by jbhoosreddy** [comment]
> I've landed the ability to run mochitests, and documented the general workflow here: https://github.com/devtools-html/debugger.html/blob/master/docs/mochitests.md

@jlongster I may be wrong but shouldn't it be `dbg.win.document.querySelectorAll("#foo")` instead of `dbg.win.querySelectorAll("#foo")`?

**Comment by jlongster** [comment]
> I may be wrong but shouldn't it be dbg.win.document.querySelectorAll("#foo") instead of dbg.win.querySelectorAll("#foo")?

Yep, you are correct! I will update it tomorrow :)

**Comment by jlongster** [comment]
This is tracking ticket, so removing from a sprint

**Comment by clarkbw** [comment]
Taking this, my job to make sure these are all done.

**Comment by jasonLaster** [comment]
closing this issue as now we have a couple small mochitests, but i think we the main work is done. @jlongster @clarkbw re-open it if you see it differently

**Comment by clarkbw** [comment]
We still didn't get the bfcache one done but I don't see good reason to keep this tracking issue open anymore.

**Comment by jasonLaster** [comment]
yeah, bfcache is tracked elsewhere and it seems out of scope as it's more than just writing a test
