### ISSUE TITLE
When reloading page: Persist debugger tabs and/or show transparent Block UI

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#6342]
Since already considering the startpage as in #6251 what I really do not like UX wise is what happens in the debugger when I reload a page. This is one of the things I do most: Reloading and reloading the exact same page.

STR:
1. Have a page and one or more tabs (files) open in debugger
2. Hit Firefox's Reload button

AR:
1. Debugger goes blank: all tabs (files) removed.
2. The buttons as in #6251 are visible again (but one cannot interact with them really because they're gonna be removed in the next strep)
3. The buttons are removed again
4. The tabs are visible again

Steps 1-4 can be fast, but depending on the page (development sites are slow) to reload in my case it is often 5-15secs. See here:
![debugger-reload](https://user-images.githubusercontent.com/3307404/40228221-f2f9c26c-5a90-11e8-97ea-986a94186882.gif)

ER:
I am not sure. Different options:
1. Best would be if the tabs would be persisted like when debugging in VSCode (that is, editor/debugger state is persistent while reloading). But I can understand that from a technical point of view this is not possible because the debugger frontend does not know if the file was removed until the reload has finished. 
2. I think a good analogy on the web is when an area updates (say, search results). Usually, one would do this with a transparent Block UI and a spinning wheel above. Something like [React Block UI](https://availity.github.io/react-block-ui/) (click on `Toggle Block` to see what I mean)

I think showing Block UI when reloading would be best in the sense of learnt experience. That is, don't go blank but leave old state behind a opaque Block UI until the new page is reloaded which possibly updates the debugger and removes the Block UI again.

**Comment by jasonLaster** [comment]
@jnachtigall i think we should show the tabs on reload

### Simple

![](http://g.recordit.co/bn0FcBvNSr.gif)

### source maps

![](http://g.recordit.co/1bp1d2otKH.gif)

### pretty and blackbox

![](http://g.recordit.co/gsCPngMEFx.gif)

**Comment by jnachtigall** [comment]
> i think we should show the tabs on reload

Hey @jasonLaster, not sure what you mean. I also think that they should be shown. My point was that they are shown, then vanish (and startpage buttons shown), then they are shown again. The tabs should not vanish. (in short)

**Comment by jasonLaster** [comment]
ohh... i see. That is a tricky problem :)

We store all of the tabs and show tabs that have sources in the store. We need to clear the sources on navigate so that we don't accidentally have them around.

We probably do want a loading state while we're waiting for sources to stream down though... Maybe we can do something there where our loading state has the previous tabs...

**Comment by jnachtigall** [comment]
yeah, complicated for sure. Keeping the old visual state, overlayed with Block UI would do imho. Best shown only if the current page is reloaded but not when navigating to another page... At least not showing the startpage buttons which will vanish a second later anyway

Not sure on the solution, but the my above screened GIF is just when reloading the current page. That's when my mind gets confused (too much happening on reload in the debugger when just it could stay all the same visually)

**Comment by jasonLaster** [comment]
yeah. Reactive programming is hard because 10 state changes is often 10 UI changes

navigate --> update store
new source --> update store
...

Redux DevTools is great for showing the craziness here

**Comment by jasonLaster** [comment]
I think i'm going to icebox this because it is something i would like to do in a couple of months after are a bit faster and more stable.

**Comment by jnachtigall** [comment]
> I think i'm going to icebox this because it is something i would like to do in a couple of months after are a bit faster and more stable.

Totally agree, tbh stable and fast are also my biggest concerns atm :) 

Just thought that if your designer (i guess @violasong) is mocking a new design because for #6251 then this (maybe blockui with firefox ping pong spinner) might be taken into consideration as well.

**Comment by jasonLaster** [comment]
i see. thanks
