### ISSUE TITLE
[Tabs] selecting debugger.js fails to navigate

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6345]
STR:

1. load localhost:8000
2. in the toolbox, add some sources including debugger.js
3. click debugger.js

AR: nothing happens

I did a big of debugging and found that it failed [here][h], somehow we don't get to setSelectedLocaton, but we do get to addTab.

Lastly, this might be best to debug with the [browser toolbox][bt], in which case you'll want to have your own checkout of firefox. [docs](https://github.com/devtools-html/debugger.html/blob/master/docs/running-as-firefox-panel.md)

![](http://g.recordit.co/QvJCLJ8byZ.gif)

[h]: https://github.com/devtools-html/debugger.html/blob/master/src/actions/sources/select.js#L170-L174

[bt]: https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox

**Comment by darkwing** [comment]
Could be related to this, which recently went in: 

https://github.com/devtools-html/debugger.html/pull/6205

**Comment by jasonLaster** [comment]
Hey @dimitardanailov still interested?

**Comment by jasonLaster** [comment]
This seems to work now.
