### ISSUE TITLE
[Tabs] Chevron overlaps other tabs

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6347]
It looks like our new chevron image overlaps other tabs.

We should find a way to either:

1. have padding on the right so that the tabs do not go under the chevron.
2. hide the chevron when space gets tight :)

![](http://g.recordit.co/RxZrICI3Ui.gif)

**Comment by lzzluca** [comment]
@jasonLaster Hi! This fix works for me:

https://github.com/devtools-html/debugger.html/pull/6356

Checking the debugger code for the first time as part of React Europe 2018 Hackathon, hope the fix can be of interest! :)

**Comment by jasonLaster** [comment]
Oh fantastic. Happy hacking

**Comment by adancarrasco** [comment]
Seems that #6356 fixed it. Just wondering if we can close this issue as well? :)
