### ISSUE TITLE
Back and Forward buttons don't update source list

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#635]
Part of the  All the mochitests! #634 issue
- [browser_dbg_bfcache.js](https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/test/mochitest/browser_dbg_bfcache.js)

Failing Test:

```
  yield testFirstPage();
  yield testLocationChange();
  yield testBack();
  yield testForward();
```

**Comment by jasonLaster** [comment]
This is not something we can do on the client. We should plan to do a fix in the server.

**Comment by jasonLaster** [comment]
changed the label to server

**Comment by jasonLaster** [comment]
closing and moving to the bugs board as a note. We can always re-open when we're ready to tackle it.
