### ISSUE TITLE
[Search] results label should not wrap

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6354]
STR:
1. open the launchpad
2. select a file
3. cmd+f
4. search for something which appears a lot
5. narrow the editor or the debugger quite a bit...

I think we likely want to just overflow hidden it so that at a certain point it goes away... Likely the same treatment as the buttons to the right.

![](http://g.recordit.co/RJl6Suqy1K.gif)

**Comment by darkwing** [comment]
Tip: Adding `white-space: nowrap` to `.search-field .summary` will prevent this wrapping 👍
