### ISSUE TITLE
[Breakpoints] breakpoint does not appear on reload

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6355]
It's pretty hard to reproduce, but there is a scenario where after you reload and go to the file with a breakpoint you can see it in the pane, but not in the editor

![Screen Shot 2018-05-19 at 9.24.39 AM.png](https://shipusercontent.com/1dafac1fe18f66f6cb2fefea63e33971/Screen%20Shot%202018-05-19%20at%209.24.39%20AM.png)

**Comment by bomsy** [comment]
i might have and STR that works
-  debug http://firefox-dev.tools/debugger-examples/examples/todomvc/
- open `backbone.js` in the debugger
- set breakpoint on line 12
- close `backbone.js`
- refresh the debugger
- click to open `backbone.js` from the source tree

AR:
No breakpoint set on line 12 in the editor

ER:
Breakpoint should be set on line 12
