### ISSUE TITLE
breakpoint sliding [mochitests]

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#637]
Sub task of the All the mochitests! #634 issue

browser_dbg_breakpoints-actual-location.js
browser_dbg_breakpoints-actual-location2.js

[DXR search](https://dxr.mozilla.org/mozilla-central/search?q=path%3Adevtools%2Fclient%2Fdebugger%2Ftest%2Fmochitest%2F+file%3A*dbg_breakpoints-actual*&redirect=false)

**Comment by jlongster** [comment]
All of those tests are already covered in https://github.com/devtools-html/debugger.html/blob/master/public/js/test/mochitest/browser_dbg-editor-gutter.js
