### ISSUE TITLE
[Frames] Visibility difficulty for file name in call stack

### ISSUE THREAD

**Issue by gregtatum** [devtools-html/debugger.html#6374]
Screenshot taken from Nightly:

<img width="298" alt="image" src="https://user-images.githubusercontent.com/1588648/40332480-da62bb92-5d19-11e8-86ae-5dd59ab49103.png">

I have trouble reading this text with my glasses. Any smudges on my lenses or chromatic aberration at the edges of my glasses makes it very difficult to read.

**Comment by jasonLaster** [comment]
@violasong are we failing the contrast test?

**Comment by violasong** [comment]
That does seem hard to read - if this is Gray-50 (#737373), then that's usually safe, but in this screenshot it looks like it's using a lighter font weight (and maybe even a different, larger font?). Changing to the normal font weight/size/face would probably fix this.

**Comment by kenjiO** [comment]
One or both of these changes could help.  Although the selectors might be used for something else that you don't want to change.  

```diff
diff --git a/src/components/SecondaryPanes/Frames/Frames.css b/src/components/SecondaryPanes/Frames/Frames.css
index 66c6e782..bf83f296 100644
--- a/src/components/SecondaryPanes/Frames/Frames.css
+++ b/src/components/SecondaryPanes/Frames/Frames.css
@@ -29,7 +29,6 @@
 }
 
 .frames .location {
-  font-weight: lighter;
   display: flex;
   justify-content: space-between;
   flex-direction: row;
diff --git a/src/components/shared/Accordion.css b/src/components/shared/Accordion.css
index 2cfa076f..70cbd44d 100644
--- a/src/components/shared/Accordion.css
+++ b/src/components/shared/Accordion.css
@@ -53,7 +53,6 @@
 
 .accordion ._content {
   border-bottom: 1px solid var(--theme-splitter-color);
-  font-size: 12px;
 }
 
 .accordion div:last-child ._content {
```

**Comment by darkwing** [comment]
We use some slight wrapping now so we can close this.
