### ISSUE TITLE
[Docs] Move CoC and CONTRIBUTION to .github

### ISSUE THREAD

**Issue by rishispeets** [devtools-html/debugger.html#6380]
# Why

Moving `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md` to `.github` will:

1. Clean up the root dir.
2. Make sure that all documentation files that GitHub can 'hook into' are in the same place. With 'hook into', I mean that GitHub sees these documents and does something with them, like adding links to the documents under 'Helpful resources' when filing a new issue.

# How

By moving the two files to the `.github` directory, where the issue template and pull request template are also located.

**Comment by jasonLaster** [comment]
I think we want these to be discoverable
