### ISSUE TITLE
[Docs] Add a SUPPORT document?

### ISSUE THREAD

**Issue by rishispeets** [devtools-html/debugger.html#6381]
# Why 

To let new contributors easily see where to get help. Specifically, GitHub will include a link to it that will appear under _Helpful resources_, which is visible when opening an issue.

GitHub documentation that explains the feature:

https://help.github.com/articles/adding-support-resources-to-your-project/

# How

By adding a `SUPPORT.md` document to `/.github`. As a first version, perhaps something like the following draft (taken from CONTRIBUTING.md)? 

# Draft

Say hello in [Slack](https://devtools-html.slack.com/) or in the #devtools-html channel on irc.mozilla.org.

There are lots of helpful folks in [Slack](https://devtools-html.slack.com/) who would be happy to help.

| Component          |                  | :dog: :panda_face: :hamster:                                                                       |
| ------------------ | ---------------- | -------------------------------------------------------------------------------------------------- |
| Editor             | ![][editor]      | ![][jasonlaster] [@jasonlaster][@jasonlaster] <br /> ![][jbhoosreddy] [@jbhoosreddy][@jbhoosreddy] |
| Sources            | ![][sources]     | ![][arthur801031] [@arthur801031][@arthur801031] <br /> ![][bomsy] [@bomsy][@bomsy]                |
| Call Stack         | ![][call-stack]  | ![][zacqary] [@zacqary][@zacqary] <br /> ![][wldcordeiro] [@wldcordeiro][@wldcordeiro]             |
| Scopes & Variables | ![][scopes]      | ![][bomsy] [@bomsy][@bomsy] <br /> ![][arthur801031] [@arthur801031][@arthur801031]                |
| Breakpoints        | ![][breakpoints] | ![][wldcordeiro] [@wldcordeiro][@wldcordeiro] <br /> ![][jbhoosreddy] [@jbhoosreddy][@jbhoosreddy] |
| Product & UI       |                  | ![][clarkbw] [@clarkbw][@clarkbw] <br /> ![][jasonlaster] [@jasonlaster][@jasonlaster]             |

[jasonlaster]: https://avatars.githubusercontent.com/jasonlaster?size=56
[bomsy]: https://avatars.githubusercontent.com/bomsy?size=56
[wldcordeiro]: https://avatars.githubusercontent.com/wldcordeiro?size=56
[clarkbw]: https://avatars.githubusercontent.com/clarkbw?size=56
[jbhoosreddy]: https://avatars.githubusercontent.com/jbhoosreddy?size=56
[arthur801031]: https://avatars.githubusercontent.com/arthur801031?size=56
[zacqary]: https://avatars.githubusercontent.com/zacqary?size=56
[@jasonlaster]: https://github.com/jasonlaster
[@bomsy]: https://github.com/bomsy
[@wldcordeiro]: https://github.com/wldcordeiro
[@clarkbw]: https://github.com/clarkbw
[@jbhoosreddy]: https://github.com/jbhoosreddy
[@arthur801031]: https://github.com/arthur801031
[@zacqary]: https://github.com/zacqary

[scopes]: https://cloud.githubusercontent.com/assets/254562/22392764/019de6e6-e4cb-11e6-8445-2c4ec87cb4a6.png
[call-stack]: https://cloud.githubusercontent.com/assets/254562/22392766/019eca70-e4cb-11e6-8b1a-e92b33a7cecb.png
[editor]: https://cloud.githubusercontent.com/assets/254562/22392767/01a45fbc-e4cb-11e6-80e7-59ae74d587fe.png
[sources]: https://cloud.githubusercontent.com/assets/254562/22392768/01a51c2c-e4cb-11e6-8fb0-4ededa83ed5e.png
[breakpoints]: https://cloud.githubusercontent.com/assets/254562/22392822/9a15d1f4-e4cb-11e6-9519-04ed772e6f1a.png

**Comment by rishispeets** [comment]
Yes, it is. But by adding a document specifically for getting support, GitHub's helpful resources for the repo would change from being (Contributing, Code of conduct) to (Contributing, Code of conduct, Support). That might help new contributors. I agree that it's a bit redundant, but I think that the extra exposure is worth the trade-off.

**Comment by jasonLaster** [comment]
Hmm, does github do something special with these docs: Contributing, Code of conduct, Support? Maybe i'm missing something here

**Comment by rishispeets** [comment]
Ah, my bad, would have been handy to include the links:

https://help.github.com/articles/setting-up-your-project-for-healthy-contributions/
https://help.github.com/articles/adding-support-resources-to-your-project/

![Picture](https://help.github.com/assets/images/help/issues/support_guidelines_in_issue.png)

**Comment by rishispeets** [comment]
Cool! Just to be sure, do you mean going ahead with #6380 by 'move contributing'? 

If so: do you want CoC moved as well, as stated in #6380?
If not: could you clarify what you mean?

Thanks :)

**Comment by jasonLaster** [comment]
yep. that would be great.
