### ISSUE TITLE
[toolbox] the debugger tab flashes when you add a breakpoint

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6382]
It's pretty subtle, but occasionally when you add a breakpoint the debugger tab in the toolbox will flash green. The bug is in the toolbox [here](https://searchfox.org/mozilla-central/source/devtools/client/framework/attach-thread.js#14)

![](http://g.recordit.co/gUnPB7yiOW.gif)

**Comment by AnshulMalik** [comment]
Here is some info that might help:

We show green icon when the debugger is paused and blue, when it's not. So when we add a breakpoint, debugger goes to paused state and adds the breakpoint and resumes. The process is sometimes slow when we see this flash.

I don't know why we need to pause the debugger to add a breakpoint.

**Comment by jasonLaster** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1465089#c2
