### ISSUE TITLE
edge cases [mochitests]

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#639]
Sub task of the All the mochitests! #634 issue

browser_dbg_clean-exit-window.js
browser_dbg_clean-exit.js
[browser_dbg_closure-inspection.js](https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/test/mochitest/browser_dbg_closure-inspection.js)

[DXR dbg_clean Search](https://dxr.mozilla.org/mozilla-central/search?q=path%3Adevtools%2Fclient%2Fdebugger%2Ftest%2Fmochitest%2F+file%3A*dbg_clean*&redirect=true)

**Comment by jasonLaster** [comment]
closing this and adding a new "clean-exit" issue as these small edge cases might be nice. The closure issue does not seem useful as we have Reps
