### ISSUE TITLE
[Tabs] Title Not Matching Tree Title

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#6394]
I found this while testing a debugger release on YouTube:

<img width="868" alt="tree2" src="https://user-images.githubusercontent.com/46655/40434331-c071594a-5e73-11e8-9cb2-c590089827b6.png">

<img width="1056" alt="treevstabname" src="https://user-images.githubusercontent.com/46655/40434336-c2704e90-5e73-11e8-8764-1e9f5721c549.png">

**Comment by jasonLaster** [comment]
nice, we should totally fix that

**Comment by darkwing** [comment]
OK, so I found the issue here.  The URL of `video_masthead` is actually:

https://www.youtube.com/video_masthead?video_id=AOnFe2aaX14&textLine1=Get+20%25+Off+Sitewide+-+Today+only&textLine2=Shop+Now+and+Save+20%25+on+EVERYTHING&autocrop=0&autoplay_start_time=0&autoplay_duration=15000&channel_banner=1&video_wall=0&subscribe_button=1&subscriber_count=1&site_cta=1&cta_label=Shop+now&layout=material&line_item_id=4691152491&creative_id=138235268831

The tree is removing the querystring.  The tabs and breakpoint pane are not:

<img width="1277" alt="sourcenames" src="https://user-images.githubusercontent.com/46655/41060080-146e106c-6994-11e8-9626-411bf1744837.png">

@digitarald What shall we do here?  I like the cleanliness of `video_masthead` but are we concerned that multiple usages of `script.js?my-module` and `script.js?my-other-module` will cause problems?

**Comment by digitarald** [comment]
How would the sources tree handle `serve.php?file=a.js` and `serve.php?file=b.js` atm? This might be already affecting some users with dynamic server-side build steps.

Assuming filename is more important than query parameters for static assets; I would propose to try to always show the filename and show the query string in muted colors and overflow into an ellipse.

Unsure about (index); it seems that we know the real name internally and should probably just show it in Sources?

**Comment by darkwing** [comment]
Here's a step in the correct direction:

```diff
diff --git a/src/components/PrimaryPanes/SourcesTree.js b/src/components/PrimaryPanes/SourcesTree.js
index a0377544d..595d70418 100644
--- a/src/components/PrimaryPanes/SourcesTree.js
+++ b/src/components/PrimaryPanes/SourcesTree.js
@@ -42,7 +42,8 @@ import {
   updateTree
 } from "../../utils/sources-tree";
 
-import { getRawSourceURL } from "../../utils/source";
+import { getFilename, getRawSourceURL } from "../../utils/source";
+
 import { copyToTheClipboard } from "../../utils/clipboard";
 import { features } from "../../utils/prefs";
 
@@ -316,19 +317,31 @@ class SourcesTree extends Component<Props, State> {
       >
         {arrow}
         {icon}
-        <span className="label"> {this.renderItemName(item.name)} </span>
+        <span className="label"> {this.renderItemName(item)} </span>
       </div>
     );
   };
 
-  renderItemName(name) {
+  renderItemName(item) {
+    const { name } = item;
+
     const hosts = {
       "ng://": "Angular",
       "webpack://": "Webpack",
       "moz-extension://": L10N.getStr("extensionsText")
     };
 
-    return hosts[name] || name;
+    if (hosts[name]) {
+      return hosts[name];
+    }
+
+    const source = this.getSource(item);
+    if (source) {
+      return getFilename(source);
+      //return source.url;
+    }
+
+    return name;
   }
 
   renderEmptyElement(message) {
```

This update would use `getFilename`, which is used everywhere else.  I do like @digitarald's suggestion, however, of showing the "filename" as it is now but adding the querystring in a grey'd out fashion.

**Comment by darkwing** [comment]
@digitarald Oh, to answer your first question, we only show one of each file name:

https://quiver-bar.glitch.me/

**Comment by AlexMolodyh** [comment]
Sorry, I haven't had too much time to work on this so I'll unclaim it so someone else can work on it.

**Comment by bomsy** [comment]
What about showing the full(filepath + filename + query parameters) in the tab tooltip and just show the filename in the tab?

**Comment by darkwing** [comment]
Working on this now.  I think this may have been introduced by the unicode work.  Anyway, the URL is being cut down to 30 and massaged before we strip out the querystring.
