### ISSUE TITLE
[Editor] Breakpoint is missing when a file is first opened

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6395]
STR:
1. go to http://firefox-dev.tools/debugger-examples/examples/todomvc/
2. add a bp at todo-view.js#34
3. close the file
4. close the debugger
5. re-open and go to todo-view.js

ER: see the bp
AR: the bp is missing

![](http://g.recordit.co/frbOwT0OCH.gif)

**Comment by janodvarko** [comment]
This works for me  on Win10

Honza

**Comment by jasonLaster** [comment]
I believe this fixed it #6583
