### ISSUE TITLE
editor [mochitests]

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#640]
Sub task of the All the mochitests! #634 issue

browser_dbg_editor-contextmenu.js
browser_dbg_editor-mode.js

[DXR Search](https://dxr.mozilla.org/mozilla-central/search?q=path%3Adevtools%2Fclient%2Fdebugger%2Ftest%2Fmochitest%2F+file%3A*dbg_editor*&redirect=true)

**Comment by jlongster** [comment]
I'll take this one, already writing editor mochitests.

**Comment by jlongster** [comment]
This will be mostly covered by #660. I added a test for modes which is the only thing we need to copy from this slice of tests. There are still other things we need to test from the editor, but we can close this issue when that PR is merged.

**Comment by jlongster** [comment]
I think we have some good editor mochitests that cover the tests listed in the original comment, so I'm closing this.
