### ISSUE TITLE
keyboard shortcuts [mochitests]

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#642]
Sub task of the All the mochitests! #634 issue

[browser_dbg_interrupts.js](https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/test/mochitest/browser_dbg_interrupts.js)

**Comment by jbhoosreddy** [comment]
I'm just trying this one out to see if I get somewhere with this.

**Comment by jbhoosreddy** [comment]
Resolved in #691 and #718.
