### ISSUE TITLE
[feature] Examine, modify, and watch variables

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#6428]
I have not seen a bug open for this or maybe I missed it.
This is important for webcompat forensics.

Examine, modify, and watch variables
https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Examine,_modify,_and_watch_variables

> This feature isn't yet supported in the new debugger. 

Concrete case:

1. Go to http://v.pptv.com/show/3nNOzDSaCkiarKZE.html (with Firefox Nightly 62.0a1 (2018-05-27) (64-bit) and no Flash installed)
2. Open the debugger tools
3. Go to the http://player.aplus.pptv.com/jsplayer/pid/5701.js script
4. Set a breakpoint on      ` 'hasFlash': function () {`

Expected: Change the return value to one of your choice.
Actual: Can't do anything with it.

**Comment by jbhoosreddy** [comment]
For anyone reading this issue, you can examine and watch variables using 'Watch Expressions' in the Secondary Pane, in the current Debugger.

There is no obvious feature to modify variables yet. However, 'Watch Expressions' is like a console so you can modify variables there, if you're paused. Just remove to take it out. 😝 . And you can modify variables in the Console in a paused state.

**Comment by jbhoosreddy** [comment]
#6144
