### ISSUE TITLE
Syntax highlighting for haxe

### ISSUE THREAD

**Issue by Shaylin** [devtools-html/debugger.html#6445]
Hello,

I'm currently using Firefox to debug my Haxe transpiled to javascript with sourcemaps.

I've noticed that CodeMirror does support the Haxe programming language.

Would it be possible to add haxe syntax highlighting to the debugger?

**Comment by nyrosmith** [comment]
Hi @Shaylin
Thanks for reporting. I'll try to look into that soon.
Can you point me to an public accessible demo app I can test against?

**Comment by Shaylin** [comment]
Sure. This is a basic pixijs haxe demo that should work: http://adireddy.github.io/demos/pixi-haxe/basics.html

Main.hx would be the easiest file to look at in the debugger.

**Comment by jasonLaster** [comment]
Thanks @Shaylin - I think this is definitely possible. 

https://codemirror.net/mode/haxe/index.html

it might be as easy as adding a mapping here:
https://github.com/devtools-html/debugger.html/blob/master/src/utils/source.js#L256-L274

would you be up for giving this a try and letting us know what you find?

**Comment by Shaylin** [comment]
Thanks for pointing out the file to look at.

I will definitely give this a shot. I'll also let you know how it goes and a possibly make a pull request.

**Comment by Shaylin** [comment]
My pull request has been merged into master now. Closing this issue.
