### ISSUE TITLE
[Blackbox] prettified source doesn't recognize blackbox

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6459]
STR:
- Install [Grammarly](https://addons.mozilla.org/en-US/firefox/addon/grammarly-1/) (becaue it runs timeouts)
- Hit debugger *Pause* button --> Pause in Grammarly code
- Prettify `grammarly.js`
- Blackbox prettified code
- Refresh and hit *Pause* again

ER: No pausing in grammarly.js
AR: Pausing grammarly.js , using the prettified source

Bonus issue: Both my `Grammarly.js` file tabs are unclickable and only focus and open the file when selected from the Sources panel.

![screenflow](https://user-images.githubusercontent.com/8599/40862033-088d357c-65a0-11e8-98ad-7f64668007d1.gif)

**Comment by darkwing** [comment]
The failure point in debugger.html is in `command.js`' `async function blackBox` function:

```js
if (isBlackBoxed) {
    await sourceClient.unblackBox();
  } else {
    await sourceClient.blackBox();
  }
```

The `await`s never resolve.

**Comment by jasonLaster** [comment]
We opted not to support blackboxing original files because in the V1 version of blackboxing. We should consider expanding blackbox support when we do our next planning session.

**Comment by jasonLaster** [comment]
@darkwing did you disable pretty-printing blackboxed sources? If not we should while we don't support it.

**Comment by jasonLaster** [comment]
Yep, we don't disable prettyprinting blackboxed sources, should be an easy fix:

```diff
diff --git a/src/utils/source.js b/src/utils/source.js
index 48f7681..fde985c 100644
--- a/src/utils/source.js
+++ b/src/utils/source.js
@@ -60,7 +60,13 @@ export function shouldPrettyPrint(source: Source) {
   const isOriginal = isOriginalId(source.id);
   const hasSourceMap = source.sourceMapURL;

-  if (_isPretty || isOriginal || hasSourceMap || !_isJavaScript) {
+  if (
+    _isPretty ||
+    isOriginal ||
+    hasSourceMap ||
+    !_isJavaScript ||
+    source.isBlackBoxed
+  ) {
     return false;
   }
```
