### ISSUE TITLE
Preview leaks out of Editor Window

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#6474]
I spotted this small issue on Windows:

![img_1320](https://user-images.githubusercontent.com/46655/40993949-81fd4d34-68c0-11e8-84ba-893344716abf.jpg)

The `Element`'s preview leaked into the tab bar; we should keep these tooltips in the editor area.

**Comment by ATCraiger** [comment]
Hey @darkwing, I could work on this. Do you have any suggestions on how I start on this? I've worked a bit on the javascript side of the debugger, but this seems like a different type of issue.

/claim

**Comment by darkwing** [comment]
Awesome @ATCraiger!  I think a good place to start would be looking at the following file:

src/components/shared/Popover.js

Within that file we do a lot of calculations for where to place a preview popup; work was recently done on this file to get previews to display on the right:

https://github.com/devtools-html/debugger.html/pull/6196

**Comment by darkwing** [comment]
I was able to reproduce on both Mac and Windows by:

1.  Go to https://davidwalsh.name
2.  Open "davidwalsh.name/wp-content/themes/punky/js/main.js
3.  Pretty-print the resource.
4.  Add a breakpoint to line 46
5.  Refresh the page, let the debugger pause on the breakpoint, and scroll the editor down so that the breakpoint line is at the top of the editor pane.  
6.  Hover over "Element"

The preview/tooltip will appear in the tab bar.

**Comment by AarontCraig** [comment]
Ok, I was able to replicate this as well through your steps. I also found that all of the tool tips do this.
I'll get working on the JavaScript and report back soon.

**Comment by AarontCraig** [comment]
My term is coming to an end, so I'll open this up for anyone else to work on.
/unclaim
