### ISSUE TITLE
[Sources] Debuggee Hostname Not Sorted to Top When Changing Domains

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#6475]
![treesort](https://user-images.githubusercontent.com/46655/40994499-f9d73a4e-68c1-11e8-9ce1-6b053e6dc5a0.gif)

**Comment by darkwing** [comment]
STR:

1.  Open TODOMVC:  https://firefox-dev.tools/debugger-examples/examples/todomvc/
2.  Then navigate to https://davidwalsh.name

The second domain's tree doesn't always sort the debuggee URL to the top

**Comment by jasonLaster** [comment]
Oh, i think this is just in the launchpad because it doesn't get debuggeeUrl's from the client. Does this happen in nightly?

**Comment by jainsneha23** [comment]
@jasonLaster I can reproduce this in master branch, but not in nightly.

**Comment by jasonLaster** [comment]
oh yeah, this is a launchpad bug.
