### ISSUE TITLE
Tests not running successfully locally

### ISSUE THREAD

**Issue by mutdmour** [devtools-html/debugger.html#6477]
Trying to run `yarn test`

I started from a fresh clone of repo
on master branch
ran `yarn install`
then `yarn test`

it runs tests locally but outputs a bunch of errors

<img width="1280" alt="screen shot 2018-06-05 at 9 24 20 pm" src="https://user-images.githubusercontent.com/4711238/41000072-8226a1b6-6915-11e8-85c1-91253652cba0.png">
<img width="1280" alt="screen shot 2018-06-05 at 9 24 30 pm" src="https://user-images.githubusercontent.com/4711238/41000073-8254df68-6915-11e8-9822-c449a75f20d9.png">
<img width="1280" alt="screen shot 2018-06-05 at 9 24 42 pm" src="https://user-images.githubusercontent.com/4711238/41000074-827ff6a8-6915-11e8-9a15-9efa2e4876c7.png">
<img width="1280" alt="screen shot 2018-06-05 at 9 24 51 pm" src="https://user-images.githubusercontent.com/4711238/41000075-82a94f12-6915-11e8-8c3e-524f5a7d698a.png">
<img width="638" alt="screen shot 2018-06-05 at 11 06 33 pm" src="https://user-images.githubusercontent.com/4711238/41000076-82d522d6-6915-11e8-8f43-830884f49db2.png">

**Comment by jasonLaster** [comment]
This should work now
