### ISSUE TITLE
404 in contributing documentation

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#6505]
The contributing doc links to the local setup doc, but it's a 404! Here's the link it tries https://github.com/devtools-html/debugger.html/blob/master/.github/docs/local-development.md

Here is the bad link: 

https://github.com/devtools-html/debugger.html/blob/de18f3437d14270df303a523a57c931d44efa8ba/.github/CONTRIBUTING.md#L141

**Comment by AnshulMalik** [comment]
It's for all the links which go to docs

**Comment by Balaji2198** [comment]
Is there anything else to be done here? I think this got fixed in #6508. I suppose this issue can be closed?

**Comment by AnshulMalik** [comment]
Yep, closing. Thanks @Balaji2198
