### ISSUE TITLE
[Breakpoints] Right clicking on a breakpoint does not open context menu

### ISSUE THREAD

**Issue by kenjiO** [devtools-html/debugger.html#6519]
STR
Set a breakpoint. In the Secondary Panes breakpoints list, right click on the breakpoint.  Then instead of opening the context menu an error comes up in the console: `TypeError: breakpoints is undefined`

![](http://g.recordit.co/lwHV2A3spj.gif)

I was able to get the error to stop by adding `breakpoints: getBreakpoints(state)` to mapStateToProps in [Breakpoint.js](https://github.com/devtools-html/debugger.html/blob/cfa74f7b77b29496e1e0beacd970a6c7778f0768/src/components/SecondaryPanes/Breakpoints/Breakpoint.js#L175-L178).  Would you like me to do a PR for this?

**Comment by jasonLaster** [comment]
Thanks @kenjiO. That'd be great

**Comment by jbhoosreddy** [comment]
fixed in #6521
