### ISSUE TITLE
Add `recordTelemetryEvent()` helper to debugger util

### ISSUE THREAD

**Issue by MikeRatcliffe** [devtools-html/debugger.html#6529]
This helper will allow us to log simple telemetry events using `recordTelemetryEvent("add_breakpoint")` etc.

Internally this would be something like this:

```js
import { Telemetry } from "devtools-modules";

const telemetry = new Telemetry();

export function recordTelemetryEvent(eventName, fields = {}) {
  telemetry.recordEvent("devtools.main", eventName, "debugger", null, {
    "session_id": this.toolbox.sessionId,
    ...fields
  });
}
```

**Comment by MikeRatcliffe** [comment]
This is linked with https://bugzil.la/1463122

**Comment by MikeRatcliffe** [comment]
@jasonLaster I have been trying to find a way to get the toolbox (we need it to get the toolbox session id). I am struggling to find a way to get it from `devtools/client/debugger/new/src/utils/utils.js`
... did you have something in mind when you suggested it?

**Comment by jasonLaster** [comment]
yep - look at the debugger/assets/panel.js and main.js
