### ISSUE TITLE
Add simple telemetry events

### ISSUE THREAD

**Issue by MikeRatcliffe** [devtools-html/debugger.html#6533]
Depends on issue #6529

### Example

```js
import { recordEvent } from "src/utils/telemetry"; // Correct the path as appropriate

// Event without extra properties
recordEvent("add_breakpoint");
```

### Events to be added

- [ ]  "continue"  https://bugzil.la/1463122
- [ ]  "add_breakpoint"  https://bugzil.la/1463123
- [ ]  "remove_breakpoint"  https://bugzil.la/1463124
- [ ]  "pretty_print"  https://bugzil.la/1463125
- [ ]  "blackbox"  https://bugzil.la/1463126

Added (via @digitarald):

- [ ] "open_file" https://bugzil.la/1463108

**Comment by MikeRatcliffe** [comment]
This is linked with https://bugzil.la/1463126

**Comment by digitarald** [comment]
Added https://bugzil.la/1463108

**Comment by jasonLaster** [comment]
Lets create a new telemetry issue for open_file
