### ISSUE TITLE
Tab icon only show a grey box

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#6543]
**Steps to reproduce**

1. Go to http://todomvc.com/examples/angularjs/#/
1. Open the debugger
1. Open app.js

**Expected results**

I see a "JS" icon before the file name in the tab

**Actual results**

On Nightly 62.0a1 (2018-06-25), I see a grey icon before the file name.

<img src='https://shipusercontent.com/9445a1ef3657c01f5ce2408cb0e5f167/Pasted%20Image%201.png' title='Grey box instead of JS icon' width=261>

**Comment by darkwing** [comment]
This doesn't happen on master:

<img width="220" alt="wegood" src="https://user-images.githubusercontent.com/46655/41862543-cd34e8bc-7869-11e8-8734-484318cd3038.png">

I noticed this a while ago, fairly certain it's fixed.

**Comment by jasonLaster** [comment]
@darkwing do you see it in nightly?

**Comment by darkwing** [comment]
I can't load todomvc right now but this is what I see in a React app:

<img width="362" alt="notonnightly" src="https://user-images.githubusercontent.com/46655/41918282-acd45cb6-7921-11e8-8786-6043b14d3f0f.png">

**Comment by jasonLaster** [comment]
I think the we fail to properly load the angular icon there

**Comment by jasonLaster** [comment]
I was able to reproduce it in nightly, but not in the launchpad. Let me do a release and see what it looks like

**Comment by jasonLaster** [comment]
good call!
