### ISSUE TITLE
"Search in file" number of occurrences does not update when switching file

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#6544]
**Steps to reproduce**

1. Go to http://todomvc.com/examples/angularjs/#/
1. Open the debugger
1. Open todoStorage.js
1. Open app.js
1. Search (cmd + F) for angular
1. There should be 3 results
1. Switch to todoStorage.js

**Expected results**

The number of occurrences is updated to 10

**Actual results**

The number of occurrences is not updated and still says 3, until you hit enter again (which then shows 10 results). See following GIF: 

![Jun-25-2018 16-00-37.gif](https://shipusercontent.com/6be56af66bbf7b2cc4519919f01faf7f/Jun-25-2018%2016-00-37.gif)

**Comment by darkwing** [comment]
Somewhat related:  https://github.com/devtools-html/debugger.html/issues/6466
