### ISSUE TITLE
[perf] Storing too much data into devtools.debugger.tabs pref

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/debugger.html#6546]
I am seeing the following warning when stepping:

Warning: attempting to write 16114 bytes to preference devtools.debugger.tabs. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.

Fixing this should have positive impact on stepping performance.

Here is example value of the pref: https://pastebin.com/3ABGfm9X

Honza

**Comment by darkwing** [comment]
I made a rough sketch for a possible solution:

https://gist.github.com/darkwing/f8d5c430f1fd6f8dffd15d36ab57f10e

This is roughly the same strategy that @jasonLaster used when he introduced async storage:

https://github.com/devtools-html/debugger.html/commit/85069876d7a85820670ca1c67fd19c25d94cd194
