### ISSUE TITLE
prepare-mochitests-dev

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#655]
I was going through the [mochitests docs](https://github.com/devtools-html/debugger.html/blob/master/docs/mochitests.md) and step one seems to fail for me.  Will keep looking into it further but wanted to post this here in case @jlongster had ideas.

```bash
clarkbw: ~/src/mozilla/debugger.html $ ./bin/prepare-mochitests-dev
WARNING: local changes detected on mozilla-central
./bin/make-firefox-bundle: line 29: webpack: command not found
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
rm: ./bin/../firefox/devtools/client/debugger/new/test/mochitest: No such file or directory
ln: ./bin/../firefox/devtools/client/debugger/new/test/mochitest: No such file or directory
touch: ./bin/../firefox/devtools/client/debugger/new/test/mochitest/browser.ini: No such file or directory
./bin/prepare-mochitests-dev: line 14: ./mach: No such file or directory
```

**Comment by clarkbw** [comment]
Embarrassing  😲 ☕ 
I didn't have mercurial installed.  Will create a PR that checks for it in the download command.  I'm guessing there will be others who don't have `hg` installed either. 😄

**Comment by jlongster** [comment]
Good call! Yeah, those scripts can be improved. I can add some more sanity checks to them.

**Comment by jlongster** [comment]
Done in #656
