### ISSUE TITLE
Opening debugger on IRCCloud takes 5+ sec

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6557]
Open Debugger on irccloud.com.

https://perfht.ml/2Kft4Uf

- 808ms for `require`
- 300 & 250ms react rendering segments right after each other in the end

Immutable causes some overhead during the rendering phases: https://perfht.ml/2KviPu6

**Comment by jasonLaster** [comment]
yep, that's correct 

1.25s-2.25s seems to be requireHooks
3s-5s seems to be Source Tree + getRelativeSources work


![Screen Shot 2018-06-27 at 10.35.50 AM.png](https://shipusercontent.com/9121ddb1074eb1d9e6a0890bd28cb1c2/Screen%20Shot%202018-06-27%20at%2010.35.50%20AM.png)

### requireHook

![Screen Shot 2018-06-27 at 10.34.17 AM.png](https://shipusercontent.com/2e58d80c20c2f0b52c055085e3b7252a/Screen%20Shot%202018-06-27%20at%2010.34.17%20AM.png)

### getRelativeSources

![Screen Shot 2018-06-27 at 10.32.38 AM.png](https://shipusercontent.com/4acfffa76f9a0ee32226bf8a57ed8709/Screen%20Shot%202018-06-27%20at%2010.32.38%20AM.png)

### newSourcesSet

![Screen Shot 2018-06-27 at 10.32.26 AM.png](https://shipusercontent.com/64d65dbc62c14d79764ff807828ffb3d/Screen%20Shot%202018-06-27%20at%2010.32.26%20AM.png)

**Comment by jasonLaster** [comment]
Lets check in next week when sources no longer use immutable and see how `getRelativeSources` and `newSourcesSet` perform. We can also revisit lazy loaders for some of the JS

**Comment by andreicristianpetcu** [comment]
Not sure if it's the same issue. I reported it here https://github.com/devtools-html/debugger.html/issues/6587 and here is my glitch project for it https://glitch.com/~andreicristianpetcu-ngcli
