### ISSUE TITLE
[wasm] Stepping broken in WASM module

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/debugger.html#6569]
STR:

1) Load http://janodvarko.cz/test/wasm/basic1/
2) Press `Load Module & Execute Exported Function` button
3) Go to the debugger and select `test.wasm` file
4) Create a breakpoint on offset 26 (`get_local $var0`)
5) Press `Execute Exported Function` button
6) The breakpoint hits, try to step over, it doesn't work -> BUG

There is an error in the Console:
TypeError: source.text.split is not a function commands.js:157:19 

The problem is that `source.text` isn't string (for WASM modules), but an object with `binary` prop inside.

The type should be updated here:
https://github.com/devtools-html/debugger.html/blob/master/src/types.js#L286-L287

And we might also want to fix places where `source.text` is expected to be string.

Honza

**Comment by bomsy** [comment]
Closing as this seems to have been fixed, by https://github.com/devtools-html/debugger.html/commit/bf8c5a57b51040ea1822fca920f17f254c410bec

**Comment by janodvarko** [comment]
Thanks for the update, works for me now.
Honza

**Comment by jasonLaster** [comment]
Thats great @bomsy. The flow work was one of the best things we've done
