### ISSUE TITLE
[wasm] Breakpoints in WASM module are not visible in Breakpoints panel

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/debugger.html#6570]
STR:

1) Load http://janodvarko.cz/test/wasm/basic1/
2) Press `Load Module & Execute Exported Function` button
3) Go to the debugger and select test.wasm file
4) Create a breakpoint at offset 26 (`get_local $var0`)
5) Check out the Breakpoints side panel, there should be one breakpoint
6) Create a breakpoint at offset 28 (`get_local $var1`)
7) Check out the Breakpoints side panel, there should be two breakpoints, but there is still one -> BUG

Honza

**Comment by jasonLaster** [comment]
mind sharing a screenshot?

**Comment by janodvarko** [comment]
![image](https://user-images.githubusercontent.com/37785/42046918-379480a4-7aff-11e8-9b0a-5cda3c487e05.png)

**Comment by jasonLaster** [comment]
oh yeah - i bet this is an assumption we have that we'll have a line snippet for each breakpoint we show. 

For instance, we currently use the source's text field now we'd need to do something different.

As a side note, we must get the text to show in the editor at some point. At that point maybe we can replace {binary} with a string...
