### ISSUE TITLE
[object-inspector] isMacOS is not defined

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6574]
was this an effect of a recent revert?

https://github.com/devtools-html/debugger.html/blob/release-65/packages/devtools-reps/src/object-inspector/component.js#L386

**Comment by jasonLaster** [comment]
ping @nchevobbe

**Comment by nchevobbe** [comment]
Where do you see this ?

**Comment by jasonLaster** [comment]
in master

**Comment by nchevobbe** [comment]
Mh, the variable is well declared on master: https://github.com/devtools-html/debugger.html/blob/8b8299b18d1e964cd53c43562729f0056f8fcd2c/packages/devtools-reps/src/object-inspector/component.js#L14

**Comment by nchevobbe** [comment]
Don't know why it was pruned on this release branch. Maybe to avoid the issue with Services in the jsonviewer when doing the reps-bundle release on mc ?

**Comment by darkwing** [comment]
Yes, my apologies; @juliandescottes said we needed to prune due to JSONViewer breaking -- my apologies for not filing an issue sooner!

**Comment by jasonLaster** [comment]
this should be fixed now
