### ISSUE TITLE
Enable syntax highlighting for ClojureScript

### ISSUE THREAD

**Issue by finalfantasia** [devtools-html/debugger.html#6578]
I was debugging ClojureScript code and noticed that the code was not being properly syntax highlighted in the editor (as shown in the screenshot attached at the end). I first thought syntax highlighting for ClojureScript is not yet supported in the debugger and so came here to file an issue for it but found this issue #2307 that was closed more than a year ago. I was wondering whether those changes haven't made it into the debugger yet or syntax highlighting for ClojureScript is somehow broken.

My environment:
Firefox 61.0 (64-bit)
GNOME 3.28.2
Fedora 28 (Linux 4.17.2-200.fc28.x86_64)

![clojurescript_syntax_highlighting_in_firefox_61](https://user-images.githubusercontent.com/2316604/42076442-fdaf1626-7b29-11e8-86c7-e1ac42274fa9.png)

**Comment by jasonLaster** [comment]
Thanks for filing. We'll look into it soon!

**Comment by darkwing** [comment]
I pinged this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1211397 for help

**Comment by finalfantasia** [comment]
Hmm...

I'm not sure if I'm reading things right here but [ClojureScript has no syntax highlight](https://bugzilla.mozilla.org/show_bug.cgi?id=1211397) was closed as a duplicate of [Update Codemirror to 5.44.0](https://bugzilla.mozilla.org/show_bug.cgi?id=1486298) which in turn was closed as resolved for Firefox 63 but I'm still not seeing ClojureScript code being syntax highlighted in Firefox Developer Edition 63.0b2 (64-bit) on macOS.

**Comment by finalfantasia** [comment]
Firefox Developer Edition 64.0b1 (64-bit) was released today and there's still no trace of syntax highlighting for ClojureScript despite the fact that the related Bugzilla tickets were all closed two months ago. May anybody (@jasonLaster @darkwing) please shed some light on what's going on? I'm more than happy to submit pull requests, if necessary.

Thanks.

**Comment by jasonLaster** [comment]
How's it going @finalfantasia

**Comment by finalfantasia** [comment]
Hi @jasonLaster .

I guess I'll probably end up fixing this issue myself. 😁 As you may have already seen, I have a few commits lined up for a pull request and am currently working "before"/"after" screenshots and test steps.

On the other hand, I have two patches against `gecko-dev` which include changes that will include the CodeMirror Clojure mode in the Webpack bundle. However, I'm not sure how to go about submitting those patches. Should we file a new Bugzilla issue or re-open issue [ClojureScript has no syntax highlight](https://bugzilla.mozilla.org/show_bug.cgi?id=1211397) and attach the patches there? Either way, I'm going to need your help there. 🙂

**Comment by jasonLaster** [comment]
@finalfantasia i think gecko-dev and bugzilla is fine. Feel free to make an attachment for the bug and share it with me.

https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/How_to_Submit_a_Patch#Creating_a_patch
