### ISSUE TITLE
add note to mochitest docs about mercurial and autoconf

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#658]
With #655 soon fixed I think we should add notes to the [mochitests docs](https://github.com/devtools-html/debugger.html/blob/master/docs/mochitests.md) describing the need to install `mercurial` and `autoconf213`.  The first install is no big deal, the second one might lose some people, but we should at least give them a heads up.

Perhaps we should run a check in the build `make-firefox-bundle` script for the presence of `autoconf213` and exit with a message similar to the `mercurial` check.

**Comment by jlongster** [comment]
Why do you need autoconf213? I mean, I know you need it, but it should already be installed if you have the Xcode developer tools installed right? I didn't have to install it specifically, but I guess I could have done that a long time ago.

Definitely should document this though. You had Xcode installed but it wasn't on your machine?

**Comment by clarkbw** [comment]
Trying this again now and I don't need `autoconf213`, which is what I suspected previously; I believe that I needed it because it previously failed to write the mozconfig file and then tried to build Firefox from source.  Which would not have been 😎 

It did, however, fail this time because I don't have the `hg purge` extension enabled.  I think that extension is turned on when you run the mozilla setup script.  We could close this and create a new issue for the `hg purge` failure.

**Comment by jlongster** [comment]
Ah, yeah sounds good. I suppose you could guard against that, or even not do it. The purge was just helpful to remove anything leftover, but it's probably not needed.

**Comment by clarkbw** [comment]
Ugh never mind. Tried again from a clean start and I do need `autoconf2131`.  I guess I had re-linked my old autoconf which was causing the problem.  I'll add it to the docs after all and make a note about `hg purge`.  If its just a nice extra then I think we can leave it.

```
0:03.33 checking for autoconf... /usr/local/Cellar/autoconf213/2.13/bin/autoconf213
```
