### ISSUE TITLE
[Breakpoints] Breakpoint changes its place on page refresh

### ISSUE THREAD

**Issue by VillageHats** [devtools-html/debugger.html#6580]
### STR
```javascript
a = {
    sameName: () => {
        return 1; /* After refresh breakpoint is now set on this line instead. */
    }
}
b = {
    sameName: () => {
        return 42; /* Set breakpoint here and refresh.*/
    }
}
```
1. Set breakpoint on line with 'return 42'
2. Refresh page

Actual results:

Breakpoint is now set on line with 'return 1'.

Expected results:

Breakpoint should stay where it was set.

This happens when two or more methods have the same name even when they are part of different objects. 
If I had to guess debugger stores breakpoint line numbers as an offset from the line where method is defined. Then on refresh it finds the first time this method's name appears and sets the breakpoint with that offset there disregarding that there could be more than one method in the code with such name.

**Comment by darkwing** [comment]
Wow, interesting find @VillageHats !  Thank you for reporting this!

**Comment by bomsy** [comment]
I'm seeing this as well

**Comment by janodvarko** [comment]
More detailed STRs with live example:

1) Load https://lumpy-plier.glitch.me/
2) Ope the debugger and create a breakpoint on line 11 `return 42`
3) Refresh the page
4) The breakpoint is now on line 6 -> BUG

Honza

**Comment by jasonLaster** [comment]
@Jiberson i think @bomsy might be working on this. Sorry

**Comment by darkwing** [comment]
How is this going @bomsy?  Anything we can look at or help with?

**Comment by bomsy** [comment]
hey @darkwing  i'm halfway thru it, will finish it up this weekend!

**Comment by bomsy** [comment]
@janodvarko sorry just seeing this, will clean up and PR today or tommorw
