### ISSUE TITLE
[wasm] Line offset jumps if hovered by mouse

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/debugger.html#6585]
STR:

1) Load http://janodvarko.cz/test/wasm/basic1/
2) Press `Load Module & Execute Exported Function` button
3) Go to the debugger and select `test.wasm` file
4) Hover mouse over any line offset number in the left source editor gutter.
5) The number jumps to the left and is only partially visible -> BUG

See the offset 0x28 on the screenshot:

![image](https://user-images.githubusercontent.com/37785/42159572-919b3faa-7df4-11e8-83a9-6ade4c3d3583.png)

Honza

**Comment by jasonLaster** [comment]
This looks similar to #6451

**Comment by darkwing** [comment]
Fixed by reverting the hover breakpoint effect.
