### ISSUE TITLE
Debugger loads a lot slower in Beta & Nightly compared to Stable

### ISSUE THREAD

**Issue by andreicristianpetcu** [devtools-html/debugger.html#6587]
Steps to reproduce:
Open https://andreicristianpetcu-ngcli.glitch.me/
Wait for it to load.
Press Ctrl+Shift+S

On Nightly v63 + Beta v62 it loads in around 10 seconds on a fresh profile. In Stable it loads in around 2-3 seconds. Chrome loads it instantly.

This is a simple Angular app with only one component.

**Comment by jasonLaster** [comment]
We're finishing landing the 50+ commits from the 63 soft freeze. I should be able to check today.

**Comment by andreicristianpetcu** [comment]
@jasonLaster Maybe you have some time to take a look at https://bugzilla.mozilla.org/show_bug.cgi?id=1471219 also... it is really frustrating to need to kill Firefox when opening DevTools. I really hope this bug does not get shipped with v62. Not sure if it's related to this one..

**Comment by jasonLaster** [comment]
Mind trying firefox nightly again? After you update, it might be pretty fast. It was 1.5 seconds each time i refreshed.
![screen shot 2018-07-03 at 8 42 26 am](https://user-images.githubusercontent.com/254562/42220484-13187b6c-7e9d-11e8-850c-ab7ee1e1efce.png)

**Comment by andreicristianpetcu** [comment]
Same thing for https://andreicristianpetcu-ngcli.glitch.me/ This is not a weak machine Intel® Core™ i7-6820HQ CPU @ 2.70GHz × 8 + SSD + tons of RAM.

**Comment by andreicristianpetcu** [comment]
Here is my perf data. I opened/closed the DevTools about 5 times https://perfht.ml/2IPTKVZ

**Comment by andreicristianpetcu** [comment]
This does not happen anymore on the latest Nightly. Closing. Will re-open if I see it again.
