### ISSUE TITLE
Change the way we access toolbox.sessionId

### ISSUE THREAD

**Issue by MikeRatcliffe** [devtools-html/debugger.html#6589]
At the moment we do this to make the toolbox ID available:

```js
let sessionId = -1;

if (typeof window === "object" && window.parent.frameElement) {
  sessionId = window.parent.frameElement.getAttribute("session_id");
}

telemetry.recordEvent("devtools.main", eventName, "debugger", null, {
  session_id: sessionId,
  ...fields
});
```

But it is a very bad idea to rely upon the HTML structure of the toolbox in order to get the session ID.

@jasonLaster Said that we would be better creating a redux field to somehow make the toolbox session ID available everywhere.

**Comment by jasonLaster** [comment]
Hmm, maybe redux doesnt make sense for a util, here's how i'd pipe the value to the module:

https://gist.github.com/jasonLaster/c3f459c8e6c66e96cedf43560bc1eb29

1. the panel.js should get the sessionId
2. onConnect should set the ID in the module
3. the module should have the ID and the telemetry object

**Comment by jasonLaster** [comment]
As a side-note, it would also be nice if the telemetry instance had the ID, because that should be the same for the lifetime of the object.

> NOTE: not a priority

```js
import { Telemetry } from "devtools-modules";

const telemetry = null;

export function setupTelemetry(id: number) {
  telemetry = new Telemetry(id);
}

/**
 * @memberof utils/telemetry
 * @static
 */
export function recordEvent(eventName: string, fields: {} = {}) {
  /* eslint-disable camelcase */
  telemetry.recordEvent("devtools.main", eventName, "debugger", null, fields);
  /* eslint-enable camelcase */
}
```

**Comment by MikeRatcliffe** [comment]
> As a side-note, it would also be nice if the telemetry instance had the ID, because that should be the same for the lifetime of the object.

You make a good point... if we stored the ID inside telemetry.js we wouldn't need to send it with every ping.

We still need the toolbox to get the ID in the first place though.

**Comment by jasonLaster** [comment]
I think this should be done in MC first and then we can pull it in later
