### ISSUE TITLE
Modify variable on watch event

### ISSUE THREAD

**Issue by abitrolly** [devtools-html/debugger.html#6596]
I need to stub return value of a function when certain conditions are met, but I don't see that this is possible with Firefox Debugger.

**Comment by nchevobbe** [comment]
You could add a conditional breakpoint that does that maybe ?

**Comment by abitrolly** [comment]
Conditional breakpoint just pauses the execution, then I go console and stub the variable, but when I switch back to browser window, the event fires again.

**Comment by nchevobbe** [comment]
@abitrolly I think you can execute whatever you want in the conditionnal breakpoint.

Let's say you have the following function: 

```js
function x(a) {
  var ret = a * 2;
  return ret;
}
```

If you put a conditional breakpoint on `return ret;` with the following instruction `if (ret > 10) ret = "big";false;`, then executing `x(7)` will return "big".

**Comment by jasonLaster** [comment]
Thanks @abitrolly.  I'll move this issue to the icebox so we can re-evaluate later.

**Comment by abitrolly** [comment]
Thanks. Solution is logical. Just haven't got enough time to test it yet.
