### ISSUE TITLE
[Search] after deleting a search string, the last character matches are still highlighted

### ISSUE THREAD

**Issue by kenjiO** [devtools-html/debugger.html#6608]
STR
  open the file search and type some characters. Matches will be highlighted.
  press backspace to delete all the characters you typed

ER
 After deleting all the characters from the search, there will be no matches highlighted
 
AR
 matches are still highlighted for the last character deleted

![](http://g.recordit.co/yROLvZRgE7.gif)

**Comment by Jiberson** [comment]
Is it fine if I try to fix this bug?
