### ISSUE TITLE
Idea: connect selected tab to editor by removing border

### ISSUE THREAD

**Issue by jlongster** [devtools-html/debugger.html#661]
I think this makes it very clear what the current tab is:

<img width="571" alt="screen shot 2016-09-02 at 5 01 08 pm" src="https://cloud.githubusercontent.com/assets/17031/18218242/56f1fe6c-712f-11e6-9413-9b4cd961c4e9.png">

What do you think, @helenvholmes ? I love the recent updates to it, just thought this might be another small tweak.

**Comment by helenvholmes** [comment]
Hahaha, three thumbs up, I think that means we should do it 👍🏽

(James, did you want to submit the PR for it, since you've already done the work?)

**Comment by jasonLaster** [comment]
oh nice

**Comment by jlongster** [comment]
Yeah, I can try to do it this week. I didn't actually do implement it, I just fiddled with the HTML/CSS in devtools to hack it up... But it shouldn't be too hard :)

**Comment by jlongster** [comment]
It's a big deal if we don't get to it this week. It's more important to get testing and bugfixes in before the merge.

**Comment by helenvholmes** [comment]
https://cl.ly/0R0b102a3X2X << one thing to check is what happens in this situation. (Might look odd, I'm not certain.)

**Comment by wldcordeiro** [comment]
I got this one. ✋
