### ISSUE TITLE
[accessibility] hide focus ring on clicks

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6628]
@marcysutton mentioned in her fantastic talk [empathy driven development][edd] that it is possible to hide focus rings on mouse clicks with a small library [what-input]. Another option is to use [focus-visible][fs], which seems to line up better with some of the spec work.

In the future, i believe she mentioned that there will be a css selector that could help us here.

This will let us clean up some of our focus ring usage [here](https://github.com/devtools-html/debugger.html/search?q=%22outline%3A+none%22&unscoped_q=%22outline%3A+none%22).

[what-input]: https://www.npmjs.com/package/what-input
[edd]: https://youtu.be/l95VFLj3e2w?t=836
[fs]: https://github.com/WICG/focus-visible

**Comment by jasonLaster** [comment]
CC @ahuth still interested?

**Comment by ahuth** [comment]
Yes, @jasonLaster. Thanks for the reminder.

**Comment by darkwing** [comment]
Thank you for taking this @ahuth!  Let us know if we can help!
