### ISSUE TITLE
lodash-move is not properly vendored to mozilla-central

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#6640]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1475421 for STRs

lodash-move uses `export default` and should be required as `import move from "lodash-move";`. Instead it is required as `import { move } from "lodash-move";` and imported via wildcard in vendors.js. 

Not sure this even worked outside of m-c? 

On a sidenote, lodash-move is a pretty small util, rather than complexifying our vendoring story it could be better to simply duplicate the method in debugger.html.

**Comment by jasonLaster** [comment]
> On a sidenote, lodash-move is a pretty small util, rather than complexifying our vendoring story it could be better to simply duplicate the method in debugger.html.

Yeah, i can see that point.
