### ISSUE TITLE
After navigating, source pane show sources from previous location

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#6642]
And sometimes misses sources for the new location.

STRs 1:
- on a mozilla-central checkout, run `./mach python browser/components/payments/server.py`
- go to http://localhost:8000
- open debugger (apart from extensions, you should only see "(index)", under localhost:8000)
- click on "paymentRequest.xhtml"

Bugs:
- Sources pane still shows "(index)", as well as "paymentRequest.xhtml"
- "containers" folder contains only one script, while it should contain a lot more (and other folders are missing)

The first issue is Nightly only, can be easily reproduced on any navigation (eg go from mozilla.org to MDN or whatever...).

The second one already occurs on DevEdition and seems more tightly linked to this specific scenario.

**Comment by jasonLaster** [comment]
Hey @juliandescottes does this still happen for you?

**Comment by juliandescottes** [comment]
Seems fixed.
