### ISSUE TITLE
Non source-mapped files are shown as sourcemapped

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#6643]
On a website that is not using sourcemaps (eg https://www.piskelapp.com/ ) any source from static/js shows "(From {name of the file})".

![image](https://user-images.githubusercontent.com/1141550/42745521-92cf38ba-88d3-11e8-8616-a1d53a385f4c.png)

This should only show up for sourcemapped files.

**Comment by jasonLaster** [comment]
CC @darkwing
