### ISSUE TITLE
uncaught exception: SyntaxError: Unexpected token (1:9)

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#6647]
I was looking at a different Preview/Popover bug and after hovering over a popup or two, I see the following in the console:

```
uncaught exception: SyntaxError: Unexpected token (1:9)
```

Going to keep experimenting to find more default but there's no line number referenced so that's about all I can give right now.

**Comment by AnshulMalik** [comment]
Can we have STR please?

**Comment by jasonLaster** [comment]
closing as there's no STR. Feel free to re-open if you see it again
