### ISSUE TITLE
[Search] New design for Find in File/Find in Project 

### ISSUE THREAD

**Issue by violasong** [devtools-html/debugger.html#6651]
I made this mock up 2 months ago, so it's possible it needs to be updated. The main changes here include: polishing/unifying the look of the two types of search, moving the fields to the bottom, and allowing the user to still see both the fields and their open file/search results at the same time. Let me know if I should make any changes.

https://mozilla.invisionapp.com/share/Y8H6UH8V5HX#/screens

<img width="1068" alt="screen shot 2018-07-18 at 11 25 38 am" src="https://user-images.githubusercontent.com/254562/42891424-561e2204-8a7d-11e8-9f77-b57ae3fb9a2a.png">

**Comment by audreyfang** [comment]
For the Find in Project mock ups, there's a "Match directory/file pattern" bar. Is that currently a feature of the debugger? If yes, how do I bring that option up? I don't see it when I do a Ctrl-Shift-F.

@violasong To confirm a few things about the new Find in Project bar: 
- If a user has Find in File open, and then tries to open Find in Project, should the Find in File bar close or stay on screen stacked below/above the other bar?
- Should the find in project bar stay open when the user switches between tabs?

**Comment by jasonLaster** [comment]
@audreyfang it isn't! It would be great to have though
