### ISSUE TITLE
Dynamically loaded js file not visible in debugger

### ISSUE THREAD

**Issue by movedoa** [devtools-html/debugger.html#6659]
Hello i load most of my js files dynamically with jquery ($.getScript)
This works but i don't see any of these js files in the debugger.
I use typescript and transpile to js with inline sourceMapping so "//# sourceMappingURL=%Data%" is present in every js file

In chrome the js files (including the sourcemaps) show up without a problem.

If you need a small example just ask, but i guess this should be simple enough to reproduce.

**Comment by AnshulMalik** [comment]
I tried to reproduce this, but seems like no browser adds the file to the debugger. It's be really helpful if you can find some time to set up an example.

**Comment by movedoa** [comment]
After some digging I found a 4 year old bugzilla entry which I think is this exact problem.
https://bugzilla.mozilla.org/show_bug.cgi?id=1115991

**Comment by movedoa** [comment]
(Sry for the spam)
After reading though the bug it seems this is not very easy to solve.
Since getScript doesn't do anything special that i need i just wrote my own version which works, everything shows up fine

Feel free to close this issue
