### ISSUE TITLE
Watch expression "delete" button is shown on top of the Reps arrow icon

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#6670]
**Steps to reproduce**
1. Open the debugger
2. Add the following watch expression: `({a: 1})`

**Expected results**

I can click the arrow icon

**Actual results**

The remove expression icon is shown on top of the arrow icon:
<img width="231" alt="image" src="https://user-images.githubusercontent.com/578107/43006979-5ca7c2b8-8c37-11e8-8a96-e3e475cb4142.png">

**Comment by jaikathuria** [comment]
@nchevobbe can you please help me reproduce the issue because I was able to get the **Expected results**
![2018-08-06 19 38 36](https://user-images.githubusercontent.com/13422807/43721481-83a1f560-99b0-11e8-86d4-9e9982388f7d.gif)

**Comment by jasonLaster** [comment]
@jaikathuria interesting. I still see in the panel.
I wonder what is different...

![screen shot 2018-08-06 at 1 35 29 pm](https://user-images.githubusercontent.com/254562/43731785-9c452da4-997d-11e8-9fcc-4d7c66945c31.png)

**Comment by jaikathuria** [comment]
I don't know if OS and Browser could make a difference here, I am on High Sierra 10.13.4 and my broswer is Firefox Version 61.0.1 (64-bit)

**Comment by darkwing** [comment]
...weird.  So I'm seeing that in launchpad the following appears:

```css
html[dir="ltr"] .expression-container__close-btn {
    right: 0px;
}
```

But doesn't when I inspect a Firefox build.  Upon more inspection, the following *does* appear in our CSS:

```css
offset-inline-end: 0px;
```

So that's being translated in launchpad to `html[dir="ltr"] .expression-container__close-btn {right: 0px; }` but *not* inside panel -- it's just showing `offset-inline-end: 0px;` as in invalid style:

<img width="416" alt="offsetinlineendwtf" src="https://user-images.githubusercontent.com/46655/44275011-52a8ce00-a209-11e8-90c4-07866e49915a.png">

**Comment by fvsch** [comment]
The direction-aware `offset-*` properties were renamed to `inset-*` in the CSS draft.
Firefox seems to have implemented that change in [bug 1464782](https://bugzilla.mozilla.org/show_bug.cgi?id=1464782), targetting Firefox 63.

**Comment by fvsch** [comment]
See also:

- [offset-* logical properties have been renamed to inset-*](https://www.fxsitecompat.com/en-CA/docs/2018/offset-logical-properties-have-been-renamed-to-inset/)
- [Intent to deprecate and remove: offset-* logical properties. ](https://groups.google.com/forum/#!topic/mozilla.dev.platform/mG6Wpz5C2PM/discussion)

The latest `postcss-bidirection` doesn't support this change:
https://github.com/gasolin/postcss-bidirection/blob/master/index.js
So it might need a PR, and perhaps should be temporarily vendored in this project.

Alternatively, it might be possible to double the declarations:

```css
.foo {
  offset-inline-end: 0px;
  inset-inline-end: 0px;
}
```

I’m only seeing a handful of `offset-inline-(start|end)` uses in this repo.

**Comment by darkwing** [comment]
Ugly solutions are better than no solution, and I very much like your idea for duplicate properties!

**Comment by darkwing** [comment]
## Suggestions for fixing:

1.  Do a search in `src/` for `offset-`
2.  Duplicate each property with `inline-`

**Comment by mbochynski** [comment]
Hi, I was not able to reproduce the issue on FF 63.0a1 (2018-08-17). Do you still want to have this suggested fix applied?

BTW in 2. you probably meant `inset-` not `inline-`.

**Comment by fvsch** [comment]
I can reproduce in the same version (on macOS).

The issue happens in the Debugger shipped with Firefox, not the version that you can that you can get from GitHub and build with Node and yarn. I don’t know the differences in build setup well, but apparently the Firefox version does not use postcss and the `postcss-bidirection` plugin.

The "web" version that you can build with Node, yarn, webpack etc. seems to use this plugin, so the outdated `offset-inline-*` syntax is transformed to the kind of code shown by David in https://github.com/devtools-html/debugger.html/issues/6670#issuecomment-413904176.

**Comment by darkwing** [comment]
Yep, still happens for me:

<img width="1373" alt="error" src="https://user-images.githubusercontent.com/46655/44288421-eee8ca00-a235-11e8-93f9-77a7e8e2a771.png">

**Comment by mbochynski** [comment]
Yeah, just in a moment when I commented I've realized that I was looking in wrong place. Sorry for noise.
