### ISSUE TITLE
debugger.html should use local version of devtools-utils

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#6679]
debugger.html depends on version 0.0.13 of devtools-utils, while the local version in packages in only version 0.0.12. This prevents the debugger from using the local version for the workspace.

We should bump the local version at https://github.com/devtools-html/debugger.html/blob/master/packages/devtools-utils/package.json#L3 and synchronize it with the version in debugger.html's main package.json.

Additionally, all packages coming from workspaces could use a more explicit version number (eg "local"), and have a comment explaining how they are resolved.

**Comment by jasonLaster** [comment]
> Additionally, all packages coming from workspaces could use a more explicit version number (eg "local"), and have a comment explaining how they are resolved.

Why do you think we should have an explicit "local" version number?

**Comment by juliandescottes** [comment]
> Why do you think we should have an explicit "local" version number?

For documentation purposes, that's a least the 3rd time I have been confused by the lack of documentation around the usage of "workspaces" :)

**Comment by jasonLaster** [comment]
I can see that. I agree we should try and find something more obvious. Lets leave this issue open so that we can prioritize fixing it up. It would be nice to see if we can make version numbers optional.

https://twitter.com/arcanis/status/1021415846663655424

**Comment by juliandescottes** [comment]
`0.0.0` works for me as well, it's pretty clear it's non-versioned.

Regarding adding comments, the `"//"` might not in the middle of the "dependencies" object, like: 

```
  "dependencies": {
    "some-npm-package": "0.10.0",
    [...]
    "//": "Warning all the 0.0.0 versioned packages below are resolved from yarn workspaces!",
    "devtools-utils": "0.0.0",
    [...]
  } 
```

To be honest I haven't tried but I thought "hmmmm this won't work in the middle of `dependencies`".

**Comment by jasonLaster** [comment]
I'm going to close this and wait for yarn to let us drop versions for local packages.
