### ISSUE TITLE
logo proporsal for debugger 

### ISSUE THREAD

**Issue by anablog** [devtools-html/debugger.html#6683]
Hello a pleasure in greeting you, I wanted to introduce myself I am Ana Medina Graphic Web Designer, I am very interested in your new open source project for me it would be a pleasure to provide my services as a designer and collaborate without commitments, You require a new logo for your brand I can help him?

I well be pleased to collaborate with you.

**Comment by jasonLaster** [comment]
@anablog lets discuss this in our slack!
https://devtools-html-slack.herokuapp.com/
