### ISSUE TITLE
Horizontal scrollbar of preview popup is only visible at bottom

### ISSUE THREAD

**Issue by gerdneuman** [devtools-html/debugger.html#6686]
Using Windows 10 Nightly with Dark Theme.

This is from a real world problem I had, here's a minimal reproducable example.

**Steps to reproduce:**
1. Go to https://30926wj5o5.codesandbox.io/
2. Set breakpoint on line 31 (Interestingly, this also adds a breakpoint on line 32, but I think this is bug #6685) 
3. Reload
4. Hover over variable `myLongObject`

**Actual results:**
The horizontal scrollbar is not visible so it looks like the value is cropped. It was not obvious to me that the value goes on. The horizontal scrollbar is only visible when scrolling to the bottom.

![horizontal-scrollbar](https://user-images.githubusercontent.com/12525563/43132176-335dc946-8f3b-11e8-8e9e-83b50774eb8c.gif)

**Expected Results:**
The horizontal should always be visible.

**Comment by jasonLaster** [comment]
Hey @darkwing is it possible we fixed this yesterday?

**Comment by darkwing** [comment]
I doubt it; my guess is that the container doesn't allow vertical overflow but the tree inside it does.  Famous last words but this doesn't look too difficult to fix.

**Comment by AnshulMalik** [comment]
`overflow: none` [here](https://github.com/devtools-html/debugger.html/blob/master/packages/devtools-components/src/tree.css#L6) seems to resolve this, can you please verify?
