### ISSUE TITLE
The splitter's drag area is too narrow

### ISSUE THREAD

**Issue by captainbrosset** [devtools-html/debugger.html#669]
By drag area, I mean the area where the cursor turns to ew-resize and you can drag the splitter to resize the sidebar.
From my testing, it looks like it's only 1px wide (maybe 2?), which is way too narrow to reliably drag the splitter.
Especially on my desktop computer with a mouse, it gets hard to precisely get the splitter, maybe with a touchpad it's easier, not sure.
I think the line between the 2 panels should remain a 1px line, but there should be a hidden element on top that's at least 5px (not sure how wide we have other splitters in devtools) that serves as a proxy for dragging.
![capture](https://cloud.githubusercontent.com/assets/1152698/18303774/0bfbc8bc-74df-11e6-8f0c-d4774b76c674.PNG)

**Comment by jasonLaster** [comment]
We discussed this feature here #426 #623 earlier and agree.

This will probably be its own enhancement that we should schedule for next sprint.

**Comment by jlongster** [comment]
Definitely agree with this one. Seems like the collapsible sidebars work fixes it.
