### ISSUE TITLE
[SourceTree] left arrow behavior is broken

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6693]
When an item is focused in the source tree and the user presses the left arrow it should do one of two things:

a) **a source is focused** the next directory should be focused
b) **a directory is focused** the directory should be collapsed

![](http://g.recordit.co/y1chMIYxs4.gif)

![](http://g.recordit.co/TK0lGydImk.gif)

**Comment by darkwing** [comment]
I just did some basic testing and this functionality works for me, but we can discuss it tomorrow
