### ISSUE TITLE
[Preview] immutable records in a react component are not shown

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6694]
It looks like we fail to preview immutable records when they are defined in a react component.

The STR for me is pausing in SecondaryPanes/Breakpoints.js#render. We should create a small test case though for this...

![](http://g.recordit.co/GpwN7q7HsF.gif)

**Comment by janodvarko** [comment]
I was able to repro this issue before, but not anymore.
Here is what I am doing:

1) Load Debugger landing page (in a tab)
2) Pick a tab to debug: https://new.codesandbox.io/
3) Open the Toolbox, select the Debugger
4) Looking for `SecondaryPanes` in the Source tree, it's not there...?

What I am doing wrong?

![image](https://user-images.githubusercontent.com/37785/44532243-f2c39300-a6f2-11e8-92be-c03287363d12.png)

**Comment by jasonLaster** [comment]
You're looking at the Launchpads components dir. The debugger's directory
is there too :)

Try cmd+p and searching for the file

**Comment by janodvarko** [comment]
This needs new STRs, I can't reproduce the issue any more (the source code has been refactored).

@jasonLaster: can you look at it please?

Honza

**Comment by jasonLaster** [comment]
Here is a good example:

https://codesandbox.io/s/k92mv0jxqv
