### ISSUE TITLE
Font-families and font-sizes differ from the rest of Firefox devtools

### ISSUE THREAD

**Issue by captainbrosset** [devtools-html/debugger.html#670]
Here's a screenshot comparing the old debugger (as it is now in dev edition), and the new one embedded into Firefox Devtools:

![capture](https://cloud.githubusercontent.com/assets/1152698/18304006/2f271200-74e0-11e6-87de-4378146f4273.PNG)

1) the sidebar panel
Both the font size and family look different between the old and new debugger UIs.
Maybe we want to stick to this new look when the new debugger is in its own app, but when it's embedded into Firefox, I think it should match the rest of the style of the toolbox, to look consistent.

2) the source editor
Both the old and new seem to use the same font-size and a monospace font family, but there is a subtle difference still. Look at the letter f for instance, you'll see those aren't the same font exactly.
Same as for 1), we should probably be consistent with the rest of Firefox, at least when embedded in it.

**Comment by jlongster** [comment]
For what it's worth, I put a lot of work to make sure that it's loading exactly the same CSS. In the panel, it's still inheriting some additional CSS that we don't have in the local tab. But it should be identical, and any problems are our CSS explicitly overriding it which we should remove. Thanks for filing!

**Comment by tonio** [comment]
![screenshot from 2016-09-14 08-41-31](https://cloud.githubusercontent.com/assets/21686/18502388/24cfb060-7a57-11e6-9a6b-8e28cbcdc985.png)

On linux, I got really big font size differences (see attached screenshot). Don’t know if it’s related, but line number are badly aligned with their corresponding lines…

**Comment by jlongster** [comment]
@wldcordeiro you are on linux, right? Can you reproduce the above screenshot?

**Comment by wldcordeiro** [comment]
@jlongster didn't see this till now but I just built moz-dev today and it looked like this. So no reproduction here.

![screenshot_20160916_103416](https://cloud.githubusercontent.com/assets/580982/18593554/270f6b10-7bf9-11e6-94ac-f15a916f035a.png)

**Comment by wldcordeiro** [comment]
floating window as well

![screenshot_20160916_103841](https://cloud.githubusercontent.com/assets/580982/18593691/dc37053e-7bf9-11e6-9a42-33454cfa3376.png)

**Comment by jasonLaster** [comment]
Looks like this issue is coming from this App.css html,body rule: https://github.com/devtools-html/debugger.html/commit/cf66f84da35299433da039ad66efcdc64424690e#diff-b0ea81e204f18a27b1f04a9cfb44581eL11

I'm inclined to disable the font-family as we want to be using system fonts. 

With it on:
![screen shot 2016-09-20 at 3 25 31 pm](https://cloud.githubusercontent.com/assets/254562/18685488/3e3d7c14-7f46-11e6-8a8b-2ddbf81757c8.png)

With it off
![screen shot 2016-09-20 at 3 26 52 pm](https://cloud.githubusercontent.com/assets/254562/18685512/57b4f14a-7f46-11e6-9822-8365fb6c58dd.png)
