### ISSUE TITLE
The sidebars can be made so big that the a second horizontal scrollbar appears

### ISSUE THREAD

**Issue by captainbrosset** [devtools-html/debugger.html#671]
STR:
- grab the left splitter,
- drag it to the right,
- continue dragging until a second scrollbar appears.

Or:
- grab the right splitter,
- drag it to the left,
- continue dragging until a second scrollbar appears.

See the screenshots below:
![capture1](https://cloud.githubusercontent.com/assets/1152698/18304181/3afd4f30-74e1-11e6-98e2-85a2b6499f6a.PNG)
![capture](https://cloud.githubusercontent.com/assets/1152698/18304182/3dbd585a-74e1-11e6-9cb8-5fa97b6ff1d3.PNG)

As you can see, there's no limit to how much you can drag, and that causes an extra horizontal scrollbar to appear.
You can make the left sidebar so big that everything else disappears from the viewport.
And you can make the right sidebar so big that the word "No Breakpoints" starts to shift and isn't centered anymore.

**Comment by jasonLaster** [comment]
haha - we should probably have some sensible max-widths.

nice find

**Comment by jasonLaster** [comment]
Looked into this briefly. It would be nice if step 1 was to update `h-split-box` so that we're consistent with m-c

**Comment by wldcordeiro** [comment]
@jasonLaster I could look into that. Pull down `h-split-box` and diff it with `SplitBox`. I'd like to find out if it's possible to have a single `SplitBox` that does horizontal and vertical rather than two with an awkward name.

**Comment by jlongster** [comment]
This was fixed by #805
