### ISSUE TITLE
[Tabs] feature to re-order editor tabs

### ISSUE THREAD

**Issue by kenjiO** [devtools-html/debugger.html#6711]
I thought it will be nice if people can re-order the tabs of the open files in the editor by dragging and dropping them.  I would like to try to implement this using the method used [for the toolbox tabs](https://searchfox.org/mozilla-central/source/devtools/client/framework/toolbox-tabs-order-manager.js).  Can you let me know your thoughts about this?

**Comment by darkwing** [comment]
Wow, that would be an awesome feature @kenjiO !  I'd love to see something like that :)

**Comment by kenjiO** [comment]
/claim
Cool.  I'll be able to get started on it next week.

**Comment by jasonLaster** [comment]
Thanks, after thinking about it. I love the feature, but I'm not sure if sharing the code makes sense. Let's see what it looks like on tabs.js

Also there's a great ticket for refactoring the trans redux logic. This might be a good prerequisite.  CC @bomsy

**Comment by bomsy** [comment]
The ticket @jasonLaster is probably referring to is #3279. it has some useful PRs that might need little to finish off.

**Comment by kenjiO** [comment]
I'll wait until #3279 gets finished then.  What still needs to be done for that one?

**Comment by jasonLaster** [comment]
@kenjiO it was close, but everyone got busy... 

https://github.com/devtools-html/debugger.html/pull/5672/files honestly is pretty old and we've come a long way since then. For instance we have much better flow types and no longer use Immutable for sources. If i were to start it now, I'd draw inspiration from it, but then start from scratch:

1) create a reducers/tabs.js file
2) separate tabs actions
3) wire it all up

**Comment by darkwing** [comment]
I feel like a re-ordering feature may be a bit much but the idea of a "pinned" tab makes sense to me.  I can see a scenario where someone would want 2-3 given tabs always displaying first.

**Comment by jasonLaster** [comment]
I feel like both of these features can be added to the icebox. Neither feels like an immediate goal for the team, but we would be happy to review PRs.

**Comment by kenjiO** [comment]
OK.  I was putting this off because there were a lot of other PRs dealing with tabs that I didn't want to interefere with.  If you ever want to implement this feature let me know.
