### ISSUE TITLE
[Sources] Vertical scrollbar is missing in the sourcepanel

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#6718]
**Steps to reproduce**
1. open the debugger on a page with a good number of sources (any todomv exa,ples should do)
2. Reduce the debugger window height so the source panel should show a scrollbar

**Expected results**

There's a vertical scrollbar

**Actual results**

There's no vertical scrollbar: 

![image](https://user-images.githubusercontent.com/578107/43402777-c7e8e758-9413-11e8-8990-f751adc592bc.png)

---

Reproduced on latest master and Nightly

**Comment by darkwing** [comment]
Yep, this happened with the accessibility stuff; `.sources-panel` has `overflow: hidden;` which is causing the problem.  Looking at it now
