### ISSUE TITLE
Scroll position in different tabs isn't preserved

### ISSUE THREAD

**Issue by captainbrosset** [devtools-html/debugger.html#672]
STR:
- open 2 JS files in the debugger UI,
- notice that you now have 2 tabs at the top,
- in one of them, scroll down to the bottom,
- click on the other tab,
- click back to the first tab,
- notice that it's no longer scrolled down.

I think this comes down to the fact that they really aren't separated tabs, but just a way to navigate between files recently opened. Maybe it wouldn't be too hard to also store the codemirror scroll position in the state and restore it when that file becomes selected again?

**Comment by jasonLaster** [comment]
This would be a good candidate for an enhancement in the next sprint.

I implemented the feature in the last debugger with codemirror documents and it is pretty straightforward, but there are edge cases with clearing state on navigation and keeping state outside of the redux app state that make it a little complicated.
