### ISSUE TITLE
Node 10.6.0 - yarn install fails because of 'upath' package in development

### ISSUE THREAD

**Issue by ganapativs** [devtools-html/debugger.html#6720]
`yarn install` fails in development with `node 10.6.0` & `yarn 1.7.0`.

```
yarn install v1.7.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

This issue is fixed by `upath` [here](https://github.com/anodynos/upath/pull/15).

**Additional info:**

Output of `yarn why upath`
```
yarn why v1.7.0
[1/4] 🤔  Why do we have the module "upath"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "upath@1.1.0"
info Reasons this module exists
   - "_project_#documentation#chokidar" depends on it
   - Hoisted from "_project_#documentation#chokidar#upath"
   - Hoisted from "_project_#webpack#watchpack#chokidar#upath"
info Disk size without dependencies: "28MB"
info Disk size with unique dependencies: "28MB"
info Disk size with transitive dependencies: "28MB"
info Number of shared dependencies: 0
✨  Done in 1.09s.
```

This can be fixed by removing `yarn.lock` and re-creating by running `yarn`, but this will probably pull latest versions of some dependencies which might break things.

For now, I can install dependencies with `--ignore-engines`, but is there any better way?

**Comment by ganapativs** [comment]
I did re-create `yarn.lock` in local and looks like some `remark` dependencies are updated which breaks `lint:md` command with a warning.

```
docs/updates/updates-3-21-2017.md
  66:250  warning  Cell should be compact  table-cell-padding  remark-lint
```

I'm new to debugger.html project, yet to understand how things work here, so it would be nice if someone experienced actually fix development flow for `node 10+`.

Thanks :)

**Comment by jasonLaster** [comment]
thanks. will do

**Comment by jasonLaster** [comment]
So, I'm working on #6730 and it is quite challenging. Haha turns out upgrading all the dependencies in one go has some surprises...

**Comment by ganapativs** [comment]
@jasonLaster Please checkout http://npmjs.com/package/babel-upgrade to upgrade babel dependencies & `.babelrc` automatically.
