### ISSUE TITLE
[Tabs] Visual jitter during file opening because of delayed icon

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6725]
STR:
- Open a file from sources
- Watch tab …

ER: Stable layout
AR: Icon pops in late and grows the tab

![screenflow](https://user-images.githubusercontent.com/8599/43420869-f49395b0-93f9-11e8-9944-6695d02f32d6.gif)

**Comment by jasonLaster** [comment]
We've discussed refactoring the tabs data structure for awhile now #3279. This would let us save the framework field for a tab so that on re-load it wouldn't have to re-calculate.

CC @kenjiO

**Comment by AnshulMalik** [comment]
We can have a placeholder icon that is on by default, and when we know the framework, we update it.

CC @phoenixking25

**Comment by AnshulMalik** [comment]
Trying to work on this [here](https://github.com/devtools-html/debugger.html/compare/master...AnshulMalik:tabs?expand=1)
