### ISSUE TITLE
Prettify Source button hides scrollbar buttons

### ISSUE THREAD

**Issue by captainbrosset** [devtools-html/debugger.html#673]
![capture](https://cloud.githubusercontent.com/assets/1152698/18304393/7618f118-74e2-11e6-940e-1ba0d2fb62b0.PNG)

Note that I'm on windows 10 with the light theme, so I don't have floating (OSX-like) scrollbars. Instead I have big ugly scrollbars with arrows at both ends.

The Prettify Source button is at the bottom right of the source editor, so it hides 2 of these arrows, and I can't click on them.

**Comment by jasonLaster** [comment]
This will be address soon in #438
