### ISSUE TITLE
[Pretty Print] Better format duplicate filename text

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#6733]
We should incorporate logic that doesn't do the extended file information when they're the same file, only pretty-printed.

<img width="1057" alt="probs" src="https://user-images.githubusercontent.com/46655/43487660-e2897374-94dc-11e8-9025-a720a7299b82.png">

**Comment by jainsneha23** [comment]
@darkwing Have you thought on the behavior is the path name is too large? Should we truncate as we do for the filenames?

**Comment by jaikathuria** [comment]
I guess something can be done here for large paths but truncate them won’t be good idea. Assume the following case when paths are 

```
abc/project2/html/landing/
abc/project3/html/landing/
```

If we truncate both for say 15 length the main difference between two paths that we actually want to display to differentiate between the files would be missing.
Just my thoughts 🙄

**Comment by darkwing** [comment]
I'm wondering if there's a logical way to identify the difference between the two paths and show that, i.e. project2 vs project 3 in @jaikathuria 's example.

**Comment by jasonLaster** [comment]
hmm, if the preceding part is long  we could show `.../abc/project2/...`

@jainsneha23 is this easy to modify with your existing logic?

**Comment by jainsneha23** [comment]
@jasonLaster @darkwing @jaikathuria 
We also have very long paths like in www.google.com, which made me feel like truncating.
@jaikathuria  your example also makes sense. 
So, we have 2 cases here.

<img width="1414" alt="screen shot 2018-08-14 at 4 36 03 pm" src="https://user-images.githubusercontent.com/8366397/44088287-3851dbc6-9fe0-11e8-80d1-667cc0a6ae3b.png">

**Comment by jasonLaster** [comment]
i think we should drop query strings from paths. perhaps show them for titles where you want more info...

**Comment by ryzokuken** [comment]
Please close this.

**Comment by jainsneha23** [comment]
Seems like the original requirement of the issue is fixed and merged. What else is pending to be done here? @darkwing 
Else can we close this issue please?

**Comment by darkwing** [comment]
Your work was amazing @jainsneha23!  Thank you so much!

I'm going to look into improving the logic this week, so let's keep it open for now.  Thank you!
