### ISSUE TITLE
Two Breakpoints Active in Secondary Pane

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#6734]
I was resuming through breakpoints and saw that two of them were marked as active:

<img width="1057" alt="probs" src="https://user-images.githubusercontent.com/46655/43488092-37cb8b28-94de-11e8-99e7-8d912fa74ddd.png">

Only one should be active at a time.

**Comment by darkwing** [comment]
Hello @Rohanhacker !  Were you still working on this?  Anything we can help with?

**Comment by Rohanhacker** [comment]
@darkwing I'll send a pr this week

**Comment by jasonLaster** [comment]
Here's where the bug is
https://github.com/devtools-html/debugger.html/blob/master/src/components/SecondaryPanes/Breakpoints/Breakpoint.js#L97-L102

we likely want to only highlight it IF it is the closest breakpoint. so at the column or the closest to the right of the pause location

**Comment by Rohanhacker** [comment]
@jasonLaster ok, I'll start on this tomorrow and will reach out if I have any questions

**Comment by Rohanhacker** [comment]
@jasonLaster so Should I change it to get the location with column and then highlight it if its close enough ??

**Comment by jasonLaster** [comment]
@Rohanhacker i think that makes sense

**Comment by janodvarko** [comment]
Does anybody have a simple online test page for this?

Honza

**Comment by darkwing** [comment]
I found steps to repeat:

1.  Go to https://davidwalsh.name
2.  Pretty-print `main.js`
3.  Add breakpoints to lines 2, 7, 9
4.  Refresh
5.  Notice:  main.js' pretty-printed page  tab pauses at line 45.  Weird.  Also, no sources highlighted with green in the right breakpoints pane
6.  Click on "main.js", the generated file
7.  All breakpoints in the right pane are highlighted

**Comment by darkwing** [comment]
I yolo'd with this a little bit (thus the `console.log` calls): 
 https://gist.github.com/darkwing/370807f88b5938d80b1e8204218cc3a3

The big change is using `makeLocationId` but it's sort of weird in that my steps to reproduce (https://github.com/devtools-html/debugger.html/issues/6734#issuecomment-422563408) still don't match, but if I put breakpoints on the pretty file's lines 30, 31, 32, 33, etc. (that batch of var declarations) they all show the single breakpoint highlighted properly.

@loganfsmyth Do you know of any existing location between original and generated sources when a breakpoint is hit?  With my original STR, the columns are shown as 30, 125, and 149 for the original source:

![whensettingbps](https://user-images.githubusercontent.com/46655/46714226-ffa73200-cc1f-11e8-9ed0-e4a3410bae81.gif)

When I refresh and the breakpoints hit, however, the breakpoint's column number is 590:

<img width="867" alt="590" src="https://user-images.githubusercontent.com/46655/46714258-249ba500-cc20-11e8-9f25-055b440c2d2d.png">

Any idea what could cause this?

**Comment by darkwing** [comment]
I think we should hold on this until @jasonLaster's column breakpoint stuff is in; this is essentially a location weirdness issue and using Logan's location work would be good.

**Comment by darkwing** [comment]
@loganfsmyth Just pinging you on this since I don't recall getting feedback.  I also don't know if your breakpoint specificity stuff would cover the oddness from this comment:  https://github.com/devtools-html/debugger.html/issues/6734#issuecomment-428439141

**Comment by loganfsmyth** [comment]
Yeah, sounds like we should re-evaluate once the specificity work is done. We'll probably need to do some work on how we track and sync breakpoints, since server-side they only really have a generated location. We'll probably want to threat the original position as render-only and maybe use it on reload when syncing things to the new file content.

> Do you know of any existing location between original and generated sources when a breakpoint is hit?

I'm not totally clear on what you're asking here.
