### ISSUE TITLE
Clicking on a breakpoint in the Breakpoints sidebar panel should take me there

### ISSUE THREAD

**Issue by captainbrosset** [devtools-html/debugger.html#675]
STR:
- add a breakpoint somewhere,
- open another file or stay in the same file but scroll down so you don't see the breakpoint anymore,
- in the sidebar, inside the Breakpoints expandable section, click on the breakpoint entry (not the checkbox, the label next to it).

I would expect this action to take me back to the breakpoint position so I can easily find it again.

**Comment by jasonLaster** [comment]
Hmm, I believe the happy case works alright - clicking a breakpoint navigates to the correct source line, but there is an edge case here:

+ navigating within a source is broken. @jlongster do you think this could be related to the sourceeditor work you did lately with codemirror? My guess is that it would be a regression with alignline

![](http://g.recordit.co/Gz1I3m8yjU.gif)

**Comment by jlongster** [comment]
Possibly, I'm not sure. I didn't change `alignLine` at all, but that code has moved around so something is going on. I can take it and try to look soon.

**Comment by jlongster** [comment]
This should be fixed once #713 lands

**Comment by jlongster** [comment]
Fixed by #713
