### ISSUE TITLE
Active file in source pane is sometimes not selected

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6750]
STR:
 - Debug on https://debugger-example-typescript-react.glitch.me/ , src directory to `webpack/src`
 - Click `index.tsx`, click `App.tsx`, repeat

At some points, the file gets opened but the selection in source pane isn't set.

![screenflow](https://user-images.githubusercontent.com/8599/43668837-e7d05b6e-9733-11e8-88f0-6160a138f45e.gif)

**Comment by janodvarko** [comment]
I can't reproduce that anyone else can?
Honza

**Comment by darkwing** [comment]
I can't reproduce this either; let's close for now and reopen if someone else can reproduce.
