### ISSUE TITLE
Framework icons only load on file openings and cause visual jitter

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6753]
Adding jitter to #6725, which was about the tabs.

STR:
- Open Debugger on https://debugger-example-typescript-react.glitch.me/
- Open of the ts files in webpack

React icon loads after the file loaded, with layout jitter in the source pane.

![screenflow](https://user-images.githubusercontent.com/8599/43672796-5c61f15a-976a-11e8-8154-400fca69755e.gif)

**Comment by darkwing** [comment]
My understanding is that we don't know about placing the React icon until we analyze the source, which I don't believe we load until the tab is opened.

I suppose we could automagically assign that icon for `tsx` files (?)

**Comment by jasonLaster** [comment]
Yeah, i think we can do three things:

1. assign it based on tsx, jsx 
2. persist the information on load
3. do something special with original files [1]

[1] the client has the original source text in the map, which means that we do not need to load the source text from the server. At that point, the only slowdown is parsing the file to determine the framework. I think we can probably stop parsing the file and instead rely on a couple of regexes, which is what the editors do as well. 

When we have sourcemap support on the server, it will be easier to identify frameworks for generated files before "load" as well.

**Comment by nchevobbe** [comment]
Could we have a transparent item that takes the place of the possible
future icon ? This way it doesn't "jump" when the icon is displayed.

Le sam. 4 août 2018 à 18:02, Jason Laster <notifications@github.com> a
écrit :

**Comment by jasonLaster** [comment]
The jump is because a tab with an icon in ~15px wider. I think it would look off to have the 15px and no tab.

**Comment by jasonLaster** [comment]
This should be fixed now with tabs.
