### ISSUE TITLE
Cleanup questionable logs and errors

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#6769]
https://github.com/devtools-html/debugger.html/search?q=WTF&unscoped_q=WTF

Unless `WTF` has a very secret technical meaning, I don't think we want this to appear on users' terminals, browser console etc...

**Comment by jasonLaster** [comment]
feel free just to open small PRs

**Comment by juliandescottes** [comment]
I know but there is always a chance I won't fix it :) So I prefer to have an issue logged so that someone else can pick it up
