### ISSUE TITLE
Hyperactive debugger in background tab

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6774]
STR:
- Open https://connorholyday.github.io/angular-pig-latin/ and Debugger
- Put in background tab and just browse the web

Debugger causes 120-140ms hangs on main thread every. Fan spinning 🔥. 

https://perfht.ml/2vMg3HM (this profile has 2 other occurrences, zoom out to see more)

**Comment by jasonLaster** [comment]
yep, we'll have to clean up some of this perf. Good news is that some of this work is already underway

**Comment by digitarald** [comment]
@jasonLaster which tickets would be relevant that we should mention here?
