### ISSUE TITLE
Extra Slashes in Paths

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#6790]
I'm seeing extra slashes displaying in a few cases:

<img width="643" alt="slashes3" src="https://user-images.githubusercontent.com/46655/43928256-d7d38ee0-9bf5-11e8-94de-5b384991a366.png">

<img width="731" alt="slashes" src="https://user-images.githubusercontent.com/46655/43928264-e2195bf0-9bf5-11e8-9018-50608917abb7.png">

**Comment by darkwing** [comment]
This started happening when we switched to `new URL` instead of the using the `url` lib.  Webpack, oddly enough, uses three slashes to begin its URLs:

For example:

```webpack-internal:///../rbd/pnpm-volume/144384a5-85d9-4142-b9b9-168eea22eb97/node_modules/.registry.npmjs.org/fbjs/0.8.17/node_modules/fbjs/lib/isNode.js```

... returns a pathname of:

```///../rbd/pnpm-volume/144384a5-85d9-4142-b9b9-168eea22eb97/node_modules/.registry.npmjs.org/fbjs/0.8.17/node_modules/fbjs/lib/isNode.js```

Somehow the three "///" make their way into the path and aren't broken off from the protocol.  The regex `pathname.replace(/\/{2,}/g, "/")` would remove those leading slashes but the result of `new URL()` doesn't allow setting of pathname.

Since webpack uses a weird protocol format, I may file a bug just to get a bit of information from them.

**Comment by darkwing** [comment]
Got an answer here:  https://twitter.com/wSokra/status/1027995652360482820

Since this isn't something *we* can config, it isn't a bug on our side.  That being said, it would be nice to figure out a more elegant way of expressing this path.

**Comment by darkwing** [comment]
I think with this we should either remove the leading slashes *or* put the "/../" back.  We might need to feel this one out first.

**Comment by jacobjzhang** [comment]
This looks interesting-- is it up for grabs?

**Comment by darkwing** [comment]
Sure 👍

**Comment by darkwing** [comment]
Closing because it represents the actual URL.
