### ISSUE TITLE
Framework collapsing also collapses user-land component

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6792]
STR:
- Debug https://firefox-debugger-example-create-react-app.glitch.me/ with Pause on Exception
- Set an X and try to set an O on the same field to raise an error

ER: `handleClick` has its own frame in the callstack
AR: `handleClick` is part of a collapsed React callstack entry

<img width="921" alt="image" src="https://user-images.githubusercontent.com/8599/43933351-1b7b9bf8-9bfe-11e8-8a0f-db15f14dfeb7.png">

Is the collapsing logic too broad in this case, maybe thrown off my too many `react` words in the project?

**Comment by janodvarko** [comment]
I can nicely reproduce this issue using STR from the first comment.

Note that the URL path of the module where the `handleClick` method is implemented contains `react` keyword in it. I can also see the problem when implementing my own simple component locally within a `react` directory.

So, the logic responsible for grouping needs to be improved.

Honza

**Comment by danny6514** [comment]
The grouping infact needs to be improved, currently it is doing a pretty basic `/react/i` match. I was thinking what we could change this to...can we always assume the files will be under node_modules? (Libraries such as Express and Pug do) Or should be match based on filename? Like `/react[^\/]*\.js/i`?
