### ISSUE TITLE
vue.js detection misses alternative file names

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6793]
Tested with a vue-cli starter kit, outputs `vue.esm.js`. Other names are possible as well: https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds

STR:
- Debug https://firefox-debugger-example-vue-cli.glitch.me/
- Pause in `webpack:///HelloWorld.vue`

AR: The internal callstack is not collapsed.
ER: vue.js callstack is being collapsed.

<img width="658" alt="image" src="https://user-images.githubusercontent.com/8599/43940583-1a939b2e-9c25-11e8-8171-88bdb2f6d6df.png">

https://github.com/devtools-html/debugger.html/blob/master/src/utils/pause/frames/getLibraryFromUrl.js#L73 needs to be extended, maybe `/vue(\.[a-z.]+)\.js/i`

**Comment by jasonLaster** [comment]
We'll also want to update this -- https://github.com/devtools-html/debugger.html/blob/master/src/workers/parser/frameworks.js

**Comment by dczombera** [comment]
I just saw @darkwing's tweet referring to this issue. I'd love to help you out since I really appreciate all the work you are doing at mozilla and I also want to support the vue project wherever I can. 
I hope you don't mind if I start working on it tomorrow, even though I have never touched this project before. :anguished:

**Comment by darkwing** [comment]
Welcome to the team @dczombera !  Setup should be fairly simple and feel free to stop by our Slack (https://devtools-html-slack.herokuapp.com/) for help!  Thank you for the help @dczombera !

**Comment by digitarald** [comment]
> We'll also want to update this -- https://github.com/devtools-html/debugger.html/blob/master/src/workers/parser/frameworks.js

Correct, the file logo idn't set for the component generate by vue-cli (v3 in the case of this screenshot)

<img width="444" alt="image" src="https://user-images.githubusercontent.com/8599/43984710-13d94be8-9cb7-11e8-8d98-b3eaac4bc02e.png">
