### ISSUE TITLE
Tweak pause on exceptions

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#680]
It's not obvious when you toggle between the different pause on exception states.

We should so something, maybe a different color. 

Maybe a disabled state when we're not pausing on exceptions.

**Comment by SezginEge** [comment]
Is there anyone working on this? If not, I can tackle it 👍

**Comment by jasonLaster** [comment]
Hi @SezginEge, thanks. We would love the help. At this point, i'm not sure if we have a clear direction for how we want to handle it. 

I would love to get your ideas here as it is a challenging problem.

**Comment by SezginEge** [comment]
I think, we should use toggle button with different color variants. This is more visually descriptive single state button or contextual menu. 

I also added some images about how different modern browsers implemented this button. 

On firefox developer edition, you can toggle different states only with contextual menu and this is not visually descriptive.

![debugger-options](https://cloud.githubusercontent.com/assets/6282991/18767214/7e6bbb84-8126-11e6-92a5-428c5bbad8f2.png)

On the other hand, Chrome using toggle button with different color variants and Edge using toggle button with contextual menu.

These images from Chrome's early version: 
<img width="250" alt="vgnon" src="https://cloud.githubusercontent.com/assets/6282991/18766479/21051fd8-8123-11e6-8193-2d57da46d90c.png">

<img width="250" alt="3tsmz" src="https://cloud.githubusercontent.com/assets/6282991/18766485/288f7dca-8123-11e6-833a-27bfc9dfe23b.png">

<img width="250" alt="bgzoy" src="https://cloud.githubusercontent.com/assets/6282991/18766484/2680a6a8-8123-11e6-807c-6e1b93dc26fd.png">

Edge's toggle button:

![edge](https://cloud.githubusercontent.com/assets/6282991/18766960/5dcc15d2-8125-11e6-8758-90fc0f8557ff.gif)

**Comment by jasonLaster** [comment]
Thanks for the research @SezginEge, this is great!

I think Chrome's is what we're looking for:
* tooltip - (first mention current state, then mention the next state)
* colors - both chrome and edge have consistent colors (blue for caught) (purple uncaught)

our colors are here [variables.css](https://github.com/devtools-html/debugger.html/blob/master/public/js/lib/themes/variables.css).

Would you like to take a stab at implementing this?

**Comment by jasonLaster** [comment]
@SezginEge nearly forgot to point you in the right direction - here's the exception [function](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/RightSidebar.js#L143-L165). If you have any questions [getting started](https://github.com/devtools-html/debugger.html/blob/master/CONTRIBUTING.md), please stop by our IRC room. That's what we're here for.

**Comment by SezginEge** [comment]
Thanks @jasonLaster! You can assign this issue to me. I will send pr as soon as possible.

**Comment by wldcordeiro** [comment]
@SezginEge heh, I wish issue assignment to contributors was a thing but I think they'd need to create a user group and invite you to it. 😆

**Comment by SezginEge** [comment]
@wldcordeiro Yes, you are right. I forgot that. 😖

**Comment by jlongster** [comment]
Closed by #816
