### ISSUE TITLE
WebDriverError: Connection Refused.

### ISSUE THREAD

**Issue by DZuz14** [devtools-html/debugger.html#6802]
I just started messing around with debugger.html, and it keeps crashing on me. I can usually type: `yarn start` and get the webpack dev-server running on http://localhost:8000 and use the debugger to inspect a site for a few minutes.

However, it keeps crashing with this error message in my terminal.

<img width="857" alt="screen shot 2018-08-10 at 9 41 20 pm" src="https://user-images.githubusercontent.com/19492185/43986856-2aeb35d8-9ce6-11e8-9c0d-0a631489687f.png">

**My environment details:**

- MacOS High Sierra 10.13.5
- Node 9.6.1

I was attempting to research some of the bugs in the repository, but cannot really do so if the debugger does not run on my machine.

**Comment by darkwing** [comment]
@DZuz14 That's frustrating :( .  I saw that recently and everything worked again when I `rm-rf node_modules` and re-installed.

**Comment by erickstm87** [comment]
Hmm ok so I tried that and even tried to clean the yarn cache but I'm still running into this error.

**Comment by erickstm87** [comment]
![image](https://user-images.githubusercontent.com/7424828/46151416-f84d5500-c22b-11e8-82df-ad2d5e9075bf.png)

Also I'm on High Sierra 10.13.6

**Comment by jasonLaster** [comment]
what version of selenium webdriver do you have?

**Comment by erickstm87** [comment]
Stupid question. I can't find out a quick way to check on OSX cli. Do you have any good reference I could use to check that?

**Comment by erickstm87** [comment]
![image](https://user-images.githubusercontent.com/7424828/46157860-e2df2780-c239-11e8-9641-cf6ea7109cce.png)

**Comment by erickstm87** [comment]
![image](https://user-images.githubusercontent.com/7424828/46352508-33c69580-c617-11e8-9b4d-d7975d87d5cb.png)

**Comment by jasonLaster** [comment]
yep - i'm seeing some issues too...

**Comment by jasonLaster** [comment]
yep - i'm seeing some issues too...

I'm now doing this `/Applications/Firefox\ Nightly.app/Contents/MacOS/firefox --start-debugger-server 6080 -P dev2`

**Comment by erickstm87** [comment]
jasonlaster what's your selenium-webdriver version? I could try another one out too

**Comment by jasonLaster** [comment]
`3.3.0`

**Comment by kenjiO** [comment]
I tried selenium-webdriver version 3.6 and it didn't crash but I couldn't get the debugger to work.

If you try using the command Jason gave you also need to go to the `about:config`  url and set these.  
devtools.chrome.enabled  **true**
devtools.debugger.remote-enabled **true**
devtools.debugger.prompt-connection **false**

**Comment by erickstm87** [comment]
Alright so I've tried version 3.3.0, 3.6, and 4.0.0 of selenium-webdriver. All of those versions crashed. I switched out those three values in the `about:config` that kenjiO mentioned and that seems to have done it. I'll update again if that changes. Thanks kenjiO!

**Comment by jasonLaster** [comment]
Thanks @erickstm87 for testing.

**Comment by snehansh** [comment]
I have encountered this error. How to fix it, I was not able to follow this thread to find out how to resolve.
I have taken a new checkout and was expecting the selenium-driver and gecko driver to be installed with the correct versions when I do yarn install.
