### ISSUE TITLE
Consistent top bar height and baseline alignment

### ISSUE THREAD

**Issue by fvsch** [devtools-html/debugger.html#6803]
Two spacing issues with the debugger's top bars:
![debugger-top-bar-height](https://user-images.githubusercontent.com/243601/43991513-c8529df6-9d6e-11e8-985d-3dd72bd1a01e.png)

1. The top bar height *excluding borders* in the Debugger is 29px. Compare to the DevTools tab bar’s 28px. That’s not a huge difference, but it would be nice to be fully consistent.

2. The file tab labels are 2px too low, compared to the Sources|Outline tabs and other icons.

My recommended fix for the second issue (which is the most visible IMO) would be to ditch the tab style with a border on top, and go with a flatter style like for "Sources"|"Outline". It might also be possible to use the devtools-tab style (like the Inspector and Netmonitor do, at 24px-high), making the Debugger feel a bit less out of place.

Or the alignment can be achieved with the current design, by tweaking a few pixels.

**Comment by darkwing** [comment]
@fvsch Can I ask which app or method you used to get these heights?  Photoshop with line tool?

**Comment by fvsch** [comment]
@darkwing It’s a screenshot in macOS at 2x resolution. The pink line and squares are drawn with Sketch.
