### ISSUE TITLE
Rows are not visually aligned when switching from "Sources" to "Outline"

### ISSUE THREAD

**Issue by fvsch** [devtools-html/debugger.html#6804]
This is a visual consistency bug.

- The "Sources" content has 0px of vertical padding.
- The "Outline" content has 10px of vertical padding.

That bit of UI would feel more polished if content didn't jump up and down when switching between those two tabs. Maybe use a common vertical padding like 4px?

**Comment by darkwing** [comment]
Great attention to detail @fvsch !

**Comment by darkwing** [comment]
The fix likely needs to be made in:

- src/components/PrimaryPanes/Sources.css
src/components/PrimaryPanes/Outline.css
