### ISSUE TITLE
"Debugging Firefox Guide" link is broken in CONTRIBUTING.md

### ISSUE THREAD

**Issue by zlypher** [devtools-html/debugger.html#6807]
The link "guide" in the CONTRIBUTING.md file leads to a 404 page.

Link can be found here: https://github.com/devtools-html/debugger.html/blob/master/.github/CONTRIBUTING.md#debugging-firefox

Currently links to: /devtools-html/debugger.html/blob/master/.github/docs/debugging-firefox.md
Should probably link to: /devtools-html/debugger.html/blob/master/docs/debugging-firefox.md

**Comment by AnshulMalik** [comment]
Nice find. Thanks.

And feel free to stop by in slack (https://devtools-html-slack.herokuapp.com/)
