### ISSUE TITLE
claim bot contains 404 link (contributing.md)

### ISSUE THREAD

**Issue by danwulff** [devtools-html/debugger.html#6815]
**Problem:**
The automated claim bot has an invalid link to the **contributing** guidelines.

This invalid link can be witnessed here: https://github.com/devtools-html/debugger.html/issues/6804#issuecomment-412683878

**Possible solution:**
I believe the proper contributing URI is: https://github.com/devtools-html/debugger.html/blob/master/.github/CONTRIBUTING.md

Please update the claim bot to point to the correct contributing guide.

**Comment by jasonLaster** [comment]
This should be fixed now. Lets see
