### ISSUE TITLE
test seeing the pause warning

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#682]
I'm pulling this test out of #644 as it's fairly different.

The test navigates to the inspector and checks to see if the pause warning is there.

[browser_dbg_pause-warning.js](https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/test/mochitest/browser_dbg_pause-warning.js)

**Comment by clarkbw** [comment]
https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/test/mochitest/browser_dbg_pause-warning.js

**Comment by codehag** [comment]
We do not have a pause warning anymore, so I am closing this and adding it to the feature backlog
