### ISSUE TITLE
Provide [sm] Style Enhancement

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#6821]
We recently added support for sourcemap files with the same URL as the minified file.  At the moment, we only show "[sm]" next to the file name in the sources tree, but it would look better with a bit more styling, a la:

<img width="162" alt="43419230-3a1ca270-93f5-11e8-8399-0600f9b27134" src="https://user-images.githubusercontent.com/46655/44096955-34191be8-9fa2-11e8-8457-e834d593e05f.png">

You can use https://q7mmol9xy9.codesandbox.io/ as a test side, as there are two sourcemapped files in that tree.

**Comment by ekaoddlass** [comment]
/claim

Hi, I would like to try this! Is this still available?
