### ISSUE TITLE
Delay when opening debugger on reddit

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6828]
STR: Open Debugger on reddit homepage.

Interesting bits:
- 25% of a 2.5s hang spend in GC (mostly in `updateSource`): https://perfht.ml/2w7m5Ts
- 350ms for loading debugger resources: https://perfht.ml/2KY8OSI

Profile with a fresh Firefox install: https://perfht.ml/2Mk2ASI

**Comment by jasonLaster** [comment]
hmm, i couldn't load the profiles. You'll be happy to know though that `updateSource` will be gonzo soon
