### ISSUE TITLE
Broken interactions & rendering in Source Map

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6829]
STR:
- Open reddit.com and Debugger on a fresh profile
- Click through Webpack folder (all non-existent source files from reddit ads)

AR: Things go haywire at some point, with files duplicating and being unclickable.

![screenflow](https://user-images.githubusercontent.com/8599/44119982-b3004f3a-9fcf-11e8-8b60-9e93d0bf81ba.gif)

State after a plain refresh, `bootstrap` is already duped several times:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/8599/44120156-447096aa-9fd0-11e8-9f38-f0585c0d3d3c.png">

**Comment by darkwing** [comment]
I'm fairly certain this is the sourcemaps stuff that @jasonLaster has just completed

**Comment by darkwing** [comment]
Just tested and can confirm this is still an issue; the only difference is that the tree items all now show mapping:

![theydontloveyoulikeiloveyou](https://user-images.githubusercontent.com/46655/44127449-ee167620-a002-11e8-9d2d-5a4f4c278768.png)

**Comment by darkwing** [comment]
With @jasonLaster 's mapped work, I can no longer get the duplicate item crap happen in panel.  Yessss.  :D

**Comment by darkwing** [comment]
Grrr, scratch that, does still happen :/

**Comment by jasonLaster** [comment]
yeah - it still happens for me too. Even after the performance fix. Not sure what is going on there though
