### ISSUE TITLE
[Breakpoints] support Inline breakpoint

### ISSUE THREAD

**Issue by mantou132** [devtools-html/debugger.html#6837]
Similar: 
<img width="381" alt="screen shot 2018-08-16 at 01 55 20" src="https://user-images.githubusercontent.com/3841872/44164053-8b588280-a0f7-11e8-8d76-a8877950c459.png">

**Comment by jasonLaster** [comment]
Thanks for filing. I believe we have other feature requests filed for this. 

The good news is as of monday, we now have support for member expression breakpoints, which means we can add `e[n]./*bp*/call` breakpionts

**Comment by jasonLaster** [comment]
closing and moving to the icebox where we will evaluate during the next release planning
