### ISSUE TITLE
Double-clicking conditional breakpoint entries should trigger Editing

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6838]
STR:
- Right click a line to Add conditional breakpoint
- Type something
- Doube-click breakpoint entry in the breakpoints panel

AR: Text selection
ER: Edit mode for condition

**Comment by digitarald** [comment]
@darkwing am I missing something here or does that expectation sound reasonable?

**Comment by jasonLaster** [comment]
@digitarald where would they edit? In the pane?

**Comment by digitarald** [comment]
@jasonLaster in the sources pane, same flow that is triggered by `Edit breakpoint` in the breakpoint context menu.

**Comment by darkwing** [comment]
Seems like a reasonable idea; a few things to consider as it's shimming a :

1.  Open the source if it's not yet opened
2.  Scroll to the position once opened
3.  Show the edit UI
