### ISSUE TITLE
[reps] getLinkifiedElements doesn't properly linkify strings

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/debugger.html#6843]
This is clone of:  [Bug 1483891](https://bugzilla.mozilla.org/show_bug.cgi?id=1483891) - Response overview doesn't indicate location value is cut off

See this [comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1483891#c4) for detailed STR and a test case.

Honza

**Comment by nchevobbe** [comment]
@janodvarko should we only add a title attribute to the link, or is there a "true" bug here ?
I also found https://bugzilla.mozilla.org/show_bug.cgi?id=1204728 which is still visible with Reps. 

We can have a look at https://github.com/mozilla-b2g/gaia-email-libs-and-more/blob/convoy-status/js/clientapi/bodies/linkify.js#L51 to change our linkification algorithm.

**Comment by janodvarko** [comment]
I think this is real bug. The header should present *the original value* to the user and additionally -the linkifying algorithm can make it a clickable link.

Honza

**Comment by arshadkazmi42** [comment]
Taken this up via [Bugzilla - 1483891](https://bugzilla.mozilla.org/show_bug.cgi?id=1483891)
