### ISSUE TITLE
Breakpoints disappear right away if source file uses \r\n line breaks

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#686]
STRs:

- open the debugger on https://dl.dropboxusercontent.com/u/17803671/devtools/debugger-test/index.html
- set a breakpoint anywhere in the page

AR: Breakpoint briefly appears, but disappears right away.
ER: Breakpoint should remain visible

This issue comes from the fact that this source file uses `\r\n` line breaks. 
You can compare with https://dl.dropboxusercontent.com/u/17803671/devtools/debugger-test/index-proper-endings.html , which uses unix line breaks.

The breakpoint gets deleted in Editor::componentWillReceiveProps, when calling setSourceText -> setText.
In Editor.js::setText, normally we bail out if the text is the same as the current text of the editor: 

    if (text == this.editor.getText()) {
      return;
    }

By default codemirror normalizes line breaks to \n , so here `this.editor.getText()` will differ from `text`. 
Then code mirror proceeds to redraw itself and removes the current markup containing the breakpoint. 

Re fixing this, we could 
- normalise line endings on our side as well
- use the lineSeparator option from CodeMirror [1] : detect the file's line endings and set it in CodeMirror (but I guess we are sharing a single instance of code mirror for all sources? might be a bit tricky?) 

The comment on Editor::setText mentions that "comparing the source text is probably inefficient", so maybe you already have other alternatives in mind, that would also take care of this issue?

[1] https://codemirror.net/doc/manual.html#option_lineSeparator

**Comment by jlongster** [comment]
Thanks!! I think the ideal solution would be to avoid comparing the text. There should be a solution that doesn't require that, because it will be slow on large texts. We'll look into it.
