### ISSUE TITLE
When paused, adding a new breakpoint should not update the scroll

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#687]
Small UX nit :)

STRs:
- (needs a source big enough to have a scrollbar)
- pause on a breakpoint
- scroll somewhere else in the source
- click to add another breakpoint

AR: The scroll is updated to show the paused line, potentially hiding the line where I just added the breakpoint.
ER: Scroll should not be updated.

![debugger-scroll-reset-when-paused](https://cloud.githubusercontent.com/assets/1141550/18328563/94f7a666-754f-11e6-8ec8-46bc9124f2d6.gif)

**Comment by jlongster** [comment]
Definitely a good bug. The scrolling needs to be reworked. Thanks!
