### ISSUE TITLE
TypeError: response.frames is undefined create.js:73:4 

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#6876]
I received this error out of the blue but unfortunately have no STR.  The error corresponds to:

```js
export function createPause(
  packet: PausedPacket,
  response: FramesResponse
): any {
  // NOTE: useful when the debugger is already paused
  const frame = packet.frame || response.frames[0];

  return {
    ...packet,
    frame: createFrame(frame),
    frames: response.frames.map(createFrame)
  };
}
```

Filing an issue because we should do some sort of additional check for a response having a `frames` property.

**Comment by jasonLaster** [comment]
I see this when the rr_console-warp-01 test fails. Do you see it on other cases too?

**Comment by darkwing** [comment]
I was testing a PR and had some a bunch of refreshes during loading of things, so it's probably tough to reproduce.  First time I've ever seen it.

**Comment by jasonLaster** [comment]
just saw it too while doing a bunch of refreshes

**Comment by darkwing** [comment]
I haven't seen this in ages, closing.
