### ISSUE TITLE
Check panel contrast in dark theme after bug 1464348 lands

### ISSUE THREAD

**Issue by fvsch** [devtools-html/debugger.html#6899]
This issue can be assigned to me.

[Bug 1464348](https://bugzilla.mozilla.org/show_bug.cgi?id=1464348) (related to https://github.com/devtools-html/ux/issues/4) should increase the contrast of the `--theme-body-color`.

Since the reason for lowering it in the first place (sometimes below accessible levels) was too bright text in secondary panes in the Debugger ([bug 1421389](https://bugzilla.mozilla.org/show_bug.cgi?id=1421389)), we should check it and perhaps use a specific color for those:

https://github.com/devtools-html/debugger.html/blob/e7f212ee3916d97c799549b6b89cb43fbc1ce34f/src/components/SecondaryPanes/SecondaryPanes.css#L39-L41

For instance:

```css
.pane {
  color: var(--theme-body-color);
}

.theme-dark .pane {
  color: var(--grey-45);
}
```

Another possibility is to used muted contrast for both themes, using `--theme-comment` or `--theme-body-color-alt`.

**Comment by violasong** [comment]
Thanks for checking this and providing the screenshots! I generally work in bright rooms but I went into my most cave-like room to look at this :). I compared it with the [old version](https://pbs.twimg.com/media/DPLwSvDVQAA03Bi.jpg:large) of the dark theme (for which I had gotten feedback re: too much sidebar contrast) and I realized even with #b1b1b3, it's much less contrasted than the original glaring one, and it really looks nicely balanced. You were right about this :). Closing the bug.
