### ISSUE TITLE
[sources] investigate isOriginal

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6900]
It might be nice to describe sources in terms of whether they are original or generated instead of isOriginalId / isGeneratedId

Here is a patch that starts that migration:
https://github.com/jasonLaster/debugger.html/tree/source-original

**Comment by akshitac8** [comment]
@jasonLaster Is this Issue solved?

**Comment by jasonLaster** [comment]
Hi @akshitac8. @darkwing is working on it now

**Comment by akshitac8** [comment]
Ohkay @jasonLaster Thank you :)
