### ISSUE TITLE
Breakpoints pause in wrong locations for source mapped files

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6921]
STR:
- Open https://perf-html.io
- Add breakpoint in `webpack:///src/actions/receive-profile.js` , line 347, `await symbolicateProfile(profile, symbolStore, {`
- Drag a profile (like [this example](https://www.dropbox.com/s/1hdvbj019d8s6pm/profile-1535757906009.json?dl=0)) into the browser

ER: No breakpoint being hit, as the action doesn't fire for this interaction
AR: Debugger breaks in `webpack:///src/reducers/url-state.js`, line 47

Disabling the breakpoint does prevent the pausing, so it seems related.

![image](https://user-images.githubusercontent.com/8599/45006031-c1c54700-afab-11e8-8df8-554a6e424d71.png)

**Comment by digitarald** [comment]
Same happened again trying to break in icloud's notes app:

STR:
- Breakpoint on `Log` line in `Database.js` (use file search), line 106, function `performQuery`.
  <img width="684" alt="image" src="https://user-images.githubusercontent.com/8599/45778924-ab0b2b00-bc0e-11e8-9088-47ce1224a7aa.png">
- Refresh

ER: Pause in `Database.js`
AR: Pauses in `Log.js`'s `setDelegate` method

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/8599/45778840-80b96d80-bc0e-11e8-9c86-ef16afdafdf1.png">

**Comment by digitarald** [comment]
Another perf-html story:

STR
- Adding breakpoint in `Root.js`, `render` function
- Reload

First breaks in `index.js`, showing `Pausing on breakpoints`:

<img width="864" alt="image" src="https://user-images.githubusercontent.com/8599/47681255-366cca00-db86-11e8-8b50-6d85a7563971.png">

First Resume hits another `create-store.js`, again `Pausing on breakpoints`

<img width="872" alt="image" src="https://user-images.githubusercontent.com/8599/47681280-48e70380-db86-11e8-8dfd-a364c22354a1.png">

Second Resume hits the wrong line in `Root.js` (243 vs actual 167):

<img width="810" alt="image" src="https://user-images.githubusercontent.com/8599/47681877-e7279900-db87-11e8-9468-5be589f35326.png">

… continued clicking leads to other files and never to the breakpoint I set.

**Comment by digitarald** [comment]
@jasonLaster @loganfsmyth if we agree that this is a P1, what are the next step to identify the root cause?

**Comment by jasonLaster** [comment]
This looks fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1503436

![](http://g.recordit.co/Si7WlvaCcy.gif)

**Comment by darkwing** [comment]
@jasonLaster I believe it got backed out.

**Comment by gregtatum** [comment]
Looks landed, I will report back if this happens to me again.

**Comment by jasonLaster** [comment]
great!
