### ISSUE TITLE
[SourceMaps] Wrong warning location

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/debugger.html#6923]
STR:

0) The test case is here: https://github.com/janodvarko/tests/tree/master/warning-location
1) `git clone https://github.com/janodvarko/tests.git`
2) `cd warning-location`
3) 'yarn install'
4) 'yarn start'
5) Open the Console panel and load `http://localhost:3000/`
6) See the following warning in the Console panel:
Warning: Invalid DOM property `class`. Did you mean `className`? 
7) Check out the location: `bundle.js:37461:16` it should dynamically change to : `index.js:2178`, but it doesn't -> BUG

Go to `Graph.js` file remove the entire `componentDidMount` method. Now it works.

This might be Console bug as well but also looks like Source map problem.

Honza

![image](https://user-images.githubusercontent.com/37785/45029406-cf7cda00-b048-11e8-8322-8311982e3bb9.png)

**Comment by janodvarko** [comment]
@nchevobbe Do you think it's Console bug?

Honza

**Comment by nchevobbe** [comment]
it may be a Frame component bug (or what's used underneath to get the original source).
I'll check that

**Comment by nchevobbe** [comment]
So from my manual testing, I get the original location directly when opening the console after a `yarn start`. But if I reload the page, it indicates bundle.js.

Adding some logs into Frame.js _locationChanged function: 

First page load: 
```js
{
  "isSourceMapped": true,
  "url": "http://localhost:3000/Users/nchevobbe/Projects/tests/warning-location/node_modules/react-error-overlay/lib/index.js",
  "line": 2178,
  "column": 0
}
```
But then on reloads, the function is not called.
The issue might be in the sourcemap service we subscribe to [here](https://searchfox.org/mozilla-central/rev/c3fef66a5b211ea8038c1c132706d02db408093a/devtools/client/shared/components/Frame.js#65-66)

**Comment by loganfsmyth** [comment]
I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1500632 with patch.

**Comment by loganfsmyth** [comment]
This has landed on central.
