### ISSUE TITLE
docs/mochitests and docs/most-common-issues reference invalid yarn commands

### ISSUE THREAD

**Issue by WenInCode** [devtools-html/debugger.html#6928]
[Mochitests doc](https://github.com/devtools-html/debugger.html/blob/master/docs/mochitests.md) and [Most Common Issues doc](https://github.com/devtools-html/debugger.html/blob/master/docs/most-common-issues.md) reference the `yarn` commands `yarn copy-assets` and `yarn copy-assets-watch`. Both of these commands give you the command not found error. I _think_ these should be updated to `yarn copy` and `yarn watch`.

**Comment by jasonLaster** [comment]
Agreed!
