### ISSUE TITLE
Inconsistent yarn versions

### ISSUE THREAD

**Issue by WenInCode** [devtools-html/debugger.html#6930]
I don't notice if this is an actual issue or not, but I have been noticing running `yarn` on my fork always seems to update the `yarn.lock`. I think it _may_ have to do with what version of `yarn` I am running locally. In [docs/most-common-issues](https://github.com/devtools-html/debugger.html/blob/0dee2dbc082ce78ff24de3a8c78f6a7a5dcb54de/docs/most-common-issues.md) it says:

> The latest version of Yarn is 1x, but we recommend using 0.28.4. You can ironically re-install yarn with npm globally: npm i -g yarn@0.28.4. and check the version with which yarn and yarn --version.

However, I noticed that we specify version `1.6.0` in the [.circleci/config.yml](https://github.com/devtools-html/debugger.html/blob/0dee2dbc082ce78ff24de3a8c78f6a7a5dcb54de/.circleci/config.yml#L12).

Is the most-common-issues yarn version warning outdated?

**Comment by WenInCode** [comment]
I seem to still get changes in my `yarn.lock`, which may be a symptom of version specification or maybe uncommitted changes previously? The _potential_ issues still stands :)

**Comment by darkwing** [comment]
That's possible; another possibility is that when we merge a PR from greenkeeper to update a dependency, it does *not* update `yarn.lock` as well, and so a subsequent `yarn install` could change the local `yarn.lock` file.
