### ISSUE TITLE
Reps: add a rep for Accessible actor.

### ISSUE THREAD

**Issue by yzen** [devtools-html/debugger.html#6932]
Accessibility panel sidebar will soon need to be able to accessible actors[fronts] for accessible object's relations. The rep for the Accessible actor is very similar (and simpler) to Element node.

**Comment by nchevobbe** [comment]
@yzen how do I do to get an Accessible actor logged in the console ? is it something that will be accessible in the content page or just in chrome ?

**Comment by yzen** [comment]
At this point it will only be used with accessibility inspector. In browser console you can query XPCOM accessible objects directly. None of it, AFAIK, is available in non privileged content.
