### ISSUE TITLE
[Editor] Removing breakpoint from pretified file doesn't remove it from the original

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/debugger.html#6938]
STR:

1) Load https://impossible-education.glitch.me/
2) Go to the debugger UI and open `impossible-education/client.js` file
3) Click the `Pretty print source` at the bottom of the toolbox UI (looks like `{}`)
3) You should be auto navigated to the new file (i.e. no spaces at the top)
4) Create breakpoints on lines  2, 5, 8
5) Go to the original, breakpoints are on wrong lines
6) Go to pretty printed file and remove all breakpoints
7) Go back to the original, breakpoints are still there -> BUG
(btw. they  can't be removed in the original file atm)

Looks to me like source-maps problem.

But could be: breakpoints, source-maps or pretty-print.

Honza

**Comment by janodvarko** [comment]
Reported here:
https://github.com/devtools-html/debugger.html/issues/6938

Honza

**Comment by janodvarko** [comment]
From Slack:

jlast @honza looks like we have an editor bug because the locations in the bp panel change (edited)

![6i0qmr39xo](https://user-images.githubusercontent.com/37785/45165239-abf69280-b1f4-11e8-8d3c-9b14e4d5f8fe.gif)

Honza

**Comment by AnshulMalik** [comment]
So, it's the [memorize](https://github.com/devtools-html/debugger.html/blob/master/src/selectors/visibleBreakpoints.js#L21-L47) function which is causing this behavior, it memorizes the location and doesn't update it when the source changes.

**Comment by jasonLaster** [comment]
yes! want to pair on this?
