### ISSUE TITLE
Duplicated webpack files for vue

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6952]
STR:
- Debugger on https://belen-albeza.github.io/webcomponents-examples/wc-vue.html, open webpack folder

AR:
1. Too many files 😱
2. Only one is _mapped_ (surprising, as they are in _Webpack_ where I expect all files to be mapped)

<img width="161" alt="image" src="https://user-images.githubusercontent.com/8599/45231771-0a1d8700-b282-11e8-90fc-e7ff97781063.png">

Chrome does it better:

![image](https://user-images.githubusercontent.com/8599/45231775-10abfe80-b282-11e8-8ad1-33ced0a9c53f.png)

P1 as vue is popular.

**Comment by darkwing** [comment]
Weird that all of their contents are also different.  Here's a more accurate accounting of Chrome:

<img width="303" alt="chromeversionn" src="https://user-images.githubusercontent.com/46655/45232039-b5830780-b293-11e8-9d39-8e496a4989ae.png">

The main problem, I guess, is that we aren't showing the querystring so they all look alike.

**Comment by darkwing** [comment]
One idea could be to only show the query string if there's another source with the same URL (minus the query string).  Maybe even on the same level?

**Comment by jasonLaster** [comment]
That makes sense.

**Comment by jasonLaster** [comment]
Wow. Looks pretty good. 

@digitarald. Mind double checking
