### ISSUE TITLE
File expand / collapse broken in ProjectSearch view

### ISSUE THREAD

**Issue by samuelfullerthomas** [devtools-html/debugger.html#6953]
Hey All:

Collapsing and expanding of files seems to be broken in search. I've got a PR to fix it though! Just thought I'd file an issue to follow procedure?

Steps to reproduce:
1. In the `ProjectSearch` view, search for a term that is in at least one file
2. In the results view of `ProjectSearch`, try to expand or collapse a files results

Gif:
![broken-collapsing](https://user-images.githubusercontent.com/10165959/45256638-4ee41380-b391-11e8-99c3-5fc1ccb96a6f.gif)

**Comment by janodvarko** [comment]
I can confirm that this has been fixed.
Thanks for the patch!
Honza
