### ISSUE TITLE
[wasm] Breakpoint gutter is broken for .wasm files

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/debugger.html#6958]
1) Load http://janodvarko.cz/test/wasm/basic1/
2) Press Load Module & Execute Exported Function button
3) Go to the debugger and select test.wasm file
4) Create a breakpoint at e.g. line ` get_local $var0`
5) The gutter line offset gets cropped -> BUG

See the screenshot:
![image](https://user-images.githubusercontent.com/37785/45361667-20557b00-b5d3-11e8-9a4d-b6e6ca99a6b3.png)

**Comment by bomsy** [comment]
This seem to have regressed..

**Comment by darkwing** [comment]
This has always been a bit off, unfortunately.  Hopefully not too difficult to fix though!

**Comment by bomsy** [comment]
Fixed! via https://github.com/devtools-html/debugger.html/commit/6b651a1305768314ebed70ba2785ac17f3da02ee
