### ISSUE TITLE
[shortcuts] pause on f8

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#6963]
the debugger documents that F8 should trigger "break on next statement", yet the client doesn't actually have that command. 

https://github.com/devtools-html/debugger.html/blob/master/src/components/SecondaryPanes/CommandBar.js#L30-L31

https://github.com/devtools-html/debugger.html/blob/master/src/components/SecondaryPanes/CommandBar.js#L34-L51

**Comment by kenjiO** [comment]
@jasonLaster  F8 is already bound to the resume command.  Is the desired behavior to also have it bound to the breakOnNext command?  So when you press F8 it executes either resume or breakOnNext based on if it is paused or running at the time?

**Comment by jasonLaster** [comment]
Yes. I think so
