### ISSUE TITLE
Debugger can't set breakpoint.

### ISSUE THREAD

**Issue by johnfound** [devtools-html/debugger.html#6965]
Firefox 62.0 (64-bit) on Manjaro Linux.

When trying to set breakpoint in the debugger, it appears for a moment in the breakpoints pane and blue marker appears on the line number of the code, then both instantly disappears. This behavior is consistent for all type of JS code - enclosed in <script> tags of loaded from separate .js file.

**Comment by janodvarko** [comment]
@johnfound: I can't reproduce this issue. It seems to be working for me just fine.

My STR:
1) Load http://janodvarko.cz/firebug/tests/601/Issue601.htm
2) Open Issue601.htm in the Debugger
3) Create a breakpoint on line 35 - the breakpoint is there (in the gutter as well as the right panel)

Does this work for you?
Can you provide a test case that shows the problem?

Honza

**Comment by mrwweb** [comment]
I'm experiencing this issue exactly as described. Windows 10, Firefox 64.0.2. I've disabled all of my add-ons and still have the issue. I followed @janodvarko's test and experienced the issue. Here's a GIF:

![firefox-breakpoint-bug](https://user-images.githubusercontent.com/1238696/51635174-09bd1a00-1f0b-11e9-829e-507de8111874.gif)

**Comment by jasonLaster** [comment]
@mrwweb could you try Firefox 65 or 66 (dev edition or nightly)?

**Comment by mrwweb** [comment]
@jasonLaster It would appear to be working correctly in 65.0beta :)

**Comment by jasonLaster** [comment]
@mrwweb oh good. yeah i think @loganfsmyth fixed this with some of the breakpoint work. it is hard to handle all of the cases :/

**Comment by th7nder** [comment]
I have the same issue. I cannot set a breakpoint. Tried on Chrome, Firefox 65.0.1 and Firefox Developer Edition 66.0b7 on a MacOS 10.14.3.

**Comment by jasonLaster** [comment]
@th7nder can you provide more context on where you're trying to add a breakpoint?

**Comment by th7nder** [comment]
Sure, I am so sorry. Completely forgot about giving you an additional context. 
It happened inside Backbone.js Todo MVC on line 52. Inside function in object which is extended in IIFE.
![image](https://user-images.githubusercontent.com/8305170/52727268-2356fc00-2fb5-11e9-98a3-d12b39806fbd.png)

**Comment by santicalcagno** [comment]
I seem to be hitting the same bug. Firefox 65.0.1 and 67.0.1a (Nightly) in Arch Linux.

Redux DevTools shows two ADD_BREAKPOINT actions every time a new breakpoint is tried to be created. The second one "clears" the first.

![image](https://user-images.githubusercontent.com/6727466/53533085-351dc080-3ad8-11e9-8141-a47ac5ecf5b3.png)
