### ISSUE TITLE
[design] Tweak Right sidebar vertical rhythm

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#700]
Each section has it's own line height typography choices. It would be nice if we had a more developed system for how this is handled. 

* I happen to think that our call stack has a lot of whitespace, but I could be persuaded if we were consistent.
* We might want to have list item borders to make the lists easier to scan. I'm not sure

![screen shot 2016-09-08 at 8 18 14 pm](https://cloud.githubusercontent.com/assets/254562/18371295/20023da0-7601-11e6-908b-9a7460a986f2.png)

**Comment by SezginEge** [comment]
I have few opinions about that.

- Call stack looks huge and it takes up too much space. We may use same line-height and font-size as breakpoint items.
- List item borders could be great for differentiating items. 👍 
- We can add hover effect for each section

If nobody on working on this, I can tackle it.

**Comment by wldcordeiro** [comment]
> Call stack looks huge and it takes up too much space. We may use same line-height and font-size as breakpoint items.

Indeed, the padding there should be the same as the others.

> List item borders could be great for differentiating items.

I'd prefer zebra-striping for differentiating items.

> We can add hover effect for each section

Maybe? With the zebra striping it might not be needed? I'd have to see.

**Comment by wldcordeiro** [comment]
I guess zebra striping is already present but very faint.

**Comment by wldcordeiro** [comment]
Made the following changes and I think it's a huge improvement.

Changed this line https://github.com/devtools-html/debugger.html/blob/master/public/js/components/Frames.css#L10

```css
padding: 0.25em
````

and this line https://github.com/devtools-html/debugger.html/blob/master/public/js/components/Frames.css#L16

```css
background-color: var(--theme-search-overlays-semitransparent);
```

The results are much nicer already.

![screenshot_20160926_154939](https://cloud.githubusercontent.com/assets/580982/18853197/2d8ff6c0-8401-11e6-8c71-0d5ddbe53453.png)

**Comment by wldcordeiro** [comment]
@SezginEge sorry about kind of stealing it from under you, I wanted to see how things would look and it was such a small change. I have a branch with the two changes applied I can open a PR from.

**Comment by SezginEge** [comment]
Np. Good work @wldcordeiro 👍

**Comment by jasonLaster** [comment]
Handled in #876
