### ISSUE TITLE
File tabs disappear when readjusting window size

### ISSUE THREAD

**Issue by Doomwyte** [devtools-html/debugger.html#7016]
Repro steps:
1. Have multiple files open (I have 5 files open originally)
2. Adjust the window size of the center panel
Observe that `apstag.js` and `showad.js` disappear from view when the window is too small. They are not present in the drop-down either.

![sep-23-2018 10-57-57](https://user-images.githubusercontent.com/16697942/45929460-224b0280-bf20-11e8-871d-cfd5de19b9c0.gif)

**Comment by jacobjzhang** [comment]
@Doomwyte have you been able to resolve this issue?

**Comment by Doomwyte** [comment]
@jacobjzhang Nope not yet :P

**Comment by Doomwyte** [comment]
Still working on this issue, but one thing I notice is that resizing the size of the browser window doesn't have this issue. This issue only happens when I resize the center panel window. 

Also, if I have an active tab that gets thrown into the dropdown, when resizing the browser window another tab gets chosen as the active tab. When resizing the center panel window, there is no new tab chosen as the active tab.

**Comment by Doomwyte** [comment]
I think the issue is that `updateHiddenTabs()` in `Tabs.js` doesn't get called when the centre panel is resized. I notice it gets called when the browser window is resized with the following code below in `Tabs.js`, which allows the hidden tabs to be adjusted correctly.

```    
this.onResize = debounce(() => {
    this.updateHiddenTabs();
});
```
