### ISSUE TITLE
[sources] only show mapped when there is a conflict

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#7026]
STR:

1. go to https://firefox-dev.tools/debugger-examples/examples/increment/
2. view sources tree

We should only show mapped if there is both an original and generated source with the same name for example: https://w6q8w3lz47.codesandbox.io/

<img width="631" alt="image" src="https://user-images.githubusercontent.com/254562/46017990-ad95d680-c08d-11e8-9690-d1851bd9cd8f.png">

**Comment by darkwing** [comment]
@ZhangYue-vhyt This would be perfect for you!

**Comment by darkwing** [comment]
I love this idea.  I think we should implement a similar functionality for when there are two sources for the exact same file but separated by query string:

```
main.js?v=1
main.js?v=2
...
```
