### ISSUE TITLE
Resizeable column widths in the network tab

### ISSUE THREAD

**Issue by jaredkerim** [devtools-html/debugger.html#7029]
Firefox version: 63.0b8 (64-bit)
OS: OSX High Sierra 10.13.5 (17F77)

I can't click and drag to resize the columns in the network tab, which is annoying because I can't see the truncated content in each tab, like full paths.

![screenshot 2018-09-25 12 12 13](https://user-images.githubusercontent.com/119884/46027611-46dbe180-c0bc-11e8-893e-28c126e0032c.png)

**Comment by jasonLaster** [comment]
Thanks for the feedback. this issue tracker is just for the debugger

please file the bug here http://bugzilla.mozilla.org/

CC @janodvarko

**Comment by janodvarko** [comment]
@jaredkerim Hi, bug for resizeable columns in the Network panel is reported here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1463423

Honza
