### ISSUE TITLE
Change tab interface to have blue borders

### ISSUE THREAD

**Issue by Doomwyte** [devtools-html/debugger.html#7034]
The tab styling between the Debugger tool and the Inspector and Network tools are different. Perhaps change the tab interface for the Debugger tool to be consistent with the blue border style that the  Inspector and Network tools have?

This is suggested from a discussion from #7006 
 
--------------------------------------------------------------------------------------------------------
Debugger:
![1](https://user-images.githubusercontent.com/16697942/46046960-ee1a4200-c0d7-11e8-99df-b3fbbe741171.png)

--------------------------------------------------------------------------------------------------------
Inspector:
![2](https://user-images.githubusercontent.com/16697942/46046964-f1adc900-c0d7-11e8-86fe-0aed2bf4f793.png)

--------------------------------------------------------------------------------------------------------
Network:
![3](https://user-images.githubusercontent.com/16697942/46046967-f3778c80-c0d7-11e8-9785-c2b4b5a56105.png)

**Comment by jasonLaster** [comment]
copying @violasong's comment

Thanks all for looking at this - I love the idea of changing both the file tabs and the sources/outline tabs to the Inspector-style simpler blue border tabs.

Debugger's file tabs are more similar to the Firefox main tabs in having highly variable, often truncated lengthy text, so it is possible we'll need to do a slight modification on these to give it enough separation. I'd love to see how just Inspector-style will look in Nightly, and can propose more UI ideas if needed.
