### ISSUE TITLE
Codemirror can get blank space below

### ISSUE THREAD

**Issue by joewalker** [devtools-html/debugger.html#705]
Something is below my codemirror instance...

<img width="241" alt="screen shot 2016-09-09 at 20 42 36" src="https://cloud.githubusercontent.com/assets/76258/18400508/26fb61cc-76ce-11e6-9ac6-5fd8c5869b82.png">

It looks like the codemirror instance is having `height:300px` set by codemirror.css. Not sure why.

**Comment by jlongster** [comment]
Any steps to reproduce? I can't repro.

**Comment by joewalker** [comment]
I was switching between tabs when it happened. I can't get it to _not_ happen now. Tried restating the browser even.

**Comment by jlongster** [comment]
I can repro this now. Not sure why I didn't see it before, but we'll fix this immediately.

**Comment by jlongster** [comment]
This will be fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1302833

**Comment by jlongster** [comment]
That bug has been pushed and will land on m-c today.
