### ISSUE TITLE
Upgrade greenkeeper

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#7085]
Greenkeeper's job is to update our dependencies so that we are always prompted when something changes. At the moment, we have a forked version which attempts to make a new commit with the yarn.lock, but it fails at the moment.

We should try to:
a) get back on current [greenkeeper](https://greenkeeper.io/) which is better or 
b) switch to [renovate](https://renovatebot.com/)

---
👍  If you'd like to help and are not an admin, ping me and i can promote you temporarily :)

**Comment by AnshulMalik** [comment]
We need to set these environment variables in circles 
- GK_LOCK_COMMIT_NAME
   
- GK_LOCK_COMMIT_EMAIL

**Comment by darkwing** [comment]
I've added these environment vars; let's hope things work properly.

**Comment by AnshulMalik** [comment]
We have renovate now :)
