### ISSUE TITLE
[enhancement][network][XHR] Ability to set cause as xhr when edit & resend

### ISSUE THREAD

**Issue by asule90** [devtools-html/debugger.html#7103]
Using Firefox 62.0.3 (64-bit) windows.

im requesting some enhancement on firefox devtool network tab.
![image](https://user-images.githubusercontent.com/10544636/46846522-25902a80-ce0a-11e8-8fb6-7261ac8c944a.png)

when i filtered network request to XHR, then i choose to "edit & resend" to one of them.
the new request edit was not showing in XHR cause, but 'unknown' . so i need to clear the filter to show all .
![image](https://user-images.githubusercontent.com/10544636/46846595-66883f00-ce0a-11e8-845a-15906e4b305c.png)

so, can you guys add this enhancement on the next release?
this would be great.

thank you.

**Comment by jasonLaster** [comment]
@asule90 could you file the enhancements bug in the network panel component https://bugzilla.mozilla.org/?
