### ISSUE TITLE
[enhancement][network] Ability to collapse all response json

### ISSUE THREAD

**Issue by asule90** [devtools-html/debugger.html#7104]
Using Firefox 62.0.3 (64-bit) windows.

im requesting some enhancement on firefox devtool network tab.
can you add an ability to "collapse all" on response json object. as im getting json object response that long enough to fold manually.

![image](https://user-images.githubusercontent.com/10544636/46847023-7e60c280-ce0c-11e8-9817-14f51faa6d74.png)

thank you :)

**Comment by jasonLaster** [comment]
@asule90 could you file the enhancements bug in the network panel component https://bugzilla.mozilla.org/?
