### ISSUE TITLE
Add DAMP tests for hitting a breakpoint during loading

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#7135]
#7134 might be a regression that hints that we have not instrumented this well to hold the line on our performance wins. Loading and hitting breakpoints is a key interaction and the tools should not get in the way or even beachball on high-end user machines.

Could we add pausing on breakpoint in a complex code base to DAMP?

**Comment by jasonLaster** [comment]
moving this to bugzilla
https://bugzilla.mozilla.org/show_bug.cgi?id=1518291
