### ISSUE TITLE
Fix/investigate Step in/Step out key shortcuts on Linux

### ISSUE THREAD

**Issue by jbhoosreddy** [devtools-html/debugger.html#715]
As seen on CI, the step In/step out key shortcut, specifically F11 key does not trigger properly on Linux. (#642) The old debugger used a different mechanism from the key shortcuts library in the new debugger. But in both cases, the F11 key doesn't seem to do much. Which is weird. I suspect that key might be reserved by the system?

In any case, I will investigate it.

**Comment by jbhoosreddy** [comment]
Resolved in #718.

**Comment by joewalker** [comment]
Do you think this fix has reached m-c yet? I just had a report that F11 was broken.
