### ISSUE TITLE
[XHR Breakpoints] Accordian panel expands at incorrect times

### ISSUE THREAD

**Issue by kenjiO** [devtools-html/debugger.html#7155]
STR
In the secondary panel collapse the accordian item for XHR breakpoints.  Then add a breakpoint or add a watch expression.

ER
The XHR accordian item stays collapsed

AR
The XHR accordian item expands
 
 

![](http://g.recordit.co/o4FCwF2cqu.gif)

**Comment by loganfsmyth** [comment]
Doesn't sound like a duplicate exactly, but at least related to #7145.
