### ISSUE TITLE
Extend Source Querystring Logic to Tabs and Sidebar

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#7159]
In https://github.com/devtools-html/debugger.html/pull/7087 @ZhangYue-vhyt implemented functionality to show the querystring of a source if there is a sibling source with the same filename within the SourcesTree component.  For example:

- script.js?v=1
- script.js?v=2

That functionality is great for the SourcesTree component but tabs and the right sidebar (breakpoints pane, for example) could use this same logic.  We would ideally have a single function which would check for the presence of sibling sources (and possibly `isOriginal` status) and return a label with querystring included.

**Comment by WenInCode** [comment]
@darkwing any chance this is available

**Comment by jasonLaster** [comment]
@WenInCode go for it
