### ISSUE TITLE
Editor - add code search

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#716]
The sourceditor has code search functionality that we should be able to use when in the panel. This ticket should be about making this work. We can add code search locally and maybe re-think some of the UI at a later point

**Comment by gasolin** [comment]
I think it just due to the broken code of migration sourceeditor from iframe to embedded element. Once it is fixed (probably handled in bug 1292592), debugger will get the `find/findNext/findPrev` function for free

**Comment by jasonLaster** [comment]
Thanks @gasolin. We wrote a small sourceeditor [shim](https://github.com/devtools-html/debugger.html/blob/master/public/js/utils/source-editor.js) to act as a substitute while the sourceditor is depriveledged. In the panel, the debugger uses the real sourceditor.
