### ISSUE TITLE
code window is only 21 lines high

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#719]
When showing a specific script the window is only 21 lines high.
See the screenshot
![capture d ecran 2016-09-14 a 06 33 03](https://cloud.githubusercontent.com/assets/505230/18492274/58758118-7a45-11e6-96a1-8dcca5b74996.png)

**Comment by jasonLaster** [comment]
Thanks. We're working on fixing that

**Comment by jlongster** [comment]
Yeah, a fix should be out by Thursday, thanks!

**Comment by clarkbw** [comment]
I believe this is the same issue as #705

**Comment by jlongster** [comment]
It is, good call. Duping.
