### ISSUE TITLE
[sourcemap] save file and map

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#7190]
One of the challenging aspects of debugging sourcemaps today is that it can 

a) be hard to downlaod the generated file and sourcemap.
b) be hard to visualize the map because source map visualizer has a cap on the size of the visualization

we can address part a by having an editor context menu item for, which saves the generated file and source map to a file

Here is a gist for creating a generic *save file prompt*

```js
   var saveData = (function () {
    var a = document.createElement("a");
    document.body.appendChild(a);
    a.style = "display: none";
    return function (data, fileName) {
        var json = JSON.stringify(data),
            blob = new Blob([json], {type: "text/json"}),
            url = window.URL.createObjectURL(blob);
        a.href = url;
          a.download = fileName;
          a.click();
          window.URL.revokeObjectURL(url);
      };
  }());

  var data = { x: 42, s: "hello, world", d: new Date() },
      fileName = "my-download.json";

  saveData(data, fileName);
```

**Comment by jainsneha23** [comment]
@jasonLaster  I am able to download the generated file. But on the sourcemap part, what is the exact requirement? to save the source-map file as it is? If yes, the devtools-source-map doesn't export the source map text as is. So, I will  need to create a PR there , to first export sourcemap text, and then use it here.
