### ISSUE TITLE
[XHR Breakpoints] "Pause on any URL" Not Persisting Upon Refresh in Panel

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#7192]
When we check the "Pause on any URL" checkbox in the XHR breakpoint panel, the checkbox unchecks itself upon a refresh or navigation.  We need this setting to persist just as Pause on Exceptions does.

**Comment by AnshulMalik** [comment]
It works fine(persists) for me.

**Comment by loganfsmyth** [comment]
@AnshulMalik Could we revisit this? Even the URL list doesn't seem to persist for me properly when I refresh the page.

**Comment by jainsneha23** [comment]
@loganfsmyth You are right. Both url list and "Pause on any URL" checkbox resets on refresh.

/claim
