### ISSUE TITLE
remove sanitizeInputs in /src/utils/expressions.js (it's not sanitizing anything)

### ISSUE THREAD

**Issue by mozfreddyb** [devtools-html/debugger.html#7201]
as a follow-up from my conversation with @codehag.
1) look at https://github.com/devtools-html/debugger.html/blob/e7f212ee3916d97c799549b6b89cb43fbc1ce34f/src/utils/expressions.js#L11
2) it doesn't sanitize anything :open_mouth:  :boom:

**Comment by ganes1410** [comment]
Hey @edwardwall. Are you currently working on this ?

**Comment by jasonLaster** [comment]
@ganes1410 feel free to run with it

**Comment by ganes1410** [comment]
@jasonLaster I have a doubt.Should i remove the function `sanitize input` from the codebase or should i different regex for sanitzing the input ?

**Comment by mozfreddyb** [comment]
When I discussed this with @codehag, she suggested the function just to be removed. But that's likely not my call :-)

The line was last touched by https://github.com/devtools-html/debugger.html/pull/4790

**Comment by jasonLaster** [comment]
We've got some unit tests that check for the correct behavior, so it should be safe to remove and validate that the tests still pass.

**Comment by arshadkazmi42** [comment]
I can work on this if it's still available.
/claim

I just have one question, what type of sanitization needed for this?

**Comment by ganes1410** [comment]
@jasonLaster  Some of the tests are failing after running `test` script for the first time.I haven't started making any changes yet.

![screenshot from 2018-12-22 20-10-11](https://user-images.githubusercontent.com/16988745/50375609-232a2800-0626-11e9-99ed-32a720453b7b.png)

**Comment by jasonLaster** [comment]
Strange @ganes1410 maybe try again on master? it seems like things are in a good spot

**Comment by ganes1410** [comment]
@jasonLaster open a PR #7767
