### ISSUE TITLE
Can't find files with query strings

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#7217]
1. Load a page containing
    ```html
    <script src="test.js?foo"></script>
    <script src="test.js?bar"></script>
    ```
2. Open the debugger
3. Use Ctrl+P to find sources
4. Enter `test.js?foo`

Expected: you get a result
Actual: no result

![bug1](https://user-images.githubusercontent.com/7477678/47826104-e5bbc380-dd75-11e8-80ca-7ace7e2e702e.png)

You need to write `test.js` in order to find the results, but then you get two identical entries and you don't know which is which.

![bug2](https://user-images.githubusercontent.com/7477678/47826107-ebb1a480-dd75-11e8-90e3-abb01881e6cc.png)

All of this used to work properly and was regressed in https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=da7e0c710c7d7a7ff3e124db32d4eae9ffebd2a1&tochange=598305280dc37b6b0136795508e4ff7c8ab7b480

https://github.com/devtools-html/debugger.html/compare/release-81...release-82

**Comment by jasonLaster** [comment]
CC @WenInCode

**Comment by WenInCode** [comment]
👀 Oh yes. I'll take a look at this when I do some work on #7206 this weekend

**Comment by WenInCode** [comment]
I think I'll just pull this into the work I'm doing now. 
/claim
