### ISSUE TITLE
Use tabs for the side panels instead of accordion view

### ISSUE THREAD

**Issue by SebastianZ** [devtools-html/debugger.html#722]
The debugger frontend uses an accordion view for its side panels, which got obviously inspired by the Chrome DevTools.

Though this requires the user to scroll up and down to get the required information or set breakpoints, which causes a bad UX.

Better would be to put them into tabs like in the existing Firefox DevTools debugger frontend, so users can switch between them by a click.

Sebastian

**Comment by jlongster** [comment]
Tabs don't work because there are too many sections to show. We were previously very constrained and could only have 2 tabs before the tab headers got too small. We will likely have around 6+ panels so tabs just don't work. There's not enough room.

I'm definitely interested in experimenting with different ways to display that information, but we were intentional about using an accordion. Sorry if you prefer the old way!

**Comment by jasonLaster** [comment]
@SebastianZ would it help if we pinned the accordion headers so that they could not scroll out of view. 

> disclaimer: this is a bad photoshop job and the idea is not fully baked. I believe this is a mobile pattern though.


![screen shot 2016-09-14 at 11 47 10 am](https://cloud.githubusercontent.com/assets/254562/18519113/a9bca062-7a70-11e6-99b6-c94fda379db7.png)

**Comment by SebastianZ** [comment]
> We will likely have around 6+ panels so tabs just don't work. There's not enough room.

So far there are just 3 panels on the right side, *Breakpoints*, *Call Stack* and *Scope* (previously only two, *Variables* and *Events*).
If you intend to add more panels for the different breakpoint types, then I suggest to do it like Firebug did. I.e. add an accordion for the different breakpoint types within the *Breakpoints* panel:

![Firebug's *Breakpoints* panel](https://cloud.githubusercontent.com/assets/958943/18529675/62333d88-7ace-11e6-935d-36de4e78c4ad.png)

> Would it help if we pinned the accordion headers so that they could not scroll out of view.

It would be better, though I still believe that the UI outlined above has a better usability and conforms better to the existing DevTools UI.

Sebastian

PS: Some years ago I suggested several UI improvements for Firebug's *Script* panel, which might be worth considering for this regard.

**Comment by clarkbw** [comment]
> PS: Some years ago I suggested several UI improvements for Firebug's Script panel, which might be worth considering for this regard.

If you can link those suggestions I'd love to look through them.  🙇

**Comment by jlongster** [comment]
I wasn't thinking of breakpoints types; there will be whole new areas like watch expressions and threads. While we don't take advantage of it now, I think we have the potential to be better at showing you more information at once. For example, if we only shows the top few call frames, you could see your watch expression, frames, and scopes all at a single glance instead of having to click between tabs. Scrolling is also much quicker than clicking between tabs.

For what it's worth, we didn't just do this without any thought. It was an intentional improvement over the existing UI, and I'm sure there are more improvements we could make. I'd like to experiment with better ways to show the info too, but it has to be more amenable to lots of information than tabs are.

**Comment by SebastianZ** [comment]
>> PS: Some years ago I suggested several UI improvements for Firebug's Script panel, which might be worth considering for this regard.
> 
> If you can link those suggestions I'd love to look through them. :bow:

Oops. Had the page open but forgot to add the link. Here it is:
https://github.com/firebug/firebug/issues/2923

> I wasn't thinking of breakpoints types; there will be whole new areas like watch expressions and threads.

In my thinking threads would have their own tab, watch expressions would go under *Scopes*.

> While we don't take advantage of it now, I think we have the potential to be better at showing you more information at once.

With the limited amount of space within the sidebar this is very tricky to do and the UI may get really crowded like it's the case in the Chrome DevTools when you're stopped at a breakpoint.

> Scrolling is also much quicker than clicking between tabs.

I strongly disagree with that statement. 1. Scrolling requires you to search for the section you want to see, especially when the sections contain a lot of information (might be mitigated with @jasonLaster's suggestion to pin the headers, but not sure yet how this would work exactly), 2. With all sections shown below each other the information you're looking at moves up and down when items in other sections are added or removed, which causes the UI to be unsteady. 3. They only allow to save one scroll position, so if you scrolled down it may happen that you e.g. only see some scope variables at a specific position. Tabs allow you to save the scroll position for each section.

Just to be clear, my opinion is that accordions are good to show related information like different kinds of breakpoints or the scope variables and watch expressions, but different information should be put into different tabs or other UI to be able to separate it better.

Sebastian

**Comment by SebastianZ** [comment]
@jlongster, @jasonLaster, @clarkbw I'd really like to get some feedback to my last comment. I am still convinced that a tab based UI for the different types of information is better for the reasons I outlined there.

Sebastian

**Comment by jasonLaster** [comment]
@SebastianZ sorry for the slow reply.

I think something like this makes sense if we think about it in terms of different modes (active / paused).

I like the idea of having the sidebar focus on breakpoints/watch expressions when the debugger is active and focus on pause state when its paused.

We would like to move the left sidebar toggling to a dropdown soon. Maybe this would be good with some keyboard shortcuts...

<img src='https://shipusercontent.com/2a346276bc2e8ad7e1c2bf52df5780e6/Screen%20Shot%202017-08-22%20at%201.41.30%20PM.png' title='Screen Shot 2017-08-22 at 1.41.30 PM.png' width=339>
