### ISSUE TITLE
Stop converting spread syntax into Object.assign

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#7223]
https://github.com/devtools-html/debugger.html/blob/e7f212ee3916d97c799549b6b89cb43fbc1ce34f/packages/devtools-reps/src/reps/grip.js#L169

```js
properties = { ...properties, ...object.preview.safeGetterValues };
```

uses spread syntax because of https://github.com/devtools-html/devtools-core/issues/986

However, somehow this is transformed into https://searchfox.org/mozilla-central/rev/50ba1dd30cf013bddce1ae756f1b3c95b26f0628/devtools/client/shared/components/reps/reps.js#1429

```js
properties = _extends({}, properties, object.preview.safeGetterValues);
```

where `_extends === Object.assign`.

This causes https://bugzilla.mozilla.org/show_bug.cgi?id=1496044

Regressed by https://bugzilla.mozilla.org/show_bug.cgi?id=1457517

https://github.com/devtools-html/debugger.html/compare/release-45...release-46, probably https://github.com/devtools-html/debugger.html/commit/03010e173028716de3c0ddb04e61487c3de05b98

**Comment by jasonLaster** [comment]
Thanks @Loirooriol I'll fix this next week.

**Comment by pradeepgangwar** [comment]
@jasonLaster @Loirooriol I don't think this needs changes in this repo. Please let me know if i am missing something.

**Comment by Loirooriol** [comment]
@pradeepgangwar This didn't happen when the code was in devtools-core. I guess babel is misconfigured here and breaks the code.

**Comment by jasonLaster** [comment]
I think this was done in m-c. Thanks

**Comment by Loirooriol** [comment]
@jasonLaster This is still broken, please reopen.

**Comment by nchevobbe** [comment]
i'm looking into this
