### ISSUE TITLE
Unify implementation for Source/Outline tabs and file tabs

### ISSUE THREAD

**Issue by Doomwyte** [devtools-html/debugger.html#7225]
<img width="864" alt="screen shot 2018-11-03 at 3 02 15 pm" src="https://user-images.githubusercontent.com/16697942/47957794-18cea480-df7a-11e8-8bf3-aed18ffcd6fe.png">

Sort of a continuation of issue #7034 . 

We want the Source/Outline tabs to have the same design as the file tabs. Currently, the way the Source/Outline tabs are implemented is different from the way the file tabs are implemented. Since they are to have the same design, we should unify the implementation, or at least on the CSS side, use the same classes.

**Comment by darkwing** [comment]
I disagree with the "unification" here; while the Sources pane could act as its own tab, the Outline tab cannot -- it needs some relationship to a given tab and thus both must be highlighted.
