### ISSUE TITLE
Documentation: Getting Started guide shouldn't mention the removed GCLI

### ISSUE THREAD

**Issue by zhuowei** [devtools-html/debugger.html#7227]
The Getting Started page mentions the Firefox GCLI:

https://github.com/devtools-html/debugger.html/blob/master/docs/getting-setup.md#firefox-gcli

which was removed in [Firefox 62](https://developer.mozilla.org/en-US/docs/Tools/GCLI).

This section of the documentation should be removed or rewritten to use whatever the GCLI replacement is.

**Comment by acnair** [comment]
Hi, I am new to FOSS is this a good first issue so that I can take it up and from here can i start contributing to Mozilla?

**Comment by AnshulMalik** [comment]
It's a good start @acnair

**Comment by acnair** [comment]
hey, @AnshulMalik could you check it?
