### ISSUE TITLE
Hovering over a number gives the wrong value

### ISSUE THREAD

**Issue by gregtatum** [devtools-html/debugger.html#7245]
I'm not sure how to provide steps to reproduce, but I found an odd bit of behavior. Hovering over the number `1` gave me the value of `areaLeftOfLastDrawnPixel`.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/1588648/48142242-07cfad00-e272-11e8-8a32-7fa1764c3d56.png">

**Comment by loganfsmyth** [comment]
Probably the same core issue as https://github.com/devtools-html/debugger.html/issues/7211?

**Comment by jasonLaster** [comment]
oh weird, we do our best to get the best expression to evaluate. It looks like we think the best expression to show is the assignment... definitely a bug
