### ISSUE TITLE
Avoid rendering column breakpoints that would not map properly to the generated source

### ISSUE THREAD

**Issue by loganfsmyth** [devtools-html/debugger.html#7248]
One issue we want to address with column breakpoints is hiding them in cases where they won't render in a meaningful way. This happens currently in sourcemapped content that only has line-granularity mappings. This also arises for pretty-printed files, though we will ideally fix that eventually.

The core of the issue is that if you look at an original file, it may have many useful column locations, but if the source mapping is not fine-grained enough, you can easily take a line/column location on the original file and simply end up at the start of the line in the generated file, essentially making the column breakpoint useless.

We want to be able to detect this failure mode and skip rendering column breakpoints for a given line if it is detected to have poor mappings. One way to do this would be to inspect the map itself to get a sense of its structure, but this can end up being relatively complex.

What is probably easier would be to take advantage of the high likelyhood that the bad mappings mean that multiple column offsets will all map to the same column in the generated code. We could then consider

```
if (callSites.length > 1 && !hasConflictingGeneratedPosition(callSites)){
  // only render the callsites if this passes
}
```
where `hasConflictingGeneratedPosition` would take the original line/column of each callsite and get its generated location. If the mappings are fine-grained, we'd expect each callsite to have a unique generated line/column, but if they are line-level mappings, it is very likely that multiple callsites would share the same generated line/column offset, meaning that we'd likely want to skip rendering the callsites entirely.

**Comment by jasonLaster** [comment]
I think we should assume callSites already has generated columns, so it could be even simpler

```js
hasConflictingGeneratedPosition(callSites) {
  return uniq(callSites.map(site => site.generatedLocation.line)).length > 0
}
```

**Comment by loganfsmyth** [comment]
Agreed that precomputing the generated location would be ideal. I think we'd want to check uniqueness of line/column pairs though, and that `length` check needs to compare with `callSites.length`.
