### ISSUE TITLE
npm run firefox crashes

### ISSUE THREAD

**Issue by daviddahl** [devtools-html/debugger.html#725]
`npm run firefox` runs a new copy of firefox 48.0.1 for a bit but then crashes. I am able to connect to the running instance from debugger.html at first

see:
http://pastebin.com/anQcuU4V

**Comment by jasonLaster** [comment]
Thanks, I think this is because we need to use `marionette` after 47.

**Comment by jasonLaster** [comment]
@jacobjzhang, @daviddahl just pushed a fix. It would be great if you could pull and see if this fixes it.
