### ISSUE TITLE
[Question] How to merge upstream changes from mozilla-central repo?

### ISSUE THREAD

**Issue by pd4d10** [devtools-html/debugger.html#7250]
Hi,

I'm wondering how do you merge upstream changes of [mozilla-central](https://hg.mozilla.org/mozilla-central/).

Sometimes both `debugger.html` and `mozilla-central/devtools/client/debugger` have some commits already, there should be a mechanism(`git rebase` or something else) to bring these commits together.

I don't find any documentation about this. Could you explain it? Thanks!

---

Because I'm working on porting Firefox's builtin JSON viewer to other browsers, which is almost done [here](https://github.com/pd4d10/json-viewer). It use `mozilla-central` repo as git sub module to sync with upstream changes.

The problem is `mozilla-central` is a huge repo, which could takes up lots of disk space, and makes operations like `git status` quite slow.

Inspired by `debugger.html` and `perf.html`, I think maybe we can do the same thing to JSON view component: Extract it as `jsonview.html` for the community.

**Comment by jasonLaster** [comment]
Oh great. Here are our docs on [releases](https://github.com/devtools-html/debugger.html/blob/master/docs/bundling.md#what-is-a-release)

We do releaess 2/3 times a week where we cherry pick commits onto our release branch and run the `copy` tool to update m-c and make a new release commit in mc. 

I'd be happy to do a call and discuss

**Comment by pd4d10** [comment]
Thanks! It's great. This documentation is exactly what I want.
