### ISSUE TITLE
Document debugger test commands / assertions

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#726]
We currently have an [api](https://github.com/devtools-html/debugger.html/blob/master/docs/mochitests.md#api) in our mochitests doc that is already out of date. 

It would be nice to use document.js to document the debugger command / assertion functions.

**Comment by jbhoosreddy** [comment]
That doc is a single source of reference for me when it comes to tests. I end up going back to it so many times, and I'm sure many other contributors would find it useful.

**Comment by jbhoosreddy** [comment]
Do you think it will be possible for me to investigate this one, unless someone else is already planning on doing it?

**Comment by jlongster** [comment]
@jbhoosreddy go ahead! Just need to look at all the helper functions in `head.js` and make sure they exist in the API list.

**Comment by clarkbw** [comment]
#750
