### ISSUE TITLE
Allow pretty printing CSS

### ISSUE THREAD

**Issue by dwt** [devtools-html/debugger.html#7267]
Hi there,

I noticed that there seems to be no option to pretty print CSS in the firefox debugger - sorry if this is the wrong place to request this.

How to reproduce:
1. Open any page with minified css
2. Look at it in the firefox debugger and try to find anything
3. Fail because it just endlessly scrolls to the right and there is no way to sensibly navigate.
4. Search around and find nobody else seems to know where this feature is
5. Find this bug tracker and realize that there seems to be no bug that tells the story of this feature

So, here we ware - hopefully at the right bug tracker.

What I'm missing is a feature like for JS where you can switch a toggle in the css view of the 'Style Editor' and have an at least somewhat sensible view of CSS.

IMO compressed CSS is quite a bit easier to work with than compressed JS as names are way less (or not at all) mangled so it's still quite intelligible.

**Comment by jasonLaster** [comment]
hmm, i don't think we show css in the debugger. Do you mean the style editor?

You can file a bug there  -- https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Style%20Editor
