### ISSUE TITLE
[Parser] mapOriginalExpression does not handle destructuring assignments well

### ISSUE THREAD

**Issue by P0lip** [devtools-html/debugger.html#7274]
When working on #7222 I found out that destructuring assignments are not handled properly by `mapOriginalExpression` function.

I created the following test case for `mapOriginalExpression` function and it does not pass.

```js
it("object destructuring", () => {
  const generatedExpression = mapOriginalExpression("({ a } = { a: 4 })", {
    a: "_mod.foo",
  });
  
  expect(generatedExpression).toEqual("({ a: _mod.foo } = { a: 4 })");
});
```

This is the actual output I received:

```js
({ _mod.foo: _mod.foo } = {  a: 4 });
``` 
It's obviously incorrect (it's not even a valid syntax).

Expected state:

Mapping is done correctly, i.e.
`({ a: _mod.foo } = { a: 4 })`

or `_mod.foo = ({ a: 4 }).a`

or no mapping is done at all (?).

**Comment by jasonLaster** [comment]
I always forget about this :) `({ a } = { a: 4 })`

do we want something like `({ a } = await { a: 4 })`

**Comment by jasonLaster** [comment]
oops didn't mean to close it 😉

**Comment by P0lip** [comment]
As stated, I didn't spend much time investigating the issue, but it seems like `mapOriginalExpression` 'rewrites' every Identifier that could be mapped. While this approach is usually correct, it does not work properly in case of destructuring.

I suppose the issue is caused by the following [traversal](https://github.com/devtools-html/debugger.html/blob/e189bec6c5bba435d4a71495f3d1715ed8cc548c/src/workers/parser/mapOriginalExpression.js#L91#L101)

We would need to apply a slightly different Identifier replacement here to support destructuring.
(ideally `({ a: <replacement> } = { a: 4 })` where replacement is the new mapped Identifier we want to insert.

I hope this makes a bit more sense now.
@loganfsmyth, you might want to provide some ideas and possible solutions. :)

Happy to implement a fix once the expected output/behavior is established.
