### ISSUE TITLE
:formatted displaying in Tabs and Breakpoints Sidebar again

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#7283]
Just spotted this:

<img width="869" alt="prettyformatted" src="https://user-images.githubusercontent.com/46655/48589851-ecfcd880-e902-11e8-81cc-f6cf02cdff5d.png">

I think this may be a result of @WenInCode's work with querystrings.  We should also add a unit test to check for this, as it's regressed a few times now.

**Comment by WenInCode** [comment]
👀
