### ISSUE TITLE
Context menu Source actions should be available from the SourcePanel and Source Tab

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#7287]
Someone was asking on IRC how one could blackbox a script, so I tried myself by: 
- doing a right click on the sources panel, on the script I wanted to blackbox: -> no luck
- opening the source, right click on the source tab -> no luck
- right click *in* the source content -> jackpot

So this is pretty confusing to me that we have to open a source and specifically right-click in the content.
We should be able to perform any source-related action from whatever represent a source in the UI (so, from the sources panel and the source header, maybe from the callstack as well)

I think it's pretty important because at the moment users might miss that we have such feature

**Comment by nchevobbe** [comment]
I checked and Chrome does the same thing, but I still find this is bad behavior and we can aim for better than them :)

**Comment by Art-Vanderlay** [comment]
@Doomwyte are you still working on this?

**Comment by nyrosmith** [comment]
I think solving this will become lots easier after refactoring the context menu https://github.com/devtools-html/debugger.html/issues/7497
