### ISSUE TITLE
Stepping out into an HTML 'onclick' attribute shows the HTML file with an unexpected highlight

### ISSUE THREAD

**Issue by loganfsmyth** [devtools-html/debugger.html#7293]
STR:
* Open https://firefox-dev.tools/debugger-examples/examples/babel/
* Open the debugger
* Click the `nestedProperty` button and the debugger should pause
* Click step out

ER:
Highlight the line in the HTML where the `onclick` attribute is

AR:
Highlights the second line for some reason:
<img width="481" alt="screen shot 2018-11-16 at 12 08 19 pm" src="https://user-images.githubusercontent.com/132260/48644712-567af680-e998-11e8-85e5-b4ef74385eef.png">

**Comment by jasonLaster** [comment]
closing as this is in bugzilla
https://bugzilla.mozilla.org/show_bug.cgi?id=1517626
