### ISSUE TITLE
[PrettyPrint] you should see the pretty icon

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#7295]
Here's a nice bug that *will* only became possible next week

- once we allow you to disable sourcemaps, it will be possible to pretty print files that have a sourcemap
- once you do that, you can pretty print a react file and then you'll want to see the pretty icon...
-but instead you see the react icon

STR:

1. go to https://4zj3qr7lx4.codesandbox.io/
2. open devtools, go to settings and disable source maps
3. go to the debugger, select Footer.js, and pretty print the file

ER: see the pretty icon in the pretty tab and the source tree
AR: see the react icon

<img width="850" alt="screen shot 2018-11-16 at 3 42 12 pm" src="https://user-images.githubusercontent.com/254562/48646278-673a6500-e9b6-11e8-97e9-4b2626798c80.png">

**Comment by ZhangYue-vhyt** [comment]
Hi, Jason

Is it possible to pretty print files that have a sourcemap now? I did the following test with an updated branch. 

The "pretty print" button doesn't show when I select Footer.js. If I pretty print it by the tab menu, an uncaught exception is popped, and `isPretty(source)` returns `false`. But yes, I see the react icon.

![image](https://i.imgur.com/rV0Uber.gif)
