### ISSUE TITLE
Step In Button Shortcuts differs in Linux, Windows 

### ISSUE THREAD

**Issue by sennahLessert** [devtools-html/debugger.html#7306]
Hi

The step in button shortcut differs in linux and windows.
`const KEYS = {
  WINNT: {
    resume: "F8",
    stepOver: "F10",
    stepIn: "F11",
    stepOut: "Shift+F11"
  },
  Linux: {
    resume: "F8",
    stepOver: "F10",
    stepIn: "Ctrl+F11",
    stepOut: "Ctrl+Shift+F11"
  }
};`

To make usage easier use the same shortcut on each OS _IF_ it is possible.
So change step -in And step out Shortcut on Linux to F11 and Shift F11 or make the shortcuts configurable through settings dialog

Thank you.

**Comment by jasonLaster** [comment]
CC @digitarald @janodvarko could you look into whether we should change these?

**Comment by sennahLessert** [comment]
any progress on that issue?

**Comment by darkwing** [comment]
Yes @sennahLessert!  Could you try out or review this PR?  https://github.com/devtools-html/debugger.html/pull/7338
