### ISSUE TITLE
Hover on minified large code causes 5s delay

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#7309]
STR: Opened debugger on Gmail and hit Pause.

https://perfht.ml/2A4FNkE

![image](https://user-images.githubusercontent.com/8599/48729544-afdb6380-ebec-11e8-8d47-5fb1a6a2053f.png)

Lots of GC caused by `locationKey`

![image](https://user-images.githubusercontent.com/8599/48729657-fe88fd80-ebec-11e8-837c-96f451e07c09.png)

`findBestMatchExpression` might suffer from cross-compartment wrapper

![image](https://user-images.githubusercontent.com/8599/48729722-20828000-ebed-11e8-98fa-7acb0e208f1e.png)

The delay caused the tooltip at some point to appear on the source panel toolbar; didn't know that was possible:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/8599/48729482-8cb0b400-ebec-11e8-84f1-84c1d892ac25.png">

**Comment by jasonLaster** [comment]
getCallSites should use reselect 
https://github.com/devtools-html/debugger.html/blob/master/src/components/SecondaryPanes/Breakpoints/Breakpoint.js#L9-L10

**Comment by darkwing** [comment]
We're using `visibleColumnBreakpoints` so this complete.
