### ISSUE TITLE
Sad face from unmatched search UI is overly sad, and red text is too bright

### ISSUE THREAD

**Issue by violasong** [devtools-html/debugger.html#7325]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/55994/48861796-58b6c980-ed79-11e8-969e-0ee035b3a753.png">

**Sad face:** I don't see an unmatched search as an error or something worthy of this much sadness. It could be a positive result (e.g. when making sure some old code no longer exists). However, I can see why the color change and icon change are helpful as a quick, bolder indicator than the pale "No results" message. I can also appreciate the whimsy factor, similar to Berror, seen at `about:asdk`.

**boring replacement ideas**
<img width="426" alt="image" src="https://user-images.githubusercontent.com/55994/48863739-3f188080-ed7f-11e8-84a6-5804ba207691.png">

**counteroffer to offset loss of whimsy**
stick this happy fox face somewhere, such as to introduce a new feature, or to applaud some use of special advanced functionality:
<img width="71" alt="image" src="https://user-images.githubusercontent.com/55994/48863847-a20a1780-ed7f-11e8-87c9-57e8ccf001d0.png">

**Text color:** Currently the red color seems to have an orange tone that doesn't match Photon. I recommend the darker red text color used in Console errors.

**Comment by darkwing** [comment]
@violasong Where can I find the warning icon?  Do we use it anywhere else?

**Comment by violasong** [comment]
We're using it console, and it's also here https://design.firefox.com/icons/viewer/#warning

Although I think my favorite solution would be https://design.firefox.com/icons/viewer/#info plus the console dark red error text color

**Comment by darkwing** [comment]
Could we go with a yellow?  Red seems harsh, like there's an error

**Comment by nchevobbe** [comment]
Whatever we decide here, let's also have a follow up for the reverse search on the console. We used red to match the debugger when there's no result, so we should keep it in sync :)

**Comment by baronKilljoy** [comment]
I am new but would like to give this a try, assuming a final decision is made on icon and color.

**Comment by violasong** [comment]
Ah, I was still thinking red was fine because its what is used for Firefox in-page search, but I know what you mean about the error part. Even yellow/warning is a little wrong.

What if it looked like this? The other searches could follow suit, so instead of "0 results" way to the right of the input in find in file, it would be pretty front and center.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/55994/49973958-09813600-feec-11e8-953a-29e02d0dc6e0.png">

(sort of matches the [black main text  /grayed out path/] pattern of the result rows)

**Comment by rivalDevYP** [comment]
I was thinking Orange? Specifically this: `color: #FF850B;`

Let me know...

**Comment by violasong** [comment]
(Oh and the text could say 0 results instead of not found of course)

> I was thinking Orange? Specifically this: color: #FF850B;

We're trying to choose a more neutral design for this so that it doesn't look like an error/warning - so I think just a prominent Gray50 message could do it

**Comment by darkwing** [comment]
@violasong I love this `not found` screenshot!  Yes!

**Comment by rivalDevYP** [comment]
> We're trying to choose a more neutral design for this so that it doesn't look like an error/warning - so I think just a prominent Gray50 message could do it

So something like a `#7f7f7f` ?

**Comment by rivalDevYP** [comment]
> I don't see an unmatched search as an error or something worthy of this much sadness

I don't know... late night compilation errors in college certainly comes close...

**Comment by violasong** [comment]
There’s a variables.css that has the gray50 token which is #737373

**Comment by darkwing** [comment]
@baronKilljoy Would you like to take this now?  I think we'd like to go with the `--no results found` option! 👍
