### ISSUE TITLE
[breakpoints] update the skip pausing button copy

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#7360]
Currently hovering on the button shows this copy "Skip all pausing". That is kind of a lie because in reality you'll just skip pausing due to breakpoints. Chrome's copy is "Deactivate breakpoints". I think that is a better option.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/254562/49172523-4f94a200-f30f-11e8-9078-e7a545217dba.png">

**Comment by melirofman** [comment]
Hi! Can I pick this one up?

**Comment by jasonLaster** [comment]
Sure!

**Comment by acnair** [comment]
@jasonLaster Hi I see that @melirofman is already working on it! But just curious where do we make the changes or where is this issue as in more precise area?

**Comment by acnair** [comment]
@kenjiO thanks for the update but what I can't figure out is where to use the ```L10N.getStr()``` .

**Comment by kenjiO** [comment]
@acnair In the case of this issue the L10N.getStr function is called [here](https://github.com/devtools-html/debugger.html/blob/04ee6a4b2d805ba5ba53eb48f167897182366099/src/components/SecondaryPanes/CommandBar.js#L273)
