### ISSUE TITLE
Exception reason stretches sidebar length

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#7361]
<img width="325" alt="pauseexceptionwidth" src="https://user-images.githubusercontent.com/46655/49172543-ff194680-f306-11e8-9176-d8311dfbbcf2.png">

The red message should wrap.

**Comment by AnshulMalik** [comment]
STR:
1. Open https://davidwalsh.name/
2. Shrink debugger's right sidebar
3. In right sidebar, check `Pause on Exceptions`
4. In right sidebar, check `Pause on caught Exceptions`

Now you'll see the exception, if not, try to refresh.
