### ISSUE TITLE
Functions with `$` character misrepresented in Outline View

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#7382]
I was on my site and looking at the following resource:

https://www.google-analytics.com/analytics.js

I switched to outline view and saw that the list looked out of order:

<img width="1424" alt="blingbling" src="https://user-images.githubusercontent.com/46655/49267722-6deac280-f421-11e8-8583-ec363ece729d.png">

It turns out our `simplifyDisplayName` function is stripping the `$` from function names.  We...shouldn't do that/

**Comment by nchevobbe** [comment]
affects console trace as well: 

```js
$a = () => b$();
b$ = () => $c$();
$c$ = () => console.trace("💲💲💲💲");
$a();
```

outputs: 
```
console.trace() 💲💲💲💲 debugger eval code:3:13
    $c$ debugger eval code:3 
    b$ debugger eval code:2 
    a debugger eval code:1 
    <anonymous> debugger eval code:4 
```

So `$a` becomes `a`. 

It would be nice to fix this before the merge day
