### ISSUE TITLE
Consider evaluating getters in the root object

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#7397]
It's usual to define getters in a function prototype so that they will be inherited by the instances. Usually it makes no sense to call the getter in the prototype itself.

For example, consider:

```js
new class {
  constructor() {
    this.num = Math.random();
  }
  get double() {
    return this.num * 2;
  }
}();
```

You can inspect the `<prototype>` and run the `double` getter but you will only get `NaN` because the prototype has no `num` property.

I think it would be more useful to evaluate the getter in the root object instead of in the owner one.

Alternatively, `double` could appear in both objects, so that the user can decide in which one it should be evaluated. The downside is that there could be lots of inherited getters and the user might lonly be interested in the own properties, then this would be a nuisance. So maybe group them in a `<inherited getters>`, similar to `<default properties>`.

**Comment by nchevobbe** [comment]
I agree that we should see the `double` property in the root, I'll try to find why we don't

**Comment by Loirooriol** [comment]
It doesn't appear in the root because it's not an own property and it's not a safe getter.
