### ISSUE TITLE
mochitest-runner fails to run

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#740]
I'm seeing the circle ci tests fail claiming it is missing the tag `latest`.  @jlongster do you know what's going on?

```
docker pull jlongster/mochitest-runner

Using default tag: latest
latest: Pulling from jlongster/mochitest-runner

Pulling repository docker.io/jlongster/mochitest-runner
Tag latest not found in repository docker.io/jlongster/mochitest-runner

docker pull jlongster/mochitest-runner returned exit code 1

Action failed: docker pull jlongster/mochitest-runner
```

**Comment by clarkbw** [comment]
I saw that in this run: https://circleci.com/gh/devtools-html/debugger.html/888

Trying additional runs to see if I can reproduce it.

**Comment by jlongster** [comment]
I don't, I have not seen that and I just did a run this morning. It may be docker's servers. Let me know if you can reproduce it.

**Comment by jlongster** [comment]
I just did a push and it worked fine; even rebuilt it to run tests again and it worked. Closing this issue as it was probably CircleCI or docker's servers at fault. If this comes up again, please reopen.
