### ISSUE TITLE
TCP connection error on setup

### ISSUE THREAD

**Issue by notjaril** [devtools-html/debugger.html#7407]
Error repeatedly thrown immediately after setup using default config:

```
yarn run v1.9.4
$ node bin/dev-server
Listening for WS on localhost:8116, all traffic is proxied to localhost:6080
Protocol messages can be logged by enabling `logging.firefoxProxy` `in /configs/local.json`
Hot Reloading - https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#hot-reloading
View debugger examples here:
https://github.com/devtools-html/debugger-examples
Development Server Listening at http://localhost:8000
TCP connection failed: Error: connect ECONNREFUSED 127.0.0.1:6080
WS connection closed, disconnected from TCP
TCP connection failed: Error: connect ECONNREFUSED 127.0.0.1:6080
WS connection closed, disconnected from TCP
TCP connection failed: Error: connect ECONNREFUSED 127.0.0.1:6080
WS connection closed, disconnected from TCP
```
Doesn't seem to affect debugger functions, though it can be misleading to beginners to the project. The error seems to stem from the default setting `webSocketConnection: false` in configs/development.json. 

The error is thrown from devtools-launchpad/bin/firefox-proxy, which is called when `webSocketConnection: false`. Error disappears with `webSocketConnection: true`, where firefox-proxy is not being used (mentioned in https://github.com/devtools-html/debugger.html/issues/1069).

**Comment by reCursedd** [comment]
Was facing this issue. How to go about resolving this issue?

**Comment by AnshulMalik** [comment]
I think we should change it's default value to `true` since launchpad I think is used with just firefox where port 6080 is not open.
