### ISSUE TITLE
Search field polish

### ISSUE THREAD

**Issue by violasong** [devtools-html/debugger.html#7425]
**Find in File:**

Pretty print/blackbox buttons, modifier buttons, and x button should have the same background hover highlight as other buttons in devtools.

(Same for all other buttons in Debugger, but most of them at least have a subtle highlight. Especially in need of an update are pretty print/blackbox (overlaps at the top) and any buttons in dark mode (too subtle))

**Quick Open:**

In dark mode, the light shadow seems odd - could we try a black shadow instead?

**Find in project:**

Discussion point - do we still want to move it to the bottom and style like Find in File? https://mozilla.invisionapp.com/share/Y8H6UH8V5HX#/screens

cc @mcroud

**Comment by darkwing** [comment]
> Pretty print/blackbox buttons, modifier buttons, and x button should have the same background hover highlight as other buttons in devtools.

What color is that?

**Comment by rjairath** [comment]
Hi,
I would like to work on this issue

**Comment by darkwing** [comment]
Sounds good @rjairath !  I can't wait to see what you come up with!

**Comment by violasong** [comment]
>What color is that?

Oh haha, great question - I realized it's currently pretty inconsistent across DevTools. I just really noticed it in Debugger because the pretty print has that overlapping problem, and the stepper icons have a non-photon blue-ish hover. 

I think we should change all button hover backgrounds to match the more contrasted gray color of the top-level tab highlight. We can do that for Debugger in this bug, and I'll also file a bugzilla for the rest of DevTools.

**Comment by violasong** [comment]
Overall DevTools bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1513414

**Comment by rjairath** [comment]
![firefoxbug](https://user-images.githubusercontent.com/20504819/50680692-a2f4c100-102e-11e9-8789-172d80c63155.png)

**Comment by rjairath** [comment]
So in the 2 buttons pointed above I have to change the :hover class property as the one in all other buttons. Can you please tell me the css file where I have to make this change.
