### ISSUE TITLE
Sort folders first in tree nodes

### ISSUE THREAD

**Issue by zspitzer** [devtools-html/debugger.html#743]
Currently the folders and files are just sorted alphabetically in the source list, can folders be sorted first?

**Comment by jlongster** [comment]
Yes, this is a good idea. I thought it was supposed to work like that, but there must have been a regression at some point. Thanks!

**Comment by clarkbw** [comment]
This does look a bit difficult.  Here's what I found when I looked into this on my flight.

This function in the `sources-tree.js` file is what does the sorting and it currently only sorts by name, comparing the files and directories against either other. 
https://github.com/devtools-html/debugger.html/blob/f67515acb9493fe1363068b305d0daa5391d659d/public/js/utils/sources-tree.js#L107-L111

It didn't look like you could easily know what was a file and what was a directory within that function so you might need discover and save that earlier so you can more easily do the sorting in that function.  (For example one difference was that the `contents` attribute was an `Array` for directories and a `Map` for files, but that isn't good data to use here)

**Comment by jbhoosreddy** [comment]
Taking this for now if no one else has. I'll see if I can make any progress on this.

**Comment by jasonLaster** [comment]
Thanks. Should be a nice win

**Comment by clarkbw** [comment]
@jbhoosreddy how's it going?  Anything questions?

**Comment by jbhoosreddy** [comment]
I don't think I found out a nice way to resolve this. So I'm dropping this if someone wants to pick it up again.

**Comment by gregtatum** [comment]
I'll take a look.
