### ISSUE TITLE
Breakpoint is changing after reloading

### ISSUE THREAD

**Issue by magsout** [devtools-html/debugger.html#7435]
When diagnosing the webcompat issue https://github.com/webcompat/web-bugs/issues/22279
this issue happens

STR:
0. With Firefox 65.0a1 (2018-12-05) (64-bit)
1. Go to https://shop.lego.com/fr-FR/
2. Open Console.
3. Click on TypeError: e is null; can't access its "functional" property
4. click on braces to pretiffy the code
5. Go back to console
6. Click again on Typerror to get to the source at the right position
7. Set a breakpoint on `var r = !!l() (Object(f.e) (), function (e) {`
8. Reload the page
9. wait
10. wait
11. Eventually the page will reload and the breakpoint is set on `r.parentPush = void 0,` which is a complete different line of the code unrelated to the initial breakpoint.

Something strange happened

**Comment by magsout** [comment]
screencast of the issue
https://imgur.com/a/xuSozgJ

**Comment by darkwing** [comment]
Thank you for filing this @magsout!  We're looking to improve breakpoint quality and this is very helpful!

**Comment by jasonLaster** [comment]
@magsout is this simlar - https://github.com/devtools-html/debugger.html/pull/7342

**Comment by magsout** [comment]
@jasonLaster oh yes it would seem. Sorry to open a new issue.
