### ISSUE TITLE
typo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by iciuperca** [devtools-html/debugger.html#745]
There's probably a typo in the following, Ex: Dec 2016 is in the future.

`devtools.html is the larger umbrella initiative that encompasses the debugger.html and several other devtools projects. The devtools.html project claims its origin from a demo for a Mozilla (Dec 2016) work week in Orlando`

**Comment by jasonLaster** [comment]
Haha nice catch @iciuperca.

**Comment by jbhoosreddy** [comment]
I fixed this in #738.

**Comment by wldcordeiro** [comment]
I liked the implication of time travel though. 😢

**Comment by jasonLaster** [comment]
Yes. We want to work on time travel debugging soon.

**Comment by clarkbw** [comment]
All good debuggers support time travel 😜

**Comment by jbhoosreddy** [comment]
The tricky bit is traveling backwards. 😉

**Comment by jasonLaster** [comment]
I believe you're making that comment from the future circa 2017.

**Comment by clarkbw** [comment]
#738 was merged
