### ISSUE TITLE
Module scope objects not displayed properly when paused in debugger

### ISSUE THREAD

**Issue by notjaril** [devtools-html/debugger.html#7465]
## Expected behavior:

When paused in a breakpoint within a .js file with `type="module"`, it should correctly display the module's scope block on the right sidebar.

## Actual behavior:

Instead, only `<this> : undefined` is displayed in that block. 

#### text/javascript
`<script type="text/javascript" src="main.js"></script>`

<img width="619" alt="screen shot 2018-12-09 at 3 18 45 pm" src="https://user-images.githubusercontent.com/15959269/49704525-0410ac80-fbc9-11e8-9d8e-a73f28fd64f7.png">

#### module
`<script type="module" src="main.js"></script>`

<img width="614" alt="screen shot 2018-12-09 at 3 20 00 pm" src="https://user-images.githubusercontent.com/15959269/49704526-05da7000-fbc9-11e8-9884-3692209e5dd0.png">

## To reproduce:

1. Clone https://github.com/notjaril/module-scope-example.git
2. Open index.html
3. Case 1 (text/javascript), set a breakpoint at main.js:7. Note the Scopes frame in the right sidebar
4. Change the script type in index.html from `text/javascript` to `module`
5. Case 2 (module), set a breakpoint at main.js:7. Note the Scopes frame in the right sidebar

**Comment by jasonLaster** [comment]
@nagpalm7 this could be quite hard... atleast a js engine bug.

**Comment by jasonLaster** [comment]
closing this as it is now in bugzilla

https://bugzilla.mozilla.org/show_bug.cgi?id=1518308
