### ISSUE TITLE
Unresponsive script in pausePoints.js when trying to debug pretty printed site

### ISSUE THREAD

**Issue by miketaylr** [devtools-html/debugger.html#7485]
<img width="426" alt="screen shot 2018-12-11 at 9 23 00 am" src="https://user-images.githubusercontent.com/67283/49811206-bca53000-fd30-11e8-95a0-8e14655bf640.png">

This reproduces for me in DevEdition 65b2 and Nightly 66 on OSX.

STR: 

1. Navigate to https://docs.arnoldrenderer.com/display/A5AFMUG/Arnold+for+Maya+User+Guide
2. Open DevTools
3. Click on the image of the 3d model space guy
4. Click on the link from the TypeError message to open the source script in the debugger
5. Click PrettyPrint (and wait...)
6. Go back to console, click on source link again to go to the right place in the debugger
7. Click around the debugger for a bit... and eventually Firefox will be locked up and you'll get a unresponsive script message.

Note: oddly, trying to go through my steps again, Nightly decided to auto-pretty print (which is neat?) but I ended up with the same frozen pausePoints.js:49 message.

**Comment by miketaylr** [comment]
(https://bugzilla.mozilla.org/show_bug.cgi?id=1512132 is what lead to this particular site)

**Comment by jasonLaster** [comment]
@miketaylr we broke this last week... working on a fix now

**Comment by kenjiO** [comment]
Is this also what is happening in #7434?
