### ISSUE TITLE
Shortcut labels should have `+` and without space in between Keys

### ISSUE THREAD

**Issue by gerdneuman** [devtools-html/debugger.html#7492]
At least on Windows and Linux all Firefox shortcuts have the notation of `+` between keys to be pressed at the same time. Also true for most other application on these platforms. I do not know about Mac though.

1. Almost correct: Only inconsistency here is that there should be no `space` in between the `+`. 

![image](https://user-images.githubusercontent.com/12525563/49864954-ee3afb80-fe03-11e8-951a-c45bbf676682.png)

Correct would be like:
![image](https://user-images.githubusercontent.com/12525563/49865272-cdbf7100-fe04-11e8-9e93-cf283bcc0c5a.png)

or:
![image](https://user-images.githubusercontent.com/12525563/49865328-f34c7a80-fe04-11e8-825a-e44b8eda13c3.png)

2. This is even more incorrect and confusing (especially for beginners):
![image](https://user-images.githubusercontent.com/12525563/49864997-06127f80-fe04-11e8-99d6-b42ae8ce8680.png)

Please add an `+` in between keys and remove `space` :) Simply for consistency. Sure this is nitpicking, but it's the small things that add up.

Side note: Especially confusing for VSCode users where `no +` means that the shortcut should be pressed *after* another like in VSCode's `Ctrl+K W` meaning to first press `Ctrl+K` and then `W`

**Comment by Art-Vanderlay** [comment]
Hello, I'm a newbie here. Can I work on this issue?

**Comment by nchevobbe** [comment]
Hello @Art-Vanderlay , thanks for offering help!
You can have a look in this function https://github.com/devtools-html/debugger.html/blob/c2c32a820018fad6310d3af9d30b4a257d8b9efb/src/utils/text.js#L29-L40
The shortcut are defined like this one: https://github.com/devtools-html/debugger.html/blob/7d20a5f91e96a7f00a7d74073875842f0dd495e6/assets/panel/debugger.properties#L191

So `CmdOrCtrl+P`, then `formatKeyShortcut` replace some part of that to match the operating system the user is on.
But doing that, we also strip the `+`, which we shouldn't do.
So you could change that in the `replace` calls to make sure we change `+` into ` + ` (with space before and after).

**Comment by nchevobbe** [comment]
You can use `/claim` on a comment, and the bug will be assigned to you

**Comment by Art-Vanderlay** [comment]
Thanks a lot. I'll get started very soon. /claim

**Comment by gerdneuman** [comment]
@Art-Vanderlay Results and Code look good to me, though code would be easier to review if it was a Pull Request, since the changes would then be highlighted. I guess you can go ahead and add a Pull Request (in case of problems one of the maintainer will review it there). 

Last not least: Thanks :+1:
