### ISSUE TITLE
Collapsing Secondary Pane Creates Horizontal Scrollbar for Entire Debugger

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#7505]
Toggling the secondary pane's collapse button shows a scrollbar at the bottom of the entire debugger panel which is ugly:

<img width="1380" alt="gross" src="https://user-images.githubusercontent.com/46655/49981613-4f56f200-ff1e-11e8-86c9-ea4921722691.png">

The cause is that the `.splitter` element is `display: flex: 0 0 1px;`.  If we add `display: none;` if that panel is closed, the scrollbar goes away.

**Comment by varghesethomase** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5429756/50009852-4ca8db00-ffb8-11e8-90d5-3e8133076f27.gif)

@darkwing I managed to fix this issue as you suggested by adding a display none. But I am relying on the `endPanelCollapsed` prop value to add the style display "none" or "block" to the splitter. But as you can see from the gif, the prop changes abruptly. Could you please check?

**Comment by darkwing** [comment]
I believe what happens when you click the "end panel collapse" button is:

1. Right column DIV animates width from {x} to 0
2. Right column DIV is removed from DOM.

I think we might be able to make this easy, actually:

```css
.A11y-mouse > .split-box > .splitter:last-child {
  display: none;
}
```

If the last element in its parent is the .splitter, simply remove it, because it can't be seen or dragged anyway.  Have a try at that :)

**Comment by varghesethomase** [comment]
Thank you @darkwing. I have raised a PR for the same. https://github.com/devtools-html/debugger.html/pull/7513/files
