### ISSUE TITLE
Make the hardcoded development web server port number 8000 configurable 

### ISSUE THREAD

**Issue by jkesseler** [devtools-html/debugger.html#751]
The port number in of the server is hardcoded in [`bin/development-server.js`](https://github.com/devtools-html/debugger.html/blob/c8292de68970552049bc9b2cfb4db1ec806e64e3/bin/development-server.js#L86). This will clash if the project you are trying to debug also runs on port 8000.

**Comment by jasonLaster** [comment]
That's a good point @jkesseler It should be a parameter [here](https://github.com/devtools-html/debugger.html/blob/master/config/development.json) and then you could override it in `local.json`.

**Comment by jbhoosreddy** [comment]
fixed in #753
