### ISSUE TITLE
Proposal for new Community Team Page

### ISSUE THREAD

**Issue by emmairwin** [devtools-html/debugger.html#7522]
Looking for feedback on this [draft](https://docs.google.com/document/d/10LDyRl4wYkZE-zEJd91e9u6TfOLRH--n46-8krx3IgM/edit#) for a new Community Leadership page. Purpose is to update to [Inclusive Leadership principles.](https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus_areas/leadership/assets/leadership-principles.md).   

1. Role Descriptions (what Community Team Does)
2. Better introduces members of the team, including what they can help with.
3. Proposes three role types (active, paused, and alumni).
4. Describes how to join the team (nomination, or self-nomination)
5. Describes a renewal cycle (every 6 months) .

I have run this by existing community team,   and looking for more feedback before we do a final Pull Request. Some prompts for feedback.

1. Does this make the community team feel more accessible (you are more likely to ask them for help)
2. Does this make the community team, feel like something you can be a part of  (if you had goals  in this area).
3. Do the role types properly honour different stages of activity (i.e. alumni).
4. Anything else you feel is missing, or not clear.  

Thanks

**Comment by jasonLaster** [comment]
The doc is great!

**Comment by emmairwin** [comment]
Current version is here:  
https://github.com/emmairwin/debugger.html/blob/master/docs/community-team.md

But I am missing information for a few community-team alumni and curren
