### ISSUE TITLE
`Sources` and QuickOpenModal should respect `Enable add-on debugging` setting

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#7531]
As most "power-users" I use several add-ons. I use these but I have no intend of debugging these. Now these fill-up my `Sources` tab:
![image](https://user-images.githubusercontent.com/3307404/50148544-15d50c80-02b9-11e9-9d8b-8924f12ae36a.png)

And also fill and slow down my `Ctrl+P`:
![image](https://user-images.githubusercontent.com/3307404/50148580-2b4a3680-02b9-11e9-8f85-c5f4bf4b8a92.png)

NB: In the above all searches for `react` find only my add-ons.

Expected results:
I do not want to debug add-ons. If I have an intent to do so, I'd be happy to learn that there's an option to turn on Add-on debugging. So please add an option under `F1` aka `Settings`  under `Advanced settings` to `Enable WebExtension (Add-on) debugging`. This checkbox setting should be off by default. Th

**Comment by jnachtigall** [comment]
Oh, well, there's already an option to `Enable browser chrome and add-on debugging toolboxes` which might be used for this. Unless enabled the sources of WebExtensions should not be visible in the Debugger (Sources, `Ctrl+P` and so on)

**Comment by jasonLaster** [comment]
I think this is a good idea.

CC @digitarald 

We also should have extension URLs instead of IDs, but that is besides the point

**Comment by digitarald** [comment]
Hooking into the setting was exactly my thought as well, as it is the opt-in for extension developers. It is not perfect, as it is also used by Firefox frontend devs; but close enough.

Same should probably apply to Console for extension logs, cc @nchevobbe .

**Comment by AnshulMalik** [comment]
This pref (`devtools.chrome.enabled`) is being used at lot of places as @digitarald said. I tried to use this pref, and it turns out that if it's disabled, we get this
`Could not run chrome debugger! You need the following prefs to be set to true: devtools.debugger.remote-enabled, devtools.chrome.enabled`
We can't debug firefox remotely.

**Comment by jnachtigall** [comment]
@AnshulMalik thanks for looking into this :)

> We can't debug firefox remotely.

Not sure what is the problem here? (you cannot use the normal workflow for developing the debugger which uses remote protocol?). Because not being able to debug firefox *remotely* would be intended in my opinion: I want to locally debug a certain web app/page, neither the Firefox Chrome nor add-ons nor debugging the debugger.

**Comment by AnshulMalik** [comment]
Created a bug https://bugzilla.mozilla.org/show_bug.cgi?id=1518221
