### ISSUE TITLE
Wrong vertical padding in Sources pane

### ISSUE THREAD

**Issue by fvsch** [devtools-html/debugger.html#7536]
It might be a regression introduced in the PR for #6804.

The `padding: 4px 0;` we wanted to have on the Sources and Outline panes should be set an element that is either the scrolling context or inside the scrolling context. Currently it's set on a parent, so when a scrollbar appears it does not touch the edges (neither does the content):

![screen shot](https://user-images.githubusercontent.com/243601/50162261-306dac80-02de-11e9-9d25-b040d512323c.png)

**Comment by fvsch** [comment]
It looks like the padding should go on `.sources-list .managed-tree .tree`.

Also keep in mind that Gecko has a bug where the bottom padding in this code will be clipped when it's overflowing the element's height:

```css
element {
  overflow: auto;
  padding: 4px 0;
}
```

Our overflow situation looks a bit strange too, we have `overflow-y: auto;`, `overflow: auto` or `overflow: hidden` on something like 4 levels of nested elements. It would be great to have just one that is like, hey, THIS is the scrolling context.

**Comment by jasonLaster** [comment]
:wave: @Garee , just checking in to see how it's going and if you have any questions.

Also, always happy to chat on [slack] or in a 'hangout!

[slack]: https://devtools-html-slack.herokuapp.com/

**Comment by Garee** [comment]
Hey @jasonLaster , I've submitted a pull request with a proposed fix for this issue. Please let me know if any changes are required or if it can be improved. Thanks for the help!
