### ISSUE TITLE
Redesign CallStack Group

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#7555]
Groups in callstacks are great, but could be a bit confusing.
We discussed a better design in https://github.com/devtools-html/ux/issues/34 , and agreed on the following design: 

![image](https://user-images.githubusercontent.com/578107/50215872-8b59df00-0384-11e9-93ea-6575bb67bd3f.png)

Here's a quick diff to start working on this patch: 

```diff
diff --git a/src/components/SecondaryPanes/Frames/Group.js b/src/components/SecondaryPanes/Frames/Group.js
index 79fd774e..841c66db 100644
--- a/src/components/SecondaryPanes/Frames/Group.js
+++ b/src/components/SecondaryPanes/Frames/Group.js
@@ -7,10 +7,7 @@ import React, { Component } from "react";
 import PropTypes from "prop-types";
 import classNames from "classnames";
 import Svg from "../../shared/Svg";
-import {
-  getLibraryFromUrl,
-  formatDisplayName
-} from "../../../utils/pause/frames";
+import { getLibraryFromUrl } from "../../../utils/pause/frames";
 import FrameMenu from "./FrameMenu";

 import "./Group.css";
@@ -28,9 +25,9 @@ function FrameLocation({ frame }: FrameLocationProps) {
   }

   return (
-    <span className="location">
-      {library}
+    <span className="group-description">
       <Svg name={library.toLowerCase()} className="annotation-logo" />
+      <span className="group-description-name">{library}</span>
     </span>
   );
 }
@@ -127,8 +124,6 @@ export default class Group extends Component<Props, State> {

   renderDescription() {
     const frame = this.props.group[0];
-    const displayName = formatDisplayName(frame);
-
     const l10NEntry = this.state.expanded
       ? "callStack.group.collapseTooltip"
       : "callStack.group.expandTooltip";
@@ -143,9 +138,8 @@ export default class Group extends Component<Props, State> {
         tabIndex={0}
         title={title}
       >
-        <span className="title">{displayName}</span>
-        <Badge>{this.props.group.length}</Badge>
         <FrameLocation frame={frame} />
+        <Badge>{this.props.group.length}</Badge>
       </li>
     );
   }
```

Then it will need to CSS changes to implement the design.

**Comment by nchevobbe** [comment]
To have the `Group` component displayed in the debugger, you can follow these steps: 

1. go to https://nchevobbe.github.io/demo/console-test-app.html , and then
1. Open the debugger
1. Search for the reducers.js file
1. Add a breakpoint on in handleLog (e.g. on if (action.data))
1. In the content page, scroll to the bottom, and in the "React/Redux" section, click on the "trace" button ![image](https://user-images.githubusercontent.com/578107/50216312-af69f000-0385-11e9-8a55-5c10731c789b.png)
1. You should get the following in the callstack panel
![image](https://user-images.githubusercontent.com/578107/50216327-bd1f7580-0385-11e9-9318-010c65994d79.png)

**Comment by carlosangon** [comment]
@nchevobbe I'd like to give this one a try if its ok with you.

**Comment by nchevobbe** [comment]
thanks @carlosangon ! You can use `/claim` to assign it to you

**Comment by jasonLaster** [comment]
@carlosangon how's it going? Have you been able to get setup? If you have any questions feel to ping us on slack!

**Comment by carlosangon** [comment]
@jasonLaster Thank you for checking on me.  I will message you guys if I run into any temporary obstacles.

**Comment by nagpalm7** [comment]
Is this issue available @jasonLaster. Can I give it a try.

**Comment by jasonLaster** [comment]
Go for it @nagpalm7
