### ISSUE TITLE
Scopes properties can't be expanded when debugger stopped on return

### ISSUE THREAD

**Issue by nicofrand** [devtools-html/debugger.html#7556]
Hi, 

when the debugger is stopped on a `return` (before the returned value is analyzed and displayed in the panel), the properties in the scopes panel can't be expanded.

**STR**:

1. Copy the code below in an index.html file
1. Open the file in Firefox 65.0b4
1. Open the devtools and debugger tab
1. Set a breakpoint on `this._bookmarks.splice(index, 1);` : check that you can expand the `_bookmarks` property for example (should be OK)
1. Step to the `return true` line: the properties are closed and you can't expand them

```js
<html>
	<head>
		<script>
			var BookmarksHolderClass = function()
			{
				this._bookmarks = ["a", "b", "c"];
			};

			BookmarksHolderClass.prototype.remove = function(val)
			{
				var index = this._bookmarks.indexOf(val);
				if (index !== -1)
				{
                                        // At this point the "_bookmarks" property can be expanded in the scopes panel
					this._bookmarks.splice(index, 1);					

					// At this one, not anymore
					return true;
				}

				return false;
			};

			var holder = new BookmarksHolderClass();
			document.addEventListener("DOMContentLoaded", function()
			{
				document.getElementById("clickme").addEventListener("click", function(event)
				{
					console.log("B removed from list:", holder.remove("b"));
				});
			});
		</script>
	</head>
	<body>
		<button id="clickme">Click me</button>
	</body>
</html>

```

**Comment by nicofrand** [comment]
Fixed by the nightly (firefox-66.0a1.fr.linux-x86_64).

**Comment by jasonLaster** [comment]
Thanks for filing @nicofrand. I'll uplift a fix to beta and maybe release soon!

**Comment by nicofrand** [comment]
Well, thanks for the fix (to whoever did it) and the uplift!
