### ISSUE TITLE
Project search takes huge amount of memory

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#7557]
**Steps to reproduce**
1. Open https://nchevobbe.github.io/demo/console-test-app.html (in toolbox)
1. Open the debugger
1. Do a project search with `event`

**Expected results**

I get some results, or a UI telling me there's no result

**Actual results**

The panel shows "Loading", doesn't update. On the Activity Monitor, I can see the memory growing fast (> 2 GB after 10s, with only 1 tab)
if I don't kill the browser, it eats up all my memory and make the OS unusable, forcing a hard reboot.

---

Reproduced on beta (65) and release (64)

**Comment by AnshulMalik** [comment]
I am scared to reproduce this :P

**Comment by chrlsstcky** [comment]
I'm not getting the memory issue described; if I search for anything the debugger gets stuck in loading. I'm using Ubuntu 18.04
