### ISSUE TITLE
[breakpoints] cmd+shift+b fails to set a conditional bp

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#7572]
STR:

1. open a file in the debugger
2. click a line
3. press cmd+shift+b

ER: see a condtional panel
AR: nothing happens

I think this broke when we made the panel use a location object

**Comment by Garee** [comment]
Hey @jasonLaster,

I've been debugging this and I think it may be the result of a combination of two bugs. One I believe I have a fix for, and the other I'm not sure about.

1. The [`toggleConditionalPanel`](https://github.com/devtools-html/debugger.html/blob/ae3213688ffeeee7a6f2cdebe14a4956ef3a5bb3/src/components/Editor/index.js#L432) function is trying to open the panel at an undefined location. I've pushed a proposed fix for this [here](https://github.com/Garee/debugger.html/commit/846c0a8a4e33249b3e87f91804ee932fca4f8fce?diff=unified). I can submit this as a pull request if you like.

2. I cannot get the keyboard event for cmd+shift+b to fire on Firefox. I've stepped up the stack to `handleEvent` in `key-shortcuts.js` within the `devtools-modules` package and I cannot see an event being fired for this shortcut. It's fine in Chrome - could this be a Firefox bug?

**Comment by Garee** [comment]
I changed the shortcut to the following and it works on Firefox.

 `toggleCondPanel.key=CmdOrCtrl+E`

The current value of `CmdOrCtrl+Shift+B` does not to be seem recognised. In fact, it just toggles the breakpoint like `CmdOrCtrl+B`. I'm using macOS.

**Comment by Garee** [comment]
I had `privacy.resistFingerprinting` set to `true` in `about:config`. It works if I disable it.
