### ISSUE TITLE
[Documentation] Link to CONTRIBUTING.md Results in 404

### ISSUE THREAD

**Issue by darkhist** [devtools-html/debugger.html#7588]
After looking through the [docs](https://firefox-dev.tools/debugger.html/), I noticed that clicking the link to the contributing guidelines (the third bullet point under Next Steps) results in a 404

Additionally, clicking the contributing link (at the bottom of the page) [here](https://firefox-dev.tools/debugger.html/docs/debugging-the-debugger.html) also results in a 404

It looks like this is the correct link: https://github.com/devtools-html/debugger.html/blob/master/.github/CONTRIBUTING.md

**Comment by chocos10** [comment]
i would like to work on it :)

**Comment by Art-Vanderlay** [comment]
The [Contributing to debugger](https://github.com/devtools-html/debugger.html/blob/master/.github/CONTRIBUTING.md) page also has a 404 in the Maintainer Tips section. It links to a file in a non existent .github/docs/ folder.

> **Maintainer Tips**
> 
> Helping maintain a project is the best way to contribute to its overall health. Here are some [notes](https://github.com/devtools-html/debugger.html/blob/master/.github/docs/maintainer.md) on how we work.

The maintainer.md is located here https://github.com/devtools-html/debugger.html/blob/master/docs/maintainer.md
