### ISSUE TITLE
[SourcesTree] No sources while there are sources available

### ISSUE THREAD

**Issue by AnshulMalik** [devtools-html/debugger.html#7607]
STR:

- Go to http://softwareishard.com/tests/debugger/issue3532/
- Open `index.js`
- Pretty Print 

AR:
Sources panel displays the sources but a new message appears saying `This page has no sources`

ER:
We shouldn't see `This page has no sources` since there are sources.

**Comment by jainsneha23** [comment]
Its a regression issue from commit efcda91d682b3e3818ed53e2f430ae70f1a7ac60
Working on it

**Comment by jainsneha23** [comment]
@AnshulMalik  Its fixed via commit 68e7f0a2803653f185c713ea0dbe2449c540c185 in master. Can you check and close this issue please

**Comment by AnshulMalik** [comment]
Thanks @jainsneha23 this is fixed :)
