### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by iskitz** [devtools-html/debugger.html#761]
After freshly cloning this devtools-html/debugger.html repo, running the `npm install` command mentioned in [Getting Started](https://github.com/devtools-html/debugger.html#getting-started) throws this error
```node
/Users/abc/xyz/debugger.html/webpack.config.js:5
const path = require("path");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/Users/.../.../debugger.html/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/Users/abc/xyz/debugger.html/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

npm ERR! Darwin 15.6.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.6.0
npm ERR! code ELIFECYCLE
npm ERR! debugger.html@0.0.5 prepublish: `webpack`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the debugger.html@0.0.5 prepublish script 'webpack'.
npm ERR! This is most likely a problem with the debugger.html package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get their info via:
npm ERR!     npm owner ls debugger.html
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/abc/xyz/npm-debug.log
```
[npm-debug.log](https://github.com/devtools-html/debugger.html/files/478110/npm-debug.log.txt)

**Comment by clarkbw** [comment]
What version of node are you using?  Can you run `node --version`?

I don't think we specify a version required but probably should.

**Comment by iskitz** [comment]
Looks like 0.10.33 from the [npm-debug.log](https://github.com/devtools-html/debugger.html/files/478110/npm-debug.log.txt) file's output
>npm ERR! node v0.10.33

Can't verify at the moment but pretty sure I checked and saw that before filing this issue.

**Comment by jasonLaster** [comment]
@iskitz I believe the minimum version is 5. We use some es6 in node.

**Comment by iskitz** [comment]
Thanks @jasonLaster good to know.

Can debugger.html be updated to make that requirement clear? Maybe both at runtime during `npm install` and upfront in the repo's [README](https://github.com/devtools-html/debugger.html/blob/master/README.md) + [CONTRIBUTING](https://github.com/devtools-html/debugger.html/blob/master/CONTRIBUTING.md#getting-started) docs?

**Comment by jasonLaster** [comment]
Yeah. I think that's a great idea. Thanks for making an issue.

This would be a nice contributor ticket.

**Comment by wldcordeiro** [comment]
@jasonLaster with your PR (#768) this issue has been covered?

**Comment by jasonLaster** [comment]
Yep

**Comment by briantully** [comment]
Has this been merged into master or did it get overwritten? I am experiencing this same issue with a fresh install of master and I don't see any check for node version in package.json version 0.0.6 so it seems #768 may have been overwritten or dropped?

**Comment by jasonLaster** [comment]
Hmm.

We have a check in the development server.

Look for checkNode

If you're still seeing an issue please share what you're seeing and I'm
sure we can fix it
