### ISSUE TITLE
write jsdoc for devtools-source-map

### ISSUE THREAD

**Issue by tromey** [devtools-html/debugger.html#7611]
The devtools-source-map module exports a number of functions and has some hidden requirements for proper use of the API.  These should be documented in the source for future developers.

**Comment by darkwing** [comment]
Is this still relevant @loganfsmyth ?

**Comment by loganfsmyth** [comment]
I'm fine with closing. We've got type annotations for basic documentation, and it's not clear what the other requirements this mentions are. Doesn't seem strictly necessary.
