### ISSUE TITLE
Breakpoint on sourcemapped file doesn't work on lemonde.fr

### ISSUE THREAD

**Issue by ochameau** [devtools-html/debugger.html#7616]
- Open http://www.lemonde.fr/
- Break on angular.js:6
- Reload the page

Note that this angular.js files appear late in the process of loading this page,
and also, this page is huge and get its DOMContentLoaded and load event fired very late.

Some debug info about that, when breaking from addBreakpoint:
```
location = { sourceId: "server1.conn5.child2/source561", line: 292, column: 250 };
appStore.getState().sources.toJS().sources[location.sourceId] = {
  id: "server1.conn5.child2/source561",
  url: "https://ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js",
  isPrettyPrinted: false,
  sourceMapURL: "angular.min.js.map"
}
```  

This mapped line and column make sense but looks somewhat wrong.
Line 6, in the pretty printed file is the following:
```
function(window, document, undefined) {'use strict';
```
And the line 292, column 250 looks like this:
```
})(window,document);
```
Column 250 is the first `)`. Which looks like the end of the line 6's expression.

This breakpoint works on the old debugger as well as chrome.

**Comment by jasonLaster** [comment]
same here. 

@ochameau feel free to re-open this.

**Comment by ochameau** [comment]
I can't easily find any breakage anymore on this website. The original angular.js disappeared.
