### ISSUE TITLE
Nothing really works for me

### ISSUE THREAD

**Issue by voltrevo** [devtools-html/debugger.html#762]
I was able to debug node, but not inspect variables and there doesn't seem to be a repl.

Launching firefox with `npm run firefox` seems to work, but before I can start doing anything I get:
`Error: Timed out waiting for the WebDriver server at http://127.0.0.1:58674/hub`

Debugger.html does not attach/respond in any way to firefox launched with this command from the getting started guide:
`/Applications/Firefox.app/Contents/MacOS/firefox-bin --start-debugger-server 6080 -P development`
(Tried refreshing / restarting dev server)

Debugger.html does not attach/respond in any way to chrome launched with the command from the getting started guide:
`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222 --no-first-run --user-data-dir=/tmp/chrome-dev-profile http://localhost:7999/todomvc/`
(Tried refreshing / restarting dev server)

Firefox 48
Chrome 53
Node 6.3.1
OS X El Capitan 10.11.6
MacBook Pro Retina 15" Mid 2014

I think I will check this out in the nightly build and just have a play with it that way. Looks really nice.

**Comment by wldcordeiro** [comment]
@voltrevo you need to go to `localhost:8000` to use the debugger currently. As far as issue titles go this probably wins in the vagueness department.

**Comment by jasonLaster** [comment]
Thanks for the report @voltrevo, we should definitely make our progress more clear.

We support debugging *node* in the sense of seeing sources, adding breakpoints, pausing, etc. But we have not yet added support for seeing variables or the console. I'll file an issue to update the docs.
