### ISSUE TITLE
huge memory consumption for source code search with 65 beta

### ISSUE THREAD

**Issue by Archaeopteryx** [devtools-html/debugger.html#7629]
With Firefox 65.0 beta 7 on Windows 8.1, the source code search (Ctrl + Shift + F) can require much memory.

Steps to reproduce:
1. Go to https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound
2. Open the debugger
3. Open the source code search.
4. Search for: push
There should be 1000+ matches. With 65.0b7, the memory consumption jumps to ~4GB (also saw 6GB and one out-of-memory crash but had more activity between launch and those situations). With 66.0a1 Nightly, memory is ~1.5GB after the search.

**Comment by jasonLaster** [comment]
Thanks for filing @Archaeopteryx

**Comment by AnshulMalik** [comment]
This should be fixed by recent changes.
