### ISSUE TITLE
Node: documentation should state the progress

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#764]
We support debugging node in the sense of seeing sources, adding breakpoints, pausing, etc. But we have not yet added support for seeing variables or the console. 

The docs should make this clear.

**Comment by wldcordeiro** [comment]
@jasonLaster I'm updating the contributing docs for this now, but I noticed this line which is in conflict with your recent node version requirement?

> Debugging node requires at least node v6.3.0 and running node with the `inspect` flag turned on.  Here's what running node looks like when running an example `server.js` file.

Should we update the minimum to `6.3.0`? Or change the docs to match the version you check for?

**Comment by jasonLaster** [comment]
Thanks.

Actually it's different. 6 is needed if you want to debug it with the
debugger. 5 is needed for running the debugger.

**Comment by clarkbw** [comment]
> Actually it's different. 6 is needed if you want to debug it with the debugger. 5 is needed for running the debugger.

We should have something like this sentence in the docs as well.  The question has come up a couple of times.

**Comment by wldcordeiro** [comment]
@clarkbw I'll open another little patch that clarifies this.
