### ISSUE TITLE
Support XHR breakpoints with methods

### ISSUE THREAD

**Issue by AnshulMalik** [devtools-html/debugger.html#7645]
Currently, we support breaking on a network request if the URL contains some string.
It'd be a nice improvement if we can also specify the method(GET, POST, etc.) of the request to give the user more control.

Here is how the UI should look like

![](https://user-images.githubusercontent.com/46655/46158481-8f71d700-c243-11e8-8b47-6c566a24b8e9.png)

I'll be happy to mentor if someone would like to give it a try :)

Here is how we render the breakpoints: https://github.com/devtools-html/debugger.html/blob/master/src/components/SecondaryPanes/XHRBreakpoints.js#L171-L210

**Comment by nchevobbe** [comment]
that mockup looks nice!
Do you think we could have a default of `All` (or something with a better wording), so by default, the user only has to enter a URL without taking care of the method?
My gut feeling is that most people only have 1 method for a given endpoint, and having to select the method would be an extra step that don't have values for them.
Then, with the UI, they can restrict to a specific method if they want to.

**Comment by AnshulMalik** [comment]
Yeah @nchevobbe by default it should be set to `ALL` or `ANY`  which would just pause on any method. I think we have the logic in place on server side to handle this as well.

**Comment by notjaril** [comment]
I can take this on :)

**Comment by princiya** [comment]
@notjaril this is how you can claim the issue https://github.com/devtools-html/debugger.html/blob/master/docs/issues.md#claiming-issues :) Good luck and thanks for helping.
