### ISSUE TITLE
[sources] Workers break the directory root layout 

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#7656]
STR:

1. debug a page with workers 
2. right click on a directory in the source tree and select "project directory"

NOTE: the launchpad cannot currently find workers, so you might need to fake it by telling the source tree there are workers

```diff
diff --git a/src/components/PrimaryPanes/SourcesTree.js b/src/components/PrimaryPanes/SourcesTree.js
index 86386a844..cd5a9ca20 100644
--- a/src/components/PrimaryPanes/SourcesTree.js
+++ b/src/components/PrimaryPanes/SourcesTree.js
@@ -416,7 +416,7 @@ const mapStateToProps = (state, props) => {
     sources: getRelativeSourcesForThread(state, thread),
     sourceCount: getSourceCount(state, props.thread),
     worker: getWorkerByThread(state, thread),
-    workerCount: getWorkerCount(state)
+    workerCount: 2//getWorkerCount(state)
   };
 };
```

<img width="206" alt="screen shot 2019-01-04 at 12 15 05 pm" src="https://user-images.githubusercontent.com/254562/50701083-78007200-101a-11e9-8d5e-0a0bdd2b297c.png">

**Comment by darkwing** [comment]
Accompanied by this:  
<img width="712" alt="ops" src="https://user-images.githubusercontent.com/46655/50704818-5608ee80-101e-11e9-97c6-ea598ef77e80.png">

**Comment by Regaddi** [comment]
Is this more like the desired layout?

<img width="300" alt="grafik" src="https://user-images.githubusercontent.com/1336590/50858050-a9b56800-138f-11e9-8a35-bc2bccdc0c83.png">
