### ISSUE TITLE
[SecondaryPane] The command bar should be visible when the panel is collapsed

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#7667]
Currently, when the user collapses the secondary pane we hide the commandbar... The problem is that in this case the user can no longer access the stepping buttons. I think that it would be nice if the command bar were still visible so that the user could still step...

### Problem
<img width="781" alt="screen shot 2019-01-06 at 1 31 35 pm" src="https://user-images.githubusercontent.com/254562/50740086-92238700-11b7-11e9-8577-c2269d2f2abc.png">

### Fix
<img width="782" alt="screen shot 2019-01-06 at 1 22 13 pm" src="https://user-images.githubusercontent.com/254562/50740089-9d76b280-11b7-11e9-95b0-13c511d203e9.png">

**Comment by Keeady** [comment]
I would like to take this one /claim
