### ISSUE TITLE
[log points] console log showing in breakpoints panel for log points

### ISSUE THREAD

**Issue by bomsy** [devtools-html/debugger.html#7672]
When a log point is set, a `console.log` show up in the breakpoints list pane on the right. We should remove that.
![logpoints](https://user-images.githubusercontent.com/792924/50765244-3b788480-126d-11e9-8f0a-2a2f844509af.PNG)

**Comment by bomsy** [comment]
Hi @soniasingla, looks like this got fixed by https://github.com/devtools-html/debugger.html/pull/7749

**Comment by soniasingla** [comment]
Thanks @bomsy and am really sorry for being inactive from few days, I was suffering from an injury. Am back now ;)
