### ISSUE TITLE
Incorrect git clone url - getting-setup.md 

### ISSUE THREAD

**Issue by moundahiwale** [devtools-html/debugger.html#7683]
Step 2 in the getting setup document (https://github.com/devtools-html/debugger.html/blob/master/docs/getting-setup.md) refers to an incorrect git url.
Should be same as readme - git clone https://github.com/devtools-html/debugger.html.git

**Comment by AnshulMalik** [comment]
It's one and the same thing @moundahiwale

**Comment by moundahiwale** [comment]
If you want I can create a quick PR and update it or close the issue if not needed - let me know.

**Comment by harshlele** [comment]
FWIW, I just came across this project, and got a permissions error when i tried to clone the URL given in the setup guide, but the readme URL worked.

**Comment by Garee** [comment]
The URL in `getting-setup.md` uses the SSH protocol. You'll need to [set up authentication](https://help.github.com/articles/connecting-to-github-with-ssh/) for this
@moundahiwale @harshlele 

![](http://g.recordit.co/mh9os73F4I.gif)

**Comment by harshlele** [comment]
The https url would be easier to setup

**Comment by AnshulMalik** [comment]
So it looks like a good choice to use https instead of ssh, since it's easier to setup and the getting started docs are there for easy setup. Let's do it then :)

**Comment by harshlele** [comment]
@AnshulMalik hey so can i take this issue then? I've been looking to start contributing :)

**Comment by AnshulMalik** [comment]
Sure @harshlele go ahead :)
