### ISSUE TITLE
Incorrect context menu for regular breakpoints

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#7689]
STRs:
- open any script in the debugger (eg. app.js in https://firefox-dev.tools/debugger-examples/examples/todomvc/)
- add a breakpoint 
- right click on the breakpoint
ER: The context menu should propose to remove breakpoint
AR: The context menu still proposes to add a breakpoint

![debugger_regular_breakpoint_menu](https://user-images.githubusercontent.com/1141550/50858382-8ccd6480-1390-11e9-96b3-5c885e0b0b85.gif)

If you create the breakpoint via "add condition" instead of "add breakpoint", the context menu will be correct.

![debugger_condition_breakpoint_menu](https://user-images.githubusercontent.com/1141550/50858469-c8682e80-1390-11e9-82a1-3b62ba6ac60f.gif)

**Comment by jasonLaster** [comment]
@salomvary sorry this was not clear. I'm working on this bug now in #7719. I kinda re-wrote context menus so that they could support conditional breakpoints

**Comment by salomvary** [comment]
@jasonLaster no worries!
