### ISSUE TITLE
Using Add Condition & Add Log successively confuses the debugger

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#7690]
You can trigger this by various sequence of actions that involve creating breakpoints, here is one which is easy to reproduce:
- open a script in the debugger
- right click on a line number
- click Add Condition
- Do not submit a condition
- right click on the same line number
- click Add Log
- try to remove the breakpoint
ER: breakpoint is removed
AR: breakpoint stays in the gutter

Trying to add other breakpoints on other lines will fail. Closing and reopening the debugger will not display all the breakpoints 

![debugger_breakpoints_not_appearing](https://user-images.githubusercontent.com/1141550/50859081-9f489d80-1392-11e9-87c1-6d0c6b9635db.gif)

**Comment by YisraelV** [comment]
/claim 
If that's OK I would like to try and debug this.

**Comment by jasonLaster** [comment]
I think Brian submitted a PR for this last night. I'll check and get back to you

**Comment by YisraelV** [comment]
@jasonLaster thanks for letting me know. In general is it safe to assume an unclaimed issue is good to work on, or should I first ask here\on slack?

**Comment by YisraelV** [comment]
@jasonLaster any news on this?

**Comment by juliandescottes** [comment]
@jasonLaster I guess this should be closed then? Is https://github.com/devtools-html/debugger.html/pull/7749 the good PR?

**Comment by nmicht** [comment]
This is fixed on current master Latest commit f4621c3
I think we can close it
