### ISSUE TITLE
Empty source tree after using Set Directory Root

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#7693]
STRs:
- open the debugger on any website
- in the source tree left click on any folder 
- select "Set directory root"
ER: The source tree should show the sources under this folder
AR: The source tree is empty

![debugger_empty_source_tree](https://user-images.githubusercontent.com/1141550/50860445-3fec8c80-1396-11e9-9efc-e6830abf4ea0.gif)

**Comment by Garee** [comment]
I am unable to reproduce this. 

@juliandescottes can you please try again?

**Comment by WenInCode** [comment]
I have also been unable to reproduce this 👆

**Comment by juliandescottes** [comment]
This was apparently fixed by #7649 , which landed in mozilla-central 2 days after I opened the issue. No test was added to prevent future regressions though. Feel free to either repurpose this to add a test, or to ignore.

**Comment by jasonLaster** [comment]
#7724
