### ISSUE TITLE
XHR Breakpoint items text should be label toggle

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#7700]
With standard breakpoints, we make clicking on the breakpoint open the source at the breakpoint's location, and thus we cannot use its label to toggle the breakpoint on and off.

XHR breakpoints don't need to go to any location, and thus clicking on the "URL contains (text)" should/could toggle the breakpoint on and off.

**Comment by baronKilljoy** [comment]
@darkwing  on single click it toggles and double click edits text still?

**Comment by notjaril** [comment]
@baronKilljoy that sounds right :)
