### ISSUE TITLE
[docs] remove "Click here to Edit" links from React / Redux Architecture overview

### ISSUE THREAD

**Issue by ravefalcon92** [devtools-html/debugger.html#7720]
Hi there!

The [React / Redux Architecture Overview](https://github.com/devtools-html/debugger.html/blob/master/docs/debugger-html-react-redux-overview.md) has several illustrations with links below that state "Click here to Edit" 

<img width="433" alt="screen shot 2019-01-14 at 3 54 47 pm" src="https://user-images.githubusercontent.com/21224637/51149086-6fc3e600-1815-11e9-9ec9-dca98d5bd5eb.png">

Clicking the links takes the user to a page where they can edit the illustration and the changes show up in the documentation.

I noticed this issue because the first illustration had been edited to look like this:

<img width="649" alt="screen shot 2019-01-14 at 3 09 33 pm" src="https://user-images.githubusercontent.com/21224637/51149119-9255ff00-1815-11e9-8bdd-71b019f89d98.png">

I fixed the image (please revert back if it was intended to look like that), but I think it'd be best to remove the links so this problem doesn't happen again.

**Problem:** Anyone with the "Click here to Edit" link has the ability to edit the illustrations 
**Proposed Solution:** I'm proposing that we comment out the "Click to Edit" URL link so that normal users scrolling through the documentation page cannot see it and are less likely to accidentally edit images. We can keep the URL in the comments so if illustrations need to be updated, we can easily find the link.

I conducted a search in all documentation for this project and it looks like the issue is isolated to [React / Redux Architecture Overview](https://github.com/devtools-html/debugger.html/blob/master/docs/debugger-html-react-redux-overview.md)

Let me know what you think, would be happy to open a PR to fix this.

**Comment by princiya** [comment]
@ravefalcon92 A PR for this would be great :)
