### ISSUE TITLE
Update getting started docs to not launch firefox via the command line

### ISSUE THREAD

**Issue by WenInCode** [devtools-html/debugger.html#7727]
The [getting started docs](https://github.com/devtools-html/debugger.html/blob/master/docs/getting-setup.md#step-3-open-firefox) currently tell you to start firefox via `yarn run firefox`. However, if you do that and then run visit the debugger launchpad at `localhost:8000` the firefox tabs are not detected, and clicking `Launch Firefox` doesn't do anything.

This was remedied by closing the firefox that was started via the command line and just using the `Launch Firefox` button on the launchpad. I think the documentation could be updated to reflect this to prevent confusion for new (or existing like me haha) contributors.

## STR
1. run `yarn run firefox` to open firefox via the command line as specified in docs
2. run `yarn start`
3. visit `localhost:8000`
4. no tabs are detected in the Firefox section of the launchpad

## References
- [Conversation in Slack](https://devtools-html.slack.com/archives/C3VTWQ4KZ/p1547520636726200)
- [Getting started docs](https://github.com/devtools-html/debugger.html/blob/master/docs/getting-setup.md#step-3-open-firefox)

**Comment by harshlele** [comment]
so i should remove the entire section on opening firefox right?
