### ISSUE TITLE
Breakpoints Panel Context Menu Using Wrong Breakpoint

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#7737]
STR:

0.  Add the following in BreakpointsContextMenu.js:  `console.log("selectedLocation is: ", selectedLocation);`
1.  Go to https://w2x2oypmqk.codesandbox.io/
2.  Add a breakpoint in: https://codesandbox.io/static/js/common-sandbox.6c32903e.chunk.js
3.  Add a breakpoint in: https://codesandbox.io/static/js/sandbox.3d2cff6e.js
4.  Refresh the page
5.  Right-click the second breakpoint
6.  Choose Enable (or Disable) breakpoint
7.  *Ooooops* ; You'll see that the action takes place on the *first* breakpoint and not the second.

Spotted in launchpad

**Comment by jasonLaster** [comment]
I believe this will be fixed with my context menus PR...

**Comment by jasonLaster** [comment]
if not, it could be worse 😉

**Comment by darkwing** [comment]
I haven't been able to reproduce this since Jason's work so closing.
