### ISSUE TITLE
Default icon color should use --theme-icon-color

### ISSUE THREAD

**Issue by fvsch** [devtools-html/debugger.html#7743]
For consistency with other panels and Photon guidelines, Debugger buttons should use this color variable for their default state: `--theme-icon-color`.

This maps to:
- Light theme: Grey 90 at 80% opacity (as specified by Photon guidelines)
- Dark theme: Grey 40 (specific to DevTools; Firefox uses Grey 10 at 70% opacity, but the effect is similar)

The best way to test is to set `--theme-icon-color` to an outrageous color like `lime`, and check that it applies to all icons.

In a first pass we could apply this color to the "Collapse panes" icons, to the "Pause", "Step..." and "Deactivate..." icons in the sidebar, and to the "Pretty print" and "Blackbox" icons in the footer.

**Comment by darkwing** [comment]
@notjaril This may be something to keep in mind when you look at the icon stuff, since they're all in buttons.

**Comment by fvsch** [comment]
Small update: if [D17075](https://phabricator.services.mozilla.com/D17075) lands, the relevant variables will be named:

- `--theme-icon-color` for the normal state
- `--theme-icon-checked-color` for icons which have a "checked" state

**Comment by varundey** [comment]
I can take this up but would require some assistance as to where to start from

**Comment by notjaril** [comment]
@varundey I'm finishing a PR on #7735 which is closely related to this issue. I should get the PR in by Wednesday - do you mind waiting until then to start work on this?

**Comment by varundey** [comment]
@notjaril Sure! :)

**Comment by rjairath** [comment]
Hey @fvsch, can I work on this issue?
