### ISSUE TITLE
Idea: Show tips in center pane rather than just the file finder note

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#776]
In Atom, when you have an empty editor it'll show different tips. This might be a nice thing to have, like showing other keyboard shortcuts and tricks.

**Comment by wldcordeiro** [comment]
@jasonLaster @jlongster is there a doc or something that lists the different keyboard shortcuts available? I'd like to come up with a list of tips to cycle.

**Comment by jasonLaster** [comment]
closing this as it's not something we'll likely get to in the near future. It's a cool idea though!
