### ISSUE TITLE
[ToggleButton] Secondary pane toggle button should be vertical

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#7763]
It looks like the toggle button for the secondary pane should be rotated 90 degrees so it either points up or down as opposed to left or right.

This is somehow not working [link](https://github.com/devtools-html/debugger.html/blob/master/src/components/shared/Button/styles/PaneToggleButton.css#L35-L38)

<img width="691" alt="screen shot 2019-01-20 at 2 07 34 pm" src="https://user-images.githubusercontent.com/254562/51443862-4abfef00-1cbd-11e9-8d57-9a29423392ef.png">
<img width="688" alt="screen shot 2019-01-20 at 2 07 27 pm" src="https://user-images.githubusercontent.com/254562/51443863-4abfef00-1cbd-11e9-9596-02e5178d87d0.png">

**Comment by zerefwayne** [comment]
@jasonLaster The left-right direction serves the right purpose in my opinion since panes are coming from left-right.

**Comment by zerefwayne** [comment]
@jasonLaster I guess we have to do it only when we come in tablet view. What do you say?

![image](https://user-images.githubusercontent.com/28949397/51473752-3e15c680-1da3-11e9-884c-c96b3c5b6333.png)

**Comment by zerefwayne** [comment]
Also, in full desktop view the secondary pane directions are opposite.

![image](https://user-images.githubusercontent.com/28949397/51473850-8c2aca00-1da3-11e9-89f8-ff952bf7807e.png)

**Comment by fvsch** [comment]
@akshithashetty So there has been some fixes landed by @jaril I think and then a CSS refactor (and icon update) by me in the past few days. So this should be fixed as of today (latest `master`).
