### ISSUE TITLE
What happened to all the search options of the old debugger?

### ISSUE THREAD

**Issue by fflorent** [devtools-html/debugger.html#777]
Hi,

First, the landing of this project in Firefox is very cool and promising.
While I was giving it a try, I was wondering how to search in all files (the `!` option in the old debugger), and unfortunately couldn't find it.

If there isn't any of these options, could we consider reintroduce them?

Because even if (IMHO) the search options weren't intuitive, they offered a lot of things. The search options could be made simpler (at least by default?), like in Firebug. What do you think?

Florent

**Comment by wldcordeiro** [comment]
In file search hasn't landed yet. There was a PR to put the groundwork in but it was reverted to get some more attention. Keep an eye on the project, and more improvements/missing features will land.

**Comment by jasonLaster** [comment]
Thanks @fflorent. Unfortunately we had to launch with a limited feature set, but we're working on catching up quickly. 

I'm working on in file search and imagine all file search will be done soon. @helenvholmes has designs for a nice sublime like project search.
