### ISSUE TITLE
add about:memory as a tab in devtools

### ISSUE THREAD

**Issue by zspitzer** [devtools-html/debugger.html#7789]
about:memory can be very useful and is currently hidden without being accessible via the UI

**Comment by fvsch** [comment]
(That's probably a bug for Bugzilla rather than this repo.)

DevTools already has a Memory tab. I don't know if there are plans for replacing that tool with about:memory later on.

**Comment by zspitzer** [comment]
about:memory is more complimentary than a replacement for the existing tab

**Comment by jasonLaster** [comment]
i think this should be filed in bugzilla.
