### ISSUE TITLE
File Search - UI Polish

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#780]
Here are some things that seem off:

- [x] The mask opacity - I think a white background would be clearer. If not, then we should put the autocomplete in a white modal.
- [x] close button - seems to be too big and not styled
- [x] search results - the borders seem too big
- [ ] hover - no hover behavior for the search result
- [x] input / list - the input is small relative to the list which seems off

<img width="743" alt="screen shot 2016-09-20 at 10 03 26 am" src="https://cloud.githubusercontent.com/assets/254562/18673268/294ca79e-7f19-11e6-8fe6-577397d91978.png">

**Comment by wldcordeiro** [comment]
Also moving the search bar down to under the tab-bar seems like another good change.

**Comment by helenvholmes** [comment]
@wldcordeiro agreed. Thanks for the list, Jason!

**Comment by jasonLaster** [comment]
Here are the most up to date screenshots. Would someone from the community like to take a stab at this?

@helenvholmes Just noticed that the designs don't have a close button, which is important for going back to the selected source.

![screen shot 2016-09-21 at 8 18 02 pm](https://cloud.githubusercontent.com/assets/254562/18733364/454dad06-8038-11e6-9b26-d834eb6587d6.png)

**Comment by jasonLaster** [comment]
Cleared the milestone as this can be done by a community member.

**Comment by akashmohapatra** [comment]
@jasonLaster I can take it up

**Comment by jasonLaster** [comment]
Thanks @akashmohapatra. Feel free to ask lots of questions. Also, have you been able to [get started](https://github.com/devtools-html/debugger.html/blob/master/CONTRIBUTING.md)

**Comment by akashmohapatra** [comment]
Yes, have the setup in place. Will ask as I go along :)

**Comment by helenvholmes** [comment]
@jasonLaster: updated screenshots:

![screen shot 2016-09-22 at 9 14 27 am](https://cloud.githubusercontent.com/assets/1720093/18749471/00a7cdb8-80a5-11e6-9931-8ce52ba9389f.png)

Issue #791 has good suggestions for closing UX that I think we should use on these close buttons as well!

**Comment by jasonLaster** [comment]
Thanks @helenvholmes. We can likely pull the close button out into it's own component so we can share it.

**Comment by helenvholmes** [comment]
A note that these designs might be changing:

Take this use case:

- searching for string "letters"
- you have three tabs open
- you want to search in the three tabs you have open, not across all files, for this string
- no easy way currently to swap between tabs—the tabs are gone!

In Sublime, you can alt+cmd and then use the directional keys to switch between files. We probably want to preserve that behavior here.

**Comment by clarkbw** [comment]
@akashmohapatra how's it going?  Any questions so far?

**Comment by wldcordeiro** [comment]
@clarkbw was this actually actionable? @helenvholmes last comment made it seem like this and #792 needed some additional fleshing out.

**Comment by wldcordeiro** [comment]
I'm going to take this and apply some of the fixes listed here. They might not be exactly what we want but they're improvements.

**Comment by jasonLaster** [comment]
Thanks! Sounds good

**Comment by helenvholmes** [comment]
[The Invision link's](https://invis.io/AY8OEG3C6#/117937554_Debugger) been updated with some new interactions so that we have a way to close search, which was kind of important 😶. @wldcordeiro, if you want to chat about those interactions more separately please just let me know!

A question for the thread: I've made an assumption in the doc that it might be cool when you switch tabs to re-run the search query. @jasonLaster, @clarkbw, does that paradigm feel okay or should we exit the search UI on tab switch?

**Comment by jasonLaster** [comment]
Thanks @helenvholmes!

> it might be cool when you switch tabs to re-run the search query

I think this makes a ton of sene

**Comment by helenvholmes** [comment]
> I think this makes a ton of sene

If we find that this causes search to be slow (say, you switch to a huge bundle and it lags)—I have an interaction idea in my back pocket we can use. I'll comp it up in the doc tomorrow, but it shouldn't slow down this issue otherwise.

**Comment by clarkbw** [comment]
I've created a module to contain the source search in #953 so heads up if you've already started this work.  The rebase could be tricky.

**Comment by wldcordeiro** [comment]
@clarkbw I hadn't, but I actually was going to do the same! So I'd like to see your PR land and then do these UX changes. I'm going to talk to @helenvholmes tomorrow to get some additional info based on the newest design comp stuff and then start work once your changes land. 😄

**Comment by jasonLaster** [comment]
done! we can tweak in other small issues
