### ISSUE TITLE
Improve code-styling for conditional breakpoint and logpoint input

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#7800]
When adding a conditional log point, I want to easily identify that the text I am typing is code, so that I don't second guess the behaviour.

Code fields should at least be monospaced, but even better providing syntax highlighting.

<img width="222" alt="image" src="https://user-images.githubusercontent.com/8599/51727483-16339680-2021-11e9-9a4a-9bbbd6af9c90.png">

**Comment by darkwing** [comment]
Should this apply to log points and conditional breakpoints?

**Comment by digitarald** [comment]
> Should this apply to log points and conditional breakpoints?

Yes. Anywhere code is entered. Also includes Watch Expressions (_asked in slack_).

**Comment by ravefalcon92** [comment]
/claim Going to give this a try!
