### ISSUE TITLE
Documentation - Highlight logging

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#781]
It would be nice to include logging next to "Hot Reloading" in the writing code section.

Also, the hot reloading link does not jump to the section.

**Comment by wldcordeiro** [comment]
@jasonLaster I was doing this but noticed I'm not really sure what the `client` option logs as I didn't see any additional output. Also could you explain what is in the `firefoxProxy` logging? From a glance it looks like a verbose output in the webpack console.
