### ISSUE TITLE
Tabs not aligned when source-icon showing

### ISSUE THREAD

**Issue by jaril** [devtools-html/debugger.html#7833]
Tabs appear normal as expected, until you have a 1) tab with source icon, and 2) tab with no source icon together in the Tabs pane. Only happens when opening debugger.html in Chrome, behavior doesn't appear in Firefox.

Steps to Reproduce:
1) Open debugger in Chrome
2) Open tab in Firefox, go to https://jsfiddle.net/chrisvfritz/50wL7mdz/
3) In sources pane, try opening `unpkg.com>vue` and `jsfiddle.usesfathom.com>tracker.js`
4) Source icon may not appear immediately, give it a few seconds

Seems to be a [known bug](https://github.com/philipwalton/flexbugs/issues/184) with how Chrome handles SVGs in flexbox.

<br/>

![jan-29-2019 09-37-11](https://user-images.githubusercontent.com/15959269/51916668-ca2f7b80-23ab-11e9-820c-0ac3a433837c.gif)

**Comment by fiji-flo** [comment]
We investigated this at our Berlin Meetup. Thanks to @emilio we traced this back to being a Firefox Bug ([#1518715](https://bugzilla.mozilla.org/show_bug.cgi?id=1518715)). Chrome does the right thing here.

Emilio provided a way to fix this. I'm PR'ing this tomorrow.
