### ISSUE TITLE
Clicking on the "Add watch expression" does not focus the input if the panel is collapsed

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#7835]
**Steps to reproduce**
1. Go to `data:text/html,<meta charset=utf8>`
1. Open the debugger
1. Ensure the `Watch Expressions` panel is collapsed and empty
1. Click on the "Add watch expression (`+`) button

**Expected results**

The panel is expanded, and the input where I can type my expression is focused

**Actual results**

The panel is expanded, but the input isn't focused, even if I click on the `+` button again.

**Comment by darkwing** [comment]
This was introduced when we did the accessibility sprint and removed the `autofocus` attribute.

**Comment by darkwing** [comment]
This also affects the XHRBreakpoints panel.
