### ISSUE TITLE
Implement ".devtools-monospace" CSS class

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#7844]
The devtools common theme (https://searchfox.org/mozilla-central/rev/c07aaf12f13037c1f5a343d31f8291549e57373f/devtools/client/themes/common.css#66-69) provides a `.devtools-monospace` CSS class.

We should use this for anywhere we monospace the font, including:

1.  Breakpoints pane (right sidebar)
2.  Watch expressions
3.  Conditional panel

**Comment by dhyey35** [comment]
@darkwing I have successfully implemented it for Breakpoints but for other's I have some confusions

1. For conditional panel: As you can see in the image below `devtools-monospace` has a lower specificity, so adding `devtools-monospace` is going to be redundant according to me. Is there any other case for which I should add it ?
![image](https://user-images.githubusercontent.com/11143604/52052712-462ced80-257d-11e9-9bb3-405293583ced.png)

2. It is also used for `.shortcutKey` in `WelcomeBox` but as `.devtools-monospace` also has `font-size` prop it reduces it's font-size. So I shouldn't be using it in WelcomeBox, right ?

3. Same issue as 2nd point also happens for `.outline-list`

4. While hovering over variable names when paused does not show the variable value and throws an error, also not able to see the value in `Watch Expressions` panel

![image](https://user-images.githubusercontent.com/11143604/52053695-18957380-2580-11e9-9e16-d85dcad91ed6.png)

**Comment by fvsch** [comment]
Generally speaking, all monospace code-like text should use the same font, a 11px font-size, and a 15px line-height. (The 15px line-height is not yet implemented in DevTools but we want to get there. Yes, that means we are going to bump the CodeMirror source code line-height from the current 13.5px to 15px.)

I have a work-in-progress bug which will provide CSS variables for this style:
https://bugzilla.mozilla.org/show_bug.cgi?id=1520440

I'm not sure we can change `.devtools-monospace` to implement the 15px line-height in that bug though, it could regress a few things in different DevTools panels. So I'm planning to implement a different, more complete class for this style (`.devtools-code-text`).

Feel free to use `.devtools-monospace` in the meantime, and I'll try to see if we can replace it in Debugger later on.

Now for different font sizes: they should be exceptions, and we should have as few of them as possible.

> It is also used for .shortcutKey in WelcomeBox but as .devtools-monospace also has font-size prop it reduces it's font-size. So I shouldn't be using it in WelcomeBox, right ?

I tend to agree, the monospace text in WelcomeBox is a good exception.
Right now you can use `font-family: var(--monospace-font);` and custom values for font-size/line-height.

> Same issue as 2nd point also happens for .outline-list

It seems to already be 11px for me.

**Comment by dhyey35** [comment]
@fvsch As I mentioned for `.outline-list` I am posting a gif that shows the change in font-size due to adding `devtools-monospace` class
![debugger-1](https://user-images.githubusercontent.com/11143604/52224300-a9948380-28cd-11e9-8d92-dda69fc46e8a.gif)

**Comment by fvsch** [comment]
@dhyey35 The text in outline-list should not be that big in the first place, it should be 11px.
Can you figure out why you're getting such a big size currently?
