### ISSUE TITLE
Tabs - polish close button

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#791]
It would be nice to adopt sublime's tab close ux

- show close label on tab hover
- show close button on close hover

![](http://g.recordit.co/U5vN9U5I4D.gif)

**Comment by AndrewPomorski** [comment]
Hello, I could help with that

**Comment by jasonLaster** [comment]
@AndrewPomorski would you like to grab this issue? https://github.com/devtools-html/debugger.html/issues/800

**Comment by wldcordeiro** [comment]
@jasonLaster for the close button is there a prefered background or something similar to the gif? Right now the button just always shows as the x

**Comment by jasonLaster** [comment]
@helenvholmes ^

@wldcordeiro I'd suggest the hover for the accordion header.

**Comment by wldcordeiro** [comment]
Can be closed
