### ISSUE TITLE
Code Search - UI Tweaks

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#792]
[Current designs](https://invis.io/AY8OEG3C6#/117937554_Debugger)

This issue covers small visual tweaks to the search input. It might also involve moving the input to the top of the editor.

I took a look at a couple editors and drew up a list of features we may want to implement:

* *label* - left magnifying glass or placeholder "find" text
* *clear* - clear button on the right
* *cancel* - button to exit search
* *results* - list a summary of results *3 of 77*
* *next/prev* - buttons to find next previous
* *regex* - regex mode for search
* *caps* - caps sensitive
* *whole word* - match whole word
* *in selection* - match in selection

----

Many of these features are more editor oriented. I think we should try and add the label and cancel button soon. And in the future it would be nice to have a results summary, regex mode, and next previous buttons.

---

**Firefox**
![screen shot 2016-09-21 at 9 38 48 am](https://cloud.githubusercontent.com/assets/254562/18713042/f3c0b5ae-7fde-11e6-83fb-0f706b3fe7ad.png)

**Atom**
![screen shot 2016-09-21 at 9 36 42 am](https://cloud.githubusercontent.com/assets/254562/18712998/c5b279b8-7fde-11e6-8bab-4e1e9b330ffc.png)

**Chrome**
![screen shot 2016-09-21 at 9 36 21 am](https://cloud.githubusercontent.com/assets/254562/18712999/c5b8834e-7fde-11e6-9d7c-ecf6ae4fc54a.png)

**Comment by helenvholmes** [comment]
[Debugger search designs](https://invis.io/AY8OEG3C6#/117937554_Debugger)

Still need: a good way to handle closing, and after chatting with Jason I think we both want to move the "1 of 7 results" string so it's not moving as people are typing.

**Comment by jasonLaster** [comment]
Here's the latest design for the "in file" search.

Changes:
* moves search to above the editor
* show a summary of the responses (this will likely move)
* show an error message when nothing is found

We'll also likely add a close button before the designs are finalized.

Would someone like to take a stab at updating the UI?

![screen shot 2016-09-21 at 10 37 47 pm](https://cloud.githubusercontent.com/assets/254562/18735420/b8113a84-804b-11e6-8042-16f231180158.png)

**Comment by wldcordeiro** [comment]
✋ I'll grab this one since someone hopped on file search 😄

**Comment by helenvholmes** [comment]
Note: James and I chatted this morning about the reference to the tabs being lost being problematic, so these desks will be changing under your feet, @wldcordeiro :(

Take this use case:

- searching for string "letters"
- you have three tabs open
- you want to search in the three tabs you have open, not across all files, for this string
- no easy way currently to swap between tabs—the tabs are gone!

In Sublime, you can alt+cmd and then use the directional keys to switch between files. We probably want to preserve that behavior here. This comment should probably also go in file search 🤔

**Comment by helenvholmes** [comment]
Updates on designs thus far (link in comment 2 will have the most up-to-date designs):

- Now has a close button
- Close button UX is address in issue #791 
- Regarding the "1 of 7 results" string: It doesn't look fabulous over on the right hand side, but since I'm still figuring out how to maintain our tabs based on James' feedback I'm going to keep playing with this.

**Comment by wldcordeiro** [comment]
@helenvholmes I hadn't started on it yet so no worries. 👍

**Comment by wldcordeiro** [comment]
Since @jasonLaster made a PR that was merged for these changes, I'm going to close the issue. We can reopen if there is more work to be done.
