### ISSUE TITLE
Set source code line-height to 15px

### ISSUE THREAD

**Issue by fvsch** [devtools-html/debugger.html#7929]
Summary: I'm going to make a PR for changing the source code line-height from `auto` (resulting in slightly different values between configs, often around 13.5px) to 15px. This was discussed previously and validated with @violasong but I want to provide context and an opportunity to push back if someone thinks it could be an issue.

/cc @mcroud 

## Context

Currently DevTools panels tend not to specify the line-height of text. Since we mostly have 11px text (base font-size and code font-size; tabs and accordion headers are 12px) with `line-height: auto`, we end up with a line-height that can be 13px, 13.5px or 14px (with perhaps a few more extreme values, depending on the actual font used and the platform).

I've proposed increasing the code line-height a bit to improve readability. At the last All Hands I reviewed a few options with Victoria, mainly 14px, 15px and 16px line-height, using this demo as a reference:
https://fx-devtools-markup-line-height.netlify.com/

We settled on using 11px text with a 15px line-height, and would like to use that consistently across devtools if possible (Inspector markup view and Rules, Debugger sources, Style Editor sources, etc.).

## Prior discussion & related issues

- General discussion: https://github.com/devtools-html/ux/issues/2
- At least one Slack discussion where changing the Debugger's source line-height from 13.5px to 16px was positively received. Since 15px is a bit more conservative, I take it as a hint that it would fit Debugger nicely too.
- Inspector markup view: https://bugzilla.mozilla.org/show_bug.cgi?id=1508036
- Creating shared styles in m-c: https://bugzilla.mozilla.org/show_bug.cgi?id=1520440

## Implementation

I'm probably not going to wait on bug 1520440 to progress, mostly because it's hard making it progress without knowing exactly how we would consume CSS variables or classes in different panels. So my new strategy is "implement first, refactor later". :grin:

**Comment by jasonLaster** [comment]
Thanks @fvsch. I'm excited about this improvement!

**Comment by mcroud** [comment]
Fantastic, I'm all for it. Looking forward to seeing the results!

**Comment by violasong** [comment]
Perfect, and +1 to the "implement first" strategy every time 🤓
