### ISSUE TITLE
[frames] framework group styling

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#7953]
It looks like the framework groups are not indented. This could have come up during the releases, which had some Frames.css conflicts

<img width="300" alt="screen shot 2019-02-13 at 11 27 50 am" src="https://user-images.githubusercontent.com/254562/52727078-7794b880-2f82-11e9-9fcf-71ac6a1896f5.png">

**Comment by nchevobbe** [comment]
Looks like the offender https://github.com/devtools-html/debugger.html/commit/37cb3683fc77a673d5d4ed55b3ef8119446758e3#diff-df7ce7e2be857a58d33fa87f3245ab89

It reverted some rules, which mean that now we don't target those elements (since we don't have `<ul>`s anymore for example)
