### ISSUE TITLE
Show a source file snippet tooltip when browsing a combined file

### ISSUE THREAD

**Issue by zspitzer** [devtools-html/debugger.html#797]
When browsing a combined source file with a source map, it would be handy to have a quick hover insight into the underlying original sources without having to double click and drill into the underlying files

**Comment by jasonLaster** [comment]
@zspitzer nice idea.

**Comment by jasonLaster** [comment]
Moved this to an `enhancement` note!

Thanks again for posting

**Comment by zspitzer** [comment]
now that #1474 has landed, a hover tooltip with the source file and line number would be possible?
