### ISSUE TITLE
Code Search - outline all matches

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#800]
We currently only highlight the selected search result. We want to highlight the selected search result and draw an outline around the other results, somewhat like atom and sublime.

![screen shot 2016-09-21 at 4 11 23 pm](https://cloud.githubusercontent.com/assets/254562/18727219/b4d70758-8015-11e6-9fa0-a32012d3bd7d.png)

**Comment by AndrewPomorski** [comment]
I can tackle it :)

**Comment by gasolin** [comment]
As #716 mentioned, You can refer the gecko patch which use keyshort cut to catch Codemirror related shortcuts https://reviewboard.mozilla.org/r/80700/diff/2#index_header

**Comment by clarkbw** [comment]
@AndrewPomorski how's it going?  Any questions?

**Comment by andreicristianpetcu** [comment]
I like the current Firefox DevTools search. It is more like filter than search. Besides highlighting the current matches, it filters out lines not matching and with the Up/Down arrows you jump between matches.

**Comment by bomsy** [comment]
is anyone still working on this? would love to take it if its free.

**Comment by jasonLaster** [comment]
@bomsy it's yours!

**Comment by jasonLaster** [comment]
This is done! Great job @bomsy!
