### ISSUE TITLE
Auto-open the first scope when paused?

### ISSUE THREAD

**Issue by captainbrosset** [devtools-html/debugger.html#804]
Whenever I'm paused at a breakpoint, the first thing I want to see is the variables currently defined in my scope, and their values. However, the scope section in the right sidebar is closed by default, and even if I open it, then I have a list of scopes that I have to expand too.

I think we should, at least, auto-expand the local scope by default when the debugger hits a breakpoint.

**Comment by jasonLaster** [comment]
@caprainbrosset I agree.

**Comment by SezginEge** [comment]
@jasonLaster If nobody working on this, I can help with that. 👍

**Comment by wldcordeiro** [comment]
@SezginEge go ahead, note that this hasn't been labeled with a difficulty yet (I don't have the best gauge for this task) so feel free to ask questions as needed.

**Comment by jlongster** [comment]
This is actually pretty complicated because the accordion API doesn't have a way to "open" it except for clicking the header. You can specify if the pane should be open by default [here](https://github.com/jlongster/debugger.html/blob/master/public/js/components/RightSidebar.js#L192), but that's only for the initial rendering.

If you want to learn React, this will be good. You need to implement a lifecycle method in the [Accordion](https://github.com/jlongster/debugger.html/blob/master/public/js/components/Accordion.js) component (probably `componentWillReceiveProps`) and update the local state to open/close based on the new items. That way we could re-render the accordion with new panes marked as `opened` and it would update its state and rerender.

**Comment by SezginEge** [comment]
Thanks @wldcordeiro! I am appreciate your help.

Thanks for starting point @jlongster. I am starting working on this. 👍

**Comment by SezginEge** [comment]
Guys, for personal reasons, I could not interest too much this issue 😞 Sorry for that. I do not want to keep you waiting more.

If there are anyone who wants to work on this, it may take.

**Comment by bomsy** [comment]
i want to pick this up.

**Comment by jasonLaster** [comment]
Great. It's yours. There's likely a change to managed tree needed, but if
you can do codemirror craziness this should be doable :)

**Comment by jasonLaster** [comment]
@bomsy are you still interested in tackling this? I know you have a lot on your plate

**Comment by jasonLaster** [comment]
I did a quick pass on this and I think we can tackle this issue like this:

who knows if it will work in practice :)

```diff
diff --git a/public/js/components/ObjectInspector.js b/public/js/components/ObjectInspector.js
index b70621d..0a32432 100644
--- a/public/js/components/ObjectInspector.js
+++ b/public/js/components/ObjectInspector.js
@@ -129,13 +129,17 @@ const ObjectInspector = React.createClass({
     return [];
   },

-  renderItem(item, depth, focused, _, expanded, { setExpanded }) {
+  renderItem(item, depth, focused, _, expanded, index, { setExpanded }) {
     let objectValue;
     if (nodeHasProperties(item) || nodeIsPrimitive(item)) {
       const object = item.contents.value;
       objectValue = Rep({ object, mode: "tiny" });
     }

+    if (depth == 0 && index == 1) {
+      expanded = true;
+    }
+
     return dom.div(
       { className: classnames("node", { focused }),
         style: { marginLeft: depth * 15 },
diff --git a/public/js/lib/tree.js b/public/js/lib/tree.js
index d3a21e2..9bfb0e9 100644
--- a/public/js/lib/tree.js
+++ b/public/js/lib/tree.js
@@ -92,7 +92,8 @@ const TreeNode = createFactory(createClass({
                             this.props.depth,
                             this.props.focused,
                             arrow,
-                            this.props.expanded),
+                            this.props.expanded,
+                            this.props.index),

       // XXX: OSX won't focus/blur regular elements even if you set tabindex
       // unless there is an input/button child.
```

**Comment by bomsy** [comment]
Cool ... i'm still interested. just wanted to quickly get issue #1151 out.

**Comment by bomsy** [comment]
done! working on this now!

**Comment by jasonLaster** [comment]
:thumbsup:

**Comment by jasonLaster** [comment]
@bomsy let me know if you have any questions here. This one could be tricky :)

**Comment by bomsy** [comment]
@jasonLaster Yeah a bit tricky , it is :). I've been able to figure most of it out,  one quick confirmation i need is which selectors can i use to check if the debugger is pause on a breakpoint.
I'm looking at these 
https://github.com/devtools-html/debugger.html/blob/master/src/reducers/pause.js#L115
and 
https://github.com/devtools-html/debugger.html/blob/master/src/reducers/breakpoints.js#L152.
Correct?

**Comment by jasonLaster** [comment]
ooh, hmm 

if you want to see if it is paused and why, then `getPause` and then `why` or reason is your answer

if you want to know if it is paused at a breakpoint, then

we do that here:
https://github.com/devtools-html/debugger.html/blob/master/src/components/Breakpoints.js#L17-L29

my guess is you want the former :)

**Comment by bomsy** [comment]
thanks!
PR coming!

**Comment by jasonLaster** [comment]
Awesome! Excited for this one.

**Comment by jasonLaster** [comment]
Hey @bomsy how's it going?

**Comment by bomsy** [comment]
heya, stuck at a point. The scope section opens but the children of the first node on the scope do not load. i'll push my PR as a WIP and we can work on it from there.

**Comment by jasonLaster** [comment]
Sounds good. Yea. I think we can figure it out, but yea I can see the
challenge

**Comment by bomsy** [comment]
@jasonLaster i think i've found a solution! Will cleanup an push a PR tommorow!

**Comment by bomsy** [comment]
Can we close this?

**Comment by jasonLaster** [comment]
Yep, I'll open a follow up issue for the panes being open. 

I missed that until your PR started the work.
