### ISSUE TITLE
Add contributor user groups

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#810]
It would be really nice if there was a contributor user group that we could be invited to that had permissions to be assigned issues, and maybe assign labels as well (or maybe multiple groups as "levels" with varying increasing permissions.) Offering to help on a issue is nice but then you have to manually remember the issue you were "assigned" rather than using Github's built-in filter by assignment.

**Comment by clarkbw** [comment]
Really great idea, sorry I haven't done this before.  I needed to read up on how its done and now I think understand what we need to do.

As far as I can see there are only 3 sets of permissions.  Admin, Write, and Read.  Admin allows inviting people to teams, Write allows all write permissions to the repo (push, labels, issues, etc), and Read is used for private repos.  The Write permission seems a little more broad than I had expected but I don't think it will be an issue, most things are fairly easy to undo.

Here's my plan:

Two groups
* debugger
* debugger-core

The main group `debugger` is what everyone will belong to and gives write permission to the repo, we can add contributors to this group.  I'm not sure what the exact process or qualifications should be but @wldcordeiro certainly belongs in there. 

The core group is the admin group which would likely be @jlongster and @jasonLaster and allows them to invite people into the debugger group.

**Comment by wldcordeiro** [comment]
I could have sworn the permissions were more granular. It had been a while since I looked at them on a repo.

**Comment by clarkbw** [comment]
This is the recommended system for issues only access https://help.github.com/articles/issues-only-access-permissions/

**Comment by wldcordeiro** [comment]
Seems like a complicated way of doing it. Hopefully Github adds more granularity at some point.

**Comment by clarkbw** [comment]
We can go ahead with this system for now.  I need to do more research into groups like Node who have a process for bringing contributors into teams but there's no need to block on that just yet.

**Comment by wldcordeiro** [comment]
> We can go ahead with this system for now. I need to do more research into groups like Node who have a process for bringing contributors into teams but there's no need to block on that just yet.

Are you referring to the additional repo method you linked or the debugger/debugger-core groups you mentioned?

**Comment by clarkbw** [comment]
Sorry, I'm talking about the current method. 

I believe we are interested in trying a separate issues repo for RFCs at some time but not quite yet.

**Comment by jlongster** [comment]
I think this is done.

**Comment by clarkbw** [comment]
Yes, done.  I just need to follow up with some docs in a PR.
