### ISSUE TITLE
Open dev server url in browser after npm start

### ISSUE THREAD

**Issue by thesabbir** [devtools-html/debugger.html#819]
When webpack build finishes successfully for the first time. Dev server should open url in default/preferred browser. I can help with a PR.

**Comment by wldcordeiro** [comment]
There is more to configure than just opening the page, so that may complicate some things. Also I would want this to be behind a preference in the local config.

**Comment by jlongster** [comment]
I prefer not opening it automatically, it's more annoying than it's worth. I may stop the webpack build and restart it, but I already have the tab open, so it'll just open another one. It may open it in the wrong browser, etc etc.

Thanks for the idea. I think we can greatly improve the output of the dev server, as right now it's a wall of text and it also outputs the examples url which is really confusing. I'd rather simplify that text and allow the dev to choose where & when to open it. Additionally, in many terminals you and Cmd+click to open URLs.

**Comment by wldcordeiro** [comment]
@jlongster I'm still holding out for `webpack-dashboard` 😄 Might take a stab at getting it working.

**Comment by jlongster** [comment]
@wldcordeiro That would be really cool, definitely in favor of that.

**Comment by jbhoosreddy** [comment]
@wldcordeiro that's so cool. I just learned about it now but seems amazing.

**Comment by wldcordeiro** [comment]
@jbhoosreddy I started experimenting with implementing it for us but we have a more complicated setup so it will take a bit more effort.
