### ISSUE TITLE
npm install fails due to TypeError

### ISSUE THREAD

**Issue by jharrowmortelliti** [devtools-html/debugger.html#827]
npm install:
```
> geckodriver@1.1.2 postinstall /home/jake/code/debugger.html/node_modules/geckodriver
> node index.js

Downloading geckodriver... Extracting... /home/jake/code/debugger.html/node_modules/graceful-fs/polyfills.js:264
      if (stats.uid < 0) stats.uid += 0x100000000
               ^

TypeError: Cannot read property 'uid' of undefined
    at /home/jake/code/debugger.html/node_modules/graceful-fs/polyfills.js:264:16
    at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.7.2-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! geckodriver@1.1.2 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the geckodriver@1.1.2 postinstall script 'node index.js'.

```

Then npm start fails due to the same error.

**Comment by wldcordeiro** [comment]
What version Node.js are you using?

**Comment by wldcordeiro** [comment]
Bizarre, it seems to be a dependency failing or something. Searching online leads me mostly to results with `npm` being the problem. Did you run just a bare `npm install`? Or did you do it as `npm install -g`?

**Comment by jlongster** [comment]
What version of `npm` are you using? I've seen the most issues with older npm versions.

This is due to the `geckodriver` dependency it seems.

**Comment by wldcordeiro** [comment]
Output makes it look like `3.10.8`

**Comment by jharrowmortelliti** [comment]
I am on archlinux.  Originally I did npm install.  I just tried npm install -g though, which seemed to work.
But then I run npm start and I get the same error.
[jake@localhost debugger.html]$ npm start

```
> debugger.html@0.0.5 start /home/jake/code/debugger.html
> npm run check-node && node bin/development-server


> debugger.html@0.0.5 check-node /home/jake/code/debugger.html
> check-node-version --node ">= 5.0.0"

node: v6.6.0
npm: v3.10.8
Listening for WS on *:9000
Will proxy to TCP on *:6080 on first WS connection
Protocol messages can be logged by enabling logging.firefoxProtocol in your local.json config
Hot Reloading can be enabled by adding "hotReloading": true to your local.json config
Development Server Listening at http://localhost:8000
View debugger examples at http://localhost:7999
/home/jake/code/debugger.html/node_modules/graceful-fs/polyfills.js:264
      if (stats.uid < 0) stats.uid += 0x100000000
               ^

TypeError: Cannot read property 'uid' of undefined
    at /home/jake/code/debugger.html/node_modules/graceful-fs/polyfills.js:264:16
    at FSReqWrap.oncomplete (fs.js:123:15)

```

**Comment by jlongster** [comment]
Unfortunately, this seems like a platform-specific bug in a dependency. Looks like it's coming from https://github.com/isaacs/node-graceful-fs.

I found the issue: https://github.com/isaacs/node-graceful-fs/issues/89

I have no idea which module is requiring this though :( I suppose you could try `npm install graceful-fs@4.1.8` and see if it'll upgrade it just for you. We're about to upgrade some of our deps so maybe this will go away.

**Comment by wldcordeiro** [comment]
Since this was an issue with `node-graceful-fs` and they've since release a fix, closing.

**Comment by jharrowmortelliti** [comment]
still not working though

**Comment by wldcordeiro** [comment]
@jharrowmortelliti it isn't something we can do anything about though, the failure is in another package I'd take a look at the issue at `node-graceful-fs`'s repo and report there if the fix still isn't working.
