### ISSUE TITLE
Webpack not working in Firefox 86 Developer Edition

### ISSUE THREAD

**Issue by Gurran** [devtools-html/debugger.html#8299]
Since the release of Firefox 86 Developer Edition I haven't been able to properly see Webpack in the Debugger. 

This worked and still works fine in FF 85, all editions.
My setup is Angular 10 and 11 projects served with regular ng seve. (I think they use Webpack-dev-server)

FF 85:
![Webpack-FF85](https://user-images.githubusercontent.com/42462633/108211643-3913d480-712d-11eb-9bea-9652e7ba051a.png)

FF 86 Dev:
![Webpack-FF86-Dev](https://user-images.githubusercontent.com/42462633/108212015-b17a9580-712d-11eb-8710-7ffc94d6264b.png)

More setup info: 
OS: Windows 10
Enviroment: WSL2

**Comment by janodvarko** [comment]
Thank you for reporting the problem in bugzilla!
https://bugzilla.mozilla.org/show_bug.cgi?id=1693299

Closing this report
Honza
