### ISSUE TITLE
Generate a consistent display title for a given eval source

### ISSUE THREAD

**Issue by jlongster** [devtools-html/debugger.html#831]
We used to assign eval sources a URL of `SOURCE1`, which used an incrementing id. The problem is that it's not a valid URL, and it makes it harder to differentiate eval sources. It should be easy to check if `source.url` is null in many places to change behavior.

However, we do need a consistent way to display eval sources, namely a good "title". Wherever a location is displayed, like the source tab title, breakpoint list, etc, all should display something like `SOURCE1`. I think it makes sense to parse the ID from the actor: just take the number from the very end (for `server2.conn3.child1/31` just extract `31`). It looks like Chrome just uses the `scriptId` which is the same thing.

That way we don't have to preprocess the sources at all, and we'll just provide a function for "formatting" what an eval source will be called.

**Comment by jasonLaster** [comment]
I believe this is fixed

![screen shot 2016-11-01 at 2 41 42 pm](https://cloud.githubusercontent.com/assets/254562/19902386/f2d51efa-a040-11e6-9836-7d0ede7c50dc.png)
