### ISSUE TITLE
Use native prefs in the Firefox panel

### ISSUE THREAD

**Issue by jlongster** [devtools-html/debugger.html#832]
So far we have yet to hook up to the native prefs when in the panel. Even if we think it's not as important as before, I think we're going to want a pref to enable/disable sourcemaps, and it should definitely persist across sessions.

We may decide it's not a blocker. Regardless, we should do it soon.

**Comment by jlongster** [comment]
We'll add a "Debugger" section to the preferences panel to add a "Toggle Sourcemaps" option.

**Comment by bgrins** [comment]
There's a shim that can be used for require("Services") that will give the same prefs API: https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/shim/Services.js

**Comment by bgrins** [comment]
Note you will probably want to set `Services._defaultPrefsEnabled` to false so that it doesn't try to read the m-c pref files: https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/shim/Services.js#425

**Comment by clarkbw** [comment]
> We'll add a "Debugger" section to the preferences panel to add a "Toggle Sourcemaps" option.

Yep, something like this:

<img width="919" alt="screen shot 2016-09-27 at 11 45 06 am" src="https://cloud.githubusercontent.com/assets/2134/18887163/e3f874d6-84a7-11e6-90c9-a850d2781b3b.png">

**Comment by clarkbw** [comment]
This is being done in #685
