### ISSUE TITLE
UI janks when a big scope is expanded

### ISSUE THREAD

**Issue by bgrins** [devtools-html/debugger.html#840]
STR:
1. Open `data:text/html,<script>debugger</script>`
2. Once it pauses, expand the `Window` scope
3. Click on the gutter to toggle a breakpoint at line 1

This leads for me to a pretty janky UI where the breakpoint doesn't get added or removed immediately

Also, in step 2 it takes quite a while to populate the scope and causes a brief hang

**Comment by jlongster** [comment]
It's common for the `window` scope to take a while to populate - it needs to send a ton of data across the RDP. But the rest of the UI should not be dependent on that, so it shouldn't be janky... thanks for filing.

**Comment by jasonLaster** [comment]
Here is a [timeline](https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.githubusercontent.com/jasonLaster/ba5f06bc2a6e0abd1e34888dd9f791c1/raw/21061cbfca8bacd3b1d75514a85bafb0255beaaa/-) view for expanding the scope.

I didn't experience much jank clicking on the gutter. Did you try adding a breakpoint before or after expanding the scope?

**Comment by jasonLaster** [comment]
@jlongster how do you feel about closing this? We've discussed it before and I'm not sure there's anything we can do at this point

**Comment by clarkbw** [comment]
I believe #1707 has fixed this issue.  Can't reproduce it anymore.
