### ISSUE TITLE
Shouldn't be able to select text in the tool 'chrome'

### ISSUE THREAD

**Issue by bgrins** [devtools-html/debugger.html#841]
If I do ctrl+a, or select the 'no breakpoints' / 'sources' / 'Want to find a file? (Cmd + P)' text in the UI it shouldn't select anything to match the rest of the browser chrome

**Comment by jlongster** [comment]
There are places we disable user selection, but I didn't think we wanted to disable it globally. I suppose I'm fine with it, hadn't really thought it through. Thanks!

**Comment by clarkbw** [comment]
This looks like a pretty easily scoped project if anyone else wants to take it on.

I would take a look at where we are using strings and find a way to disable it in specific component classes, globally could be the answer but this feels like it should probably be on a component level so as not to mess with other things where selection should work.

Here's the CSS you'll need to make this happen.

https://developer.mozilla.org/en-US/docs/Web/CSS/user-select
```
.unselectable {
  -moz-user-select: none;
  -webkit-user-select: none;
  -ms-user-select: none;
}
```

**Comment by wldcordeiro** [comment]
Could we enumerate some of the areas where we don't want selection? That would make this an easier task for a new contributor.

**Comment by wldcordeiro** [comment]
* [ ] command bar
* [ ] source tabs
* [ ] sources header
* [ ] sources tree?
* [ ] right sidebar?

@jlongster @clarkbw feel free to add to the list.

**Comment by jasonLaster** [comment]
@clarkbw do you think we could just use the `user-select` property? https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

**Comment by clarkbw** [comment]
@jasonLaster yes, I believe that's all we need to do.  I think the list @wldcordeiro has looks good.  Mostly labels and other text needs this and a global setting could prevent people from copying certain object attributes / values we might want to allow.

**Comment by wldcordeiro** [comment]
I'm getting this done right now. PR should be open shortly.
