### ISSUE TITLE
Code search already exists in the Firefox panel

### ISSUE THREAD

**Issue by jlongster** [devtools-html/debugger.html#844]
I don't know how we missed this, but the CodeMirror we use in the Firefox panel already has code search:

<img width="554" alt="de8a0e88-f7f8-4b99-9af3-f5cfd082316e" src="https://cloud.githubusercontent.com/assets/17031/18964022/2768407c-8645-11e6-9f23-fce3b18517a7.png">

Just press cmd+f to bring it up, and cmd+g and shift+cmd+g already work. It looks like the main problem is that the editor needs to be focused. I was wondering why we weren't automatically getting code search.

The only thing we need to do is forward the global cmd+f key event to codemirror, and everything should just work. We'll have the exact same code search UX as all the other tools, which is important.

**Comment by jlongster** [comment]
Brian and I talked this week about experimenting with moving our CodeMirror with all its set up to npm as a way to try to share modules better. This is a good reason to: we could pull down the same thing that the Firefox panel is using and get this locally too.

**Comment by jlongster** [comment]
> We'll have the exact same code search UX as all the other tools, which is important.

Well, I put this too simply. We're going to want to customize it to the debugger, so I don't know if there's a way to build on top of this current behavior or not. If not, I think it's still important to consider the builtin UX and copy it so it's at least the same feeling across tools.

**Comment by jasonLaster** [comment]
Closing in favor of #870
