### ISSUE TITLE
Remove -moz-use-text-color from debugger

### ISSUE THREAD

**Issue by upsuper** [devtools-html/debugger.html#848]
Gecko is removing `-moz-use-text-color` for color properties, as the standard `currentcolor` now serves the same behavior. The Gecko bug for removing that is [bug 1306214](https://bugzilla.mozilla.org/show_bug.cgi?id=1306214).

**Comment by wldcordeiro** [comment]
I only see this used in one place and that's a devtools-sham file here https://github.com/devtools-html/debugger.html/blob/master/public/js/lib/devtools-sham/sham/css-property-db.js

**Comment by clarkbw** [comment]
That's a sham library and appears to be auto-generated... 🐹

**Comment by jlongster** [comment]
Yeah, we probably should just update it from m-c after that bug lands. I'm not sure how much Xidorn cares that we actually remove every ref, but probably just letting us know. It's pretty harmless to keep it here too.

Let's just sync some of those files next week and we'll get the updates from m-c.

**Comment by jasonLaster** [comment]
We can close this PR as it will be fixed when we remove the shams and update from m-c
