### ISSUE TITLE
Add dir="" to the firefox panel HTML file

### ISSUE THREAD

**Issue by nt1m** [devtools-html/debugger.html#852]
The `<html>` tag should have dir="" so Firefox can automatically set dir="rtl" when needed (see https://bugzilla.mozilla.org/show_bug.cgi?id=1305007 ).

**Comment by juliandescottes** [comment]
As I said in https://bugzilla.mozilla.org/show_bug.cgi?id=1307250#c3 , the new debugger does not seem ready to support RTL in its current state.

![image](https://cloud.githubusercontent.com/assets/1141550/19070242/98ed3b2e-8a2a-11e6-9236-8b8430cbb2c2.png)

**Comment by jasonLaster** [comment]
Hey @SezginEge, would you be interested in polishing our RTL mode? I'm asking because I noticed you're in Turkey and might have more insights here:

- code is displayed in RTL (should keep LTR)
- source tree is not properly indented
- arrows are in the wrong direction
- icons are overlapping

**Comment by magicp-github** [comment]
And also...
- Tab close button position is reversed
- magnifying-glass and the close button are wrong place in search-container
