### ISSUE TITLE
Suggestions for tab UX

### ISSUE THREAD

**Issue by nt1m** [devtools-html/debugger.html#853]
Suggestion 1: New tab page
It would be nice to make the search popup (Cmd+P), the equivalent of a new tab page. When you think of it, this makes sense, because a new tab page is supposed to be the starting point for that tab. Additionally, the new tab page could be the tab that's selected by default.
![debugger-new-tab](https://cloud.githubusercontent.com/assets/1795135/19014084/3720768c-87db-11e6-9677-27da44e360f5.png)

Suggestion 2: Side tabs
It would be nice to use more of the left sidebar vertical space, by displaying tabs on the side. This allows you to perform file specific actions from the sidebar as shown in the mockup. One other advantage is that we can expand the toolbar on the right to take more horizontal space, which can be potentially useful when more items get added (eg. Web Replay).

We could even remove the tree, since it's not that useful (since there's the searchbox that's available).
![debugger-side-tabs](https://cloud.githubusercontent.com/assets/1795135/19014100/790297ec-87db-11e6-9321-e65a8bb1dc15.png)

**Comment by nt1m** [comment]
@helenvholmes @clarkbw @jlongster @jasonLaster Thoughts?

**Comment by wldcordeiro** [comment]
@nt1m I find the tree much more useful than just the tabs. In editors like Sublime Text and Atom the tree is indispensable. I do how ever like the idea of an open files section with quick actions like you've suggested. Atom has something like that and it's quite nice as a separate section to the tree and top tabs.

**Comment by wldcordeiro** [comment]
> Suggestion 1: New tab page

https://github.com/devtools-html/debugger.html/issues/780

There are plans in place for some UX improvements there. I do like the idea of making a new tab button that also brings up the file search dialog though as some people are much more mouse oriented than others.

**Comment by wldcordeiro** [comment]
Marking as not actionable because there's discussion still going on about these various things across other issues too. Still think there's lots of good ideas here though. 😄

**Comment by jlongster** [comment]
I agree that we don't need to put the actions there. As a regular debugger user, it just doesn't help. Eventually we'll have a context menu so you right-click the files and probably do thing like that in the rare case, but it's not worth having dedicated UI right there.

The source tree is a *huge* usability improvement, there's no question in my mind about that. I suspect you may not use the debugger as much as others (sorry if I'm wrong, maybe you just don't use it in the same way), but when dealing with a huge amount of files it's really helpful to see what's going on.

**Comment by clarkbw** [comment]
> It would be nice to make the search popup (Cmd+P), the equivalent of a new tab page

I'm not sure about the new tab page part, but I do agree that having a create a button / icon to call up the search could be good for people who don't use the debugger enough to know the key combo.  We did put the key combo suggestion in the sources view, but I do think many people won't find that as much as a search button.

**Comment by wldcordeiro** [comment]
@clarkbw plus there's the segment of users that even with keyboard shortcuts available, prefer to use their mouse. I'll open an issue for adding the plus button/show search button and I can probably knock that out today if we're all in agreement that it's a nice addition. @jlongster @jasonLaster

**Comment by clarkbw** [comment]
> I'll open an issue for adding the plus button/show search button

We should get @helenvholmes to think this over as there are some larger cross-tool design aspects to this that we need to think about.

**Comment by wldcordeiro** [comment]
@clarkbw sounds good. 👍 Add a comment to #338 detailing the suggestion since that seems to be the home for that.

**Comment by jasonLaster** [comment]
Closing as we now have a more specific issue to work off of.
