### ISSUE TITLE
Can not connect to any debuggable target and getting networkRequest is not function error

### ISSUE THREAD

**Issue by SezginEge** [devtools-html/debugger.html#855]
When i try to connect any debuggable target, connection refuses and can not see any remote tabs. Also i am getting `networkRequest is not a function` error.

Operating System:
- Windows 10

Steps to reproduce:

- Open any command line tool
- Run `npm start`
- Open new tab or new window on command line tool and go chrome or firefox directory.
- Start chrome or firefox with remote debugging turned on

For firefox:
`.\firefox.exe -start-debugger-server 6080 -P development`

For chrome:

```
.\chrome.exe --remote-debugging-port=9222 --no-first-run --user-data-d
ir=/tmp/chrome-dev-profile
```

On the first command line window, you will see this error message: `TCP connection failed: Error: connect ECONNREFUSED 127.0.0.1:6080` and on browser console window, you will see `networkRequest is not a function` error.

**Comment by wldcordeiro** [comment]
Could you post more of the log? Are there any specific packages in the logs like express throwing the error or something? I'm thinking it is possible that Windows firewall might be blocking Node.js or something but I'd like to see some further logs because Google isn't returning much for the error message alone.

**Comment by SezginEge** [comment]
I am getting `networkRequest is not a function` error on this line: https://github.com/devtools-html/debugger.html/blob/master/public/js/clients/chrome.js#L46

I checked firewall settings for nodejs and everything looks okay. :+1: 

These are console log screenshots from chrome and firefox:

![chrome-err](https://cloud.githubusercontent.com/assets/6282991/19022299/f22e2836-88dd-11e6-992e-df232caefbc3.PNG)

![firefox-err](https://cloud.githubusercontent.com/assets/6282991/19022294/e054cb10-88dd-11e6-9865-c19b5a853d98.PNG)

**Comment by wldcordeiro** [comment]
Hmm it appears `networkRequest` wraps the `fetch` API which is behind a pref in some versions of Firefox/Chrome. @jlongster seems you last touched the implementation too so I'll leave this to you for further investigation.

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Browser_compatibility

**Comment by wldcordeiro** [comment]
Hmm, seems like the require call for `networkRequest` is using the destructured import

`const { networkRequest } = require("../utils/networkRequest");`

However, the file it points to exports the whole function as it's `module.exports` so it would seem that the change needed would be `const networkRequest = require("../utils/networkRequest");` that however has another error of its own.

**Comment by wldcordeiro** [comment]
@SezginEge try that modification here https://github.com/devtools-html/debugger.html/blob/master/public/js/clients/chrome.js#L7 and see if the error persists. I have a branch ready for a PR if that's the case.

**Comment by SezginEge** [comment]
Fixed :+1: Thank you for help.

**Comment by jasonLaster** [comment]
Thanks @SezginEge and @wldcordeiro for getting to the bottom of this.
