### ISSUE TITLE
Splitter - right sidebar width shrinks when the window height increases

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#858]
![](http://g.recordit.co/2dVm0Uc8dH.gif)

**Comment by wldcordeiro** [comment]
The unit used was `vh` shouldn't we be using the `vw` unit on the SplitBox's width? https://github.com/devtools-html/debugger.html/blob/master/public/js/components/App.js#L138 That may be the cause of this @jasonLaster

**Comment by jasonLaster** [comment]
Finished in #859
