### ISSUE TITLE
Scopes always unavailable

### ISSUE THREAD

**Issue by SezginEge** [devtools-html/debugger.html#863]
Operating System: Windows 10
Nodejs Version: v6.5.0
Npm: v3.10.8

I can not see any item on scope whenever i set breakpoint. :confused: If i set breakpoint on the same line on chrome, i can see local, global and closure scope.

![scope](https://cloud.githubusercontent.com/assets/6282991/19049975/40d17e7a-89b5-11e6-899e-5e1cda9b3349.PNG)

I did not get any error or something else. Do you have any idea?

**Comment by jasonLaster** [comment]
Hi @SezginEge, we haven't implemented scopes for chrome yet. 

We have a small [note](https://github.com/devtools-html/debugger.html/blob/master/CONTRIBUTING.md#chrome) here, but it is easy to miss.

**Comment by SezginEge** [comment]
@jasonLaster Thank you! :+1:
