### ISSUE TITLE
Polish RTL mode

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#867]
We recently added basic RTL support with an html *dir* tag, but the UI is still pretty busted in this state.

Here's what it looks like:

![](https://cloud.githubusercontent.com/assets/1141550/19070242/98ed3b2e-8a2a-11e6-9236-8b8430cbb2c2.png)

It would be great if someone wanted to help us clean up the UI in this mode. Here are some actionable fixes:

- code is displayed in RTL (should keep LTR)
- source tree is not properly indented
- arrows are in the wrong direction
- icons are overlapping

**Comment by clarkbw** [comment]
RTL mode can be accessed for Firefox via CSS, see the [old debugger.css](https://dxr.mozilla.org/mozilla-central/source/devtools/client/themes/debugger.css#203)

It uses the following:
```css
.selector:-moz-locale-dir(rtl) {
  /* for rtl changes */
}
.selector:-moz-locale-dir(ltr) {
  /* this is the default, only use for selectors that need to change */
}
```

**Comment by nt1m** [comment]
@clarkbw, actually, since the new debugger uses HTML, you have to use :dir instead of :-moz-locale-dir

**Comment by clarkbw** [comment]
> you have to use :dir instead of :-moz-locale-dir

oh right!  de-XUL my brain!

**Comment by jasonLaster** [comment]
Hey @amitzur would you be interested in taking a stab at this?

**Comment by amitzur** [comment]
I would gladly, however how important is this? Don't most if not all devs debugging JS use the english version? Or at least RTL devs?
This is mainly targeted for the debugger being embedded in devtools, right?
In addition, I took a screenshot of hebrew firefox's devtools. The strings are also in hebrew. Do you think we should work on that as well?
<img width="1280" alt="screen shot 2016-10-05 at 20 41 38" src="https://cloud.githubusercontent.com/assets/394320/19124534/3bb46cda-8b3c-11e6-89ef-adf56a41b4e5.png">

**Comment by jasonLaster** [comment]
Hi @amitzur, thanks for the hebrew screen :) 

We've gone back and forth on how important internationalization is because many devs work in english. The conclusion we've landed on is that it *is* nice to support basic rtl and translated strings. We will be looking into adding translations soon :)

Would love your help  on adding basic RTL.

**Comment by amitzur** [comment]
I got it then :)
