### ISSUE TITLE
improve breakpoint highlight

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#871]
#698 updated the breakpoint list but the highlight color needs to be improved.  Right now it looks like a unfocused selection kind of highlight instead of an active indicator.  Need help from @helenvholmes here.

![screen shot 2016-10-04 at 7 55 38 am](https://cloud.githubusercontent.com/assets/2134/19079465/91229bb8-8a08-11e6-9641-9db5f17bf28c.png)

**Comment by jasonLaster** [comment]
Re-opening this issue to discuss a couple tweaks to @Zacqary's improvement.

1. Invert the text


![](https://d17oy1vhnax1f7.cloudfront.net/items/093Y280x3x2U1g0K2X1v/Screen%20Shot%202016-10-10%20at%209.22.32%20AM.hicB.png)

2. De-emphasize the paused-on-line indicator

This is a quick sketch where there is a slight indicator that highlights the breakpoint in a less dramatic fashion.
![](https://d17oy1vhnax1f7.cloudfront.net/items/1o002e2i3l3V2O1M1c1i/Screen%20Shot%202016-10-10%20at%209.27.09%20AM.hi5a.png)


@Zacqary, @helenvholmes, what do you think?

**Comment by Zacqary** [comment]
I think I like the less dramatic callout. The call stack probably needs the loudness of a full background color more than the breakpoint list does.

Can probably implement that one with a `::before` element; I doubt just using a `border` or `outline` would get it to line up the way it does in the sketch.

**Comment by wldcordeiro** [comment]
`:before` pseudo element would be preferred in my opinion. Probably easier to do line-up.

**Comment by wldcordeiro** [comment]
Closing once again. Merged with @jasonLaster's great design suggestion. 😄 Thanks @Zacqary for the PRs and working through the process.
