### ISSUE TITLE
The breakpoint gutter does not line up with the editor line

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#875]
Here's a good screenshot that illustrates where the gutter is slightly shorter than the line.

![screen shot 2016-10-04 at 11 33 32 am](https://cloud.githubusercontent.com/assets/254562/19080806/46041184-8a26-11e6-8a40-b4b7f2a1e1f1.png)

**Comment by monicau** [comment]
Hi Jason, I don't see any "first-timers-only" issues open at the moment. Can I grab this one?

**Comment by wldcordeiro** [comment]
@monicau Feel free to jump on this, the `difficulty: easy` tag generally means it is safe for first-timers as well. Feel free to ask any questions.

**Comment by jlongster** [comment]
Can't repro. When filing bugs, please state which browser and version you are using. 

<img width="606" alt="screen shot 2016-10-04 at 5 43 11 pm" src="https://cloud.githubusercontent.com/assets/17031/19093688/1adcde26-8a5a-11e6-9ef2-77d10d163eab.png">

**Comment by jasonLaster** [comment]
Thanks @monicau. 

Sorry @jlongster, I saw this in Chrome.

**Comment by monicau** [comment]
I modified the CSS to fix the gutter height, I also realigned the breakpoint svg arrow which also wasn't the same height as the line number highlighting.  When doing the unit tests, there were some warnings.  Is it something on my end? 
![debuggerunittestresult](https://cloud.githubusercontent.com/assets/2848472/19125905/cd06108e-8b06-11e6-9f25-0abbfd972648.jpg)

**Comment by wldcordeiro** [comment]
@monicau Those aren't caused by you, they're appearing currently in master. 👍

**Comment by monicau** [comment]
Thanks, that makes sense!  I created a pull request.

**Comment by jasonLaster** [comment]
Thanks @monicau. I just created an issue for cleaning this up :) 

https://github.com/devtools-html/debugger.html/issues/886
