### ISSUE TITLE
adjust the docs to suggest 'up for grabs' instead of 'first timers only'

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#877]
As pointed out by @wldcordeiro in https://github.com/devtools-html/debugger.html/issues/875#issuecomment-251516229 perhaps we should move from the `first-timers-only` label to the combination of `up for grabs`and `difficulty easy`.   So far I don't believe we've assigned any issues to `first-timers-only` so it might not be working for us; we can always bring it back again later if it makes sense.

I think we'll want similar instructions as it is good to know if it is a persons first time contributing or not.

**Comment by jasonLaster** [comment]
Thanks @clarkbw. I've been thinking about this as well. I personally feel like "up for grabs" is more friendly and contributors can grab what they're excited about.

**Comment by jasonLaster** [comment]
Going through the labels I noticed that "Bug" and "Regression" are very similar and Bug is used more often. I propose we migrate Regression over to Bug. @jlongster, @clarkbw thoughts?

**Comment by clarkbw** [comment]
Sounds good to me.

**Comment by jasonLaster** [comment]
updated

**Comment by wldcordeiro** [comment]
I had added "Regression" as it is a specific class of bug, but if it isn't used much we don't have much use for it. I just tend to think of the two differently when labeling issues, bug is the general case and includes new bugs, regressions and more. Regression was meant for when we specifically undid something that was working before. Just figured I'd explain the rationale behind its addition. Sticking to "Bug" will likely be easier for now.

**Comment by clarkbw** [comment]
I believe this is all done thanks to @wldcordeiro
