### ISSUE TITLE
Persist pause on exceptions state

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#880]
The pause on exceptions button helps users pause the debugger when an exception in thrown in their app. The button has three states for a) not pausing on exceptions, b) pausing on all exceptions, c) pausing on caught exceptions.

We should have a user preference so that the button state is persisted when the debugger is refreshed. This pref will let users: 
1. say they want to pause on exceptions 
2. close the debugger
3. open it and still have this pref set

### patch

Here's some code that should do most of the work:

This is an interesting issue because it would be the first time we'd use the Prefs system in our reducers and could set a nice precedent.

```diff
diff --git a/public/js/reducers/pause.js b/public/js/reducers/pause.js
index e7ec261..e31a4dc 100644
--- a/public/js/reducers/pause.js
+++ b/public/js/reducers/pause.js
@@ -4,6 +4,7 @@

 const constants = require("../constants");
 const fromJS = require("../utils/fromJS");
+const prefs = require("../utils/prefs");

 const initialState = fromJS({
   pause: null,
@@ -73,10 +74,15 @@ function update(state = initialState, action, emit) {
       break;

     case constants.NAVIGATE:
-      return initialState;
+      return initialState.merge({
+        shouldPauseOnExceptions: prefs.pauseOnExceptions,
+        shouldIgnoreCaughtExceptions: prefs.ignoreCaughtExceptions
+      });

     case constants.PAUSE_ON_EXCEPTIONS:
       const { shouldPauseOnExceptions, shouldIgnoreCaughtExceptions } = action;
+      prefs.pauseOnExceptions = shouldPauseOnExceptions;
+      prefs.ignoreCaughtExceptions = shouldIgnoreCaughtExceptions;
       return state.merge({
         shouldPauseOnExceptions,
         shouldIgnoreCaughtExceptions
diff --git a/public/js/utils/prefs.js b/public/js/utils/prefs.js
index 93e385b..ee787b8 100644
--- a/public/js/utils/prefs.js
+++ b/public/js/utils/prefs.js
@@ -8,6 +8,8 @@ if (isDevelopment()) {

 const prefs = new PrefsHelper("devtools", {
   clientSourceMapsEnabled: ["Bool", "debugger.client-source-maps-enabled"],
+  pauseOnExceptions: ["Bool", "debugger.pause-on-exceptions"]
+  ignoreCaughtExceptions: ["Bool", "debugger.ignore-caught-exceptions"]
 });
```

### screenshot

![](http://g.recordit.co/s5FZF6KXOH.gif)

**Comment by kareniel** [comment]
I'm gonna start looking at this tonight.

**Comment by bomsy** [comment]
i'll get on this!

**Comment by bomsy** [comment]
@jasonLaster what 's the best way init prefs outside the scope of an app refresh?
```
   pauseOnExceptions: ["Bool", "debugger.pause-on-exceptions"]
   ignoreCaughtExceptions: ["Bool", "debugger.ignore-caught-exceptions"]
```
causes a `Services.js:294 Uncaught Error: could not find pref branch devtools.debugger.pause-on-exceptions` error.

**Comment by jasonLaster** [comment]
The pref call above sets the default.

Mind adding a comment if none exists?

**Comment by bomsy** [comment]
do you mean this call ? `pref("debugger.pause-on-exceptions", true);`?

**Comment by jasonLaster** [comment]
Yea. I think so :)

**Comment by bomsy** [comment]
So on refresh of the page , that always get called .. thereby resetting the value of the prefs to the default.

**Comment by jasonLaster** [comment]
Nope. It should set a default in local storage and on refresh use the
default or user set value.

Basically, it should work. If not, it's s bug... sorry on my phone so tough
to confirm.

**Comment by bomsy** [comment]
Ok. thanks. that's good know. i'll  have a look.  I just wanted to make sure i understood what should be happening... Sorry for disturbing ur Thanksgiving! :)

**Comment by jasonLaster** [comment]
This is blocked by #1364

**Comment by jasonLaster** [comment]
Prefs should be working again.
