### ISSUE TITLE
Landing Page - Add a Settings Panel

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#881]
It would be nice to have a settings panel for setting Debugger preferences and config values. There are a couple of cool wins:
- global prefs like `devtools.debugger.source-maps-enabled` can be set
- it'll be easier for developers to get setup. 
- it'll be easier to surface experimental features and logging preferences

It's very similar to Atom and NPM.

Here is a branch [settings-panel](https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:settings-panel?expand=1)  where I added a simple function for updating the config. I don't think it would be too hard to list the preferences and configs.

Here's a screenshot of what I imagine it could look like.

![screen shot 2016-10-04 at 7 28 23 pm](https://cloud.githubusercontent.com/assets/254562/19096619/d2f51e40-8a6b-11e6-9742-f8f6e0d97916.png)

**Comment by jasonLaster** [comment]
I'm closing this as it's not a priority for local development at the moment.

If it's useful for the standalone debugger, the priority could change.

**Comment by jacobjzhang** [comment]
@jasonLaster this is cool, let me do it please :-)
