### ISSUE TITLE
Testing - fix unit test warnings

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#886]
We should clean up the unit test output, which can be confusing.

> When doing the unit tests, there were some warnings. Is it something on my end? 

![](https://cloud.githubusercontent.com/assets/2848472/19125905/cd06108e-8b06-11e6-9f25-0abbfd972648.jpg)

**Comment by clarkbw** [comment]
I believe this is fixed, I'm not seeing this kind of output

**Comment by wldcordeiro** [comment]
@clarkbw what version of Node.js are you on? I think the 6.x line is where these warnings appear.

**Comment by clarkbw** [comment]
I believe I am using 6.x...

**Comment by jasonLaster** [comment]
Cleaned up awhile  ago
