### ISSUE TITLE
Backport SVGs from MC

### ISSUE THREAD

**Issue by nt1m** [devtools-html/debugger.html#890]
They use standard dimensions, are pixel-snapped, and they are optimized.
devtools/client/themes/images/search.svg
devtools/client/themes/images/debugger-*.svg
devtools/client/themes/images/filetypes/globe.svg

**Comment by jasonLaster** [comment]
Thanks @nt1m

**Comment by jasonLaster** [comment]
Hey @helenvholmes does this issue make sense?

**Comment by jasonLaster** [comment]
closing this as it's stale.

our command buttons are pixel snapped, search is different, ...
I believe the globe is okay
