### ISSUE TITLE
Editor - the footer overlays the editor

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#891]
The footer is overlaying the bottom of the footer. The fix is likely to position the footer relative to the editor. 

Note, i think that I positioned it absolutely initially because the footer was sometimes hidden...

![screen shot 2016-10-06 at 11 19 51 am](https://cloud.githubusercontent.com/assets/254562/19158397/86f7c30c-8bb6-11e6-87f9-09284f4eb842.png)

**Comment by wldcordeiro** [comment]
Footer overlays footer eh? 😆 I'd like to take a look at the layout of the center pane and get an idea of what the main arrangement is and take a stab at refactoring it to be flexbox based. 😄

**Comment by jasonLaster** [comment]
@wldcordeiro that would be great. You're the grid + jss guy, so it makes sense. 

I remember last time the issue was:
* codemirror has some flexbox bugs and does not expand if it's a child... (maybe)
* chrome is different than firefox... so this is one of those issues where it's important to check both browsers

fixes:
* Flexbox: 0 for the bar + footer could be good
* also position relative with a greater wrapper height reduction could work too perhaps...
