### ISSUE TITLE
Add close button to search bar

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#929]
The search bar is currently missing a close button, which would help people close the UI if they are more visual.

In terms of engineering:
- we have a [closeButton](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/CloseButton.js) component here
- and the searchBar is defined [here](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/EditorSearchBar.js).

Here are some screenshots:

![screen shot 2016-10-13 at 8 06 38 am](https://cloud.githubusercontent.com/assets/254562/19348424/d5cc9f10-911b-11e6-9ed9-d97aec872a48.png)

![screen shot 2016-10-13 at 8 07 03 am](https://cloud.githubusercontent.com/assets/254562/19348425/d5cfa9a8-911b-11e6-893c-a13ab4cc173a.png)

**Comment by samuelfullerthomas** [comment]
Working on this!

**Comment by jasonLaster** [comment]
Thanks!
