### ISSUE TITLE
Toggle Breakpoint - should not jump to the line

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#940]
Currently, toggling a breakpoint in the list jumps to that line. We should change this so that toggling a breakpoint does not jump in the editor. 

![](http://g.recordit.co/6lgN8UcH2G.gif)

**Comment by jasonLaster** [comment]
@Zacqary any interest in taking a look? This seems like something you might find interesting :)

**Comment by Zacqary** [comment]
Looks like every time a checkbox is toggled, `renderBreakpoint` gets called a bunch of times. So far I've determined that the scrolling jump happens after the second `renderBreakpoint` call. Not sure what's different about that specifically, still looking into it.

It might just be React getting confused about scroll position. Or is there any other code that would be affecting the `.CodeMirror`'s scroll position? If we ever intentionally scroll it programatically, then whatever prop is responsible for that might be getting sent the wrong message.

**Comment by jasonLaster** [comment]
Hmm, I know we have a selected location prop. Also the editor updates the scroll positions.

**Comment by Zacqary** [comment]
Yep, unchecking the box sends a `selectedLocation` prop of:

```javascript
Object { sourceId: "server2.conn4.child1/32", line: 15 }
```

Although adding new breakpoints afterwards don't change the `line` and it doesn't jump to scroll. Unless it only updates the position when that prop changes.

**Comment by Zacqary** [comment]
Aha, here's the bug: https://github.com/devtools-html/debugger.html/blob/master/public/js/components/Breakpoints.js#L90

```javascript
  {
        className: classnames({
          breakpoint,
          paused: isCurrentlyPaused,
          disabled: isDisabled
        }),
        key: locationId,
        onClick: () => this.selectBreakpoint(breakpoint)
      },
```

The `onClick` handler to select the breakpoint is getting triggered when you click on the checkbox, because the checkbox is part of the same div.
