### ISSUE TITLE
Toggle Breakpoint - disabling a breakpoint fails

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#941]
Toggling all the breakpoints currently causes other breakpoint actions like removing a breakpoint to fail.

Steps to Reproduce:
* add a couple breakpoints
* toggle all breakpoints
* toggle all breakpoints
* toggle a breakpoint or remove a breakpoint

 I believe this happens because those actions are using the wrong breakpoint actor.

![](http://g.recordit.co/iGfBeeDMDV.gif)

**Comment by jasonLaster** [comment]
@ThomasCrevoisier do you have some time to look into this? If not, I'd be happy to pick this up

**Comment by ThomasCrevoisier** [comment]
@jasonLaster Unfortunately, I won't have the time to look into this this week :/
Have you got specific error messages ? Is this targetting Firefox debug ?

Normally we update the actor when we re-enable breakpoints : https://github.com/devtools-html/debugger.html/pull/926/files#diff-db5189725270fa6c573d869b7a7911acR125

**Comment by jlongster** [comment]
This should be fixed right?

**Comment by jasonLaster** [comment]
yup
