### ISSUE TITLE
Toolbox - fix flow mapping

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#942]
Our flow config no longer points to the correct spots.

[flowconfig](https://github.com/devtools-html/debugger.html/blob/master/.flowconfig#L7-L9)

```
[options]
module.name_mapper='^Services$' -> '<PROJECT_ROOT>/public/js/lib/devtools/client/shared/shim/Services.js'
module.name_mapper='^devtools/\(.+$\)' -> '<PROJECT_ROOT>/public/js/lib/devtools/\1.js'
```

^ @clarkbw you might have some ideas here

**Comment by clarkbw** [comment]
I haven't looked extensively yet, but everything probably moved to the packages directory.

```
<PROJECT_ROOT>/packages/devtools-modules/client/shared/shim/Services.js
```

**Comment by clarkbw** [comment]
I'm unsure as to why I'm not getting flow errors. But here's the change that we likely need.

This is the clever version:

```
module.name_mapper='^devtools-local-toolbox$' -> '<PROJECT_ROOT>/packages/devtools-local-toolbox/public/js/index.js'
module.name_mapper='^devtools-\(.+$\)$' -> '<PROJECT_ROOT>/packages/devtools-\1/index.js'
```

Or the more straightforward version, which I think is probably better as I'm not sure if the colliding mapper will work in the above solution.

```
module.name_mapper='^devtools-local-toolbox$' -> '<PROJECT_ROOT>/packages/devtools-local-toolbox/public/js/index.js'
module.name_mapper='^devtools-config$' -> '<PROJECT_ROOT>/packages/devtools-config/index.js'
module.name_mapper='^devtools-network-request$' -> '<PROJECT_ROOT>/packages/devtools-network-request/index.js'
module.name_mapper='^devtools-sham-modules$' -> '<PROJECT_ROOT>/packages/devtools-sham-modules/index.js'
module.name_mapper='^devtools-modules$' -> '<PROJECT_ROOT>/packages/devtools-modules/index.js'
```

**Comment by clarkbw** [comment]
Tried a couple variations, I believe that because the local packages resolve correctly now without webpack tricks there isn't a need for the `module.name_mapper` anymore.  We can probably remove the options section if this is correct.
