### ISSUE TITLE
Turn Off Pretty Print Button if Source Already Has Sourcemap

### ISSUE THREAD

**Issue by helenvholmes** [devtools-html/debugger.html#949]
## Steps to reproduce an example:
1. Open `debugger.html/public/js/test/mochitest/examples/doc-sourcemaps.html` in `debugger.html` directory
2. Select `bundle.js`
3. Hit prettyprint button

This will create a new formatted bundle.js, even though it already has a sourcemap. The old sourcemap gets destroyed. Breakpoints in the new sourcemap get real weird.

How do we want to handle this use case? My first thought it that if we detect that something already has a sourcemap, we remove the prettyprint button from the UI.

**Comment by jasonLaster** [comment]
Thanks @helenvholmes. I believe the consensus is that we should be hiding the pretty print button for bundle files (sources that have an associated source map). Thanks for the really clear issue.

**Comment by jasonLaster** [comment]
This works now
