### ISSUE TITLE
getConfig() not returning anything for tests

### ISSUE THREAD

**Issue by jacobjzhang** [devtools-html/debugger.html#954]
This is probably related to https://github.com/devtools-html/debugger.html/pull/946, where we had issues with registerConfig.

It appears that there are multiple places in the codebase where getConfig() is used to generate a file path and erroneously returns undefined. Please see screenshot.

I'm unsure if the fix requires a deeper dive into getConfig() or whether simply redoing this link in node-unit-tests.js would suffice.
![screen shot 2016-10-19 at 6 17 26 pm](https://cloud.githubusercontent.com/assets/6591285/19539699/d0fa196a-9628-11e6-92ec-7de25167eae7.png)

**Comment by jasonLaster** [comment]
Thanks. My guess is this is connected with fresh git clones.

**Comment by jasonLaster** [comment]
should be resolved
