### ISSUE TITLE
sourceURL for script tags

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#958]
When a script tag specifies a `sourceURL` we don't seem to support it.

For example:

``` html
<script>
(function() {
  console.log('this should appear to be coming from the pen.js file');
})();
//# sourceURL=pen.js
</script>
```

In Chrome the file appears as `pen.js` however it doesn't appear as a source mapped source in the source tree so you can't actually get back to it if you close it.

<img width="808" alt="screen shot 2016-10-20 at 9 14 14 am" src="https://cloud.githubusercontent.com/assets/2134/19564145/84445fbc-96b0-11e6-8f70-ae3446b0a352.png">

Here's an example [codepen](http://s.codepen.io/clarkbw/debug/gwQEym)

**Comment by clarkbw** [comment]
I wanted to figure this out, but I can't make it past the basics of mochitest. Like "How do I pause the test so I can debug the test?"  grrr...

This is my basic test: 

```diff
diff --git a/src/test/mochitest/browser_dbg-sources.js b/src/test/mochitest/browser_dbg-sources.js
index b5f89e6..fbced6a 100644
--- a/src/test/mochitest/browser_dbg-sources.js
+++ b/src/test/mochitest/browser_dbg-sources.js
@@ -47,6 +47,21 @@ add_task(function* () {
      "math.min.js",
      "The dynamic script exists");
 
+  // Make sure new sources appear in the list.
+  ContentTask.spawn(gBrowser.selectedBrowser, null, function() {
+    const script = content.document.createElement("script");
+    script.textContent = `(function() {
+      console.log('this should appear to be coming from the pen.js file');
+    })();
+    //# sourceURL=pen.js`;
+    content.document.body.appendChild(script);
+  });
+
+  yield waitForSourceCount(dbg, 9);
+  is(findElement(dbg, "sourceNode", 7).textContent,
+    "pen.js",
+    "The dynamic script exists");
+
   // Make sure named eval sources appear in the list.
   ContentTask.spawn(gBrowser.selectedBrowser, null, function() {
     content.eval("window.evaledFunc = function() {} //# sourceURL=evaled.js");
```

**Comment by jasonLaster** [comment]
Cool. Lets see what we can do here, 

perhaps we want to start by creating an example like https://github.com/devtools-html/debugger.html/pull/1407

Then we can see what is going on in the server such that it is ignored

**Comment by jlongster** [comment]
@clarkbw Why a patch instead of pasting a JS code block where it will be properly syntax highlighted? I've seen this a lot recently and not sure why 🙃 

I remember discovering this before, but I can't find an existing issue about it. It might have been a problem on the server-side which is why we didn't fix it.

**Comment by clarkbw** [comment]
> @clarkbw Why a patch instead of pasting a JS code block where it will be properly syntax highlighted? I've seen this a lot recently and not sure why 🙃

good point, will update

**Comment by clarkbw** [comment]
This is likely an issue with the server so adding that tag as well.  This might be a good project for someone who wants to learn more about the debug server while also fixing an issue on the client side of things.

**Comment by clarkbw** [comment]
added https://github.com/devtools-html/debugger.html/projects/11#card-1576974 to handle this
