### ISSUE TITLE
Ellipsis to show more rows on short debuggers, Call Stack

### ISSUE THREAD

**Issue by helenvholmes** [devtools-html/debugger.html#961]
Call Stacks quickly get vertically huge. It would be nice on short instances of the debugger to have the option to load more rows on already open Call Stacks.

![collapse rows](https://cloud.githubusercontent.com/assets/1720093/19567637/73bdb6aa-96bc-11e6-932b-f1c1120ad63a.png)

**Comment by jasonLaster** [comment]
Thanks @helenvholmes!

Here's some details for the spec:
* Copy: "Expand Rows", "Collapse Rows"
* Number of frames: 10

**Comment by jasonLaster** [comment]
Hey @monicau, @jacobjzhang interested in snagging this?

**Comment by jacobjzhang** [comment]
@jasonLaster I'll take it!

**Comment by jacobjzhang** [comment]
To confirm, we collapse after 10 frames? And show frames in intervals of 10?

**Comment by jasonLaster** [comment]
collapse after 10, and then show all
