### ISSUE TITLE
Selected States

### ISSUE THREAD

**Issue by helenvholmes** [devtools-html/debugger.html#962]
I think we're like to split up the idea of a "selected state" and a "focused state". Currently we use a blue background with white text for both of these states:

<img width="375" alt="screen shot 2016-10-20 at 12 01 23 pm" src="https://cloud.githubusercontent.com/assets/1720093/19567745/eedda750-96bc-11e6-9307-765bcbad9c09.png">

Instead of this, I think we want to use that blue background if a row is `:focus`ed, and `var(--theme-selection-color)` on backgrounds for selected (but not currently focused) rows.

**Comment by jasonLaster** [comment]
Here's the work we did:

```diff
diff --git a/public/js/components/Frames.css b/public/js/components/Frames.css
index c18faaf..4b3b212 100644
--- a/public/js/components/Frames.css
+++ b/public/js/components/Frames.css
@@ -11,11 +11,14 @@
   overflow: hidden;
 }
 
-/* Style the focused call frame like so:
+/* Style the focused call frame like so: */
 .frames ul li:focus {
-  border: 3px solid red;
+  border: none;
+  outline: 0;
 }
-*/
+
+
+
 
 .frames ul li * {
   -moz-user-select: none;
@@ -41,10 +44,26 @@
 
 .frames ul li.selected,
 .frames ul li.selected .location {
+
+  background-color: slateblue;
+
+  /*
   background-color: var(--theme-selection-background);
   color: white;
+  */
 }
 
+.frames ul li.selected:focus,
+.frames ul li.selected:focus .location {
+  background: olive;
+}
+
+.frames ul li:focus,
+.frames ul li:focus .location {
+  background: red;
+}
+
+
```

**Comment by SezginEge** [comment]
If nobody is working on this, I can tackle it.

**Comment by jasonLaster** [comment]
@SezginEge I think this is a great one. was just thinking about it earlier today!

**Comment by clarkbw** [comment]
hey @SezginEge how's this going?

**Comment by SezginEge** [comment]
@clarkbw I could not work on it yet :/ I will try to send a pr today.

**Comment by jasonLaster** [comment]
Thanks @SezginEge. This issue might be vague, so feel free to ask questions in channel if you have questions about styling
