### ISSUE TITLE
add an "Engines" section to the package.json

### ISSUE THREAD

**Issue by Pomax** [devtools-html/debugger.html#965]
Especially with an eye on security and maintenance, it's a good idea to add an `engines` section to the package.json so that the project can indicate which version(s) of Node it wants to run on. Especially now that the LTS version is Node v6.9, older 6.x versions are technically a security concern and should be ruled out through the `engines` section.

**Comment by jasonLaster** [comment]
Thanks. I agree that it's a good idea. We also have a min node check in development server for 5. Would you like to add an engineer's check for five and up?

**Comment by jasonLaster** [comment]
Will be addressed in #1156

**Comment by jasonLaster** [comment]
Thanks for filing.

Done!
