### ISSUE TITLE
Code Search - re-search when a new source is selected

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#966]
The code search component should do a new search when the selected source changes.

Steps to reproduce:
1. select a source
2. cmd+f to search (type something)
3. select a new source

(we should do a new search, when the source is selected).

![](http://g.recordit.co/35JnlDduKg.gif)

here's a sketch of what the code could look like

``` patch
diff --git a/public/js/components/EditorSearchBar.js b/public/js/components/EditorSearchBar.js
index cecba60..3215bfd 100644
--- a/public/js/components/EditorSearchBar.js
+++ b/public/js/components/EditorSearchBar.js
@@ -56,6 +56,12 @@ const EditorSearchBar = React.createClass({
     if (this.searchInput()) {
       this.searchInput().focus();
     }
+
+    if (props.selectedSource != nextProps.selectedSource) {
+      // redo the search
+      // this will likely extract the onKeyUp logic that does a search and re-use it
+      // e.g. we could add a new method this.search() that would do the search
+    }
   },
```

**Comment by akhillb** [comment]
I would like to try this one. One small question though. If I select a new tab, do you think it would be better to open the tab with search bar open or closed?

**Comment by jasonLaster** [comment]
Thanks

Good question.

The rule of thumb is to be consistent with atom and sublime.

If the search bar is open, id keep it open

**Comment by jasonLaster** [comment]
ping @akhillb do you still think you'll be able to get to this?

**Comment by akhillb** [comment]
@jasonLaster yep i think i will be able to do this.

**Comment by jasonLaster** [comment]
@akhillb do you think you can get to this?

**Comment by jasonLaster** [comment]
@akhillb I'm going to move this back to "up for grabs" feel free to re-claim it if you've got some time.

**Comment by arthur801031** [comment]
@jasonLaster May I work on this? Thank you!

**Comment by jasonLaster** [comment]
Go for it! Let me know if you have questions.

**Comment by arthur801031** [comment]
@jasonLaster  

I have looked at the attributes in `this.props.editor.codeMirror`, `this.props`, and `this.props.editor`, but I still couldn't find `selectedSource`. How do I get this value? Thank you!

**Comment by jasonLaster** [comment]
@arthur801031, oh you might need to pass it in :)

Sorry, that was a quick code sketch and i missed that detail

```diff
diff --git a/src/components/Editor.js b/src/components/Editor.js
index ae71d2d..ff35d60 100644
--- a/src/components/Editor.js
+++ b/src/components/Editor.js
@@ -414,13 +414,14 @@ const Editor = React.createClass({
   },

   render() {
-    const { sourceText } = this.props;
+    const { sourceText, selectedSource } = this.props;

     return (
       dom.div(
         { className: "editor-wrapper devtools-monospace" },
         EditorSearchBar({
           editor: this.editor,
+          selectedSource,
           sourceText
         }),
         dom.div({
```

**Comment by arthur801031** [comment]
@jasonLaster I've added the code re-search when a new source is selected. Please check. Thank you very much! :)
