### ISSUE TITLE
Style Conditional Breakpoints Panel

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#969]
We recently landed conditional breakpoints here #922, but they need to be styled and tweaked. This issue is just about making them pretty, which I have some designs for below.

The guillemet can be unicode: [»](http://www.fileformat.info/info/unicode/char/bb/index.htm)

Here's what it currently looks like

![](http://g.recordit.co/LbZV3IVNOz.gif)
### Default text

![](https://cloud.githubusercontent.com/assets/254562/19328919/17079408-90a4-11e6-9de3-f78f4bb1d742.png)
### Expression

![](https://cloud.githubusercontent.com/assets/254562/19328920/170c493a-90a4-11e6-907b-4a393e5ccd36.png)
### Code changes:

Most of the work is in [Editor.js](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/Editor.js#L35-L64) with some CSS changes in Editor.css

**Comment by jacobjzhang** [comment]
@jasonLaster I'll take this one as well
