### ISSUE TITLE
[Conditional Breakpoints] Clicking on the gutter

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#970]
- clicking on the breakpoint while the panel is open should close the panel and remove the breakpoint.
- clicking on the breakpoint when the panel is closed should open the panel and focus.
- cmd clicking on the breakpoint should focus on the panel input. We should not create lots of new panels :) 

Fail gif
![](http://g.recordit.co/cb3XFA1ZW9.gif)

**Comment by jacobjzhang** [comment]
@jasonLaster I'll take this one

**Comment by jasonLaster** [comment]
Thanks for the help! I'm closing this and opening a small issue for focusing the input on open
