### ISSUE TITLE
Remove all references to marker-offset

### ISSUE THREAD

**Issue by Manishearth** [devtools-html/debugger.html#975]
It's a property from an old draft spec that nobody implements (Firefox only parses it, doesn't do anything with it). Being removed in https://bugzilla.mozilla.org/show_bug.cgi?id=1311959

**Comment by clarkbw** [comment]
Looks like we have a reference in the sham libraries here: https://github.com/devtools-html/debugger.html/blob/466c8c315cdaf97f98b5b8a4bac83989f424bf6e/packages/devtools-sham-modules/sham/css-property-db.js#L753-L756

**Comment by jasonLaster** [comment]
closing this as we'll update it when we remove the shams
