### ISSUE TITLE
Improve flow coverage

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#983]
Our current flow coverage is _60_. There is a lot of room for improvement with our utils, actions, and reducers.

Here is our [coverage report](https://jasonlaster.github.io/debugger-flow-report).

The easiest place to add support is with our utils. There is a lot of low hanging fruit with our actions and reducers. There are also some really interesting redux + flow questions with how we support our actions!
- [x] Flow type pause actions and reducers #1004 
- [x] Flow type source map worker #1005

**Comment by wldcordeiro** [comment]
If you'd like to work on flow typing something, comment on the associated issue saying that you will get it and we'll add a 'in-progress' label.

**Comment by montogeek** [comment]
I am working on this :)

**Comment by jasonLaster** [comment]
thanks for the ping @montogeek. Just moved it to `in progress`. excited to see how you got to `%77`

**Comment by clarkbw** [comment]
This issue is done, though our flow coverage could improve lets open other individual issues for that.

**Comment by jasonLaster** [comment]
Agreed!
