### ISSUE TITLE
Is it possible to debug Safari (not iOS) on OSX?

### ISSUE THREAD

**Issue by gabrielhpugliese** [devtools-html/debugger.html#986]
I couldn't find any guide to it even on Google search. Is it possible to use this with Safari Desktop v9/10?

**Comment by jasonLaster** [comment]
Thanks @gabrielhpugliese for asking. Here is our doc on [debuggable browsers](https://github.com/devtools-html/debugger.html/blob/master/docs/remotely-debuggable-browsers.md#safari). It is vague on Safari.

@clarkbw any thoughts?

I found a CLI handle `/Applications/Safari.app/Contents/MacOS/Safari` but couldn't do much with it...

**Comment by clarkbw** [comment]
https://twitter.com/auchenberg/status/790958943677714432

> ... only possible to enable remote debugging in GTK/EFL WebKit ports. https://trac.webkit.org/wiki/WebInspector#UsingtheWebInspectorremotely

**Comment by clarkbw** [comment]
@gabrielhpugliese looks like, not really.  If you find a system that works please open a PR adding it to the docs.  Thanks!

**Comment by gabrielhpugliese** [comment]
Thanks for the info!
