### ISSUE TITLE
React 15 - The Sources tree is slow

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#987]
The Sources Tree is no longer debounced in 0.15. This is likely because isMounted is [discouraged](https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html). We use it  [here](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/SourcesTree.js#L27-L33)

**Comment by jlongster** [comment]
The above description is wrong; that was just a theory, but it turned out to be something else. This is being handled in #1016
