### ISSUE TITLE
panel - the scrollbar is hard to drag

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#992]
In the panel, the styled scrollbar is difficult to drag

The way to drag it is to scroll and then drag the scrollbar with the mouse. 

![](http://g.recordit.co/TpmmPcjEcS.gif)

**Comment by jlongster** [comment]
That's very strange, it must be something with your mouse. I can't repro; it acts exactly the same as all the other scrollbars. I don't show the scrollbars by default, but if you scroll a little then you can grab it and drag. This is the same behavior as all other scrollbars in OSX for me.

**Comment by jasonLaster** [comment]
Closing now, we re-open this if others see it.
