### ISSUE TITLE
Dark Theme - Source Footer Icon Color Polish

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#997]
The icon colors for pretty print are off.

![screenshot_20161025_141200](https://cloud.githubusercontent.com/assets/580982/19702462/0331a810-9abd-11e6-9de9-b2152f4b6b0f.png)

**How do you change themes locally?** You can edit the theme locally [here](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#themes)

**How do we fix these?** Add CSS overrides in the different components. Here's an example of how we could fix the right sidebar commands.

``` diff
diff --git a/public/js/components/RightSidebar.css b/public/js/components/RightSidebar.css
index 5f5f8b4..794aa0d 100644
--- a/public/js/components/RightSidebar.css
+++ b/public/js/components/RightSidebar.css
@@ -40,6 +40,10 @@ html[dir="rtl"] .command-bar {
   transition: opacity 200ms;
 }

+:root.theme-dark .command-bar > span {
+  stroke: var(--theme-body-color);
+}
+
 html:not([dir="rtl"]) .command-bar > span {
   margin-right: 0.7em;
 }
```

**How do I choose the right color?** Hmm, it's up to you. We have a list of variables [here](https://github.com/devtools-html/debugger.html/blob/master/packages/devtools-local-toolbox/public/js/lib/themes/variables.css). What I do is look for similar colors in the app and then see what variable it uses in the inspector.

**Comment by helenvholmes** [comment]
Closed via #1032.
